MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Document = MWF.xApplication.cms.Document || {};
MWF.xApplication.cms.Document.LP={
	"title": "Documento",
	"selectRoute": "Seleccionar decisión",
	"inputOpinion": "Agregar opinión",
	"comfirm": "Confirmar",
	"close": "Cerrar",
	"cancel": "Cancelar",
	"ok": "Enviar",
	"inputText": "Por favor escriba su opinión aquí",
	"mustSelectRoute": "Por favor seleccione una decisión primero.",
	"searchKey": "Ingrese una palabra clave.",
	"task": "Centro de tareas pendientes",
	"done": "Centro de tareas completadas",
	"draft": "Borradores",
	"myfile": "Mis archivos",
	"reset": "Restablecer responsable",
	"phone": "Teléfono móvil",
	"mail": "Correo electrónico",
	"documentGettedError": "No tiene permiso para ver el documento o ha sido eliminado.",
	"controllerGettedError": "Error al obtener el controlador.",
	"formGettedError": "Error al obtener el formulario.",
	"attachmentGettedError": "Error al obtener los adjuntos.",
	"formNotSetted": "El formulario no ha sido establecido.",
	"attachmentArea": "Área de adjuntos",
	"selectAttachment": "Seleccionar adjunto.",
	"hotPicture": "Imagen destacada",
	"cancelHotPicture": "Cancelar imagen destacada",
	"setHotPicture": "Establecer imagen destacada",
	"regularPublish": "Publicación programada",
	"publishTime": "Fecha de publicación",
	"publish": "Publicar",
	"inputPublishTime": "La fecha de publicación no puede estar vacía.",
	"inputPublishTime2": "La fecha de publicación no puede ser anterior a la fecha actual.",
	"setHotLinkSuccess": "Imagen destacada establecida exitosamente.",
	"cancelHotLinkSuccess": "Imagen destacada cancelada exitosamente.",
	"selectDocPicture": "Seleccionar imagen del documento.",
	"selectFilePicture": "Seleccionar imagen del archivo en la nube.",
	"hotLinkDescription": "Nota: La imagen seleccionada se utilizará como imagen superior en la aplicación móvil de esta plataforma. La proporción ideal es 1:2.",
	"unselectHotPic": "Por favor, seleccione una imagen primero.",
	"cancelHotPicComfirmTitle": "Cancelar imagen destacada",
	"cancelHotPicComfirmContent": "¿Está seguro de que desea cancelar la imagen destacada de este documento?"
}
MWF.xApplication.cms.Document["lp."+o2.language] = MWF.xApplication.cms.Document.LP