MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Document = MWF.xApplication.cms.Document || {};
MWF.xApplication.cms.Document.LP = {
	"title": "文書",
    "selectRoute": "決定を選択",
    "inputOpinion": "意見を記入",
    "comfirm": "確認",
    "close": "閉じる",
    "cancel": "キャンセル",
    "ok": "提出",
    "inputText": "ここにプロセス意見を記入してください",
    "mustSelectRoute": "まず決定を選択してください",
    "searchKey": "キーワードを入力",
    "task": "未処理センター",
    "done": "完了センター",
    "draft": "下書きボックス",
    "myfile": "私のファイル",
    "reset": "担当者をリセット",
    "phone": "電話",
    "mail": "メール",
    "documentGettedError": "文書取得エラー",
    "controllerGettedError": "管理者取得エラー",
    "formGettedError": "フォーム取得エラー",
    "attachmentGettedError": "添付ファイル取得エラー",
    "formNotSetted": "フォームが設定されていません",
    "attachmentArea": "添付ファイルエリア",
    "selectAttachment": "添付ファイルを選択",
    "hotPicture": "ホットピクチャー",
    "cancelHotPicture": "ホットピクチャーのキャンセル",
    "setHotPicture": "ホットピクチャーの設定",
    "regularPublish": "定期的な公開",
    "publishTime": "公開時間",
    "publish": "公開",
    "inputPublishTime": "公開時間を入力してください",
    "inputPublishTime2": "公開時間は現在の時間よりも早くすることはできません",
    "setHotLinkSuccess": "ホットリンク画像の設定に成功しました",
    "cancelHotLinkSuccess": "ホットリンク画像のキャンセルに成功しました",
    "selectDocPicture": "文書画像を選択",
    "selectFilePicture": "クラウドファイル画像を選択",
    "hotLinkDescription": "注：選択した画像は、このプラットフォームのモバイルアプリの上部画像として使用され、画像の最適な横縦比は1:2です",
    "unselectHotPic": "まず画像を選択してください",
    "cancelHotPicComfirmTitle": "ホットピクチャーのキャンセル",
    "cancelHotPicComfirmContent": "この文書のホットピクチャーをキャンセルしますか？"
};
MWF.xApplication.cms.Document["lp."+o2.language] = MWF.xApplication.cms.Document.LP;