MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Document = MWF.xApplication.cms.Document || {};
MWF.xApplication.cms.Document.LP = {
	"title": "문서",
    "selectRoute": "결정 선택",
    "inputOpinion": "의견 작성",
    "comfirm": "확인",
    "close": "닫기",
    "cancel": "취소",
    "ok": "제출",
    "inputText": "여기에 프로세스 의견을 작성하십시오",
    "mustSelectRoute": "먼저 결정을 선택하십시오",
    "searchKey": "키워드 입력",
    "task": "미처리 작업",
    "done": "완료된 작업",
    "draft": "드래프트 상자",
    "myfile": "내 파일",
    "reset": "처리자 재설정",
    "phone": "전화번호",
    "mail": "이메일",
    "documentGettedError": "문서 가져오기 오류",
    "controllerGettedError": "관리자 가져오기 오류",
    "formGettedError": "양식 가져오기 오류",
    "attachmentGettedError": "첨부 파일 가져오기 오류",
    "formNotSetted": "양식이 설정되지 않음",
    "attachmentArea": "첨부 파일 영역",
    "selectAttachment": "첨부 파일 선택",
    "hotPicture": "핫 이미지",
    "cancelHotPicture": "핫 이미지 취소",
    "setHotPicture": "핫 이미지 설정",
    "regularPublish": "정기 발행",
    "publishTime": "발행 시간",
    "publish": "게시",
    "inputPublishTime": "발행 시간을 입력하십시오",
    "inputPublishTime2": "발행 시간은 현재 시간 이전일 수 없습니다",
    "setHotLinkSuccess": "핫 링크 이미지 설정 성공",
    "cancelHotLinkSuccess": "핫 링크 이미지 취소 성공",
    "selectDocPicture": "문서 이미지 선택",
    "selectFilePicture": "클라우드 파일 이미지 선택",
    "hotLinkDescription": "참고: 선택한 이미지는 이 플랫폼 모바일 앱의 상단 이미지로 사용되며, 이미지의 최적의 가로 세로 비율은 1:2입니다",
    "unselectHotPic": "먼저 이미지를 선택하십시오",
    "cancelHotPicComfirmTitle": "핫 이미지 취소",
    "cancelHotPicComfirmContent": "이 문서의 핫 이미지를 취소하시겠습니까?"
};
MWF.xApplication.cms.Document["lp."+o2.language] = MWF.xApplication.cms.Document.LP;