MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Document = MWF.xApplication.cms.Document || {};
MWF.xApplication.cms.Document.LP = {
	"title": "文檔",
    "selectRoute": "選擇決策",
    "inputOpinion": "填寫意見",
    "comfirm": "確認",
    "close": "關閉",
    "cancel": "取消",
    "ok": "提交",
    "inputText": "請在此處填寫流程意見",
    "mustSelectRoute": "請先選擇決策",
    "searchKey": "請輸入關鍵字",
    "task": "待辦中心",
    "done": "已辦中心",
    "draft": "草稿箱",
    "myfile": "我的文件",
    "reset": "重設處理人",
    "phone": "手機",
    "mail": "郵箱",
    "documentGettedError": "文檔獲取錯誤",
    "controllerGettedError": "管理員獲取錯誤",
    "formGettedError": "表單獲取錯誤",
    "attachmentGettedError": "附件獲取錯誤",
    "formNotSetted": "未設定表單",
    "attachmentArea": "附件區域",
    "selectAttachment": "選擇附件",
    "hotPicture": "熱點圖片",
    "cancelHotPicture": "取消熱點圖片",
    "setHotPicture": "設置熱點圖片",
    "regularPublish": "定時發佈",
    "publishTime": "發佈時間",
    "publish": "發布",
    "inputPublishTime": "發佈時間不能為空",
    "inputPublishTime2": "發佈時間不能早於當前時間",
    "setHotLinkSuccess": "設置熱點圖片成功",
    "cancelHotLinkSuccess": "取消熱點圖片成功",
    "selectDocPicture": "選擇文檔圖片",
    "selectFilePicture": "選擇雲文件圖片",
    "hotLinkDescription": "注：選擇的圖片將作為本平台移動端應用的頂部圖片，圖片的最佳寬高比為1:2",
    "unselectHotPic": "請先選擇圖片",
    "cancelHotPicComfirmTitle": "取消熱點圖片",
    "cancelHotPicComfirmContent": "確定要取消此文檔的熱點圖片嗎？"
};
MWF.xApplication.cms.Document["lp."+o2.language] = MWF.xApplication.cms.Document.LP;