/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.element.FormField.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:27 CST 2018")
public class FormField_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<FormField,String> appId;
    public static volatile SingularAttribute<FormField,String> dataType;
    public static volatile SingularAttribute<FormField,String> form;
    public static volatile SingularAttribute<FormField,String> id;
    public static volatile SingularAttribute<FormField,String> name;
}
