/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.AttendanceAdmin.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:17:02 CST 2016")
public class AttendanceAdmin_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceAdmin,String> adminLevel;
    public static volatile SingularAttribute<AttendanceAdmin,String> adminName;
    public static volatile SingularAttribute<AttendanceAdmin,Date> createTime;
    public static volatile SingularAttribute<AttendanceAdmin,String> id;
    public static volatile SingularAttribute<AttendanceAdmin,String> organizationName;
    public static volatile SingularAttribute<AttendanceAdmin,String> organizationOu;
    public static volatile SingularAttribute<AttendanceAdmin,String> sequence;
    public static volatile SingularAttribute<AttendanceAdmin,Date> updateTime;
}
