/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Double;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.StatisticCompanyForMonth.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:33:54 CST 2017")
public class StatisticCompanyForMonth_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<StatisticCompanyForMonth,Long> abNormalDutyCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Double> absenceDayCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,String> companyName;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Date> createTime;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Double> employeeCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,String> id;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Long> lackOfTimeCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Long> lateCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Long> leaveEarlyCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Long> offDutyCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Long> onDutyCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Double> onDutyEmployeeCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Double> onSelfHolidayCount;
    public static volatile SingularAttribute<StatisticCompanyForMonth,String> sequence;
    public static volatile SingularAttribute<StatisticCompanyForMonth,String> statisticMonth;
    public static volatile SingularAttribute<StatisticCompanyForMonth,String> statisticYear;
    public static volatile SingularAttribute<StatisticCompanyForMonth,Date> updateTime;
}
