/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Double;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.StatisticDepartmentForDay.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:07:18 CST 2017")
public class StatisticDepartmentForDay_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<StatisticDepartmentForDay,Long> abNormalDutyCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Double> absenceDayCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,String> companyName;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Date> createTime;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Double> employeeCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,String> id;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Long> lackOfTimeCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Long> lateCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Long> leaveEarlyCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Long> offDutyCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Long> onDutyCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Double> onDutyEmployeeCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Double> onSelfHolidayEmployeeCount;
    public static volatile SingularAttribute<StatisticDepartmentForDay,String> organizationName;
    public static volatile SingularAttribute<StatisticDepartmentForDay,String> sequence;
    public static volatile SingularAttribute<StatisticDepartmentForDay,String> statisticDate;
    public static volatile SingularAttribute<StatisticDepartmentForDay,String> statisticMonth;
    public static volatile SingularAttribute<StatisticDepartmentForDay,String> statisticYear;
    public static volatile SingularAttribute<StatisticDepartmentForDay,Date> updateTime;
}
