MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.service = MWF.xApplication.service || {};
MWF.xApplication.service.ServiceManager = MWF.xApplication.service.ServiceManager || {};
MWF.xApplication.service.ServiceManager.LP={
	"title": "Service Platform",
	"categoryTitle": "Category",
	"description": "Description",
	"deleteItems": "Delete selected element",
	"copy": "Copy",
	"copyto": "Copyto...",
	"copyInfor": "Select multiple elements, press Ctrl+C to copy the elements, press Ctrl+V to paste elements into the current application",
	"copyed": "The selected element has been copied",
	"copyConfirmTitle": "Copy element confirmation",
	"copyConfirmInfor": "The target area already contains the same elements:",
	"copySource": "Original file:",
	"copyTarget": "Copy files:",
	"copyConfirm_overwrite": "Replace",
	"copyConfirm_new": "Create",
	"copyConfirm_skip": "Skip",
	"copyConfirm_cancel": "Cancel",
	"copynew": "New",
	"edit": "Edit",
	"save": "Save",
	"cancel": "Cancel",
	"phone": "Phone",
	"mail": "Mail",
	"deleteElementTitle": "Delete design confirmation",
	"deleteElement": "Are you sure you want to delete the selected design element?",
	"agent": {
		"name": "Agent",
		"create": "Create Agent",
		"search": "Search Agent",
		"searchText": "Please enter key words",
		"noAgentNoticeText": "There is no Agent, you can click here to create a new Agent",
		"loaded": "Agent loaded",
		"deleteProcessTitle": "Delete Agent confirmation",
		"deleteProcess": "Are you sure you want to delete the current Agent?",
		"noPermission": "You are not an administrator and cannot view Agents.",
		"deletePageTemplateTitle": "Delete proxy template confirmation",
		"deletePageTemplate": "Are you sure you want to delete the current proxy template?"
	},
	"invoke": {
		"name": "Service",
		"create": "Create Service",
		"search": "Search Service",
		"searchText": "Please enter key words",
		"noAgentNoticeText": "There is no Service, you can click here to create a new Service",
		"loaded": "Service loaded",
		"deleteProcessTitle": "Delete Service confirmation",
		"deleteProcess": "Are you sure you want to delete the current Service?",
		"noPermission": "You are not an administrator and cannot view Service.",
		"deletePageTemplateTitle": "Delete interface template confirmation",
		"deletePageTemplate": "Are you sure you want to delete the current interface template?"
	},
	"dictionary": {
		"name": "Dictionary",
		"create": "Create Data Dictionary",
		"search": "Search Data Dictionary",
		"searchText": "Please enter a keyword",
		"noDictionaryNoticeText": "There is no data dictionary, you can click here to create a new data dictionary",
		"noDictionaryNoCreateNoticeText": "This application does not have a data dictionary now",
		"loaded": "Data dictionary loaded",
		"deleteFormTitle": "Confirm Delete Data Dictionary",
		"deleteForm": "Are you sure you want to delete the current data dictionary?",
		"noPermission": "You are not an administrator and cannot view dictionary."
	},
	"script": {
		"name": "Script",
		"create": "Create Script",
		"search": "Search Script",
		"searchText": "Please enter a keyword",
		"noScriptNoticeText": "There is no script, you can click here to create a new script",
		"loaded": "Script loaded",
		"deleteFormTitle": "Delete Script Confirmation",
		"deleteForm": "Are you sure you want to delete the current script?",
		"noPermission": "You are not an administrator and cannot view script."
	},
	"all": "All",
	"agentConfig": "Agent Config",
	"interfaceConfig": "Service Config",
	"scriptConfig": "Script Config",
	"dataConfig": "Data Config",
	"disable": "Disabled",
	"application": {
		"inputApplicationName": "Please enter the name of the data application",
		"property": "Data application properties",
		"name": "Data application name",
		"alias": "Data application alias",
		"description": "Data application description",
		"type": "Data application type",
		"icon": "Data application icon",
		"id": "Data application identification",
		"firstPage": "Data application homepage",
		"controllerList": "controller",
		"available": "Available range"
	},
	"createSelectTemplate": "New: Select Template",
	"templateCategory": "Template classification:"
}
MWF.xApplication.service.ServiceManager["lp."+o2.language] = MWF.xApplication.service.ServiceManager.LP