MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.service = MWF.xApplication.service || {};
MWF.xApplication.service.ServiceManager = MWF.xApplication.service.ServiceManager || {};
MWF.xApplication.service.ServiceManager.LP={
	"title": "Gestión de Servicios",
	"categoryTitle": "Categoría de Aplicaciones de Datos",
	"description": "Descripción",
	"deleteItems": "Eliminar elementos seleccionados",
	"copy": "Copiar",
	"copyto": "Copiar en...",
	"copyInfor": "Seleccione varios elementos y presione Ctrl + C para copiarlos. Presione Ctrl + V para pegar los elementos copiados en la aplicación actual.",
	"copyed": "Elementos seleccionados se han copiado",
	"copyConfirmTitle": "Confirmación de Copia de Elementos",
	"copyConfirmInfor": "El área de destino ya contiene elementos idénticos:",
	"copySource": "Archivo original:",
	"copyTarget": "Archivo copiado:",
	"copyConfirm_overwrite": "Sobrescribir",
	"copyConfirm_new": "Nuevo",
	"copyConfirm_skip": "Saltar",
	"copyConfirm_cancel": "Cancelar",
	"copynew": "Nuevo",
	"edit": "Editar",
	"save": "Guardar",
	"cancel": "Cancelar",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"deleteElementTitle": "Confirmación",
	"deleteElement": "¿Estás seguro de que deseas eliminar los elementos de diseño seleccionados?",
	"agent": {
		"name": "Agente",
		"create": "Crear Nuevo Agente",
		"search": "Buscar Agente",
		"searchText": "Ingrese una palabra clave",
		"noAgentNoticeText": "Actualmente no hay agentes disponibles en la gestión del servicio. Haga clic aquí para crear un nuevo agente.",
		"loaded": "Agentes cargados.",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro que desea eliminar el agente actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro que desea eliminar la plantilla actual del agente?",
		"noPermission": "No tiene permisos de administrador para ver los agentes."
	},
	"invoke": {
		"name": "Interfaces",
		"create": "Crear Nueva Interfaz",
		"search": "Buscar Interfaz",
		"searchText": "Ingrese una palabra clave",
		"noAgentNoticeText": "Actualmente no hay interfaces disponibles en la gestión del servicio. Haga clic aquí para crear una nueva interfaz.",
		"loaded": "Interfaces cargadas.",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro que desea eliminar la interfaz actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro que desea eliminar la plantilla actual de la interfaz?",
		"noPermission": "No tiene permisos de administrador para ver las interfaces."
	},
	"dictionary": {
		"name": "Datos",
		"create": "Crear Nuevo Diccionario de Datos",
		"search": "Buscar Diccionario de Datos",
		"searchText": "Ingrese una palabra clave",
		"noDictionaryNoticeText": "Actualmente no hay diccionarios de datos disponibles en la gestión del servicio. Haga clic aquí para crear un nuevo diccionario.",
		"noDictionaryNoCreateNoticeText": "Esta aplicación no tiene actualmente un diccionario de datos.",
		"loaded": "Diccionario de datos cargado.",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro que desea eliminar el diccionario actual de datos?",
		"noPermission": "No tiene permisos de administrador para ver los diccionarios de datos."
	},
	"script": {
		"name": "Scripts",
		"create": "Crear Nuevo Script",
		"search": "Buscar Script",
		"searchText": "Ingrese una palabra clave",
		"noScriptNoticeText": "Actualmente no hay scripts disponibles en la gestión del servicio. Haga clic aquí para crear un nuevo script.",
		"loaded": "Scripts cargados.",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro que desea eliminar el script actual?",
		"noPermission": "No tiene permisos de administrador para ver los scripts."
	},
	"application": {
		"inputApplicationName": "Ingrese el nombre de la aplicación de datos",
		"property": "Propiedades de la aplicación de datos",
		"name": "Nombre de la aplicación de datos",
		"alias": "Alias de la aplicación de datos",
		"description": "Descripción de la aplicación de datos",
		"type": "Tipo de aplicación de datos",
		"icon": "Icono de la aplicación de datos",
		"id": "Identificación de la aplicación de datos",
		"firstPage": "Página principal de la aplicación de datos",
		"controllerList": "Administradores",
		"available": "Alcance disponible"
	},
	"createSelectTemplate": "Crear: Seleccionar Plantilla",
	"templateCategory": "Categoría de plantilla:",
	"all": "Todas",
	"agentConfig": "Agente",
	"interfaceConfig": "Interfaces",
	"scriptConfig": "Scripts",
	"dataConfig": "Datos",
	"disable": "Deshabilitar"
}
MWF.xApplication.service.ServiceManager["lp."+o2.language] = MWF.xApplication.service.ServiceManager.LP