/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.base.core.entity;

import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.base.core.entity.JpaObject.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:17:21 CST 2016")
public class JpaObject_ {
    public static volatile SingularAttribute<JpaObject,Boolean> scratchBoolean;
    public static volatile SingularAttribute<JpaObject,Date> scratchDate;
    public static volatile SingularAttribute<JpaObject,Date> scratchInteger;
    public static volatile SingularAttribute<JpaObject,String> scratchString;
}
