/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.base.core.entity;

import java.lang.Integer;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.base.core.entity.SliceJpaObject.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:46:02 CST 2017")
public class SliceJpaObject_ extends JpaObject_  {
    public static volatile SingularAttribute<SliceJpaObject,Integer> distributeFactor;
}
