/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import com.x.processplatform.core.entity.element.ActivityType;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.ReadCompleted.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:10:19 CST 2017")
public class ReadCompleted_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ReadCompleted,String> activity;
    public static volatile SingularAttribute<ReadCompleted,String> activityName;
    public static volatile SingularAttribute<ReadCompleted,String> activityToken;
    public static volatile SingularAttribute<ReadCompleted,ActivityType> activityType;
    public static volatile SingularAttribute<ReadCompleted,String> application;
    public static volatile SingularAttribute<ReadCompleted,String> applicationAlias;
    public static volatile SingularAttribute<ReadCompleted,String> applicationName;
    public static volatile SingularAttribute<ReadCompleted,String> company;
    public static volatile SingularAttribute<ReadCompleted,Boolean> completed;
    public static volatile SingularAttribute<ReadCompleted,Date> completedTime;
    public static volatile SingularAttribute<ReadCompleted,String> completedTimeMonth;
    public static volatile SingularAttribute<ReadCompleted,Date> createTime;
    public static volatile SingularAttribute<ReadCompleted,String> creatorCompany;
    public static volatile SingularAttribute<ReadCompleted,String> creatorDepartment;
    public static volatile SingularAttribute<ReadCompleted,String> creatorIdentity;
    public static volatile SingularAttribute<ReadCompleted,String> creatorPerson;
    public static volatile SingularAttribute<ReadCompleted,String> department;
    public static volatile SingularAttribute<ReadCompleted,Long> duration;
    public static volatile SingularAttribute<ReadCompleted,String> id;
    public static volatile SingularAttribute<ReadCompleted,String> identity;
    public static volatile SingularAttribute<ReadCompleted,String> job;
    public static volatile SingularAttribute<ReadCompleted,String> opinion;
    public static volatile SingularAttribute<ReadCompleted,String> person;
    public static volatile SingularAttribute<ReadCompleted,String> process;
    public static volatile SingularAttribute<ReadCompleted,String> processAlias;
    public static volatile SingularAttribute<ReadCompleted,String> processName;
    public static volatile SingularAttribute<ReadCompleted,ProcessingType> processingType;
    public static volatile SingularAttribute<ReadCompleted,String> read;
    public static volatile ListAttribute<ReadCompleted,String> resetIdentityList;
    public static volatile SingularAttribute<ReadCompleted,String> sequence;
    public static volatile SingularAttribute<ReadCompleted,String> serial;
    public static volatile SingularAttribute<ReadCompleted,Date> startTime;
    public static volatile SingularAttribute<ReadCompleted,String> startTimeMonth;
    public static volatile SingularAttribute<ReadCompleted,String> title;
    public static volatile SingularAttribute<ReadCompleted,Date> updateTime;
    public static volatile SingularAttribute<ReadCompleted,String> work;
    public static volatile SingularAttribute<ReadCompleted,String> workCompleted;
}
