/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.SerialNumber.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:36:06 CST 2017")
public class SerialNumber_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<SerialNumber,String> application;
    public static volatile SingularAttribute<SerialNumber,Date> createTime;
    public static volatile SingularAttribute<SerialNumber,String> id;
    public static volatile SingularAttribute<SerialNumber,String> name;
    public static volatile SingularAttribute<SerialNumber,String> process;
    public static volatile SingularAttribute<SerialNumber,String> sequence;
    public static volatile SingularAttribute<SerialNumber,Integer> serial;
    public static volatile SingularAttribute<SerialNumber,Date> updateTime;
}
