/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.component.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.component.core.entity.Component.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:08:47 CST 2017")
public class Component_ extends SliceJpaObject_  {
    public static volatile ListAttribute<Component,String> allowList;
    public static volatile ListAttribute<Component,String> controllerList;
    public static volatile SingularAttribute<Component,Date> createTime;
    public static volatile ListAttribute<Component,String> denyList;
    public static volatile SingularAttribute<Component,String> iconPath;
    public static volatile SingularAttribute<Component,String> id;
    public static volatile SingularAttribute<Component,String> name;
    public static volatile SingularAttribute<Component,Integer> order;
    public static volatile SingularAttribute<Component,String> path;
    public static volatile SingularAttribute<Component,String> sequence;
    public static volatile SingularAttribute<Component,String> title;
    public static volatile SingularAttribute<Component,Date> updateTime;
    public static volatile SingularAttribute<Component,Boolean> visible;
    public static volatile SingularAttribute<Component,String> widgetIconPath;
    public static volatile SingularAttribute<Component,String> widgetName;
    public static volatile SingularAttribute<Component,Boolean> widgetStart;
    public static volatile SingularAttribute<Component,String> widgetTitle;
    public static volatile SingularAttribute<Component,Boolean> widgetVisible;
}
