MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.portal = MWF.xApplication.portal || {};
MWF.xApplication.portal.PortalExplorer = MWF.xApplication.portal.PortalExplorer || {};
MWF.xApplication.portal.PortalExplorer.LP={
	"title": "Gestión del portal",
	"all": "Todos",
	"create": "Crear APP",
	"import": "Importar",
	"find": "Buscar",
	"noApplicationCreate": "El sistema no tiene ningún portal o no tiene permisos para gestionar ninguno <br/> Haga clic aquí para crear un nuevo portal",
	"noApplication": "El sistema no tiene ningún portal o no tiene permisos para gestionar ninguno",
	"unDescription": "Este portal no tiene descripción",
	"page": "Página",
	"noPage": "Esta aplicación aún no tiene ninguna página, haga clic aquí para crear una nueva página",
	"unCategory": "Sin categoría",
	"name": "Nombre",
	"alias": "Alias",
	"description": "Descripción",
	"type": "Tipo",
	"icon": "Icono",
	"action_ok": "Aceptar",
	"action_cancel": "Cancelar",
	"createApplication_cancel_title": "Confirmación",
	"createApplication_cancel": "¿Está seguro de que desea cancelar la creación del portal?",
	"createApplicationSuccess": "¡Se ha creado el portal exitosamente!",
	"searchAppPlacholder": "Ingrese el nombre",
	"searchAppTitle": "Coincide con el nombre, alias e id de la aplicación",
	"application": {
		"export": "Exportar",
		"export_ok": "Aceptar",
		"export_cancel": "Cancelar",
		"page": "Página",
		"process": "Proceso",
		"form": "Formulario",
		"dictionary": "Diccionario de datos",
		"script": "Script",
		"import": "Importar",
		"import_confirm_title": "Confirmación",
		"import_confirm": "¿Desea sobrescribir el portal existente que se va a importar? \nHaga clic en \"Aceptar\" para sobrescribir el portal actual. Esta acción no se puede deshacer.",
		"createApplication_cancel_title": "Confirmación",
		"createApplication_cancel": "¿Está seguro de que desea cancelar la creación del portal?",
		"inputApplicationName": "¡Ingrese el nombre del portal!",
		"createApplicationSuccess": "¡Portal creado correctamente!",
		"deleteElements": "Eliminar los portales seleccionados",
		"deleteElementsTitle": "Confirmación",
		"deleteElementsConfirm": "¿Está seguro de que desea eliminar los portales seleccionados? <br><font style='color: red'>Esta acción eliminará todos los elementos de diseño seleccionados del portal, incluidas las páginas, scripts, etc., y no se puede revertir<br></font>",
		"deleteApplicationAllConfirm": "Eliminar también las instancias de proceso completadas.",
		"deleteElementsConfirmAgain": "<font style='color: #00F; font-size:14px'>Confirme nuevamente que desea eliminar los siguientes portales:</font>",
		"deleteElementsAllConfirmAgain": "<font style='color: #00F; font-size:14px'>Confirme nuevamente que desea eliminar los siguientes portales:</font>",
		"select": "Invertir Selección"
	}
}
MWF.xApplication.portal.PortalExplorer["lp."+o2.language] = MWF.xApplication.portal.PortalExplorer.LP