

function staticData() {

    return {
        defaultAppHomePageList: [
            {
                "id": "im",
                "isNative": true,
                "nativeKey": "im",
                "name": "消息",
                "iconClass": "ooicon-message"
            },
            {
                "id": "contact",
                "isNative": true,
                "nativeKey": "contact",
                "name": "通讯录",
                "iconClass": "ooicon-contacts"
            },
            {
                "id": "home",
                "isMain": true,
                "isNative": true,
                "nativeKey": "home",
                "name": "首页",
                "iconClass": "ooicon-home"
            },
            {
                "id": "app",
                "isNative": true,
                "nativeKey": "app",
                "name": "应用",
                "iconClass": "ooicon-app-center"
            },
            {
                "id": "settings",
                "isNative": true,
                "nativeKey": "settings",
                "name": "设置",
                "iconClass": "ooicon-config"
            }
        ],
        homePageUrl: new URL("../assets/app_home.jpg", import.meta.url).href,
        imPageUrl: new URL("../assets/app_im.jpg", import.meta.url).href,
        contactPageUrl: new URL("../assets/app_contact.jpg", import.meta.url).href,
        appPageUrl: new URL("../assets/app_application.jpg", import.meta.url).href,
        settingPageUrl: new URL("../assets/app_setting.jpg", import.meta.url).href,
        iconClassNameList: [
            "ooicon-daiban",
            "ooicon-yiban",
            "ooicon-caogao",
            "ooicon-daiyue",
            "ooicon-ijian",
            "ooicon-files",
            "ooicon-upload",
            "ooicon-gprs",
            "ooicon-lashen",
            "ooicon-kaiqi",
            "ooicon-jia1",
            "ooicon-icon_weikaiqi",
            "ooicon-stop",
            "ooicon-jian",
            "ooicon-jia",
            "ooicon-shuzipaixu",
            "ooicon-zhankai",
            "ooicon-arrow_right",
            "ooicon-jiadian",
            "ooicon-zhedie",
            "ooicon-fujian",
            "ooicon-arrow_left",
            "ooicon-quanping",
            "ooicon-news1",
            "ooicon-right",
            "ooicon-down",
            "ooicon-up",
            "ooicon-message",
            "ooicon-collapse",
            "ooicon-execution",
            "ooicon-process-goback",
            "ooicon-process-submit",
            "ooicon-delete",
            "ooicon-process-monitor",
            "ooicon-edit",
            "ooicon-retract",
            "ooicon-process-downloadall",
            "ooicon-process-end",
            "ooicon-checkmark",
            "ooicon-process-add-task",
            "ooicon-process-split2",
            "ooicon-redo",
            "ooicon-print",
            "ooicon-process-read",
            "ooicon-save",
            "ooicon-process-rollback",
            "ooicon-publish",
            "ooicon-process-flow",
            "ooicon-process-message",
            "ooicon-control-panel",
            "ooicon-close",
            "ooicon-process-begin",
            "ooicon-reset",
            "ooicon-log-viewer",
            "ooicon-icon_caiwushenpi",
            "ooicon-data-center",
            "ooicon-design",
            "ooicon-a-flowprocess",
            "ooicon-a-treeorg",
            "ooicon-person_file",
            "ooicon-procurement",
            "ooicon-travel",
            "ooicon-systemconfig",
            "ooicon-workcenter",
            "ooicon-party",
            "ooicon-role",
            "ooicon-cms-maintain",
            "ooicon-computer",
            "ooicon-doc-cooperation",
            "ooicon-process-maintain",
            "ooicon-app-build",
            "ooicon-office-supplies",
            "ooicon-work-report",
            "ooicon-veriface",
            "ooicon-leave",
            "ooicon-information",
            "ooicon-netraffic",
            "ooicon-score",
            "ooicon-shijianchangjingku",
            "ooicon-ternary-management",
            "ooicon-logistics",
            "ooicon-weekly",
            "ooicon-neibudaohang",
            "ooicon-file-gateway",
            "ooicon-work-overtime",
            "ooicon-employment",
            "ooicon-xinxifabu",
            "ooicon-reports",
            "ooicon-shichangguanli",
            "ooicon-process-service",
            "ooicon-xingzhengshiwu",
            "ooicon-work-plan",
            "ooicon-appstore",
            "ooicon-icon_zhanlue",
            "ooicon-jiekuanshenqing",
            "ooicon-customer",
            "ooicon-description",
            "ooicon-meeting",
            "ooicon-onduty",
            "ooicon-xiangmuxiezuo",
            "ooicon-qianfangguanli",
            "ooicon-kucunguanli",
            "ooicon-zhaobiaoshenqing",
            "ooicon-toubiaoshenqing",
            "ooicon-duty",
            "ooicon-person_manage",
            "ooicon-message2",
            "ooicon-zhichuzhengming",
            "ooicon-contract",
            "ooicon-kaijufapiao",
            "ooicon-ai",
            "ooicon-config",
            "ooicon-taizhang",
            "ooicon-payment",
            "ooicon-employee-file",
            "ooicon-hot-article",
            "ooicon-supplier",
            "ooicon-pentagram",
            "ooicon-cloud-note",
            "ooicon-zhaopin",
            "ooicon-finance",
            "ooicon-pms",
            "ooicon-xinxicaibian",
            "ooicon-jiezhibeiyongjin_sq",
            "ooicon-chat",
            "ooicon-schedule",
            "ooicon-news",
            "ooicon-jixiaokaohe",
            "ooicon-bulletin",
            "ooicon-asset",
            "ooicon-shouwen",
            "ooicon-a-home2",
            "ooicon-a-attendanceprocess-invoke",
            "ooicon-qinggoushenqing",
            "ooicon-work-overtime-record",
            "ooicon-training",
            "ooicon-profile",
            "ooicon-zhaodaifeiyong_sq",
            "ooicon-reimbursement",
            "ooicon-minder",
            "ooicon-cost",
            "ooicon-vehicle",
            "ooicon-notes",
            "ooicon-create",
            "ooicon-shixiangshenpi",
            "ooicon-personnel",
            "ooicon-shigongshenqing",
            "ooicon-myjob",
            "ooicon-home",
            "ooicon-mail",
            "ooicon-contacts",
            "ooicon-document",
            "ooicon-work-management",
            "ooicon-yixiaopin",
            "ooicon-xiezuo",
            "ooicon-forum",
            "ooicon-activities",
            "ooicon-lingdaoxinxiang",
            "ooicon-xiansuo",
            "ooicon-knowledge",
            "ooicon-work-management2",
            "ooicon-gongzjitiao1",
            "ooicon-zongheguanli",
            "ooicon-seal",
            "ooicon-platform",
            "ooicon-fangkeguanli",
            "ooicon-pentagram_fill",
            "ooicon-version_add",
            "ooicon-menu",
            "ooicon-icon_ok_round",
            "ooicon-Import",
            "ooicon-audit",
            "ooicon-department",
            "ooicon-tanhao",
            "ooicon-help",
            "ooicon-switch",
            "ooicon-radio-unchecked",
            "ooicon-empty",
            "ooicon-update",
            "ooicon-review",
            "ooicon-password",
            "ooicon-skin",
            "ooicon-sub_depart_stat",
            "ooicon-guard",
            "ooicon-note",
            "ooicon-list-alt",
            "ooicon-srcipt",
            "ooicon-desktop_mac",
            "ooicon-text",
            "ooicon-default",
            "ooicon-business_trip",
            "ooicon-error",
            "ooicon-person_lock",
            "ooicon-identity",
            "ooicon-strategy",
            "ooicon-forward",
            "ooicon-net-meeting",
            "ooicon-window-max",
            "ooicon-version",
            "ooicon-file-text",
            "ooicon-share",
            "ooicon-storage",
            "ooicon-process-embed",
            "ooicon-party_portal",
            "ooicon-window-return",
            "ooicon-zoom_out",
            "ooicon-personnel_export",
            "ooicon-pad",
            "ooicon-full-text-search",
            "ooicon-unit-post",
            "ooicon-table-tool",
            "ooicon-tree",
            "ooicon-file_upload",
            "ooicon-portal",
            "ooicon-radio-checked",
            "ooicon-wps",
            "ooicon-folder-open",
            "ooicon-process-add-task-person",
            "ooicon-process-cancel",
            "ooicon-file_download",
            "ooicon-rename",
            "ooicon-person_import",
            "ooicon-arrow_forward",
            "ooicon-point3",
            "ooicon-process-parallel",
            "ooicon-help_outline",
            "ooicon-verified",
            "ooicon-arrow_back",
            "ooicon-onlyoffice",
            "ooicon-sub_depart",
            "ooicon-block",
            "ooicon-drop_down",
            "ooicon-a-window-return2",
            "ooicon-documents",
            "ooicon-drive",
            "ooicon-checkbox-checked",
            "ooicon-clock",
            "ooicon-farword",
            "ooicon-process-delay",
            "ooicon-meeting-room",
            "ooicon-process-merge",
            "ooicon-phone",
            "ooicon-group",
            "ooicon-sorting",
            "ooicon-unit",
            "ooicon-crm",
            "ooicon-search",
            "ooicon-qr",
            "ooicon-expand",
            "ooicon-person",
            "ooicon-details",
            "ooicon-puzzle",
            "ooicon-dynamic",
            "ooicon-process-split",
            "ooicon-export",
            "ooicon-process-agent",
            "ooicon-person_disable",
            "ooicon-alphabet",
            "ooicon-check_outline",
            "ooicon-checkbox-unchecked",
            "ooicon-category",
            "ooicon-reload",
            "ooicon-maintain",
            "ooicon-find",
            "ooicon-remove_outline",
            "ooicon-integral",
            "ooicon-app-center",
            "ooicon-process-choice",
            "ooicon-dimission",
            "ooicon-calendar",
            "ooicon-lock",
            "ooicon-eye",
            "ooicon-zoom_in",
            "ooicon-icon_boy",
            "ooicon-animals",
            "ooicon-picture",
            "ooicon-icon_arrow_up",
            "ooicon-icon_more",
            "ooicon-file",
            "ooicon-emoji-travel",
            "ooicon-emote",
            "ooicon-emoji-activities",
            "ooicon-emoji-clothes",
            "ooicon-emoji-food",
            "ooicon-camera",
            "ooicon-add-circle",
            "ooicon-scan",
            "ooicon-send",
            "ooicon-voice",
            "ooicon-emoji-prompt",
            "ooicon-icon_girl",
            "ooicon-keyboard",
            "ooicon-person_clock",
            "ooicon-gongwentaizhang",
            "ooicon-gongzuolianxidan",
            "ooicon-guizhangzhidu",
            "ooicon-home_zd",
            "ooicon-information1",
            "ooicon-hetongshenpi",
            "ooicon-hetongbiangeng",
            "ooicon-hangyexinwen",
            "ooicon-gongzjitiao",
            "ooicon-gongwen",
            "ooicon-caigoushenqing",
            "ooicon-dingbiaobaogao",
            "ooicon-duchaduban",
            "ooicon-dingcan",
            "ooicon-fawen",
            "ooicon-baojiashenqing",
            "ooicon-fapiaoguanli",
            "ooicon-gonghai",
            "ooicon-anliku",

        ]
    };

}

export default staticData