MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Index = MWF.xApplication.cms.Index || {};
MWF.xApplication.cms.Index.LP={
	"title": "Información",
	"createDocument": "Crear documento",
	"selectCategory": "Seleccionar categoría",
	"searchKey": "Introduzca la palabra clave de búsqueda",
	"all": "Todo",
	"filter": "Filtrar",
	"ok": "Aceptar",
	"clear": "Limpiar",
	"defaultView": "Vista predeterminada",
	"setDefaultView": "Establecer esta vista como vista predeterminada para la próxima vez que abra la categoría.",
	"setDefaultSuccess": "¡Vista predeterminada establecida con éxito!",
	"refresh": "Actualizar página principal",
	"documentTitle": "Título",
	"activity": "Actividad",
	"status": "Estado",
	"action": "Acción",
	"person": "Autor",
	"completedTime": "Fecha de completado",
	"noDescription": "Descripción no definida",
	"creatorCompanyList": "Empresa creadora",
	"creatorDepartmentList": "Departamento creador",
	"startTimeMonthList": "Fecha de creación",
	"completedTimeMonthList": "Fecha de completado",
	"start": "Comenzar",
	"key": "Palabra clave",
	"noFormSelected": "Esta categoría no tiene formulario asignado. Por favor, informe al administrador.",
	"documentStartedMessage": "Ha creado un nuevo documento:",
	"open": "Abrir",
	"delete": "Eliminar",
	"edit": "Editar",
	"setTop": "Fijar en la parte superior",
	"share": "Compartir",
	"phone": "Teléfono",
	"mail": "E-mail",
	"deleteDocumentTitle": "Confirmación",
	"deleteDocument": "¿Está seguro que desea eliminar el documento “{title}”?",
	"deleteDocumentOK": "El documento ha sido eliminado con éxito.",
	"allColumn": "Todos",
	"search": "Buscar",
	"reset": "Restablecer",
	"more": "Más"
}
MWF.xApplication.cms.Index["lp."+o2.language] = MWF.xApplication.cms.Index.LP