MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Index = MWF.xApplication.cms.Index || {};
MWF.xApplication.cms.Index.LP={
	"title": "コンテンツ管理ホーム",
	"createDocument": "新しいドキュメントを作成",
	"selectCategory": "カテゴリを選択",
	"searchKey": "検索キーワードを入力してください",
	"all": "すべて",
	"filter": "フィルタ",
	"ok": "確認",
	"clear": "クリア",
	"defaultView": "デフォルトビュー",
	"setDefaultView": "次回カテゴリを開いたときにデフォルトビューに設定",
	"setDefaultSuccess": "デフォルトビューが設定されました！",
	"refresh": "ホームページを更新",
	"documentTitle": "タイトル",
	"activity": "アクティビティ",
	"status": "ステータス",
	"action": "アクション",
	"person": "作成者",
	"completedTime": "完了時間",
	"noDescription": "説明なし",
	"creatorCompanyList": "作成会社",
	"creatorDepartmentList": "作成部門",
	"startTimeMonthList": "作成時間",
	"completedTimeMonthList": "完了時間",
	"start": "開始",
	"key": "キーワード",
	"noFormSelected": "このカテゴリにはフォームが設定されていません。管理者に通知してください。",
	"documentStartedMessage": "あなたは文書を作成しました：",
	"open": "開く",
	"delete": "削除",
	"edit": "編集",
	"setTop": "トップに設定",
	"share": "共有",
	"phone": "電話",
	"mail": "メール",
	"deleteDocumentTitle": "削除の確認",
	"deleteDocument": "「{title}」を削除してもよろしいですか？",
	"deleteDocumentOK": "文書が正常に削除されました",
	"allColumn": "すべての列",
	"search": "検索",
	"reset": "リセット",
	"more": "もっと見る",
	"newer": {
		"start": "新規作成",
		"createDocument": "新規作成",
		"selCategory": "分類の選択",
		"department": "新規単位",
		"identity": "身代金",
		"date": "時間",
		"subject": "ひょうだい",
		"process": "プロセス",
		"cancel": "キャンセル",
		"ok": "を選択して、",
		"unnamedUnit": "名前のない組織",
		"start_cancel_title": "新規確認のキャンセル",
		"start_cancel": "本当に新規作成をキャンセルしますか？",
		"inputSubject": "タイトルを入力してください",
		"selectStartId": "起動者を識別するための起動単位を選択してください",
		"selectCategory": "まず分類を選択してください",
		"clickForSelect": "クリックして分類を選択",
		"Started": "新規作成成功",
		"nextActivity": "次のアクティビティ：",
		"nextUser": "処理者：",
		"processStartedMessage": "新しい作業を開始しました。",
		"processStarted": "ファイルが開始されました",
		"deal": "しょり",
		"all": "すべて",
		"documentTypeInfor": "情報＃ジョウホウ＃",
		"untitled": "タイトルなし",
		"searchPlacholder": "キーワード検索分類の入力"
	}
}
MWF.xApplication.cms.Index["lp."+o2.language] = MWF.xApplication.cms.Index.LP