MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Index = MWF.xApplication.cms.Index || {};
MWF.xApplication.cms.Index.LP={
	"title": "콘텐츠 관리 홈",
	"createDocument": "새 문서 생성",
	"selectCategory": "분류 선택",
	"searchKey": "검색 키워드를 입력하세요",
	"all": "전체",
	"filter": "필터",
	"ok": "확인",
	"clear": "지우기",
	"defaultView": "기본 뷰",
	"setDefaultView": "다음에 카테고리를 열 때 기본 뷰로 설정",
	"setDefaultSuccess": "기본 뷰가 설정되었습니다!",
	"refresh": "홈 새로 고침",
	"documentTitle": "제목",
	"activity": "활동",
	"status": "상태",
	"action": "작업",
	"person": "기안자",
	"completedTime": "완료 시간",
	"noDescription": "설명 없음",
	"creatorCompanyList": "생성 회사",
	"creatorDepartmentList": "생성 부서",
	"startTimeMonthList": "생성 시간",
	"completedTimeMonthList": "완료 시간",
	"start": "시작",
	"key": "키워드",
	"noFormSelected": "이 분류에 양식이 설정되지 않았습니다. 관리자에게 알려주세요.",
	"documentStartedMessage": "문서를 생성했습니다:",
	"open": "열기",
	"delete": "삭제",
	"edit": "편집",
	"setTop": "상단 고정",
	"share": "공유",
	"phone": "전화",
	"mail": "이메일",
	"deleteDocumentTitle": "삭제 확인",
	"deleteDocument": "“{title}”을(를) 삭제하시겠습니까?",
	"deleteDocumentOK": "문서가 성공적으로 삭제되었습니다",
	"allColumn": "모든 열",
	"search": "검색",
	"reset": "초기화",
	"more": "더보기",
	"newer": {
		"start": "새로 만들기",
		"createDocument": "새로 만들기",
		"selCategory": "분류 선택",
		"department": "새 단위",
		"identity": "신분",
		"date": "시간",
		"subject": "표제",
		"process": "프로세스",
		"cancel": "취소",
		"ok": "확인",
		"unnamedUnit": "이름이 지정되지 않은 조직",
		"start_cancel_title": "새로 만들기 확인 취소",
		"start_cancel": "새로 만들기를 취소하시겠습니까?",
		"inputSubject": "제목을 입력하십시오.",
		"selectStartId": "시작 단위를 선택하여 시작자의 신원을 확인하십시오.",
		"selectCategory": "먼저 분류를 선택하십시오.",
		"clickForSelect": "클릭하여 분류 선택",
		"Started": "새로 만들기 성공",
		"nextActivity": "다음 활동:",
		"nextUser": "처리자:",
		"processStartedMessage": "새 작업을 시작했습니다.",
		"processStarted": "파일이 시작됨",
		"deal": "처리",
		"all": "모두",
		"documentTypeInfor": "정보",
		"untitled": "제목 없음",
		"searchPlacholder": "키워드 검색 분류 입력"
	}
}
MWF.xApplication.cms.Index["lp."+o2.language] = MWF.xApplication.cms.Index.LP