MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Index = MWF.xApplication.cms.Index || {};
MWF.xApplication.cms.Index.LP={
	"title": "內容管理首頁",
	"createDocument": "新建文檔",
	"selectCategory": "選擇分類",
	"searchKey": "請輸入搜索關鍵字",
	"all": "全部",
	"filter": "篩選",
	"ok": "確定",
	"clear": "清除",
	"defaultView": "默認視圖",
	"setDefaultView": "設置下次打開分類默認為該視圖",
	"setDefaultSuccess": "設置默認視圖成功！",
	"refresh": "刷新首頁",
	"documentTitle": "標題",
	"activity": "活動",
	"status": "狀態",
	"action": "操作",
	"person": "起草人",
	"completedTime": "完成時間",
	"noDescription": "未定義描述",
	"creatorCompanyList": "創建公司",
	"creatorDepartmentList": "創建部門",
	"startTimeMonthList": "創建時間",
	"completedTimeMonthList": "完成時間",
	"start": "新建",
	"key": "關鍵字",
	"noFormSelected": "該分類未設置表單，請通知管理員",
	"documentStartedMessage": "您創建了一份文檔：",
	"open": "打開",
	"delete": "刪除",
	"edit": "編輯",
	"setTop": "置頂",
	"share": "分享",
	"phone": "電話",
	"mail": "郵件",
	"deleteDocumentTitle": "刪除確認",
	"deleteDocument": "您確定要刪除“{title}”嗎？",
	"deleteDocumentOK": "文檔刪除成功",
	"allColumn": "全部欄目",
	"search": "搜索",
	"reset": "重置",
	"more": "更多",
	"newer": {
		"start": "新建",
		"createDocument": "新建",
		"selCategory": "選擇分類",
		"department": "新建組織",
		"identity": "身份",
		"date": "時間",
		"subject": "標題",
		"process": "流程",
		"cancel": "取消",
		"ok": "確定",
		"unnamedUnit": "未命名組織",
		"start_cancel_title": "取消新建確認",
		"start_cancel": "您確定要取消新建嗎？",
		"inputSubject": "請輸入標題",
		"selectStartId": "請選擇啟動組織，以確定啟動者身份",
		"selectCategory": "請先選擇分類",
		"clickForSelect": "點擊選擇分類",
		"Started": "新建成功",
		"nextActivity": "下一個活動：",
		"nextUser": "處理人：",
		"processStartedMessage": "您啟動了一個新的工作：",
		"processStarted": "檔案已啟動",
		"deal": "處理",
		"all": "全部",
		"documentTypeInfor": "訊息",
		"untitled": "無標題",
		"searchPlacholder": "輸入關鍵字蒐索分類"
	}
}
MWF.xApplication.cms.Index["lp."+o2.language] = MWF.xApplication.cms.Index.LP