/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.Document.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:27 CST 2018")
public class Document_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Document,String> appId;
    public static volatile SingularAttribute<Document,String> appName;
    public static volatile ListAttribute<Document,String> authorGroupList;
    public static volatile ListAttribute<Document,String> authorPersonList;
    public static volatile ListAttribute<Document,String> authorUnitList;
    public static volatile SingularAttribute<Document,String> categoryAlias;
    public static volatile SingularAttribute<Document,String> categoryId;
    public static volatile SingularAttribute<Document,String> categoryName;
    public static volatile SingularAttribute<Document,String> creatorIdentity;
    public static volatile SingularAttribute<Document,String> creatorPerson;
    public static volatile SingularAttribute<Document,String> creatorTopUnitName;
    public static volatile SingularAttribute<Document,String> creatorUnitName;
    public static volatile SingularAttribute<Document,String> description;
    public static volatile SingularAttribute<Document,String> docStatus;
    public static volatile SingularAttribute<Document,String> documentType;
    public static volatile SingularAttribute<Document,String> form;
    public static volatile SingularAttribute<Document,String> formName;
    public static volatile SingularAttribute<Document,Boolean> hasIndexPic;
    public static volatile SingularAttribute<Document,String> id;
    public static volatile SingularAttribute<Document,String> importBatchName;
    public static volatile ListAttribute<Document,String> managerList;
    public static volatile ListAttribute<Document,String> pictureList;
    public static volatile SingularAttribute<Document,Date> publishTime;
    public static volatile SingularAttribute<Document,String> readFormId;
    public static volatile SingularAttribute<Document,String> readFormName;
    public static volatile ListAttribute<Document,String> readGroupList;
    public static volatile ListAttribute<Document,String> readPersonList;
    public static volatile ListAttribute<Document,String> readUnitList;
    public static volatile SingularAttribute<Document,String> summary;
    public static volatile SingularAttribute<Document,String> title;
    public static volatile SingularAttribute<Document,Long> viewCount;
}
