/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.DocumentPermission.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:27 CST 2018")
public class DocumentPermission_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<DocumentPermission,String> appId;
    public static volatile SingularAttribute<DocumentPermission,String> appName;
    public static volatile SingularAttribute<DocumentPermission,String> categoryAlias;
    public static volatile SingularAttribute<DocumentPermission,String> categoryId;
    public static volatile SingularAttribute<DocumentPermission,String> categoryName;
    public static volatile SingularAttribute<DocumentPermission,Date> docCreateDate;
    public static volatile SingularAttribute<DocumentPermission,String> documentId;
    public static volatile SingularAttribute<DocumentPermission,String> documentStatus;
    public static volatile SingularAttribute<DocumentPermission,String> id;
    public static volatile SingularAttribute<DocumentPermission,String> permission;
    public static volatile SingularAttribute<DocumentPermission,String> permissionObjectCode;
    public static volatile SingularAttribute<DocumentPermission,String> permissionObjectName;
    public static volatile SingularAttribute<DocumentPermission,String> permissionObjectType;
    public static volatile SingularAttribute<DocumentPermission,Date> publishDate;
    public static volatile SingularAttribute<DocumentPermission,String> publisher;
    public static volatile SingularAttribute<DocumentPermission,String> title;
    public static volatile SingularAttribute<DocumentPermission,String> updateFlag;
}
