/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.Agent.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat Aug 25 23:19:26 CST 2018")
public class Agent_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Agent,String> alias;
    public static volatile SingularAttribute<Agent,String> cron;
    public static volatile SingularAttribute<Agent,String> description;
    public static volatile SingularAttribute<Agent,Boolean> enable;
    public static volatile SingularAttribute<Agent,String> id;
    public static volatile SingularAttribute<Agent,Date> lastEndTime;
    public static volatile SingularAttribute<Agent,Date> lastStartTime;
    public static volatile SingularAttribute<Agent,String> name;
    public static volatile SingularAttribute<Agent,String> text;
    public static volatile SingularAttribute<Agent,Boolean> validated;
}
