/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.ScheduleLocal.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat Aug 25 23:19:26 CST 2018")
public class ScheduleLocal_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ScheduleLocal,String> application;
    public static volatile SingularAttribute<ScheduleLocal,String> className;
    public static volatile SingularAttribute<ScheduleLocal,String> cron;
    public static volatile SingularAttribute<ScheduleLocal,Integer> delay;
    public static volatile SingularAttribute<ScheduleLocal,Long> elapsed;
    public static volatile SingularAttribute<ScheduleLocal,Date> fireTime;
    public static volatile SingularAttribute<ScheduleLocal,String> id;
    public static volatile SingularAttribute<ScheduleLocal,Integer> interval;
    public static volatile SingularAttribute<ScheduleLocal,String> node;
    public static volatile SingularAttribute<ScheduleLocal,Date> reportTime;
}
