/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.program.center.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.program.center.core.entity.Structure.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat Aug 25 23:19:26 CST 2018")
public class Structure_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Structure,String> data;
    public static volatile SingularAttribute<Structure,String> description;
    public static volatile SingularAttribute<Structure,String> descriptionLob;
    public static volatile SingularAttribute<Structure,String> id;
    public static volatile SingularAttribute<Structure,String> name;
}
