/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.temporary;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.temporary.TriggerWorkRecord.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:10:19 CST 2017")
public class TriggerWorkRecord_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<TriggerWorkRecord,Date> createTime;
    public static volatile SingularAttribute<TriggerWorkRecord,String> id;
    public static volatile SingularAttribute<TriggerWorkRecord,String> lastSequence;
    public static volatile SingularAttribute<TriggerWorkRecord,String> sequence;
    public static volatile SingularAttribute<TriggerWorkRecord,Date> updateTime;
}
