MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xApplication.process.Xform.LP = {
    "ok": "OK",
	"deleteDatagridLineTitle":"Delete item confirmation",
    "deleteDatagridLine": "Are you sure you want to delete the current item?",

    "cancelDatagridLineEditTitle": "Cancel Data Grid Edit Confirmation",
    "cancelDatagridLineEdit": "Are you sure to cancel editing the data grid?",

    "datagridImport": "Import Excel",
    "datagridExport": "Export Excel",
    "exportDefaultName": "DataGrid",
    "datatemplateExportDefaultName": "DataTemplate",
    "datatableExportDefaultName": "DataTable",
    "importSuccess": "Import successful!",
    "validationInfor": "Verification Information",
    "importFail": "Import failed",
    "importValidationColumnText": "Column {n}:",
    "importValidationColumnTextExcel": "Column {n}:",
    "notValidNumber": "Not a number",
    "notValidDate": "Not a date format",
    "fullstop": ".",
    "notExistInSystem": "Does not exist in the system",
    "uploadedFilesCannotHaveSpaces": "Uploaded files cannot contain spaces",

    "browserNotActiveX": "Your browser does not support ActiveX, Office controls cannot be loaded, please use Internet Explorer",

    "activity": "activity",
    "dataSaved": "Data saved successfully",
    "taskProcessed": "File has been submitted",
    "taskProcessedMessage": "You processed a task: ",
    "nextActivity": "Next Activity: ",
    "nextUser": "Processor: ",
    "arrivedActivitys": "arrived activities ",
    "arrivedUsers": "arrived user ",
    "replace": " instead ",
    "next_etc": " {count} people",

    "processStarted": "Job has been started",
    "processStartedMessage": "You started a new job: ",

    "draftStart": "Process has been started",

    "taskCompleted": "Task has been processed",
    "workCompleted": "Work has been completed",
    "arrivedActivity": "Work has arrived activity: ",
    "workProcess": "Flow to",
    "close": "Close",
    "retract": "Retract",
    "reroute": "Reroute",
    "rerouteTo": "RerouteTo",
    "rollback": "Process rollback",
    "rollbackTo": "Process rollback to",
    "selectRollbackActivity": "Select the location of the file to be rollback to:",
    "tryToProcess": "try to continue flow",
    "in": " in ",

    "andSoForth" : "...",

    "noIdentitySelectRange": "Cannot determine the range of identity selection",
    "noIdentityDutySelectRange": "Unable to determine the range of duty selection",
    "noUnitSelectRange": "Cannot determine the selection range of the unit",
    "noSelectRange": "Cannot determine the selection range",
    "noSelectType": "The selection type is not set",
    "selectRoute": "Select Route",
    "submitAt": " Submit At ",
    "idea": " Opinion ",
    "processing": " Processing ",
    "comeTime": "Arrival Time ",
    "begin": " begin ",
    "end": " end ",
    "none": " none ",
    "empower": " empower ",

    "person": " Person ",
    "department": " Department ",
    "startTime": " Received time ",
    "completedTime": " Processing Time ",
    "route": " route ",
    "opinion": " Opinion ",

    "systemProcess": "System Process",
    "showProcess": "Show Process",

    "deleteAttachmentTitle":"Delete attachment confirmation",
    "deleteAttachment": "Are you sure you want to delete the attachments you selected?",

    "sendTaskNotice": "A reminder has been sent to the task person: {users}",
    "setReadedConfirmContent": "Are you sure you want to mark \"{title}\" as readed?",
    "setReadedConfirmTitle": "Mark as readed confirmation",

    "replaceAttachmentTitle": "Replace Attachment Confirmation",
    "replaceAttachment": "Are you sure you want to replace the attachment you selected?",
    "uploadMore": "You can only upload {n} attachments",
    "notValidation": "Data validation failed",
    "notValidation_number": "Only allow numbers",

    "retractTitle": "Retract Confirmation",
    "retractText": "Are you sure you want to retract this document?",
    "workRetract": "The document has been retract",
    "retractWorkInfor": "You retract the document:",

    "currentActivity": "Current Activity:",
    "currentUser": "Processor:",

    "inputResetPeople": "Please select the person to reset to!",
    "resetTo": "Reset To",
    "reset": "Reset",
    "resetOk": "Document has been reset to",
    "workReset": "Document has been reset",
    "resetWorkInfor": "You reset the document:",

    "workRollback": "Document has been backtracked",
    "rollbackOk": "Document has been backtracked to",
    "rollbackWorkInfor": "You have backtracked the document:",

    "workReroute": "Document has been rerouted",
    "rerouteWorkInfor": "You rerouted a document:",
    "rerouteOk": "Document has been rerouted to:",

    "inputSplitValue": "Please enter or choose to increase the value of the branch",
    "addSplitOk": "The processing branch has been added:",
    "addSplitWork": "Processing branch has been added",
    "addSplitWorkInfor": "You have added a branch to the current work",

    "deleteWorkTitle": "Delete work confirmation",
    "deleteWorkText": {"html": "<div style='color: red;'>Note: You are deleting this work, and the work cannot be retrieved after deletion. Are you sure you want to delete this work?</div>" , "text": "Note: You are deleting this work. The work cannot be retrieved after deletion. Are you sure you want to delete this work?"},
    "workDelete": "Work has been deleted",
    "amount": "▌Total",
    "delete": "Delete",
    "add": "Add",
    "addLine": "AddLine",
    "edit": "Edit",
    "completedEdit": "Completed",
    "cancelEdit": "Cancel",
    "mobileGridHelp": "Long press the data area to edit the data<br>Swipe to the left to delete the data",
    "item": "▌Item",
    "all": "All",
    "imageClipper": "Image Editor",
    "noOrgObject": "Unmatched person or organization, click to modify",

    "menu_revisions_show": "ShowTraces",
    "menu_revisions_hide": "HideTraces",
    "menu_fullscreen": "Fullscreen",
    "menu_toolbar_show": "ShowToolbar",
    "menu_toolbar_hide": "HideToolbar",
    "menu_preview": "PrintPreview",
    "menu_redfile": "Red File",
    "menu_seal": "Seal",
    "menu_showHistory": "View history",
    "menu_hideHistory": "Close history",
    "menu_new": "Create Document",
    "menu_openfile": "Open local file",
    "menu_savefile": "Save to local",
    "menu_att": "View Attachment",
    "menu_file": "Open",
    "completed": "Completed",
    "openOfficeInfor": "Click here to open the {type} file",
    "seeVersion": "See Version",
    "selectVersionToRestore": "Please select the text version to be restored:",
    "restoreFile": "Restore",
    "installNTKOWebChromePluginNotice_xpi": "NTKO Web Chrome cross-browser plugin has not been installed. Please click <a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">install components</a>",
    "installNTKOWebChromePluginNotice_crx": "NTKO Web Chrome cross-browser plugin has not been installed. Please click <a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">install components</a>",

    "showReadCompletedTitle": "Readed Person ",
    "showReadTitle": "Reader",
    "worklogRead": "View read",
    "mediaOpinion_image": "Handwritten Opinion",
    "mediaOpinion_video": "Video Opinion",
    "mediaOpinion_voice": "Voice Opinion",

    "attachmentPermission": "Set attachment permission",
    "attachmentPermissionInfo": "You are setting permissions for the following attachments:",
    "attachmentRead": "Who can view this attachment: (If blank, anyone can read this document)",
    "attachmentEdit": "Who can edit this attachment: (If blank anyone can edit this document)",
    "attachmentController": "Who can set permissions of this attachment: ",

    "attachmentOCRTitle": "Correct the text in the automatically recognized picture",
    "attachmentOCR_saved": "Image text recognition results have been saved",

    "attachmentOrderTitle": "Attachment Order",
    "attachmentOrderUp": "Up",
    "attachmentOrderDown": "Down",
    "attachmentOrderInfo": "Drag the attachment icon, or sort the attachments through the \"Up\" and \"Down\" buttons",

    "autosave": "Auto Save Document",

    "ignore": "Ignore",
    "ANNInput": "Smart input suggested value: ",

    "recover": "Recover Text",
    "notRecover": "Cancel body recovery",

    "doublePage": "Double",
    "singlePage": "Single",
    "editdoc": "EditText",
    "editdocCompleted": "EditComplete",
    "printdoc": "Print",
    "history": "Text Trace",
    "fullScreen": "FullScreen",
    "returnScreen": "Restore",

    "editdoc_mobile": "Edit",
    "editdocCompleted_mobile": "EditComplete",
    "printdoc_mobile": "Print",
    "history_mobile": "Trace",


    "subformNestedError": "This form has nested subforms, please contact the administrator!",
    "subpageNestedError": "There are nested subpages on this page, please contact the administrator!",

    "subformUniqueError": "The form is embedded with the same subform repeatedly, please contact the administrator!",
    "moduleUniqueError": "The form has a field with the same name, please contact the administrator!",

    "selectEmpower": "Authorized personnel selection",
    "empowerDlgText": "The following personnel have empowered the work, the file will be sent to the empowered person after selection, and the file will be sent to the task person after deselecting",
    "empowerTo": "Empower to",
    "empowerToHtml": "<font style='color:#ff5400;'>{person}</font>({department}) empowered to <font style='color:#ff5400;'>{empowerTo}</font> Processing. ({time})</font>",
    "selectAll": "Select All",
    "computePage": "Calculating page breaks, please wait...",
    "keyLockTitle": "File editing is locked",
    "keyLockInfor": "The file is being edited by {name}. You can view the contents of the document and refresh the page to try again later.",

    "year" : " Year ",
    "month" : " Month ",
    "date" : " ",

    "documentEditor": {
        "copies": "",
        "secret":"",
        "priority": "",
        "redHeader": "文件红头",
        "fileno":"[文号]",
        "signerTitle": "签发人：",
        "signer": "[签发人]",
        "subject": "[标题]",
        "mainSend": "[主送单位：]",
        "filetext": "[请在此处编辑正文内容]",
        "attachmentTitle":"附件：",
        "attachment":"[附件]",
        "issuanceUnit":"[发文机关]",
        "issuanceDate":"[成文日期]",
        "annotation":"",
        "copytoTitle":"抄送：",
        "copyto":"[抄送]",
        "editionUnit":"[印发机关]",
        "editionDate":"[印发日期]",
        "historyList": "历史版本文档"
    },
    "documentHistory": {
        "diffContent": "<div>{time}</div>{name} modified content at \"{activity}\"",
        "insertContent": "<div>{time}</div>{name} inserted content at \"{activity}\":",
        "deleteContent": "<div>{time}</div>{name} deleted content at \"{activity}\":",
        "insert": " Insert ",
        "delete": " Deleted ",
        "insertTimes": " Insert at {times} ",
        "deleteTimes": " Deleted {times} ",

        "play": "Play",
        "pause": "Pause",
        "stop": "Stop",
        "next": "Next Modification Record",
        "prev": "Previous Modification Record",
        "exit": "Exit Trace Review",

        "diff_patch_count": "Total {history} versions, {diff} revisions.",
        "original": "Original Version",
        "nodiff": "There is no historical modification information yet",
        "word": " word ",
        "diff": "Contrast",
        "diffTitle": "Compared with the previous version"
    },
    "subjectEmpty": "Subject cannot be empty",
    "issuanceUnitEmpty": "The issuing unit cannot be empty",
    "fullWidth": "The automatic conversion of half-width spaces to full-width spaces is enabled. If you need to enter half-width spaces, please use: SHIFT+space",

    "pauseWork": "The current task has entered the pending state",
    "resumeWork": "The current task has been resumed from the pending state",

    "resume": "Resume",
    "pause": "Pending",

    "selectItemCountNotice": "Please select at least {count} items",
    "setReaded": "Mark as read",
    "readed": "Readed",

    "attachmentArea": "Attachments",
    "intelligentCorrection": "Intelligent Error Correction",

    "maxItemCountNotice": "A maximum of {n} items allowed to be added",
    "selectItemNotice": "Please select item",
    "minItemNotice": "At least {n} items need to be kept. The deleted item is less than the item to be kept, please check",
    "deleteSelectedItemNotice": "Are you sure you want to delete the selected item",
    "minItemCountNotice": "Please keep at least {n} items",
    "systemField": "System Field",
    "systemFieldEmptyNotice": "System Field cannot be empty",
    "importTooManyNotice ":" you import {n1} data, allowed to import {n2} data maximum ",
    "importTooFewNotice ": "you import {n1} data, need to keep at least {n2} data ",

    "form": {
        "close":"Close",
        "closeTitle": "Close Document",
        "save": "Save",
        "saveTitle": "Save Document",
        "flow": "Flow",
        "flowTitle": "Flow Document",
        "reroute": "Reroute",
        "rerouteTitle": "Reroute to other Activity",
        "reset": "Reset",
        "resetTitle": "Reset to other Person",
        "split": "AddSplit",
        "splitTitle": "Add Split Work branch",
        "retract": "Retract",
        "retractTitle": "Retract Task to current person",
        "rollback": "Rollback",
        "rollbackTitle": "Rollback the work to the specified activity, without keeping process records",
        "delete": "Delete",
        "deleteTitle": "Delete Document",
        "print": "Print",
        "printTitle": "Open through the print form, and print the document",
        "press": "Urge",
        "pressTitle": "Urge",
        "pause": "Pending",
        "pauseTitle": "Set the task as pending",
        "resume": "Resume",
        "resumeTitle": "Resume the task from pending",
        "downloadAll": "Download",
        "downloadAllTitle": "Download the form and all attachments",

        "rerouteActivity": "Activity: ",
        "reroutePerson": "Person: ",
        "selectPerson": "Select",
        "retouteOpinion": "Opinion: ",

        "resetPerson": "Person: ",
        "resetOpinion": "Opinion: ",
        "keepTask": "Keep my task",

        "readedOpinion": "Opinion: ",

        "rollbackInfo": "Select the location of the file to be rollback to",
        "addSplitInfo": "Split data according to your business settings. The data should match the split setting in the process. multiple values with a comma (,)",
        "selectUnit": "Select Unit",
        "excludeBranches": "Exclude existing branches",
        "yes": "Yes",
        "no": "No"
    }

};
MWF.xApplication.process.Xform["lp."+o2.language] = MWF.xApplication.process.Xform.LP;
