MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xApplication.process.Xform.LP={
	"ok": "Aceptar",
	"deleteDatagridLineTitle": "Confirmación de eliminación de entrada",
	"deleteDatagridLine": "¿Está seguro de que desea eliminar la entrada actual?",
	"cancelDatagridLineEditTitle": "Confirmación para cancelar la edición de la cuadrícula de datos",
	"cancelDatagridLineEdit": "¿Está seguro de que desea cancelar la edición de la cuadrícula de datos?",
	"datagridImport": "Importar desde Excel",
	"datagridExport": "Exportar a Excel",
	"exportDefaultName": "Cuadrícula de datos",
	"datatemplateExportDefaultName": "Plantilla de datos",
	"datatableExportDefaultName": "Tabla de datos",
	"importSuccess": "Importación exitosa!",
	"validationInfor": "Información de validación",
	"importFail": "Importación fallida",
	"importValidationColumnText": "Columna {n}: ",
	"importValidationColumnTextExcel": "Columna{n}: ",
	"notValidNumber": "No es un número",
	"notValidDate": "No es un formato de fecha válido",
	"fullstop": ".",
	"notExistInSystem": "No existe en el sistema",
	"uploadedFilesCannotHaveSpaces": "Los archivos cargados no pueden tener espacios en blanco",
	"browserNotActiveX": "Su navegador no admite controles ActiveX y no puede cargar controles de Office. Utilice el navegador IE.",
	"activity": "Actividad",
	"dataSaved": "La información se ha guardado correctamente",
	"taskProcessed": "El archivo se ha enviado",
	"taskProcessedMessage": "Usted ha procesado una tarea pendiente:",
	"nextActivity": "Siguiente actividad:",
	"nextUser": "Persona a cargo:",
	"arrivedActivitys": "Actividades alcanzadas",
	"arrivedUsers": "Personas a cargo alcanzadas",
	"replace": "Reemplazar con",
	"next_etc": "y {count} personas más",
	"nextTaskMatrix": "Posibles siguientes procesadores: ",
	"processStarted": "El archivo se ha iniciado",
	"processStartedMessage": "Usted ha iniciado un nuevo trabajo:",
	"draftStart": "El proceso se ha iniciado",
	"taskCompleted": "La tarea pendiente se ha procesado",
	"workCompleted": "El flujo de trabajo se ha completado",
	"arrivedActivity": "La tarea ha llegado a la actividad:",
	"workProcess": "Continuar el flujo de trabajo",
	"close": "Cerrar",
	"retract": "Retirar",
	"reroute": "Reajustar",
	"rerouteTo": "Reajustar a",
	"rollback": "Retroceder proceso",
	"rollbackTo": "Retroceder proceso hasta",
	"rollback_success": "Éxito al revertir",
	"selectRollbackActivity": "Por favor seleccione la posición en la que desea retroceder el archivo:",
	"tryToProcess": "y tratar de continuar el proceso",
	"in": "en",
	"andSoForth": "y así sucesivamente",
	"noIdentitySelectRange": "No se puede determinar el rango de selección de identidad",
	"noIdentityDutySelectRange": "No se puede determinar el rango de selección de posición de identidad",
	"noUnitSelectRange": "No se puede determinar el rango de selección de organización",
	"noSelectRange": "No se puede determinar el rango de selección",
	"noSelectType": "Tipo de selección no establecido",
	"selectRoute": "Seleccionar ruta",
	"submitAt": "Enviado en",
	"idea": "Idea",
	"processing": "Procesando",
	"comeTime": "Hora de llegada",
	"begin": "Inicio",
	"end": "Fin",
	"none": "Ninguno",
	"empower": "Autorizar",
	"person": "Persona responsable",
	"department": "Departamento",
	"startTime": "Tiempo de recepción",
	"completedTime": "Tiempo de procesamiento",
	"route": "Ruta",
	"opinion": "Opinión",
	"systemProcess": "Proceso del sistema",
	"showProcess": "Mostrar diagrama de flujo",
	"deleteAttachmentTitle": "Confirmación de eliminación de archivo adjunto",
	"deleteAttachment": "¿Está seguro de que desea eliminar los archivos adjuntos seleccionados?",
	"sendTaskNotice": "Se ha enviado un recordatorio a los usuarios pendientes: {users}",
	"setReadedConfirmContent": "¿Está seguro de que desea marcar '{title}' como leído?",
	"setReadedConfirmTitle": "Confirmación de marca de lectura",
	"replaceAttachmentTitle": "Confirmación de reemplazo de archivo adjunto",
	"replaceAttachment": "¿Está seguro de que desea reemplazar los archivos adjuntos seleccionados?",
	"uploadMore": "Solo se permiten cargar máximo {n} archivos adjuntos ",
	"notValidation": "La validación de datos no ha pasado",
	"lineNotValidation": "Validación de datos de línea no aprobada",
	"notValidation_number": "Debe ingresar un número",
	"notAttachmentValidation": "Validación de archivo adjunto no aprobada",
	"retractTitle": "Confirmación de Retirada",
	"retractText": "¿Está seguro de que desea retirar este archivo?",
	"workRetract": "Archivo retirado exitosamente",
	"retractWorkInfor": "Ha retirado el archivo:",
	"currentActivity": "Actividad Actual:",
	"currentUser": "Responsable:",
	"inputResetPeople": "¡Seleccione a las personas a las que desea restablecer!",
	"resetTo": "Restablecer a",
	"reset": "Reiniciar",
	"resetOk": "Archivo reiniciado exitosamente",
	"workReset": "Archivo restablecido exitosamente",
	"resetWorkInfor": "Ha restablecido el archivo:",
	"workRollback": "Archivo regresado exitosamente",
	"rollbackOk": "Archivo regresado a:",
	"rollbackWorkInfor": "Archivo regresado:",
	"workReroute": "Archivo reenrutado exitosamente",
	"rerouteWorkInfor": "Archivo reenrutado:",
	"rerouteOk": "Archivo reenrutado a:",
	"inputSplitValue": "Ingrese o seleccione un valor para agregar una rama",
	"addSplitOk": "Se ha agregado la rama de procesamiento:",
	"addSplitWork": "Se ha agregado la rama de procesamiento",
	"addSplitWorkInfor": "Ha agregado una rama al trabajo actual",
	"deleteWorkTitle": "Confirmación de Eliminación de Archivo",
	"deleteWorkText": {
		"html": "<div style='color: red;'>Nota: Está eliminando este documento, después de eliminarlo no se puede recuperar, ¿está seguro de que desea eliminar este archivo?</div>",
		"text": "Nota: Está eliminando este documento, después de eliminarlo no se puede recuperar, ¿está seguro de que desea eliminar este archivo?"
	},
	"workDelete": "Archivo eliminado exitosamente",
	"terminateWorkTitle": "Terminar la confirmación del archivo",
	"terminateWorkText": "Terminar el archivo significa que el archivo se abandona y se transferirá directamente.",
	"workTerminate": "El archivo ha sido terminado",
	"terminateWork": "terminar el archivo",
	"amount": "▌Total",
	"sectionAmount": "▌Subtotal",
	"delete": "Eliminar",
	"add": "Agregar",
	"addLine": "Agregar nueva entrada",
	"edit": "Editar",
	"completedEdit": "Completado",
	"cancelEdit": "Cancelar",
	"mobileGridHelp": "Mantenga presionado el área de datos para editar los datos<br>Deslice hacia la izquierda para eliminar los datos",
	"item": "▌Entrada",
	"all": "Todo",
	"imageClipper": "Editor de Imágenes",
	"noOrgObject": "Persona u organización no encontrada. Haga clic para modificar",
	"menu_revisions_show": "Mostrar cambios",
	"menu_revisions_hide": "Ocultar cambios",
	"menu_fullscreen": "Modo de pantalla completa",
	"menu_toolbar_show": "Mostrar barra de herramientas",
	"menu_toolbar_hide": "Ocultar barra de herramientas",
	"menu_preview": "Vista previa de impresión",
	"menu_redfile": "Agregar carátula",
	"menu_seal": "Agregar sello",
	"menu_showHistory": "Ver versiones anteriores",
	"menu_hideHistory": "Cerrar versiones anteriores",
	"menu_new": "Nuevo documento",
	"menu_openfile": "Abrir archivo local",
	"menu_savefile": "Guardar en el equipo",
	"menu_att": "Ver archivos adjuntos",
	"menu_file": "Abrir documento",
	"completed": "Completado",
	"openOfficeInfor": "Haga clic aquí para abrir el archivo {type}",
	"seeVersion": "Ver versión",
	"selectVersionToRestore": "Seleccione la versión del documento que desea restaurar:",
	"restoreFile": "Restaurar documento",
	"installNTKOWebChromePluginNotice_xpi": "El complemento NTKO Web Chrome para navegadores cruzados no está instalado. Haga clic en <a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">instalar componente</a>",
	"installNTKOWebChromePluginNotice_crx": "El complemento NTKO Web Chrome para navegadores cruzados no está instalado. Haga clic en <a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">instalar componente</a>",
	"showReadCompletedTitle": "Usuarios que han leído el documento",
	"showReadTitle": "Usuarios pendientes de leer el documento",
	"worklogRead": "Ver documentos pendientes de lectura",
	"mediaOpinion_image": "Opinión escrita a mano",
	"mediaOpinion_video": "Opinión en video",
	"mediaOpinion_voice": "Opinión en audio",
	"attachmentPermission": "Establecer permisos para archivos adjuntos",
	"attachmentPermissionInfo": "Está estableciendo permisos para los siguientes archivos adjuntos:",
	"attachmentRead": "¿Quiénes pueden ver y descargar este archivo adjunto? (Si está vacío, todos los usuarios con permiso para leer este documento lo podrán hacer. Si no es así, se deben seleccionar simultáneamente opciones para editar y establecer permisos)",
	"attachmentEdit": "¿Quiénes pueden editar este archivo adjunto? (Si está vacío, todos los usuarios con permiso para editar este documento lo podrán hacer. Si no es así, se deben seleccionar simultáneamente opciones para editar y establecer permisos)",
	"attachmentController": "¿Quiénes pueden establecer permisos para este archivo adjunto? (Si está vacío, todos los usuarios con permiso para editar este documento lo podrán hacer)",
	"attachmentOCRTitle": "Corrección de texto en imágenes identificadas automáticamente",
	"attachmentOCR_saved": "Se ha guardado el resultado del reconocimiento de texto de la imagen",
	"attachmentOrderTitle": "Ordenación de archivos adjuntos",
	"attachmentOrderUp": "Mover hacia arriba",
	"attachmentOrderDown": "Mover hacia abajo",
	"attachmentOrderInfo": "Arrastre el icono del archivo adjunto o utilice los botones \"mover hacia arriba\" y \"mover hacia abajo\" para ordenar los archivos adjuntos",
	"autosave": "Guardar automáticamente el documento",
	"ignore": "Ignorar",
	"ANNInput": "Sugerencia de valor inteligente:",
	"recover": "Restaurar documento original",
	"notRecover": "Cancelar la restauración del documento original",
	"doublePage": "Dos páginas",
	"singlePage": "Una página",
	"editdoc": "Editar documento",
	"editdocCompleted": "Edición completada",
	"printdoc": "Imprimir documento",
	"history": "Revisión de cambios en el documento",
	"handwrittenApproval": "Aprobación escrita a mano",
	"fullScreen": "Pantalla completa",
	"returnScreen": "Volver a pantalla normal",
	"editdoc_mobile": "Editar",
	"editdocCompleted_mobile": "Edición completada",
	"printdoc_mobile": "Imprimir",
	"history_mobile": "Cambios",
	"handwrittenApproval_mobile": "Aprobación",
	"subformNestedError": "Este formulario tiene formularios secundarios anidados entre sí. Por favor, contacte al administrador.",
	"subpageNestedError": "Esta página tiene subpáginas anidadas entre sí. Por favor, contacte al administrador.",
	"subformUniqueError": "Este formulario tiene campos con nombres repetidos. Por favor, contacte al administrador.",
	"moduleUniqueError": "Este formulario tiene campos anidados con nombres repetidos. Por favor, contacte al administrador.",
	"selectEmpower": "Seleccionar reemplazo para persona autorizada",
	"empowerDlgText": "Las siguientes personas han sido autorizadas para gestionar este trabajo. Si selecciona otra persona, el archivo será enviado a esa persona. Si no selecciona a nadie, el archivo se enviará a la persona autorizada originalmente.",
	"empowerTo": "Autorizar a",
	"empowerToHtml": "<font style='color:#ff5400;'>{person}</font> ({department}) ha autorizado a <font style='color:#ff5400;'>{empowerTo}</font> para gestionar el archivo. ({time})",
	"autoFlowHtml": "Enviado automáticamente por el sistema: {time}",
	"systemSubmit": "Procesado automáticamente por el sistema",
	"selectAll": "Seleccionar todo",
	"computePage": "Calculando páginas, por favor espere...",
	"keyLockTitle": "Edición del archivo bloqueada",
	"keyLockInfor": "El archivo está siendo editado por {name}. Puede ver el contenido del archivo y volver a intentarlo más tarde actualizando la página.",
	"year": "Año",
	"month": "Mes",
	"date": "Día",
	"documentEditor": {
		"copies": "",
		"secret": "",
		"priority": "",
		"redHeader": "Encabezado del archivo",
		"fileno": "[Número del documento]",
		"signerTitle": "Emisor:",
		"signer": "[Nombre del emisor]",
		"subject": "[Título del documento]",
		"mainSend": "[Destinatario principal:]",
		"filetext": "[Editar el contenido del documento aquí]",
		"attachmentTitle": "Adjuntos:",
		"attachment": "[Archivos adjuntos]",
		"issuanceUnit": "[Organismo emisor]",
		"issuanceDate": "[Fecha de escritura del documento]",
		"annotation": "",
		"copytoTitle": "Copia a:",
		"copyto": "[Persona/s que reciben copia del documento]",
		"editionUnit": "[Organismo encargado de la impresión y distribución]",
		"editionDate": "[Fecha de impresión y distribución]",
		"historyList": "Historial de versiones del documento",
		"attachmentInfor": "[Editar el contenido del archivo adjunto aquí]"
	},
	"documentHistory": {
		"diffContent": "<div>{time}</div>{name} ha modificado el contenido en \"{activity}\"",
		"insertContent": "<div>{time}</div>{name} ha insertado el contenido en \"{activity}\":",
		"deleteContent": "<div>{time}</div>{name} ha borrado el contenido en \"{activity}\":",
		"insert": "ha insertado",
		"delete": "ha borrado",
		"insertTimes": "ha insertado {times} veces",
		"deleteTimes": "ha borrado {times} veces",
		"play": "Reproducir los cambios realizados",
		"pause": "Pausar la reproducción",
		"stop": "Detener la reproducción de los cambios realizados",
		"next": "Siguiente cambio realizado",
		"prev": "Cambio realizado anterior",
		"exit": "Salir de la revisión de cambios",
		"diff_patch_count": "Hay {history} versiones anteriores y se han hecho {diff} modificaciones.",
		"original": "Versión original",
		"nodiff": "Actualmente no hay historial de cambios",
		"word": "Palabras",
		"diff": "Comparar",
		"diffTitle": "Comparar con la versión anterior",
		"showAll": "Mostrar todos los cambios"
	},
	"subjectEmpty": "El título no puede estar vacío",
	"issuanceUnitEmpty": "La unidad emisora no puede estar vacía",
	"fullWidth": "Se ha activado la conversión automática de espacios medios a espacios completos. Para ingresar un espacio medio, use SHIFT + ESPACIO.",
	"pauseWork": "El trabajo pendiente actual se ha suspendido",
	"resumeWork": "El trabajo pendiente actual se ha reanudado desde el estado suspendido",
	"resume": "Reanudar",
	"pause": "Suspender",
	"selectItemCountNotice": "Seleccione al menos {count} elementos",
	"setReaded": "Marcar como leído",
	"readed": "Leído",
	"attachmentArea": "Área de archivos adjuntos",
	"intelligentCorrection": "Corrección inteligente",
	"maxItemCountNotice": "Se permite agregar hasta {n} elementos como máximo",
	"selectItemNotice": "Seleccione primero un elemento",
	"minItemNotice": "Debe haber al menos {n} elementos. Si elimina los elementos seleccionados, habrá menos elementos que los necesarios.",
	"deleteSelectedItemNotice": "¿Está seguro de que desea eliminar los elementos seleccionados?",
	"minItemCountNotice": "Debe haber al menos {n} elementos",
	"systemField": "Campo del sistema",
	"systemFieldEmptyNotice": "El campo del sistema no puede estar vacío",
	"importTooManyNotice": "En esta ocasión ha importado {n1} datos, se permiten importar como máximo {n2} datos",
	"importTooFewNotice": "En esta ocasión ha importado {n1} datos, es necesario conservar al menos {n2} datos",
	"pleaseSelect": "Seleccione por favor",
	"form": {
		"close": "Cerrar",
		"closeTitle": "Cerrar el documento",
		"save": "Guardar",
		"saveTitle": "Guardar el documento",
		"flow": "Entregar",
		"flowTitle": "Enviar documento",
		"process": "Entregar",
		"processTitle": "Enviar documento",
		"submit": "Entregar",
		"submitTitle": "Enviar documento",
		"reroute": "Reprogramar",
		"rerouteTitle": "Reprogramar el documento",
		"reset": "Restablecer el responsable",
		"resetTitle": "Restablecer el responsable del documento",
		"split": "Agregar una rama",
		"splitTitle": "Agregar una rama de división",
		"retract": "Retirar",
		"retractTitle": "Retirar el trabajo pendiente",
		"rollback": "Retroceder en el flujo de trabajo",
		"rollbackTitle": "Retroceder a una etapa específica sin conservar los registros del flujo de trabajo",
		"delete": "Borrar el documento",
		"deleteTitle": "Borrar el archivo",
		"terminar": "Terminar",
		"terminateTitle": "Finalizar transferencia de archivo",
		"print": "Imprimir",
		"printTitle": "Imprimir el documento",
		"press": "Apurar la tarea",
		"pressTitle": "Apurar la tarea",
		"pause": "Suspender",
		"pauseTitle": "Suspender el trabajo pendiente",
		"resume": "Reanudar la suspensión",
		"resumeTitle": "Reanudar desde el estado suspendido",
		"downloadAll": "Descargar todo",
		"downloadAllTitle": "Descargar todo",
		"monitor": "Monitor de proceso",
		"monitorTitle": "Monitor de proceso",
		"addTask": "Agregar asignación",
		"addTaskTitle": "Agregar un responsable para la etapa actual",
		"rerouteActivity": "Nodo:",
		"reroutePerson": "Persona:",
		"selectPerson": "Seleccionar",
		"retouteOpinion": "Opinión sobre la reprogramación:",
		"resetPerson": "Persona:",
		"resetOpinion": "Opinión:",
		"keepTask": "Conservar mi tarea pendiente",
		"readedOpinion": "Opinión de lectura",
		"setReaded": "Marcar como leído",
		"readed": "Leído",
		"rollbackInfo": "Seleccione la etapa a la que desea retroceder el archivo",
		"addSplitInfo": "Configure los datos de división según su negocio. Estos datos deben coincidir con los criterios de división establecidos en el flujo de trabajo.<br/> Si hay varios valores, sepárelos con comas (,)",
		"splitValue": "Dividir por",
		"opinion": "opinión",
		"selectUnit": "Seleccionar organización o persona",
		"excludeBranches": "Excluir ramas existentes",
		"yes": "Sí",
		"no": "No",
		"readIdentity": "Persona para leer",
		"sendReadNotify": "Enviar notificación de lectura pendiente",
		"reviewIdentity": "Lector",
		"noTaskToReset": "No puede realizar esta operación porque no tiene una tarea pendiente.",
		"addTaskPerson": "Persona",
		"addTaskOpinion": "Opinión",
		"addTaskBefore": "Antes",
		"addTaskAfter": "Después",
		"addTaskBeforeTitle": "Agregar un responsable antes de que se procese la tarea",
		"addTaskAfterTitle": "Agregar un responsable después de que se procese la tarea",
		"addTaskType": "Método de asignación",
		"modeType": "Método de procesamiento",
		"single": "soltero",
		"queue": "serie",
		"parallel": "paralelo",
		"addTaskRepeatedTitle": "Recordatorio de asignación repetida",
		"addTaskRepeatedInfo": "<span class='mainColor_color'><b>{repeated}</b></span> ya está en la lista de responsables y no se le puede volver a asignar.",
		"mergeWork": "Fusionar trabajo",
		"terminate": "Documento de terminación",
		"goBack": "Devolución",
		"goBackTitle": "Devolución a actividades ya pasadas",
		"goBackActivity": "Devolución al evento:",
		"goBackActivityWay": "Procesamiento posterior a la devolución:",
		"goBackActivityWayStep": "Circulación normal de acuerdo con el proceso",
		"goBackActivityWayJump": "Volver directamente a la persona devuelta",
		"goBackTo": "Devuelto a:",
		"selectGoBackActivity": "Por favor, elija la actividad a devolver"
	},
	"sendRead": "Enviar lectura pendiente",
	"sendReadOk": "La lectura pendiente ha sido enviada",
	"noPermissionOrWorkNotExisted": "No tiene permiso o el trabajo no existe",
	"inputSendReadPeople": "Seleccione la persona para la lectura pendiente",
	"sendReadPeopleCanNotEmpty": "La persona para la lectura pendiente no puede estar vacía",
	"sendReview": "Agregar lector",
	"sendReviewOk": "El lector ha sido agregado",
	"inputSendReviewPeople": "Seleccione un lector",
	"sendReviewPeopleCanNotEmpty": "El lector no puede estar vacío",
	"inputAddTaskPeople": "Seleccione la persona para agregar asignación",
	"addTaskOk": "Se agregó correctamente la persona para agregar asignación",
	"addTaskInfor": "Ha agregado una asignación al archivo:",
	"applicationNotFound": "No se encontró la aplicación",
	"pdfview": {
		"nofile": "No hay archivos, por favor suba uno",
		"upload": "Subir"
	},
	"ofdview": {
		"nofile": "No hay archivos, por favor suba uno",
		"upload": "Subir"
	},
	"onlyoffice": {
		"noInstall": "Por favor instale la aplicación onlyoffice primero",
		"filetext": "Cuerpo del archivo"
	},
	"officeonline": {
		"noInstall": "Por favor instale la aplicación officeonline primero",
		"filetext": "Cuerpo del archivo"
	},
	"title": "Título",
	"createTime": "Hora de creación",
	"creatorPerson": "Creador",
	"creatorUnit": "Organización creadora",
	"score": "Relevancia",
	"updateTime": "Hora de actualización",
	"documentType": "Tipo de documento",
	"processName": "Nombre del proceso",
	"draftTime": "Tiempo de borrador",
	"draftPerson": "Autor de la propuesta",
	"categoryName": "Clasificado",
	"publishPerson": "Editor",
	"publishTime": "Publishing time",
	"document": "Información",
	"work": "Trabajo",
	"cancelAssociatedTitle": "Cancelar documento asociado",
	"cancelAssociated": "¿Está seguro de la asociación que desea cancelar con el documento '{title}'?",
	"associatedResult": "Resultado asociado",
	"selectDocNote": "Primero seleccione un documento",
	"associatedDocument": "Documento asociado",
	"docDeleted": "El documento ha sido eliminado o no tiene permiso para abrir este documento.",
	"system": "Sistema",
	"attachmentSecurity": "Identificación del nivel de confidencialidad del Anexo",
	"uploading": "Se está cargando el anexo, por favor espere a que se complete la carga del anexo antes de realizar esta operación."
}
MWF.xApplication.process.Xform["lp."+o2.language] = MWF.xApplication.process.Xform.LP