MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xApplication.process.Xform.LP = {
    "ok": "確認",
    "deleteDatagridLineTitle": "項目削除確認",
    "deleteDatagridLine": "現在の項目を削除しますか？",

    "cancelDatagridLineEditTitle": "データグリッド編集キャンセル確認",
    "cancelDatagridLineEdit": "データグリッドの編集をキャンセルしますか？",

    "datagridImport": "Excel インポート",
    "datagridExport": "Excel エクスポート",
    "exportDefaultName": "データグリッド",
    "datatemplateExportDefaultName": "データテンプレート",
    "datatableExportDefaultName": "データテーブル",
    "importSuccess": "インポート成功！",
    "validationInfor": "検証情報",
    "importFail": "インポート失敗",
    "importValidationColumnText": "第{n}列：",
    "importValidationColumnTextExcel": "列{n}：",
    "notValidNumber": "数字ではありません",
    "notValidDate": "日付形式ではありません",
    "fullstop": "。",
    "notExistInSystem": "システムに存在しません",
    "uploadedFilesCannotHaveSpaces": "アップロードしたファイルにはスペースを含めることはできません",

    "browserNotActiveX": "ご使用のブラウザはActiveXコントロールをサポートしていないため、Officeコントロールをロードできません。IEブラウザをご使用ください",

    "activity": "アクティビティ",
    "dataSaved": "データ保存成功",
    "taskProcessed": "ファイルが提出されました",
    "taskProcessedMessage": "未完了タスクを処理しました：",
    "nextActivity": "次のアクティビティ：",
    "nextUser": "処理者：",
    "arrivedActivitys": "到達アクティビティ",
    "arrivedUsers": "到達処理者",
    "replace": "代",
    "next_etc": "等{count}人",

    "nextTaskMatrix": "可能な後続処理者: ",

    "processStarted": "ドキュメントが開始されました",
    "processStartedMessage": "新しい作業を開始しました:",

    "draftStart": "プロセスが開始されました",

    "taskCompleted": "未完了タスクが処理されました",
    "workCompleted": "ワークフローが完了しました",
    "arrivedActivity": "作業が次のアクティビティに到達しました：",
    "workProcess": "作業フローを続ける",
    "close": "閉じる",
    "retract": "取り消す",
    "reroute": "再割り当て",
    "rerouteTo": "再割り当て先",
    "rollback": "プロセスを巻き戻す",
    "rollbackTo": "プロセスを巻き戻す先",
    "selectRollbackActivity" : "ドキュメントを巻き戻す位置を選択してください：",
    "tryToProcess" : "そして処理を続行しようとしています",
    "in": "で",

    "andSoForth" : "など",

    "noIdentitySelectRange" : "選択範囲の身分が確定できません",
    "noIdentityDutySelectRange" : "選択範囲の職務が確定できません",
    "noUnitSelectRange" : "選択範囲の組織が確定できません",
    "noSelectRange": "選択範囲が確定できません",
    "noSelectType": "選択タイプが設定されていません",
    "selectRoute": "ルートを選択",
    "submitAt": "提出日時",
    "idea": "意見",
    "processing": "処理中",
    "comeTime": "到着時間",
    "begin": "開始",
    "end": "終了",
    "none": "なし",
    "empower": "権限付与",

    "person": "処理者",
    "department": "部署",
    "startTime": "受信時間",
    "completedTime": "処理時間",
    "route": "ルート",
    "opinion": "意見",

    "systemProcess": "システム処理",
    "showProcess": "プロセス表示",

    "deleteAttachmentTitle":"添付ファイル削除確認",
    "deleteAttachment": "選択した添付ファイルを削除しますか？",

    "sendTaskNotice" : "未完了の処理者に通知が送信されました：{users}",
    "setReadedConfirmContent" : "「{title}」を既読としてマークしますか？",
    "setReadedConfirmTitle" : "既読マーク確認",

    "replaceAttachmentTitle":"添付ファイルの置換確認",
    "replaceAttachment": "選択した添付ファイルを置換しますか？",
    "uploadMore": "最大で {n} 個の添付ファイルしかアップロードできません",
    "notValidation": "データ検証が失敗しました",
    "lineNotValidation": "行データ検証が失敗しました",
    "notValidation_number": "数字を入力してください",
    "notAttachmentValidation": "添付ファイルの検証が失敗しました",

    "retractTitle": "撤回確認",
    "retractText": "このファイルを撤回しますか？",
    "workRetract": "ファイルが撤回されました",
    "retractWorkInfor": "ファイルを撤回しました:",

    "currentActivity": "現在のアクティビティ：",
    "currentUser": "処理者：",

    "inputResetPeople": "リセットする対象を選択してください！",
    "resetTo": "次の対象にリセット",
    "reset": "リセット",
    "resetOk": "ドキュメントが次の対象にリセットされました",
    "workReset": "ドキュメントがリセットされました",
    "resetWorkInfor": "ドキュメントをリセットしました：",

    "workRollback": "ドキュメントがロールバックされました",
    "rollbackOk": "ドキュメントが次の対象にロールバックされました",
    "rollbackWorkInfor": "ドキュメントをロールバックしました：",

    "workReroute": "ドキュメントが再割り当てされました",
    "rerouteWorkInfor": "ドキュメントを再割り当てしました：",
    "rerouteOk": "ドキュメントが次の対象に再割り当てされました",

    "inputSplitValue": "ブランチを追加する基準値を入力または選択してください",
    "addSplitOk": "処理ブランチが追加されました：",
    "addSplitWork": "処理ブランチが追加されました",
    "addSplitWorkInfor": "現在の作業に処理ブランチを追加しました",

    "deleteWorkTitle": "ドキュメント削除確認",
    "deleteWorkText": {"html": "<div style='color: red;'>注意：このドキュメントを削除しようとしています。削除後、ドキュメントは復元できませんので、削除しますか？</div>", "text": "注意：このドキュメントを削除しようとしています。削除後、ドキュメントは復元できませんので、削除しますか？"},
    "workDelete": "ドキュメントが削除されました",
    "amount": "▌合計",
    "sectionAmount": "▌小計",
    "delete": "削除",
    "add": "追加",
    "addLine": "新しいエントリを追加",
    "edit": "編集",
    "completedEdit": "完了",
    "cancelEdit": "キャンセル",
    "mobileGridHelp": "データ領域を長押ししてデータを編集できます<br>左にスワイプするとデータを削除できます",
    "item": "▌エントリ",
    "all": "すべて",
    "imageClipper" : "画像編集",
    "noOrgObject": "一致するユーザーまたは組織がありません。クリックして変更できます",

    "menu_revisions_show": "変更履歴表示",
    "menu_revisions_hide": "変更履歴非表示",
    "menu_fullscreen": "フルスクリーンモード",
    "menu_toolbar_show": "ツールバー表示",
    "menu_toolbar_hide": "ツールバー非表示",
    "menu_preview": "印刷プレビュー",
    "menu_redfile": "赤い封筒",
    "menu_seal": "印鑑押印",
    "menu_showHistory": "履歴バージョンを表示",
    "menu_hideHistory": "履歴バージョンを閉じる",
    "menu_new": "新規文書作成",
    "menu_openfile": "ローカルファイルを開く",
    "menu_savefile": "ローカルに保存",
    "menu_att": "添付ファイル表示",
    "menu_file": "本文を開く",
    "completed": "終了",
    "openOfficeInfor": "{type} ファイルを開くには、ここをクリックしてください",
    "seeVersion" : "バージョンを表示",
    "selectVersionToRestore" : "復元する本文バージョンを選択してください：",
    "restoreFile" : "本文を復元",
    "installNTKOWebChromePluginNotice_xpi" : "まだNTKO Web Chromeクロスブラウザプラグインがインストールされていません。 <a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">ここをクリックしてインストール</a>してください。",
    "installNTKOWebChromePluginNotice_crx" : "まだNTKO Web Chromeクロスブラウザプラグインがインストールされていません。 <a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">ここをクリックしてインストール</a>してください。",

    "showReadCompletedTitle": "既読処理者",
    "showReadTitle": "未読者",
    "worklogRead": "未読を表示",
    "mediaOpinion_image": "手書き意見",
    "mediaOpinion_video": "ビデオ意見",
    "mediaOpinion_voice": "音声意見",

    "attachmentPermission": "添付ファイルの権限設定",
    "attachmentPermissionInfo": "以下の添付ファイルの権限を設定しています：",
    "attachmentRead": "この添付ファイルを表示およびダウンロードできる人：（空白の場合、この文書を読む権限があるすべてのユーザーが表示できます。空でない場合、編集と権限設定を同時に選択する必要があります）",
    "attachmentEdit": "この添付ファイルを編集できる人：（空白の場合、この文書を編集できるすべてのユーザーが編集できます。空でない場合、権限設定を同時に選択する必要があります）",
    "attachmentController": "この添付ファイルの権限を設定できる人：（空白の場合、この文書を編集できるすべてのユーザーが設定できます）",

    "attachmentOCRTitle": "画像から自動認識されたテキストを訂正",
    "attachmentOCR_saved": "画像テキスト認識結果が保存されました",

    "attachmentOrderTitle": "添付ファイルの並べ替え",
    "attachmentOrderUp": "上へ移動",
    "attachmentOrderDown": "下へ移動",
    "attachmentOrderInfo": "添付ファイルアイコンをドラッグアンドドロップするか、「上へ移動」と「下へ移動」ボタンを使用して添付ファイルを並べ替えます",

    "autosave": "自動保存文書",

    "ignore": "無視",
    "ANNInput": "スマート入力提案値：",

    "recover": "本文を復元",
    "notRecover": "本文の復元をキャンセル",

    "doublePage": "両面",
    "singlePage": "単ページ",
    "editdoc": "本文の編集",
    "editdocCompleted": "編集完了",
    "printdoc": "文書印刷",
    "history": "文書履歴確認",
    "handwrittenApproval": "手書き承認",
    "fullScreen": "フルスクリーン",
    "returnScreen": "元に戻す",

    "editdoc_mobile": "編集",
    "editdocCompleted_mobile": "編集完了",
    "printdoc_mobile": "印刷",
    "history_mobile": "履歴",
    "handwrittenApproval_mobile": "承認",


    "subformNestedError" : "このフォームには相互にネストされたサブフォームが存在します。管理者に連絡してください！",
    "subpageNestedError" : "このページに相互にネストされたサブページが存在します。管理者に連絡してください！",

    "subformUniqueError" : "このフォームは同じサブフォームを重複して埋め込みました。管理者に連絡してください！",
    "moduleUniqueError" : "このフォームに重複するフィールド名が存在します。管理者に連絡してください！",

    "selectEmpower" : "権限委任者の交換を選択",
    "empowerDlgText" : "次の人々が作業に権限を委任しました。選択すると、ファイルは委任された人に送信され、選択を解除するとファイルは委任者自身に送信されます。",
    "empowerTo" : "に権限を委任",
    "empowerToHtml" : "<font style='color:#ff5400;'>{person}</font>（{department}）が<font style='color:#ff5400;'>{empowerTo}</font>に権限を委任しました。（{time}）</font>",
    "autoFlowHtml" : "システムが自動的に提出しました：{time}",
    "systemSubmit": "システム自動処理",
    "selectAll" : "すべて選択",
    "computePage": "ページ計算中、お待ちください……",
    "keyLockTitle": "文書編集がロックされています",
    "keyLockInfor": "{name} が文書を編集中ですので、文書の内容を表示できます。後でページを更新して再試行できます。",

    "year" : "年",
    "month" : "月",
    "date" : "日",

    "documentEditor": {
        "copies": "",
		"secret": "",
		"priority": "",
		"redHeader": "文書見出し",
		"fileno": "[文書番号]",
		"signerTitle": "署名者：",
		"signer": "[署名者]",
		"subject": "[タイトル]",
		"mainSend": "[主要送付先：]",
		"filetext": "[ここに本文内容を編集してください]",
		"attachmentTitle": "添付ファイル：",
		"attachment": "[添付]",
		"issuanceUnit": "[発文機関]",
		"issuanceDate": "[作成日付]",
		"annotation": "",
		"copytoTitle": "CC：",
		"copyto": "[CC]",
		"editionUnit": "[配布機関]",
		"editionDate": "[配布日付]",
		"historyList": "過去のバージョン文書",
		"attachmentInfor": "[ここをクリックして添付ファイル内容を編集してください]"
    },
    "documentHistory": {
        "diffContent": "<div>{time}</div>{name}は\"{activity}\"で変更した内容",
		"insertContent": "<div>{time}</div>{name}は\"{activity}\"で挿入した内容：",
		"deleteContent": "<div>{time}</div>{name}は\"{activity}\"で削除した内容：",
		"insert": "挿入しました",
		"delete": "削除しました",
		"insertTimes": "挿入回数：{times}回",
		"deleteTimes": "削除回数：{times}回",
		"play": "変更履歴再生",
		"pause": "再生一時停止",
		"stop": "変更履歴再生停止",
		"next": "次の変更履歴",
		"prev": "前の変更履歴",
		"exit": "変更履歴審査終了",
		"diff_patch_count": "合計 {history} 件の過去バージョンがあり、{diff} 件の修正があります。",
		"original": "元のバージョン",
		"nodiff": "現在、修正情報はありません。",
		"word": "文字",
		"diff": "比較",
		"diffTitle": "前のバージョンと比較",
		"showAll": "すべての変更履歴を表示"
    },
    "subjectEmpty": "タイトルを入力してください",
    "issuanceUnitEmpty": "発文ユニットは空にできません",
    "fullWidth": "半角スペースを全角スペースに自動変換しました。半角スペースを入力するには、SHIFT+スペースを使用してください",
    "pauseWork": "現在の未処理業務は保留中です",
    "resumeWork": "現在の未処理業務は保留状態から再開しました",
    "resume": "再開",
    "pause": "保留",
    "selectItemCountNotice": "{count}以上を選択してください",
    "setReaded": "既読としてマーク",
    "readed": "既読",
    "attachmentArea": "添付ファイル領域",
    "intelligentCorrection": "スマート修正",
    "maxItemCountNotice": "最大{n}アイテムまで追加可能",
    "selectItemNotice": "アイテムを先に選択してください",
    "minItemNotice": "最低{n}アイテムを保持する必要があります。削除後のアイテム数が保持すべきアイテム数よりも少ないため、確認してください",
    "deleteSelectedItemNotice": "選択したアイテムを削除しますか？",
    "minItemCountNotice": "最低{n}アイテムを保持してください",
    "systemField": "システムフィールド",
    "systemFieldEmptyNotice": "システムフィールドは空にできません",
    "importTooManyNotice": "今回は{n1}件のデータをインポートしました。最大{n2}件のデータのみインポートできます",
    "importTooFewNotice": "今回は{n1}件のデータをインポートしました。最低{n2}件のデータを保持する必要があります",
    "pleaseSelect": "選択してください",

    "form": {
        "close": "閉じる",
		"closeTitle": "ドキュメントを閉じる",
		"save": "保存",
		"saveTitle": "ドキュメントを保存",
		"flow": "継続的なフロー",
		"flowTitle": "ドキュメントを継続的にフローにします",
		"reroute": "ルートを変更",
		"rerouteTitle": "ドキュメントをルートに再配置",
		"reset": "担当者をリセット",
		"resetTitle": "担当者をリセット",
		"split": "ブランチを追加",
		"splitTitle": "ブランチを追加",
		"retract": "取り下げる",
		"retractTitle": "未処理タスクを取り下げる",
		"rollback": "プロセスを巻き戻す",
		"rollbackTitle": "指定されたステップに巻き戻し、プロセス履歴を削除",
		"delete": "ドキュメントを削除",
		"deleteTitle": "ファイルを削除",
		"print": "印刷",
		"printTitle": "ドキュメントを印刷",
		"press": "処理を促す",
		"pressTitle": "処理を促す",
		"pause": "保留",
		"pauseTitle": "未処理タスクを一時停止",
		"resume": "保留の再開",
		"resumeTitle": "保留状態から再開",
		"downloadAll": "一括ダウンロード",
		"downloadAllTitle": "一括ダウンロード",
		"monitor": "プロセスモニタリング",
		"monitorTitle": "プロセスモニタリング",
		"addTask": "署名を追加",
		"addTaskTitle": "現在のアクティビティに処理者を追加",
		"goBack": "戻る",
		"goBackTitle": "すでに経過したアクティビティに戻る",
		"rerouteActivity": "ルート先：",
		"reroutePerson": "ルート先：",
		"selectPerson": "人を選択",
		"retouteOpinion": "再配置の意見：",
		"resetPerson": "リセット先：",
		"resetOpinion": "リセットの意見：",
		"keepTask": "私のタスクを保持",
		"readedOpinion": "読んだ意見",
		"setReaded": "読んだとマーク",
		"readed": "読んだ",
		"rollbackInfo": "ドキュメントを巻き戻す位置を選択してください",
		"addSplitInfo": "ビジネスに基づいて分岐データを設定します。ここで設定したデータはプロセスで設定した分岐の基準と一致する必要があります。<br/>複数の値は半角コンマ(,)で区切ってください。",
		"selectUnit": "組織または人物を選択",
		"excludeBranches": "既存の分岐を除外",
		"yes": "はい",
		"no": "いいえ",
		"readIdentity": "読む人",
		"sendReadNotify": "読む通知を送信",
		"reviewIdentity": "レビューする人",
		"noTaskToReset": "現在の作業にはあなたのタスクがありませんので、この操作を実行できません",
		"addTaskPerson": "タスクを追加する人",
		"addTaskOpinion": "意見",
		"addTaskBefore": "前に署名",
		"addTaskAfter": "後に署名",
		"addTaskBeforeTitle": "あなたが処理する前に処理者を追加",
		"addTaskAfterTitle": "あなたが処理した後に処理者を追加",
		"addTaskType": "署名タイプ",
		"goBackActivity": "アクティビティに戻る：",
		"goBackActivityWay": "戻る後の処理：",
		"goBackActivityWayStep": "プロセス標準の流れに従う",
		"goBackActivityWayJump": "戻る人に直接戻る",
        "goBackTo": "戻る：",
		"selectGoBackActivity": "戻るアクティビティを選択してください",
		"addTaskRepeatedTitle": "繰り返し署名のお知らせ",
		"addTaskRepeatedInfo": "<span class='mainColor_color'><b>{repeated}</b></span> は既に処理者リストに含まれているため、署名は行われません。"

    },

    "sendRead": "未読に送信",
    "sendReadOk": "未読に送信しました",
    "noPermissionOrWorkNotExisted": "権限がないか、作業が存在しません",
    "inputSendReadPeople": "未読の人を選択してください",
    "sendReadPeopleCanNotEmpty": "未読の人を空にすることはできません",

    "sendReview": "読み物を追加",
    "sendReviewOk": "読み物が既に追加されています",
    "inputSendReviewPeople": "読み物の人を選択してください",
    "sendReviewPeopleCanNotEmpty": "読み物の人は空にできません",
    "inputAddTaskPeople": "サイン人を選択してください",
    "addTaskOk": "サイン人が既に追加されています",
    "addTaskInfor": "ファイルにサインが追加されました",

    "applicationNotFound": "アプリが見つかりません",

    "pdfview" : {
        "nofile" : "ファイルがありません、アップロードしてください",
        "upload" : "アップロード"
    },
    "ofdview" : {
        "nofile" : "ファイルがありません、アップロードしてください",
        "upload" : "アップロード"
    },
    "onlyoffice" : {
        "noInstall" : "まずOnlyOfficeアプリをインストールしてください",
        "filetext" : "ファイルの内容"
    },
    "officeonline" : {
        "noInstall" : "まずOffice Onlineアプリをインストールしてください",
        "filetext" : "ファイルの内容"
    },
    "title": "タイトル",
    "createTime": "作成日時",
    "creatorPerson": "作成者",
    "creatorUnit": "作成組織",
    "score": "関連度",
    "updateTime": "更新日時",

    "documentType": "ドキュメントタイプ",
    "processName": "プロセス名",
    "draftTime": "起案日時",
    "draftPerson": "起案者",
    "categoryName": "カテゴリ",
    "publishPerson": "発行者",
    "publishTime": "発行日時",
    "document": "情報",
    "work": "ワーク",
    "cancelAssociatedTitle": "関連文書のキャンセル",
    "cancelAssociated": "ドキュメント「{title}」との関連をキャンセルしますか？",
    "associatedResult": "関連結果",
    "selectDocNote": "まず文書を選択してください",
    "associatedDocument": "関連文書",
    "docDeleted": "文書は既に削除されています。"

};
MWF.xApplication.process.Xform["lp."+o2.language] = MWF.xApplication.process.Xform.LP;
