MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xApplication.process.Xform.LP = {
    "ok": "확인",
    "deleteDatagridLineTitle": "항목 삭제 확인",
    "deleteDatagridLine": "현재 항목을 삭제하시겠습니까?",

    "cancelDatagridLineEditTitle": "데이터 그리드 편집 취소 확인",
    "cancelDatagridLineEdit": "데이터 그리드 편집을 취소하시겠습니까?",

    "datagridImport": "Excel 가져오기",
    "datagridExport": "Excel 내보내기",
    "exportDefaultName": "데이터 그리드",
    "datatemplateExportDefaultName": "데이터 템플릿",
    "datatableExportDefaultName": "데이터 테이블",
    "importSuccess": "가져오기 성공!",
    "validationInfor": "유효성 검사 정보",
    "importFail": "가져오기 실패",
    "importValidationColumnText": "제 {n} 열 :",
    "importValidationColumnTextExcel": "열 {n} :",
    "notValidNumber": "숫자가 아님",
    "notValidDate": "날짜 형식이 아님",
    "fullstop": "。",
    "notExistInSystem": "시스템에 존재하지 않음",
    "uploadedFilesCannotHaveSpaces": "업로드한 파일에는 공백이 포함될 수 없음",

    "browserNotActiveX": "사용 중인 브라우저는 ActiveX 컨트롤을 지원하지 않으므로 Office 컨트롤을 로드할 수 없습니다. IE 브라우저를 사용해 주세요.",

    "activity": "활동",
    "dataSaved": "데이터 저장 성공",
    "taskProcessed": "파일 제출됨",
    "taskProcessedMessage": "미결 작업을 처리했습니다:",
    "nextActivity": "다음 활동:",
    "nextUser": "처리자:",
    "arrivedActivitys": "도착한 활동",
    "arrivedUsers": "도착한 처리자",
    "replace": "대",
    "next_etc": " 및 {count}명",

    "nextTaskMatrix": "가능한 후속 처리자: ",

    "processStarted": "문서가 시작되었습니다",
    "processStartedMessage": "새로운 작업을 시작했습니다:",

    "draftStart": "프로세스가 시작되었습니다",

    "taskCompleted": "미결 작업이 처리되었습니다",
    "workCompleted": "작업 흐름이 완료되었습니다",
    "arrivedActivity": "작업이 다음 활동으로 도착했습니다:",
    "workProcess": "작업 흐름 계속",
    "close": "닫기",
    "retract": "철회",
    "reroute": "재배정",
    "rerouteTo": "재배정 대상",
    "rollback": "프로세스 롤백",
    "rollbackTo": "프로세스 롤백 대상",
    "selectRollbackActivity" : "문서를 롤백할 위치를 선택하세요:",
    "tryToProcess" : "그리고 계속 처리를 시도하세요",
    "in": "에서",

    "andSoForth" : "등",

    "noIdentitySelectRange" : "신분 선택 범위를 결정할 수 없습니다",
    "noIdentityDutySelectRange" : "직책 선택 범위를 결정할 수 없습니다",
    "noUnitSelectRange" : "조직 선택 범위를 결정할 수 없습니다",
    "noSelectRange": "선택 범위를 결정할 수 없습니다",
    "noSelectType": "선택 유형이 설정되지 않았습니다",
    "selectRoute": "경로 선택",
    "submitAt": "제출 일시",
    "idea": "의견",
    "processing": "처리 중",
    "comeTime": "도착 시간",
    "begin": "시작",
    "end": "종료",
    "none": "없음",
    "empower": "권한 부여",

    "person": "처리자",
    "department": "부서",
    "startTime": "수신 시간",
    "completedTime": "처리 시간",
    "route": "경로",
    "opinion": "의견",

    "systemProcess": "시스템 처리",
    "showProcess": "프로세스 표시",

    "deleteAttachmentTitle":"첨부 파일 삭제 확인",
    "deleteAttachment": "선택한 첨부 파일을 삭제하시겠습니까?",

    "sendTaskNotice" : "미결 처리자에게 알림을 보냈습니다: {users}",
    "setReadedConfirmContent" : "“{title}”을(를) 읽음으로 표시하시겠습니까?",
    "setReadedConfirmTitle" : "읽음으로 표시 확인",

    "replaceAttachmentTitle":"첨부 파일 교체 확인",
    "replaceAttachment": "선택한 첨부 파일을 교체하시겠습니까?",
    "uploadMore": "최대 {n}개의 첨부 파일만 업로드할 수 있습니다",
    "notValidation": "데이터 유효성 검사 실패",
    "lineNotValidation": "행 데이터 유효성 검사 실패",
    "notValidation_number": "숫자를 입력해야 합니다",
    "notAttachmentValidation": "첨부 파일 유효성 검사 실패",

    "retractTitle": "철회 확인",
    "retractText": "이 파일을 철회하시겠습니까?",
    "workRetract": "파일이 철회되었습니다",
    "retractWorkInfor": "파일을 철회했습니다:",

    "currentActivity": "현재 활동:",
    "currentUser": "처리자:",

    "inputResetPeople": "재설정할 대상을 선택하십시오!",
    "resetTo": "다음 대상으로 재설정",
    "reset": "재설정",
    "resetOk": "문서가 다음 대상으로 재설정되었습니다",
    "workReset": "문서가 재설정되었습니다",
    "resetWorkInfor": "문서를 재설정했습니다:",

    "workRollback": "문서가 롤백되었습니다",
    "rollbackOk": "문서가 다음 대상으로 롤백되었습니다",
    "rollbackWorkInfor": "문서를 롤백했습니다:",

    "workReroute": "문서가 재배정되었습니다",
    "rerouteWorkInfor": "문서를 재배정했습니다:",
    "rerouteOk": "문서가 다음 대상으로 재배정되었습니다",

    "inputSplitValue": "분기를 추가할 근거 값을 입력하거나 선택하십시오",
    "addSplitOk": "처리 분기가 추가되었습니다:",
    "addSplitWork": "처리 분기가 추가되었습니다",
    "addSplitWorkInfor": "현재 작업에 처리 분기를 추가했습니다",

    "deleteWorkTitle": "문서 삭제 확인",
    "deleteWorkText": {"html": "<div style='color: red;'>주의: 이 문서를 삭제하려고 합니다. 삭제 후 문서를 복구할 수 없으니 삭제하시겠습니까?</div>", "text": "주의: 이 문서를 삭제하려고 합니다. 삭제 후 문서를 복구할 수 없으니 삭제하시겠습니까?"},
    "workDelete": "문서가 삭제되었습니다",
    "amount": "▌총계",
    "sectionAmount": "▌소계",
    "delete": "삭제",
    "add": "추가",
    "addLine": "새 항목 추가",
    "edit": "편집",
    "completedEdit": "완료",
    "cancelEdit": "취소",
    "mobileGridHelp": "데이터 영역을 길게 눌러 데이터를 편집할 수 있습니다. 왼쪽으로 스와이프하여 데이터를 삭제할 수 있습니다.",
    "item": "▌항목",
    "all": "모두",
    "imageClipper" : "이미지 편집",
    "noOrgObject": "매치되는 사용자 또는 조직이 없습니다. 클릭하여 수정",

    "menu_revisions_show": "변경 내용 표시",
    "menu_revisions_hide": "변경 내용 숨기기",
    "menu_fullscreen": "전체 화면 모드",
    "menu_toolbar_show": "도구 모음 표시",
    "menu_toolbar_hide": "도구 모음 숨기기",
    "menu_preview": "인쇄 미리보기",
    "menu_redfile": "빨간 봉투",
    "menu_seal": "도장 찍기",
    "menu_showHistory": "버전 기록 보기",
    "menu_hideHistory": "버전 기록 닫기",
    "menu_new": "새 문서 생성",
    "menu_openfile": "로컬 파일 열기",
    "menu_savefile": "로컬에 저장",
    "menu_att": "첨부 파일 보기",
    "menu_file": "본문 열기",
    "completed": "완료",
    "openOfficeInfor": "{type} 파일을 열려면 여기를 클릭하세요",
    "seeVersion": "버전 보기",
    "selectVersionToRestore": "복원할 본문 버전을 선택하세요:",
    "restoreFile": "본문 복원",
    "installNTKOWebChromePluginNotice_xpi": "NTKO Web Chrome 크로스 브라우저 플러그인이 아직 설치되지 않았습니다. <a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">여기를 클릭하여 설치</a>하십시오.",
    "installNTKOWebChromePluginNotice_crx": "NTKO Web Chrome 크로스 브라우저 플러그인이 아직 설치되지 않았습니다. <a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">여기를 클릭하여 설치</a>하십시오.",

    "showReadCompletedTitle": "읽음 처리자",
    "showReadTitle": "대기 읽음자",
    "worklogRead": "대기 읽음 보기",
    "mediaOpinion_image": "손으로 쓴 의견",
    "mediaOpinion_video": "비디오 의견",
    "mediaOpinion_voice": "음성 의견",

    "attachmentPermission": "첨부 파일 권한 설정",
    "attachmentPermissionInfo": "다음 첨부 파일에 대한 권한을 설정 중입니다:",
    "attachmentRead": "이 첨부 파일을 볼 수 있는 사람:(공백인 경우이 문서를 읽을 수 있는 모든 사용자가 볼 수 있으며 비어 있지 않으면 편집 및 권한 설정을 동시에 선택해야 함)",
    "attachmentEdit": "이 첨부 파일을 편집할 수 있는 사람:(공백인 경우이 문서를 편집할 수 있는 모든 사용자가 편집할 수 있으며 비어 있지 않으면 권한 설정을 동시에 선택해야 함)",
    "attachmentController": "이 첨부 파일의 권한을 설정할 수 있는 사람:(공백인 경우 이 문서를 편집할 수 있는 모든 사용자가 설정할 수 있음)",

    "attachmentOCRTitle": "이미지에서 자동 인식된 텍스트 수정",
    "attachmentOCR_saved": "이미지 텍스트 인식 결과가 저장되었습니다",

    "attachmentOrderTitle": "첨부 파일 정렬",
    "attachmentOrderUp": "위로 이동",
    "attachmentOrderDown": "아래로 이동",
    "attachmentOrderInfo": "첨부 파일 아이콘을 드래그하거나 '위로 이동' 및 '아래로 이동' 버튼을 사용하여 첨부 파일을 정렬합니다",

    "autosave": "문서 자동 저장",

    "ignore": "무시",
    "ANNInput": "스마트 입력 제안 값:",

    "recover": "본문 복원",
    "notRecover": "본문 복원 취소",

    "doublePage": "이중 페이지",
    "singlePage": "단일 페이지",
    "editdoc": "문서 편집",
    "editdocCompleted": "편집 완료",
    "printdoc": "문서 인쇄",
    "history": "문서 이력 검토",
    "handwrittenApproval": "손글씨 승인",
    "fullScreen": "전체 화면",
    "returnScreen": "화면 복귀",

    "editdoc_mobile": "편집",
    "editdocCompleted_mobile": "편집 완료",
    "printdoc_mobile": "인쇄",
    "history_mobile": "이력",
    "handwrittenApproval_mobile": "승인",


    "subformNestedError" : "이 양식에 상호 중첩된 하위 양식이 있습니다. 관리자에게 문의하십시오!",
    "subpageNestedError" : "이 페이지에 상호 중첩된 하위 페이지가 있습니다. 관리자에게 문의하십시오!",

    "subformUniqueError" : "이 양식에서 동일한 하위 양식을 중복으로 삽입했습니다. 관리자에게 문의하십시오!",
    "moduleUniqueError" : "이 양식에 중복된 필드 이름이 있습니다. 관리자에게 문의하십시오!",

    "selectEmpower" : "권한 부여자 교체 선택",
    "empowerDlgText" : "다음 사람들이 작업을 승인했습니다. 선택하면 파일이 승인 받은 사람에게 전송되며, 선택 취소하면 승인자에게 전송됩니다.",
    "empowerTo" : "에게 권한 부여",
    "empowerToHtml" : "<font style='color:#ff5400;'>{person}</font>（{department}）님이 <font style='color:#ff5400;'>{empowerTo}</font> 에게 권한을 부여했습니다.（{time}）</font>",
    "autoFlowHtml" : "시스템이 자동으로 제출함: {time}",
    "systemSubmit": "시스템 자동 처리",
    "selectAll" : "모두 선택",
    "computePage": "페이지 계산 중, 잠시 기다려주십시오……",
    "keyLockTitle": "문서 편집이 잠겨 있습니다",
    "keyLockInfor": "{name} 님이 문서를 편집 중이므로 문서 내용을 볼 수 있습니다. 나중에 페이지를 새로 고침하여 다시 시도할 수 있습니다.",

    "year" : "년",
    "month" : "월",
    "date" : "일",

    "documentEditor": {
        "copies": "",
		"secret": "",
		"priority": "",
		"redHeader": "서류 레드헤더",
		"fileno": "[문서 번호]",
		"signerTitle": "서명자: ",
		"signer": "[서명자]",
		"subject": "[제목]",
		"mainSend": "[본송 부서: ]",
		"filetext": "[여기에 본문 내용을 편집하세요]",
		"attachmentTitle": "첨부 파일: ",
		"attachment": "[첨부]",
		"issuanceUnit": "[발송 기관]",
		"issuanceDate": "[작성 날짜]",
		"annotation": "",
		"copytoTitle": "참조: ",
		"copyto": "[참조]",
		"editionUnit": "[배포 기관]",
		"editionDate": "[배포 날짜]",
		"historyList": "이전 버전 문서",
		"attachmentInfor": "[여기를 클릭하여 첨부 파일 내용을 편집하세요]"
    },
    "documentHistory": {
        "diffContent": "<div>{time}</div>{name}님이 \"{activity}\"에서 수정한 내용",
		"insertContent": "<div>{time}</div>{name}님이 \"{activity}\"에서 삽입한 내용:",
		"deleteContent": "<div>{time}</div>{name}님이 \"{activity}\"에서 삭제한 내용:",
		"insert": "삽입",
		"delete": "삭제",
		"insertTimes": "삽입한 횟수: {times}번",
		"deleteTimes": "삭제한 횟수: {times}번",
		"play": "수정 기록 재생",
		"pause": "재생 일시 중지",
		"stop": "수정 기록 재생 중지",
		"next": "다음 수정 기록",
		"prev": "이전 수정 기록",
		"exit": "수정 기록 검토 종료",
		"diff_patch_count": "총 {history}개의 이전 버전이 있으며, {diff}개의 수정 사항이 있습니다.",
		"original": "원본 버전",
		"nodiff": "현재까지 수정된 내용이 없습니다.",
		"word": "글자",
		"diff": "비교",
		"diffTitle": "이전 버전과 비교",
		"showAll": "모든 수정 기록 표시"
    },
    "subjectEmpty": "제목을 입력하세요.",
    "issuanceUnitEmpty": "발송 기관을 입력하세요.",
    "fullWidth": "반각 공백이 전각 공백으로 자동 전환되었습니다. 반각 공백을 입력하려면 SHIFT+스페이스를 사용하세요.",
    "pauseWork": "현재 대기 업무가 일시 중단되었습니다.",
    "resumeWork": "현재 대기 업무가 일시 중단 상태에서 복원되었습니다.",
    "resume": "복원",
    "pause": "일시 중단",
    "selectItemCountNotice": "{count}개 이상 선택해야 합니다.",
    "setReaded": "읽음으로 표시",
    "readed": "읽음",
    "attachmentArea": "첨부 파일 영역",
    "intelligentCorrection": "지능형 교정",
    "maxItemCountNotice": "최대 {n}개 항목 추가가 허용됩니다.",
    "selectItemNotice": "먼저 항목을 선택하세요.",
    "minItemNotice": "{n}개 이상 항목을 보유해야 합니다. 삭제된 항목이 보유해야 하는 항목 수보다 적습니다. 확인하세요.",
    "deleteSelectedItemNotice": "선택한 항목을 삭제하시겠습니까?",
    "minItemCountNotice": "최소 {n}개 항목을 보유하세요.",
    "systemField": "시스템 필드",
    "systemFieldEmptyNotice": "시스템 필드는 비워 둘 수 없습니다.",
    "importTooManyNotice": "{n1}개 데이터를 가져왔습니다. 최대 {n2}개 데이터만 가져올 수 있습니다.",
    "importTooFewNotice": "{n1}개 데이터를 가져왔습니다. 최소 {n2}개 데이터를 보유해야 합니다.",
    "pleaseSelect": "선택하세요.",

    "form": {
        "close": "닫기",
		"closeTitle": "문서 닫기",
		"save": "저장",
		"saveTitle": "문서 저장",
		"flow": "계속 순환",
		"flowTitle": "문서 계속 순환",
		"reroute": "재배정",
		"rerouteTitle": "문서 재배정",
		"reset": "담당자 재설정",
		"resetTitle": "담당자 재설정",
		"split": "분기 추가",
		"splitTitle": "분기 추가",
		"retract": "철회",
		"retractTitle": "대기 업무 철회",
		"rollback": "프로세스 롤백",
		"rollbackTitle": "지정된 단계로 롤백하고 프로세스 기록 삭제",
		"delete": "문서 삭제",
		"deleteTitle": "파일 삭제",
		"print": "인쇄",
		"printTitle": "문서 인쇄",
		"press": "처리 요청",
		"pressTitle": "처리 요청",
		"pause": "대기",
		"pauseTitle": "대기 업무 일시 중단",
		"resume": "대기 중지 해제",
		"resumeTitle": "대기 중지 해제",
		"downloadAll": "일괄 다운로드",
		"downloadAllTitle": "일괄 다운로드",
		"monitor": "프로세스 모니터링",
		"monitorTitle": "프로세스 모니터링",
		"addTask": "추가 서명",
		"addTaskTitle": "현재 활동에 처리자 추가",
		"goBack": "반환",
		"goBackTitle": "이미 진행한 활동으로 반환",
		"rerouteActivity": "재배정할 위치:",
		"reroutePerson": "재배정 대상:",
		"selectPerson": "사람 선택",
		"retouteOpinion": "재배정 의견:",
		"resetPerson": "재설정 대상:",
		"resetOpinion": "재설정 의견:",
		"keepTask": "내 대기 업무 유지",
		"readedOpinion": "읽음 의견",
		"setReaded": "읽음으로 표시",
		"readed": "읽음",
		"rollbackInfo": "문서를 롤백할 위치를 선택하세요",
		"addSplitInfo": "비즈니스에 따라 분기 데이터를 설정합니다. 여기에 설정한 데이터는 프로세스에서 설정한 분기 기준과 일치해야 합니다.<br/>여러 값은 반각 콤마(,)로 구분됩니다.",
		"selectUnit": "조직 또는 사람 선택",
		"excludeBranches": "이미 있는 분기 제외",
		"yes": "예",
		"no": "아니요",
		"readIdentity": "대기 대상",
		"sendReadNotify": "대기 알림 전송",
		"reviewIdentity": "읽기 대상",
		"noTaskToReset": "현재 작업에는 당신의 대기 업무가 없으므로 이 작업을 수행할 수 없습니다.",
		"addTaskPerson": "서명자 추가",
		"addTaskOpinion": "의견",
		"addTaskBefore": "앞서 서명",
		"addTaskAfter": "뒤로 서명",
		"addTaskBeforeTitle": "당신이 처리하기 전에 처리자를 추가합니다",
		"addTaskAfterTitle": "당신이 처리한 후에 처리자를 추가합니다",
		"addTaskType": "서명 방법",
		"goBackActivity": "활동으로 반환:",
		"goBackActivityWay": "반환 후 처리:",
		"goBackActivityWayStep": "프로세스 표준 순환대로",
		"goBackActivityWayJump": "직접 반환자로",
        "goBackTo": "되돌아 가기：",
		"selectGoBackActivity": "되돌아 갈 활동을 선택하십시오.",
		"addTaskRepeatedTitle": "중복 서명 알림",
		"addTaskRepeatedInfo": "<span class='mainColor_color'><b>{repeated}</b></span> 이미 처리자 목록에 있으므로 서명을 추가하지 않습니다."

    },

    "sendRead": "미결자에게 보내기",
    "sendReadOk": "미결자에게 이미 보냈습니다",
    "noPermissionOrWorkNotExisted": "권한이 없거나 작업이 존재하지 않습니다",
    "inputSendReadPeople": "미결자를 선택하십시오",
    "sendReadPeopleCanNotEmpty": "미결자를 비워 둘 수 없습니다",

    "sendReview": "검토자 추가",
    "sendReviewOk": "검토자가 이미 추가되었습니다",
    "inputSendReviewPeople": "검토자를 선택하십시오",
    "sendReviewPeopleCanNotEmpty": "검토자를 비워 둘 수 없습니다",
    "inputAddTaskPeople": "가감서명자를 선택하십시오",
    "addTaskOk": "가감서명자가 이미 추가되었습니다",
    "addTaskInfor": "파일에 서명을 추가하였습니다.",

    "applicationNotFound": "앱을 찾을 수 없습니다",

    "pdfview" : {
        "nofile" : "파일 없음, 업로드하세요",
        "upload" : "업로드"
    },
    "ofdview" : {
        "nofile" : "파일 없음, 업로드하세요",
        "upload" : "업로드"
    },
    "onlyoffice" : {
        "noInstall" : "먼저 OnlyOffice 앱을 설치하십시오",
        "filetext" : "파일 내용"
    },
    "officeonline" : {
        "noInstall" : "먼저 Office Online 앱을 설치하십시오",
        "filetext" : "파일 내용"
    },
    "title": "제목",
    "createTime": "생성 시간",
    "creatorPerson": "작성자",
    "creatorUnit": "작성 조직",
    "score": "연관성",
    "updateTime": "업데이트 시간",

    "documentType": "문서 유형",
    "processName": "프로세스 이름",
    "draftTime": "작성 시간",
    "draftPerson": "작성자",
    "categoryName": "분류",
    "publishPerson": "발행자",
    "publishTime": "발행 시간",
    "document": "정보",
    "work": "작업",
    "cancelAssociatedTitle": "문서 연결 취소",
    "cancelAssociated": "문서 '{title}'와의 연결을 취소하시겠습니까?",
    "associatedResult": "연결 결과",
    "selectDocNote": "먼저 문서를 선택하십시오",
    "associatedDocument": "연결 문서",
    "docDeleted": "문서가 이미 삭제되었습니다."

};
MWF.xApplication.process.Xform["lp."+o2.language] = MWF.xApplication.process.Xform.LP;
