MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xApplication.process.Xform.LP = {
    "ok": "ຢືນຢັນ",
    "deleteDatagridLineTitle": "ຢືນຢັນລົບ item",
    "deleteDatagridLine": "ເຈົ້າແນ່ໃຈຫຼືບໍ່ຕ້ອງການລົບ item ປະຈຸບັນ？",

    "cancelDatagridLineEditTitle": "ຍົກເລີກການຢືນຢັນແກ້ໄຂຕາຕະລາງຂໍ້ມູນ",
    "cancelDatagridLineEdit": "ເຈົ້າແນ່ໃຈຫຼືບໍ່ວ່າຕ້ອງການຍົກເລີກການແກ້ໄຂຂໍ້ມູນ？",

    "datagridImport": "ນຳເຂົ້າ Excel",
    "datagridExport": "ນຳອອກExcel",
    "exportDefaultName": "ຂໍ້ມູນຕາຕະລາງ",
    "datatemplateExportDefaultName": "DataTemplate",
    "datatableExportDefaultName": "ຕາຕະລາງຂໍ້ມູນ",
    "importSuccess": "ນຳເຂົ້າສຳເລັດ！",
    "validationInfor": "ກວດສອບຂໍ້ມູນ",
    "importFail": "ນຳເຂົ້າລົ້ມເລວ",
    "importValidationColumnText": "ທີ່{n}ຖັນ：",
    "importValidationColumnTextExcel": "ຖັນ{n}：",
    "notValidNumber": "ບໍ່ແມ່ນຕົວເລກ",
    "notValidDate": "ບໍ່ແມ່ນຮູບແບບວັນທີ່",
    "fullstop": "。",
    "notExistInSystem": "ບໍ່ຢູ່ໃນລະບົບ",
    "uploadedFilesCannotHaveSpaces": "ອັບໂລດເອກະສານບໍ່ສາມາດເວັ້ນວາງໄດ້",

    "browserNotActiveX": "browser ຂອງເຈົ້າບໍ່ຮອງຮັບການຄອບຄຸມActiveX，ບໍ່ສາມາດໂຫລດຕົວຄອບຄຸມOffice，ກະລຸນາໃຊ້ Internet Explorer",

    "activity": "activity",
    "dataSaved": "ບັນທຶກຂໍ້ມູນສຳເລັດ",
    "taskProcessed": "ສົ່ງເອກະສານແລ້ວ",
    "taskProcessedMessage": "ເຈົ້າດຳເນີນການໜ້າທີ່ທີ່ຕ້ອງເຮັດ：",
    "nextActivity": "Activity ຖັດໄປ：",
    "nextUser": "ຄົນດຳເນີນການ：",
    "arrivedActivitys": "Activity ໄປທີ່",
    "arrivedUsers": "ຄົນດຳເນີນການໄປທີ່",
    "replace": "ແທນທີ່",
    "next_etc": "{count}ຄົນ",

    "nextTaskMatrix": "ຜູ້ຈັດການຕິດຕາມຄວາມເປັນໄປໄດ້: ",

    "processStarted": "ເອກະສານເລີ່ມຕົນແລ້ວ",
    "processStartedMessage": "ເຈົ້າເລີ່ມວຽກໃໝ່：",

    "draftStart": "ກະບວນການເລີ່ມຕົ້ນແລ້ວ",

    "taskCompleted": "ການດຳເນີນTask ",
    "workCompleted": "ໜ້າວຽກສຳເລັດແລ້ວ",
    "arrivedActivity": "ງານມາເຖິງactivityແລ້ວ：",
    "workProcess": "ສືບຕໍ່ຂະບວນການ",
    "close": "ປິດ",
    "retract": "ຖອນ",
    "reroute": "ກຳນົດເວລາ",
    "rerouteTo": "ກຳນົດເວລາທີ່",
    "rollback": "ດຳເນີນການຍ້ອນກັບ",
    "rollbackTo": "ດຳເນີນການຍ້ອນກັບໄປທີ່",
    "selectRollbackActivity": "ກະລຸນາເລືອກສະຖານທີ່ຈະຍ້ອນກັບໄປທີ່ເອກະສານ：",
    "tryToProcess": "ພະຍາຍາມຍືບຕໍ່ຂະບວນການ",
    "in": " in",

    "andSoForth": "ລໍຖ້າ",

    "noIdentitySelectRange": "ບໍ່ສາມາດລະບຸຂອບເຂດຕົວຕົນທີ່ເລືອກໄດ້",
    "noIdentityDutySelectRange": "ບໍ່ສາມາດກຳນົດຂອບເຂດຂອງເລືອກວຽກ",
    "noUnitSelectRange": "ບໍ່ສາມາດກຳນົດຂອບເຂດຂອງອົງກອນໄດ້",
    "noSelectRange": "ບໍ່ສາມາດກຳນົດຂອບເຂດທີ່ເລືອກໄດ້",
    "noSelectType": "ບໍ່ໄດ້ຕັ້ງຄ່າປະເພດການເລືອກ",
    "selectRoute": "ເລືອກເສັ້ນທາງ",
    "submitAt": "ຢືນຢັນທີ່",
    "idea": "ຄຳເຫັນ",
    "processing": "ກຳລັງດຳເນີນການ",
    "comeTime": "ເວລາໄປຮອດ",
    "begin": "ເລີ່ມ",
    "end": "ຈົບ",
    "none": "",
    "empower": "ອະນຸຍາດ",

    "person": "ຄົນດຳເນີນການ",
    "department": "ພະແນກ",
    "startTime": "ເວລາໄດ້ຮັບ",
    "completedTime": "ເວລາດຳເນີນການ",
    "route": "ເສັ້ນທາງ",
    "opinion": "ຄວາມຄິດເຫັນ",

    "systemProcess": "ການປະຜົນຂອງລະບົບ",
    "showProcess": "ສະແດງການດຳເນີນງານ",

    "deleteAttachmentTitle": "ຢືນຢັນລົບເອກະສານ",
    "deleteAttachment": "ຢືນຢັນຫຼືບໍ່ຕ້ອງການລົບເອກະສານທີ່ເຈົ້າເລືອກ？",

    "sendTaskNotice": "ແຈ້ງຄົນດຳເນີນການແລ້ວ：{users}, ສົ່ງການແຈ້ງເຕືອນແລ້ວ",
    "setReadedConfirmContent": "ເຈົ້າຕ້ອງການ“{title}”ເຄື່ອງໝາຍວ່າອ່ານແລ້ວ？",
    "setReadedConfirmTitle": "ຢືນຢັນເຄື່ອງໝາຍວ່າອ່ານແລ້ວ",

    "replaceAttachmentTitle": "ຢືນຢັນແທນທີ່ເອກະສານ",
    "replaceAttachment": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການຢືນຢັນແທນທີ່ເອກະສານ？",
    "uploadMore": "ເຈົ້າສາມາດອັດໂຫລດເອກະສານໄດ້ສູງສຸດ{n} ລາຍການ",
    "notValidation": "ການຢືນຢັນຂໍ້ມູນລົ້ມເລວ",
    "lineNotValidation": "ການກວດສອບຂໍ້ມູນແຖວລົ້ມເລວ",
    "notValidation_number": "ຕ້ອງຕື່ມຕົວເລກໃສ່",
    "notAttachmentValidation": "ກວດສອບເອກະສານລົ້ມເລວ。",

    "retractTitle": "ຢືນຢັນການຕັ້ງຄ່າໃໝ່",
    "retractText": "ຈົ້າຢືນຢັນຕ້ອງການຕັ້ງຄ່າເອກະສານໃໝ່ບໍ່？",
    "workRetract": "ຕັ້ງຄ່າເອກະສານແລ້ວ",
    "retractWorkInfor": "ເຈົ້າຕັ້ງຄ່າເອກະສານໃໝ່：",


    "currentActivity": "Activity ປະຈຸບັນ：",
    "currentUser": "ຄົນດຳເນີນການ：",

    "inputResetPeople": "ກະລຸນາເລືອກຄົນທີ່ເຈົ້າຕ້ອງການຕັ້ງຄ່າ！",
    "resetTo": "ຕັ້ງຄ່າໄປທີ່",
    "reset": "ຕັ້ງຄ່າໃໝ່",
    "resetOk": "ຕັ້ງຄ່າເອກະສານໃໝ່ໃຫ້",
    "workReset": "ຕັ້ງຄ່າເອກະສານໃໝ່ແລ້ວ",
    "resetWorkInfor": "ຕັ້ງຄ່າໃໝ່ເອກະສານຂອງເຈົ້າແລ້ວ：",

    "workRollback": "ເອກະສານໄດ້ຖືກຕີກັບແລ້ວ",
    "rollbackOk": "ເອກະສານໄດ້ຖືກຕີກັບໄປໃຫ້",
    "rollbackWorkInfor": "ເອກະສານຂອງເຈົ້າໄດ້ຖືກຕີກັບ：",

    "workReroute": "ເອກະສານໄດ້ກຳນົດເວລາແລ້ວ",
    "rerouteWorkInfor": "ເອກະສານຂອງເຈົ້າໄດ້ຖືກກຳນົດເວລາ：",
    "rerouteOk": "ເອກະສານໄດ້ຖືກກຳນົດເວລາແລ້ວ：",

    "inputSplitValue": "ກະລຸາຕື່ມຂໍ້ມູນ ຫຼື ເລືອກສຳລັບການເພີ່ມສາຂາ",
    "addSplitOk": "ກຳລັງດຳເນີນການເພີ່ມສາຂາແລ້ວ：",
    "addSplitWork": "ດຳເນີນການເພີ່ມສາຂາແລ້ວ",
    "addSplitWorkInfor": "ເຈົ້າມີການເພີ່ມສາຂາໃນໜ້າວຽກປະຈຸບັນ",

    "deleteWorkTitle": "ຢືນຢັນລົບເອກະສານ",
    "deleteWorkText": {
        "html": "<div style='color: red;'>ໝາຍເຫດ：ເຈົ້າກຳລັງລົບເອກະສານ，ຫຼັງຈາກເຈົ້າລົບເອກະສານແລ້ວບໍ່ສາມາດກູ້ຄືນໄດ້，ກະລຸນາຢືນຢັນວ່າເຈົ້າຕ້ອງການລົບ？</div>",
        "text": "ໝາຍເຫດ：ເຈົ້າກຳລັງລົບເອກະສານ，ຫຼັງຈາກເຈົ້າລົບເອກະສານແລ້ວບໍ່ສາມາດກູ້ຄືນໄດ້，ກະລຸນາຢືນຢັນວ່າເຈົ້າຕ້ອງການລົບ？"
    },
    "workDelete": "ລົບເອກະສານແລ້ວ",
    "amount": "ຜົນລວມ",
    "sectionAmount": "ຜົນລວມຍ່ອຍ",
    "delete": "ລົບ",
    "add": "ເພີ່ມ",
    "addLine": "ເພີ່ມເສັ້ນ",
    "edit": "ແກ້ໄຂ",
    "completedEdit": "ສຳເລັດ",
    "cancelEdit": "ຍົກເລີກ",
    "mobileGridHelp": "ກົດພື້ນທີ່ຄ້າງໄວ້ເພື່ອແກ້ໄຂຂໍ້ມູນ<br>ປັດຊ້າຍເພື່ອລົບຂໍ້ມູນ",
    "item": "Item",
    "all": "ທັງໝົດ",
    "imageClipper": "ແກ້ໄຂຮູບພາບ",
    "noOrgObject": "ບໍ່ມີຄົນຫຼືອົງກອນທີ່ຕົງກັນ，ຄິກເພື່ອແກ້ໄຂ",

    "menu_revisions_show": "ສະແດງຮ່ຶງຮອຍ",
    "menu_revisions_hide": "ເຊື່ອງຮ່ອງຮ່ອຍ",
    "menu_fullscreen": "ເຕັມໜ້າຈໍ",
    "menu_toolbar_show": "ສະແດງ Toolbar",
    "menu_toolbar_hide": "ເຊື່ອງ Toolbar",
    "menu_preview": "Print ຕົວຢ່າງ",
    "menu_redfile": "Red File",
    "menu_seal": "ປະທັບ",
    "menu_showHistory": "ເບິ່ງປະຫວັດ",
    "menu_hideHistory": "ປິດປະຫວັດ",
    "menu_new": "ສ້າງເອກະສານ",
    "menu_openfile": "ເປີດເອກະສາານ",
    "menu_savefile": "ບົນທຶກລົງໃນພື່້ນທີ່",
    "menu_att": "ກວດເບິ່ງເອກະສານ",
    "menu_file": "ເປີດ",
    "completed": "ສິ້ນສຸດ",
    "openOfficeInfor": "ຄິກທີ່ນີ້{type}ເພື່ອເປີດເອກະສານ",
    "seeVersion": "ເບິ່ງVersion ",
    "selectVersionToRestore": "ກະລຸນາເລືອກ Version ຂໍ້ຄວາມທີ່ຈະກູ້ຄືນ：",
    "restoreFile": "ກູ້ຄືນ",
    "installNTKOWebChromePluginNotice_xpi": "NTKO Web Chrome plugin ຍັງບໍ່ໄດ້ຕິດຕັ້ງ。ກະລຸນາຄິກ<a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">ຕິດຕັ້ງອົງປະກອບ</a>",
    "installNTKOWebChromePluginNotice_crx": "NTKO Web Chrome plugin ຍັງບໍ່ໄດ້ຕິດຕັ້ງ。ກະລຸນາຄິກ<a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">ຕິດຕັ້ງອົງປະກອ</a>",

    "showReadCompletedTitle": "ຄົນອ່ານແລ້ວ",
    "showReadTitle": "ອ່ານແລ້ວ",
    "worklogRead": "View read",
    "mediaOpinion_image": "ຄວາມຄິດເຫັນດ້ວຍລາຍມື",
    "mediaOpinion_video": "ຄວາມຄິດເຫັນດ້ວຍວີດີໂອ",
    "mediaOpinion_voice": "ຄວາມຄິດເຫັນດ້ວຍສຽງ",

    "attachmentPermission": "ຕັ້ງຄ່າອະນຸຍາດເອກະສານ",
    "attachmentPermissionInfo": "ເຈົ້າກຳລັງຕັ້ງຄ່າການອະນຸຍາດສຳລັບການຕິດຕາມເອກະສານ：",
    "attachmentRead": "ໃຜສາມາດເບິ່ງແລະດາວໂຫລດເອກະສານນີ້：(ວ່າງເປົ່າໝາຍຄວາມວ່າໃຜທີ່ໄດ້ຮັບການອະນຸຍາດສາມາດເບິ່ງເອກະສານໄດ້，ຫາກບໍ່ວ່າງເປົ່າເຈົ້າມີສິດທີ່ຈະເລືອກ ຫຼືຕັ້ງຄ່າ)",
    "attachmentEdit": "ໃຜທີ່ສາມາດແກ້ໄຂເອກະສານໄດ້：(ວ່າງເປົ່າໝາຍຄວາມວ່າໃຜທີ່ໄດ້ຮັບການອະນຸຍາດສາມາດເບິ່ງເອກະສານໄດ້，ຫາກບໍ່ວ່າງເປົ່າເຈົ້າມີສິດທີ່ຈະເລືອກ ຫຼືຕັ້ງຄ່າ)",
    "attachmentController": "ໃຜສາມາດຮັບອະນຸຍາດຕັ້ງຄ່າເອກະສານ：(ວ່າງເປົ່າໝາຍຄວາມວ່າໃຜທີ່ໄດ້ຮັບການອະນຸຍາດສາມາດແກ້ໄຂເອກະສານໄດ້)",

    "attachmentOCRTitle": "ແກ້ໄຂຂໍ້ຄວາມໃນຮູບພບໃຫ້ຖືກຕ້ອງແບບອັດຕະໂນມັດ",
    "attachmentOCR_saved": "ຜົນໄດ້ຮັບຈາກຂໍ້ຄວາມຮູບພາບໄດ້ຖືກບັນທຶກແລ້ວ",

    "attachmentOrderTitle": "ລຽນລຳດັບເອກະສານ",
    "attachmentOrderUp": "ຂຶ້ນ",
    "attachmentOrderDown": "ລົງ",
    "attachmentOrderInfo": "ດຶງ iconເອກະສານ，ຫຼືຜ່ານ“ລົງ”、“ລົງ”ປຸ່ມຈັດລຽນເອກະສານ",

    "autosave": "ບັນທຶກເອກະສານອັດຕະໂນມັດ",

    "ignore": "Ignore",
    "ANNInput": "ການປ້ອນຂໍ້ມູນກຳນົດຄ່າແບບອັດສະລິຍະ：",

    "recover": "ຮຽກຂໍ້ຄວາມຄືນ",
    "notRecover": "ຍົກເລີກການຮຽກຂໍ້ຄວາມຄືນ",

    "doublePage": "ສອງໜ້າ",
    "singlePage": "ໜ້າດຽວ",
    "editdoc": "ແກ້ໄຂຂໍ້ຄວມ",
    "editdocCompleted": "ແກ້ໄຂສຳເລັດ",
    "printdoc": "Print",
    "history": "ກວດສອບການຕິດຕາມຂໍ້ຄວາມ",
    "handwrittenApproval": "ລາຍເຊັນດ້ວຍລຍມື",
    "fullScreen": "ເຕັມຈໍ",
    "returnScreen": "ນ້ອຍລົງ",

    "editdoc_mobile": "ແກ້ໄຂ",
    "editdocCompleted_mobile": "ແກ້ໄຂສຳເລັດ",
    "printdoc_mobile": "Print",
    "history_mobile": "ຕິດຕາມ",
    "handwrittenApproval_mobile": "ລາຍເຊັນ",


    "subformNestedError": "ແບບຟອມນີ້ມີຟອມຍ່ອຍຊ້ອນກັນ，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ！",
    "subpageNestedError": "ໜ້ານີ້ມີໜ້າຍ່ອຍທັບຊ້ອນກັນ，，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ！",

    "subformUniqueError": "ມີແບບຟອມຊ້ອນທັບກັນ，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ！",
    "moduleUniqueError": "ມີຊ່ອງທີ່ມີຊື່ດຽວກັໃນແບບຟແມ，ກະລຸນາຕິດຕໍ່ຜູ້ດູແລລະບົບ！",

    "selectEmpower": "ການຄັດເລືອກເອົາພະນັກງານທີ່ມີອຳນາດ",
    "empowerDlgText": "ບຸກຄົນຕໍ່ໄປນີ້ໄດ້ຖືກອະນຸຍາດການເຮັດວຽກ，ເມື່ອເລືອກແລ້ວເອກະສາານຈະສົ່ງຕໍ່ໄປໃຫ້ບຸກຄົນທີ່ໄດ້ຮັບອະນຸຍາດ，ຍົກເລີກການເລືອກຫຼັງເອກະສານໄດ້ສົ່ງໄປຫາຄົນທີ່ໄດ້ຮັບອະນຸຍາດ",
    "empowerTo": "ອະນຸຍາດໃຫ້",
    "empowerToHtml": "<font style='color:#ff5400;'>{person}</font>（{department}）ອະນຸຍາດໃຫ້<font style='color:#ff5400;'>{empowerTo}</font>ດຳເນີນການ。（{time}）</font>",
    "autoFlowHtml": "ລະບົບຈະສົ່ງຂໍ້ມູນໄປທີ່：{time}",
    "systemSubmit": "ລະບົບຈັດການອັດຕະໂນມັດ",
    "selectAll": "ເລືອກທັງໝົດ",
    "computePage": "ກຳລັງຄຳນວນການແບ່ງໜ້າ，ກະລຸນາລໍຖາ……",
    "keyLockTitle": "ການແຂ້ໄຂເອກະສາານຖືກລັອກ",
    "keyLockInfor": "ເອກສານມາຈາກ {name} ດຳເນີນແກ້ໄຂ，ເຈົ້າສາມາດກວດສອບເນື້ອໃນເອກະສານ，ເຈົ້າສາມາດrefresh ໜ້ານີ້ແລ້ວລອງອີກຄັ້ງ。",

    "year": "ປີ",
    "month": "ເດືອນ",
    "date": "ມື້",

    "documentEditor": {
        "copies": "",
        "secret": "",
        "priority": "",
        "redHeader": "ເອກະສາານຫົວແດງ",
        "fileno": "[ເລກທີ]",
        "signerTitle": "ຜູ້ລົງນນາມ：",
        "signer": "[ຜູ້ລົງນາມ]",
        "subject": "[ຫົວຂໍ້]",
        "mainSend": "[ໜວ່ຍສົ່ງຫຼັກ：]",
        "filetext": "[ກະລຸນາແກ້ໄຂເນື້ອໃນເອກະສານ]",
        "attachmentTitle": "ເອກະສານ：",
        "attachment": "[ເອກະສນ]",
        "issuanceUnit": "[ສຳນັກພິມ]",
        "issuanceDate": "[ວັນທີຂຽນ]",
        "annotation": "",
        "copytoTitle": "ສຳເນົາເຖິງCC：",
        "copyto": "[ສຳເນົາເຖິງCC]",
        "editionUnit": "[ເຄື່ອງພິມ]",
        "editionDate": "[ວັນທີພິມ]",
        "historyList": "ປະຫັວດເອກສານ",
        "attachmentInfor": "[ກົດທີ່ນີ້ເພື່ອແກ້ໄຂເອກະສານ]"
    },
    "documentHistory": {
        "diffContent": "<div>{time}</div>{name} 在 ”{activity}“ ເວລາແກ້ໄຂເນື້ອໃນ",
        "insertContent": "<div>{time}</div>{name} 在 ”{activity}“ ເວລາເພີ່ມເນື້ອໃນ:",
        "deleteContent": "<div>{time}</div>{name} 在 ”{activity}“ ເວລາລົບເນື້ອໃນ:",
        "insert": "ເພີ່ມແລ້ວ",
        "delete": "ລົບແລ້ວ",
        "insertTimes": "ເພີ່ມແລ້ວ {times} ຄັ້ງ",
        "deleteTimes": "ລົບແລ້ວ {times} ຄັ້ງ",
        "play": "ຫຼິ້ນ",
        "pause": "ຢຸດ",
        "stop": "ຢຸດເພື່ອແກ້ໄຂກນບັນທຶກ",
        "next": "ບັນທຶກການປ່ຽນແປງຕໍ່ໄປ",
        "prev": "ຍ້ອນກັບບັນທຶກການປ່ຽນແປງ",
        "exit": "ອອກການຕິດຕາມທວນຄືນ",
        "diff_patch_count": "ທັງໝົດ{history}versions，{diff}ປັບປຸງ。",
        "original": "Version ເດີມ",
        "nodiff": "ໃນປະຈຸບັນບໍ່ມີປະຫັວດຂໍ້ມູນການດັດແກ້",
        "word": "ຄຳ",
        "diff": "ປຽບທຽບ",
        "diffTitle": "ປຽບທຽບກັບລຸ້ນກ່ອນໜ້ານິ",
        "showAll": "ສະແດງປະຫວັດທັງໝົດ"
    },
    "subjectEmpty": "ຫົວຂໍ້ບໍ່ສາມາດເວັ້ນວ່າງໄດ້",
    "issuanceUnitEmpty": "ໜ່ວຍອອກເອກະສນບໍ່ສາມາດວ່າງໄດ້",
    "fullWidth": "ເປີດໃຊ້ງານເຄິ່ງຊອງວ່າເປັນຊ່ອງວ່າງເຕັມແບບອັດຕະໂນມັດ，ຖ້າເຈົ້າຕ້ອງການປ້ອນຊ່ອງວ່າງເຄິ່ງ，ກະລຸນາ：SHIFT+space",

    "pauseWork": "ສິ່ງທີ່ຕ້ອງເຮັດປະຈຸບັນເຂົ້າສູ່ສະຖານະດຳເນີນການ",
    "resumeWork": "ສິ່ງທີ່ຕ້ອງເຮັດປະຈຸບັນສືບຕໍ່ເຮັດວຽກ",

    "resume": "ສົ່ງຄືນ",
    "pause": "Pending",

    "selectItemCountNotice": "ກະລຸນາເລືອກນ້ອຍສຸດ{count}ລາຍການ",
    "setReaded": "ຕິກເຄື່ອງໝາຍອ່ານ",
    "readed": "ອ່ານແລ້ວ",

    "attachmentArea": "ເອກະສານ",
    "intelligentCorrection": "ແກ້ໄຂຂໍ້ຜິດພາດແບບອັດສະລິຍະ",

    "maxItemCountNotice": "ເພີ່ມໄດ້ຫຼາຍສຸດ{n}ລາຍການ",
    "selectItemNotice": "ກະລຸນາເລືອກitem ",
    "minItemNotice": "ເກັບຮັກສາໄວ້ໜ້ອຍສຸດ{n}ລາຍການ，ລາຍການທີ່ລົບມີນ້ອຍກວ່າຫຼາຍການທີ່ເກັບຮັກສາໄວ້，ກະລຸນາກວດກາ",
    "deleteSelectedItemNotice": "ຢືນຢັນລົບລາຍການທີ່ເລືອກ",
    "minItemCountNotice": "ກະລຸນາເກັບໄວ້ນ້ອຍສຸດ{n}ລາຍການ",
    "systemField": "System Field",
    "systemFieldEmptyNotice": "System Field ບໍ່ສາມາດເວັ້ນວ່າງໄດ້",
    "importTooManyNotice": "ນຳເຂົ້າ{n1}ຂໍ້ມູນ，ນຳເຂົ້າໄດ້ຫຼາຍສຸດ{n2}ຂໍ້ມູນ",
    "importTooFewNotice": "ນຳເຂົ້າ{n1}ຂໍ້ມູນ，ເກັບຮັກສາໄດ້ນ້ອຍສຸດ{n2}ຂໍ້ມູນ",

    "pleaseSelect": "ກະລຸນາເລືອກ",

    "form": {
        "close": "ປິດ",
        "closeTitle": "ປິດເອກະສານ",
        "save": "ບັນທຶກ",
        "saveTitle": "ບັນທຶກເອກະສານ",
        "flow": "ດຳເນີນການຕໍ່",
        "flowTitle": "ດຳເນີນເອກະສານຕໍ່",
        "reroute": "ກຳນົດເວລາ",
        "rerouteTitle": "ກຳນົດເວລາເອກະສານ",
        "reset": "ຕັ້ງຄ່າຜູ້ດຳເນີນການ",
        "resetTitle": "ຕັ້ງຄ່າຜູ້ດຳເນີນການ",
        "split": "ເພີ່ມສາຂາ",
        "splitTitle": "ເພີ່ມສາຂາແຍກ",
        "retract": "ຖອນ",
        "retractTitle": "ຍັງຢູ່ລະຫວ່າງການຖອນ",
        "rollback": "ຂະບວນການຍ້ອນກັບ",
        "rollbackTitle": "ກັບໄປລິ້ງທີ່ລະບຸ，ບໍ່ມີການເກັບບັນທຶກຂະບວນການ",
        "delete": "ລົບເອກະສານ",
        "deleteTitle": "ລົບເອກະສນ",
        "print": "Print",
        "printTitle": "Print ເອກະສານ",
        "press": "ແຈ້ງເຕືອນການຈັດການ",
        "pressTitle": "ແຈ້ງເຕືອນການຈັດການ",
        "pause": "Pending",
        "pauseTitle": "Set the task as pending",
        "resume": "ກັບຄືນ",
        "resumeTitle": "ສືບຕໍ່ສະຖານະທີ່ຖືກລະງັບໄວ້",
        "downloadAll": "ດາວໂຫລດ",
        "downloadAllTitle": "ດາວໂຫລດ",
        "monitor": "ການກວດສອບຂະບວນການ",
        "monitorTitle": "ການກວດສອບຂະບວນການ",
        "addTask": "ເພີ່ມລາຍເຊັ່ນ",
        "addTaskTitle": "ເພີ່ມກນຈັດການໃຫ້ກັບກິດຈະກຳປະຈຸບັນ",

        "goBack": "ສົ່ງກັບ",
        "goBackTitle": "ສົ່ງກັບໄປທີ່ກິດຈະກຳທີ່ຜ່ານມາ",

        "rerouteActivity": "ກຳນົດເວລາທີ່：",
        "reroutePerson": "ກຳນົດເວລາໃຫ້：",
        "selectPerson": "ເລືອກພະນັກງານ",
        "retouteOpinion": "ກຳນົດເວລາຄວາມຄິດເຫັນ：",

        "resetPerson": "ຕັ້ງຄ່າໃຫ້：",
        "resetOpinion": "ຕັ້ງຄ່າຄວາມຄິດເຫັນ：",
        "keepTask": "ເັກບຮັກສາ my task",

        "readedOpinion": "ອ່ານຄວາມຄິດເຫັນ",

        "setReaded": "ເຄື່ອງໝາຍວອ່ານ",
        "readed": "ອ່ານແລ້ວ",

        "rollbackInfo": "ກະລຸນາເລືອກສະຖານທີ່ຂອງຟາຍທີ່ຈະສົ່ງກັບໄປທີ່",
        "addSplitInfo": "ແຍກຂໍ້ມູນໂດຍອີງຕາມຕັ້ງຄ່າທຸລະກິດ，ຂໍ້ມູນຄວານຕົງກັບການຕັ້ງຄ່າໃນຂະບວນການ。<br/>ກະລຸນາແບ່ງຄ່າຫຼາຍຄ່າດ້ວຍ(,)",
        "selectUnit": "ເລືອກອົງກອນຫຼືພະນັກງານ",
        "excludeBranches": "ບໍ່ລວມສາຂາທີ່ມີຢູ່",
        "yes": "ແມ່ນ",
        "no": "ບໍ່",

        "readIdentity": "ຄົນອ່ານ",
        "sendReadNotify": "ສົ່ງແຈ້ງເຕືອນໄປເຖິງຜູ້ອ່ານ",

        "reviewIdentity": "ຄົນອ່ານ",
        "noTaskToReset": "ປະຈຸບັນບໍ່ມີວຽກທີ່ຄ້າງຢູ່ສຳລັບເຈົ້າ，ບໍ່ສາມາດດຳເນີນການໄດ້",

        "addTaskPerson": "ຄົນເຊັ່ນ",
        "addTaskOpinion": "ຍອມຮັບ",
        "addTaskBefore": "ເຊັນກ່ອນ",
        "addTaskAfter": "ເຊັນຫຼັງ",
        "addTaskBeforeTitle": "ເພີ່ມການຈັດການກ່ອນທີ່ເຈົ້າຈະດຳເນີນການ",
        "addTaskAfterTitle": "ເພີ່ມຄົນຈັດການຫຼັງຈາກທີ່ເຈົ້າຈັດການ",
        "addTaskType": "ວິທີລົງນາມ",

        "goBackActivity": "ສົ່ງກັບໄປທີ່ກິດຈະກຳ：",
        "goBackActivityWay": "ສົ່ງກັບຫຼັງດຳເນີນການ：",

        "goBackActivityWayStep": "ດຳເນີນປົກກະຕິຕາມຂະບວນການ",
        "goBackActivityWayJump": "ສົ່ງຄືນໄປທີ່ຜູ້ສົ່ງ",
        "goBackTo": "ສົ່ງກັບໄປທີ່：",

        "selectGoBackActivity": "ກະລຸນາເລືອກກິດຈະກຳທີ່ຈະສົ່ງກັບ",


        "addTaskRepeatedTitle": "ແຈ້ງເຕືອນເພີ່ມລາຍເຊັນ",
        "addTaskRepeatedInfo": "<span class='mainColor_color'><b>{repeated}</b></span> ຢູ່ໃນລຍຊື່ຜູ້ດຳເນີນການແລ້ວ，ມັນຈະບໍ່ຖືກເຊັນ。"

    },

    "sendRead": "ສົ່ງໃຫ້ອ່ານ",
    "sendReadOk": "ສົ່ງໄປເຖິງຜູ້ອ່ານແລ້ວ",
    "noPermissionOrWorkNotExisted": "ເຈົ້າບໍ່ມີການອະນຸຍາດ ຫຼື ບໍ່ມີວຽກຢູ່ທີ່ນີ້",
    "inputSendReadPeople": "ເພີ່ມຄົນອ່ານ",
    "sendReadPeopleCanNotEmpty": "ຄົນອ່ານບໍາສາມາດເວັ້ນວ່າງໄດ້",

    "sendReview": "ເພີ່ມຄົນອ່ານ",
    "sendReviewOk": "ເພີ່ມຄົນອ່ານແລ້ວ",
    "inputSendReviewPeople": "ກະລຸນາເລືອກຄົນອ່ານ",
    "sendReviewPeopleCanNotEmpty": "ຄົນອ່ານບໍ່ສາມາດເວັ້ນວ່າງໄດ້",
    "inputAddTaskPeople": "ກະລຸນາເລືອກຄົນເຊັ່ນ",
    "addTaskOk": "ໂຫລດຄົນເຊັ່ນເພີ່ມ",
    "addTaskInfor": "ເຈົ້າເພີ່ມລາຍເຊັ່ນ：",

    "applicationNotFound": "ບໍ່ພົບ Application",

    "pdfview": {
        "nofile": "ຍັງບໍ່ມີຟາຍ，ກະລຸນາອັບໂຫລດ",
        "upload": "ອັບໂຫລດ"
    },
    "ofdview": {
        "nofile": "ຍັງບໍ່ມີຟາຍ，ກະລຸນາອັບໂຫລດ",
        "upload": "ອັບໂຫລດ"
    },
    "onlyoffice": {
        "noInstall": "ກະລຸນາຕິດຕັ້ງກ່ອນonlyofficeApplication",
        "filetext": "ຟາຍຂໍ້ຄວາມ"
    },
    "officeonline": {
        "noInstall": "ກະລຸນາຕິດຕັ້ງກ່ອນofficeonline​ Application",
        "filetext": "ຟາຍຂໍ້ຄວາມ"
    },
    "title": "ຫົວຂໍ້",
    "createTime": "ສ້າງເວລາ",
    "creatorPerson": "ສ້າງຄົນ",
    "creatorUnit": "ສ້າງອົງກອນ",
    "score": "ລະດັບຄວາມສຳພັນ",
    "updateTime": "ອັບເດດເວລາ",

    "documentType": "ປະເພດເອກະສານ",
    "processName": "ຊື່ຂະບວນການ",
    "draftTime": "ເວລາຮ່າງ",
    "draftPerson": "ຄົນຮ່າງ",
    "categoryName": "ປະເພດ",
    "publishPerson": "ຄົນເຜີຍແຜ່",
    "publishTime": "ເວລາເຜີຍແຜ່",
    "document": "ຂໍ້ຄວາມ",
    "work": "ວຽກ",
    "cancelAssociatedTitle": "ຍົກເລີກຄວາມສຳພັນເອກະສາານ",
    "cancelAssociated": "ແນ່ໃຈວ່າຕ້ອງການຍົກເລີກຄວາມສຳພັນ“{title}”ກັບເອກະສານ?",
    "associatedResult": "ຜົນລັບ",
    "selectDocNote": "ກະລຸນາເລືອກເອກະສານ",
    "associatedDocument": "ເອກະສານສຳພັນ",
    "docDeleted": "ລົບເອກະສານແລ້ວ。"

};
MWF.xApplication.process.Xform["lp." + o2.language] = MWF.xApplication.process.Xform.LP;
