MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xApplication.process.Xform.LP = {
    "ok": "确定",
	"deleteDatagridLineTitle":"删除条目确认",
    "deleteDatagridLine": "是否确定要删除当前条目？",

    "cancelDatagridLineEditTitle" : "取消编辑数据网格确认",
    "cancelDatagridLineEdit" : "是否确定取消编辑数据网格？",

    "datagridImport" : "导入Excel",
    "datagridExport" : "导出Excel",
    "exportDefaultName" : "数据网格",
    "datatemplateExportDefaultName": "数据模板",
    "datatableExportDefaultName": "数据表格",
    "importSuccess" : "导入成功！",
    "validationInfor" : "校验信息",
    "importFail" : "导入失败",
    "importValidationColumnText" : "第{n}列：",
    "importValidationColumnTextExcel" : "列{n}：",
    "notValidNumber" : "不是数字",
    "notValidDate" : "不是日期格式",
    "fullstop" : "。",
    "notExistInSystem" : "在系统中不存在",
    "uploadedFilesCannotHaveSpaces" : "上传的文件不能带空格",

    "browserNotActiveX": "您的浏览器不支持ActiveX控件，不能加载Office控件，请使用IE浏览器",

    "activity": "活动",
    "dataSaved": "数据保存成功",
    "taskProcessed": "文件已提交",
    "taskProcessedMessage": "您处理了一个待办任务：",
    "nextActivity": "下一个活动：",
    "nextUser": "处理人：",
    "arrivedActivitys": "到达活动",
    "arrivedUsers": "到达处理人",
    "replace": "代",
    "next_etc": "等{count}人",

    "processStarted": "文件已启动",
    "processStartedMessage": "您启动了一个新的工作：",

    "draftStart": "流程已启动",

    "taskCompleted": "待办已处理",
    "workCompleted": "工作流转已完成",
    "arrivedActivity": "工作已到达活动：",
    "workProcess": "继续流转",
    "close": "关闭",
    "retract": "撤回",
    "reroute": "调度",
    "rerouteTo": "调度到",
    "rollback": "流程回溯",
    "rollbackTo": "流程回溯到",
    "selectRollbackActivity" : "请选择文件要回溯到的位置：",
    "tryToProcess" : "并尝试继续流转",
    "in": "在",

    "andSoForth" : "等",

    "noIdentitySelectRange" : "无法确定身份的选择范围",
    "noIdentityDutySelectRange" : "无法确定职务的选择范围",
    "noUnitSelectRange" : "无法确定组织的选择范围",
    "noSelectRange": "无法确定选择范围",
    "noSelectType": "未设置选择类型",
    "selectRoute": "选择路由",
    "submitAt": "提交于",
    "idea": "意见",
    "processing": "正在处理",
    "comeTime": "到达时间",
    "begin": "起",
    "end": "止",
    "none": "无",
    "empower": "授权",

    "person": "处理人",
    "department": "部门",
    "startTime": "收到时间",
    "completedTime": "处理时间",
    "route": "路由",
    "opinion": "意见",

    "systemProcess": "系统处理",
    "showProcess": "显示流程图",

    "deleteAttachmentTitle":"删除附件确认",
    "deleteAttachment": "是否确定要删除您选中的附件？",

    "sendTaskNotice" : "已经向待办人：{users}, 发送了提醒",
    "setReadedConfirmContent" : "您确定要将“{title}”标记为已阅吗？",
    "setReadedConfirmTitle" : "标记已阅确认",

    "replaceAttachmentTitle":"替换附件确认",
    "replaceAttachment": "是否确定要替换您选中的附件？",
    "uploadMore": "您最多只允许上传 {n} 个附件",
    "notValidation": "数据校验未通过",
    "notValidation_number": "必须输入数字",

    "retractTitle": "撤回确认",
    "retractText": "您确认要撤回此文件吗？",
    "workRetract": "文件已撤回",
    "retractWorkInfor": "您撤回了文件：",


    "currentActivity": "当前活动：",
    "currentUser": "处理人：",

    "inputResetPeople": "请选择要重置给的人员！",
    "resetTo": "重置给",
    "reset": "重置",
    "resetOk": "文件已重置给",
    "workReset": "文件已重置",
    "resetWorkInfor": "您重置了文件：",

    "workRollback": "文件已回溯",
    "rollbackOk": "文件已回溯给",
    "rollbackWorkInfor": "您回溯了文件：",

    "workReroute": "文件已调度",
    "rerouteWorkInfor": "您调度了文件：",
    "rerouteOk": "文件已调度到：",

    "inputSplitValue": "请输入或选择增加分支的依据值",
    "addSplitOk": "已经增加处理分支：",
    "addSplitWork": "已经增加处理分支",
    "addSplitWorkInfor": "您已为当前工作增加了分支",

    "deleteWorkTitle": "删除文件确认",
    "deleteWorkText": {"html": "<div style='color: red;'>注意：您正在删除此文档，删除后文档无法找回，请您确认要删除此文件吗？</div>", "text": "注意：您正在删除此文档，删除后文档无法找回，请您确认要删除此文件吗？"},
    "workDelete": "已经删除文件",
    "amount": "▌总计",
    "delete": "删除",
    "add": "新增",
    "addLine": "添加新条目",
    "edit": "编辑",
    "completedEdit": "完成",
    "cancelEdit": "取消",
    "mobileGridHelp": "长按数据区域可编辑数据<br>向左滑动可以删除数据",
    "item": "▌条目",
    "all": "全部",
    "imageClipper" : "图片编辑",
    "noOrgObject": "未匹配人员或组织，点击可修改",

    "menu_revisions_show": "显示痕迹",
    "menu_revisions_hide": "隐藏痕迹",
    "menu_fullscreen": "全屏模式",
    "menu_toolbar_show": "显示工具栏",
    "menu_toolbar_hide": "隐藏工具栏",
    "menu_preview": "打印预览",
    "menu_redfile": "套红",
    "menu_seal": "盖章",
    "menu_showHistory": "查看历史版本",
    "menu_hideHistory": "关闭历史版本",
    "menu_new": "新建文档",
    "menu_openfile": "打开本地文件",
    "menu_savefile": "保存到本地",
    "menu_att": "查看附件",
    "menu_file": "打开正文",
    "completed": "结束",
    "openOfficeInfor": "点击此处打开{type}文件",
    "seeVersion" : "查看版本",
    "selectVersionToRestore" : "请选择要恢复的正文版本：",
    "restoreFile" : "恢复正文",
    "installNTKOWebChromePluginNotice_xpi" : "尚未安装NTKO Web Chrome跨浏览器插件。请点击<a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">安装组件</a>",
    "installNTKOWebChromePluginNotice_crx" : "尚未安装NTKO Web Chrome跨浏览器插件。请点击<a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">安装组件</a>",

    "showReadCompletedTitle": "已阅人",
    "showReadTitle": "待阅人",
    "worklogRead": "查看待阅",
    "mediaOpinion_image": "手写意见",
    "mediaOpinion_video": "视频意见",
    "mediaOpinion_voice": "语音意见",

    "attachmentPermission": "设置附件权限",
    "attachmentPermissionInfo": "您正在为以下附件设置权限：",
    "attachmentRead": "谁可以查看和下载此附件：(为空表示有权限阅读此文档的人都可以)",
    "attachmentEdit": "谁可以编辑此附件：(为空表示有权限编辑此文档的人都可以)",
    "attachmentController": "谁可以设置此附件的权限：(为空表示有权限编辑此文档的人都可以)",

    "attachmentOCRTitle": "纠正自动识别的图片中的文字",
    "attachmentOCR_saved": "图像文字识别结果已保存",

    "attachmentOrderTitle": "附件排序",
    "attachmentOrderUp": "上移",
    "attachmentOrderDown": "下移",
    "attachmentOrderInfo": "拖动附件图标，或通过“下移”、“下移”按钮对附件进行排序",

    "autosave": "自动保存文档",

    "ignore": "忽略",
    "ANNInput": "智能输入建议值：",

    "recover": "恢复正文",
    "notRecover": "取消正文恢复",

    "doublePage": "双页",
    "singlePage": "单页",
    "editdoc": "编辑正文",
    "editdocCompleted": "编辑完成",
    "printdoc": "打印正文",
    "history": "正文痕迹审查",
    "fullScreen": "全屏",
    "returnScreen": "还原",

    "editdoc_mobile": "编辑",
    "editdocCompleted_mobile": "编辑完成",
    "printdoc_mobile": "打印",
    "history_mobile": "痕迹",


    "subformNestedError" : "该表单存在相互嵌套的子表单，请联系管理员！",
    "subpageNestedError" : "该页面存在相互嵌套的子页面，请联系管理员！",

    "subformUniqueError" : "该表单重复嵌入了同一子表单，请联系管理员！",
    "moduleUniqueError" : "该表单存在重名的字段，请联系管理员！",

    "selectEmpower" : "授权人员替换选择",
    "empowerDlgText" : "下列人员对工作进行了授权，选择后文件将发送给被授权人，取消选择后文件将发送给授权者本人",
    "empowerTo" : "授权给",
    "empowerToHtml" : "<font style='color:#ff5400;'>{person}</font>（{department}）授权给<font style='color:#ff5400;'>{empowerTo}</font>处理。（{time}）</font>",
    "selectAll" : "全选",
    "computePage": "正在计算分页，请稍候……",
    "keyLockTitle": "文件编辑已锁定",
    "keyLockInfor": "文件正由 {name} 编辑处理，您可以查看文件内容，稍后可刷新页面重试。",

    "year" : "年",
    "month" : "月",
    "date" : "日",

    "documentEditor": {
        "copies": "",
        "secret":"",
        "priority": "",
        "redHeader": "文件红头",
        "fileno":"[文号]",
        "signerTitle": "签发人：",
        "signer": "[签发人]",
        "subject": "[标题]",
        "mainSend": "[主送单位：]",
        "filetext": "[请在此处编辑正文内容]",
        "attachmentTitle":"附件：",
        "attachment":"[附件]",
        "issuanceUnit":"[发文机关]",
        "issuanceDate":"[成文日期]",
        "annotation":"",
        "copytoTitle":"抄送：",
        "copyto":"[抄送]",
        "editionUnit":"[印发机关]",
        "editionDate":"[印发日期]",
        "historyList": "历史版本文档"
    },
    "documentHistory": {
        "diffContent": "<div>{time}</div>{name} 在 ”{activity}“ 时修改的内容",
        "insertContent": "<div>{time}</div>{name} 在 ”{activity}“ 时插入的内容:",
        "deleteContent": "<div>{time}</div>{name} 在 ”{activity}“ 时删除的内容:",
        "insert": "插入了",
        "delete": "删除了",
        "insertTimes": "插入了 {times} 处",
        "deleteTimes": "删除了 {times} 处",
        "play": "修改记录回放",
        "pause": "暂停回放",
        "stop": "停止修改记录回放",
        "next": "下一个修改记录",
        "prev": "上一个修改记录",
        "exit": "退出痕迹审查",
        "diff_patch_count": "共有{history}个历史版本，{diff}处修订。",
        "original": "原始版本",
        "nodiff": "目前还没有历史修改信息",
        "word": "字",
        "diff": "对比",
        "diffTitle": "与上一版本对比"
    },
    "subjectEmpty": "标题不能为空",
    "issuanceUnitEmpty": "发文单位不能为空",
    "fullWidth": "已启用半角空格自动转换为全角空格，如需输入半角空格，请使用：SHIFT+空格",

    "pauseWork": "当前待办已进入挂起状态",
    "resumeWork": "当前待办已从挂起状态中恢复",

    "resume": "挂起恢复",
    "pause": "挂起",

    "selectItemCountNotice" : "请至少选择{count}项",
    "setReaded" : "标记为已阅",
    "readed" : "已阅",

    "attachmentArea": "附件区域",
    "intelligentCorrection" : "智能纠错",

    "maxItemCountNotice": "最多允许添加{n}项",
    "selectItemNotice": "请先选择条目",
    "minItemNotice": "最少需要保留{n}项，删除后的条目小于需保留的条目，请检查",
    "deleteSelectedItemNotice": "确定要删除选中的条目",
    "minItemCountNotice": "请最少保留{n}项",
    "systemField": "系统字段",
    "systemFieldEmptyNotice": "系统字段不能为空",
    "importTooManyNotice": "本次导入了{n1}条数据，最多允许导入{n2}条数据",
    "importTooFewNotice": "本次导入了{n1}条数据，最少需要保留{n2}条数据",

    "form": {
        "close":"关闭",
        "closeTitle": "关闭文档",
        "save": "保存",
        "saveTitle": "保存文档",
        "flow": "继续流转",
        "flowTitle": "继续流转文档",
        "reroute": "调度",
        "rerouteTitle": "调度文档",
        "reset": "重置处理人",
        "resetTitle": "重置处理人",
        "split": "增加分支",
        "splitTitle": "增加拆分分支",
        "retract": "撤回",
        "retractTitle": "待办撤回",
        "rollback": "流程回溯",
        "rollbackTitle": "回溯到指定的环节，不保留流程记录",
        "delete": "删除文档",
        "deleteTitle": "删除文件",
        "print": "打印",
        "printTitle": "打印文档",
        "press": "催促办理",
        "pressTitle": "催促办理",
        "pause": "挂起",
        "pauseTitle": "待办挂起",
        "resume": "挂起恢复",
        "resumeTitle": "从挂起状态恢复",
        "downloadAll": "一键下载",
        "downloadAllTitle": "一键下载",

        "rerouteActivity": "调度到：",
        "reroutePerson": "调度给：",
        "selectPerson": "选择人员",
        "retouteOpinion": "调度意见：",

        "resetPerson": "重置给：",
        "resetOpinion": "重置意见：",
        "keepTask": "保留我的待办",

        "readedOpinion": "阅读意见",

        "rollbackInfo": "请选择文件要回溯到的位置",
        "addSplitInfo": "根据您的业务设置拆分数据，此处设置的数据应与流程中设置的拆分依据匹配。<br/>多个值请用半角逗号(,)分隔",
        "selectUnit": "选择组织或人员",
        "excludeBranches": "排除已有分支",
        "yes": "是",
        "no": "否"
    }
};
MWF.xApplication.process.Xform["lp."+o2.language] = MWF.xApplication.process.Xform.LP;
