MWF.xApplication.process.Xform.LP = {
    "ok": "确定",
	"deleteDatagridLineTitle":"删除条目确认",
    "deleteDatagridLine": "是否确定要删除当前条目？",
    "browserNotActiveX": "您的浏览器不支持ActiveX控件，不能加载Office控件，请使用IE浏览器",

    "dataSaved": "数据保存成功",
    "taskProcessed": "文件已提交",
    "taskProcessedMessage": "您处理了一个待办任务：",
    "nextActivity": "下一个活动：",
    "nextUser": "处理人：",
    "workCompleted": "文件流转完成",
    "workProcess": "继续流转",
    "close": "关闭",

    "noSelectRange": "无法确定选择范围",
    "noSelectType": "未设置选择类型",
    "selectRoute": "选择路由",
    "submitAt": "提交于",
    "idea": "意见",
    "processing": "正在处理",
    "comeTime": "到达时间",
    "begin": "起",
    "end": "止",
    "none": "无",

    "person": "处理人",
    "department": "部门",
    "startTime": "收到时间",
    "completedTime": "处理时间",
    "route": "路由",
    "opinion": "意见",

    "systemProcess": "系统处理",
    "showProcess": "显示流程图",

    "deleteAttachmentTitle":"删除附件确认",
    "deleteAttachment": "是否确定要删除您选中的附件？",

    "replaceAttachmentTitle":"替换附件确认",
    "replaceAttachment": "是否确定要替换您选中的附件？",
    "uploadMore": "您最多只允许上传 {n} 个附件",
    "notValidation": "数据校验未通过",
    "notValidation_number": "必须输入数字",

    "retractTitle": "撤回确认",
    "retractText": "您确认要撤回此文件吗？",
    "workRetract": "文件已撤回",
    "retractWorkInfor": "您撤回了文件：",


    "currentActivity": "当前活动：",
    "currentUser": "处理人：",

    "inputResetPeople": "请选择要重置给的人员！",
    "resetTo": "重置给",
    "reset": "重置",
    "resetOk": "文件已重置给",
    "workReset": "文件已重置",
    "resetWorkInfor": "您重置了文件：",

    "workRollback": "文件已回溯",
    "rollbackOk": "文件已回溯给",
    "rollbackWorkInfor": "您回溯了文件：",

    "workReroute": "文件已调度",
    "rerouteWorkInfor": "您调度了文件：",
    "rerouteOk": "文件已调度到：",

    "inputSplitValue": "请输入或选择增加分支的依据值",
    "addSplitOk": "已经增加处理分支：",
    "addSplitWork": "已经增加处理分支",
    "addSplitWorkInfor": "您已为当前工作增加了分支",

    "deleteWorkTitle": "删除文件确认",
    "deleteWorkText": {"html": "<div style='color: red;'>注意：您正在删除此文档，删除后文档无法找回，请您确认要删除此文件吗？</div>", "text": "注意：您正在删除此文档，删除后文档无法找回，请您确认要删除此文件吗？"},
    "workDelete": "已经删除文件",
    "amount": "▌总计",
    "delete": "删除",
    "add": "新增",
    "addLine": "添加新条目",
    "edit": "编辑",
    "completedEdit": "完成",
    "mobileGridHelp": "长按数据区域可编辑数据<br>向左滑动可以删除数据",
    "item": "▌条目",
    "all": "全部",
    "imageClipper" : "图片编辑",
    "noOrgObject": "未匹配人员或组织，点击可修改",

    "menu_revisions_show": "显示痕迹",
    "menu_revisions_hide": "隐藏痕迹",
    "menu_fullscreen": "全屏模式",
    "menu_toolbar_show": "显示工具栏",
    "menu_toolbar_hide": "隐藏工具栏",
    "menu_preview": "打印预览",
    "menu_redfile": "套红",
    "menu_seal": "盖章",
    "menu_showHistory": "查看历史版本",
    "menu_hideHistory": "关闭历史版本",
    "menu_new": "新建文档",
    "menu_openfile": "打开本地文件",
    "menu_savefile": "保存到本地",
    "menu_att": "查看附件",
    "menu_file": "打开正文",
    "completed": "结束",
    "openOfficeInfor": "点击此处打开{type}文件",

    "showReadCompletedTitle": "已阅人",
    "showReadTitle": "待阅人",
    "worklogRead": "查看待阅",
    "mediaOpinion_image": "手写意见",
    "mediaOpinion_video": "视频意见",
    "mediaOpinion_voice": "语音意见",

    "attachmentPermission": "设置附件权限",
    "attachmentPermissionInfo": "您正在为以下附件设置权限：",
    "attachmentRead": "谁可以查看和下载此附件：(为空表示有权限阅读此文档的人都可以)",
    "attachmentEdit": "谁可以编辑此附件：(为空表示有权限编辑此文档的人都可以)",
    "attachmentController": "谁可以设置此附件的权限：(为空表示有权限编辑此文档的人都可以)",

    "attachmentOCRTitle": "纠正自动识别的图片中的文字",
    "attachmentOCR_saved": "图像文字识别结果已保存",

    "autosave": "自动保存文档",

    "ignore": "忽略",
    "ANNInput": "智能输入建议值：",

    "recover": "恢复正文",
    "notRecover": "取消正文恢复",

    "doublePage": "多页",
    "singlePage": "单页",
    "editdoc": "编辑正文",
    "editdocCompleted": "编辑完成",

    "subformNestedError" : "该表单存在相互嵌套的子表单，请联系管理员！",
    "subpageNestedError" : "该页面存在相互嵌套的子页面，请联系管理员！",

    "subformUniqueError" : "该表单重复嵌入了同一子表单，请联系管理员！",
    "moduleUniqueError" : "该表单存在重名的字段，请联系管理员！",

    "documentEditor": {
        "copies": "",
        "secret":"",
        "priority": "",
        "redHeader": "文件红头",
        "fileno":"[文号]",
        "signerTitle": "签发人：",
        "signer": "[签发人]",
        "subject": "[标题]",
        "mainSend": "[主送单位：]",
        "filetext": "[请在此处编辑正文内容]",
        "attachmentTitle":"附件：",
        "attachment":"[附件]",
        "issuanceUnit":"[发文机关]",
        "issuanceDate":"[成文日期]",
        "annotation":"",
        "copytoTitle":"抄送：",
        "copyto":"[抄送]",
        "editionUnit":"[印发机关]",
        "editionDate":"[印发日期]"
    }

};