MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xApplication.process.Xform.LP = {
    "ok": "確定",
    "deleteDatagridLineTitle": "刪除項目確認",
    "deleteDatagridLine": "是否確定要刪除當前項目？",

    "cancelDatagridLineEditTitle": "取消編輯數據網格確認",
    "cancelDatagridLineEdit": "是否確定取消編輯數據網格？",

    "datagridImport": "導入Excel",
    "datagridExport": "導出Excel",
    "exportDefaultName": "數據網格",
    "datatemplateExportDefaultName": "數據模板",
    "datatableExportDefaultName": "數據表格",
    "importSuccess": "導入成功！",
    "validationInfor": "驗證信息",
    "importFail": "導入失敗",
    "importValidationColumnText": "第{n}列：",
    "importValidationColumnTextExcel": "列{n}：",
    "notValidNumber": "不是數字",
    "notValidDate": "不是日期格式",
    "fullstop": "。",
    "notExistInSystem": "在系統中不存在",
    "uploadedFilesCannotHaveSpaces": "上傳的文件不能帶空格",

    "browserNotActiveX": "您的瀏覽器不支持ActiveX控件，不能加載Office控件，請使用IE瀏覽器",

    "activity": "活動",
    "dataSaved": "數據保存成功",
    "taskProcessed": "文件已提交",
    "taskProcessedMessage": "您處理了一個待辦任務：",
    "nextActivity": "下一個活動：",
    "nextUser": "處理人：",
    "arrivedActivitys": "到達活動",
    "arrivedUsers": "到達處理人",
    "replace": "代",
    "next_etc": "等{count}人",

    "nextTaskMatrix": "可能的後續處理人: ",

    "processStarted": "文件已啟動",
    "processStartedMessage": "您啟動了一個新的工作：",

    "draftStart": "流程已啟動",

    "taskCompleted": "待辦已處理",
    "workCompleted": "工作流轉已完成",
    "arrivedActivity": "工作已到達活動：",
    "workProcess": "繼續流轉",
    "close": "關閉",
    "retract": "撤回",
    "reroute": "調度",
    "rerouteTo": "調度到",
    "rollback": "流程回溯",
    "rollbackTo": "流程回溯到",
    "selectRollbackActivity" : "請選擇文件要回溯到的位置：",
    "tryToProcess" : "並嘗試繼續流轉",
    "in": "在",

    "andSoForth" : "等",

    "noIdentitySelectRange" : "無法確定身份的選擇範圍",
    "noIdentityDutySelectRange" : "無法確定職務的選擇範圍",
    "noUnitSelectRange" : "無法確定組織的選擇範圍",
    "noSelectRange": "無法確定選擇範圍",
    "noSelectType": "未設置選擇類型",
    "selectRoute": "選擇路由",
    "submitAt": "提交於",
    "idea": "意見",
    "processing": "處理中",
    "comeTime": "到達時間",
    "begin": "起",
    "end": "止",
    "none": "無",
    "empower": "授權",

    "person": "處理人",
    "department": "部門",
    "startTime": "收到時間",
    "completedTime": "處理時間",
    "route": "路由",
    "opinion": "意見",

    "systemProcess": "系統處理",
    "showProcess": "顯示流程圖",

    "deleteAttachmentTitle":"刪除附件確認",
    "deleteAttachment": "是否確定要刪除您選中的附件？",

    "sendTaskNotice" : "已經向待辦人：{users}, 發送了提醒",
    "setReadedConfirmContent" : "您確定要將“{title}”標記為已閱嗎？",
    "setReadedConfirmTitle" : "標記已閱確認",

    "replaceAttachmentTitle":"替換附件確認",
    "replaceAttachment": "是否確定要替換您選中的附件？",
    "uploadMore": "您最多只允許上傳 {n} 個附件",
    "notValidation": "數據校驗未通過",
    "lineNotValidation": "行數據校驗未通過",
    "notValidation_number": "必須輸入數字",
    "notAttachmentValidation": "附件校驗未通過",

    "retractTitle": "撤回確認",
    "retractText": "您確認要撤回此文件嗎？",
    "workRetract": "文件已撤回",
    "retractWorkInfor": "您撤回了文件：",

    "currentActivity": "當前活動：",
    "currentUser": "處理人：",

    "inputResetPeople": "請選擇要重置的人員！",
    "resetTo": "重置給",
    "reset": "重置",
    "resetOk": "文件已經重置給",
    "workReset": "文件已重置",
    "resetWorkInfor": "您重置了文件：",

    "workRollback": "文件已回溯",
    "rollbackOk": "文件已回溯給",
    "rollbackWorkInfor": "您回溯了文件：",

    "workReroute": "文件已調度",
    "rerouteWorkInfor": "您調度了文件：",
    "rerouteOk": "文件已調度到：",

    "inputSplitValue": "請輸入或選擇增加分支的依據值",
    "addSplitOk": "已經增加處理分支：",
    "addSplitWork": "已經增加處理分支",
    "addSplitWorkInfor": "您已為當前工作增加了分支",

    "deleteWorkTitle": "刪除文件確認",
    "deleteWorkText": {"html": "<div style='color: red;'>注意：您正在刪除此文件，刪除後文件無法找回，請您確認要刪除此文件嗎？</div>", "text": "注意：您正在刪除此文件，刪除後文件無法找回，請您確認要刪除此文件嗎？"},
    "workDelete": "已經刪除文件",
    "amount": "▌總計",
    "sectionAmount": "▌小計",
    "delete": "刪除",
    "add": "新增",
    "addLine": "添加新條目",
    "edit": "編輯",
    "completedEdit": "完成",
    "cancelEdit": "取消",
    "mobileGridHelp": "長按數據區域可編輯數據<br>向左滑動可以刪除數據",
    "item": "▌條目",
    "all": "全部",
    "imageClipper" : "圖片編輯",
    "noOrgObject": "未匹配使用者或組織，點擊可修改",

    "menu_revisions_show": "顯示痕跡",
    "menu_revisions_hide": "隱藏痕跡",
    "menu_fullscreen": "全屏模式",
    "menu_toolbar_show": "顯示工具欄",
    "menu_toolbar_hide": "隱藏工具欄",
    "menu_preview": "打印預覽",
    "menu_redfile": "套紅",
    "menu_seal": "蓋章",
    "menu_showHistory": "查看歷史版本",
    "menu_hideHistory": "關閉歷史版本",
    "menu_new": "新建文檔",
    "menu_openfile": "打開本地文件",
    "menu_savefile": "保存到本地",
    "menu_att": "查看附件",
    "menu_file": "打開正文",
    "completed": "結束",
    "openOfficeInfor": "點擊此處打開{type}文件",
    "seeVersion" : "查看版本",
    "selectVersionToRestore" : "請選擇要恢復的正文版本：",
    "restoreFile" : "恢復正文",
    "installNTKOWebChromePluginNotice_xpi" : "尚未安裝NTKO Web Chrome跨瀏覽器插件。請點擊<a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">安裝組件</a>",
    "installNTKOWebChromePluginNotice_crx" : "尚未安裝NTKO Web Chrome跨瀏覽器插件。請點擊<a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">安裝組件</a>",

    "showReadCompletedTitle": "已讀處理人",
    "showReadTitle": "待讀人",
    "worklogRead": "查看待讀",
    "mediaOpinion_image": "手寫意見",
    "mediaOpinion_video": "視頻意見",
    "mediaOpinion_voice": "語音意見",

    "attachmentPermission": "設置附件權限",
    "attachmentPermissionInfo": "您正在設置以下附件的權限：",
    "attachmentRead": "誰可以查看和下載此附件：（留空表示有權閱讀此文檔的人都可以，不留空需要同時選擇編輯和設置權限）",
    "attachmentEdit": "誰可以編輯此附件：（留空表示有權編輯此文檔的人都可以，不留空需要同時選擇設置權限）",
    "attachmentController": "誰可以設置此附件的權限：（留空表示有權編輯此文檔的人都可以）",

    "attachmentOCRTitle": "更正自動識別圖片中的文字",
    "attachmentOCR_saved": "圖片文字識別結果已保存",

    "attachmentOrderTitle": "附件排序",
    "attachmentOrderUp": "上移",
    "attachmentOrderDown": "下移",
    "attachmentOrderInfo": "拖動附件圖標，或通過“上移”和“下移”按鈕對附件進行排序",

    "autosave": "自動保存文檔",

    "ignore": "忽略",
    "ANNInput": "智能輸入建議值：",

    "recover": "恢復正文",
    "notRecover": "取消正文恢復",

    "doublePage": "雙頁",
    "singlePage": "單頁",
    "editdoc": "編輯正文",
    "editdocCompleted": "編輯完成",
    "printdoc": "列印正文",
    "history": "正文痕跡審查",
    "handwrittenApproval": "手寫簽批",
    "fullScreen": "全屏",
    "returnScreen": "還原",

    "editdoc_mobile": "編輯",
    "editdocCompleted_mobile": "編輯完成",
    "printdoc_mobile": "列印",
    "history_mobile": "痕跡",
    "handwrittenApproval_mobile": "簽批",


    "subformNestedError" : "該表單存在相互嵌套的子表單，請聯繫管理員！",
    "subpageNestedError" : "該頁面存在相互嵌套的子頁面，請聯繫管理員！",

    "subformUniqueError" : "該表單重複嵌入了同一子表單，請聯繫管理員！",
    "moduleUniqueError" : "該表單存在重名的字段，請聯繫管理員！",

    "selectEmpower" : "授權人員替換選擇",
    "empowerDlgText" : "下列人員對工作進行了授權，選擇後文件將發送給被授權人，取消選擇後文件將發送給授權者本人",
    "empowerTo" : "授權給",
    "empowerToHtml" : "<font style='color:#ff5400;'>{person}</font>（{department}）授權給<font style='color:#ff5400;'>{empowerTo}</font>處理。（{time}）</font>",
    "autoFlowHtml" : "系統自動提交於：{time}",
    "systemSubmit": "系統自動處理",
    "selectAll" : "全選",
    "computePage": "正在計算分頁，請稍候……",
    "keyLockTitle": "文件編輯已鎖定",
    "keyLockInfor": "文件正由 {name} 編輯處理，您可以查看文件內容，稍後可刷新頁面重試。",

    "year" : "年",
    "month" : "月",
    "date" : "日",

    "documentEditor": {
        "copies": "",
		"secret": "",
		"priority": "",
		"redHeader": "文件紅頭",
		"fileno": "[文號]",
		"signerTitle": "簽發人：",
		"signer": "[簽發人]",
		"subject": "[標題]",
		"mainSend": "[主送單位：]",
		"filetext": "[請在此處編輯正文內容]",
		"attachmentTitle": "附件：",
		"attachment": "[附件]",
		"issuanceUnit": "[發文機關]",
		"issuanceDate": "[成文日期]",
		"annotation": "",
		"copytoTitle": "抄送：",
		"copyto": "[抄送]",
		"editionUnit": "[印發機關]",
		"editionDate": "[印發日期]",
		"historyList": "歷史版本文檔",
		"attachmentInfor": "[點擊此處編輯附件內容]"
    },
    "documentHistory": {
        "diffContent": "<div>{time}</div>{name} 在 \"{activity}\" 時修改的內容",
		"insertContent": "<div>{time}</div>{name} 在 \"{activity}\" 時插入的內容:",
		"deleteContent": "<div>{time}</div>{name} 在 \"{activity}\" 時刪除的內容:",
		"insert": "插入了",
		"delete": "刪除了",
		"insertTimes": "插入了 {times} 處",
		"deleteTimes": "刪除了 {times} 處",
		"play": "修改記錄回放",
		"pause": "暫停回放",
		"stop": "停止修改記錄回放",
		"next": "下一個修改記錄",
		"prev": "上一個修改記錄",
		"exit": "退出痕跡審查",
		"diff_patch_count": "共有 {history} 個歷史版本，{diff} 處修訂。",
		"original": "原始版本",
		"nodiff": "目前還沒有歷史修改信息",
		"word": "字",
		"diff": "對比",
		"diffTitle": "與上一版本對比",
		"showAll": "顯示所有痕跡"
    },
    "subjectEmpty": "標題不能為空",
    "issuanceUnitEmpty": "發文單位不能為空",
    "fullWidth": "已啟用半角空格自動轉換為全角空格，如需輸入半角空格，請使用：SHIFT+空格",
    "pauseWork": "當前待辦已進入掛起狀態",
    "resumeWork": "當前待辦已從掛起狀態中恢復",
    "resume": "恢復",
    "pause": "掛起",
    "selectItemCountNotice": "請至少選擇 {count} 項",
    "setReaded": "標記為已閱",
    "readed": "已閱",
    "attachmentArea": "附件區域",
    "intelligentCorrection": "智能校正",
    "maxItemCountNotice": "最多允許添加 {n} 項",
    "selectItemNotice": "請先選擇條目",
    "minItemNotice": "最少需要保留 {n} 項，刪除後的條目數小於需保留的條目數，請檢查",
    "deleteSelectedItemNotice": "確定要刪除所選條目",
    "minItemCountNotice": "請最少保留 {n} 項",
    "systemField": "系統字段",
    "systemFieldEmptyNotice": "系統字段不能為空",
    "importTooManyNotice": "本次導入了 {n1} 條數據，最多允許導入 {n2} 條數據",
    "importTooFewNotice": "本次導入了 {n1} 條數據，最少需要保留 {n2} 條數據",
    "pleaseSelect": "請選擇",

    "form": {
        "close": "關閉",
		"closeTitle": "關閉文件",
		"save": "保存",
		"saveTitle": "保存文件",
		"flow": "繼續流轉",
		"flowTitle": "繼續流轉文件",
		"reroute": "調度",
		"rerouteTitle": "調度文件",
		"reset": "重置處理人",
		"resetTitle": "重置處理人",
		"split": "增加分支",
		"splitTitle": "增加分支",
		"retract": "撤回",
		"retractTitle": "待辦撤回",
		"rollback": "流程回溯",
		"rollbackTitle": "回溯到指定的環節，不保留流程記錄",
		"delete": "刪除文件",
		"deleteTitle": "刪除文件",
		"print": "列印",
		"printTitle": "列印文件",
		"press": "催促辦理",
		"pressTitle": "催促辦理",
		"pause": "掛起",
		"pauseTitle": "待辦掛起",
		"resume": "掛起恢復",
		"resumeTitle": "從掛起狀態恢復",
		"downloadAll": "一鍵下載",
		"downloadAllTitle": "一鍵下載",
		"monitor": "流程監控",
		"monitorTitle": "流程監控",
		"addTask": "加簽",
		"addTaskTitle": "在當前活動添加處理人",
		"goBack": "退回",
		"goBackTitle": "退回到已經過的活動",
		"rerouteActivity": "調度到：",
		"reroutePerson": "調度給：",
		"selectPerson": "選擇人員",
		"retouteOpinion": "調度意見：",
		"resetPerson": "重置給：",
		"resetOpinion": "重置意見：",
		"keepTask": "保留我的待辦",
		"readedOpinion": "閱讀意見",
		"setReaded": "標記為已閱",
		"readed": "已閱",
		"rollbackInfo": "請選擇文件要回溯到的位置",
		"addSplitInfo": "根據您的業務設置拆分數據，此處設置的數據應與流程中設置的拆分依據匹配。<br/>多個值請用半角逗號(,)分隔",
		"selectUnit": "選擇組織或人員",
		"excludeBranches": "排除已有分支",
		"yes": "是",
		"no": "否",
		"readIdentity": "待閱人",
		"sendReadNotify": "發送待閱通知",
		"reviewIdentity": "閱讀人",
		"noTaskToReset": "當前工作沒有您的待辦，不能執行該操作",
		"addTaskPerson": "加簽人",
		"addTaskOpinion": "意見",
		"addTaskBefore": "前加簽",
		"addTaskAfter": "後加簽",
		"addTaskBeforeTitle": "在您處理之前添加處理人",
		"addTaskAfterTitle": "在您處理之後添加處理人",
		"addTaskType": "加簽方式",
		"goBackActivity": "退回到活動：",
		"goBackActivityWay": "退回後處理：",
		"goBackActivityWayStep": "按流程標準流轉",
		"goBackActivityWayJump": "直接回到退回人",
        "goBackTo": "退回到：",
		"selectGoBackActivity": "请选择要退回的活动",
		"addTaskRepeatedTitle": "重複簽署提醒",
		"addTaskRepeatedInfo": "<span class='mainColor_color'><b>{repeated}</b></span> 已經在處理人列表中，不會對其執行簽署。"

    },

    "sendRead": "發送待閱",
    "sendReadOk": "已發送待閱",
    "noPermissionOrWorkNotExisted": "您沒有權限或工作不存在",
    "inputSendReadPeople": "請選擇待閱人",
    "sendReadPeopleCanNotEmpty": "待閱人不能為空",

    "sendReview": "添加閱讀人",
    "sendReviewOk": "已添加閱讀人",
    "inputSendReviewPeople": "請選擇閱讀人",
    "sendReviewPeopleCanNotEmpty": "閱讀人不能為空",
    "inputAddTaskPeople": "請選擇加簽人",
    "addTaskOk": "已添加加簽人",
    "addTaskInfor": "您已加簽文件：",

    "applicationNotFound": "未找到應用程式",

    "pdfview" : {
        "nofile" : "暫無文件，請上傳",
        "upload" : "上傳"
    },
    "ofdview" : {
        "nofile" : "暫無文件，請上傳",
        "upload" : "上傳"
    },
    "onlyoffice" : {
        "noInstall" : "請先安裝 OnlyOffice 應用程式",
        "filetext" : "文件內容"
    },
    "officeonline" : {
        "noInstall" : "請先安裝 Office Online 應用程式",
        "filetext" : "文件內容"
    },
    "title": "標題",
    "createTime": "創建時間",
    "creatorPerson": "創建人",
    "creatorUnit": "創建組織",
    "score": "關聯度",
    "updateTime": "更新時間",

    "documentType": "文檔類型",
    "processName": "流程名稱",
    "draftTime": "起草時間",
    "draftPerson": "起草人",
    "categoryName": "分類",
    "publishPerson": "發佈人",
    "publishTime": "發佈時間",
    "document": "信息",
    "work": "工作",
    "cancelAssociatedTitle": "取消關聯文檔",
    "cancelAssociated": "確定要取消與文檔“{title}”的關聯嗎？",
    "associatedResult": "關聯結果",
    "selectDocNote": "請先選擇文檔",
    "associatedDocument": "關聯文檔",
    "docDeleted": "文檔已被刪除。"

};
MWF.xApplication.process.Xform["lp."+o2.language] = MWF.xApplication.process.Xform.LP;
