/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.element.AppDictLobItem.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:34:34 CST 2017")
public class AppDictLobItem_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AppDictLobItem,Date> createTime;
    public static volatile SingularAttribute<AppDictLobItem,String> data;
    public static volatile SingularAttribute<AppDictLobItem,String> id;
    public static volatile SingularAttribute<AppDictLobItem,String> sequence;
    public static volatile SingularAttribute<AppDictLobItem,Date> updateTime;
}
