MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.ProcessManager = MWF.xApplication.process.ProcessManager || {};
MWF.xApplication.process.ProcessManager.LP={
	"title": "Gestión de flujo de trabajo",
	"categoryTitle": "Categoría de flujo de trabajo",
	"description": "Descripción",
	"deleteItems": "Eliminar elementos seleccionados",
	"copy": "Copiar",
	"copyto": "Copiar a...",
	"copyInfor": "Seleccione varios elementos y presione Ctrl+C para copiarlos. Luego, presione Ctrl+V para pegar los elementos copiados en la aplicación actual.",
	"copyed": "Los elementos seleccionados se han copiado",
	"copyConfirmTitle": "Confirmación",
	"copyConfirmInfor": "El área de destino ya contiene elementos similares:",
	"copySource": "Archivo original:",
	"copyTarget": "Archivo copiado:",
	"copyConfirm_overwrite": "Reemplazar",
	"copyConfirm_new": "Nuevo",
	"copyConfirm_skip": "Omitir",
	"copyConfirm_cancel": "Cancelar",
	"copynew": "Nuevo",
	"formConfig": "Formulario",
	"processConfig": "Proceso",
	"dataConfig": "Datos",
	"scriptConfig": "Script",
	"fileConfig": "Recursos",
	"applicationConfig": "Propiedades",
	"findDesigner": "Buscar diseñador",
	"ok": "Aceptar",
	"edit": "Editar",
	"save": "Guardar",
	"cancel": "Cancelar",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"deleteElementTitle": "Confirmación",
	"deleteElement": "¿Está seguro de que desea eliminar los elementos de diseño seleccionados?",
	"deleteProcessTitle": "Confirmación",
	"deleteProcess": "Eliminar el flujo de trabajo seleccionado también eliminará las instancias en tránsito del flujo de trabajo seleccionado. ¿Está seguro de que desea eliminar el flujo de trabajo seleccionado?",
	"process": {
		"create": "Crear flujo de trabajo",
		"search": "Buscar flujo de trabajo",
		"searchText": "Ingrese la palabra clave",
		"noProcessNoticeText": "Esta aplicación aún no tiene ningún flujo de trabajo. Puede hacer clic aquí para crear uno nuevo.",
		"loaded": "El flujo de trabajo se ha cargado correctamente",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar el flujo de trabajo actual?"
	},
	"form": {
		"create": "Crear formulario",
		"search": "Buscar formulario",
		"searchText": "Ingrese la palabra clave",
		"noFormNoticeText": "Esta aplicación aún no tiene ningún formulario. Puede hacer clic aquí para crear uno nuevo.",
		"loaded": "El formulario se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el formulario actual?",
		"deleteFormTemplateTitle": "Confirmación",
		"deleteFormTemplate": "¿Está seguro de que desea eliminar la plantilla de formulario actual?"
	},
	"view": {
		"create": "Crear vista",
		"search": "Buscar vista",
		"searchText": "Ingrese la palabra clave",
		"noNoticeText": "Esta aplicación aún no tiene ninguna vista. Puede hacer clic aquí para crear una nueva.",
		"loaded": "La vista se ha cargado correctamente",
		"deleteViewTitle": "Confirmación",
		"deleteView": "¿Está seguro de que desea eliminar la vista actual?"
	},
	"stat": {
		"create": "Crear estadística",
		"search": "Buscar estadística",
		"searchText": "Ingrese la palabra clave",
		"noNoticeText": "Esta aplicación aún no tiene ninguna configuración de estadística. Puede hacer clic aquí para crear una nueva.",
		"loaded": "La estadística se ha cargado correctamente",
		"deleteViewTitle": "Confirmación",
		"deleteView": "¿Está seguro de que desea eliminar la estadística actual?"
	},
	"dictionary": {
		"create": "Crear diccionario de datos",
		"search": "Buscar diccionario de datos",
		"searchText": "Ingrese la palabra clave",
		"noDictionaryNoticeText": "Esta aplicación aún no tiene ningún diccionario de datos. Puede hacer clic aquí para crear uno nuevo.",
		"noDictionaryNoCreateNoticeText": "Esta aplicación no tiene ningún diccionario de datos en este momento.",
		"loaded": "El diccionario de datos se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el diccionario de datos actual?"
	},
	"script": {
		"create": "Crear script",
		"search": "Buscar script",
		"searchText": "Ingrese la palabra clave",
		"noScriptNoticeText": "Esta aplicación aún no tiene ningún script. Puede hacer clic aquí para crear uno nuevo.",
		"loaded": "El script se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el script actual?"
	},
	"file": {
		"create": "Crear archivo adjunto",
		"search": "Buscar archivo adjunto",
		"searchText": "Ingrese la palabra clave",
		"description": "Información del archivo adjunto",
		"noScriptNoticeText": "Esta aplicación aún no tiene ningún archivo adjunto. Puede hacer clic aquí para crear uno nuevo.",
		"loaded": "El archivo adjunto se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el archivo adjunto actual?",
		"saveSuccess": "¡El archivo adjunto se ha guardado!",
		"saveConfirm": "Confirmación de guardar",
		"saveConfirmText": "Se han realizado cambios en el archivo adjunto. ¿Desea guardar los cambios?",
		"uploadSuccess": "El archivo adjunto se ha cargado correctamente",
		"loadFiles": "Cargar archivos de forma masiva"
	},
	"projection": {
		"create": "Crear mapeo de datos",
		"search": "Buscar mapeo de datos",
		"searchText": "Ingrese la palabra clave",
		"createProjectionType": "Tipo de mapeo de datos",
		"createProjectionProcess": "Seleccionar flujo de trabajo para el mapeo",
		"noProjectionType": "Seleccione primero el tipo de mapeo de datos",
		"noProjectionProcess": "Seleccione primero un flujo de trabajo para el mapeo",
		"noDictionaryNoticeText": "Esta aplicación aún no tiene ningún mapeo de datos. Puede hacer clic aquí para crear uno nuevo.",
		"noDictionaryNoCreateNoticeText": "Esta aplicación no tiene ningún mapeo de datos en este momento.",
		"loaded": "El mapeo de datos se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el mapeo de datos actual?",
		"disabled": "Deshabilitado",
		"work": "Mapea los datos empresariales a la instancia en proceso",
		"workCompleted": "Mapea los datos empresariales a la instancia finalizada",
		"task": "Mapea los datos empresariales a las tareas pendientes",
		"taskCompleted": "Mapea los datos empresariales a las tareas completadas",
		"read": "Mapea los datos empresariales a las lecturas pendientes",
		"readCompleted": "Mapea los datos empresariales a las lecturas completadas",
		"review": "Mapea los datos empresariales a la tabla de revisión",
		"createElementInfor": "Seleccione primero un tipo de mapeo de datos",
		"noProcessInfor": "Ya ha creado mapeos de datos de tipo {type} para todos los flujos de trabajo."
	},
	"application": {
		"inputApplicationName": "Ingrese el nombre de la aplicación",
		"property": "Propiedades de la aplicación",
		"name": "Nombre de la aplicación",
		"alias": "Alias de la aplicación",
		"description": "Descripción de la aplicación",
		"type": "Tipo de aplicación",
		"icon": "Icono de la aplicación",
		"id": "Identificador de la aplicación",
		"controllerList": "Controladores de la aplicación",
		"available": "Alcance disponible",
		"defaultForm": "Formulario predeterminado",
		"changeIcon": "Cambiar icono",
		"setManager": "Establecer controlador",
		"setAppManager": "Establecer controlador de la aplicación",
		"setUsableIdentity": "Establecer identidades utilizables",
		"setUsableUnit": "Establecer unidades utilizables",
		"setAppUsableIdentity": "Establecer identidades utilizables para la aplicación",
		"setAppUsableUnit": "Establecer unidades utilizables para la aplicación",
		"maintenanceIdentity": "Mantenimiento del flujo de trabajo",
		"setMaintainer": "Establecer mantenimiento del flujo de trabajo"
	},
	"createSelectTemplate": "Crear: Seleccionar plantilla",
	"templateCategory": "Categoría de plantillas:",
	"all": "Todo",
	"name": "Nombre",
	"alias": "Alias",
	"attachment": "Archivo adjunto",
	"upload": "Subir archivo adjunto",
	"selectorButton": {
		"ok": "Aceptar",
		"cancel": "Cancelar"
	},
	"defaultProcess": "Flujo de trabajo predeterminado",
	"sequenceProcess": "Flujo de trabajo secuencial",
	"choiceProcess": "Flujo de trabajo de elección",
	"parallelProcess": "Flujo de trabajo paralelo",
	"emptyForm": "Formulario en blanco",
	"commonForm": "Plantilla de formulario común",
	"blueForm": "Estilo estándar del formulario (azul)",
	"redForm": "Estilo estándar del formulario (rojo)",
	"greenForm": "Estilo estándar del formulario (verde)",
	"publishForm": "Plantilla de formulario de aprobación de publicación",
	"elementForm": "Plantilla de componente Element",
	"fileForm": "Plantilla de formulario de documento público",
	"submitPcForm": "Plantilla de formulario de envío personalizado (PC)",
	"submitMobileForm": "Plantilla de formulario de envío personalizado (móvil)"
}
MWF.xApplication.process.ProcessManager["lp."+o2.language] = MWF.xApplication.process.ProcessManager.LP