/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.AttendanceWorkPlace.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:14 CST 2018")
public class AttendanceWorkPlace_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AttendanceWorkPlace,String> creator;
    public static volatile SingularAttribute<AttendanceWorkPlace,String> description;
    public static volatile SingularAttribute<AttendanceWorkPlace,Integer> errorRange;
    public static volatile SingularAttribute<AttendanceWorkPlace,String> id;
    public static volatile SingularAttribute<AttendanceWorkPlace,String> latitude;
    public static volatile SingularAttribute<AttendanceWorkPlace,String> longitude;
    public static volatile SingularAttribute<AttendanceWorkPlace,String> placeAlias;
    public static volatile SingularAttribute<AttendanceWorkPlace,String> placeName;
}
