/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.attendance.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Double;
import java.lang.Long;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.attendance.entity.StatisticTopUnitForMonth.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:14 CST 2018")
public class StatisticTopUnitForMonth_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Long> abNormalDutyCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Double> absenceDayCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Double> employeeCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,String> id;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Long> lackOfTimeCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Long> lateCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Long> leaveEarlyCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Long> offDutyCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Long> onDutyCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Double> onDutyEmployeeCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,Double> onSelfHolidayCount;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,String> statisticMonth;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,String> statisticYear;
    public static volatile SingularAttribute<StatisticTopUnitForMonth,String> topUnitName;
}
