/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.mind.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.mind.entity.MindContentInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Dec 27 11:40:47 CST 2018")
public class MindContentInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MindContentInfo,String> content;
    public static volatile SingularAttribute<MindContentInfo,String> id;
}
