/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.faceconfig.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.faceconfig.entity.FacePlusConfig.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Jun 17 11:47:39 CST 2018")
public class FacePlusConfig_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<FacePlusConfig,Date> createTime;
    public static volatile SingularAttribute<FacePlusConfig,String> id;
    public static volatile SingularAttribute<FacePlusConfig,String> password;
    public static volatile SingularAttribute<FacePlusConfig,String> project;
    public static volatile SingularAttribute<FacePlusConfig,String> sequence;
    public static volatile SingularAttribute<FacePlusConfig,Date> updateTime;
    public static volatile SingularAttribute<FacePlusConfig,String> userId;
}
