o2.LP = window.LP || {
    "name": "이름",
    "description": "설명",
    "searchKey": "검색 키워드를 입력하세요",
    "desktop_style": "데스크톱 스타일",
    "flat_style": "플랫 스타일",
    "cmsName": "콘텐츠 관리",
    "processName": "프로세스 관리",
    "portalName": "포털 관리",
    "serviceName": "서비스 관리"
};

o2.LP.process = {
    "unnamed": "이름 없음",
    "unknown": "알 수 없음",
    "processConfig": "프로세스 설정",
    "formConfig": "양식 설정",

    "createCategory": "카테고리 생성",
    "searchCategory": "카테고리 검색",
    "noCategoryNotice": "현재 프로세스 카테고리가 없습니다. 여기를 클릭하여 카테고리를 생성할 수 있습니다.",
    "noProcessNoticeNode": "이 카테고리에 현재 프로세스가 없습니다. 여기를 클릭하여 프로세스를 생성할 수 있습니다.",

    "activity": "액티비티",
    "route": "경로",
    "property": "속성",
    "showJson": "JSON 보기",
    "unrealized": "이 기능은 아직 구현되지 않았습니다.",
    "tools": "도구",
    "repetitions": "중복된 속성 이름",
    "repetitionsValue": "중복된 항목",
    "repetitionsEvent": "중복된 이벤트 이름",
    "repetitionsId": "중복된 요소 식별자",
    "repetitionsOrInvalid": "중복 또는 유효하지 않은 속성 이름",
    "notNullId": "요소 식별자는 비워 둘 수 없습니다.",
    "editCategory": "카테고리 편집",
    "createProcess": "새 프로세스 생성",
    "deleteCategory": "카테고리 삭제",
    "deleteProcess": "프로세스 삭제",
    "editProcess": "프로세스 편집",
    "createForm": "새 양식 생성",
    "deleteForm": "양식 삭제",
    "editForm": "양식 편집",

    "menu": {
		"newRoute": "새 경로 생성",
		"newActivity": "새 활동 생성",
		"newActivityType": {
			"manual": "수동 활동",
			"condition": "조건 활동",
			"auto": "자동 활동",
			"split": "분할 활동",
			"merge": "병합 활동",
			"embed": "서브프로세스 활동",
			"invoke": "호출 활동",
			"begin": "시작 활동",
			"end": "종료 활동"
		},
		"copyActivity": "활동 복사",
		"deleteActivity": "활동 삭제",
		"deleteRoute": "경로 삭제",
		"saveProcess": "프로세스 저장",
		"saveProcessNew": "새 버전으로 저장",
		"checkProcess": "프로세스 검사",
		"exportProcess": "프로세스 내보내기",
		"printProcess": "프로세스 인쇄",
		"showGrid": "그리드 표시",
		"hideGrid": "그리드 숨김"
	},
    "notice": {
		"save_success": "프로세스 저장 성공!",
		"deleteForm_success": "양식 삭제 완료!",
		"deleteProcess_success": "프로세스 삭제 완료!",
		"one_begin": "각 프로세스에는 시작 활동이 하나만 있어야 합니다!",
		"deleteRoute": "선택한 경로를 삭제하시겠습니까?",
		"deleteRouteTitle": "경로 삭제 확인",
		"deleteActivityTitle": "활동 삭제 확인",
		"deleteActivity": "활동을 삭제하면 해당 활동과 관련된 모든 경로도 함께 삭제됩니다. 선택한 활동을 삭제하시겠습니까?",
		"deleteDecisionTitle": "결정 삭제 확인",
		"deleteDecision": "선택한 결정을 삭제하시겠습니까?",
		"deleteScriptTitle": "스크립트 삭제 확인",
		"deleteScript": "현재 스크립트를 삭제하시겠습니까?",
		"deleteElementTitle": "양식 요소 삭제 확인",
		"deleteElement": "현재 요소 및 하위 요소를 삭제하시겠습니까?",
		"deleteEventTitle": "이벤트 삭제 확인",
		"deleteEvent": "현재 이벤트를 삭제하시겠습니까?",
		"deleteActionTitle": "작업 삭제 확인",
		"deleteAction": "현재 작업을 삭제하시겠습니까?",
		"deleteRowTitle": "표 행 삭제 확인",
		"deleteRow": "현재 행을 삭제하면 해당 행의 모든 셀 내용도 함께 삭제됩니다. 선택한 행을 삭제하시겠습니까?",
		"deleteColTitle": "표 열 삭제 확인",
		"deleteCol": "현재 열을 삭제하면 해당 열의 모든 셀 내용도 함께 삭제됩니다. 선택한 열을 삭제하시겠습니까?",
		"deleteProcessTitle": "프로세스 삭제 확인",
		"deleteProcess": "현재 프로세스를 삭제하시겠습니까?",
		"deleteFormTitle": "양식 삭제 확인",
		"deleteForm": "현재 양식을 삭제하시겠습니까?",
		"deleteTreeNodeTitle": "노드 삭제 확인",
		"deleteTreeNode": "현재 노드를 삭제하시겠습니까?",
		"inputScriptName": "스크립트 이름을 입력하세요!",
		"inputCategoryName": "카테고리 이름을 입력하세요!"
	},
    "button": {
        "ok": "확인",
        "cancel": "취소",
        "reset": "초기화"
    },
    "formAction": {
        "insertRow": "행 삽입",
        "insertCol": "열 삽입",
        "deleteRow": "행 삭제",
        "deleteCol": "열 삭제",
        "mergerCell": "셀 병합",
        "splitCell": "셀 분할",
        "move": "이동",
        "copy": "복사",
        "delete": "삭제",
        "add": "추가",
        "script": "스크립트",
        "clickScript": "클릭 이벤트 스크립트",
        "defaultNode": "기본 노드"
    }
};
o2.LP.desktop = {
    "homepage": "홈페이지",
    "taskCenter": "업무 센터",
    "info": "정보 플랫폼",
    "calendar": "일정 조정",
    "profile": "개인 설정",
    "loadding": "시스템 자원을 불러오는 중입니다. 잠시 기다려주세요......",
    "lowBrowser": "브라우저 버전이 너무 낮습니다! 시스템은 이제 IE8 및 그 이하 버전을 지원하지 않습니다!",
    "upgradeBrowser": "브라우저를 업그레이드하세요:",
    "menuAction": "메뉴",
    "configAction": "대시보드 설정",
    "userMenu": "사용자 옵션",
    "userChat": "사용자 설정",
    "styleAction": "테마 변경",
    "showDesktop": "데스크탑 표시",
    "showMessage": "메시지",
    "logout": "로그아웃",
    "safeLogout": "안전 로그아웃",
    "safeLogoutTitle": "안전 로그아웃 확인",
    "safeLogoutMessage": "안전 로그아웃하면 모든 기기에서 로그인 상태가 종료됩니다. 이는 모바일 및 다른 브라우저를 포함합니다. 안전 로그아웃을 진행하시겠습니까?",
    "userConfig": "개인 설정",
    "userLanguage": "언어 설정",
    "application": "애플리케이션",
    "widget": "위젯",
    "process": "어플리케이션",
    "nosign": "개인 서명 편집 안 됨",
    "searchUser": "검색: 사용자 이름",
    "say": "말하기",
    "clearMessage": "메시지 지우기",
    "returnZoom": "100% 확대/축소 복원",
    "refresh": "새로 고침",
    "close": "닫기",
    "closeAll": "모두 닫기",
    "closeOther": "다른 모든 창 닫기",
    "openInBrowser": "새 창에서 열기",
    "lnkAppTitle": "자주 사용하는 앱",
    "deleteLnk": "자주 사용하는 앱 바로 가기 삭제",
    "addLnk": "자주 사용하는 앱 바로 가기 추가",
    "changeViewTitle": "뷰 스타일 변경 확인",
    "changeView": "뷰 스타일을 변경하시겠습니까?<br><br>변경하면 페이지가 새로 고쳐지며 저장되지 않은 데이터가 손실될 수 있습니다.",
    "refreshMenu": "기본 메뉴 정렬로 복원",
    "defaultMenuTitle": "기본 메뉴 복원 확인",
    "defaultMenuInfor": "메뉴의 정렬과 그룹을 기본 상태로 복원하시겠습니까?",
    "deleteLink" : "바로 가기 삭제",

    "messsage": {
		"appliction": "적용",
		"application": "적용",
		"process": "프로세스",
		"infor": "정보",
		"query": "데이터",
		"taskMessage": "미처리 업무 알림",
		"receiveTask": "미처리 업무를 받았습니다. 제목: ",
		"activity": "활동",
		"readMessage": "미확인 메시지 알림",
		"receiveRead": "미확인 메시지를 받았습니다. 제목: ",
		"reviewMessage": "확인 메시지 알림",
		"receiveReview": "확인 메시지를 받았습니다. 제목: ",
		"fileEditorMessage": "파일 수신 알림",
		"receiveFileEditor": "파일을 받았습니다. 보낸 사람: ",
		"fileShareMessage": "파일 공유 알림",
		"receiveFileShare": "파일 공유를 받았습니다. 공유한 사람: ",
		"meetingInviteMessage": "회의 초대 알림",
		"meetingInvite": "<font style='color: #ea621f'>{person}</font> 님이 <font style='color: #ea621f'>{date}</font>에 '<font style='color: #ea621f'>{subject}</font>' 주제의 회의에 초대하였습니다. 장소: <font style='color: #ea621f'>{addr}</font>",
		"meetingCancelMessage": "회의 취소 알림",
		"meetingCancel": "<font style='color: #ea621f'>{person}</font> 님이 <font style='color: #ea621f'>{date}</font>에 <font style='color: #ea621f'>{addr}</font>에서 예정된 '<font style='color: #ea621f'>{subject}</font>' 주제의 회의를 취소하였습니다.",
		"meetingAcceptMessage": "회의 초대 수락 알림",
		"meetingAccept": "<font style='color: #ea621f'>{person}</font> 님이 회의 초대를 수락하였습니다. 날짜: <font style='color: #ea621f'>{date}</font> 위치: <font style='color: #ea621f'>{addr}</font>, 주제: '<font style='color: #ea621f'>{subject}</font>'",
		"meetingRejectMessage": "회의 초대 거절 알림",
		"meetingReject": "<font style='color: #ea621f'>{person}</font> 님이 회의 초대를 거절하였습니다. 회의 시간: <font style='color: #ea621f'>{date}</font>, 회의 주제: '<font style='color: #ea621f'>{subject}</font>'",
		"meetingDeleteInviteMessage": "회의 초대 취소 알림",
		"meetingDeleteInvite": "<font style='color: #ea621f'>{person}</font> 님이 회의 초대를 취소하였습니다. 날짜: <font style='color: #ea621f'>{date}</font>, 주제: '<font style='color: #ea621f'>{subject}</font>', 장소: <font style='color: #ea621f'>{addr}</font>",
		"attendanceAppealInviteMessage": "근태 항소 승인 필요 알림",
		"attendanceAppealInvite": "{subject}",
		"attendanceAppealAcceptMessage": "근태 항소 승인 알림",
		"attendanceAppealAccept": "{subject}",
		"attendanceAppealRejectMessage": "근태 항소 거절 알림",
		"attendanceAppealReject": "{subject}",
		"canlendarAlarmMessage": "일정 알림",
		"canlendarAlarm": "{title}",
		"teamwork": {
			"executor": "담당자",
			"creatorPerson": "만든 사람"
		},
		"publishDocument": "문서 공개: ",
		"customMessageTitle": "메시지 알림: ",
		"customMessage": "메시지를 받았습니다.",
		"emoji": "이모티콘",
		"processWork": "작업",
		"cmsDoc": "정보 문서"
	},
    "styleMenu": {
		"default": "기본",
		"color": "색상",
		"black": "블랙",
		"lotus": "연꽃",
		"crane": "학",
		"peony": "모란",
		"car": "클래식 카",
		"dock": "부두",
		"panda": "판다",
		"star": "별"
	},
    "styleFlatMenu": {
		"blue": "파란색",
		"red": "빨간색",
		"orange": "오렌지색",
		"green": "녹색",
		"cyan": "청록색",
		"purple": "보라색",
		"gray": "회색",
		"darkgreen": "진한 초록색",
		"tan": "갈색",
		"navy": "다크 블루"
	},
    "notice": {
		"unload": "현재 페이지를 닫거나 새로 고칠 경우 저장되지 않은 내용이 손실됩니다. 계속하시겠습니까?",
		"changePassword": "비밀번호가 만료되었습니다. 즉시 비밀번호를 변경하십시오.",
		"errorConnectCenter1": "앱 센터 서버에 연결할 수 없습니다. 다음 중 하나의 주소가 접근 가능한지 확인하십시오:",
		"errorConnectCenter2": "위의 주소 중 어느 것도 접근할 수 없다면 네트워크를 확인하거나 관리자에게 문의하십시오!"
	},
    "login": {
		"title": "사용자 로그인",
		"loginButton": "로그인",

		"mobileDownload": "휴대폰으로 QR 코드를 스캔하여 설치",

		"inputUsernamePassword": "사용자 이름과 비밀번호를 입력하십시오...",
		"loginWait": "로그인 중, 잠시 기다려주십시오...",
		"loginError": "사용자 이름 또는 비밀번호가 잘못 입력되었습니다. 다시 시도하십시오...",

		"camera_logining": "로그인 중입니다. 카메라를 향해 정면을 보세요...",
		"camera_logining_1": "웃어주세요...",
		"camera_logining_2": "머리를 들어주세요...",
		"camera_logining_3": "인증 성공...",

		"camera_logining2": "카메라를 다양한 각도로 움직이거나 표정을 변경해 보세요...",
		"camera_loginSuccess": "{name} 님, 안녕하세요. 로그인 중입니다...",
		"camera_loginError": "신분을 확인할 수 없습니다. 다른 방법으로 로그인하십시오...",
		"camera_loginError2": "로그인 실패. 다른 방법으로 로그인하십시오...",
		"camera_loginError_camera": "카메라를 열 수 없습니다. 이미 사용 중인 것 같습니다..."
	},

    "action": {
		"uploadTitle": "업로드 중",
		"uploadComplete": "업로드 완료",
		"sendReady": "데이터 인코딩 중, 전송 준비 중...",
		"sendStart": "전송 시작",
		"sendError": "파일 전송 중 오류 발생",
		"sendAbort": "파일 전송이 취소되었습니다",
		"speed": "속도",
		"time": "소요 시간",
		"hour": "시간",
		"minute": "분",
		"second": "초",

		"cancelUploadTitle": "업로드 취소 확인",
		"cancelUpload": "파일 “{name}” 업로드를 취소하시겠습니까?"
	},
    "person": {
		"personEmployee": "인원 사원번호",
		"personMobile": "휴대전화",
		"personMail": "이메일",
		"personDuty": "직위",
		"personQQ": "QQ 번호",
		"personWeixin": "WeChat",
		"duty": "직위"
	},
    "collect": {
		"collectNotConnected": "O2 클라우드 연결 실패",
		"collectNotConnectedText": "O2 클라우드에 연결할 수 없습니다. 서버 네트워크를 확인하십시오!"
	}
};
o2.LP.desktop.message = o2.LP.desktop.messsage;
o2.LP.widget = {
    "upload": "업로드",
    "uploadTitle": "파일 업로드",
    "uploadInfor": "업로드할 파일을 선택하십시오",
    "delete": "삭제",
    "previewAtt" : "미리보기",
    "editAtt" : "편집",
    "replace": "교체",
    "select": "선택",

    "download": "다운로드",
    "share": "공유",
    "send": "전송",
    "downloadAll": "모두 다운로드",
    "createFolder": "폴더 만들기",
    "rename": "이름 바꾸기",
    "property": "속성",
    "refuseUpload": "파일 업로드 금지",
    "refuseUploadHTML": "<div>이름: <font style='color:#0000ff'>“{filename}”</font>인 첨부 파일이 허용된 업로드 유형과 일치하지 않아 <font style='color:#ff0000'>제외되었습니다</font></div>",
    "refuseUploadNotice" : "파일 “{filename}”이 허용된 업로드 유형과 일치하지 않습니다",
    "refuseUploadHTML_size" : "<div>이름: <font style='color:#0000ff'>“{filename}”</font>인 첨부 파일이 허용된 크기를 초과하여 <font style='color:#ff0000'>제외되었습니다</font> (파일 크기는 {size}M 미만만 허용됩니다)</div>",
    "refuseUploadNotice_size": "파일 “{filename}”이 허용된 크기를 초과했습니다 (파일 크기는 {size}M 미만만 허용됩니다)",
    "notUploadNotice": "현재 상태에서는 파일 첨부가 허용되지 않습니다",

    "list": "목록",
    "sequence": "순서",
    "icon": "아이콘",
    "preview": "미리보기",

    "min": "간략 모드",
    "max": "전체 모드",

    "size": "크기",
    "uploader": "업로더",
    "uploadTime": "시간",
    "modifyTime": "수정",
    "uploadActivity": "활동",
    "attCount": "파일",
    "folderCount": "폴더",

    "pictureSize": "이미지 크기: 폭 {width} 픽셀, 높이 {height} 픽셀",
    "pictureRatio": "이미지 비율: {ratio}",

    "ok": "확인",
    "cancel": "취소",
    "refresh": "새로 고침",
    "close": "닫기",
    "open": "열기",
    "choiceWork": "문서를 선택하세요.",
    "workcompleted": "전달 완료",

    "months": ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"],
    "days_abbr": ["일", "월", "화", "수", "목", "금", "토"],
    "clear": "지우기",
    "year": "년",
    "month": "월",
    "date": "일",
    "hour": "시",
    "minute": "분",
    "second": "초",
    "week": "주",
    "dateGreaterThanCurrentNotice" : "선택한 날짜는 현재 날짜보다 커야 합니다.",

    "unknow": "알 수 없음",
    "uploadImg": "이미지 업로드",
    "clearImg": "이미지 지우기",
    "clearImg_confirmTitle": "이미지 지우기 확인",
    "clearImg_confirm": "이미지를 지우시겠습니까?",
    "office": "문서 컨트롤에서 열기",
    "closeOffice": "첨부 파일 닫기",
    "configAttachment": "첨부 파일 권한 설정",
    "configAttachmentText": "설정",
    "checkOcrText": "자동으로 인식된 이미지의 텍스트 수정",
    "order": "첨부 파일 정렬",

    "record": "녹음",
    "stop": "중지",
    "play": "재생",
    "save": "저장",
    "userRefuse" : "사용자가 정보 제공을 거절했습니다.",
    "explorerNotSupportDevice" : "브라우저가 하드웨어 장치를 지원하지 않습니다.",
    "canNotFindDevice": "지정된 하드웨어 장치를 찾을 수 없습니다.",
    "canNotOpenMicrophone": "마이크를 열 수 없습니다. 오류 정보:",
    "explorerNotSupportRecordVoice" : "브라우저가 음성 녹음 기능을 지원하지 않습니다.",

    "clickToEditCss" : "여기를 클릭하여 CSS 작성",
    "uploadSuccess": "업로드 성공!",
    "uploadFail": "업로드 실패, 다시 업로드해주세요!",
    "selectLocalImage" : "로컬 이미지 선택",
    "selectCloudImage": "클라우드 이미지 선택",
    "reset": "재설정",
    "uploadOriginalImage": "원본 이미지 업로드",

    "startRecord" : "녹화 시작",
    "completeRecord": "녹화 종료",
    "requireHttps" : "비디오 녹화 기능은 HTTPS 프로토콜에서만 사용할 수 있습니다",
    "canNotToRecordVideo" : "비디오 녹화 기능을 사용할 수 없습니다. 브라우저가 다음 기능을 지원하지 않습니다:",

    "pageJumperTitle": "페이지 번호 입력, 입력란을 떠나거나 Enter를 눌러 이동",

    "scriptAreaEditNotice" : "여기를 클릭하여 스크립트 코드 작성",
    "empty" : "지우기",
    "undo" : "실행 취소",
    "redo" : "다시 실행",
    "eraserRadius": "지우개 크기",
    "eraser": "지우개",
    "input": "입력기",
    "pen": "펜",
    "thickness" : "굵기",
    "color" : "색상",
    "insertImage" : "이미지 삽입",
    "imageClipper" : "이미지 클리퍼",
    "fontSize": "글꼴 크기",
    "fontFamily": "글꼴",

    "explorerNotSupportFeatures" : "브라우저가 다음 특징을 지원하지 않습니다:"
};

o2.LP.widget.SimpleEditor = {
    "insertEmotion": "이모티콘 삽입",
    "insertImage": "이미지 삽입",
    "Emotions": "regular_smile|웃음,teeth_smile|큰 웃음,angry_smile|화남,confused_smile|혼란, cry_smile|울음,embaressed_smile|당황,omg_smile|놀람,sad_smile|슬픔,shades_smile|멋짐, tounge_smile|혀 내밀기,wink_smile|윙크,angel_smile|천사,devil_smile|악마,heart|하트,broken_heart|부서진 하트,thumbs_up|좋아요,thumbs_down|싫어요,cake|케이크,lightbulb|전구,envelope|봉투"
};
o2.LP.authentication = {
    "LoginFormTitle": "로그인 환영합니다",
    "SignUpFormTitle": "회원가입 환영합니다",
    "ResetPasswordFormTitle": "비밀번호 찾기",
    "ChangePasswordFormTitle": "비밀번호 변경 필요",
    "userName": "사용자 이름",
    "password": "비밀번호",
    "verificationCode": "인증 코드",
    "loginAction": "로그인",
    "autoLogin": "자동 로그인",
    "signUp": "회원가입",
    "forgetPassword": "비밀번호 찾기",
    "inputYourUserName": "사용자 이름을 입력하세요",
    "inputYourPassword": "비밀번호를 입력하세요",
    "inputYourMail": "이메일 주소를 입력하세요",
    "inputYourMobile": "휴대전화 번호를 입력하세요",
    "inputPicVerificationCode": "우측의 인증 코드를 입력하세요",
    "inputComfirmPassword": "비밀번호를 확인하세요",
    "inputVerificationCode": "휴대전화 인증 코드를 입력하세요",
    "confirmPassword": "비밀번호 확인",
    "sendVerification": "인증 코드 보내기",
    "resendVerification": "다시 보내기",
    "passwordIsSimple": "숫자와 문자를 혼합하여 7자 이상을 사용하세요",
    "mobileIsRegisted": "휴대전화 번호가 이미 등록되어 있습니다",
    "mailFormatError": "올바른 이메일 형식을 입력하세요",
    "hasAccount": "계정이 이미 있으신가요?",
    "gotoLogin": "로그인하러 가기",
    "weak": "약함",
    "middle": "중간",
    "high": "강함",
    "userExist": "사용자가 이미 존재합니다",
    "userNotExist": "사용자가 존재하지 않습니다",
    "passwordNotEqual": "비밀번호가 위와 일치하지 않습니다. 다시 입력해주세요",
    "changeVerification": "다른 이미지로 바꾸기",
    "mail": "이메일",
    "genderType": "성별",
    "genderTypeText": ",남성,여성",
    "genderTypeValue": ",남,여",
    "selectGenderType": "성별을 선택하세요",
    "registeSuccess": "가입 성공",
    "codeLogin": "문자 메시지 인증 로그인",
    "passwordLogin": "비밀번호로 로그인",
    "bindLogin": "QR 코드 로그인",
    "bingLoginTitle": "휴대전화로 스캔하여 안전하게 로그인하세요",
    "o2downloadLink": "https://sample.o2oa.net/app/download.html",
    "loginSuccess": "로그인 성공!",
    "userCheck": "사용자 인증",
    "shotMessageCheck": "문자 메시지 인증",
    "setMewPassword": "새 비밀번호 설정",
    "completed": "완료",
    "nextStep": "다음 단계",
    "mobile": "휴대전화",
    "setNewPassword": "새 비밀번호 설정",
    "confirmNewPassword": "새 비밀번호 확인",
    "passwordIsWeak": "비밀번호가 너무 약합니다. 숫자와 문자를 사용하고 길이가 7보다 커야 합니다.",
    "resetPasswordSuccess": "비밀번호 재설정 성공!",
    "resetPasswordFail": "비밀번호 재설정 실패!",
    "resetPasswordSuccessWord": "새로 설정한 비밀번호를 기억하세요.",
    "resetPasswordFailWord": "사용자 이름과 문자 메시지 확인 코드를 확인하세요.",
    "backtoModify": "수정으로 돌아가기",
    "pageNotFound": "404 오류. 서비스를 찾을 수 없거나 서버가 연결이 끊어졌습니다.",
    "submitAction": "확인",
    "oldPassword": "기존 비밀번호",
    "inputYourOldPassword": "기존 비밀번호를 입력하세요",
    "newPassword": "새 비밀번호",
    "inputYourNewPassword": "새 비밀번호를 입력하세요",
    "changePasswordSuccess": "비밀번호 변경 성공",
    "userAppCameraHtml": "<div>앱을 열고<div styles='bindTipLinkArea'>스캔</div>하십시오</div>",
    "loginToPage": "웹 버전으로 로그인",
    "accessError": "백엔드 서비스에 액세스하지 못했습니다"

};
o2.LP.script = {
    "error": "스크립트 실행 오류. 아래 자세한 정보를 확인하세요."
};
