o2.LP = window.LP || {
    "name": "名稱",
    "description": "描述",
    "searchKey": "請輸入搜索關鍵字",
    "desktop_style": "桌面風格",
    "flat_style": "扁平風格",
    "cmsName": "內容管理",
    "processName": "流程管理",
    "portalName": "門戶管理",
    "serviceName": "服務管理"
};

o2.LP.process = {
    "unnamed": "未命名",
    "unknown": "未知",
    "processConfig": "流程配置",
    "formConfig": "表單配置",

    "createCategory": "創建分類",
    "searchCategory": "搜索分類",
    "noCategoryNotice": "目前尚無流程分類，您可以點擊此處創建一個流程分類。",
    "noProcessNoticeNode": "此分類目前尚無流程，您可以點擊此處創建一個流程。",

    "activity": "活動",
    "route": "路由",
    "property": "屬性",
    "showJson": "查看JSON",
    "unrealized": "此功能未實現",
    "tools": "工具",
    "repetitions": "重複的屬性名稱",
    "repetitionsValue": "重複的內容項",
    "repetitionsEvent": "重複的事件名稱",
    "repetitionsId": "重複的元素標識符",
    "repetitionsOrInvalid": "重複或無效的屬性名稱",
    "notNullId": "元素標識符不能為空",
    "editCategory": "編輯分類",
    "createProcess": "新建流程",
    "deleteCategory": "刪除分類",
    "deleteProcess": "刪除流程",
    "editProcess": "編輯流程",
    "createForm": "新建表單",
    "deleteForm": "刪除表單",
    "editForm": "編輯表單",

    "menu": {
		"newRoute": "新建路徑",
		"newActivity": "新建活動",
		"newActivityType": {
			"manual": "手動活動",
			"condition": "條件活動",
			"auto": "自動活動",
			"split": "拆分活動",
			"merge": "合併活動",
			"embed": "子流程活動",
			"invoke": "呼叫活動",
			"begin": "開始活動",
			"end": "結束活動"
		},
		"copyActivity": "複製活動",
		"deleteActivity": "刪除活動",
		"deleteRoute": "刪除路徑",
		"saveProcess": "保存流程",
		"saveProcessNew": "另存新版本",
		"checkProcess": "檢查流程",
		"exportProcess": "匯出流程",
		"printProcess": "列印流程",
		"showGrid": "顯示網格",
		"hideGrid": "隱藏網格"
	},
    "notice": {
		"save_success": "流程保存成功！",
		"deleteForm_success": "表單已刪除！",
		"deleteProcess_success": "流程已刪除！",
		"one_begin": "每個流程只能有一個開始活動！",
		"deleteRoute": "您確定要刪除選中的路由嗎？",
		"deleteRouteTitle": "刪除路由確認",
		"deleteActivityTitle": "刪除活動確認",
		"deleteActivity": "刪除活動將同時刪除關聯此活動的所有路由，您確定要刪除選中的活動嗎？",
		"deleteDecisionTitle": "刪除決策確認",
		"deleteDecision": "您確定要刪除選中的決策嗎？",
		"deleteScriptTitle": "刪除腳本確認",
		"deleteScript": "您確定要刪除當前腳本嗎？",
		"deleteElementTitle": "刪除表單元素確認",
		"deleteElement": "是否確定刪除當前元素，以及其子元素？",
		"deleteEventTitle": "刪除事件確認",
		"deleteEvent": "是否確定刪除當前事件？",
		"deleteActionTitle": "刪除操作確認",
		"deleteAction": "是否確定刪除當前操作？",
		"deleteRowTitle": "刪除表格行確認",
		"deleteRow": "刪除當前行將刪除該行所有儲存格中的內容，是否確定刪除當前選中的行？",
		"deleteColTitle": "刪除表格列確認",
		"deleteCol": "刪除當前行將刪除該列所有儲存格中的內容，是否確定刪除當前選中的列？",
		"deleteProcessTitle": "刪除流程確認",
		"deleteProcess": "是否確定要刪除當前流程？",
		"deleteFormTitle": "刪除表單確認",
		"deleteForm": "是否確定要刪除當前表單？",
		"deleteTreeNodeTitle": "刪除節點確認",
		"deleteTreeNode": "是否確定要刪除當前節點？",
		"inputScriptName": "請輸入腳本名稱！",
		"inputCategoryName": "請輸入分類名稱！"
	},
    "button": {
        "ok": "確定",
        "cancel": "取消",
        "reset": "重置"
    },
    "formAction": {
        "insertRow": "插入行",
        "insertCol": "插入列",
        "deleteRow": "刪除行",
        "deleteCol": "刪除列",
        "mergerCell": "合併儲存格",
        "splitCell": "拆分儲存格",
        "move": "移動",
        "copy": "複製",
        "delete": "刪除",
        "add": "添加",
        "script": "腳本",
        "clickScript": "點擊事件腳本",
        "defaultNode": "默認節點"
    }
};
o2.LP.desktop = {
    "homepage": "首頁",
    "taskCenter": "辦公中心",
    "info": "信息平台",
    "calendar": "日程安排",
    "profile": "個人設置",
    "loadding": "正在為您加載系統資源，請稍候......",
    "lowBrowser": "您的瀏覽器版本過低啦！~系統已經不支持IE8及以下版本了！",
    "upgradeBrowser": "請升級您的瀏覽器：",
    "menuAction": "菜單",
    "configAction": "配置您的工作台",
    "userMenu": "用戶選項",
    "userChat": "用戶設置",
    "styleAction": "切換主題",
    "showDesktop": "顯示桌面",
    "showMessage": "消息",
    "logout": "註銷",
    "safeLogout": "安全註銷",
    "safeLogoutTitle": "安全註銷確認",
    "safeLogoutMessage": "安全註銷將會退出您在所有設備的登錄狀態，包括移動端和其他瀏覽器，是否確定安全註銷?",
    "userConfig": "個人設置",
    "userLanguage": "語言設置",
    "application": "組件",
    "widget": "小工具",
    "process": "應用",
    "nosign": "未編輯個性簽名",
    "searchUser": "搜索：用戶名",
    "say": "說",
    "clearMessage": "清除消息",
    "returnZoom": "恢復100%比例",
    "refresh": "刷新",
    "close": "關閉",
    "closeAll": "全部關閉",
    "closeOther": "關閉其他",
    "openInBrowser": "新窗口打開",
    "lnkAppTitle": "常用應用",
    "deleteLnk": "刪除常用應用快捷方式",
    "addLnk": "添加常用應用快捷方式",
    "changeViewTitle": "切換視圖樣式確認",
    "changeView": "您確定要切換視圖樣式嗎？<br><br>如果您選擇“確定”，頁面將直接刷新，未保存的數據可能丟失。",
       "refreshMenu": "恢復默認菜單排序",
    "defaultMenuTitle": "恢復默認菜單確認",
    "defaultMenuInfor": "您確定要將菜單的排序和分組恢復到默認狀態碼嗎？",
    "deleteLink" : "刪除快捷方式",

	"messsage": {
		"appliction": "應用",
		"application": "應用",
		"process": "流程",
		"infor": "信息",
		"query": "數據",
		"taskMessage": "待辦提醒",
		"receiveTask": "您收到一條待辦，標題為：",
		"activity": "活動",
		"readMessage": "待閱提醒",
		"receiveRead": "您收到一條待閱，標題為：",
		"reviewMessage": "閱讀提醒",
		"receiveReview": "您收到一條閱讀提醒，標題為：",
		"fileEditorMessage": "收到文件",
		"receiveFileEditor": "發送給您一個文件：",
		"fileShareMessage": "共享文件",
		"receiveFileShare": "共享給您一個文件：",
		"meetingInviteMessage": "會議邀請",
		"meetingInvite": "<font style='color: #ea621f'>{person}</font> 邀請您 於<font style='color: #ea621f'>{date}</font>參加會議：“{subject}”，地點：<font style='color: #ea621f'>{addr}</font>",
		"meetingCancelMessage": "會議取消",
		"meetingCancel": "<font style='color: #ea621f'>{person}</font> 取消了原定於<font style='color: #ea621f'>{date}</font>在<font style='color: #ea621f'>{addr}</font>舉行的會議: “{subject}”",
		"meetingAcceptMessage": "會議邀請已被接受",
			"meetingAccept": "<font style='color: #ea621f'>{person}</font> 已接受您的會議邀請，將於<font style='color: #ea621f'>{date}</font>到<font style='color: #ea621f'>{addr}</font>參加會議: “{subject}”",
		"meetingRejectMessage": "會議邀請已被拒絕",
		"meetingReject": "<font style='color: #ea621f'>{person}</font> 已拒絕您的會議邀請。會議時間：<font style='color: #ea621f'>{date}</font>；會議主題: “{subject}”",
		"meetingDeleteInviteMessage": "會議邀請已取消",
		"meetingDeleteInvite": "<font style='color: #ea621f'>{person}</font> 取消了您的會議邀請，會議信息：時間<font style='color: #ea621f'>{date}</font>，主題“{subject}”，地點<font style='color: #ea621f'>{addr}</font>",
		"attendanceAppealInviteMessage": "有考勤申述需要您審批",
		"attendanceAppealInvite": "{subject}",
		"attendanceAppealAcceptMessage": "考勤申述通過",
		"attendanceAppealAccept": "{subject}",
		"attendanceAppealRejectMessage": "考勤申述未通過",
		"attendanceAppealReject": "{subject}",
		"canlendarAlarmMessage": "日程提醒",
		"canlendarAlarm": "{title}",
		"teamwork": {
			"executor": "負責人",
			"creatorPerson": "創建者"
		},
		"publishDocument": "發布文檔：",
		"customMessageTitle": "消息提醒：",
		"customMessage": "您收到一條消息",
		"emoji": "表情",
		"processWork": "工作",
		"cmsDoc": "信息文檔"
	},
    "styleMenu": {
		"default": "默認",
		"color": "顏色",
		"black": "酷黑",
		"lotus": "荷花",
		"crane": "仙鶴",
		"peony": "牡丹",
		"car": "老爺車",
		"dock": "碼頭",
		"panda": "熊貓",
		"star": "星空"
	},
    "styleFlatMenu": {
		"blue": "藍色",
		"red": "紅色",
		"orange": "橙色",
		"green": "綠色",
		"cyan": "青色",
		"purple": "紫色",
		"gray": "灰色",
		"darkgreen": "深綠色",
		"tan": "棕色",
		"navy": "藏青色"
	},
    "notice": {
		"unload": "如果關閉或刷新當前頁面，未保存的內容會丟失，請確定您的操作",
		"changePassword": "您的密碼已過期，請及時修改密碼",
		"errorConnectCenter1": "無法連接到應用中心伺服器，請確保下列地址其中之一可以訪問：",
		"errorConnectCenter2": "如果以上地址都無法訪問，請檢查您的網絡，或聯繫管理員！"
	},
    "login": {
		"title": "用戶登錄",
		"loginButton": "登錄",

		"mobileDownload": "手機掃描二維碼安裝",

		"inputUsernamePassword": "請輸入用戶名和密碼...",
		"loginWait": "登錄中，請稍候...",
		"loginError": "用戶名或密碼輸入有誤，請重新輸入...",

		"camera_logining": "正在為您登錄，請正對攝像頭 ...",
		"camera_logining_1": "請保持微笑 ...",
		"camera_logining_2": "請抬頭 ...",
		"camera_logining_3": "驗證成功 ...",

		"camera_logining2": "請移動不同角度，或變換表情 ...",
		"camera_loginSuccess": "{name}您好，正在為您登錄 ...",
		"camera_loginError": "無法驗證您的身份，請通過其他方式登錄 ...",
		"camera_loginError2": "登錄失敗，請通過其他方式登錄 ...",
		"camera_loginError_camera": "無法打開攝像頭，可能已經在使用中 ..."
	},

    "action": {
		"uploadTitle": "正在上傳",
		"uploadComplete": "上傳完成",
		"sendReady": "正在編碼數據，準備傳輸...",
		"sendStart": "開始傳輸",
		"sendError": "文件傳輸出現錯誤",
		"sendAbort": "文件傳輸已被取消",
		"speed": "速度",
		"time": "耗時",
		"hour": "時",
		"minute": "分",
		"second": "秒",

		"cancelUploadTitle": "取消上傳確認",
		"cancelUpload": "您確定要取消上傳文件“{name}”嗎？"
	},
    "person": {
		"personEmployee": "人員工號",
		"personMobile": "手機",
		"personMail": "郵件",
		"personDuty": "職務",
		"personQQ": "QQ號碼",
		"personWeixin": "微信",
		"duty": "職務"
	},
    "collect": {
		"collectNotConnected": "連接O2雲失敗",
		"collectNotConnectedText": "無法連接到O2雲，請檢查伺服器網絡！"
	}
};
o2.LP.desktop.message = o2.LP.desktop.messsage;
o2.LP.widget = {
    "upload": "上傳",
    "uploadTitle": "上傳檔案",
    "uploadInfor": "請選擇要上傳的檔案",
    "delete": "刪除",
    "previewAtt" : "預覽",
    "editAtt" : "編輯",
    "replace": "替換",
    "select": "選擇",

    "download": "下載",
    "share": "分享",
    "send": "發送",
    "downloadAll": "全部下載",
    "createFolder": "創建資料夾",
    "rename": "重命名",
    "property": "屬性",
    "refuseUpload": "禁止檔案上傳",
    "refuseUploadHTML": "<div>名稱：<font style='color:#0000ff'>“{filename}”</font>的附件不符合允許上傳類型，<font style='color:#ff0000'>已經被剔除</font></div>",
    "refuseUploadNotice" : "檔案：“{filename}”不符合允許上傳類型",
    "refuseUploadHTML_size" : "<div>名稱：<font style='color:#0000ff'>“{filename}”</font>的附件超出允許的大小，<font style='color:#ff0000'>已經被剔除</font>（僅允許上傳小於{size}M的檔案）</div>",
    "refuseUploadNotice_size": "檔案：“{filename}”超出允許的大小，（僅允許上傳小於{size}M的檔案）",
    "notUploadNotice": "當前狀態不允許上傳附件",

    "list": "列表",
    "sequence": "序列",
    "icon": "圖標",
    "preview": "預覽",

    "min": "簡潔模式",
    "max": "完整模式",

    "size": "大小",
    "uploader": "上傳人",
    "uploadTime": "時間",
    "modifyTime": "修改",
    "uploadActivity": "活動",
    "attCount": "文件",
    "folderCount": "文件夾",

    "pictureSize": "圖片顯示寬{width}像素，高{height}像素",
    "pictureRatio": "圖片寬高比為{ratio}",

    "ok": "確定",
    "cancel": "取消",
    "refresh": "刷新",
    "close": "關閉",
    "open": "打開",
    "choiceWork": "請選擇一個文檔打開",
    "workcompleted": "流轉完成",

    "months": ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
    "days_abbr": ["日", "一", "二", "三", "四", "五", "六"],
    "clear": "清除",
    "year": "年",
    "month": "月",
    "date": "日",
    "hour": "時",
    "minute": "分",
    "second": "秒",
    "week": "週",
    "dateGreaterThanCurrentNotice" : "選擇的日期必須大於當前日期",

    "unknow": "未知",
    "uploadImg": "上傳圖片",
    "clearImg": "清除圖片",
    "clearImg_confirmTitle": "清除圖片確認",
    "clearImg_confirm": "您確定要清除圖片嗎？",
    "office": "在文檔控制元件中打開",
    "closeOffice": "關閉附件",
    "configAttachment": "設置附件權限",
    "configAttachmentText": "設置",
    "checkOcrText": "更正自動識別的圖片中的文字",
    "order": "附件排序",

    "record": "錄音",
    "stop": "停止",
    "play": "播放",
    "save": "儲存",
    "userRefuse" : "用戶拒絕提供信息。",
    "explorerNotSupportDevice" : "瀏覽器不支持硬件設備。",
    "canNotFindDevice": "無法找到指定的硬件設備。",
    "canNotOpenMicrophone": "無法打開麥克風。異常信息：",
    "explorerNotSupportRecordVoice" : "瀏覽器不支持錄音功能。",

    "clickToEditCss" : "點擊此處，編寫CSS",
    "uploadSuccess": "上載成功！",
    "uploadFail": "上載失敗，請重新上載！",
    "selectLocalImage" : "選擇本地圖片",
    "selectCloudImage": "選擇雲端圖片",
    "reset": "重設",
    "uploadOriginalImage": "上載原圖",

    "startRecord" : "開始錄制",
    "completeRecord": "結束錄制",
    "requireHttps" : "視頻錄制功能需要使用 HTTPS 協議才能使用",
    "canNotToRecordVideo" : "視頻錄制功能無法使用，您的瀏覽器不支持以下功能:",

    "pageJumperTitle": "輸入頁碼，離開輸入框或按Enter跳轉",

    "scriptAreaEditNotice" : "點擊此處，編寫腳本代碼",
    "empty" : "清空",
    "undo" : "撤銷",
    "redo" : "重做",
    "eraserRadius": "橡皮大小",
    "eraser": "橡皮",
    "input": "輸入法",
    "pen": "筆畫",
    "thickness" : "粗細",
    "color" : "顏色",
    "insertImage" : "插入圖片",
    "imageClipper" : "裁剪圖片",
    "fontSize": "字體大小",
    "fontFamily": "字體",

    "explorerNotSupportFeatures" : "您的瀏覽器不支持以下特性:"
};

o2.LP.widget.SimpleEditor = {
    "insertEmotion": "插入表情",
    "insertImage": "插入圖片",
    "Emotions": "regular_smile|微笑，teeth_smile|大笑,angry_smile|生氣,confused_smile|困惑,cry_smile|大哭,embaressed_smile|尷尬,omg_smile|驚訝,sad_smile|悲傷,shades_smile|酷, tounge_smile|吐舌,wink_smile|眨眼,angel_smile|天使,devil_smile|惡魔,heart|紅心,broken_heart|心碎,thumbs_up|讚,thumbs_down|踩,cake|蛋糕,lightbulb|燈泡,envelope|信封"
};
o2.LP.authentication = {
    "LoginFormTitle": "歡迎登錄",
    "SignUpFormTitle": "歡迎註冊",
    "ResetPasswordFormTitle": "找回密碼",
    "ChangePasswordFormTitle": "密碼已過期",
    "userName": "用戶名",
    "password": "密碼",
    "verificationCode": "驗證碼",
    "loginAction": "登錄",
    "autoLogin": "下次自動登錄",
    "signUp": "註冊",
    "forgetPassword": "忘記密碼？",
    "inputYourUserName": "請輸入用戶名",
    "inputYourPassword": "請輸入密碼",
    "inputYourMail": "請輸入您的電郵地址",
    "inputYourMobile": "請輸入您的手機號碼",
    "inputPicVerificationCode": "請輸入右側的驗證碼",
    "inputComfirmPassword": "請確認您的密碼",
    "inputVerificationCode": "請輸入手機驗證碼",
    "confirmPassword": "確認密碼",
    "sendVerification": "發送驗證碼",
    "resendVerification": "重新發送",
    "passwordIsSimple": "請使用數字和字母混合，至少7位",
    "mobileIsRegisted": "手機號碼已經被註冊",
    "mailFormatError": "請輸入正確格式的郵件地址",
    "hasAccount": "已有帳號？",
    "gotoLogin": "前往登錄",
    "weak": "弱",
    "middle": "中",
    "high": "強",
    "userExist": "用戶已經存在",
    "userNotExist": "用戶不存在",
    "passwordNotEqual": "密碼與上面不一致，請重新輸入",
    "changeVerification": "換一張",
    "mail": "郵件",
    "genderType": "性別",
    "genderTypeText": ",男,女",
    "genderTypeValue": ",m,f",
    "selectGenderType": "請選擇性別",
    "registeSuccess": "註冊成功",
    "codeLogin": "短信驗證登錄",
    "passwordLogin": "密碼登錄",
    "bindLogin": "二維碼登錄",
    "bingLoginTitle": "手機掃碼，安全登錄",
    "o2downloadLink": "https://sample.o2oa.net/app/download.html",
    "loginSuccess": "登錄成功！",
    "userCheck": "用戶認證",
    "shotMessageCheck": "短信驗證",
    "setMewPassword": "設置新密碼",
    "completed": "完成",
    "nextStep": "下一步",
    "mobile": "手機",
    "setNewPassword": "設置新密碼",
    "confirmNewPassword": "確認新密碼",
    "passwordIsWeak": "密碼太弱，請使用數字和字母，且長度大於7",
    "resetPasswordSuccess": "重置密碼成功！",
    "resetPasswordFail": "重置密碼失敗！",
    "resetPasswordSuccessWord": "請牢記您新設置的密碼。",
    "resetPasswordFailWord": "請核對您的用戶名和短信驗證碼。",
    "backtoModify": "返回修改",
    "pageNotFound": "404錯誤，未找到服務或伺服器已斷開",
    "submitAction": "確定",
    "oldPassword": "原密碼",
    "inputYourOldPassword": "請輸入原密碼",
    "newPassword": "新密碼",
    "inputYourNewPassword": "請輸入新密碼",
    "changePasswordSuccess": "修改密碼成功",
    "userAppCameraHtml": "<div>打開<div styles='bindTipLinkArea'>APP</div>掃一掃</div>",
    "loginToPage": "登錄網頁版",
    "accessError": "訪問後台服務失敗"

};
o2.LP.script = {
    "error": "腳本運行出錯，請查看以下詳細信息"
};
