MWF.xApplication.Strategy.LP = {
	"title": "战略管理平台",
	"keyWork":{
		"name":"公司重点工作",
		"add":"增加",
		"imported":"导入",
		"deptList":"部门列表：",
		"defaultSearchIn":"请按标题搜索",
		"submitWarn":{
			"title":"信息确认",
			"content":{
				"deleted":"确认删除?"
			}
		},
		"view":{
			"NO":"序号",
			"title":"标题",
			"department":"责任部门",
			"content":"内容",
			"action":"操作",
			"action_open":"打开",
			"action_edit":"编辑",
			"action_delete":"删除"
		},
		"popupForm":{
			"addTitle":"增加工作",
			"sequencenumber":"序号",
			"title":"重点工作",
			"year":"年份",
			"department":"部门",
			"description":"描述",
			"selectYears":"2016,2017,2018,2019,2020",
			"saveAction":"保存",
			"cancelAction":"取消"
		}
	},
	"measure":{
		"name":"关键举措",
		"add":"增加",
		"addTitle":"增加工作",
		"deptList":"部门列表：",
		"defaultSearchIn":"请按标题搜索",
		"submitWarn":{
			"title":"信息确认",
			"content":{
				"deleted":"确认删除?"
			}
		},
		"view":{
			"NO":"序号",
			"title":"标题",
			"department":"牵头部门",
			"resDepartment":"责任部门",
			"measuressupportdepts":"支撑部门",
			"content":"工作内容",
			"action":"操作",
			"action_open":"打开",
			"action_edit":"编辑",
			"action_delete":"删除"
		},
		"popupForm":{
			"addTitle":"增加工作",
			"sequencenumber":"序号",
			"title":"关键举措",
			"year":"年份",
			"department":"牵头部门",
			"resDepartment":"责任部门",
			"measuressupportdepts":"支撑部门",
			"keyWork":"公司工作重点",
			"Measuresinfoparentid ":"公司工作重点",
			"description":"工作内容",
			"measuresinfotargetvalue":"战略举措目标值",
			"target":"目标值",
			"selectYears":"2016,2017,2018,2019,2020",
			"saveAction":"保存",
			"cancelAction":"取消"
		}
	},
	"priority":{
		"name":"年度重点工作及目标",
		"add":"增加",
		"addTitle":"增加工作",
		"deptList":"部门列表：",
		"defaultSearchIn":"请按标题搜索",
		"submitWarn":{
			"title":"信息确认",
			"content":{
				"deleted":"确认删除?"
			}
		},
		"view":{
			"NO":"序号",
			"title":"标题",
			"measure":"相关举措",
			"content":"内容",
			"action":"操作",
			"action_open":"打开",
			"action_edit":"编辑",
			"action_delete":"删除"
		},
		"popupForm":{
			"addTitle":"增加工作",
			"sequencenumber":"序号",
			"title":"标题",
			"year":"年份",
			"department":"部门",
			"keyWork":"公司工作重点",
			"validDate":"起始时间",
			"keyworkbegindate":"开始日期",
			"validDateConnect":"至",
			"validDateMonth":"月",
			"keyworkenddate":"结束日期",
			"measurelist":"相关举措",
			"description":"描述",
			"attachments":"附件",
			"selectYears":"2016,2017,2018,2019,2020",
			"selectMonth" : " ,1,2,3,4,5,6,7,8,9,10,11,12",
			"saveAction":"保存",
			"cancelAction":"取消"
		}
	},
	"importForm":{
		"importAction":"导入",
		"importClose":"关闭",
		"template":"导入模板",
		"title":"导入",
		"notice":{
			"fileEmpty":"请选择文件",
			"sheetEmpty":"请选择sheet页"
		}
	},
	"template":{
		"defaultSelect":"请选择",
		"paging":{
			prePage : "上页",
			nextPage : "下页",
			firstPage : "首页",
			lastPage : "末页",
			"perPageText":"每页5条,每页10条,每页20条",
			"perPageValue":"5,10,20",
			"perPage":{
				"five":{"text":"每页5条","value":5},
				"ten":{"text":"每页10条","value":10},
				"twenty":{"text":"每页20条","value":20}
			}
		}
	},
	"attachment":{
		"priority":{
			"deleteAttachmentTitle":"附件删除",
			"deleteAttachment":"附件"
		}
	},
	"prompt":{
		"keyWork":{
			"deleteOK":"删除成功"
		},
		"measure":{
			"deleteOK":"删除成功"
		},
		"priority":{
			"deleteOK":"删除成功"
		}
	}
};