MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Xform = MWF.xApplication.cms.Xform || {};
MWF.xApplication.cms.Xform.LP={
	"ok": "OK",
	"deleteDatagridLineTitle": "Delete item confirmation",
	"deleteDatagridLine": "Are you sure you want to delete the current item?",
	"cancelDatagridLineEditTitle": "Cancel Data Grid Edit Confirmation",
	"cancelDatagridLineEdit": "Are you sure to cancel editing the data grid?",
	"datagridImport": "Import Excel",
	"datagridExport": "Export Excel",
	"exportDefaultName": "DataGrid",
	"datatemplateExportDefaultName": "DataTemplate",
	"datatableExportDefaultName": "DataTable",
	"importSuccess": "Import successful!",
	"validationInfor": "Verification Information",
	"importFail": "Import failed",
	"importValidationColumnText": "Column {n}:",
	"importValidationColumnTextExcel": "Column {n}:",
	"notValidNumber": "Not a number",
	"notValidDate": "Not a date format",
	"fullstop": ".",
	"notExistInSystem": "Does not exist in the system",
	"uploadedFilesCannotHaveSpaces": "Uploaded files cannot contain spaces",
	"browserNotActiveX": "Your browser does not support ActiveX, Office controls cannot be loaded, please use Internet Explorer",
	"activity": "activity",
	"dataSaved": "Data saved successfully",
	"taskProcessed": "File has been submitted",
	"taskProcessedMessage": "You processed a task: ",
	"nextActivity": "Next Activity: ",
	"nextUser": "Processor: ",
	"arrivedActivitys": "arrived activities ",
	"arrivedUsers": "arrived user ",
	"replace": " instead ",
	"next_etc": " {count} people",
	"nextTaskMatrix": "Possible next handlers: ",
	"processStarted": "Job has been started",
	"processStartedMessage": "You started a new job: ",
	"draftStart": "Process has been started",
	"taskCompleted": "Task has been processed",
	"workCompleted": "Work has been completed",
	"arrivedActivity": "Work has arrived activity: ",
	"workProcess": "Flow to",
	"close": "Close",
	"retract": "Retract",
	"reroute": "Reroute",
	"rerouteTo": "RerouteTo",
	"rollback": "Process rollback",
	"rollbackTo": "Process rollback to",
	"rollback_success": "Rollback success",
	"selectRollbackActivity": "Select the location of the file to be rollback to:",
	"tryToProcess": "try to continue flow",
	"in": " in ",
	"andSoForth": "...",
	"noIdentitySelectRange": "Cannot determine the range of identity selection",
	"noIdentityDutySelectRange": "Unable to determine the range of duty selection",
	"noUnitSelectRange": "Cannot determine the selection range of the unit",
	"noSelectRange": "Cannot determine the selection range",
	"noSelectType": "The selection type is not set",
	"selectRoute": "Select Route",
	"submitAt": " Submit At ",
	"idea": " Opinion ",
	"processing": " Processing ",
	"comeTime": "Arrival Time ",
	"begin": "begin",
	"end": "end",
	"none": "None",
	"empower": " empower ",
	"person": "Personnel Name",
	"department": "Unit",
	"startTime": "Received time",
	"completedTime": "Processing Time",
	"route": " route ",
	"opinion": "Opinion",
	"systemProcess": "System Process",
	"showProcess": "Show Process",
	"deleteAttachmentTitle": "Delete attachment confirmation",
	"deleteAttachment": "Are you sure you want to delete the attachment you selected?",
	"sendTaskNotice": "A reminder has been sent to the task person: {users}",
	"setReadedConfirmContent": "Are you sure you want to mark \"{title}\" as readed?",
	"setReadedConfirmTitle": "Mark as readed confirmation",
	"replaceAttachmentTitle": "Replace Attachment Confirmation",
	"replaceAttachment": "Are you sure you want to replace the attachment you selected?",
	"uploadMore": "You can only upload up to {n} attachments",
	"notValidation": "Data validation failed",
	"lineNotValidation": "Line data validation failed",
	"notValidation_number": "Only allow numbers",
	"notAttachmentValidation": "Attachment validation failed.",
	"retractTitle": "Retract Confirmation",
	"retractText": "Are you sure you want to retract this document?",
	"workRetract": "The document has been retract",
	"retractWorkInfor": "You retract the document:",
	"currentActivity": "Current Activity:",
	"currentUser": "Processor:",
	"inputResetPeople": "Please select the person to reset to!",
	"resetTo": "Reset To",
	"reset": "Reset",
	"resetOk": "Document has been reset to",
	"workReset": "Document has been reset",
	"resetWorkInfor": "You reset the document:",
	"workRollback": "Document has been backtracked",
	"rollbackOk": "Document has been backtracked to",
	"rollbackWorkInfor": "You have backtracked the document:",
	"workReroute": "Document has been rerouted",
	"rerouteWorkInfor": "You rerouted a document:",
	"rerouteOk": "Document has been rerouted to:",
	"inputSplitValue": "Please enter or choose to increase the value of the branch",
	"addSplitOk": "The processing branch has been added:",
	"addSplitWork": "Processing branch has been added",
	"addSplitWorkInfor": "You have added a branch to the current work",
	"deleteWorkTitle": "Delete work confirmation",
	"deleteWorkText": {
		"html": "<div style='color: red;'>Note: You are deleting this work, and the work cannot be retrieved after deletion. Are you sure you want to delete this work?</div>",
		"text": "Note: You are deleting this work. The work cannot be retrieved after deletion. Are you sure you want to delete this work?"
	},
	"workDelete": "Work has been deleted",
	"terminateWorkTitle": "Terminate file",
	"terminateWorkText": "Terminating the file means that the file is abandoned and will be transferred directly. ",
	"workTerminate": "The file has been terminated",
	"terminateWork": "Terminate file",
	"amount": "▌Total",
	"sectionAmount": "▌Subtotal",
	"delete": "Delete",
	"add": "Add",
	"addLine": "AddLine",
	"edit": "Edit",
	"completedEdit": "Completed",
	"cancelEdit": "Cancel",
	"mobileGridHelp": "Long press the data area to edit the data<br>Swipe to the left to delete the data",
	"item": "▌Item",
	"all": "All",
	"imageClipper": "Image Editor",
	"noOrgObject": "Unmatched person or organization, click to modify",
	"menu_revisions_show": "ShowTraces",
	"menu_revisions_hide": "HideTraces",
	"menu_fullscreen": "Fullscreen",
	"menu_toolbar_show": "ShowToolbar",
	"menu_toolbar_hide": "HideToolbar",
	"menu_preview": "PrintPreview",
	"menu_redfile": "Red File",
	"menu_seal": "Seal",
	"menu_showHistory": "View history",
	"menu_hideHistory": "Close history",
	"menu_new": "Create Document",
	"menu_openfile": "Open local file",
	"menu_savefile": "Save to local",
	"menu_att": "View Attachment",
	"menu_file": "Open",
	"completed": "Completed",
	"openOfficeInfor": "Click here to open the {type} file",
	"seeVersion": "See Version",
	"selectVersionToRestore": "Please select the text version to be restored:",
	"restoreFile": "Restore",
	"installNTKOWebChromePluginNotice_xpi": "NTKO Web Chrome cross-browser plugin has not been installed. Please click <a href=\"../o2_lib/officecontrol/ntkoplugins.xpi\">install components</a>",
	"installNTKOWebChromePluginNotice_crx": "NTKO Web Chrome cross-browser plugin has not been installed. Please click <a href=\"../o2_lib/officecontrol/ntkoplugins.crx\">install components</a>",
	"showReadCompletedTitle": "Readed Person ",
	"showReadTitle": "Reader",
	"worklogRead": "View read",
	"mediaOpinion_image": "Handwritten Opinion",
	"mediaOpinion_video": "Video Opinion",
	"mediaOpinion_voice": "Voice Opinion",
	"attachmentPermission": "Set attachment permission",
	"attachmentPermissionInfo": "You are setting permissions for the following attachments:",
	"attachmentRead": "Who can view and download this attachment: (if it is not empty, you need to choose to edit and set permissions at the same time)",
	"attachmentEdit": "Who can edit this attachment: (if it is not empty, you need to choose to set permissions at the same time)",
	"attachmentController": "Who can set the permissions of this attachment",
	"attachmentOCRTitle": "Correct the text in the automatically recognized picture",
	"attachmentOCR_saved": "Image text recognition results have been saved",
	"attachmentOrderTitle": "Attachment Order",
	"attachmentOrderUp": "Up",
	"attachmentOrderDown": "Down",
	"attachmentOrderInfo": "Drag the attachment icon, or sort the attachments through the \"Up\" and \"Down\" buttons",
	"autosave": "Auto Save Document",
	"ignore": "Ignore",
	"ANNInput": "Smart input suggested value: ",
	"recover": "Recover Text",
	"notRecover": "Cancel body recovery",
	"doublePage": "Double",
	"singlePage": "Single",
	"editdoc": "EditText",
	"editdocCompleted": "EditComplete",
	"printdoc": "Print",
	"history": "Text Trace",
	"handwrittenApproval": "Handwritten Approval",
	"fullScreen": "FullScreen",
	"returnScreen": "Restore",
	"editdoc_mobile": "Edit",
	"editdocCompleted_mobile": "EditComplete",
	"printdoc_mobile": "Print",
	"history_mobile": "Trace",
	"handwrittenApproval_mobile": "Approval",
	"subformNestedError": "This form has nested subforms, please contact the administrator!",
	"subpageNestedError": "There are nested subpages on this page, please contact the administrator!",
	"subformUniqueError": "The form is embedded with the same subform repeatedly, please contact the administrator!",
	"moduleUniqueError": "The form has a field with the same name, please contact the administrator!",
	"selectEmpower": "Authorized personnel selection",
	"empowerDlgText": "The following personnel have empowered the work, the file will be sent to the empowered person after selection, and the file will be sent to the task person after deselecting",
	"empowerTo": "Empower to",
	"empowerToHtml": "<font style='color:#ff5400;'>{person}</font>({department}) empowered to <font style='color:#ff5400;'>{empowerTo}</font> Processing. ({time})</font>",
	"autoFlowHtml": "The system automatically submitted at: {time}",
	"systemSubmit": "System Automatic Processing",
	"selectAll": "Select All",
	"computePage": "Calculating page breaks, please wait...",
	"keyLockTitle": "File editing is locked",
	"keyLockInfor": "The file is being edited by {name}. You can view the contents of the document and refresh the page to try again later.",
	"year": " Year ",
	"month": " Month ",
	"date": " ",
	"documentEditor": {
		"copies": "",
		"secret": "",
		"priority": "",
		"redHeader": "文件红头",
		"fileno": "[文号]",
		"signerTitle": "签发人：",
		"signer": "[签发人]",
		"subject": "[标题]",
		"mainSend": "[主送单位：]",
		"filetext": "[请在此处编辑正文内容]",
		"attachmentTitle": "附件：",
		"attachment": "[附件]",
		"issuanceUnit": "[发文机关]",
		"issuanceDate": "[成文日期]",
		"annotation": "",
		"copytoTitle": "抄送：",
		"copyto": "[抄送]",
		"editionUnit": "[印发机关]",
		"editionDate": "[印发日期]",
		"historyList": "历史版本文档",
		"attachmentInfor": "[Click here to edit the content of attachments]"
	},
	"documentHistory": {
		"diffContent": "<div>{time}</div>{name} modified content at \"{activity}\"",
		"insertContent": "<div>{time}</div>{name} inserted content at \"{activity}\":",
		"deleteContent": "<div>{time}</div>{name} deleted content at \"{activity}\":",
		"insert": " Insert ",
		"delete": " Deleted ",
		"insertTimes": " Insert at {times} ",
		"deleteTimes": " Deleted {times} ",
		"play": "Play",
		"pause": "Pause",
		"stop": "Stop",
		"next": "Next Modification Record",
		"prev": "Previous Modification Record",
		"exit": "Exit Trace Review",
		"diff_patch_count": "Total {history} versions, {diff} revisions.",
		"original": "Original Version",
		"nodiff": "There is no historical modification information yet",
		"word": " word ",
		"diff": "Contrast",
		"diffTitle": "Compared with the previous version",
		"showAllHistory": "Show All History",
		"showAll": "Show all traces"
	},
	"subjectEmpty": "Subject cannot be empty",
	"issuanceUnitEmpty": "The issuing unit cannot be empty",
	"fullWidth": "The automatic conversion of half-width spaces to full-width spaces is enabled. If you need to enter half-width spaces, please use: SHIFT+space",
	"pauseWork": "The current task has entered the pending state",
	"resumeWork": "The current task has been resumed from the pending state",
	"resume": "Resume",
	"pause": "Pending",
	"selectItemCountNotice": "Please select at least {count} items",
	"setReaded": "Mark as read",
	"readed": "Readed",
	"attachmentArea": "Attachment Area",
	"intelligentCorrection": "Intelligent Error Correction",
	"maxItemCountNotice": "A maximum of {n} items allowed to be added",
	"selectItemNotice": "Please select item",
	"minItemNotice": "At least {n} items need to be kept. The deleted item is less than the item to be kept, please check",
	"deleteSelectedItemNotice": "Are you sure you want to delete the selected item",
	"minItemCountNotice": "Please keep at least {n} items",
	"systemField": "System Field",
	"systemFieldEmptyNotice": "System Field cannot be empty",
	"importTooManyNotice ": " you import {n1} data, allowed to import {n2} data maximum ",
	"importTooFewNotice ": "you import {n1} data, need to keep at least {n2} data ",
	"pleaseSelect": "Please Choose",
	"form": {
		"close": "Close",
		"closeTitle": "Close Document",
		"save": "Save",
		"saveTitle": "Save Document",
		"flow": "Submit",
		"flowTitle": "Submit Document",
		"process": "Submit",
		"processTitle": "Submit Document",
		"submit": "Submit",
		"submitTitle": "Submit Document",
		"reroute": "Reroute",
		"rerouteTitle": "Reroute to other Activity",
		"reset": "Reset",
		"resetTitle": "Reset to other Person",
		"split": "AddSplit",
		"splitTitle": "Add Split Work branch",
		"retract": "Retract",
		"retractTitle": "Retract Task to current person",
		"rollback": "Rollback",
		"rollbackTitle": "Rollback the work to the specified activity, without keeping process records",
		"delete": "Delete",
		"deleteTitle": "Delete Document",
		"terminate": "Terminate",
		"terminateTitle": "End file process",
		"print": "Print",
		"printTitle": "Open through the print form, and print the document",
		"press": "Urge",
		"pressTitle": "Urge",
		"pause": "Pending",
		"pauseTitle": "Set the task as pending",
		"resume": "Resume",
		"resumeTitle": "Resume the task from pending",
		"downloadAll": "Download",
		"downloadAllTitle": "Download the form and all attachments",
		"monitor": "Process Monitor",
		"monitorTitle": "Process Monitor",
		"addTask": "Add Task",
		"addTaskTitle": "Add task to current activity",
		"rerouteActivity": "Activity: ",
		"reroutePerson": "Person: ",
		"selectPerson": "Select",
		"retouteOpinion": "Opinion: ",
		"resetPerson": "Person: ",
		"resetOpinion": "Opinion: ",
		"keepTask": "Keep my task",
		"readedOpinion": "Opinion: ",
		"setReaded": "Mark as read",
		"readed": "Readed",
		"rollbackInfo": "Select the location of the file to be rollback to",
		"addSplitInfo": "Split data according to your business settings. The data should match the split setting in the process. multiple values with a comma (,)",
		"splitValue": "Split by",
		"opinion": "opinion",
		"selectUnit": "Select Unit",
		"excludeBranches": "Exclude existing branches",
		"yes": "Yes",
		"no": "No",
		"readIdentity": "Identity",
		"sendReadNotify": "Send a pending notification",
		"reviewIdentity": "Identity",
		"noTaskToReset": "The current job does not have your task, and the operation cannot be performed",
		"addTaskPerson": "Add Task",
		"addTaskOpinion": "Opinion",
		"addTaskBefore": "Add Task Before",
		"addTaskAfter": "Add Task After",
		"addTaskBeforeTitle": "Add a task before you process",
		"addTaskAfterTitle": "Add a task after you process",
		"addTaskType": "Add Task Type",
		"modeType": "Processing method",
		"single": "single",
		"queue": "serial",
		"parallel": "parallel",
		"addTaskRepeatedTitle": "Repeat Reminder",
		"addTaskRepeatedInfo": "<span class='mainColor_color'><b>{repeated}</b></span>  is already in the list of handlers and will not be processed。",
		"mergeWork": "Merge work",
		"goBack": "return",
		"goBackTitle": "Return to activities that have already passed",
		"goBackActivity": "Return to Activity:",
		"goBackActivityWay": "Post return processing:",
		"goBackActivityWayStep": "Flow normally according to the process",
		"goBackActivityWayJump": "Directly return to the person returning the item",
		"goBackTo": "Return to:",
		"selectGoBackActivity": "Please select the activity to be returned"
	},
	"sendRead": "Send Read",
	"sendReadOk": "Sent Read:",
	"noPermissionOrWorkNotExisted": "You do not have permission or the job does not exist",
	"inputSendReadPeople": "Please select the person",
	"sendReadPeopleCanNotEmpty": "The person cannot be empty",
	"sendReview": "Add Review",
	"sendReviewOk": "Review has been added:",
	"inputSendReviewPeople": "Please select the person",
	"sendReviewPeopleCanNotEmpty": "Please select the person",
	"inputAddTaskPeople": "Please select Person",
	"addTaskOk": "Added Task",
	"addTaskInfor": "You have added task to the file:",
	"applicationNotFound": "App Not Found",
	"pdfview": {
		"nofile": "nofile ,please upload",
		"upload": "upload"
	},
	"ofdview": {
		"nofile": "nofile ,please upload",
		"upload": "upload"
	},
	"onlyoffice": {
		"noInstall": "no install",
		"filetext": "filetext"
	},
	"officeonline": {
		"noInstall": "no install",
		"filetext": "filetext"
	},
	"title": "Title",
	"createTime": "Created Time",
	"creatorPerson": "Creator",
	"creatorUnit": "Create organization",
	"score": "match degree",
	"updateTime": "Update Time",
	"documentType": "Document type",
	"processName": "Process name",
	"draftTime": "Draft time",
	"draftPerson": "Draft person ",
	"categoryName": "Category Name",
	"publishPerson": "Publisher",
	"publishTime": "Publish time",
	"document": "Document",
	"work": "Work",
	"cancelAssociatedTitle": "Disassociate Document",
	"cancelAssociated": "Are you sure you want to cancel the association with document '{title}'?",
	"associatedResult": "Associated Result",
	"selectDocNote": "Please select a document first",
	"associatedDocument": "Associated Document",
	"docDeleted": "The document has been deleted or you do not have permission to open this document.",
	"system": "System",
	"attachmentSecurity": "Attachment classification identification",
	"importTooManyNotice": "{n1} pieces of data were imported this time, and a maximum of {n2} pieces of data are allowed to be imported",
	"importTooFewNotice": "{n1} pieces of data were imported this time, and at least {n2} pieces of data need to be retained",
	"uploading": "Uploading attachment, please wait for the attachment upload to complete before performing this operation.",
	"documentPublished": "Published successfully",
	"documentDelayedPublished": "Timed Published Successfully",
	"firstDate": "First reading time",
	"readDate": "Recent reading time",
	"readCount": "Number of Readings",
	"deleteDocumentTitle": "Confirm Delete Document",
	"deleteDocumentText": {
		"html": "<div style='color: red;'>Note: You are deleting this document, and the document cannot be retrieved after deletion. Are you sure you want to delete this document?</div>"
	},
	"documentDelete": "Document has been deleted",
	"readerFieldNotice": "If not selected, all members will be visible",
	"readedLogTitle": "Reading Log",
	"readedCountText": "Total {person} people, {count} reads",
	"defaultReadedLogText": "<font style='color:#00F;'>{person}</font>({department}) read in <font style='color:#00F'>{date}</font>, A total of <font style='color:#00F'>{count}</font> times",
	"commendLogTitle": "Commend Log",
	"commendLogPerson": "Commend Person",
	"commendCountText": "Total {count} Commend",
	"commendLogTime": "Commend Time",
	"defaultCommendLogText": "<font style='color:#00F;'>{person}</font> Commend in<font style='color:#00F'>{date}</font>",
	"reply": "Comment",
	"commentTitle": "Comment Area",
	"commentCountText": "Total {count} comments",
	"saveComment": "Comment",
	"saveCommentSuccess": "Save Comment Success",
	"deleteCommentTitle": "Delete Comment Confirmation",
	"deleteCommentText": "After deleting a comment, it cannot be restored. Are you sure you want to delete this comment?",
	"deleteCommentSuccess": "Comment deleted successfully",
	"commentFormTitle": "Edit Comment",
	"createCommentSuccess": "Comment created successfully",
	"updateSuccess": "Update successful",
	"save": "Save",
	"setTopTitle": "Put Top Confirmation",
	"setTopText": "Are you sure to put the current document on top?",
	"setTopSuccess": "Put Top Success",
	"cancelTopTitle": "Cancel Top Title Confirmation",
	"cancelTopText": "Are you sure you want to cancel the current document on top?",
	"cancelTopSuccess": "Cancel Top Success",
	"selectAttachment": "Select Attachment",
	"yesterday": "yesterday",
	"theDayBeforeYesterday": "The Day Before yesterday",
	"severalWeekAgo": "{count}weeks ago",
	"severalDayAgo": "{count} days ago",
	"severalHourAgo": "{count}hours ago",
	"severalMintuesAgo": "{count} minutes ago",
	"justNow": "JustNow",
	"commend": {
		"do": "Commend",
		"undo": "Un Commend"
	}
}
MWF.xApplication.cms.Xform["lp."+o2.language] = MWF.xApplication.cms.Xform.LP