MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xDesktop.requireApp("process.Xform", "lp."+MWF.language, null, false);
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Xform = MWF.xApplication.cms.Xform || {};
MWF.xApplication.cms.Xform.LP = Object.merge({}, MWF.xApplication.process.Xform.LP, {
    "dataSaved": "データの保存に成功しました",
	"documentPublished": "公開成功",
	"documentDelayedPublished": "定時公開成功",
	"noSelectRange": "選択範囲を確定できません",
	"begin": "開始",
	"end": "終了",
	"none": "なし",
	"person": "人名",
	"department": "部門",
	"firstDate": "初読み取り日時",
	"readDate": "最終読み取り日時",
	"readCount": "読み取り回数",
	"startTime": "受信日時",
	"completedTime": "処理日時",
	"opinion": "意見",
	"systemProcess": "システム処理",
	"deleteAttachmentTitle": "添付ファイル削除確認",
	"deleteAttachment": "選択した添付ファイルを削除しますか？",
	"replaceAttachmentTitle": "添付ファイル置き換え確認",
	"replaceAttachment": "選択した添付ファイルを置き換えますか？",
	"uploadMore": "最大で {n} 個の添付ファイルをアップロードできます",
	"notValidation": "データ検証に失敗しました",

    "deleteDocumentTitle": "文書削除確認",
	"deleteDocumentText": {"html": "<div style='color: red;'>注意：この文書を削除すると、復元できなくなります。このファイルを削除しますか？</div>"},
	"documentDelete": "文書が削除されました",
	"readerFieldNotice": "選択しないと全員が閲覧できます",
	"readedLogTitle": "読み取り履歴",
	"readedCountText": "{person}人、{count}回読み取り",
	"defaultReadedLogText": "<font style='color:#00F;'>{person}</font>（{department}）が<font style='color:#00F'>{date}</font>に読み取り、合計<font style='color:#00F'>{count}</font>回",
	"commendLogTitle": "いいね履歴",
	"commendLogPerson": "いいねした人",
	"commendLogTime": "いいねした時間",
	"commendCountText": "合計{count}回いいね",
	"defaultCommendLogText": "<font style='color:#00F;'>{person}</font>が<font style='color:#00F'>{date}</font>にいいね",
	"reply": "コメント",
	"commentTitle": "コメントエリア",
	"commentCountText": "合計{count}回コメント",
	"saveComment": "コメントを投稿",
	"saveCommentSuccess": "コメントが成功裏に投稿されました",
	"deleteCommentTitle": "コメント削除確認",
	"deleteCommentText": "コメントを削除すると元に戻すことはできません。このコメントを削除しますか？",
	"deleteCommentSuccess": "コメントが成功裏に削除されました",
	"commentFormTitle": "コメントの編集",
	"createCommentSuccess": "コメントが成功裏に作成されました",
	"updateSuccess": "更新成功",
	"save": "保存",

    "setTopTitle": "トップに固定確認",
	"setTopText": "現在の文書をトップに固定しますか？",
	"setTopSuccess": "トップに固定しました",
	"cancelTopTitle": "トップ固定解除確認",
	"cancelTopText": "現在の文書のトップ固定を解除しますか？",
	"cancelTopSuccess": "トップ固定が解除されました",
	"attachmentArea": "添付ファイル領域",
	"selectAttachment": "添付ファイルを選択",
	"yesterday": "昨日",
	"theDayBeforeYesterday": "一昨日",
	"severalWeekAgo": "{count}週間前",
	"severalDayAgo": "{count}日前",
	"severalHourAgo": "{count}時間前",
	"severalMintuesAgo": "{count}分前",
	"justNow": "たった今",
	"commend": {
		"do": "いいね",
		"undo": "いいね解除"
	},
    "form": {
		"close": "閉じる",
		"closeTitle": "文書を閉じる",
		"edit": "編集",
		"editTitle": "文書を編集",
		"save": "保存",
		"saveTitle": "文書を保存",
		"publish": "公開",
		"publishTitle": "文書を公開",
		"publishDelayed": "定時公開",
		"publishDelayedTitle": "定時公開文書",
		"saveDraft": "下書き保存",
		"saveDraftTitle": "下書き保存文書",
		"popular": "ホット設定",
		"popularTitle": "ホット設定文書",
		"delete": "削除",
		"deleteTitle": "文書を削除",
		"print": "印刷",
		"printTitle": "文書を印刷",
		"setTop": "トップに固定",
		"setTopTitle": "文書をトップに固定",
		"cancelTop": "トップ固定解除",
		"cancelTopTitle": "文書のトップ固定を解除"
	}

    //"at" : "阅于",
    //"readdDocument" : "，",
    //"historyRead" : "共",
    //"times" : "次"
});
MWF.xApplication.cms.Xform["lp."+o2.language] = MWF.xApplication.cms.Xform.LP;
