MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xDesktop.requireApp("process.Xform", "lp."+MWF.language, null, false);
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Xform = MWF.xApplication.cms.Xform || {};
MWF.xApplication.cms.Xform.LP = Object.merge({}, MWF.xApplication.process.Xform.LP, {
    "dataSaved": "데이터 저장이 성공했습니다.",
	"documentPublished": "게시 성공",
	"documentDelayedPublished": "예약 게시 성공",
	"noSelectRange": "선택 범위를 확인할 수 없습니다.",
	"begin": "시작",
	"end": "종료",
	"none": "없음",
	"person": "사용자 이름",
	"department": "부서",
	"firstDate": "최초 읽은 시간",
	"readDate": "최근 읽은 시간",
	"readCount": "읽은 횟수",
	"startTime": "받은 시간",
	"completedTime": "처리 시간",
	"opinion": "의견",
	"systemProcess": "시스템 처리",
	"deleteAttachmentTitle": "첨부 파일 삭제 확인",
	"deleteAttachment": "선택한 첨부 파일을 삭제하시겠습니까?",
	"replaceAttachmentTitle": "첨부 파일 교체 확인",
	"replaceAttachment": "선택한 첨부 파일을 교체하시겠습니까?",
	"uploadMore": "최대 {n} 개의 첨부 파일을 업로드할 수 있습니다.",
	"notValidation": "데이터 유효성 검사 실패",

    "deleteDocumentTitle": "문서 삭제 확인",
	"deleteDocumentText": {"html": "<div style='color: red;'>주의: 이 문서를 삭제하고 나면 복구할 수 없습니다. 이 파일을 삭제하시겠습니까?</div>"},
	"documentDelete": "문서가 삭제되었습니다",
	"readerFieldNotice": "선택하지 않으면 모든 사용자가 볼 수 있습니다",
	"readedLogTitle": "읽음 기록",
	"readedCountText": "{person}명, {count}회 읽음",
	"defaultReadedLogText": "<font style='color:#00F;'>{person}</font> ({department})님이 <font style='color:#00F'>{date}</font>에 읽음, 총 <font style='color:#00F'>{count}</font>회",
	"commendLogTitle": "추천 기록",
	"commendLogPerson": "추천한 사용자",
	"commendLogTime": "추천한 시간",
	"commendCountText": "총 {count}회 추천",
	"defaultCommendLogText": "<font style='color:#00F;'>{person}</font>님이 <font style='color:#00F'>{date}</font>에 추천함",
	"reply": "댓글",
	"commentTitle": "댓글 영역",
	"commentCountText": "총 {count}회 댓글",
	"saveComment": "댓글 등록",
	"saveCommentSuccess": "댓글이 성공적으로 게시되었습니다",
	"deleteCommentTitle": "댓글 삭제 확인",
	"deleteCommentText": "댓글을 삭제하면 복구할 수 없습니다. 이 댓글을 삭제하시겠습니까?",
	"deleteCommentSuccess": "댓글이 성공적으로 삭제되었습니다",
	"commentFormTitle": "댓글 수정",
	"createCommentSuccess": "댓글이 성공적으로 생성되었습니다",
	"updateSuccess": "업데이트 성공",
	"save": "저장",

    "setTopTitle": "상단에 고정 확인",
	"setTopText": "현재 문서를 상단에 고정하시겠습니까?",
	"setTopSuccess": "상단에 고정되었습니다",
	"cancelTopTitle": "고정 해제 확인",
	"cancelTopText": "현재 문서의 상단 고정을 해제하시겠습니까?",
	"cancelTopSuccess": "상단 고정이 해제되었습니다",
	"attachmentArea": "첨부 파일 영역",
	"selectAttachment": "첨부 파일 선택",
	"yesterday": "어제",
	"theDayBeforeYesterday": "그제",
	"severalWeekAgo": "{count} 주 전",
	"severalDayAgo": "{count} 일 전",
	"severalHourAgo": "{count} 시간 전",
	"severalMintuesAgo": "{count} 분 전",
	"justNow": "지금",
	"commend": {
		"do": "좋아요",
		"undo": "좋아요 취소"
	},
	"form": {
		"close": "닫기",
		"closeTitle": "문서 닫기",
		"edit": "편집",
		"editTitle": "문서 편집",
		"save": "저장",
		"saveTitle": "문서 저장",
		"publish": "게시",
		"publishTitle": "문서 게시",
		"publishDelayed": "예약 게시",
		"publishDelayedTitle": "예약 게시 문서",
		"saveDraft": "임시 저장",
		"saveDraftTitle": "임시 저장 문서",
		"popular": "인기 설정",
		"popularTitle": "인기 설정 문서",
		"delete": "삭제",
		"deleteTitle": "문서 삭제",
		"print": "인쇄",
		"printTitle": "문서 인쇄",
		"setTop": "상단 고정",
		"setTopTitle": "문서 상단 고정",
		"cancelTop": "상단 고정 해제",
		"cancelTopTitle": "문서 상단 고정 해제"
	}

    //"at" : "阅于",
    //"readdDocument" : "，",
    //"historyRead" : "共",
    //"times" : "次"
});
MWF.xApplication.cms.Xform["lp."+o2.language] = MWF.xApplication.cms.Xform.LP;
