MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Xform = MWF.xApplication.process.Xform || {};
MWF.xDesktop.requireApp("process.Xform", "lp."+MWF.language, null, false);
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Xform = MWF.xApplication.cms.Xform || {};
MWF.xApplication.cms.Xform.LP = Object.merge({}, MWF.xApplication.process.Xform.LP, {
    "dataSaved": "數據保存成功",
	"documentPublished": "發佈成功",
	"documentDelayedPublished": "定時發佈成功",
	"noSelectRange": "無法確定選擇範圍",
	"begin": "起",
	"end": "止",
	"none": "無",
	"person": "人員名稱",
	"department": "單位",
	"firstDate": "首次閱讀時間",
	"readDate": "最近閱讀時間",
	"readCount": "閱讀次數",
	"startTime": "收到時間",
	"completedTime": "處理時間",
	"opinion": "意見",
	"systemProcess": "系統處理",
	"deleteAttachmentTitle": "刪除附件確認",
	"deleteAttachment": "是否確定刪除您選中的附件？",
	"replaceAttachmentTitle": "替換附件確認",
	"replaceAttachment": "是否確定替換您選中的附件？",
	"uploadMore": "您最多只允許上傳 {n} 個附件",
	"notValidation": "數據校驗未通過",

    "deleteDocumentTitle": "刪除文件確認",
	"deleteDocumentText": {"html": "<div style='color: red;'>注意：您正在刪除此文件，刪除後文件無法找回，您確認要刪除此文件？</div>"},
	"documentDelete": "已經刪除文件",
	"readerFieldNotice": "不選則全員可見",
	"readedLogTitle": "閱讀記錄",
	"readedCountText": "共{person}人、{count}次閱讀",
	"defaultReadedLogText": "<font style='color:#00F;'>{person}</font>（{department}） 閱於<font style='color:#00F'>{date}</font>，共<font style='color:#00F'>{count}</font>次",
	"commendLogTitle": "點讚記錄",
	"commendLogPerson": "點讚人員",
	"commendLogTime": "點讚時間",
	"commendCountText": "共{count}次點讚",
	"defaultCommendLogText": "<font style='color:#00F;'>{person}</font> 點讚於<font style='color:#00F'>{date}</font>",
	"reply": "評論",
	"commentTitle": "評論區域",
	"commentCountText": "共{count}次評論",
	"saveComment": "發表評論",
	"saveCommentSuccess": "發布評論成功",
	"deleteCommentTitle": "刪除評論確認",
	"deleteCommentText": "刪除評論後不能恢復，您確定要刪除此評論？",
	"deleteCommentSuccess": "刪除評論成功",
	"commentFormTitle": "編輯評論",
	"createCommentSuccess": "創建評論成功",
	"updateSuccess": "更新成功",
	"save": "保存",

    "setTopTitle": "置頂確認",
	"setTopText": "確定將當前文件置頂？",
	"setTopSuccess": "已置頂成功",
	"cancelTopTitle": "取消置頂確認",
	"cancelTopText": "確定取消當前文件的置頂？",
	"cancelTopSuccess": "已取消置頂成功",
	"attachmentArea": "附件區域",
	"selectAttachment": "選擇附件",
	"yesterday": "昨天",
	"theDayBeforeYesterday": "前天",
	"severalWeekAgo": "{count}週前",
	"severalDayAgo": "{count}天前",
	"severalHourAgo": "{count}小時前",
	"severalMintuesAgo": "{count}分鐘前",
	"justNow": "剛才",
	"commend": {
		"do": "讚好",
		"undo": "取消讚好"
	},
    "form": {
		"close": "關閉",
		"closeTitle": "關閉文件",
		"edit": "編輯",
		"editTitle": "編輯文件",
		"save": "保存",
		"saveTitle": "保存文件",
		"publish": "發布",
		"publishTitle": "發布文件",
		"publishDelayed": "定時發布",
		"publishDelayedTitle": "定時發布文件",
		"saveDraft": "保存草稿",
		"saveDraftTitle": "保存草稿文件",
		"popular": "設置熱點",
		"popularTitle": "設置熱點文件",
		"delete": "刪除",
		"deleteTitle": "刪除文件",
		"print": "列印",
		"printTitle": "列印文件",
		"setTop": "置頂",
		"setTopTitle": "對文件置頂",
		"cancelTop": "取消置頂",
		"cancelTopTitle": "取消對文件的置頂"
	}

    //"at" : "阅于",
    //"readdDocument" : "，",
    //"historyRead" : "共",
    //"times" : "次"
});
MWF.xApplication.cms.Xform["lp."+o2.language] = MWF.xApplication.cms.Xform.LP;
