MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Application = MWF.xApplication.process.Application || {};
MWF.xApplication.process.Application.LP={
	"title": "Process Application",
	"mywork": "My work",
	"adminwork": "Maintenance Management",
	"task": "To Do",
	"taskDone": "Done",
	"read": "to be read",
	"readDone": "read",
	"workLog": "Flow Log",
	"review": "Review",
	"draft": "Draft",
	"attachment": "Attachment",
	"businessData": "Business Data",
	"dataRecord": "Data Record",
	"work": "Working in Circulation",
	"workcompleted": "Work Completed",
	"workdelete": "Work deleted",
	"dict": "Data configuration",
	"serial": "Numbering configuration",
	"startProcess": "Start Process",
	"query": "Search",
	"reset": "Reset",
	"noFile": "No file yet",
	"actionList": {
		"delete": "Delete",
		"processing": "Attempt to transfer",
		"addReview": "Add Review",
		"endWork": "End Process",
		"jump": "Scheduling",
		"manage": "Maintenance",
		"sendRead": "Send for reading",
		"setSerial": "Modify the serial number",
		"add": "Add",
		"rollback": "rollback",
		"delSnap": "Delete completely",
		"restore": "Restore"
	},
	"subject": "Title",
	"name": "name",
	"alias": "alias",
	"desc": "description",
	"activity": "link",
	"createunit": "Drafting Department",
	"creator": "Writer",
	"currentPerson": "Processing Person",
	"readPerson": "Person to read",
	"currentDept": "Dept",
	"process": "Process",
	"begin": "Start Date",
	"end": "End Date",
	"createTime": "Create Time",
	"completedTime": "Completed Time",
	"deleteTime": "Delete Time",
	"updateTime": "Update Time",
	"startTime": "Arrival Time",
	"endTime": "Processing time",
	"routerName": "Submit route",
	"idea": "opinion",
	"editIdea": "Comment modification",
	"allFile": "All files",
	"firstPage": "First Page",
	"lastPage": "Last Page",
	"reroute": "Scheduling",
	"rollback": "rollback",
	"noItem": "No data is queried under the current conditions",
	"cancel": "Cancel",
	"tip": "Tips",
	"tip_remove": "Are you sure to delete?",
	"tip_reset": "Transfer Confirmation",
	"tip_keetask": "Please choose whether to keep your to-do or not!",
	"rest_content": " Transfer to: (name)<br/>Do you keep your to-do?<br/><br/><input type='radio' value='yes' name='reset_keep'/>Reserved <br/><input type='radio' value='no' name='reset_keep'/>No reservation<br>Comments: <textarea class='textarea' name='reset_idea' cols='40' style=' width:200px'></textarea><br><div id='reset_checkInfor'></div>",
	"close": "close",
	"ok": "OK",
	"edit": "edit",
	"remove": "Remove",
	"action": "action",
	"modify": "modify",
	"copy": "copy",
	"view": "View",
	"setOpinion": "Opinion Modification",
	"recordEdit": "Process record modification",
	"recordAdd": "Process record add",
	"reviewitem": "Review people list",
	"flow": "flow",
	"readFlow": "Ready to be read",
	"resetAction": "Transfer",
	"addSign": "Add Sign",
	"resetActionFor": "Transfer to",
	"readProcess": "Pending read processing",
	"editAction": "Maintenance",
	"unnamed": "No Title",
	"fieldName": "Field ",
	"op": "operation",
	"dataRecordView": {
		"record": "Record",
		"title": "View",
		"person": "Person",
		"time": "Time",
		"active": "Activity",
		"old": "Old",
		"new": "New"
	}
}
MWF.xApplication.process.Application["lp."+o2.language] = MWF.xApplication.process.Application.LP