MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.Application = MWF.xApplication.process.Application || {};
MWF.xApplication.process.Application.LP={
	"title": "App de flujo",
	"mywork": "Mi trabajo",
	"adminwork": "Mant. y gestión",
	"task": "Tareas pend",
	"taskDone": "Tareas comp",
	"read": "Lecturas pend",
	"readDone": "Lecturas comp",
	"workLog": "Reg. trabajo",
	"review": "Revisión",
	"draft": "Borrador",
	"attachment": "Adjunto",
	"businessData": "Datos negocio",
	"dataRecord": "Registro de Datos",
	"work": "Trabajo en progreso",
	"workcompleted": "Trabajos completados",
	"workdelete": "Trabajos eliminados",
	"dict": "Config. de datos",
	"serial": "Config. numérica",
	"startProcess": "Crear tarea",
	"query": "Buscar",
	"reset": "Reiniciar",
	"noFile": "Sin archivos",
	"actionList": {
		"delete": "Eliminar",
		"processing": "Intentar flujo",
		"addReview": "Agregar revisión",
		"endWork": "Finalizar proceso",
		"jump": "Despachar",
		"manage": "Mantenimiento",
		"sendRead": "Enviar a lectura",
		"setSerial": "Modificar número de serie",
		"add": "Agregar",
		"rollback": "Retroceder",
		"delSnap": "Eliminar definitivamente",
		"restore": "Restaurar"
	},
	"subject": "Asunto",
	"name": "Nombre",
	"alias": "Alias",
	"desc": "Descripción",
	"activity": "Actividad",
	"createunit": "Dept. de origen",
	"creator": "Creador",
	"currentPerson": "Pers. encargada",
	"readPerson": "Pers. en espera",
	"currentDept": "Dept",
	"process": "Proceso",
	"begin": "Fecha de inicio",
	"end": "Fecha de finalización",
	"createTime": "Fecha/hora de creación",
	"completedTime": "Fecha/hora de finalización",
	"deleteTime": "Fecha/hora de eliminación",
	"updateTime": "Fecha/hora de actualización",
	"startTime": "Hora de llegada",
	"endTime": "Hora de procesamiento",
	"routerName": "Ruta de envío",
	"idea": "Comentarios",
	"editIdea": "Modificar comentarios",
	"allFile": "Todos los archivos",
	"firstPage": "Primera",
	"lastPage": "Última",
	"reroute": "Reencaminar",
	"rollback": "Retroceder",
	"noItem": "No se encontraron datos con los criterios de búsqueda actuales",
	"cancel": "Cancelar",
	"tip": "Consejo",
	"tip_remove": "¿Está seguro de que desea eliminar?",
	"tip_reset": "Confirmación para reenviar",
	"tip_keetask": "Seleccione si desea conservar su propia tarea pendiente",
	"rest_content": " Enviar a:(name)<br/> ¿Desea conservar su propia tarea pendiente? <br/><br/><input type='radio' value='yes' name='reset_keep'/>Sí<br/><input type='radio' value='no' name='reset_keep'/>No<br>Comentarios: <textarea class='textarea' name='reset_idea' cols='40' style='width:200px'></textarea><br><div id='reset_checkInfor'></div>",
	"close": "Cerrar",
	"ok": "Aceptar",
	"edit": "Editar",
	"remove": "Eliminar",
	"action": "Acción",
	"modify": "Modificar",
	"copy": "Copiar",
	"view": "Ver",
	"setOpinion": "Modificar comentarios",
	"recordEdit": "Modificar registro de proceso",
	"recordAdd": "Agregar registro de proceso",
	"reviewitem": "Lista de personas a consultar",
	"flow": "Transferencia",
	"readFlow": "Pasar de pendiente a leído",
	"resetAction": "Reenviar",
	"addSign": "Agregar Firma",
	"resetActionFor": "Enviar a",
	"readProcess": "Procesar pendiente",
	"editAction": "Mantenimiento",
	"unnamed": "Sin título",
	"fieldName": "Feild ",
	"op": "Actividades",
	"dataRecordView": {
		"record": "registro",
		"title": "ver",
		"person": "persona",
		"time": "tiempo",
		"active": "activo",
		"old": "viejo",
		"new": "nuevo"
	}
}
MWF.xApplication.process.Application["lp."+o2.language] = MWF.xApplication.process.Application.LP