MWF.xApplication.process.Application.LP = {
	"title": "프로세스 애플리케이션",
	"mywork": "내 작업",
	"adminwork": "관리 작업",
	"task": "대기",
	"taskDone": "완료됨",
	"read": "대기 중 읽기",
	"readDone": "완료된 읽기",
	"workLog": "흐름 기록",
	"review": "검토",
	"draft": "초안",
	"attachment": "첨부 파일",
	"businessData": "비즈니스 데이터",
	"dataRecord": "변경 기록",
	"work": "진행 중인 작업",
	"workcompleted": "완료된 작업",
	"workdelete": "삭제된 작업",
	"dict": "데이터 설정",
	"serial": "일련 번호 설정",
	"startProcess": "프로세스 시작",
	"query": "검색",
	"reset": "초기화",
	"noFile": "파일 없음",
	"actionList": {
		"delete": "삭제",
		"processing": "시도 중인 흐름",
		"addReview": "검토 추가",
		"endWork": "프로세스 종료",
		"jump": "스케줄",
		"manage": "유지 관리",
		"sendRead": "읽을 예정으로 보내기",
		"setSerial": "일련 번호 수정",
		"add": "새로 추가",
		"rollback": "되돌아가기",
		"delSnap": "완전히 삭제",
		"restore": "복원"
	},

	"subject": "제목",
	"name": "이름",
	"alias": "별명",
	"desc": "설명",
	"activity": "단계",
	"createunit": "작성 부서",
	"creator": "작성자",
	"currentPerson": "담당자",
	"readPerson": "미확인 사용자",
	"currentDept": "부서",
	"process": "프로세스",
	"begin": "시작 날짜",
	"end": "종료 날짜",
	"createTime": "생성 시간",
	"completedTime": "완료 시간",
	"deleteTime": "삭제 시간",
	"updateTime": "업데이트 시간",
	"startTime": "도착 시간",
	"endTime": "처리 시간",
	"routerName": "제출 경로",
	"idea": "의견",
	"editIdea": "의견 수정",
	"allFile": "모든 파일",
	"firstPage": "첫 번째 페이지",
	"lastPage": "마지막 페이지",
	"reroute": "재배치",
	"rollback": "롤백",
	"noItem": "현재 조건에서 데이터를 찾을 수 없습니다",


	"cancel": "취소",
	"tip": "알림",
	"tip_remove": "삭제하시겠습니까?",
	"tip_reset": "재할당 확인",
	"tip_keetask": "자신의 업무를 보류할 지 선택하십시오!",
	"rest_content": "전달 대상: (name)<br/>자신의 업무를 보류할 지 여부를 선택하십시오.<br/><br/><input type='radio' value='yes' name='reset_keep'/>보류함<br/><input type='radio' value='no' name='reset_keep'/>보류하지 않음<br>의견:<textarea class='textarea' name='reset_idea' cols='40' style='width:200px'></textarea><br><div id='reset_checkInfor'></div>",
	"close": "닫기",
	"ok": "확인",
	"edit": "편집",
	"remove": "삭제",
	"action": "작업",
	"modify": "수정",
	"copy": "복사",
	"view": "보기",
	"setOpinion": "의견 수정",
	"recordEdit": "프로세스 레코드 수정",
	"recordAdd": "프로세스 레코드 추가",
	"reviewitem": "검토자 목록",
	"flow": "흐름",
	"readFlow": "미확인에서 확인으로 변환",
	"resetAction": "재할당",
	"resetActionFor": "전달 대상",
	"readProcess": "미확인 처리",
	"editAction": "유지",
	"unnamed": "제목 없음",
	"fieldName": "필드 이름",
	"op": "작업",
	"dataRecordView": {
		"record": "변경 기록",
		"title": "보기",
		"person": "변경자",
		"time": "시간",
		"active": "단계",
		"old": "이전",
		"new": "이후"
	}

};
