MWF.xApplication.process.Application.LP = {
    "title": "ຂະບວນການຄໍາຮ້ອງສະຫມັກ",

    "mywork" : "ວຽກຂອງຂ້ອຍ",
    "adminwork" : "ການຄຸ້ມຄອງບໍາລຸງຮັກສາ",
    "task": "ເຮັດ",
    "taskDone": "ແລ້ວໆ",
    "read": "ອ່ານ",
    "readDone": "ອ່ານ",
    "workLog" : "ບັນທຶກການໄຫຼເຂົ້າ",
    "review" : "ທົບທວນ",
    "draft" : "ຮ່າງ",
    "attachment" : "ແນບ",
    "businessData" : "ຂໍ້ມູນທຸລະກິດ",
    "dataRecord" : "ບັນທຶກຂໍ້ມູນ",
    "work" : "ເຮັດວຽກໃນການໄຫຼວຽນ",
    "workcompleted" : "ວຽກສຳເລັດ",
    "workdelete" : "ວຽກຖືກລົບ",
    "draft" : "ຮ່າງ",
    "dict": "ການຕັ້ງຄ່າຂໍ້ມູນ",
    "serial" : "ການກຳນົດຄ່າຕົວເລກ",
    "startProcess" : "ຂະບວນການເລີ່ມຕົ້ນ",

    "query": "ຄົ້ນຫາ",
    "reset": "ຣີເຊັດ",
    "noFile" : "ຍັງບໍ່ມີໄຟລ໌",

    "actionList" : {
        "delete": "ລົບ",
        "processing" : "ພະຍາຍາມໂອນຍ້າຍ",
        "addReview" : "ຕື່ມການທົບທວນຄືນ",
        "endWork": "ຂະບວນການສິ້ນສຸດ",
        "jump" : "ການກຳນົດເວລາ",
        "manage" : "ການບຳລຸງຮັກສາ",
        "sendRead" : "ສົ່ງສໍາລັບການອ່ານ",
        "setSerial" : "ປັບປ່ຽນເລກລຳດັບ",
        "add": "ເພີ່ມ",
        "rollback": "ຍ້ອນກັບ",
        "delSnap" : "ລົບທັງໝົດ",
        "restore": "ຟື້ນຟູ"
    },

    "subject": "ຫົວຂໍ້",
    "name": "ຊື່",
    "alias": "ນາມແຝງ",
    "desc": "ຄໍາອະທິບາຍ",
    "activity": "ການເຊື່ອມຕໍ່",
    "createunit" : "ກົມສ້າງຕັ້ງ",
    "creator": "ນັກຂຽນ",
    "currentPerson" : "ຜູ້ປະມວນຜົນ",
    "readPerson": "ຄົນທີ່ຈະອ່ານ",
    "currentDept" : "ກົມ",
    "ຂະບວນການ" : "ຂະບວນການ",
    "begin" : "ວັນທີເລີ່ມຕົ້ນ",
    "end": "ວັນທີສິ້ນສຸດ",
    "createTime" : "ສ້າງເວລາ",
    "completedTime" : "ເວລາສຳເລັດ",
    "deleteTime": "ລົບເວລາ",
    "updateTime": "ເວລາອັບເດດ",
    "startTime" : "ເວລາມາຮອດ",
    "endTime" : "ເວລາປະມວນຜົນ",
    "routerName" : "ສົ່ງເສັ້ນທາງ",
    "idea": "ຄວາມຄິດເຫັນ",
    "editIdea" : "ການດັດແກ້ຄຳເຫັນ",
    "allFile" : "ໄຟລ໌ທັງໝົດ",



    "firstPage": "ໜ້າທຳອິດ",
    "lastPage": "ໜ້າສຸດທ້າຍ",

    "reroute" : "ການກຳນົດເວລາ",
    "rollback": "ຍ້ອນກັບ",
    "noItem": "ບໍ່ມີຂໍ້ມູນຖືກສອບຖາມພາຍໃຕ້ເງື່ອນໄຂປະຈຸບັນ",


    "cancel": "ຍົກເລີກ",
    "tip": "ເຄັດລັບ",
    "tip_remove" : "ເຈົ້າແນ່ໃຈບໍ່ວ່າລຶບ?",
    "tip_reset" : "ການຢືນຢັນການໂອນຍ້າຍ",
    "tip_keetask" : "ກະລຸນາເລືອກວ່າຈະຮັກສາສິ່ງທີ່ຕ້ອງເຮັດຫຼືບໍ່!",
    "rest_content" : " ໂອນໄປທີ່: (ຊື່)<br/>ເຈົ້າຮັກສາສິ່ງທີ່ຕ້ອງເຮັດຂອງເຈົ້າໄວ້ບໍ?<br/><br/><input type='radio' value='yes' name='reset_keep'/> ສະຫງວນໄວ້ <br/><input type='radio' value='no' name='reset_keep'/>ບໍ່ມີການຈອງ<br>ຄຳເຫັນ: <textarea class='textarea' name='reset_idea' cols='40' style= ' width:200px'></textarea><br><div id='reset_checkInfor'></div>",
    "close": "ປິດ",
    "ok" : "ຕົກລົງ",
    "edit" : "ແກ້ໄຂ",
    "remove" : "ຍ້າຍ",
    "action" : "ການກະທຳ",
    "modify": "ປັບປ່ຽນ",
    "copy": "ສຳເນົາ",
    "view": "ເບິ່ງ",
    "setOpinion" : "ການດັດແກ້ຄວາມຄິດເຫັນ",
    "recordEdit" : "ຂະບວນການດັດແກ້ບັນທຶກ",
    "recordAdd" : "ຂະບວນການເພີ່ມບັນທຶກ",
    "reviewitem" : "ທົບທວນລາຍຊື່ຄົນ",
    "flow": "ໄຫຼ",
    "readFlow" : "ພ້ອມທີ່ຈະອ່ານ",
    "resetAction" : "ໂອນຍ້າຍ",
    "resetActionFor" : "ໂອນໄປ",
    "readProcess" : "ການປະມວນຜົນການອ່ານທີ່ລໍຖ້າຢູ່",
    "editAction" : "ການບຳລຸງຮັກສາ",

    "unnamed" : "ບໍ່ມີຊື່",
    "fieldName": "ພາກສະຫນາມ",
    "op": "ການດໍາເນີນງານ",
    "dataRecordView" : {

        "record" : "ບັນທຶກ",
        "title" : "ເບິ່ງ",
        "person" : "ບຸກຄົນ",
        "time" : "ເວລາ",
        "active" : "ການເຄື່ອນໄຫວ",
        "old" : "ເກົ່າ",
        "new" : "ໃຫມ່"
    }
};
