MWF.xApplication.process.Application.LP = {
	"title": "流程应用",

	"mywork" : "我的工作",
	"adminwork" : "维护管理",
	"task" : "待办",
	"taskDone" : "已办",
	"read" : "待阅",
	"readDone" : "已阅",
	"workLog" : "流转记录",
	"review" : "参阅",
	"draft" : "草稿",
	"attachment" : "附件",
	"businessData" : "业务数据",
	"work" : "流转中工作",
	"workcompleted" : "已完成工作",
	"workdelete" : "已删除工作",
	"draft" : "草稿",
	"dict" : "数据配置",
	"serial" : "编号配置",
	"startProcess" : "发起流程",
	"index": "索引",

	"query": "搜索",
	"reset": "重置",
	"noFile" : "暂无文件",

	"actionList" : {
		"delete" : "删除",
		"processing" : "尝试流转",
		"addReview" : "增加参阅",
		"endWork" : "结束流程",
		"jump" : "调度",
		"manage" : "维护",
		"sendRead" : "发送待阅",
		"setSerial" : "修改流水号",
		"add" : "新增",
		"rollback" : "回溯",
		"delSnap" : "彻底删除",
		"restore" : "恢复"
 	},

	"subject" : "标题",
	"name" :  "名称",
	"alias" : "别名",
	"desc" : "描述",
	"activity" : "环节",
	"createunit" : "拟稿部门",
	"creator" : "拟稿人",
	"currentPerson" : "处理人",
	"readPerson" : "待阅人",
	"currentDept" : "部门",
	"process" : "流程",
	"begin" : "开始日期",
	"end" : "结束日期",
	"createTime" : "创建时间",
	"completedTime" : "完成时间",
	"deleteTime" : "删除时间",
	"updateTime" : "更新时间",
	"startTime" : "到达时间",
	"endTime" : "处理时间",
	"routerName" : "提交路径",
	"idea" : "意见",
	"editIdea" : "意见修改",
	"allFile" : "全部文件",



	"firstPage": "第一页",
	"lastPage": "最后一页",

	"reroute" : "调度",
	"rollback" : "回溯",
	"noItem": "当前条件下没有查询到数据",


	"cancel" : "取消",
	"tip" : "提示",
	"tip_remove" : "确认是否删除?",
	"tip_reset" : "转交确认",
	"tip_keetask" : "请选择是否保留自身待办！",
	"rest_content"  : " 转交给：(name)<br/>您是否保留自身待办？ <br/><br/><input type='radio' value='yes' name='reset_keep'/>保留<br/><input type='radio' value='no' name='reset_keep'/>不保留<br>意见：<textarea class='textarea' name='reset_idea' cols='40' style='width:200px'></textarea><br><div id='reset_checkInfor'></div>",
	"close" : "关闭",
	"ok" : "确定",
	"edit" : "编辑",
	"remove" : "删除",
	"action" : "操作",
	"modify" : "修改",
	"copy" : "拷贝",
	"view": "查看",
	"setOpinion" : "意见修改",
	"recordEdit" : "流程记录修改",
	"recordAdd" : "流程记录新增",
	"reviewitem" : "参阅人员列表",
	"flow": "流转",
	"readFlow" : "待阅转已阅",
	"resetAction" : "转交",
	"resetActionFor" : "转交给",
	"readProcess" : "待阅处理",
	"editAction" : "维护",


	"more": "更多",
    "collapse": "收起",
    "multiSelect": "多选",
    "export": "导出",
    "moreFilter": "更多筛选条件",
    "collapseFilter": "收起筛选条件",

	"rangeSeparator": "至",
    "startPlaceholder": "开始时间",
    "endPlaceholder": "结束时间",
    "to": "到",
    "min": "最小值",
    "max": "最大值",
    "fromValue": "起始值",
    "toValue": "结束值",
    "minGreatThanMaxError": "起始值不能大于结束值",
    "tooMinError": "不能小于最小值",
    "tooMaxError": "不能大于最大值",
    "moreFieldSelect": "更多列选择",
    "collapseFieldSelect": "收起列选择",

	"category": "分类",
	"createTimeMonth": "创建月份",
	"updateTimeMonth": "更新月份",
	"creatorPerson": "创建者",
	"creatorUnit": "部门",

	"fieldSelect": "列选择",
	"docTotalInfor": "为您找到相关结果<span class='mainColor_color'>{count}</span>个，耗时{time}秒",


};
