MWF.xApplication.process = MWF.xApplication.process || {};
MWF.APPFD = MWF.xApplication.process.FormDesigner = MWF.xApplication.process.FormDesigner || {};
MWF.xApplication.process.FormDesigner.Module = MWF.xApplication.process.FormDesigner.Module || {};
MWF.xDesktop.requireApp("process.FormDesigner", "lp."+MWF.language, null, false);
//MWF.require("MWF.widget.Macro", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Form", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Label", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Div", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Textfield", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Number", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Personfield", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Calendar", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Textarea", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Select", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Radio", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Checkbox", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Combox", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Address", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Button", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Actionbar", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Sidebar", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Image", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.ImageClipper", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Table", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Datagrid", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Subform", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.ViewSelector", null, false); 
MWF.xDesktop.requireApp("process.FormDesigner", "Module.View", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Stat", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Html", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Common", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Tab", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Tree", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Log", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Monitor", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Iframe", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Documenteditor", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Htmleditor", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Office", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Attachment", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Orgfield", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Org", null, false);
MWF.xDesktop.requireApp("process.FormDesigner", "Module.Opinion", null, false);
