MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.query = MWF.xApplication.query || {};
MWF.xApplication.query.ImporterDesigner = MWF.xApplication.query.ImporterDesigner || {};
MWF.xApplication.query.ImporterDesigner.LP={
	"title": "Import model editing",
	"newView": "New Import Model",
	"property": "Property",
	"item": "Item",
	"type": "Type",
	"value": "Value",
	"importer": "Import Model",
	"unnamed": "Untitled",
	"unCategory": "Uncategorized",
	"id": "Identification",
	"name": "Name",
	"alias": "Alias",
	"description": "Description",
	"saveViewNotice": "Please save the imported model first!",
	"application": "Data Application",
	"newImporter": "New Import Model",
	"newViewName": "Newly imported model name",
	"copy": "Copy",
	"ok": "OK",
	"cancel": "Cancel",
	"columnField": "Excel column corresponding field",
	"calculateField": "Calculate Field",
	"action": {
		"move": "Move",
		"delete": "Delete",
		"add": "Add"
	},
	"notice": {
		"save_success": "The imported model was saved successfully!",
		"saveAs_success": "The imported model is successfully saved as, you can open the new imported model in the import model settings!",
		"deleteColumnTitle": "Delete column confirmation",
		"deleteColumn": "Are you sure you want to delete the current column?",
		"deleteFieldTitle": "Delete FieldTitle",
		"deleteField": "Are you sure you want to delete the current field?",
		"inputTypeError": "The data type you entered is wrong, please re-enter",
		"sameKey": "The item name you entered already exists in the object, please re-enter",
		"emptyKey": "Project name cannot be empty, please re-enter",
		"numberKey": "The item name cannot be a number, please re-enter",
		"inputName": "Please enter the name of the imported model",
		"noModifyName": "Cannot modify the name or alias",
		"inputType": "Please select the import destination",
		"inputProcess": "Please select a process",
		"inputCategory": "Please select a category",
		"inputTable": "Please select a self-built table",
		"deleteEventTitle": "Delete Event Confirmation",
		"deleteEvent": "Are you sure you want to delete the current event?",
		"cmsNoPublisherOrNoTitleTitle": "No title or drafter is set",
		"cmsNoPublisherOrNoTitle": "The title or drafter is not set for content management. Are you sure to save it?",
		"processNoPublisherOrNoTitleTitle": "No title or drafter is set",
		"processNoPublisherOrNoTitle": "The process has no title or drafter. Are you sure to save it?",
		"saveNotice": "Save Notice",
		"someFieldIsEmpty": "{text} is not selected, do you want to continue to save?"
	},
	"mastInputPath": "Please enter the data path",
	"mastInputTitle": "Please enter a title",
	"propertyTemplate": {
		"base": "Basic",
		"event": "Event",
		"html": "HTML",
		"json": "JSON",
		"action": "Action",
		"select": "Select",
		"alias": "Alias",
		"id": "Identification",
		"name": "Name",
		"description": "Description",
		"style": "Style",
		"attribute": "Attribute",
		"hidden": "Hidden",
		"orderNumber": "Order Number",
		"target": "Target",
		"importTarget": "Import Target",
		"cmsData": "Content Management Data",
		"tableData": "Self-built table data",
		"processPlatformData": "Process Platform Data",
		"selectCategory": "Select Category",
		"selectTable": "Select self-built table",
		"selectProcess": "Select Process",
		"processStatus": "Process Status",
		"draftActivity": "Drafting activity (first manual activity)",
		"endActivity": "End Activity",
		"enableValidation": "Enable validation",
		"yes": "Yes",
		"no": "No",
		"ececuter": "Executable",
		"ececutablePerson": "Executable Person",
		"ececutableUnit": "Executive Organization",
		"fieldTitle": "Field Title",
		"data": "Data",
		"fieldPath": "Field Path",
		"valueScript": "Value Script",
		"cmsProperty": "cms document properties",
		"isTitle": "Is it a title (unique)",
		"isSummary": "Is it a summary (unique)",
		"isPublisher": "Is it the creator (unique)",
		"isAuthor": "Is authors",
		"isReader": "Is readers",
		"workProperty": "Process work property",
		"isProcessDrafter": "Is the work drafter (unique)",
		"isName": "Organization Object",
		"fieldType": "Field Type",
		"validation": "Validation",
		"allowEmpty": "Allow empty values",
		"validFieldType": "Validation field type",
		"documentType": "Document Type",
		"information": "Information",
		"data1": "Data",
		"processDrafter": "Process Drafter",
		"publisher": "Document Creator",
		"importerAsDrafter": "Identity of importer",
		"setDrafterInField": "Set in the field (column)",
		"note": "Note:",
		"selectOrg": "Please select an organization object",
		"selectDate": "Please select the date type",
		"selectText": "Please select the text type",
		"publishTime": "Publish Time",
		"importeTimeAsPublishTime": "Import time is publishing time",
		"titleField": "Title",
		"summaryField": "Summary",
		"selectForm": "Specify Form",
		"serialField": "Serial Number/Signature",
		"startTimeField": "Start Date",
		"completeTimeField": "End Date",
		"selectProcess1": "Please select the process first",
		"lineBreak": "Line Break",
		"valueScriptNote": "The field value needs to be returned by return. You can get the data of the current imported row through this.target;, as follows:",
		"valueScriptImportedDataNote": "Imported Original Data",
		"valueScriptDataNote": "Business data generated by the system according to configuration",
		"valueScriptDocumentNote": "If you import a CMS document, the document data generated by the system",
		"valueScriptWorkNote": "If importing process Work, the system generated work data",
		"selectField": "Select Column/Field",
		"idPathNote": "When importing self created table data, a field path of 'id' indicates updating the original record.",
		"excelSelectedOption": "excel column options ",
		"selectedOptionScript": "Optional script"
	},
	"formToolbar": {
		"save": "Save",
		"saveAs": "Save As",
		"autoSave": "Auto Save",
		"preview": "preview",
		"help": "help"
	}
}
MWF.xApplication.query.ImporterDesigner["lp."+o2.language] = MWF.xApplication.query.ImporterDesigner.LP