MWF.xApplication.query.ImporterDesigner.LP = {
    "title": "가져오기 모델 편집",
    "newView": "새 가져오기 모델",
    "property": "속성",
    "item": "항목",
    "type": "유형",
    "value": "값",
    "importer": "가져오기 모델",
    "unnamed": "무제목",
    "unCategory": "미분류",
    "id": "식별자",
    "name": "이름",
    "alias": "별명",
    "description": "설명",
    "saveViewNotice": "가져오기 모델을 먼저 저장하십시오.",
    "application": "데이터 애플리케이션",
    "newImporter": "새 가져오기 모델",
    "newViewName": "새로운 가져오기 모델 이름",
    "copy": "복사",
    "ok": "확인",
    "cancel": "취소",
    "columnField": "Excel 열에 해당하는 필드",
    "calculateField": "계산 필드",
    "action": {
        "move": "이동",
        "delete": "삭제",
        "add": "추가"
    },

    "notice": {
        "save_success": "가져오기 모델이 성공적으로 저장되었습니다!",
        "saveAs_success": "가져오기 모델이 성공적으로 다른 이름으로 저장되었습니다. 가져오기 모델 설정에서 새로운 가져오기 모델을 열 수 있습니다.",
        "deleteColumnTitle": "열 삭제 확인",
        "deleteColumn": "현재 열을 삭제하시겠습니까?",
        "deleteFieldTitle": "필드 삭제 확인",
        "deleteField": "현재 필드를 삭제하시겠습니까?",
        "inputTypeError": "입력한 데이터 유형이 잘못되었습니다. 다시 입력하십시오.",
        "sameKey": "입력한 항목 이름이 객체 내에서 이미 존재합니다. 다시 입력하십시오.",
        "emptyKey": "항목 이름을 비워 둘 수 없습니다. 다시 입력하십시오.",
        "numberKey": "항목 이름은 숫자일 수 없습니다. 다시 입력하십시오.",
        "inputName": "가져오기 모델 이름을 입력하십시오.",
        "noModifyName": "이름 또는 별명을 수정할 수 없습니다.",
        "inputType": "가져올 대상을 선택하십시오.",
        "inputProcess": "프로세스를 선택하십시오.",
        "inputCategory": "카테고리를 선택하십시오.",
        "inputTable": "자체 테이블을 선택하십시오.",
        "deleteEventTitle": "이벤트 삭제 확인",
        "deleteEvent": "현재 이벤트를 삭제하시겠습니까?",
        "cmsNoPublisherOrNoTitleTitle": "제목 또는 기고자가 설정되지 않았습니다.",
        "cmsNoPublisherOrNoTitle": "제목 또는 기고자가 설정되지 않았습니다. 저장하시겠습니까?",
        "processNoPublisherOrNoTitleTitle": "제목 또는 시작자가 설정되지 않았습니다.",
        "processNoPublisherOrNoTitle": "제목 또는 시작자가 설정되지 않았습니다. 저장하시겠습니까?",
        "saveNotice": "저장 안내",
        "someFieldIsEmpty": "{text}이(가) 선택되지 않았습니다. 계속해서 저장하시겠습니까?"
    },
    "mastInputPath": "데이터 경로를 입력하십시오.",
    "mastInputTitle": "제목을 입력하십시오.",

    "propertyTemplate": {
        "base": "기본",
		"event": "이벤트",
		"html": "HTML",
		"json": "JSON",
		"action": "작업",
		"select": "선택",
		"alias": "별칭",
		"id": "ID",
		"name": "이름",
		"description": "설명",
		"style": "스타일",
		"attribute": "속성",
		"hidden": "숨김",
		"orderNumber": "정렬 순서",
		"target": "대상",
		"importTarget": "가져오기 대상",
		"cmsData": "콘텐츠 관리 데이터",
		"tableData": "사용자 지정 테이블 데이터",
		"processPlatformData": "프로세스 플랫폼 데이터",
		"selectCategory": "카테고리 선택",
		"selectTable": "사용자 지정 테이블 선택",
		"selectProcess": "프로세스 선택",
		"processStatus": "프로세스 상태",
		"draftActivity": "작업 초안 (첫 번째 수동 노드)",
		"endActivity": "종료 작업",
		"enableValidation": "유효성 검사 활성화",
		"yes": "예",
		"no": "아니오",
		"ececuter": "실행자",
		"ececutablePerson": "실행 가능한 사용자",
		"ececutableUnit": "실행 조직",

        "fieldTitle": "필드 제목",
		"data": "데이터",
		"fieldPath": "필드 경로",
		"valueScript": "값 스크립트",
		"cmsProperty": "CMS 문서 속성",
		"isTitle": "제목임 (고유)",
		"isSummary": "요약임 (고유)",
		"isPublisher": "제작자임 (고유)",
		"isAuthor": "저자임",
		"isReader": "독자임",
		"workProperty": "작업 속성",
		"isProcessDrafter": "프로세스 초안 작성자임 (고유)",
		"isName": "조직 객체임",
		"fieldType": "필드 유형",
		"validation": "유효성 검사",
		"allowEmpty": "빈 값 허용",
		"validFieldType": "유효한 필드 유형",
		"documentType": "문서 유형",
		"information": "정보",
		"data1": "데이터",
		"processDrafter": "프로세스 초안 작성자",
		"publisher": "문서 생성자",
		"selectField": "열/필드 선택",
		"importerAsDrafter": "가져올 때 운영자 신분",
		"setDrafterInField": "열/필드에 설정",

        "note": "참고:",
		"selectOrg": "조직 객체를 선택하세요",
		"selectDate": "날짜 유형을 선택하세요",
		"selectText": "텍스트 유형을 선택하세요",
		"publishTime": "발표 시간",
		"importeTimeAsPublishTime": "발표 시간으로 가져오기",
		"titleField": "제목 필드",
		"summaryField": "요약 필드",
		"selectForm": "양식 지정",
		"serialField": "일련 번호/제목 번호",
		"startTimeField": "시작 날짜",
		"completeTimeField": "완료 날짜",
		"selectProcess1": "프로세스를 먼저 선택하세요",
		"lineBreak": "줄 바꿈",
		"valueScriptNote": "“값 스크립트”에서는 값을 반환하기 위해 return을 사용해야 합니다. this.target;을 사용하여 현재 가져온 데이터 행의 값을 얻을 수 있습니다.",
		"valueScriptImportedDataNote": "가져온 원본 데이터",
		"valueScriptDataNote": "구성에 따라 생성된 업무 데이터",
		"valueScriptDocumentNote": "CMS 문서를 가져오는 경우 시스템에서 생성한 문서 데이터",
		"valueScriptWorkNote": "작업 데이터를 가져오는 경우 시스템에서 생성한 작업 데이터"
    }
};