MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Deployment = MWF.xApplication.Deployment || {};
MWF.xApplication.Deployment.LP={
	"title": "Implementación de aplicaciones",
	"open": "Abrir",
	"edit": "Editar",
	"remove": "Desinstalar",
	"add": "Implementar componente",
	"name": "Nombre del componente",
	"componentTitle": "Título del componente",
	"path": "Ruta del componente",
	"isVisible": "¿Es visible?",
	"yes": "Sí",
	"no": "No",
	"widgetName": "Nombre del widget",
	"widgetTitle": "Título del widget",
	"widgetStart": "Inicio automático del widget",
	"widgetVisible": "¿Es visible el widget?",
	"allowList": "Lista de permitidos",
	"denyList": "Lista de denegados",
	"controllerList": "Administradores",
	"selPerson": "Seleccionar personas",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"noInputInfor": "Por favor, complete toda la información del componente. (Debe completar: nombre del componente, título del componente y ruta del componente)",
	"deploySuccess": "Implementación exitosa",
	"modifySuccess": "Se ha modificado la información del componente con éxito",
	"removeComponentTitle": "Confirmación de desinstalación del componente",
	"removeComponent": "¿Está seguro de que desea desinstalar el componente {name}?",
	"removeComponentOk": "El componente se ha desinstalado correctamente",
	"modify": "Modificar información del componente",
	"deployedComponent": "Componentes implementados",
	"inputNameAndTitle": "Por favor, ingrese el nombre y el título de la aplicación",
	"uploadZipFile": "Por favor, suba el archivo ZIP de la aplicación"
}
MWF.xApplication.Deployment["lp."+o2.language] = MWF.xApplication.Deployment.LP