MWF.xApplication.Deployment.LP = {
	"title": "앱 배포",
  "open": "열기",
  "edit": "편집",
  "remove": "제거",
  "add": "구성 요소 배포",
  "name": "구성 요소 이름",
  "componentTitle": "구성 요소 제목",
  "path": "구성 요소 경로",
  "isVisible": "표시 여부",
  "yes": "예",
  "no": "아니요",
  "widgetName": "위젯 이름",
  "widgetTitle": "위젯 제목",
  "widgetStart": "위젯 자동 시작",
  "widgetVisible": "위젯 표시 여부",
  "allowList": "접근 가능 목록",
  "denyList": "거부 목록",
  "controllerList": "관리자",
  "selPerson": "사용자 선택",
  "phone": "휴대전화",
  "mail": "이메일",
  "noInputInfor": "구성 요소 정보를 완전히 입력하세요. (필수 입력 사항: 구성 요소 이름, 구성 요소 제목, 구성 요소 경로)",
  "deploySuccess": "배포 완료",
  "modifySuccess": "구성 요소 정보 수정 완료",
  "removeComponentTitle": "구성 요소 제거 확인",
  "removeComponent": "구성 요소 {name}을(를) 제거하시겠습니까?",
  "removeComponentOk": "구성 요소가 제거되었습니다",
  "modify": "구성 요소 정보 수정",
  "deployedComponent": "배포된 구성 요소",
  "inputNameAndTitle": "앱 이름과 제목을 입력하세요",
  "uploadZipFile": "파일의 ZIP 패키지를 업로드하세요"
};