MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.ViewDesigner = MWF.xApplication.cms.ViewDesigner || {};
MWF.xApplication.cms.ViewDesigner.LP={
	"title": "Edición de lista",
	"newView": "Nueva lista",
	"property": "Propiedad",
	"viewProperty": "Propiedades de la lista",
	"item": "Elemento",
	"type": "Tipo",
	"value": "Valor",
	"view": "Lista",
	"relativeForm": "Formulario",
	"noTitle": "Sin título",
	"columnProperty": "Propiedad de columna",
	"base": "Base",
	"events": "Eventos",
	"sortColumn": "Ordenar por columna",
	"asc": "Ascendente",
	"desc": "Descendente",
	"columnTitle": "Título de la columna",
	"columnValue": "Valor de la columna",
	"columnWidth": "Ancho de la columna",
	"columnAlign": "Alineación de la columna",
	"columnAlignText": "Centro, Izquierda, Derecha",
	"columnAlignValue": "center,left,right",
	"percentage": "%",
	"px": "píxeles",
	"id": "Identificación",
	"name": "Nombre",
	"alias": "Alias",
	"description": "Descripción",
	"action": "Acción",
	"delete": "Eliminar",
	"edit": "Editar",
	"share": "Compartir",
	"sortByClickTitle": "Haga clic en el título de la columna para ordenar",
	"insertColLeft": "Insertar columna a la izquierda",
	"insertColRight": "Agregar columna a la derecha",
	"deleteCol": "Eliminar columna",
	"moveCol": "Mover columna",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"deleteColConfirmTitle": "Confirmación",
	"deleteColConfirm": "¿Está seguro de que desea eliminar esta columna?",
	"notice": {
		"save_success": "¡Lista guardada exitosamente!",
		"saveAs_success": "La lista se ha guardado con éxito como una nueva, puede abrir la nueva lista en la configuración de la columna.",
		"deleteDataTitle": "Confirmación",
		"deleteData": "¿Está seguro de que desea eliminar los datos actuales y sus subdatos?",
		"changeTypeTitle": "Confirmación",
		"changeTypeDeleteChildren": "Cambiar el tipo de datos eliminará todos los subdatos. ¿Está seguro de que desea continuar?",
		"changeType": "Cambiar el tipo de datos cambiará los valores de los datos. ¿Está seguro de que desea continuar?",
		"inputTypeError": "El tipo de datos ingresado es incorrecto, por favor vuelva a intentarlo",
		"sameKey": "El nombre del elemento que ha ingresado ya existe en el objeto, por favor ingrese otro.",
		"emptyKey": "El nombre del elemento no puede estar vacío, por favor ingrese otro.",
		"numberKey": "El nombre del elemento no puede ser un número, por favor ingrese otro.",
		"inputName": "Ingrese el nombre de la lista",
		"noModifyName": "El nombre o alias no pueden ser modificados",
		"noRemoveOnlyColumn": "No es posible eliminar la única columna"
	},
	"copy": "Copia",
	"newListName": "Nombre de la nueva lista"
}
MWF.xApplication.cms.ViewDesigner["lp."+o2.language] = MWF.xApplication.cms.ViewDesigner.LP