MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.meetingv2 = MWF.xApplication.meetingv2 || {};
MWF.xApplication.meetingv2.LP={
	"title": "Metting Management",
	"metting": "Metting",
	"subject": "Metting Title",
	"applyPerson": "Applicant",
	"myMeeting": "My meetingv2",
	"month": "Month",
	"day": "Day",
	"room": "meetingv2 Room",
	"list": "meetingv2 List",
	"today": "Today",
	"tomorrow": "Tomorrow",
	"afterTomorrow": "AfterTomorrow",
	"yesterday": "Yesterday",
	"beforeYesterday": "The day before yesterday",
	"nextMonth": "Next Month",
	"floor": "Floor",
	"enable": "Enable",
	"disable": "Disable",
	"cancel": "Cancel",
	"close": "Close",
	"save": "Save",
	"newBuilding": "New Location",
	"editBuilding": "Edit Location",
	"meetingApply": "meetingv2 Apply for {person}",
	"myMeetingApply": "My meetingv2 Apply",
	"attend": "Please attend on time",
	"beginDate": "Date",
	"beginTime": "Start Time",
	"endTime": "End Time",
	"time": "Time",
	"meetingTime": "Time",
	"selectRoom": "Room",
	"invitePerson": "Invite participants",
	"invitePerson1": "Invite Person",
	"invitePerson2": "Participants",
	"addInvitePerson1": "Add Invite Person",
	"addedInvitePerson1": "Invite person has been added",
	"deleteInvitePerson": "Invite person has been cancelled",
	"deleteInvitePerson1": "Cancel the inviter",
	"deleteInvitePerson2": "Cancelled",
	"userDeleteInvitePerson": "Your meeting invitation has been cancelled.",
	"acceptPerson": "Accepted",
	"rejectPerson": "Rejected",
	"waitAccept": "Invite you to participate",
	"waitConfirm": "Need your approval",
	"isAccept": "Please attend the meeting on time",
	"timeRangeHour": "{n}Hour",
	"timeRangeMinute": "{h}Hour{m}Minute",
	"accepted": "The meeting invitation has been accepted",
	"rejected": "meetingv2 invitation has been rejected",
	"accept": "Accept meeting invitation",
	"reject": "Reject the meeting invitation",
	"disagree": "Rejected",
	"agree": "Agree",
	"countMeetings": "meetingv2",
	"noMeetingWeek": "No meetings within a week",
	"newlyMeeting": "{time}: {name}, location: {room}",
	"am": "a.m.",
	"pm": "p.m.",
	"monthSelectTextPrev": "Show the future",
	"monthSelectTextAfter": "Month meetingv2",
	"meetingNotice": "meetingv2 Notice",
	"noComingMeeting": "You have no invitations in the next {month} months",
	"roomViewHelp": "You can select the time and duration to inquire about free meeting rooms.<br/>Unavailable meeting rooms will be grayed out, and conflicting meetings will be marked in red.",
	"delete": "Delete",
	"reject_confirm_title": "Reject the meeting confirmation",
	"reject_confirm": "Are you sure you refuse to participate in the '{name}' meeting?",
	"cancel_confirm_title": "Cancel meetingv2 Confirmation",
	"cancel_confirm": "You have chosen to cancel the '{name}' meeting. This meeting request will be deleted. Are you sure you want to execute it?",
	"accept_confirm_title": "Accept meetingv2 Confirmation",
	"accept_confirm": "Are you sure you want to join the '{name}' meeting?",
	"disagree_confirm_title": "Confirmation of rejected meeting application",
	"disagree_confirm": "Are you sure you want to reject the '{name}' meeting application?",
	"agree_confirm_title": "Agree to the meeting application confirmation",
	"agree_confirm": "Are you sure you agree to the '{name}' meeting application?",
	"cancelMeeting": "Cancel meetingv2",
	"applyMeeting": "Apply meetingv2",
	"addMeeting": "New meetingv2",
	"editMeeting": "Edit meetingv2",
	"addRoom": "New meetingv2 Room",
	"editRoom": "Edit meetingv2 Room",
	"refresh": "Refresh",
	"setting": "Settings",
	"phone": "Mobile",
	"mail": "Mailbox",
	"meetingSubject": "Subject",
	"meetingDescription": "Description",
	"externalPerson": "External Person",
	"meetingAttachment": "Attachment",
	"meetingDetail": "Detail",
	"editAddress": "Edit Address",
	"removeBuilding": "Remove Location",
	"address": "Address",
	"name": "Name",
	"meetingTopInfor": "Hello {userName}! Today meeting:",
	"noMeetingTopInfor": "Hello {userName}! You have no meetings today.",
	"roomDisable": "The meeting room is disabled",
	"noPermission": "The meeting details are not visible",
	"config_saveSuccess": "Configuration saved successfully!",
	"cancel_createMeeting_title": "Cancel meeting application confirmation",
	"cancel_createMeeting": "The meeting application is about to be cancelled. The data you filled in will be lost. Are you sure you want to cancel the current meeting application?",
	"meeting_input_error": "Please fill in the following correctly:<br/>",
	"meeting_input_subject_error": "meetingv2 title cannot be empty!",
	"meeting_input_room_error": "The meeting room cannot be empty!",
	"meeting_input_url_number_error": "meetingv2 URL and meeting number cannot be empty at the same time!",
	"meeting_input_person_error": "The invited participant cannot be empty!",
	"meeting_input_date_error": "The meeting start time cannot be earlier than now!",
	"meeting_input_time_error": "The meeting end time cannot be earlier than the start time!",
	"meeting_saveSuccess": "meetingv2 application saved successfully!",
	"deleteAttachmentTitle": "Delete attachment confirmation",
	"deleteAttachment": "Are you sure you want to delete the attachment you selected?",
	"startMeetingImmediately": "Start meetingv2",
	"endMeetingImmediately": "End meetingv2",
	"startMeetingSucccess": "The meeting has started",
	"endMeetingSucccess": "The meeting has ended",
	"dateFormatMonth": "%Y-%m",
	"dateFormatMonthDay": "%m-%d",
	"dateFormatMonthOnly": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatDayOnly": "%d",
	"dateFormatAll": "%Y-%m-%d %H:%M",
	"dateFormat": "db",
	"person": "person",
	"persist": "persist",
	"hour": "Hour",
	"minute": "minute",
	"to": "to",
	"all": "All",
	"myWaitConfirm": "Audit",
	"myWaitAccept": "Invite",
	"noTask": "No meeting invitation today",
	"noMeeting": "No meeting",
	"noAddress": "Address not filled in",
	"hostPerson": "Host Person",
	"hostUnit": "Host Unit",
	"meetingType": "meetingv2 Type",
	"meetingMode": "meeting mode",
	"meetingModeSelectText": [
		"offline meeting",
		"online meeting"
	],
	"meetingModeSelectValue": [
		"offline",
		"online"
	],
	"meetingUrl": "meeting link",
	"openMeetingUrl": "Open meeting link",
	"meetingNumber": "meeting number",
	"netMeetingAbb": "Net",
	"yes": "Yes",
	"no": "No",
	"other": "Other",
	"createOnSave": "Automatically generated after saving",
	"copy": "Copy",
	"noRoomBuilding": "Network meeting without meeting room",
	"week": "Week",
	"weeks": {
		"Sun": "Sun",
		"Mon": "Mon",
		"Tues": "Tues",
		"Wed": "Wed",
		"Thur": "Thur",
		"Fri": "Fri",
		"Sat": "Sat",
		"arr": [
			"Sun",
			"Mon",
			"Tues",
			"Wed",
			"Thur",
			"Fri",
			"Sat"
		]
	},
	"device": {
		"projector": "Projector",
		"board": "Whiteboard",
		"tvset": "TV set",
		"tv": "Video Conference",
		"camera": "Camera",
		"wifi": "Wifi",
		"phone": "Tellphone"
	},
	"inputAddress": "Add Address",
	"save_success": "Save successfully!",
	"delete_building_title": "Delete Confirmation",
	"delete_building_hasRoom": "There are still meeting rooms under '{name}' and cannot be deleted.",
	"delete_building": "Are you sure you want to delete '{name}'",
	"delete_room": "Are you sure you want to delete the meeting room '{name}'",
	"add": "add",
	"roomForm": {
		"name": "Name",
		"building": "Location",
		"floor": "Floor",
		"device": "Equipment",
		"photo": "Photo",
		"orderNumber": "orderNumber",
		"capacity": "Capacity",
		"auditor": "Auditor",
		"available": "Status",
		"roomNumber": "Room Number",
		"phone": "Tellphone",
		"verification": {
			"inputName": "Please enter the name of the meeting room",
			"inputBuilding": "Please enter or select the location of the meeting room",
			"inputCapacity": "Please enter the capacity of the meeting room"
		},
		"save_success": "The meeting room was saved successfully!"
	},
	"listNavi": {
		"myApply": "My Application",
		"myMeeting": "Invitation",
		"wait": "Not started",
		"processing": "In progress",
		"apply": "Apply",
		"completed": "Completed",
		"reject": "Rejected",
		"room": "meetingv2 Room"
	},
	"config": {
		"navi": "Navigation",
		"autoHide": "AutoHide",
		"default": "Default View",
		"applyProcess": "meetingv2 Application Process",
		"legend": "Icon",
		"meetingStatus": "meetingv2 Status",
		"wait": "Appointed",
		"progress": "meetingv2",
		"completed": "Completed",
		"invite": "Invitation",
		"conflict": "meetingv2 Room Conflict",
		"weekBegin": "Starting day of the week",
		"meetingViewer": "Visible range of meeting details",
		"meetingViewerTitle": "If the visible range is empty, only the initiator, invitees and meeting managers can see the corresponding meeting details.",
		"viewSetting": "Enable View",
		"viewCustomName": "Display name",
		"mobileCreateEnable": "Whether the mobile terminal can create a new meeting",
		"mobileCreateEnableOptions": [
			"Yes",
			"No"
		],
		"meetingType": "meetingv2 Type (one per line)",
		"enableOnline": "Enable online meeting",
		"onlineConfig": "Online meeting configuration",
		"onlineProduct": "Online meeting product",
		"hstUrl": "Service Address",
		"hstKey": "Service Interface KEY",
		"hstSecret": "Service interface SECRET",
		"hstAuth": "Is authenticated",
		"o2ToHstUid": "People Synchronization Fields",
		"onlineConfigNotEmpty": "Hostel service address, interface Key, and interface Secret cannot be empty",
		"employee": "employee",
		"unique": "unique",
		"distinguishedName": "distinguishedName",
		"mobile": "mobile",
		"mail": "mail",
		"weixin": "qq",
		"qq": "qq",
		"apiAddress": "web conferencing api address",
		"key": "key",
		"secret": "secret"
	},
	"nextActivity": "Next Activity:",
	"nextUser": "Processor:",
	"deal": "Deal",
	"processStarted": "File has been started",
	"processStartedMessage": "You started a new job:",
	"needSignInPerson": "Checked in",
	"printQrcode": "Print QR Code for Sign-in",
	"weeklyViewTitle": "{month}, week {week}",
	"onlineConfigNotJson": "The online meeting configuration is not in the correct JSON format",
	"meeting_input_hostPerson_error": "The host cannot be empty!"
}
MWF.xApplication.meetingv2["lp."+o2.language] = MWF.xApplication.meetingv2.LP
