/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.portal.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.portal.core.entity.Widget.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:58 CST 2018")
public class Widget_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Widget,String> alias;
    public static volatile SingularAttribute<Widget,String> data;
    public static volatile SingularAttribute<Widget,String> description;
    public static volatile SingularAttribute<Widget,Boolean> hasMobile;
    public static volatile SingularAttribute<Widget,String> id;
    public static volatile SingularAttribute<Widget,String> mobileData;
    public static volatile SingularAttribute<Widget,String> name;
    public static volatile SingularAttribute<Widget,String> portal;
}
