MWF.xApplication.Meeting.LP = {
    "title": "Metting Management",

    "metting": "Metting",
    "subject": "Metting Title",
    "applyPerson": "Applicant",
    "myMeeting": "My Meeting",
    "month": "Month",
    "day": "Day",
    "room": "Meeting Room",
    "list": "Meeting List",
    "today": "Today",
    "tomorrow": "Tomorrow",
    "afterTomorrow": "AfterTomorrow",
    "yesterday": "Yesterday",
    "beforeYesterday": "The day before yesterday",
    "nextMonth": "Next Month",
    "floor": "Floor",
    "enable": "Enable",
    "disable": "Disable",
    "cancel": "Cancel",
    "close": "Close",
    "save": "Save",
    "newBuilding": "New Location",
    "editBuilding": "Edit Location",
    //"inputAddress": "input address",
    "meetingApply": "Meeting Apply for {person}",
    "myMeetingApply": "My Meeting Apply",
    "attend": "Please attend on time",
    "beginDate": "Date",
    "beginTime": "Start Time",
    "endTime": "End Time",
    "time": "Time",
    "meetingTime": "Time",
    "selectRoom": "Room",
    "invitePerson": "Invite participants",
    "invitePerson1": "Invite Person",
    "invitePerson2": "Participants",
    "addInvitePerson1": "Add Invite Person",
    "addedInvitePerson1": "Invite person has been added",
    "waitAccept": "Invite you to participate",
    "waitConfirm": "Need your approval",
    "isAccept": "Please attend the meeting on time",
    "timeRangeHour": "{n}Hour",
    "timeRangeMinute": "{h}Hour{m}Minute",
    "accepted": "The meeting invitation has been accepted",
    "rejected": "Meeting invitation has been rejected",
    "accept": "Accept meeting invitation",
    "reject": "Reject the meeting invitation",
    "disagree": "Rejected",
    "agree": "Agree",
    "countMeetings": "",
    "noMeetingWeek": "No meetings within a week",
    "newlyMeeting": "{time}: {name}, location: {room}",
    "am": "a.m.",
    "pm": "p.m.",
    "monthSelectTextPrev": "Show the future",
    "monthSelectTextAfter": "Month Meeting",
    "meetingNotice": "Meeting Notice",
    "noComingMeeting": "You have no invitations in the next {month} months",
    "roomViewHelp": "You can select the time and duration to inquire about free meeting rooms.<br/>Unavailable meeting rooms will be grayed out, and conflicting meetings will be marked in red.",

    "delete": "Delete",

    "reject_confirm_title": "Reject the meeting confirmation",
    "reject_confirm": "Are you sure you refuse to participate in the '{name}' meeting?",

    "cancel_confirm_title": "Cancel Meeting Confirmation",
    "cancel_confirm": "You have chosen to cancel the '{name}' meeting. This meeting request will be deleted. Are you sure you want to execute it?",

    "accept_confirm_title": "Accept Meeting Confirmation",
    "accept_confirm": "Are you sure you want to join the '{name}' meeting?",

    "disagree_confirm_title": "Confirmation of rejected meeting application",
    "disagree_confirm": "Are you sure you want to reject the '{name}' meeting application?",

    "agree_confirm_title": "Agree to the meeting application confirmation",
    "agree_confirm": "Are you sure you agree to the '{name}' meeting application?",

    "cancelMeeting": "Cancel Meeting",
    "applyMeeting": "Apply Meeting",
    "addMeeting": "New Meeting",
    "editMeeting": "Edit Meeting",
    "addRoom": "New Meeting Room",
    "editRoom": "Edit Meeting Room",
    "refresh": "Refresh",
    "setting": "Settings",
    "phone": "Mobile",
    "mail": "Mailbox",
    "meetingSubject": "Subject",
    "meetingDescription": "Description",
    "meetingAttachment": "Attachment",
    "meetingDetail": "Detail",
    "editAddress": "Edit Address",
    "removeBuilding": "Remove Location",
    "address": "Address",
    "name": "Name",
    "meetingTopInfor": "Hello {userName}! Today meeting:",
    "noMeetingTopInfor": "Hello {userName}! You have no meetings today.",
    "roomDisable": "The meeting room is disabled",
    "noPermission": "The meeting details are not visible",

    "config_saveSuccess": "Configuration saved successfully!",

    "cancel_createMeeting_title": "Cancel meeting application confirmation",
    "cancel_createMeeting": "The meeting application is about to be cancelled. The data you filled in will be lost. Are you sure you want to cancel the current meeting application?",

    "meeting_input_error": "Please fill in the following correctly:<br/>",
    //"meeting_input_subject_error": "Please fill in the full meeting title!",
    //"meeting_input_room_error": "Please select a meeting room!",
    //"meeting_input_person_error": "Please choose to invite participants!",
    //"meeting_input_date_error": "Please select the meeting start date and time correctly!",
    //"meeting_input_time_error": "Please select the meeting start time and end time correctly!",

    "meeting_input_subject_error": "Meeting title cannot be empty!",
    "meeting_input_room_error": "The meeting room cannot be empty!",
    "meeting_input_person_error": "The invited participant cannot be empty!",
    "meeting_input_date_error": "The meeting start time cannot be earlier than now!",
    "meeting_input_time_error": "The meeting end time cannot be earlier than the start time!",


    //"meeting_input_subject_error": "Please fill in the full meeting title!",
    "meeting_saveSuccess": "Meeting application saved successfully!",

    "deleteAttachmentTitle":"Delete attachment confirmation",
    "deleteAttachment": "Are you sure you want to delete the attachment you selected?",

    "startMeetingImmediately": "Start Meeting",
    "endMeetingImmediately": "End Meeting",
    "startMeetingSucccess": "The meeting has started",
    "endMeetingSucccess": "The meeting has ended",

    "dateFormatMonth": "%Y-%m",
    "dateFormatMonthDay": "%m-%d",
    "dateFormatMonthOnly": "%m",
    "dateFormatDay": "%Y-%m-%d",
    "dateFormatDayOnly": "%d",
    "dateFormatAll": "%Y-%m-%d %H:%M",
    "dateFormat": "db",
    "person": "person",
    "persist": "persist",
    "hour": "Hour",
    "minute": "minute",
    "to": "to",
    "all": "All",

    "myWaitConfirm": "Audit",
    "myWaitAccept": "Invite",

    "noTask": "No meeting invitation today",
    "noMeeting": "No meeting",
    "noAddress": "Address not filled in",

    "week": "Week",
    "weeks": {
        "Sun": "Sun",
        "Mon": "Mon",
        "Tues": "Tues",
        "Wed": "Wed",
        "Thur": "Thur",
        "Fri": "Fri",
        "Sat": "Sat",
        "arr": ["Sun", "Mon", "Tues", "Wed", "Thur", "Fri", "Sat"]
    },

    "device": {
        "projector": "Projector",
        "board": "Whiteboard",
        "tvset": "TV set",
        "tv": "Video Conference",
        "camera": "Camera",
        "wifi": "Wifi",
        "phone": "Tellphone"
    },
    "inputAddress": "Add Address",
    "save_success": "Save successfully!",
    "delete_building_title": "Delete Confirmation",
    "delete_building_hasRoom": "There are still meeting rooms under '{name}' and cannot be deleted.",
    "delete_building": "Are you sure you want to delete '{name}'",
    "delete_room": "Are you sure you want to delete the meeting room '{name}'",

    "roomForm": {
        "name": "Name",
        "building": "Location",
        "floor": "Floor",
        "device": "Equipment",
        "photo": "Photo",
        "capacity": "Capacity",
        "auditor": "Auditor",
        "available": "Status",
        "roomNumber": "Room Number",
        "phone": "Tellphone",

        "verification": {
            "inputName": "Please enter the name of the meeting room",
            "inputBuilding": "Please enter or select the location of the meeting room",
            "inputCapacity": "Please enter the capacity of the meeting room"

        },
        "save_success": "The meeting room was saved successfully!"
    },
    "listNavi": {
        "myApply": "My Application",
        "myMeeting" :"Invitation",
        "wait": "Not started",
        "processing": "In progress",
        "completed": "Completed",
        "reject": "Rejected",
        "room": "Meeting Room"
    },
    "config": {
        "navi": "Navigation",
        "autoHide": "AutoHide",
        "default": "Default View",
        "applyProcess": "Meeting Application Process",
        "legend": "Icon",
        "meetingStatus": "Meeting Status",
        "wait": "Appointed",
        "progress": "Meeting",
        "completed": "Completed",
        "invite": "Invitation",
        "conflict": "Meeting Room Conflict",
        "weekBegin": "Starting day of the week",
        "meetingViewer": "Visible range of meeting details",
        "meetingViewerTitle": "If the visible range is empty, only the initiator, invitees and meeting managers can see the corresponding meeting details.",
        "viewSetting": "Enable View",
        "viewCustomName": "Display name",
        "mobileCreateEnable": "Whether the mobile terminal can create a new meeting",
        "mobileCreateEnableOptions": ["Yes","No"]
    },
    "nextActivity": "Next Activity:",
    "nextUser": "Processor:",
    "deal": "Deal",
    "processStarted": "File has been started",
    "processStartedMessage": "You started a new job:",
    "needSignInPerson": "Checked in",
    "printQrcode": "Print QR Code for Sign-in",
    "weeklyViewTitle": "{month}, week {week}"
};