MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Meeting = MWF.xApplication.Meeting || {};
MWF.xApplication.Meeting.LP={
	"title": "Gestión de Reuniones",
	"metting": "Reunión",
	"subject": "Título de la reunión",
	"applyPerson": "Persona que solicita",
	"myMeeting": "Mis reuniones",
	"month": "Mes",
	"day": "Día",
	"room": "Sala de reuniones",
	"list": "Lista de reuniones",
	"today": "Hoy",
	"tomorrow": "Mañana",
	"afterTomorrow": "Pasado mañana",
	"yesterday": "Ayer",
	"beforeYesterday": "Anteayer",
	"nextMonth": "Siguiente mes",
	"floor": "Piso",
	"enable": "Habilitado",
	"disable": "Deshabilitado",
	"cancel": "Cancelar",
	"close": "Cerrar",
	"save": "Guardar",
	"newBuilding": "Nueva ubicación",
	"editBuilding": "Editar ubicación",
	"meetingApply": "Solicitud de reunión de {person}",
	"myMeetingApply": "Mi solicitud de reunión",
	"attend": "Por favor asista puntualmente",
	"beginDate": "Fecha",
	"beginTime": "Hora de inicio",
	"endTime": "Hora de finalización",
	"time": "Tiempo",
	"meetingTime": "Tiempo de la reunión",
	"selectRoom": "Seleccionar sala de reuniones",
	"invitePerson": "Invitar asistentes",
	"invitePerson1": "Invitador",
	"invitePerson2": "Asistente",
	"addInvitePerson1": "Agregar invitador",
	"addedInvitePerson1": "Invitador agregado",
	"deleteInvitePerson": "Asistente eliminado",
	"deleteInvitePerson1": "Eliminar asistente",
	"deleteInvitePerson2": "Asistente eliminado",
	"userDeleteInvitePerson": "Su invitación a la reunión ha sido cancelada",
	"acceptPerson": "Aceptado",
	"rejectPerson": "Rechazado",
	"waitAccept": "Te invita a participar en una reunión.",
	"waitConfirm": "Necesita su aprobación.",
	"isAccept": "Por favor asista puntualmente a la reunión.",
	"timeRangeHour": "{n} horas",
	"timeRangeMinute": "{h} horas {m} minutos",
	"accepted": "Invitación a la reunión aceptada.",
	"rejected": "Invitación a la reunión rechazada.",
	"accept": "Aceptar invitación a la reunión",
	"reject": "Rechazar invitación a la reunión",
	"disagree": "Discrepar",
	"agree": "Acuerdo",
	"countMeetings": "Reuniones programadas",
	"noMeetingWeek": "No hay reuniones programadas para esta semana.",
	"newlyMeeting": "{time}:{name}, lugar: {room}",
	"am": "AM",
	"pm": "PM",
	"monthSelectTextPrev": "Mostrar futuro",
	"monthSelectTextAfter": "meses de reuniones",
	"meetingNotice": "Notificación de reunión",
	"noComingMeeting": "No tienes reuniones en los próximos {month} meses.",
	"roomViewHelp": "Puede buscar salas de reuniones disponibles seleccionando el tiempo y la duración deseada.<br/>Las salas de reuniones no disponibles aparecerán en gris, mientras que las que presentan conflicto con otras reuniones se marcarán en rojo.",
	"delete": "Eliminar",
	"reject_confirm_title": "Confirmación",
	"reject_confirm": "¿Está seguro de que desea rechazar la invitación a la reunión '{name}'?",
	"cancel_confirm_title": "Confirmación",
	"cancel_confirm": "Ha seleccionado cancelar la reunión '{name}', lo que eliminará la solicitud de reunión. ¿Está seguro de que desea continuar?",
	"accept_confirm_title": "Confirmación",
	"accept_confirm": "¿Está seguro de que desea asistir a la reunión '{name}'?",
	"disagree_confirm_title": "Confirmación",
	"disagree_confirm": "¿Está seguro de que desea discrepar con la solicitud de la reunión '{name}'?",
	"agree_confirm_title": "Confirmación",
	"agree_confirm": "¿Está seguro de que desea estar de acuerdo con la solicitud de la reunión '{name}'?",
	"cancelMeeting": "Cancelar",
	"applyMeeting": "Solicitar una reunión",
	"addMeeting": "Agregar una nueva reunión",
	"editMeeting": "Editar reunión",
	"addRoom": "crear reunión",
	"editRoom": "Editar sala de reuniones",
	"refresh": "Actualizar",
	"setting": "Configuración",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"meetingSubject": "Título de la reunión",
	"meetingDescription": "Descripción de la reunión",
	"meetingAttachment": "Anexos de la reunión",
	"meetingDetail": "Detalles de la reunión",
	"editAddress": "Editar dirección",
	"removeBuilding": "Eliminar ubicación",
	"address": "Dirección",
	"name": "Nombre",
	"meetingTopInfor": "{userName}, ¡buen día!<br/>¡Hoy tienes <span style='color: #FB4747'>{count}</span> reuniones programadas!",
	"noMeetingTopInfor": "{userName}, ¡buen día! ¡No tienes reuniones programadas para hoy!",
	"roomDisable": "La sala de reuniones está deshabilitada.",
	"noPermission": "Los detalles de la reunión no están disponibles.",
	"config_saveSuccess": "Configuración guardada correctamente.",
	"cancel_createMeeting_title": "Confirmación",
	"cancel_createMeeting": "Está a punto de cancelar la solicitud de reunión, los datos que ha ingresado se perderán. ¿Está seguro de que desea cancelar la solicitud de reunión actual?",
	"meeting_input_error": "Por favor llene la siguiente información correctamente:<br/>",
	"meeting_input_subject_error": "¡El título de la reunión no puede estar vacío!",
	"meeting_input_room_error": "¡La sala de reuniones no puede estar vacía!",
	"meeting_input_person_error": "¡Debe haber al menos un invitado a la reunión!",
	"meeting_input_date_error": "¡La hora de inicio de la reunión no puede ser anterior a la hora actual!",
	"meeting_input_time_error": "¡La hora de finalización de la reunión no puede ser anterior a la hora de inicio!",
	"meeting_saveSuccess": "¡La solicitud de reunión se ha guardado correctamente!",
	"deleteAttachmentTitle": "Confirmación para eliminar anexo",
	"deleteAttachment": "¿Está seguro de que desea eliminar los archivos adjuntos seleccionados?",
	"startMeetingImmediately": "Comenzar la reunión",
	"endMeetingImmediately": "Finalizar la reunión",
	"startMeetingSucccess": "La reunión ha comenzado.",
	"endMeetingSucccess": "La reunión ha finalizado.",
	"dateFormatMonth": "%Y-%m",
	"dateFormatMonthDay": "%m-%d",
	"dateFormatMonthOnly": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatDayOnly": "%d",
	"dateFormatAll": "%Y-%m-%d %H:%M",
	"dateFormat": "db",
	"person": "persona(s)",
	"persist": "duración",
	"hour": "hora(s)",
	"minute": "minuto(s)",
	"to": "a",
	"all": "Todo",
	"myWaitConfirm": "Por aprobar",
	"myWaitAccept": "Invitaciones",
	"noTask": "No tienes invitaciones a reuniones para hoy.",
	"noMeeting": "No hay reuniones programadas para este día.",
	"noAddress": "Dirección no especificada",
	"hostPerson": "Anfitrión",
	"hostUnit": "Departamento organizador",
	"meetingType": "Tipo de reunión",
	"meetingMode": "metodo de encuentro",
	"meetingModeSelectText": [
		"reunión fuera de línea",
		"reunión en línea"
	],
	"meetingModeSelectValue": [
		"desconectado",
		"en línea"
	],
	"meetingUrl": "URL de la reunión",
	"openMeetingUrl": "Abrir URL de la reunión",
	"meetingNumber": "número de reunión",
	"netMeetingAbb": "neto",
	"yes": "Sí",
	"no": "No",
	"other": "otro",
	"createOnSave": "Generado automáticamente después de guardar",
	"copy": "Copiar",
	"noRoomBuilding": "reunión en línea\n (sin sala de reuniones)",
	"week": "Semana",
	"weeks": {
		"Sun": "Domingo",
		"Mon": "Lunes",
		"Tues": "Martes",
		"Wed": "Miércoles",
		"Thur": "Jueves",
		"Fri": "Viernes",
		"Sat": "Sábado",
		"arr": [
			"Domingo",
			"Lunes",
			"Martes",
			"Miércoles",
			"Jueves",
			"Viernes",
			"Sábado"
		]
	},
	"device": {
		"projector": "Proyector",
		"board": "Pizarra",
		"tvset": "Televisor",
		"tv": "Videoconferencia",
		"camera": "Cámara",
		"wifi": "Red",
		"phone": "Conferencia telefónica"
	},
	"inputAddress": "Agregar dirección",
	"save_success": "Guardado correctamente.",
	"delete_building_title": "Confirmación",
	"delete_building_hasRoom": "No se puede eliminar \"{name}\" ya que todavía tiene salas de reuniones asociadas.",
	"delete_building": "¿Estás seguro de que deseas eliminar \"{name}\"?",
	"delete_room": "¿Estás seguro de que deseas eliminar la sala de reuniones \"{name}\"?",
	"roomForm": {
		"name": "Nombre",
		"building": "Ubicación",
		"floor": "Piso",
		"device": "Dispositivos",
		"photo": "Foto",
		"capacity": "Capacidad",
		"auditor": "Revisor",
		"available": "Disponibilidad",
		"roomNumber": "Número de la sala",
		"phone": "Teléfono",
		"verification": {
			"inputName": "Por favor ingrese el nombre de la sala de reuniones",
			"inputBuilding": "Por favor ingrese o seleccione la ubicación de la sala de reuniones",
			"inputCapacity": "Por favor ingrese la capacidad máxima de la sala de reuniones"
		},
		"save_success": "¡La sala de reuniones se ha guardado correctamente!"
	},
	"listNavi": {
		"myApply": "Mis solicitudes",
		"myMeeting": "Invitaciones recibidas",
		"wait": "Pendiente",
		"processing": "En curso",
		"completed": "Completadas",
		"reject": "Rechazadas",
		"room": "Sala de reuniones"
	},
	"config": {
		"navi": "Navegación",
		"autoHide": "Ocultar automáticamente",
		"default": "Vista predeterminada",
		"applyProcess": "Proceso relacionado",
		"legend": "Leyenda",
		"meetingStatus": "Estado de la reunión",
		"wait": "Programada",
		"progress": "En curso",
		"completed": "Completadas",
		"invite": "Invitaciones a reuniones",
		"conflict": "Conflictos de salas de reuniones",
		"weekBegin": "Inicio de la semana",
		"meetingViewer": "Visibilidad de detalles de la reunión",
		"meetingViewerTitle": "Si la visibilidad está vacía, solo el organizador, los invitados y los administradores pueden ver los detalles de la reunión correspondiente.",
		"viewSetting": "Habilitar vista",
		"viewCustomName": "Nombre personalizado de la vista",
		"mobileCreateEnable": "¿Permitir crear reuniones en dispositivos móviles?",
		"mobileCreateEnableOptions": [
			"Sí",
			"No"
		],
		"meetingType": "Tipos de reuniones (uno por línea)",
		"enableOnline": "Habilitar reunión en línea",
		"onlineConfig": "Configuración de reuniones en línea",
		"onlineProduct": "Producto de reunión en línea",
		"hstUrl": "dirección de Servicio",
		"hstKey": "KEY de interfaz de servicio",
		"hstSecret": "Interfaz de servicio SECRET",
		"hstAuth": "¿Se requiere autenticación?",
		"o2ToHstUid": "Campos de mapeo de personas",
		"onlineConfigNotEmpty": "La dirección del servicio GoodSight, la interfaz \"KEY\", la interfaz \"SECRET\" no puede estar vacía",
		"employee": "employee",
		"unique": "unique",
		"distinguishedName": "distinguishedName",
		"mobile": "mobile",
		"mail": "mail",
		"weixin": "qq",
		"qq": "qq",
		"apiAddress": "dirección api de conferencia web",
		"key": "key",
		"secret": "secret"
	},
	"nextActivity": "Siguiente actividad:",
	"nextUser": "Persona responsable:",
	"deal": "Procesar",
	"processStarted": "Proceso iniciado",
	"processStartedMessage": "Has iniciado un nuevo proceso de trabajo:",
	"needSignInPerson": "lista de registro de asistencia",
	"printQrcode": "Imprimir código QR para el registro de asistencia",
	"weeklyViewTitle": "{month}, Semana {week}",
	"meeting_input_url_number_error": "¡¡ el enlace de la reunión y el número de la reunión no pueden estar vacíos al mismo tiempo!",
	"onlineConfigNotJson": "La configuración de la Conferencia en línea no está configurada para el formato json correcto"
}
MWF.xApplication.Meeting["lp."+o2.language] = MWF.xApplication.Meeting.LP