MWF.xApplication.Meeting.LP = {
	"title": "会議管理",

    "metting" : "会議",
    "subject": "会議タイトル",
    "applyPerson": "申請者",
    "myMeeting": "私の会議",
    "month": "月",
    "day": "日",
    "room": "会議室",
    "list": "会議リスト",
    "today": "今日",
    "tomorrow": "明日",
    "afterTomorrow": "明後日",
    "yesterday": "昨日",
    "beforeYesterday": "一昨日",
    "nextMonth": "来月",
    "floor": "階",
    "enable": "有効",
    "disable": "無効",
    "cancel": "キャン",
    "close": "閉じる",
    "save": "保存",
    "newBuilding": "新しい場所",
    "editBuilding": "場所の編集",
    //"inputAddress": "住所を入力",
    "meetingApply": "{person}の会議申請",
    "myMeetingApply": "私の会議申請",
    "attend": "時間通りに出席してください",
    "beginDate": "日付",
    "beginTime": "開始時間",
    "endTime": "終了時間",
    "time": "時間",
    "meetingTime" : "会議時間",
    "selectRoom": "会議室選択",
    "invitePerson": "参加者招待",
    "invitePerson1": "招待者",
    "invitePerson2": "参加者",
    "addInvitePerson1": "招待者を追加",
    "addedInvitePerson1": "招待者が追加されました",

    "deleteInvitePerson": "招待者が削除されました",
    "deleteInvitePerson1": "招待者を削除",
    "deleteInvitePerson2": "削除済み",
    "userDeleteInvitePerson": "会議の招待がキャンセルされました",

    "acceptPerson": "受諾済み",
    "rejectPerson": "拒否済み",

    "waitAccept": "招待を待っています",
    "waitConfirm": "承認が必要です",
    "isAccept": "時間通りに会議に出席してください",
    "timeRangeHour": "{n}時間",
    "timeRangeMinute": "{h}時間{m}分",
    "accepted": "会議の招待を受けました",
    "rejected": "会議の招待を拒否しました",
    "accept": "会議の招待を受ける",
    "reject": "会議の招待を拒否する",
    "disagree": "拒否",
    "agree": "同意",
    "countMeetings": "件の会議",
    "noMeetingWeek": "1週間内に会議がありません",
    "newlyMeeting": "{time}：{name}，場所：{room}",
    "am" : "午前",
    "pm" : "午後",
    "monthSelectTextPrev" : "未来を表示",
    "monthSelectTextAfter" : "ヶ月の会議",
    "meetingNotice" : "会議のお知らせ",
    "noComingMeeting" : "次の{month}ヶ月間には会議の招待がありません",
    "roomViewHelp" : "時間と持続時間を選択して空いている会議室を検索できます。<br/>使用できない会議室はグレー表示され、衝突する会議は赤で表示されます。",

    "delete": "削除",

    "reject_confirm_title": "会議拒否確認",
    "reject_confirm": "「{name}」会議の参加を拒否してもよろしいですか？",

    "cancel_confirm_title": "会議キャンセル確認",
    "cancel_confirm": "「{name}」会議の開催をキャンセルすることを選択しました。この会議申請は削除されます。実行してもよろしいですか？",

    "accept_confirm_title": "会議参加確認",
    "accept_confirm": "「{name}」会議に参加してもよろしいですか？",

    "disagree_confirm_title": "会議申請拒否確認",
    "disagree_confirm": "「{name}」会議申請を拒否してもよろしいですか？",

    "agree_confirm_title": "会議申請承認確認",
    "agree_confirm": "「{name}」会議申請を承認してもよろしいですか？",

    "cancelMeeting" : "会議のキャンセル",
    "applyMeeting": "会議の申し込み",
    "addMeeting": "新規会議",
    "editMeeting" : "会議の編集",
    "addRoom": "新しい会議室",
    "editRoom": "会議室の編集",
    "refresh": "リフレッシュ",
    "setting": "設定",
    "phone": "電話",
    "mail": "メール",
    "meetingSubject": "会議の件名",
    "meetingDescription": "会議の詳細",
    "meetingAttachment": "会議資料",
    "meetingDetail" : "会議の詳細情報",
    "editAddress" : "住所の編集",
    "removeBuilding" : "場所の削除",
    "address" : "住所",
    "name" : "名前",
    "meetingTopInfor" : "{userName}さん、こんにちは！今日は<span style='color: #FB4747'>{count}</span>件の会議に参加する必要があります：",
    "noMeetingTopInfor" : "{userName}さん、こんにちは！今日は会議予定がありません。",
    "roomDisable" : "会議室が無効になっています",
    "noPermission" : "会議の詳細情報は表示できません",

    "config_saveSuccess": "設定が正常に保存されました！",

    "cancel_createMeeting_title": "会議申し込みのキャンセル確認",
    "cancel_createMeeting": "会議の申し込みをキャンセルしようとしています。入力したデータは失われます。現在の会議の申し込みをキャンセルしますか？",

    "meeting_input_error": "次の内容を正確に入力してください：<br/>",
    //"meeting_input_subject_error": "请填写完整会议标题！",
    //"meeting_input_room_error": "请选择会议室！",
    //"meeting_input_person_error": "请选择邀请参会人员！",
    //"meeting_input_date_error": "请正确选择会议开始日期和时间！",
    //"meeting_input_time_error": "请正确选择会议开始时间和结束时间！",

    "meeting_input_subject_error": "会議のタイトルは空白にできません！",
    "meeting_input_room_error": "会議室は空白にできません！",
    "meeting_input_url_number_error": "会議リンクと会議番号を同時に空白にできません！",
    "meeting_input_person_error": "出席者を招待する必要があります！",
    "meeting_input_date_error": "会議の開始時間は現在の時間よりも前にはできません！",
    "meeting_input_time_error": "会議の終了時間は開始時間よりも前にはできません！",


    //"meeting_input_subject_error": "请填写完整会议标题！",
    "meeting_saveSuccess": "会議申し込みが正常に保存されました！",

    "deleteAttachmentTitle":"添付ファイル削除確認",
    "deleteAttachment": "選択した添付ファイルを削除しますか？",

    "startMeetingImmediately" : "会議開始",
    "endMeetingImmediately" : "会議終了",
    "startMeetingSucccess" : "会議が開始されました",
    "endMeetingSucccess" : "会議が終了しました",

    "dateFormatMonth": "%Y年%m月",
    "dateFormatMonthDay": "%m月%d日",
    "dateFormatMonthOnly": "%m月",
    "dateFormatDay": "%Y年%m月%d日",
    "dateFormatDayOnly": "%d日",
    "dateFormatAll": "%Y年%m月%d日 %H:%M",
    "dateFormat": "db",
    "person": "人",
    "persist": "持続",
    "hour": "時間",
    "minute" : "分",
    "to" : "から",
    "all" : "すべて",

    "myWaitConfirm": "審査待ち",
    "myWaitAccept": "招待",

    "noTask": "今日は会議の招待がありません",
    "noMeeting": "当日の会議はありません",
    "noAddress" : "住所が未入力です",

    "hostPerson": "ホスト",
    "hostUnit": "主催部署",
    "meetingType":"会議タイプ",
    "meetingMode":"会議モード",
    "meetingModeSelectText": ["対面会議","オンライン会議"],
    "meetingModeSelectValue": ["offline","online"],
    "meetingUrl": "会議リンク",
    "openMeetingUrl": "会議リンクを開く",
    "meetingNumber": "会議番号",
    "netMeetingAbb": "ネット",
    "yes": "はい",
    "no": "いいえ",
    "other": "その他",
    "createOnSave": "保存後に自動生成",
    "copy": "コピー",
    "noRoomBuilding": "オンライン会議\n(会議室なし)",

    "week" : "週",
    "weeks": {
        "Sun": "日曜日",
        "Mon": "月曜日",
        "Tues": "火曜日",
        "Wed": "水曜日",
        "Thur": "木曜日",
        "Fri": "金曜日",
        "Sat": "土曜日",
        "arr": ["日曜日","月曜日","火曜日","水曜日","木曜日","金曜日","土曜日"]
    },

    "device": {
        "projector": "プロジェクター",
        "board": "ホワイトボード",
        "tvset": "テレビ",
        "tv": "ビデオ会議",
        "camera": "カメラ",
        "wifi": "ネットワーク",
        "phone": "電話会議"
    },
    "inputAddress": "住所を追加",
    "save_success": "保存成功！",
    "delete_building_title": "削除確認",
    "delete_building_hasRoom": "“{name}”にはまだ会議室があるため、削除できません。",
    "delete_building": "“{name}”を削除しますか？",
    "delete_room": "会議室“{name}”を削除しますか",

    "roomForm": {
        "name": "会議室名",
        "building": "会議室の位置",
        "floor": "会議室の階層",
        "device": "会議室の設備",
        "photo": "写真",
        "capacity": "収容人数",
        "auditor": "会議室の審査者",
        "available": "会議室の状態",
        "roomNumber": "会議室の部屋番号",
        "phone": "内線番号",

        "verification": {
            "inputName": "会議室名を入力してください",
            "inputBuilding": "会議室の位置を入力または選択してください",
            "inputCapacity": "会議室の収容可能人数を入力してください"
        },
        "save_success": "会議室の保存に成功しました！"
    },
    "listNavi": {
        "myApply": "私の会議申請",
        "myMeeting": "私が受け取った招待状",
        "wait": "開始前",
        "processing": "進行中",
        "completed": "終了済み",
        "reject": "拒否済み",
        "room": "会議室"
    },
    "config": {
        "navi": "ナビゲーション",
        "autoHide": "自動非表示",
        "default": "デフォルトビュー",
        "applyProcess": "会議申請プロセス",
        "legend": "凡例",
        "meetingStatus": "会議状態",
        "wait": "予約中",
        "progress": "進行中",
        "completed": "終了",
        "invite": "会議招待",
        "conflict": "会議室の競合",
        "weekBegin": "週の開始日",
        "meetingViewer": "会議詳細表示範囲",
        "meetingViewerTitle": "表示範囲が空白の場合、詳細情報を見ることができるのは、申請者、招待されたユーザー、および会議管理者だけです。",
        "viewSetting": "ビューを有効にする",
        "viewCustomName": "ビュー表示名",
        "mobileCreateEnable": "モバイルでの会議作成を有効にする",
        "mobileCreateEnableOptions": ["はい", "いいえ"],
        "meetingType": "会議の種類（各行に1つずつ）",
        "enableOnline": "オンライン会議を有効にする",
        "onlineProduct": "オンライン会議製品",
        "onlineConfig": "オンライン会議の設定",
        'hstUrl': 'Haoshi通サービスアドレス',
        'hstKey': 'Haoshi通サービスインターフェースキー',
        'hstSecret': 'Haoshi通サービスインターフェースシークレット',
        'hstAuth': 'Haoshi通会議認証ログイン',
        'o2ToHstUid': 'O2とHaoshi通のマッピングユーザーフィールド',
        "onlineConfigNotEmpty": "Haoshi通サービスアドレス、インターフェースキー、インターフェースシークレットは空にできません",
        "employee": "従業員番号(employee)",
        "unique": "ユニークコード(unique)",
        "distinguishedName": "氏名(distinguishedName)",
        "mobile": "携帯電話(mobile)",
        "mail": "メール(mail)",
        "weixin": "WeChat番号(qq)",
        "qq": "QQ番号(qq)",
        "apiAddress": "オンライン会議APIアドレス",
        "key": "キー(key)",
        "secret": "シークレット(secret)"
    },
    "nextActivity": "次のアクティビティ:",
    "nextUser": "処理者:",
    "deal": "処理",
    "processStarted": "ファイルが開始されました",
    "processStartedMessage": "新しい作業を開始しました:",
    "needSignInPerson": "出席者",
    "printQrcode": "出席用QRコード印刷",
    "weeklyViewTitle": "{month}、第{week}週",
    "onlineConfigNotJson": "オンライン会議の設定が正しいJSON形式に設定されていません"
};