MWF.xApplication.Meeting.LP = {
	"title": "회의 관리",

    "metting" : "회의",
    "subject": "회의 주제",
    "applyPerson": "신청자",
    "myMeeting": "나의 회의",
    "month": "월",
    "day": "일",
    "room": "회의실",
    "list": "회의 목록",
    "today": "오늘",
    "tomorrow": "내일",
    "afterTomorrow": "모레",
    "yesterday": "어제",
    "beforeYesterday": "그제",
    "nextMonth": "다음 달",
    "floor": "층",
    "enable": "사용 가능",
    "disable": "사용 중지",
    "cancel": "취소",
    "close": "닫기",
    "save": "저장",
    "newBuilding": "새 위치",
    "editBuilding": "위치 편집",
    //"inputAddress": "주소 입력",
    "meetingApply": "{person}의 회의 신청",
    "myMeetingApply": "내 회의 신청",
    "attend": "시간을 지켜 참석하세요",
    "beginDate": "날짜",
    "beginTime": "시작 시간",
    "endTime": "종료 시간",
    "time": "시간",
    "meetingTime" : "회의 시간",
    "selectRoom": "회의실 선택",
    "invitePerson": "참석자 초대",
    "invitePerson1": "초대자",
    "invitePerson2": "참석자",
    "addInvitePerson1": "초대자 추가",
    "addedInvitePerson1": "초대자 추가됨",

    "deleteInvitePerson": "초대자 삭제됨",
    "deleteInvitePerson1": "초대자 삭제",
    "deleteInvitePerson2": "삭제됨",
    "userDeleteInvitePerson": "회의 초대가 취소되었습니다",

    "acceptPerson": "수락됨",
    "rejectPerson": "거절됨",

    "waitAccept": "참석 요청 수락",
    "waitConfirm": "승인 필요",
    "isAccept": "시간을 지켜 회의에 참석해주세요",
    "timeRangeHour": "{n}시간",
    "timeRangeMinute": "{h}시간 {m}분",
    "accepted": "회의 초대를 수락했습니다",
    "rejected": "회의 초대를 거절했습니다",
    "accept": "회의 초대 수락",
    "reject": "회의 초대 거절",
    "disagree": "거부",
    "agree": "동의",
    "countMeetings": "회의 개수",
    "noMeetingWeek": "참석할 회의가 없습니다",
    "newlyMeeting": "{time} : {name}, 장소 : {room}",
    "am": "오전",
    "pm": "오후",
    "monthSelectTextPrev": "미래 표시",
    "monthSelectTextAfter": "개월 동안의 회의",
    "meetingNotice": "회의 알림",
    "noComingMeeting": "{month}개월 동안 참석할 회의가 없습니다",
    "roomViewHelp": "시간 및 지속 시간을 선택하여 빈 회의실을 검색할 수 있습니다.<br/>사용 불가능한 회의실은 회색으로 표시되며 충돌되는 회의는 빨간색으로 표시됩니다.",

    "delete": "삭제",

    "reject_confirm_title": "회의 거절 확인",
    "reject_confirm": "{name} 회의 참석을 거절하시겠습니까?",

    "cancel_confirm_title": "회의 취소 확인",
    "cancel_confirm": "{name} 회의를 취소하시겠습니까? 이로써 회의 신청이 삭제됩니다. 진행하시겠습니까?",

    "accept_confirm_title": "회의 수락 확인",
    "accept_confirm": "{name} 회의에 참석하시겠습니까?",

    "disagree_confirm_title": "회의 신청 거부 확인",
    "disagree_confirm": "{name} 회의 신청을 거부하시겠습니까?",

    "agree_confirm_title": "회의 신청 승인 확인",
    "agree_confirm": "{name} 회의 신청을 승인하시겠습니까?",

    "cancelMeeting" : "회의 취소",
    "applyMeeting": "회의 신청",
    "addMeeting": "신규 회의",
    "editMeeting" : "회의 수정",
    "addRoom": "신규 회의실",
    "editRoom": "회의실 수정",
    "refresh": "새로고침",
    "setting": "설정",
    "phone": "휴대폰",
    "mail": "이메일",
    "meetingSubject": "회의 제목",
    "meetingDescription": "회의 설명",
    "meetingAttachment": "회의 자료",
    "meetingDetail" : "회의 상세 정보",
    "editAddress" : "주소 수정",
    "removeBuilding" : "위치 삭제",
    "address" : "주소",
    "name" : "이름",
    "meetingTopInfor" : "{userName}님, 안녕하세요! 오늘은 <span style='color: #FB4747'>{count}</span>개의 회의에 참석하셔야 합니다:",
    "noMeetingTopInfor" : "{userName}님, 안녕하세요! 오늘은 회의 일정이 없습니다.",
    "roomDisable" : "회의실 비활성화됨",
    "noPermission" : "회의 상세 정보를 볼 수 없음",

    "config_saveSuccess": "설정이 성공적으로 저장되었습니다!",

    "cancel_createMeeting_title": "회의 신청 취소 확인",
    "cancel_createMeeting": "회의 신청을 취소하려고 합니다. 입력한 데이터가 손실됩니다. 현재 회의 신청을 취소하시겠습니까?",

    "meeting_input_error": "다음 내용을 올바르게 입력하세요:<br/>",
    //"meeting_input_subject_error": "请填写完整会议标题！",
    //"meeting_input_room_error": "请选择会议室！",
    //"meeting_input_person_error": "请选择邀请参会人员！",
    //"meeting_input_date_error": "请正确选择会议开始日期和时间！",
    //"meeting_input_time_error": "请正确选择会议开始时间和结束时间！",

    "meeting_input_subject_error": "회의 제목은 비워 둘 수 없습니다!",
    "meeting_input_room_error": "회의실은 비워 둘 수 없습니다!",
    "meeting_input_url_number_error": "회의 링크와 회의 번호를 동시에 비워 둘 수 없습니다!",
    "meeting_input_person_error": "참석자를 초대하셔야 합니다!",
    "meeting_input_date_error": "회의 시작 시간은 현재 시간보다 이른 시간일 수 없습니다!",
    "meeting_input_time_error": "회의 종료 시간은 시작 시간보다 이른 시간일 수 없습니다!",


    //"meeting_input_subject_error": "请填写完整会议标题！",
    "meeting_saveSuccess": "회의 신청이 성공적으로 저장되었습니다！",

    "deleteAttachmentTitle":"첨부 파일 삭제 확인",
    "deleteAttachment": "선택한 첨부 파일을 삭제하시겠습니까?",

    "startMeetingImmediately" : "회의 시작",
    "endMeetingImmediately" : "회의 종료",
    "startMeetingSucccess" : "회의가 시작되었습니다",
    "endMeetingSucccess" : "회의가 종료되었습니다",

    "dateFormatMonth": "%Y년%m월",
    "dateFormatMonthDay": "%m월%d일",
    "dateFormatMonthOnly": "%m월",
    "dateFormatDay": "%Y년%m월%d일",
    "dateFormatDayOnly": "%d일",
    "dateFormatAll": "%Y년%m월%d일 %H:%M",
    "dateFormat": "db",
    "person": "명",
    "persist": "지속",
    "hour": "시간",
    "minute" : "분",
    "to" : "에서",
    "all" : "전체",

    "myWaitConfirm": "심사 대기",
    "myWaitAccept": "초대",

    "noTask": "오늘은 회의 초대가 없습니다",
    "noMeeting": "오늘은 회의 일정이 없습니다",
    "noAddress" : "주소를 입력하지 않았습니다",

    "hostPerson": "주최자",
    "hostUnit": "주관부서",
    "meetingType":"회의 유형",
    "meetingMode":"회의 방식",
    "meetingModeSelectText": ["오프라인 회의","온라인 회의"],
    "meetingModeSelectValue": ["offline","online"],
    "meetingUrl": "회의 링크",
    "openMeetingUrl": "회의 링크 열기",
    "meetingNumber": "회의 번호",
    "netMeetingAbb": "인터넷",
    "yes": "예",
    "no": "아니오",
    "other": "기타",
    "createOnSave": "저장 후 자동 생성",
    "copy": "복사",
    "noRoomBuilding": "온라인 회의\n(회의실 없음)",

    "week" : "주",
    "weeks": {
        "Sun": "일요일",
        "Mon": "월요일",
        "Tues": "화요일",
        "Wed": "수요일",
        "Thur": "목요일",
        "Fri": "금요일",
        "Sat": "토요일",
        "arr": ["일요일","월요일","화요일","수요일","목요일","금요일","토요일"]
    },

    "device": {
        "projector": "프로젝터",
        "board": "화이트보드",
        "tvset": "텔레비전",
        "tv": "비디오 회의",
        "camera": "카메라",
        "wifi": "무선 네트워크",
        "phone": "전화 회의"
    },
    "inputAddress": "주소 추가",
    "save_success": "저장 성공!",
    "delete_building_title": "삭제 확인",
    "delete_building_hasRoom": "“{name}”에는 아직 회의실이 있으므로 삭제할 수 없습니다.",
    "delete_building": "“{name}”을 삭제하시겠습니까?",
    "delete_room": "“{name}” 회의실을 삭제하시겠습니까",

    "roomForm": {
        "name": "회의실 이름",
        "building": "회의실 위치",
        "floor": "회의실 층",
        "device": "회의실 장비",
        "photo": "사진",
        "capacity": "수용 인원",
        "auditor": "회의실 검토자",
        "available": "회의실 상태",
        "roomNumber": "회의실 번호",
        "phone": "내선 번호",

        "verification": {
            "inputName": "회의실 이름을 입력하세요",
            "inputBuilding": "회의실 위치를 입력하거나 선택하세요",
            "inputCapacity": "회의실 수용 가능한 인원을 입력하세요"
        },
        "save_success": "회의실 저장 성공!"
    },
    "listNavi": {
        "myApply": "내 회의 신청",
        "myMeeting": "나에게 온 초대",
        "wait": "미시작",
        "processing": "진행 중",
        "completed": "종료됨",
        "reject": "거부됨",
        "room": "회의실"
    },
    "config": {
        "navi": "내비게이션",
        "autoHide": "자동 숨기기",
        "default": "기본 뷰",
        "applyProcess": "회의 신청 프로세스",
        "legend": "범례",
        "meetingStatus": "회의 상태",
        "wait": "예약됨",
        "progress": "진행 중",
        "completed": "종료됨",
        "invite": "회의 초대",
        "conflict": "회의실 충돌",
        "weekBegin": "주의 시작 요일",
        "meetingViewer": "회의 상세 정보 표시 범위",
        "meetingViewerTitle": "표시 범위가 비어 있으면 신청자, 초대된 사용자 및 회의 관리자 만 해당 회의 세부 정보를 볼 수 있습니다.",
        "viewSetting": "뷰 활성화",
        "viewCustomName": "뷰 표시 이름",
        "mobileCreateEnable": "모바일에서 회의 생성 활성화",
        "mobileCreateEnableOptions": ["예", "아니오"],
        "meetingType": "회의 유형(각 행에 하나씩)",
        "enableOnline": "온라인 회의 활성화",
        "onlineProduct": "온라인 회의 제품",
        "onlineConfig": "온라인 회의 설정",
        'hstUrl': '호시통 서비스 주소',
        'hstKey': '호시통 서비스 인터페이스 키',
        'hstSecret': '호시통 서비스 인터페이스 비밀',
        'hstAuth': '호시통 회의 인증 로그인',
        'o2ToHstUid': 'O2 및 호시통 매핑 사용자 필드',
        "onlineConfigNotEmpty": "호시통 서비스 주소, 인터페이스 키 및 인터페이스 비밀을 비울 수 없습니다",
        "employee": "직원 번호(employee)",
        "unique": "고유 코드(unique)",
        "distinguishedName": "전체 이름(distinguishedName)",
        "mobile": "휴대전화(mobile)",
        "mail": "이메일(mail)",
        "weixin": "위챗 번호(qq)",
        "qq": "QQ 번호(qq)",
        "apiAddress": "온라인 회의 API 주소",
        "key": "키(key)",
        "secret": "비밀(secret)"
    },
    "nextActivity": "다음 활동:",
    "nextUser": "처리자:",
    "deal": "처리",
    "processStarted": "파일이 시작되었습니다",
    "processStartedMessage": "새 작업을 시작했습니다:",
    "needSignInPerson": "출석자",
    "printQrcode": "출석 QR 코드 인쇄",
    "weeklyViewTitle": "{month} {week}주",
    "onlineConfigNotJson": "온라인 회의 설정이 올바른 JSON 형식으로 구성되지 않았습니다"
};