MWF.xApplication.Meeting.LP = {
    "title": "ບໍລິຫານການປະຊຸມ",

    "metting" : "ປະຊຸມ",
    "subject": "ຫົວຂໍ້ປະຊຸມ",
    "applyPerson": "ຜູ້ຮຽກຮ້ອງ",
    "myMeeting": "ປະຊຸມຂອງຂ້ອຍ",
    "month": "ເດືອນ",
    "day": "ມື້",
    "room": "ຫ້ອງປະຊຸມ",
    "list": "ລາຍລະອຽດການປະຊຸມ",
    "today": "ມື້ນີ້",
    "tomorrow": "ມື້ອື່ນ",
    "afterTomorrow": "2 ມື້ຕໍ່ໄປ",
    "yesterday": "ມື້ວານ",
    "beforeYesterday": "2 ມື້ ກ່ອນ",
    "nextMonth": "ເດືອນໜ້າ",
    "floor": "ຊັ້ນ",
    "enable": "ໃຊ້ງານ",
    "disable": "ຢຸດໃຊ້ງານ",
    "cancel": "ຍົກເລີກ",
    "close": "ປິດ",
    "save": "ບັນທຶກ",
    "newBuilding": "ສະຖານທີ່ໃໝ່",
    "editBuilding": "ຕັ້ງຄ່າທີ່ຕັ້ງ",
    //"inputAddress": "ເພີ່ມສະຖານທີ່",
    "meetingApply": "{person}ຄຳຮ້ອງຂໍປະຊຸມ",
    "myMeetingApply": "ຄຳຮ້ອງປະຊຸມຂອງຂ້ອຍ",
    "attend": "ກະລຸນາຕົງຕໍ່ເວລາ",
    "beginDate": "ວັນທີ່",
    "beginTime": "ເລີ່ມເວລາ",
    "endTime": "ສິ້ນສຸດເວລາ",
    "time": "ເວລາ",
    "meetingTime" : "ປະຊຸມເວລາ",
    "selectRoom": "ຫ້ອງປະຊຸມ",
    "invitePerson": "ເຊີນພະນັກງານເຂົ້າຮ່ວມປະຊຸມ",
    "invitePerson1": "ເຊີນບຸກຄົນ",
    "invitePerson2": "ຄົນເຂົ້າຮ່ວມ",
    "addInvitePerson1": "ເພີ່ມເຊີນຄົນ",
    "addedInvitePerson1": "ເພີ່ມເຊີນຄົນແລ້ວ",

    "deleteInvitePerson": "ຄົນເຊີນຍົກເລີກແລ້ວ",
    "deleteInvitePerson1": "ຍົກເລີກຄົນເຊີນ",
    "deleteInvitePerson2": "ຍົກເລີກແລ້ວ",
    "userDeleteInvitePerson": "ການເຊີນປະຊຸມຂອງເຈົ້າຖືກຍົກເລີກແລ້ວ",

    "acceptPerson": "ຍອມຮັບແລ້ວ",
    "rejectPerson": "ປະຕິເສດແລ້ວ",

    "waitAccept": "ເຊີນເຈົ້າເຂົ້າຮ່ວມ",
    "waitConfirm": "ຕ້ອງການໃຫ້ເຈົ້າອະນຸມັດ",
    "isAccept": "ກະລຸນາເຂົ້າຮ່ວມປະຊຸມຕາມເວລາ",
    "timeRangeHour": "{n}ຊົ່ວໂມງ",
    "timeRangeMinute": "{h}ຊົ່ວໂມງ{m}ນາທີ",
    "accepted": "ການເຊີນປະຊຸມໄດ້ຖືກຍອມຮັບແລ້ວ",
    "rejected": "ການເຊີນປະຊຸມໄດ້ຖືກປະຕິເສດແລ້ວ",
    "accept": "ຍອມຮັບການເຊີນ",
    "reject": "ປະຕິເສດການເຊີນ",
    "disagree": "ຍົກເລີກ",
    "agree": "ຍອມຮັບ",
    "countMeetings": "ປະຊຸມ",
    "noMeetingWeek": "ໃນອາທິດນີ້ບໍ່ມີປະຊຸມ",
    "newlyMeeting": "{time}：{name}，ສະຖານທີ່：{room}",
    "am" : "ຕອນສວຍ",
    "pm" : "ຕອນເຊົ້າ",
    "monthSelectTextPrev" : "ສະແດງໃຫ້ເຫັນອະນາຄົດ",
    "monthSelectTextAfter" : "ການປະຊຸມປະຈຳເດືອນ",
    "meetingNotice" : "ລາຍງານການປະຊຸມ",
    "noComingMeeting" : "ສຳລັບ{month}ບໍ່ມີການເຊີນປະຊຸມປະຈຳເດືອນ",
    "roomViewHelp" : "ເຈົ້າສາມາດເລືອກເວລາ ແລະ ຄົ້ນຫາຫ້ອງປະຊຸມທີ່ວ່າງໄດ້。<br/>ຫ້ອງປະຊຸມທີ່ວ່າງຈະເປັນເຄື່ອງໝາຍສີເທົາ，ສ່ວນຫ້ອງປະຊຸມທີ່ໃຊ້ງານຈະເປັນເຄື່ອງໝາຍສີແດງ。",

    "delete" : "ລົບ",

    "reject_confirm_title": "ຢືນຢັນປະຕິເສດປະຊຸມ",
    "reject_confirm": "ເຈົ້າແນ່ໃຈວ່າຈະປະຕິເສດກນເຂົ້າຮ່ວມ“{name}”ປະຊຸມບໍ?",

    "cancel_confirm_title": "ຍົກເລີກການຢືນຢັນປະຊຸມ",
    "cancel_confirm": "ເຈົ້າເລືອກທີ່ຈະຍົກເລີກການເຂົ້າຮ່ວມ“{name}”ປະຊຸມ，ການຮ້ອງຂໍຈະຖືກລົບ，ເຈົ້າແນ່ໃຈບໍຈະລົບມັນ?",

    "accept_confirm_title": "ຍອມຮັບການເຂົ້າຮ່ວມ",
    "accept_confirm": "ເຈົ້າແນ່ໃຈເຂົ້າຮ່ວມ“{name}”ປະຊຸມບໍ?",

    "disagree_confirm_title": "ຢືນຢັນການປະຕິເສດການຮ້ອງຂໍ",
    "disagree_confirm": "ເຈົ້າແນ່ໃຈວ່າຈະປະຕິເສດ“{name}”ການເຂົ້າຮ່ວມບໍ?",

    "agree_confirm_title": "ຍອມຮັບຢືນຢັນເຂົ້າຮ່ວມ",
    "agree_confirm": "ເຈົ້າແນ່ໃຈວ່າຍອມຮັບ“{name}”ການຮ້ອງຂໍການເຂົ້າຮ່ວມ?",

    "cancelMeeting" : "ຍົກເລີກປະຊຸມ",
    "applyMeeting": "ຮ້ອງຂໍປະຊຸມ",
    "addMeeting": "ການປະຊຸມໃໝ່",
    "editMeeting" : "ຕັ້ງຄ່າການປະຊຸມ",
    "addRoom": "ຫ້ອງປະຊຸມໃໝ່",
    "editRoom": "ຕັ້ງຄ່າການປະຊຸມ",
    "refresh": "ກັບຄືນໃໝ່",
    "setting": "ຕັ້ງຄ່າ",
    "phone": "ໂທລະສັບ",
    "mail": "ເມວ",
    "meetingSubject": "ຫົວຂໍ້ປະຊຸມ",
    "meetingDescription": "ລາຍລະອຽດການປະຊຸມ",
    "meetingAttachment": "ເອກະສານປະຊຸມ",
    "meetingDetail" : "ລາຍລະອຽດການປະຊຸມ",
    "editAddress" : "ດັດແກ້ສະຖານທີ່",
    "removeBuilding" : "ລົບສະຖານທີ່",
    "address" : "ສະຖານທີ່",
    "name" : "ຊື່",
    "meetingTopInfor" : "{userName}，ສະບາຍດີ！<br/>ມື້ນີ້ເຈົ້າຕ້ອງເຂົ້າຮ່ວມ<span style='color: #FB4747'>{count}</span>ປະຊຸມ：",
    "noMeetingTopInfor" : "{userName}，ສະບາຍດີ！ມື້ນີ້ເຈົ້າບໍ່ມີປະຊຸມ。",
    "roomDisable" : "ຫ້ອງປະຊຸມຢຸດການໃຊ້ງານແລ້ວ",
    "noPermission" : "ລາຍລະອຽດການປະຊຸມບໍ່ສາມາດເຫັນໄດ້",

    "config_saveSuccess": "ບັນທຶກການກຳນົດສຳເລັດ！",

    "cancel_createMeeting_title": "ຢືນຢັນຍົກເລີກການປະຊຸມ",
    "cancel_createMeeting": "ຄໍາຮ້ອງສະຫມັກກອງປະຊຸມກໍາລັງຈະຖືກຍົກເລີກ，ຂໍ້ມູນທີ່ຕື່ມໃສ່ຈະຫາຍໄປ，ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກຄໍາຮ້ອງການປະຊຸມໃນປະຈຸບັນ？",

    "meeting_input_error": "ກະລຸນາຕື່ມຂໍ້ມູນຕໍ່ໄປນີ້ໃຫ້ຖືກຕ້ອງ：<br/>",
    //"meeting_input_subject_error": "ກະລຸນາຕື່ມຫົວຂໍ້ການປະຊຸມ！",
    //"meeting_input_room_error": "ກະລຸນາເລືອກຫ້ອງປະຊຸມ！",
    //"meeting_i    //"meeting_input_person_error": "ກະລຸນາເລືອກເພືອເຊີນພະນັກງານ！",
   
//"meeting_input_time_error": "ກະລຸນາເລືອກມື້ເລີ່ມ ແລະ ມື້ສິ້ນສຸດການປະຊຸມ！",

"meeting_input_subject_error": "ຫົວຂໍ້ປະຊຸມບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "meeting_input_room_error": "ຫ້ອງປະຊຸມບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "meeting_input_url_number_error": "ລິ້ງ ແລະ ເລກທີປະຊຸມບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "meeting_input_person_error": "ການເຊີນພະນັກງານເຂົ້າຮ່ວມປະຊຸມບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "meeting_input_date_error": "ເວລາເລີ່ມການປະຊຸມບໍ່ສາມາດໄວກວ່າຕອນນີ້ໄດ້！",
    "meeting_input_time_error": "ເວລາສິ້ນສຸດການປະຊຸມບໍ່ສາມາດໄວກວ່າມື່ເລີ່ມການປະຊຸມ！",


    //"meeting_input_subject_error": "ກະລຸນາຕື່ມຫົວຂໍ້ການປະຊຸມໃຫ້ສົມບູນ！",
    "meeting_saveSuccess": "ຮ້ອງຂໍປະຊຸມບັນທຶກສຳເລັດ！",

    "deleteAttachmentTitle":"ຢືນຢັນລົບເອກະສານ",
    "deleteAttachment": "ແນ່ໃຈ ຫຼື ບໍວ່າຕ້ອງການລົບເອກະສານທີ່ເຈົ້າເລືອກ？",

    "startMeetingImmediately" : "ເລີ່ມປະຊຸມ",
    "endMeetingImmediately" : "ສິ້ນສຸດການປະຊຸມ",
    "startMeetingSucccess" : "ເລີ່ມປະຊຸມແລ້ວ",
    "endMeetingSucccess" : "ສິ້ນສຸດການປະຊຸມ",

    "dateFormatMonth": "%Yປີ%mເດືອນ",
    "dateFormatMonthDay": "%mເດືອນ%dມື້",
    "dateFormatMonthOnly": "%mເດືອນ",
    "dateFormatDay": "%Yປີ%mເດືອນ%dມື້",
    "dateFormatDayOnly": "%dມື້",
    "dateFormatAll": "%Yປີ%mເດືອນ%dມື້ %H:%M",
    "dateFormat": "db",
    "person": "ຄົນ",
    "persist": "ສືບຕໍ່",
    "hour": "ຊົ່ວໂມງ",
    "minute" : "ນາທີ",
    "to" : "ເຖິງ",
    "all" : "ທັງໝົດ",

    "myWaitConfirm": "ກວດສອບ",
    "myWaitAccept": "ເຊີນ",

    "noTask": "ມື້ນີ້ບໍ່ມີເຊີນເຂົ້າຮ່ວມປະຊຸມ",
    "noMeeting": "ບໍ່ມີປະຊຸມ",
    "noAddress" : "ບໍ່ໄດ້ຕື່ມທີ່ຢູ່",

    "hostPerson": "ຄົນຄວບຄຸມ",
    "hostUnit": "ພະແນກປະຕິບັດ",
    "meetingType":"ໝວດໝູ່ປະຊຸມ",
    "meetingMode":"ວິທີການປະຊຸມ",
    "meetingModeSelectText": ["ປະຊຸມແບບເຊິ່ງໜ້າ","ປະຊຸມແບບອອນລາຍ"],
    "meetingModeSelectValue": ["offline","online"],
    "meetingUrl": "ລິ້ງ ປະຊຸມ",
    "openMeetingUrl": "ເປີດ ລິ້ງ ປະຊຸມ",
    "meetingNumber": "ປະຊຸມເລກທີ່",
    "netMeetingAbb": "",
    "yes": "ແມ່ນ",
    "no": "ບໍ່",
    "other": "ອື່ນໆ",
    "createOnSave": "ສ້າງຂຶ້ນອັດຕະໂນມັດຫຼັງຈາກບັນທຶກ",
    "copy": "ສຳເນົາ",
    "noRoomBuilding": "ປະຊຸມອອນລາຍ\n(ບໍ່ມີຫ້ອງປະຊຸມ)",

    "week" : "ອາທິດ",
    "weeks": {
    "Sun": "ວັນທິດ",
        "Mon": "ວັນຈັນ",
        "Tues": "ວັນອັງຄານ",
        "Wed": "ວັນພຸດ",
        "Thur": "ວັນພະຫັດ",
        "Fri": "ວັນສຸກ",
        "Sat": "ວັນເສົາ",
        "arr": ["ວັນທິດ","ວັນຈັນ","ວັນອັງຄານ","ວັນພຸດ","ວັນພະຫັດ","ວັນສຸກ","ວັນເສົາ"]
},

"device": {
    "projector": "projector",
        "board": "ກະດນຂາວ",
        "tvset": "ໂທລະພາບ",
        "tv": "ວີດີໂອປະຊຸມ",
        "camera": "ກ້ອງ",
        "wifi": "ໄວຟາຍ",
        "phone": "ປະຊຸມໂທລະສັບ"
},
"inputAddress": "ເພີ່ມທີ່ຢູ່",
    "save_success": "ບັນທຶກສຳເລັດ！",
    "delete_building_title": "ຢືນຢັນລົບ",
    "delete_building_hasRoom" : "“{name}”ຊັ້ນລຸ່ມຍັງມີຫ້ອງປະຊຸມ，ບໍາສາມາດລົບໄດ້。",
    "delete_building": "ເຈົ້າຕ້ອງການລົບ“{name}”ບໍ",
    "delete_room": "ເຈົ້າຕ້ອງການລົບຫ້ອງປະຊຸມ“{name}”ບໍ",

    "roomForm": {
    "name": "ຊື່ຫ້ອງປະຊຸມ",
        "building": "ທີ່ຕັ້ງຫ້ອງປະຊຸມ",
        "floor": "ຊັ້ນທີ່",
        "device": "ອຸປະກອນຫ້ອງປະຊຸມ",
        "photo": "ຮູບພາບ",
        "capacity": "ຄວາມຈຸ",
        "auditor": "ຄົນກວດສອບຫ້ອງປະຊຸມ",
        "available": "ສະຖານະຫ້ອງປະຊຸມ",
        "roomNumber": "ໝາຍເລກປະຕູ",
        "phone": "ເລກໂທລະສັບ",

        "verification": {
        "inputName": "ກະລຸນາໃສ່ຊື່ຫ້ອງປະຊຸມ",
            "inputBuilding": "ກະລຸນາ ປ້ອນ ຫຼື ເລືອກສະຖານທີ່ຫ້ອງປະຊຸມ",
            "inputCapacity": "ກະລຸນາໃສ່ຈຳນວນຄົນທີ່ຫ້ອງປະຊຸມບັນຈຸ"

    },
    "save_success": "ຫ້ອງປະຊຸມບັນທຶກສຳເລັດ！"
},
"listNavi": {
    "myApply": "ໃບຮ້ອງຂໍປະຊຸມຂອງຂ້ອຍ",
        "myMeeting" :"ຄຳເຊີນທີ່ເຈົ້າໄດ້ຮັບ",
        "wait": "ຍັງບໍ່ໄດ້ເລີ່ມ",
        "processing": "ກຳລັງດຳເນີນການ",
        "completed": "ສິ້ນສຸດແລ້ວ",
        "reject": "ປະຕິເສດແລ້ວ",
        "room": "ຫ້ອງປະຊຸມ"
},
"config": {
    "navi": "ບອກທິດທາງ",
        "autoHide": "ເຊື່ອງອັດຕະໂນມັດ",
        "default": "Default View",
        "applyProcess": "ຂະບວນການປະຊຸມ Application",
        "legend": "Icon",
        "meetingStatus" : "ສະຖານະກນປະຊຸມ",
        "wait": "ແຕ່ງຕັ້ງແລ້ວ",
        "progress": "ໃນຫ້ອງປະຊຸມ",
        "completed": "ປະຊຸມສິ້ນສຸດແລ້ວ",
        "invite": "ເຊີນປະຊຸມ",
        "conflict": "ຂໍ້ຂັດແຍ້ງໃນຫ້ອງປະຊຸມ",
        "weekBegin" : "ມື້ເລີ່ມຕົ້ນຂອງອາທິດ",
        "meetingViewer" : "ລາຍລະອຽດຂອງກອງປະຊຸມທີ່ສັງເກດເຫັນ",
        "meetingViewerTitle" : "ຖ້າວ່າເຫັນຂອບເຂດເວັ້ນວ່າງ, ສະເພາະຜູ້ສ້າງ, ຜູ້ຖືກເຊີນແລະຜູ້ດູແລການປະຊຸມເທົ່ານັ້ນຈຶ່ງສາມາດເຫັນລາຍລະອຽດການປະຊຸມໄດ້。",
        "viewSetting" : "ເປີດໃຊ້ງານ View",
        "viewCustomName" : "Display name",
        "mobileCreateEnable" : "ສາມາດສ້າງກອງປະຊຸມໃຫມ່ໃນມືຖືໄດ້ບໍ",
        "mobileCreateEnableOptions" : ["ແມ່ນ","ບໍ່"],
        "meetingType":"ປະເພດການປະຊຸມ (ຕໍ່1ແຖວ）",
        "enableOnline":"ເປີດກອງປະຊຸມອອນລາຍ",
        "onlineProduct": "ຜະລິດຕະພັນການປະຊຸມອອນລາຍ",
        "onlineConfig": "ການກຳນົດປະຊຸມອອນລາຍ",

        'hstUrl':'ບໍລິການທີ່ຢູ່',
        'hstKey':'ບໍລິການ interface Key',
        'hstSecret':'ບໍລິການ interface Secret',
        'hstAuth':'ເຂົ້າສູ່ລະບົບຢ່າງຖືກຕ້ອງ',
        'o2ToHstUid':'O2 ເຊື່ອຕໍ່ທີ່ຢູ່ເຂົ້າກັບບຸກຄົນ',
        "onlineConfigNotEmpty": "Hostel ບໍລິການທີ່ຢູ່、interface Key、interface Secretບໍ່ສາມາດເວັ້ນວ່າງໄດ້",

        "employee": "ລະຫັດພະນັກງານ(employee)",
        "unique": "ລະຫັດທີ່ບໍ່ຊໍ້າ(unique)",
        "distinguishedName": "ຊື່ເຕັມ(distinguishedName)",
        "mobile": "ເບີໂທລະສັບ(mobile)",
        "mail": "(mail)",
        "weixin": "Wechat ID(qq)",
        "qq": "QQID(qq)",

        "apiAddress":"ປະຊຸມອິນເຕີເນັດapiສະຖານທີ່",
        "key":"key",
        "secret":"secret"
},
"nextActivity": "ງານຕໍ່ໄປ：",
    "nextUser": "ຜູ້ດຳເນີນການ：",
    "deal": "ດຳເນີນການ",
    "processStarted": "ເລີ່ມເອກະສານແລ້ວ",
    "processStartedMessage": "ເຈົ້າເລີ່ມວຽກໃໝ່：",
    "needSignInPerson" : "ພະນັກງານເຂົ້າສູ່ລະບົບ",
    "printQrcode": "ພິມ QR Code ເພື່ອເຂົ້າລະບົບ ",
    "weeklyViewTitle" : "{month}，ທີ່{week}ອາທິດ",
    "onlineConfigNotJson": "ການກຳນົດຄ່າກອງປະຊຸມອອນລາຍບໍ່ຖືກຕາມຮູບແບບຂອງ JSON"
};