MWF.xApplication.Meeting.LP = {
	"title": "会议管理",

    "metting" : "会议",
    "subject": "会议标题",
    "applyPerson": "申请人",
    "myMeeting": "我的会议",
    "month": "月",
    "day": "日",
    "room": "会议室",
    "list": "会议列表",
    "today": "今天",
    "tomorrow": "明天",
    "afterTomorrow": "后天",
    "yesterday": "昨天",
    "beforeYesterday": "前天",
    "nextMonth": "下月",
    "floor": "层",
    "enable": "可用",
    "disable": "停用",
    "cancel": "取消",
    "close": "关闭",
    "save": "保存",
    "newBuilding": "新位置",
    "editBuilding": "编辑位置",
    //"inputAddress": "输入地址",
    "meetingApply": "{person}的会议申请",
    "myMeetingApply": "我的会议申请",
    "attend": "请准时出席",
    "beginDate": "日期",
    "beginTime": "开始时间",
    "endTime": "结束时间",
    "time": "时间",
    "meetingTime" : "会议时间",
    "selectRoom": "会议室",
    "invitePerson": "邀请参会人员",
    "invitePerson1": "邀请人",
    "invitePerson2": "参会人员",
    "addInvitePerson1": "增加邀请人",
    "addedInvitePerson1": "已增加邀请人",
    "waitAccept": "邀请您参加",
    "waitConfirm": "需要您审批",
    "isAccept": "请您准时出席会议",
    "timeRangeHour": "{n}小时",
    "timeRangeMinute": "{h}小时{m}分",
    "accepted": "已接受会议邀请",
    "rejected": "已拒绝会议邀请",
    "accept": "接受会议邀请",
    "reject": "拒绝会议邀请",
    "disagree": "驳回",
    "agree": "同意",
    "countMeetings": "场会议",
    "noMeetingWeek": "一周内无会议",
    "newlyMeeting": "{time}：{name}，地点：{room}",
    "am" : "上午",
    "pm" : "下午",
    "monthSelectTextPrev" : "显示将来",
    "monthSelectTextAfter" : "个月的会议",
    "meetingNotice" : "会议提醒",
    "noComingMeeting" : "您在接下来的{month}个月内无会议邀请",
    "roomViewHelp" : "您可以选择时间和持续时长查询空闲会议室。<br/>不可用的会议室会灰显，造成冲突的会议标记为红色。",

    "delete" : "删除",

    "reject_confirm_title": "拒绝会议确认",
    "reject_confirm": "您确定拒绝参加“{name}”会议吗?",

    "cancel_confirm_title": "取消会议确认",
    "cancel_confirm": "您选择了取消召开“{name}”会议，此会议申请将被删除，您确定要执行吗?",

    "accept_confirm_title": "接受会议确认",
    "accept_confirm": "您确定要参加“{name}”会议吗?",

    "disagree_confirm_title": "驳回会议申请确认",
    "disagree_confirm": "您确定要驳回“{name}”会议申请吗?",

    "agree_confirm_title": "同意会议申请确认",
    "agree_confirm": "您确定同意“{name}”会议申请吗?",

    "cancelMeeting" : "取消会议",
    "applyMeeting": "申请会议",
    "addMeeting": "新建会议",
    "editMeeting" : "编辑会议",
    "addRoom": "新建会议室",
    "editRoom": "编辑会议室",
    "refresh": "刷新",
    "setting": "设置",
    "phone": "手机",
    "mail": "邮箱",
    "meetingSubject": "会议标题",
    "meetingDescription": "会议描述",
    "meetingAttachment": "会议材料",
    "meetingDetail" : "会议详情",
    "editAddress" : "编辑地址",
    "removeBuilding" : "删除位置",
    "address" : "地址",
    "name" : "名称",
    "meetingTopInfor" : "{userName}，您好！<br/>今日您需要参加<span style='color: #FB4747'>{count}</span>场会议：",
    "noMeetingTopInfor" : "{userName}，您好！今日您暂无会议。",
    "roomDisable" : "会议室已停用",
    "noPermission" : "会议详情不可见",

    "config_saveSuccess": "配置保存成功！",

    "cancel_createMeeting_title": "取消会议申请确认",
    "cancel_createMeeting": "即将取消会议申请，您填写的数据会丢失，您确定要取消当前会议申请吗？",

    "meeting_input_error": "请正确填写以下内容：<br/>",
    //"meeting_input_subject_error": "请填写完整会议标题！",
    //"meeting_input_room_error": "请选择会议室！",
    //"meeting_input_person_error": "请选择邀请参会人员！",
    //"meeting_input_date_error": "请正确选择会议开始日期和时间！",
    //"meeting_input_time_error": "请正确选择会议开始时间和结束时间！",

    "meeting_input_subject_error": "会议标题不能为空！",
    "meeting_input_room_error": "会议室不能为空！",
    "meeting_input_person_error": "邀请参会人员不能为空！",
    "meeting_input_date_error": "会议开始时间不能早于现在！",
    "meeting_input_time_error": "会议结束时间不能早于开始时间！",


    //"meeting_input_subject_error": "请填写完整会议标题！",
    "meeting_saveSuccess": "会议申请保存成功！",

    "deleteAttachmentTitle":"删除附件确认",
    "deleteAttachment": "是否确定要删除您选中的附件？",

    "startMeetingImmediately" : "开始会议",
    "endMeetingImmediately" : "结束会议",
    "startMeetingSucccess" : "会议已开始",
    "endMeetingSucccess" : "会议已结束",

    "dateFormatMonth": "%Y年%m月",
    "dateFormatMonthDay": "%m月%d日",
    "dateFormatMonthOnly": "%m月",
    "dateFormatDay": "%Y年%m月%d日",
    "dateFormatDayOnly": "%d日",
    "dateFormatAll": "%Y年%m月%d日 %H:%M",
    "dateFormat": "db",
    "person": "人",
    "persist": "持续",
    "hour": "小时",
    "minute" : "分钟",
    "to" : "至",
    "all" : "全部",

    "myWaitConfirm": "审核",
    "myWaitAccept": "邀请",

    "noTask": "今日无会议邀请",
    "noMeeting": "当日无会议",
    "noAddress" : "未填写地址",

    "week" : "周",
    "weeks": {
        "Sun": "周日",
        "Mon": "周一",
        "Tues": "周二",
        "Wed": "周三",
        "Thur": "周四",
        "Fri": "周五",
        "Sat": "周六",
        "arr": ["周日","周一","周二","周三","周四","周五","周六"]
    },

    "device": {
        "projector": "投影仪",
        "board": "白板",
        "tvset": "电视",
        "tv": "视频会议",
        "camera": "摄像头",
        "wifi": "网络",
        "phone": "电话会议"
    },
    "inputAddress": "添加地址",
    "save_success": "保存成功！",
    "delete_building_title": "删除确认",
    "delete_building_hasRoom" : "“{name}”下还有会议室，不能删除。",
    "delete_building": "您确定要删除“{name}”吗",
    "delete_room": "您确定要删除会议室“{name}”吗",

    "roomForm": {
        "name": "会议室名称",
        "building": "会议室位置",
        "floor": "会议室楼层",
        "device": "会议室设备",
        "photo": "照片",
        "capacity": "容纳人数",
        "auditor": "会议室审核人",
        "available": "会议室状态",
        "roomNumber": "会议室门牌",
        "phone": "分机号",

        "verification": {
            "inputName": "请输入会议室名称",
            "inputBuilding": "请输入或选择会议室位置",
            "inputCapacity": "请输入会议室可容纳人数"

        },
        "save_success": "会议室保存成功！"
    },
    "listNavi": {
        "myApply": "我的会议申请",
        "myMeeting" :"我收到的邀请",
        "wait": "未开始",
        "processing": "进行中",
        "completed": "已结束",
        "reject": "已拒绝",
        "room": "会议室"
    },
    "config": {
        "navi": "导航",
        "autoHide": "自动隐藏",
        "default": "默认视图",
        "applyProcess": "会议申请流程",
        "legend": "图示",
        "meetingStatus" : "会议状态",
        "wait": "已预约",
        "progress": "会议中",
        "completed": "已结束",
        "invite": "会议邀请",
        "conflict": "会议室冲突",
        "weekBegin" : "一周开始日",
        "meetingViewer" : "会议详情可见范围",
        "meetingViewerTitle" : "如果可见范围为空，则只有发起人、被邀请人和会议管理员可以看到相应的会议详情。",
        "viewSetting" : "启用视图",
        "viewCustomName" : "视图显示名称",
        "mobileCreateEnable" : "移动端是否能新建会议",
        "mobileCreateEnableOptions" : ["是","否"]
    },
    "nextActivity": "下一个活动：",
    "nextUser": "处理人：",
    "deal": "处理",
    "processStarted": "文件已启动",
    "processStartedMessage": "您启动了一个新的工作：",
    "needSignInPerson" : "签到人员",
    "printQrcode": "打印签到二维码",
    "weeklyViewTitle" : "{month}，第{week}周"
};