MWF.xApplication.Meeting.LP = {
	"title": "會議管理",

    "metting" : "會議",
    "subject": "會議主題",
    "applyPerson": "申請人",
    "myMeeting": "我的會議",
    "month": "月",
    "day": "日",
    "room": "會議室",
    "list": "會議列表",
    "today": "今天",
    "tomorrow": "明天",
    "afterTomorrow": "後天",
    "yesterday": "昨天",
    "beforeYesterday": "前天",
    "nextMonth": "下個月",
    "floor": "樓",
    "enable": "可用",
    "disable": "停用",
    "cancel": "取消",
    "close": "關閉",
    "save": "儲存",
    "newBuilding": "新位置",
    "editBuilding": "編輯位置",
    //"inputAddress": "輸入地址",
    "meetingApply": "{person}的會議申請",
    "myMeetingApply": "我的會議申請",
    "attend": "請準時出席",
    "beginDate": "日期",
    "beginTime": "開始時間",
    "endTime": "結束時間",
    "time": "時間",
    "meetingTime" : "會議時間",
    "selectRoom": "會議室選擇",
    "invitePerson": "邀請參加人員",
    "invitePerson1": "邀請人",
    "invitePerson2": "參加人",
    "addInvitePerson1": "新增邀請人",
    "addedInvitePerson1": "已新增邀請人",

    "deleteInvitePerson": "已取消邀請人",
    "deleteInvitePerson1": "取消邀請人",
    "deleteInvitePerson2": "已取消",
    "userDeleteInvitePerson": "您的會議邀請已被取消",

    "acceptPerson": "已接受",
    "rejectPerson": "已拒絕",

    "waitAccept": "等待接受邀請",
    "waitConfirm": "需要您批准",
    "isAccept": "請您準時參加會議",
    "timeRangeHour": "{n}小時",
    "timeRangeMinute": "{h}小時{m}分",
    "accepted": "已接受會議邀請",
    "rejected": "已拒絕會議邀請",
    "accept": "接受會議邀請",
    "reject": "拒絕會議邀請",
    "disagree": "不同意",
    "agree": "同意",
    "countMeetings": "場會議",
    "noMeetingWeek": "一周內無會議",
    "newlyMeeting": "{time}：{name}，地點：{room}",
    "am" : "上午",
    "pm" : "下午",
    "monthSelectTextPrev" : "顯示未來",
    "monthSelectTextAfter" : "個月的會議",
    "meetingNotice" : "會議提醒",
    "noComingMeeting" : "您在接下來的{month}個月內無會議邀請",
    "roomViewHelp" : "您可以選擇時間和持續時間查詢空閒會議室。<br/>不可用的會議室會變灰，造成衝突的會議會標記為紅色。",

    "delete": "刪除",

    "reject_confirm_title": "拒絕會議確認",
    "reject_confirm": "您確定拒絕參加“{name}”會議嗎?",

    "cancel_confirm_title": "取消會議確認",
    "cancel_confirm": "您選擇了取消召開“{name}”會議，此會議申請將被刪除，您確定要執行嗎?",

    "accept_confirm_title": "接受會議確認",
    "accept_confirm": "您確定要參加“{name}”會議嗎?",

    "disagree_confirm_title": "拒絕會議申請確認",
    "disagree_confirm": "您確定要拒絕“{name}”會議申請嗎?",

    "agree_confirm_title": "同意會議申請確認",
    "agree_confirm": "您確定同意“{name}”會議申請嗎?",

    "cancelMeeting" : "取消會議",
    "applyMeeting": "申請會議",
    "addMeeting": "新增會議",
    "editMeeting" : "編輯會議",
    "addRoom": "新增會議室",
    "editRoom": "編輯會議室",
    "refresh": "刷新",
    "setting": "設置",
    "phone": "手機",
    "mail": "郵箱",
    "meetingSubject": "會議標題",
    "meetingDescription": "會議描述",
    "meetingAttachment": "會議附件",
    "meetingDetail" : "會議詳情",
    "editAddress" : "編輯地址",
    "removeBuilding" : "刪除位置",
    "address" : "地址",
    "name" : "名稱",
    "meetingTopInfor" : "{userName}您好！今天您需要參加<span style='color: #FB4747'>{count}</span>場會議：",
    "noMeetingTopInfor" : "{userName}您好！今天您暫無會議。",
    "roomDisable" : "會議室已停用",
    "noPermission" : "會議詳情不可見",

    "config_saveSuccess": "配置保存成功！",

    "cancel_createMeeting_title": "取消會議申請確認",
    "cancel_createMeeting": "即將取消會議申請，您填寫的數據將丟失，您確定要取消當前會議申請嗎？",

    "meeting_input_error": "請正確填寫以下內容：<br/>",
    //"meeting_input_subject_error": "请填写完整会议标题！",
    //"meeting_input_room_error": "请选择会议室！",
    //"meeting_input_person_error": "请选择邀请参会人员！",
    //"meeting_input_date_error": "请正确选择会议开始日期和时间！",
    //"meeting_input_time_error": "请正确选择会议开始时间和结束时间！",

    "meeting_input_subject_error": "會議標題不能為空！",
    "meeting_input_room_error": "會議室不能為空！",
    "meeting_input_url_number_error": "會議鏈接和會議號不能同時為空！",
    "meeting_input_person_error": "請邀請參會人員！",
    "meeting_input_date_error": "會議開始時間不能早於當前時間！",
    "meeting_input_time_error": "會議結束時間不能早於開始時間！",


    //"meeting_input_subject_error": "请填写完整会议标题！",
    "meeting_saveSuccess": "會議申請保存成功！",

    "deleteAttachmentTitle":"刪除附件確認",
    "deleteAttachment": "是否確定要刪除您選中的附件？",

    "startMeetingImmediately" : "立即開始會議",
    "endMeetingImmediately" : "立即結束會議",
    "startMeetingSucccess" : "會議已開始",
    "endMeetingSucccess" : "會議已結束",

    "dateFormatMonth": "%Y年%m月",
    "dateFormatMonthDay": "%m月%d日",
    "dateFormatMonthOnly": "%m月",
    "dateFormatDay": "%Y年%m月%d日",
    "dateFormatDayOnly": "%d日",
    "dateFormatAll": "%Y年%m月%d日 %H:%M",
    "dateFormat": "db",
    "person": "人",
    "persist": "持續",
    "hour": "小時",
    "minute" : "分鐘",
    "to" : "至",
    "all" : "全部",

    "myWaitConfirm": "審核",
    "myWaitAccept": "邀請",

    "noTask": "今日無會議邀請",
    "noMeeting": "當日無會議",
    "noAddress" : "未填寫地址",

    "hostPerson": "主持人",
    "hostUnit": "主辦部門",
    "meetingType": "會議類型",
    "meetingMode": "會議方式",
    "meetingModeSelectText": ["線下會議", "線上會議"],
    "meetingModeSelectValue": ["offline", "online"],
    "meetingUrl": "會議連結",
    "openMeetingUrl": "打開會議連結",
    "meetingNumber": "會議號碼",
    "netMeetingAbb": "網",
    "yes": "是",
    "no": "否",
    "other": "其他",
    "createOnSave": "儲存後自動生成",
    "copy": "複製",
    "noRoomBuilding": "網絡會議\n(無會議室)",

    "week": "週",
    "weeks": {
        "Sun": "星期日",
        "Mon": "星期一",
        "Tues": "星期二",
        "Wed": "星期三",
        "Thur": "星期四",
        "Fri": "星期五",
        "Sat": "星期六",
        "arr": ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"]
    },

    "device": {
        "projector": "投影機",
        "board": "白板",
        "tvset": "電視",
        "tv": "視訊會議",
        "camera": "攝影機",
        "wifi": "網絡",
        "phone": "電話會議"
    },
    "inputAddress": "添加地址",
    "save_success": "保存成功！",
    "delete_building_title": "刪除確認",
    "delete_building_hasRoom": "“{name}”下還有會議室，不能刪除。",
    "delete_building": "您確定要刪除“{name}”嗎",
    "delete_room": "您確定要刪除會議室“{name}”嗎",

    "roomForm": {
        "name": "會議室名稱",
        "building": "會議室位置",
        "floor": "會議室樓層",
        "device": "會議室設備",
        "photo": "照片",
        "capacity": "容納人數",
        "auditor": "會議室審核人",
        "available": "會議室狀態",
        "roomNumber": "會議室門牌",
        "phone": "分機號",

        "verification": {
            "inputName": "請輸入會議室名稱",
            "inputBuilding": "請輸入或選擇會議室位置",
            "inputCapacity": "請輸入會議室可容納人數"
        },
        "save_success": "會議室保存成功！"
    },
    "listNavi": {
        "myApply": "我的會議申請",
        "myMeeting": "我收到的邀請",
        "wait": "未開始",
        "processing": "進行中",
        "completed": "已結束",
        "reject": "已拒絕",
        "room": "會議室"
    },
    "config": {
        "navi": "導航",
        "autoHide": "自動隱藏",
        "default": "默認視圖",
        "applyProcess": "會議申請流程",
        "legend": "圖例",
        "meetingStatus": "會議狀態",
        "wait": "已預約",
        "progress": "進行中",
        "completed": "已結束",
        "invite": "會議邀請",
        "conflict": "會議室衝突",
        "weekBegin": "一周開始日",
        "meetingViewer": "會議詳細信息可見範圍",
        "meetingViewerTitle": "如果可見範圍為空，只有發起人、被邀請人和會議管理員可以看到相應的會議詳細信息。",
        "viewSetting": "啟用視圖",
        "viewCustomName": "視圖顯示名稱",
        "mobileCreateEnable": "移動端是否能新建會議",
        "mobileCreateEnableOptions": ["是", "否"],
        "meetingType": "會議類型（每行一種）",
        "enableOnline": "啟用線上會議",
        "onlineProduct": "線上會議產品",
        "onlineConfig": "線上會議配置",
        'hstUrl': '好視通服務地址',
        'hstKey': '好視通服務接口Key',
        'hstSecret': '好視通服務接口Secret',
        'hstAuth': '好視通會議驗證登錄',
        'o2ToHstUid': 'O2與好視通映射人員字段',
        "onlineConfigNotEmpty": "好視通服務地址、接口Key、接口Secret不能為空",
        "employee": "人員工號(employee)",
        "unique": "唯一編碼(unique)",
        "distinguishedName": "全名(distinguishedName)",
        "mobile": "手機電話(mobile)",
        "mail": "電子郵件(mail)",
        "weixin": "微信號(qq)",
        "qq": "QQ號碼(qq)",
        "apiAddress": "線上會議API地址",
        "key": "金鑰(key)",
        "secret": "秘密(secret)"
    },
    "nextActivity": "下一個活動:",
    "nextUser": "處理人:",
    "deal": "處理",
    "processStarted": "文件已啟動",
    "processStartedMessage": "您啟動了新工作:",
    "needSignInPerson": "簽到人員",
    "printQrcode": "列印簽到二維碼",
    "weeklyViewTitle": "{month}，第{week}週",
    "onlineConfigNotJson": "線上會議配置未設置為正確的 JSON 格式"
};