/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.crm.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.crm.core.entity.CrmRegion.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Tue May 09 17:17:31 CST 2017")
public class CrmRegion_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<CrmRegion,String> citycode;
    public static volatile SingularAttribute<CrmRegion,String> cityid;
    public static volatile SingularAttribute<CrmRegion,String> cityname;
    public static volatile SingularAttribute<CrmRegion,String> citypinyin;
    public static volatile SingularAttribute<CrmRegion,Date> createTime;
    public static volatile SingularAttribute<CrmRegion,String> id;
    public static volatile SingularAttribute<CrmRegion,String> lat;
    public static volatile SingularAttribute<CrmRegion,String> leveltype;
    public static volatile SingularAttribute<CrmRegion,String> lng;
    public static volatile SingularAttribute<CrmRegion,String> mergername;
    public static volatile SingularAttribute<CrmRegion,String> parentid;
    public static volatile SingularAttribute<CrmRegion,String> sequence;
    public static volatile SingularAttribute<CrmRegion,String> shortname;
    public static volatile SingularAttribute<CrmRegion,Date> updateTime;
    public static volatile SingularAttribute<CrmRegion,String> zipcode;
}
