MWF.xApplication.StandingBook.LP = {
	"title": "StandingBook",
	"searchCondition": "search condition ",

	"searchInfor": "correlation result {count} bar, time {time} seconds ",

	"location": "Your location :",

	"cms": "Content Management",
	"processPlatform": "Process Management ",
	"processManager": "Process Management ",
	"cmsManager": "Content Management",
	"noData": "No data was queried according to the conditions ",
	"noSearchkey": "Please enter keyword search ",
	"noSearchkeyAndCondition": "Please enter keyword or click filter condition search ",
	"searchPlacholder": "Please enter the keyword, press Enter to search ",
	"docTotalInfor": "<span class='mainColor_color'>{count}</span> bar, {time} seconds ",

	"mainPage": "home page ",
	"search": "search",
	"index":  "Advanced search",
	"ftsearch": "full-text search",

	"summary": "summary",
	"docTitle": "title ",
	"createTime": "create time ",
	"completedTime": "end time ",
	"activityName": "node ",
	"creatorUnit": "department ",
	"creatorIdentity": "creator ",

	"publishTime": "PublishTime ",

	"processList": "process ",
	"creatorUnitList": "Create organization ",
	"startTimeMonthList": "Create month ",
	"completedTimeMonthList": "Completion month ",
	"activityNameList": "Active ",
	"workStatusList": "Process status ",
	"updateTime": "Update time ",

	"application": "Process application",
	"process": "process",
	"appInfo": "Content Management",
	"categoryInfo": "category ",
	"general": "general",
	"reveal": "Common Account ",

	"column":" column",
	"category": "category",
	"unit": "organization ",
	"app": "App ",
	"createTimeMonth": "Create month ",
	"updateTimeMonth": "Update month ",
	"creatorPerson": "creator ",
	"workCompleted": "Workcompleted ",
	"work": "work on the move ",
	"document": "Content management document",
	"applicationName": "Process Application ",
	"processName": "Process application ",
	"appName": "Content Management Column",
	"categoryName": "Content Management Classification ",
	"selectConditionNote": "Please select ",
	"fieldSelect": "Column selection ",
	"filter": "filter",
	"sequence": "sequence number ",

	"more": "More ",
	"collapse": "collapse",
	"multiSelect": "multiselect ",
	"enableMultiSelect": "Allow multiple selections ",
	"disableMultiSelect": "disables multiple selection",
	"ok": "OK ",
	"cancel": "cancel",
	"reset": "reset",
	"export": "export",
	"moreFilter": "more filters ",
	"collapseFilter": "collapsefilter ",

	"notSelectNotice": "Please select at least one application ",

	"completed": "Completed ",
	"true": "Yes ",
	"false": "No ",
	"rangeSeparator": "to ",
	"startPlaceholder": "start time ",
	"endPlaceholder": "end time ",
	"to": "to",
	"min": "minimum ",
	"max": "maximum value ",
	"fromValue": "starting value ",
	"toValue": "end value ",
	"minGreatThanMaxError": "The start value cannot be greater than the end value ",
	"tooMinError": "cannot be less than the minimum value ",
	"tooMaxError": "cannot be greater than the maximum value ",
	"moreFieldSelect": "More column selections ",
	"collapseFieldSelect": "Collapse column selection ",

	"firstPage": "first page ",
	"lastPage": "last page ",

	"selectModule": "Select application ",
	"searching": "You're searching",
	"switch": "switch",
	"searchAppPlacholder": "Enter the application name and press Enter to search ",
	"menuNoMatchItem": "Match app not found ",

	"setting": "Setting",

	"return": "return",
	"config": "common ledger entry configuration ",

	"delete" : "delete",
	"edit": "edit",
	"createSuccess" :" Created successfully ",
	"updateSuccess" : "Modified successfully ",
	"default" : "default",
	"insertBefore" : "insert ",
	"insertAfter": "insertafter",
	"move" : "Adjust the order ",
	"save" : "save",
	"cancelEdit": "canceledit",
	"deleteConfigTitle": "Delete configuration ",
	"deleteConfigConfirm": "Cannot restore after deleting. Are you sure to continue?" ,
	"isNewing": "New, please save...",

	"commonField": "Common field ",
	"allField": "All fields ",
	"saveSuccess": "saved successfully ",
	"saveNotice": "Save the configuration information first ",

	"inputName":" Please enter a configuration name ",
	"create_cancel_title": "Cancel new confirmation ",
	"create_cancel": "Are you sure you want to cancel the new creation?" ,

	"formTitle": "Ledger entry configuration ",
	"name": "Ledger name",
	"range": "ledger range",
	"processPlatformList": "Process application ",
	"processPlatformListNote": "Click to select, this entry will get the data in the selected process application list and content management list." ,
	"cmsList": "Content Management ",
	"cmsListNote": "Click to select, this entry will get data in the selected process application list and content management list." ,
	"availableList": "Available range ",
	"availableListNote": "Click to select the people, organizations, and groups visible in this entry. Empty is visible to all." ,
	"fieldList": "Ledger field ",
	"fieldListNote": "The ledger fields are listed according to the selected process application and content management. If Filterable is enabled, you can filter this field on the ledger interface. If Default Display is enabled, this field is displayed on the ledger interface by default. If Displayable is enabled, you can select this field on the ledger interface. ",
	"enableSelectText": [" Enable "," disable "],
	"inputNamePlacholder": "Please enter the account name ",
	"appEmptyNotice": "Process application and content management application cannot be empty at the same time ",
	"saveFailure": "Save failure ",
	"fieldListNotEmpty": "Please select at least one ledger field ",
	"noConfigNote": "Please create or select a common ledger entry for configuration ",
	"loadingData": "Querying data",
	"ignorePermission": "Ignore permissions",
	"ignorePermissionNote": "If you ignore permissions, anyone who can see this record can see all data; otherwise, they can only see the process data in which they participate, and have the above permissions to cms document.",
	"yes": "Yes",
	"no": "No",
	"defaultText": {
		"category": "category",
		"createTimeMonth": "Create month ",
		"updateTimeMonth": "Update month ",
		"completed": "Completed ",
		"applicationAlias": "Application alias ",
		"applicationName": "Application name ",
		"application": "Process identification ",
		"taskPersonNames": "current handler ",
		"activityName": "Activity name ",
		"processName": "process name ",
		"process": "process identification ",
		"serial": "Serial",
		"expired": "Expire",
		"attachment": "Attachment",
		"endDate": "End date",
		"title": "Title",
		"appName": "Column name ",
		"appAlias": "column alias ",
		"categoryName": "category name ",
		"creatorPerson": "creator ",
		"creatorUnit": "department ",
		"appId": "Column ID ",
		"modifyTime": "Modify time ",
		"publishTime": "publish Time"
	}

};
