MWF.xApplication.StandingBook.LP = {
	"title": "台账",
	"searchCondition": "查询条件",

    "searchInfor": "相关结果{count}条，耗时{time}秒",

    "location": "您的位置:",

    "cms": "内容管理",
    "processPlatform": "流程管理",
    "processManager": "流程管理",
    "cmsManager": "内容管理",
    "noData": "根据条件未查询到数据",
    "noSearchkey": "请输入关键字搜索",
    "noSearchkeyAndCondition": "请输入关键字或点击过滤条件搜索",
    "searchPlacholder": "请输入关键字，按“回车”搜索",
    "docTotalInfor": "查询到相关结果<span class='mainColor_color'>{count}</span>条，耗时{time}秒",

    "mainPage": "首页",
    "search": "搜索",
    "index": "高级搜索",
    "ftsearch": "全文搜索",

    "summary": "摘要",
    "docTitle": "标题",
    "createTime": "创建时间",
    "completedTime": "结束时间",
    "activityName": "节点",
    "creatorUnit": "部门",
    "creatorIdentity": "创建者",

    "publishTime": "发布时间",

    "processList": "流程",
    "creatorUnitList": "创建组织",
    "startTimeMonthList": "创建月份",
    "completedTimeMonthList": "完成月份",
    "activityNameList": "活动",
    "workStatusList": "流程状态",
    "updateTime": "更新时间",

    "application": "应用名称",
    "process": "流程名称",
    "appInfo": "内容管理",
    "categoryInfo": "类别",
    "general": "通用",
    "reveal": "常用台账",

    "column":"栏目",
    "category": "类别",
    "unit": "组织",
    "app": "应用",
    "createTimeMonth": "创建月份",
    "updateTimeMonth": "更新月份",
    "creatorPerson": "创建者",
    "workCompleted": "已完成工作",
    "work": "流转中工作",
    "document": "内容管理文档",
    "applicationName": "应用名称",
    "processName": "流程",
    "appName": "内容管理栏目",
    "categoryName": "内容管理分类",
    "selectConditionNote": "请选择",
    "fieldSelect": "列选择",
    "filter": "过滤",
    "sequence": "序号",

    "more": "更多",
    "collapse": "收起",
    "multiSelect": "多选",
    "enableMultiSelect": "允许多选",
    "disableMultiSelect": "取消多选",
    "ok": "确定",
    "cancel": "取消",
    "reset": "重置",
    "export": "导出",
    "moreFilter": "更多筛选条件",
    "collapseFilter": "收起筛选条件",

    "notSelectNotice": "请至少选择一个应用",

    "completed": "已完成",
    "true": "是",
    "false": "否",
    "rangeSeparator": "至",
    "startPlaceholder": "开始时间",
    "endPlaceholder": "结束时间",
    "to": "到",
    "min": "最小值",
    "max": "最大值",
    "fromValue": "起始值",
    "toValue": "结束值",
    "minGreatThanMaxError": "起始值不能大于结束值",
    "tooMinError": "不能小于最小值",
    "tooMaxError": "不能大于最大值",
    "moreFieldSelect": "更多列选择",
    "collapseFieldSelect": "收起列选择",

    "firstPage": "第一页",
    "lastPage": "最后一页",

    "selectModule": "选择应用",
    "searching": "您正在查询",
    "switch": "切换",
    "searchAppPlacholder": "输入应用名称回车搜索",
    "menuNoMatchItem": "未查找到匹配应用",

    "setting": "配置",

    "return": "返回",
    "config": "常用台账条目配置",

    "delete" : "删除",
    "edit" : "编辑",
    "createSuccess" :"创建成功",
    "updateSuccess" : "修改成功",
    "default" : "默认",
    "insertBefore" : "插入",
    "insertAfter" : "追加",
    "move" : "调整顺序",
    "save" : "保存",
    "cancelEdit" : "取消",
    "deleteConfigTitle": "删除配置",
    "deleteConfigConfirm": "删除后不能恢复，确定继续？",
    "isNewing": "新建中,请先保存...",

    "commonField": "常用字段",
    "allField": "全部字段",
    "saveSuccess": "保存成功",
    "saveNotice": "请先保存配置信息",

    "inputName":"请输入配置名称",
    "create_cancel_title": "取消新建确认",
    "create_cancel": "您确定要取消新建吗?",

    "formTitle": "台账条目配置",
    "name": "台账名称",
    "range": "台账范围",
    "processPlatformList": "流程应用",
    "processPlatformListNote": "点击可选择，本条目将在选择的流程应用列表和内容管理列表中获取数据。流程应用管理员可以看到相关应用。管理员（Manager角色）可以看到所有流程应用。",
    "cmsList": "内容管理",
    "cmsListNote": "点击可选择，本条目将在选择的流程应用列表和内容管理列表中获取数据。内容管理栏目管理员可以看到相关栏目。管理员（Manager角色）可以看到所有的内容管理栏目。",
    "availableList": "可用范围",
    "availableListNote": "点击可选择，本条目可见的人员、组织和群组。空则所有人可见。",
    "fieldList": "台账字段",
    "fieldListNote": "台账字段根据选择的流程应用及内容管理列出。启用“可过滤”可以在使用界面对该字段进行过滤，启用“默认展现”后使用界面默认列式该字段，启用“可展现”后，用户可以在使用界面选择列式该字段。",
    "enableSelectText": ["启用","禁用"],
    "inputNamePlacholder": "请输入台账名称",
    "appEmptyNotice": "流程应用和内容管理应用不能同时为空",
    "saveFailure": "保存失败",
    "fieldListNotEmpty": "请至少选择一个台账字段",
    "noConfigNote": "请新建或选择一个常用台账条目进行配置",
    "noAppNote": "请至少选择一个应用进行台账",
    "loadingData": "正在查询数据",
    "ignorePermission": "忽略权限",
    "ignorePermissionNote": "如果忽略权限，则能看到该条台账的人都可以看到所有数据；否则只能看到本人参与的流程数据，具有阅读以上权限的内容管理文档。",
    "yes": "是",
    "no": "否",
    "defaultText": {
	    "category": "类别",
        "createTimeMonth": "创建月份",
        "updateTimeMonth": "更新月份",
        "completed": "已完成",
        "applicationAlias": "应用别名",
        "applicationName": "应用名称",
        "application": "流程标识",
        "taskPersonNames": "当前处理人",
        "activityName": "活动名称",
        "processName": "流程名称",
        "process": "流程标识",
        "serial": "文号",
        "expired": "是否过期",
        "attachment": "附件",
        "endDate": "结束日期",
        "title": "标题",
        "appName": "栏目名称",
        "appAlias": "栏目别名",
        "categoryName": "分类名称",
        "creatorPerson": "创建者",
        "creatorUnit": "部门",
        "appId": "栏目标识",
        "modifyTime": "修改时间",
        "publishTime": "发布时间",
        "processPlatform_string_applicationName": "应用名称",
        "processPlatform_string_processName": "流程名称",
        "processPlatform_boolean_completed": "已完成",
        "cms_string_appName": "栏目名称",
        "cms_string_categoryName": "分类名称"
    }

};
