MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.portal = MWF.xApplication.portal || {};
MWF.xApplication.portal.WidgetDesigner = MWF.xApplication.portal.WidgetDesigner || {};
MWF.xApplication.portal.WidgetDesigner.LP={
	"title": "Editor de Widgets",
	"newPage": "Crear nuevo Widget",
	"property": "Propiedades",
	"tools": "Herramientas",
	"repetitionsId": "Identificador repetido del elemento",
	"notNullId": "El identificador del elemento no puede estar vacío",
	"button": {
		"ok": "Aceptar",
		"cancel": "Cancelar"
	},
	"notice": {
		"save_success": "¡El formulario se ha guardado con éxito!",
		"saveTemplate_success": "¡Se ha guardado el modelo de formulario con éxito!",
		"saveTemplate_inputName": "Ingrese el título del modelo",
		"saveTemplate_inputCategory": "Seleccione la categoría del modelo",
		"deleteElementTitle": "Confirmación",
		"deleteElement": "¿Está seguro de que desea eliminar el elemento actual y sus subelementos?",
		"deleteRowTitle": "Confirmación",
		"deleteRow": "La eliminación de la fila actual eliminará el contenido de todas las celdas en esa fila. ¿Está seguro de que desea eliminar la fila seleccionada?",
		"deleteColTitle": "Confirmación",
		"deleteCol": "La eliminación de la columna actual eliminará el contenido de todas las celdas en esa columna. ¿Está seguro de que desea eliminar la columna seleccionada?",
		"deleteEventTitle": "Confirmación",
		"deleteEvent": "¿Está seguro de que desea eliminar el evento actual?",
		"deleteActionTitle": "Confirmación",
		"deleteAction": "¿Está seguro de que desea eliminar la acción actual?",
		"deleteButtonTitle": "Confirmación",
		"deleteButton": "¿Está seguro de que desea eliminar el botón de acción actual?",
		"notUseModuleInMobile": "Este componente no es compatible con dispositivos móviles",
		"changeToSequenceTitle": "Confirmación",
		"changeToSequence": "Esta acción eliminará los componentes agregados. ¿Está seguro de que desea cambiar a la columna 'N° de Orden'?"
	},
	"formAction": {
		"insertRow": "Insertar fila",
		"insertCol": "Insertar columna",
		"deleteRow": "Eliminar fila",
		"deleteCol": "Eliminar columna",
		"mergerCell": "Combinar celdas",
		"splitCell": "Dividir celda",
		"move": "Mover",
		"copy": "Copiar",
		"delete": "Eliminar",
		"add": "Agregar",
		"script": "Script"
	},
	"actionbar": {
		"readhide": "Establecer si se muestra al leer",
		"edithide": "Establecer si se muestra al editar",
		"hideCondition": "Establecer condición de ocultación",
		"title": "Título",
		"img": "Icono",
		"action": "Acción",
		"condition": "Condición de visualización",
		"editScript": "Editar script de acción",
		"editCondition": "(retornar verdadero para ocultar acción)"
	},
	"isSave": "Guardando, por favor espere...",
	"validation": {
		"validation": "Validación",
		"anytime": "siempre",
		"decision": "Decisión",
		"decisionName": "<Nombre de decisión>",
		"value": "Valor",
		"length": "Longitud de valor",
		"valueInput": "<Valor>",
		"isnull": "Es nulo",
		"notnull": "No es nulo",
		"gt": "Mayor que",
		"lt": "Menor que",
		"equal": "Igual a",
		"neq": "No igual a",
		"contain": "Contiene",
		"notcontain": "No contiene",
		"prompt": "Indicación",
		"add": "añadir",
		"modify": "edit",
		"when": "Cuando",
		"as": "como",
		"inputDecisionName": "Ingrese el nombre de la decisión",
		"inputValue": "Ingrese el valor",
		"inputPrompt": "Ingrese el contenido de la indicación",
		"delete_title": "Confirmación",
		"delete_text": "¿Está seguro de que desea eliminar esta validación?"
	},
	"selectIcon": "Seleccionar icono",
	"selectImage": "Seleccionar imagen",
	"dutyInputTitle": "Agregar parámetros de puesto",
	"dutyInput": "Por favor, seleccione una organización para el puesto \"{duty}\"",
	"creatorCompany": "Empresa del autor",
	"creatorDepartment": "Departamento del autor",
	"currentCompany": "Empresa actual",
	"currentDepartment": "Departamento actual",
	"deleteDutyTitle": "Confirmación",
	"deleteDutyText": "¿Estás seguro de que deseas eliminar el puesto \"{duty}\"?",
	"saveTemplate": "Guardar como plantilla de formulario",
	"templateName": "Nombre de la plantilla",
	"templateCategory": "Categoría de la plantilla",
	"templateDescription": "Descripción de la plantilla",
	"save": "Guardar",
	"cancel": "Cancelar",
	"newCategory": "Nueva categoría",
	"selectorButton": {
		"ok": "Aceptar",
		"cancel": "Cancelar"
	}
}
MWF.xApplication.portal.WidgetDesigner["lp."+o2.language] = MWF.xApplication.portal.WidgetDesigner.LP