MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.ProcessDesigner = MWF.xApplication.process.ProcessDesigner || {};
MWF.xApplication.process.ProcessDesigner.LP={
	"title": "ProcessEditor",
	"newProcess": "Create Process",
	"tools": "Tools",
	"unnamed": "Unnamed",
	"unknow": "Unknow",
	"unrealized": "This feature is not implemented",
	"activity": "Activity",
	"route": "Route",
	"property": "Property",
	"showJson": "Show JSON",
	"all": "All",
	"showAdvanced": "Advanced properties",
	"phone": "Phone",
	"mail": "Mail",
	"selectScript": "Select script: ",
	"condition": "Condition",
	"unCategory": "Uncategorized",
	"ok": "OK",
	"close": "Close",
	"cancel": "Cancel",
	"notice": {
		"no_name": "enter the process name",
		"save_success": "Process was saved successfully!",
		"save_process": "Please save the process first!",
		"one_begin": "Only one \"begin\" Activity is allowed per process",
		"deleteRoute": "Are you sure you want to delete the selected route?",
		"deleteRouteTitle": "Delete Route Confirmation",
		"deleteActivityTitle": "Delete Activity Confirmation",
		"deleteActivity": "Deleting an activity will also delete all routes associated with this activity. Are you sure you want to delete the selected activity?",
		"saveRouteOrgNoName": "Name and title cannot be empty",
		"saveRouteOrgNumberId": "Identifier cannot be a pure number",
		"saveRouteOrgDoubleDotId": "The ID cannot contain two consecutive dots",
		"processCopyError": "Activity paste failed, please copy again and try again",
		"routeNameConfilct": "An activity cannot have two routes with the same name!"
	},
	"menu": {
		"newRoute": "Create Route",
		"newActivity": "Create Activity",
		"newActivityType": {
			"manual": "Manual",
			"condition": "Condition",
			"auto": "Auto",
			"split": "Split",
			"merge": "Merge",
			"embed": "Embed",
			"invoke": "Invoke",
			"service": "Service",
			"agent": "Agent",
			"delay": "Delay",
			"publish": "Publish",
			"message": "Message",
			"choice": "Choice",
			"cancel": "Cancel",
			"begin": "Begin",
			"end": "End",
			"parallel": "Parallel"
		},
		"copyActivity": "Copy activity",
		"deleteActivity": "Delete activity",
		"deleteRoute": "Delete route",
		"saveProcess": "Save Process",
		"saveProcessNew": "Save as a new version",
		"checkProcess": "Check Process",
		"exportProcess": "Export Process",
		"printProcess": "Print Process",
		"showGrid": "Show Grid",
		"hideGrid": "Hide Grid"
	},
	"intoScript": "Click here to write script code",
	"serialSelectTitle": "Number optional attribute",
	"serialActivityTitle": "Execute Numbering Activity",
	"delete": "Delete",
	"serialRule": "Numbering Rules",
	"serialTextTitle": "Enter text",
	"serialDateTitle": "Time",
	"serialCreatedDateTitle": "Drafting Date",
	"serialCurrentDateTitle": "Numbering Time",
	"serialCreated": "Draft Draft",
	"serialCurrent": "Number",
	"serialAttributeTitle": "Enter the attribute name",
	"serialScriptTitle": "Please enter the script",
	"serialNumberLongTitle": "Serial Number Length",
	"serialNumberByTitle": "Serial Number ByTitle",
	"isSave": "Saving, please wait...",
	"dutyInputTitle": "Add Duty parameter",
	"dutyInput": "Please add parameters for the duty \"{duty}\"",
	"creatorCompany": "Drafting Company",
	"creatorDepartment": "Drafting Department",
	"currentCompany": "Current Company",
	"currentDepartment": "Current Department",
	"deleteDutyTitle": "Remove duty confirmation",
	"deleteDutyText": "Are you sure you want to remove the duty \"{duty}\"?",
	"selectIcon": "Select Icon",
	"centerServer": "Center Serve",
	"creatorUnit": "The Unit of the author",
	"currentUnit": "The Unit of the processor",
	"selectUnit": "Select Unit",
	"scriptUnit": "script",
	"preview": "Preview",
	"copy": "Copy from other",
	"selectType": "Select Type",
	"identity": "Identity",
	"unit": "Unit",
	"selectCount": "Select Count",
	"deleteOrgConfirmTitle": "Delete selection confirmation",
	"deleteOrgConfirmContent": "Are you sure you want to delete the selected configuration?",
	"projectionTitle": "Mapping business data",
	"projectionActionNode_add": "Add mapping entry",
	"projectionActionNode_modify": "Modify the mapping entry",
	"projectionDataName": "DataName",
	"projectionPath": "Path",
	"projectionType": "Type",
	"projectionName": "Name",
	"projectionInputError": "Please enter the data name and data path",
	"projectionTypeCountError": "{type} type data mapping entries, up to {count} allowed.",
	"projectionSameNameError": "Same data name already exists",
	"projectionDeleteItemTitle": "Delete mapping confirmation",
	"projectionDeleteItem": "Are you sure you want to delete the data mapping entry named \"{name}\" and path \"{path}\"?",
	"projectionRunActionNode": "Run data mapping immediately",
	"projectionRunTitle": "Execute confirmation immediately",
	"projectionRunText": "Execute mapping confirmation",
	"projectionRunSuccess": "Data mapping has been executed",
	"projectionRunError": "No need to perform data mapping",
	"enable": "Enabled",
	"notEnable": "Not enabled",
	"currentEdition": "Current Edition",
	"editionUpdate": "Last Modified",
	"editionDiscription": "Enter the version description",
	"upgradeConfirm": "Save new version confirmation",
	"upgradeInfor": "<div style='overflow: hidden; line-height: 26px'>Are you sure you want to save the current process as a new version?<br/>Select \"Enable the new version\" after saving is complete, The new version will be set as the enabled version.</div><div style='margin-top:10px'><input type='checkbox' checked>Enable the new version</div>",
	"inputDiscription": "Please enter the version description first",
	"edition_list": {
		"editionList": "View process version",
		"number": "Version number",
		"update": "Update time",
		"updatePerson": "Update Person",
		"description": "Description",
		"enabled": "Enabled",
		"action": "Action",
		"yes": "Yes",
		"no": "No",
		"newProcess": "A new process is created.",
		"an": "individual",
		"modifyProcess": "[Process] modified the attributes <b>\"{field}\"</b>, from: <span style='color: #ff0000'>\"{old}\"</b> span>, to: <span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity": "[Activity] modified the <b>\"{name}\"</b> activity attribute <b>\"{field}\"</b> from: <span style='color: #ff0000'>\"{old}\"</span>, to: <span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity_addRoute": "[Routing] Added <b>\"{name}\"</b> activity routing <b>\"{rname}\"</b>, pointing to <span style='color: #0000ff'> \"{Next}\"</span>",
		"modifyActivity_deleteRoute": "[Route] deleted the route of <b>\"{name}\"</b> activity <b>\"{rname}\"</b>, pointing to <span style='color: #ff0000'> \"{Next}\"</span>",
		"modifyActivity_modifyRouteNext": "[Route] modified the route of <b>\"{name}\"</b> activity <b>\"{rname}\"</b>, from pointing to <span style='color: #ff0000' >\"{oldnext}\"</span>, modified to point to <span style='color: #0000ff'>\"{newnext}\"</span>",
		"modifyActivity_modifyRouteField": "[Route] modified the route of <b>\"{name}\"</b> activity <b>\"{rname}\"</b>, attribute <b>\"{field}\"< /b> From: <span style='color: #ff0000'>\"{old}\"</span>, modify to: <span style='color: #0000ff'>\"{new}\"< /span>",
		"deleteActivity": "[Activity] deleted the activity <b style='color: #ff0000'>\"{name}\"</b>",
		"addActivity": "[Activity] Added activity <b style='color: #0000ff'>\"{name}\"</b>",
		"noDiffs": "No difference with the previous version",
		"hasDiffs": "Differences from the previous version:",
		"open": "Switch",
		"enable": "Enable",
		"rollback": "Rollback",
		"override": "Override",
		"del": "Delete",
		"openInfor": "Save the currently opened version and open the version\"{v}\".",
		"enableInfor": "Enable process version\"{v}\"",
		"rollbackInfor": "Roll the process design back to the selected version, all versions after the selected version will be deleted.",
		"overrideInfor": "Override the current version with the design of the selected version.",
		"delInfor": "Delete process version\"{v}\".",
		"enabledProcessTitle": "Enable process confirmation",
		"enabledProcessInfor": "Set the current process to \"enabled\", the previously enabled process version will be set to \"not enabled\".<br><br>Process instances already in circulation will not be affected, and the process will be started next time, the process instance will be created with the enabled process version.<br><br>Are you sure you want to set the current process to \"enabled\"?",
		"deleteEditionTitle": "Delete Edition Confirmation",
		"deleteEditionInfor": "Delete the selected process version \"{v}\", and also delete the circulating instance of the process version \"{v}\". Are you sure you want to delete the process version \"{v}\"?"
	},
	"selectorButton": {
		"ok": "OK",
		"cancel": "Cancel"
	},
	"orgEditor": {
		"addOption": "Add Option",
		"modifyOption": "Modify Option",
		"conflictNotice": "The route has been configured with the same name",
		"copyConfig": "Copy selection configuration"
	},
	"serial": {
		"text": [
			"Text",
			"Arbitrary text"
		],
		"year": [
			"Year",
			"Year of drafting time"
		],
		"month": [
			"Month",
			"Month of drafting time"
		],
		"day": [
			"Day",
			"Day of drafting time"
		],
		"unit": [
			"Unit",
			"The direct unit of the author"
		],
		"unitAttribute": [
			"unitAttr",
			"Attributes of the direct unit of the author"
		],
		"script": [
			"script",
			"script"
		],
		"number": [
			"serial",
			"Serial Number"
		]
	},
	"propertyTemplate": {
		"base": "Base",
		"event": "Event",
		"html": "HTML",
		"json": "JSON",
		"person": "Person",
		"split": "Split",
		"apiDoc": "Click here to view the API documentation",
		"id": "ID",
		"name": "Name",
		"alias": "Alias",
		"description": "Description",
		"creator": "Creator",
		"createTime": "CreateTime",
		"updater": "Updater",
		"updateTime": "UpdateTime",
		"application": "Application",
		"icon": "Icon",
		"type": "Type",
		"form": "Form",
		"routeAsOpinion": "Use route name as default opinion",
		"yes": "Yes",
		"no": "No",
		"opinionInfo": "(Select \"No\": the opinion will be empty when opinion is not filled)",
		"version": "Version",
		"versionName": "Version Name",
		"versionId": "Version Id",
		"versionDescription": "Version Description",
		"startup": "Startup",
		"startTerminal": "Start Terminal",
		"pcAndMobile": "PC and mobile",
		"onlyPc": "PC only",
		"none": "none",
		"startMode": "StartMode",
		"instanceMode": "instance",
		"draftMode": "draft",
		"instanceModeInfo": "(Create a process instance directly when creating a new process, and generate to-do for the drafter)",
		"draftModeInfo": "(When creating a new process, no process instance is created, no to-do is generated, a draft document is generated, and the process instance is not created until the transfer.Attachments cannot be uploaded in draft mode.)",
		"checkDraft": "Check Draft",
		"checkDraftInfo": "(Select \"Yes\": unsaved process instances will not be retained)",
		"power": "Power",
		"stratIdentity": "Strat Person",
		"startUnit": "Start Unit",
		"starGroup": "Start Group",
		"manager": "Manager",
		"maintenanceIdentity": "Maintainer",
		"defaultIdentity": "Default handler",
		"managerScript": "Maintainer Script",
		"number": "Number",
		"numberActivity": "NumberActivity",
		"trigger": "Trigger",
		"arrivals": "Arrivals",
		"submit": "Submit",
		"aging": "Aging",
		"processTimeLimit": "Process TimeLimit",
		"noLimit": "NoLimit",
		"specifyDuration": "SpecifyDuration",
		"byScript": "By Script",
		"timeLimit": "TimeLimit",
		"days": "days",
		"hours": "hours",
		"workTimeOnly": "WorkTime Only",
		"includeNoworkTime": "Include Non-worktime",
		"script": "Script",
		"returnJson": "return JSON Object",
		"hourTimeout": "Timeout after a few hours",
		"hourWorkTimeout": "Timeout after a few working hours",
		"specifyTimeout": "Timeout after the specified time",
		"oneOfThree": "One Of Three",
		"mapping": "Mapping",
		"mappingData": "Mapping Data",
		"dataName": "Name",
		"dataPath": "Path",
		"dataType": "Type",
		"mappingOnFlow": "Mapping data every time after flow",
		"mappingDataToTable": "Mapping Query Table",
		"mappingTableEnabled": "Store the data in the query table after work completed",
		"queryTable": "tables",
		"data": "data",
		"dataTrace": "Business data trace",
		"dataTraceInfo": "Enabling business data tracking can record every change of the specified business field, and you can set to view the historical change records of business data in the form design",
		"dataTraceInfo2": "",
		"dataTraceFields": "Trace Fields",
		"dataTraceDisabled": "None",
		"dataTraceCustom": "Custom",
		"dataTraceAll": "All",
		"dataTraceDisabledInfo": "Do not trace any business data fields",
		"dataTraceCustomInfo": "Define the business fields to be traced in the following settings",
		"dataTraceAllInfo": "Trace all business data fields (excluding data tables, data templates and long text (Lob) type data)",
		"dataTraceFieldNames": "Field Names",
		"allowReroute": "Allow Reroute",
		"allowRerouteTo": "Allow Reroute to here",
		"mergeLayerThreshold": "Number of Merge Layers",
		"mergeLayerThreshold0": "Merge as many layers as possible",
		"mergeLayerThreshold1": "Merge single layers",
		"reader": "Reader",
		"readerId": "Reader ID",
		"duty": "Duty",
		"processData": "Data",
		"reviewer": "Review",
		"reviewerId": "Review Id",
		"unit": "Unit",
		"participant": "Process role",
		"participant_creator": "initiator",
		"participant_activity": "Participant",
		"participant_maintenance": "Maintainer",
		"participant_none": "None",
		"participant_creator_info": "Set the initiator of the process instance as the handler of the current activity",
		"participant_maintenance_info": "Set the maintainer of the process as the handler of the current activity",
		"participant_activity_info": "Set the handler of the activity that the process instance has transferred as the handler of the current activity. Please select the activity below",
		"splitScript": "Split Value Script",
		"embed": "Embed",
		"selectProcess": "Select Process",
		"embedType": "Embed Type",
		"sync": "Sync",
		"async": "Async",
		"copyData": "Copy Data",
		"copyAttachment": "Copy Attachment",
		"startPerson": "Initiator",
		"currentCreator": "The initiator of the current process",
		"prevHandler": "Handler of the previous activity",
		"specifyPerson": "Specify an initiator",
		"personId": "Initiator ID",
		"personScript": "Initiator Script",
		"titleScript": "Title Script",
		"dataScript": "Data Script",
		"getOldData": "Get business data of the original process",
		"setNewData": "Set the business data of the new process",
		"timer": "Timer",
		"timerType": "Timer Type",
		"delayTime": "Execute after few minute delay",
		"specifyTime": "Specify a time point to execute",
		"specifyMinute": "Specified minute",
		"specifyATime": "Specified time",
		"specifyData": "Specified data path",
		"invoke": "Invoke",
		"protocol": "Protocol",
		"invokeType": "Invoke Type",
		"wsdlAddr": "WSDL",
		"method": "Method",
		"parameterScript": "Parameter Script",
		"addParameter": "Add Parameter",
		"deleteParameter": "Delete Parameter",
		"responseScript": "Response Script",
		"use": "Use",
		"getJson": " get response content. If the response content is a string in JSON format, a JSON object is returned; otherwise, the original response content is returned.",
		"systemRequest": "System Service",
		"restAddr": "Restful Address ",
		"requestBodyScript": "Request Body Script",
		"setRequestBody": "Set Request Body ",
		"requestHeaderScript": "Request Header Script",
		"addHeader": "Add Header ",
		"delHeader": "Delete Header ",
		"setParameterInfo": "Return a json object to set parameters, please check the API documentation",
		"setParameterInfo2": "Return a array to set parameters, please check the API documentation",
		"setRequestBodyInfo": "Return a json object to set the message body, please check the API documentation",
		"setHeaderInfo": "Return a json object to set the message header, please check the API documentation",
		"getJaxws": "Get the response content. The response type depends on the return of the service",
		"service": "Service",
		"serviceResponseScript": "Response Script",
		"responseInfo": "Get the request data through \"this.request.getBody()\"<br/>return true, the drive flow continues to flow<br/>return false, indicating that the flow conditions are not met, waiting for the next call",
		"runScript": "Execute script",
		"processType": "ProcessType",
		"oneProcess": "One person handles",
		"single": "single",
		"sameTime": "Simultaneous processing by multiple people",
		"parallel": "parallel",
		"queue": "queue",
		"queueInfo": "Multiple people in sequence",
		"grab": "grab",
		"grabInfo": "Whoever opens the task first will handle it",
		"readForUntreated": "Send read to untreated person",
		"mergeTask": "Merge Task",
		"mergeTaskInfo": "(If you choose \"Yes\", the task on this activity with the same identity will be merged)",
		"mergeTaskProcess": "Merge Task Processing",
		"mergeTaskProcessInfo": "(If you select \"Yes\", when the same person's different identities generate multiple to-dos in this activity, they only need to be processed once)",
		"activityGroup": "Activity Group",
		"opinionGroup": "Opinion Group",
		"taskPerson": "Task",
		"customData": "Custom Properties",
		"identity": "Identity",
		"group": "Group",
		"readGroup": "Group",
		"reviewGroup": "Group",
		"specifyTimeoutTime": "Set the specified timeout period",
		"setTimeoutAfterHours": "Set timeout after a few hours",
		"setTimeoutAfterWorkHours": "Set timeout after a few work hours",
		"activityPower": "Power",
		"allowDelete": "Allow Delete",
		"allowTerminate": "Allow Terminate",
		"allowReset": "Allow Reset",
		"resetCount": "Reset Count",
		"resetRange": "Reset Range",
		"everyOne": "anyone",
		"directUnit": "My unit",
		"topUnit": "Top unit",
		"allowRetract": "Allow Retract",
		"allowRapid": "Allow Rapid deal with",
		"allowAddSplit": "Allow Add Split",
		"allowRollback": "Allow Rollback",
		"allowPress": "Allow Press",
		"allowPause": "Allow Pause",
		"allowAddTask": "Allow Add Task",
		"backConfig": "Back configuration",
		"allowBack": "Allow Back",
		"multiTaskEnable": "Allow rollback when multi-task",
		"multiTaskEnableInfo": "Executing return when multi-person processing will cancel the to-do of other unprocessed people, and directly return to the specified activity",
		"backType": "Back Type",
		"backPrev": "Back previous Activity",
		"backAny": "Any Activity",
		"backDefine": "Select Back Activity",
		"backPrevInfo": "Level-by-level return: the user selects \"Back\", then the current work will be returned to the previous processing activity",
		"backAnyInfo": "Back any activity: When the user selects \"Back\", they can choose any activity that has been processed",
		"backDefineInfo": "Select back activity: define the activities that allow back, used to return to the allowed activities",
		"backWay": "Process after return",
		"backWayDefault": "default",
		"backWayStep": "Normal flow according to process configuration",
		"backWayJump": "Go straight back to the bouncer",
		"backWayCustom": "BackWayCustom",
		"backActivitySelectTitle": "Select an activity that allows backtracking",
		"backActivitySelectInfo": "You can select the activity nodes that are allowed to be returned in the current activity. Only the allowed activities that have been transferred can be returned. You can also set the processing method after the return for each activity that is allowed to be returned.",
		"beforeBegin": "beforeBegin",
		"eventInfo1": "Start the process to generate a work instance",
		"afterBegin": "afterBegin",
		"beforeArrive": "beforeArrive",
		"eventInfo2": "Perform Arrive operation, set activity attribute",
		"afterArrive": "afterArrive",
		"beforeExecute": "beforeExecute",
		"eventInfo3": "Perform Execute operation, perform automatic activity tasks",
		"afterExecute": "afterExecute",
		"beforeInquire": "beforeInquire",
		"eventInfo4": "Perform the Inquire operation to query the route to the next activity",
		"afterInquire": "afterInquire",
		"beforeEnd": "beforeEnd",
		"eventInfo5": "End the process and generate workCompleted",
		"afterEnd": "afterEnd",
		"beforeWorkArrive": "beforeWorkArrive",
		"beforeArriveActivity": "beforeArrive",
		"afterArriveActivity": "afterArrive",
		"eventInfo6": "Perform Arrive operations, set activity attributes, calculate possible activity owners",
		"eventInfo7": "Execute \"Execute\" operation, generate task",
		"manualStay": "manualStay",
		"eventInfo8": "Flow Task",
		"manualBeforeTask": "manualBeforeTask",
		"eventInfo9": "Process task, generate taskComplete",
		"manualAfterTask": "manualAfterTask",
		"eventInfo10": "Determine whether the conditions are met and enter the next activity",
		"eventInfo11": "Execute all process flow tasks until staying or ending in an activity",
		"afterProcess": "Activity flow complete",
		"updataTime": "UpdataTime",
		"num": "SerialNumber",
		"defaultOpinion": "Default Opinion",
		"opinionRequired": "Opinion Required",
		"routeType": "RouteType",
		"defaultRoute": "Default Route",
		"sole": "Selected by default",
		"defaultRouteSelected": "Default Route",
		"backRoute": "Back Route",
		"appendTask": "AppendTask（Must point to the same activity）",
		"appendTaskInfo": "The AppendTask does not trigger the activity event",
		"appendTo": "AppendTo",
		"byRoute": "By Route",
		"appendToScript": "AppendTo Script",
		"asyncReturn": "Async Return",
		"expand": "Expand",
		"decisionGroup": "Decision Group",
		"decisionGroupInfo": "Separate multiple decision groups with # signs, and add an integer before the name for the sort value. Such as \"1agree#2disagree\".",
		"prefRouting": "Pref Routing",
		"routeNow": "Route Immediately",
		"routeNowInfo": "(When you select \"Yes\", as long as you select this route in multi-person processing, the document will be transferred immediately according to this route)",
		"autoFlowTime": "Auto flow when the activity timeout",
		"autoFlowPerson": "Auto flow when the handler is the same as the previous activity",
		"routeCheck": "Route Verification",
		"routeCheckInfo": "(Return true to pass, return string to indicate error)",
		"showName": "Show Name",
		"hideCondition": "Hide Condition",
		"hideConditionInfo": "(Return true to hide)",
		"select": "Select",
		"title": "Title",
		"titleInfo": "Such as: please select department manager",
		"defaultValue": "DefaultValue",
		"defaultValueScript": "Default Value Script",
		"checkCount": "Count",
		"checkCountInfo": "The number of choices is not less than",
		"verificationScript": "Verification Script",
		"unitSelectConfig": "Unit Select Config",
		"selectType": "Select Type",
		"personIdentity": "Identity",
		"selectCount": "Select Count",
		"checkEmpower": "Check Empower",
		"onlyCustom": "Use only custom options",
		"unitRange": "Unit Range",
		"allUnit": "All Unit",
		"specifyUnit": "Specify Unit",
		"draftUnit": "The Unit of the drafter",
		"currentUnit": "The Unit of the current person",
		"inUnit": "Directly affiliated organization",
		"levelIs": "The",
		"levelUnit": " level unit",
		"unitTypeIs": "The unit type is ",
		"deUnit": "Organization of",
		"expandNext": "Expand lower level",
		"selectUnit": "Select Unit",
		"formData": "Form data",
		"dutyRange": "Duty Range",
		"all": "All",
		"all2": "All",
		"specifyDuty": "Specify Duty",
		"category": "Category",
		"byUnit": "By Unit",
		"byDuty": "By Duty",
		"showLevel": "Show Level",
		"byDutyUnit": "By the unit of duty",
		"byIdentityUnit": "By the unit of identity",
		"selectDuty": "Select Duty",
		"customOption": "Custom options",
		"useScriptAddId": "Use script to add identity",
		"unitType": "Unit Type",
		"exclude": "Exclude",
		"excludeInfo": "Exclude the selection of unit, identity, person, and group by scripts",
		"firstLevelSelectable": "Allowed select the first",
		"dataStructure": "data Structure",
		"complete": "Complete",
		"simple": "Simple",
		"section": "Section",
		"enableSection": "Enable Section",
		"sectionBy": "SectionBy",
		"handler": "Handler",
		"handlerUnit": "Handler Unit",
		"activityId": "Activity Id",
		"splitValue": "Split Value",
		"publish": "Publish",
		"publishTarget": "Publish Target",
		"cms": "Content Management",
		"table": "Data Table",
		"cmsCategory": "Content Management Category",
		"selectCmsCategory": "Select Category",
		"categoryDataPath": "Category DataPath",
		"sendNotify": "Message push range field",
		"readerFields": "Reader Fields",
		"authorFields": "Author Fields",
		"pictureFields": "Homepage picture fields",
		"useProcessForm": "Use Process Form",
		"titleField": "Title Field",
		"useProcessFormNote": "Note: If yes, the document published to the content management will be opened using the process form, otherwise it will be opened using the form set by the content management classification.",
		"setNewPublishData": "Returns a json object to set the data, please check the API documentation. Such as",
		"querytable": "Data Table",
		"querytableActionNode_add": "↑ Add data table configuration entry ↑",
		"querytableActionNode_modify": "↑ Modify data table configuration entry ↑",
		"querytableInputError": "Please select a data table",
		"queryTableAssignDataScriptError": "Data script cannot be empty",
		"querytableDeleteItemTitle": "Delete data table configuration item confirmation",
		"querytableDeleteItem": "Are you sure you want to delete the current data table configuration item?",
		"queryTableDataBy": "value",
		"byDataPath": "By DataPath",
		"byDataScript": "By DataScript",
		"publishTableConfig": "Data table publishing configuration",
		"queryTableDataPathNote": "Note: the root path is empty, the data table is filled with the data table identifier .data (eg datatable1.data), and the data template is filled with the data template identifier (eg datatemplate1).",
		"orgIdPlaceholder": "Such as: departmentLeader",
		"dataTraceFieldNamesSelect": "Select form fields",
		"selectForm": "form ",
		"selectField": "Data fields",
		"selectedField": "Selected fields",
		"mergeLayerThresholdn": "Merge {n} layers",
		"waitUntilCompletedTitle": "Process waiting",
		"waitUntilCompleted": "If \"Yes\" is selected, the main process will remain waiting during the called process flow until the called process flow ends",
		"completedEventsInfo": "Enabling process waiting will trigger the main process to continue flowing after the sub process ends. The following three events will be executed",
		"completedEndEvent": "After successful sub process",
		"completedEnd": "After successful sub process",
		"completedCancelEvent": "After the sub process is cancelled",
		"completedCancel": "After the sub process is cancelled",
		"completedEvent": "After completing the sub process",
		"completed": "After completing the sub process",
		"completedEndEventInfo": "When the sub process flows to the end activity, this event will be executed",
		"completedCancelEventInfo": "When the sub process flows to the cancellation activity, this event will be executed",
		"completedEventInfo": "When the sub process flows to the end or cancels the activity, this event will be executed",
		"groupRange": "Group scope",
		"specifyGroup": "Designated groups"
	}
}
MWF.xApplication.process.ProcessDesigner["lp."+o2.language] = MWF.xApplication.process.ProcessDesigner.LP