MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.ProcessDesigner = MWF.xApplication.process.ProcessDesigner || {};
MWF.xApplication.process.ProcessDesigner.LP={
	"title": "Edición de flujo de trabajo",
	"newProcess": "Nuevo flujo de trabajo",
	"tools": "Herramientas",
	"unnamed": "Sin nombre",
	"unknow": "Desconocido",
	"unrealized": "Esta función no está implementada",
	"activity": "Actividad",
	"route": "Ruta",
	"property": "Prop",
	"showJson": "Ver JSON",
	"all": "Todo",
	"showAdvanced": "Propiedades avanzadas",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"selectScript": "Haz clic para seleccionar el script:",
	"condition": "Condición",
	"unCategory": "Sin categoría",
	"ok": "Aceptar",
	"close": "Cerrar",
	"cancel": "Cancelar",
	"notice": {
		"no_name": "Por favor, ingrese un nombre para el flujo de trabajo",
		"save_success": "¡Flujo de trabajo guardado exitosamente!",
		"save_process": "¡Por favor, guarde el flujo de trabajo primero!",
		"one_begin": "Cada flujo de trabajo solo puede tener una actividad 'Inicio'",
		"deleteRoute": "¿Está seguro de que desea eliminar la ruta seleccionada?",
		"deleteRouteTitle": "Confirmación",
		"deleteActivityTitle": "Confirmación",
		"deleteActivity": "La eliminación de la actividad también eliminará todas las rutas asociadas con esta actividad. ¿Está seguro de que desea eliminar la actividad seleccionada?",
		"saveRouteOrgNoName": "La identificación y el título no pueden estar vacíos",
		"saveRouteOrgNumberId": "La identificación no puede ser solo números",
		"saveRouteOrgDoubleDotId": "La identificación no puede contener dos puntos consecutivos",
		"processCopyError": "La copia de la actividad ha fallado. Por favor, intente copiar de nuevo.",
		"routeNameConfilct ": " una actividad no puede tener dos rutas con el mismo nombre!",
		"routeNameConfilct": "¡¡ una actividad no puede tener dos rutas con el mismo nombre!"
	},
	"menu": {
		"newRoute": "Nueva ruta",
		"newActivity": "Nueva actividad",
		"newActivityType": {
			"manual": "Manual",
			"condition": "Condicional",
			"auto": "Automática",
			"split": "División",
			"merge": "Unión",
			"embed": "Subflujo",
			"invoke": "Llamada",
			"service": "Servicio",
			"agent": "Script",
			"delay": "Programada",
			"publish": "Publicación",
			"message": "Mensaje",
			"choice": "Elección",
			"cancel": "Cancelación",
			"begin": "Inicio",
			"end": "Fin",
			"parallel": "Paralela"
		},
		"copyActivity": "Copiar actividad",
		"deleteActivity": "Eliminar actividad",
		"deleteRoute": "Eliminar ruta",
		"saveProcess": "Guardar flujo de trabajo",
		"saveProcessNew": "Guardar como nueva versión",
		"checkProcess": "Revisar flujo de trabajo",
		"exportProcess": "Exportar flujo de trabajo",
		"printProcess": "Imprimir flujo de trabajo",
		"showGrid": "Mostrar cuadrícula",
		"hideGrid": "Ocultar cuadrícula"
	},
	"intoScript": "Haga clic aquí para escribir código de script",
	"serialSelectTitle": "Atributos opcionales de número de serie",
	"serialActivityTitle": "Actividad de número de serie",
	"delete": "Eliminar",
	"serialRule": "Regla de numeración",
	"serialTextTitle": "Texto de entrada",
	"serialDateTitle": "Fecha",
	"serialCreatedDateTitle": "Fecha de presentación",
	"serialCurrentDateTitle": "Fecha del número de serie actual",
	"serialCreated": "Presentación",
	"serialCurrent": "Número de serie actual",
	"serialAttributeTitle": "Nombre de atributo",
	"serialScriptTitle": "Ingrese el script",
	"serialNumberLongTitle": "Longitud del número de serie",
	"serialNumberByTitle": "Criterio de numeración",
	"isSave": "Guardando, por favor espere...",
	"dutyInputTitle": "Agregar parámetros de cargo",
	"dutyInput": "Agregue parámetros para el cargo '{duty}'",
	"creatorCompany": "Empresa del creador",
	"creatorDepartment": "Departamento del creador",
	"currentCompany": "Empresa actual",
	"currentDepartment": "Departamento actual",
	"deleteDutyTitle": "Confirmación de eliminación de cargo",
	"deleteDutyText": "¿Está seguro de que desea eliminar el cargo '{duty}'?",
	"selectIcon": "Seleccionar icono",
	"centerServer": "Servidor central",
	"creatorUnit": "Organización del creador",
	"currentUnit": "Organización del encargado",
	"selectUnit": "Seleccionar organización",
	"scriptUnit": "Usar script",
	"preview": "Vista previa",
	"copy": "Copiar de otra configuración",
	"selectType": "Seleccionar tipo",
	"identity": "Identidad",
	"unit": "Organización",
	"selectCount": "Seleccionar cantidad",
	"deleteOrgConfirmTitle": "Confirmación",
	"deleteOrgConfirmContent": "¿Está seguro de que desea eliminar esta configuración de selección?",
	"projectionTitle": "Mapeo de datos empresariales",
	"projectionActionNode_add": "Agregar entrada de mapeo",
	"projectionActionNode_modify": "Modificar entrada de mapeo",
	"projectionDataName": "Nombre de los datos",
	"projectionPath": "Ruta de los datos",
	"projectionType": "Tipo de datos",
	"projectionName": "Nombre de columna",
	"projectionInputError": "Por favor ingrese el nombre y la ruta de los datos",
	"projectionTypeCountError": "Se permiten hasta {count} entradas de mapeo del tipo {type}.",
	"projectionSameNameError": "Ya existe un nombre de datos igual",
	"projectionDeleteItemTitle": "Confirmación",
	"projectionDeleteItem": "¿Estás seguro de que quieres eliminar la entrada de mapeo de datos llamada '{name}' con la ruta '{path}'?",
	"projectionRunActionNode": "Ejecutar el mapeo de datos ahora",
	"projectionRunTitle": "Confirmación",
	"projectionRunText": "Por favor confirme para ejecutar el mapeo de datos ahora",
	"projectionRunSuccess": "El mapeo de datos ha comenzado a ejecutarse",
	"projectionRunError": "No es necesario ejecutar el mapeo de datos",
	"enable": "Habilitado",
	"notEnable": "No habilitado",
	"currentEdition": "Versión actual",
	"editionUpdate": "Última modificación",
	"editionDiscription": "Ingrese la descripción de la versión",
	"upgradeConfirm": "Confirmar guardar como nueva versión",
	"upgradeInfor": "<div style='overflow: hidden; line-height: 26px'>¿Está seguro de que desea guardar el flujo actual como una nueva versión?<br/> Si selecciona \"Habilitar nueva versión\", después de que se complete la guardada, se establecerá la nueva versión como versión habilitada.</div><div style='margin-top:10px'><input type='checkbox' checked>Habilitar nueva versión</div>",
	"inputDiscription": "Por favor ingrese primero la descripción de la versión",
	"edition_list": {
		"editionList": "Ver versiones del flujo",
		"number": "Número",
		"update": "Hora de actualización",
		"updatePerson": "Persona",
		"description": "Descripción de la versión",
		"enabled": "Habilitado",
		"action": "Acción",
		"yes": "Sí",
		"no": "No",
		"newProcess": "Se ha creado un nuevo flujo.",
		"an": "un/a",
		"modifyProcess": "[Flujo] modificó la propiedad del flujo <b>\"{field}\"</b>, de: <span style='color: #ff0000'>\"{old}\"</span> a <span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity": "[Actividad] modificó la propiedad <b>\"{field}\"</b> de la actividad <b>“{name}”</b>, de: <span style='color: #ff0000'>\"{old}\"</span> a <span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity_addRoute": "[Ruta] agregó la ruta <b>“{rname}”</b> a la actividad <b>“{name}”</b>, dirigiéndose a <span style='color: #0000ff'>“{next}”</span>",
		"modifyActivity_deleteRoute": "[Ruta] eliminó la ruta <b>“{rname}”</b> de la actividad <b>“{name}”</b>, que se dirigía a <span style='color: #ff0000'>“{next}”</span>",
		"modifyActivity_modifyRouteNext": "[Ruta] modificó la ruta <b>“{rname}”</b> de la actividad <b>“{name}”</b>, pasando de dirigirse a <span style='color: #ff0000'>“{oldnext}”</span> a dirigirse a <span style='color: #0000ff'>“{newnext}”</span>",
		"modifyActivity_modifyRouteField": "[Ruta] modificó la ruta <b>“{rname}”</b> de la actividad <b>“{name}”</b>, la propiedad <b>\"{field}\"</b>, de: <span style='color: #ff0000'>\"{old}\"</span> a <span style='color: #0000ff'>\"{new}\"</span>",
		"deleteActivity": "[Actividad] eliminó la actividad <b style='color: #ff0000'>“{name}”</b>",
		"addActivity": "[Actividad] agregó la actividad <b style='color: #0000ff'>“{name}”</b>",
		"noDiffs": "No hay diferencias con la versión anterior",
		"hasDiffs": "Diferencias con la versión anterior:",
		"open": "Cambiar",
		"enable": "Habilitar",
		"rollback": "Revertir",
		"override": "Sobrescribir",
		"del": "Eliminar",
		"openInfor": "Guardar la versión actualmente abierta y abrir la versión '{v}'.",
		"enableInfor": "Habilitar la versión del flujo '{v}'.",
		"rollbackInfor": "Revertir el diseño del flujo a la versión seleccionada, todas las versiones después de la seleccionada serán eliminadas.",
		"overrideInfor": "Sobrescribir el diseño actual con la versión seleccionada.",
		"delInfor": "Eliminar la versión del flujo '{v}'.",
		"enabledProcessTitle": "Confirmación para habilitar el flujo",
		"enabledProcessInfor": "Establecerá el flujo actual como \"Habilitado\", la versión previamente habilitada será \"No habilitada\".<br><br>Las instancias del flujo que ya están en curso no se verán afectadas. La próxima vez que se inicie el flujo, se creará una instancia del flujo basada en la versión habilitada.<br><br>¿Estás seguro de que deseas establecer el flujo actual como \"Habilitado\"?",
		"deleteEditionTitle": "Confirmación para eliminar la versión",
		"deleteEditionInfor": "Eliminar la versión seleccionada del flujo '{v}', también se eliminarán las instancias del flujo que están en curso de la versión '{v}'. ¿Está seguro de que desea eliminar la versión del flujo '{v}'?"
	},
	"selectorButton": {
		"ok": "Aceptar",
		"cancel": "Cancelar"
	},
	"orgEditor": {
		"addOption": "Agregar",
		"modifyOption": "Modificar",
		"conflictNotice": "Esta ruta ya tiene una configuración con el mismo nombre.",
		"copyConfig": "Copiar la configuración de selección"
	},
	"serial": {
		"text": [
			"Texto",
			"Texto fijo"
		],
		"year": [
			"Año",
			"Año de creación del borrador"
		],
		"month": [
			"Mes",
			"Mes de creación del borrador"
		],
		"day": [
			"Día",
			"Día de creación del borrador"
		],
		"unit": [
			"Organización",
			"Organización directa del autor del borrador"
		],
		"unitAttribute": [
			"Atributo de organización",
			"Atributo de la organización directa del autor del borrador"
		],
		"script": [
			"Script",
			"Script"
		],
		"number": [
			"Número de serie",
			"Número de serie"
		]
	},
	"propertyTemplate": {
		"base": "Básico",
		"event": "Evento",
		"html": "HTML",
		"json": "JSON",
		"person": "Persona",
		"split": "División",
		"apiDoc": "Haga clic aquí para ver la documentación de la API",
		"id": "Identificación",
		"name": "Nombre",
		"alias": "Alias",
		"description": "Descripción",
		"creator": "Creador",
		"createTime": "Fecha de creación",
		"updater": "Actualizador",
		"updateTime": "Última actualización",
		"application": "Aplicación",
		"icon": "Ícono",
		"type": "Tipo",
		"form": "Formulario",
		"routeAsOpinion": "Usar el nombre de la ruta como opinión por defecto",
		"yes": "Sí",
		"no": "No",
		"opinionInfo": "(Seleccione \"No\": si no se completa la opinión del procesamiento, la opinión estará vacía)",
		"version": "Versión",
		"versionName": "Nombre de versión",
		"versionId": "Identificación de versión",
		"versionDescription": "Descripción de versión",
		"startup": "Inicio",
		"startTerminal": "Iniciar la terminal",
		"pcAndMobile": "PC y móvil",
		"onlyPc": "Solo PC",
		"none": "Ninguno",
		"startMode": "Modo de inicio",
		"instanceMode": "Modo de instancia",
		"draftMode": "Modo de borrador",
		"instanceModeInfo": "(Crear una instancia del flujo directamente al crear el flujo, generar una tarea pendiente para el autor del borrador)",
		"draftModeInfo": "(No crear una instancia del flujo al crear el flujo, no generar tarea pendiente, generar un documento de borrador, crear una instancia del flujo solo cuando se realiza el procesamiento. Los archivos adjuntos no se pueden cargar en modo borrador.)",
		"checkDraft": "Verificación al crear",
		"checkDraftInfo": "(Seleccionar \"Sí\": las instancias del flujo que no se hayan guardado no se guardarán)",
		"power": "Permiso",
		"stratIdentity": "Autor del inicio",
		"startUnit": "Organización de inicio",
		"starGroup": "Grupo de inicio",
		"manager": "Administrador",
		"maintenanceIdentity": "Encargado del mantenimiento",
		"defaultIdentity": "Manejador predeterminado",
		"managerScript": "mantenimiento",
		"number": "Número",
		"numberActivity": "Actividad de numeración",
		"trigger": "Condiciones de activación",
		"arrivals": "Llegadas",
		"submit": "Enviar",
		"aging": "Vigilancia temporal",
		"processTimeLimit": "Tiempo límite del flujo",
		"noLimit": "Sin tiempo límite",
		"specifyDuration": "Duración especificada",
		"byScript": "A través de script",
		"timeLimit": "Duración del tiempo límite",
		"days": "Días",
		"hours": "Horas",
		"workTimeOnly": "Solo cuenta el tiempo de trabajo",
		"includeNoworkTime": "Incluye el tiempo no laborable",
		"script": "Script",
		"returnJson": "El script devuelve datos JSON",
		"hourTimeout": "Tiempo límite después de cuántas horas",
		"hourWorkTimeout": "Tiempo límite después de cuántas horas de trabajo",
		"specifyTimeout": "Tiempo límite especificado",
		"oneOfThree": "Elija uno de los tres valores",
		"mapping": "Mapeo",
		"mappingData": "Mapeo de datos empresariales",
		"dataName": "Nombre de datos",
		"dataPath": "Ruta de datos",
		"dataType": "Tipo de datos",
		"mappingOnFlow": "Actualizar los datos de mapeo cada vez que se realiza el procesamiento",
		"mappingDataToTable": "Tabla de mapeo de datos",
		"mappingTableEnabled": "Al final del procesamiento, guarde los datos en una tabla de datos",
		"queryTable": "Tabla de datos",
		"datos": "Datos",
		"dataTrace": "Rastreo de datos comerciales",
		"dataTraceInfo": "Habilitar el seguimiento de datos comerciales puede registrar cada cambio del campo comercial especificado, y puede configurar para ver los registros de cambios históricos de datos comerciales en el diseño del formulario",
		"dataTraceInfo2": "",
		"dataTraceFields": "Campos de rastreo",
		"dataTraceDisabled": "Ninguno",
		"dataTraceCustom": "Personalizado",
		"dataTraceAll": "Todos",
		"dataTraceDisabledInfo": "No rastrear ningún campo de datos comerciales",
		"dataTraceCustomInfo": "Defina los campos comerciales a rastrear en las siguientes configuraciones",
		"dataTraceAllInfo": "Rastrear todos los campos de datos comerciales (excluyendo tablas de datos, plantillas de datos y datos de tipo texto largo (Lob))",
		"dataTraceFieldNames": "Nombres de campo",
		"allowReroute": "Permitir redireccionamiento",
		"allowRerouteTo": "Permitir redireccionamiento a esta actividad",
		"mergeLayerThreshold": "Número de capas de combinación",
		"mergeLayerThreshold0": "Combina tantas capas como sea posible",
		"mergeLayerThreshold1": "Combinar capas individuales",
		"reader": "Persona que debe leer",
		"readerId": "Identificación",
		"duty": "Posición",
		"processData": "Datos de flujo",
		"reviewer": "Revisor",
		"reviewerId": "Identificación",
		"unit": "Organización",
		"participante": "Rol del proceso",
		"participant_creator": "iniciador",
		"participant_activity": "Participante",
		"participant_maintenance": "Mantenedor",
		"participant_none": "Ninguno",
		"participant_creator_info": "Establecer el iniciador de la instancia del proceso como el controlador de la actividad actual",
		"participant_maintenance_info": "Establecer el mantenedor del proceso como el manejador de la actividad actual",
		"participant_activity_info": "Establezca el controlador de la actividad que la instancia de proceso ha transferido como el controlador de la actividad actual. Seleccione la actividad a continuación",
		"splitScript": "Script de criterios de división",
		"embed": "Llamar",
		"selectProcess": "Subflujo",
		"embedType": "Modo de llamada",
		"sync": "Síncrono",
		"async": "Asíncrono",
		"copyData": "Copiar datos",
		"copyAttachment": "Copiar archivos adjuntos",
		"startPerson": "Autor del inicio",
		"currentCreator": "Autor actual del flujo",
		"prevHandler": "Procesador de la actividad anterior",
		"specifyPerson": "Especificar un autor del inicio",
		"personId": "Identificación del autor del inicio",
		"personScript": "Script del autor del inicio",
		"titleScript": "Script del título",
		"dataScript": "Script de datos",
		"getOldData": "Obtener los datos empresariales del flujo original",
		"setNewData": "Establecer los nuevos datos empresariales del flujo",
		"waitUntilCompletedTitle": "Espera del flujo de trabajo",
		"waitUntilCompleted": "Si se selecciona \"Sí\", el flujo de trabajo principal esperará durante el procesamiento del subflujo y no continuará hasta que se complete el subflujo.",
		"completedEventsInfo": "Al habilitar la espera del flujo de trabajo, se activarán los siguientes tres eventos una vez que finalice el subflujo y permitirán que el flujo de trabajo principal continúe:",
		"completedEndEvent": "Cuando el subflujo se haya completado correctamente",
		"completedEnd": "Subflujo completado",
		"completedCancelEvent": "Cuando se haya cancelado el subflujo",
		"completedCancel": "Subflujo cancelado",
		"completedEvent": "Cuando el subflujo finalice",
		"completed": "Subflujo finalizado",
		"completedEndEventInfo": "Este evento se activará cuando el subflujo llegue a la actividad final.",
		"completedCancelEventInfo": "Este evento se activará cuando se cancele el subflujo.",
		"completedEventInfo": "Este evento se activará cuando el subflujo llegue a la actividad final o se cancele.",
		"timer": "Temp.",
		"timerType": "Tipo de temporización",
		"delayTime": "Ejecutar después de un retraso específico en minutos",
		"specifyTime": "Ejecutar en un momento específico",
		"specifyMinute": "Especificar minutos",
		"specifyATime": "Especificar la hora",
		"specifyData": "Especificar la ruta de datos",
		"invoke": "Invocar",
		"protocol": "Protocolo de servicio",
		"invokeType": "Tipo de invocación",
		"wsdlAddr": "Dirección WSDL",
		"method": "Método de invocación",
		"parameterScript": "Script de parámetros",
		"addParameter": "Agregar parámetro",
		"deleteParameter": "Eliminar parámetro",
		"responseScript": "Script de respuesta",
		"use": "Utilizar",
		"getJson": "Obtener el contenido de respuesta. Si el contenido de la respuesta es una cadena en formato JSON, se devolverá un objeto JSON; de lo contrario, se devolverá el contenido de respuesta original. Si llama a una interfaz en la plataforma de servicios, los datos que se devuelven deben estar dentro del campo \"data\", por ejemplo: {\"data\": []}",
		"systemRequest": "Solicitud interna del sistema",
		"restAddr": "Dirección REST",
		"requestBodyScript": "Script del cuerpo del mensaje",
		"setRequestBody": "Establecer el contenido del cuerpo del mensaje",
		"requestHeaderScript": "Script del encabezado del mensaje",
		"addHeader": "Agregar información de encabezado HTTP",
		"delHeader": "Eliminar información de encabezado HTTP",
		"setParameterInfo": "Devuelve un objeto JSON para establecer los parámetros. Consulte la documentación de la API",
		"setParameterInfo2": "Devuelve una matriz para establecer los parámetros. Consulte la documentación de la API",
		"setRequestBodyInfo": "Devuelve un objeto JSON para establecer el contenido del cuerpo del mensaje. Consulte la documentación de la API",
		"setHeaderInfo": "Devuelve un objeto JSON para establecer el encabezado del mensaje. Consulte la documentación de la API",
		"getJaxws": "Obtener el contenido de respuesta. El tipo de respuesta depende de lo que devuelve el servicio",
		"service": "Respuesta",
		"serviceResponseScript": "Script de respuesta del servicio",
		"responseInfo": "Use this.request.getBody() para obtener los datos de solicitud. Devuelva true para continuar el flujo de trabajo; devuelva false si no cumple con las condiciones de flujo y espere la siguiente llamada.",
		"runScript": "Ejecutar script",
		"processType": "Tipo de procesamiento",
		"oneProcess": "Solo una persona necesita procesar",
		"single": "Individual",
		"sameTime": "Procesamiento simultáneo por varias personas",
		"parallel": "Paralelo",
		"queue": "Secuencial",
		"queueInfo": "Procesamiento en orden por varias personas",
		"grab": "Asignado automáticamente",
		"grabInfo": "El primer usuario que abra la tarea pendiente será el responsable del procesamiento",
		"readForUntreated": "Enviar para leer a las personas que no han tratado la tarea pendiente",
		"mergeTask": "Combinar tareas pendientes de ramas",
		"mergeTaskInfo": "(Si se selecciona \"Sí\", cuando el flujo de trabajo se divide, las múltiples tareas pendientes de una misma persona en esta actividad se combinarán en una sola)",
		"mergeTaskProcess": "Combinar proceso de tareas pendientes",
		"mergeTaskProcessInfo": "(Si se selecciona \"Sí\", cuando diferentes identidades de la misma persona generan varias tareas pendientes en esta actividad, solo es necesario procesarlas una vez)",
		"activityGroup": "Grupo de actividad",
		"opinionGroup": "Grupo de opinión",
		"taskPerson": "Persona responsable de la tarea",
		"customData": "Atributos personalizados",
		"identity": "Identidad",
		"group": "Grupo",
		"readGroup": "Grupo",
		"reviewGroup": "Grupo",
		"specifyTimeoutTime": "Establecer un tiempo de espera específico",
		"setTimeoutAfterHours": "Establecer una hora para el tiempo de espera",
		"setTimeoutAfterWorkHours": "Establecer horas laborales para el tiempo de espera",
		"activityPower": "Permisos",
		"allowDelete": "Permitir eliminación de archivos",
		"allowTerminate": "Permitir terminación",
		"allowReset": "Permitir reinicio",
		"resetCount": "Número de reinicios de aprobación",
		"resetRange": "Alcance de reinicio",
		"everyOne": "Todos los miembros",
		"directUnit": "Organización directa",
		"topUnit": "Organización superior",
		"allowRetract": "Permitir retractación",
		"allowRapid": "Permitir procesamiento rápido",
		"allowAddSplit": "Permitir agregar ramas de división",
		"allowRollback": "Permitir reversión del flujo de trabajo",
		"allowPress": "Permitir envío de recordatorios",
		"allowPause": "Permitir pausa",
		"allowAddTask": "Permitir agregación de tarea",
		"beforeBegin": "Antes de iniciar el flujo de trabajo",
		"eventInfo1": "Iniciar el flujo de trabajo para generar una instancia de trabajo",
		"afterBegin": "Comienzo del flujo de trabajo",
		"beforeArrive": "Antes de llegar a la actividad",
		"eventInfo2": "Ejecutar Arrive y configurar las propiedades de actividad",
		"afterArrive": "Llegada a la actividad",
		"beforeExecute": "Antes de ejecutar la actividad",
		"eventInfo3": "Ejecutar Execute y procesar automáticamente las tareas de la actividad",
		"afterExecute": "Actividad completada",
		"beforeInquire": "Antes de consultar una ruta",
		"eventInfo4": "Ejecutar Inquire y buscar la ruta hacia la próxima actividad",
		"afterInquire": "Consulta de ruta completa",
		"beforeEnd": "Antes de finalizar el flujo de trabajo",
		"eventInfo5": "Finalizar el flujo de trabajo y generar workCompleted",
		"afterEnd": "Fin del flujo de trabajo",
		"beforeWorkArrive": "Antes de que el trabajo llegue",
		"beforeArriveActivity": "Antes de recibir un archivo",
		"afterArriveActivity": "Después de recibir un archivo",
		"eventInfo6": "Ejecutar Arrive, configurar las propiedades de la actividad y calcular los posibles responsables",
		"eventInfo7": "Ejecutar Execute y generar tarea pendiente",
		"manualStay": "Esperando procesamiento manual",
		"eventInfo8": "El usuario procesa la tarea pendiente",
		"manualBeforeTask": "Antes de procesar la tarea pendiente",
		"eventInfo9": "Procesar tarea pendiente y marcar como completada",
		"manualAfterTask": "Después de procesar la tarea pendiente",
		"eventInfo10": "Evaluar si se cumplen las condiciones para avanzar a la siguiente actividad",
		"eventInfo11": "Ejecutar todas las tareas de flujo de procesos hasta quedarse o terminar en una actividad",
		"afterProcess": "Flujo de actividad completo",
		"updataTime": "Hora de actualización",
		"num": "Número de secuencia",
		"defaultOpinion": "Opinión predeterminada",
		"opinionRequired": "Se requiere opinión",
		"routeType": "Tipo de ruta",
		"defaultRoute": "Ruta predeterminada",
		"sole": "Seleccionado por defecto",
		"defaultRouteSelected": "Ruta predeterminada",
		"backRoute": "Ruta de retorno",
		"appendTask": "Transferir (solo para la misma actividad)",
		"appendTaskInfo": "La transferencia no activa eventos de actividad",
		"appendTo": "Persona responsable de la transferencia",
		"byRoute": "Seleccionar según la ruta",
		"appendToScript": "Script de persona responsable de la transferencia",
		"asyncReturn": "Retorno asíncrono",
		"expand": "Expandir",
		"decisionGroup": "Grupo de decisiones",
		"decisionGroupInfo": "Separe los grupos de decisiones con #, agregue un valor entero delante del nombre como valor de ordenamiento. Ejemplo: \"1 Aprobar#2 Rechazar\"",
		"prefRouting": "Rutas preferenciales",
		"routeNow": "Ruta inmediata",
		"routeNowInfo": "(Si se selecciona \"Sí\", al procesar varias personas, si seleccionan esta ruta, el documento se enruta inmediatamente por esta ruta)",
		"autoFlowTime": "Flujo automático cuando la actividad expira",
		"autoFlowPerson": "Flujo automático con el mismo responsable que la actividad anterior",
		"routeCheck": "Verificación de ruta",
		"routeCheckInfo": "(Devolver true para aprobar, devolver una cadena para una alerta de error)",
		"showName": "Nombre visible",
		"hideCondition": "Condición oculta",
		"hideConditionInfo": "(Devolver true para ocultar)",
		"select": "Elección",
		"title": "Título",
		"titleInfo": "Ejemplo: Seleccione el gerente de departamento",
		"defaultValue": "Valor predeterminado",
		"defaultValueScript": "Script de valor predeterminado",
		"checkCount": "Verificación de cantidad",
		"checkCountInfo": "La cantidad seleccionada no debe ser inferior a",
		"verificationScript": "Script de verificación",
		"unitSelectConfig": "Configuración",
		"selectType": "Tipo de selección",
		"personIdentity": "Identidad",
		"selectCount": "Cantidad de selección",
		"checkEmpower": "Verificar la autorización pendiente",
		"onlyCustom": "Solo usar opciones personalizadas",
		"unitRange": "Rango de organización",
		"allUnit": "Todas las organizaciones",
		"specifyUnit": "Organizaciones especificadas",
		"draftUnit": "La organización del redactor",
		"currentUnit": "La organización del usuario actual",
		"inUnit": "La organización directa",
		"levelIs": "Nivel",
		"levelUnit": "de la organización",
		"unitTypeIs": "El tipo es",
		"deUnit": "de la organización",
		"expandNext": "Expandir los siguientes niveles",
		"selectUnit": "Seleccionar organización",
		"formData": "Datos del formulario",
		"dutyRange": "Rango de deberes",
		"all": "Todos",
		"all2": "Todo",
		"specifyDuty": "Deberes especificados",
		"category": "Categoría",
		"byUnit": "Por organización",
		"byDuty": "Por deberes",
		"showLevel": "Mostrar niveles",
		"byDutyUnit": "Por organización de los deberes",
		"byIdentityUnit": "Por organización de la identidad",
		"selectDuty": "Seleccionar deberes",
		"customOption": "Opciones personalizadas",
		"useScriptAddId": "Usar script para agregar identidad",
		"unitType": "Tipo de organización",
		"exclude": "Excluir",
		"excludeInfo": "Organizaciones, identidades, personas y grupos excluidos",
		"firstLevelSelectable": "Permitir selección en el primer nivel",
		"dataStructure": "Estructura de datos guardada",
		"complete": "Completa",
		"simple": "Sencilla",
		"section": "Sección",
		"enableSection": "Habilitar sección",
		"sectionBy": "Sección por",
		"handler": "Responsable",
		"handlerUnit": "Organización del responsable",
		"activityId": "ID de actividad",
		"splitValue": "Valor de división",
		"publish": "Publicar",
		"publishTarget": "Destino de publicación",
		"cms": "Gestión de contenido",
		"table": "Tabla de datos",
		"cmsCategory": "Categoría de gestión de contenido",
		"selectCmsCategory": "Seleccionar categoría",
		"categoryDataPath": "Ruta de datos de la categoría de gestión de contenido",
		"sendNotify": "Campo de alcance de la notificación de mensaje",
		"readerFields": "Campos del lector",
		"authorFields": "Campos del autor",
		"pictureFields": "Campo de imagen principal",
		"useProcessForm": "Usar formulario de flujo de trabajo",
		"titleField": "Campo de título",
		"useProcessFormNote": "Nota: si selecciona Sí, el documento de gestión de contenido se abrirá utilizando el formulario de flujo de trabajo. De lo contrario, se usará el formulario establecido en la categoría de gestión de contenido.",
		"setNewPublishData": "Devolver un objeto json para configurar los datos. Consulte la documentación de la API. Ejemplo:",
		"querytable": "Tabla de datos",
		"querytableActionNode_add": "↑ Agregar entrada de configuración de la tabla de datos ↑",
		"querytableActionNode_modify": "↑ Modificar entrada de configuración de la tabla de datos ↑",
		"querytableInputError": "Seleccione una tabla de datos",
		"queryTableAssignDataScriptError": "El script de datos no puede estar vacío",
		"querytableDeleteItemTitle": "Confirmar eliminación de entrada de configuración de tabla de datos",
		"querytableDeleteItem": "¿Está seguro de que desea eliminar la entrada de configuración actual de la tabla de datos?",
		"queryTableDataBy": "Obtener por",
		"byDataPath": "Por ruta de datos",
		"byDataScript": "Por script de datos",
		"publishTableConfig": "Configuración de publicación de tabla de datos",
		"queryTableDataPathNote": "Nota: la ruta raíz está vacía. Para la tabla de datos, ingrese el identificador de la tabla de datos seguido de '.data' (por ejemplo, datatable1.data). Para la plantilla de datos, ingrese el identificador de la plantilla de datos (por ejemplo, datatemplate1).",
		"orgIdPlaceholder": "Ejemplo: departmentLeader",
		"data": "Datos",
		"dataTraceFieldNamesSelect": "Seleccionar campos de formulario",
		"selectForm": "Formulario",
		"selectField": "Campos de datos",
		"selectedField": "Campos seleccionados",
		"mergeLayerThresholdn": "Fusión de capas (n)",
		"participant": "Papel del proceso",
		"backConfig": "Devolver configuración",
		"allowBack": "Permitir la devolución",
		"multiTaskEnable": "¿¿ se permite la devolución cuando varias personas están en paralelo?",
		"multiTaskEnableInfo": "La ejecución de la devolución cuando varias personas procesan en paralelo cancelará la pendiente de otras personas no procesadas y la devolverá directamente a la actividad designada.",
		"backType": "Método de devolución",
		"backPrev": "Devolución paso a paso",
		"backAny": "Devolución de actividades arbitrarias",
		"backDefine": "Selección de actividades de devolución",
		"backPrevInfo": "Devolución paso a paso: si el usuario elige \"devolver\", devuelve el trabajo actual a la actividad de procesamiento anterior",
		"backAnyInfo": "Devolución de cualquier actividad: cuando el usuario elige \"devolver\", puede elegir cualquiera de las actividades que se han procesado",
		"backDefineInfo": "Selección de actividades de devolución: define las actividades permitidas para la devolución, que se pueden devolver a las actividades permitidas",
		"backWay": "Procesamiento posterior a la devolución",
		"backWayDefault": "Predeterminado",
		"backWayStep": "Flujo normal de acuerdo con la configuración del proceso",
		"backWayJump": "Volver directamente a la persona devuelta",
		"backWayCustom": "Depende del remitente decidir",
		"backActivitySelectTitle": "Selección de actividades que permitan la devolución",
		"backActivitySelectInfo": "Puede seleccionar el nodo de actividad que la actividad actual permite devolver, y solo se puede devolver la actividad permitida que ha sido transferida. También puede establecer un método de procesamiento después de la devolución por separado para cada actividad de devolución permitida.",
		"groupRange": "Alcance del Grupo",
		"specifyGroup": "Grupo designado"
	}
}
MWF.xApplication.process.ProcessDesigner["lp."+o2.language] = MWF.xApplication.process.ProcessDesigner.LP