MWF.xApplication.process.ProcessDesigner.LP = {
    "title": "ຕົວແກ້ໄຂຂະບວນການ",
    "newProcess": "ສ້າງຂະບວນການ",

    "tools": "Tools",
    "unnamed": "ບໍ່ມີຊື່",
    "unknow": "ບໍ່ຮູ້",
    "unrealized": "ຄຸນສົມບັດນີ້ບໍ່ໄດ້ຖືກປະຕິບັດ",
    "activity": "ກິດຈະກໍາ",
    "route": "ເສັ້ນທາງ",
    "property": "ຊັບສິນ",
    "showJson": "ສະແດງ JSON",
    "all": "ທັງໝົດ",
    "showAdvanced": "ຄຸນສົມບັດຂັ້ນສູງ",

    "phone": "ໂທລະສັບ",
    "mail": "ເມວ",
    "selectScript": "ເລືອກເນື້ອໃນ: ",
    "condition": "ເງື່ອນໄຂ",
    "unCategory": "ບໍ່ຈັດປະເພດ",
    "ok": "ຕົກລົງ",
    "close": "ປິດ",
    "cancel": "ຍົກເລີກ",

    "notice": {
        "no_name": "ໃສ່ຊື່ຂະບວນການ",
        "save_success": "ຂະບວນການຖືກບັນທຶກສຳເລັດແລ້ວ!",
        "save_process": "ກະລຸນາບັນທຶກຂະບວນການກ່ອນ!",
        "one_begin": "ພຽງແຕ່ໜຶ່ງ \"begin\" ອະນຸຍາດໃຫ້ມີການເຄື່ອນໄຫວຕໍ່ຂະບວນການ",
        "deleteRoute": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບເສັ້ນທາງທີ່ເລືອກ?",
        "deleteRouteTitle": "ລົບການຢືນຢັນເສັ້ນທາງ",
        "deleteActivityTitle": "ລົບການຢືນຢັນການເຄື່ອນໄຫວ",
        "deleteActivity": "ການລົບການເຄື່ອນໄຫວຈະເປັນການລົບທຸກເສັ້ນທາງທີ່ກ່ຽວຂ້ອງກັບການເຄື່ອນໄຫວນີ້，ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບການເຄື່ອນໄຫວທີ່ເລືອກ？",
        "saveRouteOrgNoName": "ຊື່ແລະຫົວຂໍ້ບໍ່ສາມາດຫວ່າງເປົ່າ",
        "saveRouteOrgNumberId": "ຕົວລະບຸບໍ່ສາມາດເປັນຕົວເລກບໍລິສຸດ",
        "saveRouteOrgDoubleDotId": "ລະຫັດ ບໍ່ສາມາດມີສອງຈຸດຕິດຕໍ່ກັນ",
        "processCopyError": "ການວາງການເຄື່ອນໄຫວລົ້ມເຫລວ, ກະລຸນາສຳເນົາອີກຄັ້ງແລ້ວລອງໃໝ່ອີກຄັ້ງ",
        "routeNameConfilct": "ກິດຈະກໍາບໍ່ສາມາດມີສອງເສັ້ນທາງທີ່ມີຊື່ດຽວກັນ!"
    },
    "menu": {
        "newRoute": "ສ້າງເສັ້ນທາງ",
        "newActivity": "ສ້າງກິດຈະກຳ",
        "newActivityType": {
            "manual": "ສ້າງກິດຈະກຳ",
            "condition": "ເງື່ອນໄຂ",
            "auto": "ອັດຕະໂນມັດ",
            "split": "ແຍກ",
            "merge": "ລວມ",
            "embed": "ຂະບວນການ",
            "invoke": "ບໍລິການ",
            "service": "ບໍລິການກິດຈະກຳ",
            "agent": "ຕົວແທນ",
            "delay": "delay",
            "publish": "ເຜີຍແຜ່",
            "message": "ຂໍ້ຄວາມ",
            "choice": "ທາງເລືອກ",
            "cancel": "ຍົກເລີກ",
            "begin": "ເລີ່ມຕົ້ນ",
            "end": "ສິ້ນສຸດ",
            "parallel": "ຂະໜານ"
        },

        "copyActivity": "ສຳເນົາ",

        "deleteActivity": "ລົບ",
        "deleteRoute": "ລົບເສັ້ນທາງ",

        "saveProcess": "ຂະບວນການບັນທຶກ",
        "saveProcessNew": "ບັນທຶກເປັນVersionໃໝ່",
        "checkProcess": "ຂະບວນການກວດສອບ",
        "exportProcess": "ຂະບວນການສົ່ງອອກ",
        "printProcess": "ຂະບວນການພິມ",

        "showGrid": "show grid",
        "hideGrid": "ເຊື່ອງgrid"
    },
    "intoScript": "ກົດທີ່ນີ້ເພື່ອຂຽນລະຫັດScript",
    "serialSelectTitle": "ຄຸນສົມບັດທາງເລືອກຈຳນວນ",
    "serialActivityTitle": "ປະຕິບັດກິດຈະກໍາການນັບເລກ",
    "delete": "ລົບ",
    "serialRule": "ກົດລະບຽບການນັບເລກ",
    "serialTextTitle": "ໃສ່ຂໍ້ຄວາມ",
    "serialDateTitle": "ເວລາ",
    "serialCreatedDateTitle": "ວັນທີຮ່າງ",
    "serialCurrentDateTitle": "ການນັບເລກເວລາ",
    "serialCreated": "ສະບັບຮ່າງ",
    "serialCurrent": "ຈໍານວນ",
    "serialAttributeTitle": "ໃສ່ຊື່ຄຸນສົມບັດ",
    "serialScriptTitle": "ກະລຸນາໃສ່ເນື້ອໃນ",
    "serialNumberLongTitle": "ຄວາມຍາວເລກລໍາດັບ",
    "serialNumberByTitle": "ຫມາຍເລກລຽງຕາມຊື່",
    "isSave": "ກຳລັງບັນທຶກ, ກະລຸນາລໍຖ້າ...",

    "dutyInputTitle": "ເພີ່ມພາລາມິເຕີໜ້າທີ່",
    "dutyInput": "ກະລຸນາເພີ່ມຈຳນວນ“{duty}”ພະນັກງານ",
    "creatorCompany": "ບໍລິສັດສ້າງຮ່າງ",
    "creatorDepartment": "ພະແນກຮ່າງ",
    "currentCompany": "ບໍລິສັດປະຈຸບັນ",
    "currentDepartment": "ພະແນກປະຈຸບັນ",
    "deleteDutyTitle": "ເອົາການຢືນຢັນໜ້າທີ່",
    "deleteDutyText": "ເຈົ້າຢືນຢັນວ່າຕ້ອງການລົບພະນັກງານ“{duty}”ອອກບໍ່？",
    "selectIcon": "ເລືອກ ICon",
    "centerServer": "ສູນກາງການບໍລິການ",

    "creatorUnit": "ຫນ່ວຍງານຂອງຜູ້ຂຽນ",
    "currentUnit": "ຄົນກຳເນີນງານຂອງອົງກອນ",
    "selectUnit": "ເລືອກອົງກອນ",
    "scriptUnit": "ເນື້ອໃນ",
    "preview": "ເບິ່ງຕົວຢ່າງ",
    "copy": "ຫນ່ວຍງານຂອງຜູ້ຂຽນ",

    "selectType": "ເລືອກປະເພດ",
    "identity": "ຕົວຕົນ",
    "unit": "ອົງກອນ",
    "selectCount": "ເລືອກຈຳນວນ",
    "deleteOrgConfirmTitle": "ລົບການຢືນຢັນການເລືອກ",
    "deleteOrgConfirmContent": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບການຕັ້ງຄ່າທີ່ເລືອກ?",

    "projectionTitle": "ສ້າງແຜນທີ່ຂໍ້ມູນທຸລະກິດ",
    "projectionActionNode_add": "ເພີ່ມລາຍການແຜນທີ່",
    "projectionActionNode_modify": "ແກ້ໄຂລາຍການແຜນທີ່",
    "projectionDataName": "ຊື່ຂໍ້ມູນ",
    "projectionPath": "ເສັ້ນທາງ",
    "projectionType": "ປະເພດ",
    "projectionName": "ຊື່",
    "projectionInputError": "ກະລຸນາໃສ່ຊື່ຂໍ້ມູນ ແລະເສັ້ນທາງຂໍ້ມູນ",
    "projectionTypeCountError": "{type}ລາຍການປະເພດຂໍ້ມູນ, ອະນຸຍາດສູງສຸດ {count}.",
    "projectionSameNameError": "ຊື່ຂໍ້ມູນດຽວກັນມີຢູ່ແລ້ວ",
    "projectionDeleteItemTitle": "ລົບການຢືນຢັນແຜນທີ່",
    "projectionDeleteItem": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບຂໍ້ມູນແຜນທີ່ຊື່ '{name}' ແລະເສັ້ນທາງ '{path}'?",
    "projectionRunActionNode": "ດໍາເນີນແຜນທີ່ຂໍ້ມູນທັນທີ",
    "projectionRunTitle": "ດໍາເນີນແຜນທີ່ຂໍ້ມູນທັນທີ",
    "projectionRunText": "ປະຕິບັດການຢືນຢັນແຜນທີ່",
    "projectionRunSuccess": "ແຜນທີ່ຂໍ້ມູນໄດ້ຖືກປະຕິບັດແລ້ວ",
    "projectionRunError": "ບໍ່ຈຳເປັນຕ້ອງເຮັດແຜນທີ່ຂໍ້ມູນ",

    "enable": "ເປີດໃຊ້ງານ",
    "notEnable": "ບໍ່ໄດ້ເປີດໃຊ້ງານ",
    "currentEdition": "ສະບັບປະຈຸບັນ",
    "editionUpdate": "ດັດແກ້ຫຼ້າສຸດ",
    "editionDiscription": "ໃສ່ຄໍາອະທິບາຍສະບັບ",

    "upgradeConfirm": "ບັນທຶກການຢືນຢັນສະບັບໃໝ່",
    "upgradeInfor": "<div style='overflow: hidden; line-height: 26px'>ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການບັນທຶກຂະບວນການປັດຈຸບັນເປັນເວີຊັນໃໝ່?<br/>ເລືອກ\"ເປີດໃຊ້Versionໃໝ່\" ຫຼັງຈາກ ການບັນທຶກສຳເລັດແລ້ວ, Versionໃໝ່ຈະຖືກຕັ້ງເປັນVersionທີ່ເປີດໃຊ້ໄດ້.</div><div style='margin-top:10px'><input type='checkbox' checked>ເປີດໃຊ້ງານເວີຊັນໃໝ່</div>",
    "inputDiscription": "ກະລຸນາໃສ່ລາຍລະອຽດສະບັບກ່ອນ",

    "edition_list": {
        "editionList": "ເບິ່ງສະບັບຂະບວນການ",
        "number": "ໝາຍເລກລຸ້ນ",
        "update": "ເວລາອັບເດດ",
        "updatePerson": "ອັບເດດບຸກຄົນ",
        "description": "ລາຍລະອຽດ",
        "enabled": "ເປີດໃຊ້ງານ",
        "action": "ການກະທຳ",
        "yes": "ແມ່ນ",
        "no": "ບໍ່",
        "newProcess": "ຂະບວນການໃໝ່ຖືກສ້າງຂື້ນ.",
        "an": "ອັນ",

        "modifyProcess": "[ຂະບວນການ] ໄດ້ແກ້ໄຂຄຸນລັກສະນະ <b>\"{field}\"</b>, ຈາກ: <span style='color: #ff0000'>\"{old}\"</b> span>, ເຖິງ: <span style='color: #0000ff'>\"{new}\"</span>",
        "modifyActivity": "[ການເຄື່ອນໄຫວ] ໄດ້ແກ້ໄຂຄຸນສົມບັດການເຄື່ອນໄຫວ <b>\"{name}\"</b> <b>\"{field}\"</b> ຈາກ: <span style='color: # ff0000'>\"{old}\"</span>, ເຖິງ: <span style='color: #0000ff'>\"{new}\"</span>",
        "modifyActivity_addRoute": "[Routing] ເພີ່ມ <b>\"{name}\"</b> ເສັ້ນທາງການເຄື່ອນໄຫວ <b>\"{rname}\"</b>, ຊີ້ໄປທີ່ <span style='color: # 0000ff'> \"{Next}\"</span>",
        "modifyActivity_deleteRoute": "[ເສັ້ນທາງ] ລົບເສັ້ນທາງຂອງການເຄື່ອນໄຫວ <b>\"{name}\"</b> <b>\"{rname}\"</b>, ຊີ້ໄປທີ່ <span style='color : #ff0000'> \"{Next}\"</span>",
        "modifyActivity_modifyRouteNext": "[ເສັ້ນທາງ] ໄດ້ແກ້ໄຂເສັ້ນທາງຂອງການເຄື່ອນໄຫວ <b>\"{name}\"</b> <b>\"{rname}\"</b>, ຈາກຊີ້ໄປຫາ <span style=' color: #ff0000' >\"{oldnext}\"</span>, ດັດແກ້ເພື່ອຊີ້ໄປທີ່ <span style='color: #0000ff'>\"{newnext}\"</span>",
        "modifyActivity_modifyRouteField": "[ເສັ້ນທາງ] ແກ້ໄຂເສັ້ນທາງຂອງກິດຈະກໍາ <b>\"{name}\"</b> <b>\"{rname}\"</b>, attribute <b>\"{field }\"</b> ຈາກ: <span style='color: #ff0000'>\"{old}\"</span>, ແກ້ໄຂເປັນ: <span style='color: #0000ff'>\"{ໃໝ່ }\"</span>",

        "deleteActivity": "[ການເຄື່ອນໄຫວ] ລົບການເຄື່ອນໄຫວ<b style='color: #ff0000'>“{name}”</b>",
        "addActivity": "[ການເຄື່ອນໄຫວ] ເພີ່ມກິດຈະກໍາ<b style='color: #0000ff'>“{name}”</b>",
        "noDiffs": "ບໍ່ຕ່າງຫຍັງກັບລຸ້ນກ່ອນໜ້າ",
        "hasDiffs": "ຄວາມແຕກຕ່າງຈາກສະບັບກ່ອນໜ້າ:",

        "open": "ສະຫຼັບ",
        "enable": "ເປີດໃຊ້",
        "rollback": "ຍ້ອນກັບ",
        "override": "ລົບລ້າງ",
        "del": "ລົບ",

        "openInfor": "ບັນທຶກເວີຊັນທີ່ເປີດໃນປັດຈຸບັນ ແລະເປີດເວີຊັນ”{v}“。",
        "enableInfor": "ເປີດໃຊ້ຂະບວນການເວີຊັນ”{v}“",
        "rollbackInfor": "ມ້ວນການອອກແບບຂະບວນການກັບໄປເປັນເວີຊັນທີ່ເລືອກ, ທຸກລຸ້ນຫຼັງຈາກລຸ້ນທີ່ເລືອກຈະຖືກລົບ。",
        "overrideInfor": "ລົບລ້າງສະບັບປັດຈຸບັນດ້ວຍການອອກແບບຂອງລຸ້ນທີ່ເລືອກ。",
        "delInfor": "ລົບເວີຊັນຂະບວນການ”{v}“。",

        "enabledProcessTitle": "ເປີດໃຊ້ການຢືນຢັນຂະບວນການ",
        "enabledProcessInfor": "ຕັ້ງຂະບວນການປະຈຸບັນເປັນ“，ເວີຊັນຂະບວນການທີ່ເປີດໃຊ້ກ່ອນໜ້ານີ້ຈະຖືກຕັ້ງເປັນ“。<br><br>ຕົວຢ່າງຂະບວນການຢູ່ໃນການໄຫຼວຽນຂອງຈະບໍ່ໄດ້ຮັບຜົນກະທົບ, ແລະ ຂະບວນການຈະໄດ້ຮັບການເລີ່ມຕົ້ນໃນຄັ້ງຕໍ່ໄປ, ຕົວຢ່າງຂະບວນການຈະໄດ້ຮັບການສ້າງຕັ້ງຂຶ້ນກັບສະບັບຂະບວນການເປີດໃຊ້ງານ。<br><br>ທ່ານແນ່ໃຈວ່າທ່ານຕ້ອງການທີ່ຈະຕັ້ງຂະບວນການໃນປັດຈຸບັນເປັນ”ເປີດໃຊ້ງານ“？",

        "deleteEditionTitle": "ລົບການຢືນຢັນສະບັບ",
        "deleteEditionInfor": "ລົບເວີຊັນຂະບວນການທີ່ເລືອກ”{v}“，ແລະຍັງລົບຕົວຢ່າງການໄຫຼວຽນຂອງຂະບວນການເວີຊັນ ”{v}“。ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບເວີຊັນຂະບວນການ”{v}“？"
    },
    "selectorButton": {
        "ok": "OK",
        "cancel": "ຍົກເລີກ"
    },
    "orgEditor": {
        "addOption": "ເພີ່ມທາງເລືອກ",
        "modifyOption": "ແກ້ໄຂທາງເລືອກ",
        "conflictNotice": "ເສັ້ນທາງໄດ້ຖືກຕັ້ງຄ່າດ້ວຍຊື່ດຽວກັນ",
        "copyConfig": "ຄັດລອກການຕັ້ງຄ່າການຄັດເລືອກ"
    },
    "serial": {
        "text": ["ຂໍ້ຄວາມ", "ຂໍ້ຄວາມທີ່ມັກ"],
        "year": ["ປີ", "ປີຂອງເວລາຮ່າງ"],
        "month": ["ເດືອນ", "ເດືອນຂອງເວລາຮ່າງ"],
        "day": ["ວັນ", "ວັນເວລາຮ່າງ"],
        "unit": ["ອົງກອນ", "ຫນ່ວຍງານໂດຍກົງຂອງຜູ້ຂຽນ"],
        "unitAttribute": ["ຄຸນສົມບັດອົງກອນ", "ຄຸນລັກສະນະຂອງຫນ່ວຍງານໂດຍກົງຂອງຜູ້ຂຽນ"],
        "script": ["script", "script"],
        "number": ["ລໍາດັບ", "ເລກລໍາດັບ"]
    },
    "propertyTemplate": {
        "base": "ພື້ນຖານ",
        "event": "ເຫດການ",
        "html": "HTML",
        "json": "JSON",
        "person": "ບຸກຄົນ",
        "split": "ແຍກ",

        "apiDoc": "ຄິກທີ່ນີ້ເພື່ອເບິ່ງເອກະສານ API",

        "id": "ID",
        "name": "ຊື່",
        "alias": "ນາມແຝງ",
        "description": "ລາຍລະອຽດ",
        "creator": "ຜູ້ສ້າງ",
        "createTime": "ສ້າງເວລາ",
        "updater": "ອັບເດດ",
        "updateTime": "ເວລາອັບເດດ",
        "application": "ແອັບພລິເຄຊັນ",
        "icon": "icon",
        "type": "ປະເພດ",
        "form": "ແບບຟອມ",

        "routeAsOpinion": "ໃຊ້ຊື່ເສັ້ນທາງເປັນຄວາມຄິດເຫັນເລີ່ມຕົ້ນ",
        "yes": "ແມ່ນ",
        "no": "ບໍ່",
        "opinionInfo": "(ເລືອກ“ບໍ່”：ຄວາມຄິດເຫັນຈະຫວ່າງເປົ່າເມື່ອຄວາມຄິດເຫັນບໍ່ຖືກຕື່ມ)",
        "version": "ຮຸ່ນ",
        "versionName": "ຊື່ລຸ້ນ",
        "versionId": "Id ລຸ້ນ",
        "versionDescription": "ລາຍລະອຽດສະບັບ",

        "startup": "ການເລີ່ມຕົ້ນ",
        "startTerminal": "ເລີ່ມຕົ້ນ Terminal",
        "pcAndMobile": "PC ແລະມືຖື",
        "onlyPc": "PC ເທົ່ານັ້ນ",
        "none": "ບໍ່ມີ",
        "startMode": "ເລີ່ມຕົ້ນ  Mode",
        "instanceMode": "ຕົວຢ່າງ",
        "draftMode": "ຮ່າງ",
        "instanceModeInfo": "(ສ້າງຕົວຢ່າງຂະບວນການໂດຍກົງໃນເວລາສ້າງຂະບວນການໃຫມ່, ແລະສ້າງສິ່ງທີ່ຕ້ອງເຮັດສໍາລັບຜູ້ຮ່າງ)",
        "draftModeInfo": "(ເມື່ອສ້າງຂະບວນການໃຫມ່, ບໍ່ມີຕົວແບບຂະບວນການໃດຖືກສ້າງຂຶ້ນ, ບໍ່ມີສິ່ງທີ່ຕ້ອງເຮັດ, ເອກະສານສະບັບຮ່າງແມ່ນຖືກສ້າງຂຶ້ນ, ແລະຕົວຢ່າງຂະບວນການບໍ່ໄດ້ຖືກສ້າງຈົນກ່ວາການໂອນຍ້າຍ)",

        "checkDraft": "ກວດຮ່າງ",
        "checkDraftInfo": "(ເລືອກ“ແມ່ນ”：ຂະບວນການທີ່ບໍ່ໄດ້ບັນທຶກໄວ້ຈະບໍ່ຖືກຮັກສາໄວ້)",
        "power": "ອະນຸຍາດ",
        "stratIdentity": "ຄົນ Strat",
        "startUnit": "ອົງກອນເລີ່ມຕົ້ນ",
        "starGroup": "ກຸ່ມເລີ່ມຕົ້ນ",
        "manager": "ຜູ້ຈັດການ",
        "maintenanceIdentity": "ຜູ້ຮັກສາ",

        "number": "ຈໍານວນ",
        "numberActivity": "ກິດຈະກໍາຈໍານວນ",
        "trigger": "trigger",
        "arrivals": "ຂາເຂົ້າ",
        "submit": "ສົ່ງ",

        "aging": "ແກ່",
        "processTimeLimit": "ການຈຳກັດເວລາຂະບວນການ",
        "noLimit": "NoLimit",
        "specifyDuration": "SpecifyDuration",
        "byScript": "Script",
        "timeLimit": "ເວລາຈຳກັດ",
        "days": "ມື້",
        "hours": "ຊົ່ວໂມງ",
        "workTimeOnly": "ເວລາເຮັດວຽກເທົ່ານັ້ນ",
        "includeNoworkTime": "ລວມເວລາບໍ່ເຮັດວຽກ",
        "script": "script",
        "returnJson": "ກັບຄືນ JSON Object",
        "hourTimeout": "ໝົດເວລາຫຼັງຈາກສອງສາມຊົ່ວໂມງ",
        "hourWorkTimeout": "ໝົດເວລາຫຼັງຈາກສອງສາມຊົ່ວໂມງເຮັດວຽກ",
        "specifyTimeout": "ໝົດເວລາຫຼັງຈາກເວລາກຳນົດ",
        "oneOfThree": "ຫນຶ່ງໃນສາມ",

        "mapping": "ແຜນທີ່",
        "mappingData": "ຂໍ້ມູນແຜນທີ່",
        "dataName": "ຊື່",
        "dataPath": "ເສັ້ນທາງ",
        "dataType": "ປະເພດ",
        "mappingOnFlow": "ເຮັດແຜນທີ່ຂໍ້ມູນທຸກຄັ້ງຫຼັງຈາກການໄຫຼ",
        "mappingDataToTable": "ຕາຕະລາງການສອບຖາມແຜນທີ່",
        "mappingTableEnabled": "ເກັບຂໍ້ມູນໃນຕາຕະລາງສອບຖາມຫຼັງຈາກເຮັດວຽກສຳເລັດ",
        "queryTable": "ຕາຕະລາງ",

        "data": "ຂໍ້ມູນ",
        "dataTrace": "ການຕິດຕາມຂໍ້ມູນທຸລະກິດ",
        "dataTraceInfo": "ການເປີດໃຊ້ການຕິດຕາມຂໍ້ມູນທຸລະກິດສາມາດບັນທຶກທຸກການປ່ຽນແປງຂອງພາກສະຫນາມທຸລະກິດທີ່ກໍານົດ, ແລະທ່ານສາມາດຕັ້ງຄ່າເພື່ອເບິ່ງບັນທຶກການປ່ຽນແປງປະຫວັດສາດຂອງຂໍ້ມູນທຸລະກິດໃນການອອກແບບແບບຟອມ",
        "dataTraceInfo2": "",
        "dataTraceFields": "Trace Fields",
        "dataTraceDisabled": "ບໍ່ມີ",
        "dataTraceCustom": "ກຳນົດເອງ",
        "dataTraceAll": "ທັງຫມົດ",
        "dataTraceDisabledInfo": "ຢ່າຕິດຕາມຊ່ອງຂໍ້ມູນທຸລະກິດໃດໆ",
        "dataTraceCustomInfo": "ກໍານົດຂົງເຂດທຸລະກິດທີ່ຈະຕິດຕາມໃນການຕັ້ງຄ່າຕໍ່ໄປນີ້",
        "dataTraceAllInfo": "ຕິດຕາມຊ່ອງຂໍ້ມູນທຸລະກິດທັງໝົດ (ບໍ່ລວມຕາຕະລາງຂໍ້ມູນ, ແບບຂໍ້ມູນ ແລະຂໍ້ມູນປະເພດຂໍ້ຄວາມຍາວ (Lob))",
        "dataTraceFieldNames": "ຊື່ພາກສະຫນາມ",

        "allowReroute": "ອະນຸຍາດໃຫ້ປ່ຽນເສັ້ນທາງ",
        "allowRerouteTo": "ອະນຸຍາດໃຫ້ປ່ຽນເສັ້ນທາງມາທີ່ນີ້",

        "mergeLayerThreshold": "ຈໍານວນຂອງການລວມຊັ້ນ",
        "mergeLayerThreshold0": "ລວມຊັ້ນຫຼາຍເທົ່າທີ່ເປັນໄປໄດ້",
        "mergeLayerThreshold1": "ລວມຊັ້ນດຽວ",

        "reader": "ຜູ້ອ່ານ",
        "readerId": "ID ຜູ້ອ່ານ",
        "duty": "ຫນ້າທີ່",
        "processData": "ຂໍ້ມູນ",
        "reviewer": "ການທົບທວນຄືນ",
        "reviewerId": "ກວດສອບ ID",
        "unit": "ຫົວໜ່ວຍ",

        "participant": "ພາລະບົດບາດຂະບວນການ",
        "participant_creator": "ຜູ້ລິເລີ່ມ",
        "participant_activity": "ຜູ້ເຂົ້າຮ່ວມ",
        "participant_maintenance": "ຜູ້ຮັກສາ",
        "participant_none": "ບໍ່ມີ",

        "participant_creator_info": "ຕັ້ງຜູ້ລິເລີ່ມຂອງຕົວຢ່າງຂະບວນການເປັນຕົວຈັດການກິດຈະກໍາໃນປະຈຸບັນ",
        "participant_maintenance_info": "ຕັ້ງຜູ້ຮັກສາຂະບວນການເປັນຜູ້ຈັດການກິດຈະກໍາໃນປະຈຸບັນ",
        "participant_activity_info": "ຕັ້ງຕົວຈັດການກິດຈະກໍາທີ່ຕົວຈັດການຂະບວນການໄດ້ໂອນເປັນຕົວຈັດການກິດຈະກໍາໃນປະຈຸບັນ. ກະລຸນາເລືອກກິດຈະກໍາຂ້າງລຸ່ມນີ້",

        "splitScript": "Split Value Script",
        "embed": "ຝັງ",
        "selectProcess": "ເລືອກຂະບວນການ",
        "embedType": "ປະເພດຝັງ",
        "sync": "Sync",
        "async": "Async",
        "copyData": "ສຳເນົາຂໍ້ມູນ",
        "copyAttachment": "ສຳເນົາເອກະສານຄັດຕິດ",
        "startPerson": "ຜູ້ລິເລີ່ມ",
        "currentCreator": "ຜູ້ລິເລີ່ມຂະບວນການປະຈຸບັນ",
        "prevHandler": "ຜູ້ຈັດການກິດຈະກໍາທີ່ຜ່ານມາ",
        "specifyPerson": "ລະບຸຜູ້ລິເລີ່ມ",
        "personId": "ID ຜູ້ລິເລີ່ມ",
        "personScript": "Script ລິເລີ່ມ",
        "titleScript": "Title Script",
        "dataScript": "ຕົວຂຽນຂໍ້ມູນ",
        "getOldData": "ເອົາຂໍ້ມູນທຸລະກິດຂອງຂະບວນການຕົ້ນສະບັບ",
        "setNewData": "ກໍານົດຂໍ້ມູນທຸລະກິດຂອງຂະບວນການໃຫມ່",

        "timer": "ໂມງຈັບເວລາ",
        "timerType": "ປະເພດເຄື່ອງຈັບເວລາ",
        "delayTime": "ປະຕິບັດຫຼັງຈາກການຊັກຊ້າສອງສາມນາທີ",
        "specifyTime": "ກໍານົດຈຸດເວລາທີ່ຈະປະຕິບັດ",
        "specifyMinute": "ນາທີທີ່ລະບຸ",
        "specifyATime": "ເວລາທີ່ກໍານົດໄວ້",
        "specifyData": "ເສັ້ນທາງຂໍ້ມູນສະເພາະ",

        "invoke": "ເຊີນ",
        "protocol": "ພິທີການ",
        "invokeType": "ປະເພດການຮຽກຮ້ອງ",
        "wsdlAddr": "WSDL",
        "method": "ວິທີການ",
        "parameterScript": "Parameter Script",
        "addParameter": "ເພີ່ມ Parameter",
        "deleteParameter": "ລຶບ Parameter",
        "responseScript": "ສະຄຣິບຕອບ",

        "use": "ໃຊ້",
        "getJson": " ໄດ້ຮັບເນື້ອໃນການຕອບສະຫນອງ. ຖ້າເນື້ອຫາຕອບສະຫນອງເປັນສະຕຣິງໃນຮູບແບບ JSON, 'ວັດຖຸ JSON ຈະຖືກກັບຄືນໄປ; ຖ້າບໍ່ດັ່ງນັ້ນ', ເນື້ອຫາຕອບສະຫນອງຕົ້ນສະບັບແມ່ນກັບຄືນໄປບ່ອນ.",
        "systemRequest": "ການບໍລິການລະບົບ",
        "restAddr": "ທີ່ຢູ່ພັກຜ່ອນ ",
        "requestBodyScript": "Request Body Script",
        "setRequestBody": "Set Request Body",
        "requestHeaderScript": "Request Header Script",
        "addHeader": "ເພີ່ມຫົວ ",
        "delHeader": "Delete Header ",

        "setParameterInfo": "ກັບຄືນວັດຖຸ json ເພື່ອກໍານົດພາລາມິເຕີ, ກະລຸນາກວດເບິ່ງເອກະສານ API",
        "setParameterInfo2": "ກັບຄືນ array ເພື່ອກໍານົດພາລາມິເຕີ, ກະລຸນາກວດເບິ່ງເອກະສານ API",
        "setRequestBodyInfo": "ກັບຄືນວັດຖຸ json ເພື່ອກໍານົດເນື້ອໃນຂໍ້ຄວາມ, ກະລຸນາກວດເບິ່ງເອກະສານ API",
        "setHeaderInfo": "ກັບຄືນວັດຖຸ json ເພື່ອກໍານົດຫົວຂໍ້ຂໍ້ຄວາມ, ກະລຸນາກວດເບິ່ງເອກະສານ API",
        "getJaxws": "ໄດ້ຮັບເນື້ອຫາຕອບສະຫນອງ. ປະເພດການຕອບສະຫນອງແມ່ນຂຶ້ນກັບການກັບຄືນຂອງການບໍລິການ",

        "service": "ການບໍລິການ",
        "serviceResponseScript": "Scriptຕອບ",
        "responseInfo": "ເອົາຂໍ້ມູນການຮ້ອງຂໍຜ່ານ \this.request.getBody()\"<br/>ກັບຄືນຄວາມຈິງ",

        "runScript": "ປະຕິບັດ script",

        "processType": "ປະເພດຂະບວນການ",
        "oneProcess": "ຄົນຫນຶ່ງຈັບ",
        "single": "single",
        "sameTime": "ການປະມວນຜົນພ້ອມໆກັນໂດຍຄົນຫຼາຍຄົນ",
        "parallel": "ຂະຫນານ",
        "queue": "ຄິວ",
        "queueInfo": "ຫລາຍຄົນໃນລໍາດັບ",
        "grab": "grab",
        "grabInfo": "ໃຜເປີດວຽກກ່ອນຈະຈັດການ",
        "readForUntreated": "ສົ່ງອ່ານໃຫ້ຜູ້ທີ່ບໍ່ໄດ້ຮັບການປິ່ນປົວ",

        "mergeTask": "ລວມວຽກງານ",
        "mergeTaskInfo": "(ຖ້າທ່ານເລືອກ \"Yes\", the task on this activity with the same identity will be merged)",

        "mergeTaskProcess": "ການປຸງແຕ່ງວຽກງານລວມ",
        "mergeTaskProcessInfo": "(ຖ້າທ່ານເລືອກ \"Yes\", when the same person's different identities generate multiple to-dos in this activity, they only need to be processed once)",

        "activityGroup": "ກຸ່ມກິດຈະກໍາ",
        "opinionGroup": "ກຸ່ມຄວາມຄິດເຫັນ",
        "taskPerson": "ວຽກງານ",
        "customData": "ຄຸນສົມບັດທີ່ກໍາຫນົດເອງ",
        "identity": "ຕົວຕົນ",
        "group": "ກຸ່ມ",
        "readGroup": "ກຸ່ມ",
        "reviewGroup": "ກຸ່ມ",
        "specifyTimeoutTime": "ກໍານົດໄລຍະເວລາຫມົດເວລາທີ່ກໍານົດໄວ້",
        "setTimeoutAfterHours": "ກໍານົດເວລາຫມົດເວລາຫຼັງຈາກສອງສາມຊົ່ວໂມງ",
        "setTimeoutAfterWorkHours": "ກໍານົດເວລາຫມົດເວລາຫຼັງຈາກສອງສາມຊົ່ວໂມງເຮັດວຽກ",
        "activityPower": "ພະລັງງານ",
        "allowDelete": "ອະນຸຍາດໃຫ້ລຶບ",
        "allowReset": "ອະນຸຍາດໃຫ້Reset",
        "resetCount": "ຕັ້ງຄ່າຈຳນວນໃໝ່",
        "resetRange": "ປັບໄລຍະ",
        "everyOne": "ໃຜ",
        "directUnit": "ຫົວຫນ່ວຍຂອງຂ້ອຍ",
        "topUnit": "ຫົວຫນ່ວຍສູງສຸດ",
        "allowRetract": "ອະນຸຍາດໃຫ້ຖອນຄືນ",
        "allowRapid": "ອະນຸຍາດໃຫ້ຈັດການກັບຢ່າງໄວວາ",
        "allowAddSplit": "ອະນຸຍາດໃຫ້ເພີ່ມການແບ່ງປັນ",
        "allowRollback": "ອະນຸຍາດໃຫ້ກັບຄືນ",
        "allowPress": "ອະນຸຍາດໃຫ້ກົດ",
        "allowPause": "ອະນຸຍາດໃຫ້ຢຸດຊົ່ວຄາວ",
        "allowAddTask": "ອະນຸຍາດໃຫ້ເພີ່ມໜ້າວຽກ",

        "backConfig": "ການຕັ້ງຄ່າກັບຄືນໄປບ່ອນ",
        "allowBack": "ອະນຸຍາດໃຫ້ກັບຄືນ",
        "multiTaskEnable": "ອະນຸຍາດໃຫ້ກັບຄືນເມື່ອຫຼາຍໜ້າວຽກ",
        "multiTaskEnableInfo": "ການປະຕິບັດຜົນຕອບແທນເມື່ອການປະມວນຜົນຫຼາຍຄົນຈະຍົກເລີກສິ່ງທີ່ຕ້ອງເຮັດຂອງຄົນອື່ນໆທີ່ຍັງບໍ່ໄດ້ປະມວນຜົນ ແລະກັບຄືນໂດຍກົງກັບກິດຈະກໍາທີ່ລະບຸ",
        "backType": "ປະເພດກັບຄືນໄປບ່ອນ",
        "backPrev": "ກັບຄືນກິດຈະກໍາທີ່ຜ່ານມາ",
        "backAny": "ກິດຈະກໍາໃດກໍ່ຕາມ",
        "backDefine": "ເລືອກກິດຈະກໍາກັບຄືນ",
        "backPrevInfo": "ຜົນຕອບແທນລະດັບໂດຍລະດັບ: ຜູ້ໃຊ້ເລືອກ ກັບຄືນ",
        "backAnyInfo": "ກັບຄືນກິດຈະກໍາໃດນຶ່ງ: ເມື່ອຜູ້ໃຊ້ເລືອກ ກັບຄືນ",
        "backDefineInfo": "ເລືອກກິດຈະກໍາກັບຄືນ: ກໍານົດກິດຈະກໍາທີ່ອະນຸຍາດໃຫ້ກັບຄືນ, ໃຊ້ເພື່ອກັບຄືນໄປຫາກິດຈະກໍາທີ່ອະນຸຍາດ",
        "backWay": "ຂະບວນການຫຼັງຈາກກັບຄືນ",
        "backWayDefault": "ຄ່າເລີ່ມຕົ້ນ",
        "backWayStep": "ການໄຫຼປົກກະຕິຕາມການຕັ້ງຄ່າຂະບວນການ",
        "backWayJump": "ກັບໄປກົງກັບ bouncer",
        "backWayCustom": "BackWayCustom",
        "backActivitySelectTitle": "ເລືອກກິດຈະກຳທີ່ສາມາດຕີກັບໄດ້",
        "backActivitySelectInfo": "ທ່ານສາມາດເລືອກກິດຈະກຳທີ່ອະນຸຍາດໃຫ້ສົ່ງກັບກິດຈະກຳປະຈຸບັນ，ອະນຸຍາດໃຫ້ກິດຈະກຳທີ່ໂອນແລ້ວສາມາດສົ່ງກັບໄດ້ເທົ່ານັ້ນ，ທີ່ຈະສົ່ງກັບ。ເຈົ້າສາມາດຕັ້ງຄ່າດຳເນີນການຫຼັງຈາກສົ່ງກັບເອກສານອື່ນທີ່ໄດ້ຮັບອະນຸຍາດສົ່ງກັບ。",


        "beforeBegin": "ກ່ອນທີ່ຂະບວນການຈະເລີ່ມຕົ້ນ",
        "eventInfo1": "ເລີ່ມຂະບວນການເພື່ອສ້າງ work",
        "afterBegin": "ຫຼັງຈາກການເລີ່ມຕົ້ນ",
        "beforeArrive": "ກ່ອນມາຮອດ",
        "eventInfo2": "ປະຕິບັດການມາຮອດ, ຕັ້ງຄຸນລັກສະນະການເຄື່ອນໄຫວ",
        "afterArrive": "ຫຼັງຈາກມາຮອດ",
        "beforeExecute": "ກ່ອນທີ່ຈະປະຕິບັດ",
        "eventInfo3": "ປະຕິບັດການດໍາເນີນການ, ປະຕິບັດວຽກງານກິດຈະກໍາອັດຕະໂນມັດ",
        "afterExecute": "ຫຼັງຈາກການປະຕິບັດ",
        "beforeInquire": "ກ່ອນທີ່ຈະສອບຖາມ",
        "eventInfo4": "ປະຕິບັດການສອບຖາມເພື່ອສອບຖາມເສັ້ນທາງໄປຫາກິດຈະກໍາຕໍ່ໄປ",
        "afterInquire": "ຫຼັງການສອບຖາມ",
        "beforeEnd": "ກ່ອນສິ້ນສຸດ",
        "eventInfo5": "ສິ້ນສຸດຂະບວນການແລະສ້າງວຽກສໍາເລັດ",
        "afterEnd": "ຫຼັງຈາກສິ້ນສຸດ",
        "beforeWorkArrive": "ກ່ອນວຽກມາຮອດ",
        "beforeArriveActivity": "ກ່ອນທີ່ຈະມາຮອດ",
        "afterArriveActivity": "ຫຼັງຈາກມາຮອດ",
        "eventInfo6": "ປະຕິບັດການມາຮອດ, ກໍານົດຄຸນລັກສະນະກິດຈະກໍາ, ຄິດໄລ່ເຈົ້າຂອງກິດຈະກໍາທີ່ເປັນໄປໄດ້",
        "eventInfo7": "ດຳເນີນການ \"ປະຕິບັດ\", ສ້າງໜ້າວຽກ",
        "manualStay": "ການຢູ່ດ້ວຍຕົນເອງ",
        "eventInfo8": "ວຽກງານການໄຫຼ",
        "manualBeforeTask": "ຄູ່ມືກ່ອນຫນ້າວຽກ",
        "eventInfo9": "ດຳເນີນວຽກງານ, ສ້າງວຽກໃຫ້ສຳເລັດ",
        "manualAfterTask": "ຄູ່ມືຫຼັງຈາກ Task",
        "eventInfo10": "ກໍານົດວ່າເງື່ອນໄຂແມ່ນບັນລຸໄດ້ຫຼືບໍ່ແລະເຂົ້າໄປໃນກິດຈະກໍາຕໍ່ໄປ",

        "eventInfo11": "ປະຕິບັດວຽກງານການໄຫຼຂອງຂະບວນການທັງໝົດຈົນກວ່າຈະຢູ່ ຫຼືສິ້ນສຸດໃນກິດຈະກໍາ",
        "afterProcess": "ການເຄື່ອນໄຫວສຳເລັດ",

        "updataTime": "ອັບເດດຂໍ້ມູນ",
        "num": "ເລກລໍາດັບ",
        "defaultOpinion": "ຄວາມຄິດເຫັນເລີ່ມຕົ້ນ",
        "opinionRequired": "ຄວາມເຫັນທີ່ຕ້ອງການ",
        "routeType": "ປະເພດເສັ້ນທາງ",
        "defaultRoute": "ເສັ້ນທາງເລີ່ມຕົ້ນ",
        "backRoute": "ເສັ້ນທາງກັບຄືນ",
        "appendTask": "ເພີ່ມໜ້າວຽກ (ຕ້ອງຊີ້ໃຫ້ເຫັນກິດຈະກໍາດຽວກັນ)",
        "appendTaskInfo": "ເພີ່ມໜ້າວຽກ ບໍ່ໄດ້ກະຕຸ້ນເຫດການກິດຈະກໍາ",
        "appendTo": "ຕື່ມໃສ່",
        "byRoute": "ໂດຍເສັ້ນທາງ",
        "appendToScript": "ຕື່ມໃສ່ ເນື້ອໃນ",
        "asyncReturn": "Async ກັບຄືນ",
        "expand": "ຂະຫຍາຍ",
        "decisionGroup": "ກຸ່ມການຕັດສິນໃຈ",
        "decisionGroupInfo": "ແຍກກຸ່ມການຕັດສິນໃຈຫຼາຍອັນດ້ວຍ # ເຄື່ອງໝາຍ, ແລະເພີ່ມຈຳນວນເຕັມກ່ອນຊື່ສຳລັບຄ່າຈັດຮຽງ. ເຊັ່ນ: \"1agree#2disagree\"",
        "prefRouting": "ການສົ່ງເສີມການນໍາທາງ",
        "routeNow": "ເສັ້ນທາງທັນທີ",
        "routeNowInfo": "(ເມື່ອທ່ານເລືອກ \"ແມ່ນ\", ຕາບໃດທີ່ທ່ານເລືອກເສັ້ນທາງນີ້ໃນການປະມວນຜົນຫຼາຍຄົນ, ເອກະສານຈະຖືກໂອນທັນທີຕາມເສັ້ນທາງນີ້)",
        "autoFlowTime": "ໄຫຼອັດຕະໂນມັດເມື່ອໝົດເວລາການເຄື່ອນໄຫວ",
        "autoFlowPerson": "ໄຫຼອັດຕະໂນມັດເມື່ອຕົວຈັດການແມ່ນຄືກັນກັບການເຄື່ອນໄຫວທີ່ຜ່ານມາ",
        "routeCheck": "ການຢັ້ງຢືນເສັ້ນທາງ",
        "routeCheckInfo": "(ກັບຄືນ ຄວາມຈິງທີ່ຈະຜ່ານ, ກັບຄືນສະຕຣິງເພື່ອສະແດງຂໍ້ຜິດພາດ)",
        "showName": "ສະແດງຊື່",
        "hideCondition": "ເຊື່ອງເງື່ອນໄຂ",
        "hideConditionInfo": "(ກັບຄືນຄວາມຈິງເພື່ອຊ່ອນ)",
        "select": "ເລືອກ",

        "title": "ຫົວຂໍ້",
        "titleInfo": "ເຊັ່ນ: ກະລຸນາເລືອກຜູ້ຈັດການພະແນກ",
        "defaultValue": "ຄ່າເລີ່ມຕົ້ນ",
        "defaultValueScript": "ສະຄຣິບຄ່າເລີ່ມຕົ້ນ",
        "checkCount": "ນັບ",
        "checkCountInfo": "ຈໍານວນຂອງທາງເລືອກແມ່ນບໍ່ຫນ້ອຍກວ່າ",
        "verificationScript": "ສະຄຣິບຢັ້ງຢືນ",
        "unitSelectConfig": "ກຳນົດຄ່າການເລື່ອກໜ່ວຍ",
        "selectType": "ເລືອກປະເພດ",
        "personIdentity": "ເອກະລັກ",
        "selectCount": "ເລືອກນັບ",
        "checkEmpower": "ກວດສອບອຳນາດ",
        "onlyCustom": "ໃຊ້ທາງເລືອກທີ່ກຳນົດເອງເທົ່ານັ້ນ",
        "unitRange": "ລະດັບຫົວໜ່ວຍ",
        "allUnit": "ຫນ່ວຍງານທັງໝົດ",
        "specifyUnit": "ລະບຸຫົວໜ່ວຍ",
        "draftUnit": "ຫນ່ວຍງານຂອງຜູ້ຮ່າງ",
        "CurrentUnit": "ຫນ່ວຍງານຂອງຄົນປະຈຸບັນ",
        "inUnit": "ອົງການທີ່ກ່ຽວຂ້ອງໂດຍກົງ",
        "levelIs": "ໄດ້",
        "levelUnit": "ຫນ່ວຍງານລະດັບ",
        "unitTypeIs": "ປະເພດຫົວໜ່ວຍແມ່ນ",
        "deUnit": "",
        "expandNext": "ຂະຫຍາຍລະດັບຕໍ່າກວ່າ",
        "selectUnit": "ເລືອກຫົວໜ່ວຍ",
        "formData": "ຂໍ້ມູນແບບຟອມ",
        "dutyRange": "ຂອບເຂດໜ້າທີ່",
        "all": "ທັງໝົດ",
        "all2": "ທັງໝົດ",
        "specifyDuty": "ລະບຸໜ້າທີ່",
        "category": "ໝວດໝູ່",
        "byUnit": "ໂດຍຫົວໜ່ວຍ",
        "byDuty": "ໂດຍໜ້າທີ່",
        "showLevel": "ສະແດງລະດັບ",
        "byDutyUnit": "ໂດຍໜ່ວຍງານຂອງໜ້າທີ່",
        "byIdentityUnit": "ໂດຍຫົວໜ່ວຍຂອງຕົວຕົນ",
        "selectDuty": "ເລືອກໜ້າທີ່",
        "CustomOption": "ຕົວເລືອກທີ່ກໍາຫນົດເອງ",
        "useScriptAddId": "ໃຊ້ເນື້ອໃນເພື່ອເພີ່ມຕົວຕົນ",
        "unitType": "ປະເພດຫົວໜ່ວຍ",
        "exclude": "ຍົກເວັ້ນ",
        "excludeInfo": "ຍົກເວັ້ນການເລືອກຫົວໜ່ວຍ, ຕົວຕົນ, ຄົນ ແລະກຸ່ມຕາມສະຄຣິບ",
        "firstLevelSelectable": "ອະນຸຍາດໃຫ້ເລືອກອັນທຳອິດ",
        "dataStructure": "ໂຄງສ້າງຂໍ້ມູນ",
        "complete": "ສົມບູນ",
        "simple": "ງ່າຍດາຍ",

        "section": "section",
        "enableSection": "ເປີດໃຊ້section",
        "sectionBy": "ຕົວຈັດການ",
        "handlerUnit": "ຫນ່ວຍງານຈັດການ",
        "activityId": "ID ການເຄື່ອນໄຫວ",
        "splitValue": "ຄ່າແຍກ",

        "publish": "ເຜີຍແຜ່",
        "publishTarget": "ເຜີຍແຜ່ເປົ້າໝາຍ",
        "cms": "ການຈັດການເນື້ອຫາ",
        "table": "ຕາຕະລາງຂໍ້ມູນ",
        "cmsCategory": "ໝວດການຄຸ້ມຄອງເນື້ອຫາ",
        "selectCmsCategory": "ເລືອກໝວດໝູ່",
        "categoryDataPath": "ເສັ້ນທາງຂໍ້ມູນຫມວດຫມູ່",
        "sendNotify": "ຂໍ້ຄວາມຂະບວນການກະຕຸ້ນຂໍ້ຄວາມ",
        "readerFields": "ຊ່ອງຜູ້ອ່ານ",
        "authorFields": "ຂົງເຂດຜູ້ຂຽນ",
        "pictureFields": "ຮູບພາບຫນ້າທໍາອິດທົ່ງນາ",
        "useProcessForm": "ໃຊ້ແບບຟອມຂະບວນການ",
        "titleField": "ຊ່ອງຂໍ້ມູນ",
        "useProcessFormNote": "ໝາຍເຫດ：ຖ້າແມ່ນກ່ອນ，ຈາກນັ້ນເອກະສານເຜີຍແຜ່ໄປຍັງການຈັດການເນື້ອຫາຈະຖືກເປີດໂຍໃຊ້ແບບຟອມຂະບວນການ，ບໍ່ສະນັ້ນແບບຟອມຈະຖືກເປີດຂຶ້ນໂດຍໃຊ້ການຕັ້ງຄ່າໝວດໝູ່ການຈັດການເນື້ອຫາ。",
        "setNewPublishData": "ສົ່ງຄືນjsonເພື່ອການຕັ້ງຄ່າຂໍ້ມູນ，ກະລຸນກວດສອບເອກະສານAPI。ເຊັ່ນ",

        "querytable": "ຕາຕະລາງຂໍ້ມູນ",
        "querytableActionNode_add": "↑ ຕື່ມຂໍ້ມູນກຳນົດຄ່າ data table ↑",
        "querytableActionNode_modify": "↑ ແກ້ໄຂການກຳນົດຄ່າ data table ↑",
        "querytableInputError": "ກະລຸນາເລືອກ data table",
        "queryTableAssignDataScriptError": "Data script ບໍ່ສາມາດເວັ້ນວ່າງໄດ້",
        "querytableDeleteItemTitle": "ຢືນຢັນລົບລາຍການກຳນົດຄ່າປະຈຸບັນ",
        "querytableDeleteItem": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບລາຍການກຳນົດຄ່າປະຈຸບັນ？",
        "queryTableDataBy": "ຄ່າ",
        "byDataPath": "DataPath",
        "byDataScript": "DataScript",
        "publishTableConfig": "ການກຳນົດຄ່າ",
        "queryTableDataPathNote": "ໝາຍເຫດ：root pathວ່າງເປົ່າ，ຕື່ມແບຟອມຂໍ້ມູນລະບຸຕົວຕົນແບບຟ້ອມຂໍ້ມູນ.data（如datatable1.data），ຂໍ້ມູນ templateຕື່ມຈໍ້ມູນລະບົບtemplateຂໍ້ມູນ（ເຊັ່ນ datatemplate1）。",
        "orgIdPlaceholder": "ເຊັ່ນ：departmentLeader"
    }
};
		