MWF.xApplication.process.ProcessDesigner.LP = {
	"title": "流程编辑",
	"newProcess": "新流程",

    "tools": "工具",
	"unnamed": "未命名",	
	"unknow": "未知",
	"unrealized": "此功能未实现",
	"activity": "活动",
	"route": "路由",
	"property": "属性",
	"showJson": "查看JSON",
	"all" : "全部",

    "phone": "手机",
    "mail": "邮件",
    "selectScript": "点击选择脚本: ",
    "condition": "条件",
    "unCategory": "未分类",

	"notice":{
        "no_name": "请先输入流程名称",
		"save_success": "流程保存成功!",
		"one_begin": "每个流程只允许有一个“开始”活动",
		"deleteRoute": "您确定要删除选中的路由吗？",
		"deleteRouteTitle": "删除路由确认",
		"deleteActivityTitle": "删除活动确认",
		"deleteActivity": "删除活动将同时删除关联此活动的所有路由，您确定要删除选中的活动吗？",
		"saveRouteOrgNoName" : "名称和标题不能为空",
		"processCopyError": "活动粘贴失败，请重新复制后重试"
	},
	"menu": {
		"newRoute": "新建路由",
		"newActivity": "新建活动",
		"newActivityType": {
			"manual": "人工活动",
			"condition": "条件活动",
			"auto": "自动活动",
			"split": "拆分活动",
			"merge": "合并活动",
			"embed": "子流程活动",
			"invoke": "调用活动",
			"begin": "开始活动",
			"end": "结束活动"
		},
		
		"copyActivity": "复制活动",
		
		"deleteActivity": "删除活动",
		"deleteRoute": "删除路由",
		
		"saveProcess": "保存流程",
		"saveProcessNew": "保存为新版本",
		"checkProcess": "检查流程",
		"exportProcess": "导出流程",
		"printProcess": "打印流程",
		
		"showGrid": "显示网格",
		"hideGrid": "隐藏网格"
	},
    "intoScript": "点击此处，编写脚本代码",
    "serialSelectTitle": "编号可选属性",
    "serialActivityTitle": "执行编号活动",
    "delete": "删除",
    "serialRule": "编号规则",
    "serialTextTitle": "输入文本",
    "serialDateTitle": "时间",
    "serialCreatedDateTitle": "拟稿时间",
    "serialCurrentDateTitle": "编号时间",
    "serialCreated": "拟稿",
    "serialCurrent": "编号",
    "serialAttributeTitle": "输入属性名称",
    "serialScriptTitle": "请输入脚本",
    "serialNumberLongTitle": "流水号长度",
    "serialNumberByTitle": "流水号依据",
    "isSave": "正在保存，请稍候...",

    "dutyInputTitle": "添加职务参数",
    "dutyInput": "请为职务“{duty}”添加参数",
    "creatorCompany": "拟稿公司",
    "creatorDepartment": "拟稿部门",
    "currentCompany": "当前公司",
    "currentDepartment": "当前部门",
    "deleteDutyTitle": "移除职务确认",
    "deleteDutyText": "您确认要移除职务“{duty}”吗？",
    "selectIcon": "选择图标",

    "creatorUnit": "拟稿人所在组织",
    "currentUnit": "处理人所在组织",
    "selectUnit": "选择组织",
    "scriptUnit": "使用脚本",
	"preview" : "预览",
	"copy" : "从其他设置拷贝",

	"selectType" : "选择类型",
	"identity" : "身份",
	"unit" : "组织",
	"selectCount" : "选择数量",
	"deleteOrgConfirmTitle" : "删除选择确认",
	"deleteOrgConfirmContent" : "确定要删除该选择配置？",

	"projectionTitle": "映射业务数据",
	"projectionActionNode_add": "添加映射条目",
	"projectionActionNode_modify": "修改映射条目",
	"projectionDataName": "数据名称",
	"projectionPath": "数据路径",
	"projectionType":"数据类型",
	"projectionInputError": "请输入数据名称和数据路径",
	"projectionTypeCountError": "{type}类型的数据映射条目，最多允许{count}条。",
	"projectionSameNameError": "相同的数据名称已存在",
	"projectionDeleteItemTitle": "删除数据映射条目确认",
	"projectionDeleteItem": "您确定要删除名为“{name}”，路径为“{path}”的数据映射条目吗？",
	"projectionRunActionNode": "立即运行数据映射",
	"projectionRunTitle": "立即执行确认",
	"projectionRunText": "请确认立即执行数据映射",
	"projectionRunSuccess": "数据映射已开始执行",
	"projectionRunError": "不需要执行数据映射"
};