MWF.xApplication.process.ProcessDesigner.LP = {
	"title": "流程编辑",
	"newProcess": "新流程",

    "tools": "工具",
	"unnamed": "未命名",	
	"unknow": "未知",
	"unrealized": "此功能未实现",
	"activity": "活动",
	"route": "路由",
	"property": "属性",
	"showJson": "查看JSON",
	"all" : "全部",
	"showAdvanced": "显示高级属性",

    "phone": "手机",
    "mail": "邮件",
    "selectScript": "点击选择脚本: ",
    "condition": "条件",
    "unCategory": "未分类",
	"ok": "确定",
	"close": "关闭",
	"cancel": "取消",

	"notice":{
        "no_name": "请先输入流程名称",
		"save_success": "流程保存成功!",
		"save_process": "请先保存流程!",
		"one_begin": "每个流程只允许有一个“开始”活动",
		"deleteRoute": "您确定要删除选中的路由吗？",
		"deleteRouteTitle": "删除路由确认",
		"deleteActivityTitle": "删除活动确认",
		"deleteActivity": "删除活动将同时删除关联此活动的所有路由，您确定要删除选中的活动吗？",
		"saveRouteOrgNoName" : "名称和标题不能为空",
		"processCopyError": "活动粘贴失败，请重新复制后重试"
	},
	"menu": {
		"newRoute": "新建路由",
		"newActivity": "新建活动",
		"newActivityType": {
			"manual": "人工活动",
			"condition": "条件活动",
			"auto": "自动活动",
			"split": "拆分活动",
			"merge": "合并活动",
			"embed": "子流程活动",
			"invoke": "调用活动",
			"service": "服务活动",
			"agent": "脚本活动",
			"delay": "定时活动",
			"message": "消息活动",
			"choice": "选择活动",
			"cancel": "取消活动",
			"begin": "开始活动",
			"end": "结束活动",
			"parallel": "并行活动"
		},
		
		"copyActivity": "复制活动",
		
		"deleteActivity": "删除活动",
		"deleteRoute": "删除路由",
		
		"saveProcess": "保存流程",
		"saveProcessNew": "保存为新版本",
		"checkProcess": "检查流程",
		"exportProcess": "导出流程",
		"printProcess": "打印流程",
		
		"showGrid": "显示网格",
		"hideGrid": "隐藏网格"
	},
    "intoScript": "点击此处，编写脚本代码",
    "serialSelectTitle": "编号可选属性",
    "serialActivityTitle": "执行编号活动",
    "delete": "删除",
    "serialRule": "编号规则",
    "serialTextTitle": "输入文本",
    "serialDateTitle": "时间",
    "serialCreatedDateTitle": "拟稿时间",
    "serialCurrentDateTitle": "编号时间",
    "serialCreated": "拟稿",
    "serialCurrent": "编号",
    "serialAttributeTitle": "输入属性名称",
    "serialScriptTitle": "请输入脚本",
    "serialNumberLongTitle": "流水号长度",
    "serialNumberByTitle": "流水号依据",
    "isSave": "正在保存，请稍候...",

    "dutyInputTitle": "添加职务参数",
    "dutyInput": "请为职务“{duty}”添加参数",
    "creatorCompany": "拟稿公司",
    "creatorDepartment": "拟稿部门",
    "currentCompany": "当前公司",
    "currentDepartment": "当前部门",
    "deleteDutyTitle": "移除职务确认",
    "deleteDutyText": "您确认要移除职务“{duty}”吗？",
    "selectIcon": "选择图标",

    "creatorUnit": "拟稿人所在组织",
    "currentUnit": "处理人所在组织",
    "selectUnit": "选择组织",
    "scriptUnit": "使用脚本",
	"preview" : "预览",
	"copy" : "从其他设置拷贝",

	"selectType" : "选择类型",
	"identity" : "身份",
	"unit" : "组织",
	"selectCount" : "选择数量",
	"deleteOrgConfirmTitle" : "删除选择确认",
	"deleteOrgConfirmContent" : "确定要删除该选择配置？",

	"projectionTitle": "映射业务数据",
	"projectionActionNode_add": "添加映射条目",
	"projectionActionNode_modify": "修改映射条目",
	"projectionDataName": "数据名称",
	"projectionPath": "数据路径",
	"projectionType":"数据类型",
	"projectionInputError": "请输入数据名称和数据路径",
	"projectionTypeCountError": "{type}类型的数据映射条目，最多允许{count}条。",
	"projectionSameNameError": "相同的数据名称已存在",
	"projectionDeleteItemTitle": "删除数据映射条目确认",
	"projectionDeleteItem": "您确定要删除名为“{name}”，路径为“{path}”的数据映射条目吗？",
	"projectionRunActionNode": "立即运行数据映射",
	"projectionRunTitle": "立即执行确认",
	"projectionRunText": "请确认立即执行数据映射",
	"projectionRunSuccess": "数据映射已开始执行",
	"projectionRunError": "不需要执行数据映射",

	"enable": "已启用",
	"notEnable": "未启用",
	"currentEdition": "当前版本",
	"editionUpdate": "最后修改",
	"editionDiscription":"请输入版本描述",

	"upgradeConfirm": "保存为新版本确认",
	"upgradeInfor": "<div style='overflow: hidden; line-height: 26px'>您是否确定要将当前流程保存为新版?<br/>选中\"同时启用新版本\"在保存完成之后,会将新版本设置为启用版本.</div><div style='margin-top:10px'><input type='checkbox' checked>同时启用新版本</div>",
	"inputDiscription": "请先输入版本描述",

	"edition_list":{
		"editionList": "查看流程版本",
		"number": "版本号",
		"update": "更新时间",
		"updatePerson": "更新人",
		"description": "版本描述",
		"enabled": "启用",
		"action": "操作",
		"yes": "是",
		"no": "否",
		"newProcess": "创建了新的流程。",
		"an": "个",

		"modifyProcess": "[流程] 修改了流程的属性 <b>\"{field}\"</b>，从：<span style='color: #ff0000'>\"{old}\"</span>，修改为：<span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity": "[活动] 修改了<b>“{name}”</b>活动的属性 <b>\"{field}\"</b>，从：<span style='color: #ff0000'>\"{old}\"</span>，修改为：<span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity_addRoute": "[路由] 增加了<b>“{name}”</b>活动的路由<b>“{rname}”</b>，指向<span style='color: #0000ff'>“{next}”</span>",
		"modifyActivity_deleteRoute": "[路由] 删除了<b>“{name}”</b>活动的路由<b>“{rname}”</b>，指向<span style='color: #ff0000'>“{next}”</span>",
		"modifyActivity_modifyRouteNext": "[路由] 修改了<b>“{name}”</b>活动的路由<b>“{rname}”</b>，从指向<span style='color: #ff0000'>“{oldnext}”</span>，修改为指向<span style='color: #0000ff'>“{newnext}”</span>",
		"modifyActivity_modifyRouteField": "[路由] 修改了<b>“{name}”</b>活动的路由<b>“{rname}”</b>， 属性<b>\"{field}\"</b> 从：<span style='color: #ff0000'>\"{old}\"</span>，修改为：<span style='color: #0000ff'>\"{new}\"</span>",
		"deleteActivity": "[活动] 删除了活动<b style='color: #ff0000'>“{name}”</b>",
		"addActivity": "[活动] 增加了活动<b style='color: #0000ff'>“{name}”</b>",
		"noDiffs": "与上一版本无差异",
		"hasDiffs": "与上一版本差异:",

		"open": "切换",
		"enable": "启用",
		"rollback": "回滚",
		"override": "覆盖",
		"del": "删除",

		"openInfor": "保存当前打开的版本，并打开版本”{v}“。",
		"enableInfor": "启用流程版本”{v}“",
		"rollbackInfor": "将流程设计回滚所选版本，所有所选版本之后的版本会被删除。",
		"overrideInfor": "用所选版本的设计覆盖当前版本。",
		"delInfor": "删除流程版本”{v}“。",

		"enabledProcessTitle": "启用流程确认",
		"enabledProcessInfor": "将当前流程设置为”启用“，原来已启用的流程版本将被设置为”未启用“。<br><br>已经在流转的流程实例不会受到影响，下次启动流程时，会以已启用的流程版本为模板创建流程实例。<br><br>您确定要将当前流程设置为”启用“吗？",

		"deleteEditionTitle": "删除版本确认",
		"deleteEditionInfor": "删除选中的流程版本”{v}“，同时也会删除流程版本”{v}“的流转中实例。您确定要删除流程版本”{v}“吗？"
	},
	"selectorButton" : {
		"ok" : "确　定",
		"cancel" : "取 消"
	},
	"orgEditor" : {
		"addOption" : "添加选择项",
		"modifyOption" : "修改选择项",
		"conflictNotice" : "该路由已经有重名配置",
		"copyConfig" : "拷贝选择配置"
	},
	"serial": {
		"text": ["文本", "固定文本"],
		"year": ["年", "拟稿时间年度"],
		"month": ["月", "拟稿时间月份"],
		"day": ["日", "拟稿时间日"],
		"unit": ["组织", "拟稿人所在直接组织"],
		"unitAttribute": ["组织属性", "拟稿人所在直接组织的属性"],
		"script": ["脚本", "脚本"],
		"number": ["流水号", "流水号"]
	},
	"propertyTemplate": {
		"base": "基本",
		"event": "事件",
		"html": "HTML",
		"json": "JSON",
		"person": "人员",
		"split": "拆分",

		"id": "标识",
		"name": "名称",
		"alias": "别名",
		"description": "描述",
		"creator": "创建人",
		"createTime": "创建时间",
		"updater": "更新人",
		"updateTime": "更新时间",
		"application": "应用",
		"icon": "图标",
		"type": "类型",
		"form": "表单",

		"routeAsOpinion": "使用路由名称作为缺省意见",
		"yes": "是",
		"no": "否",
		"opinionInfo": "(选择“否”：处理意见没填写则意见为空)",
		"version": "版 本",
		"versionName": "版本名称",
		"versionId": "版本标识",
		"versionDescription": "版本描述",

		"startup": "启 动",
		"startTerminal": "启动终端",
		"pcAndMobile": "PC端和移动端",
		"onlyPc": "仅PC端",
		"startMode": "启动模式",
		"instanceMode": "实例模式",
		"draftMode": "草稿模式",
		"instanceModeInfo": "(新建流程时直接创建流程实例，给拟稿人生成待办)",
		"draftModeInfo": "(新建流程时不创建流程实例，不生成待办，产生一个草稿文档，直到流转时才创建流程实例)",

		"checkDraft": "新建检查",
		"checkDraftInfo": "(选择“是”：未保存过的流程实例不会保留)",
		"power": "权 限",
		"stratIdentity": "启动人",
		"startUnit": "启动组织",
		"manager": "管理者",

		"number": "编号",
		"numberActivity": "编号活动",
		"trigger": "触发条件",
		"arrivals": "到达",
		"submit": "提交",

		"aging": "时效",
		"processTimeLimit": "流程超时",
		"noLimit": "不超时",
		"specifyDuration": "指定时长",
		"byScript": "通过脚本",
		"timeLimit": "超时时长",
		"days": "天",
		"hours": "小时",
		"workTimeOnly": "仅计算工作时间",
		"includeNoworkTime": "包含非工作时长",
		"script": "脚本",
		"returnJson": "脚本返回JSON数据",
		"hourTimeout": "几小时后超时",
		"hourWorkTimeout": "几个工作小时后超时",
		"specifyTimeout": "到达指定时间后超时",
		"oneOfThree": "三个值任选其一",

		"mapping": "映射",
		"mappingData": "映射业务数据",
		"dataName": "数据名称",
		"dataPath": "数据路径",
		"dataType": "数据类型",
		"mappingOnFlow": "每次流转刷新映射数据",

		"allowReroute": "是否允许调度",
		"allowRerouteTo": "允许调度到此活动",

		"reader": "待阅人",
		"readerId": "待阅人标识",
		"duty": "职　　位",
		"processData": "流程数据",
		"reviewer": "阅读人",
		"reviewerId": "阅读人标识",
		"unit": "组织",

		"splitScript": "拆分依据脚本",
		"embed": "调用",
		"selectProcess": "选择流程",
		"embedType": "调用方式",
		"sync": "同步",
		"async": "异步",
		"copyData": "拷贝数据",
		"copyAttachment": "拷贝附件",
		"startPerson": "启动者",
		"currentCreator": "当前流程的启动者",
		"prevHandler": "上一个活动的处理人",
		"specifyPerson": "指定一个启动者",
		"personId": "启动者标识",
		"personScript": "启动者脚本",
		"titleScript": "标题脚本",
		"dataScript": "数据脚本",
		"getOldData": "获取原流程的业务数据",
		"setNewData": "设置新流程的业务数据",

		"timer": "定时",
		"timerType": "定时方式",
		"delayTime": "延时指定的分钟后执行",
		"specifyTime": "指定一个时间点执行",
		"specifyMinute": "指定分钟",
		"specifyATime": "指定时间",
		"specifyData": "指定数据路径",

		"invoke": "调用",
		"protocol": "服务协议",
		"invokeType": "调用方式",
		"wsdlAddr": "WSDL地址",
		"method": "调用方法",
		"parameterScript": "参数脚本",
		"addParameter": "增加参数",
		"deleteParameter": "删除参数",
		"responseScript": "响应脚本",
		"use": "使用",
		"getJson": "获取响应的JSON对象",
		"systemRequest": "系统内请求",
		"restAddr": "REST地址",
		"requestBodyScript": "消息体脚本",
		"setRequestBody": "设置消息体内容",
		"requestHeaderScript": "消息头脚本",
		"addHeader": "增加http头信息",
		"delHeader": "删除http头信息",

		"service": "响应",
		"serviceResponseScript": "服务响应脚本",
		"responseInfo": "通过 this.request.getBody() 获取请求数据<br/>返回 true，驱动流程继续流转<br/>返回 false，表示不符合流转条件，等待下一次调用",

		"runScript": "执行脚本",

		"processType": "处理方式",
		"oneProcess": "只需一人处理",
		"single": "单人",
		"sameTime": "多人同时处理",
		"parallel": "并行",
		"queue": "串行",
		"queueInfo": "多人按顺序处理",
		"grab": "抢办",
		"grabInfo": "谁先打开待办就由谁处理",
		"readForUntreated": "给未处理待办的人发待阅",
		"mergeTask": "合并待办",
		"mergeTaskInfo": "（ 如果选“是”，同一身份在此节点上的待办会被合并 ）",
		"activityGroup": "活动组",
		"opinionGroup": "意见组",
		"taskPerson": "处理人",
		"identity": "用户标识",
		"group": "处理群组",
		"specifyTimeoutTime": "设置指定的超时时间",
		"setTimeoutAfterHours": "设置几小时后超时",
		"setTimeoutAfterWorkHours": "设置几个工作小时后超时",
		"activityPower": "权限",
		"allowDelete": "允许删除文件",
		"allowReset": "是否允许重置",
		"resetCount": "重置人数",
		"resetRange": "重置范围",
		"everyOne": "所有人",
		"directUnit": "直接组织",
		"topUnit": "顶层组织",
		"allowRetract": "是否允许撤回",
		"allowRapid": "允许快速处理",
		"allowAddSplit": "允许增加拆分分支",
		"allowRollback": "允许流程回溯",
		"allowPress": "允许发起办理提醒",
		"allowPause": "允许挂起",

		"beforeBegin": "流程启动前",
		"eventInfo1": "启动流程生成work实例",
		"afterBegin": "流程启动后",
		"beforeArrive": "活动到达前",
		"eventInfo2": "执行Arrive操作<br/>活动属性设置",
		"afterArrive": "活动到达后",
		"beforeExecute": "活动执行前",
		"eventInfo3": "执行Execute操作<br/>执行自动活动任务",
		"afterExecute": "活动执行后",
		"beforeInquire": "路由查询前",
		"eventInfo4": "执行Inquire操作<br/>查询到达下一个活动的路由",
		"afterInquire": "路由查询后",
		"beforeEnd": "流程结束前",
		"eventInfo5": "结束流程<br/>生成workCompleted",
		"afterEnd": "流程结束后",
		"beforeWorkArrive": "工作到达前",
		"beforeArriveActivity": "文件收到前",
		"afterArriveActivity": "文件收到后",
		"eventInfo6": "执行Arrive操作<br/>活动属性设置，计算可能的活动所有者",
		"eventInfo7": "执行Execute操作<br/>生成待办",
		"manualStay": "等待人工处理时",
		"eventInfo8": "用户流转待办",
		"manualBeforeTask": "待办处理前",
		"eventInfo9": "处理待办，转已办",
		"manualAfterTask": "待办处理后",
		"eventInfo10": "判断是否满足条件进入下一个活动",

		"updataTime": "更新时间",
		"num": "顺序号",
		"defaultOpinion": "默认意见",
		"opinionRequired": "意见必填",
		"routeType": "路由类型",
		"defaultRoute": "默认路由",
		"backRoute": "回退路由",
		"appendTask": "转交（仅指向同活动时生效）",
		"appendTaskInfo": "转交活动不触发活动事件",
		"appendTo": "转交人员",
		"byRoute": "根据路由选择",
		"appendToScript": "转交人脚本",
		"asyncReturn": "异步返回",
		"expand": "扩展",
		"decisionGroup": "决策组",
		"decisionGroupInfo": "多个决策组请用#号分隔，名称前加整数为排序值。如“1同意#2不同意”。",
		"prefRouting": "优先路由",
		"routeNow": "立即路由",
		"routeNowInfo": "(当选择“是”，多人处理时只要选择此路由，则立即按此路由流转文档)",
		"autoFlowTime": "活动超时时自动流转",
		"autoFlowPerson": "与上一活动处理人相同时自动流转",
		"routeCheck": "路由校验",
		"routeCheckInfo": "(返回true通过，返回string为错误提示)",
		"showName": "显示名称",
		"hideCondition": "隐藏条件",
		"hideConditionInfo": "(返回true隐藏)",
		"select": "选择",

		"title": "标题",
		"titleInfo": "如：请选择部门经理",
		"defaultValue": "默认值",
		"defaultValueScript": "默认值脚本",
		"checkCount": "校验数量",
		"checkCountInfo": "选择的个数不少于",
		"verificationScript": "校验脚本",
		"unitSelectConfig": "人员组织选择配置",
		"selectType": "选择类型",
		"personIdentity": "身份",
		"selectCount": "选择数量",
		"checkEmpower": "检查待办授权",
		"onlyCustom": "只使用自定义选项",
		"unitRange": "组织范围",
		"allUnit": "所有组织",
		"specifyUnit": "指定组织",
		"draftUnit": "拟稿人所在的组织",
		"currentUnit": "当前人所在的组织",
		"inUnit": "直接所属组织",
		"levelIs": "第",
		"levelUnit": "层组织",
		"unitTypeIs": "类型为",
		"deUnit": "的组织",
		"expandNext": "展开下级",
		"selectUnit": "选择组织",
		"formData": "表单数据",
		"dutyRange": "职务范围",
		"all": "所有",
		"all2": "全部",
		"specifyDuty": "指定职务",
		"category": "分类",
		"byUnit": "按组织",
		"byDuty": "按职务",
		"showLevel": "展现层级",
		"byDutyUnit": "按职务所在组织",
		"byIdentityUnit": "按身份所在组织",
		"selectDuty": "选择职务",
		"customOption": "自定义选项",
		"useScriptAddId": "使用脚本添加身份",
		"unitType": "组织类型",
		"exclude": "排除",
		"excludeInfo": "通过编写脚本排除组织、身份、个人和群组的选择范围",
		"dataStructure": "数据保存",
		"complete": "完整",
		"simple": "精简",

		"section": "区段",
		"enableSection": "启用区段",
		"sectionBy": "区段依据",
		"handler": "处理人",
		"handlerUnit": "处理人所在组织",
		"activityId": "活动ID",
		"splitValue": "拆分值",

	}
};
