MWF.xApplication.process.ProcessDesigner.LP = {
	"title": "流程編輯",
    "newProcess": "新流程",
    "tools": "工具",
    "unnamed": "未命名",
    "unknow": "未知",
    "unrealized": "此功能未實現",
    "activity": "活動",
    "route": "路由",
    "property": "屬性",
    "showJson": "查看JSON",
    "all": "全部",
    "showAdvanced": "顯示高級屬性",
    "phone": "手機",
    "mail": "郵件",
    "selectScript": "點擊選擇腳本：",
    "condition": "條件",
    "unCategory": "未分類",
    "ok": "確定",
    "close": "關閉",
    "cancel": "取消",
    "notice": {
        "no_name": "請先輸入流程名稱",
        "save_success": "流程保存成功！",
        "save_process": "請先保存流程！",
        "one_begin": "每個流程只允許有一個“開始”活動",
        "deleteRoute": "您確定要刪除選中的路由嗎？",
        "deleteRouteTitle": "刪除路由確認",
        "deleteActivityTitle": "刪除活動確認",
        "deleteActivity": "刪除活動將同時刪除關聯此活動的所有路由，您確定要刪除選中的活動嗎？",
        "saveRouteOrgNoName": "標識和標題不能為空",
        "saveRouteOrgNumberId": "標識不能為純數字",
        "saveRouteOrgDoubleDotId": "標識不能包含連續兩個點號",
        "processCopyError": "活動粘貼失敗，請重新複製後重試",
        "routeNameConfilct": "一個活動不能有兩個同名路由！"
    },
	"menu": {
        "newRoute": "新建路由",
        "newActivity": "新建活動",
        "newActivityType": {
            "manual": "人工活動",
            "condition": "條件活動",
            "auto": "自動活動",
            "split": "拆分活動",
            "merge": "合併活動",
            "embed": "流程調用",
            "invoke": "服務調用",
            "service": "服務活動",
            "agent": "腳本活動",
            "delay": "定時活動",
            "publish": "數據發布",
            "message": "消息活動",
            "choice": "選擇活動",
            "cancel": "取消活動",
            "begin": "開始活動",
            "end": "結束活動",
            "parallel": "並行活動"
        },
        "copyActivity": "複製活動",
        "deleteActivity": "刪除活動",
        "deleteRoute": "刪除路由",
        "saveProcess": "保存流程",
        "saveProcessNew": "保存為新版本",
        "checkProcess": "檢查流程",
        "exportProcess": "導出流程",
        "printProcess": "打印流程",
        "showGrid": "顯示網格",
        "hideGrid": "隱藏網格"
    },
    "intoScript": "點擊此處，編寫腳本代碼",
    "serialSelectTitle": "序列選擇屬性",
    "serialActivityTitle": "執行序列活動",
    "delete": "刪除",
    "serialRule": "序列規則",
    "serialTextTitle": "輸入文本",
    "serialDateTitle": "時間",
    "serialCreatedDateTitle": "創建日期",
    "serialCurrentDateTitle": "序列日期",
    "serialCreated": "創建",
    "serialCurrent": "序列",
    "serialAttributeTitle": "輸入屬性名稱",
    "serialScriptTitle": "輸入腳本",
    "serialNumberLongTitle": "序列號長度",
    "serialNumberByTitle": "序列號依據",
    "isSave": "正在保存，請稍候...",
    "dutyInputTitle": "添加職務參數",
    "dutyInput": "為'{duty}'職務添加參數",
    "creatorCompany": "創建公司",
    "creatorDepartment": "創建部門",
    "currentCompany": "當前公司",
    "currentDepartment": "當前部門",
    "deleteDutyTitle": "移除職務確認",
    "deleteDutyText": "您確定要移除'{duty}'職務嗎？",
    "selectIcon": "選擇圖標",
    "centerServer": "中心服務",
    "creatorUnit": "創建者所屬組織",
    "currentUnit": "處理者所屬組織",
    "selectUnit": "選擇組織",
    "scriptUnit": "使用腳本",
    "preview": "預覽",
    "copy": "從其他設置複製",
    "selectType": "選擇類型",
    "identity": "身份",
    "unit": "組織",
    "selectCount": "選擇數量",
    "deleteOrgConfirmTitle": "刪除選擇確認",
    "deleteOrgConfirmContent": "確定要刪除此選擇配置嗎？",

	"projectionTitle": "映射業務數據",
    "projectionActionNode_add": "添加映射條目",
    "projectionActionNode_modify": "修改映射條目",
    "projectionDataName": "數據名稱",
    "projectionPath": "數據路徑",
    "projectionType": "數據類型",
    "projectionName": "列名",
    "projectionInputError": "請輸入數據名稱和數據路徑",
    "projectionTypeCountError": "最多允許 {count} 個 {type} 類型的數據映射條目",
    "projectionSameNameError": "相同的數據名稱已存在",
    "projectionDeleteItemTitle": "刪除數據映射條目確認",
    "projectionDeleteItem": "您確定要刪除名為“{name}”，路徑為“{path}”的數據映射條目嗎？",
    "projectionRunActionNode": "立即運行數據映射",
    "projectionRunTitle": "立即執行確認",
    "projectionRunText": "請確認立即執行數據映射",
    "projectionRunSuccess": "數據映射已經開始執行",
    "projectionRunError": "不需要執行數據映射",
    "enable": "已啟用",
    "notEnable": "未啟用",
    "currentEdition": "當前版本",
    "editionUpdate": "最後修改",
    "editionDiscription": "請輸入版本描述",
    "upgradeConfirm": "保存為新版本確認",
    "upgradeInfor": "<div style='overflow: hidden; line-height: 26px'>您是否確定要將當前流程保存為新版本?<br/>選中“同時啟用新版本”在保存完成之後,會將新版本設置為啟用版本.</div><div style='margin-top:10px'><input type='checkbox' checked>同時啟用新版本</div>",
    "inputDiscription": "請先輸入版本描述",

	"edition_list":{
		"editionList": "查看流程版本",
		"number": "版本號",
		"update": "更新時間",
		"updatePerson": "更新人",
		"description": "版本描述",
		"enabled": "啟用",
		"action": "操作",
		"yes": "是",
		"no": "否",
		"newProcess": "創建了新的流程。",
		"an": "個",
		"modifyProcess": "[流程] 修改了流程的屬性 <b>\"{field}\"</b>，從：<span style='color: #ff0000'>\"{old}\"</span>，修改為：<span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity": "[活動] 修改了<b>“{name}”</b>活動的屬性 <b>\"{field}\"</b>，從：<span style='color: #ff0000'>\"{old}\"</span>，修改為：<span style='color: #0000ff'>\"{new}\"</span>",
		"modifyActivity_addRoute": "[路由] 增加了<b>“{name}”</b>活動的路由<b>“{rname}”</b>，指向<span style='color: #0000ff'>“{next}”</span>",
		"modifyActivity_deleteRoute": "[路由] 刪除了<b>“{name}”</b>活動的路由<b>“{rname}”</b>，指向<span style='color: #ff0000'>“{next}”</span>",
		"modifyActivity_modifyRouteNext": "[路由] 修改了<b>“{name}”</b>活動的路由<b>“{rname}”</b>，從指向<span style='color: #ff0000'>“{oldnext}”</span>，修改為指向<span style='color: #0000ff'>“{newnext}”</span>",
		"modifyActivity_modifyRouteField": "[路由] 修改了<b>“{name}”</b>活動的路由<b>“{rname}”</b>， 屬性<b>\"{field}\"</b> 從：<span style='color: #ff0000'>\"{old}\"</span>，修改為：<span style='color: #0000ff'>\"{new}\"</span>",
		"deleteActivity": "[活動] 刪除了活動<b style='color: #ff0000'>“{name}”</b>",
		"addActivity": "[活動] 增加了活動<b style='color: #0000ff'>“{name}”</b>",
		"noDiffs": "與上一版本無差異",
		"hasDiffs": "與上一版本差異:",
		"open": "切換",
		"enable": "啟用",
		"rollback": "回滾",
		"override": "覆蓋",
		"del": "刪除",
		"openInfor": "保存當前打開的版本，並打開版本“{v}”。",
		"enableInfor": "啟用流程版本“{v}”",
		"rollbackInfor": "將流程設計回滾到所選版本，所選版本之後的所有版本將被刪除。",
		"overrideInfor": "用所選版本的設計覆蓋當前版本。",
		"delInfor": "刪除流程版本“{v}”。",
		"enabledProcessTitle": "啟用流程確認",
		"enabledProcessInfor": "將當前流程設定為“啟用”，原來已啟用的流程版本將被設定為“未啟用”。<br><br>已經在流轉的流程實例不會受到影響，下次啟動流程時，會以已啟用的流程版本為模板創建流程實例。<br><br>您確定要將當前流程設定為“啟用”嗎？",
		"deleteEditionTitle": "刪除版本確認",
		"deleteEditionInfor": "刪除選中的流程版本“{v}”，同時也會刪除流程版本“{v}”的流轉中實例。您確定要刪除流程版本“{v}”嗎？"
	},
	"selectorButton": {
        "ok": "確 定",
        "cancel": "取 消"
    },
    "orgEditor": {
        "addOption": "添加選擇項",
        "modifyOption": "修改選擇項",
        "conflictNotice": "該路由已經有重名配置",
        "copyConfig": "複製選擇配置"
    },
    "serial": {
        "text": ["文本", "固定文本"],
        "year": ["年", "拟稿时间年度"],
        "month": ["月", "拟稿时间月份"],
        "day": ["日", "拟稿时间日"],
        "unit": ["組織", "拟稿人所在直接組織"],
        "unitAttribute": ["組織屬性", "拟稿人所在直接組織的屬性"],
        "script": ["腳本", "腳本"],
        "number": ["流水號", "流水號"]
    },
	"propertyTemplate": {
		"base": "基本",
		"event": "事件",
		"html": "HTML",
		"json": "JSON",
		"person": "人員",
		"split": "拆分",
		"apiDoc": "點擊此處查看API文檔",
		"id": "標識",
		"name": "名稱",
		"alias": "別名",
		"description": "描述",
		"creator": "創建人",
		"createTime": "創建時間",
		"updater": "更新人",
		"updateTime": "更新時間",
		"application": "應用",
		"icon": "圖標",
		"type": "類型",
		"form": "表單",
		"routeAsOpinion": "使用路由名稱作為預設意見",
		"yes": "是",
		"no": "否",
		"opinionInfo": "(選擇“否”：處理意見未填寫則意見為空)",
		"version": "版本",
		"versionName": "版本名稱",
		"versionId": "版本標識",
		"versionDescription": "版本描述",
		"startup": "啟動",
		"startTerminal": "啟動終端",
		"pcAndMobile": "PC端和移動端",
		"onlyPc": "僅PC端",
		"none": "無",
		"startMode": "啟動模式",
		"instanceMode": "實例模式",
		"draftMode": "草稿模式",
		"instanceModeInfo": "(新建流程時直接創建流程實例，為起草人生成待辦)",
		"draftModeInfo": "(新建流程時不創建流程實例，不生成待辦，產生一個草稿文檔，直到流轉時才創建流程實例)",

		"checkDraft": "新建檢查",
		"checkDraftInfo": "(選擇“是”：未保存過的流程實例不會保留)",
		"power": "權 限",
		"stratIdentity": "啟動人",
		"startUnit": "啟動組織",
		"starGroup": "啟動群組",
		"manager": "管理者",
		"maintenanceIdentity": "維護人",
		"number": "編號",
		"numberActivity": "編號活動",
		"trigger": "觸發條件",
		"arrivals": "到達",
		"submit": "提交",
		"aging": "時效",
		"processTimeLimit": "流程超時",
		"noLimit": "不超時",
		"specifyDuration": "指定時長",
		"byScript": "通過腳本",
		"timeLimit": "超時時長",
		"days": "天",
		"hours": "小時",
		"workTimeOnly": "僅計算工作時間",
		"includeNoworkTime": "包含非工作時長",
		"script": "腳本",
		"returnJson": "腳本返回JSON數據",
		"hourTimeout": "幾小時後超時",
		"hourWorkTimeout": "幾個工作小時後超時",
		"specifyTimeout": "到達指定時間後超時",
		"oneOfThree": "三個值任選其一",
		"mapping": "映射",
		"mappingData": "映射業務數據",
		"dataName": "數據名稱",
		"dataPath": "數據路徑",
		"dataType": "數據類型",
		"mappingOnFlow": "每次流轉刷新映射數據",
		"mappingDataToTable": "映射數據表",
		"mappingTableEnabled": "流轉結束後將數據存儲到數據表",
		"queryTable": "數據表查詢",

		"data": "數據",
		"dataTrace": "業務數據追蹤",
		"dataTraceInfo": "啟用業務數據追蹤可以記錄指定業務字段的每次變化情況，可以在表單設計中設置查看業務數據的歷史變化記錄",
		"dataTraceInfo2": "",
		"dataTraceFields": "追蹤字段",
		"dataTraceDisabled": "無",
		"dataTraceCustom": "自定義",
		"dataTraceAll": "所有",
		"dataTraceDisabledInfo": "不追蹤任何業務數據字段",
		"dataTraceCustomInfo": "在下面的設置中定義要追蹤的業務字段",
		"dataTraceAllInfo": "追蹤所有業務數據字段（不包括數據表格、數據模板和長文本（LOB）類型的數據）",
		"dataTraceFieldNames": "字段名稱",
		"dataTraceFieldNamesSelect": "選擇表單字段",
		"selectForm": "表單",
		"selectField": "數據字段",
		"selectedField": "已選字段",
		"allowReroute": "是否允許調度",
		"allowRerouteTo": "允許調度到此活動",
		"mergeLayerThreshold": "合併層數閾值",
		"mergeLayerThreshold0": "合併尽量多的層數",
		"mergeLayerThreshold1": "合併單層",
		"mergeLayerThresholdn": "合併{n}層",
		"reader": "待閱人",
		"readerId": "身份",
		"duty": "職務",
		"processData": "流程數據",
		"reviewer": "審閱人",
		"reviewerId": "身份",
		"unit": "組織",

		"splitScript": "分割腳本",
		"embed": "呼叫",
		"selectProcess": "選擇流程",
		"embedType": "呼叫類型",
		"sync": "同步",
		"async": "非同步",
		"copyData": "複製數據",
		"copyAttachment": "複製附件",
		"startPerson": "發起者",
		"currentCreator": "當前流程的發起者",
		"prevHandler": "上一個活動的處理者",
		"specifyPerson": "指定一個發起者",
		"personId": "發起者標識",
		"personScript": "發起者腳本",
		"titleScript": "標題腳本",
		"dataScript": "數據腳本",
		"getOldData": "獲取原始流程的業務數據",
		"setNewData": "設置新流程的業務數據",
		"waitUntilCompletedTitle": "流程等待",
		"waitUntilCompleted": "如果選擇“是”，主流程將在被呼叫流程流轉過程中保持等待，直到等待被呼叫流程流轉結束",
		"completedEventsInfo": "啟用流程等待，子流程結束後會觸發主流程繼續流轉，下面的三個事件會被執行",
		"completedEndEvent": "子流程成功後",
		"completedEnd": "子流程成功",
		"completedCancelEvent": "子流程取消後",
		"completedCancel": "子流程取消",
		"completedEvent": "子流程完成後",
		"completed": "子流程完成",
		"completedEndEventInfo": "當子流程流轉到結束活動，此事件會被執行",
		"completedCancelEventInfo": "當子流程流轉到取消活動，此事件會被執行",
		"completedEventInfo": "當子流程流轉到結束或取消活動，此事件會被執行",
		"timer": "定時",
		"timerType": "定時方式",
		"delayTime": "延時指定的分鐘後執行",
		"specifyTime": "指定一個時間點執行",
		"specifyMinute": "指定分鐘",
		"specifyATime": "指定時間",
		"specifyData": "指定數據路徑",
		"invoke": "呼叫",
		"protocol": "服務協議",
		"invokeType": "呼叫類型",
		"wsdlAddr": "WSDL地址",
		"method": "呼叫方法",
		"parameterScript": "參數腳本",
		"addParameter": "增加參數",
		"deleteParameter": "刪除參數",
		"responseScript": "響應腳本",

		"use": "使用",
		"getJson": "獲取響應內容。如果響應內容是JSON格式的字符串，則返回JSON對象；否則返回原始響應內容。如果調用本平台服務管理中的接口，在接口中返回的數據需放在data中，如:{ \"data\" : [] }",
		"systemRequest": "系統內請求",
		"restAddr": "REST地址",
		"requestBodyScript": "消息體腳本",
		"setRequestBody": "設置消息體內容",
		"requestHeaderScript": "消息頭腳本",
		"addHeader": "增加http頭信息",
		"delHeader": "刪除http頭信息",
		"setParameterInfo": "返回一個json對象來設置參數，請查看API文檔",
		"setParameterInfo2": "返回一個數組來設置參數，請查看API文檔",
		"setRequestBodyInfo": "返回一個json對象來設置消息體內容，請查看API文檔",
		"setHeaderInfo": "返回一個json對象來設置消息頭，請查看API文檔",
		"getJaxws": "獲取響應內容。響應類型取決於服務的返回",
		"service": "響應",
		"serviceResponseScript": "服務響應腳本",
		"responseInfo": "通過 this.request.getBody() 獲取請求數據。返回 true，驅動流程繼續流轉；返回 false，表示不符合流轉條件，等待下一次調用",
		"runScript": "執行腳本",
		"processType": "處理方式",
		"oneProcess": "只需一人處理",
		"single": "單人",
		"sameTime": "多人同時處理",
		"parallel": "並行",
		"queue": "串行",
		"queueInfo": "多人按順序處理",
		"grab": "搶辦",
		"grabInfo": "誰先打開待辦就由誰處理",
		"readForUntreated": "給未處理待辦的人發待閱",
		"mergeTask": "合併分支待辦",
		"mergeTaskInfo": "（ 如果選“是”，當流程拆分狀態下，同一身份在此活動上的多個待辦會被合併為一個 ）",
		"mergeTaskProcess": "合併待辦處理",
		"mergeTaskProcessInfo": "（ 如果選“是”，當同一人員的不同身份在此活動中產生多個待辦時，只需要處理一次 ）",
		"activityGroup": "活動組",
		"opinionGroup": "意見組",
		"taskPerson": "處理人",
		"customData": "自定義屬性",

		"identity": "身份",
		"group": "組別",
		"readGroup": "讀取組別",
		"reviewGroup": "審核組別",
		"specifyTimeoutTime": "設定指定的逾時時間",
		"setTimeoutAfterHours": "幾小時後逾時設定",
		"setTimeoutAfterWorkHours": "幾個工作小時後逾時設定",
		"activityPower": "權限",
		"allowDelete": "允許刪除文件",
		"allowReset": "是否允許重置",
		"resetCount": "重置加簽人數",
		"resetRange": "重置加簽範圍",
		"everyOne": "所有人",
		"directUnit": "直接組織",
		"topUnit": "頂層組織",
		"allowRetract": "是否允許撤回",
		"allowRapid": "允許快速處理",
		"allowAddSplit": "允許增加拆分分支",
		"allowRollback": "允許流程回溯",
		"allowPress": "允許發起辦理提醒",
		"allowPause": "允許暫停",
		"allowAddTask": "允許加簽",

		"backConfig": "退回配置",
		"allowBack": "允許退回",
		"multiTaskEnable": "多人並行時是否允許退回",
		"multiTaskEnableInfo": "多人並行處理時執行退回會取消其他未處理人的待辦，直接退回到指定活動",
		"backType": "退回方式",
		"backPrev": "逐級退回",
		"backAny": "任意活動退回",
		"backDefine": "選擇退回活動",
		"backPrevInfo": "逐級退回：用戶選擇“退回”，則將當前工作退回到上一個處理活動",
		"backAnyInfo": "任意活動退回：用戶選擇“退回”時，可選擇任意一個已經處理過的活動",
		"backDefineInfo": "選擇退回活動：定義允許退回的活動，用於可以退回到已允許的活動",
		"backWay": "退回後處理",
		"backWayDefault": "默認",
		"backWayStep": "按流程配置正常流轉",
		"backWayJump": "直接回到退回人",
		"backWayCustom": "由退回人決定",

		"backActivitySelectTitle": "選擇允許退回的活動",
		"backActivitySelectInfo": "您可以選擇允許在當前活動中退回的活動節點，只有已經流轉過的活動才能被退回。您還可以為每個允許退回的活動單獨設置退回後的處理方式。",


		"beforeBegin": "流程啟動前",
		"eventInfo1": "啟動流程生成work實例",
		"afterBegin": "流程啟動",
		"beforeArrive": "活動到達前",
		"eventInfo2": "執行Arrive操作，活動屬性設置",
		"afterArrive": "活動到達後",
		"beforeExecute": "活動執行前",
		"eventInfo3": "執行Execute操作，執行自動活動任務",
		"afterExecute": "活動執行後",
		"beforeInquire": "路由查詢前",
		"eventInfo4": "執行Inquire操作，查詢到達下一個活動的路由",
		"afterInquire": "路由查詢後",
		"beforeEnd": "流程結束前",
		"eventInfo5": "結束流程，生成workCompleted",
		"afterEnd": "流程結束",
		"beforeWorkArrive": "工作到達前",
		"beforeArriveActivity": "文件收到前",
		"afterArriveActivity": "文件收到後",
		"eventInfo6": "執行Arrive操作，活動屬性設置，計算可能的活動所有者",
		"eventInfo7": "執行Execute操作，生成待辦",
		"manualStay": "等待人工處理時",
		"eventInfo8": "用戶流轉待辦",
		"manualBeforeTask": "待辦處理前",
		"eventInfo9": "處理待辦，轉已辦",
		"manualAfterTask": "待辦處理後",
		"eventInfo10": "判斷是否滿足條件進入下一個活動",

		"eventInfo11": "執行所有流程流轉任務，直到在某個活動停留或結束",
		"afterProcess": "活動流轉完成",

		"updataTime": "更新時間",
		"num": "順序號",
		"defaultOpinion": "預設意見",
		"opinionRequired": "意見必填",
		"routeType": "路由類型",
		"defaultRoute": "默認路由",
		"backRoute": "回退路由",
		"appendTask": "轉交（僅指向同活動時生效）",
		"appendTaskInfo": "轉交活動不觸發活動事件",
		"appendTo": "轉交人員",
		"byRoute": "根據路由選擇",
		"appendToScript": "轉交人員腳本",
		"asyncReturn": "異步返回",
		"expand": "擴展",
		"decisionGroup": "決策組",
		"decisionGroupInfo": "多個決策組請用#號分隔，名稱前加整數為排序值。例如“1同意#2不同意”。",
		"prefRouting": "優先路由",
		"routeNow": "立即路由",
		"routeNowInfo": "(當選擇“是”，多人處理時只要選擇此路由，則立即按此路由流轉文檔)",
		"autoFlowTime": "活動超時時自動流轉",
		"autoFlowPerson": "與上一活動處理人相同時自動流轉",
		"routeCheck": "路由驗證",
		"routeCheckInfo": "(返回true通過，返回string為錯誤提示)",
		"showName": "顯示名稱",
		"hideCondition": "隱藏條件",
		"hideConditionInfo": "(返回true隱藏)",
		"select": "選擇",

		"title": "標題",
		"titleInfo": "例如：選擇部門經理",
		"defaultValue": "默認值",
		"defaultValueScript": "默認值腳本",
		"checkCount": "校驗數量",
		"checkCountInfo": "選擇的數量不少於",
		"verificationScript": "校驗腳本",
		"unitSelectConfig": "人員組織選擇配置",
		"selectType": "選擇類型",
		"personIdentity": "身份",
		"selectCount": "選擇數量",
		"checkEmpower": "檢查待辦授權",
		"onlyCustom": "僅使用自定義選項",
		"unitRange": "組織範圍",
		"allUnit": "所有組織",
		"specifyUnit": "指定組織",
		"draftUnit": "起草人所在的組織",
		"currentUnit": "當前人所在的組織",
		"inUnit": "直接所屬組織",
		"levelIs": "第",
		"levelUnit": "層組織",
		"unitTypeIs": "類型為",
		"deUnit": "的組織",
		"expandNext": "展開下級",
		"selectUnit": "選擇組織",
		"formData": "表單數據",
		"dutyRange": "職務範圍",
		"all": "全部",
		"all2": "全部",
		"groupRange": "群組範圍",
		"specifyGroup": "指定群組",
		"specifyDuty": "指定職務",
		"category": "分類",
		"byUnit": "按組織",
		"byDuty": "按職務",
		"showLevel": "顯示層級",
		"byDutyUnit": "按職務所在組織",
		"byIdentityUnit": "按身份所在組織",
		"selectDuty": "選擇職務",
		"customOption": "自定義選項",
		"useScriptAddId": "使用腳本添加身份",
		"unitType": "組織類型",
		"exclude": "排除",
		"excludeInfo": "通過編寫腳本排除組織、身份、個人和群組的選擇範圍",
		"firstLevelSelectable": "允許選擇第一層",
		"dataStructure": "數據保存",
		"complete": "完整",
		"simple": "簡化",

		"section": "區段",
		"enableSection": "啟用區段",
		"sectionBy": "區段依據",
		"handler": "處理人",
		"handlerUnit": "處理人所屬組織",
		"activityId": "活動 ID",
		"splitValue": "分割值",
		"publish": "發佈",
		"publishTarget": "發佈目標",
		"cms": "內容管理",
		"table": "數據表",
		"cmsCategory": "內容管理分類",
		"selectCmsCategory": "選擇分類",
		"categoryDataPath": "內容管理分類數據路徑",
		"sendNotify": "消息推送範圍欄位",
		"readerFields": "讀者欄位",
		"authorFields": "作者欄位",
		"pictureFields": "首頁圖片欄位",
		"useProcessForm": "使用流程表單",
		"titleField": "標題欄位",
		"useProcessFormNote": "注意：如果選擇「是」，則發佈到內容管理文件將使用流程表單打開，否則將使用內容管理分類設定的表單打開。",
		"setNewPublishData": "返回一個 JSON 對象以設置數據，請參閱 API 文件。例如:",

		"querytable": "數據表",
		"querytableActionNode_add": "↑ 添加數據表配置條目 ↑",
		"querytableActionNode_modify": "↑ 修改數據表配置條目 ↑",
		"querytableInputError": "請選擇數據表",
		"queryTableAssignDataScriptError": "數據腳本不能為空",
		"querytableDeleteItemTitle": "刪除數據表配置條目確認",
		"querytableDeleteItem": "您確定要刪除當前數據表配置條目嗎？",
		"queryTableDataBy": "取值",
		"byDataPath": "通過數據路徑",
		"byDataScript": "通過數據腳本",
		"publishTableConfig": "數據表發佈配置",
		"queryTableDataPathNote": "注意：根路徑留空，數據表填數據表識別.data（例如：datatable1.data），數據模板填數據模板識別（例如：datatemplate1）。",
		"orgIdPlaceholder" : "例如：departmentLeader"
	}
};
