MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.query = MWF.xApplication.query || {};
MWF.xApplication.query.TableDesigner = MWF.xApplication.query.TableDesigner || {};
MWF.xApplication.query.TableDesigner.LP={
	"title": "Data Sheet Design",
	"newTable": "New Data Table",
	"property": "Property",
	"item": "Item",
	"type": "Type",
	"value": "Value",
	"stat": "Statistics",
	"unnamed": "Untitled column",
	"newColumn": "New Column",
	"unCategory": "Uncategorized",
	"close": "Close",
	"id": "Identification",
	"name": "Name",
	"alias": "Alias",
	"description": "Description",
	"application": "Data Application",
	"copyStat": "Copy Statistics",
	"newStatName": "New Statistics Name",
	"copy": "Copy",
	"ok": "OK",
	"cancel": "Cancel",
	"view": "View",
	"table": "Data Table",
	"clumn": "Column",
	"addLine": "Add Data",
	"jpqlType": "JPQL Type",
	"jpqlFromResult": "Query start entry",
	"jpqlMaxResult": "Maximum return result",
	"jpqlSelectTitle": "JPQL Statement",
	"inputWhere": "You can enter the Where clause in the edit box below",
	"jpqlRunSuccess": "JPQL executed successfully",
	"newLineSuccess": "Insert data successfully",
	"newLineJsonError": "Insert data error, data format is wrong",
	"action": {
		"move": "Move",
		"delete": "Delete",
		"add": "Add"
	},
	"errorName": "Column names only allow alphanumeric and underscore combinations, and cannot start with numbers or capital letters.",
	"nameUseKeywork": "{key} is not allowed for column names",
	"errorFieldList": "Please create a data column first.",
	"duplicateName": "A column with the same name already exists",
	"inputName": "Please enter the column name",
	"inputTableName": "Please enter the data table name",
	"tableNameNotStartWithLetter": "The name of the data table must start with a letter",
	"tableAliasNotStartWithLetter": "The table alias must start with a letter",
	"tableNameNotBeLetterAndNumber": "The name of the data table must be all letters or letters plus numbers",
	"tableAliasNotBeLetterAndNumber": "The table alias must be all letters or letters plus numbers",
	"save_success": "Data table saved successfully!",
	"deleteColumnTitle": "Delete column confirmation",
	"deleteColumn": "Are you sure you want to delete the current column?",
	"statusBuildTitle": "Release Data Sheet",
	"statusBuildInfor": "The current data table will be published to the compilation environment. If you delete a column or modify the type of a column, you may need to manually delete the database table. Are you sure you want to perform this operation?",
	"statusDraftTitle": "Cancel compilation of data table",
	"statusDraftInfor": "<span style='color: #FF0000;'>Note: You are deleting this data table from the compilation environment. The database table will be deleted in the next compilation.</span><br><br>You Are you sure you want to perform this operation?",
	"statusDraftInforAgain": "<span style='color: #FF0000;'>Note: You are deleting this data table from the compilation environment. You will not be able to use the current data table, which may affect users who have already used this data table. Related applications.</span><br><br>Are you sure you want to perform this operation again?",
	"statusBuild_success": "The current data table has been published to the compilation environment, you need to run \"Compile All\" to make it effective",
	"statusDraft_success": "The current data table has been cancelled from the compilation environment, and the next time \"Compile All\" will delete the table from the database",
	"buildAllViewTitle": "Compile all data tables",
	"tableExplodeTitle": "Export Data",
	"tableExplodeInfo": "By default, up to 2000 rows can be exported. Are you sure you want to export?",
	"tableExplode_success": "Export successful",
	"buildNoTableError": "The current application has no data table, no need to compile.",
	"buildCurrentAppTitle": "Build current application data table",
	"buildCurrentAppInfor": "The following data tables will be built:</br>{buildlist}",
	"unbuildCurrentAppInfor": "The following data tables are not compiled or uncompiled:</br>{draftList}",
	"buildCurrentAppQuection": "Are you sure you want to do this?",
	"buildCurrentApp_success": "All data tables of the current application have been compiled!",
	"building": "Building...",
	"tableImplodeTitle": "Import Data",
	"tableImplodeInfo": "The imported data will be overwritten. Are you sure to import?",
	"tableExcelImplodeInfo": "If the imported data has an id field, it will be overwritten, otherwise it will be added. Are you sure to import?",
	"tableImplode_success": "Import successful",
	"tableClearTitle": "Clear Data",
	"tableClearInfo": "The emptied data cannot be restored! Are you sure you want to clear it?",
	"tableClear_success": "Clearing successfully",
	"exportExcelFileName": "Export Data",
	"buildAllViewInfor": "All data tables will be compiled, including data tables in all data applications. <span style='color: #FF0000;'>After compiling, please restart the server immediately, otherwise it will cause the JVM to crash</span>. Are you sure you want to perform this operation?",
	"buildAllView_success": "All data tables have been compiled, please restart the server immediately!",
	"tableHelp": "The data table can automatically create a real table in the system database and generate java entity objects. You can use JPQL to operate the data table. The following steps are required to create a data table:<br><br>1. Create a data table, And create each column;<br>2. Click the toolbar button to publish the data table to the compilation state;<br>3. Click the toolbar button to execute the \"compile all data tables of the current application\" operation, after the success, the data table can be used.",
	"propertyTemplate": {
		"base": "Basic",
		"event": "Event",
		"html": "HTML",
		"json": "JSON",
		"action": "Action",
		"select": "Select",
		"alias": "Alias",
		"id": "Id",
		"name": "Name",
		"description": "Description",
		"style": "Style",
		"attribute": "Attribute",
		"type": "Type",
		"status": "Status",
		"draft": "Draft",
		"published": "Published",
		"authority": "Execution Authority",
		"readPersonList": "Readable Person",
		"readUnitList": "Readable Organization",
		"editPersonList": "Editable people",
		"editUnitList": "Editable organization"
	},
	"formToolbar": {
		"save": "Save",
		"saveAs": "save as",
		"autoSave": "Auto Save",
		"preview": "preview",
		"help": "help",
		"build": "Publish the data table and enter the compilable state",
		"statusDraft": "Cancel database compilation, and the compiled data table will be deleted when recompiling",
		"bulidCurrentApp": "Compile all data tables of the current application",
		"tableExplode": "Data Export",
		"tableImplode": "Data Import",
		"tableExcelExplode": "Excel export",
		"tableExcelImplode": "Excel import",
		"tableClear": "Clear table data"
	}
}
MWF.xApplication.query.TableDesigner["lp."+o2.language] = MWF.xApplication.query.TableDesigner.LP