MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.query = MWF.xApplication.query || {};
MWF.xApplication.query.TableDesigner = MWF.xApplication.query.TableDesigner || {};
MWF.xApplication.query.TableDesigner.LP={
	"title": "Diseño de tabla de datos",
	"newTable": "Nueva tabla de datos",
	"property": "Propiedad",
	"item": "Elemento",
	"type": "Tipo",
	"value": "Valor",
	"stat": "Estadística",
	"unnamed": "Columna sin título",
	"newColumn": "Nueva columna",
	"unCategory": "Sin categoría",
	"close": "Cerrar",
	"id": "Identificación",
	"name": "Nombre",
	"alias": "Alias",
	"description": "Descripción",
	"application": "Aplicación de datos",
	"copyStat": "Copiar estadística",
	"newStatName": "Nuevo nombre de estadística",
	"copy": "Copiar",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"view": "Vista",
	"table": "Tabla de datos",
	"clumn": "Columna",
	"addLine": "Agregar datos",
	"jpqlType": "Tipo JPQL",
	"jpqlFromResult": "Elemento de inicio de la consulta",
	"jpqlMaxResult": "Máximo de resultados devueltos",
	"jpqlSelectTitle": "Declaración JPQL",
	"inputWhere": "Puede ingresar la cláusula Where a continuación en el cuadro de edición",
	"jpqlRunSuccess": "La ejecución de JPQL se realizó correctamente",
	"newLineSuccess": "Los datos se agregaron correctamente",
	"newLineJsonError": "Error al agregar datos. El formato de los datos es incorrecto",
	"action": {
		"move": "Mover",
		"delete": "Eliminar",
		"add": "Agregar"
	},
	"errorName": "El nombre de la columna solo permite combinaciones de letras, números y guión bajo, y no puede empezar con un número o letra mayúscula.",
	"nameUseKeywork": "El nombre de la columna no puede usar {key}",
	"errorFieldList": "Cree las columnas de datos primero.",
	"duplicateName": "Ya existe una columna con el mismo nombre.",
	"inputName": "Ingrese el nombre de la columna",
	"inputTableName": "Ingrese el nombre de la tabla de datos",
	"tableNameNotStartWithLetter": "El nombre de la tabla de datos debe comenzar con una letra.",
	"tableAliasNotStartWithLetter": "El alias de la tabla de datos debe comenzar con una letra.",
	"tableNameNotBeLetterAndNumber": "El nombre de la tabla de datos debe ser completamente alfabético o alfanumérico.",
	"tableAliasNotBeLetterAndNumber": "El alias de la tabla de datos debe ser completamente alfabético o alfanumérico.",
	"save_success": "¡Tabla de datos guardada exitosamente!",
	"deleteColumnTitle": "Confirmación para eliminar columna",
	"deleteColumn": "¿Está seguro de que desea eliminar la columna actual?",
	"statusBuildTitle": "Publicar tabla de datos",
	"statusBuildInfor": "Esta tabla de datos se publicará en el entorno de compilación. Si elimina o cambia el tipo de columna, es posible que deba eliminar manualmente la tabla de la base de datos. ¿Está seguro de que desea continuar?",
	"statusDraftTitle": "Cancelar la compilación de la tabla de datos",
	"statusDraftInfor": "<span style='color: #FF0000;'>Atención: está a punto de eliminar esta tabla de datos del entorno de compilación. La próxima vez que se compile, se eliminará la tabla de la base de datos.</span><br><br>¿Está seguro de que desea continuar?",
	"statusDraftInforAgain": "<span style='color: #FF0000;'>Atención: está a punto de eliminar esta tabla de datos del entorno de compilación. No podrá utilizar esta tabla de datos y esto puede afectar las aplicaciones relacionadas que ya están utilizando esta tabla de datos.</span><br><br>¿Está seguro de que desea continuar?",
	"statusBuild_success": "Esta tabla de datos se ha publicado en el entorno de compilación. Debe ejecutar \"Compilar todo\" para que tenga efecto.",
	"statusDraft_success": "Se ha cancelado la compilación de esta tabla de datos en el entorno de compilación. La próxima vez que se ejecute \"Compilar todo\", se eliminará la tabla de la base de datos.",
	"buildAllViewTitle": "Compilar todas las tablas de datos",
	"tableExplodeTitle": "Exportar datos",
	"tableExplodeInfo": "Por defecto, se exportarán como máximo 2000 filas. ¿Está seguro de que desea exportarlos?",
	"tableExplode_success": "¡Datos exportados con éxito!",
	"buildNoTableError": "La aplicación actual no tiene tablas de datos y no es necesario compilar.",
	"buildCurrentAppTitle": "Compilar tablas de datos de la aplicación actual",
	"buildCurrentAppInfor": "Se van a compilar estas tablas de datos: </br>{buildlist}",
	"unbuildCurrentAppInfor": "Estas tablas de datos no se compilan o se han cancelado la compilación:</br>{draftList}",
	"buildCurrentAppQuection": "</br>¿Está seguro de que desea continuar?",
	"buildCurrentApp_success": "¡Se han compilado las tablas de datos de la aplicación actual!",
	"building": "Compilando...",
	"tableImplodeTitle": "Importar datos",
	"tableImplodeInfo": "Los datos importados sobrescribirán los datos existentes. ¿Está seguro de que desea importarlos?",
	"tableExcelImplodeInfo": "Si los datos importados tienen un campo \"id\", se sobrescribirán; de lo contrario, se agregarán como nuevos. ¿Está seguro de que desea importarlos?",
	"tableImplode_success": "¡Datos importados con éxito!",
	"tableClearTitle": "Vaciar datos",
	"tableClearInfo": "¡Los datos vaciados no se pueden recuperar! ¿Está seguro de que desea vaciarlos?",
	"tableClear_success": "¡Datos eliminados con éxito!",
	"exportExcelFileName": "Exportar datos",
	"buildAllViewInfor": "Está a punto de compilar todas las tablas de datos, incluidas las de todas las aplicaciones de datos. <span style='color: #FF0000;'>Después de compilar, reinicie el servidor inmediatamente, de lo contrario JVM puede fallar.</span> ¿Está seguro de que desea continuar?",
	"buildAllView_success": "¡Se han compilado todas las tablas de datos! Reinicie el servidor de inmediato.",
	"tableHelp": "Las tablas de datos pueden crear una tabla real automáticamente en la base de datos del sistema y generar objetos de entidad Java. Puede operar las tablas de datos mediante JPQL. Para crear tablas de datos, siga estos pasos:<br><br>1. Cree una tabla de datos y agregue cada columna.<br>2. Haga clic en el botón de la barra de herramientas para publicar la tabla de datos en el estado compilado.<br>3. Haga clic en el botón de la barra de herramientas para compilar todas las tablas de datos de la aplicación actual. Después del éxito de la compilación, las tablas de datos se pueden usar.",
	"propertyTemplate": {
		"base": "Básico",
		"event": "Evento",
		"html": "HTML",
		"json": "JSON",
		"action": "Acción",
		"select": "Seleccionar",
		"alias": "Alias",
		"id": "Identificación",
		"name": "Nombre",
		"description": "Descripción",
		"style": "Estilo",
		"attribute": "Atributo",
		"type": "Tipo",
		"status": "Estado",
		"draft": "Borrador",
		"published": "Publicado",
		"authority": "Permiso de ejecución",
		"readPersonList": "Personas que pueden leer",
		"readUnitList": "Organizaciones que pueden leer",
		"editPersonList": "Personas que pueden editar",
		"editUnitList": "Organizaciones que pueden editar"
	},
	"formToolbar": {
		"save": "Guardar",
		"saveAs": "Guardar como",
		"autoSave": "Guardar automáticamente",
		"preview": "vista previa",
		"help": "ayuda",
		"build": "Publica la tabla de datos e ingresa el estado compilable",
		"statusDraft": "Cancele la compilación de la base de datos y la tabla de datos compilada se eliminará al volver a compilar",
		"bulidCurrentApp": "Compile todas las tablas de datos de la aplicación actual",
		"tableExplode": "Exportación de datos",
		"tableImplode": "Importación de datos",
		"tableExcelExplode": "Exportar a Excel",
		"tableExcelImplode": "Importación de Excel",
		"tableClear": "Borrar datos de la tabla"
	}
}
MWF.xApplication.query.TableDesigner["lp."+o2.language] = MWF.xApplication.query.TableDesigner.LP