MWF.xApplication.query.TableDesigner.LP = {
    "title": "데이터 테이블 디자인",
    "newTable": "새로운 데이터 테이블",
    "property": "속성",
    "item": "항목",
    "type": "유형",
    "value": "값",
    "stat": "통계",
    "unnamed": "제목 없는 열",
    "newColumn": "새로운 열",
    "unCategory": "미분류",
    "close": "닫기",

    "id": "아이디",
    "name": "이름",
    "alias": "별명",
    "description": "설명",

    "application": "데이터 응용 프로그램",
    "copyStat": "통계 복사",
    "newStatName": "새로운 통계 이름",
    "copy": "복사",
    "ok": "확인",
    "cancel": "취소",
    "view": "보기",
    "table": "데이터 테이블",
    "clumn": "열",
    "addLine": "데이터 추가",

    "jpqlType": "JPQL 유형",
    "jpqlFromResult": "쿼리 시작 항목",
    "jpqlMaxResult": "최대 결과 수",
    "jpqlSelectTitle": "JPQL 쿼리",
    "inputWhere": "아래 편집 상자에 Where 절을 입력할 수 있습니다",
    "jpqlRunSuccess": "JPQL 실행 성공",
    "newLineSuccess": "데이터 추가 성공",
    "newLineJsonError": "데이터 추가 오류, 데이터 형식이 잘못되었습니다",

    "action": {
        "move": "이동",
        "delete": "삭제",
        "add": "추가"
    },
    "errorName": "열 이름은 문자, 숫자 및 밑줄을 조합하여 사용할 수 있으며, 숫자나 대문자로 시작할 수 없습니다.",
    "nameUseKeywork": "열 이름에 {key}을(를) 사용할 수 없습니다.",
    "errorFieldList": "데이터 열을 먼저 만드십시오.",
    "duplicateName": "동명의 열이 이미 존재합니다.",
    "inputName": "열 이름을 입력하십시오.",
    "inputTableName": "데이터 테이블 이름을 입력하십시오.",
    "tableNameNotStartWithLetter": "데이터 테이블 이름은 문자로 시작해야 합니다.",
    "tableAliasNotStartWithLetter": "데이터 테이블 별칭은 문자로 시작해야 합니다.",
    "tableNameNotBeLetterAndNumber": "데이터 테이블 이름은 문자 또는 문자와 숫자 조합이어야 합니다.",
    "tableAliasNotBeLetterAndNumber": "데이터 테이블 별칭은 문자 또는 문자와 숫자 조합이어야 합니다.",
    "save_success": "데이터 테이블 저장 성공!",
    "deleteColumnTitle": "열 삭제 확인",
    "deleteColumn": "현재 열을 삭제하시겠습니까?",
    "statusBuildTitle": "데이터 테이블 배포",
    "statusBuildInfor": "현재 데이터 테이블은 컴파일 환경에 게시됩니다. 열을 삭제하거나 열 유형을 수정한 경우 데이터베이스 테이블을 수동으로 삭제해야 할 수도 있습니다. 이 작업을 수행하시겠습니까?",
    "statusDraftTitle": "데이터 테이블 컴파일 취소",
    "statusDraftInfor": "<span style='color: #FF0000;'>참고: 이 데이터 테이블을 컴파일 환경에서 제거하고 다음 컴파일 시 데이터베이스 테이블이 삭제됩니다.</span><br><br>이 작업을 수행하시겠습니까?",
    "statusDraftInforAgain": "<span style='color: #FF0000;'>참고: 이 데이터 테이블을 컴파일 환경에서 제거하고 현재 데이터 테이블을 사용할 수 없게 됩니다. 이것은 이미 이 데이터 테이블을 사용하는 관련 응용 프로그램에 영향을 줄 수 있습니다.</span><br><br>이 작업을 다시 한 번 확인하시겠습니까?",
    "statusBuild_success": "현재 데이터 테이블은 컴파일 환경에 게시되었으며, 이를 적용하려면 '모두 컴파일'을 실행해야 합니다.",
    "statusDraft_success": "현재 데이터 테이블은 컴파일 환경에서 제거되었으며, 다음 '모두 컴파일' 시에 데이터베이스에서 테이블이 삭제됩니다.",
    "buildAllViewTitle": "모든 데이터 테이블 컴파일",
    "tableExplodeTitle": "데이터 내보내기",
    "tableExplodeInfo": "기본적으로 최대 2000행까지 내보내기 가능합니다. 내보낼 것인가 확인하시겠습니까?",
    "tableExplode_success": "내보내기 성공",

    "buildNoTableError": "현재 앱에는 아직 데이터 테이블이 없으므로 컴파일이 필요하지 않습니다.",
    "buildCurrentAppTitle": "현재 앱 데이터 테이블 컴파일",
    "buildCurrentAppInfor": "다음 데이터 테이블이 컴파일됩니다:</br>{buildlist}",
    "unbuildCurrentAppInfor": "다음 데이터 테이블은 컴파일하지 않거나 컴파일을 취소합니다:</br>{draftList}",
    "buildCurrentAppQuection": "</br>이 작업을 수행하시겠습니까?",
    "buildCurrentApp_success": "현재 앱 데이터 테이블이 성공적으로 컴파일되었습니다!",
    "building": "컴파일 중...",

    "tableImplodeTitle": "데이터 가져오기",
    "tableImplodeInfo": "가져온 데이터는 덮어씁니다. 가져올 것인가 확인하시겠습니까?",
    "tableExcelImplodeInfo": "가져온 데이터에 ID 필드가 있다면 덮어씁니다. 그렇지 않으면 추가합니다. 가져올 것인가 확인하시겠습니까?",
    "tableImplode_success": "가져오기 성공",

    "tableClearTitle": "데이터 지우기",
    "tableClearInfo": "지운 데이터는 복구할 수 없습니다! 지울 것인가 확인하시겠습니까?",
    "tableClear_success": "지우기 성공",
    "exportExcelFileName": "데이터 내보내기",

    "buildAllViewInfor": "모든 데이터 테이블을 컴파일하려고 합니다. 이는 모든 데이터 애플리케이션의 데이터 테이블을 포함하며, <span style='color: #FF0000;'>컴파일 후에 서버를 즉시 다시 시작해야 합니다. 그렇지 않으면 JVM 충돌이 발생할 수 있습니다.</span> 이 작업을 실행하시겠습니까?",
    "buildAllView_success": "모든 데이터 테이블이 컴파일되었습니다. 서버를 즉시 다시 시작하십시오!",
    "tableHelp": "데이터 테이블은 시스템 데이터베이스에서 실제 테이블을 자동으로 생성하고 Java 엔터티 객체를 생성하며, JPQL을 사용하여 데이터 테이블을 조작할 수 있습니다. 데이터 테이블을 생성하려면 다음 단계를 따르십시오：<br><br>1. 데이터 테이블을 만들고 각 열을 생성하십시오.<br>2. 도구 모음 버튼을 클릭하여 데이터 테이블을 컴파일 상태로 게시하십시오.<br>3. 도구 모음 버튼을 클릭하여 '현재 애플리케이션의 모든 데이터 테이블을 컴파일' 작업을 실행하십시오. 성공한 후 데이터 테이블을 사용할 수 있습니다.",

    
	"propertyTemplate": {
        "base": "기본",
        "event": "이벤트",
        "html": "HTML",
        "json": "JSON",
        "action": "작업",
        "select": "선택",
        "alias": "별칭",
        
        "id": "식별자",
        "name": "이름",
        "description": "설명",
        "style": "스타일",
        "attribute": "속성",
        "type": "유형",
        "status": "상태",
        "draft": "드래프트",
        "published": "게시됨",
        
        "authority": "권한",
        "readPersonList": "읽을 수 있는 사람",
        "readUnitList": "읽을 수 있는 단위",
        "editPersonList": "편집 가능한 사람",
        "editUnitList": "편집 가능한 단위"
    }
};
