MWF.xApplication.query.TableDesigner.LP = {
    "title": "Data Sheet Design",
    "newTable": "New Data Table",
    "property": "ຄຸນສົມບັດ",
    "item": "Item",
    "type": "ປະເພດ",
    "value": "Value",
    "stat": "ສະຖິຕິ",
    "unnamed": "ບໍ່ມີຖັນ",
    "newColumn": "ຖັນໃໝ່",
    "unCategory": "ປະເພດ",
    "close": "ປິດ",

    "id": "ID",
    "name": "ຊື່",
    "alias": "ຊື່ແຝງ",
    "description": "ອະທິບາຍ",

    "application": "Data Application",
    "copyStat": "ສຳເນົາສະຖິຕິ",
    "newStatName": "ຊື່ສະຖິຕິໃໝ່",
    "copy": "ສຳເນົາ",
    "ok": "ຢືນຢັນ",
    "cancel": "ຍົກເລີກ",
    "view": "View",
    "table": "ຂໍ້ມູນຕາຕະລາງ",
    "clumn": "ຖັນ",
    "addLine": "ເພີ່ມຂໍ້ມູນ",

    "jpqlType": "JPQLປະເພດ",
    "jpqlFromResult": "ລາຍການເລີ່ມຕົ້ນ Query ",
    "jpqlMaxResult": "ຜົນລັບສູງສຸດ",
    "jpqlSelectTitle": "JPQLStatement",
    "inputWhere": "ເຈົ້າສາມາດປ້ອນຄຳສັ່ງໃນບ່ອນແກ້ໄຂ Where ໃນກ່ອງທາງລຸ່ມ",
    "jpqlRunSuccess": "JPQLການດຳເນີນສຳເລັດ",
    "newLineSuccess": "ເພີ່ມຂໍ້ມູນສຳເລັດ",
    "newLineJsonError": "ເພີ່ມຂໍ້ມູນຜິດພາດ，ຮູບແບບຂໍ້ມູນບໍ່ຖືກຕ້ອງ",

    "action": {
        "move": "ຍ້າຍ",
        "delete": "ລົບ",
        "add": "ເພີ່ມ"
    },
    "errorName": "ອະນຸຍາດໃຫ້ໃຊ້ການປະສົມຕົວອັກສອນ, ຕົວເລກ ແລະ Symbol，ແລະຕ້ອງບໍ່ໃຫ້ຂຶ້ນຕົ້ນດ້ວຍຕົວເລກແລະຕົວອັກສອນພິມໃຫ່ຍ。",
    "nameUseKeywork": "ບໍ່ໄດ້ຮັບອານຸຍາດສຳລັບຖັນ{key}",
    "errorFieldList": "ກະລຸນາສ້າງຂໍ້ມູນຖັນກ່ອນ。",
    "duplicateName": "ມີຊື່ຖັນທີ່ຕົງກັນ",
    "inputName": "ກະລຸນາປ້ອນຊື່ຖັນ",
    "inputTableName": "ກະລຸນາປ້ອນຊື່ຕາຕະລາງຂໍ້ມູນ",
    "tableNameNotStartWithLetter": "ຊື່ຕາຕະລາງຂໍ້ມູນຕ້ອງຂຶ້ນຕົ້ນດ້ວຍຕົວອັກສອນ",
    "tableAliasNotStartWithLetter": "ຊື່ແຝງຕາລະລາງຕ້ອງຂຶ້ນຕົ້ນດ້ວຍຕົວອັກສອນ",
    "tableNameNotBeLetterAndNumber": "ຊື່ຕາຕະລາງຂໍ້ມູນຕ້ອງເປັນຕົວອັກສອນທັງໝົດ ຫຼືເພີ່ມຕົວເລກ",
    "tableAliasNotBeLetterAndNumber": "ຊື່ແຝງຕາຕະລາງຂໍ້ມູນຕ້ອງເປັນຕົວອັກສອນທັງໝົດ ຫຼືເພີ່ມຕົວເລກ",
    "save_success": "ຕາຕະລາງຂໍ້ມູນບັນທຶກສຳເລັດ！",
    "deleteColumnTitle": "ຢືນຢັນລົບຖັນ",
    "deleteColumn": "ແນ່ໃຈຫຼືບໍ່ຕ້ອງການລົບຖັນ？",
    "statusBuildTitle": "ເຜີຍແຜ່ຕາຕະລາງຂໍ້ມູນ",
    "statusBuildInfor": "ຂໍ້ມູນຕາຕະລາງປະຈຸບັນຈະຖືກເຜີຍແຜ່ໄປທີ່compilation environment ，ຖ້າເຈົ້າລົບຖັນຫຼືປ່ຽນແປງປະເພດຖັນ，ເຈົ້າສາມາລົບຕາຕະລາງຂໍ້ມູນໄດ້ດ້ວຍຕົນເອງ。ເຈົ້າແນ່ໃຈທີ່ຈະດຳເນີນການນີ້ບໍ່？",
    "statusDraftTitle": "ຍົກເລີກການຮອບຮວມຕາຕະລາງຂໍ້ມູນ",
    "statusDraftInfor": "<span style='color: #FF0000;'>ໝາຍເຫດ：ເຈົ້າກຳລັງລົບຕາຕະລາງນີ້ອອກຈາກcompilation environment，compilationຈະລົບຕາຕະລາງຖານຂໍ້ມູນ。</span><br><br>ເຈົ້າແນ່ໃຈທີ່ຈະດຳເນີນການນີ້ບໍ່?",
    "statusDraftInforAgain": "<span style='color: #FF0000;'>ໝາຍເຫດ：ເຈົ້າກຳລັງລົບຕາຕະລາງນີ້ອອກຈາກcompilation environment，ເຈົ້າຈະບໍ່ສາມາດໃຊ້ຕາຕະລາງຂໍ້ມູນປະຈຸບັນໄດ້，ຊຶ່ງຈະສົ່ງຜົນຕໍ່ຂໍ້ມູນຕາຕະລາງປະຈຸບັນທີ່ໃຊ້ຂໍ້ມູນນີ້。</span><br><br>ເຈົ້າແນ່ໃຈທີ່ຈະດຳເນີນການນີ້ອີກຄັ້ງ？",
    "statusBuild_success": "ຂໍ້ມູນຕາຕະລາງປະຈຸບັນຈະຖືກເຜີຍແຜ່ໄປທີ່compilation environment，ເຈົ້າຕ້ອງໃຊ້“compilation ທັງໝົດ”ເພື່ອໃຫ້ເກີດຜົນ",
    "statusDraft_success": "ຂໍ້ມູນຕາຕະລາງປະຈຸບັນຈະຖືກຍົກເລີກເຜີຍແຜ່ໄປທີ່compilation environment，ຕໍ່ໄປ“compilation ທັງໝົດ”ຕາຕະລາງຈະຖືກລົບອອກຈາກຖານຂໍ້ມູນ",
    "buildAllViewTitle": "ຍົກເລີກຕຕະລາງ compilation ທັງໝົດ ",
    "tableExplodeTitle": "ນໍາອອກຂໍ້ມູນ",
    "tableExplodeInfo": "ສາມາດນຳອອກໄດ້ສູງສຸດ 2000ແຖວ。ຢືນຢັນນຳອອກຫຼືບໍ່？",
    "tableExplode_success": "ນຳອອກສຳເລັດ",

    "buildNoTableError": "ປະຈຸບັນ application ບໍ່ມີ ຂໍ້ມູນຕາຕະລາງ ，ບໍ່ຈຳເປັນຕ້ອງຮອບຮວມ。",
    "buildCurrentAppTitle": "ສ້າງ application ຕາຕະລາງຂໍ້ມູນ ",
    "buildCurrentAppInfor": "ຕາຕະລາງຂໍ້ມູນຕໍ່ໄປນີ້ຈະຖືກຮອບຮ່ວມ：</br>{buildlist}",
    "unbuildCurrentAppInfor": "ຕາຕະລາງຕໍ່ໄປນີ້ບໍ່ໄດ້ຮອບຮ່ວມຫຼືຍົກເລີກການຮອບຮ່ວມ：</br>{draftList}",
    "buildCurrentAppQuection": "</br>ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການດຳເນີນການນີ້？",
    "buildCurrentApp_success": "ຕາຕະລາງຂໍ້ມູນທັງໝົດຂອງ applicationປະຈຸບັນໄດ້ຖືກຮອບຮວມແລ້ວ！",
    "building": "ກຳລັງສ້າງ...",

    "tableImplodeTitle": "ນຳເຂົ້າຂໍ້ມູນ",
    "tableImplodeInfo": "ຂໍ້ມູນນຳເຂົ້າຈະຖືກແທນທີ່。ຢືນຢັນນຳເຂົາຫຼືບໍ່？",
    "tableExcelImplodeInfo": "ຖ້ານຳເຂົ້າຂໍ້ມູນມີ id field ，ສາມາຊ້ອນທັບ，ບໍ່ສະນັ້ນຈະຖືກເພີ່ມ。ຢືນຢັນນຳເຂົ້າຫຼືບໍ່？",
    "tableImplode_success": "ນຳເຂົ້າສຳເລັດ",

    "tableClearTitle": "ລ້າງຂໍ້ມູ",
    "tableClearInfo": "ລ້າງຂໍ້ມູນບໍ່ສາມາດກູ້ຄືນໄດ້！！ຢືນຢັນລ້າງຫຼືບໍ່？",
    "tableClear_success": "ລ້າງສຳເລັດ",
    "exportExcelFileName": "ນຳອອກຂໍ້ມູນ",

    "buildAllViewInfor": "ຂໍ້ມູນທັງໝົດຈະຖືກຮອບຮວມ, ລວມຕາຕະລາງຂໍ້ມູນໃນdata applicationsທັງໝົດ，<span style='color: #FF0000;'>ຫຼັງຈາກຮອບຮວມແລ້ວໃຫ້ເລີ່ມຕົ້ນເປີດເຄື່ອງໃໝ່ທັງທີ່，ບໍ່ສະນັ້ນ JVM ອາດຈະຢຸດການເຮັດວຽກ</span>。ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການດຳເນີນການນີ້？",
    "buildAllView_success": "ຂໍ້ມູນຕາຕະລາງທັງໝົດໄດ້ຖືກຮອບຮວມແລ້ວ，ກະລຸນາເລີ່ມຕົ້ນໃໝ່ທັນທີ່！",
    // "tableHelp": "ຕາຕະລາງຂໍ້ມູນສາມາດສ້າງຕາຕະລາງຈິງໃນລະບົບຖານຂໍ້ມູນເປັນອັດຕາໂນມັດ，ສ້າງດ້ວຍ java，ເຈົ້າສ້າມາດໃຊ້JPQLດຳເນີນຕາຕະລາງຂໍ້ມູນ。ສ້າງຕາຕະລາງຂໍ້ມູນຕ້ອງມີຂັ້ນຕອນດັ່ງນີ້：<br><br>1、ສ້າງຕາຕະລາງຂໍ້ມູນ，ແລະສ້າງແຕ່ລະຖັນ；<br>2、ກົດປຸ່ມແຖບtoolbar，ເຜີຍແຜ່ຂໍ້ມູນໄປທີ່ສະຖານະທີ່ຮວບຮວມແລ້ວ；<br>3、ກົດປຸ່ມແຖບtoolbar, ດຳເນີນການ"ຮວບຮວມຕາຕະລາງຂໍ້ມູນທັງໝົດຂອງ application ປະຈຸບັນ"<br>4、ເລີ່ມຕົ້ນserverໃໝ່(ບໍ່ສະນັ້ນອາດຈະເຮັດໃຫ້JVMຢຸດເຮັດວຽກ)，ຂໍ້ມູນຕາຕະລາງພ້ອມໃຊ້ງານໄດ້。",

    "tableHelp": "ຕາຕະລາງຂໍ້ມູນສາມາດສ້າງຕາຕະລາງຈິງໃນລະບົບຖານຂໍ້ມູນເປັນອັດຕາໂນມັດ，ສ້າງດ້ວຍ java，ເຈົ້າສ້າມາດໃຊ້JPQLດຳເນີນຕາຕະລາງຂໍ້ມູນ。ສ້າງຕາຕະລາງຂໍ້ມູນຕ້ອງມີຂັ້ນຕອນດັ່ງນີ້：<br><br>1、ສ້າງຕາຕະລາງຂໍ້ມູນ，ແລະສ້າງແຕ່ລະຖັນ；<br>2、ກົດປຸ່ມແຖບtoolbar，ເຜີຍແຜ່ຂໍ້ມູນໄປທີ່ສະຖານະທີ່ຮວບຮວມແລ້ວ；<br>3、ກົດປຸ່ມແຖບtoolbar，ດຳເນີນການ“ຮວບຮວມຕາຕະລາງຂໍ້ມູນທັງໝົດຂອງ application ປະຈຸບັນ”，ຫຼັງຈາກສຳເລັດແລ້ວຂໍ້ມູນຕາຕະລາງກໍສາມາດໃຊ້ງານໄດ້。",

    "propertyTemplate": {
        "base": "ພື້ນຖານ",
        "event": "ເຫດການ",
        "html": "HTML",
        "json": "JSON",
        "action": "ດຳເນີນ",
        "select": "ເລືອກ",
        "alias": "ຊື່ນາມແຝງ",

        "id": "Id",
        "name": "ຊື່",
        "description": "ອະທິບາຍ",
        "style": "ຮູບແບບ",
        "attribute": "ຄຸນສົມບັດ",
        "type": "ປະເພດ",
        "status": "ສະຖານະ",
        "draft": "ຮ່າງສະບັບ",
        "published": "ເຜີຍແຜ່",

        "authority": "ດຳເນີນການອະນຸຍາດ",
        "readPersonList": "ຄົນສາມາດອ່ານ",
        "readUnitList": "ສາມາດອ່ານອົງກອນ",
        "editPersonList": "ຄົນສາມາດແກ້ໄຂ",
        "editUnitList": "ຄົນສາມາດແກ້ໄຂອົງກອນ"
    }
};
