MWF.xApplication.query.TableDesigner.LP = {
    "title": "数据表设计",
    "newTable": "新建数据表",
    "property": "属性",
    "item": "项目",
    "type": "类型",
    "value": "值",
    "stat": "统计",
    "unnamed": "无标题列",
    "newColumn": "新建列",
    "unCategory": "未分类",
    "close": "关闭",

    "id": "标识",
    "name": "名称",
    "alias": "别名",
    "description": "描述",

    "application" : "数据应用",
    "copyStat" : "拷贝统计",
    "newStatName" : "新统计名称",
    "copy" : "副本",
    "ok" : "确定",
    "cancel" : "取消",
    "view" : "视图",
    "table": "数据表",
    "clumn": "列",
    "addLine": "添加数据",

    "jpqlType": "JPQL类型",
    "jpqlFromResult": "查询开始条目",
    "jpqlMaxResult": "最大返回结果",
    "jpqlSelectTitle": "JPQL语句",
    "inputWhere": "您可以在下面的编辑框输入Where子句",
    "jpqlRunSuccess": "JPQL执行成功",
    "newLineSuccess": "插入数据成功",
    "newLineJsonError": "插入数据错误，数据格式有误",

    "action": {
        "move": "移动",
        "delete": "删除",
        "add": "添加"
    },
    "errorName": "列名只允许使用字母数字和下划线组合，并且不能以数字开头。",
    "errorFieldList": "请先创建数据列。",
    "duplicateName": "同名的列已存在",
    "inputName": "请输入列名称",
    "inputTableName": "请输入数据表名称",
    "save_success": "数据表保存成功！",
    "deleteColumnTitle": "删除列确认",
    "deleteColumn": "是否确定删除当前列？",
    "statusBuildTitle": "发布数据表",
    "statusBuildInfor": "当前数据表将会发布到编译环境，如果您删除了列或修改了列的类型，您可能需要手工删除数据库表。您确定要执行此操作吗？",
    "statusDraftTitle": "取消编译数据表",
    "statusDraftInfor": "<span style='color: #FF0000;'>注意：您正在将此数据表从编译环境中删除，下次编译会删除数据库表。</span><br><br>您确定要执行此操作吗？",
    "statusDraftInforAgain": "<span style='color: #FF0000;'>注意：您正在将此数据表从编译环境中删除，您将无法使用当前数据表，这可能会影响到已使用此数据表的相关应用。</span><br><br>请再次确认要执行此操作吗？",
    "statusBuild_success": "当前数据表已经发布到编译环境，您需要运行“全部编译”使其生效",
    "statusDraft_success": "当前数据表已从编译环境取消，下次“全部编译”时会删除从数据库中删除表",
    "buildAllViewTitle": "编译所有数据表",
    "tableExplodeTitle": "导出数据",
    "tableExplodeInfo": "默认最多导出1000行。确认是否导出？",
    "tableExplode_success": "导出成功",

    "tableImplodeTitle": "导入数据",
    "tableImplodeInfo": "导入的数据会覆盖。确认是否导入？",
    "tableImplode_success": "导入成功",


    "buildAllViewInfor": "即将编译所有数据表，包括所有数据应用中的数据表，编译后您可能需要重启服务器后才能使用此数据表。您确定要执行此操作吗？",
    "buildAllView_success": "已编译所有数据表，新的更改需要您重启服务器后生效",
    "tableHelp": "数据表能够在系统数据库中自动创建真实表，并生成java实体对象，您可以使用JPQL操作数据表。创建数据表需要以下步骤：<br><br>1、创建数据表，并创建每一列；<br>2、点击工具栏按钮，将数据表发布到编译状态；<br>3、点击工具栏按钮，执行“编译所有数据表”操作<br>4、重启服务器，数据表就可以使用了。"
};