MWF.xApplication.query.TableDesigner.LP = {
    "title": "數據表設計",
    "newTable": "新建數據表",
    "property": "屬性",
    "item": "項目",
    "type": "類型",
    "value": "值",
    "stat": "統計",
    "unnamed": "無標題列",
    "newColumn": "新建列",
    "unCategory": "未分類",
    "close": "關閉",

    "id": "標識",
    "name": "名稱",
    "alias": "別名",
    "description": "描述",

    "application": "數據應用",
    "copyStat": "複製統計",
    "newStatName": "新統計名稱",
    "copy": "複製",
    "ok": "確定",
    "cancel": "取消",
    "view": "視圖",
    "table": "數據表",
    "clumn": "列",
    "addLine": "添加數據",

    "jpqlType": "JPQL類型",
    "jpqlFromResult": "查詢開始項目",
    "jpqlMaxResult": "最大返回結果",
    "jpqlSelectTitle": "JPQL語句",
    "inputWhere": "您可以在下面的編輯框輸入Where子句",
    "jpqlRunSuccess": "JPQL執行成功",
    "newLineSuccess": "插入數據成功",
    "newLineJsonError": "插入數據錯誤，數據格式有誤",

    "action": {
        "move": "移動",
        "delete": "刪除",
        "add": "添加"
    },
    "errorName": "列名只允許使用字母、數字和底線組合，且不可以數字和大寫字母開頭。",
    "nameUseKeywork": "列名不允許使用{key}",
    "errorFieldList": "請先創建數據列。",
    "duplicateName": "同名的列已存在",
    "inputName": "請輸入列名稱",
    "inputTableName": "請輸入數據表名稱",
    "tableNameNotStartWithLetter": "數據表名稱必須以字母開頭",
    "tableAliasNotStartWithLetter": "數據表別名必須以字母開頭",
    "tableNameNotBeLetterAndNumber": "數據表名稱必須是全字母或字母加數字",
    "tableAliasNotBeLetterAndNumber": "數據表別名必須是全字母或字母加數字",
    "save_success": "數據表保存成功！",
    "deleteColumnTitle": "刪除列確認",
    "deleteColumn": "是否確定刪除當前列？",
    "statusBuildTitle": "發佈數據表",
    "statusBuildInfor": "當前數據表將會發佈到編譯環境，如果您刪除了列或修改了列的類型，您可能需要手工刪除數據庫表。您確定要執行此操作嗎？",
    "statusDraftTitle": "取消編譯數據表",
    "statusDraftInfor": "<span style='color: #FF0000;'>注意：您正在將此數據表從編譯環境中刪除，下次編譯會刪除數據庫表。</span><br><br>您確定要執行此操作嗎？",
    "statusDraftInforAgain": "<span style='color: #FF0000;'>注意：您正在將此數據表從編譯環境中刪除，您將無法使用當前數據表，這可能會影響到已使用此數據表的相關應用。</span><br><br>請再次確認要執行此操作嗎？",
    "statusBuild_success": "當前數據表已經發佈到編譯環境，您需要運行“全部編譯”使其生效",
    "statusDraft_success": "當前數據表已從編譯環境取消，下次“全部編譯”時會刪除從數據庫中刪除表",
    "buildAllViewTitle": "編譯所有數據表",
    "tableExplodeTitle": "導出數據",
    "tableExplodeInfo": "默認最多導出2000行。確認是否導出？",
    "tableExplode_success": "導出成功",

    "buildNoTableError": "當前應用還沒有數據表，不需要編譯。",
    "buildCurrentAppTitle": "編譯當前應用數據表",
    "buildCurrentAppInfor": "下列數據表將被編譯：</br>{buildlist}",
    "unbuildCurrentAppInfor": "下列數據表不編譯或取消編譯：</br>{draftList}",
    "buildCurrentAppQuection": "</br>您確定要執行此操作嗎？",
    "buildCurrentApp_success": "已編譯當前應用數據表！",
    "building": "正在編譯...",

    "tableImplodeTitle": "導入數據",
    "tableImplodeInfo": "導入的數據會覆蓋。確認是否導入？",
    "tableExcelImplodeInfo": "導入的數據如果有id字段，會覆蓋，否則會新增。確認是否導入？",
    "tableImplode_success": "導入成功",

    "tableClearTitle": "清空數據",
    "tableClearInfo": "清空的數據不能恢復！！確認是否清空？",
    "tableClear_success": "清空成功",
    "exportExcelFileName": "導出數據",

    "buildAllViewInfor": "即將編譯所有數據表，包括所有數據應用中的數據表，<span style='color: #FF0000;'>編譯後您請馬上重啟伺服器，否則可能造成JVM崩潰</span>。您確定要執行此操作嗎？",
    "buildAllView_success": "已編譯所有數據表，請馬上重啟伺服器！",
    "tableHelp": "數據表能夠在系統數據庫中自動創建真實表，並生成Java實體對象，您可以使用JPQL操作數據表。創建數據表需要以下步驟：<br><br>1、創建數據表，並創建每一列；<br>2、點擊工具欄按鈕，將數據表發佈到編譯狀態；<br>3、點擊工具欄按鈕，執行“編譯當前應用所有數據表”操作，成功後數據表就可使用了。",


    "propertyTemplate": {
        "base": "基本",
        "event": "事件",
        "html": "HTML",
        "json": "JSON",
        "action": "操作",
        "select": "選擇",
        "alias": "別名",

        "id": "標識",
        "name": "名稱",
        "description": "描述",
        "style": "樣式",
        "attribute": "屬性",
        "type": "類型",
        "status": "狀態",
        "draft": "草稿",
        "published": "已發布",

        "authority": "執行權限",
        "readPersonList": "可讀人",
        "readUnitList": "可讀組織",
        "editPersonList": "可編輯人",
        "editUnitList": "可編輯組織"
    }
};
