MWF.xApplication.ProcessTool.LP = {
	"title": "流程维护",

	"data_title" : "标题",
	"data_activityName" : "状态",
	"data_applicationName" : "应用",
	"data_processName" : "流程",
	"data_person" : "处理人",
	"data_unit" : "处理部门",
	"data_creatorPerson" : "创建人",
	"data_creatorUnit" : "创建部门",
	"data_createTime" : "创建时间",
	"data_op" : "操作",

	"data_fromIdentity" : "授权人",
	"data_toIdentity" : "被授权人",
	"data_type" : "授权类型",
	"data_startTime" : "授权开始时间",
	"data_completedTime" : "授权结束时间",
	"data_enable" : "是否启用",
	"data_empowerTime" :"授权时间",
	"data_processOrApplicatinonName" : "流程/应用",

	"person" : "用户",
	"node": "节点",
	"clientIp": "客户端IP",
	"module": "模块",
	"operation": "操作",
	"httpType": "类型",
	"httpStatus": "状态",
	"httpUrl": "请求地址",
	"startTime": "开始",
	"endTime": "结束",
	"createTime": "开始时间",
	"updateTime": "结束时间",
	"requestTime": "请求时间",
	"spendTime": "执行持续时间(毫秒)",
	"spendTime1": "执行持续时间",
	"millisecond": "毫秒",
	"firstPage": "第一页",
	"lastPage": "最后一页",
	"query": "搜索",
	"reset": "重置",
	"reroute" : "调度",
	"rollback" : "回溯",
	"noItem": "当前条件下没有查询到数据",
	"all": "所有日志",
	"sendData": "请求数据",

	"cancel" : "取消",
	"close" : "关闭",
	"ok" : "确定",
	"edit" : "编辑",
	"remove" : "删除",
	"action" : "操作",
	"view": "查看",
	"setOpinion" : "意见修改",
	"flow": "流转",
	"readFlow" : "待阅转已阅",
	"resetAction" : "转交",
	"editAction" : "维护",

	"viewDetail": "查看详情",
	"logDetail": "日志详情",

	"yesterday": "昨天",
	"twoDaysAgo" : "前天",
	"weekAgo" : "周前",
	"dayAgo" : "天前",
	"hourAgo" : "小时前",
	"minuteAgo" : "分钟前",
	"justNow" : "刚才",
	"publishJustNow": "刚刚发表"
};
