MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.TaskCenter = MWF.xApplication.process.TaskCenter || {};
MWF.xApplication.process.TaskCenter.LP={
	"title": "Centro de oficina",
	"searchKey": "Ingrese la palabra clave",
	"task": "Pendiente",
	"done": "Completado",
	"draft": "Borrador",
	"myfile": "Mis archivos",
	"read": "Por leer",
	"readed": "Leído",
	"review": "A revisar",
	"start": "Iniciar",
	"startTop5": "Flujos de trabajo comunes",
	"startProcess": "Flujos de trabajo disponibles",
	"back": "Volver",
	"unnamed": "Sin título",
	"draftTab": "Borradores",
	"list_title": "Título",
	"list_application": "Aplicación",
	"list_process": "Flujo de trabajo",
	"list_activity": "Actividad",
	"list_owner": "Responsable",
	"list_creator": "Redactor",
	"list_departmet": "Departamento del redactor",
	"list_comedate": "Fecha de llegada",
	"list_createDate": "Fecha de redacción",
	"processStarted": "El archivo ha sido iniciado",
	"taskProcessed": "El archivo ha sido enviado",
	"taskProcessedMessage": "Ha procesado una tarea pendiente:",
	"nextActivity": "Siguiente actividad:",
	"nextUser": "Responsable:",
	"processStartedMessage": "Ha iniciado un nuevo trabajo:",
	"filter": "Filtrar",
	"all": "Todo",
	"ok": "Aceptar",
	"clear": "Limpiar",
	"currentFileStatus": "Estado actual del archivo",
	"fileat": "Archivo en",
	"flowto": "Flujo hacia",
	"doing": "Actualmente está siendo manejado por",
	"deal": "Manejar",
	"processing": "Procesando",
	"workCompleted": "El flujo de trabajo del archivo se ha completado",
	"completed": "Completado",
	"workProcess": "Continuar el flujo de trabajo",
	"applicationList": "Aplicación del flujo de trabajo",
	"processList": "Nombre del flujo de trabajo",
	"creatorUnitList": "Organización creadora",
	"creatorCompanyList": "Empresa creadora",
	"creatorDepartmentList": "Departamento creador",
	"activityNameList": "Actividad manejada",
	"completedTimeMonthList": "Fecha de finalización",
	"startTimeMonthList": "Fecha de llegada",
	"completedList": "Estado de finalización",
	"key": "Palabra clave",
	"year": "Año",
	"month": "Mes",
	"expire1": "Fecha límite de la tarea: {time}",
	"expire2": "La tarea está a punto de expirar, fecha límite: {time}",
	"expire3": "La tarea ha expirado, fecha límite: {time}",
	"unit": "Organización",
	"duty": "Posición",
	"searchProcess": "Ingrese la palabra clave para buscar flujos de trabajo disponibles",
	"searchProcessResault": "Resultados de búsqueda para ”{key}“",
	"datch": "Procesamiento por lotes",
	"setReaded": "Marcar como leído",
	"setReadedConfirmContent": "¿Está seguro de que desea marcar “{title}” como leído?",
	"setReadedConfirmTitle": "Confirmación",
	"open": "Abrir",
	"workcenter": "El nuevo centro de oficina ya está en línea. ¿Desea cambiar al nuevo centro de oficina?",
	"gotoWorkcenter": "Cambiar al nuevo centro de oficina"
}
MWF.xApplication.process.TaskCenter["lp."+o2.language] = MWF.xApplication.process.TaskCenter.LP