/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.report.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.report.core.entity.Report_C_WorkProgDetail.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Dec 27 11:41:25 CST 2018")
public class Report_C_WorkProgDetail_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> id;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> keyWorkId;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> progId;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> progPersonId;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> progressContent;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> reportId;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> workContent;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> workInfoId;
    public static volatile SingularAttribute<Report_C_WorkProgDetail,String> workTitle;
}
