/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.report.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.report.core.entity.Report_I_WorkInfoDetail.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 21 15:31:57 CST 2018")
public class Report_I_WorkInfoDetail_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Report_I_WorkInfoDetail,String> describe;
    public static volatile SingularAttribute<Report_I_WorkInfoDetail,String> id;
    public static volatile SingularAttribute<Report_I_WorkInfoDetail,String> keyWorkId;
    public static volatile SingularAttribute<Report_I_WorkInfoDetail,String> reportId;
    public static volatile SingularAttribute<Report_I_WorkInfoDetail,String> workPlanSummary;
    public static volatile SingularAttribute<Report_I_WorkInfoDetail,String> workProgSummary;
}
