/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.report.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.report.core.entity.Report_P_ProfileDetail.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Dec 27 11:41:25 CST 2018")
public class Report_P_ProfileDetail_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> id;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> profileId;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> reportModule;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> reportModuleName;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> snapContent;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> snapType;
}
