/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrCenterWorkReportStatistic.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:18:45 CST 2016")
public class OkrCenterWorkReportStatistic_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> centerId;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> centerTitle;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,Date> createTime;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> defaultWorkLevel;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> defaultWorkType;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> id;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,Integer> month;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> reportStatistic;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> sequence;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> statisticCycle;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,Date> statisticTime;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,String> status;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,Date> updateTime;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,Integer> week;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,Integer> workCount;
    public static volatile SingularAttribute<OkrCenterWorkReportStatistic,Integer> year;
}
