/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrConfigSecretary.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:09:40 CST 2017")
public class OkrConfigSecretary_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrConfigSecretary,Date> createTime;
    public static volatile SingularAttribute<OkrConfigSecretary,String> description;
    public static volatile SingularAttribute<OkrConfigSecretary,String> id;
    public static volatile SingularAttribute<OkrConfigSecretary,String> leaderCompanyName;
    public static volatile SingularAttribute<OkrConfigSecretary,String> leaderIdentity;
    public static volatile SingularAttribute<OkrConfigSecretary,String> leaderName;
    public static volatile SingularAttribute<OkrConfigSecretary,String> leaderOrganizationName;
    public static volatile SingularAttribute<OkrConfigSecretary,String> secretaryCompanyName;
    public static volatile SingularAttribute<OkrConfigSecretary,String> secretaryIdentity;
    public static volatile SingularAttribute<OkrConfigSecretary,String> secretaryName;
    public static volatile SingularAttribute<OkrConfigSecretary,String> secretaryOrganizationName;
    public static volatile SingularAttribute<OkrConfigSecretary,String> sequence;
    public static volatile SingularAttribute<OkrConfigSecretary,Date> updateTime;
}
