/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrErrorSystemIdentityInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:35:29 CST 2017")
public class OkrErrorSystemIdentityInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrErrorSystemIdentityInfo,Date> createTime;
    public static volatile SingularAttribute<OkrErrorSystemIdentityInfo,String> flag;
    public static volatile SingularAttribute<OkrErrorSystemIdentityInfo,String> id;
    public static volatile SingularAttribute<OkrErrorSystemIdentityInfo,String> identity;
    public static volatile SingularAttribute<OkrErrorSystemIdentityInfo,String> sequence;
    public static volatile SingularAttribute<OkrErrorSystemIdentityInfo,Date> updateTime;
}
