/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrUserInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:18:45 CST 2016")
public class OkrUserInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrUserInfo,Date> createTime;
    public static volatile SingularAttribute<OkrUserInfo,String> customContent;
    public static volatile SingularAttribute<OkrUserInfo,String> id;
    public static volatile SingularAttribute<OkrUserInfo,String> sequence;
    public static volatile SingularAttribute<OkrUserInfo,Date> updateTime;
    public static volatile SingularAttribute<OkrUserInfo,String> userName;
}
