/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrWorkProblemInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:18:45 CST 2016")
public class OkrWorkProblemInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> centerId;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> centerTitle;
    public static volatile SingularAttribute<OkrWorkProblemInfo,Date> createTime;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> creatorCompanyName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> creatorIdentity;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> creatorName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> creatorOrganizationName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> currentProcessorCompanyName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> currentProcessorIdentity;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> currentProcessorName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> currentProcessorOrganizationName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> id;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> policynessDetail;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> problemDetail;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> processStatus;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> processType;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> recommendedSolution;
    public static volatile SingularAttribute<OkrWorkProblemInfo,Integer> reportCount;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> reporterCompanyName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> reporterIdentity;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> reporterName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> reporterOrganizationName;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> sequence;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> shortTitle;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> status;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> title;
    public static volatile SingularAttribute<OkrWorkProblemInfo,Date> updateTime;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> workId;
    public static volatile SingularAttribute<OkrWorkProblemInfo,String> workTitle;
}
