/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrWorkDetailInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:09:40 CST 2017")
public class OkrWorkDetailInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> centerId;
    public static volatile SingularAttribute<OkrWorkDetailInfo,Date> createTime;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> dutyDescription;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> id;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> landmarkDescription;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> majorIssuesDescription;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> progressAction;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> progressPlan;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> resultDescription;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> sequence;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> status;
    public static volatile SingularAttribute<OkrWorkDetailInfo,Date> updateTime;
    public static volatile SingularAttribute<OkrWorkDetailInfo,String> workDetail;
}
