/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrWorkProblemProcessLog.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:18:45 CST 2016")
public class OkrWorkProblemProcessLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> activityName;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,Date> arriveTime;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> arriveTimeStr;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> centerId;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> centerTitle;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,Date> createTime;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> decision;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> id;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> opinion;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,Integer> processLevel;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,Date> processTime;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> processTimeStr;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> processorCompanyName;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> processorIdentity;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> processorName;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> processorOrganizationName;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> reportTitle;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> sequence;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> status;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,Long> stayTime;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> title;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,Date> updateTime;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> workId;
    public static volatile SingularAttribute<OkrWorkProblemProcessLog,String> workReportId;
}
