/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrWorkBaseInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:09:40 CST 2017")
public class OkrWorkBaseInfo_ extends SliceJpaObject_  {
    public static volatile ListAttribute<OkrWorkBaseInfo,String> attachmentList;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> centerId;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> centerTitle;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Date> completeDateLimit;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> completeDateLimitStr;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> confirmDateStr;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> cooperateCompanyName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> cooperateEmployeeName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> cooperateIdentity;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> cooperateOrganizationName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Date> createTime;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> creatorCompanyName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> creatorIdentity;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> creatorName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> creatorOrganizationName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> deployDateStr;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> deployMonth;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> deployYear;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> deployerCompanyName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> deployerIdentity;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> deployerName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> deployerOrganizationName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> id;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Boolean> isCompleted;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Boolean> isNeedReport;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Boolean> isOverTime;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Date> lastReportTime;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Date> nextReportTime;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Double> overallProgress;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> parentWorkId;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> parentWorkTitle;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> progressAnalyseTime;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> readLeaderCompanyName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> readLeaderIdentity;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> readLeaderName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> readLeaderOrganizationName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> reportAdminIdentity;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> reportAdminName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Integer> reportCount;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> reportCycle;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Integer> reportDayInCycle;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Boolean> reportNeedAdminAudit;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> reportTimeQue;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> responsibilityCompanyName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> responsibilityEmployeeName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> responsibilityIdentity;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> responsibilityOrganizationName;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> sequence;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> shortDutyDescription;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> shortLandmarkDescription;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> shortMajorIssuesDescription;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> shortProgressAction;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> shortProgressPlan;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> shortResultDescription;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> shortWorkDetail;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> status;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> title;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Date> updateTime;
    public static volatile SingularAttribute<OkrWorkBaseInfo,Integer> workAuditLevel;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> workDateTimeType;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> workLevel;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> workProcessStatus;
    public static volatile SingularAttribute<OkrWorkBaseInfo,String> workType;
}
