/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.Route.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:03 CST 2018")
public class Route_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Route,String> activity;
    public static volatile SingularAttribute<Route,ActivityType> activityType;
    public static volatile SingularAttribute<Route,String> alias;
    public static volatile SingularAttribute<Route,String> description;
    public static volatile SingularAttribute<Route,String> id;
    public static volatile SingularAttribute<Route,String> name;
    public static volatile SingularAttribute<Route,String> opinion;
    public static volatile SingularAttribute<Route,Integer> orderNumber;
    public static volatile SingularAttribute<Route,Boolean> passExpired;
    public static volatile SingularAttribute<Route,Boolean> passSameTarget;
    public static volatile SingularAttribute<Route,String> position;
    public static volatile SingularAttribute<Route,String> process;
    public static volatile SingularAttribute<Route,String> script;
    public static volatile SingularAttribute<Route,String> scriptText;
    public static volatile SingularAttribute<Route,String> track;
}
