/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.TemplateForm.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:03 CST 2018")
public class TemplateForm_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<TemplateForm,String> alias;
    public static volatile SingularAttribute<TemplateForm,String> category;
    public static volatile SingularAttribute<TemplateForm,String> data;
    public static volatile SingularAttribute<TemplateForm,String> description;
    public static volatile SingularAttribute<TemplateForm,String> icon;
    public static volatile SingularAttribute<TemplateForm,String> id;
    public static volatile SingularAttribute<TemplateForm,String> mobileData;
    public static volatile SingularAttribute<TemplateForm,String> name;
    public static volatile SingularAttribute<TemplateForm,String> outline;
}
