MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Setting = MWF.xApplication.Setting || {};
MWF.xApplication.Setting.LP={
	"title": "Configuración del sistema",
	"default": "Por defecto",
	"tab_base": "Básico",
	"tab_ui": "Interfaz de usuario",
	"tab_mobile": "Oficina móvil",
	"tab_cloud": "Servicios en la nube",
	"tab_dispose": "Despliegue del sistema",
	"tab_name": "Nombre del sistema",
	"tab_user": "Usuarios del sistema",
	"tab_login": "Inicio de sesión del sistema",
	"tab_sso": "SSO del sistema",
	"tab_config": "Plataforma",
	"tab_cloud_connect": "Conexión",
	"tab_mobile_connect": "Conexión",
	"tab_mobile_module": "Módulos",
	"tab_mobile_style": "Estilo",
	"tab_mobile_mpweixin_menu": "Menú de cuenta pública",
	"tab_mobile_app_pack": "Empaquetado de aplicaciones móviles",
	"tab_ui_login": "Estilo de página de inicio de sesión",
	"tab_ui_index": "Estilo de la página principal",
	"tab_ui_module": "Despliegue de módulos",
	"tab_ui_resource": "Despliegue de recursos",
	"tab_ui_service": "Despliegue de servicios",
	"tab_ui_menu": "Edición de menús",
	"base_nameSetting": "Configure el nombre de su sistema",
	"base_title": "Nombre del sistema",
	"base_title_infor": "El nombre de su sistema que se mostrará en la página de inicio de sesión y en la barra de título del navegador.",
	"base_title_action": "Editar el nombre del sistema",
	"base_title_empty": "El nombre del sistema no puede estar vacío, por favor ingrese un nombre.",
	"base_footer": "Subtítulo del sistema",
	"base_footer_infor": "El subtítulo de su sistema que se mostrará debajo de la página de inicio de sesión.",
	"base_footer_action": "Editar el subtítulo del sistema",
	"base_version": "Versión actual del sistema",
	"base_personSetting": "Configuración básica de la cuenta de usuario del sistema",
	"base_UserPassword": "Contraseña predeterminada para nuevos usuarios",
	"base_UserPassword_infor": "Se utilizará la siguiente contraseña al crear nuevos usuarios, los cuales podrán modificarla después de iniciar sesión en el sistema",
	"base_UserPassword_action": "Modificar la contraseña predeterminada",
	"base_UserPassword_empty": "La contraseña predeterminada no puede estar vacía",
	"base_passwordPeriod": "Período de vencimiento de la contraseña (días)",
	"base_passwordPeriod_infor": "Los usuarios que no cambien su contraseña dentro de este período de días especificado serán obligados a hacerlo después de iniciar sesión. Si no lo hacen, no podrán ingresar al sistema.",
	"base_passwordPeriod_action": "Modificar el plazo de vencimiento de la contraseña",
	"base_adminPassword": "Contraseña del administrador principal",
	"base_adminPassword_infor": "Contraseña del administrador principal xadmin.",
	"base_adminPassword_action": "Modificar la contraseña del administrador principal",
	"base_adminPassword_confirm": "<div style='color:red'>La contraseña del administrador principal está relacionada con la contraseña predeterminada de la base de datos, entre otros aspectos. ¡Cuidado al modificarla! <br>Después de cambiar la contraseña, reinicie el sistema inmediatamente, de lo contrario podría fallar.</div><br>¿Está seguro de querer modificarlo?",
	"base_loginSetting": "Configuración de opciones de inicio de sesión de usuario",
	"base_captchaLogin": "Habilitar el inicio de sesión con captcha de imágenes",
	"base_captchaLogin_infor": "Al habilitar esta opción, será necesario ingresar correctamente el captcha de imágenes al iniciar sesión.",
	"base_captchaLogin_action": "",
	"base_codeLogin": "Habilitar el inicio de sesión con código SMS",
	"base_codeLogin_infor": "Al habilitar esta opción, se permitirá el inicio de sesión con código SMS.",
	"base_codeLogin_action": "",
	"base_bindLogin": "Habilitar el inicio de sesión con escaneo de código QR",
	"base_bindLogin_infor": "Al habilitar esta opción, se permitirá el inicio de sesión mediante el escaneo de códigos QR.",
	"base_faceLogin": "Habilitar el inicio de sesión con reconocimiento facial",
	"base_faceLogin_infor": "Al habilitar esta opción, se permitirá el inicio de sesión mediante reconocimiento facial. Los usuarios podrán configurar su característica facial en su configuración personal. Después de habilitar esta opción, debe crear una configuración SSO con el nombre 'face' y la clave 'xplatform' (esto es una función experimental que requiere https).",
	"base_faceApi": "Servicio de reconocimiento facial",
	"base_faceApi_action": "Editar el servicio de reconocimiento facial",
	"base_faceApi_delete": "Eliminar el servicio de reconocimiento facial",
	"base_faceApi_infor": "Utilice el servicio de reconocimiento facial face++. Puede editar su clave API y secreta API. Si no lo hace, el sistema utilizará una cuenta predeterminada, que estará limitada a un QPS.",
	"base_register": "Habilitar el registro autoasistido",
	"base_register_infor": "Indica si se permitirá el registro autoasistido como usuario del sistema, y qué opciones de registro se habilitarán.",
	"register_disable": "No permitir el registro autoasistido",
	"register_captcha": "Permitir el registro autoasistido con captcha de imágenes",
	"register_code": "Permitir el registro autoasistido con código SMS",
	"base_portalLogin": "Iniciar sesión mediante página de portal",
	"base_portalLogin_infor": "Puede utilizar una página de portal personalizada como página de inicio de sesión, y la plantilla de la página de inicio de sesión se puede descargar desde el mercado de aplicaciones.",
	"base_portalLogin_action": "",
	"base_loginPortalId": "Portal de inicio de sesión",
	"base_loginPortalId_infor": "Seleccione el portal de la página de inicio de sesión.",
	"base_portalIndex": "Usar página de portal como página de inicio del sistema",
	"base_portalIndex_infor": "Puede utilizar una página de portal personalizada como página de inicio del sistema, que se abrirá después de iniciar sesión.",
	"base_portalIndex_action": "",
	"base_indexPortalId": "Puerta de enlace de la página principal del sistema",
	"base_indexPortalId_infor": "Seleccione el portal para la página principal del sistema.",
	"base_temary": "Administración de tres niveles",
	"base_temary_info": "Administración de tres niveles (administrador del sistema, administrador de seguridad y auditor de seguridad). Reinicie el servidor para iniciar los registros después de habilitar esta función.",
	"base_temary_action": "",
	"base_ldap": "Habilitar autenticación LDAP",
	"base_ldap_infor": "Después de habilitar esto, los usuarios utilizan la autenticación LDAP para iniciar sesión, en lugar de usar la contraseña del sistema.",
	"base_ldap_action": "Editar configuración de autenticación LDAP",
	"base_ldap_enable": "Habilitado",
	"base_ldap_unenable": "No habilitado",
	"base_ssoSetting": "Configuración de autenticación y inicio de sesión único con otros sistemas",
	"base_ssos": "Configuración de autenticación",
	"base_sso_infor": "Puede crear la autenticación para varios sistemas, que se utiliza para inicio de sesión único y llamadas de servicio SSO.",
	"base_sso_action": "Agregar configuración de autenticación",
	"base_sso_editAction": "Editar configuración de autenticación",
	"base_oauths": "Configuración del cliente de OAUTH",
	"base_oauths_infor": "Si el sistema actúa como servidor de autenticación OAUTH2, puede configurar varios clientes de OAUTH aquí para autorizar a otros sistemas.",
	"base_oauths_action": "Agregar configuración de OAuth",
	"base_oauths_editAction": "Editar configuración de OAuth",
	"base_oauths_server": "Configuración del servidor de OAUTH",
	"base_oauths_infor_server": "Si se necesita autenticación a través de otro servidor OAUTH2 en este sistema, puede configurar varios servidores de OAUTH aquí.",
	"base_qyweixin": "Configuración de WeChat Enterprise",
	"base_qyweixin_infor": "El sistema se puede integrar con WeChat Enterprise. Configure la cuenta empresarial de WeChat y la clave primero.",
	"base_qyweixin_action": "Editar configuración de WeChat Enterprise",
	"base_dingding": "Configuración de DingTalk",
	"base_dingding_infor": "El sistema se puede integrar con DingTalk. Configure la cuenta empresarial de DingTalk y la clave primero.",
	"base_dingding_action": "Editar configuración de DingTalk",
	"mobile_connectSetting": "Configuración de conexión a la oficina móvil",
	"cloud_connectSetting": "Configuración de conexión a servicios en la nube",
	"mobile_connect_first_cloud_check": "1. Verificación de conexión de servicios en la nube",
	"mobile_connect_first_cloud_check_connected": "<span style='color: #5fbf78'> [Conectado e ingresado] </span>servicios en la nube",
	"mobile_connect_first_cloud_check_disconnected": "<span style='color: #ff0000'> [No conectado e ingresado] </span>servicios en la nube. ¡Regístrese e ingrese en la página de configuración de servicios en la nube!",
	"mobile_connect_connectSetting": "2. Configuración de conexión externa",
	"mobile_connect_third_mobile_connect_check": "3. Prueba de conexión móvil",
	"mobile_connect_third_mobile_connect_check_info": "Escanee el código QR con su teléfono móvil para verificar si se puede conectar al servidor a través de Internet.",
	"mobile_connect_third_mobile_connect_check_generate_button": "Generar código QR",
	"mobile_connectO2Cloud": "Conexión a O2 Cloud",
	"mobile_connectO2Cloud_infor": "Para usar la aplicación móvil, primero debe conectarse a O2 Cloud. Esto ayudará a la aplicación a ubicar el servidor empresarial y permitirá el uso del servicio de mensajes de texto, entre otros.",
	"mobile_connectO2Cloud_action": "Conectar a O2 Cloud",
	"mobile_connectO2Cloud_success": "Configuración de conexión",
	"mobile_connectO2Cloud_error": "Sin conexión a O2 Cloud aún",
	"mobile_httpProtocol": "Protocolo http",
	"mobile_httpProtocol_infor": "Seleccione si desea usar el protocolo http o https",
	"mobile_center": "Servidor central",
	"mobile_center_infor": "Dirección IP o nombre de dominio y puerto para los servicios externos del servidor central. (Cuando se usa el protocolo http, solo se puede usar la dirección IP)",
	"mobile_center_action": "Editar servidor central",
	"mobile_web": "Servidor web",
	"mobile_web_infor": "Dirección IP o nombre de dominio y puerto para los servicios externos del servidor web. Si el nombre de dominio o la dirección IP está vacío o es \"127.0.0.1\", se utilizará la dirección del servidor central. (Cuando se usa el protocolo http, solo se puede usar la dirección IP)",
	"mobile_web_action": "Editar servidor web",
	"mobile_application": "Servidor de aplicaciones",
	"mobile_application_infor": "Dirección IP o nombre de dominio y puerto para los servicios externos del servidor de aplicaciones. Si el nombre de dominio o la dirección IP está vacío o es \"127.0.0.1\", se utilizará la dirección del servidor central. (Cuando se usa el protocolo http, solo se puede usar la dirección IP)",
	"mobile_application_action": "Editar servidor de aplicaciones",
	"mobile_moduleSetting": "Configuración de módulos para dispositivos móviles",
	"mobile_index": "Configuración de la página de inicio para dispositivos móviles",
	"mobile_index_infor": "Puede configurar la página de inicio para dispositivos móviles como el estilo de aplicación predeterminado o especificar una página de portal.",
	"mobile_index_defalue": "Predeterminado",
	"mobile_module": "Módulo {name}",
	"mobile_module_infor": "¿Está activado el módulo {name} para dispositivos móviles?",
	"mobile_module_simple_mode": "Modo simplificado para dispositivos móviles",
	"mobile_module_simple_mode_infor": "When the simple mode is enabled on the mobile end, only the home page and settings page will be displayed.",
	"mobile_module_system_message_switch": "Display system notifications",
	"mobile_module_system_message_switch_infor": "Whether to display system notifications in the mobile app message list",
	"mobile_module_contact_permission_view": "Mobile app address book permission view",
	"mobile_module_contact_permission_view_infor": "You need to install the \"Address Book\" application in the application market, which contains the permission configuration view of the address book.",
	"mobile_module_contact_permission_view_action": "Change view name",
	"mobile_styleSetting": "Mobile icon style configuration",
	"mobile_style": "{name} image",
	"mobile_style_infor": "Click to replace the {name} image",
	"mobile_style_imgs": {
		"launch_logo": "Startup Logo",
		"login_avatar": "Default avatar for login interface",
		"application_top": "Top of application page",
		"index_bottom_menu_logo_blur": "Home page navigation icon (not selected)",
		"index_bottom_menu_logo_focus": "Home page navigation icon (selected)",
		"people_avatar_default": "Default user avatar",
		"process_default": "Default process icon",
		"setup_about_logo": "Icon on the about page"
	},
	"mobile_style_imgs_defaultTitle": "Confirm default image",
	"mobile_style_imgs_defaultInfor": "Are you sure you want to replace {name} with the default image?",
	"mpweixin": "公众号",
	"publishMpweixin": "Publicar en cuenta de WeChat",
	"subscribeMpweixin": "Respuesta de seguimiento",
	"subscribeMpweixin_desc": "Mensaje automático enviado cuando hay nuevos usuarios que siguen la cuenta",
	"subscribeMpweixin_save": "Guardar",
	"mpweixinInfo": "⚠️ La función del menú de la cuenta de WeChat debe activarse primero a través del archivo de configuración correspondiente [mpweixin.json] y se debe habilitar la configuración del servidor en el módulo de desarrollo de la cuenta de WeChat Management!",
	"mobile_mpweixin_menu_msg_publish_2_wxmp": "¡Atención! ¡Esta acción sobrescribirá todos los datos guardados del menú en la cuenta de WeChat, seguro que desea continuar?",
	"mobile_mpweixin_menu_msg_publish_success": "¡Publicado exitosamente! Se mostrará en el dispositivo móvil después de 24 horas.",
	"mobile_mpweixin_menu_msg_first_max_len": "¡Solo se pueden crear hasta 3 elementos en el menú de nivel 1!",
	"mobile_mpweixin_menu_msg_sub_max_len": "¡Solo se pueden crear hasta 5 elementos en el menú de nivel 2!",
	"mobile_mpweixin_menu_msg_parent_no_save": "¡Los datos del menú principal no se han guardado, por favor guarde los datos primero!",
	"mobile_mpweixin_menu_deleteBtnName_label": "Eliminar menú",
	"mobile_mpweixin_menu_default_new_name": "Nuevo elemento de menú",
	"mobile_mpweixin_menu_form_name_label": "Nombre del menú",
	"mobile_mpweixin_menu_form_name_error_empty": "El nombre del menú no puede estar vacío!",
	"mobile_mpweixin_menu_form_name_error_max_len_4": "El nombre del menú no debe tener más de 4 caracteres!",
	"mobile_mpweixin_menu_form_name_error_max_len_6": "El nombre del menú no debe tener más de 6 caracteres!",
	"mobile_mpweixin_menu_form_name_error": "Excede el límite de caracteres",
	"mobile_mpweixin_menu_form_name_tips_4": "Solo admitido chino, inglés y números, no más de 4 caracteres",
	"mobile_mpweixin_menu_form_name_tips_6": "Solo admitido chino, inglés y números, no más de 6 caracteres",
	"mobile_mpweixin_menu_form_order_label": "Orden del Menú",
	"mobile_mpweixin_menu_form_order_error_empty": "El orden del menú no puede estar vacío!",
	"mobile_mpweixin_menu_form_order_error_not_number": "El orden del menú solo puede ingresar números!",
	"mobile_mpweixin_menu_form_order_error_max_len": "El orden del menú no debe tener más de 6 caracteres!",
	"mobile_mpweixin_menu_form_order_error": "Excede el límite de caracteres",
	"mobile_mpweixin_menu_form_order_tips": "Solo se admiten números, no más de 6 caracteres, clasificados según la secuencia de caracteres",
	"mobile_mpweixin_menu_form_radio_label": "Contenido del menú",
	"mobile_mpweixin_menu_form_radio_type_msg": "Enviar mensaje",
	"mobile_mpweixin_menu_form_radio_type_url": "Redirección web",
	"mobile_mpweixin_menu_form_radio_type_miniprogram": "Redirección a mini-programa",
	"mobile_mpweixin_menu_form_type_msg_tips": "Al hacer clic en este menú, se enviará el siguiente texto al usuario. Los suscriptores no autenticados no admiten mensajes de texto.",
	"mobile_mpweixin_menu_form_type_msg_label": "Mensaje de texto",
	"mobile_mpweixin_menu_form_type_msg_error_empty": "El contenido del mensaje de texto no puede estar vacío!",
	"mobile_mpweixin_menu_form_subscribe_content_error_empty": "¡El contenido de la respuesta al mensaje no puede estar vacío!",
	"mobile_mpweixin_menu_form_type_url_tips": "Al hacer clic en este menú, se redirigirá a la siguiente URL",
	"mobile_mpweixin_menu_form_type_url_label": "Dirección de la página",
	"mobile_mpweixin_menu_form_type_url_error_empty": "La dirección de la página no puede estar vacía!",
	"mobile_mpweixin_menu_form_type_miniprogram_tips": "Al hacer clic en este menú, se redirigirá a la siguiente miniaplicación",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_label": "ID de la miniaplicación",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_placeholder": "ID de la miniaplicación. Por favor, consulte en el backend de administración de miniaplicaciones de WeChat",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_error_empty": "El ID de la miniaplicación no puede estar vacío!",
	"mobile_mpweixin_menu_form_type_miniprogram_path_label": "Ruta de la miniaplicación",
	"mobile_mpweixin_menu_form_type_miniprogram_path_placeholder": "Ruta de la miniaplicación. Por favor, consulte en el backend de administración de miniaplicaciones de WeChat",
	"mobile_mpweixin_menu_form_type_miniprogram_path_error_empty": "La ruta de la miniaplicación no puede estar vacía!",
	"mobile_mpweixin_menu_form_type_miniprogram_url_label": "Página web alternativa",
	"mobile_mpweixin_menu_form_type_miniprogram_url_placeholder": "Página web alternativa. Los usuarios antiguos de WeChat abrirán esta página web alternativa",
	"mobile_mpweixin_menu_form_type_miniprogram_url_error_empty": "La página web alternativa no puede estar vacía!",
	"mobile_mpweixin_menu_save_success": "¡Los datos se han guardado correctamente!",
	"mobile_mpweixin_menu_delete_alert_msg": "¿Está seguro de que desea eliminar estos datos? ¿También desea eliminar los submenús?",
	"mobile_mpweixin_menu_delete_success": "¡Los datos se han eliminado correctamente!",
	"save": "Guardar",
	"alert": "Alerta",
	"mobile_apppack_tips1": "⚠️ La función de empaquetamiento en línea de la aplicación móvil actual solo admite el lado Android.",
	"mobile_apppack_tips2": "⚠️ Si desea realizar un empaquetado en línea, debe registrarse e iniciar sesión en la [configuración del servicio en la nube].",
	"mobile_apppack_tips3": "⚠️ Después de enviar la información, se mostrará el estado de empaquetado actual. El proceso de empaquetado lleva mucho tiempo. Puede dejar esta página temporalmente y esperar a que se complete el paquete antes de descargar el archivo APK en esta página nuevamente.",
	"mobile_apppack_status_label": "Estado actual",
	"mobile_apppack_form_appName": "Nombre de la aplicación",
	"mobile_apppack_form_appName_tip": "El nombre de la aplicación que se muestra en el escritorio de la aplicación, no más de 6 caracteres.",
	"mobile_apppack_form_logo": "Imagen del logotipo",
	"mobile_apppack_form_logo_tip": "La imagen del logotipo que se muestra en el escritorio de la aplicación debe estar en formato PNG.",
	"mobile_apppack_form_protocol": "Protocolo HTTP",
	"mobile_apppack_form_protocol_tip": "http / https",
	"mobile_apppack_form_host": "Nombre de dominio",
	"mobile_apppack_form_host_tip": "Nombre de dominio o dirección IP del servidor central, como www.o2oa.net",
	"mobile_apppack_form_port": "Número de puerto",
	"mobile_apppack_form_port_tip": "El número de puerto del servidor central, como 20030",
	"mobile_apppack_form_context": "Contexto",
	"mobile_apppack_form_context_tip": "El contexto del servidor central, como /x_program_center",
	"mobile_apppack_form_urlMapping": "Mapeo de direcciones URL de proxy",
	"mobile_apppack_form_urlMapping_tip": "Se utiliza cuando se utiliza una dirección de proxy para acceder al servidor desde fuera de la red. Por ejemplo: {\"demo.o2oa.net:20020\": \"demo.o2oa.net/dev/app\"}",
	"mobile_apppack_form_appVersionName": "Nombre de la versión de la aplicación",
	"mobile_apppack_form_appVersionName_tip": "El nombre de la versión de la aplicación, como v1.0.0. ¡Este campo no necesita ser llenado por defecto!",
	"mobile_apppack_form_appBuildNo": "Número de compilación de la aplicación",
	"mobile_apppack_form_appBuildNo_tip": "El número de compilación de la aplicación debe ser un número entero positivo, como 100. ¡Este campo no necesita ser llenado por defecto!",
	"mobile_apppack_form_button": "Enviar y comenzar a empaquetar",
	"mobile_apppack_form_reinput_button": "Volver a completar el formulario y empaquetar",
	"mobile_apppack_form_re_pack_button": "Empaquetar directamente con los datos existentes",
	"mobile_apppack_form_download_apk_button": "Descargar archivo APK",
	"mobile_apppack_message_o2cloud_not_enable": "¡O2 Cloud no está habilitado o no se puede conectar!",
	"mobile_apppack_message_o2cloud_not_login": "¡Inicie sesión en O2 Cloud primero!",
	"mobile_apppack_message_apppack_server_login_fail": "¡Error de inicio de sesión del servidor de empaquetado de aplicaciones!",
	"mobile_apppack_message_check_connect_fail": "¡Error al comprobar la conexión del servicio de empaquetado de aplicaciones!",
	"mobile_apppack_form_enable_outer_status_no": "Desactivado",
	"mobile_apppack_form_enable_outer_status_yes": "Activado",
	"mobile_apppack_form_enable_outer_package": "¿Habilitar el nombre del paquete externo?",
	"mobile_apppack_form_enable_delete_hms": "¿Eliminar HMS?",
	"mobile_apppack_form_enable_outer_tips": "Habilitar el nombre del paquete externo puede evitar conflictos y sobrescribir la versión oficial de la aplicación.",
	"mobile_apppack_form_enable_delete_hms_tips": "Eliminar HMS impide el uso de Huawei Push. ¡Tenga cuidado al realizar esta operación!",
	"mobile_apppack_form_enable_delete_hms_status_no": "No",
	"mobile_apppack_form_enable_delete_hms_status_yes": "Sí",
	"mobile_apppack_form_download_publish_btn": "Descargar para publicar localmente",
	"mobile_apppack_message_confirm_publish": "La aplicación se ha empaquetado correctamente. ¡Descargue y publique en el servidor local para instalarla escaneando el código QR!",
	"mobile_apppack_publish_status_doing": "Publicando...",
	"mobile_apppack_publish_status_completed": "¡Publicación completada! Escanee el código QR en la página de inicio de sesión para instalar la aplicación.",
	"mobile_apppack_publish_status_fail": "Error en la publicación. Inténtelo de nuevo o póngase en contacto con el administrador.",
	"mobile_apppack_status_order_inline": "En cola...",
	"mobile_apppack_status_packing": "Empaquetando...",
	"mobile_apppack_status_pack_end": "Empaquetado completado",
	"mobile_apppack_status_pack_error": "Error en el empaquetado",
	"mobile_apppack_message_appname_not_empty": "¡El nombre de la aplicación no puede estar vacío!",
	"mobile_apppack_message_appname_len_max_6": "¡El nombre de la aplicación no puede tener más de 6 caracteres!",
	"mobile_apppack_message_app_logo_not_empty": "¡La imagen de logo no puede estar vacía!",
	"mobile_apppack_message_app_logo_need_png": "¡La imagen del logo debe estar en formato PNG!",
	"mobile_apppack_message_portocol_not_empty": "¡El protocolo HTTP no puede estar vacío!",
	"mobile_apppack_message_host_not_empty": "¡El nombre de dominio del servidor central no puede estar vacío!",
	"mobile_apppack_message_host_format_error": "Por favor, ingrese el nombre de dominio o la dirección IP del servidor central, como www.o2oa.net, sin prefijos como http.",
	"mobile_apppack_message_port_not_empty": "¡El número de puerto del servidor central no puede estar vacío!",
	"mobile_apppack_message_context_not_empty": "¡El contexto del servidor central no puede estar vacío!",
	"mobile_apppack_message_portocol_http_https": "¡El protocolo HTTP solo puede ser http o https!",
	"mobile_apppack_refresh_status_btn": "Actualizar estado",
	"mobile_apppack_message_alert_submit": "¿Está seguro de que desea enviar este formulario para empaquetar la aplicación móvil?",
	"imgSize": "Tamaño de la imagen:",
	"defaultImg": "Imagen predeterminada",
	"ui_loginSetting": "Configuración del estilo de la página de inicio de sesión",
	"ui_login_default": "Estilo predeterminado",
	"ui_login_defaultStyle": "Estilo predeterminado de la página de inicio de sesión",
	"ui_login_defaultStyle_infor": "",
	"ui_login_customStyle": "Estilo personalizado de la página de inicio de sesión",
	"ui_login_customStyle_infor": "",
	"ui_login_customStyle_Action": "Crear un estilo personalizado",
	"ui_login_customStyle_newName": "Nombre del nuevo estilo",
	"ui_login_customStyle_newName_empty": "Ingrese el nombre del nuevo estilo",
	"ui_login_setCurrent": "Usar este estilo",
	"ui_login_current": "Estilo actualmente utilizado",
	"ui_login_setCurrent_confirmTitle": "Confirmación para usar el estilo",
	"ui_login_setCurrent_confirm": "¿Está seguro de que desea utilizar el estilo “{title}”?",
	"ui_login_delete_confirmTitle": "Confirmación para eliminar el estilo",
	"ui_login_delete_confirm": "¿Está seguro de que desea eliminar el estilo “{title}”?",
	"ui_indexSetting": "Configuración del estilo de la plataforma",
	"ui_index_systemStyle": "Estilo integrado en la plataforma",
	"ui_index_systemStyle_infor": "",
	"ui_index_customStyle": "Configuración de estilos personalizados",
	"ui_index_customStyle_infor": "",
	"ui_index_customStyle_Action": "",
	"ui_index_enabled": "Habilitado",
	"ui_index_disabled": "Deshabilitado",
	"ui_moduleSetting": "Configuración de módulos del sistema",
	"ui_module_modules": "Módulos implementados",
	"ui_module_modules_infor": "",
	"ui_module_modules_Action": "Implementar módulos",
	"ui_moduleSetting_resource": "Implementación de recursos web",
	"ui_moduleSetting_service": "Implementación de servicios",
	"resource_upload": "Selección de recursos",
	"resource_replace": "¿Reemplazar?",
	"resource_replaceDesc": "Tipo de reemplazo: 'no' elimina el archivo original y luego lo sube, 'sí' lo sobrescribe.",
	"resource_replace_yes": "Sí",
	"resource_replace_no": "No",
	"resource_filePath": "Directorio de almacenamiento",
	"resource_filePathDesc": "El archivo ZIP puede estar vacío, pero otros deben tener un formato path:/xxx/xxx",
	"resource_success": "Implementación exitosa",
	"service_ctl": "Nombre del comando",
	"service_node": "Nodo del servidor",
	"service_allNode": "Todos los nodos",
	"service_success": "Implementación exitosa. El servicio debe reiniciarse para que surta efecto.",
	"on": "Encendido",
	"off": "Apagado",
	"loading": "Cargando estilos, por favor espere...",
	"returnBack": "Volver",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"edit": "Editar",
	"delete": "Eliminar",
	"copy": "Copiar",
	"copyName": "Copia",
	"deleteItem": "Confirmación para eliminar la configuración",
	"deleteItemInfor": "¿Está seguro de que desea eliminar esta configuración?",
	"setSaved": "Los datos de configuración se han guardado.",
	"pleaseInput": "Por favor ingrese",
	"list": {
		"client": "Nombre de autenticación",
		"key": "Clave (mínimo 8 caracteres)",
		"clientId": "ID del cliente (ClientId)",
		"mapping": "Mapeo (Mapping)",
		"corpId": "corpId",
		"corpSecret": "corpSecret",
		"agentId": "agentId",
		"proxyHost": "Nombre de dominio o dirección IP",
		"proxyPort": "Puerto",
		"node": "Servidor de la aplicación",
		"enable": "¿Activado?",
		"name": "Nombre",
		"icon": "Icono",
		"clientSecret": "Secreto del cliente",
		"authAddress": "Dirección web para solicitar clave",
		"authParameter": "Parámetros de solicitud de clave",
		"authMethod": "Método para solicitar clave (GET o POST)",
		"tokenAddress": "Dirección web para solicitar token",
		"tokenParameter": "Parámetros de solicitud de token",
		"tokenMethod": "Método para solicitar token (GET o POST)",
		"tokenType": "Formato de información de token (json o form)",
		"infoAddress": "Dirección web para solicitar información",
		"infoParameter": "Parámetros de solicitud de información",
		"infoMethod": "Método para solicitar información (GET o POST)",
		"infoType": "Formato de información (json o form)",
		"infoCredentialField": "Campo en la información que identifica al usuario",
		"infoProxyHost": "El nombre de dominio no debe incluir http",
		"ldapUrl": "ldapUrl (dirección LDAP, por ejemplo ldap://111.111.111.111:5389/)",
		"baseDn": "baseDn (nombre de raíz de la consulta LDAP, por ejemplo dc=zone,DC=COM)",
		"userDn": "userDn (DN del usuario de autenticación, por ejemplo uid=*,ou=users,dc=zone,DC=COM, donde * es el código único del usuario, que corresponde al código único del usuario en O2)"
	},
	"module": {
		"title": "Implementación de aplicaciones",
		"open": "Abrir",
		"edit": "Editar",
		"remove": "Desinstalar",
		"add": "Implementar componente",
		"name": "Nombre del componente",
		"componentTitle": "Título del componente",
		"path": "Ruta del componente",
		"icon": "Icono del componente",
		"isVisible": "¿Visible?",
		"yes": "Sí",
		"no": "No",
		"widgetName": "Nombre del widget",
		"widgetTitle": "Título del widget",
		"widgetStart": "Inicio automático del widget",
		"widgetVisible": "¿Widget visible?",
		"allowList": "Lista de acceso permitido",
		"denyList": "Lista de acceso denegado",
		"controllerList": "Administradores",
		"selPerson": "Seleccionar persona",
		"selIcon": "Seleccionar icono",
		"urlInfor": "Puede agregar una URL de página web como ruta utilizando '@url:', por ejemplo: '@url:http://www.bing.com'",
		"phone": "Teléfono",
		"mail": "Correo electrónico",
		"noInputInfor": "Complete toda la información del componente. (Debe completar: nombre del componente, título del componente, ruta del componente)",
		"deploySuccess": "Componente implementado correctamente",
		"modifySuccess": "Información del componente modificada correctamente",
		"removeComponentTitle": "Confirmación para desinstalar el componente",
		"removeComponent": "¿Está seguro de que desea desinstalar el componente {name}?",
		"removeComponentOk": "El componente se ha desinstalado correctamente",
		"modify": "Modificar información del componente",
		"moduleDeployed": "Componente implementado",
		"inputAppNameNotice": "Ingrese el nombre y el título de la aplicación",
		"uploadZipFileNotice": "Cargue el archivo en formato ZIP"
	},
	"tab_centerServer": "Servidor Center",
	"tab_Server": "Configuración del host de servicio",
	"tab_Application": "Configuración de los datos de la aplicación",
	"tab_Resource": "Configuración de parámetros de recursos",
	"tab_Mobile": "Configuración de la oficina móvil",
	"tab_ApplicationServer": "Servidor de aplicaciones",
	"tab_DataServer": "Servidor de base de datos",
	"tab_StorageServer": "Servidor de almacenamiento",
	"tab_WebServer": "Servidor web",
	"deploy": "Implementar aplicación",
	"deleteAppServer_title": "Confirmación para eliminar configuración del servidor de aplicaciones",
	"deleteAppServer": "¿Está seguro que desea eliminar el documento de configuración del servidor de aplicaciones? Eliminar este documento no afectará al funcionamiento del servidor. ¿Desea continuar?",
	"deployAppServer_title": "Confirmación para implementar aplicación",
	"deployAppServer": "¿Está seguro que desea implementar una aplicación en el servidor actual?<br><br><div style='color: #F00'><input type='checkbox'>Volver a implementar todas las aplicaciones</div>",
	"deleteDataServer_title": "Confirmación para eliminar configuración del servidor de base de datos",
	"deleteDataServer": "¿Está seguro que desea eliminar el documento de configuración del servidor de base de datos? Eliminar este documento no afectará al funcionamiento del servidor. ¿Desea continuar?",
	"deleteStorageServer_title": "Confirmación para eliminar configuración del servidor de almacenamiento",
	"deleteStorageServer": "¿Está seguro que desea eliminar el documento de configuración del servidor de almacenamiento? Eliminar este documento no afectará al funcionamiento del servidor. ¿Desea continuar?",
	"deleteWebServer_title": "Confirmación para eliminar configuración del servidor web",
	"deleteWebServer": "¿Está seguro que desea eliminar el documento de configuración del servidor web? Eliminar este documento no afectará al funcionamiento del servidor. ¿Desea continuar?",
	"deleteStorage_title": "Confirmación para eliminar configuración de almacenamiento",
	"deleteStorage": "¿Está seguro que desea eliminar el documento de configuración de almacenamiento? ¿Desea continuar?",
	"centerSaveInfor": "Los datos se han enviado correctamente",
	"saveWeightError": "Debe ser un número",
	"mobileSetting1": "1. Comprobar",
	"mobileSetting2": "2. Cuenta",
	"mobileSetting3": "3. Servidor",
	"checkCenterToCollect": "Conexión del servidor con el centro O2",
	"checkComputerToCollect": "Conexión del cliente con el centro O2",
	"success": "Éxito",
	"failure": "Fracaso",
	"reCheck": "Volver a comprobar la conexión",
	"next": "Siguiente",
	"loginCollect": "Iniciar sesión en el centro O2",
	"loggedCollect": "Ha iniciado sesión en el centro O2",
	"loginText": "Iniciar sesión en el centro O2",
	"logoutText": "Cerrar sesión en el centro O2",
	"registerText": "Si aún no tiene una cuenta de empresa en el centro O2, regístrese primero",
	"loginInputUsername": "Ingrese su nombre de usuario y contraseña",
	"loginInputCode": "Ingrese el código de verificación",
	"companyName": "Nombre de la empresa",
	"code": "Código de verificación",
	"phone": "Número de teléfono móvil",
	"password": "Contraseña",
	"confirmPassword": "Confirmar contraseña",
	"registerTitle": "Registrar su empresa en el centro O2",
	"getPhoneCode": "Obtener código de verificación por teléfono móvil",
	"getPhoneCodeWait": "El código de verificación ha sido enviado",
	"registerActionText": "Registrarse",
	"registerCancelActionText": "Cancelar registro",
	"phoneError": "Ingrese su número de teléfono móvil",
	"phoneTypeError": "Ingrese un número de teléfono móvil válido",
	"nameError": "Ingrese el nombre de su empresa",
	"codeError": "Ingrese el código de verificación",
	"passwordError": "Ingrese una contraseña",
	"confirmError": "Ingrese la contraseña nuevamente para confirmar",
	"confirmPasswordError": "Las contraseñas ingresadas no coinciden",
	"cancelRegisterTitle": "Confirmación para cancelar el registro",
	"cancelRegister": "¿Está seguro que desea cancelar el registro?",
	"registerSuccess": "Su empresa se ha registrado con éxito en el centro O2.<br/>Puede ingresar al centro O2 con su nombre de usuario: “{name}”",
	"registerSuccessTitle": "Su empresa se ha registrado con éxito en el centro O2",
	"mobileServerSaveInfor": "Los datos se han enviado correctamente",
	"mobileServerSaveErrorInfor": "Los datos se han enviado correctamente, pero se han producido los siguientes errores: {error}",
	"saveDefaultMenuData": "Guardar como configuración de menú predeterminada",
	"clearDefaultMenuData": "Borrar configuración de menú predeterminada",
	"saveDefaultMenuDataInfor": "Si guarda la configuración de menú como predeterminada, los usuarios que no hayan configurado su propio menú verán esta configuración.",
	"saveDefaultMenuDataSuccess": "Configuración de menú predeterminada guardada con éxito",
	"clearDefaultMenuDataSuccess": "Configuración de menú predeterminada eliminada",
	"clearDefaultMenuDataConfirm": "¿Está seguro que desea borrar la configuración de menú predeterminada?",
	"loadDefaultMenuData": "Cargar configuración predeterminada",
	"saveForceMenuData": "Guardar como configuración de menú forzada",
	"clearForceMenuData": "Borrar configuración de menú forzada",
	"saveForceMenuDataInfor": "Si guarda la configuración de menú como forzada, todos los usuarios verán esta configuración y no podrán personalizar su propio menú.",
	"saveForceMenuDataSuccess": "Configuración de menú forzada guardada con éxito",
	"clearForceMenuDataSuccess": "Configuración de menú forzada eliminada",
	"clearForceMenuDataConfirm": "¿Está seguro que desea borrar la configuración de menú forzada?",
	"loadForceMenuData": "Cargar configuración forzada",
	"clearCustomMenuData": "Borrar configuración personalizada de menú de usuario",
	"clearCustomMenuDataInfor": "Se eliminará la configuración personalizada del menú de todos los usuarios y se verá el menú predeterminado.",
	"clearCustomMenuDataSuccess": "Configuración personalizada del menú de usuario eliminada",
	"clearCustomMenuDataConfirm": "¿Está seguro que desea borrar la configuración personalizada del menú de todos los usuarios?"
}
MWF.xApplication.Setting["lp."+o2.language] = MWF.xApplication.Setting.LP