MWF.xApplication.Setting.LP = {
    "title": "システム設定",
	"default": "デフォルト",

	"tab_base": "基本設定",
	"tab_ui": "インターフェース設定",
	"tab_mobile": "モバイルオフィス設定",
	"tab_cloud": "クラウドサービス設定",
	"tab_dispose": "システム展開",
	"tab_name": "システム名設定",
	"tab_user": "システムユーザー設定",
	"tab_login": "システムログイン設定",
	"tab_sso": "システムSSO設定",
	"tab_config": "プラットフォーム設定",

	"tab_cloud_connect": "接続設定",

	"tab_mobile_connect": "接続設定",
	"tab_mobile_module": "モジュール設定",
	"tab_mobile_style": "スタイル設定",
	"tab_mobile_mpweixin_menu": "公式アカウントメニュー設定",
	"tab_mobile_app_pack": "モバイルアプリオンラインパッケージ",

	"tab_ui_login": "ログインページのスタイル",
	"tab_ui_index": "ホームページのスタイル",
	"tab_ui_module": "モジュール展開",
	"tab_ui_resource": "リソース展開",
	"tab_ui_service": "サービス展開",
	"tab_ui_menu": "メニュー編集",

	"base_nameSetting": "システム名設定",

	"base_title": "システム名",
	"base_title_infor": "システム名はログインページとブラウザのタイトルバーに表示されます。",
	"base_title_action": "システム名の編集",
	"base_title_empty": "システム名を入力してください。",

	"base_footer": "システムフッター",
	"base_footer_infor": "システムフッターはログインページの下部に表示されます。",
	"base_footer_action": "システムフッターの編集",
	"base_version": "現在のシステムバージョン",


    "base_personSetting": "システムのユーザーアカウント基本情報の設定",
	"base_UserPassword": "新しいユーザーのデフォルトパスワード",
	"base_UserPassword_infor": "新しいユーザーを作成する際に使用されるデフォルトパスワードです。ユーザーはシステムにログイン後、パスワードを自分で変更できます。",
	"base_UserPassword_action": "デフォルトパスワードの変更",
	"base_UserPassword_empty": "デフォルトパスワードを入力してください。",

	"base_passwordPeriod": "パスワード有効期限（日）",
	"base_passwordPeriod_infor": "パスワードを変更する必要がある日数を示します。この期間内にパスワードを変更しなかったユーザーは、システムにログインする際にパスワードの変更が必要です。",
	"base_passwordPeriod_action": "パスワード有効期限の変更",

	"base_adminPassword": "スーパー管理者のパスワード",
	"base_adminPassword_infor": "スーパー管理者 xadmin のパスワードです。",
	"base_adminPassword_action": "スーパー管理者のパスワードの変更",
	"base_adminPassword_confirm": "<div style='color:red'>スーパー管理者のパスワードはデフォルトのデータベースパスワードなどと関連しているため、注意して変更してください！ <br>パスワードを変更したらすぐに再起動する必要があります。それ以外の場合、システムが誤作動する可能性があります。</div><br>変更しますか？",

	"base_loginSetting": "ユーザーログインオプションの設定",

	"base_captchaLogin": "画像認証コードのログインを有効化",
	"base_captchaLogin_infor": "有効化すると、ログイン時に画像認証コードを正確に入力する必要があります。",
	"base_captchaLogin_action": "",

	"base_codeLogin": "SMSコードのログインを有効化",
	"base_codeLogin_infor": "有効化すると、SMSコードを使用してログインできます。",
	"base_codeLogin_action": "",

	"base_bindLogin": "QRコードスキャンログインを有効化",
	"base_bindLogin_infor": "有効化すると、QRコードをスキャンしてログインできます。",

    "base_faceLogin": "顔認証ログインを有効化",
	"base_faceLogin_infor": "有効化すると、顔認証ログインが許可されます。ユーザーは個人設定で顔の特徴を設定できます。有効化するには、faceという名前のSSO設定を作成し、キーをxplatformに設定する必要があります（これは実験的な機能で、httpsを有効にする必要があります）。",

	"base_faceApi": "顔認証サービス",
	"base_faceApi_action": "顔認証サービスの編集",
	"base_faceApi_delete": "顔認証サービスの削除",
	"base_faceApi_infor": "Face++の顔認証サービスを使用して、APIキーとAPIシークレットを編集できます。それ以外の場合、システムはデフォルトアカウントを使用し、QPSに制限がかかります。",

	"base_register": "セルフサービス登録を有効化",
	"base_register_infor": "システムユーザーになるためのセルフサービス登録を許可するかどうか、および登録方法を設定します。",
	"register_disable": "セルフサービス登録を許可しない",
	"register_captcha": "画像認証を使用したセルフサービス登録を許可",
	"register_code": "SMSコードを使用したセルフサービス登録を許可",

	"base_portalLogin": "ポータルページを使用してログイン",
	"base_portalLogin_infor": "カスタムのポータルページをログインページとして使用できます。ログインページのテンプレートはアプリケーションマーケットからダウンロードできます。",
	"base_portalLogin_action": "",

	"base_loginPortalId": "ログインポータル",
	"base_loginPortalId_infor": "ログインページのポータルを選択します。",

	"base_portalIndex": "ポータルページをシステムのホームページとして使用",
	"base_portalIndex_infor": "カスタムのポータルページをシステムのホームページとして使用できます。ログイン後、このページが開きます。",
	"base_portalIndex_action": "",
	"base_indexPortalId": "システムのホームページポータル",
	"base_indexPortalId_infor": "システムのホームページのポータルを選択します。",

	"base_temary": "三者管理",
	"base_temary_info": "三者管理（システム管理者、セキュリティ管理者、セキュリティ監査員）です。この機能を有効にするには、サーバーを再起動する必要があります。",
	"base_temary_action": "",

	"base_ldap": "LDAP認証を有効化",
	"base_ldap_infor": "有効にすると、ユーザーログイン認証にLDAP認証が使用され、システムのパスワードログインは使用されなくなります。",
	"base_ldap_action": "LDAP認証設定の編集",
	"base_ldap_enable": "有効",
	"base_ldap_unenable": "無効",


    "base_ssoSetting": "他のシステムとの認証およびシングルサインオン設定を構成する",
	"base_ssos": "認証設定",
	"base_sso_infor": "SSOログインおよびサービス呼び出しに使用するために、複数のシステムの認証を作成できます。",
	"base_sso_action": "認証設定の追加",
	"base_sso_editAction": "認証設定の編集",

	"base_oauths": "OAUTHクライアント設定",
	"base_oauths_infor": "このシステムがOAUTH2認証サーバーとして機能する場合、他のシステムに認可を実現するために複数のOAUTHクライアントを設定できます。",
	"base_oauths_action": "OAuth設定の追加",
	"base_oauths_editAction": "OAuth設定の編集",

	"base_oauths_server": "OAUTHサーバー設定",
	"base_oauths_infor_server": "このシステムが他のOAUTH2サーバーを介して認証する必要がある場合、本システムに認可を実現するために複数のOAUTHサーバーを設定できます。",

	"base_qyweixin": "企業WeChat設定",
	"base_qyweixin_infor": "システムは企業WeChatと統合できます。最初にWeChat企業番号とキーを設定してください。",
	"base_qyweixin_action": "企業WeChat設定の編集",

	"base_dingding": "DingDing設定",
	"base_dingding_infor": "システムはDingDingと統合できます。最初にDingDing企業番号とキーを設定してください。",
	"base_dingding_action": "DingDing設定の編集",

	"mobile_connectSetting": "モバイルオフィス接続設定",
	"cloud_connectSetting": "クラウドサービス接続設定",
	"mobile_connect_first_cloud_check": "1. クラウドサービス接続確認",
	"mobile_connect_first_cloud_check_connected": "<span style='color: #5fbf78'> [接続済みログイン] </span> クラウドサービス",
	"mobile_connect_first_cloud_check_disconnected": "<span style='color: #ff0000'> [未接続ログイン] </span> クラウドサービス、クラウドサービス設定ページでログインを登録してください！",
	"mobile_connect_connectSetting": "2. 外部ネットワーク接続設定",
	"mobile_connect_third_mobile_connect_check": "3. モバイル接続テスト",
	"mobile_connect_third_mobile_connect_check_info": "携帯でQRコードをスキャンして外部ネットワークからサーバーに接続できるか確認してください！",
	"mobile_connect_third_mobile_connect_check_generate_button": "QRコードの生成",

	"mobile_connectO2Cloud": "O2クラウドへの接続",
	"mobile_connectO2Cloud_infor": "モバイルオフィスを使用するためには、まずO2クラウドに接続してください。これにより、アプリが企業サーバーを特定し、SMSサービスなどを利用できます。",
	"mobile_connectO2Cloud_action": "O2クラウドに接続",
	"mobile_connectO2Cloud_success": "接続設定",
	"mobile_connectO2Cloud_error": "まだO2クラウドに接続されていません。",

    "mobile_httpProtocol": "HTTPプロトコル",
	"mobile_httpProtocol_infor": "HTTPプロトコルまたはHTTPSプロトコルを選択してください",

	"mobile_center": "センターサーバー",
	"mobile_center_infor": "センターサーバーの外部サービスのIPアドレスまたはドメインとポートです。（HTTPプロトコルを使用する場合、IPアドレスのみ使用できます）",
	"mobile_center_action": "センターサーバーの編集",

	"mobile_web": "WEBサーバー",
	"mobile_web_infor": "WEBサーバーの外部サービスのIPアドレスまたはドメインとポートです。ドメインまたはIPアドレスが空白または「127.0.0.1」の場合、センターサーバーアドレスが使用されます。 （HTTPプロトコルを使用する場合、IPアドレスのみ使用できます）",
	"mobile_web_action": "WEBサーバーの編集",

	"mobile_application": "アプリケーションサーバー",
	"mobile_application_infor": "アプリケーションサーバーの外部サービスのIPアドレスまたはドメインとポートです。ドメインまたはIPアドレスが空白または「127.0.0.1」の場合、センターサーバーアドレスが使用されます。 （HTTPプロトコルを使用する場合、IPアドレスのみ使用できます）",
	"mobile_application_action": "アプリケーションサーバーの編集",

	"mobile_moduleSetting": "モバイルモジュール設定",
	"mobile_index": "モバイルホームページ設定",
	"mobile_index_infor": "モバイルホームページをデフォルトのアプリスタイルまたは特定のポータルページに設定できます",
	"mobile_index_defalue": "デフォルト",

	"mobile_module": "{name}モジュール",
	"mobile_module_infor": "モバイルで{name}モジュールを有効にしますか？",

	"mobile_module_simple_mode": "モバイルシンプルモード",
	"mobile_module_simple_mode_infor": "モバイルシンプルモードを有効にすると、ホームページと設定ページのみが表示されます",

	"mobile_module_system_message_switch": "システム通知を表示",
	"mobile_module_system_message_switch_infor": "モバイルアプリのメッセージリストにシステム通知を表示しますか？",

	"mobile_module_contact_permission_view": "モバイルアプリの連絡先アクセス許可ビューア",
	"mobile_module_contact_permission_view_infor": "アプリマーケットから「アドレス帳」アプリをインストールする必要があります。アプリ内にはアドレス帳アクセス許可の構成ビューアが含まれています。",
	"mobile_module_contact_permission_view_action": "ビューア名の変更",

	"mobile_styleSetting": "モバイルアイコンスタイル設定",
	"mobile_style": "{name}画像 ",
	"mobile_style_infor": "{name}画像を変更するにはクリックしてください",
    "mobile_style_imgs": {
		"launch_logo": "起動ロゴ",
		"login_avatar": "ログイン画面のデフォルトアバター",
		"application_top": "アプリケーションページの上部",
		"index_bottom_menu_logo_blur": "ホームナビゲーションアイコン（未選択）",
		"index_bottom_menu_logo_focus": "ホームナビゲーションアイコン（選択済み）",
		"people_avatar_default": "ユーザーデフォルトアバター",
		"process_default": "プロセスデフォルトアイコン",
		"setup_about_logo": "紹介ページのアイコン"
	},
	"mobile_style_imgs_defaultTitle": "デフォルト画像の確認",
	"mobile_style_imgs_defaultInfor": "{name} をデフォルト画像に変更しますか？",

    "mpweixin": "公衆号",
	"publishMpweixin": "公衆号への投稿",
	"subscribeMpweixin": "フォロー応答",
	"subscribeMpweixin_desc": "公衆号に新しいユーザーがフォローすると、自動的に送信されるメッセージの内容",
	"subscribeMpweixin_save": "保存",
	"mpweixinInfo": "⚠️ Weiboの小規模プログラム管理バックエンドに移動して、Weiboの公衆号管理バックエンドでサーバーの設定を有効にしてください",
	"mobile_mpweixin_menu_msg_publish_2_wxmp": "注意！現在の操作は、すべての保存されたメニューデータをWeiboの公衆号に上書きします。続行しますか？",
	"mobile_mpweixin_menu_msg_publish_success": "正常に投稿され、モバイルデバイスでの表示が24時間後に同期されます！",
	"mobile_mpweixin_menu_msg_first_max_len": "一次メニューは最大3つしか作成できません！",
	"mobile_mpweixin_menu_msg_sub_max_len": "サブメニューは最大5つしか作成できません！",
	"mobile_mpweixin_menu_msg_parent_no_save": "親メニューデータが保存されていません。まずデータを保存してください！",
	"mobile_mpweixin_menu_deleteBtnName_label": "メニューを削除",
	"mobile_mpweixin_menu_default_new_name": "新しいメニュー",
	"mobile_mpweixin_menu_form_name_label": "メニュー名",
	"mobile_mpweixin_menu_form_name_error_empty": "メニュー名は空白にできません！",
	"mobile_mpweixin_menu_form_name_error_max_len_4": "メニュー名の文字数は4文字を超えることはできません！",
	"mobile_mpweixin_menu_form_name_error_max_len_6": "メニュー名の文字数は6文字を超えることはできません！",
	"mobile_mpweixin_menu_form_name_error": "文字数が制限を超えています",
	"mobile_mpweixin_menu_form_name_tips_4": "中英文と数字のみをサポートし、文字数は4文字を超えないようにしてください",
	"mobile_mpweixin_menu_form_name_tips_6": "中英文と数字のみをサポートし、文字数は6文字を超えないようにしてください",
	"mobile_mpweixin_menu_form_order_label": "メニューの順番",
	"mobile_mpweixin_menu_form_order_error_empty": "メニューの順番は空白にできません！",
	"mobile_mpweixin_menu_form_order_error_not_number": "メニューの順番には数字しか入力できません！",
	"mobile_mpweixin_menu_form_order_error_max_len": "メニューの順番の文字数は6文字を超えることはできません！",
	"mobile_mpweixin_menu_form_order_error": "文字数が制限を超えています",
	"mobile_mpweixin_menu_form_order_tips": "数字のみをサポートし、文字数は6文字を超えないようにしてください。文字列順に並べ替えます",
	"mobile_mpweixin_menu_form_radio_label": "メニューの内容",
	"mobile_mpweixin_menu_form_radio_type_msg": "メッセージを送信",
	"mobile_mpweixin_menu_form_radio_type_url": "ウェブページに移動",
	"mobile_mpweixin_menu_form_radio_type_miniprogram": "プログラムに移動",
	"mobile_mpweixin_menu_form_type_msg_tips": "このメニューをクリックすると、ユーザーに以下のテキストが送信されます。認証されていない購読号はテキストメッセージをサポートしていません",
	"mobile_mpweixin_menu_form_type_msg_label": "テキストメッセージ",
	"mobile_mpweixin_menu_form_type_msg_error_empty": "テキストメッセージの内容は空白にできません！",
	"mobile_mpweixin_menu_form_subscribe_content_error_empty": "返信メッセージの内容は空白にできません！",
	"mobile_mpweixin_menu_form_type_url_tips": "このメニューをクリックすると、以下のリンクに移動します",
	"mobile_mpweixin_menu_form_type_url_label": "ページのアドレス",
	"mobile_mpweixin_menu_form_type_url_error_empty": "ページのアドレスは空白にできません！",
	"mobile_mpweixin_menu_form_type_miniprogram_tips": "このメニューをクリックすると、以下の小プログラムに移動します",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_label": "小プログラムID",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_placeholder": "小プログラムIDはWeiboの小プログラム管理バックエンドで確認できます",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_error_empty": "小プログラムIDは空白にできません！",
	"mobile_mpweixin_menu_form_type_miniprogram_path_label": "小プログラムのパス",
	"mobile_mpweixin_menu_form_type_miniprogram_path_placeholder": "小プログラムのパスはWeiboの小プログラム管理バックエンドで確認できます",
	"mobile_mpweixin_menu_form_type_miniprogram_path_error_empty": "小プログラムのパスは空白にできません！",
	"mobile_mpweixin_menu_form_type_miniprogram_url_label": "予備のウェブページ",
	"mobile_mpweixin_menu_form_type_miniprogram_url_placeholder": "予備のウェブページ、古いバージョンのWeiboではこの予備のウェブページが開きます",
	"mobile_mpweixin_menu_form_type_miniprogram_url_error_empty": "予備のウェブページは空白にできません！",
	"mobile_mpweixin_menu_save_success": "データの保存に成功しました！",
	"mobile_mpweixin_menu_delete_alert_msg": "このデータを削除してもよろしいですか？それに子メニューも一緒に削除されますか？",
	"mobile_mpweixin_menu_delete_success": "データの削除に成功しました！",
    
    
    "save": "保存",
	"alert": "警告",
	"mobile_apppack_tips1": "⚠️ 現在、モバイルアプリのオンラインパッケージ機能はAndroid端末のみをサポートしています。",
	"mobile_apppack_tips2": "⚠️ オンラインパッケージを行うには、まず[クラウドサービスの構成]で登録とログインを行う必要があります。",
	"mobile_apppack_tips3": "⚠️ 情報を提出すると、現在のパッケージの状態が表示され、パッケージのプロセスには時間がかかります。パッケージが完了するのを待つために、一旦このページを離れてAPKファイルをダウンロードできます。",
	"mobile_apppack_status_label": "現在のステータス",
	"mobile_apppack_form_appName": "アプリ名",
	"mobile_apppack_form_appName_tip": "デスクトップに表示されるアプリ名、6文字以内",
	"mobile_apppack_form_logo": "ロゴ画像",
	"mobile_apppack_form_logo_tip": "デスクトップに表示されるアプリのロゴ画像、必ずPNG形式である必要があります",
	"mobile_apppack_form_protocol": "HTTPプロトコル",
	"mobile_apppack_form_protocol_tip": "http / https",
	"mobile_apppack_form_host": "ドメイン",
	"mobile_apppack_form_host_tip": "中央サーバのドメインまたはIP、例: www.o2oa.net",
	"mobile_apppack_form_port": "ポート番号",
	"mobile_apppack_form_port_tip": "中央サーバのポート番号、例: 20030",
	"mobile_apppack_form_context": "コンテキスト",
	"mobile_apppack_form_context_tip": "中央サーバのコンテキスト、例: /x_program_center",
	"mobile_apppack_form_urlMapping": "プロキシurlMapping",
	"mobile_apppack_form_urlMapping_tip": "外部サーバでプロキシアドレスを使用する際に使用、例: { \"demo.o2oa.net:20020\": \"demo.o2oa.net/dev/app\" }",
	"mobile_apppack_form_appVersionName": "アプリバージョン名",
	"mobile_apppack_form_appVersionName_tip": "アプリのバージョン名、例: v1.0.0。このフィールドは通常入力する必要はありません。",
	"mobile_apppack_form_appBuildNo": "アプリバージョン番号",
	"mobile_apppack_form_appBuildNo_tip": "アプリのバージョン番号、正の整数である必要があり、例: 100。このフィールドは通常入力する必要はありません。",
	"mobile_apppack_form_button": "提出してパッケージ開始",
	"mobile_apppack_form_reinput_button": "フォームを再入力してパッケージ",
	"mobile_apppack_form_re_pack_button": "既存のデータを使用してパッケージ",
	"mobile_apppack_form_download_apk_button": "APKファイルのダウンロード",
	"mobile_apppack_message_o2cloud_not_enable": "O2クラウドが有効になっていないか、接続できません！",
	"mobile_apppack_message_o2cloud_not_login": "まずO2クラウドにログインしてください！",
	"mobile_apppack_message_apppack_server_login_fail": "アプリパッケージサーバへのログインに失敗しました！",
	"mobile_apppack_message_check_connect_fail": "アプリパッケージサービスの接続チェックに失敗しました！",

    "mobile_apppack_form_enable_outer_status_no": "無効",
	"mobile_apppack_form_enable_outer_status_yes": "有効",
	"mobile_apppack_form_enable_outer_package": "外部パッケージ名の有効化",
	"mobile_apppack_form_enable_delete_hms": "HMS の削除",
	"mobile_apppack_form_enable_outer_tips": "外部パッケージ名の有効化は、公式リリースのアプリとの競合と上書きを防ぎます。",
	"mobile_apppack_form_enable_delete_hms_tips": "HMS を削除すると HUAWEI プッシュが使用できなくなるため、注意して操作してください。",
	"mobile_apppack_form_enable_delete_hms_status_no": "いいえ",
	"mobile_apppack_form_enable_delete_hms_status_yes": "はい",
	"mobile_apppack_form_download_publish_btn": "ローカルに発行してダウンロード",
	"mobile_apppack_message_confirm_publish": "アプリは既にパッケージ化されています。即座にダウンロードしてローカルサーバーに発行し、QR コードをスキャンしてアプリをインストールできます。",
	"mobile_apppack_publish_status_doing": "発行中...",
	"mobile_apppack_publish_status_completed": "発行完了、ログイン画面のQRコードをスキャンしてアプリをインストールできます！",
	"mobile_apppack_publish_status_fail": "発行に失敗しました。再試行するか、管理者にお問い合わせください。",
	"mobile_apppack_status_order_inline": "キューイング中...",
	"mobile_apppack_status_packing": "パッケージ化中...",
	"mobile_apppack_status_pack_end": "パッケージ化完了",
	"mobile_apppack_status_pack_error": "パッケージ化エラー",
	"mobile_apppack_message_appname_not_empty": "アプリ名を入力してください。",
	"mobile_apppack_message_appname_len_max_6": "アプリ名は6文字を超えることはできません。",
	"mobile_apppack_message_app_logo_not_empty": "ロゴ画像を選択してください。",
	"mobile_apppack_message_app_logo_need_png": "ロゴ画像はPNG形式である必要があります。",
	"mobile_apppack_message_portocol_not_empty": "HTTPプロトコルを入力してください。",
	"mobile_apppack_message_host_not_empty": "センターサーバードメインを入力してください。",
	"mobile_apppack_message_host_format_error": "センターサーバードメインまたはIPを入力してください。例：www.o2oa.net、プロトコル（httpなど）を含めないでください。",
	"mobile_apppack_message_port_not_empty": "センターサーバーポート番号を入力してください。",
	"mobile_apppack_message_context_not_empty": "センターサーバーコンテキストを入力してください。",
	"mobile_apppack_message_portocol_http_https": "HTTPプロトコルはhttpまたはhttpsのみを許可しています。",
	"mobile_apppack_refresh_status_btn": "ステータスのリフレッシュ",
	"mobile_apppack_message_alert_submit": "提出してもよろしいですか？現在のフォーム情報がモバイルアプリにパッケージ化されます。",
	"imgSize": "画像サイズ：",
	"defaultImg": "デフォルト画像",

    "ui_loginSetting": "ログインページのスタイル設定",
    "ui_login_default": "デフォルトスタイル",
    "ui_login_defaultStyle": "ログインページのデフォルトスタイル",
    "ui_login_defaultStyle_infor": "",
    "ui_login_customStyle": "ログインページのカスタムスタイル",
    "ui_login_customStyle_infor": "",
    "ui_login_customStyle_Action": "カスタムスタイルを作成",
    "ui_login_customStyle_newName": "新しいスタイル名",
    "ui_login_customStyle_newName_empty": "新しいスタイル名を入力してください",
    "ui_login_setCurrent": "このスタイルを使用",
    "ui_login_current": "現在使用中のスタイル",
    "ui_login_setCurrent_confirmTitle": "スタイルの使用確認",
    "ui_login_setCurrent_confirm": "本当に “{title}” スタイルを使用しますか？",

    "ui_login_delete_confirmTitle": "スタイル削除確認",
    "ui_login_delete_confirm": "本当に “{title}” スタイルを削除しますか？",

    "ui_indexSetting": "プラットフォームのスタイル設定",
    "ui_index_systemStyle": "プラットフォーム内蔵スタイル",
    "ui_index_systemStyle_infor": "",

    "ui_index_customStyle": "カスタムスタイル設定",
    "ui_index_customStyle_infor": "",
    "ui_index_customStyle_Action": "",
    "ui_index_enabled": "有効",
    "ui_index_disabled": "無効",

    "ui_moduleSetting": "システムモジュール設定",
    "ui_module_modules": "展開済みモジュール",
    "ui_module_modules_infor": "",
    "ui_module_modules_Action": "モジュール展開",

    "ui_moduleSetting_resource": "webリソース展開",
    "ui_moduleSetting_service": "サービス展開",

    "resource_upload": "リソース選択",
    "resource_replace": "上書きしますか？",
    "resource_replaceDesc": "上書きタイプ: 'いいえ' は元のファイルを削除してアップロードします。 'はい' は元のファイルを上書きします。",
    "resource_replace_yes": "はい",
    "resource_replace_no": "いいえ",
    "resource_filePath": "保存ディレクトリ",
    "resource_filePathDesc": "zipファイルは空白にできますが、他のファイルは空白にできません。 パス: /xxx/xxx",
    "resource_success": "デプロイ成功",

    "service_ctl": "コマンド名",
    "service_node": "サーバーノード",
    "service_allNode": "すべてのノード",
    "service_success": "デプロイ成功、サービスを再起動する必要があります。",

    "on": "オン",
    "off": "オフ",

    "loading": "スタイルを読み込んでいます。お待ちください...",
    "returnBack": "戻る",

    "ok": "確定",
    "cancel": "キャンセル",
    "edit": "編集",
    "delete": "削除",
    "copy": "コピー",
    "copyName": "コピー",

    "deleteItem": "設定の削除確認",
    "deleteItemInfor": "この設定を削除してもよろしいですか？",

    "setSaved": "設定データが保存されました",

    "pleaseInput": "入力してください",
    "list": {
        "client": "認証名",
        "key": "キー（最低8文字）",
        "clientId": "クライアントID",
        "mapping": "マッピング (Mapping)",
        "corpId": "corpId",
        "corpSecret": "corpSecret",
        "agentId": "エージェントID",
        "proxyHost": "ドメインまたはIPアドレス",
        "proxyPort": "ポート",
        "node": "アプリケーションサーバー",

        "enable": "有効化",
        "name": "名前",
        "icon": "アイコン",
        "clientSecret": "クライアントシークレット",
        "authAddress": "鍵を要求するURL",
        "authParameter": "鍵を要求するメソッドパラメータ",
        "authMethod": "鍵を要求するメソッド（GETまたはPOST）",
        "tokenAddress": "トークンを要求するURL",
        "tokenParameter": "トークンを要求するメソッドパラメータ",
        "tokenMethod": "トークンを要求するメソッド（GETまたはPOST）",
        "tokenType": "トークン情報の形式（jsonまたはform）",
        "infoAddress": "情報を要求するURL",
        "infoParameter": "情報を要求するメソッドパラメータ",
        "infoMethod": "情報を要求するメソッド（GETまたはPOST）",
        "infoType": "情報情報の形式（jsonまたはform）",
        "infoCredentialField": "個人を識別するために情報内で使用されるフィールド",

        "infoProxyHost" : "ドメインにはhttpを含めないでください",

        "ldapUrl": "ldapUrl（LDAPアドレス、例：ldap://111.111.111.111:5389/）",
        "baseDn": "baseDn（LDAPクエリのルート名、例：dc=zone,DC=COM）",
        "userDn": "userDn（認証ユーザーのDN、例：uid=*,ou=users,dc=zone,DC=COM、ここでuid=*の*はユーザーの一意なコードを表し、この一意なコードはO2ユーザーの一意なコードと対応します）"
    },

    "module": {
        "title": "アプリケーションデプロイ",
        "open": "開く",
        "edit": "編集",
        "remove": "アンインストール",
        "add": "コンポーネントデプロイ",

        "name": "コンポーネント名",
        "componentTitle": "コンポーネントタイトル",
        "path": "コンポーネントパス",
        "icon": "コンポーネントアイコン",
        "isVisible": "表示するかどうか",
        "yes": "はい",
        "no": "いいえ",
        "widgetName": "ウィジェット名",
        "widgetTitle": "ウィジェットタイトル",
        "widgetStart": "ウィジェット自動起動",
        "widgetVisible": "ウィジェットが表示されるかどうか",

        "allowList": "アクセス許可リスト",
        "denyList": "アクセス拒否リスト",
        "controllerList": "管理者",
        "selPerson": "ユーザーを選択",
        "selIcon": "アイコンを選択",
        "urlInfor": "パスをWebページURLとして追加できます。 例：'@url:http://www.bing.com'",

        "phone": "携帯電話",
        "mail": "メール",

        "noInputInfor": "コンポーネント情報を完全に入力してください（コンポーネント名、コンポーネントタイトル、コンポーネントパスは必須です）。",
        "deploySuccess": "デプロイ成功",
        "modifySuccess": "コンポーネント情報の編集に成功しました",

        "removeComponentTitle": "コンポーネントアンインストール確認",
        "removeComponent": "コンポーネント {name} をアンインストールしますか？",
        "removeComponentOk": "コンポーネントがアンインストールされました",

        "modify": "コンポーネント情報の編集",

        "moduleDeployed" : "デプロイ済みのコンポーネント",
        "inputAppNameNotice" : "アプリ名とアプリタイトルを入力してください",
        "uploadZipFileNotice": "ファイルのZIPパッケージをアップロードしてください"
    },






    "tab_centerServer": "センターサーバー",
    "tab_Server": "サービスホスト設定",
    "tab_Application": "アプリケーションデータ設定",
    "tab_Resource": "リソースパラメータ設定",
    "tab_Mobile": "モバイルオフィス設定",

    "tab_ApplicationServer": "アプリケーションサーバー",
    "tab_DataServer": "データベースサーバー",
    "tab_StorageServer": "ストレージサーバー",
    "tab_WebServer": "Webサーバー",

    "deploy": "アプリケーションのデプロイ",
    "deleteAppServer_title": "アプリケーションサーバー設定の削除確認",
    "deleteAppServer": "アプリケーションサーバー設定文書を削除しようとしています。この文書を削除してもサーバーの運用には影響しません。続行しますか？",
    "deployAppServer_title": "アプリケーションのデプロイ確認",
    "deployAppServer": "現在のサーバーにアプリケーションをデプロイしようとしています。確認しますか？<br><br><div style='color: #F00'><input type='checkbox'> すべてのアプリケーションを再デプロイ</div>",

    "deleteDataServer_title": "データベースサーバー設定の削除確認",
    "deleteDataServer": "データベースサーバー設定文書を削除しようとしています。この文書を削除してもサーバーの運用には影響しません。続行しますか？",

    "deleteStorageServer_title": "ストレージサーバー設定の削除確認",
    "deleteStorageServer": "ストレージサーバー設定文書を削除しようとしています。この文書を削除してもサーバーの運用には影響しません。続行しますか？",

    "deleteWebServer_title": "Webサーバー設定の削除確認",
    "deleteWebServer": "Webサーバー設定文書を削除しようとしています。この文書を削除してもサーバーの運用には影響しません。続行しますか？",

    "deleteStorage_title": "ストレージ設定の削除確認",
    "deleteStorage": "ストレージ設定文書を削除しようとしています。続行しますか？",

    "centerSaveInfor": "データが提出されました",
    "saveWeightError": "数字でなければなりません",

    "mobileSetting1": "1、確認",
    "mobileSetting2": "2、アカウント",
    "mobileSetting3": "3、サーバー",

    "checkCenterToCollect": "サーバーがO2センターに接続されています",
    "checkComputerToCollect": "クライアントがO2センターに接続されています",
    "success": "成功",
    "failure": "失敗",

    "reCheck": "接続を再確認",
    "next": "次へ",
    "loginCollect": "O2センターにログイン",
    "loggedCollect": "すでにO2センターにログインしています",
    "loginText": "O2センターログイン",
    "logoutText": "O2センターからログアウト",
    "registerText": "O2センターの企業アカウントをまだ持っていない場合、まず企業を登録してください",

    "loginInputUsername": "ユーザー名とパスワードを入力してください",
    "loginInputCode": "認証コードを入力してください",

    "companyName": "会社名",
    "code": "認証コード",
    "phone": "携帯電話番号",
    "password": "パスワードを入力",
    "confirmPassword": "パスワードの確認",

    "registerTitle": "会社をO2センターに登録してください",
    "getPhoneCode": "携帯電話認証コードを取得",
    "getPhoneCodeWait": "認証コードが送信されました",
    "registerActionText": "登録",
    "registerCancelActionText": "登録をキャンセル",
    "phoneError": "携帯電話番号を入力してください",
    "phoneTypeError": "正しい携帯電話番号を入力してください",
    "nameError": "会社名を入力してください",
    "codeError": "認証コードを入力してください",
    "passwordError": "パスワードを入力してください",
    "confirmError": "パスワードの確認を入力してください",
    "confirmPasswordError": "パスワードとパスワードの確認が一致しません",

    "cancelRegisterTitle": "登録キャンセル確認",
    "cancelRegister": "登録をキャンセルしてもよろしいですか？",
    "registerSuccess": "お客様の会社はすでにO2センターに登録されています<br/>「{name}」でO2センターにログインできます",
    "registerSuccessTitle": "お客様の会社はすでにO2センターに登録されています",

    "mobileServerSaveInfor": "データが提出されました",
    "mobileServerSaveErrorInfor": "データが提出されましたが、以下のエラーが発生しました：{error}",

    "saveDefaultMenuData": "デフォルトメニュー設定として保存",
    "clearDefaultMenuData": "デフォルトメニュー設定をクリア",
    "saveDefaultMenuDataInfor": "デフォルトメニュー設定として保存すると、個別のメニュー設定を行っていないユーザーはこの設定に従ってメニューが表示されます。",
    "saveDefaultMenuDataSuccess": "デフォルトメニュー設定が正常に保存されました",
    "clearDefaultMenuDataSuccess": "デフォルトメニュー設定がクリアされました",
    "clearDefaultMenuDataConfirm": "デフォルトメニュー設定をクリアしますか？",
    "loadDefaultMenuData": "デフォルト設定を読み込む",

    "saveForceMenuData": "強制メニュー設定として保存",
    "clearForceMenuData": "強制メニュー設定をクリア",
    "saveForceMenuDataInfor": "強制メニュー設定として保存すると、すべてのユーザーはこの設定に従ってメニューが表示され、個別の設定は無効になります。",
    "saveForceMenuDataSuccess": "強制メニュー設定が正常に保存されました",
    "clearForceMenuDataSuccess": "強制メニュー設定がクリアされました",
    "clearForceMenuDataConfirm": "強制メニュー設定をクリアしますか？",
    "loadForceMenuData": "強制設定を読み込む",

    "clearCustomMenuData": "ユーザー個別メニュー設定をクリア",
    "clearCustomMenuDataInfor": "すべてのユーザーの個別メニュー設定がクリアされ、デフォルト設定に従ってメニューが表示されます。",
    "clearCustomMenuDataSuccess": "ユーザー個別メニュー設定がクリアされました",
    "clearCustomMenuDataConfirm": "すべてのユーザーの個別メニュー設定をクリアしますか？"
};
