MWF.xApplication.Setting.LP = {
    "title": "시스템 설정",
	"default": "기본값",

	"tab_base": "기본 설정",
	"tab_ui": "인터페이스 설정",
	"tab_mobile": "모바일 오피스 설정",
	"tab_cloud": "클라우드 서비스 설정",
	"tab_dispose": "시스템 배포",
	"tab_name": "시스템 이름 설정",
	"tab_user": "시스템 사용자 설정",
	"tab_login": "시스템 로그인 설정",
	"tab_sso": "시스템 SSO 설정",
	"tab_config": "플랫폼 설정",

	"tab_cloud_connect": "연결 설정",

	"tab_mobile_connect": "연결 설정",
	"tab_mobile_module": "모듈 설정",
	"tab_mobile_style": "스타일 설정",
	"tab_mobile_mpweixin_menu": "공중 메뉴 설정",
	"tab_mobile_app_pack": "모바일 앱 온라인 패키지",

	"tab_ui_login": "로그인 페이지 스타일",
	"tab_ui_index": "홈페이지 스타일",
	"tab_ui_module": "모듈 배포",
	"tab_ui_resource": "자원 배포",
	"tab_ui_service": "서비스 배포",
	"tab_ui_menu": "메뉴 편집",

	"base_nameSetting": "시스템 이름 설정",

	"base_title": "시스템 이름",
	"base_title_infor": "시스템 이름은 로그인 페이지와 브라우저 제목 표시줄에 표시됩니다.",
	"base_title_action": "시스템 이름 편집",
	"base_title_empty": "시스템 이름을 입력하세요.",

	"base_footer": "시스템 부제목",
	"base_footer_infor": "시스템 부제목은 로그인 페이지 하단에 표시됩니다.",
	"base_footer_action": "시스템 부제목 편집",
	"base_version": "현재 시스템 버전",


    "base_personSetting": "사용자 계정 기본 정보 설정",
	"base_UserPassword": "신규 사용자의 기본 암호",
	"base_UserPassword_infor": "새로운 사용자를 만들 때 사용되는 기본 암호입니다. 사용자는 시스템에 로그인한 후 암호를 변경할 수 있습니다.",
	"base_UserPassword_action": "기본 암호 변경",
	"base_UserPassword_empty": "기본 암호를 입력하세요.",

	"base_passwordPeriod": "암호 만료 기간 (일)",
	"base_passwordPeriod_infor": "암호 변경을 요구하는 일 수를 나타냅니다. 이 기간 동안 암호를 변경하지 않은 사용자는 시스템에 로그인할 때 암호 변경이 필요합니다.",
	"base_passwordPeriod_action": "암호 만료 기간 변경",

	"base_adminPassword": "슈퍼 관리자 암호",
	"base_adminPassword_infor": "슈퍼 관리자 xadmin의 암호입니다.",
	"base_adminPassword_action": "슈퍼 관리자 암호 변경",
	"base_adminPassword_confirm": "<div style='color:red'>슈퍼 관리자 암호는 기본 데이터베이스 비밀번호와 관련이 있으므로 조심히 변경해야 합니다! <br>암호를 변경한 후 즉시 시스템을 다시 시작해야 하며, 그렇지 않으면 시스템이 오작동할 수 있습니다!</div><br>변경하시겠습니까?",

	"base_loginSetting": "사용자 로그인 옵션 설정",

	"base_captchaLogin": "이미지 인증 로그인 활성화",
	"base_captchaLogin_infor": "활성화하면 로그인 시 이미지 인증을 올바르게 입력해야 합니다.",
	"base_captchaLogin_action": "",

	"base_codeLogin": "SMS 코드 로그인 활성화",
	"base_codeLogin_infor": "활성화하면 SMS 코드를 사용하여 로그인할 수 있습니다.",
	"base_codeLogin_action": "",

	"base_bindLogin": "QR 코드 스캔 로그인 활성화",
	"base_bindLogin_infor": "활성화하면 QR 코드를 스캔하여 로그인할 수 있습니다.",

    "base_faceLogin": "얼굴 인식 로그인 활성화",
	"base_faceLogin_infor": "활성화하면 얼굴 인식 로그인이 허용됩니다. 사용자는 얼굴 특징을 개인 설정에서 설정할 수 있습니다. 활성화하려면 face로 명명된 SSO 구성을 만들어야 하며, 키는 xplatform이어야 합니다. (이것은 실험적인 기능이며, HTTPS를 활성화해야 함).",

	"base_faceApi": "얼굴 인식 서비스",
	"base_faceApi_action": "얼굴 인식 서비스 편집",
	"base_faceApi_delete": "얼굴 인식 서비스 삭제",
	"base_faceApi_infor": "Face++ 얼굴 서비스를 사용하여 API 키 및 API 비밀을 편집할 수 있습니다. 그렇지 않으면 시스템은 기본 계정을 사용하며 QPS가 제한됩니다.",

	"base_register": "자체 등록 활성화",
	"base_register_infor": "사용자가 시스템 사용자로 자체 등록할 수 있는지 및 등록 방법을 설정합니다.",
	"register_disable": "자체 등록 비활성화",
	"register_captcha": "이미지 인증을 사용한 자체 등록 허용",
	"register_code": "SMS 코드를 사용한 자체 등록 허용",

	"base_portalLogin": "포털 페이지를 사용하여 로그인",
	"base_portalLogin_infor": "맞춤형 포털 페이지를 로그인 페이지로 사용할 수 있으며, 로그인 페이지 템플릿은 앱 스토어에서 다운로드할 수 있습니다.",
	"base_portalLogin_action": "",

	"base_loginPortalId": "로그인 포털",
	"base_loginPortalId_infor": "로그인 페이지의 포털을 선택합니다.",

	"base_portalIndex": "시스템 홈페이지로 포털 페이지 사용",
	"base_portalIndex_infor": "맞춤형 포털 페이지를 시스템 홈페이지로 사용할 수 있으며, 로그인 후에 이 페이지가 열립니다.",
	"base_portalIndex_action": "",
	"base_indexPortalId": "시스템 홈페이지 포털",
	"base_indexPortalId_infor": "시스템 홈페이지의 포털을 선택합니다.",

	"base_temary": "3요 관리",
	"base_temary_info": "3요 관리(시스템 관리자, 보안 및 비밀 관리자, 보안 감사원)입니다. 이 기능을 활성화하려면 서버를 다시 시작해야 합니다.",
	"base_temary_action": "",

	"base_ldap": "LDAP 인증 활성화",
	"base_ldap_infor": "활성화하면 사용자 로그인 인증에 LDAP 인증을 사용하며 이 시스템의 비밀번호 로그인을 더 이상 사용하지 않습니다.",
	"base_ldap_action": "LDAP 인증 구성 편집",
	"base_ldap_enable": "활성화됨",
	"base_ldap_unenable": "비활성화됨",


    "base_ssoSetting": "다른 시스템의 인증 및 싱글 사인온 설정 구성",
	"base_ssos": "인증 구성",
	"base_sso_infor": "SSO 로그인 및 서비스 호출에 사용할 수 있는 다양한 시스템에 대한 인증을 만들 수 있습니다.",
	"base_sso_action": "인증 구성 추가",
	"base_sso_editAction": "인증 구성 편집",

	"base_oauths": "OAUTH 클라이언트 구성",
	"base_oauths_infor": "이 시스템이 OAUTH2 인증 서버로 작동하는 경우, 다른 시스템에 권한 부여를 위해 다양한 OAUTH 클라이언트를 구성할 수 있습니다.",
	"base_oauths_action": "OAuth 구성 추가",
	"base_oauths_editAction": "OAuth 구성 편집",

	"base_oauths_server": "OAUTH 서버 구성",
	"base_oauths_infor_server": "이 시스템이 다른 OAUTH2 서버를 통해 인증을 수행해야 하는 경우, 이 시스템에 권한 부여를 위해 다양한 OAUTH 서버를 구성할 수 있습니다.",

	"base_qyweixin": "기업 위챗 구성",
	"base_qyweixin_infor": "시스템은 기업 위챗과 통합될 수 있으며, 먼저 위챗 기업 번호 및 키를 구성해야 합니다.",
	"base_qyweixin_action": "기업 위챗 구성 편집",

	"base_dingding": "딩딩 구성",
	"base_dingding_infor": "시스템은 딩딩과 통합될 수 있으며, 먼저 딩딩 기업 번호 및 키를 구성해야 합니다.",
	"base_dingding_action": "딩딩 구성 편집",

	"mobile_connectSetting": "모바일 오피스 연결 구성",
	"cloud_connectSetting": "클라우드 서비스 연결 구성",
	"mobile_connect_first_cloud_check": "1. 클라우드 서비스 연결 확인",
	"mobile_connect_first_cloud_check_connected": "<span style='color: #5fbf78'> [연결된 로그인] </span> 클라우드 서비스",
	"mobile_connect_first_cloud_check_disconnected": "<span style='color: #ff0000'> [연결되지 않은 로그인] </span> 클라우드 서비스, 클라우드 서비스 설정 페이지에서 로그인을 등록하십시오!",
	"mobile_connect_connectSetting": "2. 외부 네트워크 연결 구성",
	"mobile_connect_third_mobile_connect_check": "3. 모바일 연결 테스트",
	"mobile_connect_third_mobile_connect_check_info": "모바일로 QR 코드를 스캔하여 외부 네트워크에서 서버에 연결 가능한지 확인하십시오!",
	"mobile_connect_third_mobile_connect_check_generate_button": "QR 코드 생성",

	"mobile_connectO2Cloud": "O2 클라우드에 연결",
	"mobile_connectO2Cloud_infor": "모바일 오피스를 사용하려면 먼저 O2 클라우드에 연결하십시오. 이렇게 하면 앱이 회사 서버를 확인할 수 있어 SMS 서비스 등을 사용할 수 있습니다.",
	"mobile_connectO2Cloud_action": "O2 클라우드에 연결",
	"mobile_connectO2Cloud_success": "연결 설정",
	"mobile_connectO2Cloud_error": "아직 O2 클라우드에 연결되지 않았습니다.",

    "mobile_httpProtocol": "HTTP 프로토콜",
	"mobile_httpProtocol_infor": "HTTP 프로토콜 또는 HTTPS 프로토콜을 선택하십시오.",

	"mobile_center": "중앙 서버",
	"mobile_center_infor": "중앙 서버의 공용 서비스 IP 주소 또는 도메인 및 포트입니다. (HTTP 프로토콜을 사용하는 경우 IP 주소만 사용할 수 있음)",
	"mobile_center_action": "중앙 서버 편집",

	"mobile_web": "웹 서버",
	"mobile_web_infor": "웹 서버의 공용 서비스 IP 주소 또는 도메인 및 포트입니다. 도메인 또는 IP 주소가 비어 있거나 '127.0.0.1'인 경우 중앙 서버 주소를 사용합니다. (HTTP 프로토콜을 사용하는 경우 IP 주소만 사용할 수 있음)",
	"mobile_web_action": "웹 서버 편집",

	"mobile_application": "애플리케이션 서버",
	"mobile_application_infor": "애플리케이션 서버의 공용 서비스 IP 주소 또는 도메인 및 포트입니다. 도메인 또는 IP 주소가 비어 있거나 '127.0.0.1'인 경우 중앙 서버 주소를 사용합니다. (HTTP 프로토콜을 사용하는 경우 IP 주소만 사용할 수 있음)",
	"mobile_application_action": "애플리케이션 서버 편집",

	"mobile_moduleSetting": "모바일 모듈 설정",
	"mobile_index": "모바일 홈페이지 설정",
	"mobile_index_infor": "모바일 홈페이지를 기본 앱 스타일 또는 특정 포털 페이지로 설정할 수 있습니다.",
	"mobile_index_defalue": "기본",

	"mobile_module": "{name} 모듈",
	"mobile_module_infor": "모바일에서 {name} 모듈을 활성화하시겠습니까?",

	"mobile_module_simple_mode": "모바일 간편 모드",
	"mobile_module_simple_mode_infor": "모바일 간편 모드를 활성화하면 홈페이지와 설정 페이지만 표시됩니다.",

	"mobile_module_system_message_switch": "시스템 알림 표시",
	"mobile_module_system_message_switch_infor": "모바일 앱 메시지 목록에 시스템 알림을 표시하시겠습니까?",

	"mobile_module_contact_permission_view": "모바일 앱 주소록 권한 뷰어",
	"mobile_module_contact_permission_view_infor": "앱 마켓에서 '주소록' 앱을 설치해야 합니다. 해당 앱에는 주소록 권한 구성 뷰어가 포함되어 있습니다.",
	"mobile_module_contact_permission_view_action": "뷰어 이름 편집",

	"mobile_styleSetting": "모바일 아이콘 스타일 설정",
	"mobile_style": "{name} 이미지",
	"mobile_style_infor": "{name} 이미지를 변경하려면 클릭하십시오.",
    "mobile_style_imgs": {
		"launch_logo": "시작 로고",
		"login_avatar": "로그인 화면 기본 아바타",
		"application_top": "앱 화면 상단",
		"index_bottom_menu_logo_blur": "홈 네비게이션 아이콘 (선택 안 됨)",
		"index_bottom_menu_logo_focus": "홈 네비게이션 아이콘 (선택됨)",
		"people_avatar_default": "사용자 기본 아바타",
		"process_default": "프로세스 기본 아이콘",
		"setup_about_logo": "소개 페이지 아이콘"
	},
	"mobile_style_imgs_defaultTitle": "기본 이미지 확인",
	"mobile_style_imgs_defaultInfor": "{name}를 기본 이미지로 바꾸시겠습니까?",

    "mpweixin": "공중계정",
	"publishMpweixin": "웨이보 공중계정에 게시",
	"subscribeMpweixin": "구독 회신",
	"subscribeMpweixin_desc": "신규 사용자가 구독하면 자동으로 전송되는 메시지 내용",
	"subscribeMpweixin_save": "저장",
	"mpweixinInfo": "⚠️ 웨이보 메뉴 기능을 사용하려면 먼저 관련 설정 파일 [mpweixin.json]을 활성화하고 웨이보 관리자 백엔드에서 서버 설정을 활성화해야 합니다!",
	"mobile_mpweixin_menu_msg_publish_2_wxmp": "주의! 현재 작업은 모든 저장된 메뉴 데이터를 웨이보 공중계정에 덮어씌울 것입니다. 계속하시겠습니까?",
	"mobile_mpweixin_menu_msg_publish_success": "게시 성공, 모바일에서 24시간 후에 동기화됩니다!",
	"mobile_mpweixin_menu_msg_first_max_len": "1급 메뉴는 최대 3개까지만 만들 수 있습니다!",
	"mobile_mpweixin_menu_msg_sub_max_len": "2급 메뉴는 최대 5개까지만 만들 수 있습니다!",
	"mobile_mpweixin_menu_msg_parent_no_save": "상위 메뉴 데이터가 저장되지 않았습니다. 먼저 데이터를 저장하십시오!",
	"mobile_mpweixin_menu_deleteBtnName_label": "메뉴 삭제",
	"mobile_mpweixin_menu_default_new_name": "새 메뉴",
	"mobile_mpweixin_menu_form_name_label": "메뉴 이름",
	"mobile_mpweixin_menu_form_name_error_empty": "메뉴 이름을 입력하세요!",
	"mobile_mpweixin_menu_form_name_error_max_len_4": "메뉴 이름은 4자 이내여야 합니다!",
	"mobile_mpweixin_menu_form_name_error_max_len_6": "메뉴 이름은 6자 이내여야 합니다!",
	"mobile_mpweixin_menu_form_name_error": "문자 제한을 초과했습니다",
	"mobile_mpweixin_menu_form_name_tips_4": "한글, 영문, 숫자만 허용하며 4자 이내여야 합니다",
	"mobile_mpweixin_menu_form_name_tips_6": "한글, 영문, 숫자만 허용하며 6자 이내여야 합니다",
	"mobile_mpweixin_menu_form_order_label": "메뉴 정렬 번호",
	"mobile_mpweixin_menu_form_order_error_empty": "메뉴 정렬 번호를 입력하세요!",
	"mobile_mpweixin_menu_form_order_error_not_number": "메뉴 정렬 번호는 숫자만 입력할 수 있습니다!",
	"mobile_mpweixin_menu_form_order_error_max_len": "메뉴 정렬 번호는 6자 이내여야 합니다!",
	"mobile_mpweixin_menu_form_order_error": "문자 제한을 초과했습니다",
	"mobile_mpweixin_menu_form_order_tips": "숫자만 입력할 수 있으며 6자 이내로 정렬되며 문자열로 정렬됩니다",
	"mobile_mpweixin_menu_form_radio_label": "메뉴 내용",
	"mobile_mpweixin_menu_form_radio_type_msg": "메시지 보내기",
	"mobile_mpweixin_menu_form_radio_type_url": "웹 페이지로 이동",
	"mobile_mpweixin_menu_form_radio_type_miniprogram": "소규모 프로그램으로 이동",
	"mobile_mpweixin_menu_form_type_msg_tips": "이 메뉴를 클릭하면 사용자에게 다음 텍스트가 전송됩니다. 인증되지 않은 구독 계정은 텍스트 메시지를 지원하지 않습니다",
	"mobile_mpweixin_menu_form_type_msg_label": "텍스트 메시지",
	"mobile_mpweixin_menu_form_type_msg_error_empty": "텍스트 메시지 내용을 입력하세요!",
	"mobile_mpweixin_menu_form_subscribe_content_error_empty": "회신 메시지 내용을 입력하세요!",
	"mobile_mpweixin_menu_form_type_url_tips": "이 메뉴를 클릭하면 다음 링크로 이동합니다",
	"mobile_mpweixin_menu_form_type_url_label": "페이지 주소",
	"mobile_mpweixin_menu_form_type_url_error_empty": "페이지 주소를 입력하세요!",
	"mobile_mpweixin_menu_form_type_miniprogram_tips": "이 메뉴를 클릭하면 다음 소규모 프로그램으로 이동합니다",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_label": "소규모 프로그램 ID",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_placeholder": "소규모 프로그램 ID를 확인하려면 웨이보의 소규모 프로그램 관리 백엔드로 이동하십시오",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_error_empty": "소규모 프로그램 ID를 입력하세요!",
	"mobile_mpweixin_menu_form_type_miniprogram_path_label": "소규모 프로그램 경로",
	"mobile_mpweixin_menu_form_type_miniprogram_path_placeholder": "소규모 프로그램 경로를 확인하려면 웨이보의 소규모 프로그램 관리 백엔드로 이동하십시오",
	"mobile_mpweixin_menu_form_type_miniprogram_path_error_empty": "소규모 프로그램 경로를 입력하세요!",
	"mobile_mpweixin_menu_form_type_miniprogram_url_label": "백업 웹 페이지",
	"mobile_mpweixin_menu_form_type_miniprogram_url_placeholder": "백업 웹 페이지로 이동할 때 사용됩니다. 이전 버전의 웨이보는 이 백업 웹 페이지를 엽니다",
	"mobile_mpweixin_menu_form_type_miniprogram_url_error_empty": "백업 웹 페이지를 입력하세요!",
	"mobile_mpweixin_menu_save_success": "데이터 저장 성공!",
	"mobile_mpweixin_menu_delete_alert_msg": "이 데이터를 삭제하시겠습니까? 하위 메뉴도 동시에 삭제됩니다.",
	"mobile_mpweixin_menu_delete_success": "데이터 삭제 성공!",
    
    
    "save": "저장",
	"alert": "알림",
	"mobile_apppack_tips1": "⚠️ 현재 모바일 앱 온라인 패키징 기능은 Android만 지원합니다.",
	"mobile_apppack_tips2": "⚠️ 온라인 패키징을 위해 먼저 [클라우드 서비스 구성]에서 등록 및 로그인해야 합니다.",
	"mobile_apppack_tips3": "⚠️ 정보를 제출하면 현재 패키징 상태가 표시되며 패키징 프로세스는 시간이 오래 걸립니다. 패키징이 완료될 때까지 현재 페이지를 떠나서 APK 파일을 다운로드할 수 있습니다.",
	"mobile_apppack_status_label": "현재 상태",
	"mobile_apppack_form_appName": "앱 이름",
	"mobile_apppack_form_appName_tip": "앱 데스크톱에 표시되는 이름, 6자 이내",
	"mobile_apppack_form_logo": "로고 이미지",
	"mobile_apppack_form_logo_tip": "앱 데스크톱에 표시되는 로고 이미지, 반드시 PNG 형식이어야 함",
	"mobile_apppack_form_protocol": "HTTP 프로토콜",
	"mobile_apppack_form_protocol_tip": "http / https",
	"mobile_apppack_form_host": "도메인",
	"mobile_apppack_form_host_tip": "중앙 서버 도메인 또는 IP, 예: www.o2oa.net",
	"mobile_apppack_form_port": "포트 번호",
	"mobile_apppack_form_port_tip": "중앙 서버 포트 번호, 예: 20030",
	"mobile_apppack_form_context": "컨텍스트",
	"mobile_apppack_form_context_tip": "중앙 서버 컨텍스트, 예: /x_program_center",
	"mobile_apppack_form_urlMapping": "프록시 urlMapping",
	"mobile_apppack_form_urlMapping_tip": "서버 외부에서 프록시 주소 사용 시 사용, 예: {\"demo.o2oa.net:20020\": \"demo.o2oa.net/dev/app\"}",
	"mobile_apppack_form_appVersionName": "앱 버전 이름",
	"mobile_apppack_form_appVersionName_tip": "앱 버전 이름, 예: v1.0.0. 이 필드는 기본적으로 작성하지 않아도 됩니다.",
	"mobile_apppack_form_appBuildNo": "앱 버전 번호",
	"mobile_apppack_form_appBuildNo_tip": "앱 버전 번호, 반드시 양의 정수여야 함, 예: 100. 이 필드는 기본적으로 작성하지 않아도 됩니다.",
	"mobile_apppack_form_button": "제출 및 패키징 시작",
	"mobile_apppack_form_reinput_button": "양식 다시 작성 및 패키징",
	"mobile_apppack_form_re_pack_button": "기존 데이터 사용하여 패키징",
	"mobile_apppack_form_download_apk_button": "APK 파일 다운로드",
	"mobile_apppack_message_o2cloud_not_enable": "O2 클라우드가 활성화되지 않았거나 연결할 수 없습니다!",
	"mobile_apppack_message_o2cloud_not_login": "먼저 O2 클라우드에 로그인하세요!",
	"mobile_apppack_message_apppack_server_login_fail": "앱 패키징 서버 로그인에 실패했습니다!",
	"mobile_apppack_message_check_connect_fail": "앱 패키징 서비스 연결 확인에 실패했습니다!",

    "mobile_apppack_form_enable_outer_status_no": "미사용",
	"mobile_apppack_form_enable_outer_status_yes": "사용",
	"mobile_apppack_form_enable_outer_package": "외부 패키지명 사용 여부",
	"mobile_apppack_form_enable_delete_hms": "HMS 제거 여부",
	"mobile_apppack_form_enable_outer_tips": "외부 패키지명 사용은 공식 출시 앱과 충돌 및 덮어쓰기를 방지합니다",
	"mobile_apppack_form_enable_delete_hms_tips": "HMS 제거로는 HUAWEI 푸시를 사용할 수 없으니 신중하게 조작하세요.",
	"mobile_apppack_form_enable_delete_hms_status_no": "아니오",
	"mobile_apppack_form_enable_delete_hms_status_yes": "예",
	"mobile_apppack_form_download_publish_btn": "로컬로 발행 다운로드",
	"mobile_apppack_message_confirm_publish": "앱이 이미 패키징되었습니다. 즉시 다운로드하여 로컬 서버에 발행하고 QR 코드를 스캔하여 앱을 설치할 수 있습니다!",
	"mobile_apppack_publish_status_doing": "발행 중...",
	"mobile_apppack_publish_status_completed": "발행 완료, 로그인 화면의 QR 코드를 스캔하여 앱을 설치할 수 있습니다!",
	"mobile_apppack_publish_status_fail": "발행 실패, 다시 시도하거나 관리자에게 문의하십시오!",
	"mobile_apppack_status_order_inline": "대기 중...",
	"mobile_apppack_status_packing": "패키징 중...",
	"mobile_apppack_status_pack_end": "패키징 완료",
	"mobile_apppack_status_pack_error": "패키징 오류",
	"mobile_apppack_message_appname_not_empty": "앱 이름을 입력하십시오!",
	"mobile_apppack_message_appname_len_max_6": "앱 이름은 6자를 초과할 수 없습니다!",
	"mobile_apppack_message_app_logo_not_empty": "로고 이미지를 선택하십시오!",
	"mobile_apppack_message_app_logo_need_png": "로고 이미지는 PNG 형식이어야 합니다!",
	"mobile_apppack_message_portocol_not_empty": "HTTP 프로토콜을 입력하십시오!",
	"mobile_apppack_message_host_not_empty": "중앙 서버 도메인을 입력하십시오!",
	"mobile_apppack_message_host_format_error": "중앙 서버 도메인이나 IP를 입력하십시오. 예: www.o2oa.net, http와 같은 프로토콜을 제외하십시오!",
	"mobile_apppack_message_port_not_empty": "중앙 서버 포트 번호를 입력하십시오!",
	"mobile_apppack_message_context_not_empty": "중앙 서버 컨텍스트를 입력하십시오!",
	"mobile_apppack_message_portocol_http_https": "HTTP 프로토콜은 http 또는 https만 허용됩니다!",
	"mobile_apppack_refresh_status_btn": "상태 새로 고침",
	"mobile_apppack_message_alert_submit": "제출하시겠습니까? 현재 양식 정보가 모바일 앱으로 패키징됩니다.",
	"imgSize": "이미지 크기:",
	"defaultImg": "기본 이미지",

    "ui_loginSetting": "로그인 페이지 스타일 설정",
    "ui_login_default": "기본 스타일",
    "ui_login_defaultStyle": "로그인 페이지 기본 스타일",
    "ui_login_defaultStyle_infor": "",
    "ui_login_customStyle": "로그인 페이지 사용자 정의 스타일",
    "ui_login_customStyle_infor": "",
    "ui_login_customStyle_Action": "사용자 정의 스타일 생성",
    "ui_login_customStyle_newName": "새로운 스타일 이름",
    "ui_login_customStyle_newName_empty": "새 스타일 이름을 입력하세요",
    "ui_login_setCurrent": "이 스타일 사용",
    "ui_login_current": "현재 사용 중인 스타일",
    "ui_login_setCurrent_confirmTitle": "스타일 사용 확인",
    "ui_login_setCurrent_confirm": "정말로 “{title}” 스타일을 사용하시겠습니까?",

    "ui_login_delete_confirmTitle": "스타일 삭제 확인",
    "ui_login_delete_confirm": "정말로 “{title}” 스타일을 삭제하시겠습니까?",

    "ui_indexSetting": "플랫폼 스타일 구성",
    "ui_index_systemStyle": "플랫폼 내장 스타일",
    "ui_index_systemStyle_infor": "",

    "ui_index_customStyle": "사용자 정의 스타일 구성",
    "ui_index_customStyle_infor": "",
    "ui_index_customStyle_Action": "",
    "ui_index_enabled": "사용 가능",
    "ui_index_disabled": "사용 불가",

    "ui_moduleSetting": "시스템 모듈 구성",
    "ui_module_modules": "설치된 모듈",
    "ui_module_modules_infor": "",
    "ui_module_modules_Action": "모듈 설치",

    "ui_moduleSetting_resource": "웹 리소스 설치",
    "ui_moduleSetting_service": "서비스 설치",

    "resource_upload": "자원 선택",
    "resource_replace": "덮어쓸까요?",
    "resource_replaceDesc": "덮어쓰기 유형: '아니오'는 원본 파일을 삭제하고 업로드합니다. '예'는 원본 파일을 덮어씁니다.",
    "resource_replace_yes": "예",
    "resource_replace_no": "아니오",
    "resource_filePath": "저장 디렉터리",
    "resource_filePathDesc": "zip 파일은 비워 둘 수 있으며, 다른 파일은 비워 둘 수 없습니다. 경로: /xxx/xxx",
    "resource_success": "배포 성공",

    "service_ctl": "명령 이름",
    "service_node": "서버 노드",
    "service_allNode": "모든 노드",
    "service_success": "배포 성공, 서비스를 다시 시작해야 합니다.",

    "on": "켜기",
    "off": "끄기",

    "loading": "스타일을 불러오는 중입니다. 잠시 기다려주세요...",
    "returnBack": "돌아가기",

    "ok": "확인",
    "cancel": "취소",
    "edit": "편집",
    "delete": "삭제",
    "copy": "복사",
    "copyName": "복사",

    "deleteItem": "구성 삭제 확인",
    "deleteItemInfor": "이 항목을 삭제하시겠습니까?",

    "setSaved": "구성 데이터가 저장되었습니다.",

    "pleaseInput": "입력해 주세요",
    "list": {
        "client": "인증 이름",
        "key": "키 (최소 8 자)",
        "clientId": "클라이언트 ID",
        "mapping": "매핑 (Mapping)",
        "corpId": "corpId",
        "corpSecret": "corpSecret",
        "agentId": "에이전트 ID",
        "proxyHost": "도메인 또는 IP 주소",
        "proxyPort": "포트",
        "node": "애플리케이션 서버",

        "enable": "사용 여부",
        "name": "이름",
        "icon": "아이콘",
        "clientSecret": "클라이언트 비밀",
        "authAddress": "인증 키 URL",
        "authParameter": "인증 키 메서드 매개변수",
        "authMethod": "인증 키 메서드 (GET 또는 POST)",
        "tokenAddress": "토큰 URL",
        "tokenParameter": "토큰 메서드 매개변수",
        "tokenMethod": "토큰 메서드 (GET 또는 POST)",
        "tokenType": "토큰 정보 형식 (json 또는 form)",
        "infoAddress": "정보 URL",
        "infoParameter": "정보 메서드 매개변수",
        "infoMethod": "정보 메서드 (GET 또는 POST)",
        "infoType": "정보 정보 형식 (json 또는 form)",
        "infoCredentialField": "개인 식별을 식별하는 데 사용되는 정보 필드",

        "infoProxyHost" : "도메인은 http를 포함하지 않아야 합니다",

        "ldapUrl": "ldapUrl(LDAP 주소, 예: ldap://111.111.111.111:5389/)",
        "baseDn": "baseDn(LDAP 쿼리의 루트 이름, 예: dc=zone,DC=COM)",
        "userDn": "userDn(인증 사용자의 DN, 예: uid=*,ou=users,dc=zone,DC=COM, 여기서 uid=* 중의 *은 사용자의 고유 코드를 나타내며, 이 고유 코드는 O2 사용자의 고유 코드와 대응합니다)"
    },

    "module": {
        "title": "애플리케이션 배포",
        "open": "열기",
        "edit": "편집",
        "remove": "제거",
        "add": "컴포넌트 배포",

        "name": "컴포넌트 이름",
        "componentTitle": "컴포넌트 제목",
        "path": "컴포넌트 경로",
        "icon": "컴포넌트 아이콘",
        "isVisible": "가시 여부",
        "yes": "예",
        "no": "아니오",
        "widgetName": "위젯 이름",
        "widgetTitle": "위젯 제목",
        "widgetStart": "위젯 자동 시작",
        "widgetVisible": "위젯 가시 여부",

        "allowList": "접근 허용 목록",
        "denyList": "접근 거부 목록",
        "controllerList": "관리자",
        "selPerson": "사용자 선택",
        "selIcon": "아이콘 선택",
        "urlInfor": "경로를 웹 페이지 URL로 추가할 수 있습니다. 예: '@url:http://www.bing.com'",

        "phone": "전화번호",
        "mail": "이메일",

        "noInputInfor": "컴포넌트 정보를 모두 입력하세요. (컴포넌트 이름, 컴포넌트 제목, 컴포넌트 경로는 필수 입력 사항입니다.)",
        "deploySuccess": "배포 성공",
        "modifySuccess": "컴포넌트 정보 수정 성공",

        "removeComponentTitle": "컴포넌트 제거 확인",
        "removeComponent": "컴포넌트 {name}을/를 제거하시겠습니까?",
        "removeComponentOk": "컴포넌트가 제거되었습니다",

        "modify": "컴포넌트 정보 수정",

        "moduleDeployed" : "배포된 컴포넌트",
        "inputAppNameNotice" : "애플리케이션 이름과 제목을 입력하세요",
        "uploadZipFileNotice": "파일의 ZIP 패키지를 업로드하세요"
    },






    "tab_centerServer": "센터 서버",
    "tab_Server": "서비스 호스트 설정",
    "tab_Application": "애플리케이션 데이터 설정",
    "tab_Resource": "자원 매개변수 설정",
    "tab_Mobile": "모바일 오피스 설정",

    "tab_ApplicationServer": "애플리케이션 서버",
    "tab_DataServer": "데이터베이스 서버",
    "tab_StorageServer": "스토리지 서버",
    "tab_WebServer": "웹 서버",

    "deploy": "애플리케이션 배포",
    "deleteAppServer_title": "애플리케이션 서버 설정 제거 확인",
    "deleteAppServer": "애플리케이션 서버 설정 문서를 제거하려고 합니다. 이 문서를 제거하면 서버 운영에는 영향을 미치지 않습니다. 계속하시겠습니까?",
    "deployAppServer_title": "애플리케이션 배포 확인",
    "deployAppServer": "현재 서버에 애플리케이션을 배포하려고 합니다. 확인하시겠습니까?<br><br><div style='color: #F00'><input type='checkbox'> 모든 애플리케이션을 다시 배포</div>",

    "deleteDataServer_title": "데이터베이스 서버 설정 제거 확인",
    "deleteDataServer": "데이터베이스 서버 설정 문서를 제거하려고 합니다. 이 문서를 제거하면 서버 운영에는 영향을 미치지 않습니다. 계속하시겠습니까?",

    "deleteStorageServer_title": "스토리지 서버 설정 제거 확인",
    "deleteStorageServer": "스토리지 서버 설정 문서를 제거하려고 합니다. 이 문서를 제거하면 서버 운영에는 영향을 미치지 않습니다. 계속하시겠습니까?",

    "deleteWebServer_title": "웹 서버 설정 제거 확인",
    "deleteWebServer": "웹 서버 설정 문서를 제거하려고 합니다. 이 문서를 제거하면 서버 운영에는 영향을 미치지 않습니다. 계속하시겠습니까?",

    "deleteStorage_title": "스토리지 설정 제거 확인",
    "deleteStorage": "스토리지 설정 문서를 제거하려고 합니다. 계속하시겠습니까?",

    "centerSaveInfor": "데이터가 제출되었습니다",
    "saveWeightError": "숫자여야 합니다",

    "mobileSetting1": "1. 점검",
    "mobileSetting2": "2. 계정",
    "mobileSetting3": "3. 서버",

    "checkCenterToCollect": "서버가 O2 센터에 연결됨",
    "checkComputerToCollect": "클라이언트가 O2 센터에 연결됨",
    "success": "성공",
    "failure": "실패",

    "reCheck": "연결 재확인",
    "next": "다음",
    "loginCollect": "O2 센터에 로그인",
    "loggedCollect": "이미 O2 센터에 로그인되었습니다",
    "loginText": "O2 센터 로그인",
    "logoutText": "O2 센터에서 로그아웃",
    "registerText": "아직 O2 센터 회사 계정이 없다면 먼저 회사를 등록하세요",

    "loginInputUsername": "사용자 이름과 비밀번호를 입력하세요",
    "loginInputCode": "인증 코드를 입력하세요",

    "companyName": "회사 이름",
    "code": "인증 코드",
    "phone": "휴대전화 번호",
    "password": "비밀번호 입력",
    "confirmPassword": "비밀번호 확인",

    "registerTitle": "회사를 O2 센터에 등록하세요",
    "getPhoneCode": "휴대전화 인증 코드 받기",
    "getPhoneCodeWait": "인증 코드가 발송되었습니다",
    "registerActionText": "등 록",
    "registerCancelActionText": "등록 취소",
    "phoneError": "휴대전화 번호를 입력하세요",
    "phoneTypeError": "정확한 휴대전화 번호를 입력하세요",
    "nameError": "회사 이름을 입력하세요",
    "codeError": "인증 코드를 입력하세요",
    "passwordError": "비밀번호를 입력하세요",
    "confirmError": "비밀번호 확인을 입력하세요",
    "confirmPasswordError": "비밀번호와 비밀번호 확인이 일치하지 않습니다",

    "cancelRegisterTitle": "등록 취소 확인",
    "cancelRegister": "등록을 취소하시겠습니까?",
    "registerSuccess": "회사가 이미 O2 센터에 성공적으로 등록되었습니다<br/>\"{name}\"로 O2 센터에 로그인할 수 있습니다",
    "registerSuccessTitle": "회사가 이미 O2 센터에 성공적으로 등록되었습니다",

    "mobileServerSaveInfor": "데이터가 제출되었습니다",
    "mobileServerSaveErrorInfor": "데이터가 제출되었지만 다음 오류가 발생했습니다: {error}",

    "saveDefaultMenuData": "기본 메뉴 설정으로 저장",
    "clearDefaultMenuData": "기본 메뉴 설정 지우기",
    "saveDefaultMenuDataInfor": "기본 메뉴 설정으로 저장하면 개인화된 메뉴 설정을 하지 않은 사용자는 이 설정에 따라 메뉴가 표시됩니다.",
    "saveDefaultMenuDataSuccess": "기본 메뉴 설정이 성공적으로 저장되었습니다",
    "clearDefaultMenuDataSuccess": "기본 메뉴 설정이 지워졌습니다",
    "clearDefaultMenuDataConfirm": "기본 메뉴 설정을 지우시겠습니까?",
    "loadDefaultMenuData": "기본 설정 불러오기",

    "saveForceMenuData": "강제 메뉴 설정으로 저장",
    "clearForceMenuData": "강제 메뉴 설정 지우기",
    "saveForceMenuDataInfor": "강제 메뉴 설정으로 저장하면 모든 사용자는 이 설정에 따라 메뉴가 표시되며 개인화 설정은 무효화됩니다.",
    "saveForceMenuDataSuccess": "강제 메뉴 설정이 성공적으로 저장되었습니다",
    "clearForceMenuDataSuccess": "강제 메뉴 설정이 지워졌습니다",
    "clearForceMenuDataConfirm": "강제 메뉴 설정을 지우시겠습니까?",
    "loadForceMenuData": "강제 설정 불러오기",

    "clearCustomMenuData": "사용자 맞춤 메뉴 설정 지우기",
    "clearCustomMenuDataInfor": "모든 사용자의 맞춤 메뉴 설정이 지워지며 기본 설정대로 메뉴가 표시됩니다.",
    "clearCustomMenuDataSuccess": "사용자 맞춤 메뉴 설정이 지워졌습니다",
    "clearCustomMenuDataConfirm": "모든 사용자의 맞춤 메뉴 설정을 지우시겠습니까?"
};
