MWF.xApplication.Setting.LP = {
    "title": "ຕັ້ງຄ່າລະບົບ",
    "default": "ຄ່າເລີ່ມຕົ້ນ",

    "tab_base": "ຕັ້ງຄ່າພື້ນຖານ",
    "tab_ui": "ຕັ້ງຄ່າ interface",
    "tab_mobile": "ຕັ້ງຄ່າໂທລະສັບ",
    "tab_cloud": "ຕັ້ງຄ່າ Cloud",
    "tab_dispose": "ລະບົບ",
    "tab_name": "ຕັ້ງຄ່າຊື່ລະບົບ",
    "tab_user": "ຕັ້ງຄ່າຊື່ຜູ້ໃຊ້",
    "tab_login": "ຕັ້ງຄ່າເຂົ້າສູ່ລະບົບ",
    "tab_sso": "ຕັ້ງຄ່າລະບົບSSO",
    "tab_config": "ຕັ້ງຄ່າເອກະສນ",

    "tab_cloud_connect": "ຕັ້ງຄ່າການເຊື່ອມຕໍ່",

    "tab_mobile_connect": "ຕັ້ງຄ່າການເຊື່ອມຕໍ່",
    "tab_mobile_module": "ຕັ້ງຄ່າ Module ",
    "tab_mobile_style": "ຕັ້ງຄ່າຮູບແບບ",
    "tab_mobile_mpweixin_menu": "ຕັ້ງຄ່າເມນູ Wechat",
    "tab_mobile_app_pack": "App Pack Online",

    "tab_ui_login": "ຮູບແບບເຂົ້າສູ່ລະບົບ",
    "tab_ui_index": "ຮູບແບບໜ້າຫຼັກ",
    "tab_ui_module": "Module",
    "tab_ui_resource": "ນຳໃຊ້ຊັບພະຍາກອນ",
    "tab_ui_service": "Service",
    "tab_ui_menu": "ແກ້ໄຂເມນູ",

    "base_nameSetting": "ກຳນົດຊື່ລະບົບຂອງເຈົ້າ",

    "base_title": "ລະບົບຊື່",
    "base_title_infor": "ລະບົບຂອງເຈົ້າຊື່，ມັນຈະສະແດງຢູ່ໃນໜ້າເຂົ້າສູ່ລະບົບ ແລະ ແຖບຫົວຂໍ້ໜ້າເວັບຂອງເຈົ້າ",
    "base_title_action": "ແກ້ໄຂລະບົບຊື່",
    "base_title_empty": "ລະບົບຊື່ບໍ່ສາມາດເວັ້ນວ່າງໄດ້，ກະລຸນາຢືນຢັນລະບົບຊື່",

    "base_footer": "ຄຳບັນຍາຍຂອງລະບົບ",
    "base_footer_infor": "ຄຳບັນຍາຍຂອງເຈົ້າ，ມັນຈະສະແດງຢູ່ຂຶ້ນຢູ້ກ້ອງເຂົ້າສູ່ລະບົບ",
    "base_footer_action": "ແກ້ໄຂລະບົບບັນຍາຍ",
    "base_version": "Version ປະຈຸບັນຂອງລະບົບ",


    "base_personSetting": "ຕັ້ງຄ່າຂໍ້ມູນພື້ນຖານຂອງບັນຊີບຸກຄົນໃນລະບົບ",
    "base_UserPassword": "ກຳນົດລະຫັດຜ່ານຊື່ຜູ້ໃຊ້ໃໝ່",
    "base_UserPassword_infor": "ເມື່ອສ້າງຊື່ຜູ້ໃຊ້，ໃຊ້ລະຫັດຜ່ານຕໍ່ໄປນີ້，ຜູ້ໃຊ້ສາມາດແກ້ໄຂມັນດ້ວຍຕົນເອງຫຼັກຈາກເຂົ້າສູ່ລະບົບ",
    "base_UserPassword_action": "ປ່ຽນລະຫັດຜ່ານ",
    "base_UserPassword_empty": "ລະຫັດບໍ່ສາມາດເວັ້ນວ່າງໄດ້",

    "base_passwordPeriod": "ເວລາໝົດອາຍຸລະຫັດຜ່ານ（ມື້）",
    "base_passwordPeriod_infor": "ຜູ້ໃຊ້ບໍ່ໄດ້ປ່ຽນລະຫັດຜ່ານເປັນເວລາດົນນານກວ່າກຳນົດ，ຫຼັງຈາກເຂົ້າສູ່ລະບົບເຈົ້າຈະຖືກບັງຄັບໃຫ້ປ່ຽນລະຫັດ，ບໍ່ສະນັ້ນເຈົ້າຈະບໍ່ສາມາດເຂົ້າສູ່ລະບົບໄດ້",
    "base_passwordPeriod_action": "ປ່ຽນລະຫັດຜ່ານໝົດອາຍຸ",

    "base_adminPassword": "ລະຫັດຜ່ານຂອງຜູ້ດູແລສູງສຸດ",
    "base_adminPassword_infor": "ລະຫັດຜ່ານ xadmin ຜູ້ດູແລສູງສຸດ，",
    "base_adminPassword_action": "ປ່ຽນລະຫັດຜ່ານຜູ້ດູແລສູງສຸດ",
    "base_adminPassword_confirm": "<div style='color:red'>ລະຫັດຜ່ານຜູ້ດູແລສູງລຸດ ແມ່ນກ້ຽວຂ້ອງກັບລະຫັດຜ່ານຖານຂໍ້ມູນ ແລະ ອື່ນໆ，ກະລຸນາລະມັດລະວັງການປ່ຽນລະຫັດຜ່ານຂອງຜູ້ດູແລສູງສຸດ！<br>ຫຼັງຈາກປ່ຽນລະຫັດຜ່ານແລ້ວກະລຸນາເປີດເຂົ້າສູ່ລະບົບໃໝ່，ບໍ່ດັ່ງນັ້ນລະບົບອາດຈະຜິດພາດ！</div><br>ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການປ່ຽນລະຫັດ？",


    "base_loginSetting": "ຕັ້ງຄ່າຕົວເລືອກເຂົ້າສູ່ລະບົບ",


    "base_captchaLogin": "ເປີດໃຊ້ງານເຂົ້າສູ່ລະບົບດ້ວຍລະຫັດໃບໜ້າ",
    "base_captchaLogin_infor": "ຫຼັງຈາກການເປີດໃຊ້ງານຕ້ອງໃສ່ລະຫັດການຢັ້ງຢືນຮູບພາບໃຫ້ຖືກຕ້ອງໃນເວລາທີ່ເຂົ້າສູ່ລະບົບ",
    "base_captchaLogin_action": "",

    "base_codeLogin": "ເປີດໃຊ້ງານເຂົ້າສູ່ລະບົບດ້ວຍ SMS",
    "base_codeLogin_infor": "ຫຼັງຈາກເປີດໃຊ້ງານອະນຸຍາດໃຫ້ໃຊ້ ລະຫັດຜ່ານຢືນຢັນ SMSເຂົ້າສູ່ລະບົບ",
    "base_codeLogin_action": "",

    "base_bindLogin": "ເປີດໃຊ້ງານ ສະແກນ QR ເຂົ້າສູ່ລະບົບ",
    "base_bindLogin_infor": "ຫຼັງຈາກເປີດໃຊ້ງານອະນຸຍາດໃຫ້ໃຊ້  ສະແກນ QR ເຂົ້າສູ່ລະບົບ",

    "base_faceLogin": "ເປີດໃຊ້ງານເຂົ້າສູ່ລະບົບຈົດຈຳໃບໜ້າ",
    "base_faceLogin_infor": "ຫຼັງຈາກເປີດໃຊ້ງານອະນຸຍາດໃຫ້ໃຊ້ລະບົບຈົດຈຳໃບໜ້າເຂົ້າສູ່ລະບົບ ，ຜູ້ໃຊ້ສາມາດຕັ້ງຄ່າໃບໜ້າໃນການຕັ້ງຄ່າສ່ວນບຸກຄົນໄດ້。ຫຼັງຈາກເປີດໃຊ້ງານ ເຈົ້າຕ້ອງກຳນົດຄ່າ SSO，ຊື່ face，ສິ່ງສຳຄັນກໍຄື xplatform（ນີ້ແມ່ນລັກສະນະທົດລອງ，ເຈົ້າຕ້ອງເປີດໃຊ້ງານhttps）",

    "base_faceApi": "ບໍລິການຈົດຈຳໃບໜ້າ",
    "base_faceApi_action": "ແກ້ໄຂບໍລິການຈົດຈຳໃບໜ້າ",
    "base_faceApi_delete": "ລົບການບໍລິກນຈົດຈຳໃບໜ້າ",
    "base_faceApi_infor": "ໃຊ້ face++ບໍລິການໃບໜ້າ，ເຈົ້າສາມາດແກ້ໄຂAPI Key ແລະ API Secret ຂອງເຈົ້າ。ບໍ່ດັ່ງນັ້ນລະບົບຈະໃຊ້ບັນຊີຄ່າເລີ່ມຕົ້ນ，QPSຈະຖືກຈຳກັດ。",

    "base_register": "ເປີດໃຊ້ງານລົງທະບຽນ",
    "base_register_infor": "ອະນຸຍາດການລົງທະບຽນດ້ວຍຕົນເອງໃຊ້ລະບົບ ຫຼື ບໍ່，ແລະວິທີການລົງທະບຽນ",
    "register_disable": "ບໍ່ອະນຸຍາດໃຫ້ລົງທະບຽນດ້ວຍຕົນເອງ",
    "register_captcha": "ອະນຸຍາດໃຫ້ລົງທະບຽນດ້ວຍຕົນເອງໂດຍໃຊ້ຮູບພາບຢືນຢັນ",
    "register_code": "ອະນຸຍາດໃຫ້ລົງທະບຽນດ້ວຍຕົນເອງໂດຍໃຊ້ລະຫັດ SMSຢືນຢັນ",

    "base_portalLogin": "ເຂົ້າສູ່ລະບົບໂດຍໃຊ້  portal",
    "base_portalLogin_infor": "portal ທີ່ກຳນົດເອງສາມາດໃຊ້ເຂົ້າສູລະບົບ，ສາມາດດາວໂຫລດ ໜ້າtemplateເພື່ອເຂົ້າສູ່ລະບົບໄດ້ຈາກ application market。",
    "base_portalLogin_action": "",

    "base_loginPortalId": "ເຂົ້າສູ່ລະບົບ Portal",
    "base_loginPortalId_infor": "ເລືອກເຂົ້າສູ່ລະບົບ Portal。",

    "base_portalIndex": "ໃຊ້ ໜ້າportal ເປັນລະບົບ ໜ້າບ້ານ",
    "base_portalIndex_infor": "portal ທີ່ກຳນົດເອງສາມາດໃຊ້ ເປັນລະບົບ ໜ້າບ້ານ，ເຂົ້າສູ່ລະບົບເພື່ອເປີດໜ້ານີ້。",
    "base_portalIndex_action": "",
    "base_indexPortalId": "ໜ້າຫຼັກຂອງລະບົບ Portal",
    "base_indexPortalId_infor": "ເລືອກ Portalສຳລັບໜ້າທຳອິດຂອງລະບົບ。",

    "base_temary": "ການບໍລິຫານ 3 ຄົນ",
    "base_temary_info": "ການບໍລິຫານ 3 ຄົນ（ເບິ່ງແຍງລະບົບ、ດູແລຄວາມປອດໄພ、ຄົນກວດສອບຄວມປອດໄພ）。ຫຼັງຈາກເປີດໃຊ້ງານນີ້ແລ້ວກະລຸນາປິດແລ້ວເປີດເຊີບເວີຄືນໃໝ່。",
    "base_temary_action": "",

    "base_ldap": "ເປີດໃຊ້ງານ Ldap ຮອງຮັບ",
    "base_ldap_infor": "ຫຼັງຈາກເປີດໃຊ້ງານແລ້ວ，ການກວດສອບການຮອງຮັບເຂົ້າສູ່ລະບົບLdap，ບໍ່ໃ9້ລະຫັດຜ່ານເພື່ອເຂົ້າສູ່ລະບົບນີ້ອີກຕໍ່ໄປ。",
    "base_ldap_action": "ຕັ້ງຄ່າແກ້ໄຂການຮອງຮັບ Ldap",
    "base_ldap_enable": "ເປີດໃຊ້ງານແລ້ວ",
    "base_ldap_unenable": "ບໍ່ໄດ້ເປີດໃຊ້ງານ",


    "base_ssoSetting": " ລະບົບການຮັບຮອງຢືນຢັນຕົວຕົນ ແລະ ການຕັ້ງຄ່າເຂົ້າລະບົບຄັ້ງດຽວກັບລະບົບອື່ນ",
    "base_ssos": "ການຕັ້ງຄ່າການຢືນຢັນຕົວຕົນ",
    "base_sso_infor": "ເຈົ້າສາມາດສ້າງການຢືນຢັນຕົວຕົນຫຼາຍລະບົບໄດ້，ໃຊ້ SSO ເຂົ້າສູ່ລະບົບ ແລະ ຂໍຮ້ອງການບໍລິການ",
    "base_sso_action": "ເພີ່ມການກຳນົດຄ່າການຢືນຢັນຕົວຕົນ",
    "base_sso_editAction": "ແກ້ໄຂການກຳນົດຄ່າການຢືນຢັນຕົວຕົນ",

    "base_oauths": "OAUTHກຳນົດຄ່າລູກຄ້າ",
    "base_oauths_infor": "ຖ້າລະບົບເຊີເວີນີ້ OAUTH2 ໃຊ້ເປັນລະບົບການລະບຸຕົວຕົນ，ເຈົ້າສາມາດກຳນົດຄ່າລູກຄ່າOAUTH ຫຼາຍລາຍການ，ດຳເນີນການອະນຸຍາດສຳລັບລະບົບອື່ນ",
    "base_oauths_action": "ເພີ່ມການກຳນົດຄ່າ oauth",
    "base_oauths_editAction": "ແກ້ໄຂການກຳນົດຄ່າ oauth",

    "base_oauths_server": "OAUTHກຳນົດຄ່າການບໍລິການ",
    "base_oauths_infor_server": "ຖ້າລົບບົບນີ້ຈຳເປັນຕ້ອງລະບຸຕົວຕົນຂອງເຊີບເວີ OAUTH2 ອື່ນ，ເຈົ້າສາມາດກຳນົດຄ່າບໍລິການOAUTHຫຼາຍລາຍການ，ອະນຸຍາດລະບົບນີ້",


    "base_qyweixin": "ການກຳນົດຄ່າ  Enterprise WeChat",
    "base_qyweixin_infor": "ລະບົບສາມາດຮ່ວມເຂົ້າກັບ Enterprise WeChat，ກະລຸນາກຳນົດບັນຊີ Enterprise WeChat ກັບລະຫັດຜ່ານກ່ອນ",
    "base_qyweixin_action": "ແກ້ໄຂການກຳນົດຄ່າ  Enterprise WeChat",

    "base_dingding": "ການກຳນົດຄ່າ DingTalk ",
    "base_dingding_infor": "ລະບົບສາມາດປະສົມປະສານກັບ DingTalk，ກະລຸນາກຳນົດຄ່າ DingTalk ແລະ ລະຫັດຜ່ານກ່ອນ",
    "base_dingding_action": "ຕັ້ງຄ່າການກຳນົດຄ່າ DingTalk ",


    "mobile_connectSetting": "ຕັ້ງຄ່າການເຊື່ອມຕໍ່ກັບໂທລະສັບ",
    "cloud_connectSetting": "ຕັ້ງຄ່າການເຊື່ອມຕໍ່ Cloud",
    "mobile_connect_first_cloud_check": "1. ການກວດສອບເຊື່ອມຕໍ່ Cloud",
    "mobile_connect_first_cloud_check_connected": "<span style='color: #5fbf78'> [ເຊື່ອມຕໍ່ເຂົ້າສູ່ລະບົບແລ້ວ] </span>ບໍລິການ Cloud",
    "mobile_connect_first_cloud_check_disconnected": "<span style='color: #ff0000'> [ເຊື່ອມຕໍ່ເຂົ້າສູ່ລະບົບແລ້ວ] </span>ບໍລິການ Cloud，ກະລຸນາໄປທີ່ການຕັ້ງຄ່າການເຊື່ອມຕໍ່ໜ້າ Cloudເພື່ອລົງທະບຽນ ແລະ ເຂົ້າສູ່ລະບົບ！",
    "mobile_connect_connectSetting": "2. ຕັ້ງຄ່າການເຊື່ອມຕໍ່ App ",
    "mobile_connect_third_mobile_connect_check": "3. ທົດລອງການເຊື່ອມຕໍ່ໂທລະສັັບ",
    "mobile_connect_third_mobile_connect_check_info": "ໃຊ້ໂທລະສັບຂອງເຈົ້າສະແກນ QR，ກວດສອບເຄື່ອຂ່າຍນອກສາມາດເຊື່ອມຕໍ່ກັບເຊີບເວີໄດ້ຫຼືບໍ່！",
    "mobile_connect_third_mobile_connect_check_generate_button": "ສ້າງ QR code",

    "mobile_connectO2Cloud": "ເຊື່ອມຕໍ່ທີ່ O2 Cloud",
    "mobile_connectO2Cloud_infor": "ຈະໃຊ້ໂທລະສັບຂອງບໍລິສັດກະລຸນາເຊື່ອມຕໍ່ໄປທີ່O2Cloud，ສິ່ງນີ້ຈະຊ່ວຍສະຖານທີ່ APP ຂອງເຊີບເວີຂອງເຈົ້າໄດ້，ສາມາດໃຊ້ບໍລິການ SMS ອື່ນໆໄດ້",
    "mobile_connectO2Cloud_action": "ເຊື່ອມຕໍ່ທີ່ O2Cloud",
    "mobile_connectO2Cloud_success": "ຕັ້ງຄ່າການເຊື່ອມຕໍ່",
    "mobile_connectO2Cloud_error": "ຍັງບໍ່ໄດ້ເຊື່ອມຕໍ່ຫາ O2Cloud",

    "mobile_httpProtocol": "http protocol",
    "mobile_httpProtocol_infor": "ກະລຸນາເລືອກໃຊ້http protocol ຫຼື https protocol",

    "mobile_center": "ສູນກາງ Server",
    "mobile_center_infor": "ໃຊ້ທີ່ຢູ່ IP ຫຼື ຊື່domain ແລະ port ຂອງການບໍລິການພາຍນອກຂອງສູນກາງ Server。（ໃຊ້ ທີ່ຢູ່ IP ເທົ່ານັ້ນທີ່ສາມາດໃຊ້ສຳລັບ http protocol）",
    "mobile_center_action": "ແກ້ໄຂສູນກາງ Server",

    "mobile_web": "WEB Server",
    "mobile_web_infor": "ໃຊ້ທີ່ຢູ່ IP ຫຼື ຊື່domain ແລະ port ຂອງການບໍລິການພາຍນອກຂອງWEB Server，ຖ້າຊື່ domain ຫຼື  ທີ່ຢູ່ IPວ່າງເປົ່າຫຼື”127.0.0.1“ຈາກນັ້ນໃຊ້ ທີ່ຢູ່Center Server。（ໃຊ້ ທີ່ຢູ່ IP ເທົ່ານັ້ນທີ່ສາມາດໃຊ້ສຳລັບ http protocol）",
    "mobile_web_action": "ແກ້ໄຂ WEB Server",

    "mobile_application": "application Server",
    "mobile_application_infor": "ໃຊ້ທີ່ຢູ່ IP ຫຼື ຊື່domain ແລະ port ຂອງການບໍລິການພາຍນອກຂອງapplication Server，ຖ້າຊື່ domain ຫຼື  ທີ່ຢູ່ IPວ່າງເປົ່າຫຼື”127.0.0.1“ຈາກນັ້ນໃຊ້ ທີ່ຢູ່Center Server。（ໃຊ້ ທີ່ຢູ່ IP ເທົ່ານັ້ນທີ່ສາມາດໃຊ້ສຳລັບ http protocol）",
    "mobile_application_action": "ແກ້ໄຂ application Server",

    "mobile_moduleSetting": "ການກຳນົດຄ່າ module ມືຖື ",
    "mobile_index": "ການກຳນົດຄ່າໜ້າຫຼັກຂອງມືຖື",
    "mobile_index_infor": "ເຈົ້າສາມາດກຳນົດຄ່າຫຼ້າຫຼັກຂອງມືຖືໄດ້ທີ່ຮູບແບບ APP ，ຫຼືລະບຸໜ້າ portal",
    "mobile_index_defalue": "defalue",

    "mobile_module": "{name}Module",
    "mobile_module_infor": "ການເປີດໃຊ້ງານເທິງມືຖື{name}module",

    "mobile_module_simple_mode": "ໂມດທຳມະດາເທິງມືຖື",
    "mobile_module_simple_mode_infor": "ມີພຽງໜ້າຫຼັກ ແລະ ການຕັ້ງຄ່າເທົ່ານັັ້ນທີ່ຈະສະແດງຫຼັກຈາກເປີດໃຊ້ງານໂມດທຳມະດາ",

    "mobile_module_system_message_switch": "ການແຈ້ງເຕືອນຂອງລະບົບ",
    "mobile_module_system_message_switch_infor": "ຕ້ອງການການແຈ້ງເຕືອນຂອງລະບົບສົ່ງລາຍງານຂໍ້ຄວາມໃນມືຖື",

    "mobile_module_contact_permission_view": "Mobile app address book permission view",
    "mobile_module_contact_permission_view_infor": "ເຈົ້າຕ້ອງການຕິດຕັ້ງapplication market  【address book】application，ການຕັ້ງຄ່າ ການອະນຸຍາດ view ຂອງ address bookລວມຢູ່ໃນapplication ",
    "mobile_module_contact_permission_view_action": "ແກ້ໄຂ view name",

    "mobile_styleSetting": "ກາານຕັ້ງຄ່າຮູບແບບ icon ມືຖື ",
    "mobile_style": "{name}ຮູບພາບ ",
    "mobile_style_infor": "ກົດປ່ຽນ {name}ຮູບພາບ",
    "mobile_style_imgs": {
        "launch_logo": "ເລີ່ມຕົ້ນ Logo",
        "login_avatar": "Default avatar for login page",
        "application_top": "ຮູບທີ່ໜ້າ Application",
        "index_bottom_menu_logo_blur": "icon ນຳທາງບ້ານ（ບໍ່ໄດ້ເລືອກ）",
        "index_bottom_menu_logo_focus": "icon ນຳທາງບ້ານ（ເລືອກ）",
        "people_avatar_default": "avatar ຜູ້ໃຊ້ ",
        "process_default": "ຂະບວນການຂອງ icon ",
        "setup_about_logo": "ກ່ຽວກັບໜ້າຂອງ icon "
    },
    "mobile_style_imgs_defaultTitle": "ຢືນຢັນຕົວຕົນດ້ວຍຮູບ",
    "mobile_style_imgs_defaultInfor": "ເຈົ້າແນ່ໃຈວ່າຕ້ອງການ{name}，ຢືນຢັນຕົວຕົນດ້ວຍຮູບ？",

    "mpweixin": "MpWechat",
    "publishMpweixin": "Publish to Wechat",
    "subscribeMpweixin": "ຕິດຕາມການຕອບກັບ",
    "subscribeMpweixin_desc": "ເມື່ອມີຜູ້ໃຊ້ໃໝ່ກະລຸນາຕິດຕາມ official account ，ເນື້ອໃນຂໍ້ຄວາວມທີ່ສົ່ງໂດຍອັດຕະໂນມັດ",
    "subscribeMpweixin_save": "ບັນທຶກ",
    "mpweixinInfo": "⚠️ WeChat official account ເມນູ function ຈຳເປັນຕ້ອງເປີດໃຊ້ງານຟາຍທີ່ກຳນົດຄ່າທີ່ກ່ຽວຂ້ອງກ່ອນ[mpweixin.json]，ໄປທີ່ກນຈັດການຂອງ WeChat official account，ເປີດໃຊ້ການການຕັ້ງຄ່າຂອງເຊີບເວີ！",
    "mobile_mpweixin_menu_msg_publish_2_wxmp": "ໝາຍເຫດ！ການດຳເນີນການປະຈຸບັນຈະແທນທີ່ຂໍ້ມູນທີ່ບັນທຶກໄວ້ທັງໝົດໄປທີ່ WeChat official account，ຕ້ອງການສືບຕໍ່ບໍ？",
    "mobile_mpweixin_menu_msg_publish_success": "ເຜີຍແຜ່ສຳເລັດ，ຈະສະແດງພ້ອມກັນໃນໂທລະສັບມືຖືຫຼັງຈາກຜ່ານໄປ 24 ຊົ່ວໂມງ！",
    "mobile_mpweixin_menu_msg_first_max_len": "ລະດັບແລກສາມາດສ້າງໄດສູງສຸດ 3 ເມນູເທົ່ານັ້ນ！",
    "mobile_mpweixin_menu_msg_sub_max_len": "ລະດັບ2ສາມາດສ້າງໄດສູງສຸດ 5 ເມນູເທົ່ານັ້ນ！",
    "mobile_mpweixin_menu_msg_parent_no_save": "ຂໍ້ມູນກ່ອນໜ້ານີ້ຈະບໍ່ຖືກບັນທຶກ，ກະລຸນາເລືອກບັນທຶກຂໍ້ມູນກ່ອນ！",
    "mobile_mpweixin_menu_deleteBtnName_label": "ລົບເມນູ",
    "mobile_mpweixin_menu_default_new_name": "ເມນູໃໝ່",
    "mobile_mpweixin_menu_form_name_label": "ຊື່ເມນູ",
    "mobile_mpweixin_menu_form_name_error_empty": "ຊື່ເມນູບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "mobile_mpweixin_menu_form_name_error_max_len_4": "ຊື່ເມນູຕ້ອງມີຄວາມຍາວບໍ່ເກີນ 4 ຄຳ！",
    "mobile_mpweixin_menu_form_name_error_max_len_6": "ຊື່ເມນູຕ້ອງມີຄວາມຍາວບໍ່ເກີນ 6 ຄຳ！",
    "mobile_mpweixin_menu_form_name_error": "ຈຳນວນຄຳສູງກວ່າຂີດຈຳກັດ",
    "mobile_mpweixin_menu_form_name_tips_4": "ຮອງຮັບສະເພາະພາສາຈີນ,ອັງກິດ ແລະ ຕົວເລກເທົ່ານັ່ນ，ຄວາມຍາວບໍ່ໃຫ້ເກີນ 4 ຄຳ",
    "mobile_mpweixin_menu_form_name_tips_6": "ຮອງຮັບສະເພາະພາສາຈີນ,ອັງກິດ ແລະ ຕົວເລກເທົ່ານັ່ນ，ຄວາມຍາວບໍ່ໃຫ້ເກີນ 6 ຄຳ",
    "mobile_mpweixin_menu_form_order_label": "ເລກລຳດັບເມນູ",
    "mobile_mpweixin_menu_form_order_error_empty": "ເລກລຳດັບເມນູບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "mobile_mpweixin_menu_form_order_error_not_number": "ເລກລຳດັບສາມາດປ້ອນໃສ່ສະເພາະຕົວເລກເທົ່ານັ້ນ！",
    "mobile_mpweixin_menu_form_order_error_max_len": "ເລກລຳດັບເມນູຄວາມຍາວບໍ່ໃຫ້ເກີນ 6 ຄຳ！",
    "mobile_mpweixin_menu_form_order_error": "ຈຳນວນຄຳສູງກວ່າຂີດຈຳກັດ",
    "mobile_mpweixin_menu_form_order_tips": "ຮອງຮັບສະເພາະຕົວເລກເທົ່ານັ້ນ，ຄວາມຍາວບໍ່ໃຫ້ເກີນ 6 ຄຳ，ຈັດລຽນດ້ວຍstring",
    "mobile_mpweixin_menu_form_radio_label": "ເນື້ອໃນເມນູ",
    "mobile_mpweixin_menu_form_radio_type_msg": "ເຜີຍແຜ່ຂໍ້ມູນ",
    "mobile_mpweixin_menu_form_radio_type_url": "ຂ້າມໄປທີ່ໜ້າເວັບ",
    "mobile_mpweixin_menu_form_radio_type_miniprogram": "ເວັບ Mini Program",
    "mobile_mpweixin_menu_form_type_msg_tips": "ຄິກໃສ່ເມນູນີ້ຈະສົ່ງຂໍ້ຄວາມຕໍ່ໄປນີ້ໄປຫາຊື່ຜູ້ໃຊ້，ບັນຊີສະມັກສະມາຊິກບໍ່ຜ່ານການຮັບຮອງການສົ່ງຂໍ້ຄວາມ",
    "mobile_mpweixin_menu_form_type_msg_label": "ຂໍ້ຄວາມ",
    "mobile_mpweixin_menu_form_type_msg_error_empty": "ເນື້ອໃນຂໍ້ຄວາມບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "mobile_mpweixin_menu_form_subscribe_content_error_empty": "ການຕອບກັບຂໍ້ຄວາມບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "mobile_mpweixin_menu_form_type_url_tips": "ຄິກໃສ່ເມນູນີ້ຈະໄປທີ່ການຕິດຕາມ ລິ້ງ",
    "mobile_mpweixin_menu_form_type_url_label": "ທີ່ຢູ່",
    "mobile_mpweixin_menu_form_type_url_error_empty": "ທີ່ຢູ່ຂອງ page ບໍ່ສາມາດເວັ້ນວ່າງໄດ້！",
    "mobile_mpweixin_menu_form_type_miniprogram_tips": "ຄິກໃສ່ເມນູນີ້ຈະໄປເວັບ Mini Program",
    "mobile_mpweixin_menu_form_type_miniprogram_appid_label": "Program ID",
    "mobile_mpweixin_menu_form_type_miniprogram_appid_placeholder": "Mini program ID，ກະລຸນາໄປທີ່ WeChat’s mini programພື້ນຫຼັງການບໍລິຫານເພື່ອກວດ",
    "mobile_mpweixin_menu_form_type_miniprogram_appid_error_empty": "Program IDບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_mpweixin_menu_form_type_miniprogram_path_label": "Program Path",
    "mobile_mpweixin_menu_form_type_miniprogram_path_placeholder": "The path of the mini program，ກະລຸນາກວດເບິ່ງພື້ນຫຼັງການບໍລິຫານ mini program ຂອງ WeChat",
    "mobile_mpweixin_menu_form_type_miniprogram_path_error_empty": "Mini program pathບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_mpweixin_menu_form_type_miniprogram_url_label": "ໜ້າເວັບສຳຮອງ",
    "mobile_mpweixin_menu_form_type_miniprogram_url_placeholder": "ໜ້າເວັບສຳຮອງ，ເວີຊັ່ນເກົ່າຂອງ WeChat ຈະເປີດໜ້າເວັບສຳຮອງນີ້",
    "mobile_mpweixin_menu_form_type_miniprogram_url_error_empty": "ໜ້າເວັບສຳຮອງບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_mpweixin_menu_save_success": "ບັນທຶກຂໍ້ມູນສຳເລັດ！",
    "mobile_mpweixin_menu_delete_alert_msg": "ຢືນຢັນຕຕ້ອງການລົບຂໍ້ມູນນີ້ບໍ，ຕ້ອງການລົບເມນູຍ່ອຍຂອງມັນນຳບໍ？",
    "mobile_mpweixin_menu_delete_success": "ລົບຂໍ້ມູນສຳເລັດ！",


    "save": "ບັນທຶກ",
    "alert": "Alert",

    "mobile_apppack_tips1": "⚠️ ປະຈຸບັນມັນ App ໃນມືຖື ສາມາດຮັບຮອງສະເພາະລະບົບ Android ເທົ່ານັ້ນ。",
    "mobile_apppack_tips2": "⚠️ ຖ້າເຈົ້າຕ້ອງການpackage online，ຕ້ອງໄປທີ່ [ການຕັ້ງຄ່າ Cloud]ເພື່ອລົງທະບຽນກ່ອນ、log inເຂົ້າສູ່ລະບົບ。",
    "mobile_apppack_tips3": "⚠️ ຫຼຫງຈາກສົ່ງຂໍ້ມູນ，ສະຖານະ packing ປະຈຸບັນຈະສະແດງຂຶ້ນ，ຂະບວນການ packing ຈະໃຊ້ເວລາດົນ ，ເຈົ້າສາມາດອອກຈາກໜ້າເວັບປະຈຸບັນນີ້ໄດ້，ລໍຖ້າpacking ສຳເລັດແລ້ວດາວAPKໂລດຟາຍໃນໜ້ານີ້。",
    "mobile_apppack_status_label": "ສະຖານະປະຈຸບັນ",
    "mobile_apppack_form_appName": "Appຊື່",
    "mobile_apppack_form_appName_tip": "ຊື່ສະແດງເທິງ Desktop ຂອງ app，ຄວາມຍາວບໍ່ໃຫ້ເກີນ 6 ຄຳ",
    "mobile_apppack_form_logo": "Logoຮູບ",
    "mobile_apppack_form_logo_tip": "ຮູບ Logo ສະແດງເທິງ Desktop ຂອງ app，ຕ້ອງເປັນ png ເທົ່ານັ້ນ",
    "mobile_apppack_form_protocol": "HTTP protocol",
    "mobile_apppack_form_protocol_tip": "http / https",
    "mobile_apppack_form_host": "ຊື່ domain",
    "mobile_apppack_form_host_tip": "ຊື່ Central server domain ຫຼື IP，ເຊັ່ນ www.o2oa.net",
    "mobile_apppack_form_port": "ເລກ Port ",
    "mobile_apppack_form_port_tip": "Port number of central server，ເຊັ່ນ 20030",
    "mobile_apppack_form_context": "Context",
    "mobile_apppack_form_context_tip": "Central server context，ເຊັ່ນ/x_program_center",
    "mobile_apppack_form_urlMapping": "ການສະແດງurlMapping",
    "mobile_apppack_form_urlMapping_tip": "ໃຊ້ມັນເມື່ອທີ່ຢູ່ proxy ໃຊ້ເຄື່ອຂ່າຍ server ພາຍນອກ，ເຊັ່ນ{ \"demo.o2oa.net:20020\": \"demo.o2oa.net/dev/app\" }",
    "mobile_apppack_form_appVersionName": "ຊື່ app Version",
    "mobile_apppack_form_appVersionName_tip": "ຊື່ app Version，ເຊັ່ນ v1.0.0。ສິ່ງນີ້ບໍ່ຈຳເປັນຕ້ອງຕື່ມຄ່າໃສ່！",
    "mobile_apppack_form_appBuildNo": "app Build number",
    "mobile_apppack_form_appBuildNo_tip": "app Build number，ຕ້ອງເປັນຈຳນວນເຕັມບວກ， ເຊັນ 100。ສິ່ງນີ້ບໍ່ຈຳເປັນຕ້ອງຕື່ມຄ່າໃສ່！",
    "mobile_apppack_form_button": "ສົ່ງ ແລະ ເລີ່ມpackaging ",
    "mobile_apppack_form_reinput_button": "ຕື່ມຂໍ້ມູນໃສ່ແບບຟອມ",
    "mobile_apppack_form_re_pack_button": "ໃຊ້ຂໍ້ມູນຕົ້ນສະບັບເພື່ອເຂົ້າ",
    "mobile_apppack_form_download_apk_button": "ດາວໂລດເອກະສານ APK",
    "mobile_apppack_message_o2cloud_not_enable": "O2Cloud ບໍ່ໄດ້ເປີດໃຊ້ການ ຫຼື ບໍ່ສາມາດເຊື່ອມຕໍ່ໄດ້！",
    "mobile_apppack_message_o2cloud_not_login": "ເລືອກເຂົ້າສູ່ລະບົບໜ້າ O2Cloud！",
    "mobile_apppack_message_apppack_server_login_fail": "App packaging service ເຂົ້າສູ່ລະບົບລົ້ມເລວ！",
    "mobile_apppack_message_check_connect_fail": "App packaging service ກວດສອບການເຊື່ອມຕໍ່ລົ້ມເລວ！",

    "mobile_apppack_form_enable_outer_status_no": "ບໍ່ໄດ້ເປີດໃຊ້ງານ",
    "mobile_apppack_form_enable_outer_status_yes": "ເປີດໃຊ້ງານແລ້ວ",
    "mobile_apppack_form_enable_outer_package": "ເປີດໃຊ້ງານ ຊື່ external package",
    "mobile_apppack_form_enable_delete_hms": "ຕ້ອງການລົບ HMS ຫຼືບໍ",
    "mobile_apppack_form_enable_outer_tips": "ການເປີດໃຊ້ຊື່ແພັກເກັດພາຍນອກສາມາດປ້ອງກັນການຂັດແຍ້ງກັບ APP ທີ່ປ່ອຍອອກມາຢ່າງເປັນທາງການ",
    "mobile_apppack_form_enable_delete_hms_tips": "ລົບ HMS ບໍ່ສາມາດໃຊ້ Huawei push ໄດ້，ກະລຸນາດຳເນີນການຢ່າງລະມັດລະວັງ",
    "mobile_apppack_form_enable_delete_hms_status_no": "ບໍ່",
    "mobile_apppack_form_enable_delete_hms_status_yes": "ແມ່ນ",
    "mobile_apppack_form_download_publish_btn": "ດາວໂລດ ແລະເຜີຍແຜ່ໄປທີ່ທີ່ຢູ່",
    "mobile_apppack_message_confirm_publish": "app ສຳເລັດແລ້ວ，ທັນທີທີ່ດາວໂຫລດ ແລະ ເຜີຍແຜ່ໄປຍັງເຊີບເວີພາຍໃນເຄື່ອງທັນທີ່ ກໍສາມາດສະແກນ QR ເພື່ອຕິດຕັ້ງໄດ້ໂດຍຕົງ！",
    "mobile_apppack_publish_status_doing": "ເຜີຍແຜ່...",
    "mobile_apppack_publish_status_completed": "ເຜີຍແຜ່ສຳເລັດ，ສະແກນ QRເພື່ອຕັ້ງລະບົບ APP！",
    "mobile_apppack_publish_status_fail": "ເຜີຍແຜ່ລົ້ມເລວ，ກະລຸນາລອງໃໝ່ ຫຼືຕິດຕໍ່ພະນະການບໍລິກາານ！",

    "mobile_apppack_status_order_inline": "In line......",
    "mobile_apppack_status_packing": "Packing......",
    "mobile_apppack_status_pack_end": "Package ສຳເລັດ",
    "mobile_apppack_status_pack_error": "Package ຜິດພາດ",
    "mobile_apppack_message_appname_not_empty": "ຊື່ App ບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_apppack_message_appname_len_max_6": "ຊື່App ຄວາມຍາວບໍ່ໃຫ້ເກີນ 6 ຄຳ！",
    "mobile_apppack_message_app_logo_not_empty": "ຮູບ Logo ບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_apppack_message_app_logo_need_png": "ຮູບ Logo ຕ້ອງເປັນຮູບແບບ png！",
    "mobile_apppack_message_portocol_not_empty": "HTTP protocol ບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_apppack_message_host_not_empty": "ຊື່ Central server domain ບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_apppack_message_host_format_error": "ກະລຸນນາປ້ອນຊື່ Central server domain ຫຼື IP，ເຊັ່ນwww.o2oa.net，ບໍ່ໃຫ້ໃສ່ http ແບບນີ້！",
    "mobile_apppack_message_port_not_empty": "ເລກ Central server portບໍ່ສາມາດວ່າງໄດ້ ！",
    "mobile_apppack_message_context_not_empty": "Central server context ບໍ່ສາມາດວ່າງໄດ້！",
    "mobile_apppack_message_portocol_http_https": "HTTP protocol ສາມາດເປັນ http ຫຼື https ເທົ່ານັ້ນ ！",
    "mobile_apppack_refresh_status_btn": "Refresh Status",
    "mobile_apppack_message_alert_submit": "ເຈົ້າແນ່ໃຈວ່າຕ້ອງກາານສົ່ງ，ຂໍ້ມູນຟອມປະຈຸບັນຈະເປັນ packaged ເທິ່ງ mobile App ？",
    "imgSize": "ຂະໜາດຮູບ：",
    "defaultImg": "ຮູບ Default",

    "ui_loginSetting": "ເຂົ້າສູ່ລະບົບຮູບແບບກາານຕັ້ງຄ່າ",
    "ui_login_default": "ຮູບແບບ Default",
    "ui_login_defaultStyle": "ເຂົ້າສູ່ລະບົບກາານຕັ້ງຄ່າຮູບແບບDefault",
    "ui_login_defaultStyle_infor": "",
    "ui_login_customStyle": "ເຂົ້າສູ່ລະບົບຮູບແບບ custom ",
    "ui_login_customStyle_infor": "",
    "ui_login_customStyle_Action": "ສ້າງຮູບແບບ custom",
    "ui_login_customStyle_newName": "ຊື່ຮູບແບບໃໝ່",
    "ui_login_customStyle_newName_empty": "ກະລຸນາປ້ອນຊື່ຂອງຮູບແບບໃໝ່",
    "ui_login_setCurrent": "ໃຊ້ຮູບແບບນີ້",
    "ui_login_current": "ໃຊ້ຮູບແບບປະຈຸບັນ",
    "ui_login_setCurrent_confirmTitle": "ຢືນຢັນໃຊ້ຮູບແບບນີ້",
    "ui_login_setCurrent_confirm": "ເຈົ້າແນ່ໃຈວ່າຕ້ອງການໃຊ້ “{title}” ນີ້ບໍ？",

    "ui_login_delete_confirmTitle": "ຢືນຢັນລົບຮູບແບບນີ້",
    "ui_login_delete_confirm": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບ “{title}” ນີ້？",

    "ui_indexSetting": "ຕັ້ງຄ່າຮູບແບບ Platform ",
    "ui_index_systemStyle": "ຮູບແບບທີ່ສ້າງຂຶ້ນໃນ Platform",
    "ui_index_systemStyle_infor": "",

    "ui_index_customStyle": "ການຕັ້ງຄ່າ ຮູບແບບ Custom",
    "ui_index_customStyle_infor": "",
    "ui_index_customStyle_Action": "",
    "ui_index_enabled": "ເປີດໃຊ້ງານແລ້ວ",
    "ui_index_disabled": "ປິດໃຊ້ງານແລ້ວ",

    "ui_moduleSetting": "ຕັ້ງຄ່າລະບົບ Module ",
    "ui_module_modules": "Module ທີ່ປັບໃຊ້",
    "ui_module_modules_infor": "",
    "ui_module_modules_Action": "Module ທີ່ປັບໃຊ້",

    "ui_moduleSetting_resource": "ປັບໃຊ້ອຸປະກອນໃນweb",
    "ui_moduleSetting_service": "ປັບໃຊ້ບໍລິການ",

    "resource_upload":"ເລືອກວິທີການ",
    "resource_replace":"ປັບໃຊ້ຫຼືບໍ",
    "resource_replaceDesc":"ປະເພດກນປັບໃຊ້：‘ບໍ່’ລົບເອກະສນຕົ້ນສະບັບຫຼັງຈາກນັ້ອັບໂຫຼດ，‘ແມ່ນ’ປັບໃຊ້ເອກະສານຕົ້ນສະບັບ",
    "resource_replace_yes":"ແມ່ນ",
    "resource_replace_no":"ບໍ່",
    "resource_filePath":"ບັນທຶກການເກັບຮັກສາ",
    "resource_filePathDesc":"zipເອກະສານສາມາດວ່າງເປົ່າ，ເອກະສານອື່ນບໍ່ສາມາດເປົ່າວ່າງໄດ້path:/xxx/xxx",
    "resource_success":"ການປັບໃຊ້ສຳເລັດ",

    "service_ctl":"ຊື່ຄໍາສັ່ງ",
    "service_node":"ບໍລິການ Node",
    "service_allNode":"Node ທັງໝົດ",
    "service_success":"ນຳໃຊ້ສຳເລັດ,ມັນຈະມີຜົນຫຼັງຈາກເປີດຄືນໃໝ່.",

    "on": "ເປີດ",
    "off": "ປິດ",

    "loading": "ກຳລັງເພີ່ມຮູບແບບ，ກະລຸນາລໍຖ້າ……",
    "returnBack": "ຍ້ອນກັບ",

    "ok": "ຢືນຢັນ",
    "cancel": "ຍົກເລີກ",
    "edit": "ແກ້ໄຂ",
    "delete": "ລົບ",
    "copy": "ສຳເນົາ",
    "copyName": "ສຳເນົາ",

    "deleteItem": "ຢືນຢັນລົບການຕັ້ງຄ່າ",
    "deleteItemInfor": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບການຕັ້ງຄ່ານີ້?？",

    "setSaved": "ບັນທຶກຂໍ້ມູນການຕັ້ງຄ່າແລ້ວ",

    "pleaseInput": "ກະລຸນາໃສ່",
    "list": {
        "client": "ຊື່ລູກຄ້າ",
        "key": "key(ຢ່າງໜ້ອຍ 8 ຕົວ)",
        "clientId": "IDລູກຄ້າ (ClientId)",
        "mapping": "ແຜນທີ່ (Mapping)",
        "corpId": "corpId",
        "corpSecret": "corpSecret",
        "agentId": "agentId",
        "proxyHost": "ທີ່ຢູ່ IP",
        "proxyPort": "port",
        "node": "application server",

        "enable": "ເປີດໃຊ້ງານ",
        "name": "ຊື່",
        "icon": "icon",
        "clientSecret": "ຄວາມລັບລູກຄ້າ",
        "authAddress": "auth Address ",
        "authParameter": "auth Parameter",
        "authMethod": "ຮ້ອງຂໍວິທີ（GET ຫຼືPOST）",
        "tokenAddress": "ຮ້ອງຂໍ URL token",
        "tokenParameter": "ຮ້ອງຂໍຕົວກໍານົດວິທີການ token",
        "tokenMethod": "ຮ້ອງຂໍວິທີການ token（GET ຫຼືPOST）",
        "tokenType": "token ຮູບແບບຂໍ້ຄວາມ（json ຫຼືform）",
        "infoAddress": "ຮ້ອງຂໍຂໍ້ມູນ URL",
        "infoParameter": "ຮ້ອງຂໍຕົວກໍານົດວິທີການຂໍ້ມູນ",
        "infoMethod": "ວິທີການຮ້ອງຂໍຂໍ້ມູນ（GETຫຼືPOST）",
        "infoType": "infoຮູບແບບຂໍ້ຄວາມ（jsonຫຼືform）",
        "infoCredentialField": "infoຊ່ອງຂໍ້ຄວາມທີ່ໃຊ້ລະບຸ IDບຸກຄົນ ",

        "infoProxyHost" : "ບໍ່ຈຳເປັນຕ້ອງໃຊ້ຮູບແບບ http",

        "ldapUrl": "ldapUrl(ທີ່ຢູ່ LDAP,ເຊັ່ນ ldap://111.111.111.111:5389/)",
        "baseDn": "baseDn(LDAPຊື່ຂອງແບບສອບຖາມ,ເຊັ່ນ：dc=zone,DC=COM)",
        "userDn": "userDn(ຢືນຢັນ DN ຂອງຜູ້ໃຊ້,ເຊັ່ນ：uid=*,ou=users,dc=zone,DC=COM，ໃນuid=*ທາງໃນ*IDສະເພາະຂອງຕາຕະລາງຜູ້ໃຊ້，ລະຫັດສະເພາະນີ້ກົງກັບລະຫັດສະເພາະຂອງຜູ້ໃຊ້ O2)"
    },

    "module": {
        "title": "ການນໍາໃຊ້ແອັບພິເຄຊັ່ນ",
        "open": "ເປີດ",
        "edit": "ແກ້ໄຂ",
        "remove": "ຍ້າຍອອກ",
        "add": "ນຳໃຊ້ອົງປະກອບ",

        "name": "ຊື່ອົງປະກອບ",
        "componentTitle": "ຫົວຂໍ້ອົງປະກອບ",
        "path": "ເສັ້ນທາງອົງປະກອບ",
        "icon": "icon",
        "isVisible": "ສາມາດຫຼືບໍ່",
        "yes": "ແມ່ນ",
        "no": "ບໍ່",
        "widgetName": "ຊື່ widget",
        "widgetTitle": "ຊື່ widget",
        "widgetStart": "widgetອັດຕະໂນມັດ",
        "widgetVisible": "widgetສາມາດຫຼືບໍ່",

        "allowList": "ລາຍການທີ່ສາມາດເຂົ້າເຖິງໄດ້",
        "denyList": "ປະຕິເສດການເຂົ້າເຖິງລາຍຊື່",
        "controllerList": "ການຈັດການ",
        "selPerson": "ເລືອກພະນັກງານ",
        "selIcon": "ເລືອກ Icon",
        "urlInfor": "ເຈົ້າສາມາດຜ່ານ“@url:”ເພີ່ມເສັ້ນທາງເປັນ URL ຂອງຫນ້າເວັບ，ເຊັ່ນ“@url:http://www.bing.com”",

        "phone": "ໂທລະສັບ",
        "mail": "ເມວ",

        "noInputInfor": "ກະລຸນາຕື່ມຂໍ້ມູນໃຫ້ຄົບຖ້ວນ。（ຕ້ອງຂຽນ：ຊື່ອົງປະກອບ、ຫົວຂໍ້ອົງປະກອບ、ເສັ້ນທາງອົງປະກອບ）",
        "deploySuccess": "ການນຳໃຊ້ສຳເລັດແລ້ວ",
        "modifySuccess": "ການແກ້ໄຂຂໍ້ມູນອົງປະກອບສໍາເລັດ",

        "removeComponentTitle": "ຍ້າຍການຕິດຕັ້ງອອກສຳເລັດ",
        "removeComponent": "ເຈົ້າແນ່ໃຈຍ້າຍອົງປະກອບອອກ：{name}ບໍ່？",
        "removeComponentOk": "ຍ້າຍອົງປະກອບອອກສຳເລັດ",

        "modify": "ແກ້ໄຂຂໍ້ມູນອົງປະກອບ",

        "moduleDeployed" : "ອົງປະກອບທີ່ນຳໃຊ້ແລ້ວ",
        "inputAppNameNotice" : "ກະລຸນາໃສ່ຊື່ແອັບ ແລະຫົວຂໍ້ແອັບຂອງທ່ານ",
        "uploadZipFileNotice": "ກະລຸນາອັບໂຫຼດ ZIPເອກະສານ"
    },






    "tab_centerServer": "Server Center ",
    "tab_Server": "ການຕັ້ງຄ່າService Host",
    "tab_Application": "ການຕັ້ງຄ່າຂໍ້ມູນແອັບພິເຄຊັນ",
    "tab_Resource": "ການຕັ້ງຄ່າResource Parameter",
    "tab_Mobile": "ການຕັ້ງຄ່າ IDຫ້ອງການ",

    "tab_ApplicationServer": "Application Server",
    "tab_DataServer": "ຂໍ້ມູນ Server",
    "tab_StorageServer": "ຄວາມຈຳ Server",
    "tab_WebServer": "Web Server",

    "deploy": "ນຳໃຊ້ແອັບພິເຄຊັນ",
    "deleteAppServer_title": "ລຶບການຢືນຢັນການຕັ້ງຄ່າເຊີບເວີ",
    "deleteAppServer": "ທ່ານກຳລັງຈະລຶບເອກະສານການກຳນົດຄ່າ application serverອອກ，ການລຶບເອກະສານນີ້ຈະບໍ່ສົ່ງຜົນກະທົບຕໍ່ການເຮັດວຽກຂອງເຊີບເວີ，ຕ້ອງການສືບຕໍ່ບໍ？",
    "deployAppServer_title": "ການຢືນຢັນການໃຊ້ງານ",
    "deployAppServer": "ນຳໃຊ້ແອັບພິເຄຊັນໄປຍັງເຊີບເວີປະຈຸບັນ，ຢືນຢັນຫຼືບໍ່？<br><br><div style='color: #F00'><input type='checkbox'>ກຳນົດຄ່າແອັບພິເຄຊັນໃໝ່ທັງໝົດ</div>",

    "deleteDataServer_title": "ເອົາການຢືນຢັນການຕັ້ງຄ່າເຊີບເວີຖານຂໍ້ມູນ",
    "deleteDataServer": "ທ່ານກຳລັງຈະລຶບເອກະສານການຕັ້ງຄ່າເຊີບເວີຖານຂໍ້ມູນ，ການລຶບເອກະສານນີ້ຈະບໍ່ສົ່ງຜົນກະທົບຕໍ່ການເຮັດວຽກຂອງເຊີບເວີ，ຕ້ອງການສືບຕໍ່ບໍ？",

    "deleteStorageServer_title": "ເອົາການຢືນຢັນການຕັ້ງຄ່າການເກັບຮັກສາເຊີບເວີ",
    "deleteStorageServer": "ທ່ານກຳລັງຈະລົບລ້າງເອກະສານການຕັ້ງຄ່າການເກັບຮັກສາເຊີບເວີ，ການລຶບເອກະສານນີ້ຈະບໍ່ສົ່ງຜົນກະທົບຕໍ່ການເຮັດວຽກຂອງເຊີບເວີ，ຕ້ອງການສືບຕໍ່ບໍ？",

    "deleteWebServer_title": "ເອົາການຢືນຢັນການຕັ້ງຄ່າWeb",
    "deleteWebServer": "ທ່ານກຳລັງລົບເອກະສນການຕັ້ງຄ່າ Web ，ການລຶບເອກະສານນີ້ຈະບໍ່ສົ່ງຜົນກະທົບຕໍ່ການເຮັດວຽກຂອງເຊີບເວີ，ຕ້ອງການສືບຕໍ່ບໍ？",

    "deleteStorage_title": "ຖອນການຢືນຢັນການຕັ້ງຄ່າບ່ອນເກັບຂໍ້ມູນ",
    "deleteStorage": "ທ່ານກຳລັງລົບເອກະສານການຕັ້ງຄ່າການເກັບຮັກສາເຊີບເວີ，ຕ້ອງການສືບຕໍ່ບໍ？",

    "centerSaveInfor": "ສົ່ງຂໍ້ມູນສຳເລັດ",
    "saveWeightError": "ຕ້ອງເປັນຕົວເລກ",

    "mobileSetting1": "1、ກວດສອບ",
    "mobileSetting2": "2、ບັນຊີ",
    "mobileSetting3": "3、server",

    "checkCenterToCollect": "ເຊື່ອມຕໍ່ Sever O2 Center ",
    "checkComputerToCollect": "ລູກຄ້າເຊື່ອມຕໍ່ ",
    "success": "ສຳເລັດ",
    "failure": "ລົ້ມເລວ",

    "reCheck": "ກວດສອບ Link ຄືນໃໝ່",
    "next": "ຖັດໄປ",
    "loginCollect": "ເຂົ້າລະບົບ O2 ສູນກາງ ",
    "loggedCollect": "ເຈົ້າເຂົ້າລະບົບ O2 ສູນກາງແລ້ວ",
    "loginText": "ເຂົ້າລະບົບ O2 ສູນກາງ",
    "logoutText": "ອອກຈາກລະບົບ O2 ສູນກາງ ",
    "registerText": "ຖ້າເຈົ້າບໍ່ມີບັນຊີໃນລະບົບ O2 ສູນກາງ，ກະລຸນາລົງທະບຽນບໍລິສັດຂອງເຈົ້າກ່ອນ",

    "loginInputUsername": "ກະລຸນາຕື່ມຊື່ຜູ້ໃຊ້ ແລະ ລະຫັດ",
    "loginInputCode": "ກະລຸນາປ້ອນລະຫັດຢືນຢັນ",

    "companyName": "ຊື່ບໍລິສັດ",
    "code": "ລະຫັດຢືນຢັນ",
    "phone": "ເບີໂທລະສັບ",
    "password": "ປ້ອນລະຫັດ",
    "confirmPassword": "ຢືນຢັນລະຫັດ",

    "registerTitle": "ລົງທະບຽນບໍລິສັດຂອງທ່ານຢູ່ສູນ O2",
    "getPhoneCode": "ລະຫັດຢືນຢັນໂທລະສັບມືຖື",
    "getPhoneCodeWait": "ສົ່ງລະຫັດຢືນຢັນແລ້ວ",
    "registerActionText": "ລົງທະບຽນ",
    "registerCancelActionText": "ຍົກເລີກລົງທະບຽນ",
    "phoneError": "ກະລຸນາຕື່ມເບີໂທລະສັບ",
    "phoneTypeError": "ກະລຸນາຢືນຢັນການປ້ອນເບີໂທລະສັບ",
    "nameError": "ກະລຸນາປ້ອນຊື່ບໍລິສັດ",
    "codeError": "ກະລຸນາໃສ່ລະຫັດຢືນຢັນ",
    "passwordError": "ກະລຸາປ້ອນລະຫັດໃສ່",
    "confirmError": "ກະລຸນາຢືນຢັນການປ້ອນລະຫັດ",
    "confirmPasswordError": "ການປ້ອນລະຫັດຜ່ານແລະການຢືນຢັນລະຫັດບໍ່ສອດຄ່ອງກັນ",

    "cancelRegisterTitle": "ຍົກເລີກການຢືນຢັນການລົງທະບຽນ",
    "cancelRegister": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກການລົງທະບຽນ？",
    "registerSuccess": "ບໍລິສັດຂອງທ່ານໄດ້ຖືກລົງທະບຽນ O2 ສູນກາງສໍາເລັດ<br/>ທ່ານສາມາດໃຊ້“{name}”ເຂົ້າເຖິງລະບົບສູນກາງO2 ",
    "registerSuccessTitle": "ບໍລິສັດຂອງທ່ານໄດ້ຖືກລົງທະບຽນ O2 ສູນກາງສໍາເລັດ",

    "mobileServerSaveInfor": "ສົ່ງຂໍ້ມູນສຳເລັດ",
    "mobileServerSaveErrorInfor": "ສົ່ງຂໍ້ມູນສຳເລັດ, ເມື່ອຂໍ້ຜິດພາດຕໍ່ໄປນີ້ເກີດຂື້ນ：{error}",

    "saveDefaultMenuData": "ບັນທຶກເປັນການຕັ້ງຄ່າເມນູເລີ່ມຕົ້ນ",
    "clearDefaultMenuData": "ລຶບລ້າງການຕັ້ງຄ່າເມນູເລີ່ມຕົ້ນ",
    "saveDefaultMenuDataInfor": "ຫຼັງຈາກບັນທຶກເປັນການຕັ້ງຄ່າເມນູເລີ່ມຕົ້ນ，ຜູ້ໃຊ້ທີ່ຍັງບໍ່ໄດ້ຕັ້ງຄ່າເມນູສ່ວນບຸກຄົນ，ເມນູຈະສະແດງຕາມການຕັ້ງຄ່ານີ້。",
    "saveDefaultMenuDataSuccess": "ບັນທຶກການຕັ້ງຄ່າເມນູເລີ່ມຕົ້ນສຳເລັດແລ້ວ",
    "clearDefaultMenuDataSuccess": "ລຶບລ້າງການຕັ້ງຄ່າເມນູເລີ່ມຕົ້ນແລ້ວ",
    "clearDefaultMenuDataConfirm": "ທ່ານແນ່ໃຈບໍ່ວ່າລຶບການຕັ້ງຄ່າເມນູເລີ່ມຕົ້ນ？",
    "loadDefaultMenuData": "ໂຫຼດການຕັ້ງຄ່າເລີ່ມຕົ້ນ",

    "saveForceMenuData": "ບັນທຶກເປັນການຕັ້ງຄ່າເມນູບັງຄັບ",
    "clearForceMenuData": "ລຶບການຕັ້ງຄ່າເມນູບັງຄັບ",
    "saveForceMenuDataInfor": "ຫຼັງຈາກບັນທຶກເປັນການຕັ້ງຄ່າເມນູບັງຄັບ，ຜູ້ໃຊ້ທັງໝົດຈະສະແດງເມນູຕາມການຕັ້ງຄ່ານີ້，ການຕັ້ງຄ່າສ່ວນບຸກຄົນຈະບໍ່ເຮັດວຽກອີກຕໍ່ໄປ。",
    "saveForceMenuDataSuccess": "ບັນທຶກການຕັ້ງຄ່າເມນູເລີ່ມຕົ້ນສຳເລັດແລ້ວ",
    "clearForceMenuDataSuccess": "ບັງຄັບການຕັ້ງຄ່າເມນູຖືກລຶບລ້າງ",
    "clearForceMenuDataConfirm": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງກນລຶບການຕັ້ງຄ່າເມນູບັງຄັບ？",
    "loadForceMenuData": "ໂຫຼດການຕັ້ງຄ່າບັງຄັບ",

    "clearCustomMenuData": "ລຶບລ້າງການຕັ້ງຄ່າເມນູສ່ວນບຸກຄົນຂອງຜູ້ໃຊ້",
    "clearCustomMenuDataInfor": "ການຕັ້ງຄ່າເມນູສ່ວນບຸກຄົນຂອງຜູ້ໃຊ້ທັງຫມົດຈະຖືກລຶບລ້າງ，ສະແດງເມນູໃນຮູບແບບເລີ່ມຕົ້ນ。",
    "clearCustomMenuDataSuccess": "ການຕັ້ງຄ່າເມນູສ່ວນບຸກຄົນຂອງຜູ້ໃຊ້ຖືກລົບລ້າງແລ້ວ",
    "clearCustomMenuDataConfirm": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບລ້າງການຕັ້ງຄ່າເມນູສ່ວນຕົວຜູ້ໃຊ້ທັງໝົດ"
};
