MWF.xApplication.Setting.LP = {
    "title": "系統設置",
	"default": "默認值",

	"tab_base": "基本設置",
	"tab_ui": "界面設置",
	"tab_mobile": "移動辦公設置",
	"tab_cloud": "雲服務設置",
	"tab_dispose": "系統部署",
	"tab_name": "系統名稱設置",
	"tab_user": "系統用戶設置",
	"tab_login": "系統登錄設置",
	"tab_sso": "系統SSO設置",
	"tab_config": "平臺設置",

	"tab_cloud_connect": "連接設置",

	"tab_mobile_connect": "連接設置",
	"tab_mobile_module": "模塊設置",
	"tab_mobile_style": "樣式設置",
	"tab_mobile_mpweixin_menu": "公眾號菜單設置",
	"tab_mobile_app_pack": "移動應用程序在線打包",

	"tab_ui_login": "登錄頁面樣式",
	"tab_ui_index": "主頁樣式",
	"tab_ui_module": "模塊部署",
	"tab_ui_resource": "資源部署",
	"tab_ui_service": "服務部署",
	"tab_ui_menu": "菜單編輯",

	"base_nameSetting": "系統名稱設置",

	"base_title": "系統名稱",
	"base_title_infor": "系統名稱將顯示在登錄頁面和瀏覽器標題欄中。",
	"base_title_action": "編輯系統名稱",
	"base_title_empty": "請輸入系統名稱。",

	"base_footer": "系統副標題",
	"base_footer_infor": "系統副標題將顯示在登錄頁面底部。",
	"base_footer_action": "編輯系統副標題",
	"base_version": "當前系統版本",


    "base_personSetting": "配置系統的用戶帳戶基本信息",
	"base_UserPassword": "新建用戶的默認密碼",
	"base_UserPassword_infor": "創建新用戶時使用的默認密碼，用戶可以登錄系統後自行更改",
	"base_UserPassword_action": "修改默認密碼",
	"base_UserPassword_empty": "默認密碼不能為空",

	"base_passwordPeriod": "密碼過期時間（天）",
	"base_passwordPeriod_infor": "超過此設定的天數未修改密碼的用戶，在登錄後將強制要求修改密碼，否則無法進入系統",
	"base_passwordPeriod_action": "修改密碼期限",

	"base_adminPassword": "超級管理員密碼",
	"base_adminPassword_infor": "超級管理員 xadmin 的密碼。",
	"base_adminPassword_action": "修改超級管理員密碼",
	"base_adminPassword_confirm": "<div style='color:red'>超級管理員密碼關聯默認數據庫口令等，請謹慎修改超級管理員密碼！<br>修改密碼後請立即重啟，否則系統可能出錯！</div><br>您確定要修改嗎？",

	"base_loginSetting": "配置用戶登錄選項",

	"base_captchaLogin": "啟用圖片驗證碼登錄",
	"base_captchaLogin_infor": "啟用後登錄時必須正確輸入圖片驗證碼",
	"base_captchaLogin_action": "",

	"base_codeLogin": "啟用短信驗證碼登錄",
	"base_codeLogin_infor": "啟用後允許通過短信驗證碼登錄",
	"base_codeLogin_action": "",

	"base_bindLogin": "啟用掃描二維碼登錄",
	"base_bindLogin_infor": "啟用後允許掃描二維碼登錄",

    "base_faceLogin": "啟用人臉識別登錄",
	"base_faceLogin_infor": "啟用後允許人臉識別登錄，用戶可到個人設置中設置人臉特徵。啟用後您必須創建一個SSO配置，名稱為face，密鑰為xplatform（這是一個實驗性功能，您必須啟用https）。",

	"base_faceApi": "人臉識別服務",
	"base_faceApi_action": "編輯人臉識別服務",
	"base_faceApi_delete": "編輯人臉識別服務",
	"base_faceApi_infor": "使用Face++人臉服務，您可以編輯您的API Key和API Secret。否則系統將使用默認帳戶，QPS會受到限制。",

	"base_register": "啟用自助註冊",
	"base_register_infor": "是否允許自助註冊成為系統用戶，以及註冊方式。",
	"register_disable": "不允許自助註冊",
	"register_captcha": "允許使用圖片驗證碼自助註冊",
	"register_code": "允許使用短信驗證碼自助註冊",

	"base_portalLogin": "使用門戶頁面登錄",
	"base_portalLogin_infor": "可使用定制的門戶頁面作為登錄頁，登錄頁面模板可從應用市場下載。",
	"base_portalLogin_action": "",

	"base_loginPortalId": "登錄門戶",
	"base_loginPortalId_infor": "選擇登錄頁面的門戶。",

	"base_portalIndex": "使用門戶頁面作為系統首頁",
	"base_portalIndex_infor": "可使用定制的門戶頁面作為系統首頁，登錄後打開此頁面。",
	"base_portalIndex_action": "",
	"base_indexPortalId": "系統首頁門戶",
	"base_indexPortalId_infor": "選擇系統首頁的門戶。",

	"base_temary": "三員管理",
	"base_temary_info": "三員管理（系統管理員、安全保密管理員、安全審計員）。本功能開啟後請重啟伺服器以啟動日誌。",
	"base_temary_action": "",

	"base_ldap": "啟用LDAP認證",
	"base_ldap_infor": "啟用後，用戶登錄認證使用LDAP認證，不再使用本系統的密碼登錄。",
	"base_ldap_action": "編輯LDAP認證配置",
	"base_ldap_enable": "已啟用",
	"base_ldap_unenable": "未啟用",


    "base_ssoSetting": "配置與其他系統的驗證和單點登錄設置",
	"base_ssos": "驗證配置",
	"base_sso_infor": "您可以為多個系統創建驗證，用於SSO登錄和服務調用",
	"base_sso_action": "添加驗證配置",
	"base_sso_editAction": "編輯驗證配置",

	"base_oauths": "OAUTH客戶端配置",
	"base_oauths_infor": "如果本系統作為OAUTH2認證伺服器，您可以在此可以配置多個OAUTH客戶端，為其他系統實現授權",
	"base_oauths_action": "添加oauth配置",
	"base_oauths_editAction": "編輯oauth配置",

	"base_oauths_server": "OAUTH服務器配置",
	"base_oauths_infor_server": "如果本系統需要通過其他OAUTH2伺服器認證，您可以在此可以配置多個OAUTH服務器，為本系統實現授權",

	"base_qyweixin": "企業微信配置",
	"base_qyweixin_infor": "系統可以和企業微信集成，請先配置微信企業號和密鑰",
	"base_qyweixin_action": "編輯企業微信配置",

	"base_dingding": "釘釘配置",
	"base_dingding_infor": "系統可以和釘釘集成，請先配置釘釘企業號和密鑰",
	"base_dingding_action": "編輯釘釘配置",

	"mobile_connectSetting": "移動辦公連接配置",
	"cloud_connectSetting": "雲服務連接配置",
	"mobile_connect_first_cloud_check": "1. 雲服務連接檢查",
	"mobile_connect_first_cloud_check_connected": "<span style='color: #5fbf78'> [已連接登錄] </span> 雲服務",
	"mobile_connect_first_cloud_check_disconnected": "<span style='color: #ff0000'> [未連接登錄] </span> 雲服務，請到 雲服務配置 頁面進行註冊登錄！",
	"mobile_connect_connectSetting": "2. 外網連接配置",
	"mobile_connect_third_mobile_connect_check": "3. 手機連接測試",
	"mobile_connect_third_mobile_connect_check_info": "使用手機掃描二維碼，查看外網是否可以連接伺服器！",
	"mobile_connect_third_mobile_connect_check_generate_button": "生成二維碼",

	"mobile_connectO2Cloud": "連接到O2雲",
	"mobile_connectO2Cloud_infor": "使用移動辦公請先連接到O2雲，這有助於APP定位到您的企業伺服器，可以使用短信服務等",
	"mobile_connectO2Cloud_action": "連接到O2雲",
	"mobile_connectO2Cloud_success": "連接設定",
	"mobile_connectO2Cloud_error": "還未連接到O2雲",

    "mobile_httpProtocol": "HTTP協議",
	"mobile_httpProtocol_infor": "請選擇使用HTTP協議還是HTTPS協議",

	"mobile_center": "中心伺服器",
	"mobile_center_infor": "中心伺服器對外服務的IP地址或域名和端口。（使用HTTP協議時只能使用IP地址）",
	"mobile_center_action": "編輯中心伺服器",

	"mobile_web": "WEB伺服器",
	"mobile_web_infor": "WEB伺服器對外服務的IP地址或域名和端口，如果域名或IP地址為空或“127.0.0.1”則使用中心伺服器地址。（使用HTTP協議時只能使用IP地址）",
	"mobile_web_action": "編輯WEB伺服器",

	"mobile_application": "應用伺服器",
	"mobile_application_infor": "應用伺服器對外服務的IP地址或域名和端口，如果域名或IP地址為空或“127.0.0.1”則使用中心伺服器地址。（使用HTTP協議時只能使用IP地址）",
	"mobile_application_action": "編輯應用伺服器",

	"mobile_moduleSetting": "移動端模塊配置",
	"mobile_index": "移動端首頁配置",
	"mobile_index_infor": "您可以配置移動端的首頁為默認應用程序樣式，或指定一個門戶頁面",
	"mobile_index_defalue": "默認",

	"mobile_module": "{name}模塊",
	"mobile_module_infor": "是否在移動端啟用{name}模塊",

	"mobile_module_simple_mode": "移動端簡易模式",
	"mobile_module_simple_mode_infor": "啟用移動端簡易模式後，僅顯示首頁和設置頁面",

	"mobile_module_system_message_switch": "顯示系統通知",
	"mobile_module_system_message_switch_infor": "在移動應用程序消息列表中是否顯示系統通知",

	"mobile_module_contact_permission_view": "移動應用程序通訊錄權限視圖",
	"mobile_module_contact_permission_view_infor": "需要安裝應用市場的【通訊錄】應用程序，應用內包含通訊錄的權限配置視圖",
	"mobile_module_contact_permission_view_action": "修改視圖名稱",

	"mobile_styleSetting": "移動端圖標樣式配置",
	"mobile_style": "{name}圖片 ",
	"mobile_style_infor": "點擊更換{name}圖片",
    "mobile_style_imgs": {
		"launch_logo": "啟動標誌",
		"login_avatar": "登錄界面默認頭像",
		"application_top": "應用程序頁面頂部",
		"index_bottom_menu_logo_blur": "主頁導航圖標（未選中）",
		"index_bottom_menu_logo_focus": "主頁導航圖標（已選中）",
		"people_avatar_default": "用戶默認頭像",
		"process_default": "流程默認圖標",
		"setup_about_logo": "關於頁面圖標"
	},
	"mobile_style_imgs_defaultTitle": "默認圖片確認",
	"mobile_style_imgs_defaultInfor": "您確定要將{name}更換為默認圖像嗎？",

    "mpweixin": "公眾號",
	"publishMpweixin": "發佈到微信公眾號",
	"subscribeMpweixin": "關注回覆",
	"subscribeMpweixin_desc": "當新用戶關注時，自動發送的消息內容",
	"subscribeMpweixin_save": "保存",
	"mpweixinInfo": "⚠️ 微信公眾號菜單功能需要先啟用相關的配置文件[mpweixin.json]，並到微信的公眾號管理後台，開發模塊中啟用服務器配置！",
	"mobile_mpweixin_menu_msg_publish_2_wxmp": "注意！當前操作會將所有保存的菜單數據覆蓋到微信公眾號，確定要繼續嗎？",
	"mobile_mpweixin_menu_msg_publish_success": "發佈成功，將在24小時後在手機端同步顯示！",
	"mobile_mpweixin_menu_msg_first_max_len": "一級菜單最多只能創建3個！",
	"mobile_mpweixin_menu_msg_sub_max_len": "二級菜單最多只能創建5個！",
	"mobile_mpweixin_menu_msg_parent_no_save": "上級菜單數據未保存，請先保存數據！",
	"mobile_mpweixin_menu_deleteBtnName_label": "刪除菜單",
	"mobile_mpweixin_menu_default_new_name": "新增菜單",
	"mobile_mpweixin_menu_form_name_label": "菜單名稱",
	"mobile_mpweixin_menu_form_name_error_empty": "菜單名稱不能為空！",
	"mobile_mpweixin_menu_form_name_error_max_len_4": "菜單名稱字數不能超過4個！",
	"mobile_mpweixin_menu_form_name_error_max_len_6": "菜單名稱字數不能超過6個！",
	"mobile_mpweixin_menu_form_name_error": "字數超過上限",
	"mobile_mpweixin_menu_form_name_tips_4": "僅支持中英文和數字，字數不超過4個",
	"mobile_mpweixin_menu_form_name_tips_6": "僅支持中英文和數字，字數不超過6個",
	"mobile_mpweixin_menu_form_order_label": "菜單排序號",
	"mobile_mpweixin_menu_form_order_error_empty": "菜單排序號不能為空！",
	"mobile_mpweixin_menu_form_order_error_not_number": "菜單排序號只能輸入數字！",
	"mobile_mpweixin_menu_form_order_error_max_len": "菜單排序號字數不能超過6個！",
	"mobile_mpweixin_menu_form_order_error": "字數超過上限",
	"mobile_mpweixin_menu_form_order_tips": "僅支持數字，字數不超過6個，排序按照字符串排序",
	"mobile_mpweixin_menu_form_radio_label": "菜單內容",
	"mobile_mpweixin_menu_form_radio_type_msg": "發送消息",
	"mobile_mpweixin_menu_form_radio_type_url": "跳轉網頁",
	"mobile_mpweixin_menu_form_radio_type_miniprogram": "跳轉小程序",
	"mobile_mpweixin_menu_form_type_msg_tips": "點擊該菜單會發送下列文字給用戶，未認證訂閱號不支持文字消息",
	"mobile_mpweixin_menu_form_type_msg_label": "文字消息",
	"mobile_mpweixin_menu_form_type_msg_error_empty": "文字消息內容不能為空！",
	"mobile_mpweixin_menu_form_subscribe_content_error_empty": "回復消息內容不能為空！",
	"mobile_mpweixin_menu_form_type_url_tips": "點擊該菜單會跳到以下鏈接",
	"mobile_mpweixin_menu_form_type_url_label": "頁面地址",
	"mobile_mpweixin_menu_form_type_url_error_empty": "頁面地址不能為空！",
	"mobile_mpweixin_menu_form_type_miniprogram_tips": "點擊該菜單會跳到以下小程序",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_label": "小程序ID",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_placeholder": "小程序ID，請到微信的小程序管理後台查看",
	"mobile_mpweixin_menu_form_type_miniprogram_appid_error_empty": "小程序ID不能為空！",
	"mobile_mpweixin_menu_form_type_miniprogram_path_label": "小程序路徑",
	"mobile_mpweixin_menu_form_type_miniprogram_path_placeholder": "小程序路徑，請到微信的小程序管理後台查看",
	"mobile_mpweixin_menu_form_type_miniprogram_path_error_empty": "小程序路徑不能為空！",
	"mobile_mpweixin_menu_form_type_miniprogram_url_label": "備用網頁",
	"mobile_mpweixin_menu_form_type_miniprogram_url_placeholder": "備用網頁，舊版微信會打開這個備用網頁",
	"mobile_mpweixin_menu_form_type_miniprogram_url_error_empty": "備用網頁不能為空！",
	"mobile_mpweixin_menu_save_success": "數據保存成功！",
	"mobile_mpweixin_menu_delete_alert_msg": "確認要刪除這條數據嗎，會同時刪除它的子菜單？",
	"mobile_mpweixin_menu_delete_success": "數據刪除成功！",
    
    
    "save": "儲存",
	"alert": "警告",
	"mobile_apppack_tips1": "⚠️ 目前，移動應用程序在線打包功能僅支持 Android 端。",
	"mobile_apppack_tips2": "⚠️ 若要進行在線打包，必須先在[雲服務配置]中進行註冊和登錄。",
	"mobile_apppack_tips3": "⚠️ 提交信息後，當前打包狀態將顯示，打包過程需要較長時間，您可以暫時離開當前頁面，等待完成後再在本頁面下載 APK 文件。",
	"mobile_apppack_status_label": "當前狀態",
	"mobile_apppack_form_appName": "應用程式名稱",
	"mobile_apppack_form_appName_tip": "顯示在桌面的應用程式名稱，不超過6個字符",
	"mobile_apppack_form_logo": "標誌圖片",
	"mobile_apppack_form_logo_tip": "應用程式桌面顯示的標誌圖片，必須是 PNG 格式",
	"mobile_apppack_form_protocol": "HTTP 協議",
	"mobile_apppack_form_protocol_tip": "http / https",
	"mobile_apppack_form_host": "域名",
	"mobile_apppack_form_host_tip": "中央伺服器的域名或 IP，例如 www.o2oa.net",
	"mobile_apppack_form_port": "埠號",
	"mobile_apppack_form_port_tip": "中央伺服器的埠號，例如 20030",
	"mobile_apppack_form_context": "上下文",
	"mobile_apppack_form_context_tip": "中央伺服器的上下文，例如 /x_program_center",
	"mobile_apppack_form_urlMapping": "代理 URL 對應",
	"mobile_apppack_form_urlMapping_tip": "在外部伺服器使用代理地址時使用，例如 { \"demo.o2oa.net:20020\": \"demo.o2oa.net/dev/app\" }",
	"mobile_apppack_form_appVersionName": "應用程式版本名稱",
	"mobile_apppack_form_appVersionName_tip": "應用程式的版本名稱，例如 v1.0.0。通常不需要填寫此欄位！",
	"mobile_apppack_form_appBuildNo": "應用程式版本編號",
	"mobile_apppack_form_appBuildNo_tip": "應用程式的版本編號，必須為正整數，例如 100。通常不需要填寫此欄位！",
	"mobile_apppack_form_button": "提交並開始打包",
	"mobile_apppack_form_reinput_button": "重新填寫表單並打包",
	"mobile_apppack_form_re_pack_button": "使用現有資料直接打包",
	"mobile_apppack_form_download_apk_button": "下載 APK 文件",
	"mobile_apppack_message_o2cloud_not_enable": "O2 雲未啟用或無法連接！",
	"mobile_apppack_message_o2cloud_not_login": "請先登錄到 O2 雲！",
	"mobile_apppack_message_apppack_server_login_fail": "應用程式打包伺服器登錄失敗！",
	"mobile_apppack_message_check_connect_fail": "應用程式打包服務檢查連接失敗！",

    "mobile_apppack_form_enable_outer_status_no": "未啟用",
	"mobile_apppack_form_enable_outer_status_yes": "已啟用",
	"mobile_apppack_form_enable_outer_package": "是否啟用外部包名",
	"mobile_apppack_form_enable_delete_hms": "是否刪除HMS",
	"mobile_apppack_form_enable_outer_tips": "啟用外部包名可以防止和官方發布的應用程式衝突覆蓋",
	"mobile_apppack_form_enable_delete_hms_tips": "刪除HMS無法使用華為推送，請謹慎操作",
	"mobile_apppack_form_enable_delete_hms_status_no": "否",
	"mobile_apppack_form_enable_delete_hms_status_yes": "是",
	"mobile_apppack_form_download_publish_btn": "下載發布到本地",
	"mobile_apppack_message_confirm_publish": "應用程式已經打包完成，立即下載並發布到本地伺服器，然後掃描登錄畫面的二維碼即可安裝應用程式！",
	"mobile_apppack_publish_status_doing": "發布中...",
	"mobile_apppack_publish_status_completed": "發布完成，掃描登錄畫面的二維碼即可安裝應用程式！",
	"mobile_apppack_publish_status_fail": "發布失敗，請重試或聯繫管理員！",
	"mobile_apppack_status_order_inline": "排隊中......",
	"mobile_apppack_status_packing": "打包中......",
	"mobile_apppack_status_pack_end": "打包完成",
	"mobile_apppack_status_pack_error": "打包出錯",
	"mobile_apppack_message_appname_not_empty": "應用程式名稱不能為空！",
	"mobile_apppack_message_appname_len_max_6": "應用程式名稱不能超過6個字！",
	"mobile_apppack_message_app_logo_not_empty": "標誌圖片不能為空！",
	"mobile_apppack_message_app_logo_need_png": "標誌圖片必須是 PNG 格式！",
	"mobile_apppack_message_portocol_not_empty": "HTTP 協議不能為空！",
	"mobile_apppack_message_host_not_empty": "中央伺服器域名不能為空！",
	"mobile_apppack_message_host_format_error": "請填寫中央伺服器域名或 IP，例如 www.o2oa.net，不要帶 http 這樣的頭！",
	"mobile_apppack_message_port_not_empty": "中央伺服器埠號不能為空！",
	"mobile_apppack_message_context_not_empty": "中央伺服器上下文不能為空！",
	"mobile_apppack_message_portocol_http_https": "HTTP 協議只能是 http 或 https ！",
	"mobile_apppack_refresh_status_btn": "刷新狀態",
	"mobile_apppack_message_alert_submit": "確定要提交嗎，當前表單信息將被打包成移動端應用程式？",
	"imgSize": "圖片尺寸：",
	"defaultImg": "默認圖片",

    "ui_loginSetting": "登錄頁面樣式設置",
    "ui_login_default": "默認樣式",
    "ui_login_defaultStyle": "登錄頁面默認樣式",
    "ui_login_defaultStyle_infor": "",
    "ui_login_customStyle": "登錄頁面自定義樣式",
    "ui_login_customStyle_infor": "",
    "ui_login_customStyle_Action": "創建自定義樣式",
    "ui_login_customStyle_newName": "新樣式名稱",
    "ui_login_customStyle_newName_empty": "請輸入新樣式名稱",
    "ui_login_setCurrent": "使用此樣式",
    "ui_login_current": "當前使用的樣式",
    "ui_login_setCurrent_confirmTitle": "使用樣式確認",
    "ui_login_setCurrent_confirm": "您確定要使用 “{title}” 樣式嗎？",

    "ui_login_delete_confirmTitle": "刪除樣式確認",
    "ui_login_delete_confirm": "您確定要刪除 “{title}” 樣式嗎？",

    "ui_indexSetting": "平台樣式配置",
    "ui_index_systemStyle": "平台內置樣式",
    "ui_index_systemStyle_infor": "",

    "ui_index_customStyle": "自定義樣式配置",
    "ui_index_customStyle_infor": "",
    "ui_index_customStyle_Action": "",
    "ui_index_enabled": "已啟用",
    "ui_index_disabled": "已禁用",

    "ui_moduleSetting": "系統模塊配置",
    "ui_module_modules": "已部署模塊",
    "ui_module_modules_infor": "",
    "ui_module_modules_Action": "部署模塊",

    "ui_moduleSetting_resource": "web端資源部署",
    "ui_moduleSetting_service": "服務部署",

    "resource_upload": "資源選擇",
    "resource_replace": "是否覆蓋",
    "resource_replaceDesc": "覆蓋類型：'否'刪除原文件然後上傳，'是'覆蓋原文件",
    "resource_replace_yes": "是",
    "resource_replace_no": "否",
    "resource_filePath": "存放目錄",
    "resource_filePathDesc": "zip文件可以為空，其他不能為空path:/xxx/xxx",
    "resource_success": "部署成功",

    "service_ctl": "命令名稱",
    "service_node": "伺服器節點",
    "service_allNode": "全部節點",
    "service_success": "部署成功，需要重啟服務後生效",

    "on": "開",
    "off": "關",

    "loading": "正在加載樣式，請稍候……",
    "returnBack": "返回",

    "ok": "確定",
    "cancel": "取消",
    "edit": "編輯",
    "delete": "刪除",
    "copy": "複製",
    "copyName": "複製",

    "deleteItem": "刪除配置確認",
    "deleteItemInfor": "您確定要刪除此項配置嗎？",

    "setSaved": "配置數據已保存",

    "pleaseInput": "請輸入",
    "list": {
        "client": "驗證名稱",
        "key": "密鑰（最少8位）",
        "clientId": "客戶端 ID",
        "mapping": "映射 (Mapping)",
        "corpId": "corpId",
        "corpSecret": "corpSecret",
        "agentId": "代理商 ID",
        "proxyHost": "域名或 IP 地址",
        "proxyPort": "端口",
        "node": "應用伺服器",

        "enable": "是否啟用",
        "name": "名稱",
        "icon": "圖示",
        "clientSecret": "客戶端密鑰",
        "authAddress": "請求密鑰網址",
        "authParameter": "請求密鑰方法參數",
        "authMethod": "請求密鑰方法（GET或POST）",
        "tokenAddress": "請求令牌網址",
        "tokenParameter": "請求令牌方法參數",
        "tokenMethod": "請求令牌方法（GET或POST）",
        "tokenType": "令牌資訊格式（json或form）",
        "infoAddress": "請求資訊網址",
        "infoParameter": "請求資訊方法參數",
        "infoMethod": "請求資訊方法（GET或POST）",
        "infoType": "資訊資訊格式（json或form）",
        "infoCredentialField": "資訊中用於標識個人的字段",

        "infoProxyHost" : "域名不需要包含 http",

        "ldapUrl": "ldapUrl(LDAP地址，例如 ldap://111.111.111.111:5389/)",
        "baseDn": "baseDn(LDAP查詢的根名稱，例如：dc=zone,DC=COM)",
        "userDn": "userDn(認證使用者的DN，例如：uid=*,ou=users,dc=zone,DC=COM，其中 uid=* 中的 * 表示使用者的唯一編碼，此唯一編碼與 O2 使用者的唯一編碼對應)"
    },

    "module": {
        "title": "應用部署",
        "open": "打開",
        "edit": "編輯",
        "remove": "卸載",
        "add": "部署組件",

        "name": "組件名稱",
        "componentTitle": "組件標題",
        "path": "組件路徑",
        "icon": "組件圖示",
        "isVisible": "是否可見",
        "yes": "是",
        "no": "否",
        "widgetName": "部件名稱",
        "widgetTitle": "部件標題",
        "widgetStart": "部件自動啟動",
        "widgetVisible": "部件是否可見",

        "allowList": "可訪問列表",
        "denyList": "拒絕訪問列表",
        "controllerList": "管理員",
        "selPerson": "選擇人員",
        "selIcon": "選擇圖示",
        "urlInfor": "您可以通過“@url:”將路徑添加為一個網頁URL，如“@url:http://www.bing.com”",

        "phone": "手機",
        "mail": "電子郵件",

        "noInputInfor": "請完整填寫組件信息。（必須填寫：組件名稱、組件標題、組件路徑）",
        "deploySuccess": "部署成功",
        "modifySuccess": "修改組件信息成功",

        "removeComponentTitle": "卸載組件確認",
        "removeComponent": "您確定要卸載組件：{name} 嗎？",
        "removeComponentOk": "組件已卸載",

        "modify": "修改組件信息",

        "moduleDeployed" : "已部署組件",
        "inputAppNameNotice" : "請輸入應用名稱和應用標題",
        "uploadZipFileNotice": "請上傳文件的ZIP包"
    },






    "tab_centerServer": "中心伺服器",
    "tab_Server": "服務主機配置",
    "tab_Application": "應用數據配置",
    "tab_Resource": "資源參數配置",
    "tab_Mobile": "移動辦公配置",

    "tab_ApplicationServer": "應用伺服器",
    "tab_DataServer": "數據庫伺服器",
    "tab_StorageServer": "儲存伺服器",
    "tab_WebServer": "Web伺服器",

    "deploy": "部署應用",
    "deleteAppServer_title": "移除應用伺服器配置確認",
    "deleteAppServer": "您即將移除應用伺服器配置文件，移除此文件不會影響伺服器運行，是否要繼續？",
    "deployAppServer_title": "部署應用確認",
    "deployAppServer": "為當前伺服器部署應用，是否確認？<br><br><div style='color: #F00'><input type='checkbox'>重新部署所有應用</div>",

    "deleteDataServer_title": "移除數據庫伺服器配置確認",
    "deleteDataServer": "您即將移除數據庫伺服器配置文件，移除此文件不會影響伺服器運行，是否要繼續？",

    "deleteStorageServer_title": "移除儲存伺服器配置確認",
    "deleteStorageServer": "您即將移除儲存伺服器配置文件，移除此文件不會影響伺服器運行，是否要繼續？",

    "deleteWebServer_title": "移除Web伺服器配置確認",
    "deleteWebServer": "您即將移除Web伺服器配置文件，移除此文件不會影響伺服器運行，是否要繼續？",

    "deleteStorage_title": "移除儲存配置確認",
    "deleteStorage": "您即將移除儲存配置文件，是否要繼續？",

    "centerSaveInfor": "數據已提交",
    "saveWeightError": "必須是數字",

    "mobileSetting1": "1、檢查",
    "mobileSetting2": "2、帳號",
    "mobileSetting3": "3、伺服器",

    "checkCenterToCollect": "伺服器連接O2中心",
    "checkComputerToCollect": "客戶端連接O2中心",
    "success": "成功",
    "failure": "失敗",

    "reCheck": "重新檢查連線",
    "next": "下一步",
    "loginCollect": "登錄到O2中心",
    "loggedCollect": "您已經登錄O2中心",
    "loginText": "登錄O2中心",
    "logoutText": "從O2中心登出",
    "registerText": "如果您還沒有O2中心的公司帳號，請先註冊您的公司",

    "loginInputUsername": "請輸入用戶名和密碼",
    "loginInputCode": "請輸入驗證碼",

    "companyName": "公司名稱",
    "code": "驗證碼",
    "phone": "手機號碼",
    "password": "輸入密碼",
    "confirmPassword": "確認密碼",

    "registerTitle": "在O2中心註冊您的公司",
    "getPhoneCode": "獲取手機驗證碼",
    "getPhoneCodeWait": "驗證碼已發送",
    "registerActionText": "註 冊",
    "registerCancelActionText": "取消註冊",
    "phoneError": "請輸入手機號碼",
    "phoneTypeError": "請正確輸入手機號碼",
    "nameError": "請輸入公司名稱",
    "codeError": "請輸入驗證碼",
    "passwordError": "請輸入密碼",
    "confirmError": "請輸入確認密碼",
    "confirmPasswordError": "密碼和確認密碼輸入不一致",

    "cancelRegisterTitle": "取消註冊確認",
    "cancelRegister": "您確定要取消註冊嗎？",
    "registerSuccess": "您的公司已經在O2中心註冊成功<br/>您可以用“{name}”登錄到O2中心",
    "registerSuccessTitle": "您的公司已經在O2中心註冊成功",

    "mobileServerSaveInfor": "數據已提交",
    "mobileServerSaveErrorInfor": "數據已提交，但存在以下錯誤：{error}",

    "saveDefaultMenuData": "保存為默認菜單設置",
    "clearDefaultMenuData": "清除默認菜單設置",
    "saveDefaultMenuDataInfor": "保存為默認菜單設置後，未進行個性化菜單設置的用戶，將按照此設置顯示菜單。",
    "saveDefaultMenuDataSuccess": "默認菜單設置保存成功",
    "clearDefaultMenuDataSuccess": "默認菜單設置已清除",
    "clearDefaultMenuDataConfirm": "您是否確認清除默認菜單設置？",
    "loadDefaultMenuData": "載入默認配置",

    "saveForceMenuData": "保存為強制菜單設置",
    "clearForceMenuData": "清除強制菜單設置",
    "saveForceMenuDataInfor": "保存為強制菜單設置後，所有用戶都將按照此設置顯示菜單，個性化設置將失效。",
    "saveForceMenuDataSuccess": "強制菜單設置保存成功",
    "clearForceMenuDataSuccess": "強制菜單設置已清除",
    "clearForceMenuDataConfirm": "您是否確認清除強制菜單設置？",
    "loadForceMenuData": "載入強制配置",

    "clearCustomMenuData": "清除用戶個性化菜單設置",
    "clearCustomMenuDataInfor": "所有用戶的個性化菜單設置將被清除，以默認方式顯示菜單。",
    "clearCustomMenuDataSuccess": "用戶個性化菜單設置已清除",
    "clearCustomMenuDataConfirm": "您確定要清除所有用戶的個性化菜單設置嗎？"
};
