MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.query = MWF.xApplication.query || {};
MWF.xApplication.query.QueryManager = MWF.xApplication.query.QueryManager || {};
MWF.xApplication.query.QueryManager.LP={
	"title": "Aplicaciones de Datos",
	"categoryTitle": "Categorización de Aplicaciones de Datos",
	"description": "Descripción",
	"deleteItems": "Eliminar elementos seleccionados",
	"copy": "Copiar",
	"copyto": "Copiar a...",
	"copyInfor": "Seleccione varios elementos, presione Ctrl + C para copiar los elementos, presione Ctrl + V para pegar los elementos copiados en la aplicación actual.",
	"copyed": "Elementos seleccionados copiados",
	"copyConfirmTitle": "Confirmar copia de elementos",
	"copyConfirmInfor": "El área de destino ya contiene elementos idénticos:",
	"copyConfirmInfor_server": "Este servidor ya contiene elementos idénticos:",
	"copySource": "Archivo original:",
	"copyTarget": "Archivo copiado:",
	"copyConfirm_overwrite": "Sobrescribir",
	"copyConfirm_new": "Nuevo",
	"copyConfirm_skip": "Saltar",
	"copyConfirm_cancel": "Cancelar",
	"copynew": "Nuevo",
	"edit": "Editar",
	"save": "Guardar",
	"cancel": "Cancelar",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"deleteElementTitle": "Confirmación",
	"deleteElement": "¿Está seguro de que desea eliminar los elementos de diseño seleccionados?",
	"DeleteElementTable": "Después de la eliminación, el sistema elimina automáticamente la configuración de consulta correspondiente. ¿Está seguro de que desea eliminar la tabla seleccionada?",
	"viewName": "Vista",
	"statName": "Estadísticas",
	"statementName": "Consulta",
	"importerName": "Importar",
	"show": "Mostrar",
	"hide": "Ocultar",
	"naviCategory": "Navegación",
	"isShow": "¿Mostrar?",
	"isHidden": "¿Ocultar?",
	"showText": "Mostrar nombre",
	"interfaceConfig": "Configuración de navegación de interfaz",
	"moveUp": "Mover hacia arriba",
	"select": {
		"create": "Crear selector nuevo",
		"search": "Buscar selector",
		"searchText": "Ingrese la palabra clave",
		"noSelectNoticeText": "Esta aplicación de datos aún no tiene un selector, puede hacer clic aquí para crear uno nuevo.",
		"loaded": "Selector cargado",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar el selector actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar la plantilla del selector actual?"
	},
	"view": {
		"create": "Crear vista nueva",
		"search": "Buscar vista",
		"searchText": "Ingrese la palabra clave",
		"noViewNoticeText": "Esta aplicación de datos aún no tiene una vista, puede hacer clic aquí para crear una nueva vista.",
		"loaded": "Vista cargada",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar la vista actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar la plantilla de vista actual?"
	},
	"stat": {
		"create": "Crear estadística nueva",
		"search": "Buscar estadística",
		"searchText": "Ingrese la palabra clave",
		"noStatNoticeText": "Esta aplicación de datos aún no tiene una estadística, puede hacer clic aquí para crear una nueva estadística.",
		"loaded": "Estadística cargada",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar la estadística actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar la plantilla de la estadística actual?"
	},
	"reveal": {
		"create": "Crear presentador nuevo",
		"search": "Buscar presentador",
		"searchText": "Ingrese la palabra clave",
		"noRevealNoticeText": "Esta aplicación de datos aún no tiene un presentador, puede hacer clic aquí para crear uno nuevo.",
		"loaded": "Presentador cargado",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar el presentador actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar la plantilla del presentador actual?"
	},
	"table": {
		"create": "Crear tabla de datos nueva",
		"search": "Buscar tabla de datos",
		"searchText": "Ingrese la palabra clave",
		"noStatNoticeText": "Esta aplicación de datos aún no tiene una tabla de datos, puede hacer clic aquí para crear una nueva tabla de datos.",
		"loaded": "Tabla de datos cargada",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar la tabla de datos actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar la plantilla de la tabla de datos actual?"
	},
	"statement": {
		"create": "Crear configuración de consulta nueva",
		"search": "Buscar configuración de consulta",
		"searchText": "Ingrese la palabra clave",
		"noStatNoticeText": "Esta aplicación de datos aún no tiene una configuración de consulta, puede hacer clic aquí para crear una nueva configuración de consulta.",
		"loaded": "Configuración de consulta cargada",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar la configuración de consulta actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar la plantilla de la configuración de consulta actual?"
	},
	"application": {
		"inputApplicationName": "Ingrese el nombre",
		"property": "Propiedad",
		"name": "Nombre",
		"alias": "Alias",
		"description": "Descripción",
		"type": "Tipo",
		"icon": "Ícono",
		"id": "Identificación",
		"firstPage": "Página principal",
		"controllerList": "Controladores",
		"available": "Alcance disponible",
		"changeIcon": "Cambiar ícono",
		"setManager": "Establecer controladores",
		"setAppManager": "Establecer administrador de aplicaciones",
		"setUsableIdentity": "Establecer identidad utilizada",
		"setUsableUnit": "Establecer organización utilizada",
		"setAppUsableIdentity": "Establecer identidad de aplicación utilizada",
		"setAppUsableUnit": "Establecer organización de aplicación utilizada"
	},
	"importer": {
		"create": "Crear modelo de importación nuevo",
		"search": "Buscar modelo de importación",
		"searchText": "Ingrese la palabra clave",
		"noSelectNoticeText": "Esta aplicación de datos aún no tiene un modelo de importación, puede hacer clic aquí para crear uno nuevo.",
		"loaded": "Modelo de importación cargado",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar el modelo de importación actual?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar la plantilla del modelo de importación actual?"
	},
	"createSelectTemplate": "Crear: Plantilla de selección",
	"templateCategory": "Categoría de plantilla:",
	"all": "Todo",
	"selectorButton": {
		"ok": "Aceptar",
		"cancel": "Cancelar"
	},
	"navi": {
		"viewConfig": "Vista",
		"statConfig": "Estadísticas",
		"tableConfig": "Tabla",
		"statementConfig": "Consulta",
		"importerConfig": "Importación",
		"queryProperty": "Propiedades"
	},
	"deleteElementTable": "¿¿ está seguro de que quiere eliminar el formulario seleccionado y el sistema eliminará automáticamente la configuración de consulta correspondiente después de eliminarlo?"
}
MWF.xApplication.query.QueryManager["lp."+o2.language] = MWF.xApplication.query.QueryManager.LP