MWF.xApplication.query.QueryManager.LP = {
	"title": "データアプリ管理",
    "categoryTitle": "データアプリのカテゴリ",
    "description": "説明",
    "deleteItems": "選択したアイテムの削除",
    "copy": "コピー",
    "copyto": "コピー先...",
    "copyInfor": "複数の要素を選択し、Ctrl+Cを押すと要素がコピーされ、Ctrl+Vを押すとコピーした要素が現在のアプリに貼り付けられます。",
    "copyed": "選択した要素がコピーされました",
    "copyConfirmTitle": "要素コピーの確認",
    "copyConfirmInfor": "ターゲット領域には既に同じ要素が含まれています：",
    "copyConfirmInfor_server": "このサーバには既に同じ要素が含まれています：",
    "copySource": "元ファイル:",
    "copyTarget": "コピー ファイル:",
    "copyConfirm_overwrite": "上書き",
    "copyConfirm_new": "新規",
    "copyConfirm_skip": "スキップ",
    "copyConfirm_cancel": "キャンセル",
    "copynew": "新規",
    "edit": "編集",
    "save": "保存",
    "cancel": "キャンセル",
    "phone": "電話",
    "mail": "メール",
    "deleteElementTitle": "デザイン削除の確認",
    "deleteElement": "選択したデザイン要素を削除してもよろしいですか？",
    "viewName": "ビュー",
    "statName": "統計",
    "statementName": "クエリ",
    "importerName": "インポーター",
    "show": "表示",
    "hide": "非表示",
    "naviCategory": "ナビゲーション カテゴリ",
    "isShow": "表示するかどうか",
    "isHidden": "非表示かどうか",
    "showText": "表示名",
    "interfaceConfig": "インターフェース ナビゲーションの設定",
    "moveUp": "上に移動",


    "select": {
        "create": "セレクタの作成",
        "search": "セレクタの検索",
        "searchText": "キーワードを入力",
        "noSelectNoticeText": "このデータアプリにはまだセレクタがありません。新しいセレクタを作成するにはここをクリックしてください。",
        "loaded": "セレクタの読み込み完了",
        "deleteProcessTitle": "セレクタの削除確認",
        "deleteProcess": "現在のセレクタを削除しますか？",
        "deletePageTemplateTitle": "セレクタテンプレートの削除確認",
        "deletePageTemplate": "現在のセレクタテンプレートを削除しますか？"
    },
    "view": {
        "create": "ビューの作成",
        "search": "ビューの検索",
        "searchText": "キーワードを入力",
        "noViewNoticeText": "このデータアプリにはまだビューがありません。新しいビューを作成するにはここをクリックしてください。",
        "loaded": "ビューの読み込み完了",
        "deleteProcessTitle": "ビューの削除確認",
        "deleteProcess": "現在のビューを削除しますか？",
        "deletePageTemplateTitle": "ビューテンプレートの削除確認",
        "deletePageTemplate": "現在のビューテンプレートを削除しますか？"
    },
    "stat": {
        "create": "統計の作成",
        "search": "統計の検索",
        "searchText": "キーワードを入力",
        "noStatNoticeText": "このデータアプリにはまだ統計がありません。新しい統計を作成するにはここをクリックしてください。",
        "loaded": "統計の読み込み完了",
        "deleteProcessTitle": "統計の削除確認",
        "deleteProcess": "現在の統計を削除しますか？",
        "deletePageTemplateTitle": "統計テンプレートの削除確認",
        "deletePageTemplate": "現在の統計テンプレートを削除しますか？"
    },
    "reveal": {
        "create": "リベールを作成",
        "search": "リベールを検索",
        "searchText": "キーワードを入力",
        "noRevealNoticeText": "このデータアプリにはまだリベールがありません。ここをクリックして新しいリベールを作成できます。",
        "loaded": "リベールの読み込み完了",
        "deleteProcessTitle": "リベールの削除確認",
        "deleteProcess": "現在のリベールを削除しますか？",
        "deletePageTemplateTitle": "リベールテンプレートの削除確認",
        "deletePageTemplate": "現在のリベールテンプレートを削除しますか？"
    },
    "table": {
        "create": "データテーブルを作成",
        "search": "データテーブルを検索",
        "searchText": "キーワードを入力",
        "noStatNoticeText": "このデータアプリにはまだデータテーブルがありません。ここをクリックして新しいデータテーブルを作成できます。",
        "loaded": "データテーブルの読み込み完了",
        "deleteProcessTitle": "データテーブルの削除確認",
        "deleteProcess": "現在のデータテーブルを削除しますか？",
        "deletePageTemplateTitle": "データテーブルテンプレートの削除確認",
        "deletePageTemplate": "現在のデータテーブルテンプレートを削除しますか？"
    },
    "statement": {
        "create": "クエリ設定を作成",
        "search": "クエリ設定を検索",
        "searchText": "キーワードを入力",
        "noStatNoticeText": "このデータアプリにはまだクエリ設定がありません。ここをクリックして新しいクエリ設定を作成できます。",
        "loaded": "データテーブルの読み込み完了",
        "deleteProcessTitle": "クエリ設定の削除確認",
        "deleteProcess": "現在のクエリ設定を削除しますか？",
        "deletePageTemplateTitle": "クエリ設定テンプレートの削除確認",
        "deletePageTemplate": "現在のクエリ設定テンプレートを削除しますか？"
    },

    "application": {
        "inputApplicationName": "データアプリ名を入力してください",
        "property": "データアプリのプロパティ",
        "name": "データアプリ名",
        "alias": "データアプリの別名",
        "description": "データアプリの説明",
        "type": "データアプリの種類",
        "icon": "データアプリのアイコン",
        "id": "データアプリのID",
        "firstPage": "データアプリの最初のページ",
        "controllerList": "管理者リスト",
        "available": "利用可能な範囲",
        "changeIcon" : "アイコンの変更",
        "setManager" : "管理者の設定",
        "setAppManager" : "アプリの管理者の設定",
        "setUsableIdentity" : "利用可能なIDの設定",
        "setUsableUnit" : "利用可能なユニットの設定",
        "setAppUsableIdentity" : "アプリの利用可能なIDの設定",
        "setAppUsableUnit" : "アプリの利用可能なユニットの設定"
    },
    "importer": {
        "create": "インポートモデルの作成",
        "search": "インポートモデルの検索",
        "searchText": "キーワードを入力してください",
        "noSelectNoticeText": "このデータアプリにはまだインポートモデルがありません。ここをクリックしてインポートモデルを作成できます。",
        "loaded": "インポートモデルの読み込み完了",
        "deleteProcessTitle": "インポートモデルの削除確認",
        "deleteProcess": "現在のインポートモデルを削除しますか？",
        "deletePageTemplateTitle": "インポートモデルテンプレートの削除確認",
        "deletePageTemplate": "現在のインポートモデルテンプレートを削除しますか？"
    },
    "createSelectTemplate": "新規作成: 選択テンプレート",
    "templateCategory": "テンプレートのカテゴリ:",
    "all": "すべて",
    "selectorButton" : {
        "ok" : "確定",
        "cancel" : "キャンセル"
    },
    "navi":{
        "viewConfig":"ビューの設定",
        "statConfig":"統計の設定",
        "tableConfig":"データシート",
        "statementConfig":"クエリの設定",
        "importerConfig": "インポート",
        "queryProperty":"アプリの特性"
    }
};