MWF.xApplication.query.QueryManager.LP = {
	"title": "데이터 앱 관리",
    "categoryTitle": "데이터 앱 카테고리",
    "description": "설명",
    "deleteItems": "선택한 항목 삭제",
    "copy": "복사",
    "copyto": "복사 대상...",
    "copyInfor": "여러 요소를 선택하고 Ctrl+C를 누르면 요소를 복사하고 Ctrl+V를 누르면 복사한 요소를 현재 앱에 붙여넣습니다.",
    "copyed": "선택한 요소가 복사되었습니다",
    "copyConfirmTitle": "요소 복사 확인",
    "copyConfirmInfor": "대상 영역에 동일한 요소가 이미 포함되어 있습니다:",
    "copyConfirmInfor_server": "이 서버에 이미 동일한 요소가 포함되어 있습니다:",
    "copySource": "원본 파일:",
    "copyTarget": "복사 파일:",
    "copyConfirm_overwrite": "덮어쓰기",
    "copyConfirm_new": "새로 만들기",
    "copyConfirm_skip": "건너뛰기",
    "copyConfirm_cancel": "취소",
    "copynew": "새로 만들기",
    "edit": "편집",
    "save": "저장",
    "cancel": "취소",
    "phone": "휴대전화",
    "mail": "이메일",
    "deleteElementTitle": "디자인 삭제 확인",
    "deleteElement": "선택한 디자인 요소를 삭제하시겠습니까?",
    "viewName": "뷰",
    "statName": "통계",
    "statementName": "쿼리",
    "importerName": "가져오기",
    "show": "표시",
    "hide": "숨김",
    "naviCategory": "네비게이션 카테고리",
    "isShow": "표시 여부",
    "isHidden": "숨김 여부",
    "showText": "표시 이름",
    "interfaceConfig": "인터페이스 네비게이션 설정",
    "moveUp": "위로 이동",


    "select": {
        "create": "선택기 생성",
        "search": "선택기 검색",
        "searchText": "키워드를 입력하세요",
        "noSelectNoticeText": "이 데이터 앱에는 아직 선택기가 없습니다. 여기를 클릭하여 새 선택기를 만들 수 있습니다.",
        "loaded": "선택기 로드 완료",
        "deleteProcessTitle": "선택기 삭제 확인",
        "deleteProcess": "현재 선택기를 삭제하시겠습니까?",
        "deletePageTemplateTitle": "선택기 템플릿 삭제 확인",
        "deletePageTemplate": "현재 선택기 템플릿을 삭제하시겠습니까?"
    },
    "view": {
        "create": "뷰 생성",
        "search": "뷰 검색",
        "searchText": "키워드를 입력하세요",
        "noViewNoticeText": "이 데이터 앱에는 아직 뷰가 없습니다. 여기를 클릭하여 새 뷰를 만들 수 있습니다.",
        "loaded": "뷰 로드 완료",
        "deleteProcessTitle": "뷰 삭제 확인",
        "deleteProcess": "현재 뷰를 삭제하시겠습니까?",
        "deletePageTemplateTitle": "뷰 템플릿 삭제 확인",
        "deletePageTemplate": "현재 뷰 템플릿을 삭제하시겠습니까?"
    },
    "stat": {
        "create": "통계 생성",
        "search": "통계 검색",
        "searchText": "키워드를 입력하세요",
        "noStatNoticeText": "이 데이터 앱에는 아직 통계가 없습니다. 여기를 클릭하여 새 통계를 만들 수 있습니다.",
        "loaded": "통계 로드 완료",
        "deleteProcessTitle": "통계 삭제 확인",
        "deleteProcess": "현재 통계를 삭제하시겠습니까?",
        "deletePageTemplateTitle": "통계 템플릿 삭제 확인",
        "deletePageTemplate": "현재 통계 템플릿을 삭제하시겠습니까?"
    },
    "reveal": {
        "create": "표시기 생성",
        "search": "표시기 검색",
        "searchText": "키워드를 입력하세요",
        "noRevealNoticeText": "이 데이터 앱에는 아직 표시기가 없습니다. 여기를 클릭하여 새 표시기를 만들 수 있습니다.",
        "loaded": "표시기 로드 완료",
        "deleteProcessTitle": "표시기 삭제 확인",
        "deleteProcess": "현재 표시기를 삭제하시겠습니까?",
        "deletePageTemplateTitle": "표시기 템플릿 삭제 확인",
        "deletePageTemplate": "현재 표시기 템플릿을 삭제하시겠습니까?"
    },
    "table": {
        "create": "데이터 테이블 생성",
        "search": "데이터 테이블 검색",
        "searchText": "키워드를 입력하세요",
        "noStatNoticeText": "이 데이터 앱에는 아직 데이터 테이블이 없습니다. 여기를 클릭하여 새 데이터 테이블을 만들 수 있습니다.",
        "loaded": "데이터 테이블 로드 완료",
        "deleteProcessTitle": "데이터 테이블 삭제 확인",
        "deleteProcess": "현재 데이터 테이블을 삭제하시겠습니까?",
        "deletePageTemplateTitle": "데이터 테이블 템플릿 삭제 확인",
        "deletePageTemplate": "현재 데이터 테이블 템플릿을 삭제하시겠습니까?"
    },
    "statement": {
        "create": "쿼리 설정 생성",
        "search": "쿼리 설정 검색",
        "searchText": "키워드를 입력하세요",
        "noStatNoticeText": "이 데이터 앱에는 아직 쿼리 설정이 없습니다. 여기를 클릭하여 새 쿼리 설정을 만들 수 있습니다.",
        "loaded": "데이터 테이블 로드 완료",
        "deleteProcessTitle": "쿼리 설정 삭제 확인",
        "deleteProcess": "현재 쿼리 설정을 삭제하시겠습니까?",
        "deletePageTemplateTitle": "쿼리 설정 템플릿 삭제 확인",
        "deletePageTemplate": "현재 쿼리 설정 템플릿을 삭제하시겠습니까?"
    },

    "application": {
        "inputApplicationName": "데이터 앱 이름을 입력하세요",
        "property": "데이터 앱 속성",
        "name": "데이터 앱 이름",
        "alias": "데이터 앱 별칭",
        "description": "데이터 앱 설명",
        "type": "데이터 앱 유형",
        "icon": "데이터 앱 아이콘",
        "id": "데이터 앱 식별자",
        "firstPage": "데이터 앱 주요 페이지",
        "controllerList": "관리자",
        "available": "사용 가능 범위",
        "changeIcon" : "아이콘 변경",
        "setManager" : "관리자 설정",
        "setAppManager" : "앱 관리자 설정",
        "setUsableIdentity" : "사용 가능 ID 설정",
        "setUsableUnit" : "사용 가능 단위 설정",
        "setAppUsableIdentity" : "앱 사용 가능 ID 설정",
        "setAppUsableUnit" : "앱 사용 가능 단위 설정"
    },
    "importer": {
        "create": "데이터 모델 생성",
        "search": "데이터 모델 검색",
        "searchText": "키워드를 입력하세요",
        "noSelectNoticeText": "이 데이터 앱에는 아직 데이터 모델이 없습니다. 여기를 클릭하여 데이터 모델을 만들 수 있습니다.",
        "loaded": "데이터 모델 로드 완료",
        "deleteProcessTitle": "데이터 모델 삭제 확인",
        "deleteProcess": "현재 데이터 모델을 삭제하시겠습니까?",
        "deletePageTemplateTitle": "데이터 모델 템플릿 삭제 확인",
        "deletePageTemplate": "현재 데이터 모델 템플릿을 삭제하시겠습니까?"
    },
    "createSelectTemplate": "새로 만들기: 선택 템플릿",
    "templateCategory": "템플릿 분류:",
    "all": "모두",
    "selectorButton" : {
        "ok" : "확인",
        "cancel" : "취소"
    },
    "navi":{
        "viewConfig":"뷰 설정",
        "statConfig":"통계 설정",
        "tableConfig":"데이터 테이블",
        "statementConfig":"쿼리 설정",
        "importerConfig": "데이터 모델",
        "queryProperty":"응용 속성"
    }
};