MWF.xApplication.query.QueryManager.LP = {
	"title": "數據應用管理",
    "categoryTitle": "數據應用分類",
    "description": "描述",
    "deleteItems": "刪除選中的內容",
    "copy": "複製",
    "copyto": "複製到...",
    "copyInfor": "選擇多個元素，按Ctrl+C可複製元素，按下Ctrl+V可將複製的元素粘貼到當前應用",
    "copyed": "所選元素已複製",
    "copyConfirmTitle": "複製元素確認",
    "copyConfirmInfor": "目標區域已包含相同的元素：",
    "copyConfirmInfor_server": "本伺服器已包含相同的元素：",
    "copySource": "原文件:",
    "copyTarget": "複製文件:",
    "copyConfirm_overwrite": "替換",
    "copyConfirm_new": "新建",
    "copyConfirm_skip": "跳過",
    "copyConfirm_cancel": "取消",
    "copynew": "新",
    "edit": "編輯",
    "save": "保存",
    "cancel": "取消",
    "phone": "手機",
    "mail": "郵件",
    "deleteElementTitle": "刪除設計確認",
    "deleteElement": "是否確定要刪除選中的設計元素？",
    "viewName": "視圖",
    "statName": "統計",
    "statementName": "查詢",
    "importerName": "導入",
    "show": "顯示",
    "hide": "隱藏",
    "naviCategory": "導航分類",
    "isShow": "是否顯示",
    "isHidden": "是否隱藏",
    "showText": "顯示名稱",
    "interfaceConfig": "界面導航配置",
    "moveUp": "上移",


    "select": {
        "create": "新建選擇器",
        "search": "搜索選擇器",
        "searchText": "請輸入關鍵字",
        "noSelectNoticeText": "此數據應用現在還沒有選擇器，您可以點擊此處創建一個新選擇器",
        "loaded": "選擇器載入完成",
        "deleteProcessTitle": "刪除選擇器確認",
        "deleteProcess": "是否確定要刪除當前選擇器？",
        "deletePageTemplateTitle": "刪除選擇器模板確認",
        "deletePageTemplate": "是否確定要刪除當前選擇器模板？"
    },
    "view": {
        "create": "新建視圖",
        "search": "搜索視圖",
        "searchText": "請輸入關鍵字",
        "noViewNoticeText": "此數據應用現在還沒有視圖，您可以點擊此處創建一個新視圖",
        "loaded": "視圖載入完成",
        "deleteProcessTitle": "刪除視圖確認",
        "deleteProcess": "是否確定要刪除當前視圖？",
        "deletePageTemplateTitle": "刪除視圖模板確認",
        "deletePageTemplate": "是否確定要刪除當前視圖模板？"
    },
    "stat": {
        "create": "新建統計",
        "search": "搜索統計",
        "searchText": "請輸入關鍵字",
        "noStatNoticeText": "此數據應用現在還沒有統計，您可以點擊此處創建一個新統計",
        "loaded": "統計載入完成",
        "deleteProcessTitle": "刪除統計確認",
        "deleteProcess": "是否確定要刪除當前統計？",
        "deletePageTemplateTitle": "刪除統計模板確認",
        "deletePageTemplate": "是否確定要刪除當前統計模板？"
    },
    "reveal": {
        "create": "新建展示器",
        "search": "搜索展示器",
        "searchText": "請輸入關鍵字",
        "noRevealNoticeText": "此數據應用現在還沒有展示器，您可以點擊此處創建一個新展示器",
        "loaded": "展示器載入完成",
        "deleteProcessTitle": "刪除展示器確認",
        "deleteProcess": "是否確定要刪除當前展示器？",
        "deletePageTemplateTitle": "刪除展示器模板確認",
        "deletePageTemplate": "是否確定要刪除當前展示器模板？"
    },
    "table": {
        "create": "新建數據表",
        "search": "搜索數據表",
        "searchText": "請輸入關鍵字",
        "noStatNoticeText": "此數據應用現在還沒有數據表，您可以點擊此處創建一個新數據表",
        "loaded": "數據表載入完成",
        "deleteProcessTitle": "刪除數據表確認",
        "deleteProcess": "是否確定要刪除當前數據表？",
        "deletePageTemplateTitle": "刪除數據表模板確認",
        "deletePageTemplate": "是否確定要刪除當前數據表模板？"
    },
    "statement": {
        "create": "新建查詢配置",
        "search": "搜索查詢配置",
        "searchText": "請輸入關鍵字",
        "noStatNoticeText": "此數據應用現在還沒有查詢配置，您可以點擊此處創建一個新查詢配置",
        "loaded": "數據表載入完成",
        "deleteProcessTitle": "刪除查詢配置確認",
        "deleteProcess": "是否確定要刪除當前查詢配置？",
        "deletePageTemplateTitle": "刪除查詢配置模板確認",
        "deletePageTemplate": "是否確定要刪除當前查詢配置模板？"
    },

    "application": {
        "inputApplicationName": "請輸入數據應用名稱",
        "property": "數據應用屬性",
        "name": "數據應用名稱",
        "alias": "數據應用別名",
        "description": "數據應用描述",
        "type": "數據應用類型",
        "icon": "數據應用圖標",
        "id": "數據應用標識",
        "firstPage": "數據應用主頁",
        "controllerList": "管理者",
        "available": "可用範圍",
        "changeIcon" : "更改圖標",
        "setManager" : "設置管理者",
        "setAppManager" : "設置應用管理者",
        "setUsableIdentity" : "設置可用身份",
        "setUsableUnit" : "設置可用組織",
        "setAppUsableIdentity" : "設置應用可用身份",
        "setAppUsableUnit" : "設置應用可用組織"
    },
    "importer": {
        "create": "新建導入模型",
        "search": "搜索導入模型",
        "searchText": "請輸入關鍵字",
        "noSelectNoticeText": "此數據應用現在還沒有導入模型，您可以點擊此處創建一個導入模型",
        "loaded": "導入模型載入完成",
        "deleteProcessTitle": "刪除導入模型確認",
        "deleteProcess": "是否確定要刪除當前導入模型？",
        "deletePageTemplateTitle": "刪除導入模型模板確認",
        "deletePageTemplate": "是否確定要刪除當前導入模型模板？"
    },
    "createSelectTemplate": "新建：選擇模板",
    "templateCategory": "模板分類：",
    "all": "全部",
    "selectorButton" : {
        "ok" : "確　定",
        "cancel" : "取 消"
    },
    "navi":{
        "viewConfig":"視圖配置",
        "statConfig":"統計配置",
        "tableConfig":"數據表",
        "statementConfig":"查詢配置",
        "importerConfig": "導入模型",
        "queryProperty":"數據應用屬性"
    }
};