MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.ANN = MWF.xApplication.ANN || {};
MWF.xApplication.ANN.LP={
	"title": "Red neuronal",
	"unnamed": "Sin nombre",
	"create": "Crear modelo de red neuronal",
	"checkSave": "¡Guarde o cierre el modelo abierto actual antes de continuar!",
	"status": {
		"idle": "No hay tarea en ejecución actualmente",
		"generating": "Recopilando conjunto de entrenamiento",
		"learning": "Ejecutando aprendizaje de red neuronal",
		"completed": "Tarea de aprendizaje completada",
		"excessive": "El resultado del entrenamiento tiene un sesgo excesivo"
	},
	"name": "Nombre",
	"description": "Descripción",
	"alias": "Alias",
	"processList": "Lista de procesos",
	"applicationList": "Lista de aplicaciones",
	"inValueScriptText": "Procesamiento de entrada del conjunto de entrenamiento",
	"outValueScriptText": "Procesamiento de salida del conjunto de entrenamiento",
	"attachmentScriptText": "Procesamiento de archivos adjuntos",
	"analyzeType": "Tipo de análisis",
	"propertyMap": "Parámetros de la red neuronal",
	"placeholder": {
		"name": "Ingrese el nombre del modelo de entrenamiento",
		"description": "Ingrese la descripción del modelo de entrenamiento",
		"alias": "Ingrese el alias del modelo de entrenamiento"
	},
	"selectProcess": "Seleccionar proceso",
	"selectApplication": "Seleccionar aplicación",
	"closeTitle": "Confirmación",
	"closeInfor": "¡El contenido no guardado se perderá! ¿Está seguro de que desea continuar?",
	"saveSuccess": "Guardado exitoso",
	"generate": "Recopilando conjunto de entrenamiento",
	"learn": "Ejecutando aprendizaje de red neuronal",
	"stopGenerate": "Se ha enviado una orden para detener la recopilación del conjunto de entrenamiento",
	"stopLearn": "Se ha enviado una orden para detener el aprendizaje de la red neuronal",
	"resetStatus": "Se ha enviado una orden para restablecer el estado del modelo",
	"deleteModel": "Se ha eliminado el modelo \"{name}\"",
	"stopGenerateTitle": "Confirmación",
	"stopGenerateInfor": "¿Está seguro de que desea detener la recopilación del conjunto de entrenamiento?",
	"stopLearningTitle": "Confirmación",
	"stopLearningInfor": "¿Está seguro de que desea detener el aprendizaje de la red neuronal?",
	"resetStatusTitle": "Confirmación",
	"resetStatusInfor": "¿Está seguro de que desea restablecer el estado del modelo?",
	"removeTitle": "Confirmación",
	"removeInfor": "¿Está seguro de que desea eliminar el modelo actual?",
	"startDate": "Hora de inicio",
	"endDate": "Hora de finalización",
	"entryCount": "Número de entradas",
	"effectiveEntryCount": "Número efectivo de entradas",
	"statusText": "Estado",
	"generatingPercent": "Progreso de generación de entradas actuales",
	"learnEntryCount": "Número de entradas de aprendizaje",
	"validationEntryCount": "Número de entradas de prueba"
}
MWF.xApplication.ANN["lp."+o2.language] = MWF.xApplication.ANN.LP