MWF.xApplication.ANN.LP = {
	"title": "ニューラルネットワークモデル",
	"unnamed": "無名",
	"create": "ニューラルネットワークモデルを作成",
	"checkSave": "現在開いているモデルを保存または閉じてください！",
	"status": {
		"idle": "現在実行中のタスクはありません",
		"generating": "トレーニングデータの収集中",
		"learning": "ニューラルネットワーク学習実行中",
		"completed": "学習タスクが完了しました",
		"excessive": "トレーニング結果が過度に偏っています"
	},
	"name": "名前",
	"description": "説明",
	"alias": "エイリアス",
	"processList": "プロセスリスト",
	"applicationList": "アプリケーションリスト",
	"inValueScriptText": "トレーニングデータの入力処理",
	"outValueScriptText": "トレーニングデータの出力処理",
	"attachmentScriptText": "添付ファイル処理",
	"analyzeType": "分析タイプ",
	"propertyMap": "ニューラルネットワークパラメータ",
	"placeholder": {
		"name": "トレーニングモデルの名前を入力してください",
		"description": "トレーニングモデルの説明を入力してください",
		"alias": "トレーニングモデルのエイリアスを入力してください"
	},

	"selectProcess": "プロセス選択",
	"selectApplication": "アプリケーション選択",
	"closeTitle": "閉じる確認",
	"closeInfor": "保存されていない内容は失われます。この操作を実行しますか？",
	"saveSuccess": "保存成功",
	"generate": "トレーニングデータ収集中",
	"learn": "ニューラルネットワーク学習中",
	"stopGenerate": "トレーニングデータ収集停止コマンドが送信されました",
	"stopLearn": "ニューラルネットワーク学習停止コマンドが送信されました",
	"resetStatus": "ステータスリセットコマンドが送信されました",
	"deleteModel": "モデル“{name}”が削除されました",
	"stopGenerateTitle": "トレーニングデータ収集停止確認",
	"stopGenerateInfor": "トレーニングデータ収集を停止しますか？",
	"stopLearningTitle": "学習停止確認",
	"stopLearningInfor": "ニューラルネットワーク学習を停止しますか？",
	"resetStatusTitle": "ステータスリセット確認",
	"resetStatusInfor": "モデルのステータスをリセットしますか？",
	"removeTitle": "モデル削除確認",
	"removeInfor": "現在のモデルを削除しますか？",
	"startDate": "開始時間",
	"endDate": "完了時間",
	"entryCount": "エントリ数",
	"effectiveEntryCount": "有効なエントリ数",
	"statusText": "ステータス",
	"generatingPercent": "現在のエントリ生成進捗",
	"learnEntryCount": "学習エントリ数",
	"validationEntryCount": "テストエントリ数"
};