MWF.xApplication.ANN.LP = {
	"title": "신경망 모델",
	"unnamed": "이름 없음",
	"create": "신경망 모델 생성",
	"checkSave": "현재 열려 있는 모델을 먼저 저장하거나 닫으십시오!",
	"status": {
		"idle": "현재 실행 중인 작업이 없습니다",
		"generating": "학습 데이터 수집 중",
		"learning": "신경망 학습 실행 중",
		"completed": "학습 작업이 완료되었습니다",
		"excessive": "학습 결과가 과도하게 편향됨"
	},
	"name": "이름",
	"description": "설명",
	"alias": "별칭",
	"processList": "프로세스 목록",
	"applicationList": "응용 프로그램 목록",
	"inValueScriptText": "학습 데이터 입력 처리",
	"outValueScriptText": "학습 데이터 출력 처리",
	"attachmentScriptText": "첨부 파일 처리",
	"analyzeType": "분석 유형",
	"propertyMap": "신경망 매개 변수",
	"placeholder": {
		"name": "학습 모델 이름을 입력하세요",
		"description": "학습 모델 설명을 입력하세요",
		"alias": "학습 모델 별칭을 입력하세요"
	},

	"selectProcess": "프로세스 선택",
	"selectApplication": "애플리케이션 선택",
	"closeTitle": "닫기 확인",
	"closeInfor": "저장되지 않은 내용이 손실됩니다. 이 작업을 실행하시겠습니까?",
	"saveSuccess": "저장 성공",
	"generate": "학습 데이터 수집 중",
	"learn": "신경망 학습 실행 중",
	"stopGenerate": "학습 데이터 수집 중지 명령이 전송되었습니다",
	"stopLearn": "신경망 학습 중지 명령이 전송되었습니다",
	"resetStatus": "상태 재설정 명령이 전송되었습니다",
	"deleteModel": "모델 “{name}” 삭제됨",
	"stopGenerateTitle": "학습 데이터 수집 중지 확인",
	"stopGenerateInfor": "학습 데이터 수집을 중지하시겠습니까?",
	"stopLearningTitle": "신경망 학습 중지 확인",
	"stopLearningInfor": "신경망 학습을 중지하시겠습니까?",
	"resetStatusTitle": "상태 재설정 확인",
	"resetStatusInfor": "모델 상태를 재설정하시겠습니까?",
	"removeTitle": "모델 삭제 확인",
	"removeInfor": "현재 모델을 삭제하시겠습니까?",
	"startDate": "시작 시간",
	"endDate": "종료 시간",
	"entryCount": "항목 수",
	"effectiveEntryCount": "유효한 항목 수",
	"statusText": "상태",
	"generatingPercent": "현재 항목 생성 진행률",
	"learnEntryCount": "학습 항목 수",
	"validationEntryCount": "검증 항목 수"
};