MWF.xApplication.ANN.LP = {
	"title": "神經網絡模型",
	"unnamed": "未命名",
	"create": "建立神經網絡模型",
	"checkSave": "請先保存或關閉當前打開的模型！",
	"status": {
		"idle": "當前沒有運行任務",
		"generating": "正在收集訓練集",
		"learning": "正在運行神經網絡學習",
		"completed": "學習任務已完成",
		"excessive": "訓練結果偏差過大"
	},
	"name": "名稱",
	"description": "描述",
	"alias": "別名",
	"processList": "流程列表",
	"applicationList": "應用程序列表",
	"inValueScriptText": "訓練集輸入處理",
	"outValueScriptText": "訓練集輸出處理",
	"attachmentScriptText": "附件處理",
	"analyzeType": "分析類型",
	"propertyMap": "神經網絡參數",
	"placeholder": {
		"name": "請輸入訓練模型名稱",
		"description": "請輸入訓練模型描述",
		"alias": "請輸入訓練模型別名"
	},

	"selectProcess": "選擇流程",
	"selectApplication": "選擇應用",
	"closeTitle": "關閉確認",
	"closeInfor": "未保存的內容將會遺失，確定要執行此操作嗎？",
	"saveSuccess": "保存成功",
	"generate": "正在收集訓練集",
	"learn": "正在運行神經網絡學習",
	"stopGenerate": "已發出停止收集訓練集指令",
	"stopLearn": "已發出停止神經網絡學習指令",
	"resetStatus": "已發出重置狀態指令",
	"deleteModel": "模型“{name}”已刪除",
	"stopGenerateTitle": "停止收集訓練集確認",
	"stopGenerateInfor": "您確定要停止收集訓練集嗎？",
	"stopLearningTitle": "停止學習確認",
	"stopLearningInfor": "您確定要停止神經網絡學習嗎？",
	"resetStatusTitle": "重置狀態確認",
	"resetStatusInfor": "您確定要重置模型狀態嗎？",
	"removeTitle": "刪除模型確認",
	"removeInfor": "您確定要刪除當前模型嗎？",
	"startDate": "開始時間",
	"endDate": "完成時間",
	"entryCount": "項目數",
	"effectiveEntryCount": "有效項目數",
	"statusText": "狀態",
	"generatingPercent": "當前項目生成進度",
	"learnEntryCount": "學習項目數",
	"validationEntryCount": "測試項目數"
};