MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Collect = MWF.xApplication.Collect || {};
MWF.xApplication.Collect.LP={
	"title": "Configuración de la nube O2",
	"collectConnected": "¡Ya puede conectarse a la nube O2!",
	"collectDisconnect": "¡Su servidor no puede conectarse a la nube O2!",
	"checking": "Comprobando...",
	"collectLogin": "¡Ha iniciado sesión en la nube O2!",
	"collectNotLogin": "¡No ha iniciado sesión en la nube O2!",
	"recheck": "Volver a comprobar la conexión",
	"doDisconnect": "Desconectar",
	"modifyAccountAction": "Modificar cuenta",
	"modifyPwdAccountAction": "Modificar contraseña",
	"deleteAccountAction": "Eliminar cuenta",
	"login": "Iniciar sesión en la nube O2",
	"logining": "Iniciando sesión...",
	"register": "Registrar una cuenta de la nube O2",
	"registering": "Registrando...",
	"forget": "¿Olvidó su contraseña?",
	"connectedAndLogin": "<span style='color: #ff0000'>¡Felicidades!</span> Ha iniciado sesión en la nube O2 y ahora puede usar todas las funciones de la plataforma O2, incluyendo el trabajo móvil.",
	"modifyAccount": "",
	"loginAccount": "",
	"disconnect": "Su servidor no puede conectarse a la nube O2. Por favor, compruebe la red de su servidor.",
	"disconnectInfo": "La plataforma O2 requiere que su servidor de centro O2 pueda acceder a la nube O2 para utilizar todas las funciones geniales, lo que significa que su servidor debe tener acceso a Internet. Sin embargo, esto no es obligatorio. Puede utilizar la plataforma O2 en un entorno de red privada cerrada, pero no podrá utilizar funciones como trabajo móvil y servicios de mensajería.",
	"notLogin": "Inicie sesión en la nube O2 para poder utilizar todas las funciones geniales, incluyendo el trabajo móvil.",
	"notLoginInfoLogin": "Si ya tiene una cuenta de la nube O2, haga clic aquí para iniciar sesión:",
	"notLoginInfoRegister": "Si no tiene una cuenta de la nube O2, haga clic aquí para registrarse:",
	"username": "Nombre de cuenta",
	"password": "Contraseña",
	"mobile": "Número de teléfono móvil",
	"mail": "Correo electrónico",
	"code": "Código de verificación",
	"secret": "Clave secreta de mensajes push",
	"key": "Clave de mensajes push",
	"back": "Volver",
	"backUp": "Volver",
	"errorUsername": "Por favor, introduzca el nombre de cuenta",
	"errorKey": "Por favor, introduzca la clave de mensajes push",
	"errorSecret": "Por favor, introduzca la clave secreta de mensajes push",
	"errorPassword": "Por favor, introduzca la contraseña",
	"errorPasswordRule": "La contraseña es demasiado simple. Debe tener al menos 8 caracteres y combinar números y letras.",
	"errorMobile": "El número de teléfono móvil es incorrecto",
	"errorMail": "El correo electrónico es incorrecto",
	"errorCode": "El código de verificación es incorrecto",
	"loginError": "No se pudo iniciar sesión en la nube O2. Por favor, compruebe el nombre de cuenta y la contraseña.",
	"getCodeAtion": "Obtener código de verificación",
	"getCodeNext": "Obtener nuevamente",
	"modifyNextStep": "Siguiente paso",
	"nextStepWait": "Verificando...",
	"modifyPassword": "Modificar contraseña",
	"modifyUnit": "Confirmar modificación",
	"confirmDelete": "Confirmar eliminación",
	"usernameExisted": "El nombre de cuenta ya existe",
	"requestError": "Se produjo un error en la solicitud del servidor."
}
MWF.xApplication.Collect["lp."+o2.language] = MWF.xApplication.Collect.LP