MWF.xApplication.Collect.LP = {
    "title": "O2 클라우드 설정",
	"collectConnected": "이제 O2 클라우드에 연결할 수 있습니다!",
	"collectDisconnect": "귀하의 서버는 O2 클라우드에 연결할 수 없습니다!",
	"checking": "확인 중...",
	"collectLogin": "이미 O2 클라우드에 로그인되었습니다!",
	"collectNotLogin": "아직 O2 클라우드에 로그인되지 않았습니다!",
	"recheck": "연결 재확인",
	"doDisconnect": "연결 끊기",
	"modifyAccountAction": "계정 수정",
	"modifyPwdAccountAction": "비밀번호 수정",
	"deleteAccountAction": "계정 삭제",
	"login": "O2 클라우드 로그인",
	"logining": "로그인 중...",
	"register": "O2 클라우드 계정 등록",
	"registering": "등록 중...",
	"forget": "비밀번호 잊어버렸나요?",
	"connectedAndLogin": "<span style='color: #ff0000'>축하합니다!</span> O2 클라우드에 로그인되었으며 모바일 오피스를 비롯한 모든 O2 플랫폼 기능을 사용할 수 있습니다!",
	"modifyAccount": "",
	"loginAccount": "",
	"disconnect": "귀하의 서버는 O2 클라우드에 연결할 수 없습니다. 서버 네트워크 환경을 확인하십시오.",
	"disconnectInfo": "O2 플랫폼은 O2 센터 서버가 O2 클라우드에 액세스할 수 있는 경우에만 모든 기능을 사용할 수 있습니다. 이것은 귀하의 서버가 인터넷에 액세스할 수 있어야 한다는 것을 의미합니다. 그러나 이것은 강제 조치가 아닙니다. 귀하의 사설 네트워크 환경에서도 O2 플랫폼을 사용할 수 있지만 모바일 오피스, SMS 서비스 등의 기능을 사용할 수 없습니다.",
	"notLogin": "O2 클라우드에 로그인하면 모바일 오피스를 비롯한 모든 멋진 기능을 사용할 수 있습니다!",
	"notLoginInfoLogin": "이미 O2 클라우드 계정을 보유하고 있다면 여기를 클릭하여 로그인하세요:",
	"notLoginInfoRegister": "아직 O2 클라우드 계정이 없다면 여기를 클릭하여 등록하세요:",

    "username": "계정 이름",
	"password": "비밀번호",
	"mobile": "휴대전화 번호",
	"mail": "이메일",
	"code": "인증 코드",
	"secret": "푸시 메시지 비밀 키",
	"key": "푸시 메시지 키",
	"back": "뒤로",
	"backUp": "이전 단계로 돌아가기",
	"errorUsername": "계정 이름을 입력하세요",
	"errorKey": "푸시 메시지 키를 입력하세요",
	"errorSecret": "푸시 메시지 비밀 키를 입력하세요",
	"errorPassword": "비밀번호를 입력하세요",
	"errorPasswordRule": "비밀번호가 너무 간단합니다. 최소 8자의 숫자와 문자 조합이 필요합니다",
	"errorMobile": "휴대전화 번호 입력이 잘못되었습니다",
	"errorMail": "이메일 입력이 잘못되었습니다",
	"errorCode": "인증 코드 입력이 잘못되었습니다",
	"loginError": "O2 클라우드 로그인에 실패했습니다. 계정 이름과 비밀번호를 확인하세요",
	"getCodeAtion": "인증 코드 가져오기",
	"getCodeNext": "다시 가져오기",
	"modifyNextStep": "다음 단계",
	"nextStepWait": "확인 중...",
	"modifyPassword": "비밀번호 수정",
	"modifyUnit": "수정 확인",
	"confirmDelete": "삭제 확인",
	"usernameExisted": "계정 이름이 이미 존재합니다",
	"requestError": "서버 요청 중 오류가 발생했습니다"
}
