MWF.xDesktop.requireApp("process.FormDesigner", "Module.Package", null, false);

MWF.xApplication.portal.PageDesigner = MWF.xApplication.portal.PageDesigner || {};
MWF.xApplication.portal.PageDesigner.Module = MWF.xApplication.portal.PageDesigner.Module || {};
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Page", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Div", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Label", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Button", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Image", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Table", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.View", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Stat", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Html", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Common", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Tab", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Tree", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Iframe", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Textfield", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Personfield", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Org", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Calendar", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Textarea", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Select", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Radio", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Checkbox", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Source", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.SourceText", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.SubSource", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Widget", null, false);
MWF.xDesktop.requireApp("portal.PageDesigner", "Module.Widgetmodules", null, false);