/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.base.core.entity;


@javax.persistence.metamodel.StaticMetamodel
(value=com.x.base.core.entity.StorageObject.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon Dec 24 19:03:24 CST 2018")
public class StorageObject_ extends SliceJpaObject_  {
}
