MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.query = MWF.xApplication.query || {};
MWF.xApplication.query.StatDesigner = MWF.xApplication.query.StatDesigner || {};
MWF.xApplication.query.StatDesigner.LP={
	"title": "Edición de estadísticas",
	"newStat": "Nueva estadística",
	"property": "Propiedad",
	"item": "Elemento",
	"type": "Tipo",
	"value": "Valor",
	"stat": "Estadística",
	"unnamed": "Sin título",
	"unCategory": "Sin categoría",
	"id": "Identificación",
	"name": "Nombre",
	"alias": "Alias",
	"description": "Descripción",
	"application": "Aplicación de datos",
	"copyStat": "Copiar estadística",
	"newStatName": "Nuevo nombre de estadística",
	"copy": "Copia",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"view": "Vista",
	"saveViewNotice": "¡Guarde la estadística antes de agregar una vista!",
	"action": {
		"move": "Mover",
		"delete": "Eliminar",
		"add": "Agregar"
	},
	"notice": {
		"save_success": "¡Estadística guardada exitosamente!",
		"saveAs_success": "¡La estadística se ha guardado con éxito! Puede abrir la nueva estadística en la configuración de estadísticas.",
		"deleteFilterTitle": "Confirmar",
		"deleteFilter": "¿Está seguro de que desea eliminar la condición de filtro actual?",
		"deleteColumnTitle": "Confirmar",
		"deleteColumn": "¿Está seguro de que desea eliminar la columna actual?",
		"changeTypeTitle": "Confirmar",
		"changeTypeDeleteChildren": "Cambiar el tipo de datos eliminará todos los subdatos. ¿Está seguro de que desea continuar?",
		"changeType": "Cambiar el tipo de datos cambiará los valores de los datos. ¿Está seguro de que desea continuar?",
		"inputTypeError": "Ha ingresado un tipo de datos incorrecto. Por favor, vuelva a intentarlo",
		"sameKey": "El nombre del elemento que ha ingresado ya existe en el objeto. Por favor, ingrese otro nombre",
		"emptyKey": "El nombre del elemento no puede estar vacío. Por favor, ingrese un nuevo nombre",
		"numberKey": "El nombre del elemento no puede ser un número. Por favor, ingrese otro nombre",
		"inputName": "Por favor ingrese el nombre de la estadística",
		"noModifyName": "No puede modificar el nombre o alias",
		"inputView": "Por favor seleccione una vista primero",
		"errorViewColumn": "Error al seleccionar columnas de vista. Por favor, seleccione de nuevo"
	},
	"category": "Categoría",
	"amount": "Total",
	"propertyTemplate": {
		"base": "Básico",
		"event": "Evento",
		"html": "HTML",
		"json": "JSON",
		"action": "Acción",
		"select": "Seleccionar",
		"alias": "Alias",
		"id": "Identificación",
		"name": "Nombre",
		"description": "Descripción",
		"appearance": "Tipo de apariencia",
		"style": "Estilo",
		"attribute": "Atributo",
		"display": "Mostrar",
		"hidden": "Ocultar",
		"orderNumber": "Número de orden",
		"view": "Vista",
		"viewNote": "Se requiere una columna de categoría para la vista.",
		"column": "Columna de vista",
		"columnNote": "Seleccione una vista primero para el estadística.",
		"calculateType": "Tipo de cálculo",
		"sum": "Suma(sum)",
		"average": "Promedio(average)",
		"count": "Cantidad(count)",
		"formatType": "Formato",
		"number": "Número",
		"percent": "Porcentaje",
		"currency": "Moneda",
		"decimal": "Posiciones decimales",
		"defaultValue": "Valor por defecto",
		"code": "Script de visualización",
		"chart": "Gráfico",
		"bar": "Gráfico de barras",
		"pie": "Gráfico circular",
		"line": "Gráfico de líneas",
		"authority": "Permiso de ejecución",
		"availableIdentity": "Usuarios disponibles",
		"availableUnit": "Organizaciones disponibles",
		"category": "Categoría",
		"isGroup": "Estadística de categoría",
		"yes": "Sí",
		"no": "No",
		"categoryTitle": "Título de la categoría",
		"isAmount": "Total",
		"sort": "Ordenar",
		"none": "Ninguno",
		"asc": "Ascendente",
		"desc": "Descendente",
		"orderColumn": "Columna de ordenamiento",
		"categoryValue": "Valor de categoría",
		"categoryDisplay": "Visualización de categoría",
		"item": "Calcular según la columna de vista",
		"specified": "Calcular según los valores de categoría específicos",
		"intersection": "Intersección entre la columna de vista y los valores de categoría especificados",
		"sum1": "Unión entre la columna de vista y los valores de categoría especificados",
		"groupSpecifiedList": "Valores de categoría específicos",
		"conversion": "Conversión filas-columnas"
	},
	"formToolbar": {
		"save": "Guardar",
		"saveAs": "Guardar como",
		"autoSave": "Guardar automáticamente",
		"preview": "vista previa",
		"help": "ayuda"
	}
}
MWF.xApplication.query.StatDesigner["lp."+o2.language] = MWF.xApplication.query.StatDesigner.LP