/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.Bind.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:53 CST 2018")
public class Bind_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Bind,String> id;
    public static volatile SingularAttribute<Bind,String> meta;
    public static volatile SingularAttribute<Bind,String> name;
}
