MWF.xApplication.portal.PageDesigner = MWF.xApplication.portal.PageDesigner || {};
MWF.APPPOD = MWF.xApplication.portal.PageDesigner;
MWF.APPPOD.LP = {
    "title": "ページ編集",
    "newPage": "新しいページを作成",
    "property": "プロパティ",
    "tools": "ツール",
    "all": "すべて",
    "repetitionsId": "繰り返し要素の識別子",
    "notNullId": "要素の識別子は空白にできません",
    "history": "履歴",
    "componentTree": "コンポーネントツリー",
    "button": {
        "ok": "確認",
        "cancel": "キャンセル"
    },

    "notice": {
        "save_success": "フォーム保存成功！",
        "saveTemplate_success": "フォームテンプレート保存成功！",
        "saveTemplate_inputName": "テンプレートのタイトルを入力してください",
        "saveTemplate_inputCategory": "テンプレートのカテゴリを確認してください",
        "deleteElementTitle": "フォーム要素の削除確認",
        "deleteElement": "現在の要素およびその子要素を削除してもよろしいですか？",
        "deleteRowTitle": "行の削除確認",
        "deleteRow": "現在の行を削除すると、その行内のすべてのセルの内容が削除されます。選択した行を削除してもよろしいですか？",
        "deleteColTitle": "列の削除確認",
        "deleteCol": "現在の列を削除すると、その列内のすべてのセルの内容が削除されます。選択した列を削除してもよろしいですか？",
        "deleteEventTitle": "イベントの削除確認",
        "deleteEvent": "現在のイベントを削除してもよろしいですか？",
        "deleteActionTitle": "アクションの削除確認",
        "deleteAction": "現在のアクションを削除してもよろしいですか？",
        "deleteButtonTitle": "アクションの削除確認",
        "deleteButton": "現在のアクションボタンを削除してもよろしいですか？",
        "notUseModuleInMobile": "モバイルではこのモジュールはサポートされていません",
        "changeToSequenceTitle": "確認",
        "changeToSequence": "この操作はすでに追加されたモジュールを削除し、'シーケンス' 列に変更します。'シーケンス' 列に変更してもよろしいですか？",
        "selectPage": "ページを選択してください",
        "selectPortal": "ポータルを選択してください",
        "selectWidget": "ウィジェットを選択してください",
        "widgetNameEmpty": "ウィジェット名を入力してください",
        "widgetNameConflict": "ウィジェット名が競合しています",
        "widget_save_success": "ウィジェットの保存に成功しました"
    },

    "formAction": {
        "insertRow": "行の挿入",
        "insertCol": "列の挿入",
        "deleteRow": "行の削除",
        "deleteCol": "列の削除",
        "mergerCell": "セルの結合",
        "splitCell": "セルの分割",
        "move": "移動",
        "copy": "コピー",
        "delete": "削除",
        "add": "追加",
        "script": "スクリプト",
        "makeWidget": "ウィジェットに設定",
        "defaultWidgetName": "ウィジェット"
    },
    "actionbar": {
        "readhide": "表示の際に読み込みますか？",
        "edithide": "編集の際に表示しますか？",
        "hideCondition": "非表示条件を設定",
        "title": "タイトル",
        "img": "アイコン",
        "action": "アクション",
        "condition": "表示条件",
        "editScript": "アクションスクリプトを編集",
        "editCondition": "非表示条件を編集（trueを返すとアクションが非表示になります）"
    },
    "isSave": "保存中です。お待ちください...",
    "validation": {
        "validation": "バリデーション",
        "anytime": "いつでも",
        "decision": "選択の決定",
        "decisionName": "<決定名>",
        "value": "値",
        "length": "値の長さ",
        "valueInput": "<値>",
        "isnull": "空",
        "notnull": "空でない",
        "gt": "大なり",
        "lt": "小なり",
        "equal": "等しい",
        "neq": "等しくない",
        "contain": "含む",
        "notcontain": "含まない",
        "prompt": "プロンプト",
        "add": "追加",
        "modify": "修正",
        "when": "とき",
        "as": "として",
        "inputDecisionName": "決定名を入力してください",
        "inputValue": "値を入力してください",
        "inputPrompt": "プロンプト内容を入力してください",
        "delete_title": "バリデーションコンテンツの削除の確認",
        "delete_text": "このバリデーション項目を削除してもよろしいですか？"
    },
    "selectIcon": "アイコンを選択",
    "selectImage": "画像を選択",
    "dutyInputTitle": "職務パラメーターを追加",
    "dutyInput": "職務 \"{duty}\" にパラメーターを追加してください",
    "creatorCompany": "起案会社",
    "creatorDepartment": "起案部署",
    "currentCompany": "現在の会社",
    "currentDepartment": "現在の部署",
    "deleteDutyTitle": "職務削除の確認",
    "deleteDutyText": "職務 \"{duty}\" を削除してもよろしいですか？",
    "select": "選択",
    "empty": "クリア",

    "saveTemplate": "フォームテンプレートとして保存",
    "templateName": "テンプレート名",
    "templateCategory": "テンプレートカテゴリ",
    "templateDescription": "テンプレートの説明",
    "save": "保存",
    "cancel": "キャンセル",
    "newCategory": "新しいカテゴリ",
    "filter": {
        "and": "かつ",
        "or": "または",
        "equals": "等しい",
        "notEquals": "異なる",
        "greaterThan": "より大きい",
        "greaterThanOrEqualTo": "以上",
        "lessThan": "未満",
        "lessThanOrEqualTo": "以下",
        "like": "含む",
        "notLike": "含まない",
        "from": "から",
        "value": "値"
    },
    "mastInputPath": "データパスを入力してください",
    "mastInputTitle": "タイトルを入力してください",
    "delete_filterItem_title": "フィルタ条件の削除確認",
    "delete_filterItem": "現在のフィルタ条件を削除しますか？",
    "implodeError": "インポートするデータの形式が誤っています",
    "implodeEmpty": "インポートするデータを編集ボックスに入力してください",
    "implodeConfirmTitle": "インポート確認",
    "implodeConfirmText": "インポートしたデータは現在のページを消去し、元に戻すことはできません。インポートしますか？",

    "subpageNameConflictTitle": "サブページのフィールド名の競合",
    "subpageNameConflictInfor": "以下のサブページのフィールド名が既存のフォームと競合しています：\n{name}",
    "subpageConflictTitle": "サブページの挿入エラー",
    "subpageConflictInfor": "同じサブページを二度挿入することはできません",

    "subpageNestedTitle": "サブページの挿入エラー",
    "subpageNestedInfor": "相互に挿入できないサブページを挿入することはできません",
    "checkSubpageNestedError" : "選択したサブページに相互に挿入する状況が存在します。確認してください！",

    "checkSubpageTitle": "ページ保存の検証",
    "checkFormSaveError": "ページを保存できません、理由は次の通りです：<br>",
    "checkSubpagePcInfor": "PCページには以下のサブフィールドの競合があります：<br>{subform}<br>",
    "checkSubpageMobileInfor": "モバイルページには以下のサブフィールドの競合があります：<br>{subform}",


    "design": "設計",
    "script": "コード",
    "html": "HTML",
    "css": "CSS",
    "byModule": "要素",
    "byPath": "タイプ",
    "events": "イベント",
    "importO2": "O2データからインポート",
    "importHTML": "HTMLからインポート",
    "importOffice": "WORDまたはEXCELからインポート",
    "importO2_infor": "O2フォーマットのフォームデータを以下のエディタにコピーしてください。 （フォームまたはページデザイナーツールバーの「エクスポート」ボタンを使用してフォームデータを取得できます）<br/> Ctrl + Alt + Iを押してデータをフォーマットできます",
    "importHTML_infor": "HTMLデータを以下のエディタにコピーしてください。 Ctrl + Alt + Iを押すとデータがフォーマットされます",
    "importHTML_infor2": "CSSデータを以下のエディタにコピーしてください。 Ctrl + Alt + Iを押すとデータがフォーマットされます",
    "importOffice_infor": "WordまたはExcelファイルを選択してください。",
    "import_ok": "インポート",
    "import_cancel": "キャンセル",
    "import_option1": "空のセルに入力フィールドを追加",
    "import_option2": "空の要素を削除",
    "implodeOfficeEmpty": "インポートするWordまたはExcelファイルを選択してください",
    "applicationNotFound": "アプリケーションが見つかりません",

    "scriptTitle": {
        "validationOpinion": "フォームの意見の検証",
        "validationRoute": "フォームのルートの検証",
        "validationFormCustom": "フォームの検証",
        "defaultValue": "デフォルト値",
        "validation": "検証スクリプト",
        "sectionByScript": "スクリプトによるセクション",
        "itemScript": "選択可能な値のスクリプト",
        "iframeScript": "iframeスクリプト",
        "labelScript": "テキスト値",
        "rangeKey": "組織範囲",
        "identityRangeKey": "アイデンティティ組織範囲",
        "unitRangeKey": "組織選択範囲",
        "rangeDutyKey": "職務範囲",
        "exclude": "選択を除外するスクリプト",
        "cookies": "データソースリクエストのクッキー",
        "requestBody": "データソースリクエストボディ",
        "jsonText": "データテキスト",
        "dataScript": "ツリーコントロールスクリプト",
        "itemDynamic": "ダイナミックオプションのスクリプト",
        "defaultData": "データグリッドのデフォルト値",
        "editableScript": "データグリッドの編集可能性",
        "config": "HTMLエディットボックスの設定",
        "filterScript": "プロセスレコードのフィルタリング",
        "readScript": "Officeの読み取り専用スクリプト",
        "fileSite": "Officeファイルサイトスクリプト",
        "subformScript": "サブフォームスクリプト",
        "selectedScript": "ビュー選択スクリプト",
        "action.tools": "アクションボタン"
    },
    "selectorButton": {
        "ok": "確 定",
        "cancel": "キャンセル"
    },
    "modules": {
        "label": "テキスト",
        "textfield": "テキスト",
        "number": "数値フィールド",
        "org": "人員と組織",
        "calendar": "日付選択",
        "textarea": "複数行テキスト",
        "select": "ドロップダウン",
        "radio": "ラジオボタン",
        "checkbox": "チェックボックス",
        "combox": "コンボボックス",
        "opinion": "意見ボックス",
        "button": "ボタン",
        "Address": "住所",
        "Actionbar": "アクションバー",
        "Sidebar": "サイドバーアクションバー",
        "image": "画像",
        "imageclipper": "画像エディタ",
        "attachment": "添付ファイル",
        "div": "コンテナ",
        "table": "テーブル",
        "datatable": "データテーブル",
        "datatemplate": "テンプレート",
        "subform": "サブフォーム",
        "ViewSelector": "ビュー選択",
        "view": "ビュー埋め込み",
        "stat": "埋め込み統計",
        "html": "HTML",
        "common": "一般要素",
        "tab": "タブ",
        "tree": "ツリー",
        "log": "ワークフロー履歴",
        "monitor": "ワークフローモニタリング",
        "iframe": "Iframe",
        "documenteditor": "文書エディタ",
        "htmledit": "HTMLエディタ",
        "office": "Officeコントロール",
        "statementSelector": "クエリビュー選択",
        "statement": "조회 뷰",
        "source": "データソース",
        "subSource": "サブデータソース",
        "sourceText": "データテキスト",
        "widget": "ウィジェット",
        "widgetmodules": "ウィジェット要素",
        "address": "住所",
        "importer": "データインポート",
        "SmartBI": "SmartBIレポート",
        "application": "自社アプリ",

        "group_all": "すべて",
        "group_form": "フォーム",
        "group_layout": "レイアウト",
        "group_data": "データ",
        "group_filetext": "ファイル編集",
        "group_function": "機能",
        "group_element": "Element"
    },
    "filedConfigurator": {
        "sequence": "シーケンス",
        "fieldTitle": "フィールドタイトル",
        "fieldId": "フィールドID",
        "action": "操作",
        "moveup": "上に移動",
        "deleteRow": "行を削除",
        "insertRow": "行を挿入",
        "importFromForm": "画面からフィールド設定をインポート"
    }
};
