MWF.xApplication.portal.PageDesigner = MWF.xApplication.portal.PageDesigner || {};
MWF.APPPOD = MWF.xApplication.portal.PageDesigner;
MWF.APPPOD.LP = {
    "title": "페이지 편집",
    "newPage": "새 페이지 생성",
    "property": "속성",
    "tools": "도구",
    "all": "모두",
    "repetitionsId": "반복 요소 식별자",
    "notNullId": "요소 식별자를 비워 둘 수 없습니다",
    "history": "기록",
    "componentTree": "구성 요소 트리",
    "button": {
        "ok": "확인",
        "cancel": "취소"
    },

    "notice": {
        "save_success": "양식 저장 성공!",
        "saveTemplate_success": "양식 템플릿 저장 성공!",
        "saveTemplate_inputName": "템플릿 제목을 입력하십시오",
        "saveTemplate_inputCategory": "템플릿 범주를 확인하십시오",
        "deleteElementTitle": "양식 요소 삭제 확인",
        "deleteElement": "현재 요소 및 하위 요소를 삭제하시겠습니까?",
        "deleteRowTitle": "행 삭제 확인",
        "deleteRow": "현재 행을 삭제하면 해당 행의 모든 셀 내용이 삭제됩니다. 선택한 행을 삭제하시겠습니까?",
        "deleteColTitle": "열 삭제 확인",
        "deleteCol": "현재 열을 삭제하면 해당 열의 모든 셀 내용이 삭제됩니다. 선택한 열을 삭제하시겠습니까?",
        "deleteEventTitle": "이벤트 삭제 확인",
        "deleteEvent": "현재 이벤트를 삭제하시겠습니까?",
        "deleteActionTitle": "조치 삭제 확인",
        "deleteAction": "현재 조치를 삭제하시겠습니까?",
        "deleteButtonTitle": "버튼 삭제 확인",
        "deleteButton": "현재 작업 버튼을 삭제하시겠습니까?",
        "notUseModuleInMobile": "모바일에서는이 구성 요소를 사용할 수 없습니다",
        "changeToSequenceTitle": "확인",
        "changeToSequence": "이 작업은 이미 추가된 구성 요소를 제거하며 '일련 번호' 열로 변경합니다. '일련 번호' 열로 변경하시겠습니까?",
        "selectPage": "페이지를 선택하십시오",
        "selectPortal": "포털을 선택하십시오",
        "selectWidget": "위젯을 선택하십시오",
        "widgetNameEmpty": "위젯 이름을 입력하십시오",
        "widgetNameConflict": "위젯 이름이 충돌합니다",
        "widget_save_success": "위젯 저장 성공"
    },

    "formAction": {
        "insertRow": "행 삽입",
        "insertCol": "열 삽입",
        "deleteRow": "행 삭제",
        "deleteCol": "열 삭제",
        "mergerCell": "셀 병합",
        "splitCell": "셀 분할",
        "move": "이동",
        "copy": "복사",
        "delete": "삭제",
        "add": "추가",
        "script": "스크립트",
        "makeWidget": "위젯으로 설정",
        "defaultWidgetName": "위젯"
    },
    "actionbar": {
        "readhide": "읽기 시 표시 여부 설정",
        "edithide": "편집 시 표시 여부 설정",
        "hideCondition": "숨김 조건 설정",
        "title": "제목",
        "img": "아이콘",
        "action": "동작",
        "condition": "표시 조건",
        "editScript": "동작 스크립트 편집",
        "editCondition": "숨김 조건 편집 (true를 반환하면 동작 숨김)"
    },
    "isSave": "저장 중입니다. 잠시 기다려주세요...",
    "validation": {
        "validation": "검증",
        "anytime": "언제나",
        "decision": "결정 선택",
        "decisionName": "<결정 이름>",
        "value": "값",
        "length": "값 길이",
        "valueInput": "<값>",
        "isnull": "비어 있음",
        "notnull": "비어 있지 않음",
        "gt": "크다",
        "lt": "작다",
        "equal": "같음",
        "neq": "같지 않음",
        "contain": "포함",
        "notcontain": "포함하지 않음",
        "prompt": "프롬프트",
        "add": "추가",
        "modify": "수정",
        "when": "때",
        "as": "으로",
        "inputDecisionName": "결정 이름을 입력하세요",
        "inputValue": "값을 입력하세요",
        "inputPrompt": "프롬프트 내용을 입력하세요",
        "delete_title": "검증 내용 삭제 확인",
        "delete_text": "이 검증 항목을 삭제하시겠습니까?"
    },
    "selectIcon": "아이콘 선택",
    "selectImage": "이미지 선택",
    "dutyInputTitle": "직책 매개 변수 추가",
    "dutyInput": "직책 \"{duty}\"에 매개 변수를 추가하십시오.",
    "creatorCompany": "기업 제작자",
    "creatorDepartment": "부서 제작자",
    "currentCompany": "현재 기업",
    "currentDepartment": "현재 부서",
    "deleteDutyTitle": "직책 제거 확인",
    "deleteDutyText": "직책 \"{duty}\"를 제거하시겠습니까?",
    "select": "선택",
    "empty": "지우기",

    "saveTemplate": "양식 템플릿으로 저장",
    "templateName": "템플릿 이름",
    "templateCategory": "템플릿 범주",
    "templateDescription": "템플릿 설명",
    "save": "저장",
    "cancel": "취소",
    "newCategory": "새 범주",
    "filter": {
        "and": "그리고",
        "or": "또는",
        "equals": "같음",
        "notEquals": "다름",
        "greaterThan": "초과",
        "greaterThanOrEqualTo": "이상",
        "lessThan": "미만",
        "lessThanOrEqualTo": "이하",
        "like": "포함",
        "notLike": "포함하지 않음",
        "from": "에서",
        "value": "값"
    },
    "mastInputPath": "데이터 경로를 입력하십시오",
    "mastInputTitle": "제목을 입력하십시오",
    "delete_filterItem_title": "필터 조건 삭제 확인",
    "delete_filterItem": "현재 필터 조건을 삭제하시겠습니까?",
    "implodeError": "가져올 데이터 형식이 잘못되었습니다",
    "implodeEmpty": "가져올 데이터를 편집란에 입력하십시오",
    "implodeConfirmTitle": "가져오기 확인",
    "implodeConfirmText": "가져올 데이터는 현재 페이지를 지우고 취소할 수 없으며, 가져오시겠습니까?",

    "subpageNameConflictTitle": "하위 페이지 필드 이름 충돌",
    "subpageNameConflictInfor": "하위 페이지의 다음 필드 이름이 기존 양식과 충돌합니다:\n{name}",
    "subpageConflictTitle": "하위 페이지 삽입 오류",
    "subpageConflictInfor": "동일한 하위 페이지를 두 번 삽입할 수 없습니다",

    "subpageNestedTitle": "하위 페이지 삽입 오류",
    "subpageNestedInfor": "상호 삽입할 수 없는 하위 페이지를 삽입할 수 없습니다",
    "checkSubpageNestedError" : "선택한 하위 페이지에 상호 삽입되는 상황이 있습니다. 확인하십시오!",

    "checkSubpageTitle": "페이지 저장 유효성 검사",
    "checkFormSaveError": "페이지를 저장할 수 없음. 다음과 같은 이유로 인함:<br>",
    "checkSubpagePcInfor": "PC 페이지에서 다음과 같은 하위 필드 충돌이 있습니다:<br>{subform}<br>",
    "checkSubpageMobileInfor": "모바일 페이지에서 다음과 같은 하위 필드 충돌이 있습니다:<br>{subform}",


    "design": "디자인",
    "script": "코드",
    "html": "HTML",
    "css": "CSS",
    "byModule": "디자인 요소별",
    "byPath": "스크립트 유형별",
    "events": "이벤트",
    "importO2": "O2 데이터 가져오기",
    "importHTML": "HTML에서 가져오기",
    "importOffice": "WORD 또는 EXCEL에서 가져오기",
    "importO2_infor": "O2 형식의 폼 데이터를 아래 편집기에 복사하십시오. (폼 또는 페이지 디자이너 도구 모음의 '내보내기' 버튼을 사용하여 폼 데이터를 가져옵니다)<br/> Ctrl+Alt+I를 눌러 데이터를 형식화합니다.",
    "importHTML_infor": "HTML 데이터를 아래 편집기에 복사하십시오. Ctrl+Alt+I를 눌러 데이터를 형식화합니다.",
    "importHTML_infor2": "CSS 데이터를 아래 편집기에 복사하십시오. Ctrl+Alt+I를 눌러 데이터를 형식화합니다.",
    "importOffice_infor": "Word 또는 Excel 파일을 선택하십시오.",
    "import_ok": "가져오기",
    "import_cancel": "취소",
    "import_option1": "빈 셀에 입력란 추가",
    "import_option2": "빈 항목 제거",
    "implodeOfficeEmpty": "가져올 Word 또는 Excel 파일을 먼저 선택하십시오.",
    "applicationNotFound": "앱을 찾을 수 없음",

    "scriptTitle": {
        "validationOpinion": "폼 의견 유효성 검사",
        "validationRoute": "폼 경로 유효성 검사",
        "validationFormCustom": "폼 유효성 검사",
        "defaultValue": "기본값",
        "validation": "유효성 검사 스크립트",
        "sectionByScript": "스크립트에 따른 섹션",
        "itemScript": "선택 가능한 값 스크립트",
        "iframeScript": "iframe 스크립트",
        "labelScript": "텍스트 값",
        "rangeKey": "조직 범위",
        "identityRangeKey": "신분 조직 범위",
        "unitRangeKey": "조직 선택 범위",
        "rangeDutyKey": "직무 범위",
        "exclude": "선택 제외 스크립트",
        "cookies": "데이터 소스 요청 쿠키",
        "requestBody": "데이터 소스 요청 본문",
        "jsonText": "데이터 텍스트",
        "dataScript": "트리 컨트롤 스크립트",
        "itemDynamic": "동적 옵션 스크립트",
        "defaultData": "데이터 그리드 기본값",
        "editableScript": "데이터 그리드 편집 가능 여부",
        "config": "HTML 편집 상자 구성",
        "filterScript": "워크플로 레코드 필터",
        "readScript": "Office 읽기 전용 스크립트",
        "fileSite": "Office 파일 사이트 스크립트",
        "subformScript": "하위 폼 스크립트",
        "selectedScript": "뷰 선택 스크립트",
        "action.tools": "작업 버튼"
    },
    "selectorButton": {
        "ok": "확 인",
        "cancel": "취 소"
    },
    "modules": {
        "label": "텍스트",
        "textfield": "텍스트 필드",
        "number": "숫자 필드",
        "org": "인원 및 조직",
        "calendar": "날짜 선택",
        "textarea": "다중 텍스트",
        "select": "드롭다운 상자",
        "radio": "라디오 버튼",
        "checkbox": "체크 박스",
        "combox": "콤보 상자",
        "opinion": "의견 상자",
        "button": "버튼",
        "Address": "주소",
        "Actionbar": "액션 바",
        "Sidebar": "사이드바",
        "image": "이미지",
        "imageclipper": "이미지 편집",
        "attachment": "첨부 파일",
        "div": "컨테이너",
        "table": "테이블",
        "datatable": "데이터 테이블",
        "datatemplate": "데이터 템플릿",
        "subform": "하위 폼",
        "ViewSelector": "뷰 선택",
        "view": "뷰 삽입",
        "stat": "통계 삽입",
        "html": "HTML",
        "common": "일반 요소",
        "tab": "탭",
        "tree": "트리",
        "log": "워크플로 레코드",
        "monitor": "워크플로 모니터링",
        "iframe": "Iframe",
        "documenteditor": "문서 편집기",
        "htmledit": "HTML 편집기",
        "office": "Office 컨트롤",
        "statementSelector": "질의 뷰 선택",
        "statement": "질의 뷰 삽입",
        "source": "데이터 원본",
        "subSource": "하위 데이터 원본",
        "sourceText": "데이터 텍스트",
        "widget": "위젯",
        "widgetmodules": "위젯 요소",
        "address": "주소",
        "importer": "데이터 가져오기",
        "SmartBI": "SmartBI 보고서",
        "application": "플랫폼 앱",

        "group_all": "모두",
        "group_form": "양식",
        "group_layout": "레이아웃",
        "group_data": "데이터",
        "group_filetext": "파일 편집",
        "group_function": "기능",
        "group_element": "Element"
    },
    "filedConfigurator": {
        "sequence": "일련번호",
        "fieldTitle": "필드 제목",
        "fieldId": "필드 식별자",
        "action": "조치",
        "moveup": "위로 이동",
        "deleteRow": "행 삭제",
        "insertRow": "행 삽입",
        "importFromForm": "화면에서 필드 설정 가져오기"
    }
};
