MWF.xApplication.portal.PageDesigner = MWF.xApplication.portal.PageDesigner || {};
MWF.APPPOD = MWF.xApplication.portal.PageDesigner;
MWF.APPPOD.LP = {
    "title": "ເຄື່ອງມືແກ້ໄຂໜ້າ",
    "newPage": "ສ້າງເພສ",
    "property": "ຊັບສິນ",
    "tools": "ເຄື່ອງມື",
    "all": "ທັງໝົດ",

    "repetitionsId": "ລະຫັດ ອົງປະກອບບໍ່ຊໍ້າກັນ",
    "notNullId": "ລະຫັດ ອົງປະກອບບໍ່ສາມາດຫວ່າງເປົ່າ",
    "ປະຫວັດສາດ": "ປະຫວັດສາດ",
    "componentTree": "ຕົ້ນໄມ້ອົງປະກອບ",

    "button":{
        "ok": "ຕົກລົງ",
        "cancel": "ຍົກເລີກ"
    },

    "notice": {
        "save_success": "ບັນທຶກໜ້າສຳເລັດແລ້ວ!",
        "saveTemplate_success": "ແມ່ແບບໜ້າບັນທຶກສຳເລັດແລ້ວ!",
        "saveTemplate_inputName": "ກະລຸນາໃສ່ຊື່ແມ່ແບບ",
        "saveTemplate_inputCategory": "ກະລຸນາຢືນຢັນປະເພດແມ່ແບບ",

        "deleteElementTitle": "ລົບການຢືນຢັນອົງປະກອບແບບຟອມ",
        "deleteElement": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບອົງປະກອບປັດຈຸບັນ ແລະອົງປະກອບລູກຂອງມັນອອກ?",

        "deleteRowTitle": "ລົບການຢືນຢັນແຖວຕາຕະລາງ",
        "deleteRow": "ການລົບແຖວປະຈຸບັນຈະລົບເນື້ອໃນຂອງເຊລທັງໝົດໃນແຖວນີ້. ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບແຖວທີ່ເລືອກໃນປັດຈຸບັນ?",
        "deleteColTitle": "ລົບການຢືນຢັນຖັນຕາຕະລາງ",
        "deleteCol": "ການລົບແຖວປະຈຸບັນຈະລົບເນື້ອໃນຂອງເຊລທັງໝົດໃນຖັນນີ້. ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບຖັນທີ່ເລືອກໃນປັດຈຸບັນ?",
        "deleteEventTitle": "ລົບການຢືນຢັນເຫດການ",
        "deleteEvent": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບເຫດການປັດຈຸບັນອອກ?",

        "deleteActionTitle": "ລົບການຢືນຢັນການປະຕິບັດ",
        "deleteAction": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບການກະທຳດັ່ງກ່າວ?",

        "deleteButtonTitle": "ລົບການຢືນຢັນການດໍາເນີນງານ",
        "deleteButton": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບປຸ່ມປະຕິບັດການປະຈຸບັນ?",

        "notUseModuleInMobile": "ສະຖານີມືຖືບໍ່ຮອງຮັບອົງປະກອບນີ້",

        "changeToSequenceTitle": "ຢືນຢັນ",
        "changeToSequence": "ຄຳສັ່ງນີ້ຈະລຶບອົງປະກອບທີ່ເພີ່ມເຂົ້າມາ. ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການປ່ຽນເປັນຖັນ \"ເລກລຳດັບ\"?",

        "selectPage" : "ເລືອກໜ້າ",
        "selectWidget" : "ເລືອກ ວິດເຈັດ",

        "widgetNameEmpty": "ໃສ່ຊື່ ວິດເຈັດ",
        "widgetNameConflict" : "ຂໍ້ຂັດແຍ່ງຊື່ວິດເຈັດ",
        "widget_save_success" : "ບັນທຶກວິດເຈັດສຳເລັດແລ້ວ"
    },

    "formAction": {
        "insertRow": "ແຊກແຖວ",
        "insertCol": "ແຊກຖັນ",
        "deleteRow": "ລົບແຖວ",
        "deleteCol": "ລົບຖັນ",
        "mergerCell": "ລວມເຊລ",
        "splitCell": "ແຍກເຊລ",
        "move": "ຍ້າຍ",
        "copy": "ກອ໋ບປີ້",
        "delete": "ລົບ",
        "add": "ເພີ່ມ",
        "script": "ເນື້ອໃນ",
        "styleBrush": "ແປງສະໄຕລ໌",
        "insertTop": "ໃສ່ທາງເທິງ",
        "insertBottom": "ໃສ່ລົງລຸ່ມ",
        "insertBefore": "ໃສ່ກ່ອນ",
        "insertAfter": "ແຊກຫຼັງ",
        "injectNotice": "ກົດ Ctrl ຄ້າງໄວ້ແລ້ວປ່ອຍເມົາສ໌ເພື່ອວາງຕຳແໜ່ງທີ່ຊັດເຈນ",

        "makeWidget" : "ຕັ້ງເປັນ ວິດເຈັດ",
        "defaultWidgetName": " ວິດເຈັດ"
    },

    "actionbar": {
        "readhide": "ຕັ້ງວ່າຈະສະແດງໃນເວລາອ່ານ",
        "edithide": "ຕັ້ງວ່າຈະສະແດງໃນເວລາແກ້ໄຂ",
        "hideCondition": "ກໍານົດເງື່ອນໄຂການເຊື່ອງ",
        "title": "ຫົວຂໍ້",
        "img": "ໄອຄອນ",
        "action": "ການກະທຳ",
        "condition": "ສະພາບການສະແດງ",

        "editScript": "ການແກ້ໄຂເນື້ອໃນການກະທຳ",
        "editCondition": "ເຊື່ອງການດັດແກ້ສະພາບ (ກັບຄືນຄວາມຈິງເພື່ອຊ່ອນການດຳເນີນການ)",
        "up": "ຍ້າຍຂຶ້ນ",
        "property": "ຊັບສິນ",
        "addCustomTool": "ເພີ່ມການກະທຳແບບກຳນົດເອງ",
        "delete": "ລົບ",
        "setProperties": "ກໍານົດຄຸນສົມບັດການປະຕິບັດ",
        "restoreDefaultTool": "ຟື້ນຟູການກະທຳຂອງລະບົບທີ່ຖືກລົບ",
        "selectDefaultTool": "ເລືອກການປະຕິບັດລະບົບ",
        "setReaded": "ໝາຍວ່າອ່ານແລ້ວ",
        "readed": "ອ່ານແລ້ວ"
    },
    "isSave": "Saving, please wait...",
    "validation": {
        "validation": "ການກວດສອບ",
        "anytime": "ທຸກເວລາ",
        "decision": "ເລືອກການຕັດສິນໃຈ",
        "decisionName": "<ຊື່ການຕັດສິນໃຈ>",
        "value": "ຄຸນຄ່າ",

        "length": "ຄວາມຍາວຂອງມູນຄ່າ",
        "valueInput": "<value>",
        "isnull": "ເປັນ null",
        "notnull": "ບໍ່ແມ່ນ  null",
        "gt": "ຍິ່ງໃຫຍ່ກວ່າ",
        "lt": "ຫນ້ອຍກວ່າ",
        "equal": "ເທົ່າທຽມກັນ",
        "neq": "ບໍ່ເທົ່າກັນ",
        "contain": "ບັນຈຸ",
        "notcontain": "ບໍ່ບັນຈຸ",
        "prompt": "ກະຕຸ້ນ",
        "add": "ຕື່ມ",
        "modify": "ປັບປ່ຽນ",
        "when": "ເມື່ອ",
        "as": "",

        "inputDecisionName": "ກະລຸນາໃສ່ຊື່ຂອງການຕັດສິນໃຈ",
        "inputValue": "ກະລຸນາໃສ່ຄ່າ",
        "inputPrompt": "ກະລຸນາໃສ່ເນື້ອໃນທີ່ວ່ອງໄວ",
        "delete_title": "ລົບການຢືນຢັນ",
        "delete_text": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບລະຫັດຢືນຢັນນີ້?"
    },
    "datagrid" : {
        "import": "ນຳເຂົ້າ",
        "export": "ສົ່ງອອກ"
    },

    "selectIcon": "ເລືອກໄອຄອນ",
    "selectImage": "ເລືອກຮູບພາບ",
    "selectApplication": "ເລືອກແອັບພລິເຄຊັນ",
    "dutyInputTitle": "ເພີ່ມພາລາມິເຕີຫົວຂໍ້",
    "dutyInput": "ກະລຸນາເລືອກຫົວໜ່ວຍສຳລັບໜ້າທີ່ \"{duty}\"",
    "select": "ເລືອກ",
    "empty": "ເປົ່າ",

    "creatorUnit": "ຫນ່ວຍງານຜູ້ຂຽນ",
    "CurrentUnit": "ຫນ່ວຍງານ",
    "selectUnit": "ເລືອກຫົວໜ່ວຍ",
    "scriptUnit": "ໃຊ້ສະຄຣິບ",

    "creatorCompany": "ບໍລິສັດສ້າງຮ່າງ",
    "creatorDepartment": "ກົມຮ່າງ",
    "currentCompany": "ບໍລິສັດປະຈຸບັນ",
    "CurrentDepartment": "ພະແນກປະຈຸບັນ",

    "deleteDutyTitle": "ລົບການຢືນຢັນວຽກ",
    "deleteDutyText": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບໜ້າທີ່ \"{duty}\"?",

    "saveTemplate": "ບັນທຶກເປັນແມ່ແບບແບບຟອມ",
    "templateName": "ຊື່",
    "templateCategory": "ໝວດໝູ່",
    "templateDescription": "ລາຍລະອຽດ",
    "save": "ບັນທຶກ",
    "cancel": "ຍົກເລີກ",
    "newCategory": "ໝວດໝູ່ໃໝ່",
    "mustSelectFormStyle": "ທ່ານຕ້ອງເລືອກຮູບແບບແບບຟອມ",
    "notValidJson": "ຮູບແບບ json ຜິດ",

    "filter": {
        "and": "ແລະ",
        "or": "ຫຼື",
        "equals": "ເທົ່າ",
        "notEquals": "ບໍ່ເທົ່າກັບ",
        "greaterThan": "ໃຫຍ່ກວ່າ",
        "greaterThanOrEqualTo": "ຍິ່ງໃຫຍ່ກວ່າຄວາມເທົ່າທຽມ",
        "lessThan": "ຫນ້ອຍກວ່າ",
        "lessThanOrEqualTo": "ນ້ອຍກວ່າເທົ່າກັບ",
        "like": "ຈັບຄູ່",
        "notLike": "ບໍ່ກົງກັນ",
        "from": "ຈາກ",
        "value": "ຄຸນຄ່າ"
    },

    "mastInputPath": "ປ້ອນຂໍ້ມູນເສັ້ນທາງ",
    "mastInputTitle": "ໃສ່ຫົວຂໍ້",
    "delete_filterItem_title": "ຢືນຢັນການລົບເງື່ອນໄຂການກັ່ນຕອງ",
    "delete_filterItem": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບການກັ່ນຕອງປັດຈຸບັນອອກ?",

    "checkFormSaveError": "ບໍ່ສາມາດບັນທຶກໜ້າໄດ້ດ້ວຍເຫດຜົນຕໍ່ໄປນີ້:<br>",

    "implodeError": "ຮູບແບບຂອງຂໍ້ມູນທີ່ຈະນໍາເຂົ້າບໍ່ຖືກຕ້ອງ",
    "implodeEmpty": "ກະລຸນາຕື່ມຂໍ້ມູນທີ່ຈະນໍາເຂົ້າໃນປ່ອງແກ້ໄຂ",
    "implodeConfirmTitle": "ການຢືນຢັນການນໍາເຂົ້າ",
    "implodeConfirmText": "ການນໍາເຂົ້າຂໍ້ມູນຈະລົບຫນ້າປັດຈຸບັນແລະບໍ່ສາມາດຍົກເລີກໄດ້. ທ່ານແນ່ໃຈວ່າທ່ານຕ້ອງການທີ່ຈະນໍາເຂົ້າມັນ?",

    "subpageNameConflictTitle": "ຄວາມຂັດແຍ້ງຂອງຊື່ຫນ້າຍ່ອຍ",
    "subpageNameConflictInfor": "ຊື່ຊ່ອງຂໍ້ມູນຕໍ່ໄປນີ້ຂອງໜ້າຍ່ອຍຂັດກັນກັບໜ້າທີ່ມີຢູ່:\n{name}",
    "subpageConflictTitle": "ຂໍຜິດພາດໃນການຝັງຟອມຍ່ອຍ",
    "subpageConflictInfor": "ທ່ານບໍ່ສາມາດຝັງໜ້າຍ່ອຍດຽວກັນຊ້ຳໆໄດ້",

    "subpageNestedTitle": "ຂໍຜິດພາດໃນການຝັງຟອມຍ່ອຍ",
    "subpageNestedInfor": "ໜ້າຍ່ອຍທີ່ຝັງໄວ້ທີ່ບໍ່ສາມາດຕັ້ງຢູ່ໃນກັນໄດ້",
    "checkSubpageNestedError" : "ໜ້າຍ່ອຍທີ່ທ່ານເລືອກນັ້ນຖືກຕັ້ງຢູ່ໃນກັນ, ກະລຸນາກວດເບິ່ງ!",

    "checkSubpageTitle": "ບັນທຶກໜ້າເວັບ",
    "checkSubpagePcInfor": "ຊ່ອງຍ່ອຍຕໍ່ໄປນີ້ຂັດກັນຢູ່ໃນໜ້າ PC: <br>{subform}<br>",
    "checkSubpageMobileInfor": "ໃນໜ້າມືຖື, ຊ່ອງຍ່ອຍຕໍ່ໄປນີ້ຂັດກັນ:<br>{subform}",

    "design": "ອອກແບບ",
    "script": "ເນື້ອໃນ",
    "html": "HTML",
    "css": "CSS",
    "byModule": "ໂດຍອົງປະກອບ",
    "byPath": "ຕາມປະເພດ",
    "events": "ເຫດການ",
    "pageform": "ຫນ້າ",
    "importO2": "ນໍາເຂົ້າຈາກຂໍ້ມູນ O2",
    "importHTML": "ນໍາເຂົ້າຈາກ HTML",
    "importOffice": "ນໍາເຂົ້າຈາກ WORD ຫຼື EXCEL",

    "importO2_infor": "ກະລຸນາຄັດລອກຂໍ້ມູນແບບຟອມໃນຮູບແບບ O2 ໄປໃສ່ຕົວແກ້ໄຂຕໍ່ໄປນີ້. (ໃຊ້ປຸ່ມ \"ສົ່ງອອກ\" ໃນແຖບເຄື່ອງມືຂອງແບບຟອມ ຫຼືຕົວອອກແບບໜ້າເພື່ອເອົາຂໍ້ມູນແບບຟອມ). ກົດ Ctrl+Alt+I Formatable. ຂໍ້ມູນ",
    "importHTML_infor": "ກະລຸນາສຳເນົາຂໍ້ມູນ HTML ໄປໃສ່ຕົວແກ້ໄຂຕໍ່ໄປນີ້. ກົດ Ctrl+Alt+I ເພື່ອຈັດຮູບແບບຂໍ້ມູນ",
    "importHTML_infor2": "ກະລຸນາສຳເນົາຂໍ້ມູນ CSS ໄປໃສ່ຕົວແກ້ໄຂຕໍ່ໄປນີ້. ກົດ Ctrl+Alt+I ເພື່ອຈັດຮູບແບບຂໍ້ມູນ",
    "importOffice_infor": "ກະລຸນາເລືອກໄຟລ໌ Word ຫຼື Excel.",
    "import_ok": "ນຳເຂົ້າ",
    "import_cancel": "ຍົກເລີກ",
    "import_option1": "ເພີ່ມກ່ອງໃສ່ກັບຕາລາງຫວ່າງເປົ່າໃນຕາຕະລາງ",
    "import_option2": "ເອົາອົງປະກອບເປົ່າ",
    "implodeOfficeEmpty": "ກະລຸນາເລືອກໄຟລ໌ Word ຫຼື Excel ເພື່ອນໍາເຂົ້າກ່ອນ",
    "applicationNotFound": "ບໍ່ພົບແອັບ",

    "scriptTitle": {
        "validationOpinion": "ການຢືນຢັນແບບຟອມ",
        "validationRoute": "ການຢັ້ງຢືນເສັ້ນທາງແບບຟອມ",
        "validationFormCustom": "ການກວດສອບແບບຟອມ",
        "defaultValue": "ຄ່າເລີ່ມຕົ້ນ",
        "validation": "ສະຄຣິບການກວດສອບ",
        "sectionByScript": "ມາດຕາ ByScript",
        "itemScript": "ສະຄຣິບຄ່າທາງເລືອກ",
        "iframeScript": " ເນື້ອໃນiframe",
        "labelScript": "ຄ່າຂໍ້ຄວາມ",
        "rangeKey": "ຊ່ວງຫົວໜ່ວຍ",
        "identityRangeKey": "ຊ່ວງຫົວໜ່ວຍຕົວຕົນ",
        "unitRangeKey": "ຊ່ວງການເລືອກຫົວໜ່ວຍ",
        "rangeDutyKey": "ຂອບເຂດໜ້າທີ່",
        "exclude": "ຍົກເວັ້ນ Script",
        "cookies": "ແຫຼ່ງຂໍ້ມູນຮ້ອງຂໍ cookies",
        "requestBody": "ຂໍ້ຄວາມຂໍແຫຼ່ງຂໍ້ມູນ",
        "jsonText": "ຂໍ້ຄວາມຂໍ້ມູນ",
        "dataScript": "ສະຄຣິບຄວບຄຸມຕົ້ນໄມ້",
        "itemDynamic": "ຕົວເລືອກແບບໄດນາມິກ",
        "defaultData": " ຄ່າເລີ່ມຕົ້ນຂອງຕາຕະລາງຂໍ້ມູນ",
        "editableScript": "ສາມາດແກ້ໄຂໄດ້",
        "config": "ການຕັ້ງຄ່າຕົວແກ້ໄຂ HTML",
        "filterScript": "ການກັ່ນຕອງການບັນທຶກ",
        "readScript": "ເນື້ອໃນໄຟລຂອງຫ້ອງການ",
        "fileSite": "ສະຄຣິບໄຟລ໌ຫ້ອງການ",
        "subformScript": "ສະຄຣິບຍ່ອຍ",
        "selectedScript": "ເບິ່ງສະຄຣິບເລືອກ",
        "action.tools": "ປຸ່ມປະຕິບັດ"
    },
    "selectorButton" : {
        "ok" : "ຕົກລົງ",
        "cancel" : "ຍົກເລີກ"
    },

    "modules": {
        "label": "ປ້າຍ",
        "textfield": "ຖັນຂໍ້ຄວາມ",
        "number": "ຈໍານວນ",
        "currency": "ສະກຸນເງິນ",
        "org": "Org",
        "calendar": "ປະຕິທິນ",
        "textarea": "ພື້ນທີ່ຂໍ້ຄວາມ",
        "select": "ເລືອກ",
        "ວິທະຍຸ": "ວິທະຍຸ",
        "checkbox": "ກວດສອບກ່່ອງ",
        "combox": "ຄອມbox",
        "ຄວາມຄິດເຫັນ": "ຄວາມຄິດເຫັນ",
        "button": "ປຸ່ມ",
        "ທີ່ຢູ່": "ທີ່ຢູ່",
        "Actionbar": "ແຖບການກະກຳ",
        "Sidebar": "ແຖບດ້ານຂ້າງ",
        "image": "ພາບ",
        "imageclipper": "ຮູບພາບຄິບເປີ",
        "attachment": "ແນບ",
        "div": "Div",
        "table": "ຕາຕະລາງ",
        "datagrid": "ຕາຕະລາງຂໍ້ມູນ(ເຊົາຮອງຮັບ)",
        "datatable": "ສາມາດເຮັດໄດ້",
        "datatemplate": "ແຜນຜັງຂໍ້ມູນ",
        "subform": "ແບບຟອມຍ່ອຍ",
        "ViewSelector": "ຕົວເລື່ອກມຸມມອງ",
        "view": "ເບິ່ງ",
        "stat": "ສະຖິຕິ",
        "html": "HTML",
        "common": "ສາມັນ",
        "tab": "ແຖບ",
        "tree": "ຕົ້ນໄມ້",
        "log": "ບັນທຶກ",
        "monitor": "ຕິດຕາມກວດກາ",
        "iframe": "iframe",
        "documenteditor": "ບັນນາທິການເອກະສານ",
        "htmledit": "htmleditor",
        "office": "ຫ້ອງການ",
        "StatementSelector": "ຜູ້ເລືອກຄຳຖະແຫຼງ",
        "statement": "ຖະແຫຼງການ",
        "source": "ແຫຼ່ງຂໍ້ມູນ",
        "subSource": "ແຫຼ່ງຍ່ອຍ",
        "sourceText": "ຂໍ້ຄວາມແຫຼ່ງ",
        "widget": "ວິດເຈັດ",
        "widgetmodules": "ວິດເຈັດ",
        "address": "ທີ່ຢູ່",
        "importer": "ການນຳເຂົ້າ",
        "SmartBI":"ອັດສະລິຍະ BI",
        "application ": "ແພລຟອມແອັບພລິເຄຊັນ",

        "group_all": "ອົງປະກອບທັງໝົດ",
        "group_form":" ອົງປະກອບແບບຟອມ",
        "group_layout":"ອົງປະກອບໂຄງຮ່າງ",
        "group_data": "ອົງປະກອບຂໍ້ມູນ",
        "group_filetext":"ອົງປະກອບການແກ້ໄຂໄຟລ໌",
        "group_function":"ອົງປະກອບຟັງຊັນ",
        "group_element": "ອົງປະກອບອົງປະກອບ"
    },
    "filedConfigurator": {
        "sequence": "ລໍາດັບ",
        "fieldTitle": "ຊື່ພາກສະຫນາມ",
        "fieldId": "ລະຫັດ ພາກສະຫນາມ",
        "action": "ການກະທຳ",
        "moveup": "ຍ້າຍໄປແຖວກ່ອນໜ້າ",
        "deleteRow": "ລົບແຖວ",
        "insertRow": "ແຊກແຖວ",
        "importFromForm": "ນໍາເຂົ້າການຕັ້ງຄ່າພາກສະຫນາມຈາກການໂຕ້ຕອບ"
    }
};
