MWF.xApplication.portal.PageDesigner = MWF.xApplication.portal.PageDesigner || {};
MWF.APPPOD = MWF.xApplication.portal.PageDesigner;
MWF.APPPOD.LP = {
    "title": "頁面編輯",
    "newPage": "新建頁面",
    "property": "屬性",
    "tools": "工具",
    "all": "全部",
    "repetitionsId": "重複的元素標識符",
    "notNullId": "元素標識符不能為空",
    "history": "歷史",
    "componentTree": "組件樹",
    "button": {
        "ok": "確定",
        "cancel": "取消"
    },

    "notice": {
        "save_success": "表單保存成功！",
        "saveTemplate_success": "表單模板保存成功！",
        "saveTemplate_inputName": "請輸入模板標題",
        "saveTemplate_inputCategory": "請確定模板分類",
        "deleteElementTitle": "刪除表單元素確認",
        "deleteElement": "是否確定刪除當前元素，以及其子元素？",
        "deleteRowTitle": "刪除表格行確認",
        "deleteRow": "刪除當前行將刪除該行所有儲存格中的內容，是否確定刪除當前選中的行？",
        "deleteColTitle": "刪除表格列確認",
        "deleteCol": "刪除當前行將刪除該列所有儲存格中的內容，是否確定刪除當前選中的列？",
        "deleteEventTitle": "刪除事件確認",
        "deleteEvent": "是否確定刪除當前事件？",
        "deleteActionTitle": "刪除操作確認",
        "deleteAction": "是否確定刪除當前操作？",
        "deleteButtonTitle": "刪除操作確認",
        "deleteButton": "確定要刪除當前操作按鈕嗎？",
        "notUseModuleInMobile": "移動端不支持此組件",
        "changeToSequenceTitle": "確認",
        "changeToSequence": "此操作將刪除已經添加的組件，確定要改成“序號”列嗎？",
        "selectPage": "請選擇頁面",
        "selectPortal": "請選擇門戶",
        "selectWidget": "請選擇部件",
        "widgetNameEmpty": "請填寫部件名稱",
        "widgetNameConflict": "部件名稱衝突",
        "widget_save_success": "部件保存成功"
    },

    "formAction": {
        "insertRow": "插入行",
        "insertCol": "插入列",
        "deleteRow": "删除行",
        "deleteCol": "删除列",
        "mergerCell": "合併儲存格",
        "splitCell": "拆分儲存格",
        "move": "移動",
        "copy": "複製",
        "delete": "刪除",
        "add": "添加",
        "script": "腳本",
        "makeWidget": "設定為部件",
        "defaultWidgetName": "部件"
    },
    "actionbar": {
        "readhide": "設定閱讀時是否顯示",
        "edithide": "設定編輯時是否顯示",
        "hideCondition": "設定隱藏條件",
        "title": "標題",
        "img": "圖示",
        "action": "操作",
        "condition": "顯示條件",
        "editScript": "操作腳本編輯",
        "editCondition": "隱藏條件編輯（返回 true 隱藏操作）"
    },
    "isSave": "正在保存，請稍候...",
    "validation": {
        "validation": "驗證",
        "anytime": "任何時候",
        "decision": "選擇決策",
        "decisionName": "<決策名稱>",
        "value": "值",
        "length": "值長度",
        "valueInput": "<值>",
        "isnull": "為空",
        "notnull": "不為空",
        "gt": "大於",
        "lt": "小於",
        "equal": "等於",
        "neq": "不等於",
        "contain": "包含",
        "notcontain": "不包含",
        "prompt": "提示",
        "add": "添加",
        "modify": "修改",
        "when": "當",
        "as": "時",
        "inputDecisionName": "請輸入決策名稱",
        "inputValue": "請輸入值",
        "inputPrompt": "請輸入提示內容",
        "delete_title": "刪除驗證內容確認",
        "delete_text": "您確定要刪除此驗證項目嗎？"
    },
    "selectIcon": "選擇圖標",
    "selectImage": "選擇圖片",
    "dutyInputTitle": "添加職務參數",
    "dutyInput": "請為職務 \"{duty}\" 添加參數",
    "creatorCompany": "起草公司",
    "creatorDepartment": "起草部門",
    "currentCompany": "當前公司",
    "currentDepartment": "當前部門",
    "deleteDutyTitle": "移除職務確認",
    "deleteDutyText": "您確定要移除職務 \"{duty}\" 嗎？",
    "select": "選擇",
    "empty": "清空",

    "saveTemplate": "保存為表單模板",
    "templateName": "模板名稱",
    "templateCategory": "模板分類",
    "templateDescription": "模板描述",
    "save": "保存",
    "cancel": "取消",
    "newCategory": "新分類",
    "filter": {
        "and": "並且",
        "or": "或者",
        "equals": "等於",
        "notEquals": "不等於",
        "greaterThan": "大於",
        "greaterThanOrEqualTo": "大於等於",
        "lessThan": "小於",
        "lessThanOrEqualTo": "小於等於",
        "like": "匹配",
        "notLike": "不匹配",
        "from": "從",
        "value": "值"
    },
    "mastInputPath": "請輸入資料路徑",
    "mastInputTitle": "請輸入標題",
    "delete_filterItem_title": "刪除篩選條件確認",
    "delete_filterItem": "您確定要刪除當前篩選條件嗎？",
    "implodeError": "要導入的資料格式錯誤",
    "implodeEmpty": "請在編輯框中填入要導入的資料",
    "implodeConfirmTitle": "導入確認",
    "implodeConfirmText": "導入資料將清除當前頁面，且無法撤銷，您確定要導入嗎？",

    "subpageNameConflictTitle": "子頁面字段名稱衝突",
    "subpageNameConflictInfor": "以下子頁面的字段名稱與現有表單衝突：\n{name}",
    "subpageConflictTitle": "子頁面插入錯誤",
    "subpageConflictInfor": "您不能插入兩個相同的子頁面",

    "subpageNestedTitle": "子頁面插入錯誤",
    "subpageNestedInfor": "不允許互相嵌套的子頁面插入",
    "checkSubpageNestedError" : "您選擇的子頁面存在互相嵌套的情況，請檢查！",

    "checkSubpageTitle": "頁面保存驗證",
    "checkFormSaveError": "無法保存頁面，原因如下：<br>",
    "checkSubpagePcInfor": "PC頁面中，存在以下子字段衝突：<br>{subform}<br>",
    "checkSubpageMobileInfor": "Mobile頁面中，存在以下子字段衝突：<br>{subform}",


    "design": "設計",
    "script": "腳本",
    "html": "HTML",
    "css": "CSS",
    "byModule": "按設計元素",
    "byPath": "按腳本類型",
    "events": "事件",
    "importO2": "從O2數據導入",
    "importHTML": "從HTML導入",
    "importOffice": "從WORD或EXCEL導入",
    "importO2_infor": "請將O2格式的表單數據複製到以下編輯器中。（使用表單或頁面設計工具欄上的“導出”按鈕，獲取表單數據）<br/> 按下Ctrl+Alt+I可格式化數據",
    "importHTML_infor": "請將HTML數據複製到以下編輯器中。按下Ctrl+Alt+I可格式化數據",
    "importHTML_infor2": "請將CSS數據複製到以下編輯器中。按下Ctrl+Alt+I可格式化數據",
    "importOffice_infor": "請選擇Word或Excel文件。",
    "import_ok": "導入",
    "import_cancel": "取消",
    "import_option1": "在表格的空單元格中添加輸入框",
    "import_option2": "去除空元素",
    "implodeOfficeEmpty": "請先選擇要導入的Word或Excel文件",
    "applicationNotFound": "未找到應用",

    "scriptTitle": {
        "validationOpinion": "表單意見驗證",
        "validationRoute": "表單路徑驗證",
        "validationFormCustom": "表單驗證",
        "defaultValue": "默認值",
        "validation": "驗證腳本",
        "sectionByScript": "區段依據",
        "itemScript": "可選值腳本",
        "iframeScript": "iframe腳本",
        "labelScript": "文本值",
        "rangeKey": "組織範圍",
        "identityRangeKey": "身份組織範圍",
        "unitRangeKey": "組織選擇範圍",
        "rangeDutyKey": "職務範圍",
        "exclude": "選擇排除腳本",
        "cookies": "數據源請求cookies",
        "requestBody": "數據源請求消息體",
        "jsonText": "數據文本",
        "dataScript": "樹控件腳本",
        "itemDynamic": "動態選項腳本",
        "defaultData": "數據網格默認值",
        "editableScript": "數據網格是否可編輯",
        "config": "HTML編輯框配置",
        "filterScript": "流程記錄過濾",
        "readScript": "Office只讀腳本",
        "fileSite": "Office文件site腳本",
        "subformScript": "子表單腳本",
        "selectedScript": "視圖選擇腳本",
        "action.tools": "操作按鈕"
    },
    "selectorButton": {
        "ok": "確 定",
        "cancel": "取 消"
    },
    "modules": {
        "label": "文本",
        "textfield": "文本字段",
        "number": "數字字段",
        "org": "人員組織",
        "calendar": "日期選擇",
        "textarea": "多行文本",
        "select": "下拉框",
        "radio": "單選框",
        "checkbox": "多選框",
        "combox": "組合框",
        "opinion": "意見框",
        "button": "按鈕",
        "Address": "地址",
        "Actionbar": "操作欄",
        "Sidebar": "側邊操作欄",
        "image": "圖片",
        "imageclipper": "圖片編輯",
        "attachment": "附件",
        "div": "容器",
        "table": "表格",
        "datatable": "數據表格",
        "datatemplate": "數據模板",
        "subform": "子表單",
        "ViewSelector": "選擇視圖",
        "view": "嵌入視圖",
        "stat": "嵌入統計",
        "html": "HTML",
        "common": "通用元素",
        "tab": "分頁",
        "tree": "樹",
        "log": "流程記錄",
        "monitor": "流程監控",
        "iframe": "Iframe",
        "documenteditor": "公文編輯器",
        "htmledit": "HTML編輯器",
        "office": "Office控件",
        "statementSelector": "選擇查詢視圖",
        "statement": "嵌入查詢視圖",
        "source": "數據源",
        "subSource": "子數據源",
        "sourceText": "數據文本",
        "widget": "部件",
        "widgetmodules": "部件元素",
        "address": "地址",
        "importer": "數據導入",
        "SmartBI": "SmartBI報告",
        "application": "平台應用",
        "group_all": "所有組件",
        "group_form": "表單組件",
        "group_layout": "佈局組件",
        "group_data": "數據組件",
        "group_filetext": "文件編輯組件",
        "group_function": "功能組件",
        "group_element": "Element組件"
    },
    "filedConfigurator": {
        "sequence": "序號",
        "fieldTitle": "字段標題",
        "fieldId": "字段標識",
        "action": "操作",
        "moveup": "移動到上一行",
        "deleteRow": "刪除行",
        "insertRow": "插入行",
        "importFromForm": "從界面上匯入字段配置"
    }
};
