MWF.xApplication.Org.LP = {
    "title": "組織管理",
    "manage": "管理",
    "identity": "身分",
    "person": "個人",
    "role": "役割",
    "group": "グループ",
    "org": "組織",

    "unitList": "組織構造",
    "groupList": "グループ管理",
    "roleList": "役割管理",
    "personList": "個人管理",
    "personImport": "個人情報のインポート",
    "privateNamesQueryPower": "個人アドレス帳の閲覧権限の設定",

    "application": "アプリケーション",
    "CMSApplication": "アプリケーション",
    "CMSCategory": "カテゴリ",
    "CMSFormField": "フィールド",
    "formField": "フィールド",
    "process": "プロセス",
    "yes": "はい",
    "no": "いいえ",
    "sortByPinYin": "ピンインでソート",
    "sortByPinYinConfirmContent": "この操作により、この組織内の役割がピンインでソートされます。続行しますか？",
    "sortByManual": "手動でソート",

    "search": "検索",
    "searchText": "キーワードを入力してください",
    "edit": "編集",
    "save": "保存",
    "cancel": "キャンセル",
    "add": "追加",
    "delete": "削除",
    "phone": "電話",
    "mail": "メール",
    "department": "部門",
    "company": "会社",
    "duty": "役職",
    "manager": "管理者",
    "ok": "確認",
    "back": "戻る",
    "name": "名前",
    "description": "説明",
    "ipAddress": "ログインIP",
    "ipAddressPlaceHolder": "空でない場合、一致するIPのみがこのアカウントにログインできます。複数の値はカンマで区切られます。",
    "ipAddressIncorrectNotice": "IPアドレスの形式が正しくありません：",

    "createSubCompany": "サブ会社を作成",
    "createSubDepartment": "サブ部門を作成",
    "configCompany": "会社管理者を設定",
    "configCompanyOk": "会社管理者の設定が完了しました。次回のログイン後に権限が適用されます。",
    "configCompanyNull": "<font style='color: red'>会社管理者がクリアされます。クリア後、スーパーアドミニストレータと上位会社管理者だけがこの会社を編集できます。</font><br/><br/>この操作を実行しますか？",
    "configCompanyNullTitle": "会社管理者のクリア確認",
    "deleteOrganization": "選択した組織を削除",
    "deleteOrganizationTitle": "組織の削除確認",
    "deleteOrganizationConfirm": "選択した組織を削除しますか？",
    "deleteOrganizationAllConfirm": "選択した組織には複数の役職、属性、およびメンバーが存在します。この組織を削除すると、これらの役職、属性、およびメンバーも削除されます。現在の操作を続行しますか？<br/><br/>" +
        "<div style=\"color:red\">（注意：この操作はこれらの組織に依存する他のアプリケーションにエラーが発生する可能性があります！）</div>",
    "deleteOrganizationSubConfirm": "1つまたは複数の組織を削除することを選択しました。これらの組織を削除すると、次の操作が実行されます：<br/>" +
        "1. 選択した組織および下位組織のすべての役職および属性を削除<br/>" +
        "2. 選択した組織および下位組織のすべてのメンバー身分を削除<br/>" +
        "3. 選択した組織およびすべての下位組織を削除<br/>" +
        "現在の組織を削除しますか？<br/><br/>" +
        "<div style=\"color:red\">（注意：この操作はこれらの組織に依存する他のアプリケーションにエラーが発生する可能性があります！）</div>",


    "organizationSave": "組織情報を先に保存してください",
    "inputOrganizationInfor": "組織名を入力してください",

    "unitBaseText": "組織情報",
    "unitPersonMembers": "組織メンバー",
    "unitDutys": "組織役職",
    "unitAttribute": "組織属性",
    "unitName": "組織名",
    "unitUnique": "固有コード",
    "unitTypeList": "組織タイプ",
    "unitShortName": "組織略名",
    "unitLevel": "組織階層",
    "unitLevelName": "階層名",
    "unitControllerList": "管理者",
    "unitSuperUnit": "上位組織",
    "unitDescription": "組織の説明",
    "editUnit": "組織情報の編集",
    "saveUnit": "組織情報の保存",
    "inputUnitInfor": "組織名と固有コードを入力してください",
    "orderNumber": "ソート値",


    "unitReadDn": "組織の全名：{dn}",
    "unitReadCreate": "組織は{date}に作成され、最後に{date2}に編集されました",
    "unitReadLevel": "この組織は{level}段階の組織で、階層名は：{levelName}です",

    "dutyName": "役職名",
    "dutyMembers": "メンバー",

    "deleteDutyTitle": "役職の削除確認",
    "deleteDuty": "選択した役職を削除しますか？",

    "deleteDutyIdentityTitle": "役職身分の削除確認",
    "deleteDutyIdentity": "「{duty}」から「{identity}」を削除しますか？",

    "deleteAttributeTitle": "属性の削除確認",
    "deleteAttribute": "選択した属性を削除しますか？",
    "deleteIdentityInDepartmentTitle": "部門から身分を削除する確認",
    "deleteIdentityInDepartment": "「{depart}」から「{identity}」を削除しますか？\n身分を削除すると、この身分に関連するすべての役職も削除されます。削除してもよろしいですか？",

    "deleteGroupsTitle": "グループの削除確認",
    "deleteGroupsConfirm": "選択したグループを削除しますか？",
    "deleteGroupError_InRole": "グループの削除中にエラーが発生しました。グループは役職を持っています。",
    "deleteGroupError_InGroup": "グループの削除中にエラーが発生しました。グループは他のグループのメンバーです。",


    "deleteRolesTitle": "役職削除確認",
    "deleteRolesConfirm": "選択した役職を削除しますか？",

    "deletePersonsTitle": "メンバー削除確認",
    "deletePersonsConfirm": "選択したメンバーを削除しますか？",

    "deleteGroups": "選択したグループを削除",
    "deleteRoles": "選択した役職を削除",
    "deletePersons": "選択したメンバーを削除",
    "deleteUnits": "選択した組織を削除",
    "deleteElementsCancel": "キャンセル",

    "deletePersonMemeberTitle": "個人メンバー削除確認",
    "deletePersonMemeber": "選択した個人メンバーを削除しますか？",
    "deleteGroupMemeberTitle": "グループメンバー削除確認",
    "deleteUnitMemeberTitle": "組織メンバー削除確認",
    "deleteGroupMemeber": "選択したグループメンバーを削除しますか？",
    "deleteUnitMemeber": "選択した組織メンバーを削除しますか？",
    "deleteIdentityMemeberTitle": "組織メンバー削除確認",
    "deleteIdentityMemeber": "選択した組織メンバーを削除しますか？",


    "groupLoaded": "グループの読み込みが完了しました",
    "groupSave": "まずグループ情報を保存してください",
    "inputGroupName": "グループ名を入力してください",
    "editGroup": "グループ情報の編集",
    "saveGroup": "グループ情報の保存",

    "groupBaseText": "グループ情報",
    "groupMemberPersonText": "個人メンバー",
    "groupMemberIdentityText": "アイデンティティメンバー",
    "groupMemberGroupText": "グループメンバー",
    "unitMemberGroupText": "組織メンバー",
    "groupName": "グループ名",
    "groupDn": "グループ全体名",
    "groupUnique": "一意のコード",

    "inputGroupInfor": "グループ名を入力してください",

    "groupReadDn": "グループの全体名は次のとおりです：{dn}",
    "groupReadCreate": "グループは{date}に作成され、最後に{date2}に編集されました",

    // "personEmployee": "工号",
    // "personDisplay": "名称",
    // "personMail": "邮件",
    "personPhone": "電話",
    "groupDescription": "グループの説明",

    "deletePersonMemberTitle": "個人メンバー削除確認",
    "deleteGroupMemberTitle": "グループメンバー削除確認",
    "deletePersonMember": "選択した個人メンバーを削除しますか？",
    "deleteGroupMember": "選択したグループメンバーを削除しますか？",

    "roleBaseText": "役割情報",
    "roleName": "役割名",
    "roleUnique": "ユニークコード",
    "roleDescription": "役割の説明",
    "roleLoaded": "役割の読み込みが完了しました",
    "roleSave": "まず役割情報を保存してください",
    "roleReadDn": "役割の全称は次のとおりです：{dn}",
    "roleReadCreate": "役割は{date}に作成され、最後に{date2}に編集されました",
    "rolePersonMembers": "個人メンバー",
    "roleGroupMembers": "グループメンバー",
    "editRole": "役割情報の編集",
    "saveRole": "役割情報の保存",
    "inputRoleInfor": "役割名を入力してください",


    "roleMemberPersonText": "個人メンバー",
    "roleMemberGroupText": "グループメンバー",

    "inputRoleName": "役割名を入力してください",

    "personLoaded": "ユーザーの読み込みが完了しました",

    "personBaseText": "ユーザー情報",

    "personSave": "まずユーザー情報を保存してください",
    "personImage": "プロフィール画像",
    "uploadImage": "プロフィール画像をアップロード",
    "personName": "ユーザー名",
    "personEmployee": "ユーザー番号",
    "personGender": "性別",
    "personDisplay": "表示名",
    "personMobile": "携帯電話番号",
    "personMail": "電子メール",
    "personQQ": "QQ番号",
    "personWeixin": "WeChat ID",
    "personWeibo": "Weibo",
    "personUnique": "ユニークコード",
    "personOfficePhone": "オフィス電話番号",
    "personBoardDate": "入社日",
    "personBirthday": "生年月日",
    "personSuperior": "上司",
    "editPerson": "ユーザー情報の編集",
    "resetPassword": "パスワードのリセット",
    "savePerson": "ユーザー情報の保存",
    "personReadDn": "ユーザーの全称は次のとおりです：{dn}",
    "personReadLogin": "ユーザーは{date}に最後にログインし、IPアドレスは{ip}、クライアントは{client}です。",
    "personReadCreate": "ユーザーは{date}に作成され、最後に{date2}に変更されました。",
    "personReadPassword": "パスワードの有効期限は{date}で、パスワードは最後に{date2}に変更されました。",
    "roleFullName": "フルネームの役割名",

    "unlockPerson": "ログインのロック解除",
    "unlockPersonTitle": "ログインのロック解除の確認",
    "unlockPersonText": "“{name}”ユーザーは指定された回数を超えてパスワードを誤って入力しました。再度ログインを許可しますか？",
    "unlockPersonSuccess": "ユーザー {name} はすでにログインできる状態です！",

    "expiredTime": "パスワードの有効期限",
    "expiredTimeTitle": "パスワードの有効期限",
    "expiredTimeSuccess": "パスワードの有効期限の設定に成功しました",
    "inputExpiredTime": "パスワードの有効期限を入力してください",
    "inputExpiredTime2": "パスワードの有効期限は現在の時間よりも過去に設定できません",

    "attributeName": "属性",
    "attributeValue": "値",

    //"inputPersonInfor": "请输入完整人员信息（人员名称、人员工号、手机号码、性别必填）",
    "inputPersonInfor": "個人情報を完全に入力してください（名前、一意のコード、携帯番号、性別は必須項目です）",
    "personAttributeText": "個人属性",
    "personIdentityText": "個人身分",
    "controllerListText": "管理者",
    "personRoleText": "個人の役割",

    "IdentityName": "身分名",
    "IdentityInUnit": "所属組織",
    "IdentityDn": "身分のフルネーム",
    "IdentityDuty": "担当職務",
    "modifyIdentity": "身分を変更",
    "IdentityMain": "メイン身分",
    "setIdentityMain": "メイン身分を設定",

    "noSignature": "個性的な署名を編集",

    "man": "男性",
    "female": "女性",
    "other": "その他",

    "changePersonIcon": "プロフィール画像を変更",
    "resetPasswordTitle": "パスワードリセットの確認",
    "resetPasswordText": "ユーザー {name} のパスワードをリセットしてもよろしいですか？",
    "resetPasswordSuccess": "ユーザー {name} のパスワードはリセットされました",

    "importPersonClean": "人員と組織データをクリア",
    "importPersonTitle": "組織のインポート/エクスポート",
    "importPersonInfor": "Excelを使用して大量の組織をインポートできます。 <a target='_blank' href='{url}'>ここをクリックして</a> 組織のインポートテンプレートをダウンロードしてください。",
    "importPersonAction": "Excelファイルをアップロードして組織をインポート",
    "importPersonResult": "データのインポートは処理されました。 <a target='_blank' href='{url}' >ここをクリックして</a> インポート結果を確認してください（検証に合格しない場合、データはインポートされません）。",
    "exportPersonText": "組織をExcelファイルにエクスポート",

    "queryPrivateConfigTitle": "個人アドレス帳の権限設定",
    "queryPrivateConfigExcludUnit": "クエリ不許可のユニット",
    "queryPrivateConfigExcludPerson": "クエリ不許可の個人",
    "queryPrivateConfigLimitOuter": "外部部門の表示制限",
    "queryPrivateConfigLimitAll": "すべての人の表示制限",
    "queryPrivateConfigDescribe": "説明",
    "queryPrivateConfigBtnEdit": "編集",
    "queryPrivateConfigBtnSave": "保存",
    "queryPrivateConfigBtnCancel": "キャンセル",

    "unitUniqueModifyNote": "注意：一意のコードを変更すると、システム内で組織の権限に影響を与える可能性があるため、慎重に変更してください",
    "personUniqueModifyNote": "注意：一意のコードを変更すると、システム内でユーザーおよび身分の権限に影響を与える可能性があるため、慎重に変更してください",
    "roleUniqueModifyNote": "注意：一意のコードを変更すると、システム内で役割の権限に影響を与える可能性があるため、慎重に変更してください",
    "groupUniqueModifyNote": "注意：一意のコードを変更すると、システム内でグループの権限に影響を与える可能性があるため、慎重に変更してください"
};
