MWF.xApplication.Org.LP = {
    "title": "조직 관리",
    "manage": "관리",
    "identity": "신분",
    "person": "개인",
    "role": "역할",
    "group": "그룹",
    "org": "조직",
    "unitList": "조직 구조",
    "groupList": "그룹 관리",
    "roleList": "역할 관리",
    "personList": "개인 관리",
    "personImport": "개인 정보 가져오기",
    "privateNamesQueryPower": "개인 주소록 조회 권한 설정",
    "application": "애플리케이션",
    "CMSApplication": "애플리케이션",
    "CMSCategory": "카테고리",
    "CMSFormField": "필드",
    "formField": "필드",
    "process": "프로세스",
    "yes": "예",
    "no": "아니오",
    "sortByPinYin": "알파벳순 정렬",
    "sortByPinYinConfirmContent": "이 작업은 해당 조직 내에서 신분을 알파벳순으로 정렬합니다. 계속하시겠습니까?",
    "sortByManual": "수동으로 정렬",

    "search": "검색",
    "searchText": "키워드를 입력하세요",
    "edit": "편집",
    "save": "저장",
    "cancel": "취소",
    "add": "추가",
    "delete": "삭제",
    "phone": "전화",
    "mail": "이메일",
    "department": "부서",
    "company": "회사",
    "duty": "직책",
    "manager": "관리",
    "ok": "확인",
    "back": "뒤로",
    "name": "이름",
    "description": "설명",
    "ipAddress": "로그인 IP",
    "ipAddressPlaceHolder": "비어 있지 않으면 매칭되는 IP만이이 계정에 로그인 할 수 있습니다. 여러 값은 쉼표로 구분됩니다.",
    "ipAddressIncorrectNotice": "IP 주소 형식이 올바르지 않습니다: ",

	"createSubCompany": "하위 회사 생성",
    "createSubDepartment": "하위 부서 생성",
    "configCompany": "회사 관리자 설정",
    "configCompanyOk": "회사 관리자 설정이 완료되었습니다. 다음 로그인 후 권한이 적용됩니다.",
    "configCompanyNull": "<font style='color: red'>회사 관리자가 지워질 것입니다. 이후에는 슈퍼 관리자와 상위 회사 관리자만이 이 회사를 편집할 수 있습니다.</font><br/><br/>이 작업을 실행하시겠습니까?",
    "configCompanyNullTitle": "회사 관리자 지우기 확인",
    "deleteOrganization": "선택한 조직 삭제",
    "deleteOrganizationTitle": "조직 삭제 확인",
    "deleteOrganizationConfirm": "선택한 조직을 삭제하시겠습니까?",
    "deleteOrganizationAllConfirm": "선택한 조직에는 여러 직무, 속성 및 멤버가 있습니다. 이 조직을 삭제하면 이러한 직무, 속성 및 멤버도 함께 삭제됩니다. 현재 작업을 계속하시겠습니까?<br/><br/>" +
        "<div style=\"color:red\">(주의: 이 작업은이러한 조직에 의존하는 다른 응용 프로그램에 오류가 발생할 수 있습니다!)</div>",
    "deleteOrganizationSubConfirm": "하나 이상의 조직을 삭제하려고 선택했습니다. 이러한 조직을 삭제하면 다음 조치가 수행됩니다:<br/>" +
        "1. 선택한 조직 및 하위 조직의 모든 직무 및 속성 삭제<br/>" +
        "2. 선택한 조직 및 하위 조직의 모든 멤버 신분 삭제<br/>" +
        "3. 선택한 조직 및 모든 하위 조직 삭제<br/>" +
        "현재 조직을 삭제하시겠습니까?<br/><br/>" +
        "<div style=\"color:red\">(주의: 이 작업은 이러한 조직에 의존하는 다른 응용 프로그램에 오류가 발생할 수 있습니다!)</div>",


    "organizationSave": "조직 정보를 먼저 저장하십시오",
    "inputOrganizationInfor": "조직 이름을 입력하십시오",

    "unitBaseText": "조직 정보",
    "unitPersonMembers": "조직 구성원",
    "unitDutys": "조직 직무",
    "unitAttribute": "조직 속성",
    "unitName": "조직 이름",
    "unitUnique": "고유 코드",
    "unitTypeList": "조직 유형",
    "unitShortName": "조직 약칭",
    "unitLevel": "조직 계층",
    "unitLevelName": "계층 이름",
    "unitControllerList": "관리자",
    "unitSuperUnit": "상위 조직",
    "unitDescription": "조직 설명",
    "editUnit": "조직 정보 편집",
    "saveUnit": "조직 정보 저장",
    "inputUnitInfor": "조직 이름 및 고유 코드를 입력하십시오",
    "orderNumber": "정렬 값",


    "unitReadDn": "조직의 전체 이름은: {dn}",
    "unitReadCreate": "조직 생성 날짜: {date}, 최종 수정 날짜: {date2}",
    "unitReadLevel": "이 조직은 {level}단계 조직이며 레벨 이름은: {levelName}",

    "dutyName": "직무 이름",
    "dutyMembers": "멤버",

    "deleteDutyTitle": "직무 삭제 확인",
    "deleteDuty": "선택한 직무를 삭제하시겠습니까?",

    "deleteDutyIdentityTitle": "직무 신분 삭제 확인",
    "deleteDutyIdentity": "{duty}에서 {identity} 삭제하시겠습니까?",

    "deleteAttributeTitle": "속성 삭제 확인",
    "deleteAttribute": "선택한 속성을 삭제하시겠습니까?",
    "deleteIdentityInDepartmentTitle": "부서에서 멤버 신분 삭제 확인",
    "deleteIdentityInDepartment": "{depart}에서 {identity}를 삭제하시겠습니까?\n신분 삭제시 해당 신분에 속한 모든 직무가 삭제됩니다. 정말로 삭제하시겠습니까?",

    "deleteGroupsTitle": "그룹 삭제 확인",
    "deleteGroupsConfirm": "선택한 그룹을 삭제하시겠습니까?",
    "deleteGroupError_InRole": "그룹 삭제 중 오류가 발생했습니다. 그룹이 역할을 보유하고 있습니다.",
    "deleteGroupError_InGroup": "그룹 삭제 중 오류가 발생했습니다. 그룹이 다른 그룹의 구성원입니다.",


    "deleteRolesTitle": "역할 삭제 확인",
    "deleteRolesConfirm": "선택한 역할을 삭제하시겠습니까?",

    "deletePersonsTitle": "사용자 삭제 확인",
    "deletePersonsConfirm": "선택한 사용자를 삭제하시겠습니까?",

    "deleteGroups": "선택한 그룹 삭제",
    "deleteRoles": "선택한 역할 삭제",
    "deletePersons": "선택한 사용자 삭제",
    "deleteUnits": "선택한 조직 삭제",
    "deleteElementsCancel": "취소",

    "deletePersonMemeberTitle": "개인 멤버 삭제 확인",
    "deletePersonMemeber": "선택한 개인 멤버를 삭제하시겠습니까?",
    "deleteGroupMemeberTitle": "그룹 멤버 삭제 확인",
    "deleteUnitMemeberTitle": "조직 멤버 삭제 확인",
    "deleteGroupMemeber": "선택한 그룹 멤버를 삭제하시겠습니까?",
    "deleteUnitMemeber": "선택한 조직 멤버를 삭제하시겠습니까?",
    "deleteIdentityMemeberTitle": "조직 멤버 삭제 확인",
    "deleteIdentityMemeber": "선택한 조직 멤버를 삭제하시겠습니까?",


    "groupLoaded": "그룹 로드 완료",
    "groupSave": "먼저 그룹 정보를 저장하십시오",
    "inputGroupName": "그룹 이름을 입력하십시오",
    "editGroup": "그룹 정보 편집",
    "saveGroup": "그룹 정보 저장",

    "groupBaseText": "그룹 정보",
    "groupMemberPersonText": "개인 멤버",
    "groupMemberIdentityText": "아이덴티티 멤버",
    "groupMemberGroupText": "그룹 멤버",
    "unitMemberGroupText": "조직 멤버",
    "groupName": "그룹 이름",
    "groupDn": "그룹 전체 이름",
    "groupUnique": "고유 코드",

    "inputGroupInfor": "그룹 이름을 입력하십시오",

    "groupReadDn": "그룹의 전체 이름은 다음과 같습니다: {dn}",
    "groupReadCreate": "그룹은 {date}에 생성되었으며 마지막으로 {date2}에 수정되었습니다.",

    // "personEmployee": "工号",
    // "personDisplay": "名称",
    // "personMail": "邮件",
    "personPhone": "전화",
    "groupDescription": "그룹 설명",

    "deletePersonMemberTitle": "개인 멤버 삭제 확인",
    "deleteGroupMemberTitle": "그룹 멤버 삭제 확인",
    "deletePersonMember": "선택한 개인 멤버를 삭제하시겠습니까?",
    "deleteGroupMember": "선택한 그룹 멤버를 삭제하시겠습니까?",

    "roleBaseText": "역할 정보",
    "roleName": "역할 이름",
    "roleUnique": "고유 코드",
    "roleDescription": "역할 설명",
    "roleLoaded": "역할 로드 완료",
    "roleSave": "먼저 역할 정보를 저장하십시오",
    "roleReadDn": "역할의 전체 이름은 다음과 같습니다: {dn}",
    "roleReadCreate": "역할은 {date}에 생성되었으며 마지막으로 {date2}에 수정되었습니다",
    "rolePersonMembers": "개인 멤버",
    "roleGroupMembers": "그룹 멤버",
    "editRole": "역할 정보 편집",
    "saveRole": "역할 정보 저장",
    "inputRoleInfor": "역할 이름을 입력하십시오",


    "roleMemberPersonText": "개인 멤버",
    "roleMemberGroupText": "그룹 멤버",

    "inputRoleName": "역할 이름을 입력하십시오",

    "personLoaded": "사용자 로드 완료",

    "personBaseText": "사용자 정보",

    "personSave": "먼저 개인 정보를 저장하십시오",
    "personImage": "프로필 사진",
    "uploadImage": "프로필 사진 업로드",
    "personName": "사용자 이름",
    "personEmployee": "사원 번호",
    "personGender": "성별",
    "personDisplay": "표시 이름",
    "personMobile": "휴대폰 번호",
    "personMail": "이메일",
    "personQQ": "QQ 번호",
    "personWeixin": "WeChat ID",
    "personWeibo": "Weibo",
    "personUnique": "고유 코드",
    "personOfficePhone": "사무실 전화번호",
    "personBoardDate": "입사일",
    "personBirthday": "생년월일",
    "personSuperior": "상사",
    "editPerson": "사용자 정보 편집",
    "resetPassword": "비밀번호 재설정",
    "savePerson": "사용자 정보 저장",
    "personReadDn": "사용자의 전체 이름은 다음과 같습니다: {dn}",
    "personReadLogin": "사용자는 {date}에 마지막으로 로그인하였으며 IP 주소는 {ip}이고 클라이언트는 {client}입니다.",
    "personReadCreate": "사용자는 {date}에 생성되었으며 마지막으로 {date2}에 수정되었습니다.",
    "personReadPassword": "비밀번호 만료 날짜는 {date}이며 비밀번호는 마지막으로 {date2}에 수정되었습니다.",
    "roleFullName": "전체 역할 이름",

    "unlockPerson": "로그인 잠금 해제",
    "unlockPersonTitle": "로그인 잠금 해제 확인",
    "unlockPersonText": "“{name}” 사용자는 지정된 횟수를 초과하여 비밀번호를 잘못 입력했습니다. 다시 로그인을 허용하시겠습니까?",
    "unlockPersonSuccess": "사용자 {name}은(는) 이제 로그인할 수 있습니다!",

    "expiredTime": "비밀번호 만료 시간",
    "expiredTimeTitle": "비밀번호 만료 시간",
    "expiredTimeSuccess": "비밀번호 만료 시간 설정 성공",
    "inputExpiredTime": "비밀번호 만료 시간을 입력하세요",
    "inputExpiredTime2": "비밀번호 만료 시간은 현재 시간 이전일 수 없습니다",

    "attributeName": "속성",
    "attributeValue": "값",

    //"inputPersonInfor": "请输入完整人员信息（人员名称、人员工号、手机号码、性别必填）",
    "inputPersonInfor": "인물 정보를 완전히 입력하세요 (이름, 고유 코드, 휴대폰 번호, 성별은 필수 입력 사항입니다)",
    "personAttributeText": "개인 속성",
    "personIdentityText": "개인 신분",
    "controllerListText": "관리자",
    "personRoleText": "개인 역할",

    "IdentityName": "신분 이름",
    "IdentityInUnit": "소속 조직",
    "IdentityDn": "신분 풀 네임",
    "IdentityDuty": "직책",
    "modifyIdentity": "신분 수정",
    "IdentityMain": "주 신분",
    "setIdentityMain": "주 신분 설정",

    "noSignature": "개인 서명 편집",

    "man": "남성",
    "female": "여성",
    "other": "기타",

    "changePersonIcon": "프로필 사진 변경",
    "resetPasswordTitle": "비밀번호 재설정 확인",
    "resetPasswordText": "사용자 {name}의 비밀번호를 재설정하시겠습니까?",
    "resetPasswordSuccess": "사용자 {name}의 비밀번호가 재설정되었습니다",

    "importPersonClean": "인원 및 조직 데이터 삭제",
    "importPersonTitle": "조직 가져오기/내보내기",
    "importPersonInfor": "Excel을 사용하여 대량 조직을 가져올 수 있습니다. <a target='_blank' href='{url}'>여기를 클릭하여</a> 조직 가져오기 템플릿을 다운로드하십시오.",
    "importPersonAction": "Excel 파일 업로드 및 조직 가져오기",
    "importPersonResult": "데이터 가져오기가 처리되었습니다. <a target='_blank' href='{url}'>여기를 클릭하여</a> 가져오기 결과를 확인하십시오 (검증에 실패한 경우 데이터가 가져와지지 않습니다).",
    "exportPersonText": "조직 내보내기를 Excel 파일로",

    "queryPrivateConfigTitle": "개인 주소록 권한 설정",
    "queryPrivateConfigExcludUnit": "조회 금지 단위",
    "queryPrivateConfigExcludPerson": "조회 금지 개인",
    "queryPrivateConfigLimitOuter": "외부 부서 조회 제한",
    "queryPrivateConfigLimitAll": "모든 사람 조회 제한",
    "queryPrivateConfigDescribe": "설명",
    "queryPrivateConfigBtnEdit": "편집",
    "queryPrivateConfigBtnSave": "저장",
    "queryPrivateConfigBtnCancel": "취소",

    "unitUniqueModifyNote": "참고: 고유 코드를 변경하면 시스템 내에서 해당 조직의 권한에 영향을 미칠 수 있으므로 신중하게 변경하십시오.",
    "personUniqueModifyNote": "참고: 고유 코드를 변경하면 시스템 내에서 해당 사용자 및 신분의 권한에 영향을 미칠 수 있으므로 신중하게 변경하십시오.",
    "roleUniqueModifyNote": "참고: 고유 코드를 변경하면 시스템 내에서 해당 역할의 권한에 영향을 미칠 수 있으므로 신중하게 변경하십시오.",
    "groupUniqueModifyNote": "참고: 고유 코드를 변경하면 시스템 내에서 해당 그룹의 권한에 영향을 미칠 수 있으므로 신중하게 변경하십시오."
};
