MWF.xApplication.Org.LP = {
    "title": "組織管理",
    "manage": "管理",
    "identity": "身份",
    "person": "個人",
    "role": "角色",
    "group": "群組",
    "org": "組織",

    "unitList": "組織架構",
    "groupList": "群組管理",
    "roleList": "角色管理",
    "personList": "個人管理",
    "personImport": "人員導入",
    "privateNamesQueryPower": "個人通訊錄查看權限配置",

    "application": "應用",
    "CMSApplication": "應用",
    "CMSCategory": "分類",
    "CMSFormField": "字段",
    "formField": "字段",
    "process": "流程",
    "yes": "是",
    "no": "否",
    "sortByPinYin": "按拼音排序",
    "sortByPinYinConfirmContent": "此操作將使本組織內身份按照拼音排序，確定操作？",
    "sortByManual": "修改",

    "search": "搜索",
    "searchText": "請輸入關鍵詞",
    "edit": "編輯",
    "save": "保存",
    "cancel": "取消",
    "add": "添加",
    "delete": "刪除",
    "phone": "手機",
    "mail": "郵件",
    "department": "部門",
    "company": "公司",
    "duty": "職位",
    "manager": "管理",
    "ok": "確定",
    "back": "返回",
    "name": "名稱",
    "description": "描述",
    "ipAddress": "登錄IP",
    "ipAddressPlaceHolder": "如果不為空，只有匹配的IP才能登錄該賬號，用“,”分隔多值",
    "ipAddressIncorrectNotice": "IP地址格式不正確：",

	"createSubCompany": "建立子公司",
    "createSubDepartment": "建立子部門",
    "configCompany": "設置公司管理員",
    "configCompanyOk": "公司管理員設置成功，權限將在下次登錄後生效",
    "configCompanyNull": "<font style='color: red'>公司管理員將被清空，清空後只有超級管理員和上層公司管理員有權編輯此公司。</font><br/><br/>您確定要執行此操作嗎？",
    "configCompanyNullTitle": "清空公司管理員確認",
    "deleteOrganization": "刪除所選組織",
    "deleteOrganizationTitle": "刪除組織確認",
    "deleteOrganizationConfirm": "您確定要刪除所選組織嗎？",
    "deleteOrganizationAllConfirm": "您選擇的組織中存在多個職務、屬性和成員，刪除此組織將同時刪除這些職務、屬性和成員，您確定要繼續當前操作嗎？<br/><br/>" +
        "<div style=\"color:red\">（注意：此操作可能會導致其他依賴於這些組織的應用程序發生錯誤！）</div>",
    "deleteOrganizationSubConfirm": "您選擇刪除一個或多個組織，刪除這些組織將執行以下操作：<br/>" +
        "1、刪除所選組織及下級組織的所有職務和屬性；<br/>" +
        "2、刪除所選組織及下級組織的所有成員身份；<br/>" +
        "3、刪除所選組織及所有下級組織；<br/>" +
        "您確定要刪除當前組織嗎？<br/><br/>" +
        "<div style=\"color:red\">（注意：此操作可能會導致其他依賴於這些組織的應用程序發生錯誤！）</div>",


    "organizationSave": "請先保存組織信息",
    "inputOrganizationInfor": "請輸入組織名稱",

    "unitBaseText": "組織信息",
    "unitPersonMembers": "組織成員",
    "unitDutys": "組織職務",
    "unitAttribute": "組織屬性",
    "unitName": "組織名稱",
    "unitUnique": "唯一編碼",
    "unitTypeList": "組織類別",
    "unitShortName": "組織簡稱",
    "unitLevel": "組織層級",
    "unitLevelName": "層級名稱",
    "unitControllerList": "管理者",
    "unitSuperUnit": "上級組織",
    "unitDescription": "組織描述",
    "editUnit": "編輯組織信息",
    "saveUnit": "保存組織信息",
    "inputUnitInfor": "請輸入組織名稱和唯一編碼",
    "orderNumber": "排序值",


    "unitReadDn": "組織的全名為：{dn}",
    "unitReadCreate": "組織建立於 {date}，最後修改於 {date2}",
    "unitReadLevel": "此組織位於第 {level} 層級，層級名稱為：{levelName}",

    "dutyName": "職務名稱",
    "dutyMembers": "成員",

    "deleteDutyTitle": "刪除職務確認",
    "deleteDuty": "您確定要刪除所選職務嗎？",

    "deleteDutyIdentityTitle": "刪除職務身份確認",
    "deleteDutyIdentity": "您確定要從“{duty}”中刪除“{identity}”嗎？",

    "deleteAttributeTitle": "刪除屬性確認",
    "deleteAttribute": "您確定要刪除所選屬性嗎？",
    "deleteIdentityInDepartmentTitle": "移除人員身份確認",
    "deleteIdentityInDepartment": "確定要從部門“{depart}”中刪除“{identity}”嗎？\n刪除身份將同時刪除此身份的所有職務，您確定要刪除嗎？",

    "deleteGroupsTitle": "刪除群組確認",
    "deleteGroupsConfirm": "您確定要刪除所選群組嗎？",
    "deleteGroupError_InRole": "刪除群組時出錯，群組擁有角色",
    "deleteGroupError_InGroup": "刪除群組時出錯，群組是其他群組成員",


    "deleteRolesTitle": "刪除角色確認",
    "deleteRolesConfirm": "您確定要刪除所選角色嗎？",

    "deletePersonsTitle": "刪除人員確認",
    "deletePersonsConfirm": "您確定要刪除所選人員嗎？",

    "deleteGroups": "刪除所選群組",
    "deleteRoles": "刪除所選角色",
    "deletePersons": "刪除所選人員",
    "deleteUnits": "刪除所選組織",
    "deleteElementsCancel": "取消",

    "deletePersonMemeberTitle": "刪除個人成員確認",
    "deletePersonMemeber": "您確定要刪除所選個人成員嗎？",
    "deleteGroupMemeberTitle": "刪除群組成員確認",
    "deleteUnitMemeberTitle": "刪除組織成員確認",
    "deleteGroupMemeber": "您確定要刪除所選群組成員嗎？",
    "deleteUnitMemeber": "您確定要刪除所選組織成員嗎？",
    "deleteIdentityMemeberTitle": "刪除組織成員確認",
    "deleteIdentityMemeber": "您確定要刪除所選組織成員嗎？",


    "groupLoaded": "群組載入完成",
    "groupSave": "請先保存群組信息",
    "inputGroupName": "請輸入群組名稱",
    "editGroup": "編輯群組信息",
    "saveGroup": "保存群組信息",

    "groupBaseText": "群組信息",
    "groupMemberPersonText": "個人成員",
    "groupMemberIdentityText": "身份成員",
    "groupMemberGroupText": "群組成員",
    "unitMemberGroupText": "組織成員",
    "groupName": "群組名稱",
    "groupDn": "群組全稱",
    "groupUnique": "唯一編碼",

    "inputGroupInfor": "請輸入群組名稱",

    "groupReadDn": "群組的全稱為：{dn}",
    "groupReadCreate": "群組創建於{date}，最後修改於：{date2}",

    // "personEmployee": "工号",
    // "personDisplay": "名称",
    // "personMail": "邮件",
    "personPhone": "電話",
    "groupDescription": "群組描述",

    "deletePersonMemberTitle": "刪除個人成員確認",
    "deleteGroupMemberTitle": "刪除群組成員確認",
    "deletePersonMember": "您確定要刪除選定的個人成員嗎？",
    "deleteGroupMember": "您確定要刪除選定的群組成員嗎？",

    "roleBaseText": "角色信息",
    "roleName": "角色名稱",
    "roleUnique": "唯一編碼",
    "roleDescription": "角色描述",
    "roleLoaded": "角色載入完成",
    "roleSave": "請先保存角色信息",
    "roleReadDn": "角色的全稱為：{dn}",
    "roleReadCreate": "角色創建於{date}，最後修改於：{date2}",
    "rolePersonMembers": "個人成員",
    "roleGroupMembers": "群組成員",
    "editRole": "編輯角色信息",
    "saveRole": "保存角色信息",
    "inputRoleInfor": "請輸入角色名稱",


    "roleMemberPersonText": "個人成員",
    "roleMemberGroupText": "群組成員",

    "inputRoleName": "請輸入角色名稱",

    "personLoaded": "用戶載入完成",

    "personBaseText": "用戶信息",

    "personSave": "請先保存個人信息",
    "personImage": "頭像",
    "uploadImage": "上傳頭像",
    "personName": "用戶名稱",
    "personEmployee": "用戶工號",
    "personGender": "性別",
    "personDisplay": "顯示名稱",
    "personMobile": "手機號碼",
    "personMail": "電子郵件",
    "personQQ": "QQ號碼",
    "personWeixin": "微信號",
    "personWeibo": "微博",
    "personUnique": "唯一編碼",
    "personOfficePhone": "辦公室電話",
    "personBoardDate": "入職時間",
    "personBirthday": "出生日期",
    "personSuperior": "報告對象",
    "editPerson": "編輯用戶信息",
    "resetPassword": "重設密碼",
    "savePerson": "保存用戶信息",
    "personReadDn": "用戶的全稱為：{dn}",
    "personReadLogin": "用戶於{date}最後一次登錄，地址為：{ip}，客戶端：{client}",
    "personReadCreate": "用戶創建於{date}，最後修改於：{date2}",
    "personReadPassword": "密碼到期時間{date}，密碼最後修改於：{date2}",
    "roleFullName": "全稱角色名稱",

    "unlockPerson": "解鎖登錄",
    "unlockPersonTitle": "解鎖登錄確認",
    "unlockPersonText": "“{name}”用戶已經連續輸錯密碼超過指定次數，是否允許重新登錄？",
    "unlockPersonSuccess": "用戶 {name} 現在可以登錄！",

    "expiredTime": "密碼到期時間",
    "expiredTimeTitle": "密碼到期時間",
    "expiredTimeSuccess": "設定密碼到期時間成功",
    "inputExpiredTime": "密碼到期時間不能為空",
    "inputExpiredTime2": "密碼到期時間不能早於當前時間",

    "attributeName": "屬性",
    "attributeValue": "值",

    //"inputPersonInfor": "请输入完整人员信息（人员名称、人员工号、手机号码、性别必填）",
    "inputPersonInfor": "請輸入完整的人員信息（人員名稱、唯一編碼、手機號碼、性別必填）",
    "personAttributeText": "個人屬性",
    "personIdentityText": "個人身份",
    "controllerListText": "管理者",
    "personRoleText": "個人角色",

    "IdentityName": "身份名稱",
    "IdentityInUnit": "所屬組織",
    "IdentityDn": "身份全稱",
    "IdentityDuty": "擔任職務",
    "modifyIdentity": "修改身份",
    "IdentityMain": "主身份",
    "setIdentityMain": "設定主身份",

    "noSignature": "編輯個性簽名",

    "man": "男性",
    "female": "女性",
    "other": "其他",

    "changePersonIcon": "更換頭像",
    "resetPasswordTitle": "重設密碼確認",
    "resetPasswordText": "您確定要為用戶 {name} 重設密碼嗎？",
    "resetPasswordSuccess": "用戶 {name} 的密碼已重設",

    "importPersonClean": "清空人員和組織數據",
    "importPersonTitle": "組織導入/導出",
    "importPersonInfor": "您可以使用Excel批量導入組織，<a target='_blank' href='{url}' >點擊此處</a> 下載組織導入模板。",
    "importPersonAction": "上傳Excel文件，導入組織",
    "importPersonResult": "數據導入已處理，<a target='_blank' href='{url}' >點擊此處</a> 查看導入結果（如果驗證未通過，則不會導入任何數據）。",
    "exportPersonText": "導出組織到Excel文件",

    "queryPrivateConfigTitle": "個人通訊錄權限配置",
    "queryPrivateConfigExcludUnit": "不允許被查詢單位",
    "queryPrivateConfigExcludPerson": "不允許被查詢個人",
    "queryPrivateConfigLimitOuter": "限制查看外部部門",
    "queryPrivateConfigLimitAll": "限制查看所有人",
    "queryPrivateConfigDescribe": "描述",
    "queryPrivateConfigBtnEdit": "編輯",
    "queryPrivateConfigBtnSave": "保存",
    "queryPrivateConfigBtnCancel": "取消",

    "unitUniqueModifyNote": "注：修改唯一編碼會影響該組織在系統中的權限，請謹慎修改",
    "personUniqueModifyNote": "注：修改唯一編碼會影響該用戶及身份在系統中的權限，請謹慎修改",
    "roleUniqueModifyNote": "注：修改唯一編碼會影響該角色在系統中的權限，請謹慎修改",
    "groupUniqueModifyNote": "注：修改唯一編碼會影響該群組在系統中的權限，請謹慎修改"
};
