/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrConfigSystem.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:49 CST 2018")
public class OkrConfigSystem_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrConfigSystem,String> configCode;
    public static volatile SingularAttribute<OkrConfigSystem,String> configName;
    public static volatile SingularAttribute<OkrConfigSystem,String> configValue;
    public static volatile SingularAttribute<OkrConfigSystem,String> description;
    public static volatile SingularAttribute<OkrConfigSystem,String> id;
    public static volatile SingularAttribute<OkrConfigSystem,Boolean> isMultiple;
    public static volatile SingularAttribute<OkrConfigSystem,Integer> orderNumber;
    public static volatile SingularAttribute<OkrConfigSystem,String> selectContent;
    public static volatile SingularAttribute<OkrConfigSystem,String> valueType;
}
