/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrTask.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:49 CST 2018")
public class OkrTask_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrTask,String> activityName;
    public static volatile SingularAttribute<OkrTask,Date> arriveDateTime;
    public static volatile SingularAttribute<OkrTask,String> arriveDateTimeStr;
    public static volatile SingularAttribute<OkrTask,String> centerId;
    public static volatile SingularAttribute<OkrTask,String> centerTitle;
    public static volatile SingularAttribute<OkrTask,String> dynamicObjectId;
    public static volatile SingularAttribute<OkrTask,String> dynamicObjectTitle;
    public static volatile SingularAttribute<OkrTask,String> dynamicObjectType;
    public static volatile SingularAttribute<OkrTask,String> id;
    public static volatile SingularAttribute<OkrTask,String> processType;
    public static volatile SingularAttribute<OkrTask,String> status;
    public static volatile SingularAttribute<OkrTask,String> targetIdentity;
    public static volatile SingularAttribute<OkrTask,String> targetName;
    public static volatile SingularAttribute<OkrTask,String> targetTopUnitName;
    public static volatile SingularAttribute<OkrTask,String> targetUnitName;
    public static volatile SingularAttribute<OkrTask,String> title;
    public static volatile SingularAttribute<OkrTask,String> viewUrl;
    public static volatile SingularAttribute<OkrTask,String> workId;
    public static volatile SingularAttribute<OkrTask,String> workTitle;
    public static volatile SingularAttribute<OkrTask,String> workType;
}
