/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrWorkAppraiseInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:49 CST 2018")
public class OkrWorkAppraiseInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> activityName;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> centerId;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> centerTitle;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> id;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> status;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> title;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> wf_jobId;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> wf_workId;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> workId;
    public static volatile SingularAttribute<OkrWorkAppraiseInfo,String> workTitle;
}
