/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrWorkChat.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:49 CST 2018")
public class OkrWorkChat_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrWorkChat,String> centerId;
    public static volatile SingularAttribute<OkrWorkChat,String> centerTitle;
    public static volatile SingularAttribute<OkrWorkChat,String> content;
    public static volatile SingularAttribute<OkrWorkChat,String> description;
    public static volatile SingularAttribute<OkrWorkChat,String> id;
    public static volatile SingularAttribute<OkrWorkChat,String> senderIdentity;
    public static volatile SingularAttribute<OkrWorkChat,String> senderName;
    public static volatile SingularAttribute<OkrWorkChat,String> targetIdentity;
    public static volatile SingularAttribute<OkrWorkChat,String> targetName;
    public static volatile SingularAttribute<OkrWorkChat,String> workId;
    public static volatile SingularAttribute<OkrWorkChat,String> workTitle;
}
