/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.okr.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.okr.entity.OkrWorkDynamics.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:49 CST 2018")
public class OkrWorkDynamics_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OkrWorkDynamics,String> centerId;
    public static volatile SingularAttribute<OkrWorkDynamics,String> centerTitle;
    public static volatile SingularAttribute<OkrWorkDynamics,String> content;
    public static volatile SingularAttribute<OkrWorkDynamics,Date> dateTime;
    public static volatile SingularAttribute<OkrWorkDynamics,String> dateTimeStr;
    public static volatile SingularAttribute<OkrWorkDynamics,String> description;
    public static volatile SingularAttribute<OkrWorkDynamics,String> dynamicObjectId;
    public static volatile SingularAttribute<OkrWorkDynamics,String> dynamicObjectTitle;
    public static volatile SingularAttribute<OkrWorkDynamics,String> dynamicObjectType;
    public static volatile SingularAttribute<OkrWorkDynamics,String> dynamicType;
    public static volatile SingularAttribute<OkrWorkDynamics,String> id;
    public static volatile SingularAttribute<OkrWorkDynamics,String> operatorName;
    public static volatile SingularAttribute<OkrWorkDynamics,String> status;
    public static volatile SingularAttribute<OkrWorkDynamics,String> targetIdentity;
    public static volatile SingularAttribute<OkrWorkDynamics,String> targetName;
    public static volatile SingularAttribute<OkrWorkDynamics,String> viewUrl;
    public static volatile SingularAttribute<OkrWorkDynamics,String> workId;
    public static volatile SingularAttribute<OkrWorkDynamics,String> workTitle;
}
