/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.ApplicationDictLobItem.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:36:06 CST 2017")
public class ApplicationDictLobItem_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ApplicationDictLobItem,Date> createTime;
    public static volatile SingularAttribute<ApplicationDictLobItem,String> data;
    public static volatile SingularAttribute<ApplicationDictLobItem,String> id;
    public static volatile SingularAttribute<ApplicationDictLobItem,String> sequence;
    public static volatile SingularAttribute<ApplicationDictLobItem,Date> updateTime;
}
