/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.ApplicationDict.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:19:07 CST 2016")
public class ApplicationDict_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<ApplicationDict,String> alias;
    public static volatile SingularAttribute<ApplicationDict,String> application;
    public static volatile SingularAttribute<ApplicationDict,Date> createTime;
    public static volatile SingularAttribute<ApplicationDict,String> description;
    public static volatile SingularAttribute<ApplicationDict,String> id;
    public static volatile SingularAttribute<ApplicationDict,String> name;
    public static volatile SingularAttribute<ApplicationDict,String> sequence;
    public static volatile SingularAttribute<ApplicationDict,Date> updateTime;
}
