/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.Route.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:19:07 CST 2016")
public class Route_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Route,String> activity;
    public static volatile SingularAttribute<Route,ActivityType> activityType;
    public static volatile SingularAttribute<Route,String> alias;
    public static volatile SingularAttribute<Route,Date> createTime;
    public static volatile SingularAttribute<Route,String> description;
    public static volatile SingularAttribute<Route,String> id;
    public static volatile SingularAttribute<Route,String> name;
    public static volatile SingularAttribute<Route,String> position;
    public static volatile SingularAttribute<Route,String> process;
    public static volatile SingularAttribute<Route,String> script;
    public static volatile SingularAttribute<Route,String> scriptText;
    public static volatile SingularAttribute<Route,String> sequence;
    public static volatile SingularAttribute<Route,String> track;
    public static volatile SingularAttribute<Route,Date> updateTime;
}
