/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.element;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.element.Split.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:10:19 CST 2017")
public class Split_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Split,String> afterArriveScript;
    public static volatile SingularAttribute<Split,String> afterArriveScriptText;
    public static volatile SingularAttribute<Split,String> afterExecuteScript;
    public static volatile SingularAttribute<Split,String> afterExecuteScriptText;
    public static volatile SingularAttribute<Split,String> afterInquireScript;
    public static volatile SingularAttribute<Split,String> afterInquireScriptText;
    public static volatile SingularAttribute<Split,String> alias;
    public static volatile SingularAttribute<Split,Boolean> allowReroute;
    public static volatile SingularAttribute<Split,Boolean> allowRerouteTo;
    public static volatile SingularAttribute<Split,String> beforeArriveScript;
    public static volatile SingularAttribute<Split,String> beforeArriveScriptText;
    public static volatile SingularAttribute<Split,String> beforeExecuteScript;
    public static volatile SingularAttribute<Split,String> beforeExecuteScriptText;
    public static volatile SingularAttribute<Split,String> beforeInquireScript;
    public static volatile SingularAttribute<Split,String> beforeInquireScriptText;
    public static volatile SingularAttribute<Split,Date> createTime;
    public static volatile SingularAttribute<Split,String> description;
    public static volatile SingularAttribute<Split,String> extension;
    public static volatile SingularAttribute<Split,String> form;
    public static volatile SingularAttribute<Split,String> id;
    public static volatile SingularAttribute<Split,String> name;
    public static volatile SingularAttribute<Split,String> position;
    public static volatile SingularAttribute<Split,String> process;
    public static volatile ListAttribute<Split,String> readDataPathList;
    public static volatile ListAttribute<Split,String> readDepartmentList;
    public static volatile SingularAttribute<Split,String> readDuty;
    public static volatile ListAttribute<Split,String> readIdentityList;
    public static volatile SingularAttribute<Split,String> readScript;
    public static volatile SingularAttribute<Split,String> readScriptText;
    public static volatile ListAttribute<Split,String> reviewDataPathList;
    public static volatile ListAttribute<Split,String> reviewDepartmentList;
    public static volatile SingularAttribute<Split,String> reviewDuty;
    public static volatile ListAttribute<Split,String> reviewIdentityList;
    public static volatile SingularAttribute<Split,String> reviewScript;
    public static volatile SingularAttribute<Split,String> reviewScriptText;
    public static volatile SingularAttribute<Split,String> route;
    public static volatile SingularAttribute<Split,String> script;
    public static volatile SingularAttribute<Split,String> scriptText;
    public static volatile SingularAttribute<Split,String> sequence;
    public static volatile SingularAttribute<Split,Date> updateTime;
}
