/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.file.core.entity.personal;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.file.core.entity.personal.Folder.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:37 CST 2018")
public class Folder_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Folder,String> id;
    public static volatile SingularAttribute<Folder,String> name;
    public static volatile SingularAttribute<Folder,String> person;
    public static volatile SingularAttribute<Folder,String> superior;
}
