/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.portal.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.portal.core.entity.Menu.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:35:54 CST 2017")
public class Menu_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Menu,String> alias;
    public static volatile SingularAttribute<Menu,Date> createTime;
    public static volatile SingularAttribute<Menu,String> data;
    public static volatile SingularAttribute<Menu,String> description;
    public static volatile SingularAttribute<Menu,String> id;
    public static volatile SingularAttribute<Menu,String> name;
    public static volatile SingularAttribute<Menu,String> portal;
    public static volatile SingularAttribute<Menu,String> sequence;
    public static volatile SingularAttribute<Menu,Date> updateTime;
}
