/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.portal.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.portal.core.entity.Source.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:35:54 CST 2017")
public class Source_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Source,String> alias;
    public static volatile SingularAttribute<Source,Date> createTime;
    public static volatile SingularAttribute<Source,String> data;
    public static volatile SingularAttribute<Source,String> description;
    public static volatile SingularAttribute<Source,String> id;
    public static volatile SingularAttribute<Source,String> name;
    public static volatile SingularAttribute<Source,String> portal;
    public static volatile SingularAttribute<Source,String> sequence;
    public static volatile SingularAttribute<Source,Date> updateTime;
}
