/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package o2.collect.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=o2.collect.core.entity.Code.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat Aug 25 23:06:36 CST 2018")
public class Code_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Code,String> answer;
    public static volatile SingularAttribute<Code,Date> expiredTime;
    public static volatile SingularAttribute<Code,String> id;
    public static volatile SingularAttribute<Code,String> meta;
    public static volatile SingularAttribute<Code,String> mobile;
}
