/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package o2.collect.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=o2.collect.core.entity.Module.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat Aug 25 23:06:36 CST 2018")
public class Module_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Module,String> brief;
    public static volatile SingularAttribute<Module,String> category;
    public static volatile SingularAttribute<Module,String> data;
    public static volatile SingularAttribute<Module,String> icon;
    public static volatile SingularAttribute<Module,String> id;
    public static volatile SingularAttribute<Module,String> name;
}
