MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.BAM = MWF.xApplication.BAM || {};
MWF.xApplication.BAM.LP={
	"title": "Monitoreo del proceso",
	"summaryTitle": "Estado actual",
	"monthlyTitle": "Estadísticas mensuales",
	"applicationCount": "Aplicaciones",
	"processCount": "Procesos",
	"usedApplicationCount": "Aplicaciones utilizadas",
	"usedProcessCount": "Procesos utilizados",
	"taskCount": "Pendiente",
	"taskCompletedCount": "hecho",
	"readCount": "pend. lectura",
	"readCompletedCount": "lectura",
	"workCount": "En proceso",
	"workCompletedCount": "Completado",
	"expired": "Vencido",
	"taskElapsedTitle": "Pendiente",
	"workElapsedTitle": "proceso",
	"taskElapsedCountTitle": "Vencido pendiente (%)",
	"workElapsedCountTitle": "Vencido proceso (%)",
	"proportion": "prop.",
	"distribution": "dist.",
	"count": "cant.",
	"top10": "TOP10",
	"taskRankTypeExpired": "tiempo proc.",
	"taskRankTypeExpiredCount": "cant. vencida",
	"taskRankTypeCompletedCount": "cant. proc.",
	"taskRankTypeCompletedTimeliness": "tasa oport.",
	"unit": "org.",
	"company": "emp.",
	"department": "dep.",
	"person": "ind.",
	"application": "app.",
	"process": "proc.",
	"activity": "act.",
	"task": "Pendiente",
	"taskCompleted": "hecho",
	"work": "En proceso",
	"workCompleted": "Completado",
	"contentTypeCount": "cantidad",
	"contentTypeExpired": "tiempo perm.",
	"contentTypeExpiredCount": "cant. vencida",
	"taskContentTypeExpiredCount": "cant. vencida",
	"contentTypeDuration": "tiempo proc.",
	"timeliness": "tasa oport.%",
	"timeout": "tasa venc.%",
	"taskElapsed": {
		"halfDay": "Menos de 12 horas",
		"oneDay": "12-24 horas",
		"twoDay": "24-48 horas",
		"threeDay": "2-3 días",
		"moreDay": "Más de 3 días"
	},
	"workElapsed": {
		"threeDay": "Menos de 3 días",
		"oneWeek": "3-7 días",
		"twoWeek": "1-2 semanas",
		"oneMonth": "2 semanas - 1 mes",
		"moreMonth": "Más de 1 mes"
	},
	"other": "Otro",
	"monthly": {
		"task": "Cantidad de tareas pendientes generadas",
		"taskCompleted": "Cantidad de tareas completadas",
		"work": "Cantidad de procesos iniciados",
		"workCompleted": "Cantidad de procesos completados",
		"taskExpired": "Cantidad de tareas vencidas",
		"workExpired": "Cantidad de procesos vencidos",
		"sort": "Clasificación",
		"sortInfor": {
			"application": "Por aplicación",
			"process": "Por proceso de la aplicación “{app}”",
			"activity": "Por actividad del proceso “{pro}” de la aplicación “{app}”",
			"topUnit": "Por organización superior",
			"unit": "Por organizaciones subordinadas de “{unit}”",
			"company": "Por empresa",
			"department": "Por departamento de la empresa “{com}”"
		},
		"filter": "Filtrar",
		"filterInfor": {
			"all": "Todo",
			"unit": "Organización: {name}",
			"company": "Empresa: {name}",
			"department": "Departamento: {name}",
			"person": "{name}",
			"application": "Aplicación: {name}",
			"process": "Proceso: {name}",
			"activity": "Actividad: {name}"
		},
		"columnTitle": {
			"application": "Aplicación",
			"process": "Proceso",
			"activity": "Actividad",
			"company": "Empresa",
			"department": "Departamento"
		},
		"year": "Año",
		"month": "Mes",
		"selecteAll": "Seleccionar todo",
		"selecteAllCol": "Seleccionar todas las columnas",
		"selecteAllRow": "Seleccionar todas las filas",
		"sortItems": {
			"topUnit": "Organización superior",
			"unit": "Organización",
			"company": "Por empresa",
			"department": "Por departamento",
			"application": "Por aplicación",
			"process": "Por proceso",
			"activity": "Por actividad"
		},
		"filterItems": {
			"unit": "Filtrar organización",
			"company": "Filtrar empresa",
			"department": "Filtrar departamento",
			"application": "Filtrar aplicación",
			"process": "Filtrar proceso"
		},
		"selectSortUnit": "Seleccionar organización",
		"selectSortCompany": "Seleccionar empresa",
		"selectSortApplication": "Seleccionar aplicación",
		"selectSortProcess": "Seleccionar proceso"
	}
}
MWF.xApplication.BAM["lp."+o2.language] = MWF.xApplication.BAM.LP