MWF.xApplication.cms.ColumnManager.LP = {
    "title": "Content Management Column Settings",
    "categoryTitle": "Category Management",
    "description": "Description",
    "deleteItems": "Delete selected items",

    "copy": "Copy",
    "copyto": "Copy to...",
    "copyInfor": "Select multiple elements, press Ctrl+C to copy the elements, press Ctrl+V to paste the copied elements into the current application",
    "copyed": "The selected element has been copied",
    "copyConfirmTitle": "Copy element confirmation",
    "copyConfirmInfor": "The target area already contains the same elements:",
    "copySource": "Original file:",
    "copyTarget": "Copy file:",
    "copyConfirm_overwrite": "Replace",
    "copyConfirm_new": "New",
    "copyConfirm_skip": "Skip",
    "copyConfirm_cancel": "Cancel",
    "copynew": "New",

    "setting": "Settings",

    "ok": "OK",
    "edit": "Edit",
    "save": "Save",
    "cancel": "Cancel",

    "phone": "Mobile",
    "mail": "Mail",

    "deleteElementTitle": "Delete Design Confirmation",
    "deleteElement": "Are you sure you want to delete the selected design element?",

    "setControllerSuccess": "Set Controller Success",
    "noAdministratorAccess": "You do not have the administrative authority for this column",

    "createSelectTemplate": "New: Select Template",
    "templateCategory": "Template Category:",
    "all": "All",

    "formType": {
        "empty": "Empty form",
        "publishEdit": "Publish Edit Form",
        "publishRead": "Publish Reading Form",
        "dataInput": "Data Input Form"
    },

    "category": {
        "create": "New category",
        "search": "Search Category",
        "searchText": "Please enter a keyword",

        "noCategoryNoticeText": "This AppInfo Doesn't has category, you can click here to create a new category",
        "loaded": "Category loaded",

        "deleteCategoryTitle": "Delete Category Confirmation",
        "deleteCategoryConfirm": "Are you sure you want to delete the current category?",
        "deleteFailAsHasDocument": "Failed to delete category '{title}', please delete the document under this category first.",

        "idLabel": "Category Label",
        "nameLabel": "Category Name",
        "aliasLabel": "Category Alias",
        "descriptionLabel": "Category description",
        "sortLabel": "Queue Number",
        "columnLabel": "AppInfo",
        "iconLabel": "Category Icon",
        "formLabel": "Corresponding form",
        "formLabelEdit": "Edit Status Form",
        "formLabelRead": "Reading status form",
        "viewLabel": "Use List",
        "defaultViewLabel": "Default List",
        "cancel": "Cancel",
        "ok": "OK",
        "inputName":"Please enter the category name",
        "create_cancel_title": "Cancel New Category Confirmation",
        "create_cancel": "Are you sure you want to cancel the new category?",
        "noDescription": "There is no description for this category",
        "delete": "Delete category",
        "edit": "Edit category",
        "createCategorySuccess": "Category created successfully",
        "updateCategorySuccess": "Category modified succeeded",
        "defaultView": "Default",
        "insertCateogryBefore": "Insert Category",
        "insertCateogryAfter": "Add Category",
        "deleteCategory": "Delete Category",
        "moveCategory": "Adjust the sort order",
        "saveCategory": "Save Category",
        "editCategory": "Edit Category",
        "cancelEdit": "Cancel",
        "categoryProperty": "Category Property",
        "baseProperty": "Basic Property",
        "useProcess": "Use Process",
        "setProcessAppSucess": "Set Process App Sucess",
        "setProcessSucess":"Set Process Sucess",
        "selectProcess":"Select Process",
        "selectProcessApp":"Select Process App",
        "setCategoryManager": "Set Category Manager",
        "none": "None",
        "noProcess": "There is no process in the system that you can manage",
        "documentType": "Document Type",
        "excelImportView": "Data Import and Export View"
    },
    "form": {
        "create": "New Form",
        "search": "Search Form",
        "searchText": "Please enter a keyword",
        "selectCategoryForm": "Select category form",

        "noFormNoticeText": "There is no form in this column, you can click here to create a new form",
        "loaded": "The form is loaded",
        "deleteFormTitle": "Delete Form Confirmation",
        "deleteForm": "Deleting a form will also delete the associated list of this form. Are you sure you want to delete the current form?",

        "deleteFormTemplateTitle": "Confirm to delete form template",
        "deleteFormTemplate": "Are you sure you want to delete the current template?"
    },
    "view": {
        "create": "New List",
        "search": "Search List",
        "searchText": "Please enter a keyword",
        "selectRelativeForm": "Select Relative Form",

        "noViewNoticeText": "There is no list for this AppInfo, you can click here to create a list",
        "noViewNoCreateNoticeText": "There is no list for this AppInfo now",
        "loaded": "The list is loaded",
        "deleteFormTitle": "Confirm Delete List",
        "deleteForm": "Are you sure you want to delete the current list?",
        "selectRelativeFormNoticeText": "Please select the related form of the view to be pasted"
    },
    "dictionary": {
        "create": "Create a new data dictionary",
        "search": "Search Data Dictionary",
        "searchText": "Please enter a keyword",

        "noDictionaryNoticeText": "There is no data dictionary for this AppInfo, you can click here to create a new data dictionary",
        "noDictionaryNoCreateNoticeText": "There is no data dictionary for this AppInfo now",
        "loaded": "Data dictionary loaded",
        "deleteFormTitle": "Confirm Delete Data Dictionary",
        "deleteForm": "Are you sure you want to delete the current data dictionary?"
    },
    "script": {
        "create": "New Script",
        "search": "Search script",
        "searchText": "Please enter a keyword",

        "noScriptNoticeText": "There is no script for this column, you can click here to create a new script",
        "loaded": "Script loaded",
        "deleteFormTitle": "Delete Script Confirmation",
        "deleteForm": "Are you sure you want to delete the current script?"
    },
    "application": {
        "inputApplicationName": "Please enter the AppInfo name",
        "saveSuccess": "Save successfully",
        "id": "AppInfo ID",
        "property": "Basic Properties",
        "name": "AppInfo Name",
        "alias": "AppInfo alias",
        "description": "AppInfo Description",
        "sort": "AppInfo Sorting",
        "documentType": "Document Type",
        "showAllDocumentViews": "AppInfo Views",
        "icon": "AppInfo Icon",
        "sign": "AppInfo alias",
        "controllerList": "Manager",
        "appType": "AppInfo Type",
        "ignoreTitle": "Ignore Title",
        "latest": "Check Draft",
        viewerSetting: {
            title: "Visible Range",
            set: "Set visible range",
            setSuccess: "Set visible range successfully"
        },
        publisherSetting: {
            title: "Publisher",
            set: "Set Publisher",
            setSuccess: "Successfully set publisher"
        },
        managerSetting: {
            title: "Manager",
            set: "Set Manager",
            setSuccess: "Set manager success"
        }
    },
    "queryView": {
        "create": "New Data View",
        "search": "Search Data View",
        "searchText": "Please enter a keyword",
        "selectRelativeForm": "Select View Related Form",

        "noViewNoticeText": "There is no data view for this column, you can click here to create a data view",
        "noViewNoCreateNoticeText": "There is no data view for this AppInfo now",
        "loaded": "Data view loaded",
        "deleteFormTitle": "Delete Data View Confirmation",
        "deleteForm": "Are you sure you want to delete the current data view?"
    },
    "file": {
        "create": "Create a new attachment",
        "search": "Search for attachments",
        "searchText": "Please enter a keyword",
        "description": "Attachment Information",

        "noScriptNoticeText": "This app has no attachments yet, you can click here to create a new attachment",
        "loaded": "Attachment is loaded",
        "deleteFormTitle": "Confirm Delete Attachment",
        "deleteForm": "Are you sure you want to delete the current attachment?",
        "saveSuccess": "The attachment has been saved!",
        "saveConfirm": "Save Confirmation",
        "saveConfirmText": "The attachment has been modified, do you want to save the modified content?",
        "uploadSuccess": "Attachment has been uploaded",
        "loadFiles": "Batch upload attachments"
    },

    "name": "Name",
    "alias": "Alias",
    "attachment": "Attachment",
    "upload": "Upload attachments",

    "selectDataView": "Select Data View",
    "selectDataViewTitle": "Select from an existing data view",

    "selectList": "Select List",
    "selectListTitle": "Select from an existing list",

    "categoryDisplay": "Category Display",
    "setCategoryListSuccess": "Set the category list successfully",
    "setDefaultViewSuccess": "Set the default view successfully",
    "cancelCategoryListSuccess": "Cancel the category list successfully",
    "setImpExpViewSuccess": "Set the category import and export view successfully",
    "setCategoryAliasSuccess": "Set category alias successfully",
    "setDocumentTypeSuccess": "Set the document type successfully",
    "setEditFormSuccess": "Set Edit Form Success",
    "setReadFormSuccess": "Set Read Form Success",
    "inputCategoryNotice": "Please enter the category name",
    "noCategoryNotice": "Please create or select a category first",
    "saveCategoryNotice":"Please save the category first",
    "dragToDesktopNotice": "Can be dragged to the desktop",
    "asEditForm": "Set as Edit Form",
    "asReadForm": "Set as Reading Form",
    "delete": "Delete",
    "notAddListOrView": "Not added list or data view",
    "systemList": "System List",
    "selectCategoryNotice":"Please select a category first",
    "conflictedListNotice": "The list {text} already exists, so won’t add it again!",
    "selectView": "Select View",
    "conflictedViewNotice": "The view {text} already exists, so won’t add it again!",
    "list": "List",
    "view1": "View",
    "setAsDefaultList": "Set As Default List",
    "adjustOrder": "Adjust Order",
    "cancelEdit": "Cancel Edit",
    "enableProcess": "Enable the approval process",
    "disableProcess": "Disable the approval process",
    "documentTypeSelectValue": ["信息","数据"],
    "documentTypeSelectText": ["Information","Data"],
    "infor": "Information",
    "data": "Data",
    "type": "Type",
    "listName": "List Name",
    "relativeForm": "Related Form",
    "dataView": "Data View",
    "viewName": "View Name",
    "column": "AppInfo",

    "categorySetting": "Category Configuration",
    "formSetting": "Form Configuration",
    "dataSetting": "Data Configuration",
    "scriptSetting": "Script Editing",
    "listSetting": "List Configuration",
    "queryViewSetting": "dataView Configuration",
    "attachmentSetting": "Attachment Setting",
    "resourceFile": "Resource File",
    "findDesign": "Search Code",
    "new": "New",
    "appProperty": "App Property",
    "changeIcon": "Change Icon",
    "ignoreTitleSelectText": ["Do not fill in the title of the new interface", "The title of the new interface needs to be filled in"],
    "checkDraftSelectText": ["New interface check draft","New interface does not check draft"],
    "showAllDocumentSelectText": ["Show all document views","Hide all document views"],

    "selectRelateFormNotice": "Please select the related form of the view to be pasted"
};