MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.ColumnManager = MWF.xApplication.cms.ColumnManager || {};
MWF.xApplication.cms.ColumnManager.LP={
	"title": "Configuración de la categoría",
	"categoryTitle": "Administración de categorías",
	"description": "Descripción",
	"deleteItems": "Eliminar los elementos seleccionados",
	"copy": "Copiar",
	"copyto": "Copiar a...",
	"copyInfor": "Seleccione varios elementos y presione Ctrl + C para copiarlos. Luego, presione Ctrl + V para pegar los elementos copiados en la aplicación actual.",
	"copyed": "Los elementos seleccionados se han copiado.",
	"copyConfirmTitle": "Confirmación",
	"copyConfirmInfor": "La zona de destino ya contiene elementos idénticos:",
	"copySource": "Archivo original:",
	"copyTarget": "Archivo copiado:",
	"copyConfirm_overwrite": "Reemplazar",
	"copyConfirm_new": "Nuevo",
	"copyConfirm_skip": "Saltar",
	"copyConfirm_cancel": "Cancelar",
	"copynew": "Nuevo",
	"setting": "Configuración",
	"ok": "Aceptar",
	"edit": "Editar",
	"save": "Guardar",
	"cancel": "Cancelar",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"deleteElementTitle": "Confirmación",
	"deleteElement": "¿Está seguro de que desea eliminar los elementos de diseño seleccionados?",
	"setControllerSuccess": "Se estableció el controlador con éxito.",
	"noAdministratorAccess": "No tiene permisos de administrador para este categoría.",
	"createSelectTemplate": "Crear: Seleccionar plantilla",
	"templateCategory": "Categoría de plantilla:",
	"all": "Todos",
	"formType": {
		"empty": "Formulario en blanco",
		"publishEdit": "Formulario de edición de publicación",
		"publishRead": "Formulario de lectura de publicación",
		"publishEditGreen": "Formulario de edición de publicación (verde)",
		"publishReadGreen": "Formulario de lectura de publicación (verde)",
		"dataInput": "Formulario de entrada de datos"
	},
	"category": {
		"create": "Crear categoría",
		"search": "Buscar categoría",
		"searchText": "Ingrese una palabra clave",
		"noCategoryNoticeText": "Actualmente no hay categorías en esta categoría. Puede hacer clic aquí para crear una nueva categoría.",
		"loaded": "Categorías cargadas correctamente.",
		"deleteCategoryTitle": "Confirmación",
		"deleteCategoryConfirm": "¿Está seguro de que desea eliminar esta categoría?",
		"deleteFailAsHasDocument": "Error al eliminar la categoría “{title}”. Primero, elimine los documentos que pertenecen a esta categoría.",
		"idLabel": "Identificación",
		"nameLabel": "Nombre",
		"aliasLabel": "Alias",
		"sendNotify": "¿Enviar notificación al publicar?",
		"sendNotifyInfo": "La estrategia específica de notificación se configura en el formulario.",
		"blankToAllNotify": "¿Notificar a todos cuando el alcance de publicación esté vacío?",
		"descriptionLabel": "Descripción",
		"sortLabel": "Orden",
		"columnLabel": "Pertenece",
		"iconLabel": "Ícono",
		"formLabel": "Formulario",
		"formLabelEdit": "Formulario en estado de edición",
		"formLabelRead": "Formulario en estado de lectura",
		"viewLabel": "Lista de uso",
		"defaultViewLabel": "Lista predeterminada",
		"cancel": "Cancelar",
		"ok": "Aceptar",
		"inputName": "Ingrese el nombre de la categoría",
		"create_cancel_title": "Confirmación",
		"create_cancel": "¿Está seguro de que desea cancelar la creación de una nueva categoría?",
		"noDescription": "Esta categoría no tiene descripción.",
		"delete": "Eliminar categoría",
		"edit": "Editar categoría",
		"createCategorySuccess": "Categoría creada correctamente.",
		"updateCategorySuccess": "Categoría actualizada correctamente.",
		"defaultView": "Predeterminado",
		"insertCateogryBefore": "Insertar categoría",
		"insertCateogryAfter": "Agregar categoría",
		"deleteCategory": "Eliminar categoría",
		"moveCategory": "Ajustar orden de categoría",
		"saveCategory": "Guardar categoría",
		"editCategory": "Editar categoría",
		"cancelEdit": "Cancelar",
		"categoryProperty": "Propiedades de categoría",
		"baseProperty": "Propiedades básicas",
		"useProcess": "Usar proceso",
		"setProcessAppSucess": "Proceso de aplicación configurado correctamente.",
		"setProcessSucess": "Proceso configurado correctamente.",
		"selectProcess": "Seleccionar proceso",
		"selectProcessApp": "Seleccionar proceso de aplicación",
		"setCategoryManager": "Configuración de administrador de categoría",
		"none": "Ninguno",
		"noProcess": "No hay procesos disponibles para que usted administre en el sistema.",
		"documentType": "Tipo de documento",
		"excelImportView": "Vista de importación y exportación de datos",
		"useProcessForm": "Usar formulario de proceso",
		"useProcessFormNote": "Nota: Si usa un formulario de proceso, se abrirá el documento publicado utilizando el formulario de proceso. De lo contrario, se usará el formulario configurado en la categoría.",
		"setSucess": "Configuración exitosa"
	},
	"form": {
		"create": "Crear formulario",
		"search": "Buscar formulario",
		"searchText": "Ingrese la palabra clave",
		"selectCategoryForm": "Seleccionar formulario de categoría",
		"noFormNoticeText": "Actualmente no hay formularios en esta categoría. Puede hacer clic aquí para crear un nuevo formulario.",
		"loaded": "El formulario se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el formulario actual?",
		"deleteFormTemplateTitle": "Confirmación",
		"deleteFormTemplate": "¿Está seguro de que desea eliminar la plantilla de formulario actual?"
	},
	"view": {
		"create": "Crear lista",
		"search": "Buscar lista",
		"searchText": "Ingrese una palabra clave",
		"selectRelativeForm": "Seleccionar formulario de lista relacionado",
		"noViewNoticeText": "Este elemento de diseño está obsoleto. Utilice una vista o configuración de consulta para mostrar los datos.",
		"noViewNoCreateNoticeText": "Actualmente no hay listas en esta categoría.",
		"loaded": "Listas cargadas correctamente.",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar esta lista?",
		"selectRelativeFormNoticeText": "Seleccione el formulario relacionado al cual desea pegar la vista."
	},
	"dictionary": {
		"create": "Crear diccionario de datos",
		"search": "Buscar diccionario de datos",
		"searchText": "Ingrese la palabra clave",
		"noDictionaryNoticeText": "Esta aplicación aún no tiene ningún diccionario de datos. Puede hacer clic aquí para crear uno nuevo.",
		"noDictionaryNoCreateNoticeText": "Esta aplicación no tiene ningún diccionario de datos en este momento.",
		"loaded": "El diccionario de datos se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el diccionario de datos actual?"
	},
	"script": {
		"create": "Crear script",
		"search": "Buscar script",
		"searchText": "Ingrese la palabra clave",
		"noScriptNoticeText": "Esta aplicación aún no tiene ningún script. Puede hacer clic aquí para crear uno nuevo.",
		"loaded": "El script se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el script actual?"
	},
	"application": {
		"inputApplicationName": "Ingrese el nombre de la categoría",
		"saveSuccess": "Guardado correctamente.",
		"id": "Identificación",
		"property": "Propiedades básicas",
		"name": "Nombre",
		"alias": "Alias",
		"description": "Descripción",
		"sort": "Orden",
		"documentType": "Tipo de documento",
		"showAllDocumentViews": "Vista del documento en la categoría",
		"icon": "Ícono",
		"sign": "Alias",
		"controllerList": "Lista de administradores",
		"appType": "Tipo de categoría",
		"ignoreTitle": "Ignorar título",
		"latest": "Comprobar borrador",
		"delayView": "Vista programada",
		"defaultEditForm": "Formulario de edición predeterminado",
		"defaultReadForm": "Formulario de lectura predeterminado",
		"editformNote": "Nota: El formulario predeterminado para editar cuando se crea una nueva categoría.",
		"readformNote": "Nota: El formulario predeterminado para leer cuando se crea una nueva categoría. Si no se selecciona, será igual que el formulario de edición.",
		"viewerSetting": {
			"title": "Alcance de visibilidad",
			"set": "Establecer alcance de visibilidad",
			"setSuccess": "Alcance de visibilidad establecido correctamente."
		},
		"publisherSetting": {
			"title": "Publicador",
			"set": "Establecer publicador",
			"setSuccess": "Publicador establecido correctamente."
		},
		"managerSetting": {
			"title": "Administrador",
			"set": "Establecer administrador",
			"setSuccess": "Administrador establecido correctamente."
		},
		"saveDraftOnClose": "Guardar automáticamente"
	},
	"queryView": {
		"create": "Crear vista",
		"search": "Buscar vista",
		"searchText": "Ingrese la palabra clave",
		"selectRelativeForm": "Seleccionar formulario de vista relacionado",
		"noViewNoticeText": "Actualmente no hay vistas en esta categoría. Puede hacer clic aquí para crear una nueva vista.",
		"noViewNoCreateNoticeText": "Actualmente no hay vistas en esta categoría.",
		"loaded": "Vistas cargadas correctamente.",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar esta vista?"
	},
	"file": {
		"create": "Crear archivo adjunto",
		"search": "Buscar archivo adjunto",
		"searchText": "Ingrese la palabra clave",
		"description": "Información del archivo adjunto",
		"noScriptNoticeText": "Esta aplicación aún no tiene ningún archivo adjunto. Puede hacer clic aquí para crear uno nuevo.",
		"loaded": "El archivo adjunto se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el archivo adjunto actual?",
		"saveSuccess": "¡El archivo adjunto se ha guardado!",
		"saveConfirm": "Confirmación de guardar",
		"saveConfirmText": "Se han realizado cambios en el archivo adjunto. ¿Desea guardar los cambios?",
		"uploadSuccess": "El archivo adjunto se ha cargado correctamente",
		"loadFiles": "Cargar archivos de forma masiva"
	},
	"enable": "Activar",
	"disable": "Desactivar",
	"name": "Nombre",
	"alias": "Alias",
	"attachment": "Adjunto",
	"upload": "Cargar adjunto",
	"selectDataView": "Seleccionar vista",
	"selectDataViewTitle": "Seleccionar desde vistas existentes",
	"selectList": "Seleccionar lista",
	"selectListTitle": "Seleccionar desde listas existentes",
	"categoryDisplay": "Visualización de categoría",
	"setCategoryListSuccess": "Lista de categoría establecida correctamente.",
	"setDefaultViewSuccess": "Vista predeterminada establecida correctamente.",
	"cancelCategoryListSuccess": "Lista de categoría cancelada correctamente.",
	"setImpExpViewSuccess": "Vista de importación y exportación de categorías establecida correctamente.",
	"setCategoryAliasSuccess": "Alias de categoría establecido correctamente.",
	"setDocumentTypeSuccess": "Tipo de documento establecido correctamente.",
	"setSendNotifySuccess": "Configuración de envío de notificaciones establecida correctamente.",
	"setBlankToAllNotifySuccess": "Configuración de enviar notificaciones cuando el rango de publicación está vacío establecida correctamente.",
	"setEditFormSuccess": "Formulario de edición establecido correctamente.",
	"setReadFormSuccess": "Formulario de lectura establecido correctamente.",
	"setProjectionSuccess": "Mapeo de datos establecido correctamente.",
	"inputCategoryNotice": "Ingrese el nombre de la categoría.",
	"noCategoryNotice": "Por favor, cree o seleccione una categoría primero.",
	"saveCategoryNotice": "Por favor, guarde la categoría primero.",
	"dragToDesktopNotice": "Se puede arrastrar al escritorio.",
	"asEditForm": "Establecer como formulario de edición.",
	"asReadForm": "Establecer como formulario de lectura.",
	"delete": "Eliminar",
	"notAddListOrView": "No se han agregado listas o vistas de datos.",
	"systemList": "Listas del sistema",
	"selectCategoryNotice": "Seleccione una categoría primero.",
	"conflictedListNotice": "La lista {text} ya existe y no se puede agregar nuevamente.",
	"selectView": "Seleccionar vista",
	"conflictedViewNotice": "La vista {text} ya existe y no se puede agregar nuevamente.",
	"list": "Lista",
	"view1": "Vista",
	"setAsDefaultList": "Establecer como lista predeterminada de la categoría",
	"adjustOrder": "Ajustar orden",
	"cancelEdit": "Cancelar edición",
	"enableProcess": "Habilitar flujo de aprobación fijo",
	"disableProcess": "Desactivar flujo de aprobación",
	"documentTypeSelectValue": [
		"Información",
		"Datos"
	],
	"documentTypeSelectText": [
		"Información",
		"Datos"
	],
	"sendNotifySelectText": [
		"Sí",
		"No"
	],
	"sendNotifySelectValue": [
		"true",
		"false"
	],
	"blankToAllNotifySelectText": [
		"Sí",
		"No"
	],
	"blankToAllNotifySelectValue": [
		"true",
		"false"
	],
	"infor": "Información",
	"data": "Datos",
	"type": "Tipo",
	"listName": "Nombre de la lista",
	"relativeForm": "Formulario relacionado",
	"dataView": "Vista de datos",
	"viewName": "Nombre de la vista",
	"column": "Columna",
	"categorySetting": "Categoría",
	"formSetting": "Formulario",
	"dataSetting": "Datos",
	"scriptSetting": "Script",
	"listSetting": "Lista",
	"queryViewSetting": "Vista de consulta",
	"attachmentSetting": "Adjunto",
	"resourceFile": "Archivo de recurso",
	"findDesign": "Buscar diseño",
	"new": "Nuevo",
	"appProperty": "Propiedad",
	"changeIcon": "Cambiar ícono",
	"ignoreTitleSelectText": [
		"No rellenar título en la interfaz de creación",
		"Rellenar título en la interfaz de creación"
	],
	"checkDraftSelectText": [
		"Verificar borrador en la interfaz de creación",
		"No verificar borrador en la interfaz de creación"
	],
	"showAllDocumentSelectText": [
		"Mostrar todas las vistas de documentos",
		"Ocultar todas las vistas de documentos"
	],
	"showDelayDocumentSelectText": [
		"Mostrar vista de publicación programada de documentos",
		"Ocultar vista de publicación programada de documentos"
	],
	"selectRelateFormNotice": "Seleccione el formulario relacionado en el que desea pegar la vista",
	"projectionTitle": "Mapeo de datos empresariales",
	"projectionActionNode_add": "Agregar elemento de mapeo",
	"projectionActionNode_modify": "Modificar elemento de mapeo",
	"projectionDataName": "Nombre del dato",
	"projectionPath": "Ruta del dato",
	"projectionType": "Tipo de dato",
	"projectionColumnName": "nombre de la columna",
	"projectionInputError": "Por favor ingrese un nombre y una ruta para el dato.",
	"projectionTypeCountError": "Solo se permiten un máximo de {count} elementos de mapeo de datos de tipo {type}.",
	"projectionSameNameError": "Ya existe un elemento de mapeo de datos con el mismo nombre.",
	"projectionDeleteItemTitle": "Confirmación",
	"projectionDeleteItem": "¿Está segur@ de que desea eliminar el elemento de mapeo de datos llamado \"{name}\" con la ruta \"{path}\"?",
	"projectionRunActionNode": "Ejecutar mapeo de datos inmediatamente",
	"projectionRunTitle": "Confirmación",
	"projectionRunText": "Confirme que desea ejecutar el mapeo de datos inmediatamente.",
	"projectionRunSuccess": "El mapeo de datos se está ejecutando.",
	"projectionRunError": "No es necesario ejecutar el mapeo de datos.",
	"mapping": "Mapeo",
	"mappingData": "Mapeo de datos empresariales",
	"dataName": "Nombre del dato",
	"dataPath": "Ruta del dato",
	"dataType": "Tipo de dato",
	"saveDraftOnClose": {
		"0": "Guardar automáticamente el documento al cerrar el borrador",
		"1": "No guardar automáticamente el documento al cerrar el borrador"
	}
}
MWF.xApplication.cms.ColumnManager["lp."+o2.language] = MWF.xApplication.cms.ColumnManager.LP