MWF.xApplication.cms.ColumnManager = MWF.xApplication.cms.ColumnManager || {};
MWF.xApplication.cms.ColumnManager.LP = {
	"title": "コンテンツ管理カテゴリ設定",
    "categoryTitle": "カテゴリ管理",
    "description": "説明",
    "deleteItems": "選択したアイテムを削除",
    "copy": "コピー",
    "copyto": "コピー先...",
    "copyInfor": "複数のアイテムを選択し、Ctrl+Cを押すとアイテムがコピーされ、Ctrl+Vを押すとコピーしたアイテムを現在のアプリケーションに貼り付けることができます。",
    "copyed": "選択したアイテムは既にコピーされています。",
    "copyConfirmTitle": "アイテムのコピー確認",
    "copyConfirmInfor": "対象エリアに同じアイテムが含まれています：",
    "copySource": "元ファイル：",
    "copyTarget": "コピー先ファイル：",
    "copyConfirm_overwrite": "上書き",
    "copyConfirm_new": "新規作成",
    "copyConfirm_skip": "スキップ",
    "copyConfirm_cancel": "キャンセル",
    "copynew": "新規",

    "setting": "設定",

    "ok": "確定",
    "edit": "編集",
    "save": "保存",
    "cancel": "キャンセル",

    "phone": "携帯電話",
    "mail": "メール",

    "deleteElementTitle": "デザイン削除確認",
    "deleteElement": "選択したデザイン要素を削除しますか？",
    "setControllerSuccess": "管理者の設定に成功しました",
    "noAdministratorAccess": "このカテゴリの管理権限がありません",
    "createSelectTemplate": "新規作成：テンプレート選択",
    "templateCategory": "テンプレートのカテゴリ：",
    "all": "すべて",
    "formType": {
        "empty": "空白のフォーム",
        "publishEdit": "公開編集フォーム",
        "publishRead": "公開閲覧フォーム",
        "publishEditGreen": "公開編集フォーム（緑色）",
        "publishReadGreen": "公開閲覧フォーム（緑色）",
        "dataInput": "データ入力フォーム"
    },

	"category": {
        "create": "カテゴリ新規作成",
		"search": "カテゴリ検索",
		"searchText": "キーワードを入力してください。",
		"noCategoryNoticeText": "このカテゴリにはまだカテゴリがありません。ここをクリックして新しいカテゴリを作成できます。",
		"loaded": "カテゴリの読み込みが完了しました。",
		"deleteCategoryTitle": "カテゴリの削除確認",
		"deleteCategoryConfirm": "現在のカテゴリを削除してもよろしいですか？",
		"deleteFailAsHasDocument": "カテゴリ '{title}' の削除に失敗しました。まず、このカテゴリ内のドキュメントを削除してください。",

        "idLabel": "カテゴリ識別子",
		"nameLabel": "カテゴリ名",
		"aliasLabel": "カテゴリ別名",
		"sendNotify": "発行時にメッセージを送信するか",
		"sendNotifyInfo": "具体的なメッセージ戦略はフォームで構成されます。",
		"blankToAllNotify": "発行範囲が空の場合、すべてのユーザーに通知するか",
		"descriptionLabel": "カテゴリの説明",
		"sortLabel": "カテゴリの並べ替え",
		"columnLabel": "所属カラム",
		"iconLabel": "カテゴリアイコン",
		"formLabel": "対応フォーム",
		"formLabelEdit": "編集状態フォーム",
		"formLabelRead": "読み取り状態フォーム",
		"viewLabel": "リストの使用",
		"defaultViewLabel": "デフォルトリスト",
		"cancel": "キャンセル",
		"ok": "確認",
		"inputName": "カテゴリ名を入力してください。",
		"create_cancel_title": "カテゴリ作成のキャンセル確認",
		"create_cancel": "カテゴリ作成をキャンセルしますか？",
		"noDescription": "このカテゴリには説明がありません。",
		"delete": "カテゴリの削除",
		"edit": "カテゴリの編集",
        "createCategorySuccess": "カテゴリの作成に成功しました",
		"updateCategorySuccess": "カテゴリの更新に成功しました",
		"defaultView": "デフォルト",
		"insertCateogryBefore": "カテゴリの前に挿入",
		"insertCateogryAfter": "カテゴリの後に追加",
		"deleteCategory": "カテゴリの削除",
		"moveCategory": "カテゴリの順序を変更",
		"saveCategory": "カテゴリの保存",
		"editCategory": "カテゴリの編集",
		"cancelEdit": "キャンセル",
		"categoryProperty": "カテゴリのプロパティ",
		"baseProperty": "基本プロパティ",
		"useProcess": "プロセスの使用",
		"setProcessAppSucess": "プロセスアプリの設定に成功しました",
		"setProcessSucess": "プロセスの設定に成功しました",
		"selectProcess": "プロセスの選択",
		"selectProcessApp": "プロセスアプリの選択",
		"setCategoryManager": "カテゴリのマネージャの設定",
		"none": "なし",
		"noProcess": "システム内には管理できるプロセスがありません",
		"documentType": "ドキュメントタイプ",
		"excelImportView": "データのインポートとエクスポートビュー",
		"useProcessForm": "プロセスフォームの使用",
		"useProcessFormNote": "注意：プロセスフォームを使用する場合、発行後のドキュメントはプロセスフォームで開きます。それ以外の場合は、カテゴリで設定されたフォームを使用します。",
		"setSucess": "設定成功"
	},
	"form": {
        "create": "新しいフォームを作成",
		"search": "フォームを検索",
		"searchText": "キーワードを入力してください",
		"selectCategoryForm": "カテゴリフォームを選択",
		"noFormNoticeText": "このカテゴリにはまだフォームがありません。ここをクリックして新しいフォームを作成できます。",
		"loaded": "フォームの読み込みが完了しました",
		"deleteFormTitle": "フォームの削除の確認",
		"deleteForm": "フォームを削除すると関連するリストも削除されます。現在のフォームを削除してもよろしいですか？",
		"deleteFormTemplateTitle": "フォームテンプレートの削除の確認",
		"deleteFormTemplate": "現在のフォームテンプレートを削除してもよろしいですか？"
		
	},
    "view": {
        "create": "新しいリストを作成",
		"search": "リストを検索",
		"searchText": "キーワードを入力してください",
		"selectRelativeForm": "関連フォームを選択",
		"noViewNoticeText": "このデザイン要素はもはや使用されていません。データを表示するにはビューまたはクエリ設定を使用してください。",
		"noViewNoCreateNoticeText": "このカテゴリには現在リストがありません。",
		"loaded": "リストの読み込みが完了しました",
		"deleteFormTitle": "リストの削除の確認",
		"deleteForm": "現在のリストを削除してもよろしいですか？",
		"selectRelativeFormNoticeText": "ビューを貼り付ける関連フォームを選択してください"
    },
    "dictionary": {
        "create": "新しいデータ辞書を作成",
		"search": "データ辞書を検索",
		"searchText": "キーワードを入力してください",
		"noDictionaryNoticeText": "現在、このカテゴリにはデータ辞書がありません。新しいデータ辞書を作成するには、ここをクリックできます。",
		"noDictionaryNoCreateNoticeText": "現在、このカテゴリにはデータ辞書がありません。",
		"loaded": "データ辞書の読み込みが完了しました",
		"deleteFormTitle": "データ辞書の削除の確認",
		"deleteForm": "現在のデータ辞書を削除してもよろしいですか？"
    },
    "script": {
        "create": "新しいスクリプトを作成",
		"search": "スクリプトを検索",
		"searchText": "キーワードを入力してください",
		"noScriptNoticeText": "現在、このカテゴリにはスクリプトがありません。新しいスクリプトを作成するには、ここをクリックできます。",
		"loaded": "スクリプトの読み込みが完了しました",
		"deleteFormTitle": "スクリプトの削除の確認",
		"deleteForm": "現在のスクリプトを削除してもよろしいですか？"
    },
    "application": {
        "inputApplicationName": "カラム名を入力してください",
		"saveSuccess" : "保存成功",
		"id" : "カラム識別子",
		"property": "基本プロパティ",
		"name": "カラム名",
		"alias": "カラム別名",
		"description": "カラム説明",
		"sort" : "カラムソート",
		"documentType": "ドキュメントタイプ",
		"showAllDocumentViews" : "カラムビュー",
		"icon": "カラムアイコン",
		"sign" : "カラム別名",
		"controllerList": "管理者リスト",
		"appType" : "カラムタイプ",
		"ignoreTitle" : "タイトルを無視",
		"latest" : "最新確認",
		"delayView": "遅延ビュー",
		"saveDraftOnClose": "自動保存",
		"defaultEditForm": "デフォルト編集フォーム",
		"defaultReadForm": "デフォルト読み取りフォーム",
		"editformNote": "注意：カテゴリ作成時のデフォルト編集フォーム",
		"readformNote": "注意：カテゴリ作成時のデフォルト読み取りフォーム、選択しない場合は編集フォームと同じ",
        "viewerSetting": {
			"title": "表示範囲",
			"set": "表示範囲の設定",
			"setSuccess": "表示範囲の設定に成功しました"
		},
		"publisherSetting": {
			"title": "発行者",
			"set": "発行者の設定",
			"setSuccess": "発行者の設定に成功しました"
		},
		"managerSetting": {
			"title": "マネージャー",
			"set": "マネージャーの設定",
			"setSuccess": "マネージャーの設定に成功しました"
		}
    },
    "queryView": {
        "create": "データビューの作成",
		"search": "データビューの検索",
		"searchText": "キーワードを入力してください",
		"selectRelativeForm": "関連フォームを選択",
		"noViewNoticeText": "この項目には現在データビューがありません。ここをクリックしてデータビューを作成できます。",
		"noViewNoCreateNoticeText": "この項目には現在データビューがありません。",
		"loaded": "データビューが読み込まれました。",
		"deleteFormTitle": "データビューの削除確認",
		"deleteForm": "現在のデータビューを削除してもよろしいですか？"
    },
    "file": {
        "create": "添付ファイルの作成",
		"search": "添付ファイルの検索",
		"searchText": "キーワードを入力してください",
		"description": "添付ファイル情報",
		"noScriptNoticeText": "現在、このアプリには添付ファイルがありません。ここをクリックして新しい添付ファイルを作成できます。",
		"loaded": "添付ファイルが読み込まれました。",
		"deleteFormTitle": "添付ファイルの削除確認",
		"deleteForm": "現在の添付ファイルを削除してもよろしいですか？",
		"saveSuccess": "添付ファイルが保存されました！",
		"saveConfirm": "保存確認",
		"saveConfirmText": "添付ファイルが変更されました。変更内容を保存しますか？",
		"uploadSuccess": "添付ファイルがアップロードされました",
		"loadFiles": "一括で添付ファイルをアップロード"
    },

    "enable": "有効化",
    "disable": "無効化",
    "name": "名前",
    "alias": "別名",
    "attachment": "添付ファイル",
    "upload": "添付ファイルのアップロード",
    "selectDataView": "データビューの選択",
    "selectDataViewTitle": "既存のデータビューから選択",
    "selectList": "リストの選択",
    "selectListTitle": "既存のリストから選択",

    "categoryDisplay": "カテゴリディスプレイ",
    "setCategoryListSuccess": "カテゴリリストの設定に成功しました",
    "setDefaultViewSuccess": "デフォルトビューの設定に成功しました",
    "cancelCategoryListSuccess": "カテゴリリストのキャンセルに成功しました",
    "setImpExpViewSuccess": "インポート/エクスポートビューの設定に成功しました",
    "setCategoryAliasSuccess": "カテゴリエイリアスの設定に成功しました",
    "setDocumentTypeSuccess": "ドキュメントタイプの設定に成功しました",
    "setSendNotifySuccess": "通知の送信設定に成功しました",
    "setBlankToAllNotifySuccess": "空の発行範囲の通知設定に成功しました",
    "setEditFormSuccess": "編集フォームの設定に成功しました",
    "setReadFormSuccess": "読み取りフォームの設定に成功しました",
    "setProjectionSuccess": "プロジェクションの設定に成功しました",
    "inputCategoryNotice": "カテゴリ名を入力してください",
    "noCategoryNotice": "まず、カテゴリを作成または選択してください",
    "saveCategoryNotice": "まず、カテゴリを保存してください",
    "dragToDesktopNotice": "デスクトップにドラッグできます",
    "asEditForm": "編集フォームとして設定",
    "asReadForm": "読み取りフォームとして設定",
    "delete": "削除",
    "notAddListOrView": "リストまたはビューが追加されていません",
    "systemList": "システムリスト",
    "selectCategoryNotice": "まず、カテゴリを選択してください",
    "conflictedListNotice": "リスト '{text}' は既に存在しています。重複して追加しないでください！",
    "selectView": "ビューを選択",
    "conflictedViewNotice": "ビュー '{text}' は既に存在しています。重複して追加しないでください！",
    "list": "リスト",
    "view1": "ビュー",
    "setAsDefaultList": "カテゴリのデフォルトリストに設定",
    "adjustOrder": "順序を調整",
    "cancelEdit": "編集をキャンセル",
    "enableProcess": "固定承認プロセス",
    "disableProcess": "承認プロセスの無効化",
    "documentTypeSelectValue": ["情報", "データ"],
    "documentTypeSelectText": ["情報", "データ"],
    "sendNotifySelectText": ["はい", "いいえ"],
    "sendNotifySelectValue": ["true", "false"],
    "blankToAllNotifySelectText": ["はい", "いいえ"],
    "blankToAllNotifySelectValue": ["true", "false"],
    "infor": "情報",
    "data": "データ",
    "type": "タイプ",
    "listName": "リスト名",
    "relativeForm": "関連フォーム",
    "dataView": "ビュー",
    "viewName": "ビュー名",
    "column": "カラム",
    "categorySetting": "カテゴリ設定",
    "formSetting": "フォーム設定",
    "dataSetting": "データ設定",
    "scriptSetting": "スクリプト設定",
    "listSetting": "リスト設定",
    "queryViewSetting": "データビュー設定",
    "attachmentSetting": "添付ファイル設定",
    "resourceFile": "リソースファイル",
    "findDesign": "デザインを検索",
    "new": "新規作成",
    "appProperty": "カテゴリのプロパティ",
    "changeIcon": "アイコンを変更",
    "ignoreTitleSelectText": ["新規画面にタイトルを入力しない", "新規画面にタイトルを入力する"],
    "checkDraftSelectText": ["新規画面で下書きを確認", "新規画面で下書きを確認しない"],
    "showAllDocumentSelectText": ["すべての文書ビューを表示", "すべての文書ビューを非表示"],
    "showDelayDocumentSelectText": ["予約発行文書ビューを表示", "予約発行文書ビューを非表示"],
    "saveDraftOnClose": ["下書きを閉じるときに自動保存", "下書きを閉じるときに自動保存しない"],

    "selectRelateFormNotice": "関連するフォームを選択してください",

    "projectionTitle": "ビジネスデータマッピング",
    "projectionActionNode_add": "マッピングエントリの追加",
    "projectionActionNode_modify": "マッピングエントリの変更",
    "projectionDataName": "データ名",
    "projectionPath": "データパス",
    "projectionType": "データタイプ",
    "projectionColumnName": "列名",
    "projectionInputError": "データ名とデータパスを入力してください",
    "projectionTypeCountError": "{type}タイプのデータマッピングエントリは最大で{count}件まで許可されています。",
    "projectionSameNameError": "同じデータ名がすでに存在します",
    "projectionDeleteItemTitle": "データマッピングエントリの削除確認",
    "projectionDeleteItem": "名前が“{name}”でパスが“{path}”のデータマッピングエントリを削除しますか？",
    "projectionRunActionNode": "データマッピングを即時実行",
    "projectionRunTitle": "即時実行の確認",
    "projectionRunText": "データマッピングを即時実行しますか？",
    "projectionRunSuccess": "データマッピングが正常に開始されました",
    "projectionRunError": "データマッピングの実行は不要です",

    "mapping": "マッピング",
    "mappingData": "ビジネスデータマッピング",
    "dataName": "データ名",
    "dataPath": "データパス",
    "dataType": "データタイプ"
};