MWF.xApplication.cms.ColumnManager = MWF.xApplication.cms.ColumnManager || {};
MWF.xApplication.cms.ColumnManager.LP = {
	"title": "콘텐츠 관리 카테고리 설정",
    "categoryTitle": "카테고리 관리",
    "description": "설명",
    "deleteItems": "선택한 항목 삭제",
    "copy": "복사",
    "copyto": "복사해서...",
    "copyInfor": "여러 항목을 선택하고 Ctrl+C를 누르면 항목을 복사하고, Ctrl+V를 누르면 복사한 항목을 현재 애플리케이션에 붙여넣을 수 있습니다.",
    "copyed": "선택한 항목이 이미 복사되었습니다.",
    "copyConfirmTitle": "항목 복사 확인",
    "copyConfirmInfor": "대상 영역에 이미 동일한 항목이 포함되어 있습니다:",
    "copySource": "원본 파일:",
    "copyTarget": "복사 파일:",
    "copyConfirm_overwrite": "덮어쓰기",
    "copyConfirm_new": "새로 만들기",
    "copyConfirm_skip": "건너뛰기",
    "copyConfirm_cancel": "취소",
    "copynew": "새로운",
    "setting": "설정",

    "ok": "확인",
    "edit": "편집",
    "save": "저장",
    "cancel": "취소",

    "phone": "휴대폰",
    "mail": "이메일",

    "deleteElementTitle": "디자인 삭제 확인",
    "deleteElement": "선택한 디자인 요소를 삭제하시겠습니까?",
    "setControllerSuccess": "관리자 설정 성공",
    "noAdministratorAccess": "이 카테고리를 관리할 수 있는 권한이 없습니다",
    "createSelectTemplate": "새로 만들기: 템플릿 선택",
    "templateCategory": "템플릿 분류:",
    "all": "모두",

    "formType": {
        "empty": "빈 폼",
        "publishEdit": "게시 편집 폼",
        "publishRead": "게시 읽기 폼",
        "publishEditGreen": "게시 편집 폼 (녹색)",
        "publishReadGreen": "게시 읽기 폼 (녹색)",
        "dataInput": "데이터 입력 폼"
    },

	"category": {
        "create": "분류 생성",
		"search": "분류 검색",
		"searchText": "키워드를 입력하세요.",
		"noCategoryNoticeText": "현재 이 카테고리에는 아직 분류가 없습니다. 여기를 클릭하여 새로운 분류를 생성할 수 있습니다.",
		"loaded": "분류가 로드되었습니다.",
		"deleteCategoryTitle": "분류 삭제 확인",
		"deleteCategoryConfirm": "현재 분류를 삭제하시겠습니까?",
		"deleteFailAsHasDocument": "분류 ' {title} ' 삭제 실패. 먼저 해당 분류의 문서를 삭제하십시오.",

        "idLabel": "분류 식별자",
		"nameLabel": "분류 이름",
		"aliasLabel": "분류 별칭",
		"sendNotify": "배포 시 메시지 전송 여부",
		"sendNotifyInfo": "구체적인 메시지 전략은 양식에서 구성됩니다.",
		"blankToAllNotify": "배포 범위가 비어 있을 때 모든 사용자에게 알림 전송",
		"descriptionLabel": "분류 설명",
		"sortLabel": "분류 정렬",
		"columnLabel": "소속 콜럼",
		"iconLabel": "분류 아이콘",
		"formLabel": "대응 양식",
		"formLabelEdit": "편집 상태 양식",
		"formLabelRead": "읽기 상태 양식",
		"viewLabel": "리스트 사용",
		"defaultViewLabel": "기본 리스트",
		"cancel": "취소",
		"ok": "확인",
		"inputName": "분류 이름을 입력하세요.",
		"create_cancel_title": "분류 생성 취소 확인",
		"create_cancel": "분류 생성을 취소하시겠습니까?",
		"noDescription": "이 분류에는 설명이 없습니다.",
		"delete": "분류 삭제",
		"edit": "분류 편집",
        "createCategorySuccess": "분류 생성 성공",
		"updateCategorySuccess": "분류 수정 성공",
		"defaultView": "기본",
		"insertCateogryBefore": "분류 앞에 삽입",
		"insertCateogryAfter": "분류 뒤에 삽입",
		"deleteCategory": "분류 삭제",
		"moveCategory": "분류 순서 조정",
		"saveCategory": "분류 저장",
		"editCategory": "분류 편집",
		"cancelEdit": "취소",
		"categoryProperty": "분류 속성",
		"baseProperty": "기본 속성",
		"useProcess": "프로세스 사용",
		"setProcessAppSucess": "프로세스 응용프로그램 설정 성공",
		"setProcessSucess": "프로세스 설정 성공",
		"selectProcess": "프로세스 선택",
		"selectProcessApp": "프로세스 응용프로그램 선택",
		"setCategoryManager": "분류 관리자 설정",
		"none": "없음",
		"noProcess": "관리 가능한 프로세스가 시스템에 없습니다.",
		"documentType": "문서 유형",
		"excelImportView": "데이터 가져오기/내보내기 뷰",
		"useProcessForm": "프로세스 양식 사용",
		"useProcessFormNote": "참고: 프로세스 양식을 사용하는 경우, 발행 후 문서를 프로세스 양식으로 열 수 있으며, 그렇지 않으면 분류에서 설정한 양식을 사용합니다.",
		"setSucess": "설정 성공"
	},
	"form": {
        "create": "새로운 양식 생성",
		"search": "양식 검색",
		"searchText": "검색어를 입력하세요",
		"selectCategoryForm": "분류 양식 선택",
		"noFormNoticeText": "이 카테고리에는 아직 양식이 없습니다. 여기를 클릭하여 새 양식을 만들 수 있습니다.",
		"loaded": "양식 로드 완료",
		"deleteFormTitle": "양식 삭제 확인",
		"deleteForm": "양식을 삭제하면 관련 목록도 삭제됩니다. 현재 양식을 삭제하시겠습니까?",
		"deleteFormTemplateTitle": "양식 템플릿 삭제 확인",
		"deleteFormTemplate": "현재 양식 템플릿을 삭제하시겠습니까?"
		
	},
    "view": {
        "create": "새 목록 생성",
		"search": "목록 검색",
		"searchText": "키워드를 입력하세요",
		"selectRelativeForm": "관련 양식 선택",
		"noViewNoticeText": "이 설계 요소는 더 이상 사용되지 않습니다. 데이터를 표시하려면 뷰 또는 쿼리 설정을 사용하십시오.",
		"noViewNoCreateNoticeText": "이 카테고리에는 현재 목록이 없습니다.",
		"loaded": "목록 로드 완료",
		"deleteFormTitle": "목록 삭제 확인",
		"deleteForm": "현재 목록을 삭제하시겠습니까?",
		"selectRelativeFormNoticeText": "붙여넣을 뷰를 선택하려면 관련 양식을 선택하십시오."
    },
    "dictionary": {
        "create": "데이터 사전 생성",
		"search": "데이터 사전 검색",
		"searchText": "키워드를 입력하세요",
		"noDictionaryNoticeText": "현재 이 카테고리에는 데이터 사전이 없습니다. 새로운 데이터 사전을 생성하려면 여기를 클릭할 수 있습니다.",
		"noDictionaryNoCreateNoticeText": "현재 이 카테고리에는 데이터 사전이 없습니다.",
		"loaded": "데이터 사전 로드 완료",
		"deleteFormTitle": "데이터 사전 삭제 확인",
		"deleteForm": "현재 데이터 사전을 삭제하시겠습니까?"
    },
    "script": {
        "create": "스크립트 생성",
		"search": "스크립트 검색",
		"searchText": "키워드를 입력하세요",
		"noScriptNoticeText": "현재 이 카테고리에는 스크립트가 없습니다. 새로운 스크립트를 생성하려면 여기를 클릭할 수 있습니다.",
		"loaded": "스크립트 로드 완료",
		"deleteFormTitle": "스크립트 삭제 확인",
		"deleteForm": "현재 스크립트를 삭제하시겠습니까?"
    },
    "application": {
        "inputApplicationName": "칼럼 이름을 입력하세요",
		"saveSuccess" : "저장 성공",
		"id" : "칼럼 식별자",
		"property": "기본 속성",
		"name": "칼럼 이름",
		"alias": "칼럼 별명",
		"description": "칼럼 설명",
		"sort" : "칼럼 정렬",
		"documentType": "문서 유형",
		"showAllDocumentViews" : "칼럼 뷰",
		"icon": "칼럼 아이콘",
		"sign" : "칼럼 별칭",
		"controllerList": "관리자 목록",
		"appType" : "칼럼 유형",
		"ignoreTitle" : "제목 무시",
		"latest" : "최신 확인",
		"delayView": "지연 뷰",
		"saveDraftOnClose": "자동 저장",
		"defaultEditForm": "기본 편집 폼",
		"defaultReadForm": "기본 읽기 폼",
		"editformNote": "참고: 카테고리 생성 시 기본 편집 폼",
		"readformNote": "참고: 카테고리 생성 시 기본 읽기 폼, 선택하지 않으면 편집 폼과 동일",
        "viewerSetting": {
			"title": "가시 범위",
			"set": "가시 범위 설정",
			"setSuccess": "가시 범위 설정 성공"
		},
		"publisherSetting": {
			"title": "게시자",
			"set": "게시자 설정",
			"setSuccess": "게시자 설정 성공"
		},
		"managerSetting": {
			"title": "매니저",
			"set": "매니저 설정",
			"setSuccess": "매니저 설정 성공"
		}
    },
    "queryView": {
        "create": "데이터 뷰 생성",
		"search": "데이터 뷰 검색",
		"searchText": "키워드를 입력하세요",
		"selectRelativeForm": "관련 양식 선택",
		"noViewNoticeText": "현재 이 항목에는 데이터 뷰가 없습니다. 여기를 클릭하여 데이터 뷰를 생성할 수 있습니다.",
		"noViewNoCreateNoticeText": "현재 이 항목에는 데이터 뷰가 없습니다.",
		"loaded": "데이터 뷰가 로드되었습니다.",
		"deleteFormTitle": "데이터 뷰 삭제 확인",
		"deleteForm": "현재 데이터 뷰를 삭제하시겠습니까?"
    },
    "file": {
        "create": "첨부 파일 생성",
		"search": "첨부 파일 검색",
		"searchText": "키워드를 입력하세요",
		"description": "첨부 파일 정보",
		"noScriptNoticeText": "현재 이 앱에는 첨부 파일이 없습니다. 여기를 클릭하여 새로운 첨부 파일을 생성할 수 있습니다.",
		"loaded": "첨부 파일이 로드되었습니다.",
		"deleteFormTitle": "첨부 파일 삭제 확인",
		"deleteForm": "현재 첨부 파일을 삭제하시겠습니까?",
		"saveSuccess": "첨부 파일이 저장되었습니다!",
		"saveConfirm": "저장 확인",
		"saveConfirmText": "첨부 파일이 수정되었습니다. 수정 내용을 저장하시겠습니까?",
		"uploadSuccess": "첨부 파일이 업로드되었습니다",
		"loadFiles": "일괄 첨부 파일 업로드"
    },

    "enable": "활성화",
    "disable": "비활성화",
    "name": "이름",
    "alias": "별칭",
    "attachment": "첨부 파일",
    "upload": "첨부 파일 업로드",
    "selectDataView": "데이터 뷰 선택",
    "selectDataViewTitle": "기존 데이터 뷰 선택",
    "selectList": "리스트 선택",
    "selectListTitle": "기존 리스트 선택",

    "categoryDisplay": "카테고리 표시",
    "setCategoryListSuccess": "카테고리 목록 설정 성공",
    "setDefaultViewSuccess": "기본 뷰 설정 성공",
    "cancelCategoryListSuccess": "카테고리 목록 취소 성공",
    "setImpExpViewSuccess": "가져오기/내보내기 뷰 설정 성공",
    "setCategoryAliasSuccess": "카테고리 별칭 설정 성공",
    "setDocumentTypeSuccess": "문서 유형 설정 성공",
    "setSendNotifySuccess": "알림 전송 설정 성공",
    "setBlankToAllNotifySuccess": "공백 전체 알림 설정 성공",
    "setEditFormSuccess": "편집 양식 설정 성공",
    "setReadFormSuccess": "읽기 양식 설정 성공",
    "setProjectionSuccess": "프로젝션 설정 성공",
    "inputCategoryNotice": "카테고리 이름을 입력하세요",
    "noCategoryNotice": "먼저 카테고리를 생성하거나 선택하세요",
    "saveCategoryNotice": "먼저 카테고리를 저장하세요",
    "dragToDesktopNotice": "바탕 화면으로 끌어서 놓을 수 있습니다",
    "asEditForm": "편집 양식으로 설정",
    "asReadForm": "읽기 양식으로 설정",
    "delete": "삭제",
    "notAddListOrView": "목록 또는 데이터 뷰를 추가하지 않았습니다",
    "systemList": "시스템 목록",
    "selectCategoryNotice": "먼저 카테고리를 선택하세요",
    "conflictedListNotice": "목록 '{text}'은(는) 이미 존재합니다. 중복 추가하지 마세요!",
    "selectView": "뷰 선택",
    "conflictedViewNotice": "뷰 '{text}'은(는) 이미 존재합니다. 중복 추가하지 마세요!",
    "list": "목록",
    "view1": "뷰",
    "setAsDefaultList": "카테고리 기본 목록으로 설정",
    "adjustOrder": "순서 조절",
    "cancelEdit": "편집 취소",
    "enableProcess": "픽스된 승인 프로세스",
    "disableProcess": "승인 프로세스 비활성화",
    "documentTypeSelectValue": ["정보", "데이터"],
    "documentTypeSelectText": ["정보", "데이터"],
    "sendNotifySelectText": ["예", "아니요"],
    "sendNotifySelectValue": ["true", "false"],
    "blankToAllNotifySelectText": ["예", "아니요"],
    "blankToAllNotifySelectValue": ["true", "false"],
    "infor": "정보",
    "data": "데이터",
    "type": "유형",
    "listName": "목록 이름",
    "relativeForm": "관련 양식",
    "dataView": "뷰",
    "viewName": "뷰 이름",
    "column": "열",
    "categorySetting": "카테고리 설정",
    "formSetting": "양식 설정",
    "dataSetting": "데이터 설정",
    "scriptSetting": "스크립트 설정",
    "listSetting": "목록 설정",
    "queryViewSetting": "데이터 뷰 설정",
    "attachmentSetting": "첨부 설정",
    "resourceFile": "리소스 파일",
    "findDesign": "디자인 찾기",
    "new": "새로 만들기",
    "appProperty": "카테고리 속성",
    "changeIcon": "아이콘 변경",
    "ignoreTitleSelectText": ["새로운 화면에 제목 입력 안 함", "새로운 화면에 제목 입력함"],
    "checkDraftSelectText": ["새로운 화면에서 초안 확인", "새로운 화면에서 초안 확인 안 함"],
    "showAllDocumentSelectText": ["모든 문서 뷰 표시", "모든 문서 뷰 숨기기"],
    "showDelayDocumentSelectText": ["예약 게시 문서 뷰 표시", "예약 게시 문서 뷰 숨기기"],
    "saveDraftOnClose": ["문서 자동 저장 기능 끄기", "문서 자동 저장 기능 켜기"],

    "selectRelateFormNotice": "관련 양식을 선택하세요",

    "projectionTitle": "비즈니스 데이터 매핑",
    "projectionActionNode_add": "매핑 항목 추가",
    "projectionActionNode_modify": "매핑 항목 수정",
    "projectionDataName": "데이터 이름",
    "projectionPath": "데이터 경로",
    "projectionType": "데이터 유형",
    "projectionColumnName": "열 이름",
    "projectionInputError": "데이터 이름과 데이터 경로를 입력하세요",
    "projectionTypeCountError": "{type} 유형의 데이터 매핑 항목은 최대 {count}개까지 허용됩니다.",
    "projectionSameNameError": "동일한 데이터 이름이 이미 존재합니다",
    "projectionDeleteItemTitle": "데이터 매핑 항목 삭제 확인",
    "projectionDeleteItem": "이름이 “{name}”이고 경로가 “{path}”인 데이터 매핑 항목을 삭제하시겠습니까?",
    "projectionRunActionNode": "데이터 매핑 즉시 실행",
    "projectionRunTitle": "즉시 실행 확인",
    "projectionRunText": "데이터 매핑을 즉시 실행하시겠습니까?",
    "projectionRunSuccess": "데이터 매핑이 성공적으로 시작되었습니다",
    "projectionRunError": "데이터 매핑을 실행할 필요가 없습니다",

    "mapping": "매핑",
    "mappingData": "비즈니스 데이터 매핑",
    "dataName": "데이터 이름",
    "dataPath": "데이터 경로",
    "dataType": "데이터 유형"
};