MWF.xApplication.cms.ColumnManager = MWF.xApplication.cms.ColumnManager || {};
MWF.xApplication.cms.ColumnManager.LP = {
    "title": "ການຕັ້ງຄ່າຖັນການຈັດການເນື້ອຫາ",
    "categoryTitle": "ປະເພດການຈັດການ",
    "description": "ອະທິບາຍ",
    "deleteItems": "ລຶບເນື້ອຫາທີ່ເລືອກ",

    "copy": "ສຳເນົາ",
    "copyto": "ສຳເນົາໄປທີ່...",
    "copyInfor": "ເລືອກຫຼາຍອົງປະກອບ, ກົດ Ctrl+C ເພື່ອສຳເນົາອົງປະກອບ, ກົດ Ctrl+V ເພື່ອວາງອົງປະກອບທີ່ສຳເນົາໄວ້ໃນແອັບພລິເຄຊັນປັດຈຸບັນ",
    "copyed": "ຄັດລອກອົງປະກອບທີ່ເລືອກ",
    "copyed": "ຄັດລອກອົງປະກອບທີ່ເລືອກ",
    "copyConfirmTitle": "ສຳເນົາການຢືນຢັນອົງປະກອບ",
    "copyConfirmInfor": "ພື້ນທີ່ເປົ້າຫມາຍມີອົງປະກອບດຽວກັນຢູ່ແລ້ວ：",
    "copySource": "ເອກະສນຕົ້ນສະບັບ:",
    "copyTarget": "ສຳເນົາເອກະສານ:",
    "copyConfirm_overwrite": "ແທນຄືນ",
    "copyConfirm_new": "ໃໝ່",
    "copyConfirm_skip": "ຂ້າມ",
    "copyConfirm_cancel": "ຍົກເລີກ",
    "copynew": "ໃໝ່",

    "setting" : "ຕັ້ງຄ່າ",

    "ok": "ຕົກລົງ",
    "edit": "ແກ້ໄຂ",
    "save": "ບັນທຶກ",
    "cancel": "ຍົກເລີກ",

    "phone": "ໂທລະສັບ",
    "mail": "ເມວ",

    "deleteElementTitle": "ຢືນຢັນລົບການອອກແບບ",
    "deleteElement": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບກນອອກແບບທີ່ເລືອກ？",

    "setControllerSuccess" : "ຕັ້ງຄ່າຜູ້ຈັດການສຳເລັດ",
    "noAdministratorAccess" : "ເຈົ້າບໍ່ໄດຮັບອະນຸຍາດໃຫ້ຈັດການລາຍການນີ້",

    "createSelectTemplate": "ໃໝ່：ເລືອກແມ່ແບບ",
    "templateCategory": "ປະເພດແມ່ແບບ：",
    "all": "ທັງໝົດ",

    "formType": {
        "empty": "ຟອມວ່າງເປົ່າ",
        "publishEdit": "ເຜີຍແຜ່ແກ້ໄຂແບບຟອມ",
        "publishRead": "ເຜີຍແຜ່ອ່ານຟອມ",
        "publishEditGreen": "ເຜີຍແຜ່ແບບຟອມແກ້ໄຂ(ສີຂຽວ)",
        "publishReadGreen": "ເຜີຍແຜ່ຟອມອ່ານ(ສີຂຽວ)",
        "dataInput": "ຟອມນຳເຂົ້າຂໍ້ມູນ"
    },

    "category": {
        "create": "ປະເພດໃໝ່",
        "search": "ຄົ້ນຫາປະເພດ",
        "searchText": "ກະລຸນາຕື່ມຂໍ້ມູນ",

        "noCategoryNoticeText": "ປະຈຸບັນ AppInfo ບໍ່ມີປະເພດ，ເຈົ້າສວາມາດຄິກທີ່ນີ້ເພື່ອເພີ່ມປະເພດ",
        "loaded": "ໂຫຼດປະເພດແລ້ວ",

        "deleteCategoryTitle": "ຢືນຢັນລົບປະເພດ",
        "deleteCategoryConfirm": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບປະເພດປະຈຸບັນ？",
        "deleteFailAsHasDocument" : "ລົບປະເພດ“{title}”ລົມເລວ，ກະລຸນາລົບປະເພດເອກະສານຕໍ່ໄປນີ້ກ່ອນ。",

        "idLabel" : "ປະເພດ ID",
        "nameLabel" : "ຊື່ປະເພດ",
        "aliasLabel" : "ຊື່ປະເພດ",
        "sendNotify" : "ສົ່ງຂໍ້ຄວາມ",
        "sendNotifyInfo": "ຂໍ້ຄວາມແມ່ນໄດ້ຖືກກຳນົດໃສ່ແບບຟອມ",
        "blankToAllNotify": "ແຈ້ງການໃຫ້ພະນັກງານທັງໝົດເມື່ອຂອບເຂດການເຜີຍແຜ່ຫວ່າງເປົ່າຫຼືບໍ່",
        "descriptionLabel" : "ອະທິບາຍປະເພດ",
        "sortLabel" : "ລຽນລຳດັບປະເພດ",
        "columnLabel" : "ຖັນ",
        "iconLabel" : "ປະເພດ",
        "formLabel" : "ຟອມ",
        "formLabelEdit" : "ແກ້ໄຂສະຖານະຟອມ",
        "formLabelRead" : "ສະຖານະຟອມອ່ານ",
        "viewLabel" : "ນຳໃຊ້ລາຍການ",
        "defaultViewLabel" : "ລາຍການເລີ່ມຕົ້ນ",
        "cancel" : "ຍົກເລີກ",
        "ok" : "ຕົກລົງ",
        "inputName":"ຕື່ມຂໍ້ມູນຊື່ປະເພດ",
        "create_cancel_title": "ຢືນຢັນຍົກເລີກສ້າງປະເພດ",
        "create_cancel": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກສ້າງປະເພດ?",
        "noDescription" : "ບໍ່ມີການອະທິບາຍປະເພດໃນທີ່ນີ້",
        "delete" : "ລົບປະເພດ",
        "edit" : "ແກ້ໄຂປະເພດ",
        "createCategorySuccess" :"ສ້າງປະເພດສຳເລັດ",
        "updateCategorySuccess" : "ແກ້ໄຂປະເພດສຳເລັດ",
        "defaultView" : "ຄ່າເລີ່ມຕົ້ນ",
        "insertCateogryBefore" : "ເພີ່ມປະເພດ",
        "insertCateogryAfter" : "ເພີ່ມປະເພດ",
        "deleteCategory" : "ລົບປະເພດ",
        "moveCategory" : "ຈັດລຽນປະເພດ",
        "saveCategory" : "ບັນທຶກປະເພດ",
        "editCategory" : "ແກ້ໄຂປະເພດ",
        "cancelEdit" : "ຍົກເລີກ",
        "categoryProperty" : "ປະເພດຄຸນສົມບັດ",
        "baseProperty" : "ຄຸນສົມບັດທົ່ວໄປ",
        "useProcess" : "ໃຊ້ຂະບວນການ",
        "setProcessAppSucess" : "ຕັ້ງຄ່າຂະບວນການແອັບສຳເລັດ",
        "setProcessSucess":"ຕັ້ງຄ່າຂະບວນການສຳເລັດ",
        "selectProcess":"ເລືອກຂະບວນການ",
        "selectProcessApp":"ເລືອກຂະບວນການແອັບ",
        "setCategoryManager" : "ຕັ້ງຄ່າປະເພດຄົນຈັດການ",
        "none" : "ບໍ່ມີ",
        "noProcess" : "ບໍ່ມີຂະບວນການໃນລະບົບທີ່ທ່ານສາມາດຈັດການໄດ້",
        "documentType" : "ປະເພດເອກະສານ",
        "excelImportView" : "ມຸມມອງຂໍ້ມູນນຳອອກແລະນຳເຂົ້າ",

        "useProcessForm": "ນຳໃຊ້ຂະບວນການຟອມ",
        "useProcessFormNote": "ໝາຍເຫດ：ຖ້ານຳໃຊ້ຂະບວນການຟອມ，ຈາກນັ້ນ ໃຊ້ແບບຟອມຂະບວນການເພື່ອເປີດເອກະສານທີ່ເຜີຍແຜ່，ຖ້າບໍ່ດັ່ງນັ້ນໃຊ້ປະເພດການຕັ້ງຄ່າເພື່ອເປີດຟອມ。",
        "setSucess": "ຕັ້ງຄ່າສຳເລັດ"
    },
    "form": {
        "create": "ສ້າງຟອມ",
        "search": "ຄົ້ນຫາຟອມ",
        "searchText": "ກະລຸນາຕື່ມຂໍ້ມູນ",
        "selectCategoryForm": "ເລືອກປະເພດຟອມ",

        "noFormNoticeText": "ປະຈຸບັນບໍ່ມີຟອມໃນທີ່ນີ້，ກະລຸນາຄິກທີ່ນີ້ເພື່ອສ້າງຟອມໃໝ່",
        "loaded": "ໂຫຼດຟອມສຳເລັດ",
        "deleteFormTitle": "ຢືນຢັນລົບຟອມ",
        "deleteForm": "ການລົບແບບຟອມຈະເປັນການລົບລາຍການທີ່ກ່ຽວຂ້ອງຂອງແບບຟອມນີ້.，ແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບຟອມປະຈຸບັນ？",

        "deleteFormTemplateTitle": "ຢືນຢັນລົບແມ່ແບບຟອມ",
        "deleteFormTemplate": "ແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບແມ່ແບບຟອມປະຈຸບັນ？"

    },
    "view": {
        "create": "ສ້າງລາຍການ",
        "search": "ຄົ້ນຫາລາຍການ",
        "searchText": "ກະລຸນາຕື່ມຂໍ້ຄວາມ",
        "selectRelativeForm" : "ເລືອກຟອມທີ່ກ່ຽວຂ້ອງ",

        "noViewNoticeText": "ການອອກແບບອົງປະກອບແບບເກົ່າ，ກະ​ລຸ​ນາ​ໃຊ້ views ຫຼື​ການ​ຕັ້ງ​ຄ່າ​ການ​ສອບ​ຖາມ​ເພື່ອ​ສະ​ແດງ​ຂໍ້​ມູນ。",
        "noViewNoCreateNoticeText": "ໃນປັດຈຸບັນບໍ່ມີລາຍຊື່ຢູ່ໃນຖັນນີ້",
        "loaded": "ໂຫຼດລາຍການສຳເລັດ",
        "deleteFormTitle": "ຢືນຢັນລົບລາຍການ",
        "deleteForm": "ແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບລາຍການປະຈຸບັນນີ້？",
"selectRelativeFormNoticeText" : "ກະ​ລຸ​ນາ​ເລືອກ​ເອົາ​ຮູບ​ແບບ​ທີ່​ກ່ຽວ​ຂ້ອງ​ກັບ​ການ​ເບິ່ງ​ຈໍາ​ເປັນ​ຕ້ອງ​ໄດ້​ຮັບ​ການ​ວາງ​"
},
"dictionary": {
    "create": "ສ້າງຂໍ້ມູນວັດຈະນານຸກົມ",
        "search": "ຄົ້ນຫາ",
        "searchText": "ກະລຸນາຕື່ມຂໍ້ິຄວາມ",

        "noDictionaryNoticeText": "ບໍ່ມີຂໍ້ມູນວັດຈະນານຸກົມໃນຖັນນີ້，ກະລຸນາຄິກທີ່ນີ້ເພື່ອເພີ່ມຂໍ້ມູນວັດຈະນນານຸກົມໃໝ່",
        "noDictionaryNoCreateNoticeText": "ປະຈຸບັນບໍ່ມີຂໍ້ມູນວັດຈະນານຸກົມໃນຖັນນີ້",
        "loaded": "ໂຫຼດຂໍ້ມູນວັດຈະນຸກົມສຳເລັດ",
        "deleteFormTitle": "ຢືນຢັນລົບຂໍ້ມູນວັດຈະນານຸກົມສຳເລັດ",
        "deleteForm": "ແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບຂໍ້ມູນວັດຈະນານຸກົມ？"
},
"script": {
    "create": "ສ້າງ",
        "search": "ຄົ້ນຫາຟອມ",
        "searchText": "ກະລຸນາຕື່ມຂໍ້ຄວາມ",

        "noScriptNoticeText": "ບໍ່ຟອມໃນຖັນນີ້，ເຈົ້າສາມາດຄິກທີ່ນີ້ເພື່ອສ້າງຟອມໃໝ່",
        "loaded": "ໂຫຼດຟອມສຳເລັດ",
        "deleteFormTitle": "ຢືນຢັນລົບຟອມ",
        "deleteForm": "ເຈົ້າແນ່ບໍ່ວ່າຕ້ອງການລົບແມ່ແບບປະຈຸບັນ？"
},
"application": {
    "inputApplicationName": "ກະລຸນາຕື່ມຊື່ AppInfo",
        "saveSuccess" : "ບັນທຶກສຳເລັດ",
        "id" : "AppInfo ID",
        "property": "ຄຸນສົມບັດທົ່ວໄປ",
        "name": "ຊື່ AppInfo",
        "alias": "ຊື່ AppInfo",
        "description": "ອະທິບາຍ",
        "sort" : "ຈັດລຽນ",
        "documentType": "ປະເພດເອກະສານ",
        "showAllDocumentViews" : "ມຸມມອງ",
        "icon": "icon",
        "sign" : "ຊື່",
        "controllerList": "ຈັດການໂດຍ",
        "appType" : "ປະເພດ",
        "ignoreTitle" : "ລະເລີຍຫົວຂໍ້",
        "latest" : "ກວດສອບຮ່າງ",
        "delayView": "ມຸມມອງລ້າຊ້າ",
        "saveDraftOnClose": "ບັນທຶກອັດຕະໂນມັດ",
        "defaultEditForm": "ແກ້ໄຂຟອມເລີ່ມຕົ້ນ",
        "defaultReadForm": "ແກ້ໄຂຟອມອ່ານ",
        "editformNote": "ໝາຍເຫດ：ແກ້ໄຂຟອມເມື່ອສ້າງປະເພດໃໝ່",
        "readformNote": "ໝາຍເຫດ：ຄ່າເລີມຕົ້ນຟອມອ່ານເພື່ອສ້າງປະເພດໃໝ່，ຖ້າບໍ່ໄດ້ເລືອກ, ມັນຈະຄືກັນກັບແບບຟອມການແກ້ໄຂ.",
        viewerSetting : {
        title : "ສາມາດເຫັນຂອບເຂດ",
            set: "ຕັ້ງຄ່າສາມາດເຫັນຂອບເຂດ",
            setSuccess : "ຕັ້ງຄ່າສາມາດເຫັນຂອບເຂດສຳເລັດ"
    },
    publisherSetting : {
        title : "ເຜີຍແຜ່ໂດຍ",
            set: "ຕັ້ງຄ່າກນເຜີຍແຜ່ໂດຍ",
            setSuccess : "ຕັ້ງຄ່າສຳເລັດ"
    },
    managerSetting : {
        title : "ຈັດການ",
            set: "ຕັ້ງຄ່າການຈັດການ",
            setSuccess : "ຕັ້ງຄ່າການຈັດການສຳເລັດ"
    }
},
"queryView": {
    "create": "ສ້າງຂໍ້ມູນມຸມມອງ",
        "search": "ຊອກຫາຂໍ້ມູນມຸມມອງ",
        "searchText": "ກະລຸນາປ້ອນຂໍ້ຄວາມທີ່ກ່ຽວຂ້ອງ",
        "selectRelativeForm" : "ກະລຸນາເລືອກມຸມມອງທີ່ກ່ຽວຂ້ອງກັບຟອມ",

        "noViewNoticeText": "ບໍ່ມີຂໍ້ມູນສຳລັບຖັນນີ້ເທື່ອ，ເຈົ້າສາມາດຄິກທີ່ນີ້ເພື່ອສ້າງມຸມມອງຂໍ້ມູນໃໝ່",
        "noViewNoCreateNoticeText": "ປະຈຸບັນບໍ່ມີມຸມມອງຂໍ້ມູນສຳລັບຖັນນີ້",
        "loaded": "ໂຫຼດຂໍ້ມູນມຸມມອງສຳເລັດ",
        "deleteFormTitle": "ຢືນຢັນລົບຂໍ້ມູນມຸມມອງ",
        "deleteForm": "ແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບຂໍ້ມຸນມຸມມອງປະຈຸບັນ？"
},
"file": {
    "create": "ສ້າງເອກສານ",
        "search": "ຄົ້ນຫາເອກະສານ",
        "searchText": "ກະລຸນາຕື່ມຂໍ້ຄວາມ",
        "description": "ຂໍ້ຄວາມເອກະສານ",

        "noScriptNoticeText": "ແອັບນີ້ຍັງບໍ່ພົບເອກະສານ，ເຈົ້າສາມາດຄິກທີ່ນີ້ເພື່ອເພີ່ມເອກະສານໃໝ່",
        "loaded": "ໂຫຼດເອກະສານແລ້ວ",
        "deleteFormTitle": "ຢືນຢັນລົບເອກະສານ",
        "deleteForm": "ແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບເອກະສານປະຈຸບັນ？",
        "saveSuccess": "ເອກະສານບັນທຶກແລ້ວ！",
        "saveConfirm": "ຢືນຢັນບັນທຶກ",
        "saveConfirmText": "ເອກະສານຖືກແປງແລ້ວ，ເຈົ້າຕ້ອງການບັນທຶກການແກ້ໄຂເນື້ອໃນຫຼືບໍ？",
        "uploadSuccess": "ອັບໂຫຼດເອກະສານແລ້ວ",
        "loadFiles": "ອັບໂຫຼດເອກະສານ"
},

"enable": "ເປີດໃຊ້ງານ",
    "disable": "ປິດໃຊ້ງານ",
    "name": "ຊື່",
    "alias": "ຊື່ຫຼິ້ນ",
    "attachment": "ເອກະສານຊ້ອນທ້າຍ",
    "upload": "ອັບໂຫຼດເອກະສານ",

    "selectDataView" : "ເລືອກມຸມມອງ",
    "selectDataViewTitle" : "ເລືອກຈາກມຸມມອງທີ່ມີຢູ່ແລ້ວ",

    "selectList": "ເລືອກລາຍການ",
    "selectListTitle": "ເລືອກຈາກບັນຊີລາຍຊື່ທີ່ມີຢູ່ແລ້ວ",

    "categoryDisplay" : "ສະແດງປະເພດ",
    "setCategoryListSuccess": "ຕັ້ງຄ່າລາຍການປະເພດສຳເລັດ",
    "setDefaultViewSuccess": "ຕັ້ງຄ່າມຸມມອງເລີ່ມຕົ້ນສຳເລັດ",
    "cancelCategoryListSuccess": "ຍົກເລີກລາຍການປະເພດສຳເລັດ",
    "setImpExpViewSuccess" : "ຕັ້ງຄ່າປະເພດມຸມມອງນຳອອກນຳເຂົ້າສຳເລັດ",
    "setCategoryAliasSuccess": "ຕັ້ງຄ່າປະເພດຊື່ຫຼິ້ນສຳເລັດ",
    "setDocumentTypeSuccess": "ຕັ້ງຄ່າປະເພດເອກະສານສຳເລັດ",
    "setSendNotifySuccess": "ຕັ້ງຄ່າສົ່ງເອກະສານສຳເລັດ",
    "setBlankToAllNotifySuccess": "ຕັ້ງຂອບເຂດການເຜີຍແຜ່ໃຫ້ຫວ່າງເປົ່າວ່າຂໍ້ຄວາມຈະຖືກສົ່ງສຳເລັດຫຼືບໍ່",
    "setEditFormSuccess": "ຕັ້ງຄ່າຟອມຕັ້ງຄ່າສຳເລັດ",
    "setReadFormSuccess": "ຕັ້ງຄ່າຟອມອ່ານສຳເລັດ",
    "setProjectionSuccess": "ຕັ້ງຄ່າຂໍ້ມູນແຜນທີ່ສຳເລັດ",
    "inputCategoryNotice": "ກະລຸນາປ້ອນຊື່ປະເພດ",
    "noCategoryNotice": "ກະລະນາສ້າງ ຫຼືເລືອກປະເພດ",
    "saveCategoryNotice":"ກະລຸນາບັນທຶກປະເພດກ່ອນ",
    "dragToDesktopNotice": "ສາມາດລາກໄປທີ່ desktop",
    "asEditForm": "ຕັ້ງເປັນຟອມແກ້ໄຂ",
    "asReadForm": "ຕັ້ງເປັນຟອມອ່ານ",
    "delete": "ລົບ",
    "notAddListOrView": "ບໍ່ສາມາດເພີ່ມລາຍການໄດ້ ຫຼື ຂໍ້ມູນມຸມມອງ",
    "systemList": "ລາຍການລະບົບ",
    "selectCategoryNotice":"ກະລຸນາເລືອກປະເພດກ່ອນ",
    "conflictedListNotice": "ລາຍການ{text}ມີຢູ່ແລ້ວ，ບໍ່ສາມາດເພີ່ມໄດ້ອີກ！",
    "selectView": "ເລືອກມຸມມອງ",
    "conflictedViewNotice": "ມຸມມອງ{text}ມີຢູ່ແລ້ວ，ບໍ່ສາມາດເພີ່ມໄດ້ອີກ！",
    "list": "ລາຍການ",
    "view1": "ມຸມມອງ",
    "setAsDefaultList": "ຕັ້ງຄ່າເປັນປະເພດລາຍການເລີ່ມຕົ້ນ",
    "adjustOrder": "ປ່ຽນຄຳສັ່ງ",
    "cancelEdit": "ຍົກເລີກການແກ້ໄຂ",
    "enableProcess" : "ຂັ້ນຕອນການອະນຸມັດ",
    "disableProcess": "ປິດໃຊ້ງານຂັ້ນຕອນການອະນຸມັດ",
    "documentTypeSelectValue": ["ຂໍ້ຄວາມ","ຂໍ້ມູນ"],
    "documentTypeSelectText": ["ຂໍ້ຄວາມ","ຂໍ້ມູນ"],
    "sendNotifySelectText": ["ແມ່ນ","ບໍ່"],
    "sendNotifySelectValue": ["true","false"],
    "blankToAllNotifySelectText": ["ແມ່ນ","ບໍ່"],
    "blankToAllNotifySelectValue": ["true","false"],
    "infor": "ຂໍ້ຄວາມ",
    "data": "ຂໍ້ມູນ",
    "type": "ປະເພດ",
    "listName": "ຊື່ລາຍການ",
    "relativeForm": "ຄວາມສຳພັນຟອມ",
    "dataView": "ມຸມມອງ",
    "viewName": "ຊື່ມຸມມອງ",
    "column": "ຖັນ",
    "categorySetting": "ປະເພດຕັ້ງຄ່າ",
    "formSetting": "ຕັ້ງຄ່າຟອມ",
    "dataSetting": "ຕັ້ງຄ່າຂໍ້ມູນ",
    "scriptSetting": "ຕັ້ງຄ່າ script",
    "listSetting": "ຕັ້ງຄ່າລາຍການ",
    "queryViewSetting": "ຕັ້ງຄ່າມຸມມອງຂໍ້ມູນ",
    "attachmentSetting": "ຕັ້ງຄ່າເອກະສານ",
    "resourceFile": "ເອກະສານ",
    "findDesign": "ຄົ້ນຫາກນອອກແບບ",
    "new": "ສ້າງໃໝ່",
    "appProperty": "ເພີ່ມຄຸນະສົມບັດ",
    "changeIcon": "ປ່ຽນ Icon",
    "ignoreTitleSelectText": ["ຫ້າມຂຽນຫົວຂໍ້ໃນ interfaceໃໝ່","ຈໍາເປັນຂຽນຫົວຂໍ້ໃນ interfaceໃໝ່"],
    "checkDraftSelectText": ["ຂໍ້ມູນinterfaceສາມາດກວດສອບຮ່າງເອກະສານ","ຂໍ້ມູນinterfaceບໍ່ສາມາດກວດສອບຮ່າງເອກະສານ"],
    "showAllDocumentSelectText": ["ສະແດງມຸມມອງເອກະສານທັງໝົດ","ເຊື່ອງມຸມມອງເອກະສນທັງໝົດ"],
    "showDelayDocumentSelectText": ["ສະແດງກຳນົດເວລາເມືອສົ່ງເອກະສານ","ເຊື່ອງການກຳນົດເວລາເມື່ອສົ່ງເອກະສານ"],
    "saveDraftOnClose": ["ບັນທຶກເອກະສານອັດຕະໂນມັດເມື່ອປິດຮ່າງເອກະສານ","ບໍ່ບັນທຶກເອກະສນອັດຕະໂນມັດເມື່ອປິດຮ່າງເອກະສານ"],

    "selectRelateFormNotice": "ກະລຸນາເລືອກແບບຟອມທີ່ກ່ຽວຂ້ອງເຊິ່ງຈຳເປັນຕ້ອງວ່າງມຸມມອງ",

    "projectionTitle": "ແຜນທີ່ຂໍ້ມູນທຸລະກິດ",
    "projectionActionNode_add": "ເພີ່ມລາຍການແຜນທີ່",
    "projectionActionNode_modify": "ແກ້ໄຂລາຍການແຜນທີ່",
    "projectionDataName": "ຊື່ຂໍ້ມູນ",
    "projectionPath": "ເສັ້ນທາງຂໍ້ມູນ",
    "projectionType":"ປະເພດຂໍ້ມູນ",
    "projectionColumnName":"ຊື່ຖັນ",
    "projectionInputError": "ກະລຸນາໃສ່ຊື່ຂໍ້ມູນ ແລະເສັ້ນທາງຂໍ້ມູນ",
    "projectionTypeCountError": "{type}ການປ້ອນຂໍ້ມູນແຜນທີ່ປະເພດ，ອະນຸຍາດຫຼາຍສຸດ{count}ລາຍການ。",
    "projectionSameNameError": "ຊື່ຂໍ້ມູນມີຢູ່ກ່ອນແລ້ວ",
    "projectionDeleteItemTitle": "ລຶບການຢືນຢັນການເຂົ້າແຜນທີ່ຂໍ້ມູນ",
    "projectionDeleteItem": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບຂໍ້ມູນແຜນທີ່ຊື່ \"{name}\" ກັບເສັ້ນທາງ \"{path}\"？",
    "projectionRunActionNode": "ດໍາເນີນການແຜນທີ່ຂໍ້ມູນດຽວນີ້",
    "projectionRunTitle": "ຢືນຢັນດຽວນີ້",
    "projectionRunText": "ກະລຸນາຢືນຢັນເພື່ອເຮັດແຜນທີ່ຂໍ້ມູນທັນທີ",
    "projectionRunSuccess": "ແຜນທີ່ຂໍ້ມູນໄດ້ເລີ່ມປະຕິບັດແລ້ວ",
    "projectionRunError": "ບໍ່ຈໍາເປັນຕ້ອງເຮັດແຜນທີ່ຂໍ້ມູນ",

    "mapping": "ແຜນທີ່",
    "mappingData": "ຂໍ້ມູນແຜນທີ",
    "dataName": "ຊື່ຂໍ້ມູນ",
    "dataPath": "ຂໍ້ມູນເສັ້ນທາງ",
    "dataType": "ປະເພດຂໍ້ມູນ"
};