MWF.xApplication.cms.ColumnManager.LP = {
	"title": "内容管理栏目设置",
	"categoryTitle": "分类管理",
	"description": "描述",
    "deleteItems": "删除选中的内容",

    "copy": "复制",
    "copyto": "复制到...",
    "copyInfor": "选择多个元素，按Ctrl+C可复制元素，按下Ctrl+V可将复制的元素粘贴到当前应用",
    "copyed": "所选元素已复制",
    "copyConfirmTitle": "复制元素确认",
    "copyConfirmInfor": "目标区域已包含相同的元素：",
    "copySource": "原文件:",
    "copyTarget": "复制文件:",
    "copyConfirm_overwrite": "替换",
    "copyConfirm_new": "新建",
    "copyConfirm_skip": "跳过",
    "copyConfirm_cancel": "取消",
    "copynew": "新",

    "setting" : "设置",

    "ok": "确定",
    "edit": "编辑",
    "save": "保存",
    "cancel": "取消",

    "phone": "手机",
    "mail": "邮件",

    "deleteElementTitle": "删除设计确认",
    "deleteElement": "是否确定要删除选中的设计元素？",

    "setControllerSuccess" : "设置管理者成功",
    "noAdministratorAccess" : "您没有此栏目的管理权限",

    "createSelectTemplate": "新建：选择模板",
    "templateCategory": "模板分类：",
    "all": "全部",

    "formType": {
        "empty": "空白表单",
        "publishEdit": "发布类编辑表单",
        "publishRead": "发布类阅读表单",
        "dataInput": "数据录入类表单"
    },

	"category": {
        "create": "新建分类",
        "search": "搜索分类",
        "searchText": "请输入关键字",

		"noCategoryNoticeText": "此栏目现在还没有分类，您可以点击此处创建一个新分类",
		"loaded": "分类加载完毕",
		
		"deleteCategoryTitle": "删除分类确认",
		"deleteCategoryConfirm": "是否确定要删除当前分类？",
        "deleteFailAsHasDocument" : "删除分类“{title}”失败，请先删除该分类下的文档。",

        "idLabel" : "分类标识",
        "nameLabel" : "分类名称",
        "aliasLabel" : "分类别名",
        "descriptionLabel" : "分类描述",
        "sortLabel" : "分类排序",
        "columnLabel" : "所属栏目",
        "iconLabel" : "分类图标",
        "formLabel" : "对应表单",
        "formLabelEdit" : "编辑状态表单",
        "formLabelRead" : "阅读状态表单",
        "viewLabel" : "使用列表",
        "defaultViewLabel" : "默认列表",
        "cancel" : "取消",
        "ok" : "确定",
        "inputName":"请输入分类名称",
        "create_cancel_title": "取消新建分类确认",
        "create_cancel": "您确定要取消新建分类吗?",
        "noDescription" : "此分类没有描述",
        "delete" : "删除分类",
        "edit" : "编辑分类",
        "createCategorySuccess" :"分类创建成功",
        "updateCategorySuccess" : "分类修改成功",
        "defaultView" : "默认",
        "insertCateogryBefore" : "插入分类",
        "insertCateogryAfter" : "追加分类",
        "deleteCategory" : "删除分类",
        "moveCategory" : "调整分类顺序",
        "saveCategory" : "保存分类",
        "editCategory" : "编辑分类",
        "cancelEdit" : "取消",
        "categoryProperty" : "分类属性",
        "baseProperty" : "基本属性",
        "useProcess" : "使用流程",
        "setProcessAppSucess" : "设置流程应用成功",
        "setProcessSucess":"设置流程成功",
        "selectProcess":"选择流程",
        "selectProcessApp":"选择流程应用",
        "setCategoryManager" : "设置分类管理者",
        "none" : "无",
        "noProcess" : "系统中没有您可以管理的流程",
        "documentType" : "文档类型",
        "excelImportView" : "数据导入导出视图"
	},
	"form": {
        "create": "新建表单",
        "search": "搜索表单",
        "searchText": "请输入关键字",
        "selectCategoryForm": "选择分类表单",

		"noFormNoticeText": "此栏目现在还没有表单，您可以点击此处创建一个新表单",
		"loaded": "表单加载完毕",
		"deleteFormTitle": "删除表单确认",
		"deleteForm": "删除表单同时将删除此表单的关联列表，是否确定要删除当前表单？",

        "deleteFormTemplateTitle": "删除表单模板确认",
        "deleteFormTemplate": "是否确定要删除当前表单模板吗？"
		
	},
    "view": {
        "create": "新建列表",
        "search": "搜索列表",
        "searchText": "请输入关键字",
        "selectRelativeForm" : "选择列表关联表单",

        "noViewNoticeText": "此栏目现在还没有列表，您可以点击此处创建一个列表",
        "noViewNoCreateNoticeText": "此栏目现在没有列表",
        "loaded": "列表加载完毕",
        "deleteFormTitle": "删除列表确认",
        "deleteForm": "是否确定要删除当前列表？",
        "selectRelativeFormNoticeText" : "请选择需粘贴视图的关联表单"
    },
    "dictionary": {
        "create": "新建数据字典",
        "search": "搜索数据字典",
        "searchText": "请输入关键字",

        "noDictionaryNoticeText": "此栏目现在还没有数据字典，您可以点击此处创建一个新数据字典",
        "noDictionaryNoCreateNoticeText": "此栏目现在没有数据字典",
        "loaded": "数据字典加载完毕",
        "deleteFormTitle": "删除数据字典确认",
        "deleteForm": "是否确定要删除当前数据字典？"
    },
    "script": {
        "create": "新建脚本",
        "search": "搜索脚本",
        "searchText": "请输入关键字",

        "noScriptNoticeText": "此栏目现在还没有脚本，您可以点击此处创建一个新脚本",
        "loaded": "脚本加载完毕",
        "deleteFormTitle": "删除脚本确认",
        "deleteForm": "是否确定要删除当前脚本？"
    },
    "application": {
        "inputApplicationName": "请输入栏目名称",
        "saveSuccess" : "保存成功",
        "id" : "栏目标识",
        "property": "基本属性",
        "name": "栏目名称",
        "alias": "栏目别名",
        "description": "栏目描述",
        "sort" : "栏目排序",
        "documentType": "文档类型",
        "showAllDocumentViews" : "栏目视图",
        "icon": "栏目图标",
        "sign" : "栏目别名",
        "controllerList": "管理者",
        "appType" : "栏目类型",
        "ignoreTitle" : "忽略标题",
        "latest" : "检查草稿",
        viewerSetting : {
            title : "可见范围",
            set: "设置可见范围",
            setSuccess : "设置可见范围成功"
        },
        publisherSetting : {
            title : "发布者",
            set: "设置发布者",
            setSuccess : "设置发布者成功"
        },
        managerSetting : {
            title : "管理者",
            set: "设置管理者",
            setSuccess : "设置管理者成功"
        }
    },
    "queryView": {
        "create": "新建数据视图",
        "search": "搜索数据视图",
        "searchText": "请输入关键字",
        "selectRelativeForm" : "选择视图关联表单",

        "noViewNoticeText": "此栏目现在还没有数据视图，您可以点击此处创建一个数据视图",
        "noViewNoCreateNoticeText": "此栏目现在没有数据视图",
        "loaded": "数据视图加载完毕",
        "deleteFormTitle": "删除数据视图确认",
        "deleteForm": "是否确定要删除当前数据视图？"
    },
    "file": {
        "create": "新建附件",
        "search": "搜索附件",
        "searchText": "请输入关键字",
        "description": "附件信息",

        "noScriptNoticeText": "此应用现在还没有附件，您可以点击此处创建一个新附件",
        "loaded": "附件加载完毕",
        "deleteFormTitle": "删除附件确认",
        "deleteForm": "是否确定要删除当前附件？",
        "saveSuccess": "附件已保存！",
        "saveConfirm": "保存确认",
        "saveConfirmText": "附件已被修改，您是否要保存修改的内容？",
        "uploadSuccess": "附件已上传",
        "loadFiles": "批量上传附件"
    },

    "name": "名称",
    "alias": "别名",
    "attachment": "附件",
    "upload": "上传附件",

    "selectDataView" : "选择数据视图",
    "selectDataViewTitle" : "从已有数据视图中选择",

    "selectList": "选择列表",
    "selectListTitle": "从已有列表中选择",

    "categoryDisplay" : "分类展现",
    "setCategoryListSuccess": "设置分类列表成功",
    "setDefaultViewSuccess": "设置默认视图成功",
    "cancelCategoryListSuccess": "取消分类列表成功",
    "setImpExpViewSuccess" : "设置分类导入导出视图成功",
    "setCategoryAliasSuccess": "设置分类别名成功",
    "setDocumentTypeSuccess": "设置文档类型成功",
    "setEditFormSuccess": "设置编辑表单成功",
    "setReadFormSuccess": "设置阅读表单成功",
    "inputCategoryNotice": "请输入分类名称",
    "noCategoryNotice": "请先新建或者选择分类",
    "saveCategoryNotice":"请先保存分类",
    "dragToDesktopNotice": "可以拖动到桌面",
    "asEditForm": "设为编辑表单",
    "asReadForm": "设为阅读表单",
    "delete": "删除",
    "notAddListOrView": "未添加列表或者数据视图",
    "systemList": "系统列表",
    "selectCategoryNotice":"请先选择分类",
    "conflictedListNotice": "列表{text}已经存在了，不再重复添加！",
    "selectView": "选择视图",
    "conflictedViewNotice": "视图{text}已经存在了，不再重复添加！",
    "list": "列表",
    "view1": "视图",
    "setAsDefaultList": "设为分类默认列表",
    "adjustOrder": "调整顺序",
    "cancelEdit": "取消编辑",
    "enableProcess" : "固定审批流",
    "disableProcess": "禁用审批流",
    "documentTypeSelectValue": ["信息","数据"],
    "documentTypeSelectText": ["信息","数据"],
    "infor": "信息",
    "data": "数据",
    "type": "类型",
    "listName": "列表名称",
    "relativeForm": "关联表单",
    "dataView": "数据视图",
    "viewName": "视图名称",
    "column": "栏目",
    "categorySetting": "分类配置",
    "formSetting": "表单配置",
    "dataSetting": "数据配置",
    "scriptSetting": "脚本配置",
    "listSetting": "列表配置",
    "queryViewSetting": "数据视图配置",
    "attachmentSetting": "附件配置",
    "resourceFile": "资源文件",
    "findDesign": "查找设计",
    "new": "新建",
    "appProperty": "栏目属性",
    "changeIcon": "更改图标",
    "ignoreTitleSelectText": ["新建界面不填写标题","新建界面需要填写标题"],
    "checkDraftSelectText": ["新建界面检查草稿","新建界面不检查草稿"],
    "showAllDocumentSelectText": ["显示所有文档视图","隐藏所有文档视图"],

    "selectRelateFormNotice": "请选择需粘贴视图的关联表单"
};