MWF.xApplication.cms.ColumnManager = MWF.xApplication.cms.ColumnManager || {};
MWF.xApplication.cms.ColumnManager.LP = {
	"title": "內容管理欄目設置",
    "categoryTitle": "分類管理",
    "description": "描述",
    "deleteItems": "刪除選定的內容",
    "copy": "複製",
    "copyto": "複製到...",
    "copyInfor": "選擇多個項目，按Ctrl+C可以複製項目，按下Ctrl+V可以將複製的項目粘貼到當前應用程序",
    "copyed": "所選項目已複製",
    "copyConfirmTitle": "複製項目確認",
    "copyConfirmInfor": "目標區域已包含相同的項目：",
    "copySource": "原文件：",
    "copyTarget": "複製文件：",
    "copyConfirm_overwrite": "替換",
    "copyConfirm_new": "新建",
    "copyConfirm_skip": "跳過",
    "copyConfirm_cancel": "取消",
    "copynew": "新",

    "setting": "設置",

    "ok": "確定",
    "edit": "編輯",
    "save": "保存",
    "cancel": "取消",

    "phone": "手機",
    "mail": "郵件",

    "deleteElementTitle": "刪除設計確認",
    "deleteElement": "是否確定要刪除選定的設計元素？",
    "setControllerSuccess": "設定管理員成功",
    "noAdministratorAccess": "您無權管理此欄目",
    "createSelectTemplate": "新建：選擇模板",
    "templateCategory": "模板分類：",
    "all": "全部",

    "formType": {
        "empty": "空白表單",
        "publishEdit": "發佈類編輯表單",
        "publishRead": "發佈類閱讀表單",
        "publishEditGreen": "發佈類編輯表單 (綠色)",
        "publishReadGreen": "發佈類閱讀表單 (綠色)",
        "dataInput": "數據輸入類表單"
    },

	"category": {
        "create": "新建分類",
		"search": "搜索分類",
		"searchText": "請輸入關鍵字。",
		"noCategoryNoticeText": "此欄目現在還沒有分類，您可以點擊此處創建一個新分類。",
		"loaded": "分類載入完成",
		"deleteCategoryTitle": "刪除分類確認",
		"deleteCategoryConfirm": "是否確定要刪除當前分類？",
		"deleteFailAsHasDocument": "刪除分類 '{title}' 失敗，請先刪除該分類下的文件。",

        "idLabel": "分類標識",
		"nameLabel": "分類名稱",
		"aliasLabel": "分類別名",
		"sendNotify": "發布時是否發送消息",
		"sendNotifyInfo": "具體消息策略在表單中配置",
		"blankToAllNotify": "發布範圍為空時是否全員通知",
		"descriptionLabel": "分類描述",
		"sortLabel": "分類排序",
		"columnLabel": "所屬欄目",
		"iconLabel": "分類圖標",
		"formLabel": "對應表單",
		"formLabelEdit": "編輯狀態表單",
		"formLabelRead": "閱讀狀態表單",
		"viewLabel": "使用列表",
		"defaultViewLabel": "默認列表",
		"cancel": "取消",
		"ok": "確定",
		"inputName": "請輸入分類名稱",
		"create_cancel_title": "取消新建分類確認",
		"create_cancel": "您確定要取消新建分類嗎？",
		"noDescription": "此分類沒有描述",
		"delete": "刪除分類",
		"edit": "編輯分類",
        "createCategorySuccess": "分類創建成功",
		"updateCategorySuccess": "分類修改成功",
		"defaultView": "默認",
		"insertCateogryBefore": "在分類之前插入",
		"insertCateogryAfter": "在分類之後追加",
		"deleteCategory": "刪除分類",
		"moveCategory": "調整分類順序",
		"saveCategory": "保存分類",
		"editCategory": "編輯分類",
		"cancelEdit": "取消",
		"categoryProperty": "分類屬性",
		"baseProperty": "基本屬性",
		"useProcess": "使用流程",
		"setProcessAppSucess": "設置流程應用成功",
		"setProcessSucess": "設置流程成功",
		"selectProcess": "選擇流程",
		"selectProcessApp": "選擇流程應用",
		"setCategoryManager": "設置分類管理員",
		"none": "無",
		"noProcess": "系統中沒有您可以管理的流程",
		"documentType": "文檔類型",
		"excelImportView": "數據導入導出視圖",
		"useProcessForm": "使用流程表單",
		"useProcessFormNote": "注：如果使用流程表單，那麼發佈後的文檔將使用流程表單打開，否則將使用分類設置的表單。",
		"setSucess": "設置成功"
	},
	"form": {
        "create": "新建表單",
		"search": "搜尋表單",
		"searchText": "請輸入關鍵字",
		"selectCategoryForm": "選擇分類表單",
		"noFormNoticeText": "此分類目前沒有表單，您可以點擊此處創建一個新表單。",
		"loaded": "表單加載完成",
		"deleteFormTitle": "刪除表單確認",
		"deleteForm": "刪除表單時將同時刪除與該表單關聯的列表，您確定要刪除當前表單嗎？",
		"deleteFormTemplateTitle": "刪除表單模板確認",
		"deleteFormTemplate": "您確定要刪除當前表單模板嗎？"
		
	},
    "view": {
        "create": "新建清單",
		"search": "搜尋清單",
		"searchText": "請輸入關鍵字",
		"selectRelativeForm": "選擇相關表單",
		"noViewNoticeText": "此設計元素已不再使用。請使用視圖或查詢配置以展示數據。",
		"noViewNoCreateNoticeText": "此分類目前沒有清單。",
		"loaded": "清單加載完成",
		"deleteFormTitle": "刪除清單確認",
		"deleteForm": "您確定要刪除當前清單嗎？",
		"selectRelativeFormNoticeText": "請選擇要粘貼視圖的相關表單"
    },
    "dictionary": {
        "create": "新建數據字典",
		"search": "搜索數據字典",
		"searchText": "請輸入關鍵字",
		"noDictionaryNoticeText": "此分類目前沒有數據字典。您可以點擊此處創建新的數據字典。",
		"noDictionaryNoCreateNoticeText": "此分類目前沒有數據字典。",
		"loaded": "數據字典加載完成",
		"deleteFormTitle": "刪除數據字典確認",
		"deleteForm": "您確定要刪除當前數據字典嗎？"
    },
    "script": {
        "create": "新建腳本",
		"search": "搜索腳本",
		"searchText": "請輸入關鍵字",
		"noScriptNoticeText": "此分類目前沒有腳本。您可以點擊此處創建新的腳本。",
		"loaded": "腳本加載完成",
		"deleteFormTitle": "刪除腳本確認",
		"deleteForm": "您確定要刪除當前腳本嗎？"
    },
    "application": {
        "inputApplicationName": "請輸入欄目名稱",
		"saveSuccess" : "保存成功",
		"id" : "欄目標識",
		"property": "基本屬性",
		"name": "欄目名稱",
		"alias": "欄目別名",
		"description": "欄目描述",
		"sort" : "欄目排序",
		"documentType": "文檔類型",
		"showAllDocumentViews" : "欄目視圖",
		"icon": "欄目圖標",
		"sign" : "欄目別名",
		"controllerList": "管理者清單",
		"appType" : "欄目類型",
		"ignoreTitle" : "忽略標題",
		"latest" : "檢查草稿",
		"delayView": "定時視圖",
		"saveDraftOnClose": "自動保存",
		"defaultEditForm": "默認編輯表單",
		"defaultReadForm": "默認閱讀表單",
		"editformNote": "註：創建分類時的默認編輯表單",
		"readformNote": "註：創建分類時的默認閱讀表單，如果不選則和編輯表單一致",
        "viewerSetting": {
			"title": "可見範圍",
			"set": "設置可見範圍",
			"setSuccess": "設置可見範圍成功"
		},
		"publisherSetting": {
			"title": "發布者",
			"set": "設置發布者",
			"setSuccess": "設置發布者成功"
		},
		"managerSetting": {
			"title": "管理員",
			"set": "設置管理員",
			"setSuccess": "設置管理員成功"
		}
    },
    "queryView": {
        "create": "建立數據視圖",
		"search": "搜索數據視圖",
		"searchText": "請輸入關鍵字",
		"selectRelativeForm": "選擇相關表格",
		"noViewNoticeText": "此項目目前沒有數據視圖，您可以點擊此處創建一個新的數據視圖。",
		"noViewNoCreateNoticeText": "此項目目前沒有數據視圖。",
		"loaded": "數據視圖已加載完畢。",
		"deleteFormTitle": "刪除數據視圖確認",
		"deleteForm": "您確定要刪除當前的數據視圖嗎？"
    },
    "file": {
        "create": "建立附件",
		"search": "搜尋附件",
		"searchText": "請輸入關鍵字",
		"description": "附件資訊",
		"noScriptNoticeText": "目前此應用程式中沒有附件。您可以點擊此處建立新附件。",
		"loaded": "附件已載入完畢。",
		"deleteFormTitle": "刪除附件確認",
		"deleteForm": "您確定要刪除目前的附件嗎？",
		"saveSuccess": "附件已儲存！",
		"saveConfirm": "儲存確認",
		"saveConfirmText": "附件已被修改。您要儲存修改的內容嗎？",
		"uploadSuccess": "附件已上傳",
		"loadFiles": "批次上傳附件"
    },

    "enable": "啟用",
    "disable": "停用",
    "name": "名稱",
    "alias": "別名",
    "attachment": "附件",
    "upload": "上傳附件",
    "selectDataView": "選擇資料視圖",
    "selectDataViewTitle": "從現有資料視圖中選擇",
    "selectList": "選擇列表",
    "selectListTitle": "從現有列表中選擇",

    "categoryDisplay": "分類顯示",
    "setCategoryListSuccess": "設置分類列表成功",
    "setDefaultViewSuccess": "設置默認視圖成功",
    "cancelCategoryListSuccess": "取消分類列表成功",
    "setImpExpViewSuccess": "設置導入/導出視圖成功",
    "setCategoryAliasSuccess": "設置分類別名成功",
    "setDocumentTypeSuccess": "設置文件類型成功",
    "setSendNotifySuccess": "設置是否發送消息成功",
    "setBlankToAllNotifySuccess": "設置發布範圍為空是否發送消息成功",
    "setEditFormSuccess": "設置編輯表單成功",
    "setReadFormSuccess": "設置閱讀表單成功",
    "setProjectionSuccess": "設置數據映射成功",
    "inputCategoryNotice": "請輸入分類名稱",
    "noCategoryNotice": "請先創建或選擇分類",
    "saveCategoryNotice": "請先保存分類",
    "dragToDesktopNotice": "可拖動到桌面",
    "asEditForm": "設為編輯表單",
    "asReadForm": "設為閱讀表單",
    "delete": "刪除",
    "notAddListOrView": "未添加列表或數據視圖",
    "systemList": "系統列表",
    "selectCategoryNotice": "請先選擇分類",
    "conflictedListNotice": "列表'{text}'已經存在。請勿重複添加！",
    "selectView": "選擇視圖",
    "conflictedViewNotice": "視圖'{text}'已經存在。請勿重複添加！",
    "list": "列表",
    "view1": "視圖",
    "setAsDefaultList": "設為分類默認列表",
    "adjustOrder": "調整順序",
    "cancelEdit": "取消編輯",
    "enableProcess": "固定審批流程",
    "disableProcess": "禁用審批流程",
    "documentTypeSelectValue": ["信息", "數據"],
    "documentTypeSelectText": ["信息", "數據"],
    "sendNotifySelectText": ["是", "否"],
    "sendNotifySelectValue": ["true", "false"],
    "blankToAllNotifySelectText": ["是", "否"],
    "blankToAllNotifySelectValue": ["true", "false"],
    "infor": "信息",
    "data": "數據",
    "type": "類型",
    "listName": "列表名稱",
    "relativeForm": "關聯表單",
    "dataView": "視圖",
    "viewName": "視圖名稱",
    "column": "欄",
    "categorySetting": "分類設置",
    "formSetting": "表單設置",
    "dataSetting": "數據設置",
    "scriptSetting": "腳本設置",
    "listSetting": "列表設置",
    "queryViewSetting": "數據視圖設置",
    "attachmentSetting": "附件設置",
    "resourceFile": "資源文件",
    "findDesign": "查找設計",
    "new": "新建",
    "appProperty": "分類屬性",
    "changeIcon": "更改圖示",
    "ignoreTitleSelectText": ["新建界面不填寫標題", "新建界面需要填寫標題"],
    "checkDraftSelectText": ["新建界面檢查草稿", "新建界面不檢查草稿"],
    "showAllDocumentSelectText": ["顯示所有文檔視圖", "隱藏所有文檔視圖"],
    "showDelayDocumentSelectText": ["顯示定時發佈文檔視圖", "隱藏定時發佈文檔視圖"],
    "saveDraftOnClose": ["關閉草稿時自動保存文檔", "關閉草稿時不自動保存文檔"],

    "selectRelateFormNotice": "請選擇要粘貼視圖的相關表單",

    "projectionTitle": "映射業務數據",
    "projectionActionNode_add": "添加映射條目",
    "projectionActionNode_modify": "修改映射條目",
    "projectionDataName": "數據名稱",
    "projectionPath": "數據路徑",
    "projectionType": "數據類型",
    "projectionColumnName": "列名",
    "projectionInputError": "請輸入數據名稱和數據路徑",
    "projectionTypeCountError": "{type}類型的數據映射條目，最多允許{count}條。",
    "projectionSameNameError": "相同的數據名稱已存在",
    "projectionDeleteItemTitle": "刪除數據映射條目確認",
    "projectionDeleteItem": "您確定要刪除名為“{name}”，路徑為“{path}”的數據映射條目嗎？",
    "projectionRunActionNode": "立即運行數據映射",
    "projectionRunTitle": "立即執行確認",
    "projectionRunText": "請確認立即執行數據映射",
    "projectionRunSuccess": "數據映射已成功啟動",
    "projectionRunError": "無需執行數據映射",

    "mapping": "映射",
    "mappingData": "映射業務數據",
    "dataName": "數據名稱",
    "dataPath": "數據路徑",
    "dataType": "數據類型"
};