MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.ftsearch = MWF.xApplication.ftsearch || {};
MWF.xApplication.ftsearch.LP={
	"title": "Search",
	"searchCondition": "Search Condition",
	"searchInfor": "Find about {count} of relevant results for you, which takes {time} seconds",
	"location": "Your location:",
	"searchDisable": "Search Disabled",
	"cms": "CMS",
	"processPlatform": "Process Management",
	"processManager": "Process Management",
	"cmsManager": "Content Management",
	"noData": "No data was found according to the condition",
	"noSearchkey": "Please enter a keyword to search",
	"noSearchkeyAndCondition": "Please enter a keyword or click filter to search",
	"searchPlacholder": "Please enter a keyword and press \"Enter\" to search",
	"docTotalInfor": "Find <span class='mainColor_color'>{count}</span> related results, it took {time} seconds",
	"mainPage": "Home",
	"search": "Search",
	"index": "Advanced Search",
	"ftsearch": "Full Text Search",
	"filter": "Filter",
	"summary": "Summary",
	"docTitle": "Title",
	"createTime": "Create Time",
	"completedTime": "End Time",
	"activityName": "Node",
	"creatorUnit": "Department",
	"creatorIdentity": "Creator",
	"publishTime": "Publish Time",
	"processList": "Process",
	"creatorUnitList": "Create Organization",
	"startTimeMonthList": "Creation month",
	"completedTimeMonthList": "Completed Month",
	"activityNameList": "Activity",
	"workStatusList": "Process Status",
	"updateTime": "Update Time",
	"completed": "Completed",
	"true": "true",
	"false": "false",
	"application": "Process Application",
	"process": "Process",
	"appInfo": "Content Management",
	"categoryInfo": "Category",
	"general": "General",
	"column": "Column",
	"category": "Category",
	"unit": "Organization",
	"app": "App",
	"createTimeMonth": "Create month",
	"updateTimeMonth": "Update Month",
	"creatorPerson": "Creator",
	"workCompleted": "Work Completed",
	"work": "Working in Circulation",
	"document": "Content Management Document",
	"applicationName": "Process Application",
	"processName": "Process Application",
	"appName": "Content Management Section",
	"categoryName": "Content Management Category",
	"selectConditionNote": "Please select",
	"fieldSelect": "Column Select",
	"more": "more",
	"collapse": "Collapse",
	"multiSelect": "Multiple Select",
	"ok": "OK",
	"cancel": "Cancel",
	"reset": "Reset",
	"export": "Export",
	"moreFilter": "More filter criteria",
	"collapseFilter": "Collapse filter criteria",
	"rangeSeparator": "to",
	"startPlaceholder": "Start time",
	"endPlaceholder": "End time",
	"to": "to",
	"min": "minimum value",
	"max": "Maximum value",
	"fromValue": "Start Value",
	"toValue": "End Value",
	"minGreatThanMaxError": "Start value cannot be greater than end value",
	"tooMinError": "Cannot be less than the minimum value",
	"tooMaxError": "Cannot be greater than the maximum value",
	"moreFieldSelect": "More column selection",
	"collapseFieldSelect": "Collapse column selection",
	"firstPage": "First Page",
	"lastPage": "Last Page",
	"selectModule": "Select Application",
	"searching": "You are searching",
	"switch": "Switch",
	"searchCorePlacholder": "Please enter a keyword and press \"Enter\" to search for an application or process",
	"expandCondition": "Expand",
	"collapseCondition": "Collapse"
}
MWF.xApplication.ftsearch["lp."+o2.language] = MWF.xApplication.ftsearch.LP