MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.ftsearch = MWF.xApplication.ftsearch || {};
MWF.xApplication.ftsearch.LP={
	"title": "Buscar",
	"searchCondition": "Condiciones de búsqueda",
	"searchInfor": "Se encontraron aproximadamente {count} resultados relacionados en aprox. {time} segundos",
	"location": "Tu ubicación:",
	"searchDisable": "La búsqueda no está habilitada",
	"cms": "Gestión de contenido",
	"processPlatform": "Gestión de procesos",
	"processManager": "Gestión de procesos",
	"cmsManager": "Gestión de contenido",
	"noData": "No se encontraron datos según las condiciones de búsqueda",
	"noSearchkey": "Ingrese una palabra clave para buscar",
	"noSearchkeyAndCondition": "Ingrese una palabra clave o haga clic en los términos de búsqueda para comenzar la búsqueda.",
	"searchPlacholder": "Ingrese una palabra clave y presione 'Enter' para buscar",
	"docTotalInfor": "Se encontraron <span class='mainColor_color'>{count}</span> resultados relacionados en aprox. {time} segundos",
	"mainPage": "Página principal",
	"search": "Buscar",
	"index": "Búsqueda avanzada",
	"ftsearch": "Búsqueda de texto completo",
	"filter": "Filtrar",
	"summary": "Resumen",
	"docTitle": "Título",
	"createTime": "Fecha de creación",
	"completedTime": "Fecha de finalización",
	"activityName": "Nodo",
	"creatorUnit": "Departamento del creador",
	"creatorIdentity": "Creador",
	"publishTime": "Fecha de publicación",
	"processList": "Procesos",
	"creatorUnitList": "Unidad creadora",
	"startTimeMonthList": "Mes de creación",
	"completedTimeMonthList": "Mes de finalización",
	"activityNameList": "Actividades",
	"workStatusList": "Estado del proceso",
	"updateTime": "Fecha de actualización",
	"completed": "Completado",
	"true": "Sí",
	"false": "No",
	"application": "Aplicación del proceso",
	"process": "Proceso",
	"appInfo": "Gestión de contenido",
	"categoryInfo": "Categoría",
	"general": "General",
	"column": "Columna",
	"category": "Categoría",
	"unit": "Unidad",
	"app": "Aplicación",
	"createTimeMonth": "Mes de creación",
	"updateTimeMonth": "Mes de actualización",
	"creatorPerson": "Creador",
	"workCompleted": "Trabajo completado",
	"work": "Trabajo en curso",
	"document": "Documento de gestión de contenido",
	"applicationName": "Aplicación del proceso",
	"processName": "Proceso",
	"appName": "Columna de gestión de contenido",
	"categoryName": "Categoría de gestión de contenido",
	"selectConditionNote": "Seleccione",
	"fieldSelect": "Selección de columna",
	"more": "Más",
	"collapse": "Contraer",
	"multiSelect": "Selección múltiple",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"reset": "Reiniciar",
	"export": "Exportar",
	"moreFilter": "Más opciones de filtrado",
	"collapseFilter": "Contraer opciones de filtrado",
	"rangeSeparator": "-",
	"startPlaceholder": "Fecha de inicio",
	"endPlaceholder": "Fecha de finalización",
	"to": "a",
	"min": "Valor mínimo",
	"max": "Valor máximo",
	"fromValue": "Valor inicial",
	"toValue": "Valor final",
	"minGreatThanMaxError": "El valor inicial no puede ser mayor que el valor final",
	"tooMinError": "No puede ser menor que el valor mínimo",
	"tooMaxError": "No puede ser mayor que el valor máximo",
	"moreFieldSelect": "Más selección de columnas",
	"collapseFieldSelect": "Contraer selección de columnas",
	"firstPage": "Primera",
	"lastPage": "Última",
	"selectModule": "Seleccionar aplicación",
	"searching": "Buscando",
	"switch": "Cambiar",
	"searchCorePlacholder": "Ingrese una palabra clave y presione 'Enter' para buscar aplicaciones o procesos",
	"expandCondition": "Más opciones de filtrado",
	"collapseCondition": "Contraer opciones de filtrado"
}
MWF.xApplication.ftsearch["lp."+o2.language] = MWF.xApplication.ftsearch.LP