MWF.xApplication.ftsearch.LP = {
	"title": "검색",
	"searchCondition": "검색 조건",
	"searchInfor": "관련 결과 약 {count}개, {time}초 걸림",
	"location": "귀하의 위치:",
	"searchDisable": "검색이 비활성화되었습니다",
	"cms": "콘텐츠 관리",
	"processPlatform": "프로세스 관리",
	"processManager": "프로세스 관리",
	"cmsManager": "콘텐츠 관리",
	"noData": "조건에 맞는 데이터를 찾을 수 없습니다",
	"noSearchkey": "검색어를 입력하십시오",
	"noSearchkeyAndCondition": "키워드를 입력하거나 필터 조건을 클릭하십시오",
	"searchPlacholder": "키워드를 입력하고 'Enter' 키를 눌러 검색하십시오",
	"docTotalInfor": "관련 결과를 찾았습니다 <span class='mainColor_color'>{count}</span>개, {time}초 소요",
	"mainPage": "홈페이지",
	"search": "검색",
	"index": "고급 검색",
	"ftsearch": "전체 텍스트 검색",
	"filter": "필터",
	"summary": "요약",
	"docTitle": "제목",
	"createTime": "생성 날짜",
	"completedTime": "종료 날짜",
	"activityName": "노드",
	"creatorUnit": "부서",
	"creatorIdentity": "작성자",
	"publishTime": "게시 날짜",

    "processList": "프로세스",
	"creatorUnitList": "생성 조직",
	"startTimeMonthList": "생성 월",
	"completedTimeMonthList": "완료 월",
	"activityNameList": "활동",
	"workStatusList": "프로세스 상태",
	"updateTime": "업데이트 시간",
	"completed": "완료됨",
	"true": "예",
	"false": "아니오",
	"application": "프로세스 응용프로그램",
	"process": "프로세스",
	"appInfo": "콘텐츠 관리",
	"categoryInfo": "카테고리",
	"general": "일반",
	"column": "컬럼",
	"category": "카테고리",
	"unit": "조직",
	"app": "응용프로그램",
	"createTimeMonth": "생성 월",
	"updateTimeMonth": "업데이트 월",
	"creatorPerson": "생성자",
	"workCompleted": "완료된 작업",
	"work": "진행 중인 작업",
	"document": "콘텐츠 관리 문서",
	"applicationName": "프로세스 응용프로그램",
	"processName": "프로세스 응용프로그램",
	"appName": "콘텐츠 관리 컬럼",
	"categoryName": "콘텐츠 관리 카테고리",
	"selectConditionNote": "선택하세요",
	"fieldSelect": "열 선택",

    "more": "더보기",
	"collapse": "접기",
	"multiSelect": "다중 선택",
	"ok": "확인",
	"cancel": "취소",
	"reset": "초기화",
	"export": "내보내기",
	"moreFilter": "더 많은 필터",
	"collapseFilter": "필터 접기",
	"rangeSeparator": "에서",
	"startPlaceholder": "시작 시간",
	"endPlaceholder": "종료 시간",
	"to": "대상",
	"min": "최소값",
	"max": "최대값",
	"fromValue": "시작 값",
	"toValue": "대상 값",
	"minGreatThanMaxError": "시작 값은 종료 값보다 커서는 안 됩니다",
	"tooMinError": "최소값보다 작을 수 없습니다",
	"tooMaxError": "최대값보다 클 수 없습니다",
	"moreFieldSelect": "더 많은 열 선택",
	"collapseFieldSelect": "열 선택 닫기",
	"firstPage": "첫 페이지",
	"lastPage": "마지막",
	"selectModule": "앱 선택",
	"searching": "현재 검색 중입니다",
	"switch": "전환",
	"searchCorePlacholder": "키워드를 입력하고 'Enter' 키를 눌러 앱 또는 프로세스 검색",
	"expandCondition": "추가 필터 조건",
	"collapseCondition": "필터 조건 닫기"
};
