MWF.xApplication.ftsearch.LP = {
	"title": "ຄົ້ນຫາ",
	"searchCondition": "ເງື່ອນໄຂການຄົ້ນຫາ",

	"searchInfor": "ຊອກຫາກ່ຽວກັບ {count} ຂອງຜົນໄດ້ຮັບທີ່ກ່ຽວຂ້ອງສໍາລັບທ່ານ, ເຊິ່ງໃຊ້ເວລາ {time} ວິນາທີ",

	"location": "ທີ່ຕັ້ງຂອງເຈົ້າ:",
	"searchDisable": "ການຄົ້ນຫາຖືກປິດ",

	"cms": "CMS",
	"processPlatform": "ການຈັດການຂະບວນການ",
	"processManager": "ການຈັດການຂະບວນການ",
	"cmsManager": "ການຈັດການເນື້ອຫາ",
	"noData": "ບໍ່ພົບຂໍ້ມູນຕາມເງື່ອນໄຂ",
	"noSearchkey": "ກະລຸນາໃສ່ຄໍາສໍາຄັນເພື່ອຄົ້ນຫາ",
	"noSearchkeyAndCondition": "ກະລຸນາໃສ່ຄໍາສໍາຄັນຫຼືກົດຕົວກອງເພື່ອຊອກຫາ",
	"searchPlacholder": "ກະລຸນາໃສ່ຄໍາສໍາຄັນແລະກົດ \"Enter\" ເພື່ອຊອກຫາ",
	"docTotalInfor": "ຊອກຫາ <span class='mainColor_color'>{count}</span> ຜົນການຄົ້ນຫາທີ່ກ່ຽວຂ້ອງ, ມັນໃຊ້ເວລາ {time} seconds",

	"mainPage": "ຫນ້າທໍາອິດ",
	"search": "ຄົ້ນຫາ",
	"index": "ການຄົ້ນຫາແບບພິເສດ",
	"ftsearch": "ຊອກຫາຂໍ້ຄວາມເຕັມ",
	"filter": "ການກັ່ນຕອງ",

	"summary": "ສະຫຼຸບ",
	"docTitle": "ຫົວຂໍ້",
// "processName": "ຂະບວນການ",
	"createTime": "ສ້າງເວລາ",
	"completedTime": "ເວລາສິ້ນສຸດ",
	"activityName": "ບ່ອນບັນທຶກ",
	"creatorUnit": "ພະແນກ",
	"creatorIdentity": "ຜູ້ສ້າງ",

// "categoryName": "ໝວດໝູ່",
	"publishTime": "ເວລາເຜີຍແຜ່",

	"processList": "ຂະບວນການ",
	"creatorUnitList": "ສ້າງອົງກອນ",
	"startTimeMonthList": "ເດືອນສ້າງ",
	"completedTimeMonthList": "ເດືອນສຳເລັດ",
	"activityNameList": "ການເຄື່ອນໄຫວ",
	"workStatusList": "ສະຖານະຂະບວນການ",
	"updateTime": "ເວລາອັບເດດ",
	"completed": "ສໍາເລັດ",
	"true": "ຖຶກ",
	"false": "ຜິດ",

	"application": "ຂະບວນການຄໍາຮ້ອງສະຫມັກ",
	"process": "ຂະບວນການ",
	"appInfo": "ການຈັດການເນື້ອຫາ",
	"categoryInfo": "ໝວດໝູ່",
	"general": "ທົ່ວໄປ",

	"column":"ຖັນ",
	"category": "ໝວດ",
	"unit": "ອົງການ",
	"app": "ແອັບ",
	"createTimeMonth": "ສ້າງເດືອນ",
	"updateTimeMonth": "ເດືອນອັບເດດ",
	"creatorPerson": "ຜູ້ສ້າງ",
	"workCompleted": "ວຽກສຳເລັດ",
	"work": "ເຮັດວຽກໃນການໄຫຼວຽນ",
	"document": "ເອກະສານການຄຸ້ມຄອງເນື້ອຫາ",
	"applicationName": "ຂະບວນການຄໍາຮ້ອງສະຫມັກ",
	"processName": "ຄໍາຮ້ອງສະຫມັກຂະບວນການ",
	"appName": "ພາກສ່ວນການຈັດການເນື້ອຫາ",
	"categoryName": "ໝວດການຄຸ້ມຄອງເນື້ອຫາ",
	"selectConditionNote": "ກະລຸນາເລືອກ",
	"fieldSelect": "ເລືອກຖັນ",

	"more": "ຫຼາຍ",
	"collapse": "ຍຸບ",
	"multiSelect": "ເລືອກຫຼາຍອັນ",
	"ok​":  "ຕົກ​ລົງ",
	"cancel": "ຍົກເລີກ",
	"reset": "ຣີເຊັດ",
	"export": "ສົ່ງອອກ",
	"moreFilter": "ເງື່ອນໄຂການກັ່ນຕອງເພີ່ມເຕີມ",
	"collapseFilter": "ຫຍໍ້ເງື່ອນໄຂການກັ່ນຕອງ",

	"rangeSeparator": "ເຖິງ",
	"startPlaceholder": "ເວລາເລີ່ມຕົ້ນ",
	"endPlaceholder": "ເວລາສິ້ນສຸດ",
	"to": "ໄປ",
	"min": "ຄ່າຕໍ່າສຸດ",
	"max": "ຄ່າສູງສຸດ",
	"fromValue": "ຄ່າເລີ່ມຕົ້ນ",
	"toValue": "ຄ່າສິ້ນສຸດ",
	"minGreatThanMaxError": "ຄ່າເລີ່ມຕົ້ນບໍ່ສາມາດໃຫຍ່ກວ່າຄ່າສິ້ນສຸດ",
	"tooMinError": "ບໍ່ສາມາດໜ້ອຍກວ່າຄ່າຕໍ່າສຸດ",
	"tooMaxError": "ບໍ່ສາມາດໃຫຍ່ກວ່າຄ່າສູງສຸດໄດ້",
	"moreFieldSelect": "ເລືອກຖັນເພີ່ມເຕີມ",
	"collapseFieldSelect": "ຫຍໍ້ການເລືອກຖັນ",

	"firstPage": "ໜ້າທຳອິດ",
	"lastPage": "ໜ້າສຸດທ້າຍ",

	"selectModule": "ເລືອກແອັບພລິເຄຊັນ",
	"searching": "ເຈົ້າກຳລັງຊອກຫາ",
	"switch": "ປ່ຽນ",
	"searchCorePlacholder": "ກະລຸນາໃສ່ຄໍາສໍາຄັນແລະກົດ \"Enter\" ເພື່ອຊອກຫາຄໍາຮ້ອງສະຫມັກຫຼືຂະບວນການ",

	"expandCondition":"ຂະຫຍາຍ",
	"collapseCondition": "ຍຸບ"
};