MWF.xApplication.ftsearch.LP = {
	"title": "搜索",
	"searchCondition": "查询条件",

    "searchInfor": "为您找到相关结果约{count}个，耗时{time}秒",

    "location": "您的位置:",
    "searchDisable": "搜索未启用",

    "cms": "内容管理",
    "processPlatform": "流程管理",
    "processManager": "流程管理",
    "cmsManager": "内容管理",
    "noData": "根据条件未查询到数据",
    "noSearchkey": "请输入关键字搜索",
    "noSearchkeyAndCondition": "请输入关键字或点击过滤条件搜索",
    "searchPlacholder": "请输入关键字，按“回车”搜索",
    "docTotalInfor": "查询到相关结果<span class='mainColor_color'>{count}</span>个，耗时{time}秒",

    "mainPage": "首页",
    "search": "搜索",
    "index": "高级搜索",
    "ftsearch": "全文搜索",
    "filter": "过滤",

    "summary": "摘要",
    "docTitle": "标题",
    "createTime": "创建时间",
    "completedTime": "结束时间",
    "activityName": "节点",
    "creatorUnit": "部门",
    "creatorIdentity": "创建者",

    "publishTime": "发布时间",

    "processList": "流程",
    "creatorUnitList": "创建组织",
    "startTimeMonthList": "创建月份",
    "completedTimeMonthList": "完成月份",
    "activityNameList": "活动",
    "workStatusList": "流程状态",
    "updateTime": "更新时间",
    "completed": "已完成",
    "true": "是",
    "false": "否",

    "application": "流程应用",
    "process": "流程",
    "appInfo": "内容管理",
    "categoryInfo": "分类",
    "general": "通用",

    "column":"栏目",
    "category": "分类",
    "unit": "组织",
    "app": "应用",
    "createTimeMonth": "创建月份",
    "updateTimeMonth": "更新月份",
    "creatorPerson": "创建者",
    "workCompleted": "已完成工作",
    "work": "流转中工作",
    "document": "内容管理文档",
    "applicationName": "流程应用",
    "processName": "流程应用",
    "appName": "内容管理栏目",
    "categoryName": "内容管理分类",
    "selectConditionNote": "请选择",
    "fieldSelect": "列选择",

    "more": "更多",
    "collapse": "收起",
    "multiSelect": "多选",
    "ok": "确定",
    "cancel": "取消",
    "reset": "重置",
    "export": "导出",
    "moreFilter": "更多筛选条件",
    "collapseFilter": "收起筛选条件",

    "rangeSeparator": "至",
    "startPlaceholder": "开始时间",
    "endPlaceholder": "结束时间",
    "to": "到",
    "min": "最小值",
    "max": "最大值",
    "fromValue": "起始值",
    "toValue": "结束值",
    "minGreatThanMaxError": "起始值不能大于结束值",
    "tooMinError": "不能小于最小值",
    "tooMaxError": "不能大于最大值",
    "moreFieldSelect": "更多列选择",
    "collapseFieldSelect": "收起列选择",

    "firstPage": "第一页",
    "lastPage": "最后一页",

    "selectModule": "选择应用",
    "searching": "您正在查询",
    "switch": "切换",
    "searchCorePlacholder": "请输入关键字，按“回车”搜索应用或流程",

    "expandCondition":"更多过滤条件",
    "collapseCondition": "收起过滤条件"
};
