/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.mind.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.mind.entity.MindVersionContent.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:46 CST 2018")
public class MindVersionContent_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MindVersionContent,String> content;
    public static volatile SingularAttribute<MindVersionContent,String> id;
}
