/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.mind.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.mind.entity.MindShareRecord.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:46 CST 2018")
public class MindShareRecord_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<MindShareRecord,String> fileId;
    public static volatile SingularAttribute<MindShareRecord,String> fileStatus;
    public static volatile SingularAttribute<MindShareRecord,String> fileType;
    public static volatile SingularAttribute<MindShareRecord,String> id;
    public static volatile SingularAttribute<MindShareRecord,String> name;
    public static volatile SingularAttribute<MindShareRecord,String> shareType;
    public static volatile SingularAttribute<MindShareRecord,String> source;
    public static volatile SingularAttribute<MindShareRecord,String> target;
    public static volatile SingularAttribute<MindShareRecord,String> targetType;
}
