/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.report.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.report.core.entity.Report_I_WorkTag.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:17 CST 2018")
public class Report_I_WorkTag_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Report_I_WorkTag,Date> createTime;
    public static volatile SingularAttribute<Report_I_WorkTag,String> id;
    public static volatile SingularAttribute<Report_I_WorkTag,String> sequence;
    public static volatile SingularAttribute<Report_I_WorkTag,String> tagName;
    public static volatile SingularAttribute<Report_I_WorkTag,String> tagType;
    public static volatile SingularAttribute<Report_I_WorkTag,Date> updateTime;
}
