/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.report.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.report.core.entity.Report_I_Ext_ContentDetail.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:17 CST 2018")
public class Report_I_Ext_ContentDetail_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,String> content;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,String> contentId;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,String> contentType;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,Date> createTime;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,String> id;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,Integer> orderNumber;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,String> profileId;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,String> reportId;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,String> sequence;
    public static volatile SingularAttribute<Report_I_Ext_ContentDetail,Date> updateTime;
}
