/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.report.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.report.core.entity.Report_P_ProfileDetail.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:17 CST 2018")
public class Report_P_ProfileDetail_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Report_P_ProfileDetail,Date> createTime;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> id;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> profileId;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> reportModule;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> reportModuleName;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> sequence;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> snapContent;
    public static volatile SingularAttribute<Report_P_ProfileDetail,String> snapType;
    public static volatile SingularAttribute<Report_P_ProfileDetail,Date> updateTime;
}
