/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.report.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.report.core.entity.Report_R_View.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:17 CST 2018")
public class Report_R_View_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Report_R_View,Date> createTime;
    public static volatile SingularAttribute<Report_R_View,String> id;
    public static volatile SingularAttribute<Report_R_View,Date> lastViewTime;
    public static volatile SingularAttribute<Report_R_View,String> reportId;
    public static volatile SingularAttribute<Report_R_View,String> sequence;
    public static volatile SingularAttribute<Report_R_View,String> title;
    public static volatile SingularAttribute<Report_R_View,Date> updateTime;
    public static volatile SingularAttribute<Report_R_View,Integer> viewCount;
    public static volatile SingularAttribute<Report_R_View,String> viewerName;
}
