MWF.xApplication.AI.LP = {
	"title": "AI Assistant",
	"config" : {
		"title" : "I am O2OA, nice to meet you!",
		"desc" :"I can help you write code, read files, and collaborate on various creative content. Please entrust your tasks to me~",
		"appName" : "Application Name",
		"appIconUrl" : "Application Icon URL",
		"welcome" : "Welcome Theme",
		"aidesc" : "Function Description",
		"aiModel" : "Model Name",
		"knowledge": "Knowledge Base",
		"questions" : "Questions",
		"o2AiEnable": "Enable O2 Agent",
		"o2AiBaseUrl": "O2 Agent Service Address",
		"o2AiToken": "O2 Agent Service Authentication Key"
	},
	"o2AiEnableTip" : "Please enable the O2 agent first",
	"common" : {
		"yes" : "Yes",
		"close" : "Close",
		"all" : "All",
		"no" : "No",
		"tip" : "Tip",
		"save" : "Save",
		"select" : "Select",
		"savesuccess" : "Saved Successfully",
		"removetitle" : "Delete Confirmation",
		"removeconfirm" : "Are you sure you want to delete?",
		"unselectfile" : "No File Selected",
		"export" : "Export",
		"exportconfirm" : "Export Confirmation"
	},
	"navi" : {
		"index" : "Home",
		"newmcp" : "Create New MCP",
		"mcp" : "MCP Settings",
		"model" : "Model Settings",
		"setting" : "Conversation Settings"
	},
	"copysuccess" : "Copied to Clipboard",
	"copyerror" : "Unable to Copy Text",
	"today" : "Today",
	"lastSevenDays" : "Last 7 Days",
	"lastThirtyDays" : "Last 30 Days",
	"older" : "Older",
	"newchat" : "Start New Conversation",
	"expandthingking" : "Collapse Thought Process",
	"collapsethingking" : "Expand Thought Process",
	"thinking" : "Thinking Hard",
	"types" : {
		"auto" : "Automatic",
		"auto_text" : "AI automatically selects the most suitable answer to your question",
		"chat" : "Chat",
		"chat_text" : "Chat directly with AI, ask and answer",
		"task" : "Task",
		"task_text" : "AI assists with OA tasks",
		"knowledge" : "Knowledge Base",
		"knowledge_text" : "AI answers using system documentation data"
	},
	"searchhistory" : "Search History",
	"inputholder" : "Enter content, Shift + Enter for new line",
	"inputholderm" : "Enter content",
	"setting" : "System Settings",
	"newmodule" : "Create New Model",
	"modifymodule" : "Modify Model",
	"newmcp" : "Create New MCP",
	"modifymcp" : "Modify MCP",
	"module" : {
		"name" : "Model Name",
		"desc" : "Model Description",
		"company" : "Model Provider",
		"ali" : "Ali Tongyi Qianwen",
		"local" : "Local Model",
		"version" : "Model Version",
		"completionUrl" : "Model Service URL",
		"apiKey" :"Model Key",
		"asDefault" : "Set as Default",
		"proxyHost" : "Proxy Host",
		"proxyPort" : "Proxy Port",
		"proxyEnable" : "Enable Proxy"
	},
	"mcp" : {
		"name" : "Name",
		"category" : "Category",
		"desc" : "Description",
		"enable" : "Enable",
		"url" : "Interface URL",
		"mcpbody" : "Body Parameter List",
		"addbody" : "Add Body Parameter",
		"mcplist" : "MCP Parameter List",
		"required" : "Required",
		"fieldtype" : "Field Type",
		"addmcp" : "Add MCP Parameter",
		"returntemplate" : "Return Template",
		"script" : "Execution Script"
	}
};
