MWF.xApplication.AI.LP = {
	"title": "Asistente de IA",
	"config" : {
		"title" : "¡Soy O2OA, encantado de conocerte!",
		"desc" :"Puedo ayudarte a escribir código, leer archivos y colaborar en varios contenidos creativos. Por favor, confía tus tareas a mí~",
		"appName" : "Nombre de la Aplicación",
		"appIconUrl" : "URL del Icono de la Aplicación",
		"welcome" : "Tema de Bienvenida",
		"aidesc" : "Descripción de la Función",
		"aiModel" : "Nombre del Modelo",
		"knowledge": "Base de Conocimiento",
		"questions" : "Preguntas",
		"o2AiEnable": "Habilitar Agente O2",
		"o2AiBaseUrl": "Dirección del Servicio del Agente O2",
		"o2AiToken": "Clave de Autenticación del Servicio del Agente O2"
	},
	"o2AiEnableTip" : "Por favor, habilita primero el agente O2",
	"common" : {
		"yes" : "Sí",
		"close" : "Cerrar",
		"all" : "Todos",
		"no" : "No",
		"tip" : "Consejo",
		"save" : "Guardar",
		"select" : "Seleccionar",
		"savesuccess" : "Guardado Exitosamente",
		"removetitle" : "Confirmación de Eliminación",
		"removeconfirm" : "¿Estás seguro de que quieres eliminar?",
		"unselectfile" : "Ningún Archivo Seleccionado",
		"export" : "Exportar",
		"exportconfirm" : "Confirmación de Exportación"
	},
	"navi" : {
		"index" : "Inicio",
		"newmcp" : "Crear Nuevo MCP",
		"mcp" : "Configuraciones MCP",
		"model" : "Configuraciones del Modelo",
		"setting" : "Configuraciones de Conversación"
	},
	"copysuccess" : "Copiado al Portapapeles",
	"copyerror" : "No se Puede Copiar el Texto",
	"today" : "Hoy",
	"lastSevenDays" : "Últimos 7 Días",
	"lastThirtyDays" : "Últimos 30 Días",
	"older" : "Más Antiguo",
	"newchat" : "Iniciar Nueva Conversación",
	"expandthingking" : "Colapsar Proceso de Pensamiento",
	"collapsethingking" : "Expandir Proceso de Pensamiento",
	"thinking" : "Pensando Intensamente",
	"types" : {
		"auto" : "Automático",
		"auto_text" : "La IA selecciona automáticamente la respuesta más adecuada a tu pregunta",
		"chat" : "Chat",
		"chat_text" : "Chatear directamente con IA, preguntar y responder",
		"task" : "Tarea",
		"task_text" : "IA ayuda con tareas de OA",
		"knowledge" : "Base de Conocimiento",
		"knowledge_text" : "IA responde usando datos de documentación del sistema"
	},
	"searchhistory" : "Historial de Búsqueda",
	"inputholder" : "Ingrese contenido, Shift + Enter para nueva línea",
	"inputholderm" : "Ingrese contenido",
	"setting" : "Configuración del Sistema",
	"newmodule" : "Crear Nuevo Modelo",
	"modifymodule" : "Modificar Modelo",
	"newmcp" : "Crear Nuevo MCP",
	"modifymcp" : "Modificar MCP",
	"module" : {
		"name" : "Nombre del Modelo",
		"desc" : "Descripción del Modelo",
		"company" : "Proveedor del Modelo",
		"ali" : "Ali Tongyi Qianwen",
		"local" : "Modelo Local",
		"version" : "Versión del Modelo",
		"completionUrl" : "URL del Servicio del Modelo",
		"apiKey" :"Clave del Modelo",
		"asDefault" : "Establecer como Predeterminado",
		"proxyHost" : "Host del Proxy",
		"proxyPort" : "Puerto del Proxy",
		"proxyEnable" : "Habilitar Proxy"
	},
	"mcp" : {
		"name" : "Nombre",
		"category" : "Categoría",
		"desc" : "Descripción",
		"enable" : "Habilitar",
		"url" : "URL de la Interfaz",
		"mcpbody" : "Lista de Parámetros del Cuerpo",
		"addbody" : "Agregar Parámetro del Cuerpo",
		"mcplist" : "Lista de Parámetros MCP",
		"required" : "Requerido",
		"fieldtype" : "Tipo de Campo",
		"addmcp" : "Agregar Parámetro MCP",
		"returntemplate" : "Plantilla de Retorno",
		"script" : "Script de Ejecución"
	}
};
