MWF.xApplication.query.ViewDesigner.LP = {
    "title": "View Edit",
    "newView": "New View",
    "property": "Property",
    "item": "Item",
    "type": "Type",
    "value": "Value",
    "view": "View",
    "unnamed": "Untitled column",
    "unCategory": "Uncategorized",

    "id": "Id",
    "name": "Name",
    "alias": "Alias",
    "description": "Description",
    "saveViewNotice": "Please save the view first!",

    "application": "Data Application",
    "newView": "New View",
    "newViewName": "New View Name",
    "copy": "Copy",
    "ok": "OK",
    "cancel": "Cancel",

    "action": {
        "move": "Move",
        "delete": "Delete",
        "add": "Add"
    },

    "notice": {
        "save_success": "The view was saved successfully!",
        "saveAs_success": "The view is saved as successfully. You can open a new view in the view settings!",

        "deleteFilterTitle": "Delete FilterTitle Confirmation",
        "deleteFilter": "Are you sure you want to delete the filter criteria?",

        "deleteColumnTitle": "Delete column confirmation",
        "deleteColumn": "Are you sure you want to delete the current column?",


        "changeTypeTitle": "Change Data Type Confirmation",
        "changeTypeDeleteChildren": "Changing the data type will delete all child data. Are you sure you want to execute it?",
        "changeType": "Changing the data type will change the value of the data. Are you sure you want to execute it?",

        "inputTypeError": "The data type you entered is wrong, please re-enter",
        "sameKey": "The item name you entered already exists in the object, please re-enter",
        "emptyKey": "Project name cannot be empty, please re-enter",
        "numberKey": "The item name cannot be a number, please re-enter",

        "inputName": "Please enter the view name",
        "noModifyName": "Cannot modify the name or alias",

        "deleteEventTitle": "Delete Event Confirmation",
        "deleteEvent": "Are you sure you want to delete the current event?",

        "selectProcess": "Please select an application or process",
        "selectCMS": "Please select content management column or category",
        "selectDateRange": "The period type is a range, please select the start date and end date"
    },
    "actionbar": {
        "readhide": "Set whether to display when reading",
        "edithide": "Set whether to display when editing",
        "hideCondition": "Set hiding conditions",
        "title": "Title",
        "img": "Icon",
        "action": "Action",
        "condition": "Display Condition",
        "editScript": "Operation Script Editing",
        "editCondition": "Hide condition editing (return true to hide operation)",
        "up": "Move up",
        "property": "Property",
        "addCustomTool": "Add custom operation",
        "delete": "Delete",
        "setProperties": "Set operation properties",
        "restoreDefaultTool": "Restore deleted system operations",
        "selectDefaultTool": "Select System Operation"
    },
    "mastInputPath": "Please enter the data path",
    "mastInputTitle": "Please enter a title",
    "filter": {
        "and": "and",
        "or": "Or",
        "equals": "Equals",
        "notEquals": "Not Equals",
        "greaterThan": "Greater Than",
        "greaterThanOrEqualTo": "Greater Than Equal To",
        "lessThan": "less than",
        "lessThanOrEqualTo": "Less than or equal to",
        "like": "match",
        "notLike": "Does not match",
        "range": "range",
        "logic": "Logic",
        "path": "Path",
        "compare": "Compare",
        "value": "Value",
        "columnValue": "Column Value",
        "contain": "Contain",
        "from": "from"
    },
    "delete_filterItem_title": "Confirm Delete Filter Condition",
    "delete_filterItem": "Are you sure you want to delete the current filter?",
    "propertyTemplate": {
        "base": "Basic",
        "event": "Event",
        "html": "HTML",
        "json": "JSON",
        "action": "Action",
        "select": "Select",
        "alias": "Alias",

        "id": "Id",
        "name": "Name",
        "description": "Description",
        "appearance": "Appearance Type",
        "style": "Style",
        "attribute": "Attribute",
        "systemAction": "System Action",

        "show": "Show",
        "hide": "Hide",
        "columnTitle": "Column Title",
        "columnName":"Column Name",
        "defaultValue":"Default Value",
        "openDocument":"Open Document",
        "yes":"Yes",
        "no":"No",
        "openDocumentScript":"Open Document Script",
        "data":"Data",
        "selectData":"Select Data",
        "selectTitle":"(Please select)",
        "title":"title",
        "startTime":"Create Time",
        "startTimeMonth":"Create Month",
        "completedTime":"Completed Time",
        "completedTimeMonth":"Complete Month",
        "creatorPerson":"Drafter",
        "creatorIdentity":"Author's Identity",
        "creatorUnit":"Draft Organization",
        "creatorUnitLevelName":"Draft Organization Level",
        "application":"application ID",
        "applicationName":"application name",
        "applicationAlias":"application alias",
        "process":"Process ID",
        "processName":"process name",
        "processAlias":"process alias",
        "serial":"Number",
        "activityType":"Activity Type",
        "activityName":"activity name",
        "activityArrivedTime":"Activity ArrivedTime",
        "workId":"work ID",
        "workCompletedId":"Completed work ID",
        "job":"JOB's ID(job)",
        "completed":"Is it completed (completed)",

        "publishTime":"Publish Time",
        "creatorUnitName":"Drafting Organization",
        "creatorTopUnitName":"Draft Top Unit",
        "appId":"Column ID",
        "appName":"Column Name",
        "categoryId":"category ID",
        "categoryName":"Category Name",
        "categoryAlias":"Category Alias",
        "documentId":"Document ID",

        "dataPath":"Data Path",
        "order":"Order",
        "none":"None",
        "asc":"ascending order",
        "desc":"Descending Order",
        "orderToNumber":"Convert to numeric sort",
        "category":"category",
        "hidden":"Hidden",
        "org":"Organization Object",
        "htmlValue":"HTML Value",
        "showScript":"Show Script",
        "titleStyles":"Title Cell Styles",
        "titleProperties": "Title Cell Properties",
        "contentStyles":"Content cell styles",
        "contentProperties":"Content cell properties",

        "buttonStyles":"Button Styles",
        "round":"rounded corners",
        "rect":"square angle",
        "showNumberPaging":"Show NumberPaging",
        "numberShowCount":"Number of Digital Shows",
        "showBeforeAfter":"Show Before and After",
        "page":"页:",
        "hasFirstLastPage":"Display the last page of the first page",
        "hasPreNextPage":"Display the previous page and the next page",
        "hasPageJumper":"Show Jumping Page",
        "firstPageText":"First Page Text",
        "lastPageText":"Last Page Text",
        "prevPageText":"PrevPage Text",
        "nextPageText":"Next Page Text",

        "hideView":"Hidden",
        "viewStyles":"View Styles",
        "expandView":"Expand Category",
        "showSequence":"Show Sequence Number",
        "maxRow":"Maximum number of rows",
        "pageSize":"Number of rows per page",
        "pageMaxCountNotice":"Note: The maximum number of lines per page is 2000",
        "actionbarHidden":"Hide actionbar",
        "radio": "Single Selection",
        "checkbox": "Multiple Selection",
        "selectBoxShow":"When to show select Box",
        "always":"Always",
        "mouseover":"Mouse over",
        "allowSelectAll":"Allow select all",
        "firstTdHidden":"No category and selection to hide the first column",
        "noDataText": "No data to display",
        "cacheAccess":"Enable cache",
        "cacheAccessNotice":"Note: Enabling the cache will invalidate the permissions in the scope!",
        "executable": "executable",
        "availableIdentityList":"Executive Identity",
        "availableUnitList":"Executive Organization",
        "defaultSelectedScript":"default selected line script",
        "selectedAbleScript":"Allow select row script",
        "range":"Range",
        "timeRange":"Time Period",
        "timeRangeNotice":"Note: It is recommended to set the time range to improve efficiency!",
        "rangeType":"Period Type",
        "all":"All",
        "year":"year",
        "season":"Quarter",
        "monthly":"Month",
        "week":"week",
        "date":"date",
        "beginDate":"Start Date",
        "endDate":"End Date",
        "currentYear":"Current Year",
        "currentSeason":"Current Season",
        "firstSeason":"First Season",
        "secondSeason":"Second Season",
        "thirdSeason":"third season",
        "fourthSeason":"Fourth Season",
        "currentMonth":"Current Month",
        "month":"月",
        "monthNumber":"",
        "currentWeek":"Current Week",
        "weekNumber": "(i)",
        "dateNumber": "(i)",
        "today":"Today",
        "adjust":"Offset",
        "processPlatform":"ProcessPlatform Data",
        "cmsPlatform":"CMS Data",
        "authority":"Authority",
        "check":"with permission",
        "ignore":"ignore",
        "processStatus":"Circulation Status",
        "work":"Circulation in",
        "workCompleted":"Completed",
        "selectApplicationNotice": "Take the union of application and process",
        "selectApplication":"Select Application",
        "selectProcess":"Select Process",
        "dataType":"Data Type",
        "dataTypeValue": ["Information Type","Data Type"],
        "showDraft":"Show Draft",
        "selectColumnNotice":"Take the union of column and category",
        "selectColumn":"Select Column",
        "selectCategory":"Select Category",
        "selectOrgNotice": "Take the union of organization, personnel, and identity",
        "selectUnit":"Draft Organization",
        "selectPerson":"Drafter",
        "selectIdentity":"Draft Identity",

        "filter":"Filter",
        "path":"Path",

        "textValue":"Text",
        "numberValue":"Number",
        "dateTimeValue":"DateTime",
        "dateValue":"Date",
        "timeValue":"Time",
        "booleanValue":"Boolean",

        "equals":"equals",
        "notEquals":"Not Equals",
        "greaterThan":"Greater Than",
        "greaterThanOrEqualTo":"Greater than or equal to",
        "lessThan":"less than",
        "lessThanOrEqualTo":"less than or equal to",
        "like":"match",
        "notLike":"Does not match",
        "inRange":"Range",
        "in":"Contains",


        "filterRestrict":"As the default filter condition",
        "customFilterRestrict": "As a custom filter Condition",
        "logic":"Logic",
        "or":"Or",
        "and":"and",
        "comparison":"Compare",
        "value":"value",
        "multiValueNotice":"Multi-values are separated by commas (,)",
        "now":"Current Time",
        "currentPerson":"currentPerson",
        "currentIdentity":"Current Identity",
        "currentPersonDirectUnit":"The current person's direct organization",
        "currentPersonAllUnit":"All organizations where the current person belongs",
        "to":"to",
        "input":"input",
        "selectable":"Optional",
        "selectOptionScriptNotice":"return [\"option text|option value\"]",
        "selectOptionScript":"Option Script",
        "defaultFilterCondition":"Default Filter Condition",
        "customFilterCondition":"Custom filter Condition"
    },
    "viewStyle":{
        "default": "Default",
        "redSimple":"Red Simple",
        "blueSimple":"Blue Simple",
        "official":"Official",
        "deepBlue":"Deep Blue",
        "blueFlat":"Blue and white flat"
    }
};