MWF.xApplication.query.ViewDesigner.LP = {
    "title": "ビュー編集",
    "newView": "新規ビュー",
    "property": "プロパティ",
    "item": "アイテム",
    "type": "タイプ",
    "value": "値",
    "view": "ビュー",
    "unnamed": "無題の列",
    "unCategory": "未分類",
    "id": "ID",
    "name": "名前",
    "alias": "別名",
    "description": "説明",
    "saveViewNotice": "ビューを先に保存してください。",
    "application": "データアプリ",
    "newView": "新しいビュー",
    "newViewName": "新しいビュー名",
    "copy": "コピー",
    "ok": "確認",
    "cancel": "キャンセル",
    "action": {
        "move": "移動",
        "delete": "削除",
        "add": "追加"
    },

    "notice": {
        "save_success": "ビューが正常に保存されました！",
        "saveAs_success": "ビューが正常に別名保存されました。ビュー設定で新しいビューを開くことができます！",

        "deleteFilterTitle": "フィルタ条件の削除確認",
        "deleteFilter": "フィルタ条件を削除しますか？",

        "deleteColumnTitle": "列の削除確認",
        "deleteColumn": "現在の列を削除しますか？",

        "changeTypeTitle": "データ型の変更確認",
        "changeTypeDeleteChildren": "データ型を変更すると、すべての子データが削除されます。実行しますか？",
        "changeType": "データ型の変更はデータの値を変更します。実行しますか？",

        "inputTypeError": "入力したデータ型が無効です。もう一度入力してください。",
        "sameKey": "入力した項目名は既存のオブジェクトにすでに存在します。別の名前を入力してください。",
        "emptyKey": "項目名は空白にできません。別の名前を入力してください。",
        "numberKey": "項目名に数字を使用することはできません。別の名前を入力してください。",

        "inputName": "ビュー名を入力してください。",
        "noModifyName": "名前または別名を変更できません。",

        "deleteEventTitle": "イベントの削除確認",
        "deleteEvent": "現在のイベントを削除しますか？",

        "selectProcess": "アプリケーションまたはプロセスを選択してください。",
        "selectCMS": "コンテンツ管理カテゴリまたは分類を選択してください。",
        "selectDateRange": "期間タイプが範囲の場合、開始日と終了日を選択してください。"
    },
    "actionbar": {
        "readhide": "表示時の読み取り設定",
        "edithide": "表示時の編集設定",
        "hideCondition": "非表示条件の設定",
        "title": "タイトル",
        "img": "アイコン",
        "action": "アクション",
        "condition": "表示条件",
        "editScript": "アクションスクリプトの編集",
        "editCondition": "非表示条件の編集（true を返すと非表示）",
        "up": "上に移動",
        "property": "プロパティ",
        "addCustomTool": "カスタムアクションの追加",
        "delete": "削除",
        "setProperties": "アクションのプロパティ設定",
        "restoreDefaultTool": "削除したシステムアクションの復元",
        "selectDefaultTool": "システムアクションの選択"
    },
    "actionBar": {
        "exportExcel": "Excel へエクスポート"
    },
    "mastInputPath": "データのパスを入力してください",
    "mastInputTitle": "タイトルを入力してください",
    "filter": {
        "and": "かつ",
        "or": "または",
        "equals": "等しい",
        "notEquals": "等しくない",
        "greaterThan": "より大きい",
        "greaterThanOrEqualTo": "以上",
        "lessThan": "未満",
        "lessThanOrEqualTo": "以下",
        "like": "一致",
        "notLike": "不一致",
        "range": "範囲",
        "logic" : "論理",
        "path" : "パス",
        "compare" : "比較",
        "value" : "値",
        "columnValue" : "列の値",
        "contain" : "含む",
        "from" : "から",
        "in": "含む"
    },
    "delete_filterItem_title": "フィルタ条件の削除の確認",
    "delete_filterItem": "現在のフィルタ条件を削除してもよろしいですか？",
    "propertyTemplate": {
        "base": "基本",
		"event": "イベント",
		"html": "HTML",
		"json": "JSON",
		"action": "アクション",
		"select": "選択",
		"alias": "別名",
		"id": "識別子",
		"name": "名前",
		"description": "説明",
		"appearance": "外観タイプ",
		"style": "スタイル",
		"attribute": "属性",
		"systemAction": "システムアクション",
		"show": "表示",
		"hide": "非表示",
		"columnTitle": "列のタイトル",
		"columnName":"列名",
		"defaultValue":"デフォルト値",
		"openDocument":"ドキュメントを開く",
		"yes":"はい",
		"no":"いいえ",
		"openDocumentScript":"ドキュメントスクリプトを開く",
		"data":"データ",
		"selectData":"データを選択",
		"selectTitle":"(選択してください)",
		"title":"タイトル",
		"startTime":"作成時間",
		"startTimeMonth":"作成月",
		"completedTime":"完了時間",
		"completedTimeMonth":"完了月",

        "creatorPerson": "起案者",
		"creatorIdentity": "起案者身分",
		"creatorUnit": "起案組織",
		"creatorUnitLevelName": "起案組織階層名",
		"application": "アプリケーションID",
		"applicationName": "アプリケーション名",
		"applicationAlias": "アプリケーション別名",
		"process": "プロセスID",
		"processName": "プロセス名",
		"processAlias": "プロセス別名",
		"serial": "シリアル",
		"activityType": "アクティビティタイプ",
		"activityName": "アクティビティ名",
		"activityArrivedTime": "アクティビティ到達時間",
		"workId": "ワークID",
		"workCompletedId": "完了ワークID",
		"job": "JOBのID",
		"completed": "完了済み",
		"publishTime": "公開時間",
		"creatorUnitName": "起案組織",
		"creatorTopUnitName": "起案トップ組織",
		"appId": "コラムID",
		"appName": "コラム名",
		"categoryId": "分類ID",
		"categoryName": "分類名",
		"categoryAlias": "分類別名",
		"documentId": "ドキュメントID",

        "dataPath": "データパス",
		"order": "並べ替え",
		"none": "なし",
		"asc": "昇順",
		"desc": "降順",
		"orderToNumber": "数値に変換して並べ替え",
		"category": "カテゴリ",
		"hidden": "非表示",
		"org": "組織オブジェクト",
		"htmlValue": "HTML値",
		"showScript": "スクリプト表示",
		"titleStyles": "タイトルセルスタイル",
		"titleProperties": "タイトルセルプロパティ",
		"contentStyles": "コンテンツセルスタイル",
		"contentProperties": "コンテンツセルプロパティ",
		"buttonStyles": "ボタンスタイル",
		"round": "ラウンド",
		"rect": "四角形",
		"showNumberPaging": "数字ページ表示",
		"numberShowCount": "数字表示数",
		"showBeforeAfter": "前後表示",
		"page": "ページ:",
		"hasFirstLastPage": "最初のページと最後のページ表示",
		"hasPreNextPage": "前のページと次のページ表示",
		"hasPageJumper": "ページ切り替え表示",
		"firstPageText": "最初のページテキスト",
		"lastPageText": "最後のページテキスト",
		"prevPageText": "前のページテキスト",
		"nextPageText": "次のページテキスト",

        "desciption": "ページ情報",
		"position": "位置",
		"top": "前方",
		"bottom": "後方",
		"format": "フォーマット",
		"hideView": "ビュー非表示",
		"orderNumber": "順序番号",
		"viewStyles": "ビュースタイル",
		"expandView": "カテゴリ展開",
		"showSequence": "シーケンス表示",
		"maxRow": "最大行数",
		"pageSize": "ページごとの行数",
		"pageMaxCountNotice": "注：ページごとの最大行数は2000行です",
		"actionbarHidden": "アクションバー非表示",
		"pagingbarHidden": "ページングバー非表示",
		"searchbarHidden": "検索バー非表示",
		"radio": "ラジオ",
		"checkbox": "チェックボックス",
		"selectBoxShow": "選択ボックス表示",
		"always": "常に表示",
		"mouseover": "マウスオーバー時",
		"allowSelectAll": "全選択を許可",
		"firstTdHidden": "カテゴリおよび選択なしで最初の列を非表示",
		"noDataText": "データなし表示",
		"cacheAccess": "キャッシュアクセス有効化",
        "cacheAccessNotice": "注意: キャッシュを有効にすると、範囲内のアクセス権が無効になります。",
		"executable": "実行可能",
		"availableIdentityList": "利用可能な実行者",
		"availableUnitList": "利用可能な組織",
		"defaultSelectedScript": "デフォルトの選択行スクリプト",
		"selectedAbleScript": "選択可能な行スクリプト",
		"range": "範囲",
		"timeRange": "時間範囲",
		"timeRangeNotice": "注意: 時間範囲を設定することは効率向上に役立ちます。",
		"rangeType": "範囲の種類",

        "all": "すべて",
		"year": "年",
		"season": "四半期",
		"monthly": "月",
		"week": "週",
		"date": "日",
		"beginDate": "開始日",
		"endDate": "終了日",
		"currentYear": "現在の年度",
		"currentSeason": "現在の四半期",
		"firstSeason": "第1四半期",
		"secondSeason": "第2四半期",
		"thirdSeason": "第3四半期",
		"fourthSeason": "第4四半期",
		"currentMonth": "現在の月",
		"month": "月",
		"monthNumber": "(i)月",
		"currentWeek": "現在の週",
		"weekNumber": "(i)週",
		"dateNumber": "(i)日",
		"today": "今日",
		"adjust": "調整",
		"processPlatform": "プロセスプラットフォームデータ",
		"cmsPlatform": "コンテンツ管理データ",
		"authority": "権限",
		"check": "権限付き",
		"ignore": "無視",
		"processStatus": "プロセス状態",
		"work": "進行中",
		"workCompleted": "完了済み",
		"selectApplicationNotice": "アプリケーションとプロセスの和集合を選択",
		"selectApplication": "アプリケーションを選択",
		"selectProcess": "プロセスを選択",
		"dataType": "データタイプ",
		"dataTypeValue": ["情報型", "データ型"],
		"showDraft": "下書きを表示",
		"selectColumnNotice": "カラムとカテゴリの和集合を選択",
		"selectColumn": "カラムを選択",
		"selectCategory": "カテゴリを選択",
		"selectOrgNotice": "組織、個人、およびアイデンティティの和集合を選択",
		"selectUnit": "起案組織を選択",
		"selectPerson": "起案者を選択",
		"selectIdentity": "起案者のアイデンティティを選択",

        "filter": "フィルター",
		"path": "パス",
		"textValue": "テキスト",
		"numberValue": "数値",
		"dateTimeValue": "日時",
		"dateValue": "日付",
		"timeValue": "時間",
		"booleanValue": "ブール",
		"equals": "等しい",
		"notEquals": "等しくない",
		"greaterThan": "より大きい",
		"greaterThanOrEqualTo": "以上",
		"lessThan": "未満",
		"lessThanOrEqualTo": "以下",
		"like": "一致",
		"notLike": "一致しない",
		"inRange": "範囲内",
		"in": "含む",
		"script": "スクリプト",


        "filterRestrict": "デフォルトフィルタ条件として使用",
		"customFilterRestrict": "カスタムフィルタデータとして使用",
		"logic": "論理",
		"or": "または",
		"and": "かつ",
		"comparison": "比較",
		"value": "値",
		"multiValueNotice": "複数の値は半角カンマ(,)で区切る",
		"now": "現在の時刻",
		"currentPerson": "現在のユーザー",
		"currentIdentity": "現在のアイデンティティ",
		"currentPersonDirectUnit": "現在のユーザーの直属組織",
		"currentPersonAllUnit": "現在のユーザーの所属するすべての組織",
		"currentPersonGroupList": "現在のユーザーの所属するグループリスト",
		"currentPersonRoleList": "現在のユーザーが所有するロールリスト",
		"to": "から",
		"input": "入力",
		"selectable": "選択可能",
		"selectOptionScriptNotice": "return [\"オプションテキスト|オプション値\"]",
		"selectOptionScript": "オプションスクリプト",
		"defaultFilterCondition": "デフォルトフィルタ条件",
		"customFilterCondition": "カスタムフィルタデータ",
		"byScript": "スクリプトによる",
		"language": "言語パッケージ",
		"languageInfo": "言語情報を含むJSONオブジェクトを返し、o2.languageを使用して現在の言語情報を取得します。"
    },
    "viewStyle": {
        "default": "デフォルトスタイル",
        "redSimple": "赤いシンプルスタイル",
        "blueSimple": "青いシンプルスタイル",
        "official": "公文スタイル",
        "deepBlue": "グループスタイル",
        "blueFlat": "青白いフラットスタイル",
        "greenFlat": "緑のフラットスタイル"
    }
};