MWF.xApplication.query.ViewDesigner.LP = {
    "title": "뷰 편집",
    "newView": "새로운 뷰",
    "property": "속성",
    "item": "항목",
    "type": "유형",
    "value": "값",
    "view": "뷰",
    "unnamed": "제목 없음",
    "unCategory": "미분류",
    "id": "식별자",
    "name": "이름",
    "alias": "별칭",
    "description": "설명",
    "saveViewNotice": "뷰를 먼저 저장해 주세요.",
    "application": "데이터 앱",
    "newView": "새로운 뷰",
    "newViewName": "새로운 뷰 이름",
    "copy": "복사",
    "ok": "확인",
    "cancel": "취소",
    "action": {
        "move": "이동",
        "delete": "삭제",
        "add": "추가"
    },

    "notice": {
        "save_success": "뷰가 성공적으로 저장되었습니다!",
        "saveAs_success": "뷰를 성공적으로 다른 이름으로 저장하였습니다. 뷰 설정에서 새 뷰를 열 수 있습니다.",
        "deleteFilterTitle": "필터 조건 삭제 확인",
        "deleteFilter": "필터 조건을 삭제하시겠습니까?",
        "deleteColumnTitle": "열 삭제 확인",
        "deleteColumn": "현재 열을 삭제하시겠습니까?",
        "changeTypeTitle": "데이터 유형 변경 확인",
        "changeTypeDeleteChildren": "데이터 유형을 변경하면 모든 하위 데이터가 삭제됩니다. 계속하시겠습니까?",
        "changeType": "데이터 유형을 변경하면 데이터 값이 변경됩니다. 계속하시겠습니까?",
        "inputTypeError": "입력한 데이터 유형이 잘못되었습니다. 다시 입력해주세요.",
        "sameKey": "입력한 항목 이름은 이미 해당 객체에 존재합니다. 다시 입력해주세요.",
        "emptyKey": "항목 이름은 비워둘 수 없습니다. 다시 입력해주세요.",
        "numberKey": "항목 이름은 숫자일 수 없습니다. 다시 입력해주세요.",
        "inputName": "뷰 이름을 입력해주세요.",
        "noModifyName": "이름 또는 별칭을 수정할 수 없습니다.",
        "deleteEventTitle": "이벤트 삭제 확인",
        "deleteEvent": "현재 이벤트를 삭제하시겠습니까?",
        "selectProcess": "앱 또는 프로세스를 선택해주세요.",
        "selectCMS": "콘텐츠 관리 항목 또는 분류를 선택해주세요.",
        "selectDateRange": "시간 범위 유형은 시작 날짜와 종료 날짜를 선택해야 합니다."
    },
    "actionbar": {
        "readhide": "읽을 때 표시 여부 설정",
        "edithide": "편집할 때 표시 여부 설정",
        "hideCondition": "숨김 조건 설정",
        "title": "제목",
        "img": "아이콘",
        "action": "동작",
        "condition": "표시 조건",
        "editScript": "동작 스크립트 편집",
        "editCondition": "숨김 조건 편집 (true 반환하면 동작 숨김)",
        "up": "위로 이동",
        "property": "속성",
        "addCustomTool": "사용자 지정 동작 추가",
        "delete": "삭제",
        "setProperties": "동작 속성 설정",
        "restoreDefaultTool": "삭제된 시스템 동작 복원",
        "selectDefaultTool": "시스템 동작 선택"
    },
    "actionBar": {
        "exportExcel": "Excel로 내보내기"
    },
    "mastInputPath": "데이터 경로를 입력하세요",
    "mastInputTitle": "제목을 입력하세요",
    "filter": {
        "and": "그리고",
        "or": "또는",
        "equals": "동일",
        "notEquals": "동일하지 않음",
        "greaterThan": "초과",
        "greaterThanOrEqualTo": "이상",
        "lessThan": "미만",
        "lessThanOrEqualTo": "이하",
        "like": "일치",
        "notLike": "불일치",
        "range": "범위",
        "logic" : "논리",
        "path" : "경로",
        "compare" : "비교",
        "value" : "값",
        "columnValue" : "열값",
        "contain" : "포함",
        "from" : "부터",
        "in": "포함"
    },
    "delete_filterItem_title": "필터 조건 삭제 확인",
    "delete_filterItem": "현재 필터 조건을 삭제하시겠습니까?",
    "propertyTemplate": {
        "base": "기본",
		"event": "이벤트",
		"html": "HTML",
		"json": "JSON",
		"action": "동작",
		"select": "선택",
		"alias": "별명",
		"id": "식별자",
		"name": "이름",
		"description": "설명",
		"appearance": "외관 유형",
		"style": "스타일",
		"attribute": "속성",
		"systemAction": "시스템 동작",
		"show": "표시",
		"hide": "숨김",
		"columnTitle": "열 제목",
		"columnName":"열 이름",
		"defaultValue":"기본값",
		"openDocument":"문서 열기",
		"yes":"예",
		"no":"아니오",
		"openDocumentScript":"문서 열기 스크립트",
		"data":"데이터",
		"selectData":"데이터 선택",
		"selectTitle":"(선택)",
		"title":"제목",
		"startTime":"생성 시간",
		"startTimeMonth":"생성 월",
		"completedTime":"완료 시간",
		"completedTimeMonth":"완료 월",

        "creatorPerson": "기안자",
		"creatorIdentity": "기안자 신분",
		"creatorUnit": "기안 조직",
		"creatorUnitLevelName": "기안 조직 레벨 이름",
		"application": "애플리케이션 ID",
		"applicationName": "애플리케이션 이름",
		"applicationAlias": "애플리케이션 별명",
		"process": "프로세스 ID",
		"processName": "프로세스 이름",
		"processAlias": "프로세스 별명",
		"serial": "일련 번호",
		"activityType": "활동 유형",
		"activityName": "활동 이름",
		"activityArrivedTime": "활동 도착 시간",
		"workId": "작업 ID",
		"workCompletedId": "완료된 작업 ID",
		"job": "JOB ID",
		"completed": "완료 여부",
		"publishTime": "발행 시간",
		"creatorUnitName": "기안 조직",
		"creatorTopUnitName": "최상위 기안 조직",
		"appId": "컬럼 ID",
		"appName": "컬럼 이름",
		"categoryId": "분류 ID",
		"categoryName": "분류 이름",
		"categoryAlias": "분류 별명",
		"documentId": "문서 ID",

        "dataPath": "데이터 경로",
		"order": "정렬",
		"none": "없음",
		"asc": "오름차순",
		"desc": "내림차순",
		"orderToNumber": "숫자 정렬으로 변환",
		"category": "분류",
		"hidden": "숨김",
		"org": "조직 객체",
		"htmlValue": "HTML 값",
		"showScript": "스크립트 표시",
		"titleStyles": "제목 셀 스타일",
		"titleProperties": "제목 셀 속성",
		"contentStyles": "내용 셀 스타일",
		"contentProperties": "내용 셀 속성",
		"buttonStyles": "버튼 스타일",
		"round": "둥근",
		"rect": "직사각형",
		"showNumberPaging": "숫자 페이지 표시",
		"numberShowCount": "숫자 표시 개수",
		"showBeforeAfter": "이전 및 이후 표시",
		"page": "페이지:",
		"hasFirstLastPage": "첫 페이지 및 끝 페이지 표시",
		"hasPreNextPage": "이전 페이지 및 다음 페이지 표시",
		"hasPageJumper": "페이지 전환 표시",
		"firstPageText": "첫 페이지 텍스트",
		"lastPageText": "마지막 페이지 텍스트",
		"prevPageText": "이전 페이지 텍스트",
		"nextPageText": "다음 페이지 텍스트",

        "desciption": "페이징 정보",
		"position": "위치",
		"top": "위",
		"bottom": "아래",
		"format": "형식",
		"hideView": "뷰 숨기기",
		"orderNumber": "정렬 번호",
		"viewStyles": "뷰 스타일",
		"expandView": "분류 펼치기",
		"showSequence": "일련 번호 표시",
		"maxRow": "최대 행 수",
		"pageSize": "페이지 당 행 수",
		"pageMaxCountNotice": "참고: 페이지 당 최대 행 수는 2000개입니다",
		"actionbarHidden": "액션바 숨기기",
		"pagingbarHidden": "페이징바 숨기기",
		"searchbarHidden": "검색바 숨기기",
		"radio": "라디오",
		"checkbox": "체크박스",
		"selectBoxShow": "선택 상자 표시",
		"always": "항상 표시",
		"mouseover": "마우스 오버 시",
		"allowSelectAll": "모두 선택 허용",
		"firstTdHidden": "분류 및 선택 없이 첫 번째 열 숨김",
		"noDataText": "데이터 없음 표시",
		"cacheAccess": "캐시 액세스 활성화",
		"cacheAccessNotice": "참고: 캐시 액세스를 활성화하면 범위 내의 권한이 무효화됩니다!",
		"executable": "실행 가능자",
		"availableIdentityList": "실행 가능한 사람",
		"availableUnitList": "실행 조직",
		"defaultSelectedScript": "기본 선택된 행 스크립트",
		"selectedAbleScript": "선택 가능한 행 스크립트",
		"range": "범위",
		"timeRange": "시간 범위",
		"timeRangeNotice": "참고: 시간 범위를 설정하는 것이 효율성을 높이는 데 도움이 됩니다!",
		"rangeType": "시간 범위 유형",

        "all": "모두",
		"year": "연도",
		"season": "분기",
		"monthly": "월",
		"week": "주",
		"date": "일",
		"beginDate": "시작 날짜",
		"endDate": "종료 날짜",
		"currentYear": "현재 연도",
		"currentSeason": "현재 분기",
		"firstSeason": "제 1 분기",
		"secondSeason": "제 2 분기",
		"thirdSeason": "제 3 분기",
		"fourthSeason": "제 4 분기",
		"currentMonth": "현재 월",
		"month": "월",
		"monthNumber": "(i)월",
		"currentWeek": "현재 주",
		"weekNumber": "(i)주",
		"dateNumber": "(i)일",
		"today": "오늘",
		"adjust": "이동",
		"processPlatform": "프로세스 플랫폼 데이터",
		"cmsPlatform": "콘텐츠 관리 데이터",
		"authority": "권한",
		"check": "권한 사용",
		"ignore": "무시",
		"processStatus": "진행 상태",
		"work": "진행 중",
		"workCompleted": "완료됨",
		"selectApplicationNotice": "애플리케이션 및 프로세스의 합집합 가져오기",
		"selectApplication": "애플리케이션 선택",
		"selectProcess": "프로세스 선택",
		"dataType": "데이터 유형",
		"dataTypeValue": ["정보 유형", "데이터 유형"],
		"showDraft": "임시 저장 반환",
		"selectColumnNotice": "열 및 카테고리의 합집합 가져오기",
		"selectColumn": "열 선택",
		"selectCategory": "카테고리 선택",
		"selectOrgNotice": "조직, 개인 및 신분의 합집합 가져오기",
		"selectUnit": "기안 조직 선택",
		"selectPerson": "기안자 선택",
		"selectIdentity": "기안 신분 선택",

        "filter": "필터",
		"path": "경로",
		"textValue": "텍스트",
		"numberValue": "숫자",
		"dateTimeValue": "날짜 및 시간",
		"dateValue": "날짜",
		"timeValue": "시간",
		"booleanValue": "불리언",
		"equals": "같음",
		"notEquals": "같지 않음",
		"greaterThan": "크다",
		"greaterThanOrEqualTo": "크거나 같음",
		"lessThan": "작다",
		"lessThanOrEqualTo": "작거나 같음",
		"like": "일치",
		"notLike": "일치하지 않음",
		"inRange": "범위 내",
		"in": "포함",
		"script": "스크립트",


        "filterRestrict": "기본 필터로 사용",
		"customFilterRestrict": "사용자 정의 필터 데이터로 사용",
		"logic": "논리",
		"or": "또는",
		"and": "그리고",
		"comparison": "비교",
		"value": "값",
		"multiValueNotice": "여러 값은 반각 쉼표(,)로 구분",
		"now": "현재 시간",
		"currentPerson": "현재 사용자",
		"currentIdentity": "현재 신분",
		"currentPersonDirectUnit": "현재 사용자 직속 조직",
		"currentPersonAllUnit": "현재 사용자 소속 모든 조직",
		"currentPersonGroupList": "현재 사용자 그룹 목록",
		"currentPersonRoleList": "현재 사용자 역할 목록",
		"to": "에서",
		"input": "입력",
		"selectable": "선택 가능",
		"selectOptionScriptNotice": "return [\"옵션 텍스트|옵션 값\"]",
		"selectOptionScript": "옵션 스크립트",
		"defaultFilterCondition": "기본 필터 조건",
		"customFilterCondition": "사용자 정의 필터 데이터",
		"byScript": "스크립트에 의해",
		"language": "언어 팩",
		"languageInfo": "언어 정보를 포함하는 JSON 객체를 반환하며, o2.language를 사용하여 현재 언어 정보를 가져옵니다."
    },
    "viewStyle": {
        "default": "기본 스타일",
        "redSimple": "빨간색 간결한 스타일",
        "blueSimple": "파란색 간결한 스타일",
        "official": "공문 스타일",
        "deepBlue": "그룹 스타일",
        "blueFlat": "파란색 및 흰색 평면 스타일",
        "greenFlat": "녹색 평면 스타일"
    }
};