MWF.xApplication.query.ViewDesigner.LP = {
    "title": "ແກ້ໄຂ View",
    "newView": "View ໃໝ່",
    "property": "ຄຸນສົມບັດ",
    "item": "Item",
    "type": "ປະເພດ",
    "value": "ຄ່າ",
    "view": "View",
    "unnamed": "ບໍ່ມີຖັນ",
    "unCategory": "ບໍ່ມີໝວດໝູ່",

    "id": "Id",
    "name": "ຊື່",
    "alias": "ນາມແຝງ",
    "description": "ອະທິບາຍ",
    "saveViewNotice": "ກະລຸນາບັນທຶກ view ກ່ອນ！",

    "application": "Data Application",
    "newView": "View ໃໝ່",
    "newViewName": "ຊື່ View ໃໝ່",
    "copy": "ສຳເນົາ",
    "ok": "ຢືນຢັນ",
    "cancel": "ຍົກເລີກ",

    "action": {
        "move": "ຍ້າຍ",
        "delete": "ລົບ",
        "add": "ເພີ່ມ"
    },

    "notice": {
        "save_success": "ບັນທຶກ View ສຳເລັດ",
        "saveAs_success": "ບັນທຶກ View ສຳເລັດ，ເຈົ້າສາມາດເປີດ View ໃໝ່ ໃນ Viewທີ່ກຳລັງຕິດຄ່າຢູ່！",

        "deleteFilterTitle": "ຢືນຢັນລົບການຂັດກອງເອກະສານ",
        "deleteFilter": "ແນ່ໃຈຫຼືບໍ່ຢືນຢັນລົບການຂັດກອງເອກະສານ？",

        "deleteColumnTitle": "ຢືນຢັນລົບຖັນ",
        "deleteColumn": "ແນ່ໃຈຢືນຢັນລົບຖັນຫຼືບໍ່？",


        "changeTypeTitle": "ຢືນຢັນປ່ຽນປະເພດຂໍ້ມູນ",
        "changeTypeDeleteChildren": "ເມື່ອປ່ຽນປະເພດຂໍ້ມູນຈະລົບຂໍ້ມູນຍ່ອຍທັງໝົດ，ເຈົ້າແນ່ໃຈບໍ່ວ່າຈະດຳເນີນການນີ້？",
        "changeType": "ເມື່ອເຈົ້າປ່ຽນປະເພດຂໍ້ມູນຈະປ່ຽນຄ່າຂອງຂໍ້ມູນ，ເຈົ້າແນ່ໃຈບໍ່ວ່າຈະດຳເນີນການນີ້？",

        "inputTypeError": "ເຈົ້າປ້ອນປະເພດຂໍ້ມູນພິດພາດ，ກະລຸນາປ້ອນຂໍ້ມູນໃສ່ໃໝ່",
        "sameKey": "ຊື່ itemທີ່ເຈົ້າປ້ອນໃສ່ມີຢູ່ແລ້ວ ，ກະລຸນາປ້ອນຂໍ້ມູນໃສ່ໃໝ່",
        "emptyKey": "ຊື່ item ບໍ່ສາມາດວ່າງໄດ້，ກະລຸນາປ້ອນຂໍ້ມູນໃສ່ໃໝ່",
        "numberKey": "ຊື່ item ບໍ່ສາມາດເປັນຕົວເລກໄດ້，ກະລຸນາປ້ອນຂໍ້ມູນໃສ່ໃໝ່",

        "inputName": "ກະລຸນາປ້ອນຊື່ item ",
        "noModifyName": "ບໍ່ສາມາດປ່ຽນຊື່ ຫຼື ປ່ຽນນາມແຝງໄດ້",

        "deleteEventTitle": "ຢືນຢົັນລົບເຫດການ",
        "deleteEvent": "ແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບເຫດການນີ້？",

        "selectProcess": "ກະລຸນາເລືອກapplication ຫຼື ຂະບວນການ ",
        "selectCMS": "ກະລຸນາເລືອກຖັນບໍລິຫານເນື້ອໃນ ຫຼື ໝວດໝູ່",
        "selectDateRange": "ປະເພດໄລຍະເປັນຊ່ວງ，ກະລຸນາເລືອກເວລາເລີ່ມຕົ້ນແລະເວລາສິ້ນສຸດ"
    },
    "actionbar": {
        "readhide": "ຕັ້ງຄ່າສະແດງເມື່ອກຳລັງອ່ານ",
        "edithide": "ຕັ້ງຄ່າສະແດງເມື່ອກຳລັງຕັ້ງຄ່າ",
        "hideCondition": "ຕັ້ງຄ່າເຊື່ອງເອກະສານ",
        "title": "ຫົວຂໍ້",
        "img": "Icon",
        "action": "ດຳເນີນການ",
        "condition": "ສະແດງເອກະສານ",
        "editScript": "ຕັ້ງຄ່າການດຳເນີນລາຍງານ",
        "editCondition": "ຕັ້ງຄ່າເຊື່ອງເອກະສານ（ກັບໄປ true ດຳເນີນການເຊື່ອງ）",
        "up": "ຍ້າຍຂຶ້ນ",
        "property": "ຄຸນສົມບັດ",
        "addCustomTool": "ເພີ່ມການກະທຳທີ່ກຳນົດເອງ",
        "delete": "ລົບ",
        "setProperties": "ຕັ້ງຄ່າການດຳເນີນຄຸນສົມບັດ",
        "restoreDefaultTool": "ກູ້ຄືນການດຳເນີນການລະບົບທີ່ຖືກລົບ",
        "selectDefaultTool": "ເລືອກຂະບວນການດຳເນີນງານ"
    },
    "actionBar": {
        "exportExcel": "ນຳອອກ Excel"
    },
    "mastInputPath": "ກະລຸນາຕື່ມໃສ່data path ",
    "mastInputTitle": "ກະລຸນາປ້ອນໃສ່ຫົວຂໍ້",
    "filter": {
        "and": "ແລະ",
        "or": "ຫຼື",
        "equals": "ເທົ່າ",
        "notEquals": "ບໍ່ເທົ່າ",
        "greaterThan": "ໃຫ່ຍກວ່າ",
        "greaterThanOrEqualTo": "ໃຫ່ຍກວ່າເທົ່າກັບ",
        "lessThan": "ນ້ອຍກວ່າ",
        "lessThanOrEqualTo": "ນ້ອຍກວ່າເທົ່າກັບ",
        "like": "ຈັບຄູ່",
        "notLike": "ບໍ່ຈັບຄູ່",
        "range": "ຊ່ວງ",
        "logic": "Logic",
        "path": "Path",
        "compare": "ປຽບທຽບ",
        "value": "ຄ່າ",
        "columnValue": "ຄ່າຖັນ",
        "contain": "ລວມ",
        "from": "ຈາກ",
        "in": "ລວມ",
        "script": "ລາຍງານ",
        "input": "ປ້ອນຂໍ້ມູນເຂົ້າ"
    },
    "delete_filterItem_title": "ຢືນຢັນລົບຂັດກອງເອກະສານ",
    "delete_filterItem": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບຕົວຂັດກອງເອກະສານ？",
    "propertyTemplate": {
        "base": "ພື້ນຖານ",
        "event": "ເຫດການ",
        "html": "HTML",
        "json": "JSON",
        "action": "ດຳເນີນ",
        "select": "ເລືອກ",
        "alias": "ນາມແຝງ",

        "id": "Id",
        "name": "ຊື່",
        "description": "ອະທິບາຍ",
        "appearance": "ປະເພດຮູບຮ່າງ",
        "style": "ຮູບແບບ",
        "attribute": "ຄຸນສົມບັດ",
        "systemAction": "ດຳເນີນຂະບວນການ",

        "show": "ສະແດງ",
        "hide": "ເຊື່ອງ",
        "columnTitle": "ຫົວຂໍ້ຖັນ",
        "columnName": "ຊື່ຖັນ",
        "defaultValue": "ຄ່າເລີ່ມຕົ້ນ",
        "openDocument": "ພິມເອກະສານ",
        "yes": "ແມ່ນ",
        "no": "ບໍ່",
        "openDocumentScript": "ເປີດເອກະສານ",
        "data": "ຂໍ້ມູນ",
        "selectData": "ເລືອກຂໍ້ມູນ",
        "selectTitle": "(ກະລຸນາເລືອກ)",
        "title": "ຫົວຂໍ້",
        "startTime": "ສ້າງເວລາ",
        "startTimeMonth": "ສ້າງເດືອນ",
        "completedTime": "ເວລາສຳເລັດ",
        "completedTimeMonth": "ເດືອນສຳເລັດ",
        "creatorPerson": "ຄົນຮ່າງ",
        "creatorIdentity": "ຕົວຕົນຄົນຮ່າງ",
        "creatorUnit": "ອົງກອນຮ່າງ",
        "creatorUnitLevelName": "ຮ່າງລຳດັບຊັ້ນຂອງອົງກອນ",
        "application": "application ID",
        "applicationName": "ຊື່ application",
        "applicationAlias": "ຊື່ແຝງ application",
        "process": "ຂະບວນການ ID",
        "processName": "ຊື່ຂະບວນການ",
        "processAlias": "ຊື່ແຝງຂະບວນການ",
        "serial": "serial number",
        "activityType": "ປະເພດ Activity",
        "activityName": "ຊື່ Activity",
        "activityArrivedTime": "Activityຮອດເວລາ",
        "workId": "ວຽກ ID",
        "workCompletedId": "ວຽກສຳເລັດID",
        "job": "JOBຂອງID(job)",
        "completed": "ສຳເລັດຫຼືບໍ່(completed)",

        "publishTime": "ເວລາເຜີຍແຜ່",
        "creatorUnitName": "ຮ່າງອົງກອນ",
        "creatorTopUnitName": "ຮ່າງລະດັບອົງກອນ",
        "appId": "ຖັນID",
        "appName": "ຊື່ຖັນ",
        "categoryId": "ປະເພດID",
        "categoryName": "ຊື່ປະເພດ",
        "categoryAlias": "ຊື່ແຝງປະເພດ",
        "documentId": "ເອກະສານID",

        "dataPath": "ຂໍ້ມູນ Path",
        "order": "ລຳດັບ",
        "none": "ບໍ່ມີ",
        "asc": "ລຽນລຳດັບນ້ອຍຫາໃຫ່ຍ",
        "desc": "ລຽນລຳດັບໃຫ່ຍຫານ້ອຍ",
        "orderToNumber": "ປ່ຽນເປັນລຽນລຳດັບຕົວເລກ",
        "category": "ປະເພດ",
        "hidden": "ເຊື່ອງ",
        "org": "ອົງກອນ",
        "htmlValue": "HTMLຄ່າ",
        "showScript": "ສະແດງລາຍງານ",
        "titleStyles": "ຮູບແບບຫົວຂໍ້ Cell",
        "titleProperties": "ຄຸນສົມບັດຫົວຂໍ້ Cell ",
        "contentStyles": "ຮູບແບບເນື້ອໃນ Cell",
        "contentProperties": "ຄຸນສົມບັດເນື້ອໃນ Cell",

        "buttonStyles": "ຮູບແບບແຖບ",
        "round": "rounded corners",
        "rect": "square angle",
        "showNumberPaging": "ສະແດງເລກໜ້າ",
        "numberShowCount": "ສະແດງຕົວເລກDigital ",
        "showBeforeAfter": "ສະແດງ ໜ້າຫຼັງ",
        "page": "ໜ້າ:",
        "hasFirstLastPage": "ສະແດງໜ້າທຳອິດໜ້າສຸດທ້າຍ",
        "hasPreNextPage": "ສະແດງໜ້າກ່ອນໜ້າໜ້າຖັດໄປ",
        "hasPageJumper": "ສະແດງຂ້າມໜ້າ",
        "firstPageText": "ເເອກະສານໜ້າ1",
        "lastPageText": "ເເອກະສານໜ້າສຸດທ້າຍ",
        "prevPageText": "ກັບໜ້າ",
        "nextPageText": "ໜ້າຖັດໄປ",

        "desciption": "ຂໍ້ມູນການແບ່ງໜ້າ",
        "position": "ທີ່ຕັ້ງ",
        "top": "ທາງໜ້າ",
        "bottom": "ທາງຫຼັງ",
        "format": "ຮູບແບບ",

        "hideView": "ເຊື່ອງ View",
        "orderNumber": "ລຳດັບ",
        "viewStyles": "ຮູບແບບView",
        "expandView": "ຂະຫຍາຍໝວດໝູ່",
        "showSequence": "ສະແດງລຳດັບ",
        "maxRow": "ຈຳນວນແຖວສູງສຸດ",
        "pageSize": "ຈຳນວນຂອງໜ້າແຖວ",
        "pageMaxCountNotice": "ໝາຍເຫດ：ຈຳນວນບັນທັດໄດ້ສູງສຸດເຖິງ2000",
        "actionbarHidden": "ເຊື່ອງແຖບດຳເນີນງານ",
        "pagingbarHidden": "ເຊື່ອງແຖບໜ້າ",
        "searchbarHidden": "ເຊື່ອງແຖບຄົ້ນຫາ",
        "radio": "ເລືອກອັນດຽວ",
        "checkbox": "ເລືອກຫຼາຍ",
        "selectBoxShow": "ເລືອກສະແດງ Box ",
        "always": "ຕະຫຼອດເວລາ",
        "mouseover": "Mouse over",
        "allowSelectAll": "ອະນຸຍາດເລືອກທັງໝົດ",
        "firstTdHidden": "ບໍ່ມີຈັດໝວດໝູ່ ແລະການເລືອກໃຫ້ເຊື່ອງຖັນທຳອິດ",
        "noDataText": "ບໍ່ມີຂໍ້ມູນສະແດງ",
        "cacheAccess": "ເປີດໃຊ້ງານ cache ",
        "cacheAccessNotice": "ໝາຍເຫດ：ເປີດໃຊ້ງານ cache ຈະເຮັດໃຫ້ສິດໃນຂອບເຂດເປັນໂມຄະ！",
        "executable": "ຜູ້ດຳເນີນການ",
        "availableIdentityList": "ຜູ້ດຳເນີນການ",
        "availableUnitList": "ດຳເນີນອົງກອນ",
        "defaultSelectedScript": "default selected line script",
        "selectedAbleScript": "ອະນຸຍາດເລືອກແຖວລາຍງານ",
        "range": "ຊ່ວງ",
        "timeRange": "ໄລຍະເວລາ",
        "timeRangeNotice": "ໝາຍເຫດ：ແນະນຳກຳນົດຊ່ວງເວລາເພື່ອປັບປຸງປະສິດຕິພາບ！",
        "rangeType": "ປະເພດໄລຍະເວລາ",
        "all": "ທັງໝົດ",
        "year": "ປີ",
        "season": "ລະດູການ",
        "monthly": "ປີ",
        "week": "ອາທິດ",
        "date": "ວັນທີ່",
        "beginDate": "ວັນທີ່ເລີ່ມ",
        "endDate": "ວັນທີ່ສິ້ນສຸດ",
        "currentYear": "ປະຈຸບັນປີ",
        "currentSeason": "ລະດູການປະຈຸບັນ",
        "firstSeason": "ລະດູການ 1",
        "secondSeason": "ລະດູການ 2",
        "thirdSeason": "ລະດູການ 3",
        "fourthSeason": "ລະດູການ 4 ",
        "currentMonth": "ເດືອນປະຈຸບັນ",
        "month": "ເດືອນ",
        "monthNumber": "ເດືອນ",
        "currentWeek": "ອາທິດປະຈຸບັນ",
        "weekNumber": "ອາທິດທີ(i)",
        "dateNumber": "(i)ວັນທີ່",
        "today": "ມື້ນີ້",
        "adjust": "Offset",
        "processPlatform": "ຂໍ້ມູນຂະບວນການPlatform ",
        "cmsPlatform": "ຂໍ້ມູນບໍລິຫານເນື້ອໃນ",
        "authority": "ອະນຸຍາດ",
        "check": "ການອະນຸຍາດ",
        "ignore": "ignore",
        "processStatus": "ສະຖານະCirculation",
        "work": "Circulation",
        "workCompleted": "ສຳເລັດ",
        "selectApplicationNotice": "ນຳເອົາ application ແລະ ຂະບວນການມາຮ່ວມກັນ",
        "selectApplication": "ເລືອກ application",
        "selectProcess": "ເລືອກຂະບວນການ",
        "dataType": "ປະເພດຂໍ້ມູນ",
        "dataTypeValue": ["ຂໍ້ຄວາມ", "ຂໍ້ມູນ"],
        "showDraft": "ກັບສູ່ຮ່າງເອກະສານ",
        "selectColumnNotice": "ນຳເອົາຖັນແລະປະເພດມາລວມກັນ",
        "selectColumn": "ເລືອກຖັນ",
        "selectCategory": "ເລືອກປະເພດ",
        "selectOrgNotice": "ເອົາອົງກອນ、ບຸກຄົນແລະຕົວຕົນມາລວມກັນ",
        "selectUnit": "ຮ່າງອົງກອນ",
        "selectPerson": "ຮ່າງບຸກຄົນ",
        "selectIdentity": "ຮ່າງຕົວຕົນ",

        "filter": "ຂັດກອງ",
        "path": "Path",

        "textValue": "ອັກສອນ",
        "numberValue": "ຕົວເລກ",
        "dateTimeValue": "ວັນທີເວລາ",
        "dateValue": "ວັນທີ",
        "timeValue": "ເວລາ",
        "booleanValue": "Boolean",

        "equals": "ເທົ່າ",
        "notEquals": "ບໍ່ເທົ່າ",
        "greaterThan": "ໃຫ່ຍກວ່າ",
        "greaterThanOrEqualTo": "ໃຫ່ຍກວ່າເທົ່າກັບ",
        "lessThan": "ນ້ອຍກວ່າ",
        "lessThanOrEqualTo": "ນ້ອຍກວ່າເທົ່າກັບ",
        "like": "ຈັບຄູ່",
        "notLike": "ບໍ່ຈັບຄູ່",
        "inRange": "ຊ່ວງ",
        "in": "ລວມ",

        "script": "ລາຍງານ",


        "filterRestrict": "ເປັນຕົວຂັດກອງເອກະສານ",
        "customFilterRestrict": "ເປັນຂໍ້ມູນຂັດກອງທີ່ກຳນົດເອງ",
        "logic": "Logic",
        "or": "ຫຼື",
        "and": "ແລະ",
        "comparison": "ປຽບທຽບ",
        "value": "ຄ່າ",
        "multiValueNotice": "ຄ່າຫຼາຍຄ່າຄັ້ນດ້ວຍເຄື່ຶອງໝາຍ(,)",
        "now": "ເວລາປະຈຸບັນ",
        "currentPerson": "ຄົນປະຈຸບັນ",
        "currentIdentity": "ຕົວຕົນປະຈຸບັນ",
        "currentPersonDirectUnit": "ບຸກຄົນປະຈຸບັນທັງໝົດໄປຫາອົງກອນໂດຍຕົງ",
        "currentPersonAllUnit": "ອົງກອນທັງໝົດທີ່ບຸກຄົນເປັນສະມາຊິກຢູ່",
        "currentPersonGroupList": "ກຸ່ມຄົນປະຈຸບັນ",
        "currentPersonRoleList": "ບົດບາດຂອງບຸກຄົນທີ່ຈຳເປັນປະຈຸບັນ",
        "to": "ທີ່",
        "input": "ປ້ອນຂໍ້ມູນ",
        "selectable": "ບໍ່ຈຳເປັນ",
        "selectOptionScriptNotice": "return [\"ຂໍ້ຄວາມຕົວເລືອກ|ຄ່າຕົວເລືອກ\"]",
        "selectOptionScript": "ລາຍງານຕົວເລືອກ",
        "defaultFilterCondition": "Default Filter Condition",
        "customFilterCondition": "Custom filter Condition",
        "byScript": "ອີງຕາມລາຍງານ",
        "language": "ພາສາ",
        "languageInfo": "ສົ່ງກັບ JSON ທີ່ມີຂໍ້ມູນພາສາ；o2.languageຮັບເອົາຂໍ້ມູນພາສາປະຈຸບັນ",
    },
    "viewStyle": {
        "default": "Default",
        "redSimple": "ສີແດງ",
        "blueSimple": "ສີຟ້າ",
        "official": "ຫ້ອງການ",
        "deepBlue": "ຟ້າເຂັັ້ມ",
        "blueFlat": "ສີຟ້າຂາວ",
        "greenFlat": "ສີຂຽວ"
    }
};