MWF.xApplication.query.ViewDesigner.LP = {
    "title": "视图编辑",
    "newView": "新建视图",
    "property": "属性",
    "item": "项目",
    "type": "类型",
    "value": "值",
    "view": "视图",
    "unnamed": "无标题列",
    "unCategory": "未分类",

    "id": "标识",
    "name": "名称",
    "alias": "别名",
    "description": "描述",
    "saveViewNotice" : "请先保存视图！",

    "application" : "数据应用",
    "newView" : "新视图",
    "newViewName" : "新视图名称",
    "copy" : "副本",
    "ok" : "确定",
    "cancel" : "取消",

    "action": {
        "move": "移动",
        "delete": "删除",
        "add": "添加"
    },

    "notice": {
        "save_success": "视图保存成功！",
        "saveAs_success" : "视图另存成功，您可以在视图设置中打开新视图！",

        "deleteFilterTitle": "删除筛选条件确认",
        "deleteFilter": "是否确定删除筛选条件？",

        "deleteColumnTitle": "删除列确认",
        "deleteColumn": "是否确定删除当前列？",


        "changeTypeTitle": "改变数据类型确认",
        "changeTypeDeleteChildren": "改变数据类型将删除所有子数据，是否确定要执行？",
        "changeType": "改变数据类型将改变数据的值，是否确定要执行？",

        "inputTypeError": "您输入的数据类型有误，请重新输入",
        "sameKey": "您输入的项目名称在对象中已存在，请重新输入",
        "emptyKey": "项目名称不能为空，请重新输入",
        "numberKey": "项目名称不能为数字，请重新输入",

        "inputName": "请输入视图名称",
        "noModifyName": "不能修改名称或者别名",

        "deleteEventTitle": "删除事件确认",
        "deleteEvent": "是否确定删除当前事件吗？",

        "selectProcess": "请选择应用或者流程",
        "selectCMS": "请选择内容管理栏目或者分类",
        "selectDateRange": "时段类型为范围，请选择开始日期和结束日期"
    },
    "actionbar": {
        "readhide": "设置阅读时是否显示",
        "edithide": "设置编辑时是否显示",
        "hideCondition": "设置隐藏条件",
        "title": "标题",
        "img": "图标",
        "action": "操作",
        "condition": "显示条件",
        "editScript": "操作脚本编辑",
        "editCondition": "隐藏条件编辑（返回true隐藏操作）",
        "up" : "上移",
        "property" : "属性",
        "addCustomTool" : "添加自定义操作",
        "delete" : "删除",
        "setProperties" : "设置操作属性",
        "restoreDefaultTool" : "恢复删除的系统操作",
        "selectDefaultTool" : "选择系统操作"
    },
    "mastInputPath": "请输入数据路径",
    "mastInputTitle": "请输入标题",
    "filter": {
        "and": "并且",
        "or": "或者",
        "equals": "等于",
        "notEquals": "不等于",
        "greaterThan": "大于",
        "greaterThanOrEqualTo": "大于等于",
        "lessThan": "小于",
        "lessThanOrEqualTo": "小于等于",
        "like": "匹配",
        "notLike": "不匹配",
        "range": "范围",
        "logic" : "逻辑",
        "path" : "路径",
        "compare" : "比较",
        "value" : "值",
        "columnValue" : "列值",
        "contain" : "包含",
        "from" : "从"
    },
    "delete_filterItem_title": "删除过滤条件确认",
    "delete_filterItem": "您确定要删除当前过滤条件吗？",
    "propertyTemplate": {
        "base": "基本",
        "event": "事件",
        "html": "HTML",
        "json": "JSON",
        "action": "操作",
        "select": "选择",
        "alias": "别名",

        "id": "标识",
        "name": "名称",
        "description": "描述",
        "appearance": "外观类型",
        "style": "样式",
        "attribute": "属性",
        "systemAction": "系统操作",

        "show": "显示",
        "hide": "隐藏",
        "columnTitle": "列标题",
        "columnName":"列名",
        "defaultValue":"默认值",
        "openDocument":"打开文档",
        "yes":"是",
        "no":"否",
        "openDocumentScript":"打开文档脚本",
        "data":"数据",
        "selectData":"选择数据",
        "selectTitle":"(请选择)",
        "title":"标题",
        "startTime":"创建时间",
        "startTimeMonth":"创建月份",
        "completedTime":"完成时间",
        "completedTimeMonth":"完成月份",
        "creatorPerson":"拟稿人",
        "creatorIdentity":"拟稿人身份",
        "creatorUnit":"拟稿组织",
        "creatorUnitLevelName":"拟稿组织层级",
        "application":"应用ID",
        "applicationName":"应用名称",
        "applicationAlias":"应用别名",
        "process":"流程ID",
        "processName":"流程名称",
        "processAlias":"流程别名",
        "serial":"编号",
        "activityType":"活动类型",
        "activityName":"活动名称",
        "activityArrivedTime":"活动到达时间",
        "workId":"工作ID",
        "workCompletedId":"已完成工作ID",
        "job":"JOB的ID(job)",
        "completed":"是否已完成(completed)",

        "publishTime":"发布时间",
        "creatorUnitName":"拟稿组织",
        "creatorTopUnitName":"拟稿顶级组织",
        "appId":"栏目ID",
        "appName":"栏目名称",
        "categoryId":"分类ID",
        "categoryName":"分类名称",
        "categoryAlias":"分类别名",
        "documentId":"文档ID",

        "dataPath":"数据路径",
        "order":"排序",
        "none":"无",
        "asc":"升序",
        "desc":"降序",
        "orderToNumber":"转换成数字排序",
        "category":"分类",
        "hidden":"隐藏",
        "org":"组织对象",
        "htmlValue":"HTML值",
        "showScript":"显示脚本",
        "titleStyles":"标题单元格样式",
        "titleProperties":"标题单元格属性",
        "contentStyles":"内容单元格样式",
        "contentProperties":"内容单元格属性",

        "buttonStyles":"按钮样式",
        "round":"圆角",
        "rect":"方角",
        "showNumberPaging":"显示数字分页",
        "numberShowCount":"数字显示个数",
        "showBeforeAfter":"显示前后",
        "page":"页:",
        "hasFirstLastPage":"显示首页末页",
        "hasPreNextPage":"显示上页下页",
        "hasPageJumper":"显示跳页",
        "firstPageText":"第一页文本",
        "lastPageText":"最后一页文本",
        "prevPageText":"上一页文本",
        "nextPageText":"下一页文本",

        "hideView":"隐藏视图",
        "viewStyles":"视图样式",
        "expandView":"展开分类",
        "showSequence":"显示序号",
        "maxRow":"最大行数",
        "pageSize":"每页行数",
        "pageMaxCountNotice":"注：每页最大行数为2000条",
        "actionbarHidden":"隐藏操作条",
        "radio": "单选",
        "checkbox": "多选",
        "selectBoxShow":"选择框显示",
        "always":"一直显示",
        "mouseover":"鼠标经过时",
        "allowSelectAll":"允许全选",
        "firstTdHidden":"无分类和选择隐藏首列",
        "noDataText":"无数据显示",
        "cacheAccess":"启用缓存",
        "cacheAccessNotice":"注：启用缓存则范围中的权限失效！",
        "executable": "可执行者",
        "availableIdentityList":"可执行人",
        "availableUnitList":"执行组织",
        "defaultSelectedScript":"默认选中行脚本",
        "selectedAbleScript":"允许选择行脚本",
        "range":"范围",
        "timeRange":"时段",
        "timeRangeNotice":"注：建议设定时间范围有助于提高效率！",
        "rangeType":"时段类型",
        "all":"全部",
        "year":"年度",
        "season":"季度",
        "monthly":"月份",
        "week":"周",
        "date":"日",
        "beginDate":"开始日期",
        "endDate":"结束日期",
        "currentYear":"当前年度",
        "currentSeason":"当前季度",
        "firstSeason":"第一季度",
        "secondSeason":"第二季度",
        "thirdSeason":"第三季度",
        "fourthSeason":"第四季度",
        "currentMonth":"当前月份",
        "month":"月",
        "monthNumber":"月",
        "currentWeek":"当前周",
        "weekNumber": "第(i)周",
        "dateNumber": "(i)日",
        "today":"当天",
        "adjust":"偏移量",
        "processPlatform":"流程平台数据",
        "cmsPlatform":"内容管理数据",
        "authority":"权限",
        "check":"带权限",
        "ignore":"忽略",
        "processStatus":"流转状态",
        "work":"流转中",
        "workCompleted":"已完成",
        "selectApplicationNotice":"取应用和流程的并集",
        "selectApplication":"选择应用",
        "selectProcess":"选择流程",
        "dataType":"数据类型",
        "dataTypeValue": ["信息类","数据类"],
        "showDraft":"返回草稿",
        "selectColumnNotice":"取栏目和分类的并集",
        "selectColumn":"选择栏目",
        "selectCategory":"选择分类",
        "selectOrgNotice":"取组织、人员和身份的并集",
        "selectUnit":"拟稿组织",
        "selectPerson":"拟稿人员",
        "selectIdentity":"拟稿身份",

        "filter":"过滤",
        "path":"路径",

        "textValue":"文本",
        "numberValue":"数字",
        "dateTimeValue":"日期时间",
        "dateValue":"日期",
        "timeValue":"时间",
        "booleanValue":"布尔",

        "equals":"等于",
        "notEquals":"不等于",
        "greaterThan":"大于",
        "greaterThanOrEqualTo":"大于等于",
        "lessThan":"小于",
        "lessThanOrEqualTo":"小于等于",
        "like":"匹配",
        "notLike":"不匹配",
        "inRange":"范围",
        "in":"包含",

        "script" : "脚本",


        "filterRestrict":"作为默认过滤条件",
        "customFilterRestrict":"作为自定义过滤数据",
        "logic":"逻辑",
        "or":"或者",
        "and":"并且",
        "comparison":"比较",
        "value":"值",
        "multiValueNotice":"多值用半角逗号(,)隔开",
        "now":"当前时间",
        "currentPerson":"当前人",
        "currentIdentity":"当前身份",
        "currentPersonDirectUnit":"当前人所在直接组织",
        "currentPersonAllUnit":"当前人所在所有组织",
        "to":"到",
        "input":"输入",
        "selectable":"可选",
        "selectOptionScriptNotice":"return [\"选项文本|选项值\"]",
        "selectOptionScript":"选项脚本",
        "defaultFilterCondition":"默认过滤条件",
        "customFilterCondition":"自定义过滤数据"
    },
    "viewStyle":{
        "default": "默认样式",
        "redSimple":"红色简洁",
        "blueSimple":"蓝色简洁",
        "official":"公文样式",
        "deepBlue":"集团样式",
        "blueFlat":"蓝白扁平"
    }
};