MWF.xApplication.query.ViewDesigner.LP = {
    "title": "視圖編輯",
    "newView": "新建視圖",
    "property": "屬性",
    "item": "項目",
    "type": "類型",
    "value": "值",
    "view": "視圖",
    "unnamed": "無標題列",
    "unCategory": "未分類",
    "id": "標識",
    "name": "名稱",
    "alias": "別名",
    "description": "描述",
    "saveViewNotice": "請先保存視圖！",
    "application": "數據應用",
    "newView": "新視圖",
    "newViewName": "新視圖名稱",
    "copy": "複製",
    "ok": "確認",
    "cancel": "取消",
    "action": {
        "move": "移動",
        "delete": "刪除",
        "add": "添加"
    },

    "notice": {
        "save_success": "儲存視圖成功！",
        "saveAs_success": "另存視圖成功，您可以在視圖設定中開啟新視圖！",

        "deleteFilterTitle": "刪除篩選條件確認",
        "deleteFilter": "是否確定刪除篩選條件？",

        "deleteColumnTitle": "刪除列確認",
        "deleteColumn": "是否確定刪除目前的列？",

        "changeTypeTitle": "更改數據類型確認",
        "changeTypeDeleteChildren": "更改數據類型將刪除所有子數據，是否確定執行？",
        "changeType": "更改數據類型將更改數據的值，是否確定執行？",

        "inputTypeError": "您輸入的數據類型有誤，請重新輸入",
        "sameKey": "您輸入的項目名稱已存在於對象中，請重新輸入",
        "emptyKey": "項目名稱不能為空，請重新輸入",
        "numberKey": "項目名稱不能為數字，請重新輸入",

        "inputName": "請輸入視圖名稱",
        "noModifyName": "無法修改名稱或別名",

        "deleteEventTitle": "刪除事件確認",
        "deleteEvent": "是否確定刪除目前事件？",

        "selectProcess": "請選擇應用程序或流程",
        "selectCMS": "請選擇內容管理項目或分類",
        "selectDateRange": "時間範圍為範圍，請選擇開始日期和結束日期"
    },
    "actionbar": {
        "readhide": "設定閱讀時是否顯示",
        "edithide": "設定編輯時是否顯示",
        "hideCondition": "設定隱藏條件",
        "title": "標題",
        "img": "圖示",
        "action": "操作",
        "condition": "顯示條件",
        "editScript": "操作腳本編輯",
        "editCondition": "隱藏條件編輯（返回 true 隱藏操作）",
        "up": "上移",
        "property": "屬性",
        "addCustomTool": "新增自訂操作",
        "delete": "刪除",
        "setProperties": "設定操作屬性",
        "restoreDefaultTool": "還原已刪除的系統操作",
        "selectDefaultTool": "選擇系統操作"
    },
    "actionBar": {
        "exportExcel": "匯出 Excel"
    },
    "mastInputPath": "請輸入數據路徑",
    "mastInputTitle": "請輸入標題",
    "filter": {
        "and": "並且",
        "or": "或者",
        "equals": "等於",
        "notEquals": "不等於",
        "greaterThan": "大於",
        "greaterThanOrEqualTo": "大於等於",
        "lessThan": "小於",
        "lessThanOrEqualTo": "小於等於",
        "like": "匹配",
        "notLike": "不匹配",
        "range": "範圍",
        "logic" : "邏輯",
        "path" : "路徑",
        "compare" : "比較",
        "value" : "值",
        "columnValue" : "列值",
        "contain" : "包含",
        "from" : "從",
        "in": "包含"
    },
    "delete_filterItem_title": "刪除篩選條件確認",
    "delete_filterItem": "您確定要刪除當前篩選條件嗎？",
    "propertyTemplate": {
        "base": "基本",
		"event": "事件",
		"html": "HTML",
		"json": "JSON",
		"action": "操作",
		"select": "選擇",
		"alias": "別名",
		"id": "標識",
		"name": "名稱",
		"description": "描述",
		"appearance": "外觀類型",
		"style": "風格",
		"attribute": "屬性",
		"systemAction": "系統操作",
		"show": "顯示",
		"hide": "隱藏",
		"columnTitle": "列標題",
		"columnName":"列名",
		"defaultValue":"默認值",
		"openDocument":"打開文檔",
		"yes":"是",
		"no":"否",
		"openDocumentScript":"打開文檔腳本",
		"data":"數據",
		"selectData":"選擇數據",
		"selectTitle":"(請選擇)",
		"title":"標題",
		"startTime":"創建時間",
		"startTimeMonth":"創建月份",
		"completedTime":"完成時間",
		"completedTimeMonth":"完成月份",

        "creatorPerson": "擬稿人",
		"creatorIdentity": "擬稿人身份",
		"creatorUnit": "擬稿組織",
		"creatorUnitLevelName": "擬稿組織層級名稱",
		"application": "應用ID",
		"applicationName": "應用名稱",
		"applicationAlias": "應用別名",
		"process": "流程ID",
		"processName": "流程名稱",
		"processAlias": "流程別名",
		"serial": "編號",
		"activityType": "活動類型",
		"activityName": "活動名稱",
		"activityArrivedTime": "活動到達時間",
		"workId": "工作ID",
		"workCompletedId": "已完成工作ID",
		"job": "JOB的ID",
		"completed": "是否已完成",
		"publishTime": "發佈時間",
		"creatorUnitName": "擬稿組織",
		"creatorTopUnitName": "擬稿頂級組織",
		"appId": "欄目ID",
		"appName": "欄目名稱",
		"categoryId": "分類ID",
		"categoryName": "分類名稱",
		"categoryAlias": "分類別名",
		"documentId": "文檔ID",

        "dataPath": "數據路徑",
		"order": "排序",
		"none": "無",
		"asc": "升序",
		"desc": "降序",
		"orderToNumber": "轉換成數字排序",
		"category": "分類",
		"hidden": "隱藏",
		"org": "組織對象",
		"htmlValue": "HTML值",
		"showScript": "顯示腳本",
		"titleStyles": "標題儲存格樣式",
		"titleProperties": "標題儲存格屬性",
		"contentStyles": "內容儲存格樣式",
		"contentProperties": "內容儲存格屬性",
		"buttonStyles": "按鈕樣式",
		"round": "圓角",
		"rect": "方角",
		"showNumberPaging": "顯示數字分頁",
		"numberShowCount": "數字顯示個數",
		"showBeforeAfter": "顯示前後",
		"page": "頁:",
		"hasFirstLastPage": "顯示首頁末頁",
		"hasPreNextPage": "顯示上頁下頁",
		"hasPageJumper": "顯示跳頁",
		"firstPageText": "第一頁文本",
		"lastPageText": "最後一頁文本",
		"prevPageText": "上一頁文本",
		"nextPageText": "下一頁文本",

        "desciption": "分頁資訊",
		"position": "位置",
		"top": "前方",
		"bottom": "後方",
		"format": "格式",
		"hideView": "隱藏視圖",
		"orderNumber": "排序號",
		"viewStyles": "視圖樣式",
		"expandView": "展開分類",
		"showSequence": "顯示序號",
		"maxRow": "最大行數",
		"pageSize": "每頁行數",
		"pageMaxCountNotice": "注：每頁最大行數為2000條",
		"actionbarHidden": "隱藏操作欄",
		"pagingbarHidden": "隱藏分頁欄",
		"searchbarHidden": "隱藏搜索欄",
		"radio": "單選",
		"checkbox": "多選",
		"selectBoxShow": "選擇框顯示",
		"always": "一直顯示",
		"mouseover": "鼠標經過時",
		"allowSelectAll": "允許全選",
		"firstTdHidden": "無分類和選擇隱藏首列",
		"noDataText": "無數據顯示",
		"cacheAccess": "啟用緩存訪問",
		"cacheAccessNotice": "注：啟用緩存則範圍內的權限失效！",
		"executable": "可執行者",
		"availableIdentityList": "可執行人",
		"availableUnitList": "執行組織",
		"defaultSelectedScript": "默認選中行腳本",
		"selectedAbleScript": "允許選擇行腳本",
		"range": "範圍",
		"timeRange": "時段範圍",
		"timeRangeNotice": "注：建議設定時間範圍有助於提高效率！",
		"rangeType": "時段類型",

        "all": "全部",
		"year": "年度",
		"season": "季度",
		"monthly": "月份",
		"week": "周",
		"date": "日期",
		"beginDate": "開始日期",
		"endDate": "結束日期",
		"currentYear": "當前年度",
		"currentSeason": "當前季度",
		"firstSeason": "第一季度",
		"secondSeason": "第二季度",
		"thirdSeason": "第三季度",
		"fourthSeason": "第四季度",
		"currentMonth": "當前月份",
		"month": "月",
		"monthNumber": "第(i)月",
		"currentWeek": "當前周",
		"weekNumber": "第(i)周",
		"dateNumber": "第(i)日",
		"today": "今天",
		"adjust": "調整",
		"processPlatform": "流程平台數據",
		"cmsPlatform": "內容管理數據",
		"authority": "權限",
		"check": "帶權限",
		"ignore": "忽略",
		"processStatus": "流轉狀態",
		"work": "流轉中",
		"workCompleted": "已完成",
		"selectApplicationNotice": "取應用和流程的並集",
		"selectApplication": "選擇應用",
		"selectProcess": "選擇流程",
		"dataType": "數據類型",
		"dataTypeValue": ["信息類", "數據類"],
		"showDraft": "返回草稿",
		"selectColumnNotice": "取欄目和分類的並集",
        "selectColumn": "열 선택",
		"selectCategory": "카테고리 선택",
		"selectOrgNotice": "조직, 사람 및 신분의 합집합 선택",
		"selectUnit": "기안 조직",
		"selectPerson": "기안자",
		"selectIdentity": "기안 신분",

        "filter": "過濾",
		"path": "路徑",
		"textValue": "文本",
		"numberValue": "數字",
		"dateTimeValue": "日期時間",
		"dateValue": "日期",
		"timeValue": "時間",
		"booleanValue": "布爾值",
		"equals": "等於",
		"notEquals": "不等於",
		"greaterThan": "大於",
		"greaterThanOrEqualTo": "大於等於",
		"lessThan": "小於",
		"lessThanOrEqualTo": "小於等於",
		"like": "匹配",
		"notLike": "不匹配",
		"inRange": "範圍內",
		"in": "包含",
		"script": "腳本",


        "filterRestrict": "作為默認過濾條件",
		"customFilterRestrict": "作為自定義過濾數據",
		"logic": "邏輯",
		"or": "或者",
		"and": "並且",
		"comparison": "比較",
		"value": "值",
		"multiValueNotice": "多個值用半角逗號(,)隔開",
		"now": "當前時間",
		"currentPerson": "當前用戶",
		"currentIdentity": "當前身份",
		"currentPersonDirectUnit": "當前用戶所在直接組織",
		"currentPersonAllUnit": "當前用戶所在所有組織",
		"currentPersonGroupList": "當前用戶所在群組",
		"currentPersonRoleList": "當前用戶擁有角色",
		"to": "到",
		"input": "輸入",
		"selectable": "可選",
		"selectOptionScriptNotice": "return [\"選項文本|選項值\"]",
		"selectOptionScript": "選項腳本",
		"defaultFilterCondition": "默認過濾條件",
		"customFilterCondition": "自定義過濾數據",
		"byScript": "根據腳本",
		"language": "語言包",
		"languageInfo": "返回包含語言信息的JSON對象；o2.language獲取當前語言信息"
    },
    "viewStyle": {
        "default": "默認風格",
        "redSimple": "紅色簡潔風格",
        "blueSimple": "藍色簡潔風格",
        "official": "公文風格",
        "deepBlue": "集團風格",
        "blueFlat": "藍白扁平風格",
        "greenFlat": "綠色扁平風格"
    }
};