MWF.xApplication.Profile.LP = {
	"title": "Personal Settings",
    "inforConfig": "Personal",
    "layoutConfig": "UI",
    "ideaConfig": "Opinion",
    "passwordConfig": "Password",

    "clear": "清除界面数据",
    "setDefault": "设置为默认界面",
    "clearDefault": "清除默认界面",
    "setForce": "设置强制打开应用",
    "clearForce": "清除强制打开应用",
    "setDefaultOk": "已设置为默认界面",
    "setForceOk": "已设置强制打开应用",
    "clearok": "桌面缓存记录已清除",
    "saveIdea": "保存常用意见",
    "saveIdeaDefault": "保存为默认常用意见",
    "ideaSaveOk": "常用意见保存完成",

    "icon": "头像",
    "changeIcon": "更换头像",
    "name": "姓名",
    "employee": "工号",
    "display": "昵称",
    "officePhone": "办公电话",
    "mail": "邮件地址",
    "mobile": "手机号码",
    "weixin": "微信号",
    "QQ": "QQ",
    "signature": "个人签名",
    "saveInfor": "保存个人信息",
    "saveInforOk": "保存个人信息成功",

    "passwordRule" : "密码规则",
    "oldPassword": "原密码",
    "password": "新密码",
    "morePassword": "确认密码",
    "passwordNotMatch": "新密码与确认密码不一致",
    "changePasswordOk": "密码修改成功",

    "changePersonIcon": "修改个人头像",

    "layoutAction": "界面操作",
    "desktopBackground": "桌面背景",
    "paswordRule" : "请使用数字和字母组合且长度大于7。不要用常用密码如password、123等",
    "weak" : "弱",
    "middle" : "中",
    "high" : "强",

    "empower":{
        "fromPerson":"人员",
        "fromIdentity":"身份",
        "toPerson":"委托人员",
        "toIdentity":"委托身份",
        "application":"应用",
        "applicationName":"应用名称",
        "applicationAlias":"应用别名",
        "process":"流程ID",
        "processName":"流程名称",
        "processAlias":"流程别名",
        "type":"授权类型",
        "startTime":"授权开始时间",
        "completedTime":"授权结束时间",
        "emPowerConfig": "外出授权",
        "addEmPower": "新增",
        "myEmPower": "我的委托",
        "receiveEmPower": "收到的委托",
        "ok":"保存",
        "cancel":"关闭",
        "noData":"暂时没有委托",
        "withdraw":"撤回",
        "alert1":"请选择流程或应用",
        "alert2":"请联系管理员添加身份信息！",
        "withdrawOk":"撤回委托成功",
        "selectEmPower":"请选择委托",
        "saveOk":"保存成功",
        "type_all":"全部",
        "type_application":"应用",
        "type_process":"流程",
        "type_filter":"文件类型",
        "saveNotAll":"部分保存失败",
        "title":"标题",
        "activityName":"状态",
        "createTime":"委托时间",
        "edit":"编辑",
        "editEmpower":"编辑外出授权",
        "enable":"启用",
        "disable":"禁用"
    },

    "emPowerConfig": "外出授权",
    "addEmPower": "新增",
    "myEmPower": "我的委托",
    "receiveEmPower": "收到的委托",
    "myEmPowerLog": "委托的待办",
    "receiveEmPowerLog": "收到的待办",
    "ok":"保存",
    "cancel":"关闭"
};