MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Profile = MWF.xApplication.Profile || {};
MWF.xApplication.Profile.LP={
	"title": "Personal Settings",
	"inforConfig": "Personal",
	"layoutConfig": "UI",
	"ideaConfig": "Opinion",
	"passwordConfig": "Password",
	"ssoConfig": "SSO",
	"facelogin": "FaceLogin",
	"openFaceSet": "click here, Open FaceSet",
	"clear": "Clear ui config data",
	"setDefault": "Set as the default ui config",
	"clearDefault": "Clear default ui config data",
	"setForce": "Set force to open the application",
	"clearForce": "Clear forced open application",
	"setDefaultOk": "The default ui config has been set",
	"setForceOk": "Forced to open the app has been set",
	"clearok": "Desktop cache record has been cleared",
	"saveIdea": "Save frequently opinions",
	"saveIdeaDefault": "Save as default opinions",
	"ideaSaveOk": "Frequently opinions saved",
	"workDeletedNote": "Job '{title}' has been deleted or you do not have permission to open it.",
	"workDeletedTitle": "No job found",
	"workDeletedContent": "Job '{title}' has been deleted or you do not have permission to open it. Do you want to delete this authorization record?",
	"deleteSuccess": "Delete successful",
	"icon": "Avatar",
	"changeIcon": "Change",
	"name": "Name",
	"employee": "Employee",
	"display": "Nickname",
	"officePhone": "OfficePhone",
	"mail": "Mail",
	"mobile": "Cellphone",
	"weixin": "Wechat",
	"QQ": "QQ",
	"signature": "Signature",
	"saveInfor": "Save personal information",
	"saveInforOk": "Personal information saved successfully",
	"nickNameInforError": "The nickname format is incorrect, the rules are as follows: only Chinese, Number, English, _, - and spaces can be used, the length is 4 to 20, and the length of one Chinese is 2",
	"ipAddress": "Login IP",
	"ipAddressPlaceHolder": "If it is not empty, only the matching ip address can log in to the account. Separate multiple values with \",\"",
	"ipAddressIncorrectNotice": "IP address format is incorrect:",
	"language": "Language",
	"forumNickName": "Forum Nickname",
	"lps": {
		"zh-CN": "简体中文",
		"en": "English",
		"es": "español",
		"ko": "한국인",
		"zh-HK": "繁體中文"
	},
	"passwordRule": "Password rules",
	"oldPassword": "Old password",
	"password": "New password",
	"morePassword": "Confirm password",
	"passwordNotMatch": "The new password does not match the confirmed password",
	"changePasswordOk": "Password reset complete",
	"changePersonIcon": "Change Avatar",
	"layoutAction": "UI operation",
	"desktopBackground": "Desktop background",
	"paswordRule": "6 or more digits, including numbers and letters.",
	"weak": "weak",
	"middle": "middle",
	"high": "high",
	"empower": {
		"fromPerson": "Person",
		"fromIdentity": "Identity",
		"toPerson": "EmpoweredPerson",
		"toIdentity": "EmpoweredIdentity",
		"keepTask": "Keep my task",
		"application": "Application",
		"applicationName": "Application Name",
		"applicationAlias": "Application Alias",
		"process": "Process",
		"processName": "Process Name",
		"processAlias": "Process Alias",
		"type": "Type",
		"startTime": "Start Time",
		"completedTime": "Completed Time",
		"emPowerConfig": "Empowerment",
		"addEmPower": "create",
		"myEmPower": "My Empowerment",
		"receiveEmPower": "Empowered to me",
		"ok": "Save",
		"cancel": "Cancel",
		"noData": "No Empowerment",
		"withdraw": "Withdraw",
		"alert1": "Please select a process or application",
		"alert2": "Please contact the administrator to add identity information!",
		"withdrawOk": "Withdraw the empowerment successfully",
		"selectEmPower": "Select the empowerment",
		"saveOk": "Saved successfully",
		"type_all": "All",
		"type_application": "Application",
		"type_process": "Process",
		"type_filter": "File type",
		"saveNotAll": "Partial save failed",
		"startTimeEarlyCompleteTime": "The start time cannot be later than the end time",
		"title": "Title",
		"activityName": "Activity",
		"createTime": "Commission time",
		"edit": "Edit",
		"editEmpower": "Edit empowerment",
		"enable": "Enable",
		"disable": "Disable"
	},
	"emPowerConfig": "Empower",
	"addEmPower": "create",
	"myEmPower": "My Empowerment",
	"receiveEmPower": "Empowered to me",
	"myEmPowerLog": "Empowered Task",
	"receiveEmPowerLog": "Empowered Task received",
	"ok": "Save",
	"cancel": "Cancel",
	"bindOauth": "Bind Oauth account",
	"pageText": "Page {n}",
	"search": "search",
	"cancel1": "cancel",
	"createEmpower": "New Out of Office Authorization",
	"noTask": "No To Do",
	"action": "operation",
	"createAuthorize": "New Delegation"
}
MWF.xApplication.Profile["lp."+o2.language] = MWF.xApplication.Profile.LP