MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Profile = MWF.xApplication.Profile || {};
MWF.xApplication.Profile.LP={
	"title": "Configuración personal",
	"inforConfig": "Persona",
	"layoutConfig": "Configuración de interfaz",
	"ideaConfig": "Opinión",
	"passwordConfig": "Contraseña",
	"ssoConfig": "Único punto",
	"facelogin": "Cara",
	"openFaceSet": "Haga clic aquí para abrir la configuración de inicio de sesión facial",
	"clear": "Borrar datos de interfaz",
	"setDefault": "Establecer como interfaz predeterminada",
	"clearDefault": "Limpiar interfaz predeterminada",
	"setForce": "Establecer aplicación forzada",
	"clearForce": "Borrar aplicación forzada",
	"setDefaultOk": "Interfaz predeterminada establecida",
	"setForceOk": "Aplicación forzada establecida",
	"clearok": "Se ha eliminado el registro de caché del escritorio",
	"saveIdea": "Guardar opiniones comunes",
	"saveIdeaDefault": "Guardar como opinión común predeterminada",
	"ideaSaveOk": "Opiniones comunes guardadas",
	"workDeletedNote": "El trabajo \"{title}\" ha sido eliminado o no tiene permisos para abrirlo.",
	"workDeletedTitle": "Trabajo no encontrado",
	"workDeletedContent": "El trabajo \"{title}\" ha sido eliminado o no tiene permisos para abrirlo. ¿Quieres eliminar este registro de autorización?",
	"deleteSuccess": "Eliminado con éxito",
	"icon": "Avatar",
	"changeIcon": "Cambiar avatar",
	"name": "Nombre",
	"employee": "Empleado",
	"display": "Apodo",
	"officePhone": "Teléfono de oficina",
	"mail": "Dirección de correo electrónico",
	"mobile": "Número de teléfono móvil",
	"weixin": "ID de WeChat",
	"QQ": "QQ",
	"signature": "Firma personal",
	"saveInfor": "Guardar información personal",
	"saveInforOk": "Información personal guardada correctamente",
	"nickNameInforError": "El formato del apodo no es correcto, las reglas son las siguientes: solo se permiten caracteres chinos, números, letras, guiones bajos (_), guiones (-) y espacios, la longitud debe ser de 4 a 20 caracteres, una letra china cuenta como 2 caracteres",
	"ipAddress": "IP de inicio de sesión",
	"ipAddressPlaceHolder": "Si no está vacío, solo se pueden iniciar sesión las direcciones IP que coincidan, separadas por ,",
	"ipAddressIncorrectNotice": "Formato de dirección IP incorrecto:",
	"language": "Configuración de idioma",
	"forumNickName": "Apodo del foro",
	"lps": {
		"zh-CN": "简体中文",
		"en": "English",
		"es": "español",
		"ko": "한국인",
		"zh-HK": "繁體中文"
	},
	"passwordRule": "Reglas de contraseña",
	"oldPassword": "Contraseña anterior",
	"password": "Nueva contraseña",
	"morePassword": "Confirmar contraseña",
	"passwordNotMatch": "La nueva contraseña y la confirmación de contraseña no coinciden",
	"changePasswordOk": "Contraseña modificada con éxito",
	"changePersonIcon": "Cambiar avatar personal",
	"layoutAction": "Acciones de interfaz",
	"desktopBackground": "Fondo de pantalla del escritorio",
	"paswordRule": "Mínimo 6 caracteres con números y letras.",
	"weak": "Débil",
	"middle": "Media",
	"high": "Fuerte",
	"bindOauth": "Vincular cuenta Oauth",
	"empower": {
		"fromPerson": "Persona",
		"fromIdentity": "Identidad",
		"toPerson": "Persona delegada",
		"toIdentity": "Identidad delegada",
		"keepTask": "Guardar mis tareas pendientes",
		"application": "Aplicación",
		"applicationName": "Nombre de la aplicación",
		"applicationAlias": "Alias de la aplicación",
		"process": "ID del proceso",
		"processName": "Nombre del proceso",
		"processAlias": "Alias del proceso",
		"type": "Tipo",
		"startTime": "Hora de inicio de la autorización",
		"completedTime": "Hora de finalización de la autorización",
		"emPowerConfig": "Autorización de ausencia",
		"addEmPower": "Agregar",
		"myEmPower": "Mi autorización",
		"receiveEmPower": "Autorización recibida",
		"ok": "Guardar",
		"cancel": "Cerrar",
		"noData": "No hay autorizaciones por el momento",
		"withdraw": "Retirar",
		"alert1": "Seleccione un proceso o aplicación",
		"alert2": "Por favor, póngase en contacto con el administrador para agregar información de identidad",
		"withdrawOk": "La autorización se ha retirado con éxito",
		"selectEmPower": "Seleccione la autorización",
		"saveOk": "Guardado correctamente",
		"type_all": "Todos",
		"type_application": "Aplicación",
		"type_process": "Proceso",
		"type_filter": "Tipo de archivo",
		"saveNotAll": "Algunos no se pudieron guardar",
		"startTimeEarlyCompleteTime": "La hora de inicio no puede ser posterior a la hora de finalización",
		"title": "Título",
		"activityName": "Estado",
		"createTime": "Hora de autorización",
		"edit": "Editar",
		"editEmpower": "Editar autorización de ausencia",
		"enable": "Activar",
		"disable": "Desactivar"
	},
	"emPowerConfig": "Autorización",
	"addEmPower": "Agregar",
	"myEmPower": "Mi autorización",
	"receiveEmPower": "Autorización recibida",
	"myEmPowerLog": "Tareas delegadas",
	"receiveEmPowerLog": "Tareas recibidas",
	"ok": "Guardar",
	"cancel": "Cerrar",
	"pageText": "Página {n}",
	"search": "Buscar",
	"cancel1": "Cancelar",
	"createEmpower": "Crear autorización de ausencia",
	"noTask": "No hay tareas pendientes",
	"action": "Acción",
	"createAuthorize": "Crear autorización"
}
MWF.xApplication.Profile["lp."+o2.language] = MWF.xApplication.Profile.LP