MWF.xApplication.Profile.LP = {
	"title": "個人設定",
    "inforConfig": "個人情報",
    "layoutConfig": "レイアウト設定",
    "ideaConfig": "よく使う意見",
    "passwordConfig": "パスワード変更",
    "ssoConfig": "シングルサインオン",
    "facelogin": "顔認証ログイン",
    "openFaceSet": "ここをクリックして顔認証設定を開く",

    "clear": "インターフェースデータのクリア",
    "setDefault": "デフォルトインターフェースに設定",
    "clearDefault": "デフォルトインターフェースのクリア",
    "setForce": "アプリを強制的に開くように設定",
    "clearForce": "強制的に開くアプリのクリア",
    "setDefaultOk": "デフォルトインターフェースに設定されました",
    "setForceOk": "アプリを強制的に開くように設定されました",
    "clearok": "デスクトップキャッシュレコードがクリアされました",
    "saveIdea": "よく使う意見を保存",
    "saveIdeaDefault": "デフォルトのよく使う意見を保存",
    "ideaSaveOk": "よく使う意見の保存が完了しました",
    "workDeletedNote": "「{title}」の作業は削除されているか、開く権限がありません。",
    "workDeletedTitle": "作業が見つかりません",
    "workDeletedContent": "「{title}」の作業は削除されているか、開く権限がありません。この権限記録を削除しますか？",
    "deleteSuccess": "削除が成功しました",

    "icon": "アイコン",
    "changeIcon": "アイコン変更",
    "name": "名前",
    "employee": "社員番号",
    "display": "ニックネーム",
    "officePhone": "オフィス電話",
    "mail": "メールアドレス",
    "mobile": "携帯電話番号",
    "weixin": "WeChat ID",
    "QQ": "QQ",
    "signature": "個人署名",
    "saveInfor": "個人情報保存",
    "saveInforOk": "個人情報保存完了",
    "nickNameInforError": "ニックネームの形式が正しくありません。規則は次のとおりです：漢字、数字、英字、_、-、スペースのみ使用でき、長さは4から20文字である必要があります。漢字1文字は2文字として計算されます。",
    "ipAddress" : "ログインIP",
    "ipAddressPlaceHolder" : "空白でない場合、一致するIPアドレスのみログインできます。複数の値はコンマで区切ります。",
    "ipAddressIncorrectNotice" : "IPアドレスの形式が正しくありません：",
    "language": "言語設定",
    "forumNickName": "フォーラムのニックネーム",
    "lps": {
        "zh-CN": "简体中文",
        "en": "English",
		"es": "español",
		"ko":"한국어",
		"ja":"日本語",
		"zh-hk":"繁體中文"
    },

    "passwordRule" : "パスワードルール",
    "oldPassword": "旧パスワード",
    "password": "新しいパスワード",
    "morePassword": "パスワード確認",
    "passwordNotMatch": "新しいパスワードとパスワード確認が一致しません",
    "changePasswordOk": "パスワードが正常に変更されました",

    "changePersonIcon": "プロフィール写真の変更",

    "layoutAction": "インターフェース操作",
    "desktopBackground": "デスクトップの背景",
    "paswordRule" : "6文字以上で、数字と文字を含めてください。",
    "weak" : "弱",
    "middle" : "中",
    "high" : "強",

    "bindOauth": "Oauthアカウントのバインド",
    "empower":{
        "fromPerson":"発信者",
        "fromIdentity":"発信者の身分",
        "toPerson":"受信者",
        "toIdentity":"受信者の身分",
        "application":"アプリケーション",
        "applicationName":"アプリケーション名",
        "applicationAlias":"アプリケーション別名",
        "process":"プロセスID",
        "processName":"プロセス名",
        "processAlias":"プロセス別名",
        "type":"認可の種類",
        "startTime":"認可開始時間",
        "completedTime":"認可終了時間",
        "emPowerConfig": "外出認可",
        "addEmPower": "追加",
        "myEmPower": "私の認可",
        "receiveEmPower": "受信した認可",
        "ok":"保存",
        "cancel":"閉じる",
        "noData":"現在、認可はありません",
        "withdraw":"取り消し",
        "alert1":"プロセスまたはアプリケーションを選択してください",
        "alert2":"管理者に身分情報を追加するようにお問い合わせください！",
        "withdrawOk":"認可の取り消しが成功しました",
        "selectEmPower":"認可を選択してください",
        "saveOk":"保存が成功しました",
        "type_all":"すべて",
        "type_application":"アプリケーション",
        "type_process":"プロセス",
        "type_filter":"ファイルの種類",
        "saveNotAll":"一部の保存に失敗しました",
        "startTimeEarlyCompleteTime": "開始時間は終了時間よりも早い必要があります",
        "title":"タイトル",
        "activityName":"ステータス",
        "createTime":"認可時間",
        "edit":"編集",
        "editEmpower":"外出認可の編集",
        "enable":"有効",
        "disable":"無効"
    },

    "emPowerConfig": "外出認可",
    "addEmPower": "新規",
    "myEmPower": "私の認可",
    "receiveEmPower": "受信認可",
    "myEmPowerLog": "認可待ち",
    "receiveEmPowerLog": "受信待ち",
    "ok":"保存",
    "cancel":"閉じる",
    "pageText" : "第{n}ページ",
    "search" : "検索",
    "cancel1" : "キャンセル",
    "createEmpower" : "外出認可の新規作成",
    "noTask" : "未処理タスクなし",
    "action" : "操作",
    "createAuthorize" : "委託の新規作成"
};
