MWF.xApplication.Profile.LP = {
	"title": "개인 설정",
    "inforConfig": "개인 정보",
    "layoutConfig": "인터페이스 설정",
    "ideaConfig": "자주 사용하는 의견",
    "passwordConfig": "비밀번호 변경",
    "ssoConfig": "싱글 사인온",
    "facelogin": "얼굴로 로그인",
    "openFaceSet": "여기를 클릭하여 얼굴 로그인 설정 열기",

    "clear": "인터페이스 데이터 지우기",
    "setDefault": "기본 인터페이스로 설정",
    "clearDefault": "기본 인터페이스 지우기",
    "setForce": "앱 강제 실행으로 설정",
    "clearForce": "앱 강제 실행 지우기",
    "setDefaultOk": "기본 인터페이스로 설정되었습니다",
    "setForceOk": "앱 강제 실행으로 설정되었습니다",
    "clearok": "데스크톱 캐시 레코드가 지워졌습니다",
    "saveIdea": "일반 의견 저장",
    "saveIdeaDefault": "기본 일반 의견으로 저장",
    "ideaSaveOk": "일반 의견 저장이 완료되었습니다",
    "workDeletedNote": "작업 \"{title}\"이(가) 삭제되었거나 열 권한이 없습니다.",
    "workDeletedTitle": "작업을 찾을 수 없음",
    "workDeletedContent": "작업 \"{title}\"이(가) 삭제되었거나 열 권한이 없습니다. 이 권한 기록을 삭제하시겠습니까?",
    "deleteSuccess": "삭제 완료",

    "icon": "아이콘",
    "changeIcon": "아이콘 변경",
    "name": "이름",
    "employee": "직원 번호",
    "display": "닉네임",
    "officePhone": "사무실 전화",
    "mail": "이메일 주소",
    "mobile": "휴대전화 번호",
    "weixin": "위챗 ID",
    "QQ": "QQ",
    "signature": "개인 서명",
    "saveInfor": "개인 정보 저장",
    "saveInforOk": "개인 정보 저장 완료",
    "nickNameInforError": "닉네임 형식이 올바르지 않습니다. 규칙은 다음과 같습니다: 한글, 숫자, 영문, _, -, 공백만 사용 가능하며, 길이는 4에서 20자여야 합니다. 한글 한 글자는 2자로 계산합니다.",
    "ipAddress" : "로그인 IP",
    "ipAddressPlaceHolder" : "비어 있지 않으면 일치하는 IP 주소만 로그인할 수 있으며, 여러 값을 쉼표로 구분합니다.",
    "ipAddressIncorrectNotice" : "IP 주소 형식이 올바르지 않습니다:",
    "language": "언어 설정",
    "forumNickName": "포럼 닉네임",
    "lps": {
        "zh-CN": "简体中文",
        "en": "English",
		"es": "español",
		"ko":"한국어",
		"ja":"日本語",
		"zh-hk":"繁體中文"
    },

    "passwordRule" : "암호 규칙",
    "oldPassword": "기존 암호",
    "password": "새 암호",
    "morePassword": "암호 확인",
    "passwordNotMatch": "새 암호와 확인 암호가 일치하지 않습니다",
    "changePasswordOk": "암호가 성공적으로 변경되었습니다",

    "changePersonIcon": "프로필 사진 변경",

    "layoutAction": "인터페이스 조작",
    "desktopBackground": "데스크톱 배경",
    "paswordRule" : "6자 이상, 숫자와 문자를 포함해야 합니다.",
    "weak" : "약함",
    "middle" : "보통",
    "high" : "강함",

    "bindOauth": "Oauth 계정 바인딩",
    "empower":{
        "fromPerson":"출처 인원",
        "fromIdentity":"출처 신분",
        "toPerson":"위임 인원",
        "toIdentity":"위임 신분",
        "application":"애플리케이션",
        "applicationName":"애플리케이션 이름",
        "applicationAlias":"애플리케이션 별칭",
        "process":"프로세스 ID",
        "processName":"프로세스 이름",
        "processAlias":"프로세스 별칭",
        "type":"인가 유형",
        "startTime":"인가 시작 시간",
        "completedTime":"인가 완료 시간",
        "emPowerConfig": "외출 인가",
        "addEmPower": "추가",
        "myEmPower": "내 위임",
        "receiveEmPower": "받은 위임",
        "ok":"저장",
        "cancel":"닫기",
        "noData":"현재 위임이 없습니다",
        "withdraw":"취소",
        "alert1":"프로세스 또는 애플리케이션을 선택하세요",
        "alert2":"관리자에게 신분 정보를 추가하도록 문의하세요!",
        "withdrawOk":"위임 취소 완료",
        "selectEmPower":"위임을 선택하세요",
        "saveOk":"저장 완료",
        "type_all":"모두",
        "type_application":"애플리케이션",
        "type_process":"프로세스",
        "type_filter":"파일 유형",
        "saveNotAll":"일부 저장 실패",
        "startTimeEarlyCompleteTime": "시작 시간은 완료 시간보다 빨라야 합니다",
        "title":"제목",
        "activityName":"상태",
        "createTime":"위임 시간",
        "edit":"편집",
        "editEmpower":"외출 인가 편집",
        "enable":"사용",
        "disable":"비활성화"
    },

    "emPowerConfig": "외출 인가",
    "addEmPower": "추가",
    "myEmPower": "내 위임",
    "receiveEmPower": "받은 위임",
    "myEmPowerLog": "위임 대기 중",
    "receiveEmPowerLog": "받은 대기 중",
    "ok":"저장",
    "cancel":"닫기",
    "pageText" : "{n} 페이지",
    "search" : "검색",
    "cancel1" : "취소",
    "createEmpower" : "외출 인가 생성",
    "noTask" : "대기 중인 작업 없음",
    "action" : "조작",
    "createAuthorize" : "위임 생성"
};
