MWF.xApplication.Profile.LP = {
    "title": "ຕັ້ງຄ່າສ່ວນຕົວ",
    "inforConfig": "ຂໍ້ມູນສ່ວນຕົວ",
    "layoutConfig": "ກຳນົດຄ່າໂຕ້ຕອບ",
    "ideaConfig": "ຄວມຄິດເຫັນ",
    "passwordConfig": "ແກ້ໄຂລະຫັດ",
    "ssoConfig": "ເຂົ້າສູ່ລະບົບ",
    "facelogin": "ເຂົ້າສູ່ລະບົບດດ້ວຍໃບໜ້າ",
    "openFaceSet": "ກົດທີ່ນີ້，ເພື່ອເປີດກນເຂົ້າສູ່ລະບົບດ້ວຍໃບໜ້າ",

    "clear": "ລົບຂໍ້ມູນການໂຕ້ຕອບ",
    "setDefault": "ຕັ້ງຄ່າການໂຕ້ຕອບເລີ່ມຕົ້ນ",
    "clearDefault": "ລ້າງຂໍ້ມູນກໂຕ້ຕອບ",
    "setForce": "ຕັ້ງຄ່າບັງຄັບການເປີດແອັບ",
    "clearForce": "ລົບລ້າງການຕັ້ງຄ່າບັງຄັບເປີດແອັບ",
    "setDefaultOk": "ຕັ້ງຄ່າການໂຕ້ຕອບເລີ່ມຕົ້ນແລ້ວ",
    "setForceOk": "ຕັ້ງຄ່າບັງຄັບການເປີດແອັບແລ້ວ",
    "clearok": "ລ້າງປະຫັວດກນບັນທຶກ Desktop cache ແລ້ວ ",
    "saveIdea": "ບັນທຶກຄວາມຄິດເຫັນທີ່ໃຊ້ເລື່ອຍໆ",
    "saveIdeaDefault": "ບັນທຶກຄວາມຄິດເຫັນທົ່ວໄປ",
    "ideaSaveOk": "ບັນທຶກຄວາມຄິດເຫັນທີ່ໃຊ້ເລື່ອຍໆສຳເລັດ",
    "workDeletedNote": "ວຽກ\"{title}\"ຖືກລົບໄປແລ້ວ ຫຼື ເຈົ້າບໍ່ໄດ້ຮັບອະນຸຍາດໃຫ້ເປີດ。",
    "workDeletedTitle": "ບໍ່ພົບວຽກ",
    "workDeletedContent": "ວຽກ\"{title}\"ຖືກລົບໄປແລ້ວ ຫຼື ເຈົ້າບໍ່ໄດ້ຮັບອະນຸຍາດໃຫ້ເປີດ。ຕ້ອງການລົບບັນທຶກການອະນຸຍາດ ແມ່ນຫຼື ບໍ？",
    "deleteSuccess": "ລົບສຳເລັດ",

    "icon": "icon",
    "changeIcon": "ປ່ຽນ icon",
    "name": "ຊື່",
    "employee": "ລະຫັດພະນັກງານ",
    "display": "ຊື້ຫຼິ້ນ",
    "officePhone": "ເບີໂທຫ້ອງການ",
    "mail": "mail",
    "mobile": "ເບີໂທລະສັບ",
    "weixin": "Wechat ID",
    "QQ": "QQ",
    "signature": "ລາຍເຊັ່ນ",
    "saveInfor": "ບັນທຶກຂໍ້ມູນສ່ວນຕົວ",
    "saveInforOk": "ບັນທຶກຂໍ້ມູນສ່ວນຕົວສຳເລັດ",
    "nickNameInforError": "ຮູບແບບຊື່ຫຼີ້ນບໍ່ຖືກຕ້ອງ，ມີກົດດັ່ງນີ້：ໃຊ້ສະເພາະພາສາຈີນ、ຕົວເລກ、ພາສາອັງກິດ、_、-ແລະເວັ້ນວ່າງ，ຄວາມຍາວ4ເຖິງ20，ຄວາມຍາວຂອງຕົວອັກສອນຈີນແມ່ນ2",
    "ipAddress": "ໜ້າຫຼັກ IP",
    "ipAddressPlaceHolder": "ຖ້າບໍ່ເວັ້ວ່າງ， ip ທີ່ຕົງກັນເທົ່ານັ້ນຈຶ່ງສາມາດເຂົ້າສູ່ລະບົບໄດ້，ໃຊ້,ແຍກຫຼາຍຄ່າ",
    "ipAddressIncorrectNotice": "ທີ່ຢູ່ IP ບໍ່ຖືກຕ້ອງ：",
    "language": "ຕັ້ງຄ່າພາສາ",
    "forumNickName": "ຊື່ຫຼິ້ນforum ",
    "lps": {
        "zh-CN": "简体中文",
        "en": "English",
        "es": "español",
        "la": "ພາສາລາວ"
    },

    "passwordRule": "ກົດລະບຽບລະຫັດ",
    "oldPassword": "ລະຫັດເກົ່າ",
    "password": "ລະຫັດໃໝ່",
    "morePassword": "ຢືນຢັນລະຫັດ",
    "passwordNotMatch": "ລະຫັດໃໝ່ແລະຢືນຢັນລະຫົດບໍ່ຕົງກັນ",
    "changePasswordOk": "ປ່ຽນລະຫັດສຳເລັດ",

    "changePersonIcon": "ປ່ຽນ Icon ສ່ວນຕົວ",

    "layoutAction": "ການດຳເນີນການໂຕ້ຕອບ",
    "desktopBackground": "ພື້ນຫຼັງ desktop",
    "paswordRule": "6ຕົວຂຶ້ນໄປ,ປະກອບຕົວຕົວເລກແລະຕົວອັກສອນ.",
    "weak": "weak",
    "middle": "ກາງ",
    "high": "ລວງສູງ",

    "bindOauth": "ຜູກມັດ Oauth ເລກບັນຊີ",
    "empower": {
        "fromPerson": "ພະນັກງານ",
        "fromIdentity": "ຕົວຕົນ",
        "toPerson": "ພະນັກງານຖືກມອບສິດ",
        "toIdentity": "ຕົວຕົນໄດ້ຮັບຫານມອບໝາຍ",
        "application": "ແອັບພິເຄຊັ້ນ",
        "applicationName": "ຊື່ແອັບພິເຄຊັ້ນ",
        "applicationAlias": "ນາມແຟງແອັບພິເຄຊັ້ນ",
        "process": "ຂະບານການID",
        "processName": "ຊື່ຂະບວນການ",
        "processAlias": "ຊື່ນາມແຟງແອັບພິເຄຊັ້ນ",
        "type": "ປະເພດມອບສິດ",
        "startTime": "ມອບສິດເລີ່ມເວລາ",
        "completedTime": "ມອບສິດສິ້ນສຸດເວລາ",
        "emPowerConfig": "ໃຫ້ອຳນາດ",
        "addEmPower": "ສ້າງໃໝ່",
        "myEmPower": "ມອບໝາຍຂອງຂ້ອຍ",
        "receiveEmPower": "ໄດ້ຮັບສິ່ງທີ່ຕ້ອງເຮັດ",
        "ok": "ບັນທຶກ",
        "cancel": "ຍົກເລີກ",
        "noData": "ຍັງບໍ່ມີຄ່ານາຍໜ້າ",
        "withdraw": "ຖອນ",
        "alert1": "ກະລຸນາເລືອກຂະບວນການ ຫຼື ແອັບພິເຄຊັ່ນ",
        "alert2": "ກະລຸນາຕິດຕໍ່ຜູ້ດູແລເພື່ອເພີ່ມຂໍ້ມູນປະຈຳຕົວ！",
        "withdrawOk": "ຖອນການມອບໝາຍສຳເລັດ",
        "selectEmPower": "ກະລຸນາເລືອກມອບໃຫ້ເຮັດແທນ",
        "saveOk": "ບັທຶກສຳເລັດ",
        "type_all": "ທັງໝົດ",
        "type_application": "Application",
        "type_process": "ຂະບວນການ",
        "type_filter": "ເອກະສານປະເພດ",
        "saveNotAll": "ບັນທຶກບາງຢ່າງລົ້ມເລວ",
        "startTimeEarlyCompleteTime": "ເວລາເລີ່ມຕ້ອງບໍ່ຊ້າກວ່າເວລາສິ້ນສຸດ",
        "title": "ຫົວຂໍ້",
        "activityName": "ສະຖານະ",
        "createTime": "ເວລາມອບສິດ",
        "edit": "ແກ້ໄຂ",
        "editEmpower": "ແກ້ໄຂການມອບສິດ",
        "enable": "ເປີດໃຊ້ງານ",
        "disable": "ປິດໃຊ້ງານ"
    },

    "emPowerConfig": "ໃຫ້ອຳນາດ",
    "addEmPower": "ສ້າງໃໝ່",
    "myEmPower": "ມອບໝາຍຂອງຂ້ອຍ",
    "receiveEmPower": "ໄດ້ຮັບການມອບໝາຍ",
    "myEmPowerLog": "ສິ່ງທີ່ຕ້ອງເຮັດ",
    "receiveEmPowerLog": "ໄດ້ຮັບສິ່ງທີ່ຕ້ອງເຮັດ",
    "ok": "ບັນທຶກ",
    "cancel": "ຍົກເລີກ",
    "pageText": "ໜ້າທີ{n}",
    "search": "ຄົ້ນຫາ",
    "cancel1": "ຍົກເລີກ",
    "createEmpower": "ສ້າງມອບອຳນາດ",
    "noTask": "ບໍ່ມີສິ່ງທີ່ຕ້ອງເຮັດ",
    "action": "ດຳເນີນການ",
    "createAuthorize": "ສ້າງມອບໝາຍໃຫ້ເຮັດແທນ"
};
