MWF.xApplication.Profile.LP = {
	"title": "個人設置",
    "inforConfig": "個人信息",
    "layoutConfig": "界面配置",
    "ideaConfig": "常用意見",
    "passwordConfig": "修改密碼",
    "ssoConfig": "單點登錄",
    "facelogin": "人臉登錄",
    "openFaceSet": "點擊此處，打開人臉登錄設置",

    "clear": "清除界面數據",
    "setDefault": "設置為默認界面",
    "clearDefault": "清除默認界面",
    "setForce": "設置強制打開應用",
    "clearForce": "清除強制打開應用",
    "setDefaultOk": "已設置為默認界面",
    "setForceOk": "已設置強制打開應用",
    "clearok": "桌面緩存記錄已清除",
    "saveIdea": "保存常用意見",
    "saveIdeaDefault": "保存為默認常用意見",
    "ideaSaveOk": "常用意見保存完成",
    "workDeletedNote": "工作\"{title}\"已經被刪除或您沒有權限打開。",
    "workDeletedTitle": "未找到工作",
    "workDeletedContent": "工作\"{title}\"已經被刪除或您沒有權限打開。是否要刪除這條授權記錄？",
    "deleteSuccess": "刪除成功",

    "icon": "頭像",
    "changeIcon": "更換頭像",
    "name": "姓名",
    "employee": "工號",
    "display": "暱稱",
    "officePhone": "辦公電話",
    "mail": "郵件地址",
    "mobile": "手機號碼",
    "weixin": "微信號",
    "QQ": "QQ",
    "signature": "個人簽名",
    "saveInfor": "保存個人信息",
    "saveInforOk": "保存個人信息成功",
    "nickNameInforError": "暱稱格式不正確，規則如下：只能使用中文、數字、英文、_、-和空格，長度應為4到20，一個中文字符長度為2",
    "ipAddress" : "登錄IP",
    "ipAddressPlaceHolder" : "如果不為空，僅匹配的IP地址可以登錄，多個值用逗號分隔",
    "ipAddressIncorrectNotice" : "IP地址格式不正確：",
    "language": "語言設置",
    "forumNickName": "論壇暱稱",
    "lps": {
        "zh-CN": "简体中文",
        "en": "English",
		"es": "español",
		"ko":"한국어",
		"ja":"日本語",
		"zh-hk":"繁體中文"
    },

    "passwordRule" : "密碼規則",
    "oldPassword": "舊密碼",
    "password": "新密碼",
    "morePassword": "確認密碼",
    "passwordNotMatch": "新密碼與確認密碼不一致",
    "changePasswordOk": "密碼修改成功",

    "changePersonIcon": "修改個人頭像",

    "layoutAction": "界面操作",
    "desktopBackground": "桌面背景",
    "paswordRule" : "6位以上，包含數字和字母。",
    "weak" : "弱",
    "middle" : "中",
    "high" : "強",

    "bindOauth": "綁定Oauth帳號",
    "empower":{
        "fromPerson":"來源人員",
        "fromIdentity":"來源身份",
        "toPerson":"委託人員",
        "toIdentity":"委託身份",
        "application":"應用程式",
        "applicationName":"應用程式名稱",
        "applicationAlias":"應用程式別名",
        "process":"流程ID",
        "processName":"流程名稱",
        "processAlias":"流程別名",
        "type":"授權類型",
        "startTime":"授權開始時間",
        "completedTime":"授權結束時間",
        "emPowerConfig": "外出授權",
        "addEmPower": "新增",
        "myEmPower": "我的委託",
        "receiveEmPower": "收到的委託",
        "ok":"保存",
        "cancel":"關閉",
        "noData":"暫時沒有委託",
        "withdraw":"撤回",
        "alert1":"請選擇流程或應用程式",
        "alert2":"請聯絡管理員添加身份資訊！",
        "withdrawOk":"委託已成功撤回",
        "selectEmPower":"請選擇委託",
        "saveOk":"保存成功",
        "type_all":"全部",
        "type_application":"應用程式",
        "type_process":"流程",
        "type_filter":"文件類型",
        "saveNotAll":"部分保存失敗",
        "startTimeEarlyCompleteTime": "開始時間不能晚於結束時間",
        "title":"標題",
        "activityName":"狀態",
        "createTime":"委託時間",
        "edit":"編輯",
        "editEmpower":"編輯外出授權",
        "enable":"啟用",
        "disable":"禁用"
    },

    "emPowerConfig": "外出授權",
    "addEmPower": "新增",
    "myEmPower": "我的委託",
    "receiveEmPower": "收到的委託",
    "myEmPowerLog": "委託的待辦",
    "receiveEmPowerLog": "收到的待辦",
    "ok":"保存",
    "cancel":"關閉",
    "pageText" : "第{n}頁",
    "search" : "搜索",
    "cancel1" : "取消",
    "createEmpower" : "新建外出授權",
    "noTask" : "無待辦",
    "action" : "操作",
    "createAuthorize" : "新建委託"
};
