/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.strategydeploy.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.strategydeploy.core.entity.Attachment.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:20 CST 2018")
public class Attachment_ extends StorageObject_  {
    public static volatile SingularAttribute<Attachment,String> extension;
    public static volatile SingularAttribute<Attachment,String> id;
    public static volatile SingularAttribute<Attachment,Date> lastUpdateTime;
    public static volatile SingularAttribute<Attachment,Long> length;
    public static volatile SingularAttribute<Attachment,String> name;
    public static volatile SingularAttribute<Attachment,String> person;
    public static volatile SingularAttribute<Attachment,String> site;
    public static volatile SingularAttribute<Attachment,String> storage;
    public static volatile SingularAttribute<Attachment,String> workyear;
}
