/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.strategydeploy.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.strategydeploy.core.entity.Keywork_Measures_Relation.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:20 CST 2018")
public class Keywork_Measures_Relation_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Keywork_Measures_Relation,String> id;
    public static volatile SingularAttribute<Keywork_Measures_Relation,String> keyworkid;
    public static volatile SingularAttribute<Keywork_Measures_Relation,String> keyworktitle;
    public static volatile SingularAttribute<Keywork_Measures_Relation,String> measuresinfoid;
    public static volatile SingularAttribute<Keywork_Measures_Relation,String> measuresinfotitle;
    public static volatile SingularAttribute<Keywork_Measures_Relation,String> strategydeployid;
    public static volatile SingularAttribute<Keywork_Measures_Relation,String> strategydeploytitle;
}
