/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.strategydeploy.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.strategydeploy.core.entity.StrategyDeploy.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:20 CST 2018")
public class StrategyDeploy_ extends SliceJpaObject_  {
    public static volatile ListAttribute<StrategyDeploy,String> deptlist;
    public static volatile SingularAttribute<StrategyDeploy,String> id;
    public static volatile SingularAttribute<StrategyDeploy,Integer> sequencenumber;
    public static volatile SingularAttribute<StrategyDeploy,String> status;
    public static volatile SingularAttribute<StrategyDeploy,String> strategydeployconfiglevel;
    public static volatile SingularAttribute<StrategyDeploy,String> strategydeploycreator;
    public static volatile SingularAttribute<StrategyDeploy,String> strategydeploydescribe;
    public static volatile SingularAttribute<StrategyDeploy,String> strategydeploytitle;
    public static volatile SingularAttribute<StrategyDeploy,String> strategydeployunit;
    public static volatile SingularAttribute<StrategyDeploy,String> strategydeployyear;
}
