MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.IMV2 = MWF.xApplication.IMV2 || {};
MWF.xApplication.IMV2.LP={
	"title": "Chat",
	"modifyMember": "Members",
	"noMessage": "No Message!",
	"createConversation": "Create a chat session",
	"createSingle": "Single Chat",
	"createGroup": "Group Chat",
	"sendSuccess": "Message sent successfully!",
	"minutesBefore": " Minutes Before",
	"hoursBefore": " Hours Before",
	"yesterday": "Yesterday",
	"beforeYesterday": "Before Yesterday ",
	"daysBefore": " Days Before",
	"monthAgo": "One Month Ago",
	"towMonthAgo": "Tow Month Ago",
	"threeMonthAgo": "Three Month Ago",
	"selectPerson": "Person",
	"ok": "OK",
	"close": "Close",
	"alert": "Tips",
	"setting": "Setting",
	"chooseConversation": "Select Conversation",
	"chooseConversationExistConversation": "Currently there is an associated chat conversation:",
	"chooseConversationCreateNew": "Create a new chat",
	"choosePerson": "Select personnel",
	"choosePersonCreate": "Create chat",
	"chooseConveration": "Select Converation",
	"conversationCreate": "Create a new chat",
	"chooseBusinessWorkTitle": "Associated work",
	"open": "open",
	"noTitle": "Untitled",
	"openGroupInfo": "Group information",
	"groupMember": "Group members",
	"groupMemberAdmin": "Group administrator",
	"modifyGroupName": "Modify Name",
	"groupName": "Name",
	"deleteConversation": "Delete Conversation",
	"msgMenuItemRevokeMemberMsg": "Revoke member message",
	"msgMenuItemRevokeMsg": "Revoke",
	"msgLoadNoMoreData": "No more data!",
	"msgNoBusinessId": "No business ID!",
	"msgNoBusinessPerson": "No business related personnel found, unable to create chat!",
	"msgNotSupport": "Temporarily not supported!",
	"msgNeedChoosePerson": "Please select at least one person!",
	"msgShareNoBody": "No message was obtained, unable to share and forward!",
	"msgShareError": "Failed to share and forward messages!",
	"settingsClearMsg": " Enable Clearing msg",
	"settingsRevokeMsg": " Enable Revoke msg",
	"settingsRevokeOutMinuteMsg": "Withdrawal time limit (minutes)",
	"enterMessage": "Enter message content",
	"send": "Send",
	"sendKeyTips": "Ctrl + Enter Line feed",
	"file": "[File]",
	"messageXadminNotSupport": "The xadmin cannot use chat, please switch to normal user login!",
	"messageDeleteSingleConversationAlert": "确定要删除当前会话吗，删除后将看不到以前的聊天记录？",
	"messageDeleteGroupConversationAlert": "确定要删除当前会话吗，这会解散当前群聊并删除聊天记录？"
}
MWF.xApplication.IMV2["lp."+o2.language] = MWF.xApplication.IMV2.LP