MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.IMV2 = MWF.xApplication.IMV2 || {};
MWF.xApplication.IMV2.LP={
	"title": "Chat",
	"modifyMember": "Modificar miembros",
	"noMessage": "¡No hay contenido de mensajes!",
	"createConversation": "Crear conversación",
	"createSingle": "Individual",
	"createGroup": "Grupal",
	"sendSuccess": "¡Mensaje enviado correctamente!",
	"minutesBefore": "hace minutos",
	"hoursBefore": "hace horas",
	"yesterday": "Ayer",
	"beforeYesterday": "Anteayer",
	"daysBefore": "días antes",
	"monthAgo": "hace un mes",
	"towMonthAgo": "hace dos meses",
	"threeMonthAgo": "hace tres meses",
	"selectPerson": "Personas",
	"ok": "Aceptar",
	"close": "Cerrar",
	"alert": "Alerta",
	"setting": "Configuraciones",
	"chooseConversation": "Seleccionar conversación",
	"chooseConversationExistConversation": "Ya existe una conversación relacionada:",
	"chooseConversationCreateNew": "Crear nueva conversación",
	"choosePerson": "Seleccionar personas",
	"choosePersonCreate": "Crear conversación",
	"chooseConveration": "Seleccionar conversación",
	"conversationCreate": "Crear nueva conversación",
	"chooseBusinessWorkTitle": "Relacionar trabajo",
	"open": "Abrir",
	"noTitle": "Sin título",
	"openGroupInfo": "Información del Grupo",
	"groupMember": "Miembros del Grupo",
	"groupMemberAdmin": "Administrador del Grupo",
	"modifyGroupName": "Modificar nombre de grupo",
	"groupName": "Nombre",
	"deleteConversation": "Eliminar conversación",
	"msgMenuItemRevokeMemberMsg": "Revocar mensaje del miembro",
	"msgMenuItemRevokeMsg": "Revocar",
	"msgLoadNoMoreData": "¡No hay más datos!",
	"msgNoBusinessId": "¡Sin ID de trabajo!",
	"msgNoBusinessPerson": "¡No se encontró a nadie relacionado con el trabajo para crear una conversación!",
	"msgNotSupport": "No soportado por ahora.",
	"msgNeedChoosePerson": "Por favor, seleccione al menos una persona.",
	"msgShareNoBody": "¡No se ha obtenido ningún mensaje para compartir o reenviar!",
	"msgShareError": "¡Fallo en compartir o reenviar mensaje!",
	"settingsClearMsg": "¿Habilitar la función de eliminación de conversaciones?",
	"settingsRevokeMsg": "¿Habilitar la función de revocación de mensajes?",
	"settingsRevokeOutMinuteMsg": "撤回时效(分钟数)",
	"enterMessage": "Ingrese el contenido del mensaje",
	"send": "Enviar",
	"sendKeyTips": "Ctrl + Enter para cambiar de línea",
	"file": "[Archivo]",
	"messageXadminNotSupport": "Los usuarios de xadmin no pueden usar Chat, ¡por favor cambie a un usuario normal para iniciar sesión!",
	"messageDeleteSingleConversationAlert": "¿Está seguro de que desea eliminar esta conversación y perder todos los registros de chat relacionados?",
	"messageDeleteGroupConversationAlert": "¿Está seguro de que desea eliminar esta conversación grupal, disolviendo el grupo y perdiendo todos los registros de chat relacionados?"
}
MWF.xApplication.IMV2["lp."+o2.language] = MWF.xApplication.IMV2.LP