MWF.xApplication.IMV2.LP = {
	"title": "チャット",
	"modifyMember": "メンバーの変更",
	"noMessage": "メッセージがありません！",
	"createConversation": "チャット会話の作成",
	"createSingle": "1対1",
	"createGroup": "グループ",
	"sendSuccess": "メッセージの送信に成功しました！",
	"minutesBefore": "分前",
	"hoursBefore": "時間前",
	"yesterday": "昨日",
	"beforeYesterday": "一昨日",
	"daysBefore": "日前",
	"monthAgo": "1か月前",
	"towMonthAgo": "2か月前",
	"threeMonthAgo": "3か月前",
	"selectPerson": "人を選択",
	"ok": "OK",
	"close": "閉じる",
	"alert": "アラート",
	"setting": "設定",
	"chooseConversation": "チャット選択",
	"chooseConversationExistConversation": "現在、関連するチャット会話が既に存在します：",
	"chooseConversationCreateNew": "新しいチャットを作成",
	"choosePerson": "人を選択",
	"choosePersonCreate": "チャットの作成",


	"chooseConveration": "チャット選択",
	"conversationCreate": "新しいチャットを作成",
	"chooseBusinessWorkTitle": "関連する作業",
	"open": "開く",
	"noTitle": "タイトルなし",
	"modifyGroupName": "グループ名を変更",
	"groupName": "グループ名",
	"deleteConversation": "会話を削除",
	"msgMenuItemRevokeMemberMsg": "メンバーメッセージを取り消す",
	"msgMenuItemRevokeMsg": "取り消す",
	"msgLoadNoMoreData": "もうデータがありません！",
	"msgNoBusinessId": "ビジネスIDがありません！",
	"msgNoBusinessPerson": "ビジネス関連の人物を検索できないため、チャットを作成できません！",
	"msgNotSupport": "現在サポートしていません！",
	"msgNeedChoosePerson": "少なくとも1人を選択してください！",
	"msgShareNoBody": "メッセージが取得できないため、共有または転送できません！",
	"msgShareError": "メッセージの共有、転送に失敗しました！",
	"settingsClearMsg": " 会話削除機能を有効にしますか？",
	"settingsRevokeMsg": " チャットメッセージ取り消し機能を有効にしますか？",
	"enterMessage": "メッセージを入力",
	"send": "送信",
	"sendKeyTips": "Ctrl + Enterで改行",
	"file": "[ファイル]",
	"messageXadminNotSupport": "xadminユーザーはチャットを使用できません。通常のユーザーに切り替えてログインしてください！",
	"messageDeleteSingleConversationAlert": "現在の会話を削除してもよろしいですか？削除すると、以前のチャット記録は表示されなくなります。",
	"messageDeleteGroupConversationAlert": "現在の会話を削除してもよろしいですか？これにより、現在のグループチャットが解散され、チャット記録が削除されます。"
};
