MWF.xApplication.IMV2.LP = {
	"title": "대화",
	"modifyMember": "멤버 수정",
	"noMessage": "메시지가 없습니다!",
	"createConversation": "대화 세션 생성",
	"createSingle": "1:1 대화",
	"createGroup": "그룹 대화",
	"sendSuccess": "메시지 전송 성공!",
	"minutesBefore": "분 전",
	"hoursBefore": "시간 전",
	"yesterday": "어제",
	"beforeYesterday": "그제",
	"daysBefore": "일 전",
	"monthAgo": "한 달 전",
	"towMonthAgo": "2달 전",
	"threeMonthAgo": "3달 전",
	"selectPerson": "인원 선택",
	"ok": "확인",
	"close": "닫기",
	"alert": "알림",
	"setting": "설정",
	"chooseConversation": "대화 선택",
	"chooseConversationExistConversation": "이미 연결된 대화 세션이 있습니다:",
	"chooseConversationCreateNew": "새로운 대화 생성",
	"choosePerson": "인원 선택",
	"choosePersonCreate": "대화 생성",


	"chooseConveration": "대화 선택",
	"conversationCreate": "새로운 채팅 생성",
	"chooseBusinessWorkTitle": "관련 작업",
	"open": "열기",
	"noTitle": "제목 없음",
	"modifyGroupName": "그룹 이름 수정",
	"groupName": "그룹 이름",
	"deleteConversation": "대화 삭제",
	"msgMenuItemRevokeMemberMsg": "멤버 메시지 취소",
	"msgMenuItemRevokeMsg": "취소",
	"msgLoadNoMoreData": "데이터가 더 이상 없습니다!",
	"msgNoBusinessId": "비즈니스 ID가 없습니다!",
	"msgNoBusinessPerson": "비즈니스 관련 인원을 조회할 수 없으므로 채팅을 생성할 수 없습니다!",
	"msgNotSupport": "현재 지원하지 않습니다!",
	"msgNeedChoosePerson": "적어도 한 명의 인원을 선택해주세요!",
	"msgShareNoBody": "메시지를 가져오지 못했으므로 공유 또는 전달할 수 없습니다!",
	"msgShareError": "메시지 공유 또는 전달에 실패했습니다!",
	"settingsClearMsg": "대화 삭제 기능을 활성화하시겠습니까?",
	"settingsRevokeMsg": "채팅 메시지 취소 기능을 활성화하시겠습니까?",
	"enterMessage": "메시지 입력",
	"send": "보내기",
	"sendKeyTips": "Ctrl + Enter로 줄 바꿈",
	"file": "[파일]",
	"messageXadminNotSupport": "Xadmin 사용자는 채팅을 사용할 수 없습니다. 정상 사용자로 전환하여 로그인하십시오!",
	"messageDeleteSingleConversationAlert": "현재 대화를 삭제하시겠습니까? 삭제하면 이전 대화 기록을 볼 수 없게 됩니다.",
	"messageDeleteGroupConversationAlert": "현재 대화를 삭제하시겠습니까? 이로써 현재 그룹 채팅이 해체되고 대화 기록이 삭제됩니다."
};
