MWF.xApplication.IMV2.LP = {
	"title": "聊天",
	"modifyMember": "修改成員",
	"noMessage": "沒有消息內容！",
	"createConversation": "建立對話",
	"createSingle": "建立單聊",
	"createGroup": "建立群聊",
	"sendSuccess": "消息發送成功！",
	"minutesBefore": "分鐘前",
	"hoursBefore": "小時前",
	"yesterday": "昨天",
	"beforeYesterday": "前天",
	"daysBefore": "天前",
	"monthAgo": "一個月前",
	"towMonthAgo": "2個月前",
	"threeMonthAgo": "3個月前",
	"selectPerson": "選擇人員",
	"ok": "確定",
	"close": "關閉",
	"alert": "提示",
	"setting": "設定",
	"chooseConversation": "選擇對話",
	"chooseConversationExistConversation": "當前已存在關聯的聊天對話：",
	"chooseConversationCreateNew": "創建新的聊天",
	"choosePerson": "選擇人員",
	"choosePersonCreate": "創建聊天",


	"chooseConveration": "選擇對話",
	"conversationCreate": "創建新的聊天",
	"chooseBusinessWorkTitle": "相關工作",
	"open": "打開",
	"noTitle": "無標題",
	"modifyGroupName": "修改群名",
	"groupName": "群名",
	"deleteConversation": "刪除對話",
	"msgMenuItemRevokeMemberMsg": "撤回成員消息",
	"msgMenuItemRevokeMsg": "撤回",
	"msgLoadNoMoreData": "沒有更多數據了！",
	"msgNoBusinessId": "沒有業務ID！",
	"msgNoBusinessPerson": "沒有查詢到業務相關的人員，無法創建聊天！",
	"msgNotSupport": "暫不支持！",
	"msgNeedChoosePerson": "請選擇至少一位人員！",
	"msgShareNoBody": "沒有獲取到消息，無法分享、轉發！",
	"msgShareError": "分享、轉發消息失敗！",
	"settingsClearMsg": " 是否開啟對話刪除功能",
	"settingsRevokeMsg": " 是否開啟聊天消息撤回功能",
	"enterMessage": "輸入消息內容",
	"send": "發送",
	"sendKeyTips": "Ctrl + Enter 換行",
	"file": "[文件]",
	"messageXadminNotSupport": "xadmin用戶無法使用聊聊，請切換正常的用戶登錄！",
	"messageDeleteSingleConversationAlert": "確定要刪除當前對話嗎，刪除後將看不到以前的聊天記錄？",
	"messageDeleteGroupConversationAlert": "確定要刪除當前對話嗎，這將解散當前群聊並刪除聊天記錄？"
};
