/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package o2.collect.core.entity.log;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=o2.collect.core.entity.log.AppLog.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat Aug 25 23:06:36 CST 2018")
public class AppLog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AppLog,String> androidManufacturer;
    public static volatile SingularAttribute<AppLog,String> centerContext;
    public static volatile SingularAttribute<AppLog,String> centerHost;
    public static volatile SingularAttribute<AppLog,Integer> centerPort;
    public static volatile SingularAttribute<AppLog,String> deviceToken;
    public static volatile SingularAttribute<AppLog,String> distinguishedName;
    public static volatile SingularAttribute<AppLog,String> id;
    public static volatile SingularAttribute<AppLog,String> logContent;
    public static volatile SingularAttribute<AppLog,Date> logDate;
    public static volatile SingularAttribute<AppLog,String> manufacturerOsVersion;
    public static volatile SingularAttribute<AppLog,String> mobile;
    public static volatile SingularAttribute<AppLog,String> name;
    public static volatile SingularAttribute<AppLog,String> o2Version;
    public static volatile SingularAttribute<AppLog,String> osCpu;
    public static volatile SingularAttribute<AppLog,String> osDpi;
    public static volatile SingularAttribute<AppLog,String> osMemory;
    public static volatile SingularAttribute<AppLog,String> osType;
    public static volatile SingularAttribute<AppLog,String> osVersion;
    public static volatile SingularAttribute<AppLog,String> unit;
    public static volatile SingularAttribute<AppLog,String> unitName;
}
