UPDATE PUBLIC.OKR_WORK_PERSON SET XRECORDTYPE = '中心工作' WHERE  XWORID is null;
UPDATE PUBLIC.OKR_WORK_PERSON SET XRECORDTYPE = '具体工作' WHERE  XRECORDTYPE is null;
UPDATE PUBLIC.OKR_CENTERWORKINFO SET XDEPLOYDATESTR = XCREATETIME;

--补充中心工作的信息
UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XCOMPLETEDATELIMIT = (SELECT B.XDEFAULTCOMPLETEDATELIMIT FROM   PUBLIC.OKR_CENTERWORKINFO B WHERE B.XID= A.XCENTERID)
WHERE  A.XRECORDTYPE = '中心工作';

UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XCOMPLETEDATELIMITSTR = (SELECT B.XDEFAULTCOMPLETEDATELIMITSTR FROM   PUBLIC.OKR_CENTERWORKINFO B WHERE B.XID= A.XCENTERID)
WHERE  A.XRECORDTYPE = '中心工作';

UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XDEPLOYDATESTR = ( SELECT B.XCREATETIME FROM  PUBLIC.OKR_CENTERWORKINFO B WHERE B.XID= A.XCENTERID )
WHERE  A.XRECORDTYPE = '中心工作';

UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XWORKCREATEDATESTR = ( SELECT B.XCREATETIME FROM  PUBLIC.OKR_CENTERWORKINFO B WHERE B.XID= A.XCENTERID )
WHERE  A.XRECORDTYPE = '中心工作';

--补充具体工作的信息
UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XCOMPLETEDATELIMIT = (SELECT B.XCOMPLETEDATELIMIT FROM   PUBLIC.OKR_WORKBASEINFO B WHERE B.XID= A.XWORKID)
WHERE  A.XRECORDTYPE = '具体工作';

UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XCOMPLETEDATELIMITSTR = (SELECT B.XCOMPLETEDATELIMITSTR FROM   PUBLIC.OKR_WORKBASEINFO B WHERE B.XID= A.XWORKID)
WHERE  A.XRECORDTYPE = '具体工作';

UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XDEPLOYDATESTR = (SELECT B.XDEPLOYDATESTR FROM   PUBLIC.OKR_WORKBASEINFO B WHERE B.XID= A.XWORKID)
WHERE  A.XRECORDTYPE = '具体工作';

UPDATE PUBLIC.OKR_WORK_PERSON A SET 
			  A.XWORKCREATEDATESTR = (SELECT B.XCREATETIME FROM   PUBLIC.OKR_WORKBASEINFO B WHERE B.XID= A.XWORKID)
WHERE  A.XRECORDTYPE = '具体工作';
























