/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.crm.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.crm.core.entity.Clue.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 19 17:55:09 CST 2018")
public class Clue_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Clue,String> address;
    public static volatile SingularAttribute<Clue,String> company;
    public static volatile SingularAttribute<Clue,String> contactway;
    public static volatile SingularAttribute<Clue,Date> createTime;
    public static volatile SingularAttribute<Clue,String> customerid;
    public static volatile SingularAttribute<Clue,String> department;
    public static volatile SingularAttribute<Clue,String> email;
    public static volatile SingularAttribute<Clue,String> id;
    public static volatile SingularAttribute<Clue,String> marketingeventid;
    public static volatile SingularAttribute<Clue,String> mobile;
    public static volatile SingularAttribute<Clue,String> position;
    public static volatile SingularAttribute<Clue,String> remark;
    public static volatile SingularAttribute<Clue,String> salescluename;
    public static volatile SingularAttribute<Clue,String> salescluepoolid;
    public static volatile SingularAttribute<Clue,String> sequence;
    public static volatile SingularAttribute<Clue,String> source;
    public static volatile SingularAttribute<Clue,String> state;
    public static volatile SingularAttribute<Clue,Date> updateTime;
    public static volatile SingularAttribute<Clue,String> url;
}
