/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.meeting.core.entity;

import com.x.base.core.entity.StorageObject_;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.meeting.core.entity.Attachment.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:09:29 CST 2017")
public class Attachment_ extends StorageObject_  {
    public static volatile SingularAttribute<Attachment,Date> createTime;
    public static volatile SingularAttribute<Attachment,String> extension;
    public static volatile SingularAttribute<Attachment,String> id;
    public static volatile SingularAttribute<Attachment,String> lastUpdatePerson;
    public static volatile SingularAttribute<Attachment,Date> lastUpdateTime;
    public static volatile SingularAttribute<Attachment,Long> length;
    public static volatile SingularAttribute<Attachment,String> meeting;
    public static volatile SingularAttribute<Attachment,String> name;
    public static volatile SingularAttribute<Attachment,String> sequence;
    public static volatile SingularAttribute<Attachment,String> storage;
    public static volatile SingularAttribute<Attachment,Boolean> summary;
    public static volatile SingularAttribute<Attachment,Date> updateTime;
}
