MWF.xApplication.Forum = MWF.xApplication.Forum || {};
MWF.xApplication.Forum.LP = {
	"title": "Forum Homepage",
	"delete": "Delete",
	"deleteDocumentTitle": "Delete Confirmation",
	"deleteDocument": "Are you sure you want to delete?",
	"deleteDocumentOK": "Delete successfully",
	"createSuccess": "Created successfully",
	"updateSuccess": "Update successful",
	"createReplySuccess": "Reply success",
	"inputName": "Please enter a name",
	"deleteAttachmentTitle": "Delete attachment confirmation",
	"deleteAttachment": "Are you sure you want to delete this attachment?",
	"search": "Search",
	"searchKey": "Please enter the search key",
	"searchTitle": "Keywords can be topics, divisions, sections, creators",
	"noSearchContentNotice": "Please enter the search keyword, and then perform the search",

	"dateFormatMonth": "%Y-%m",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%m-%d",
	"dateFormat": "db",
	"SelectOrgForm": "Personnel Organization Selection",

	"month": "month",
	"today": "today",
	"day": "Day",

	"cancel": "Cancel",
	"close": "Close",
	"ok": "OK",
	"edit": "Edit",
	"remove": "Remove",
	"action": "Action",

	"login": "Login",
	"signup": "Sign up",
	"logout": "Logout",

	"name": "Name",
	"create_cancel_title": "Cancel New Confirmation",
	"create_cancel": "Are you sure you want to cancel the new creation?",

	"systemSettingFormTitle": "System Settings",
	"configName": "Configuration Name",
	"configCode": "Configuration Code",
	"configValue": "Configuration Value",

	"categoryManager": "Manager",
	"setting": "Settings",
	"createCategory": "Create Partition",
	"createSection": "Create Section",
	"categoryFormTitle": "Partition Settings",
	"sectionFormTitle": "Section Setting",

	"baseSetting": "Basic Settings",
	"permissionSetting": "Permission Setting",


	"forumName": "Partition Name",
	"forumManagerName": "Partition Manager",
	"forumNotice": "Notice",
	"forumVisible": "Visible User",
	"forumVisibleButton": "Select a visible user",
	"allPerson": "Everyone",
	"byPermission": "ByPermission",
	"forumVisibleValue": "Everyone, according to permissions",
	"indexListStyle": "Homepage style list",
	"indexListStyleValue": "Classic, Simple rectangle, Picture rectangle",
	"indexListStyleButton": "Select Homepage Style",
	"selectIndexType": "Select Homepage Style",
	"all": "All",
	"all1": "All",
	"disable": "Disable",
	"typeColumn": "Number of columns per row",
	"indexListStyleImage": "Picture Rectangle",
	"forumIndexStyle": "Section Homepage Style",
	"forumIndexStyleValue": "Classic, News, Photo",
	"indexRecommendable": "Allow recommendation to the homepage",
	"subjectNeedAudit": "SubjectNeedAudit",
	"replyNeedAudit": "Reply needs to be reviewed",
	"sectionCreateAble": "Enable section creation",
	"sectionTotal": "Number of Sections",
	"subjectTotal": "Subject Total",
	"replyTotal": "Reply Quantity",
	"creatorName": "creator",
	"forumStatus": "Partition Status",
	"forumStatusValue": "Enable, Disable",
	"orderNumber": "Order Number",
	"yesOrNo": "Yes, No",
	"yes": "Yes",
	"owneForum": "Owning Partition",
	"createTime": "Create Time",
	"time": "Time",
	"create": "Create",
	"replyCount": "Reply",
	"auditPerson": "auditor",
	"forumColor": "Partition Color",
	"forumColorFormTitle": "Select section color",
	"defaultForumColor" : "#7e7e7e",
	"optionsForumColors" : [
		["#ff4040","#ff421e","#ffbf18","#e1e100","#00e100","#00e1ad","#00e0e0","#0082bf","#0080ff","#4181ff","#8242ff","#c140ff","#ff42f9","#ff40a0","#ff4070","#606060"],
		["#ff1f35","#ff1f10","#ff8100","#bfbf00","#00c200","#00c197","#00c1c2","#4181c0","#0062e1","#4141ff","#4200ff","#c200ff","#ff22ff","#f52b97","#ff2259","#5f5f5f"],
		["#e01f25","#e12000","#e26200","#a1a100","#00a000","#009f82","#3f8080","#0060a0","#0041c2","#0021bf","#4100c2","#8100ff","#ff00ff","#ff0080","#79656a","#4f4f4f"],
		["#c20000","#ff0000","#bf4100","#80803f","#3f803f","#008250","#006062","#004080","#001fe2","#0021bf","#4000a2","#6000a1","#e000e0","#df007f","#c20041","#3f3f3f"],
		["#a00000","#e10000","#a13f00","#626200","#006000","#00603c","#004041","#002f80","#0000ff","#2020a0","#2200a1","#400080","#a1009f","#c0007f","#9f000f","#2f2f2f"],
		["#600000","#c21212","#824200","#424200","#004200","#004023","#00323f","#002060","#0020c2","#2222c0","#000080","#1f007f","#800080","#820040","#800000","#1f1f1f"],
		["#400000","#a11f12","#604200","#212100","#002100","#00201f","#002041","#00204f","#0000e0","#0000a1","#000061","#1f0062","#40005f","#620042","#620012","#0f0f0f"]
	],
	"selectColor": "Select Color",
	"selectList": "Select List",
	"effect": "Effect",
	"column": "Column",
	"mainSection": "Main Section",
	"welcomeTitle": "{user}, hello!",
	"seePersonCenter": "Click to view personal center",
	"closeNavi": "Close the navigation",
	"navi": "Navigation",
	"naviLayout": "Navigation Layout",

	"sectionName": "Section Name",
	"mainSectionName": "Main Section Name",
	"sectionLevel": "Section Level",
	"sectionLevelValue": "Main section, subsection",
	"sectionDescription": "section description",
	"sectionNotice": "Notice",
	"sectionVisible": "Section Visible",
	"sectionVisibleValue": "Everyone, according to permissions",
	"replyVisible": "Reply to visible range",
	"replyVisibleValue": "Everyone, according to permissions",
	"subjectPublishAble": "Able to post range",
	"subjectPublishAbleValue": "Everyone, according to permissions",
	"replyPublishAble": "Able to reply range",
	"replyPublishAbleValue": "Everyone, according to permissions",
	"moderatorNames": "Manager",
	"sectionType": "Type",
	"sectionTypeValue": "Classic, photo news, general news, announcement",
	"subSectionCreateAble": "Allow the creation of subsections",
	"sectionStatus": "Status",
	"sectionStatusValue": "Enable, Disable",
	"sectionIcon": "Section Icon",
	"uploadIcon": "Upload local icon",
	"selectIcon": "Select Icon",
	"sectionIconFormTitle": "Select section icon",
	"indexRecommenPerson": "Recommended Person",

	"permissionFormTitle": "Permission Settings",
	"permissionType": "Permission Type",
	"permissionTypeValue": "Forum permissions, section permissions, other permissions",
	"permissionName": "permission name",
	"permissionCode": "Permission Code",
	"description": "Description",
	"create": "Create",

	"roleFormTitle": "Role Form",
	"createRole": "Create Role Setting",
	"roleType": "Role Type",
	"roleTypeValue": "Forum role, forum role",
	"roleName": "role name",
	"roleCode": "Role Code",
	"selectPerson": "Select Person",
	"selectDepartment": "Select Department",
	"selectCompany": "Select Company",

	"recommanded": "Recommended",
	"subject": "Subject",
	"allSubject": "All Subjects",
	"recommandedSubject": "Recommended Subject",
	"primeSubject": "prime subject",
	"type": "Type",
	"typeValue": "Discussion, voting, news, rewards, debate, irrigation, knowledge, dynamics",
	"subjectType": "Subject Type Option",
	"subjectTypeDefaultValue": "Discussion|News|News|Knowledge|Watering",
	"vote": "Vote",
	"typeCategoryDefaultValue": "Information|Question|Vote",
	"typeCatagory": "Theme Type Option",
	"typeCategorySelectValue": "Information|Question|Vote",
	"portalImage": "Homepage Image",
	"summary": "Summary",
	"content": "Content",
	"createSubject": "Post",
	"saveSubject": "Post",
	"selectCurrentDocumentFile": "Select Post Picture",
	"selectCloudFile": "Select Cloud File Picture",
	"insertUrl": "Insert Image Link",
	"voteLimitTime": "Time limit",
	"voteResultVisible": "Result is visible",
	"votePersonVisible": "Privacy",
	"votePersonValue": "Public, Anonymous",
	"voteOptions": "Options",
	"option": "Option",
	"opt": "Item",
	"voteCountLimit": "Choose limit",
	"group": "Group",
	"addVoteGroup": "Add Voting Group",
	"removeVoteGroup": "Remove this group",
	"confirmRemoveVoteGroupTitle": "Confirm to delete voting group",
	"confirmRemoveVoteGroupContent": "Are you sure you want to delete this voting group?",
	"confirmPublishVoteDocumentTitle": "Post Confirmation",
	"confirmPublishVoteDocumentContent": "This post is a voting post. In order to ensure the authenticity of the vote, it cannot be modified after publishing. Are you sure you want to publish the post?",
	"voteSubject": "Voting Subject",

	"timeToEndText": ", there is {time} before the end",
	"voteCompleteText": "The voting has ended",
	"votedPersonCountText": ", There are {count} people participating so far",
	"noPersonVoteText": ", No one has participated yet",
	"privateVoteText": "This is a private vote, only the poster can see the result of the vote",
	"publicVoteText": "(This is a public vote, others can see your voted items)",
	"anonymousVoteText": "(This is an anonymous vote, others cannot view your vote)",
	"submit": "Submit",
	"youAreVoted": "You have already voted, thank you for your participation",
	"picture": "Picture",
	"word": "text",
	"multiSelectText": "Multiple choice (at most {n} items can be selected):",
	"singleSelectText": "Single choice:",
	"uploadPicture": "Upload Picture",
	"notSelectGroupNotice": "Please select at least one item for each group before submitting",
	"notSelectItemNotice": "Please select at least one item before submitting",
	"second": "second",
	"minute": "minute",
	"hour": "Hour",
	"seeVotedPerson": "See Voting Participants",
	"group1": "Group:",
	"option1": "Option:",

	"attachmentArea": "Attachment Area",
	"selectAttachment": "Select Attachment",
	"attachment": "Attachment",
	"bindObject": "Object",
	"replyAndReadCount": "Reply/View",
	"lastReply": "Last Reply",
	"acceptReplySuccess": "Accept Reply Success",

	"readed": "Read",
	"reply": "Reply",
	"allReply": "Reply all",
	"accessed": "popularity",
	"prime": "The Best",
	"experience": "Experience",
	"nextSubject": "Next Subject",
	"prevSubject": "Previous Subject",
	"floor": "Floor",
	"mainFloor": "Subject",
	"publishAt": "Published at",
	"at": "at",
	"saveReply": "Post a reply",
	"noNextSubject": "Currently is the last subject",
	"noPrevSubject": "Currently is the first subject",

	"recommandSubject": "Recommendation",
	"replyFormTitle": "Reply to subject",
	"setRecommend": "Recommend to the homepage",
	"cancelRecommend": "Cancel Recommendation",
	"setTop": "SetTop",
	"cancelTop": "Cancel Top",
	"setPrime": "Set to best",
	"setRecommendSuccess": "Recommend to the homepage successfully",
	"cancelRecommendSuccess": "Cancel recommendation success",
	"saveReplySuccess": "Reply success",
	"deleteReplySuccess": "Delete Reply Success",
	"deleteReplyTitle": "Delete Reply",
	"deleteReplyText": "It cannot be restored after deletion. Are you sure to delete this reply?",
	"quoteReplyBeingDeleted": "The quoted reply has been deleted!",
	"setPrimeSuccess": "Set to best Success",
	"cancelPrime": "Cancel Prime",
	"cancelPrimeSuccess": "Cancel Prime Success",

	"moveto": "Moveto",
	"lock": "Lock",
	"unlock": "Unlock",
	"lockSuccess": "Successfully locked the post, the post cannot be replied to",
	"unlockSuccess": "Unlock the post successfully, the post can be replied",
	"topFormTitle": "Set Top Form",
	"topType": "Please select the top type, multiple choice are allowed:",
	"topTypeText": "Homepage on top, section on top, section on top",
	"topTypeValue": "bbs,forum,section",
	"setTopSuccess": "Top setting is successful",
	"setToFail": "Top Setting Failed",
	"cancelTopSuccess": "Top cancel successfully",
	"topToBBS": "Top page on top",
	"topToForum": "Top Partition",
	"topToSection": "Section on top",
	"returnToList": "Return to List",
	"invalid": "Disable",
	"personCenter": "Personal Center",
	"company": "Company",
	"department": "Department",
	"mail": "Mail",
	"weixin": "WeChat",
	"mobile": "Mobile",
	"signature": "Signature",

	"mySubject": "My Post",
	"myReply": "My Reply",
	"hisSubject": "His Post",
	"herSubject": "Her Subject",
	"replyContent": "Reply Content",
	"replyTime": "Reply Time",
	"changePersonSetting": "Change Personal Information",
	"sendMessage": "Send Message",
	"todaySubject": "Today Subject",
	"todayReply": "Today Reply",
	"replyTo": "Reply",
	"newSubjectPublishedText": "There are {count} newly published topics, click to view",

	"hotPicture": "Hot Picture",
	"cancelHotPicture": "Cancel hotspot",
	"setHot": "Hot",
	"setHotPicture": "Set HotPicture",
	"setHotLinkSuccess": "Set hotspot picture successfully",
	"cancelHotLinkSuccess": "Cancel Hot Link Success",
	"selectDocPicture": "Select Document Picture",
	"selectFilePicture": "Select Cloud File Picture",
	"hotLinkDescription": "Note: The selected picture will be used as the top picture of the mobile APP on this platform, and the best aspect ratio of the picture is 1:2",
	"unselectHotPic": "Please select a picture first",
	"cancelHotPicComfirmTitle": "Cancel Hotspot",
	"cancelHotPicComfirmContent": "Are you sure to cancel the hot spot of this document?",
	"replyNeedLoginText": "You need to log in to reply",
	"signUp": "Sign Up",
	"satisfiedReply": "Accepted Reply",
	"satisfiedAnswer": "Satisfied Reply",
	"question": "Question",

	"gotoTop": "Top",
	"forumConfig": "Forum Settings",

	"yesterday": "Yesterday",
	"twoDaysAgo": "The day before yesterday",
	"weekAgo": " Week Ago",
	"dayAgo": " Day Ago",
	"hourAgo": " Hours ago",
	"minuteAgo": " minutes ago",
	"justNow": "JustNow",
	"publishJustNow": "Just published",

	"selectTargetSection": "Select the section to move to",
	"moveSuccess": "The post has been moved to {section}",
	"poster": "Poster",
	"replyAbbr": "reply"

};