MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Forum = MWF.xApplication.Forum || {};
MWF.xApplication.Forum.LP={
	"title": "Foro",
	"delete": "Eliminar",
	"deleteDocumentTitle": "Confirmación",
	"deleteDocument": "¿Está seguro de que desea eliminar?",
	"deleteDocumentOK": "Eliminado con éxito",
	"createSuccess": "Creado con éxito",
	"updateSuccess": "Actualizado con éxito",
	"createReplySuccess": "Respuesta creada con éxito",
	"inputName": "Ingrese el nombre",
	"deleteAttachmentTitle": "Confirmación",
	"deleteAttachment": "¿Está seguro de que desea eliminar este archivo adjunto?",
	"search": "Buscar",
	"searchKey": "Ingrese la palabra clave de búsqueda",
	"searchTitle": "La palabra clave puede ser el tema, la sección, la placa o el creador",
	"searchTitleNick": "La palabra clave puede ser el tema, la sección o la placa",
	"noSearchContentNotice": "Ingrese la palabra clave de búsqueda antes de buscar",
	"dateFormatMonth": "%Y年%m月",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%m月%d日",
	"dateFormat": "db",
	"SelectOrgForm": "Selección de organización y personal",
	"month": "Mes",
	"today": "Hoy",
	"day": "Día",
	"cancel": "Cancelar",
	"close": "Cerrar",
	"ok": "Aceptar",
	"edit": "Editar",
	"remove": "Eliminar",
	"action": "Acción",
	"login": "Iniciar sesión",
	"signup": "Registrarse",
	"logout": "Cerrar sesión",
	"name": "Nombre",
	"create_cancel_title": "Confirmación",
	"create_cancel": "¿Está seguro de que desea cancelar la creación?",
	"systemSettingFormTitle": "Sistema",
	"configName": "Nombre",
	"configCode": "Código",
	"configValue": "Valor",
	"categoryManager": "Moderador de sección",
	"setting": "Configuración",
	"createCategory": "Crear sección",
	"createSection": "Crear placa",
	"categoryFormTitle": "Sección",
	"sectionFormTitle": "Placa",
	"muteSettingFormTitle": "Silencio",
	"baseSetting": "Configuración básica",
	"permissionSetting": "Configuración de permisos",
	"forumName": "Nombre",
	"forumManagerName": "Administrador",
	"forumNotice": "Aviso",
	"forumVisible": "Usuarios visibles",
	"forumVisibleButton": "Seleccionar usuarios visibles",
	"allPerson": "Todos",
	"byPermission": "Según permiso",
	"forumVisibleValue": "Todos, Según permiso",
	"indexListStyle": "Estilo de lista",
	"indexListStyleValue": "Clásico, Rectángulo simple, Rectángulo de imagen",
	"indexListStyleButton": "Seleccionar estilo de lista de la página principal",
	"selectIndexType": "Seleccionar estilo de lista de la página principal",
	"all": "Todo",
	"all1": "Todo",
	"disable": "Inhabilitado",
	"typeColumn": "Número de columnas por fila",
	"indexListStyleImage": "Rectángulo de imagen",
	"forumIndexStyle": "Estilo de página principal de la sección",
	"forumIndexStyleValue": "Clásico, Noticias, Fotos",
	"indexRecommendable": "Permitir recomendaciones para la página principal",
	"subjectNeedAudit": "Se necesita aprobación para el tema",
	"replyNeedAudit": "Se necesita aprobación para la respuesta",
	"sectionCreateAble": "Permitir crear placas",
	"sectionTotal": "Número de placas",
	"subjectTotal": "Número de temas",
	"replyTotal": "Número de respuestas",
	"creatorName": "Creador",
	"forumStatus": "Estado",
	"forumStatusValue": "Habilitado, Inhabilitado",
	"orderNumber": "Número de orden",
	"yesOrNo": "Sí, No",
	"yes": "Sí",
	"owneForum": "Sección perteneciente",
	"createTime": "Fecha de creación",
	"time": "Hora",
	"create": "Crear",
	"replyCount": "Respuestas",
	"auditPerson": "Persona de aprobación",
	"forumColor": "Color",
	"forumColorFormTitle": "Seleccionar color de la sección",
	"defaultForumColor": "#7e7e7e",
	"optionsForumColors": [
		[
			"#ff4040",
			"#ff421e",
			"#ffbf18",
			"#e1e100",
			"#00e100",
			"#00e1ad",
			"#00e0e0",
			"#0082bf",
			"#0080ff",
			"#4181ff",
			"#8242ff",
			"#c140ff",
			"#ff42f9",
			"#ff40a0",
			"#ff4070",
			"#606060"
		],
		[
			"#ff1f35",
			"#ff1f10",
			"#ff8100",
			"#bfbf00",
			"#00c200",
			"#00c197",
			"#00c1c2",
			"#4181c0",
			"#0062e1",
			"#4141ff",
			"#4200ff",
			"#c200ff",
			"#ff22ff",
			"#f52b97",
			"#ff2259",
			"#5f5f5f"
		],
		[
			"#e01f25",
			"#e12000",
			"#e26200",
			"#a1a100",
			"#00a000",
			"#009f82",
			"#3f8080",
			"#0060a0",
			"#0041c2",
			"#0021bf",
			"#4100c2",
			"#8100ff",
			"#ff00ff",
			"#ff0080",
			"#79656a",
			"#4f4f4f"
		],
		[
			"#c20000",
			"#ff0000",
			"#bf4100",
			"#80803f",
			"#3f803f",
			"#008250",
			"#006062",
			"#004080",
			"#001fe2",
			"#0021bf",
			"#4000a2",
			"#6000a1",
			"#e000e0",
			"#df007f",
			"#c20041",
			"#3f3f3f"
		],
		[
			"#a00000",
			"#e10000",
			"#a13f00",
			"#626200",
			"#006000",
			"#00603c",
			"#004041",
			"#002f80",
			"#0000ff",
			"#2020a0",
			"#2200a1",
			"#400080",
			"#a1009f",
			"#c0007f",
			"#9f000f",
			"#2f2f2f"
		],
		[
			"#600000",
			"#c21212",
			"#824200",
			"#424200",
			"#004200",
			"#004023",
			"#00323f",
			"#002060",
			"#0020c2",
			"#2222c0",
			"#000080",
			"#1f007f",
			"#800080",
			"#820040",
			"#800000",
			"#1f1f1f"
		],
		[
			"#400000",
			"#a11f12",
			"#604200",
			"#212100",
			"#002100",
			"#00201f",
			"#002041",
			"#00204f",
			"#0000e0",
			"#0000a1",
			"#000061",
			"#1f0062",
			"#40005f",
			"#620042",
			"#620012",
			"#0f0f0f"
		]
	],
	"replyMessageNotify": "Habilitar recordatorio de mensaje de respuesta",
	"replyMessageNotifyType": "Notificar al administrador de la partición,notificar al moderador,notificar al cartel",
	"subjectMessageNotify": "Habilitar recordatorio de publicación de mensajes",
	"subjectMessageNotifyType": "Notificar al administrador de la partición,notificar al moderador",
	"selectColor": "Seleccionar color",
	"selectList": "Seleccionar lista",
	"effect": "Efecto",
	"column": "Columna",
	"mainSection": "Placa principal",
	"welcomeTitle": "¡Hola {user}!",
	"seePersonCenter": "Haga clic para ver el centro personal",
	"closeNavi": "Cerrar navegación",
	"navi": "Navegación",
	"naviLayout": "Diseño de navegación",
	"sectionName": "Nombre",
	"mainSectionName": "Placa principal",
	"sectionLevel": "Nivel",
	"sectionLevelValue": "Placa principal, Subplaca",
	"sectionDescription": "Descripción",
	"sectionNotice": "Aviso",
	"sectionVisible": "Alcance visible",
	"sectionVisibleValue": "Todos, Según permiso",
	"replyVisible": "Alcance visible de respuestas",
	"replyVisibleValue": "Todos, Según permiso",
	"subjectPublishAble": "Permitir publicación de temas",
	"subjectPublishAbleValue": "Todos, Según permiso",
	"replyPublishAble": "Permitir publicación de respuestas",
	"replyPublishAbleValue": "Todos, Según permiso",
	"moderatorNames": "Moderador",
	"sectionType": "Tipo",
	"sectionTypeValue": "Clásico, Noticias de imagen, Noticias normales, Aviso",
	"subSectionCreateAble": "Permitir crear subplacas",
	"sectionStatus": "Estado",
	"sectionStatusValue": "Habilitado, Inhabilitado",
	"sectionGrade": "Calificación",
	"sectionGradeValue": "No, Sí",
	"sectionIcon": "Icono",
	"uploadIcon": "Cargar icono",
	"selectIcon": "Seleccionar icono",
	"sectionIconFormTitle": "Seleccionar icono",
	"indexRecommenPerson": "Persona que recomienda",
	"permissionFormTitle": "Configuración de permisos",
	"permissionType": "Tipo de permiso",
	"permissionTypeValue": "Permiso de foro, Permiso de placa, Otros permisos",
	"permissionName": "Nombre del permiso",
	"permissionCode": "Código del permiso",
	"description": "Descripción",
	"roleFormTitle": "Configuración de roles",
	"createRole": "Crear configuración de roles",
	"roleType": "Tipo de rol",
	"roleTypeValue": "Rol de foro, Rol de placa",
	"roleName": "Nombre del rol",
	"roleCode": "Código del rol",
	"selectPerson": "Seleccionar persona",
	"selectDepartment": "Seleccionar departamento",
	"selectCompany": "Seleccionar empresa",
	"recommanded": "Recomendado",
	"subject": "Tema",
	"allSubject": "Todos los temas",
	"selectSubjectType": "Filtrar por tipo de tema",
	"recommandedSubject": "Temas recomendados",
	"primeSubject": "Temas destacados",
	"type": "Tipo",
	"typeValue": "Discusión, Votación, Noticias, Recompensa, Debate, Flood, Conocimiento, Actividad",
	"subjectType": "Opciones de tipo de tema",
	"subjectTypeDefaultValue": "Discusión|Noticias|Actividad|Conocimiento|Flood",
	"vote": "Votación",
	"sectionApp": "Tienda de aplicaciones",
	"typeCategoryDefaultValue": "Información|Pregunta|Votación",
	"typeCatagory": "Opciones de tipo de tema",
	"typeCategorySelectValue": "Información|Pregunta|Votación",
	"portalImage": "Imagen principal",
	"summary": "Resumen",
	"content": "Contenido",
	"createSubject": "Publicar tema",
	"anonymousSubject": "Publicar tema como anónimo",
	"saveSubject": "Guardar tema",
	"selectCurrentDocumentFile": "Seleccionar imagen del tema",
	"selectCloudFile": "Seleccionar imagen en la nube",
	"insertUrl": "Insertar enlace de imagen",
	"voteLimitTime": "Límite de tiempo para votar",
	"voteResultVisible": "Resultados de votación visibles",
	"votePersonVisible": "Privacidad de los votantes",
	"votePersonValue": "Público, Anónimo",
	"voteOptions": "Opciones de votación",
	"option": "Opción",
	"opt": "opción",
	"voteCountLimit": "Máximo de opciones seleccionables",
	"group": "Grupo",
	"addVoteGroup": "Agregar grupo de votantes",
	"removeVoteGroup": "Eliminar este grupo",
	"confirmRemoveVoteGroupTitle": "Confirmación para eliminar el grupo de votantes",
	"confirmRemoveVoteGroupContent": "¿Estás seguro de que deseas eliminar este grupo de votantes?",
	"confirmPublishVoteDocumentTitle": "Confirmar publicación del tema",
	"confirmPublishVoteDocumentContent": "Este tema es una votación. Para garantizar la autenticidad de la votación, no se podrá modificar después de la publicación. ¿Seguro que quieres publicar este tema?",
	"voteSubject": "Tema de votación",
	"timeToEndText": "，quedan {time} para finalizar",
	"voteCompleteText": "，la votación ha finalizado",
	"votedPersonCountText": "，actualmente hay {count} personas que han participado",
	"noPersonVoteText": "，por el momento no hay personas que hayan participado",
	"privateVoteText": "Esta es una votación privada, solo el autor del tema podrá ver los resultados de la votación",
	"publicVoteText": "(Esta es una votación pública, otros pueden ver su selección de votos)",
	"anonymousVoteText": "(Esta es una votación anónima, otros no pueden ver su selección de votos)",
	"submit": "Enviar",
	"youAreVoted": "Ya has votado, gracias por participar",
	"picture": "Imagen",
	"word": "Texto",
	"multiSelectText": "Selección múltiple (seleccionable hasta {n} opciones):",
	"singleSelectText": "Selección única:",
	"uploadPicture": "Cargar imagen",
	"notSelectGroupNotice": "Seleccione al menos una opción en cada grupo antes de enviar",
	"notSelectItemNotice": "Seleccione al menos una opción antes de enviar",
	"second": "segundo(s)",
	"minute": "minuto(s)",
	"hour": "hora(s)",
	"seeVotedPerson": "Ver personas que han votado",
	"group1": "Grupo:",
	"option1": "Opción:",
	"attachmentArea": "Área de adjuntos",
	"selectAttachment": "Seleccionar adjunto",
	"attachment": "Adjunto",
	"bindObject": "Objeto vinculado",
	"replyAndReadCount": "Respuestas/Vistas",
	"lastReply": "Última respuesta",
	"acceptReplySuccess": "Respuesta aceptada con éxito",
	"readed": "Leído",
	"reply": "Rpta.",
	"allReply": "Todas las respuestas",
	"accessed": "Popularidad",
	"prime": "Destacado",
	"sType": "Filtro de categoría de tema",
	"experience": "Experiencia",
	"nextSubject": "Siguiente tema",
	"prevSubject": "Tema anterior",
	"floor": "Piso",
	"mainFloor": "Edificio principal",
	"publishAt": "Publicado en",
	"at": "en",
	"saveReply": "Publicar respuesta",
	"noNextSubject": "Este es el último tema actualmente",
	"noPrevSubject": "Este es el primer tema actualmente",
	"recommandSubject": "Recomendaciones más recientes",
	"replyFormTitle": "Responder al tema",
	"setRecommend": "Recomendar para la página de inicio",
	"cancelRecommend": "Cancelar recomendación",
	"setTop": "Fijo",
	"cancelTop": "Canc. Fijo",
	"setPrime": "Est. Destacado",
	"setRecommendSuccess": "Recomendado exitosamente para la página de inicio",
	"cancelRecommendSuccess": "Cancelación de recomendación exitosa",
	"saveReplySuccess": "Respuesta publicada con éxito",
	"deleteReplySuccess": "Eliminación de la respuesta exitosa",
	"deleteReplyTitle": "Eliminar respuesta",
	"deleteReplyText": "Después de eliminar, no se puede recuperar, ¿está seguro de que desea eliminar esta respuesta?",
	"quoteReplyBeingDeleted": "La respuesta citada ha sido eliminada",
	"setPrimeSuccess": "Destacado establecido con éxito",
	"cancelPrime": "Cancelar destacado",
	"cancelPrimeSuccess": "Cancelación de destacado exitosa",
	"moveto": "Mover a",
	"lock": "Bloquear",
	"unlock": "Desbloquear",
	"lockSuccess": "El tema ha sido bloqueado exitosamente, ya no se puede responder",
	"unlockSuccess": "El tema ha sido desbloqueado exitosamente, ahora se puede responder",
	"topFormTitle": "Establecer como fijo",
	"topType": "Seleccione el tipo de fijación, selección múltiple permitida:",
	"topTypeText": "Fijar en la página de inicio, fijar en la sección, fijar en el foro",
	"topTypeValue": "bbs,forum,section",
	"setTopSuccess": "Fijación establecida con éxito",
	"setToFail": "Error al establecer como fijo",
	"cancelTopSuccess": "Cancelación de fijación exitosa",
	"topToBBS": "Fijar en la página de inicio",
	"topToForum": "Fijar en la sección",
	"topToSection": "Fijar en el foro",
	"returnToList": "Volver a la lista",
	"invalid": "Inválido",
	"personCenter": "Centro personal",
	"company": "Compañía",
	"department": "Departamento",
	"mail": "Correo electrónico",
	"weixin": "WeChat",
	"mobile": "Teléfono móvil",
	"signature": "Firma",
	"mySubject": "Publicaciones",
	"myReply": "Respuestas",
	"hisSubject": "Sus publicaciones",
	"herSubject": "Las publicaciones de ella",
	"replyContent": "Contenido de la respuesta",
	"replyTime": "Tiempo de respuesta",
	"changePersonSetting": "Modificar información personal",
	"sendMessage": "Enviar mensaje",
	"todaySubject": "Temas de hoy",
	"todayReply": "Respuestas de hoy",
	"replyTo": "Responder a",
	"newSubjectPublishedText": "Hay {count} nuevos temas publicados, haga clic para ver",
	"hotPicture": "Imagen popular",
	"cancelHotPicture": "Cancelar imagen popular",
	"setHot": "Popular",
	"setHotPicture": "Establecer imagen popular",
	"setHotLinkSuccess": "Imagen popular establecida con éxito",
	"cancelHotLinkSuccess": "Imagen popular cancelada con éxito",
	"selectDocPicture": "Seleccionar imagen del documento",
	"selectFilePicture": "Seleccionar imagen del archivo en la nube",
	"hotLinkDescription": "Nota: La imagen seleccionada se utilizará como imagen superior de la aplicación móvil del sitio web. La mejor relación de altura y anchura de la imagen es 1:2.",
	"unselectHotPic": "Primero seleccione una imagen",
	"cancelHotPicComfirmTitle": "Cancelar imagen popular",
	"cancelHotPicComfirmContent": "¿Seguro que desea cancelar la imagen popular de este documento?",
	"replyNeedLoginText": "Debe iniciar sesión para responder",
	"signUp": "Registrarse",
	"satisfiedReply": "Respuesta aceptada",
	"satisfiedAnswer": "Respuesta satisfactoria",
	"question": "Pregunta",
	"gotoTop": "Arriba",
	"forumConfig": "Configuración del foro",
	"yesterday": "Ayer",
	"twoDaysAgo": "Anteayer",
	"weekAgo": "Hace una semana",
	"dayAgo": "Días atrás",
	"hourAgo": "Horas atrás",
	"minuteAgo": "Minutos atrás",
	"justNow": "Ahora mismo",
	"publishJustNow": "Publicado justo ahora",
	"gradeNotice": "Por favor, califique antes de enviar",
	"selectTargetSection": "Seleccione la sección a la que desea moverlo",
	"moveSuccess": "El tema ha sido movido a {section}",
	"editPermissionFormTitle": "Establecer permisos de edición",
	"editorSetting": "Editor(es)",
	"setEditorSuccess": "Permisos de edición establecidos con éxito!",
	"setEditorFail": "Error al establecer permisos de edición!",
	"addMutePerson": "Agregar persona a la lista de prohibidos",
	"mute1SettingFormTitle": "Configuración de personas prohibidas",
	"mutePerson": "Persona prohibida",
	"muteTime": "Tiempo de prohibición",
	"unmuteDate": "Fecha de desbloqueo",
	"unmuteDateNote": "Se desbloqueará automáticamente después de que expire",
	"unmute": "Desbloquear",
	"unmuteTitle": "Confirmar desbloqueo",
	"unmuteDocument": "¿Está seguro de que desea desbloquear {person}?",
	"multReason": "Motivo de la prohibición",
	"unmuteSuccess": "Desbloqueado con éxito!",
	"unmuteTimeUnvalid": "La fecha de desbloqueo debe ser posterior a hoy",
	"muteNote": "Has sido prohibido, no puedes publicar ni responder temas.",
	"muteInfor": "Fecha de desbloqueo: {unmuteDate}, Motivo de la prohibición: {reason}.",
	"poster": "Autor del tema"
}
MWF.xApplication.Forum["lp."+o2.language] = MWF.xApplication.Forum.LP