MWF.xApplication.Forum = MWF.xApplication.Forum || {};
MWF.xApplication.Forum.LP = {
	"title": "フォーラムホーム",
	"delete": "削除",
	"deleteDocumentTitle": "削除の確認",
	"deleteDocument": "本当に削除しますか？",
	"deleteDocumentOK": "削除成功",
	"createSuccess": "作成成功",
	"updateSuccess": "更新成功",
	"createReplySuccess": "返信成功",
	"inputName": "名前を入力してください",
	"deleteAttachmentTitle": "添付ファイル削除の確認",
	"deleteAttachment": "この添付ファイルを削除しますか？",
	"search": "検索",
	"searchKey": "検索キーワードを入力してください",
	"searchTitle": "キーワードは主題、セクション、フォーラム、作成者として入力できます",
	"searchTitleNick": "キーワードは主題、セクション、フォーラムとして入力できます",
	"noSearchContentNotice": "検索キーワードを入力し、検索を実行してください",

	"dateFormatMonth": "%Y年%m月",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%m月%d日",
	"dateFormat": "db",
	"SelectOrgForm": "人員組織の選択",

	"month": "月",
	"today": "今日",
	"day": "日",

	"cancel": "キャンセル",
	"close": "閉じる",
	"ok": "確認",
	"edit": "編集",
	"remove": "削除",
	"action": "アクション",

	"login": "ログイン",
	"signup": "サインアップ",
	"logout": "ログアウト",

	"name": "名前",
	"create_cancel_title": "新規作成のキャンセル確認",
	"create_cancel": "新規作成をキャンセルしますか？",

	"systemSettingFormTitle": "システム設定",
	"configName": "設定名",
	"configCode": "設定コード",
	"configValue": "設定値",

	"categoryManager": "カテゴリーマネージャー",
	"setting": "設定",
	"createCategory": "カテゴリー作成",
	"createSection": "セクション作成",
	"categoryFormTitle": "カテゴリー設定",
	"sectionFormTitle": "セクション設定",
	"muteSettingFormTitle": "ミュート管理",

	"baseSetting": "基本設定",
	"permissionSetting": "権限設定",


	"forumName": "フォーラム名",
	"forumManagerName": "フォーラムマネージャー",
	"forumNotice": "フォーラム告知",
	"forumVisible": "表示可能なユーザー",
	"forumVisibleButton": "表示可能なユーザーの選択",
	"allPerson": "すべての人",
	"byPermission": "権限に従って",
	"forumVisibleValue": "すべての人,権限に従って",
	"indexListStyle": "ホームページスタイルリスト",
	"indexListStyleValue": "クラシック,シンプルな長方形,画像長方形",
	"indexListStyleButton": "ホームページスタイルの選択",
	"selectIndexType": "ホームページスタイルの選択",
	"all": "すべて",
	"all1": "すべて",
	"disable": "無効",
	"typeColumn": "各行の列数",
	"indexListStyleImage": "画像長方形",
	"forumIndexStyle": "フォーラムホームページスタイル",
	"forumIndexStyleValue": "クラシック,ニュース,写真",
	"indexRecommendable": "ホームページへの推奨を許可",
	"subjectNeedAudit": "トピックの審査が必要",
	"replyNeedAudit": "回答の審査が必要",
	"sectionCreateAble": "セクションの作成を許可",
	"sectionTotal": "セクションの数",
	"subjectTotal": "トピックの数",
	"replyTotal": "回答の数",
	"creatorName": "作成者",
	"forumStatus": "フォーラムステータス",
	"forumStatusValue": "有効,無効",
	"orderNumber": "並び替え番号",
	"yesOrNo": "はい,いいえ",
	"yes": "はい",
	"owneForum": "所属フォーラム",
	"createTime": "作成日時",
	"time": "時間",
	"create": "作成",
	"replyCount": "回答",
	"auditPerson": "審査担当",
	"forumColor": "フォーラムの色",
	"forumColorFormTitle": "フォーラムの色を選択",
	"defaultForumColor" : "#7e7e7e",
	"optionsForumColors" : [
		["#ff4040","#ff421e","#ffbf18","#e1e100","#00e100","#00e1ad","#00e0e0","#0082bf","#0080ff","#4181ff","#8242ff","#c140ff","#ff42f9","#ff40a0","#ff4070","#606060"],
		["#ff1f35","#ff1f10","#ff8100","#bfbf00","#00c200","#00c197","#00c1c2","#4181c0","#0062e1","#4141ff","#4200ff","#c200ff","#ff22ff","#f52b97","#ff2259","#5f5f5f"],
		["#e01f25","#e12000","#e26200","#a1a100","#00a000","#009f82","#3f8080","#0060a0","#0041c2","#0021bf","#4100c2","#8100ff","#ff00ff","#ff0080","#79656a","#4f4f4f"],
		["#c20000","#ff0000","#bf4100","#80803f","#3f803f","#008250","#006062","#004080","#001fe2","#0021bf","#4000a2","#6000a1","#e000e0","#df007f","#c20041","#3f3f3f"],
		["#a00000","#e10000","#a13f00","#626200","#006000","#00603c","#004041","#002f80","#0000ff","#2020a0","#2200a1","#400080","#a1009f","#c0007f","#9f000f","#2f2f2f"],
		["#600000","#c21212","#824200","#424200","#004200","#004023","#00323f","#002060","#0020c2","#2222c0","#000080","#1f007f","#800080","#820040","#800000","#1f1f1f"],
		["#400000","#a11f12","#604200","#212100","#002100","#00201f","#002041","#00204f","#0000e0","#0000a1","#000061","#1f0062","#40005f","#620042","#620012","#0f0f0f"]
	],
	"selectColor": "色を選択",
	"selectList": "リストを選択",
	"effect": "効果",
	"column": "列",
	"mainSection": "メインセクション",
	"welcomeTitle": "{user}、こんにちは！",
	"seePersonCenter": "個人センターを表示するにはクリック",
	"closeNavi": "ナビゲーションを閉じる",
	"navi": "ナビゲーション",
	"naviLayout": "ナビゲーションレイアウト",

	"sectionName": "セクション名",
	"mainSectionName": "メインセクション名",
	"sectionLevel": "セクションレベル",
	"sectionLevelValue": "メインセクション、サブセクション",
	"sectionDescription": "セクションの説明",
	"sectionNotice": "セクションのお知らせ",
	"sectionVisible": "セクションの表示範囲",
	"sectionVisibleValue": "すべて,権限に従って",
	"replyVisible": "返信の表示範囲",
	"replyVisibleValue": "すべて,権限に従って",
	"subjectPublishAble": "投稿可能範囲",
	"subjectPublishAbleValue": "すべて,権限に従って",
	"replyPublishAble": "返信可能範囲",
	"replyPublishAbleValue": "すべて,権限に従って",
	"moderatorNames": "モデレータ",
	"sectionType": "タイプ",
	"sectionTypeValue": "クラシック,画像ニュース,一般ニュース,お知らせ",
	"subSectionCreateAble": "サブセクションの作成を許可",
	"sectionStatus": "ステータス",
	"sectionStatusValue": "有効,無効",
	"sectionGrade": "評価",
	"sectionGradeValue": "いいえ,はい",
	"sectionIcon": "セクションアイコン",
	"uploadIcon": "ローカルアイコンをアップロード",
	"selectIcon": "アイコンを選択",
	"sectionIconFormTitle": "セクションアイコンを選択",
	"indexRecommenPerson": "推薦者",

	"permissionFormTitle": "権限設定",
	"permissionType": "権限タイプ",
	"permissionTypeValue": "フォーラム権限,セクション権限,その他権限",
	"permissionName": "権限名",
	"permissionCode": "権限コード",
	"description": "説明",
	"create": "作成",

	"roleFormTitle": "役割設定",
	"createRole": "役割設定の作成",
	"roleType": "役割タイプ",
	"roleTypeValue": "フォーラム役割,セクション役割",
	"roleName": "役割名",
	"roleCode": "役割コード",
	"selectPerson": "ユーザーの選択",
	"selectDepartment": "組織の選択",
	"selectCompany": "会社の選択",

	"recommanded": "おすすめ",
	"subject": "トピック",
	"allSubject": "すべてのトピック",
	"selectSubjectType": "トピックタイプの選択",
	"recommandedSubject": "おすすめトピック",
	"primeSubject": "ベストトピック",
	"type": "カテゴリ",
	"typeValue": "ディスカッション,投票,ニュース,報酬,議論,フラッド,知識,トレンド",
	"subjectType": "トピックタイプの選択肢",
	"subjectTypeDefaultValue": "ディスカッション|ニュース|トレンド|知識|フラッド",
	"vote": "投票",
	"sectionApp": "アプリマーケット",
	"typeCategoryDefaultValue": "情報|質問|投票",
	"typeCatagory": "トピックタイプの選択肢",
	"typeCategorySelectValue": "情報|質問|投票",
	"portalImage": "ホーム画像",
	"summary": "要約",
	"content": "コンテンツ",
	"createSubject": "投稿する",
	"anonymousSubject": "匿名で投稿",
	"saveSubject": "投稿保存",
	"selectCurrentDocumentFile": "トピック画像を選択",
	"selectCloudFile": "クラウドファイル画像を選択",
	"insertUrl": "画像リンクを挿入",
	"voteLimitTime": "投票制限時間",
	"voteResultVisible": "投票結果表示",
	"votePersonVisible": "投票者のプライバシー",
	"votePersonValue": "公開,匿名",
	"voteOptions": "投票オプション",
	"option": "オプション",
	"opt": "項目",
	"voteCountLimit": "選択制限の最大数",
	"group": "グループ",
	"addVoteGroup": "投票グループを追加",
	"removeVoteGroup": "このグループを削除",
	"confirmRemoveVoteGroupTitle": "投票グループ削除の確認",
	"confirmRemoveVoteGroupContent": "このグループを削除しますか？",
	"confirmPublishVoteDocumentTitle": "投稿確認",
	"confirmPublishVoteDocumentContent": "この投稿は投票投稿です。投票の正確性を確保するため、投稿後は編集できません。投稿しますか？",
	"voteSubject": "投票トピック",

	"timeToEndText": "，終了まであと{time}",
	"voteCompleteText": "，投票は終了しました",
	"votedPersonCountText": "，現在{count}人が参加しています",
	"noPersonVoteText": "，現在誰も参加していません",
	"privateVoteText": "これは非公開の投票です。投票結果は投稿者のみが見ることができます",
	"publicVoteText": "（これは公開投票です。他の人はあなたの投票アイテムを見ることができます）",
	"anonymousVoteText": "（これは匿名投票です。他の人はあなたの投票アイテムを見ることはできません）",
	"submit": "提出",
	"youAreVoted": "すでに投票済みです。ご参加いただきありがとうございます",
	"picture": "画像",
	"word": "テキスト",
	"multiSelectText": "複数選択（最大{n}アイテムまで選択可能）：",
	"singleSelectText": "単一選択：",
	"uploadPicture": "画像をアップロード",
	"notSelectGroupNotice": "各グループで少なくとも1つ選択してから送信してください",
	"notSelectItemNotice": "少なくとも1つ選択してから送信してください",
	"second": "秒",
	"minute": "分",
	"hour": "時間",
	"seeVotedPerson": "投票参加者を表示",
	"group1": "グループ：",
	"option1": "オプション：",

	"attachmentArea": "添付ファイルエリア",
	"selectAttachment": "添付ファイルを選択",
	"attachment": "添付ファイル",
	"bindObject": "オブジェクト",
	"replyAndReadCount": "返信/閲覧数",
	"lastReply": "最後の返信",
	"acceptReplySuccess": "返信を受け入れました",

	"readed": "既読",
	"reply": "返信",
	"allReply": "全ての返信",
	"accessed": "人気",
	"prime": "おすすめ",
	"sType": "トピック タイプのフィルタリング",
	"experience": "経験",
	"nextSubject": "次のトピック",
	"prevSubject": "前のトピック",
	"floor": "階",
	"mainFloor": "メイン階",
	"publishAt": "発表日",
	"at": "で",
	"saveReply": "返信を保存",
	"noNextSubject": "現在、最後のトピックです",
	"noPrevSubject": "現在、最初のトピックです",
	"recommandSubject": "最新のおすすめ",
	"replyFormTitle": "トピックに返信",
	"setRecommend": "トップページにおすすめ",
	"cancelRecommend": "おすすめを解除",
	"setTop": "トップに固定",
	"cancelTop": "固定を解除",
	"setPrime": "プライムを設定",
	"setRecommendSuccess": "トップページにおすすめに設定しました",
	"cancelRecommendSuccess": "おすすめを解除しました",
	"saveReplySuccess": "返信に成功しました",
	"deleteReplySuccess": "返信を削除しました",
	"deleteReplyTitle": "返信を削除",
	"deleteReplyText": "削除した後、元に戻すことはできません。この返信を削除しますか？",
	"quoteReplyBeingDeleted": "引用された返信が既に削除されています！",
	"setPrimeSuccess": "プライムを設定しました",
	"cancelPrime": "プライムを解除",
	"cancelPrimeSuccess": "プライムを解除しました",

	"moveto": "移動",
	"lock": "ロック",
	"unlock": "ロック解除",
	"lockSuccess": "投稿をロックしました、コメントはできません。",
	"unlockSuccess": "投稿のロックが解除されました、コメントが可能です。",
	"topFormTitle": "トップ設定",
	"topType": "複数選択可能なトップの種類を選択してください：",
	"topTypeText": "ホームトップ, 区別トップ, フォーラムトップ",
	"topTypeValue": "bbs, forum, section",
	"setTopSuccess": "トップ設定が成功しました",
	"setToFail": "トップ設定が失敗しました",
	"cancelTopSuccess": "トップの解除が成功しました",
	"topToBBS": "ホームトップ",
	"topToForum": "区別トップ",
	"topToSection": "フォーラムトップ",
	"returnToList": "リストに戻る",
	"invalid": "無効",
	"personCenter": "個人センター",
	"company": "会社",
	"department": "部門",
	"mail": "メール",
	"weixin": "WeChat",
	"mobile": "モバイル",
	"signature": "署名",
	"mySubject": "私の投稿",
	"myReply": "私の回答",
	"hisSubject": "彼の投稿",
	"herSubject": "彼女の投稿",
	"replyContent": "回答内容",
	"replyTime": "回答時間",
	"changePersonSetting": "個人情報の変更",
	"sendMessage": "メッセージを送る",
	"todaySubject": "今日のトピック",
	"todayReply": "今日の回答",
	"replyTo": "回答",
	"newSubjectPublishedText": "新しい{count}件のトピックが投稿されました、クリックして確認してください",

	"hotPicture": "ホット画像",
	"cancelHotPicture": "ホット取消",
	"setHot": "ホット設定",
	"setHotPicture": "ホット画像設定",
	"setHotLinkSuccess": "ホット画像設定成功",
	"cancelHotLinkSuccess": "ホット画像キャンセル成功",
	"selectDocPicture": "ドキュメント画像を選択",
	"selectFilePicture": "クラウドファイル画像を選択",
	"hotLinkDescription": "注意: 選択した画像は、このプラットフォームのモバイルアプリのトップ画像として使用され、最適な縦横比は1:2です。",
	"unselectHotPic": "先に画像を選択してください",
	"cancelHotPicComfirmTitle": "ホット画像キャンセル",
	"cancelHotPicComfirmContent": "このドキュメントのホット画像をキャンセルしますか？",
	"replyNeedLoginText": "回答にはログインが必要です",
	"signUp": "サインアップ",
	"satisfiedReply": "回答を採用",
	"satisfiedAnswer": "満足度の高い回答",
	"question": "質問",
	"gotoTop": "トップへ",
	"forumConfig": "フォーラム設定",
	"yesterday": "昨日",
	"twoDaysAgo": "一昨日",
	"weekAgo": "週間前",
	"dayAgo": "日前",
	"hourAgo": "時間前",
	"minuteAgo": "分前",
	"justNow": "たった今",
	"publishJustNow": "ちょうど今投稿",
	"gradeNotice": "評価後に提出してください",

	"selectTargetSection": "移動先のセクションを選択",
	"moveSuccess": "投稿が{section}に移動しました。",
	"editPermissionFormTitle": "編集権限の設定",
	"editorSetting": "エディタ",
	"setEditorSuccess": "編集権限の設定に成功しました！",
	"setEditorFail": "編集権限の設定に失敗しました！",
	"addMutePerson": "ミュート対象を追加",
	"mute1SettingFormTitle": "ミュート対象の設定",
	"mutePerson": "ミュート対象",
	"muteTime": "ミュート期間",
	"unmuteDate": "解除日",
	"unmuteDateNote": "期限切れ後、ミュートが自動的に解除されます",
	"unmute": "ミュート解除",
	"unmuteTitle": "ミュート解除の確認",
	"unmuteDocument": "{person}のミュートを解除しますか？",
	"multReason": "ミュート理由",
	"unmuteSuccess": "ミュートが正常に解除されました！",
	"unmuteTimeUnvalid": "解除日は今日よりも遅くする必要があります",
	"muteNote": "あなたはミュートされており、投稿や返信ができません。",
	"muteInfor": "解除日：{unmuteDate}、ミュートの理由：{reason}",
	"poster": "投稿者"

};