MWF.xApplication.Forum = MWF.xApplication.Forum || {};
MWF.xApplication.Forum.LP = {
	"title": "포럼 홈",
	"delete": "삭제",
	"deleteDocumentTitle": "삭제 확인",
	"deleteDocument": "정말 삭제하시겠습니까?",
	"deleteDocumentOK": "삭제 성공",
	"createSuccess": "생성 성공",
	"updateSuccess": "업데이트 성공",
	"createReplySuccess": "답변 성공",
	"inputName": "이름을 입력하세요",
	"deleteAttachmentTitle": "첨부 파일 삭제 확인",
	"deleteAttachment": "이 첨부 파일을 삭제하시겠습니까?",
	"search": "검색",
	"searchKey": "검색어를 입력하세요",
	"searchTitle": "검색어로 주제, 분야, 게시판, 작성자를 입력할 수 있습니다",
	"searchTitleNick": "검색어로 주제, 분야, 게시판을 입력할 수 있습니다",
	"noSearchContentNotice": "검색어를 입력한 후 검색을 실행하세요",

	"dateFormatMonth": "%Y년%m월",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%m월%d일",
	"dateFormat": "db",
	"SelectOrgForm": "인원 및 조직 선택",

	"month": "월",
	"today": "오늘",
	"day": "일",

	"cancel": "취소",
	"close": "닫기",
	"ok": "확인",
	"edit": "편집",
	"remove": "삭제",
	"action": "작업",

	"login": "로그인",
	"signup": "가입",
	"logout": "로그아웃",

	"name": "이름",
	"create_cancel_title": "생성 취소 확인",
	"create_cancel": "생성을 취소하시겠습니까?",

	"systemSettingFormTitle": "시스템 설정",
	"configName": "구성 이름",
	"configCode": "구성 코드",
	"configValue": "구성 값",

	"categoryManager": "분야 관리자",
	"setting": "설정",
	"createCategory": "분야 생성",
	"createSection": "섹션 생성",
	"categoryFormTitle": "분야 설정",
	"sectionFormTitle": "섹션 설정",
	"muteSettingFormTitle": "음소거 관리",

	"baseSetting": "기본 설정",
	"permissionSetting": "권한 설정",


	"forumName": "분야 이름",
	"forumManagerName": "분야 관리자",
	"forumNotice": "분야 공지",
	"forumVisible": "표시 가능한 사용자",
	"forumVisibleButton": "표시 가능한 사용자 선택",
	"allPerson": "모두",
	"byPermission": "권한에 따라",
	"forumVisibleValue": "모두, 권한에 따라",
	"indexListStyle": "홈페이지 스타일 목록",
	"indexListStyleValue": "클래식, 간단한 사각형, 이미지 사각형",
	"indexListStyleButton": "홈페이지 스타일 선택",
	"selectIndexType": "홈페이지 스타일 선택",
	"all": "모두",
	"all1": "전체",
	"disable": "사용 중지",
	"typeColumn": "행당 열 수",
	"indexListStyleImage": "이미지 사각형",
	"forumIndexStyle": "분야 홈페이지 스타일",
	"forumIndexStyleValue": "클래식, 뉴스, 사진",
	"indexRecommendable": "홈페이지에 추천 허용",
	"subjectNeedAudit": "주제 검토 필요",
	"replyNeedAudit": "답글 검토 필요",
	"sectionCreateAble": "섹션 생성 허용",
	"sectionTotal": "섹션 수",
	"subjectTotal": "주제 수",
	"replyTotal": "답글 수",
	"creatorName": "생성자",
	"forumStatus": "분야 상태",
	"forumStatusValue": "사용 중, 사용 중지",
	"orderNumber": "정렬 번호",
	"yesOrNo": "예, 아니요",
	"yes": "예",
	"owneForum": "소유 분야",
	"createTime": "생성 시간",
	"time": "시간",
	"create": "생성",
	"replyCount": "답글",
	"auditPerson": "검토자",
	"forumColor": "분야 색상",
	"forumColorFormTitle": "분야 색상 선택",
	"defaultForumColor" : "#7e7e7e",
	"optionsForumColors" : [
		["#ff4040","#ff421e","#ffbf18","#e1e100","#00e100","#00e1ad","#00e0e0","#0082bf","#0080ff","#4181ff","#8242ff","#c140ff","#ff42f9","#ff40a0","#ff4070","#606060"],
		["#ff1f35","#ff1f10","#ff8100","#bfbf00","#00c200","#00c197","#00c1c2","#4181c0","#0062e1","#4141ff","#4200ff","#c200ff","#ff22ff","#f52b97","#ff2259","#5f5f5f"],
		["#e01f25","#e12000","#e26200","#a1a100","#00a000","#009f82","#3f8080","#0060a0","#0041c2","#0021bf","#4100c2","#8100ff","#ff00ff","#ff0080","#79656a","#4f4f4f"],
		["#c20000","#ff0000","#bf4100","#80803f","#3f803f","#008250","#006062","#004080","#001fe2","#0021bf","#4000a2","#6000a1","#e000e0","#df007f","#c20041","#3f3f3f"],
		["#a00000","#e10000","#a13f00","#626200","#006000","#00603c","#004041","#002f80","#0000ff","#2020a0","#2200a1","#400080","#a1009f","#c0007f","#9f000f","#2f2f2f"],
		["#600000","#c21212","#824200","#424200","#004200","#004023","#00323f","#002060","#0020c2","#2222c0","#000080","#1f007f","#800080","#820040","#800000","#1f1f1f"],
		["#400000","#a11f12","#604200","#212100","#002100","#00201f","#002041","#00204f","#0000e0","#0000a1","#000061","#1f0062","#40005f","#620042","#620012","#0f0f0f"]
	],
	"selectColor": "색상 선택",
	"selectList": "목록 선택",
	"effect": "효과",
	"column": "열",
	"mainSection": "주요 섹션",
	"welcomeTitle": "{user}, 안녕하세요!",
	"seePersonCenter": "개인 센터 보기를 클릭하십시오",
	"closeNavi": "내비게이션 닫기",
	"navi": "내비게이션",
	"naviLayout": "내비게이션 레이아웃",

	"sectionName": "섹션 이름",
	"mainSectionName": "주요 섹션 이름",
	"sectionLevel": "섹션 레벨",
	"sectionLevelValue": "주요 섹션, 하위 섹션",
	"sectionDescription": "섹션 설명",
	"sectionNotice": "섹션 공지",
	"sectionVisible": "섹션 표시 가능 범위",
	"sectionVisibleValue": "모두, 권한에 따라",
	"replyVisible": "답글 표시 가능 범위",
	"replyVisibleValue": "모두, 권한에 따라",
	"subjectPublishAble": "게시 가능 범위",
	"subjectPublishAbleValue": "모두, 권한에 따라",
	"replyPublishAble": "답글 가능 범위",
	"replyPublishAbleValue": "모두, 권한에 따라",
	"moderatorNames": "모니터",
	"sectionType": "유형",
	"sectionTypeValue": "클래식, 이미지 뉴스, 일반 뉴스, 공지",
	"subSectionCreateAble": "하위 섹션 생성 허용",
	"sectionStatus": "상태",
	"sectionStatusValue": "사용 중, 사용 중지",
	"sectionGrade": "등급",
	"sectionGradeValue": "아니요, 예",
	"sectionIcon": "섹션 아이콘",
	"uploadIcon": "로컬 아이콘 업로드",
	"selectIcon": "아이콘 선택",
	"sectionIconFormTitle": "섹션 아이콘 선택",
	"indexRecommenPerson": "추천인",

	"permissionFormTitle": "권한 설정",
	"permissionType": "권한 유형",
	"permissionTypeValue": "포럼 권한, 섹션 권한, 기타 권한",
	"permissionName": "권한 이름",
	"permissionCode": "권한 코드",
	"description": "설명",
	"create": "생성",

	"roleFormTitle": "역할 설정",
	"createRole": "역할 설정 생성",
	"roleType": "역할 유형",
	"roleTypeValue": "포럼 역할, 섹션 역할",
	"roleName": "역할 이름",
	"roleCode": "역할 코드",
	"selectPerson": "사용자 선택",
	"selectDepartment": "조직 선택",
	"selectCompany": "회사 선택",

	"recommanded": "추천",
	"subject": "주제",
	"allSubject": "모든 주제",
	"selectSubjectType": "주제 유형 선택",
	"recommandedSubject": "추천 주제",
	"primeSubject": "우수 주제",
	"type": "유형",
	"typeValue": "토론, 투표, 뉴스, 보상, 토론, 물 흐르기, 지식, 동향",
	"subjectType": "주제 유형 옵션",
	"subjectTypeDefaultValue": "토론|뉴스|동향|지식|물 흐르기",
	"vote": "투표",
	"sectionApp": "앱 마켓",
	"typeCategoryDefaultValue": "정보|질문|투표",
	"typeCatagory": "주제 유형 옵션",
	"typeCategorySelectValue": "정보|질문|투표",
	"portalImage": "홈페이지 이미지",
	"summary": "요약",
	"content": "내용",
	"createSubject": "게시물 작성",
	"anonymousSubject": "익명으로 게시",
	"saveSubject": "게시물 저장",
	"selectCurrentDocumentFile": "게시물 이미지 선택",
	"selectCloudFile": "클라우드 파일 이미지 선택",
	"insertUrl": "이미지 링크 삽입",
	"voteLimitTime": "투표 시간 제한",
	"voteResultVisible": "투표 결과 표시",
	"votePersonVisible": "투표자 개인 정보 보호",
	"votePersonValue": "공개, 익명",
	"voteOptions": "투표 옵션",
	"option": "옵션",
	"opt": "항목",
	"voteCountLimit": "선택 허용 수 제한",
	"group": "그룹",
	"addVoteGroup": "투표 그룹 추가",
	"removeVoteGroup": "이 그룹 삭제",
	"confirmRemoveVoteGroupTitle": "투표 그룹 삭제 확인",
	"confirmRemoveVoteGroupContent": "이 그룹을 삭제하시겠습니까?",
	"confirmPublishVoteDocumentTitle": "게시 확인",
	"confirmPublishVoteDocumentContent": "이 게시물은 투표 게시물입니다. 투표의 진정성을 보장하기 위해 게시 후 수정할 수 없습니다. 게시물을 작성하시겠습니까?",
	"voteSubject": "투표 주제",

	"timeToEndText": "，종료까지 {time} 남았습니다",
	"voteCompleteText": "，투표가 이미 종료되었습니다",
	"votedPersonCountText": "，현재 {count}명이 참여하였습니다",
	"noPersonVoteText": "，현재 아무도 참여하지 않았습니다",
	"privateVoteText": "비공개 투표로, 투표 결과는 게시자만 볼 수 있습니다",
	"publicVoteText": "(공개 투표로, 다른 사람이 귀하의 투표 항목을 볼 수 있습니다)",
	"anonymousVoteText": "(익명 투표로, 다른 사람은 귀하의 투표 항목을 확인할 수 없습니다)",
	"submit": "제출",
	"youAreVoted": "이미 투표하셨습니다. 참여해 주셔서 감사합니다",
	"picture": "이미지",
	"word": "텍스트",
	"multiSelectText": "다중 선택 (최대 {n} 항목 선택 가능):",
	"singleSelectText": "단일 선택:",
	"uploadPicture": "이미지 업로드",
	"notSelectGroupNotice": "각 그룹에서 적어도 하나를 선택한 후 제출하십시오",
	"notSelectItemNotice": "적어도 하나를 선택한 후 제출하십시오",
	"second": "초",
	"minute": "분",
	"hour": "시간",
	"seeVotedPerson": "투표 참여자 확인",
	"group1": "그룹:",
	"option1": "옵션:",

	"attachmentArea": "첨부 파일 영역",
	"selectAttachment": "첨부 파일 선택",
	"attachment": "첨부 파일",
	"bindObject": "오브젝트",
	"replyAndReadCount": "댓글/조회수",
	"lastReply": "마지막 댓글",
	"acceptReplySuccess": "답변 수락 성공",

	"readed": "읽음",
	"reply": "답장",
	"allReply": "모든 답장",
	"accessed": "인기",
	"prime": "추천",
	"sType": "주제 유형 필터링",
	"experience": "경험",
	"nextSubject": "다음 주제",
	"prevSubject": "이전 주제",
	"floor": "층",
	"mainFloor": "메인 층",
	"publishAt": "게시 일시",
	"at": "에서",
	"saveReply": "답장 저장",
	"noNextSubject": "현재 마지막 주제입니다",
	"noPrevSubject": "현재 첫 번째 주제입니다",
	"recommandSubject": "최신 추천",
	"replyFormTitle": "주제에 답장",
	"setRecommend": "홈페이지에 추천",
	"cancelRecommend": "추천 취소",
	"setTop": "상단에 고정",
	"cancelTop": "고정 취소",
	"setPrime": "프라임 설정",
	"setRecommendSuccess": "홈페이지에 추천 성공",
	"cancelRecommendSuccess": "추천 취소 성공",
	"saveReplySuccess": "답장 성공",
	"deleteReplySuccess": "답장 삭제 성공",
	"deleteReplyTitle": "답장 삭제",
	"deleteReplyText": "삭제하면 되돌릴 수 없으며, 이 답장을 삭제하시겠습니까?",
	"quoteReplyBeingDeleted": "인용한 답장이 이미 삭제되었습니다!",
	"setPrimeSuccess": "프라임 설정 성공",
	"cancelPrime": "프라임 취소",
	"cancelPrimeSuccess": "프라임 취소 성공",

	"moveto": "이동",
	"lock": "잠금",
	"unlock": "잠금 해제",
	"lockSuccess": "게시물을 잠금 설정하였으며, 댓글이 불가능합니다.",
	"unlockSuccess": "게시물 잠금이 해제되었으며, 댓글이 가능합니다.",
	"topFormTitle": "상단 고정 설정",
	"topType": "다중 선택 가능한 상단 고정 유형을 선택하세요:",
	"topTypeText": "홈 상단 고정, 분할 상단 고정, 게시판 상단 고정",
	"topTypeValue": "bbs,forum,section",
	"setTopSuccess": "상단 고정 설정 완료",
	"setToFail": "상단 고정 설정 실패",
	"cancelTopSuccess": "상단 고정 해제 완료",
	"topToBBS": "홈 상단 고정",
	"topToForum": "분할 상단 고정",
	"topToSection": "게시판 상단 고정",
	"returnToList": "목록으로 돌아가기",
	"invalid": "비활성화",
	"personCenter": "개인 센터",
	"company": "회사",
	"department": "부서",
	"mail": "이메일",
	"weixin": "WeChat",
	"mobile": "휴대전화",
	"signature": "서명",
	"mySubject": "내 게시물",
	"myReply": "내 답장",
	"hisSubject": "그의 게시물",
	"herSubject": "그녀의 게시물",
	"replyContent": "답장 내용",
	"replyTime": "답장 시간",
	"changePersonSetting": "개인 정보 수정",
	"sendMessage": "메시지 보내기",
	"todaySubject": "오늘의 주제",
	"todayReply": "오늘의 답장",
	"replyTo": "답장",
	"newSubjectPublishedText": "{count}개의 새 주제가 게시되었습니다. 확인하려면 클릭하세요.",

	"hotPicture": "핫 이미지",
	"cancelHotPicture": "핫 이미지 취소",
	"setHot": "핫 설정",
	"setHotPicture": "핫 이미지 설정",
	"setHotLinkSuccess": "핫 이미지 설정 성공",
	"cancelHotLinkSuccess": "핫 이미지 취소 성공",
	"selectDocPicture": "문서 이미지 선택",
	"selectFilePicture": "클라우드 파일 이미지 선택",
	"hotLinkDescription": "참고: 선택한 이미지는 이 플랫폼 모바일 앱의 상단 이미지로 사용되며, 최적의 세로 가로 비율은 1:2입니다.",
	"unselectHotPic": "먼저 이미지를 선택하십시오",
	"cancelHotPicComfirmTitle": "핫 이미지 취소",
	"cancelHotPicComfirmContent": "이 문서의 핫 이미지를 취소하시겠습니까?",
	"replyNeedLoginText": "회답을 위해 로그인이 필요합니다",
	"signUp": "회원가입",
	"satisfiedReply": "답변 확인",
	"satisfiedAnswer": "만족스러운 답변",
	"question": "질문",
	"gotoTop": "맨 위로 이동",
	"forumConfig": "포럼 설정",
	"yesterday": "어제",
	"twoDaysAgo": "그제",
	"weekAgo": "주 전",
	"dayAgo": "일 전",
	"hourAgo": "시간 전",
	"minuteAgo": "분 전",
	"justNow": "방금",
	"publishJustNow": "방금 게시됨",
	"gradeNotice": "평가 후 제출해주세요",

	"selectTargetSection": "이동할 섹션 선택",
	"moveSuccess": "게시물이 {section}(으)로 이동되었습니다.",
	"editPermissionFormTitle": "편집 권한 설정",
	"editorSetting": "편집자",
	"setEditorSuccess": "편집 권한 설정 성공!",
	"setEditorFail": "편집 권한 설정 오류!",
	"addMutePerson": "음소거 대상 추가",
	"mute1SettingFormTitle": "음소거 대상 설정",
	"mutePerson": "음소거 대상",
	"muteTime": "음소거 시간",
	"unmuteDate": "해제 날짜",
	"unmuteDateNote": "만료 후 자동으로 음소거가 해제됩니다",
	"unmute": "음소거 해제",
	"unmuteTitle": "음소거 해제 확인",
	"unmuteDocument": "{person}의 음소거를 해제하시겠습니까?",
	"multReason": "음소거 이유",
	"unmuteSuccess": "음소거가 성공적으로 해제되었습니다!",
	"unmuteTimeUnvalid": "해제 날짜는 오늘보다 미래 날짜여야 합니다",
	"muteNote": "음소거되었습니다. 게시물 작성과 답변이 불가능합니다.",
	"muteInfor": "해제 날짜: {unmuteDate}, 음소거 이유: {reason}",
	"poster": "게시자"

};