MWF.xApplication.Forum = MWF.xApplication.Forum || {};
MWF.xApplication.Forum.LP = {
	"title": "Forum Homepage",
	"delete" : "ລົບ",
	"deleteDocumentTitle": "ຢືນຢັນລົບ",
	"deleteDocument": "ເຈົ້າແນ່ໃຈບໍວ່າຕ້ອງກນລົບ?",
	"deleteDocumentOK": "ລົບສຳເລັດ",
	"createSuccess" : "ສ້າງສຳເລັດ",
	"updateSuccess" : "ອັບເດດສຳເລັດ",
	"createReplySuccess" : "ຕອບກັບສຳເລັດ",
	"inputName" : "ກະລຸນາຢືນຢັນຊື່",
	"deleteAttachmentTitle" : "ຢືນຢັນລົບເອກະສານ",
	"deleteAttachment" : "ເຈົ້າແນ່ໃຈບໍວ່າຕ້ອງການລົບເອກະສານ？",
	"search" : "ຄົ້ນຫາ",
	"searchKey" : "ກະລຸນາຢືນຢັນການຄົ້ນຫາ",
	"searchTitle" : "ຄຳຫຼັກອາດເປັນຫົວຂໍ້、ພື້ນທີ່、sections、ຜູ້ສ້າງ",
	"searchTitleNick": "ຄຳຫຼັກອາດເປັນຫົວຂໍ້、ພື້ນທີ່、sections",
	"noSearchContentNotice" : "ກະລຸນາຢືນຢັນການຄົ້ນຫາຄຳຫຼັກ，ດຳເນີນການຄົ້ນຫາ",

	"dateFormatMonth": "%Yປີ%mເດືອນ",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%mເດືອນ%dມື້",
	"dateFormat": "db",
	"SelectOrgForm" : "ເລືອກອົງກອນ",

	"month" : "ເດືອນ",
	"today" : "ມື້ນີ້",
	"day" : "ມື້",

	"cancel" : "ຍົກເລີກ",
	"close" : "ປິດ",
	"ok" : "ຕົກລົງ",
	"edit" : "ແກ້ໄຂ",
	"remove" : "ລົບ",
	"action" : "ດຳເນີນ",

	"login" : "ເຂົ້າລະບົບ",
	"signup" : "ລົງທະບຽນ",
	"logout" : "ອອກຈາກລະບົບ",

	"name" : "ຊື່",
	"create_cancel_title": "ຢືນຢັນຍົກເລີກໃໝ່",
	"create_cancel": "ເຈົ້າແນ່ໃຈບໍວ່າຕ້ອງການຍົກເລີກສ້າງໃໝ່?",

	"systemSettingFormTitle" : "ຕັ້ງຄ່າລະບົບ",
	"configName" : "ຕັ້ງຄ່າຊື່",
	"configCode" : "ຕັ້ງຄ່າລະຫັດ",
	"configValue" : "ຕັ້ງຄ່າຄ່າ",

	"categoryManager" : "ຜູ້ຈັດການ",
	"setting" : "ຕັ້ງຕ່າ",
	"createCategory" : "ສ້າງພື້ນທີ່",
	"createSection" : "ສ້າງ Section",
	"categoryFormTitle" : "ຕັ້ງຄ່າພື້ນທີ່",
	"sectionFormTitle" : "ຕັ້ງຄ່າSection",
	"muteSettingFormTitle": "ຈັດການປິດສຽງ",

	"baseSetting" : "ຕິດຕັ້ງເລີ່ມຕົ້ນ",
	"permissionSetting" : "ການອະນຸຍາດຕັ້ງຄ່າ",


	"forumName" : "ຊື່ພື້ນທີ່",
	"forumManagerName" : "ພະນັງານຈັດການພື້ນທີ່",
	"forumNotice" : "Notice",
	"forumVisible" : "ຜູ້ໃຊ້ເຫັນໄດ້",
	"forumVisibleButton" : "ເລືອກຜູ້ໃຊ້ໃຫ້ເຫັນ",
	"allPerson" : "ທັງໝົດທຸກຄົນ",
	"byPermission" : "ການອະນຸຍາດ",
	"forumVisibleValue" : "ໝົດທຸກຄົນ,ອະນຸຍາດ",
	"indexListStyle" : "ລາຍການ Home Page",
	"indexListStyleValue" : "ທຳມະດາ,ສີ່ແຈທຳມະດາ,ຮູບສາມແຈ",
	"indexListStyleButton" : "ເລືອກຮູບແບບ Home Page",
	"selectIndexType" : "ເລືອກຮູບແບບ Home Page",
	"all" : "ທັງໝົດ",
	"all1" : "ທັງໝົດ",
	"disable" : "ຢຸດໃຊ້",
	"typeColumn" : "ຈຳວນຖັນ",
	"indexListStyleImage" : "ຮູບສີ່ແຈ",
	"forumIndexStyle" : "ຮູບແບບພື້ນທີ່ Homepage",
	"forumIndexStyleValue" : "ທຳມະດາ,ໃໝ່,ຮູບ",
	"indexRecommendable" : "ອະນຸຍາດແນນະໄປທີ່ Homepage ",
	"subjectNeedAudit" : "ຫົວຂໍ້ຕ້ອງການກວດສອບ",
	"replyNeedAudit" : "ກນຕອບກັບຕ້ອງການກວດສອບ",
	"sectionCreateAble" : "ອະນຸຍາດໃຫ້ສ້າງ section ",
	"sectionTotal" : "ຈຳນວນ section",
	"subjectTotal" : "ຈຳນວນຫົວຂໍ້",
	"replyTotal" : "ຈຳນວນຕອບກັບ",
	"creatorName" : "ຜູ້ສ້າງ",
	"forumStatus" : "ສະນາຖະພື້ນທີ່",
	"forumStatusValue" : "ໃຊ້ງານ,ຢຸດໃຊ້ງານ",
	"orderNumber" : "ລຳດັບເລກທີ",
	"yesOrNo" : "ແມ່ນ,ບໍ່",
	"yes" : "ແມ່ນ",
	"owneForum" : "Forum ເປັນຂອງ",
	"createTime" : "ແກ້ໄຂເວລາ",
	"time" : "ເວລາ",
	"create" : "ສ້າງ",
	"replyCount" : "ຕອບກັບ",
	"auditPerson" : "ຜູ້ກວດສອບ",
	"forumColor" : "ພື້ນທີ່ສີ",
	"forumColorFormTitle" : "ເລືອກພື້ນທີສີ",
	"defaultForumColor" : "#7e7e7e",
	"optionsForumColors" : [
		["#ff4040","#ff421e","#ffbf18","#e1e100","#00e100","#00e1ad","#00e0e0","#0082bf","#0080ff","#4181ff","#8242ff","#c140ff","#ff42f9","#ff40a0","#ff4070","#606060"],
		["#ff1f35","#ff1f10","#ff8100","#bfbf00","#00c200","#00c197","#00c1c2","#4181c0","#0062e1","#4141ff","#4200ff","#c200ff","#ff22ff","#f52b97","#ff2259","#5f5f5f"],
		["#e01f25","#e12000","#e26200","#a1a100","#00a000","#009f82","#3f8080","#0060a0","#0041c2","#0021bf","#4100c2","#8100ff","#ff00ff","#ff0080","#79656a","#4f4f4f"],
		["#c20000","#ff0000","#bf4100","#80803f","#3f803f","#008250","#006062","#004080","#001fe2","#0021bf","#4000a2","#6000a1","#e000e0","#df007f","#c20041","#3f3f3f"],
		["#a00000","#e10000","#a13f00","#626200","#006000","#00603c","#004041","#002f80","#0000ff","#2020a0","#2200a1","#400080","#a1009f","#c0007f","#9f000f","#2f2f2f"],
		["#600000","#c21212","#824200","#424200","#004200","#004023","#00323f","#002060","#0020c2","#2222c0","#000080","#1f007f","#800080","#820040","#800000","#1f1f1f"],
		["#400000","#a11f12","#604200","#212100","#002100","#00201f","#002041","#00204f","#0000e0","#0000a1","#000061","#1f0062","#40005f","#620042","#620012","#0f0f0f"]
	],
	"selectColor" : "ເລືອກສີ",
	"selectList" : "ເລືອກລາຍການ",
	"effect": "Effect",
	"column" : "ຖັນ",
	"mainSection": "Section ຫຼັກ",
	"welcomeTitle" : "{user},ສະບາຍດີ！",
	"seePersonCenter": "ກົດເບິ່ງ Personal Center",
	"closeNavi": "ປິດການນຳທາງ",
	"navi": "ນຳທາງ",
	"naviLayout": "ຮູບແບບການນຳທາງ",

	"sectionName" : "ຊື່ section ",
	"mainSectionName" : "ຊື່ section ໜັກ",
	"sectionLevel" : "ລະດັບ section",
	"sectionLevelValue" : "section ຫຼັກ,section ຍ່ອຍ",
	"sectionDescription" : "ບົດນຳ section ",
	"sectionNotice" : "ປະກາດ section",
	"sectionVisible" : "ຊ່ວງໄລຍະການເບິ່ງເຫັນ",
	"sectionVisibleValue" : "ທຸກຄົນ,ອີງຕາມການອະນຸຍາດ",
	"replyVisible" : "ຕອບກັບໄລຍະການເບິ່ງເຫັນ",
	"replyVisibleValue" : "ທຸກຄົນ,ອີງຈາມການອະນຸຍາດ",
	"subjectPublishAble" : "ໄລຍະການອະນຸຍາດໃຫ້ປະກາດ",
	"subjectPublishAbleValue" : "ທຸກຄົນ,ອີງຕາມການອະນຸຍາດ",
	"replyPublishAble" : "ຕອບກັບຊ່ວງໄລຍະອະນຸຍາດ",
	"replyPublishAbleValue" : "ທຸກຄົນ,ອີງຕາມກນອະນຸຍາດ",
	"moderatorNames" : "ຜູ້ຈັດການ",
	"sectionType" : "ປະເພດ",
	"sectionTypeValue" : "ທຳມະດາ,ຮູບຂ່າວ,ຂ່າວທົ່ວໄປ,ປະກາດ",
	"subSectionCreateAble" : "ອະນຸຍາດໃຫ້ສ້າງ Section ຍ່ອຍ ",
	"sectionStatus" : "ສະຖານະ",
	"sectionStatusValue" : "ເປີດໃຊ້ງານ,ປິດໃຊ້ງານ",
	"sectionGrade" : "ຄະແນນ",
	"sectionGradeValue" : "ບໍ່,ແມ່ນ",
	"sectionIcon" : "section Icon",
	"uploadIcon" : "ອັບໂຫລດ Icon ນຳທາງ",
	"selectIcon" : "ເລືອກສະຖານທີ່",
	"sectionIconFormTitle" : "ເລືອກ section Icon ",
	"indexRecommenPerson" : "ຜູ້ແນະນຳ",

	"permissionFormTitle" : "ຕັ້ງຄ່າອະນຸຍາດ",
	"permissionType" : "ໝວດໝູ່ການອະນຸຍາດ",
	"permissionTypeValue" : "Forum ອະນຸຍາດ,section ອະນຸຍາດ,ອະນຸຍາດອື່ນໆ",
	"permissionName" : "ຊື່ການອະນຸຍາດ",
	"permissionCode" : "ລະຫັດການອະນະຍາດ",
	"description" : "ອະທິບາຍ",
	"create" : "ສ້າງ",

	"roleFormTitle" : "ບົດບາດ ຟອມ",
	"createRole" : "ສ້າງຕັ້ງຄ່າໜ້າທີ່",
	"roleType" : "ປະເພດຕົວອັກສອນ",
	"roleTypeValue" : "Forum ບົດບາດ ,section ບົດບາດ ",
	"roleName" : "ຊື່ໜ້າທີ່",
	"roleCode" : "ລະຫັດໜ້າທີ່",
	"selectPerson" : "ເລືອກພະນັກງານ",
	"selectDepartment" : "ເລືອກອົງກອນ",
	"selectCompany" : "ເລືອກບໍລິສັດ",

	"recommanded" : "ແນະນຳ",
	"subject" : "ຫົວຂໍ້",
	"allSubject" : "ຫົວຂໍ້ທັງໝົດ",
	"selectSubjectType" : "ການກັ່ນຕອງປະເພດຫົວຂໍ້",
	"recommandedSubject" : "ແນະນຳຫົວຂໍ້",
	"primeSubject" : "ຫົວຂໍ້ສຳຄັນ",
	"type" : "ໝວດໝູ່",
	"typeValue" : "ອະພິປາຍ,ລົງຄະແນນສຽງ,ຂ່າວ,ລາງວັນ,ຕອບໂຕ້,ຊົນລະປະທານ,ຄວາມຮູ້,ຜົນວັດ",
	"subjectType" : "ຕົວເລືອກປະເພດຫົວຂໍ້",
	"subjectTypeDefaultValue" : "ອະພິບາຍ|ຂ່າວ|ວັດຜົນ|ຄວາມຮູ້|ຊົນລະປະທານ",
	"vote" : "ລົງຄະແນນສຽງ",
	"sectionApp" : "ຕະຫຼາດ ແອັບ",
	"typeCategoryDefaultValue" : "ຂໍ້ມູນ|ຄຳຖາມ|ໃຫ້ຄະແນນ",
	"typeCatagory" : "ຕົວເລືອກປະເພດຫົວຂໍ້",
	"typeCategorySelectValue" : "ຂໍ້ມູນ|ຄຳຖາມ|ໃຫ້ຄະແນນ",
	"portalImage" : "ຮູບໜ້າ Homepage",
	"summary" : "ຄຳນຳ",
	"content" : "ເນື້ອໃນ",
	"createSubject" : "ປະກາດ",
	"anonymousSubject" : "ປະກາດບໍ່ລະບຸຊື່",
	"saveSubject" : "ປະກາດ",
	"selectCurrentDocumentFile" : "ເລືອກຮູບປະກາດ",
	"selectCloudFile" : "ເລືອກຮູບ ຟາຍ Cloud",
	"insertUrl" : "ເລີ່ມລິ້ງຮູບ",
	"voteLimitTime" : "ກຳນົດເວລາໃຫ້ຄະແນນ",
	"voteResultVisible" : "ສາມາດເຫັນຜົນຄະແນນ",
	"votePersonVisible" : "ການເປັນສວນຕົວຂອງຄົນໃຫ້ຄະແນນ",
	"votePersonValue" : "ສາທາລະນະ,ບໍ່ລະບຸຊື່",
	"voteOptions" : "ຕົວເລືອກໃຫ້ຄະແນນ",
	"option" : "ຕົວເລືອກ",
	"opt" : "ລາຍການ",
	"voteCountLimit" : "ເລືອກສູງສຸດ",
	"group" : "ກຸ່ມ",
	"addVoteGroup" : "ເພີ່ມກຸ່ມໃຫ້ຄະແນນ",
	"removeVoteGroup" : "ລົບກຸ່ມອອກ",
	"confirmRemoveVoteGroupTitle" : "ຢືນຢັນກນລົບກຸ່ມ",
	"confirmRemoveVoteGroupContent" : "ເຈົ້າແນ່ໃຈບໍວ່າຕ້ອງການລົບກຸ່ມນີ້ອອກ？",
	"confirmPublishVoteDocumentTitle" : "ຢືນຢັນການປະກາດ",
	"confirmPublishVoteDocumentContent" : "ປະກາດນີ້ແມ່ນປະກາດການໃຫ້ຄະແນນ，ເພື່ອຮັບຮ້ອງຄວາມຖືກຕ້ອງ，ຈະບໍ່ສາມາດແກ້ໄຂໄດ້ຫຼັງຈາເຜີແຜ່，ເຈົ້າແນ່ໃຈບໍ ວ່າຕ້ອງການປະກາດສິ່ງນີ້？",
	"voteSubject" : "ຫົວຂໍ້ລົງຄະແນນ",

	"timeToEndText": "，ຍັງ{time}ກ່ອນຈະສິ້ນສຸດ",
	"voteCompleteText": "，ການລົງຄະແນນສິ້ນສຸດລົງແລ້ວ",
	"votedPersonCountText": "，ປະຈຸບັນມີ{count}ຄົນລົງສຽງ",
	"noPersonVoteText": "，ປະຈຸບັນຍັງບໍ່ຄົນລົງຄະແນນສຽງ",
	"privateVoteText": "ນີ້ແມ່ນການລົງຄະແນນສ່ວນຕົວ，ສະເພາະຜູ້ລາຍງານເທົ່ານັ້ນຈຶ່ງສາມາດເຫັນໄດ້",
	"publicVoteText": "(ນີ້ແມ່ນການລົງຄະແນນສຽງສາທາລະນະ，ຄົນອື່ນສາມາດເບິ່ງເຫັນໄດ້)",
	"anonymousVoteText": "(ນີ້ແມ່ນການໃຫ້ຄະແນນແບບບໍ່ລະບຸຊື່，ຜູ້ອື່ນບໍ່ສາມາດເບິ່ງການລົງຄະແນນຂອງເຈົ້າໄດ້)",
	"submit" : "ສົ່ງ",
	"youAreVoted": "ເຈົ້າໄດ້ລົງຄະແນນສຽງແລ້ວ，ຂອບໃຈສຳລັບລົງຄະແນນສຽງ",
	"picture": "ຮູບພາບ",
	"word": "ຕົວອັກສອນ",
	"multiSelectText" : "ເລືອກຫຼາຍ（ສາມາດເລືອກໄດ້ຫຼາຍສຸດ{n}ລາຍການ）：",
	"singleSelectText" : "ເລືອກອັນດຽວ：",
	"uploadPicture" : "ອັບໂຫລດຮູບ",
	"notSelectGroupNotice": "ກະລຸນາເລືອກຢ່າງໜ້ອຍໜ່ງລາຍການຈາກອົງກອນກ່ອນທີ່ຈະສົ່ງ",
	"notSelectItemNotice": "ກະລຸນາເລືອກຢ່າງໜ້ອຍໜຶ່ງລຍກນກ່ອນທີ່ຈະສົ່ງ",
	"second": "ວິນາທີ",
	"minute": "ນາທີ",
	"hour": "ຊົ່ວໂມງ",
	"seeVotedPerson": "ເບິ່ງຄົນລົງຄະແນນສຽງ",
	"group1": "ກຸ່ມ：",
	"option1": "ຕົວເລືອກ：",

	"attachmentArea" : "ພື້ນທີ່ເອກະສານ",
	"selectAttachment" : "ເລືອກເອກະສານ",
	"attachment" : "ເອກະສານຕິດຄັດ",
	"bindObject" : "ເລື່ອງ",
	"replyAndReadCount" : "ຕອບກັບ/ກວດເບິ່ງ",
	"lastReply" : "ຕອບກັບສຸດທ້າຍ",
	"acceptReplySuccess" : "ຍອມຮັບກນຕອບກັບສຳເລັດ",

	"readed" : "ອ່ານແລ້ວ",
	"reply" : "ຕອບກັບ",
	"allReply" : "ຕອບກັບທັງໝົດ",
	"accessed" : "ຄວາມນິຍົມ",
	"prime" : "ສ່ວນສຳຄັນ",
	"sType" : "ກັ່ນຕອງປະເພດຫົວຂໍ້",
	"experience" : "ປະສົບການ",
	"nextSubject" : "ຕໍ່ໄປ",
	"prevSubject" : "ກັບ",
	"floor" : "ຊັ້ນ",
	"mainFloor" : "ອາຄານຫຼັກ",
	"publishAt" : "ເຜີຍແຜ່ເມື່ອ",
	"at" : "ທີ່",
	"saveReply" : "ບັນທຶກການຕອບກັບ",
	"noNextSubject" : "ປະຈຸບັນແມ່ນຫົວຂໍ້ສຸດທ້າຍ",
	"noPrevSubject" : "ປະຈຸບັນແມ່ນຫົວຂໍ້ທຳອິດ",

	"recommandSubject" : "ແນະນຳ",
	"replyFormTitle" : "ຕອບກັບຫົວຂໍ້",
	"setRecommend" : "ແນະນຳທີ່ໜ້າ Homepage",
	"cancelRecommend" : "ຍົກເລີກການແນະນຳ",
	"setTop" : "ປັກມຸດ",
	"cancelTop" : "ຍົກເລີກການປັກມຸດ",
	"setPrime" : "ຕັ້ງຄ່າສ່ວນສຳຄັນ",
	"setRecommendSuccess" : "ແນະນຳ",
	"cancelRecommendSuccess" : "ຍົກເລີກການແນະນຳສຳເລັດ",
	"saveReplySuccess" : "ຕອບກັບສຳເລັດ",
	"deleteReplySuccess" : "ລົບການຕອບກັບສຳເລັດ",
	"deleteReplyTitle" : "ລົບການຕອບກັບ",
	"deleteReplyText" : "ລົບແລ້ວບໍ່ສາມາດກູ້ຄືນໄດ້，ຢືນຢັນເພື່ອລົບການຕອບກັບນີ້？",
	"quoteReplyBeingDeleted" : "ການຕອບກັບໄດ້ຖືກລົບແລ້ວ！",
	"setPrimeSuccess" : "ຕັ້ງຄ່າສ່ວນສຳຄັນສຳເລັດ",
	"cancelPrime" : "ຍົກເລີກສ່ວນສຳຄັນ",
	"cancelPrimeSuccess" : "ຍົກເລີກສ່ວນສຳຄັນສຳເລັດ",

	"moveto" : "ຍ້າຍໄປທີ່",
	"lock" : "ລ໋ອກ",
	"unlock" : "ປົດລ໋ອກ",
	"lockSuccess" : "ລ໋ອກປະກາດສຳເລັດ，ບໍ່ສາມາດຕອບກັບໄດ້",
	"unlockSuccess" : "ປົດລ໋ອກປະກາດສຳເລັດ，ສາມາດຕອບກັບໄດ້ແລ້ວ",
	"topFormTitle" : "ຕັ້ງຄ່າການປັກມຸດ",
	"topType" : "ກະລຸນາເລືອກປະເພດການປັກມຸດ，ອະນຸຍາດເລືອກໄດ້ຫຼາຍ：",
	"topTypeText" : "ປັກມຸດໜ້າເຈ້ຍ,ປັກມຸດພື້ນທີ່,ປັກມຸດ Section",
	"topTypeValue" : "bbs,forum,section",
	"setTopSuccess" : "ຕັ້ງຄ່າການປັກມຸດສຳເລັດ",
	"setToFail" : "ຕັ້ງຄ່າການປັກມຸດລົ້ມເລວ",
	"cancelTopSuccess" : "ຍົກເລີກການປັກມຸດສຳເລັດ",
	"topToBBS" : "ປັກມຸດໜ້າເຈ້ຍ",
	"topToForum" : "ປັກມຸດພື້ນທີ່",
	"topToSection" : "ປັກມຸດ Section",
	"returnToList" : "ກັບໄປທີ່ລາຍການ",
	"invalid" : "ຢຸດການໃຊ້ງານ",
	"personCenter" : "Personal Center",
	"company" : "ບໍລິສັດ",
	"department" : "ພະແນກ",
	"mail" : "ເມວ",
	"weixin" : "Wechat",
	"mobile" : "ໂທລະສັບ",
	"signature" : "ເຊັ່ນຊື່",

	"mySubject" : "ຫົວຂໍ້ຂອງຂ້ອຍ",
	"myReply" : "My reply",
	"hisSubject" : "ຫົວຂໍ້ຂອງລາວ(ຊາຍ)",
	"herSubject" : "ຫົວຂໍ້ຂອງລາວ(ຍິງ)",
	"replyContent" : "ເນື້ອໃນຕອບກັບ",
	"replyTime" : "ເວລາຕອບກັບ",
	"changePersonSetting" : "ແກ້ໄຂຂໍ້ມູນສວນຕົວ",
	"sendMessage" : "ຍົກເລີກຂໍ້ຄວາມ",
	"todaySubject" : "ຫົວຂໍ້ມື້ນີ້",
	"todayReply" : "ຕອບກັບມື້ນີ້",
	"replyTo" : "ຕອບກັບ",
	"newSubjectPublishedText" : "ມີຫົວຂໍ້ທີ່ເຜີຍແຜ່ໃໝ່{count}ລາຍການ，ກົດປຸມເພືອເບິ່ງ",

	"hotPicture" : "hotspot ຮູບພາບ",
	"cancelHotPicture" : "ຍົກເລີກ hotspot ",
	"setHot" : "hotspot",
	"setHotPicture" : "ຕັ້ງຄ່າhotspot",
	"setHotLinkSuccess" : "ຕັ້ງຄ່າhotspotສຳເລັດ",
	"cancelHotLinkSuccess" : "ຍົກເລີກhotspotສຳເລັດ",
	"selectDocPicture" : "ເລືອກຟາຍຮູບ",
	"selectFilePicture" : "ເລືອກ CLoud ຟາຍຮູບ",
	"hotLinkDescription" : "ໝາຍເຫດ：ຮູບທີ່ເລືອກຈະຖືກໃຊ້ເປັນຮູບພາບທາງເທິງຂອງ platform ໃນແອັບໂທລະສັບມືຖື，ອັດຕາສ່ວນຂອງຮູບພາບ1:2",
	"unselectHotPic" : "ກະລຸນາເລືອກຮູບ",
	"cancelHotPicComfirmTitle" : "ຍົກເລີກhotspot",
	"cancelHotPicComfirmContent" : "ເຈົ້າແນ່ໃຈ ບໍ ວ່າຕ້ອງການຍົກເລີກhotspotຂອງຟາຍນີ້？",
	"replyNeedLoginText" : "ເຈົ້າຕ້ອງການເຂົ້າສູ່ລະບົບເພື່ອຕອບກັບ",
	"signUp" : "ອອກຈາກລະບົບ",
	"satisfiedReply" : "ຍອມຮັບກນຕອບກັບ",
	"satisfiedAnswer" : "ຕອບກັບນ່າພໍໃຈ",
	"question" : "ຄຳຖາມ",

	"gotoTop" : "ສູງສຸດ",
	"forumConfig" : "ຕັ້ງຄ່າ Forum",

	"yesterday": "ມື້ວານ",
	"twoDaysAgo" : "2ມື້ທີ່ແລ້ວ",
	"weekAgo" : "ອາທິດກ່ອນ",
	"dayAgo" : "ມື້ທີ່ມາ",
	"hourAgo" : "ຊົ່ວໂມງທີ່ແລ້ວ",
	"minuteAgo" : "ນາທີ່ທີ່ແລ້ວ",
	"justNow" : "ຫາກໍ",
	"publishJustNow": "ຫາກໍເຜີຍແຜ່",

	"gradeNotice":"ກະລູນາໃຫ້ຄະແນນ ແລະ ສົ່ງ",

	"selectTargetSection" : "ເລືອກ Section ທີ່ຈະຍ້າຍໄປ",
	"moveSuccess": "ປະກາດຖືກຍ້າຍໄປທີ່{section}",

	"editPermissionFormTitle": "ກຳກົດສິດການແກ້ໄຂ",
	"editorSetting": "Editor",
	"setEditorSuccess": "ກຳນົດສິດການແກ້ໄຂສຳເລັດ！",
	"setEditorFail": "ຕັ້ງຄ່າການອະນຸຍາດລົ້ມເລວ！",

	"addMutePerson": "ເພີ່ມຄົນທີ່ຖືກຫ້າມ",
	"mute1SettingFormTitle": "ຕັ້ງຄ່າພະນັກງານທີ່ຖືກຫ້າມ",
	"mutePerson": "ພະນັກງານປິດສຽງ",
	"muteTime": "ເວລາປິດສຽງ",
	"unmuteDate": "ວັນທີເປີດສຽງ",
	"unmuteDateNote": "ປົດບລັອກອັດຕະໂນມັດຫຼັກຈາກໝົດກຳນົດ",
	"unmute": "ປົດບລັອກ",
	"unmuteTitle": "ຢືນຢັນປົດບລັອກ",
	"unmuteDocument": "ເຈົ້າແນ່ໃຈຫຼື ບໍວ່າເຈົ້າຕ້ອງການຫ້າມ:{person}？",
	"multReason": "ເຫດຜົນປິດສຽງ",
	"unmuteSuccess": "ເປີດສຽງສຳເລັດ!",
	"unmuteTimeUnvalid": "ການປົດບລັອກຕ້ອງຊ້າກວ່າມື້ນີ້",
	"muteNote": "ຈົ້າຖກປິດສຽງແລ້ວ，ບໍ່ສາມາດປະກາດຫຼື ຕອບໄດ້。",
	"muteInfor": "ວັນທີ່ປົດບລັອກ：{unmuteDate}，ເຫດຜົນ：{reason}。",
	"poster": "ຄົນປະກາດ"

};