MWF.xApplication.Forum = MWF.xApplication.Forum || {};
MWF.xApplication.Forum.LP = {
	"title": "论坛首页",
	"delete" : "删除",
	"deleteDocumentTitle": "删除确认",
	"deleteDocument": "您确定要删除吗?",
	"deleteDocumentOK": "删除成功",
	"createSuccess" : "创建成功",
	"updateSuccess" : "更新成功",
	"createReplySuccess" : "回复成功",
	"inputName" : "请输入名称",
	"deleteAttachmentTitle" : "删除附件确认",
	"deleteAttachment" : "您确定要删除该附件吗？",
	"search" : "搜索",
	"searchKey" : "请输入搜索关键字",
	"searchTitle" : "关键字可以是主题、分区、板块、创建人",
	"noSearchContentNotice" : "请输入搜索关键字，再执行搜索",

	"dateFormatMonth": "%Y年%m月",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%m月%d日",
	"dateFormat": "db",
	"SelectOrgForm" : "人员组织选择",

	"month" : "月",
	"today" : "今天",
	"day" : "天",

	"cancel" : "取消",
	"close" : "关闭",
	"ok" : "确定",
	"edit" : "编辑",
	"remove" : "删除",
	"action" : "操作",

	"login" : "登录",
	"signup" : "注册",
	"logout" : "注销",

	"name" : "姓名",
	"create_cancel_title": "取消新建确认",
	"create_cancel": "您确定要取消新建吗?",

	"systemSettingFormTitle" : "系统设置",
	"configName" : "配置名称",
	"configCode" : "配置编码",
	"configValue" : "配置值",

	"categoryManager" : "分区版主",
	"setting" : "设置",
	"createCategory" : "创建分区",
	"createSection" : "创建版块",
	"categoryFormTitle" : "分区设置",
	"sectionFormTitle" : "版块设置",

	"baseSetting" : "基本设置",
	"permissionSetting" : "权限设置",


	"forumName" : "分区名称",
	"forumManagerName" : "分区管理员",
	"forumNotice" : "分区公告",
	"forumVisible" : "可见用户",
	"forumVisibleButton" : "选择可见用户",
	"allPerson" : "所有人",
	"byPermission" : "根据权限",
	"forumVisibleValue" : "所有人,根据权限",
	"indexListStyle" : "首页样式列表",
	"indexListStyleValue" : "经典,简单矩形,图片矩形",
	"indexListStyleButton" : "选择首页样式",
	"selectIndexType" : "选择首页样式",
	"all" : "所有",
	"typeColumn" : "每行列数",
	"indexListStyleImage" : "图片矩形",
	"forumIndexStyle" : "分区主页样式",
	"forumIndexStyleValue" : "经典,新闻,照片",
	"indexRecommendable" : "允许推荐到首页",
	"subjectNeedAudit" : "主题需要审核",
	"replyNeedAudit" : "回复需要审核",
	"sectionCreateAble" : "允许创建版块",
	"sectionTotal" : "版块数量",
	"subjectTotal" : "主题数量",
	"replyTotal" : "回复数量",
	"creatorName" : "创建人",
	"forumStatus" : "分区状态",
	"forumStatusValue" : "启用,停用",
	"orderNumber" : "排序号",
	"yesOrNo" : "是,否",
	"yes" : "是",
	"owneForum" : "所属分区",
	"createTime" : "创建时间",
	"time" : "时间",
	"create" : "创建",
	"replyCount" : "回复",
	"auditPerson" : "审核人",
	"forumColor" : "分区颜色",
	"forumColorFormTitle" : "选择分区颜色",
	"defaultForumColor" : "#7e7e7e",
	"optionsForumColors" : [
		["#ff4040","#ff421e","#ffbf18","#e1e100","#00e100","#00e1ad","#00e0e0","#0082bf","#0080ff","#4181ff","#8242ff","#c140ff","#ff42f9","#ff40a0","#ff4070","#606060"],
		["#ff1f35","#ff1f10","#ff8100","#bfbf00","#00c200","#00c197","#00c1c2","#4181c0","#0062e1","#4141ff","#4200ff","#c200ff","#ff22ff","#f52b97","#ff2259","#5f5f5f"],
		["#e01f25","#e12000","#e26200","#a1a100","#00a000","#009f82","#3f8080","#0060a0","#0041c2","#0021bf","#4100c2","#8100ff","#ff00ff","#ff0080","#79656a","#4f4f4f"],
		["#c20000","#ff0000","#bf4100","#80803f","#3f803f","#008250","#006062","#004080","#001fe2","#0021bf","#4000a2","#6000a1","#e000e0","#df007f","#c20041","#3f3f3f"],
		["#a00000","#e10000","#a13f00","#626200","#006000","#00603c","#004041","#002f80","#0000ff","#2020a0","#2200a1","#400080","#a1009f","#c0007f","#9f000f","#2f2f2f"],
		["#600000","#c21212","#824200","#424200","#004200","#004023","#00323f","#002060","#0020c2","#2222c0","#000080","#1f007f","#800080","#820040","#800000","#1f1f1f"],
		["#400000","#a11f12","#604200","#212100","#002100","#00201f","#002041","#00204f","#0000e0","#0000a1","#000061","#1f0062","#40005f","#620042","#620012","#0f0f0f"]
	],
	"selectColor" : "选择颜色",

	"sectionName" : "版块名称",
	"mainSectionName" : "主版块名称",
	"sectionLevel" : "版块级别",
	"sectionLevelValue" : "主版块,子版块",
	"sectionDescription" : "版块简介",
	"sectionNotice" : "版块公告",
	"sectionVisible" : "版块可见范围",
	"sectionVisibleValue" : "所有人,根据权限",
	"replyVisible" : "回复可见范围",
	"replyVisibleValue" : "所有人,根据权限",
	"subjectPublishAble" : "允许发帖范围",
	"subjectPublishAbleValue" : "所有人,根据权限",
	"replyPublishAble" : "允许回复范围",
	"replyPublishAbleValue" : "所有人,根据权限",
	"moderatorNames" : "版主",
	"sectionType" : "类型",
	"sectionTypeValue" : "经典,图片新闻,普通新闻,公告",
	"subSectionCreateAble" : "允许创建子版块",
	"sectionStatus" : "状态",
	"sectionStatusValue" : "启用,停用",
	"sectionIcon" : "版块图标",
	"uploadIcon" : "上传本地图标",
	"selectIcon" : "选择图标",
	"sectionIconFormTitle" : "选择版块图标",
	"indexRecommenPerson" : "推荐人",

	"permissionFormTitle" : "权限设置",
	"permissionType" : "权限类别",
	"permissionTypeValue" : "论坛权限,版块权限,其他权限",
	"permissionName" : "权限名称",
	"permissionCode" : "权限代码",
	"description" : "说明",
	"create" : "创建",

	"roleFormTitle" : "角色设置",
	"createRole" : "创建角色设置",
	"roleType" : "角色类别",
	"roleTypeValue" : "论坛角色,版块角色",
	"roleName" : "角色名称",
	"roleCode" : "角色代码",
	"selectPerson" : "选择人员",
	"selectDepartment" : "选择组织",
	"selectCompany" : "选择公司",

	"recommanded" : "推荐",
	"subject" : "主题",
	"allSubject" : "全部主题",
	"recommandedSubject" : "推荐主题",
	"primeSubject" : "精华主题",
	"type" : "类别",
	"typeValue" : "讨论,投票,新闻,悬赏,辩论,灌水,知识,动态",
	"subjectType" : "主题类别选项",
	"subjectTypeDefaultValue" : "讨论|新闻|动态|知识|灌水",
	"vote" : "投票",
	"typeCategoryDefaultValue" : "信息|问题|投票",
	"typeCatagory" : "主题类型选项",
	"typeCategorySelectValue" : "信息|问题|投票",
	"portalImage" : "首页图片",
	"summary" : "摘要",
	"content" : "内容",
	"createSubject" : "发帖",
	"saveSubject" : "发表帖子",
	"selectCurrentDocumentFile" : "选择帖子图片",
	"selectCloudFile" : "选择云文件图片",
	"insertUrl" : "插入图片链接",
	"voteLimitTime" : "投票时限",
	"voteResultVisible" : "投票结果可见",
	"votePersonVisible" : "投票人隐私",
	"votePersonValue" : "公开,匿名",
	"voteOptions" : "投票选项",
	"option" : "选项",
	"opt" : "项",
	"voteCountLimit" : "最多允许选择",
	"group" : "组",
	"addVoteGroup" : "添加投票组",
	"removeVoteGroup" : "删除此组",
	"confirmRemoveVoteGroupTitle" : "删除投票组确认",
	"confirmRemoveVoteGroupContent" : "确认删除此投票组？",
	"confirmPublishVoteDocumentTitle" : "发帖确认",
	"confirmPublishVoteDocumentContent" : "该帖子是投票帖，为了保证投票真实性，发布后不能再修改，确定要发表帖子？",
	"voteSubject" : "投票主题",

	"attachment" : "附件",
	"bindObject" : "对象",
	"replyAndReadCount" : "回复/查看",
	"lastReply" : "最后回复",
	"acceptReplySuccess" : "采纳回复成功",

	"readed" : "阅读",
	"reply" : "回复",
	"allReply" : "全部回复",
	"accessed" : "人气",
	"prime" : "精华",
	"experience" : "经验",
	"nextSubject" : "下一主题",
	"prevSubject" : "上一主题",
	"floor" : "楼",
	"mainFloor" : "主楼",
	"publishAt" : "发表于",
	"at" : "于",
	"saveReply" : "发表回复",
	"noNextSubject" : "当前已是最后一个主题",
	"noPrevSubject" : "当前已是第一个主题",

	"recommandSubject" : "最新推荐",
	"replyFormTitle" : "回复主题",
	"setRecommend" : "推荐到首页",
	"cancelRecommend" : "取消推荐",
	"setTop" : "置顶",
	"cancelTop" : "取消置顶",
	"setPrime" : "设置精华",
	"setRecommendSuccess" : "推荐到首页成功",
	"cancelRecommendSuccess" : "取消推荐成功",
	"saveReplySuccess" : "回复成功",
	"deleteReplySuccess" : "删除回复成功",
	"deleteReplyTitle" : "删除回复",
	"deleteReplyText" : "删除后无法恢复，确定删除此回复？",
	"quoteReplyBeingDeleted" : "引用的回复已被删除！",
	"setPrimeSuccess" : "设置精华成功",
	"cancelPrime" : "取消精华",
	"cancelPrimeSuccess" : "取消精华成功",

	"moveto" : "移动到",
	"lock" : "锁定",
	"unlock" : "解锁",
	"lockSuccess" : "锁定帖子成功，帖子不能回复了",
	"unlockSuccess" : "解锁帖子成功，帖子可以回复了",
	"topFormTitle" : "设置置顶",
	"topType" : "请选择置顶的类型，允许多选：",
	"topTypeText" : "首页置顶,分区置顶,版块置顶",
	"topTypeValue" : "bbs,forum,section",
	"setTopSuccess" : "置顶设置成功",
	"setToFail" : "置顶设置失败",
	"cancelTopSuccess" : "置顶取消成功",
	"topToBBS" : "首页置顶",
	"topToForum" : "分区置顶",
	"topToSection" : "版块置顶",
	"returnToList" : "返回列表",
	"invalid" : "停用",
	"personCenter" : "个人中心",
	"company" : "公司",
	"department" : "部门",
	"mail" : "邮件",
	"weixin" : "微信",
	"mobile" : "手机",
	"signature" : "签名",

	"mySubject" : "我的发帖",
	"myReply" : "我的回复",
	"hisSubject" : "他的发帖",
	"herSubject" : "她的发帖",
	"replyContent" : "回复内容",
	"replyTime" : "回复时间",
	"changePersonSetting" : "修改个人信息",
	"sendMessage" : "发送消息",
	"todaySubject" : "今日主题",
	"todayReply" : "今日回复",
	"replyTo" : "回复",
	"newSubjectPublishedText" : "有新发布的{count}个主题，点击查看",

	"hotPicture" : "热点图片",
	"cancelHotPicture" : "取消热点",
	"setHot" : "热点",
	"setHotPicture" : "设置热点",
	"setHotLinkSuccess" : "设置热点图片成功",
	"cancelHotLinkSuccess" : "取消热点图片成功",
	"selectDocPicture" : "选择文档图片",
	"selectFilePicture" : "选择云文件图片",
	"hotLinkDescription" : "注：选择的图片将作为本平台移动端APP的顶部图片，图片的最佳高宽比为1:2",
	"unselectHotPic" : "请先选择图片",
	"cancelHotPicComfirmTitle" : "取消热点",
	"cancelHotPicComfirmContent" : "确定取消该文档的热点？",
	"replyNeedLoginText" : "您需要登录后才能回复",
	"signUp" : "注册",
	"satisfiedReply" : "采纳回复",
	"satisfiedAnswer" : "满意回复",
	"question" : "问题",

	"gotoTop" : "顶部",
	"forumConfig" : "论坛设置"

};