MWF.xApplication.Forum = MWF.xApplication.Forum || {};
MWF.xApplication.Forum.LP = {
	"title": "論壇首頁",
	"delete": "刪除",
	"deleteDocumentTitle": "刪除確認",
	"deleteDocument": "您確定要刪除嗎？",
	"deleteDocumentOK": "刪除成功",
	"createSuccess": "創建成功",
	"updateSuccess": "更新成功",
	"createReplySuccess": "回覆成功",
	"inputName": "請輸入名稱",
	"deleteAttachmentTitle": "刪除附件確認",
	"deleteAttachment": "您確定要刪除該附件嗎？",
	"search": "搜索",
	"searchKey": "請輸入搜索關鍵字",
	"searchTitle": "關鍵字可以是主題、分區、版塊、創建人",
	"searchTitleNick": "關鍵字可以是主題、分區、版塊",
	"noSearchContentNotice": "請輸入搜索關鍵字，然後執行搜索",

	"dateFormatMonth": "%Y年%m月",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%Y-%m-%d",
	"dateFormatMonthDayLocal": "%m月%d日",
	"dateFormat": "db",
	"SelectOrgForm": "人員組織選擇",

	"month": "月",
	"today": "今天",
	"day": "天",

	"cancel": "取消",
	"close": "關閉",
	"ok": "確定",
	"edit": "編輯",
	"remove": "刪除",
	"action": "操作",

	"login": "登錄",
	"signup": "註冊",
	"logout": "登出",

	"name": "姓名",
	"create_cancel_title": "取消新建確認",
	"create_cancel": "您確定要取消新建嗎？",

	"systemSettingFormTitle": "系統設置",
	"configName": "配置名稱",
	"configCode": "配置編碼",
	"configValue": "配置值",

	"categoryManager": "分區版主",
	"setting": "設置",
	"createCategory": "創建分區",
	"createSection": "創建版塊",
	"categoryFormTitle": "分區設置",
	"sectionFormTitle": "版塊設置",
	"muteSettingFormTitle": "禁言管理",

	"baseSetting": "基本設置",
	"permissionSetting": "權限設置",


	"forumName": "分區名稱",
	"forumManagerName": "分區管理員",
	"forumNotice": "分區公告",
	"forumVisible": "可見用戶",
	"forumVisibleButton": "選擇可見用戶",
	"allPerson": "所有人",
	"byPermission": "根據權限",
	"forumVisibleValue": "所有人,根據權限",
	"indexListStyle": "首頁風格列表",
	"indexListStyleValue": "經典,簡單矩形,圖片矩形",
	"indexListStyleButton": "選擇首頁風格",
	"selectIndexType": "選擇首頁風格",
	"all": "所有",
	"all1": "全部",
	"disable": "停用",
	"typeColumn": "每行列數",
	"indexListStyleImage": "圖片矩形",
	"forumIndexStyle": "分區首頁風格",
	"forumIndexStyleValue": "經典,新聞,照片",
	"indexRecommendable": "允許推薦到首頁",
	"subjectNeedAudit": "主題需要審核",
	"replyNeedAudit": "回覆需要審核",
	"sectionCreateAble": "允許創建版塊",
	"sectionTotal": "版塊數量",
	"subjectTotal": "主題數量",
	"replyTotal": "回覆數量",
	"creatorName": "創建人",
	"forumStatus": "分區狀態",
	"forumStatusValue": "啟用,停用",
	"orderNumber": "排序號",
	"yesOrNo": "是,否",
	"yes": "是",
	"owneForum": "所屬分區",
	"createTime": "創建時間",
	"time": "時間",
	"create": "創建",
	"replyCount": "回覆",
	"auditPerson": "審核人",
	"forumColor": "分區顏色",
	"forumColorFormTitle": "選擇分區顏色",
	"defaultForumColor" : "#7e7e7e",
	"optionsForumColors" : [
		["#ff4040","#ff421e","#ffbf18","#e1e100","#00e100","#00e1ad","#00e0e0","#0082bf","#0080ff","#4181ff","#8242ff","#c140ff","#ff42f9","#ff40a0","#ff4070","#606060"],
		["#ff1f35","#ff1f10","#ff8100","#bfbf00","#00c200","#00c197","#00c1c2","#4181c0","#0062e1","#4141ff","#4200ff","#c200ff","#ff22ff","#f52b97","#ff2259","#5f5f5f"],
		["#e01f25","#e12000","#e26200","#a1a100","#00a000","#009f82","#3f8080","#0060a0","#0041c2","#0021bf","#4100c2","#8100ff","#ff00ff","#ff0080","#79656a","#4f4f4f"],
		["#c20000","#ff0000","#bf4100","#80803f","#3f803f","#008250","#006062","#004080","#001fe2","#0021bf","#4000a2","#6000a1","#e000e0","#df007f","#c20041","#3f3f3f"],
		["#a00000","#e10000","#a13f00","#626200","#006000","#00603c","#004041","#002f80","#0000ff","#2020a0","#2200a1","#400080","#a1009f","#c0007f","#9f000f","#2f2f2f"],
		["#600000","#c21212","#824200","#424200","#004200","#004023","#00323f","#002060","#0020c2","#2222c0","#000080","#1f007f","#800080","#820040","#800000","#1f1f1f"],
		["#400000","#a11f12","#604200","#212100","#002100","#00201f","#002041","#00204f","#0000e0","#0000a1","#000061","#1f0062","#40005f","#620042","#620012","#0f0f0f"]
	],
	"selectColor": "選擇顏色",
	"selectList": "選擇列表",
	"effect": "效果",
	"column": "列",
	"mainSection": "主版塊",
	"welcomeTitle": "{user}，您好！",
	"seePersonCenter": "點擊查看個人中心",
	"closeNavi": "關閉導航",
	"navi": "導航",
	"naviLayout": "導航佈局",

	"sectionName": "版塊名稱",
	"mainSectionName": "主版塊名稱",
	"sectionLevel": "版塊級別",
	"sectionLevelValue": "主版塊,子版塊",
	"sectionDescription": "版塊簡介",
	"sectionNotice": "版塊公告",
	"sectionVisible": "版塊可見範圍",
	"sectionVisibleValue": "所有人,根據權限",
	"replyVisible": "回覆可見範圍",
	"replyVisibleValue": "所有人,根據權限",
	"subjectPublishAble": "允許發帖範圍",
	"subjectPublishAbleValue": "所有人,根據權限",
	"replyPublishAble": "允許回覆範圍",
	"replyPublishAbleValue": "所有人,根據權限",
	"moderatorNames": "版主",
	"sectionType": "類型",
	"sectionTypeValue": "經典,圖片新聞,普通新聞,公告",
	"subSectionCreateAble": "允許創建子版塊",
	"sectionStatus": "狀態",
	"sectionStatusValue": "啟用,停用",
	"sectionGrade": "評分",
	"sectionGradeValue": "否,是",
	"sectionIcon": "版塊圖標",
	"uploadIcon": "上傳本地圖標",
	"selectIcon": "選擇圖標",
	"sectionIconFormTitle": "選擇版塊圖標",
	"indexRecommenPerson": "推薦人",

	"permissionFormTitle": "權限設定",
	"permissionType": "權限類別",
	"permissionTypeValue": "論壇權限,版塊權限,其他權限",
	"permissionName": "權限名稱",
	"permissionCode": "權限代碼",
	"description": "說明",
	"create": "創建",

	"roleFormTitle": "角色設定",
	"createRole": "創建角色設定",
	"roleType": "角色類別",
	"roleTypeValue": "論壇角色,版塊角色",
	"roleName": "角色名稱",
	"roleCode": "角色代碼",
	"selectPerson": "選擇人員",
	"selectDepartment": "選擇組織",
	"selectCompany": "選擇公司",

	"recommanded": "推薦",
	"subject": "主題",
	"allSubject": "全部主題",
	"selectSubjectType": "主題類別選擇",
	"recommandedSubject": "推薦主題",
	"primeSubject": "精華主題",
	"type": "類別",
	"typeValue": "討論,投票,新聞,懸賞,辯論,灌水,知識,動態",
	"subjectType": "主題類別選項",
	"subjectTypeDefaultValue": "討論|新聞|動態|知識|灌水",
	"vote": "投票",
	"sectionApp": "應用市場",
	"typeCategoryDefaultValue": "信息|問題|投票",
	"typeCatagory": "主題類型選項",
	"typeCategorySelectValue": "信息|問題|投票",
	"portalImage": "首頁圖片",
	"summary": "摘要",
	"content": "內容",
	"createSubject": "發帖",
	"anonymousSubject": "匿名發帖",
	"saveSubject": "發表帖子",
	"selectCurrentDocumentFile": "選擇帖子圖片",
	"selectCloudFile": "選擇雲文件圖片",
	"insertUrl": "插入圖片鏈接",
	"voteLimitTime": "投票時限",
	"voteResultVisible": "投票結果可見",
	"votePersonVisible": "投票人隱私",
	"votePersonValue": "公開,匿名",
	"voteOptions": "投票選項",
	"option": "選項",
	"opt": "項",
	"voteCountLimit": "最多允許選擇",
	"group": "組",
	"addVoteGroup": "添加投票組",
	"removeVoteGroup": "刪除此組",
	"confirmRemoveVoteGroupTitle": "刪除投票組確認",
	"confirmRemoveVoteGroupContent": "確認刪除此投票組？",
	"confirmPublishVoteDocumentTitle": "發帖確認",
	"confirmPublishVoteDocumentContent": "該帖子是投票帖，為了保證投票真實性，發布後不能再修改，確定要發表帖子？",
	"voteSubject": "投票主題",

	"timeToEndText": "，距結束還有 {time}",
	"voteCompleteText": "，投票已經結束",
	"votedPersonCountText": "，目前已有 {count} 人參與",
	"noPersonVoteText": "，目前還沒有人參與",
	"privateVoteText": "此為不公開投票，只有發帖人能看到投票結果",
	"publicVoteText": "(此為公開投票，其他人可以看到您的投票項目)",
	"anonymousVoteText": "(此為匿名投票，他人無法查看您的投票項目)",
	"submit": "提交",
	"youAreVoted": "您已經投過票，謝謝您的參與",
	"picture": "圖片",
	"word": "文字",
	"multiSelectText": "多選（最多可選 {n} 項）：",
	"singleSelectText": "單選：",
	"uploadPicture": "上傳圖片",
	"notSelectGroupNotice": "請對每組至少選擇一項再提交",
	"notSelectItemNotice": "請至少選擇一項再提交",
	"second": "秒",
	"minute": "分",
	"hour": "小時",
	"seeVotedPerson": "查看投票參與人",
	"group1": "組別：",
	"option1": "選項：",

	"attachmentArea": "附件區域",
	"selectAttachment": "選擇附件",
	"attachment": "附件",
	"bindObject": "對象",
	"replyAndReadCount": "回覆/瀏覽次數",
	"lastReply": "最後回覆",
	"acceptReplySuccess": "採納回覆成功",

	"readed": "閱讀",
	"reply": "回覆",
	"allReply": "全部回覆",
	"accessed": "人氣",
	"prime": "精華",
	"sType": "主題類別篩選",
	"experience": "經驗",
	"nextSubject": "下一主題",
	"prevSubject": "上一主題",
	"floor": "樓",
	"mainFloor": "主樓",
	"publishAt": "發表於",
	"at": "於",
	"saveReply": "發表回覆",
	"noNextSubject": "當前已是最後一個主題",
	"noPrevSubject": "當前已是第一個主題",
	"recommandSubject": "最新推薦",
	"replyFormTitle": "回覆主題",
	"setRecommend": "推薦到首頁",
	"cancelRecommend": "取消推薦",
	"setTop": "置頂",
	"cancelTop": "取消置頂",
	"setPrime": "設置精華",
	"setRecommendSuccess": "推薦到首頁成功",
	"cancelRecommendSuccess": "取消推薦成功",
	"saveReplySuccess": "回覆成功",
	"deleteReplySuccess": "刪除回覆成功",
	"deleteReplyTitle": "刪除回覆",
	"deleteReplyText": "刪除後無法恢復，確定刪除此回覆？",
	"quoteReplyBeingDeleted": "引用的回覆已被刪除！",
	"setPrimeSuccess": "設置精華成功",
	"cancelPrime": "取消精華",
	"cancelPrimeSuccess": "取消精華成功",

	"moveto": "移動到",
	"lock": "鎖定",
	"unlock": "解鎖",
	"lockSuccess": "成功鎖定文章，無法回覆",
	"unlockSuccess": "成功解鎖文章，可以回覆",
	"topFormTitle": "設定置頂",
	"topType": "請選擇置頂的類型，可多選：",
	"topTypeText": "首頁置頂, 分區置頂, 版塊置頂",
	"topTypeValue": "bbs, forum, section",
	"setTopSuccess": "置頂設定成功",
	"setToFail": "置頂設定失敗",
	"cancelTopSuccess": "取消置頂成功",
	"topToBBS": "首頁置頂",
	"topToForum": "分區置頂",
	"topToSection": "版塊置頂",
	"returnToList": "返回列表",
	"invalid": "停用",
	"personCenter": "個人中心",
	"company": "公司",
	"department": "部門",
	"mail": "郵件",
	"weixin": "微信",
	"mobile": "手機",
	"signature": "簽名",
	"mySubject": "我的發帖",
	"myReply": "我的回覆",
	"hisSubject": "他的發帖",
	"herSubject": "她的發帖",
	"replyContent": "回覆內容",
	"replyTime": "回覆時間",
	"changePersonSetting": "修改個人信息",
	"sendMessage": "發送消息",
	"todaySubject": "今日主題",
	"todayReply": "今日回覆",
	"replyTo": "回覆",
	"newSubjectPublishedText": "有新發布的{count}個主題，點擊查看",

	"hotPicture": "熱點圖片",
	"cancelHotPicture": "取消熱點",
	"setHot": "設置熱點",
	"setHotPicture": "設置熱點圖片",
	"setHotLinkSuccess": "設置熱點圖片成功",
	"cancelHotLinkSuccess": "取消熱點圖片成功",
	"selectDocPicture": "選擇文檔圖片",
	"selectFilePicture": "選擇雲端文件圖片",
	"hotLinkDescription": "注意：選擇的圖片將作為該平台移動應用程序的頂部圖片，最佳的高寬比為1:2。",
	"unselectHotPic": "請先選擇圖片",
	"cancelHotPicComfirmTitle": "取消熱點",
	"cancelHotPicComfirmContent": "確定取消此文檔的熱點嗎？",
	"replyNeedLoginText": "您需要登錄後才能回覆",
	"signUp": "註冊",
	"satisfiedReply": "採納回覆",
	"satisfiedAnswer": "滿意回覆",
	"question": "問題",
	"gotoTop": "返回頂部",
	"forumConfig": "論壇設置",
	"yesterday": "昨天",
	"twoDaysAgo": "前天",
	"weekAgo": "週前",
	"dayAgo": "天前",
	"hourAgo": "小時前",
	"minuteAgo": "分鐘前",
	"justNow": "剛剛",
	"publishJustNow": "剛剛發布",
	"gradeNotice": "請評分後提交",

	"selectTargetSection": "選擇移動到的版塊",
	"moveSuccess": "帖子已經移動到{section}",
	"editPermissionFormTitle": "設置編輯權限",
	"editorSetting": "編輯者",
	"setEditorSuccess": "設置編輯權限成功！",
	"setEditorFail": "設置編輯權限出錯！",
	"addMutePerson": "添加禁言人員",
	"mute1SettingFormTitle": "禁言人員設置",
	"mutePerson": "禁言人員",
	"muteTime": "禁言時間",
	"unmuteDate": "解封日期",
	"unmuteDateNote": "到期後自動解除禁言",
	"unmute": "解除禁言",
	"unmuteTitle": "解除禁言確認",
	"unmuteDocument": "確定要解除禁言:{person}？",
	"multReason": "禁言理由",
	"unmuteSuccess": "解除禁言成功！",
	"unmuteTimeUnvalid": "解封日期需要晚於今天",
	"muteNote": "您被禁言了，無法發帖和回復。",
	"muteInfor": "解封日期：{unmuteDate}，禁言原因：{reason}。",
	"poster": "發帖人"

};