MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.service = MWF.xApplication.service || {};
MWF.xApplication.service.InvokeDesigner = MWF.xApplication.service.InvokeDesigner || {};
MWF.xApplication.service.InvokeDesigner.LP={
	"title": "Editar Interfaz",
	"newInvoke": "Crear Nueva Interfaz",
	"invokeLibrary": "Biblioteca de Interfaces",
	"property": "Propiedades",
	"include": "Incluir",
	"id": "Identificación",
	"name": "Nombre",
	"alias": "Alias",
	"description": "Descripción",
	"validated": "¿El formato del código es correcto?",
	"isEnable": "¿Está habilitado?",
	"remoteAddrRegex": "Expresión para direcciones permitidas",
	"lastStartTime": "Última hora de inicio",
	"lastEndTime": "Última hora de finalización",
	"true": "Sí",
	"false": "No",
	"enable": "Habilitar haciendo clic aquí",
	"disable": "Deshabilitar haciendo clic aquí",
	"invokeUri": "Dirección de llamada",
	"invokeMethod": "Método de llamada",
	"enableToken": "Habilitar autenticación",
	"enableTokenInfo": "Después de habilitar la autenticación, debe usar el nombre del cliente y el token cifrado para llamar al servicio. <a href='https://www.o2oa.net/cms/tech/430.html' target='_blank'>Haga clic aquí para ver el documento de configuración de autenticación de la interfaz</a>",
	"invokeHead": "head",
	"openLogViewer": "Abrir visor de registro",
	"debugger": "Depurar",
	"run": "Ejecutar ahora",
	"runSuccess": "Ejecutado con éxito",
	"requireArguments": "Parámetros requeridos",
	"tokenSetting": "Configuración de autenticación",
	"runResult": "Resultado de la ejecución",
	"noSSOSetting": "Configure la autenticación primero",
	"notice": {
		"save_success": "¡Interfaz guardada exitosamente!",
		"deleteDataTitle": "Confirmación",
		"deleteData": "¿Está seguro que desea eliminar los datos actuales y sus subdatos?",
		"changeTypeTitle": "Confirmación",
		"changeTypeDeleteChildren": "Cambiar el tipo de datos eliminará todos los subdatos. ¿Está seguro que desea continuar?",
		"changeType": "Cambiar el tipo de datos cambiará su valor. ¿Está seguro que desea continuar?",
		"inputTypeError": "El tipo de dato que ingresó es inválido, por favor ingrese uno válido.",
		"sameKey": "El nombre del elemento que ingresó ya existe en el objeto, por favor ingrese otro nombre.",
		"emptyKey": "El nombre del elemento no puede estar vacío, por favor ingrese un nombre.",
		"numberKey": "El nombre del elemento no puede ser un número, por favor ingrese otro nombre.",
		"inputName": "Ingrese el nombre de la interfaz.",
		"inputCron": "La expresión cron para tareas programadas no puede estar vacía."
	},
	"comment": {
		"entityManager": "Administrador de Entidades",
		"applications": "Acceso a servicios dentro del sistema",
		"requestText": "Cuerpo de la solicitud",
		"request": "Solicitud",
		"currentPerson": "Usuario actual",
		"response": "Objeto de respuesta. Use this.response.setBody(data) para establecer el contenido de respuesta.",
		"organization": "Acceso a la organización",
		"org": "Métodos rápidos de acceso a la organización",
		"service": "Cliente de servicios web"
	},
	"formToolbar": {
		"save": "Guardar secuencia de comandos",
		"autoSave": "AutoGuardar",
		"fontSize": "Tamaño de fuente",
		"style": "estilo",
		"scriptEditor": "Editor de guiones",
		"viewAllVersions": "Ver todas las versiones de script"
	}
}
MWF.xApplication.service.InvokeDesigner["lp."+o2.language] = MWF.xApplication.service.InvokeDesigner.LP