MWF.xApplication.service.InvokeDesigner.LP = {
    "title": "インターフェース編集",
    "newInvoke": "新しいインターフェース",
    "invokeLibrary": "インターフェースライブラリ",
    "property": "プロパティ",
    "include": "含む",
    "id": "識別子",
    "name": "名前",
    "alias": "別名",
    "description": "説明",
    "validated": "コード形式が正しいかどうか",
    "isEnable": "有効ですか？",
    "remoteAddrRegex": "許可されたアクセスアドレスの表現",
    "lastStartTime": "最終開始時間",
    "lastEndTime": "最終終了時間",
    "true": "はい",
    "false": "いいえ",
    "enable": "クリックして有効にする",
    "disable": "クリックして無効にする",
    "invokeUri": "呼び出しアドレス",
    "invokeMethod": "呼び出し方法",
    "enableToken": "認証を有効にする",
    "enableTokenInfo": "認証を有効にした場合、認証クライアント名と暗号化されたトークンを使用してサービスを呼び出す必要があります。<a href='https://www.o2oa.net/cms/tech/430.html' target='_blank'>インターフェース認証設定ドキュメントを表示</a>",
    "invokeHead": "ヘッダー",
    "openLogViewer": "ログビューアを開く",
    "debugger": "デバッガ",
    "run": "すぐに実行",
    "runSuccess": "実行成功",
    "requireArguments": "要求パラメータ",
    "tokenSetting": "認証設定",
    "runResult": "実行結果",
    "noSSOSetting": "まず認証を設定してください",

    "notice": {
        "save_success": "インターフェースの保存に成功しました！",
        "deleteDataTitle": "データ削除の確認",
        "deleteData": "現在のデータおよびそのサブデータを削除してもよろしいですか？",
        "changeTypeTitle": "データタイプ変更の確認",
        "changeTypeDeleteChildren": "データタイプ変更はすべてのサブデータを削除します。実行してもよろしいですか？",
        "changeType": "データタイプ変更はデータの値を変更します。実行してもよろしいですか？",
        "inputTypeError": "入力したデータタイプが正しくありません。再入力してください。",
        "sameKey": "入力した項目名は既存のオブジェクトにすでに存在します。再入力してください。",
        "emptyKey": "項目名は空白にできません。再入力してください。",
        "numberKey": "項目名は数字ではありません。再入力してください。",
        "inputName": "インターフェース名を入力してください。",
        "inputCron": "定期タスクのcron式は空白にできません。"
    },
    "comment": {
        "entityManager": "エンティティマネージャ",
        "applications": "システム内のサービスへのアクセス",
        "requestText": "リクエスト本文",
        "request": "リクエスト",
        "currentPerson": "現在のユーザー",
        "response": "レスポンスオブジェクト。this.response.setBody(data) を使用してレスポンスコンテンツを設定します。",
        "organization": "組織へのアクセス",
        "org": "組織への迅速なアクセス方法",
        "service": "Webサービスクライアント"
    }
};
