MWF.xApplication.service.InvokeDesigner.LP = {
    "title": "인터페이스 편집",
    "newInvoke": "새 인터페이스",
    "invokeLibrary": "인터페이스 라이브러리",
    "property": "속성",
    "include": "포함",
    "id": "식별자",
    "name": "이름",
    "alias": "별명",
    "description": "설명",
    "validated": "코드 형식이 올바른가요?",
    "isEnable": "사용 중인가요?",
    "remoteAddrRegex": "허용된 주소 표현식",
    "lastStartTime": "최근 시작 시간",
    "lastEndTime": "최근 종료 시간",
    "true": "예",
    "false": "아니요",
    "enable": "클릭하여 활성화",
    "disable": "클릭하여 비활성화",
    "invokeUri": "호출 주소",
    "invokeMethod": "호출 메소드",
    "enableToken": "인증 활성화",
    "enableTokenInfo": "인증 활성화 후, 인증 클라이언트 이름 및 암호화된 토큰을 사용하여 서비스를 호출해야 합니다.<a href='https://www.o2oa.net/cms/tech/430.html' target='_blank'>인터페이스 인증 구성 설명서 보기</a>",
    "invokeHead": "헤드",
    "openLogViewer": "로그 뷰어 열기",
    "debugger": "디버거",
    "run": "즉시 실행",
    "runSuccess": "성공적으로 실행",
    "requireArguments": "요청 매개변수",
    "tokenSetting": "인증 설정",
    "runResult": "실행 결과",
    "noSSOSetting": "먼저 인증을 구성하세요",

    "notice": {
        "save_success": "인터페이스 저장 성공!",
        "deleteDataTitle": "데이터 삭제 확인",
        "deleteData": "현재 데이터 및 하위 데이터를 삭제하시겠습니까?",
        "changeTypeTitle": "데이터 유형 변경 확인",
        "changeTypeDeleteChildren": "데이터 유형 변경은 모든 하위 데이터를 삭제합니다. 실행하시겠습니까?",
        "changeType": "데이터 유형 변경은 데이터 값을 변경합니다. 실행하시겠습니까?",
        "inputTypeError": "입력한 데이터 유형이 잘못되었습니다. 다시 입력해주세요.",
        "sameKey": "입력한 항목 이름은 이미 개체에 있습니다. 다시 입력해주세요.",
        "emptyKey": "항목 이름을 비울 수 없습니다. 다시 입력해주세요.",
        "numberKey": "항목 이름은 숫자일 수 없습니다. 다시 입력해주세요.",
        "inputName": "인터페이스 이름을 입력하세요.",
        "inputCron": "정기 작업 corn 표현식을 입력하세요."
    },
    "comment": {
        "entityManager": "엔터티 매니저",
        "applications": "시스템 내 서비스에 액세스",
        "requestText": "요청 본문",
        "request": "요청",
        "currentPerson": "현재 사용자",
        "response": "응답 객체. this.response.setBody(data)로 응답 내용을 설정합니다.",
        "organization": "조직 액세스",
        "org": "빠른 조직 액세스 방법",
        "service": "Web 서비스 클라이언트"
    }
};
