/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.bbs.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.bbs.entity.BBSConfigSetting.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:19 CST 2018")
public class BBSConfigSetting_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<BBSConfigSetting,String> configCode;
    public static volatile SingularAttribute<BBSConfigSetting,String> configName;
    public static volatile SingularAttribute<BBSConfigSetting,String> configValue;
    public static volatile SingularAttribute<BBSConfigSetting,String> description;
    public static volatile SingularAttribute<BBSConfigSetting,String> id;
    public static volatile SingularAttribute<BBSConfigSetting,Boolean> isMultiple;
    public static volatile SingularAttribute<BBSConfigSetting,Integer> orderNumber;
    public static volatile SingularAttribute<BBSConfigSetting,String> selectContent;
    public static volatile SingularAttribute<BBSConfigSetting,String> valueType;
}
