/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.bbs.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.bbs.entity.BBSReplyInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:19 CST 2018")
public class BBSReplyInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<BBSReplyInfo,String> auditorName;
    public static volatile SingularAttribute<BBSReplyInfo,String> content;
    public static volatile SingularAttribute<BBSReplyInfo,String> creatorName;
    public static volatile SingularAttribute<BBSReplyInfo,String> forumId;
    public static volatile SingularAttribute<BBSReplyInfo,String> forumName;
    public static volatile SingularAttribute<BBSReplyInfo,String> hostIp;
    public static volatile SingularAttribute<BBSReplyInfo,String> id;
    public static volatile SingularAttribute<BBSReplyInfo,String> machineName;
    public static volatile SingularAttribute<BBSReplyInfo,String> mainSectionId;
    public static volatile SingularAttribute<BBSReplyInfo,String> mainSectionName;
    public static volatile SingularAttribute<BBSReplyInfo,Integer> orderNumber;
    public static volatile SingularAttribute<BBSReplyInfo,String> parentId;
    public static volatile SingularAttribute<BBSReplyInfo,String> picId;
    public static volatile SingularAttribute<BBSReplyInfo,String> replyAuditStatus;
    public static volatile SingularAttribute<BBSReplyInfo,String> sectionId;
    public static volatile SingularAttribute<BBSReplyInfo,String> sectionName;
    public static volatile SingularAttribute<BBSReplyInfo,String> subjectId;
    public static volatile SingularAttribute<BBSReplyInfo,String> systemType;
    public static volatile SingularAttribute<BBSReplyInfo,String> title;
}
