/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.bbs.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.bbs.entity.BBSVoteOptionGroup.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:19 CST 2018")
public class BBSVoteOptionGroup_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<BBSVoteOptionGroup,String> creatorName;
    public static volatile SingularAttribute<BBSVoteOptionGroup,String> forumId;
    public static volatile SingularAttribute<BBSVoteOptionGroup,String> groupName;
    public static volatile SingularAttribute<BBSVoteOptionGroup,String> id;
    public static volatile SingularAttribute<BBSVoteOptionGroup,String> mainSectionId;
    public static volatile SingularAttribute<BBSVoteOptionGroup,Integer> orderNumber;
    public static volatile SingularAttribute<BBSVoteOptionGroup,String> sectionId;
    public static volatile SingularAttribute<BBSVoteOptionGroup,String> subjectId;
    public static volatile SingularAttribute<BBSVoteOptionGroup,Integer> voteChooseCount;
}
