MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.portal = MWF.xApplication.portal || {};
MWF.xApplication.portal.PortalManager = MWF.xApplication.portal.PortalManager || {};
MWF.xApplication.portal.PortalManager.LP={
	"title": "Portal Manage",
	"categoryTitle": "Category",
	"description": "Description",
	"deleteItems": "Delete selected element",
	"copy": "Copy",
	"copyto": "Copyto...",
	"copyInfor": "Select multiple elements, press Ctrl+C to copy the elements, press Ctrl+V to paste elements into the current application",
	"copyed": "The selected element has been copied",
	"copyConfirmTitle": "Copy element confirmation",
	"copyConfirmInfor": "The target area already contains the same elements:",
	"copySource": "Original file:",
	"copyTarget": "Copy files:",
	"copyConfirm_overwrite": "Replace",
	"copyConfirm_new": "Create",
	"copyConfirm_skip": "Skip",
	"copyConfirm_cancel": "Cancel",
	"copynew": "New",
	"pageConfig": "Page",
	"widgetConfig": "Widget",
	"scriptConfig": "Script",
	"fileConfig": "Resource",
	"applicationConfig": "Attributes",
	"dataConfig": "Dictionary",
	"findDesigner": "FindCode",
	"edit": "Edit",
	"save": "Save",
	"cancel": "Cancel",
	"phone": "Phone",
	"mail": "Mail",
	"deleteElementTitle": "Delete design confirmation",
	"deleteElement": "Are you sure you want to delete the selected design element?",
	"page": {
		"create": "Create Page",
		"search": "Search Page",
		"searchText": "Please enter key words",
		"noProcessNoticeText": "This application does not have a page yet, you can click here to create a new page",
		"loaded": "The page is loaded",
		"deleteProcessTitle": "Delete page confirmation",
		"deleteProcess": "Are you sure you want to delete the current page?",
		"deletePageTemplateTitle": "Delete confirmation",
		"deletePageTemplate": "Are you sure you want to delete the current page template?",
		"noPageNoticeText": "This portal currently does not have a page. You can click here to create a new page"
	},
	"widget": {
		"create": "Create widget",
		"search": "Search widget",
		"searchText": "Please enter key words",
		"noNoticeText": "This application does not have a widget yet, you can click here to create a new widget",
		"loaded": "The widget is loaded",
		"deleteViewTitle": "Delete widget confirmation",
		"deleteView": "Are you sure you want to delete the current widget?"
	},
	"dictionary": {
		"create": "Create Data Dictionary",
		"search": "Search Data Dictionary",
		"searchText": "Please enter a keyword",
		"noDictionaryNoticeText": "This application does not have a data dictionary yet, you can click here to create a new data dictionary",
		"noDictionaryNoCreateNoticeText": "This application does not have a data dictionary now",
		"loaded": "Data dictionary loaded",
		"deleteFormTitle": "Confirm Delete Data Dictionary",
		"deleteForm": "Are you sure you want to delete the current data dictionary?"
	},
	"script": {
		"create": "Create Script",
		"search": "Search Script",
		"searchText": "Please enter a keyword",
		"noScriptNoticeText": "There is no script for this application, you can click here to create a new script",
		"loaded": "Script loaded",
		"deleteFormTitle": "Delete Script Confirmation",
		"deleteForm": "Are you sure you want to delete the current script?"
	},
	"application": {
		"inputApplicationName": "Please enter the portal name",
		"property": "Portal Properties",
		"name": "Portal Name",
		"alias": "Portal Alias",
		"description": "Portal Description",
		"type": "Portal Type",
		"icon": "Icon",
		"id": "Portal ID",
		"url": "Portal URL",
		"firstPage": "Portal Homepage",
		"controllerList": "Manager",
		"available": "Available range",
		"pcClient": "PC",
		"mobileClient": "Mobile",
		"true": "Enabled",
		"false": "Disabled",
		"anonymousAccess": "Anonymous Access",
		"changeIcon": "Change Icon",
		"setManager": "Set Manager",
		"setAppManager": "Set Application Manager",
		"setUsableIdentity": "Set Usable Identity",
		"setUsableUnit": "Set UsableUnit",
		"setAppUsableIdentity": "Set AppUsableIdentity",
		"setAppUsableUnit": "Set AppUsableUnit",
		"cornerMark": "Corner Mark Settings",
		"cornerMarkNote": "Note: The corner mark is the number in the upper right corner of the mobile application interface -> portal application.",
		"selectScriptNote": "Click the plus sign to select the script library",
		"selectScript": "Select Script",
		"cornerMarkScript": "CornerMarkScript",
		"run": "Run immediately",
		"openLogView": "Open Log Viewer",
		"runResult": "Run result:"
	},
	"createSelectTemplate": "Create: Select template",
	"templateCategory": "Template Category: ",
	"all": "All",
	"menu": {
		"create": "New Menu",
		"search": "Search menu",
		"searchText": "Please enter keywords",
		"noFormNoticeText": "This portal currently does not have a menu. You can click here to create a new menu",
		"loaded": "Menu loading completed",
		"deleteFormTitle": "Delete menu confirmation",
		"deleteForm": "Are you sure you want to delete the current form?"
	},
	"source": {
		"create": "Create a new data source",
		"search": "search for data sources",
		"searchText": "Please enter keywords",
		"noNoticeText": "This portal currently does not have a data source. You can click here to create a new data source",
		"loaded": "Data source loading completed",
		"deleteViewTitle": "Delete Data Source Confirmation",
		"deleteView": "Are you sure you want to delete the current data source?"
	}
}
MWF.xApplication.portal.PortalManager["lp."+o2.language] = MWF.xApplication.portal.PortalManager.LP