MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.portal = MWF.xApplication.portal || {};
MWF.xApplication.portal.PortalManager = MWF.xApplication.portal.PortalManager || {};
MWF.xApplication.portal.PortalManager.LP={
	"title": "Gestión del portal",
	"categoryTitle": "Categoría del portal",
	"description": "Descripción",
	"deleteItems": "Eliminar elementos seleccionados",
	"copy": "Copiar",
	"copyto": "Copiar a...",
	"copyInfor": "Seleccione varios elementos y presione Ctrl+C para copiar los elementos. Presione Ctrl+V para pegar los elementos copiados en la aplicación actual",
	"copyed": "Elementos seleccionados copiados",
	"copyConfirmTitle": "Confirmación para copiar elementos",
	"copyConfirmInfor": "El área de destino ya contiene elementos idénticos:",
	"copySource": "Origen:",
	"copyTarget": "Destino:",
	"copyConfirm_overwrite": "Sobrescribir",
	"copyConfirm_new": "Nuevo",
	"copyConfirm_skip": "Saltar",
	"copyConfirm_cancel": "Cancelar",
	"copynew": "Nuevo",
	"pageConfig": "Página",
	"widgetConfig": "Widget",
	"scriptConfig": "Script",
	"fileConfig": "Recursos",
	"applicationConfig": "Propiedades",
	"dataConfig": "Datos",
	"edit": "Editar",
	"save": "Guardar",
	"cancel": "Cancelar",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"deleteElementTitle": "Confirmación",
	"deleteElement": "¿Está seguro de que desea eliminar los elementos de diseño seleccionados?",
	"page": {
		"create": "Crear nueva página",
		"search": "Buscar página",
		"searchText": "Ingrese una palabra clave",
		"noPageNoticeText": "Este portal aún no tiene ninguna página. Haga clic aquí para crear una nueva página",
		"loaded": "La página se ha cargado correctamente.",
		"deleteProcessTitle": "Confirmación",
		"deleteProcess": "¿Está seguro de que desea eliminar esta página?",
		"deletePageTemplateTitle": "Confirmación",
		"deletePageTemplate": "¿Está seguro de que desea eliminar esta plantilla de página?"
	},
	"widget": {
		"create": "Crear nuevo Widget",
		"search": "Buscar Widget",
		"searchText": "Ingrese una palabra clave",
		"noNoticeText": "Este portal aún no tiene ningún Widget. Haga clic aquí para crear un nuevo Widget",
		"loaded": "Se han cargado correctamente los Widgets de la página",
		"deleteViewTitle": "Confirmación",
		"deleteView": "¿Está seguro de que desea eliminar este widget de la página actual?"
	},
	"menu": {
		"create": "Crear nuevo menú",
		"search": "Buscar menú",
		"searchText": "Ingrese una palabra clave",
		"noFormNoticeText": "Este portal aún no tiene ningún menú. Haga clic aquí para crear un nuevo menú.",
		"loaded": "Los menús se han cargado correctamente.",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar este formulario?"
	},
	"source": {
		"create": "Crear nuevo origen de datos",
		"search": "Buscar origen de datos",
		"searchText": "Ingrese una palabra clave",
		"noNoticeText": "Este portal aún no tiene ningún origen de datos. Haga clic aquí para crear uno nuevo.",
		"loaded": "Se han cargado correctamente los orígenes de datos.",
		"deleteViewTitle": "Confirmación",
		"deleteView": "¿Está seguro de que desea eliminar este origen de datos?"
	},
	"dictionary": {
		"create": "Crear diccionario de datos",
		"search": "Buscar diccionario de datos",
		"searchText": "Ingrese la palabra clave",
		"noDictionaryNoticeText": "Esta aplicación aún no tiene ningún diccionario de datos. Puede hacer clic aquí para crear uno nuevo.",
		"noDictionaryNoCreateNoticeText": "Esta aplicación no tiene ningún diccionario de datos en este momento.",
		"loaded": "El diccionario de datos se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el diccionario de datos actual?"
	},
	"script": {
		"create": "Crear script",
		"search": "Buscar script",
		"searchText": "Ingrese la palabra clave",
		"noScriptNoticeText": "Esta aplicación aún no tiene ningún script. Puede hacer clic aquí para crear uno nuevo.",
		"loaded": "El script se ha cargado correctamente",
		"deleteFormTitle": "Confirmación",
		"deleteForm": "¿Está seguro de que desea eliminar el script actual?"
	},
	"application": {
		"inputApplicationName": "Ingrese el nombre del portal",
		"property": "Propiedades del portal",
		"name": "Nombre del portal",
		"alias": "Alias del portal",
		"description": "Descripción del portal",
		"type": "Tipo de portal",
		"icon": "Ícono del portal",
		"id": "Identificador del portal",
		"url": "URL del portal",
		"firstPage": "Página principal del portal",
		"controllerList": "Lista de controladores",
		"available": "Disponible para",
		"pcClient": "Cliente de PC",
		"mobileClient": "Cliente móvil",
		"true": "Habilitado",
		"false": "Deshabilitado",
		"anonymousAccess": "Acceso anónimo",
		"changeIcon": "Cambiar ícono",
		"setManager": "Establecer administrador",
		"setAppManager": "Establecer administrador de la aplicación",
		"setUsableIdentity": "Establecer identidad utilizable",
		"setUsableUnit": "Establecer organización utilizable",
		"setAppUsableIdentity": "Establecer identidad utilizable de la aplicación",
		"setAppUsableUnit": "Establecer organización utilizable de la aplicación",
		"cornerMark": "Configuración de marca de esquina",
		"cornerMarkNote": "Nota: La marca de la esquina es el número en la esquina superior derecha de la interfaz de la aplicación móvil -> aplicación del portal.",
		"selectScriptNote": "Haga clic en el signo más para seleccionar la biblioteca de secuencias de comandos",
		"selectScript": "Seleccionar guión",
		"cornerMarkScript": "CornerMarkScript",
		"run": "Ejecutar inmediatamente",
		"openLogView": "Abrir Visor de Registros",
		"runResult": "Ejecutar resultado:"
	},
	"createSelectTemplate": "Crear: Seleccionar plantilla",
	"templateCategory": "Categoría de plantilla:",
	"all": "Todos"
}
MWF.xApplication.portal.PortalManager["lp."+o2.language] = MWF.xApplication.portal.PortalManager.LP