MWF.xApplication.portal.PortalManager.LP = {
	"title": "포털 관리",
    "categoryTitle": "포털 분류",
    "description": "설명",
    "deleteItems": "선택한 항목 삭제",
    "copy": "복사",
    "copyto": "복사 대상...",
    "copyInfor": "여러 요소를 선택하고 Ctrl+C를 누르면 요소를 복사하고, Ctrl+V를 누르면 복사한 요소를 현재 애플리케이션에 붙여넣을 수 있습니다.",
    "copyed": "선택한 요소가 복사되었습니다",
    "copyConfirmTitle": "요소 복사 확인",
    "copyConfirmInfor": "대상 영역에 이미 동일한 요소가 포함되어 있습니다:",
    "copySource": "원본 파일:",
    "copyTarget": "복사된 파일:",
    "copyConfirm_overwrite": "덮어쓰기",
    "copyConfirm_new": "새로 만들기",
    "copyConfirm_skip": "건너뛰기",
    "copyConfirm_cancel": "취소",
    "copynew": "새로 만들기",
    "pageConfig": "페이지 구성",
    "widgetConfig": "위젯 구성",
    "scriptConfig": "스크립트 구성",
    "fileConfig": "리소스 파일",
    "applicationConfig": "포털 속성",
    "dataConfig": "데이터 구성",
    "edit": "편집",
    "save": "저장",
    "cancel": "취소",
    "phone": "전화",
    "mail": "이메일",
    "deleteElementTitle": "디자인 삭제 확인",
    "deleteElement": "선택한 디자인 요소를 삭제하시겠습니까?",

	"page": {
        "create": "페이지 생성",
        "search": "페이지 검색",
        "searchText": "키워드를 입력하세요",
        "noPageNoticeText": "이 포털에는 아직 페이지가 없습니다. 여기를 클릭하여 새 페이지를 생성할 수 있습니다.",
        "loaded": "페이지가 로드되었습니다.",
        "deleteProcessTitle": "페이지 삭제 확인",
        "deleteProcess": "현재 페이지를 삭제하시겠습니까?",
        "deletePageTemplateTitle": "페이지 템플릿 삭제 확인",
        "deletePageTemplate": "현재 페이지 템플릿을 삭제하시겠습니까?"
    },
    "widget": {
        "create": "위젯 생성",
        "search": "위젯 검색",
        "searchText": "키워드를 입력하세요",
        "noNoticeText": "이 포털에는 아직 위젯이 없습니다. 여기를 클릭하여 새 위젯을 생성할 수 있습니다.",
        "loaded": "위젯이 로드되었습니다.",
        "deleteViewTitle": "위젯 삭제 확인",
        "deleteView": "현재 위젯을 삭제하시겠습니까?"
    },
    "menu": {
        "create": "메뉴 생성",
        "search": "메뉴 검색",
        "searchText": "키워드를 입력하세요",
        "noFormNoticeText": "이 포털에는 아직 메뉴가 없습니다. 여기를 클릭하여 새 메뉴를 생성할 수 있습니다.",
        "loaded": "메뉴가 로드되었습니다.",
        "deleteFormTitle": "메뉴 삭제 확인",
        "deleteForm": "현재 메뉴를 삭제하시겠습니까?"
    },
    "source": {
        "create": "데이터 소스 생성",
        "search": "데이터 소스 검색",
        "searchText": "키워드를 입력하세요",
        "noNoticeText": "이 포털에는 아직 데이터 소스가 없습니다. 여기를 클릭하여 새 데이터 소스를 생성할 수 있습니다.",
        "loaded": "데이터 소스가 로드되었습니다.",
        "deleteViewTitle": "데이터 소스 삭제 확인",
        "deleteView": "현재 데이터 소스를 삭제하시겠습니까?"
    },
    "dictionary": {
        "create": "데이터 사전 생성",
        "search": "데이터 사전 검색",
        "searchText": "키워드를 입력하세요",
        "noDictionaryNoticeText": "이 응용프로그램에는 아직 데이터 사전이 없습니다. 여기를 클릭하여 새 데이터 사전을 생성할 수 있습니다.",
        "noDictionaryNoCreateNoticeText": "이 응용프로그램에는 현재 데이터 사전이 없습니다.",
        "loaded": "데이터 사전이 로드되었습니다.",
        "deleteFormTitle": "데이터 사전 삭제 확인",
        "deleteForm": "현재 데이터 사전을 삭제하시겠습니까?"
    },
    "script": {
        "create": "스크립트 생성",
        "search": "스크립트 검색",
        "searchText": "키워드를 입력하세요",
        "noScriptNoticeText": "이 응용프로그램에는 아직 스크립트가 없습니다. 여기를 클릭하여 새 스크립트를 생성할 수 있습니다.",
        "loaded": "스크립트가 로드되었습니다.",
        "deleteFormTitle": "스크립트 삭제 확인",
        "deleteForm": "현재 스크립트를 삭제하시겠습니까?"
    },
    "application": {
        "inputApplicationName": "포털 이름을 입력하세요",
        "property": "포털 속성",
        "name": "포털 이름",
        "alias": "포털 별칭",
        "description": "포털 설명",
        "type": "포털 유형",
        "icon": "포털 아이콘",
        "id": "포털 ID",
        "url": "포털 URL",
        "firstPage": "포털 메인 페이지",
        "controllerList": "관리자 목록",
        "available": "사용 가능 범위",
        "pcClient": "PC 클라이언트",
        "mobileClient": "모바일 클라이언트",
        "true": "활성화",
        "false": "비활성화",
        "anonymousAccess": "익명 액세스",
        "changeIcon": "아이콘 변경",
        "setManager": "관리자 설정",
        "setAppManager": "앱 관리자 설정",
        "setUsableIdentity": "사용 가능한 ID 설정",
        "setUsableUnit": "사용 가능한 조직 설정",
        "setAppUsableIdentity": "앱에서 사용 가능한 ID 설정",
        "setAppUsableUnit": "앱에서 사용 가능한 조직 설정",
        "cornerMark": "코너 마크 설정",
        "cornerMarkNote": "참고: 코너 마크는 모바일 클라이언트 앱 인터페이스의 포털 앱 우상단에 나타나는 숫자입니다.",
        "selectScriptNote": "플러스 아이콘을 클릭하여 스크립트 라이브러리를 선택합니다",
        "selectScript": "스크립트 선택",
        "cornerMarkScript": "코너 마크 스크립트",
        "run": "즉시 실행",
        "openLogView": "로그 뷰어 열기",
        "runResult": "실행 결과:"
    },
    "createSelectTemplate": "새로 만들기: 템플릿 선택",
    "templateCategory": "템플릿 카테고리:",
    "all": "모두"
};