MWF.xApplication.process.FormDesigner.LP = {
    "title": "FormEditor",
    "newForm": "Create Form",
    "property": "Property",
    "tools": "Tools",
    "all": "All",

    "repetitionsId": "Element ID is not unique",
    "notNullId": "Element ID cannot be empty",

    "button":{
        "ok": "OK",
        "cancel": "Cancel"
    },
    "version" : {
        "title" : "View form version history",
        "close" : "Close",
        "no":"SerialNumber",
        "updateTime":"UpdateTime",
        "op":"action",
        "resume" : "Resume",
        "resumeConfirm" : "Resume Confirmation",
        "resumeInfo" : "Are you sure you need to perform a form recovery operation? After confirming the restoration, the current form will be updated, and the current form needs to be manually saved to take effect.",
        "resumeSuccess" :"Resume Successfully"
    },
    "notice": {
        "save_success": "Form saved successfully!",
        "saveTemplate_success": "Form template saved successfully!",
        "saveTemplate_inputName": "Please enter the template title",
        "saveTemplate_inputCategory": "Please confirm the template category",

        "deleteElementTitle": "Delete form element confirmation",
        "deleteElement": "Are you sure you want to delete the current element and its child elements?",

        "deleteRowTitle": "Delete table row confirmation",
        "deleteRow": "Deleting the current row will delete the contents of all cells in this row. Are you sure you want to delete the currently selected row?",
        "deleteColTitle": "Delete table column confirmation",
        "deleteCol": "Deleting the current row will delete the contents of all cells in this column. Are you sure you want to delete the currently selected column?",
        "deleteEventTitle": "Delete Event Confirmation",
        "deleteEvent": "Are you sure you want to delete the current event?",

        "deleteActionTitle": "Delete Action Confirmation",
        "deleteAction": "Are you sure you want to delete the current action?",

        "deleteButtonTitle": "Delete Operation Confirmation",
        "deleteButton": "Are you sure you want to delete the current operation button?",

        "notUseModuleInMobile": "The mobile terminal does not support this component",

        "changeToSequenceTitle": "Confirm",
        "changeToSequence": "This operation will delete the added components. Are you sure you want to change it to the \"Sequence Number\" column?"
    },

    "formAction": {
        "insertRow": "Insert Row",
        "insertCol": "Insert Column",
        "deleteRow": "Delete Row",
        "deleteCol": "Delete column",
        "mergerCell": "Merge Cells",
        "splitCell": "Split Cell",
        "move": "Move",
        "copy": "Copy",
        "delete": "Delete",
        "add": "Add",
        "script": "Script",
        "styleBrush": "StyleBrush",
        "insertTop": "Insert Top",
        "insertBottom": "Insert to the bottom",
        "insertBefore": "InsertBefore",
        "insertAfter": "Insert After",
        "injectNotice": "Hold down Ctrl and release the mouse for precise positioning"
    },

    "actionbar": {
        "readhide": "Set whether to display when reading",
        "edithide": "Set whether to display when editing",
        "hideCondition": "Set hiding conditions",
        "title": "Title",
        "img": "Icon",
        "action": "Action",
        "condition": "Display Condition",

        "editScript": "Action Script Editing",
        "editCondition": "Hide condition editing (return true to hide operation)",
        "up": "Move up",
        "property": "Property",
        "addCustomTool": "Add custom Action",
        "delete": "Delete",
        "setProperties": "Set action properties",
        "restoreDefaultTool": "Restore deleted system Actions",
        "selectDefaultTool": "Select System Action",
        "setReaded": "Mark as read",
        "readed": "Readed"
    },
    "isSave": "Saving, please wait...",
    "scriptIncluder" : {
        "yes": "Yes",
        "no": "No",
        "selectScript": "Select script:",
        "repeatAddScriptNotice": "Please do not add scripts repeatedly",
        "selectScriptNotice": "Please select the script first",
        "asyncLoad": "Asynchronous Load:",
        "asyncLoadScript": "Asynchronous load script:",
        "syncLoadScript": "Sync Load Script:",
        "delete_title": "Cancel loading script confirmation",
        "delete_text": "Are you sure you want to cancel the loading of the selected script?"
    },
    "dictionaryIncluder" : {
        "selectDictionary": "Select:",
        "repeatAddDictionaryNotice": "Please do not add data dictionary repeatedly",
        "rootDictionaryExistNotice": "The root path of the data dictionary has been added, no need to add it again",
        "parentDictionaryExistNotice": "The parent path of the data dictionary has been added, no need to add it again",
        "subDictionaryExistNotice": "The sub-path of the data dictionary already exists, please delete and then add",
        "selectDictionaryNotice": "Please select the data dictionary first",
        "path": "Path:",
        "delete_title": "Confirm to cancel loading data dictionary",
        "delete_text": "Are you sure you want to cancel loading the selected data dictionary?"
    },
    "validation": {
        "validation": "Validation",
        "anytime": "Anytime",
        "decision": "Choose Decision",
        "decisionName": "<decision name>",
        "value": "Value",

        "length": "ValueLength",
        "valueInput": "<value>",
        "isnull": "isnull",
        "notnull": "Notnull",
        "gt": "GreaterThan",
        "lt": "LessThan",
        "equal": "equal",
        "neq": "NotEqual",
        "contain": "Contain",
        "notcontain": "Notcontain",
        "prompt": "Prompt",
        "add": "Add",
        "modify": "Modify",
        "when": "When ",
        "as": "",

        "inputDecisionName": "Please enter the name of the decision",
        "inputValue": "Please enter a value",
        "inputPrompt": "Please enter the prompt content",
        "delete_title": "Delete confirmation",
        "delete_text": "Are you sure you want to delete this verification code?"
    },

    "datagrid" : {
        "import": "Import",
        "export": "export"
    },
    "selectIcon": "Select Icon",
    "selectImage": "Select Image",
    "selectApplication": "Select Application",
    "dutyInputTitle": "Add title parameter",
    "dutyInput": "Please select Unit for duty \"{duty}\"",
    "select": "Select",
    "empty": "Empty",

    "creatorUnit": "Author Unit",
    "currentUnit": "Task Unit",
    "selectUnit": "Select Unit",
    "scriptUnit": "Use script",

    "creatorCompany": "Drafting Company",
    "creatorDepartment": "Drafting Department",
    "currentCompany": "Current Company",
    "currentDepartment": "Current Department",

    "deleteDutyTitle": "Remove job confirmation",
    "deleteDutyText": "Are you sure you want to remove the duty \"{duty}\"?",

    "saveTemplate": "Save as a form template",
    "templateName": "Name",
    "templateCategory": "Category",
    "templateDescription": "Description",
    "save": "Save",
    "cancel": "Cancel",
    "newCategory": "New Category",
    "mustSelectFormStyle": "You must select a form style",
    "notValidJson": "Wrong json format",

    "imageClipper": "ImageEditor",

    "clearNoDomModuleTitle": "Clear the component configuration that is not in the HTML tree",
    "clearNoDomModuleContent": "Do you want to clear the component configuration that is not in the HTML tree? It needs to be saved after clearing to take effect.",

    "filter": {
        "and": "并且",
        "or": "或者",
        "equals": "等于",
        "notEquals": "不等于",
        "greaterThan": "大于",
        "greaterThanOrEqualTo": "大于等于",
        "lessThan": "小于",
        "lessThanOrEqualTo": "小于等于",
        "like": "匹配",
        "notLike": "不匹配",
        "from" : "从",
        "value" : "值"
    },
    "mastInputPath": "请输入数据路径",
    "mastInputTitle": "请输入标题",
    "delete_filterItem_title": "删除过滤条件确认",
    "delete_filterItem": "您确定要删除当前过滤条件吗？",

    "subformNameConflictTitle": "子表单字段名称冲突",
    "subformNameConflictInfor": "子表单的以下字段名称和现有表单冲突：\n{name}",
    "subformConflictTitle": "子表单嵌入错误",
    "subformConflictInfor": "您不能重复嵌入同一个子表单",

    "subformNestedTitle": "子表单嵌入错误",
    "subformNestedInfor": "不能相互嵌套的嵌入子表单",
    "checkSubformNestedError" : "您选择的子表单存在相互嵌套的情况，请检查！",

    "checkSubformTitle": "表单保存校验",
    "checkFormSaveError": "无法保存表单，原因如下：<br>",
    "checkSubformPcInfor": "PC表单中，有以下子表单字段冲突：<br>{subform}<br>",
    "checkSubformMobileInfor": "Mobile表单中，有以下子表单字段冲突：<br>{subform}",

    "implodeError": "要导入的数据格式有误",
    "implodeEmpty": "请在编辑框中填入要导入的数据",
    "implodeConfirmTitle": "导入确认",
    "implodeConfirmText": "导入数据将清除当前页面，并无法撤销，您确定要导入吗？",

    "design": "设计",
    "script": "脚本",
    "html": "HTML",
    "css": "CSS",
    "byModule": "按设计元素",
    "byPath": "按脚本类型",
    "events": "事件",
    "pageform": "页面",
    "importO2": "从O2数据导入",
    "importHTML": "从HTML导入",
    "importOffice": "从WORD或EXCEL导入",
    "importO2_infor": "请将O2格式的表单数据拷贝到以下编辑器中。（使用表单或页面设计器工具条上的“导出”按钮，获取表单数据）<br/>按下Ctrl+Alt+I可格式化数据",
    "importHTML_infor": "请将HTML数据拷贝到以下编辑器中。按下Ctrl+Alt+I可格式化数据",
    "importHTML_infor2": "请将CSS数据拷贝到以下编辑器中。按下Ctrl+Alt+I可格式化数据",
    "importOffice_infor": "请选择一个Word或Excel文件。",
    "import_ok": "导入",
    "import_cancel": "取消",
    "import_option1": "在表格的空单元格中添加输入框",
    "import_option2": "去除空元素",
    "implodeOfficeEmpty": "请先选择要导入的Word或Excel文件",

    "scriptTitle": {
        "validationOpinion": "表单意见校验",
        "validationRoute": "表单路由校验",
        "validationFormCustom": "表单校验",
        "defaultValue": "默认值",
        "validation": "校验脚本",
        "sectionByScript": "区段依据",
        "itemScript": "可选值脚本",
        "iframeScript": "iframe脚本",
        "labelScript": "文本值",
        "rangeKey": "组织范围",
        "identityRangeKey": "身份组织范围",
        "unitRangeKey": "组织选择范围",
        "rangeDutyKey": "职务范围",
        "exclude": "选择排除脚本",
        "cookies": "数据源请求cookies",
        "requestBody": "数据源请求消息体",
        "jsonText": "数据文本",
        "dataScript": "树控件脚本",
        "itemDynamic": "动态选项脚本",
        "defaultData": "数据网格默认值",
        "editableScript": "数据网格是否可编辑",
        "config": "HTML编辑框配置",
        "filterScript": "流程记录过滤",
        "readScript": "Office只读脚本",
        "fileSite": "Office文件site脚本",
        "subformScript": "子表单脚本",
        "selectedScript": "视图选择脚本",
        "action.tools": "操作按钮"
    },
    "copyed": "已复制",
    "selectorButton" : {
        "ok" : "确　定",
        "cancel" : "取 消"
    }

};
