MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.FormDesigner = MWF.xApplication.process.FormDesigner || {};
MWF.xApplication.process.FormDesigner.LP={
	"title": "FormEditor",
	"newForm": "Create Form",
	"property": "Property",
	"tools": "Tools",
	"all": "All",
	"repetitionsId": "Element ID is not unique",
	"notNullId": "Element ID cannot be empty",
	"notNumberId": "Element identifiers cannot be pure numbers",
	"notDoubleDotId": "Element identifier cannot contain two consecutive dots",
	"notSpecialCharacterId": "The following characters cannot be included in the component ID: !{}<>,;'\"",
	"history": "History",
	"componentTree": "Component Tree",
	"invalidElementUIId": "Dado que los datos del componente Element deben vincularse en dos direcciones, no tenga el mismo nombre que el elemento de configuración:",
	"button": {
		"ok": "OK",
		"cancel": "Cancel"
	},
	"version": {
		"title": "View form version history",
		"close": "Close",
		"no": "SerialNumber",
		"updateTime": "UpdateTime",
		"op": "action",
		"person": "person",
		"resume": "Resume",
		"resumeConfirm": "Resume Confirmation",
		"resumeInfo": "Are you sure you need to perform a form recovery operation? After confirming the restoration, the current form will be updated, and the current form needs to be manually saved to take effect.",
		"resumeSuccess": "Resume Successfully"
	},
	"notice": {
		"save_success": "Form saved successfully!",
		"saveTemplate_success": "Form template saved successfully!",
		"saveTemplate_inputName": "Please enter the template title",
		"saveTemplate_inputCategory": "Please confirm the template category",
		"deleteElementTitle": "Delete form element confirmation",
		"deleteElement": "Are you sure you want to delete the current element and its child elements?",
		"deleteRowTitle": "Delete table row confirmation",
		"deleteRow": "Deleting the current row will delete the contents of all cells in this row. Are you sure you want to delete the currently selected row?",
		"deleteColTitle": "Delete table column confirmation",
		"deleteCol": "Deleting the current row will delete the contents of all cells in this column. Are you sure you want to delete the currently selected column?",
		"deleteEventTitle": "Delete Event Confirmation",
		"deleteEvent": "Are you sure you want to delete the current event?",
		"deleteActionTitle": "Delete Action Confirmation",
		"deleteAction": "Are you sure you want to delete the current action?",
		"deleteButtonTitle": "Delete Operation Confirmation",
		"deleteButton": "Are you sure you want to delete the current operation button?",
		"notUseModuleInMobile": "The mobile terminal does not support this component",
		"changeToSequenceTitle": "Confirm",
		"changeToSequence": "This operation will delete the added components. Are you sure you want to change it to the \"Sequence Number\" column?"
	},
	"formAction": {
		"insertRow": "Insert Row",
		"insertCol": "Insert Column",
		"deleteRow": "Delete Row",
		"deleteCol": "Delete column",
		"mergerCell": "Merge Cells",
		"splitCell": "Split Cell",
		"move": "Move",
		"copy": "Copy",
		"delete": "Delete",
		"add": "Add",
		"cut": "Cut",
		"paste": "Paste",
		"open": "Open",
		"script": "Script",
		"create": "Create",
		"mergeCell": "Merge Cells",
		"styleBrush": "StyleBrush",
		"insertTop": "Insert Top",
		"insertBottom": "Insert to the bottom",
		"insertBefore": "InsertBefore",
		"insertAfter": "Insert After",
		"injectNotice": "Hold down Ctrl and release the mouse for precise positioning",
		"selectedContainer": "Select Parent",
		"property": "Property",
		"batchModify": "Batch modify ",
		"selectParent": "Select superior components"
	},
	"actionbar": {
		"readhide": "Set whether to display when reading",
		"edithide": "Set whether to display when editing",
		"hideCondition": "Set hiding conditions",
		"title": "Title",
		"img": "Icon",
		"action": "Action",
		"condition": "Display Condition",
		"editScript": "Action Script Editing",
		"editCondition": "Hide condition editing (return true to hide operation)",
		"up": "Move up",
		"property": "Property",
		"addCustomTool": "Add custom Action",
		"delete": "Delete",
		"setProperties": "Set action properties",
		"restoreDefaultTool": "Restore deleted system Actions",
		"selectDefaultTool": "Select System Action",
		"setReaded": "Mark as read",
		"readed": "Readed"
	},
	"isSave": "Saving, please wait...",
	"scriptIncluder": {
		"yes": "Yes",
		"no": "No",
		"selectScript": "Select script:",
		"repeatAddScriptNotice": "Please do not add scripts repeatedly",
		"selectScriptNotice": "Please select the script first",
		"asyncLoad": "Asynchronous Load:",
		"asyncLoadScript": "Asynchronous load script:",
		"syncLoadScript": "Sync Load Script:",
		"delete_title": "Cancel loading script confirmation",
		"delete_text": "Are you sure you want to cancel the loading of the selected script?"
	},
	"dictionaryIncluder": {
		"selectDictionary": "Select:",
		"repeatAddDictionaryNotice": "Please do not add data dictionary repeatedly",
		"rootDictionaryExistNotice": "The root path of the data dictionary has been added, no need to add it again",
		"parentDictionaryExistNotice": "The parent path of the data dictionary has been added, no need to add it again",
		"subDictionaryExistNotice": "The sub-path of the data dictionary already exists, please delete and then add",
		"selectDictionaryNotice": "Please select the data dictionary first",
		"path": "Path:",
		"delete_title": "Confirm to cancel loading data dictionary",
		"delete_text": "Are you sure you want to cancel loading the selected data dictionary?"
	},
	"validation": {
		"validation": "Validation",
		"anytime": "Anytime",
		"decision": "Choose Decision",
		"decisionName": "<decision name>",
		"value": "Value",
		"length": "ValueLength",
		"valueInput": "<value>",
		"isnull": "isnull",
		"notnull": "Notnull",
		"gt": "GreaterThan",
		"lt": "LessThan",
		"equal": "equal",
		"neq": "NotEqual",
		"contain": "Contain",
		"notcontain": "Notcontain",
		"prompt": "Prompt",
		"add": "Add",
		"modify": "Modify",
		"when": "When ",
		"as": "Time",
		"inputDecisionName": "Please enter the name of the decision",
		"inputValue": "Please enter a value",
		"inputPrompt": "Please enter the prompt content",
		"delete_title": "Delete confirmation",
		"delete_text": "Are you sure you want to delete this verification code?"
	},
	"datagrid": {
		"import": "Import",
		"export": "export"
	},
	"selectIcon": "Select Icon",
	"selectImage": "Select Image",
	"selectApplication": "Select Application",
	"dutyInputTitle": "Add title parameter",
	"dutyInput": "Please select Unit for duty \"{duty}\"",
	"select": "Select",
	"empty": "Empty",
	"creatorUnit": "Author Unit",
	"currentUnit": "Task Unit",
	"selectUnit": "Select Unit",
	"scriptUnit": "Use script",
	"creatorCompany": "Drafting Company",
	"creatorDepartment": "Drafting Department",
	"currentCompany": "Current Company",
	"currentDepartment": "Current Department",
	"deleteDutyTitle": "Remove job confirmation",
	"deleteDutyText": "Are you sure you want to remove the duty \"{duty}\"?",
	"saveTemplate": "Save as a form template",
	"templateName": "Name",
	"templateCategory": "Category",
	"templateDescription": "Description",
	"save": "Save",
	"cancel": "Cancel",
	"newCategory": "New Category",
	"mustSelectFormStyle": "You must select a form style",
	"notValidJson": "Wrong json format",
	"mustSelectDict": "Please select the data dictionary first",
	"mustSelect": "Please select.",
	"imageClipper": "ImageEditor",
	"clearNoDomModuleTitle": "Clear the component configuration that is not in the HTML tree",
	"clearNoDomModuleContent": "Do you want to clear the component configuration that is not in the HTML tree? It needs to be saved after clearing to take effect.",
	"refreshDatatemplateImpExpTitle": "Import field confirmation",
	"refreshDatatemplateImpExpContent": "This operation gets the fields from the internal components of the data template. If you perform this operation, the previously configured fields will be replaced. Do you want to continue?",
	"handWriting": "handwriting",
	"filter": {
		"and": "and",
		"or": "Or",
		"equals": "Equals",
		"notEquals": "NotEquals",
		"greaterThan": "GreaterThan",
		"greaterThanOrEqualTo": "GreaterThanEqual",
		"lessThan": "LessThan",
		"lessThanOrEqualTo": "LessThanEqual",
		"like": "Match",
		"notLike": "NotMatch",
		"from": "From",
		"value": "value"
	},
	"mastInputPath": "Enter Data Path",
	"mastInputTitle": "Enter Title",
	"delete_filterItem_title": "Confirm Delete Filter Condition",
	"delete_filterItem": "Are you sure you want to delete the current filter?",
	"subformNameConflictTitle": "Subform Field Name Conflict",
	"subformNameConflictInfor": "The following field names of the subform conflict with the existing form:\n{name}",
	"subformConflictTitle": "Subform Embedding Error",
	"subformConflictInfor": "You cannot embed the same subform repeatedly",
	"subformNestedTitle": "Subform Embedding Error",
	"subformNestedInfor": "Embedded subforms that cannot be nested within each other",
	"checkSubformNestedError": "The subforms you selected are nested in each other, please check!",
	"checkSubformTitle": "Form Save Check",
	"checkFormSaveError": "Unable to save the form for the following reasons:<br>",
	"checkSubformPcInfor": "The following subform fields conflict in the PC form: <br>{subform}<br>",
	"checkSubformMobileInfor": "In the Mobile form, the following subform fields conflict: <br>{subform}",
	"implodeError": "The format of the data to be imported is incorrect",
	"implodeEmpty": "Please fill in the data to be imported in the edit box",
	"implodeConfirmTitle": "Import Confirmation",
	"implodeConfirmText": "Importing data will clear the current page and cannot be undone. Are you sure you want to import it?",
	"design": "Design",
	"script": "Script",
	"html": "HTML",
	"css": "CSS",
	"byModule": "By Element",
	"byPath": "By Type",
	"events": "Events",
	"pageform": "Page",
	"importO2": "Import from O2 data",
	"importHTML": "Import from HTML",
	"importOffice": "Import from WORD or EXCEL",
	"importO2_infor": "Please copy the form data in O2 format to the following editor. (Use the \"Export\" button on the toolbar of the form or page designer to get the form data). Press Ctrl+Alt+I Formatable data",
	"importHTML_infor": "Please copy the HTML data to the following editor. Press Ctrl+Alt+I to format the data",
	"importHTML_infor2": "Please copy the CSS data to the following editor. Press Ctrl+Alt+I to format the data",
	"importOffice_infor": "Please select a Word or Excel file.",
	"import_ok": "Import",
	"import_cancel": "Cancel",
	"import_option1": "Add an input box to an empty cell in the table",
	"import_option2": "Remove empty elements",
	"implodeOfficeEmpty": "Please select the Word or Excel file to import first",
	"scriptTitle": {
		"validationOpinion": "Form Opinion Verification",
		"validationRoute": "Form routing verification",
		"validationFormCustom": "Form Validation",
		"defaultValue": "Default Value",
		"validation": "Validation Script",
		"sectionByScript": "Section ByScript",
		"itemScript": "Optional value script",
		"iframeScript": "iframeScript",
		"labelScript": "Text Value",
		"rangeKey": "Unit Range",
		"identityRangeKey": "Identity Unit Range",
		"unitRangeKey": "Unit Selection Range",
		"rangeDutyKey": "Duty Range",
		"exclude": "Exclude Script",
		"cookies": "Data source requests cookies",
		"requestBody": "Data source request message body",
		"jsonText": "Data Text",
		"dataScript": "Tree Control Script",
		"itemDynamic": "Dynamic Option Script",
		"defaultData": "Data grid default value",
		"editableScript": "Is editable",
		"config": "HTML editer configuration",
		"filterScript": "Record filtering",
		"readScript": "Office Read-Only Script",
		"fileSite": "Office file site script",
		"subformScript": "Subform Script",
		"selectedScript": "View Selection Script",
		"action.tools": "Action Button"
	},
	"copyed": "Copyed",
	"selectorButton": {
		"ok": "OK",
		"cancel": "Cancel"
	},
	"modules": {
		"label": "Label",
		"textfield": "Textfield",
		"number": "Number",
		"currency": "Currency",
		"org": "Org",
		"calendar": "Calendar",
		"textarea": "Textarea",
		"select": "Select",
		"radio": "Radio",
		"checkbox": "Checkbox",
		"combox": "Combox",
		"opinion": "Opinion",
		"button": "Button",
		"Address": "Address",
		"Actionbar": "Actionbar",
		"Sidebar": "Sidebar",
		"image": "Image",
		"imageclipper": "Imageclipper",
		"attachment": "Attachment",
		"div": "Div",
		"table": "Table",
		"datagrid": "Datagrid(Deprecated)",
		"datatable": "Datatable",
		"datatemplate": "Datatemplate",
		"subform": "Subform",
		"ViewSelector": "ViewSelector",
		"view": "View",
		"stat": "Stat",
		"html": "HTML",
		"common": "Common",
		"tab": "Tab",
		"tree": "Tree",
		"log": "Log",
		"monitor": "Monitor",
		"iframe": "Iframe",
		"documenteditor": "Documenteditor",
		"htmledit": "Htmleditor",
		"office": "Office",
		"yozoOffice": "yozoOffice",
		"statementSelector": "StatementSelector",
		"statement": "Statement",
		"SmartBI": "SmartBI",
		"group_all": "All Module",
		"group_form": "Form",
		"group_layout": "Layout",
		"group_process": "Process",
		"group_filetext": "Filetext",
		"group_function": "Feature",
		"group_element": "Element UI",
		"el_container": "Container",
		"el_icon": "Icon",
		"el_button": "Button",
		"el_radio": "Radio",
		"el_checkbox": "Checkbox",
		"el_select": "Select",
		"el_input": "Input",
		"el_autocomplete": "autocomplete",
		"el_cascader": "Cascader",
		"el_number": "Number",
		"el_switch": "Switch",
		"el_slider": "Slider",
		"el_time": "Time",
		"el_date": "Date",
		"el_datetime": "Datetime",
		"el_rate": "Rate",
		"el_colorpicker": "ColorPicker",
		"el_tree": "Tree",
		"el_dropdown": "Dropdown",
		"el_carousel": "Carousel",
		"el-menu": "menu",
		"el_common": "Common",
		"importer": "DataImporter",
		"readLog": "Read Log",
		"writingBoard": "writingBoard",
		"tinymceEditor": "TinyMCE",
		"relatedLink": "Related Link",
		"associatedDocument": "Associated Document",
		"security": "Security Label",
		"securityInfo": "Only one \"classification identification\" field is allowed"
	},
	"propertyTemplate": {
		"base": "Base",
		"event": "Event",
		"html": "HTML",
		"json": "JSON",
		"action": "Action",
		"select": "Select",
		"id": "ID",
		"name": "Name",
		"description": "Description",
		"appearance": "Appearance",
		"style": "Style",
		"attribute": "Attribute",
		"imageStyle": "Image Style",
		"hideSystemTools": "SystemTools",
		"show": "Show",
		"hide": "Hide",
		"readed": "Readed",
		"category": "Category",
		"formStyle": "FormStyle",
		"icon": "Icon",
		"printForm": "PrintForm",
		"preloadScript": "PreloadScript",
		"script": "Script",
		"dict": "Dictonary",
		"dictName": "Dictonary Name",
		"dictPath": "Data Path",
		"valueKey": "Value attribute name",
		"textKey": "Text attribute name",
		"valueColumn": "Value Column",
		"textColumn": "Text Column",
		"dictKeyNote": "If an object array is returned, you need to configure the value attribute name or text attribute name",
		"firstOptionEnable": "Use Preferences",
		"firstOption": "Preferences",
		"copy": "Copy",
		"paste": "Paste",
		"language": "Language",
		"languageScript": "Language Script (S)",
		"languageInfo": "Return a JSON object containing language information; use \"o2.language\" get current language",
		"SubmitUI": "SubmitUI",
		"submit": "Submit",
		"systemDefault": "Default",
		"selectForm": "SelectForm",
		"computeForm": "ComputeForm",
		"application": "Application",
		"form": "Form",
		"crossApplication": "CrossApplication",
		"computeSubmitAnnotation1": "application name, alias or id",
		"computeSubmitAnnotation2": "form name or id",
		"computeWidgetAnnotation2": "widget name or id",
		"thisApplication": "Current Application",
		"submitFormScript": "Submit Form Script",
		"flowActionScript": "Submit Action Script",
		"handwritingSetting": "Handwriting Comment Setting",
		"enableHandwriting": "Enable Handwriting Comments",
		"handwritingWidth": "handwriting board width",
		"effectivePC": "effective PC",
		"handwritingHeight": "Handwriting board height",
		"promptBoxFlow": "Prompt after flow",
		"yes": "Yes",
		"no": "No",
		"usedNewWindow": "Only used new browser window",
		"promptLocation": "Prompt Location",
		"lefttop": "leftTop",
		"righttop": "rightTop",
		"leftbottom": "leftBottom",
		"rightbottom": "rightBottom",
		"center": "Center",
		"prompt": "Prompt",
		"notClose": "Not Close",
		"closeInfo": "seconds later, automatically close",
		"afterFlow": "After flow",
		"closeWindow": "CloseWindow",
		"redirect": "Redirect",
		"redirectScript": "Redirect Script",
		"returnUrl": "Return a URL for redirection",
		"check": "Verification",
		"checkOpinion": "Verify opinion",
		"checkRoute": "Verify route",
		"checkFlow": "Verify flow",
		"noEventInfo": "Note: When embedded as a sub-form, the following events will not be executed",
		"none": "none",
		"default": "default",
		"byScript": "byScript",
		"scriptLib": "Script Lib",
		"byFormat": "byFormat",
		"table": "Table",
		"languageDefaultInfoScript": "The system will automatically load a script named (\"lp-\"+o2.language) as a language pack",
		"languageDefaultInfoDict": "The system will automatically load a data dictionary named (\"lp-\"+o2.language) as a language pack",
		"prefix": "Prefix",
		"suffix": "Suffix",
		"value": "Value",
		"textValue": "TextValue",
		"showIcon": "Show icon",
		"readonly": "Readonly",
		"AIInput": "AI Input",
		"inputStyle": "Input Style",
		"itemStyle": "Item Style",
		"actionStyles": "Button Styles",
		"imageStyles": "Picture Style",
		"compute": "Compute",
		"create": "Create",
		"save": "Save",
		"linkStyles": "Item Style",
		"defaultValue": "DefaultValue",
		"verificationScript": "Verification Script",
		"verificationLineScript": "Verification Single Line Script",
		"section": "Section",
		"enableSection": "Enable Section",
		"sectionBy": "SectionBy",
		"handler": "Handler",
		"handlerUnit": "Handler Unit",
		"activityId": "Activity Id",
		"splitValue": "Split Value",
		"enableSectionMerge": "Section Merge",
		"showSectionKey": "Show Section Value",
		"editByMerge": "Merge edit (delete section key)",
		"sectionMergeSortScript": "Sorting Script",
		"sectionNodeStyles": "Section entry styles",
		"sectionKeystyles": "Section Value Styles",
		"sectionContentStyles": "Section Content Styles",
		"mergeDisplay": "Read only",
		"editCurrentSection": "Edit (allows editing the current section)",
		"mergeEdit": "Edit (merge data after deleting section key)",
		"sectionKey": "section value",
		"sectionKeyScript": "Section Value Script",
		"textValue1": "Text Value",
		"mergeType": "Merge Type",
		"amountValue": "Total Value",
		"averageValue": "Average",
		"sectionMergeEditScript": "Merge Data Script",
		"sectionMergeReadHtmlScript": "Displayed html script",
		"sectionMergeReadDataScript": "Data Script",
		"htmlScript": "html script",
		"dataScript": "Data Script",
		"bySection": "By Section",
		"byModule": "By Component",
		"totalRow": "Total Row",
		"sectionAmountCellStyle": "section total cell style",
		"showAllSection": "Show All Sections",
		"rangeByDatetime": "Datetime range",
		"rangeByDateAndTime": "Date range and time range",
		"rangeByDate": "Date Range",
		"rangeByTime": "Time Range",
		"rangeByOhter": "Other",
		"enableDate": "Effective Date",
		"enableHours": "Enable Hours Range",
		"enableMinutes": "Effective minutes range",
		"enableSeconds": "Enabled seconds range",
		"decimal": "Decimal",
		"showCard": "Show Card",
		"allowInput": "Allow Input",
		"dataStructure": "data Structure",
		"complete": "Complete",
		"simple": "Simple",
		"separator": "Separator",
		"asyncMode": "Async Mode",
		"asyncLoad": "Async Loading",
		"identity": "Identity",
		"unit": "Unit",
		"duty": "Duty",
		"group": "Group",
		"person": "Person",
		"defaultValueScript": "Default Value Script",
		"showText": "Show Text",
		"showTextScript": "Show Text Script",
		"unitSelectConfig": "Unit Select Config",
		"selectType": "Select Type",
		"selectCount": "Select Count",
		"returnValue": "Return Value",
		"readonlyScript": "Readonly Script",
		"selectTypeInfo": "Please choose an identity to participate in the process!",
		"selectTypeInfo2": "Note: select Person cannot participate in the process!",
		"checkEmpower": "Check Empower",
		"onlyCustom": "Use only custom options",
		"unitRange": "Unit Range",
		"allUnit": "All Unit",
		"specifyUnit": "Specify Unit",
		"draftUnit": "The Unit of the drafter",
		"currentUnit": "The Unit of the current person",
		"inUnit": "Directly affiliated organization",
		"levelIs": "The",
		"levelUnit": " level unit",
		"unitTypeIs": "The unit type is ",
		"deUnit": "Organization of",
		"expandNext": "Expand lower level",
		"selectUnit": "Select Unit",
		"formData": "Form data",
		"dutyRange": "Duty Range",
		"all": "All",
		"all2": "All",
		"specifyDuty": "Specify Duty",
		"byUnit": "By Unit",
		"byDuty": "By Duty",
		"showLevel": "Show Level",
		"byDutyUnit": "By the unit of duty",
		"byIdentityUnit": "By the unit of identity",
		"selectDuty": "Select Duty",
		"customOption": "Custom options",
		"useScriptAddIdOrPerson": "Use script to add identity/person",
		"unitType": "Unit Type",
		"selectRange": "Select Range",
		"specifyGroup": "Specify Group",
		"exclude": "Exclude",
		"excludeInfo": "Exclude the selection of unit, identity, person, and group by scripts",
		"firstLevelSelectable": "Allowed select the first",
		"dateTime": "DateTime",
		"dateTime2": "DateTime",
		"dateOnly": "DateOnly",
		"monthOnly": "MonthOnly",
		"yearOnly": "YearOnly",
		"timeOnly": "TimeOnly",
		"weekOnly": "WeekOnly",
		"multidate": "Dates",
		"datetimerange": "DatetimeRange",
		"daterange": "DateRange",
		"timerange": "TimeRange",
		"monthrange": "MonthRange",
		"selectSecond": "Select Second",
		"timeSelectType": "Time Select Type",
		"timeSelectType_slider": "Slider",
		"timeSelectType_select": "Dropdown",
		"format": "Format",
		"rateTexts": "bad, disappointed, average, satisfied, surprise",
		"allowHalf": "Allow half selection",
		"lowThreshold": "Low-Mid Threshold",
		"lowThresholdNote": "Note: The value itself is divided into low scores",
		"highThreshold": "Mid-High Threshold",
		"highThresholdNote": "Note: The value itself is divided into high scores",
		"lowColor": "Low score color",
		"mediumColor": "Medium color",
		"highColor": "High-score color",
		"voidColor": "Unselected color",
		"disabledVoidColor": "Color is not selected when read-only",
		"showAfter": "Show After",
		"showScore": "Show Score",
		"textColor": "Text Color",
		"textContent": "Text Content",
		"showAlpha": "Show Alpha",
		"colorFormat": "Color Format",
		"nodeKey": "The unique identification key of the node",
		"nodeKeyNote": "Each tree node is used as an attribute for unique identification. The entire tree should be unique.",
		"renderAfterExpand": "Render the child nodes after expanding the node",
		"defaultExpandAll": "Expand all nodes by default",
		"highlightCurrent": "Highlight the currently selected node",
		"currentNodeKey": "The key value of the currently selected node",
		"expandOnClickNode": "Click to expand",
		"clickNode": "When a node is clicked",
		"clickArrow": "When clicking the arrow",
		"checkOnClickNode": "Click to select",
		"clickCheckbox": "When the checkbox is clicked",
		"defaultExpandedkeys": "Nodes expanded by default",
		"defaultExpandedkeysNote": "Returns the default expanded node key array, such as: return['2','4']",
		"showCheckbox": "Allow selection",
		"defaultCheckedKeysNote": "Return to the default checked node key array, such as: return['2','4']",
		"defaultCheckedkeys": "Nodes checked by default",
		"accordion": "Expand one node at the same level each time",
		"indent": "Indent each level",
		"dragdrop": "Dragdrop",
		"draggable": "Dragging allowed",
		"allowDrag": "Judging whether the node can be dragged",
		"allowDrop": "Determine whether the target node can be dropped while dragging",
		"emptyText": "Text with empty content",
		"allowDragNote": "this.event is the incoming node,'return true' means dragging is allowed",
		"allowDropNote": "this.event can get data {draggingNode, dropNode, type }. There are three cases for the type parameter:'prev','inner' and'next', which respectively indicate to be placed in front of the target node, inserted into the target node and Placed after the target node.'return true' means inserting is allowed.",
		"loadFun": "Method of loading subtree data",
		"loadFunNote": "this.event.node is the clicked node, this.event.resolve(data) is the callback after the data is loaded, and the data parameter is the subtree data",
		"dataScriptNote": "Return and format of each node:",
		"labelDescription": "Node Text",
		"childrenDescription": "ChildrenDescription",
		"disabledDescription": "Available after enabling the selection, is the current selection box disabled",
		"isLeafDescription": "Available after enabling dynamic loading, is the current node a leaf node (the arrow does not appear by default)",
		"idDescription": "Only display is not required. It is required to expand the script by default, select by default, check by default, and for script operations. You can use the id or the key set in the basic attributes.",
		"settedKey": "Set key",
		"customDescription": "Other custom data",
		"selectStyle": "Select Style",
		"options": "Options",
		"optionScript": "Options Script",
		"extendOptions": "Additional optional values",
		"divStyle": "Container style",
		"buttonStyle": "Button style",
		"dynamic": "Dynamic",
		"canSelectCount": "Select Count",
		"showSeparator": "Show Separator",
		"optionDynamicScript": "Option Dynamic Script",
		"handwriting": "Handwriting",
		"writingBoard": "Writing Board",
		"width": "Width",
		"height": "Height",
		"recording": "Record",
		"writingPreview": "Writing Preview",
		"commonIdea": "Common opinions",
		"addressStyle": "Address Style",
		"location": "location",
		"right": "right",
		"left": "left",
		"relocate": "Relocate",
		"image": "Image",
		"selectSrc": "Select Resources",
		"imageCropping": "ImageCropping",
		"unlimited": "Unlimited",
		"fixedSize": "Fixed Size",
		"fixedRatio": "Fixed Ratio",
		"aspectRatio": "Aspect Ratio",
		"site": "site",
		"defaultSiteInfo": "（default is the same as the ID）",
		"editInActivex": "Edit in the control",
		"activexId": "Control ID",
		"showType": "Show Type",
		"switchStyle": "Switch Style",
		"allow": "Allow",
		"notAllow": "Not allowed",
		"uploadType": "Allow upload type",
		"wordDoc": "WORD",
		"excelDoc": "EXCEL",
		"pptDoc": "PPT",
		"textDoc": "Text",
		"imgDoc": "Image",
		"pdfDoc": "PDF",
		"zipDoc": "Compressed file",
		"audioDoc": "Audio file",
		"videoDoc": "Video file",
		"otherDoc": "Other",
		"docSample": "Examples: .doc, .docx, .xls",
		"uploadSize": "Allow upload size (M)",
		"uploadSizeInfo": "\"0\" means there is no limit on upload size",
		"uploadCount": "Allowed upload count",
		"uploadCountInfo": "\"0\" means there is no limit on upload count",
		"changeSize": "Change Size",
		"useAttachmentStyle": "Allowed styles",
		"list": "List",
		"sequence": "Sequence",
		"preview": "Preview",
		"attDefaultStyle": "Default style",
		"readonlyMode": "Readonly Mode",
		"allowUpload": "Allow Upload",
		"allowPreview": "Allow Preview",
		"allowDownload": "Allow Download",
		"allowDownloadBatch": "Allow Download Batch",
		"allowEdit": "Allow Edit",
		"officeTool": "Office Tool",
		"allowDelete": "Allow Delete",
		"allowDelMyAtt": "Only allow delete files uploaded by yourself",
		"allowDelCurActivityAtt": "Only allow delete files uploaded on current activity",
		"allowDelMyCurActivityAtt": "Only allow delete files uploaded by this event on current activity",
		"allowReplace": "Allow Replace",
		"allowConfig": "Allow setting permissions",
		"allowOrder": "Allow Ordering",
		"dblClickAttachment": "Double-click attachment",
		"openAtt": "Open",
		"previewFirst": "Preview First",
		"previewAttachmentNote": "The following file formats can be previewed directly: zip, pdf, ofd, png, jpg, bmp, jpeg, gif, js, css, java, json, xml, php, html, htm, xhtml, log, md, txt. The following formats need to install liberoffice: doc, docx, xls, xlsx, ppt, pptx. Directly open attachments that are not in the above formats.",
		"actionBar": "Action Bar",
		"hideEditButton": "Hide Edit Buttons",
		"hideReadButton": "Hide Read Buttons",
		"hideLayoutButton": "Hide Layout Buttons",
		"hideSettingButton": "Hide Setting Buttons",
		"hideModeButton": "Hide Mode Button",
		"showInDatagrid": "Show In Datagrid(Deprecated)",
		"attachmentValidation": "Validate when uploading",
		"attachmentValidationNote": "The currently uploading attachments can be obtained through this.target.uploadingFiles. Returning true means passed, and the system prompts the text to interrupt the upload.",
		"attachmentValidationScript": "Validation script when uploading",
		"hideEraserButton": "Hide Eraser Button",
		"hideEraserRadioButton": "Hide Eraser Radio Button",
		"hideSizeButton": "Hide Size Button",
		"hideColorButton": "Hide Color Button",
		"hideImageButton": "Hide the Insert Picture Button",
		"hideImageClipperButton": "Hide ImageClipper Button",
		"tableSize": "Table Size",
		"row": "Row",
		"col": "Column",
		"tableWidth": "Table Width",
		"pixel": "pixel",
		"percent": "percent",
		"borderWidth": "borderWidth",
		"cellpadding": "cellpadding",
		"cellspacing": "cellspacing",
		"containStyle": "Container Style",
		"containAttribute": "Container Attribute",
		"titleCellStyle": "Title Cell Style",
		"contentCellStyle": "Content Cell Style",
		"layoutCellStyle": "Layout Cell Style",
		"contentTitleCellStyle": "Content Title Cell Style",
		"contentLineStyle": "Content Line Style",
		"contentLineOverStyle": "Content Line Over Style",
		"columns": "Columns",
		"onTheLeft": "On The Left",
		"onTheRight": "On The Right",
		"rows": "Rows",
		"onTheTop": "On The Top",
		"onTheBottom": "On The Bottom",
		"type": "Type",
		"titleCell": "Title Cell",
		"contentCell": "Content Cell",
		"layoutCell": "Layout Cell",
		"other": "Other",
		"permission": "Permission",
		"containerStyles": "Container Styles",
		"tableAttribute": "Table Attribute",
		"border": "Border",
		"backgroundColor": "Background Color",
		"alternateRow": "Alternate Row",
		"tableStyle": "Table Style",
		"defaultData": "Default Data",
		"allowAdd": "Allow Add",
		"allowSort": "Allow Sort",
		"exportImport": "Export Import",
		"enabled": "Enable",
		"disabled": "Disable",
		"onlyExport": "Export Only",
		"onlyImport": "Import Only",
		"exportInfo": "Note: Serial numbers, image, writingBoard, attachment and hidden columns cannot be imported or exported.",
		"buttonLocation": "Button Location",
		"centertop": "centerTop",
		"centerbottom": "centerBottom",
		"importText": "Import Button Text",
		"importExcel": "Import Excel",
		"exportExcel": "Export Excel",
		"importButtonStyle": "Import Button Style",
		"exportFileName": "Export Filename",
		"actionCellStyles": "Action Cell Styles",
		"editCellStyles": "Edit Cell Styles",
		"amountCellStyle": "Amount Cell Style",
		"itemTitleStyle": "Item title style (mobile only)",
		"canEdit": "Editable",
		"exportText": "Export Button Text",
		"exporButtonStyle": "Export Button Style",
		"content": "Content",
		"serialNumber": "SerialNumber",
		"total": "Total",
		"notNeeded": "Not needed",
		"totalValue": "Total Value",
		"totalCount": "Total Count",
		"showCol": "Show Column",
		"hideCol": "Hide Column",
		"delayedLoading": "Delayed Loading",
		"selectSubform": "Select",
		"calculationSubform": "Calculation",
		"subform": "Subform",
		"subformScript": "Subform Script",
		"activeType": "Activation method",
		"click": "Click to activate",
		"delay": "Delay activation",
		"immediately": "Activate directly",
		"buttonText": "Button Text",
		"delayNote": "When you choose delayed activation, you need to use this.form.get(moduleId).active() to activate",
		"viewBox": "View Box",
		"viewBoxTitle": "View Box Title",
		"columnTitle": "Column Title",
		"expandDefault": "Expand Default",
		"expand": "Expand",
		"collapse": "Collapse",
		"singleChoice": "Single Choice",
		"multipleChoice": "Multiple Choice",
		"view": "View",
		"boxTitleStyle": "Box Title Style",
		"boxItemStyle": "Box Item Style",
		"selectResultProcessing": "Result Processing",
		"resultProcessing": "Processing",
		"assignValue": "Assign Value",
		"assignValueForResult": "Assign Value",
		"selectResult": "Select Result",
		"defaultSelectedLineScript": "Default Selected Line Script",
		"allowSelectiLineScript": "Allow Select Line Script",
		"reserve": "Reserve",
		"changeViewReserve": "Reselect after changing the view, retain the original view data",
		"changeViewNotReserve": "Reselect after changing the view, delete the original view data",
		"filter": "Filter",
		"title": "Title",
		"path": "Path",
		"servicePath": "Service Path",
		"servicePathNote": "Example：/jaxrs/user/hotpic/filter/list/page/1/count/6",
		"dataItemPath": "Data item path",
		"dataItemPathNote": "The path of the data to be displayed, such as: data",
		"dataScriptNote2": "The script returns a Promise object or data, such as: return this.Actions.load('x_hotpic_assemble_control').HotPictureInfoAction.listForPage(1, 6);",
		"dataType": "Data Type",
		"text": "Text",
		"number": "Number",
		"currencySymbol": "currency symbol",
		"currencySymbolStyles": "Currency symbol styles",
		"datetime": "Datetime",
		"boolean": "Boolean",
		"resultType": "Result type",
		"asDefaultFilter": "As default filter",
		"asCustomFilter": "As custom filter",
		"logic": "logic",
		"and": "And(and)",
		"or": "Or(or)",
		"compare": "compare",
		"equals": "equals",
		"notEquals": "notEquals",
		"greaterThan": "greaterThan",
		"greaterThanOrEqualTo": "greaterThanOrEqualTo",
		"lessThan": "lessThan",
		"lessThanOrEqualTo": "lessThanOrEqualTo",
		"like": "like",
		"notLike": "notLike",
		"range": "range",
		"in": "in",
		"true": "true",
		"false": "false",
		"filterValueInfo": "Multiple values are separated by half-width commas (,)",
		"defaultFilter": "Default Filter",
		"customFilter": "Custom Filter",
		"filterCond": "Filter",
		"filterNote": "Note: return the filter condition array of the view, please refer to the format ",
		"titleStyle": "Title Style",
		"dataStyle": "Data Style",
		"loadNow": "instantLoading",
		"showTitle": "Show Title",
		"allowSelect": "Allow Select",
		"stat": "Stat",
		"showChart": "Show Chart",
		"showLegend": "Show Legend",
		"showTable": "Show Table",
		"showRowToColumn": "Row to column conversion",
		"chartNodeStyles": "Chart Container Styles",
		"tableNodeStyles": "Table Container Styles",
		"selectTag": "Select Tag",
		"elementTag": "Tag",
		"innerHtml": "Inner Html",
		"delayedTabInfo": "When delayed loading, the content of the tab page that is not displayed will not be loaded, and the content will be loaded only when the tab page is first displayed",
		"tabContainerStyle": "Tab Container Style",
		"contentContainerStyle": "Content Container Style",
		"baseTabStyle": "Default Tab Style",
		"baseTabSpanStyle": "Default Tab Font Style",
		"currentTabStyle": "Selected Tab Style",
		"currentTabSpanStyle": "Selected Tab Font Style",
		"data": "Data",
		"treeAreaStyle": "Tree Container Style",
		"treeNodeStyle": "Tree Node Style",
		"treeNodeFontStyle": "Tree Node Font Style",
		"treeSelectNodeFontStyle": "Selected Node Font Style",
		"record": "Record Source",
		"recordTable": "Table",
		"recordMedia": "Media (Handwriting or voice)",
		"expandHandwritten": "Expand Handwritten",
		"handwrittenWidth": "Handwritten Width",
		"validOnPcSide": "(Valid on pc side)",
		"handwrittenHeight": "Handwritten Height",
		"logFormat": "Format",
		"logFormatScript": "Format Script",
		"logHtmlScript": "Html Script",
		"currentPerson": "Current Processor",
		"readReaded": "Read and Readed",
		"readTitle": "Read Title",
		"readedTitle": "Readed Title",
		"exactMatch": "Exact Match",
		"filterActivity": "Filter By Activity",
		"filterActivityAlias": "Filter By Activity Alias",
		"filterPerson": "Filter By Processor",
		"filterRoute": "Filter By Route",
		"filterScript": "Filter By Script",
		"activity": "Activity",
		"opinionGroup": "Opinion Group",
		"unitLevelName": "Unit level name",
		"unitLevel": "Unit Level",
		"sortInCategory": "Sort In Category",
		"sortByActivity": "Sort By Activity",
		"sortByTimeAsc": "Sort By Time Asc",
		"sortByTimeDesc": "Sort By Time Desc",
		"noSort": "Not Sorted",
		"categoryTable": "Category Table",
		"categoryTableAttr": "Category Table Attribute",
		"categoryTableStyle": "Category Table Style",
		"categoryTitleCellStyle": "Category Titl eCell Style",
		"categoryContentCellStyle": "Category Content Cell Style",
		"categoryContentCellInnerStyle": "Category Content Cell Inner Style",
		"expandOrCollapse": "Expand Or Collapse",
		"defaultExpandCount": "Eefault Expand Count",
		"expandHtml": "Expand Html",
		"collapseHtml": "Collapse Html",
		"relativedLinkField": "Selectable Field：flag,title,createTime,updateTime,creatorPerson,creatorUnit,score",
		"documentListShow": "Document List",
		"associatedDocumentField": "Selectable Field：targetTitle,targetStartTime,targetCreatorPersonCn,targetType,targetCategory",
		"fileTemplate": "File Template",
		"systemTemplate": "System Template",
		"customTemplate": "Custom Template",
		"selectTemplate": "Select Template",
		"templatePath": "Template Path",
		"templateId": "Template Id",
		"edit": "Edit",
		"printFile": "Print File",
		"viewTraces": "View Traces",
		"viewTracesFullScreen": "View Traces Full Screen",
		"viewTracesFullScreenInfo": "Full screen when viewing traces",
		"editScript": "Edit Script",
		"printScript": "Allow Print Script",
		"viewTracesScript": "Allow View Traces Script",
		"handwrittenApproval": "Handwritten Approval",
		"handwrittenApprovalScript": "Allow handwritten approval scripts",
		"handwrittenApprovalType": "Approval Type",
		"savetext": "Save text (as background)",
		"notsavetext": "Do not save text",
		"handwrittenApprovalTypeInfo": "Save the text is suitable for the case where the process text will be modified after the approval is signed",
		"zoom": "Allow Zoom",
		"zoomInfo": "Whether the user can customize the zoom ratio",
		"fullWidth": "Full-width conversion",
		"fullWidthInfo": "Select \"Yes\" to automatically convert the entered half-width interval to full-width",
		"paragraphIndent": "Paragraph indent",
		"paragraphIndentInfo": "Select \"Yes\" to automatically indent the first line of each paragraph",
		"doublePage": "Double Page",
		"doublePageInfo": "Whether to allow double page display",
		"fullScreen": "Full Screen",
		"fullScreenInfo": "Whether to allow full screen display",
		"wordConversion": "Convert to word",
		"wordConversionType": "Convert Type",
		"isConversionSeal": "Convert Seal",
		"wordConversionWithService": "By Service",
		"fileName": "Filename",
		"fileSite": "Attachment site",
		"addPageNumber": "Page Number",
		"addPageNumberInfo": "Whether to add page numbers after converting Word files",
		"whenConversion": "When Conversion",
		"onSubmit": "onSubmit",
		"onSave": "onSave",
		"conversionCondition": "Conversion Condition",
		"alwaysConvert": "Always",
		"whenConditionsMet": "Met Condition",
		"static": "static",
		"wordConversionEncryption": "Edit Protection",
		"wordConversionEncryptionInfo1": "(only available in OOXML mode)",
		"wordConversionEncryptionInfo": "If you select \"Yes\", the converted file will be edited and protected, and all editing of the converted Word document will be restricted. The password provided below will be used as the password for document protection. If the password is not provided, editing protection will also be carried out, but the protection can be removed in Work without a password.",
		"wordEncryptionPasswordType": "Password",
		"toWordPasswordScript": "Password Script",
		"wordEncryptionPasswordInput": "Enter password",
		"toWordPasswordScriptInfo": "Return a string as the password. Note: Administrators or clerks and other related personnel need to know this password, otherwise the converted files will not be unprotected",
		"config": "Config",
		"copiesSecretPriority": "Copies Secret And Priority",
		"isShow": "Whether to show",
		"copies": "Copies",
		"auto": "Auto",
		"showScript": "Show Script",
		"bindValue": "Bind Value",
		"bindValueScript": "Bind Value Script",
		"secret": "Secret",
		"priority": "Priority",
		"redHeader": "RedHeader",
		"redLine": "RedLine",
		"fileNo": "FileNo",
		"signer": "Signer",
		"subject": "Subject",
		"editSubjectInfo": "When the title allows editing, please do not bind value",
		"mainSend": "Main Send",
		"attachment": "Attachment",
		"attachmentText": "Attachment Text",
		"attachmentInfor": "[Click here to edit the content of attachments]",
		"issuanceUnit": "Issuance Unit",
		"issuanceDate": "Issuance Date",
		"annotation": "Annotation",
		"copyto": "Copyto",
		"copyto2": "Copyto2",
		"editionUnit": "Edition Unit",
		"editionDate": "Edition Date",
		"meetingAttend": "Meeting Attend",
		"meetingLeave": "Meeting Leave",
		"meetingSit": "Meeting Sit",
		"meetingRecord": "Meeting Record",
		"customElement": "Custom element configuration",
		"subjectEditBindFormData": "Bind Data",
		"fontFamily": "Font Family",
		"autoCorrect": "Auto Correct",
		"ckeditorInfo": "For more attribute help, please see ",
		"ckeditorInfo2": "Return the Config object of CKEditor, used for editor initialization",
		"ckeditorInfo3": "For more event help, please see",
		"tinymceInfo": "For more attribute help, please see",
		"tinymceInfo2": "Return TinyMCE's Config object for editor initialization",
		"tinymceInfo3": "queryLoad,postLoad, load and afterLoad events are O2 platform events, other events are Tinymce editor events, please see",
		"base64Encode ": " Image Base64 Encode",
		"imagePreview ": " View larger images",
		"ieOnly": "Only available in IE browser",
		"keepHistory": "Whether to keep the historical version",
		"openAttachment": "Can the attachment be opened",
		"attachmentId": "Attachment Id",
		"attachmentReadonly": "Attachment Readonly",
		"autoSave": "Autosave",
		"historyCount": "Keep History Count",
		"timeInterval": "Time Interval (minute)",
		"showSummary": "Show summary when control cannot be enabled",
		"byTemplate": "By Template",
		"readonlyCondition": "Read only when the conditions are met",
		"officeFileSite": "Office File site",
		"userTitle": "Control Title",
		"userId": "Control Id",
		"toolbar": "Toolbar",
		"tools": "Tools",
		"newDoc": "New Document",
		"openLocal": "Open Local File",
		"saveLocal": "Save To Local",
		"traceSwitch": "Trace Switch",
		"fullscreenMode": "Full Screen",
		"toolbarSwitch": "Toolbar Switch",
		"printPreview": "Print Preview",
		"redFileButton": "redFile Button",
		"stampButton": "Stamp Button",
		"showHistory": "Show History",
		"showTitleBar": "Show Title Bar",
		"showMenuBar": "Show Menu Bar",
		"showToolBar": "Show Toolbar",
		"showStatusBar": "Show Status Bar",
		"showZoom": "Show Zoom",
		"borderStyle": "Border Style",
		"borderColor": "Border Color",
		"flat": "Flat",
		"noCopy": "No Copy",
		"keepTraces": "Keep Traces",
		"read": "Read",
		"otherAttr": "Other Attribute",
		"querySelectBox": "Query Select Box",
		"selectBoxTitle": "Select Box Title",
		"query": "Query",
		"pathInfo": "Note: The path is written as \"table alias. field name\", such as: o.title",
		"parameterNote": "Note: The parameter corresponds to the where condition in the query statement and the total number statement like \":field\", fill in \"field\".",
		"source": "Source",
		"method": "Method",
		"systemSource": "System Source",
		"applicationService": "Application",
		"parameter": "Parameter",
		"requestBody": "Request Body",
		"test": "Test",
		"hostPort": "Host/Port",
		"handle": "Handle",
		"widget": "widget",
		"widgetScript": "Widget Script",
		"parameterScript": "Parameter Script (Return JSON Object)",
		"insertWidget": "Tnsert Widget",
		"selectWidget": "Select Widget",
		"selectPortal": "Select Portal",
		"inDiv": "Wrapped in a div",
		"outerSideModuleId": "external related component ID",
		"addButtonId": "Add button ID",
		"deleteSelectedButtonId": "Delete selected item button ID",
		"selectAllModuleId": "Select All component ID",
		"selectedValue": "Selected Value",
		"innerSideModuleId": "Internal related component ID",
		"deleteButtonId": "Delete Button ID",
		"sequenctModuleId": "Sequence number component ID",
		"selectModuleId": "Select component ID",
		"defaultShow": "Default Show",
		"item": "Item",
		"maxItemCount": "Maximum Add",
		"minItemCount": "Minimum Keep",
		"dtImportInfor": "Note: Pictures, attachments, datagrids, and sub datatemplates cannot be imported or exported.",
		"importButtonId": "Import Button Id",
		"exportButtonId": "Export Button Id",
		"importExporConfig": "Import and export field configuration",
		"validationPopFormConfig": "PopForm Config",
		"validationPopFormHeight": "PopForm Height",
		"validationPopFormWidth": "PopForm Width",
		"validationTableStyle": "Validation Table Style",
		"validationTitleTdStyle": "Validation Title Cell Style",
		"validationContentTdStyle": "Validation Content Td Style",
		"validationTableAttribute": "Validation Table Attribute",
		"count": "Count",
		"import": "Import",
		"datatableEditMode": "Edit Mode",
		"datatableEditModeValue": [
			"single row",
			"multiple rows"
		],
		"onlyPc": "Available on PC only",
		"size": "Size",
		"color": "Color",
		"el_bt_default": "Default",
		"el_bt_primary": "Primary",
		"el_bt_success": "Success",
		"el_bt_warning": "Warning",
		"el_bt_danger": "Danger",
		"el_bt_info": "Info",
		"el_bt_text": "Text",
		"el_plain": "Plain",
		"el_round": "Round",
		"el_circle": "Circle",
		"el_icon": "Icon",
		"el_disabled": "Disabled",
		"el_loading": "Loading",
		"el_autofocus": "Autofocus",
		"el_isText": "Show Text",
		"layout": "Layout",
		"layoutCode": "Layout Code",
		"layoutTemplate": "Layout Template",
		"elGroupStyles": "Group Styles",
		"elGroupProperties": "Group Properties",
		"el_border": "Show Border",
		"el_radioColor": "Font Color",
		"el_radioFillColor": "Fill Color",
		"el_buttonRadio": "Button Mode",
		"datatemplateOuterNote": "Note: The data template can have multiple layers, and the external component identifier must be filled in with the following rules:<br/>1. Single layer or the outermost data template, fill in \"fieldId\" to indicate the direct component on the form.<br/>2. If there are multiple data templates, \"./fieldId\" means components at the same level as the current data template, \"../fieldId\" means components at the same level as the previous data template, and so on .<br/>3. If there is a multi-layer data template, you can also use \"datatemplateId.*.datatemplateId2.*.fieldId\" to indicate the full-level path. datatemplateId indicates the id of the first-level data template, and datatemplateId2 indicates the id of the second-level. ",
		"datatemplateInnerNote": "Note: Regardless of single-layer or multi-layer data template, directly fill in the component ID.",
		"importModel": "Import Model",
		"enable": "enable",
		"disable": "disable",
		"downloadTempalte": "Download Template",
		"downloadTempalteId": "Download template component ID",
		"downloadTempalteIdNote": "You can create a component on the form and fill in the component ID here. The system will bind the click event of the download template to the node of the component.",
		"province": "Province",
		"city": "City",
		"county": "County",
		"useTextFieldNote": "Note: It is recommended to use text components",
		"useChecboxNote": "Note: It is recommended to use multiple selection components",
		"checkboxValueNote": "Note: the optional value corresponding to the selected component",
		"checkboxValueAllNote": "Note: Corresponding to the optional value of select all components",
		"notShow": "Not Show",
		"insertDataTemplate": "Insert Data Template",
		"widthModules": "Insert related components",
		"ckeditConfig": "Ckeditor Options",
		"ckeditConfigInfor": "Return Json Object",
		"ckeditConfigInfor1": "The editor toolbar function can be configured through the following link：",
		"ckeditConfigInfor2": "../o2_lib/htmleditor/ckeditor4161/samples/toolbarconfigurator/index.html",
		"ckeditConfigInfor3": "click here",
		"ckeditConfigInfor4": "For more configuration, please check the official website of Ckeditor",
		"ckeditConfigInfor5": "https://ckeditor.com/ckeditor-4/",
		"ckeditConfigInfor6": "Note: After the editor properties are customized, the text format may no longer meet the national party and government agency official document format standards",
		"showRead": "Show Read",
		"password": "password",
		"search": "search",
		"email": "email",
		"datetime-local": "datetime-local",
		"month": "month",
		"date": "date",
		"time": "time",
		"week": "week",
		"textarea": "textarea",
		"wordNumber": "wordNumber",
		"maxlength": "maxlength",
		"clearable": "clearable",
		"showPassword": "showPassword",
		"prefixIcon": "prefixIcon",
		"suffixIcon": "suffixIcon",
		"textareaRows": "Textarea Rows",
		"autosize": "autosize",
		"minRows": "minRows",
		"maxRows": "maxRows",
		"resize": "resize",
		"resizeNone": "none",
		"resizeBoth": "both",
		"resizeHorizontal": "horizontal",
		"resizeVertical": "vertical",
		"el_placement": "placement",
		"popperClass": "Popper Class",
		"triggerOnFocus": "trigger on focus",
		"itemScriptInfo": "Return a function。Function(queryString, callback)",
		"multiple": "Multiple",
		"collapseTags": "Collapse Tags",
		"multipleInfo": "Take effect when multiple selections are possible",
		"filterable": "Filterable",
		"filterMethod": "Filter Method",
		"filterRemote": "Filter Remote",
		"allowCreate": "Allow Create",
		"noMatchText": "No Match Text",
		"noDataText": "No Data Text",
		"loadingText": "Loading Text",
		"remoteMethod": "Remote Method",
		"multipleLimit": "Multiple Limit",
		"max": "max",
		"min": "min",
		"step": "step",
		"step_strictly": "step_strictly",
		"precision": "precision",
		"controls": "controls",
		"controlsPosition": "controls-position",
		"activeText": "active text",
		"inactiveText": "inactive text",
		"activeColor": "active color",
		"inactiveColor": "inactive color",
		"activeIconClass": "active icon",
		"inactiveIconClass": "inactive icon",
		"activeValue": "active value",
		"inactiveValue": "inactive value",
		"valueType": "Value Type",
		"showInput": "Show Input Box",
		"showInputControls": "Show Input Controls Buttons",
		"inputSize": "Input Box Size",
		"sliderRange": "Whether to select the range",
		"sliderVertical": "Vertical Mode",
		"sliderMarks": "Marks Marks",
		"showTooltip": "Show Tooltip",
		"tooltipClass": "tip class name",
		"formatTooltip": "Formatting Tip",
		"formatTooltipScript": "Returns a formatting function:",
		"showStops": "Whether to show break points",
		"marksScriptInfo": "Return an object, the type of key must be number and the value must be in the closed interval [min, max], and each mark can be styled separately",
		"optionsGroup": "Options Group",
		"selectItemScriptInfo": "Return a list of optional value arrays; or a Promise object that resolves the optional value array.",
		"selectTemplete": "Custom Options Templete",
		"showAllLevels": "Show All Levels",
		"checkStrictly": "Check Strictly",
		"checkStrictlyInfo": "Whether to strictly observe that the parent and child nodes are not related to each other",
		"emitPath": "Emit Path",
		"emitPathInfo": "When the selected node is changed, whether to return an array composed of the values of the various levels of the menu where the node is located, if set to false, only the value of the node is returned",
		"lazy": "Dynamic loading",
		"lazyLoadScript": "Loading Method",
		"props_value": "Value Key",
		"props_label": "Label Key",
		"props_children": "Children Key",
		"props_disabled": "Disabled Key",
		"props_leaf": "Leaf key",
		"expandTrigger": "Expand Trigger",
		"beforeFilter": "Before Filter",
		"filterMethodInfo": "Return a Function. Custom search logic, the first parameter is the node node, the second parameter is the search keyword keyword, by returning a boolean value to indicate whether it is hit or not",
		"beforeFilterInfo": "Return a Function. Filter the hook before, the parameter is the input value, if it returns false or returns a Promise and is rejected, then stop filtering",
		"lazyLoadScriptInfo": "The method of loading dynamic data is only valid when lazy is true; it returns a function (node, resolve), where node is the currently clicked node, and resolve is the callback for the completion of data loading (must be called)",
		"firstPageNumber": "First Page Number",
		"showOptions": "Show Options",
		"onInput": "When inputting",
		"onFocus": "On Click",
		"emptyValue": "Empty Value",
		"showZero": "Show Zero",
		"showNullString": "Show an empty string",
		"centerServer": "Center service",
		"pathConditions": "Path default conditions",
		"parameterConditions": "Parameter default conditions",
		"addDefaultConditionByPath": "Add default condition by path",
		"addDefaultConditionByParameter": "Add default condition by parameter",
		"placementValue": [
			"upper center",
			"upper left",
			"upper right",
			"lower center",
			"lower left",
			"lower right"
		],
		"trigger": "Trigger drop down",
		"triggerValue": [
			"Mouse over",
			"Mouse click"
		],
		"hideOnClick": "Click to hide the menu",
		"showTimeout": "Expand Delay",
		"hideTimeout": "Folding Delay",
		"splitButton": "Enable button click",
		"splitButtonType": "Button Type",
		"menuItem": "Menu Item",
		"dropdownDefaultText": "Dropdown Menu",
		"showButton": "Show Button",
		"countPerline": "Options per line",
		"countPerlineNote": "0 means no limit",
		"wps": {
			"config": "Config",
			"options": "options",
			"topArea": "topArea",
			"show": "show",
			"hide": "hide",
			"headArea": "headArea",
			"showMode": "showMode",
			"showMode_normal": "showMode normal",
			"showMode_simple": "showMode simple",
			"wordConfig": "wordConfig",
			"comment": "comment",
			"isShowDocMap": "isShowDocMap",
			"isBestScale": "isBestScale(PC)",
			"isShowBottomStatusBar": "isShowBottomStatusBar",
			"isOpenIntoEdit": "isOpenIntoEdit",
			"component": "Module",
			"isComponent": "isComponent（PC）",
			"HeaderLeft": "HeaderLeft",
			"HeaderRight": "HeaderRight",
			"FloatQuickHelp": "FloatQuickHelp",
			"HistoryVersion": "HistoryVersion",
			"HistoryRecord": "HistoryRecord",
			"HistoryVersionDivider": "HistoryVersionDivider",
			"TabPrintPreview": "TabPrintPreview",
			"MenuPrintPreview": "MenuPrintPreview",
			"ReviewTrackChanges": "ReviewTrackChanges",
			"TrackChanges": "TrackChanges",
			"ContextMenuConvene": "ContextMenuConvene",
			"isComponentMobile": "isComponentMobile",
			"Logo": "Logo",
			"Cooperation": "Cooperation",
			"More": "More",
			"SendButton": "SendButton",
			"CooperHistoryMenuItem": "CooperHistoryMenuItem",
			"WriterHoverToolbars": "WriterHoverToolbars",
			"ReadSetting": "ReadSetting"
		},
		"onlyoffice": {
			"config": "Config",
			"moduleConfig": "moduleConfig",
			"autosave": "autosave",
			"chat": "chat",
			"comments": "comments",
			"compatibleFeatures": "compatibleFeatures",
			"plugins": "plugins",
			"reviewDisplay": "reviewDisplay",
			"reviewDisplay_markup": "markup",
			"reviewDisplay_final": "final",
			"reviewDisplay_original": "original",
			"showReviewChanges": "showReviewChanges",
			"trackChanges": "trackChanges",
			"spellcheck": "spellcheck",
			"viewSet": "viewSet",
			"compactHeader": "compactHeader",
			"compactToolbar": "compactToolbar",
			"feedback": "feedback",
			"help": "help",
			"toolbarHideFileName": "toolbarHideFileName",
			"toolbarNoTabs": "toolbarNoTabs",
			"unit": "unit",
			"unit_cm": "cm",
			"unit_pt": "pt",
			"unit_inch": "inch",
			"zoom": "zoom",
			"hideRightMenu": "hideRightMenu",
			"individualization": "individualization",
			"address": "address",
			"mail": "mail",
			"info": "info",
			"company": "company",
			"www": "www",
			"feedbackUrl": "feedbackUrl",
			"logoImg": "left logo（172x40）",
			"logoUrl": "logo link"
		},
		"smartbi": {
			"select": "select",
			"displayToolbar": "toolbar",
			"toolbarShow": "show",
			"toolbarHide": "hide",
			"displayLeftTree": "leftTree",
			"leftTreeShow": "show",
			"leftTreeHide": "hide"
		},
		"weeks": {
			"arr": [
				"Sun",
				"Mon",
				"Tues",
				"Wed",
				"Thur",
				"Fri",
				"Sat"
			]
		},
		"tabletWidth": "Tablet Width",
		"tabletHeight": "Tablet Height",
		"tabletSizeNote": "Valid only on the PC terminal, full screen horizontally on the mobile terminal",
		"tabletToolbarNote": "Only valid on PC, not displayed on mobile",
		"editable": "Editable",
		"firstDayOfWeek": "Week start day",
		"disabledDate": "Disabled selection",
		"disabledDateNote": "this.event is the incoming date, 'return true' means the date is disabled",
		"disabledDateScript": "Disabled date script selection",
		"selectableRangeNote": "Return a selectable time range, such as return '18:30:00 - 20:30:00' or return ['09:30:00 - 12:00:00', '14:30:00 - 18:30:00']",
		"selectableRangeScript": "Time selectable range script",
		"placeholder": "Placeholder text",
		"rangeSeparator": "Separate Text",
		"startPlaceholder": "Start placeholder text",
		"endPlaceholder": "End placeholder text",
		"arrowControl": "Use arrows to select time",
		"timeSelectType2": "Time Selection Type",
		"isRange": "Range",
		"fixedTimePoint": "Fixed Time",
		"anyTimePoint": "Anytime",
		"to": "to",
		"startTime": "Start Time",
		"endTime": "End Time",
		"startDate": "Start Date",
		"endDate": "End Date",
		"selectableRange": "Selectable Range",
		"endSelectableRange": "End SelectableRange",
		"initialIndex": "Initial Slide Index",
		"autoplay": "Auto switch",
		"interval": "Switch Interval",
		"indicatorPosition": "Indicator Position",
		"indicatorPositionValue": [
			"internal",
			"external",
			"none"
		],
		"arrow": "arrow",
		"arrowValue": [
			"Display when the mouse is over",
			"Always display",
			"Do not display"
		],
		"carouselTypeValue": [
			"default",
			"card"
		],
		"loop": "Whether to loop",
		"direction": "Display direction",
		"directionValue": [
			"Horizontal",
			"Vertical"
		],
		"hotpicture": "Hotpicture",
		"page": "Number of pages",
		"filterParameter": "Filter parameter",
		"selectComponent": "Select Application",
		"calculationComponent": "Calculation Application Path",
		"component": "Application",
		"scriptComponentNote": "Return application path, such as organization management",
		"componentScript": "Apply Path Script",
		"applicationOptions": "Application Options",
		"applicationStatus": "Application Status",
		"titleAddTo": "Title Line Add",
		"firstLine": "First Line",
		"lastLine": "last line",
		"digitsToSeparate": "Number of separator digits",
		"digitsToSeparateNote": "Add a separator for every few digits, such as adding a separator for every three digits in the thousands, then fill in 3.",
		"defaultOptionScript": "Default optional value script",
		"statement": "query",
		"associatedDocumentScriptNote": "The current item data can be obtained through this. line",
		"base64Encode": "Image Base64 encoding",
		"imagePreview": "Browsing the original image",
		"flow": "Continue circulation",
		"el_iconPosition": "Icon position",
		"checkOtherFlow": "Verify other circulation methods",
		"checkOtherFlowNote": "When adding, resetting, or returning, execute the verification script. Obtain the flow method (add as: addTask, reset as: reset, return as: goBack) through this. form. opinion, and other parameters of the flow through this. form. flowData",
		"forceClearCustomViewStyle": "Clear custom styles when switching",
		"forceClearCustomStyle": "Clear custom styles when switching"
	},
	"smartbi": {
		"nosetup": "please install SmartBI APP first",
		"txt": "SmartBI"
	},
	"onlyoffice": {
		"nosetup": "please install onlyOffice APP first"
	},
	"wpsoffice": {
		"nosetup": "please install wpsOffice APP first"
	},
	"officeonline": {
		"nosetup": "please install OfficeOnline APP first"
	},
	"actionBar": {
		"close": "Close",
		"closeTitle": "Close Document",
		"save": "Save",
		"saveTitle": "Save Document",
		"flow": "Flow",
		"flowTitle": "Flow Document",
		"submit": "Submit",
		"submitTitle": "Submit document",
		"reroute": "Reroute",
		"rerouteTitle": "Reroute to other Activity",
		"reset": "Reset",
		"resetTitle": "Reset to other Person",
		"split": "AddSplit",
		"splitTitle": "Add Split Work branch",
		"retract": "Retract",
		"retractTitle": "Retract Task to current person",
		"rollback": "Rollback",
		"rollbackTitle": "Rollback the work to the specified activity, without keeping process records",
		"delete": "Delete",
		"deleteTitle": "Delete Document",
		"terminate": "Terminate",
		"terminateTitle": "End file process",
		"print": "Print",
		"printTitle": "Open through the print form, and print the document",
		"press": "Urge",
		"pressTitle": "Urge",
		"pause": "Pending",
		"pauseTitle": "Set the task as pending",
		"resume": "Resume",
		"resumeTitle": "Resume the task from pending",
		"downloadAll": "Download",
		"downloadAllTitle": "Download the form and all attachments",
		"monitor": "Process Monitor",
		"monitorTitle": "Process Monitor",
		"setReaded": "Mark as read",
		"readed": "Readed",
		"addTask": "Add Task",
		"addTaskTitle": "Add task to current activity",
		"goBack": "Go Back",
		"goBackTitle": "Go back to a past event"
	},
	"filedConfigurator": {
		"sequence": "Sequence",
		"fieldTitle": "Field Title",
		"fieldId": "Field ID",
		"action": "Action",
		"moveup": "Move to the previous line",
		"deleteRow": "Delete Row",
		"insertRow": "Insert Row",
		"importFromForm": "Import field configuration from the interface",
		"forceClearCustomViewStyle": "Clear custom styles when switching"
	},
	"formToolbar": {
		"save": "Save form",
		"saveNew": "Save as template",
		"preview": "preview",
		"print": "print",
		"formExplode": "Form Export",
		"formImplode": "Form import",
		"formImplodeO2": "Import from O2 data",
		"formImplodeO2Title": "Import O2 format form",
		"htmlImplode": "Import from HTML",
		"officeImplode": "Import from WORD or EXCEL",
		"help": "help",
		"clearNoDomModule": "Clear component configurations that are not in the HTML tree",
		"autoSave": "AutoSave",
		"brush": "brush",
		"viewAllVersion": "View all form versions"
	}
}
MWF.xApplication.process.FormDesigner["lp."+o2.language] = MWF.xApplication.process.FormDesigner.LP