MWF.xApplication.process.FormDesigner.LP = {
    "title": "FormEditor",
    "newForm": "Create Form",
    "property": "Property",
    "tools": "Tools",
    "all": "All",

    "repetitionsId": "Element ID is not unique",
    "notNullId": "Element ID cannot be empty",

    "button":{
        "ok": "OK",
        "cancel": "Cancel"
    },
    "version" : {
        "title" : "View form version history",
        "close" : "Close",
        "no":"SerialNumber",
        "updateTime":"UpdateTime",
        "op":"action",
        "resume" : "Resume",
        "resumeConfirm" : "Resume Confirmation",
        "resumeInfo" : "Are you sure you need to perform a form recovery operation? After confirming the restoration, the current form will be updated, and the current form needs to be manually saved to take effect.",
        "resumeSuccess" :"Resume Successfully"
    },
    "notice": {
        "save_success": "Form saved successfully!",
        "saveTemplate_success": "Form template saved successfully!",
        "saveTemplate_inputName": "Please enter the template title",
        "saveTemplate_inputCategory": "Please confirm the template category",

        "deleteElementTitle": "Delete form element confirmation",
        "deleteElement": "Are you sure you want to delete the current element and its child elements?",

        "deleteRowTitle": "Delete table row confirmation",
        "deleteRow": "Deleting the current row will delete the contents of all cells in this row. Are you sure you want to delete the currently selected row?",
        "deleteColTitle": "Delete table column confirmation",
        "deleteCol": "Deleting the current row will delete the contents of all cells in this column. Are you sure you want to delete the currently selected column?",
        "deleteEventTitle": "Delete Event Confirmation",
        "deleteEvent": "Are you sure you want to delete the current event?",

        "deleteActionTitle": "Delete Action Confirmation",
        "deleteAction": "Are you sure you want to delete the current action?",

        "deleteButtonTitle": "Delete Operation Confirmation",
        "deleteButton": "Are you sure you want to delete the current operation button?",

        "notUseModuleInMobile": "The mobile terminal does not support this component",

        "changeToSequenceTitle": "Confirm",
        "changeToSequence": "This operation will delete the added components. Are you sure you want to change it to the \"Sequence Number\" column?"
    },

    "formAction": {
        "insertRow": "Insert Row",
        "insertCol": "Insert Column",
        "deleteRow": "Delete Row",
        "deleteCol": "Delete column",
        "mergerCell": "Merge Cells",
        "splitCell": "Split Cell",
        "move": "Move",
        "copy": "Copy",
        "delete": "Delete",
        "add": "Add",
        "script": "Script",
        "styleBrush": "StyleBrush",
        "insertTop": "Insert Top",
        "insertBottom": "Insert to the bottom",
        "insertBefore": "InsertBefore",
        "insertAfter": "Insert After",
        "injectNotice": "Hold down Ctrl and release the mouse for precise positioning"
    },

    "actionbar": {
        "readhide": "Set whether to display when reading",
        "edithide": "Set whether to display when editing",
        "hideCondition": "Set hiding conditions",
        "title": "Title",
        "img": "Icon",
        "action": "Action",
        "condition": "Display Condition",

        "editScript": "Action Script Editing",
        "editCondition": "Hide condition editing (return true to hide operation)",
        "up": "Move up",
        "property": "Property",
        "addCustomTool": "Add custom Action",
        "delete": "Delete",
        "setProperties": "Set action properties",
        "restoreDefaultTool": "Restore deleted system Actions",
        "selectDefaultTool": "Select System Action",
        "setReaded": "Mark as read",
        "readed": "Readed"
    },
    "isSave": "Saving, please wait...",
    "scriptIncluder" : {
        "yes": "Yes",
        "no": "No",
        "selectScript": "Select script:",
        "repeatAddScriptNotice": "Please do not add scripts repeatedly",
        "selectScriptNotice": "Please select the script first",
        "asyncLoad": "Asynchronous Load:",
        "asyncLoadScript": "Asynchronous load script:",
        "syncLoadScript": "Sync Load Script:",
        "delete_title": "Cancel loading script confirmation",
        "delete_text": "Are you sure you want to cancel the loading of the selected script?"
    },
    "dictionaryIncluder" : {
        "selectDictionary": "Select:",
        "repeatAddDictionaryNotice": "Please do not add data dictionary repeatedly",
        "rootDictionaryExistNotice": "The root path of the data dictionary has been added, no need to add it again",
        "parentDictionaryExistNotice": "The parent path of the data dictionary has been added, no need to add it again",
        "subDictionaryExistNotice": "The sub-path of the data dictionary already exists, please delete and then add",
        "selectDictionaryNotice": "Please select the data dictionary first",
        "path": "Path:",
        "delete_title": "Confirm to cancel loading data dictionary",
        "delete_text": "Are you sure you want to cancel loading the selected data dictionary?"
    },
    "validation": {
        "validation": "Validation",
        "anytime": "Anytime",
        "decision": "Choose Decision",
        "decisionName": "<decision name>",
        "value": "Value",

        "length": "ValueLength",
        "valueInput": "<value>",
        "isnull": "isnull",
        "notnull": "Notnull",
        "gt": "GreaterThan",
        "lt": "LessThan",
        "equal": "equal",
        "neq": "NotEqual",
        "contain": "Contain",
        "notcontain": "Notcontain",
        "prompt": "Prompt",
        "add": "Add",
        "modify": "Modify",
        "when": "When ",
        "as": "",

        "inputDecisionName": "Please enter the name of the decision",
        "inputValue": "Please enter a value",
        "inputPrompt": "Please enter the prompt content",
        "delete_title": "Delete confirmation",
        "delete_text": "Are you sure you want to delete this verification code?"
    },

    "datagrid" : {
        "import": "Import",
        "export": "export"
    },
    "selectIcon": "Select Icon",
    "selectImage": "Select Image",
    "selectApplication": "Select Application",
    "dutyInputTitle": "Add title parameter",
    "dutyInput": "Please select Unit for duty \"{duty}\"",
    "select": "Select",
    "empty": "Empty",

    "creatorUnit": "Author Unit",
    "currentUnit": "Task Unit",
    "selectUnit": "Select Unit",
    "scriptUnit": "Use script",

    "creatorCompany": "Drafting Company",
    "creatorDepartment": "Drafting Department",
    "currentCompany": "Current Company",
    "currentDepartment": "Current Department",

    "deleteDutyTitle": "Remove job confirmation",
    "deleteDutyText": "Are you sure you want to remove the duty \"{duty}\"?",

    "saveTemplate": "Save as a form template",
    "templateName": "Name",
    "templateCategory": "Category",
    "templateDescription": "Description",
    "save": "Save",
    "cancel": "Cancel",
    "newCategory": "New Category",
    "mustSelectFormStyle": "You must select a form style",
    "notValidJson": "Wrong json format",

    "imageClipper": "ImageEditor",

    "clearNoDomModuleTitle": "Clear the component configuration that is not in the HTML tree",
    "clearNoDomModuleContent": "Do you want to clear the component configuration that is not in the HTML tree? It needs to be saved after clearing to take effect.",

    "filter": {
        "and": "and",
        "or": "Or",
        "equals": "Equals",
        "notEquals": "NotEquals",
        "greaterThan": "GreaterThan",
        "greaterThanOrEqualTo": "GreaterThanEqual",
        "lessThan": "LessThan",
        "lessThanOrEqualTo": "LessThanEqual",
        "like": "Match",
        "notLike": "NotMatch",
        "from": "From",
        "value": "value"
    },
    "mastInputPath": "Enter Data Path",
    "mastInputTitle": "Enter Title",
    "delete_filterItem_title": "Confirm Delete Filter Condition",
    "delete_filterItem": "Are you sure you want to delete the current filter?",

    "subformNameConflictTitle": "Subform Field Name Conflict",
    "subformNameConflictInfor": "The following field names of the subform conflict with the existing form:\n{name}",
    "subformConflictTitle": "Subform Embedding Error",
    "subformConflictInfor": "You cannot embed the same subform repeatedly",

    "subformNestedTitle": "Subform Embedding Error",
    "subformNestedInfor": "Embedded subforms that cannot be nested within each other",
    "checkSubformNestedError": "The subforms you selected are nested in each other, please check!",

    "checkSubformTitle": "Form Save Check",
    "checkFormSaveError": "Unable to save the form for the following reasons:<br>",
    "checkSubformPcInfor": "The following subform fields conflict in the PC form: <br>{subform}<br>",
    "checkSubformMobileInfor": "In the Mobile form, the following subform fields conflict: <br>{subform}",

    "implodeError": "The format of the data to be imported is incorrect",
    "implodeEmpty": "Please fill in the data to be imported in the edit box",
    "implodeConfirmTitle": "Import Confirmation",
    "implodeConfirmText": "Importing data will clear the current page and cannot be undone. Are you sure you want to import it?",

    "design": "Design",
    "script": "Script",
    "html": "HTML",
    "css": "CSS",
    "byModule": "By Element",
    "byPath": "By Type",
    "events": "Events",
    "pageform": "Page",
    "importO2": "Import from O2 data",
    "importHTML": "Import from HTML",
    "importOffice": "Import from WORD or EXCEL",
    "importO2_infor": "Please copy the form data in O2 format to the following editor. (Use the \"Export\" button on the toolbar of the form or page designer to get the form data). Press Ctrl+Alt+I Formatable data",
    "importHTML_infor": "Please copy the HTML data to the following editor. Press Ctrl+Alt+I to format the data",
    "importHTML_infor2": "Please copy the CSS data to the following editor. Press Ctrl+Alt+I to format the data",
    "importOffice_infor": "Please select a Word or Excel file.",
    "import_ok": "Import",
    "import_cancel": "Cancel",
    "import_option1": "Add an input box to an empty cell in the table",
    "import_option2": "Remove empty elements",
    "implodeOfficeEmpty": "Please select the Word or Excel file to import first",

    "scriptTitle": {
        "validationOpinion": "Form Opinion Verification",
        "validationRoute": "Form routing verification",
        "validationFormCustom": "Form Validation",
        "defaultValue": "Default Value",
        "validation": "Validation Script",
        "sectionByScript": "Section ByScript",
        "itemScript": "Optional value script",
        "iframeScript": "iframeScript",
        "labelScript": "Text Value",
        "rangeKey": "Unit Range",
        "identityRangeKey": "Identity Unit Range",
        "unitRangeKey": "Unit Selection Range",
        "rangeDutyKey": "Duty Range",
        "exclude": "Exclude Script",
        "cookies": "Data source requests cookies",
        "requestBody": "Data source request message body",
        "jsonText": "Data Text",
        "dataScript": "Tree Control Script",
        "itemDynamic": "Dynamic Option Script",
        "defaultData": "Data grid default value",
        "editableScript": "Is editable",
        "config": "HTML editer configuration",
        "filterScript": "Record filtering",
        "readScript": "Office Read-Only Script",
        "fileSite": "Office file site script",
        "subformScript": "Subform Script",
        "selectedScript": "View Selection Script",
        "action.tools": "Action Button"
    },
    "copyed": "Copyed",
    "selectorButton" : {
        "ok" : "OK",
        "cancel" : "Cancel"
    },
    "modules": {
        "label": "Label",
        "textfield": "Textfield",
        "number": "Number",
        "org": "Org",
        "calendar": "Calendar",
        "textarea": "Textarea",
        "select": "Select",
        "radio": "Radio",
        "checkbox": "Checkbox",
        "combox": "Combox",
        "opinion": "Opinion",
        "button": "Button",
        "Address": "Address",
        "Actionbar": "Actionbar",
        "Sidebar": "Sidebar",
        "image": "Image",
        "imageclipper": "Imageclipper",
        "attachment": "Attachment",
        "div": "Div",
        "table": "Table",
        "datagrid": "Datagrid(Deprecated)",
        "datatable": "Datatable",
        "datatemplate": "Datatemplate",
        "subform": "Subform",
        "ViewSelector": "ViewSelector",
        "view": "View",
        "stat": "Stat",
        "html": "HTML",
        "common": "Common",
        "tab": "Tab",
        "tree": "Tree",
        "log": "Log",
        "monitor": "Monitor",
        "iframe": "Iframe",
        "documenteditor": "Documenteditor",
        "htmledit": "Htmleditor",
        "office": "Office",
        "statementSelector": "StatementSelector",
        "statement": "Statement",
        "importer": "DataImporter"
    },
    "propertyTemplate": {
        "base": "Base",
        "event": "Event",
        "html": "HTML",
        "json": "JSON",
        "action": "Action",
        "select": "Select",

        "id": "ID",
        "name": "Name",
        "description": "Description",
        "appearance": "Appearance",
        "style": "Style",
        "attribute": "Attribute",

        "hideSystemTools": "SystemTools",
        "show": "Show",
        "hide": "Hide",
        "readed": "Readed",

        "category": "Category",
        "formStyle": "FormStyle",
        "icon": "Icon",
        "printForm": "PrintForm",
        "preloadScript": "PreloadScript",
        "script": "Script",
        "copy": "Copy",
        "paste": "Paste",
        "language": "Language",
        "languageScript": "Language Script (S)",
        "languageInfo": "Return a JSON object containing language information; use \"o2.language\" get current language",
        "SubmitUI": "SubmitUI",
        "submit": "Submit",
        "systemDefault": "Default",
        "selectForm": "SelectForm",
        "computeForm": "ComputeForm",
        "application": "Application",
        "form": "Form",
        "crossApplication": "CrossApplication",
        "computeSubmitAnnotation1": "application name, alias or id",
        "computeSubmitAnnotation2": "form name or id",
        "thisApplication": "Current Application",
        "submitFormScript": "Submit Form Script",
        "flowActionScript": "Submit Action Script",
        "handwritingWidth": "Handwriting width",
        "effectivePC": "Effective on pc",
        "handwritingHeight": "andwriting height",
        "promptBoxFlow": "Prompt after flow",
        "yes": "Yes",
        "no": "No",
        "usedNewWindow": "Only used new browser window",
        "promptLocation": "Prompt Location",
        "lefttop": "leftTop",
        "righttop": "rightTop",
        "leftbottom": "leftBottom",
        "rightbottom": "rightBottom",
        "center": "Center",
        "prompt": "Prompt",
        "notClose":"Not Close",
        "closeInfo": "seconds later, automatically close",
        "afterFlow": "After flow",
        "closeWindow": "CloseWindow",
        "redirect": "Redirect",
        "redirectScript": "Redirect Script",
        "returnUrl": "Return a URL for redirection",
        "check": "Verification",
        "checkOpinion": "Verify opinion",
        "checkRoute": "Verify route",
        "checkFlow": "Verify flow",
        "noEventInfo": "Note: When embedded as a sub-form, the following events will not be executed",

        "none": "none",
        "default": "default",
        "byScript": "byScript",
        "languageDefaultInfo": "The system will automatically load a data dictionary named (\"lp-\"+o2.language) as a language pack",

        "prefix": "Prefix",
        "suffix": "Suffix",

        "value": "Value",
        "textValue": "TextValue",

        "showIcon": "Show icon",
        "readonly": "Readonly",
        "AIInput": "AI Input",
        "inputStyle": "Input Style",
        "compute": "Compute",
        "create": "Create",
        "save": "Save",

        "defaultValue": "DefaultValue",
        "verificationScript": "Verification Script",
        "section": "Section",
        "enableSection": "Enable Section",
        "sectionBy": "SectionBy",
        "handler": "Handler",
        "handlerUnit": "Handler Unit",
        "activityId": "Activity Id",
        "splitValue": "Split Value",

        "decimal": "Decimal",

        "showCard": "Show Card",
        "allowInput": "Allow Input",
        "dataStructure": "data Structure",
        "complete": "Complete",
        "simple": "Simple",
        "separator": "Separator",

        "identity": "Identity",
        "unit": "Unit",
        "duty": "Duty",
        "group": "Group",
        "person": "Person",

        "defaultValueScript": "Default Value Script",
        "showText": "Show Text",
        "showTextScript": "Show Text Script",
        "unitSelectConfig": "Unit Select Config",
        "selectType": "Select Type",
        "selectCount": "Select Count",
        "returnValue": "Return Value",

        "selectTypeInfo": "Please choose an identity to participate in the process!",
        "selectTypeInfo2": "Note: select Person cannot participate in the process!",
        "checkEmpower": "Check Empower",
        "onlyCustom": "Use only custom options",
        "unitRange": "Unit Range",
        "allUnit": "All Unit",
        "specifyUnit": "Specify Unit",
        "draftUnit": "The Unit of the drafter",
        "currentUnit": "The Unit of the current person",
        "inUnit": "Directly affiliated organization",
        "levelIs": "The",
        "levelUnit": " level unit",
        "unitTypeIs": "The unit type is ",
        "deUnit": "",
        "expandNext": "Expand lower level",
        "selectUnit": "Select Unit",
        "formData": "Form data",
        "dutyRange": "Duty Range",
        "all": "All",
        "all2": "All",
        "specifyDuty": "Specify Duty",
        "byUnit": "By Unit",
        "byDuty": "By Duty",
        "showLevel": "Show Level",
        "byDutyUnit": "By the unit of duty",
        "byIdentityUnit": "By the unit of identity",
        "selectDuty": "Select Duty",
        "customOption": "Custom options",
        "useScriptAddIdOrPerson": "Use script to add identity/person",
        "unitType": "Unit Type",
        "selectRange": "Select Range",
        "specifyGroup": "Specify Group",
        "exclude": "Exclude",
        "excludeInfo": "Exclude the selection of unit, identity, person, and group by scripts",

        "dateTime": "DateTime",
        "dateOnly": "DateOnly",
        "monthOnly": "MonthOnly",
        "yearOnly": "YearOnly",
        "timeOnly": "TimeOnly",
        "selectSecond": "Select Second",
        "format": "Format",

        "selectStyle": "Select Style",
        "options": "Options",
        "optionScript": "Options Script",
        "divStyle": "Container style",
        "buttonStyle": "Button style",

        "dynamic": "Dynamic",
        "canSelectCount": "Select Count",
        "showSeparator": "Show Separator",
        "optionDynamicScript": "Option Dynamic Script",

        "handwriting": "Handwriting",
        "writingBoard": "Writing Board",
        "width": "Width",
        "height": "Height",
        "recording": "Record",
        "writingPreview": "Writing Preview",

        "addressStyle": "Address Style",

        "image": "Image",
        "selectSrc": "Select Resources",

        "imageCropping": "ImageCropping",
        "unlimited": "Unlimited",
        "fixedSize": "Fixed Size",
        "fixedRatio": "Fixed Ratio",
        "aspectRatio": "Aspect Ratio",

        "site": "site",
        "defaultSiteInfo":"（default is the same as the ID）",
        "editInActivex": "Edit in the control",
        "activexId": "Control ID",
        "showType": "Show Type",
        "switchStyle": "Switch Style",
        "allow": "Allow",
        "notAllow": "Not allowed",
        "uploadType": "Allow upload type",
        "wordDoc": "WORD",
        "excelDoc": "EXCEL",
        "pptDoc": "PPT",
        "textDoc": "Text",
        "imgDoc": "Image",
        "pdfDoc": "PDF",
        "zipDoc": "Compressed file",
        "audioDoc": "Audio file",
        "videoDoc": "Video file",
        "otherDoc": "Other",
        "docSample": "Examples: .doc, .docx, .xls",
        "uploadSize": "Allow upload size (M)",
        "uploadSizeInfo": "\"0\" means there is no limit on upload size",
        "uploadCount": "Allowed upload count",
        "uploadCountInfo": "\"0\" means there is no limit on upload count",
        "changeSize": "Change Size",
        "useAttachmentStyle": "Allowed styles",
        "list": "List",
        "sequence": "Sequence",
        "preview": "Preview",
        "attDefaultStyle": "Default style",
        "readonlyMode": "Readonly Mode",
        "allowUpload": "Allow Upload",
        "allowPreview": "Allow Preview",
        "allowDownload": "Allow Download",
        "allowEdit": "Allow Edit",
        "allowDelete": "Allow Delete",
        "allowDelMyAtt": "Only allow delete files uploaded by yourself",
        "allowDelCurActivityAtt": "Only allow delete files uploaded on current activity",
        "allowDelMyCurActivityAtt": "Only allow delete files uploaded by this event on current activity",
        "allowReplace": "Allow Replace",
        "actionBar": "Action Bar",
        "hideEditButton": "Hide Edit Buttons",
        "hideReadButton": "Hide Read Buttons",
        "hideLayoutButton": "Hide Layout Buttons",
        "hideSettingButton": "Hide Setting Buttons",
        "hideModeButton": "Hide Mode Button",
        "showInDatagrid": "Show In Datagrid Or Datatable",

        "tableSize": "Table Size",
        "row": "Row",
        "col": "Column",
        "tableWidth": "Table Width",
        "pixel": "pixel",
        "percent": "percent",
        "borderWidth": "borderWidth",
        "cellpadding": "cellpadding",
        "cellspacing": "cellspacing",

        "titleCellStyle": "Title Cell Style",
        "contentCellStyle": "Content Cell Style",
        "layoutCellStyle": "Layout Cell Style",

        "columns": "Columns",
        "onTheLeft": "On The Left",
        "onTheRight": "On The Right",
        "rows": "Rows",
        "onTheTop": "On The Top",
        "onTheBottom": "On The Bottom",
        "type": "Type",
        "titleCell": "Title Cell",
        "contentCell": "Content Cell",
        "layoutCell": "Layout Cell",
        "other": "Other",

        "permission": "Permission",

        "containerStyles": "Container Styles",
        "tableAttribute": "Table Attribute",
        "border": "Border",
        "backgroundColor": "Background Color",
        "alternateRow": "Alternate Row",
        "tableStyle": "Table Style",
        "defaultData": "Default Data",
        "allowAdd": "Allow Add",
        "exportImport": "Export Import",
        "enabled": "Enable",
        "disabled": "Disable",
        "onlyExport": "Export Only",
        "onlyImport": "Import Only",
        "exportInfo": "Note: Serial numbers, image, attachment and hidden columns cannot be imported or exported.",
        "buttonLocation": "Button Location",
        "centerTop": "centerTop",
        "centerBottom": "centerBottom",
        "importText": "Import Button Text",
        "importExcel": "Import Excel",
        "importButtonStyle": "Import Button Style",
        "exportFileName": "Export Filename",
        "actionCellStyles": "Action Cell Styles",
        "editCellStyles": "Edit Cell Styles",
        "amountCellStyle": "Amount Cell Style",
        "itemTitleStyle": "Item title style (mobile only)",
        "canEdit": "Editable",
        "exportText": "Export Button Text",
        "exporButtonStyle": "Export Button Style",

        "content": "Content",
        "serialNumber": "SerialNumber",
        "total": "Total",
        "notNeeded": "Not needed",
        "totalValue": "Total Value",
        "totalCount": "Total Count",
        "showCol": "Show Column",
        "hideCol": "Hide Column",

        "delayedLoading": "Delayed Loading",
        "selectSubform": "Select",
        "calculationSubform": "Calculation",
        "subform": "Subform",
        "subformScript": "Subform Script",

        "viewBox": "View Box",
        "viewBoxTitle": "View Box Title",
        "columnTitle": "Column Title",
        "expandDefault": "Expand Default",
        "expand": "Expand",
        "collapse": "Collapse",
        "singleChoice": "Single Choice",
        "multipleChoice": "Multiple Choice",
        "view": "View",
        "boxTitleStyle": "Box Title Style",
        "boxItemStyle": "Box Item Style",
        "selectResultProcessing": "Result Processing",
        "resultProcessing": "Processing",
        "assignValue": "Assign Value",
        "assignValueForResult": "Assign Value",
        "selectResult": "Select Result",
        "defaultSelectedLineScript": "Default Selected Line Script",
        "allowSelectiLineScript": "Allow Select Line Script",
        "filter": "Filter",
        "title": "Title",
        "path": "Path",
        "dataType": "Data Type",
        "text": "Text",
        "number": "Number",
        "datetime": "Datetime",
        "boolean": "Boolean",
        "asDefaultFilter": "As default filter",
        "asCustomFilter": "As custom filter",
        "logic": "logic",
        "and": "And(and)",
        "or": "Or(or)",
        "compare": "compare",
        "equals": "equals",
        "notEquals": "notEquals",
        "greaterThan": "greaterThan",
        "greaterThanOrEqualTo": "greaterThanOrEqualTo",
        "lessThan": "lessThan",
        "lessThanOrEqualTo": "lessThanOrEqualTo",
        "like": "like",
        "notLike": "notLike",
        "range": "range",
        "in": "in",
        "true": "true",
        "false": "false",
        "filterValueInfo": "Multiple values are separated by half-width commas (,)",
        "defaultFilter": "Default Filter",
        "customFilter": "Custom Filter",

        "titleStyle": "Title Style",
        "dataStyle": "Data Style",
        "loadNow": "instantLoading",
        "showTitle": "Show Title",
        "allowSelect": "Allow Select",

        "stat": "Stat",
        "showChart": "Show Chart",
        "showLegend": "Show Legend",
        "showTable": "Show Table",

        "selectTag": "Select Tag",
        "elementTag": "Tag",
        "innerHtml": "Inner Html",

        "delayedTabInfo": "When delayed loading, the content of the tab page that is not displayed will not be loaded, and the content will be loaded only when the tab page is first displayed",
        "tabContainerStyle": "Tab Container Style",
        "contentContainerStyle": "Content Container Style",
        "baseTabStyle": "Default Tab Style",
        "baseTabSpanStyle": "Default Tab Font Style",
        "currentTabStyle": "Selected Tab Style",
        "currentTabSpanStyle": "Selected Tab Font Style",

        "data": "Data",
        "treeAreaStyle": "Tree Container Style",
        "treeNodeStyle": "Tree Node Style",
        "treeNodeFontStyle": "Tree Node Font Style",
        "treeSelectNodeFontStyle": "Selected Node Font Style",

        "record": "Record Source",
        "recordTable": "Table",
        "recordMedia": "Media (Handwriting or voice)",
        "expandHandwritten": "Expand Handwritten",
        "handwrittenWidth": "Handwritten Width",
        "validOnPcSide": "(Valid on pc side)",
        "handwrittenHeight": "Handwritten Height",
        "logFormat": "Format",
        "logFormatScript": "Format Script",
        "currentPerson": "Current Processor",
        "readReaded": "Read and Readed",
        "readTitle": "Read Title",
        "readedTitle": "Readed Title",
        "filterActivity": "Filter By Activity",
        "filterActivityAlias": "Filter By Activity Alias",
        "filterPerson": "Filter By Processor",
        "filterRoute": "Filter By Route",
        "filterScript": "Filter By Script",
        "activity": "Activity",
        "opinionGroup": "Opinion Group",
        "sortInCategory": "Sort In Category",
        "sortByActivity": "Sort By Activity",
        "sortByTimeAsc": "Sort By Time Asc",
        "sortByTimeDesc": "Sort By Time Desc",
        "noSort": "Not Sorted",
        "categoryTable": "Category Table",
        "categoryTableAttr": "Category Table Attribute",
        "categoryTableStyle": "Category Table Style",
        "categoryTitleCellStyle": "Category Titl eCell Style",
        "categoryContentCellStyle": "Category Content Cell Style",
        "categoryContentCellInnerStyle": "Category Content Cell Inner Style",
        "expandOrCollapse": "Expand Or Collapse",
        "defaultExpandCount": "Eefault Expand Count",
        "expandHtml": "Expand Html",
        "collapseHtml": "Collapse Html",

        "fileTemplate": "File Template",
        "systemTemplate": "System Template",
        "customTemplate": "Custom Template",
        "selectTemplate": "Select Template",
        "templatePath": "Template Path",
        "edit": "Edit",
        "printFile": "Print File",
        "viewTraces": "View Traces",
        "editScript": "Edit Script",
        "printScript": "Allow Print Script",
        "viewTracesScript": "Allow View Traces Script",
        "zoom": "Allow Zoom",
        "zoomInfo": "Whether the user can customize the zoom ratio",
        "fullWidth": "Full-width conversion",
        "fullWidthInfo": "Select \"Yes\" to automatically convert the entered half-width interval to full-width",
        "paragraphIndent": "Paragraph indent",
        "paragraphIndentInfo": "Select \"Yes\" to automatically indent the first line of each paragraph",
        "doublePage": "Double Page",
        "doublePageInfo": "Whether to allow double page display",
        "fullScreen": "Full Screen",
        "fullScreenInfo": "Whether to allow full screen display",
        "wordConversion": "Convert to word",
        "wordConversionType": "Convert Type",
        "wordConversionWithService": "By Service",
        "fileName": "Filename",
        "fileSite": "Attachment site",
        "addPageNumber": "Page Number",
        "addPageNumberInfo": "Whether to add page numbers after converting Word files",
        "whenConversion": "When Conversion",
        "onSubmit": "onSubmit",
        "onSave": "onSave",
        "conversionCondition": "Conversion Condition",
        "alwaysConvert": "Always",
        "whenConditionsMet": "Met Condition",
        "config": "Config",
        "copiesSecretPriority": "Copies Secret And Priority",
        "isShow": "Whether to show",
        "showScript": "Show Script",
        "copies": "Copies",
        "auto": "Auto",
        "bindValue": "Bind Value",
        "bindValueScript": "Bind Value Script",
        "secret": "Secret",
        "priority": "Priority",
        "redHeader": "RedHeader",
        "redLine": "RedLine",
        "fileNo": "FileNo",
        "signer": "Signer",
        "subject": "Subject",
        "allowEdit": "Allow Edit",
        "editSubjectInfo": "When the title allows editing, please do not bind value",
        "mainSend": "Main Send",
        "attachment": "Attachment",
        "issuanceUnit": "Issuance Unit",
        "issuanceDate": "Issuance Date",
        "annotation": "Annotation",
        "copyto": "Copyto",
        "copyto2": "Copyto2",
        "editionUnit": "Edition Unit",
        "editionDate": "Edition Date",
        "meetingAttend": "Meeting Attend",
        "meetingLeave": "Meeting Leave",
        "meetingSit": "Meeting Sit",
        "meetingRecord": "Meeting Record",
        "customElement": "Custom element configuration",
        "subjectEditBindFormData": "Bind Data",

        "autoCorrect": "Auto Correct",
        "ckeditorInfo": "For more attribute help, please see ",
        "ckeditorInfo2": "Return the Config object of CKEditor, used for editor initialization",
        "ckeditorInfo3": "For more event help, please see",

        "ieOnly": "Only available in IE browser",
        "keepHistory": "Whether to keep the historical version",
        "openAttachment": "Can the attachment be opened",
        "attachmentId": "Attachment Id",
        "attachmentReadonly": "Attachment Readonly",
        "autoSave": "Autosave",
        "historyCount": "Keep History Count",
        "timeInterval": "Time Interval (minute)",
        "showSummary": "Show summary when control cannot be enabled",
        "byTemplate": "By Template",
        "readonlyCondition": "Read only when the conditions are met",
        "officeFileSite": "Office File site",
        "userTitle": "Control Title",
        "userId": "Control Id",
        "toolbar": "Toolbar",
        "tools": "Tools",
        "newDoc": "New Document",
        "openLocal": "Open Local File",
        "saveLocal": "Save To Local",
        "traceSwitch": "Trace Switch",
        "fullscreenMode": "Full Screen",
        "toolbarSwitch": "Toolbar Switch",
        "printPreview": "Print Preview",
        "redFileButton": "redFile Button",
        "stampButton": "Stamp Button",
        "showHistory": "Show History",
        "showTitleBar": "Show Title Bar",
        "showMenuBar": "Show Menu Bar",
        "showToolBar": "Show Toolbar",
        "showStatusBar": "Show Status Bar",
        "showZoom": "Show Zoom",
        "borderStyle": "Border Style",
        "borderColor": "Border Color",
        "flat": "Flat",
        "noCopy": "No Copy",
        "keepTraces": "Keep Traces",
        "read": "Read",
        "otherAttr": "Other Attribute",

        "querySelectBox": "Query Select Box",
        "selectBoxTitle": "Select Box Title",
        "query": "Query",
        "pathInfo": "Note: The path is written as \"table alias. field name\", such as: o.title",

        "source": "Source",
        "method": "Method",
        "systemSource": "System Source",
        "applicationService": "Application",
        "parameter": "Parameter",
        "requestBody": "Request Body",
        "test": "Test",
        "hostPort": "Host/Port",

        "handle": "Handle",

        "widget": "widget",
        "widgetScript": "Widget Script",
        "parameterScript": "Parameter Script (Return JSON Object)",
        "insertWidget": "Tnsert Widget",
        "selectWidget": "Select Widget",
        "inDiv": "Wrapped in a div",

        "outerSideModuleId": "external related component ID",
        "addButtonId": "Add button ID",
        "deleteSelectedButtonId": "Delete selected item button ID",
        "selectAllModuleId": "Select All component ID",
        "selectedValue": "Selected Value",
        "innerSideModuleId": "Internal related component ID",
        "deleteButtonId": "Delete Button ID",
        "sequenctModuleId": "Sequence number component ID",
        "selectModuleId": "Select component ID",
        "defaultShow": "Default Show",
        "item": "Item",
        "maxItemCount": "Maximum Add",
        "minItemCount": "Minimum Keep",
        "dtImportInfor": "Note: Pictures, attachments, datagrids, and sub datatemplates cannot be imported or exported.",
        "importButtonId": "Import Button Id",
        "exportButtonId": "Export Button Id",
        "importExporConfig": "Import and export field configuration",
        "validationPopFormConfig": "PopForm Config",
        "validationPopFormHeight": "PopForm Height",
        "validationPopFormWidth": "PopForm Width",
        "validationTableStyle": "Validation Table Style",
        "validationTitleTdStyle": "Validation Title Cell Style",
        "validationContentTdStyle": "Validation Content Td Style",
        "validationTableAttribute": "Validation Table Attribute",
        "count": "Count",
        "import" : "Import",
        "datatableEditMode": "Edit Mode",
        "datatableEditModeValue": ["single row","multiple rows"],
        "onlyPc": "Available on PC only",
        "datatemplateOuterNote": "Note: The data template can have multiple layers, and the external component identifier must be filled in with the following rules:<br/>" +
            "1. Single layer or the outermost data template, fill in \"fieldId\" to indicate the direct component on the form.<br/>" +
            "2. If there are multiple data templates, \"./fieldId\" means components at the same level as the current data template, \"../fieldId\" means components at the same level as the previous data template, and so on .<br/>" +
            "3. If there is a multi-layer data template, you can also use \"datatemplateId.*.datatemplateId2.*.fieldId\" to indicate the full-level path. datatemplateId indicates the id of the first-level data template, and datatemplateId2 indicates the id of the second-level. ",
        "datatemplateInnerNote": "Note: Regardless of single-layer or multi-layer data template, directly fill in the component ID.",
        "importModel": "Import Model",
        "enable": "enable",
        "disable": "disable",
        "downloadTempalte": "Download Template",
        "downloadTempalteId": "Download template component ID",
        "downloadTempalteIdNote": "You can create a component on the form and fill in the component ID here. The system will bind the click event of the download template to the node of the component.",
        "province": "Province",
        "city": "City",
        "county": "County",
        "useTextFieldNote": "Note: It is recommended to use text components",
        "useChecboxNote": "Note: It is recommended to use multiple selection components",
        "checkboxValueNote": "Note: the optional value corresponding to the selected component",
        "checkboxValueAllNote": "Note: Corresponding to the optional value of select all components",

        "notShow": "Not Show"
    },
    "actionBar": {
        "close":"Close",
        "closeTitle": "Close Document",
        "save": "Save",
        "saveTitle": "Save Document",
        "flow": "Flow",
        "flowTitle": "Flow Document",
        "reroute": "Reroute",
        "rerouteTitle": "Reroute to other Activity",
        "reset": "Reset",
        "resetTitle": "Reset to other Person",
        "split": "AddSplit",
        "splitTitle": "Add Split Work branch",
        "retract": "Retract",
        "retractTitle": "Retract Task to current person",
        "rollback": "Rollback",
        "rollbackTitle": "Rollback the work to the specified activity, without keeping process records",
        "delete": "Delete",
        "deleteTitle": "Delete Document",
        "print": "Print",
        "printTitle": "Open through the print form, and print the document",
        "press": "Urge",
        "pressTitle": "Urge",
        "pause": "Pending",
        "pauseTitle": "Set the task as pending",
        "resume": "Resume",
        "resumeTitle": "Resume the task from pending",
        "downloadAll": "Download",
        "downloadAllTitle": "Download the form and all attachments",
        "setReaded": "Mark as read",
        "readed": "Readed"
    },
    "filedConfigurator": {
        "sequence": "Sequence",
        "fieldTitle": "Field Title",
        "fieldId": "Field ID",
        "action": "Action",
        "moveup": "Move to the previous line",
        "deleteRow": "Delete Row",
        "insertRow": "Insert Row"
    }

};
