MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.FormDesigner = MWF.xApplication.process.FormDesigner || {};
MWF.xApplication.process.FormDesigner.LP={
	"title": "Edición de formulario",
	"newForm": "Crear nuevo formulario",
	"property": "Propiedad",
	"tools": "Herramientas",
	"all": "Todos",
	"repetitionsId": "Identificador de elemento repetido",
	"notNullId": "El identificador del elemento no puede estar vacío",
	"notNumberId": "El identificador del elemento no puede ser solo un número",
	"notDoubleDotId": "El identificador del elemento no puede contener dos puntos consecutivos",
	"notSpecialCharacterId": "Los siguientes caracteres no se pueden incluir en el ID del componente: !{}<>,;'\"",
	"history": "Historial",
	"componentTree": "Árbol",
	"invalidElementUIId": "Dado que los datos del componente Element deben vincularse en dos direcciones, no tenga el mismo nombre que el elemento de configuración:",
	"button": {
		"ok": "Aceptar",
		"cancel": "Cancelar"
	},
	"version": {
		"title": "Ver registro de versiones del formulario",
		"close": "Cerrar",
		"no": "No.",
		"updateTime": "Fecha de actualización",
		"op": "Acciones",
		"person": "Operador",
		"resume": "Restaurar",
		"resumeConfirm": "Confirmación",
		"resumeInfo": "¿Está seguro de que desea restaurar el formulario? Después de confirmar la restauración, se actualizará el formulario actual y deberá guardarlo manualmente para que surta efecto.",
		"resumeSuccess": "Restauración exitosa"
	},
	"notice": {
		"save_success": "¡El formulario se ha guardado con éxito!",
		"saveTemplate_success": "¡Se ha guardado el modelo de formulario con éxito!",
		"saveTemplate_inputName": "Ingrese el título del modelo",
		"saveTemplate_inputCategory": "Seleccione la categoría del modelo",
		"deleteElementTitle": "Confirmación",
		"deleteElement": "¿Está seguro de que desea eliminar el elemento actual y sus subelementos?",
		"deleteRowTitle": "Confirmación",
		"deleteRow": "La eliminación de la fila actual eliminará el contenido de todas las celdas en esa fila. ¿Está seguro de que desea eliminar la fila seleccionada?",
		"deleteColTitle": "Confirmación",
		"deleteCol": "La eliminación de la columna actual eliminará el contenido de todas las celdas en esa columna. ¿Está seguro de que desea eliminar la columna seleccionada?",
		"deleteEventTitle": "Confirmación",
		"deleteEvent": "¿Está seguro de que desea eliminar el evento actual?",
		"deleteActionTitle": "Confirmación",
		"deleteAction": "¿Está seguro de que desea eliminar la acción actual?",
		"deleteButtonTitle": "Confirmación",
		"deleteButton": "¿Está seguro de que desea eliminar el botón de acción actual?",
		"notUseModuleInMobile": "Este componente no es compatible con dispositivos móviles",
		"changeToSequenceTitle": "Confirmación",
		"changeToSequence": "Esta acción eliminará los componentes agregados. ¿Está seguro de que desea cambiar a la columna 'N° de Orden'?"
	},
	"formAction": {
		"insertRow": "Insertar fila",
		"insertCol": "Insertar columna",
		"deleteRow": "Eliminar fila",
		"deleteCol": "Eliminar columna",
		"mergerCell": "Combinar celdas",
		"splitCell": "Dividir celda",
		"move": "Mover",
		"copy": "Copiar",
		"delete": "Eliminar",
		"add": "Agregar",
		"cut": "Cortar",
		"paste": "Pegar",
		"open": "Abrir",
		"script": "Script",
		"create": "Crear",
		"mergeCell": "Combinar celdas",
		"styleBrush": "Pincel de estilo",
		"insertTop": "Insertar en la parte superior",
		"insertBottom": "Insertar en la parte inferior",
		"insertBefore": "Insertar antes",
		"insertAfter": "Insertar después",
		"injectNotice": "Mantenga presionado Ctrl y suelte el mouse para posicionamiento preciso",
		"selectedContainer": "Seleccionar objeto padre",
		"property": "Propiedad",
		"batchModify": "Modificación masiva",
		"selectParent": "Seleccionar componentes superiores"
	},
	"actionbar": {
		"readhide": "Establecer si se muestra al leer",
		"edithide": "Establecer si se muestra al editar",
		"hideCondition": "Establecer condición de ocultación",
		"title": "Título",
		"img": "Icono",
		"action": "Acción",
		"condition": "Condición de visualización",
		"editScript": "Editar script de acción",
		"editCondition": "(retornar verdadero para ocultar acción)",
		"up": "Mover hacia arriba",
		"property": "Propiedad",
		"addCustomTool": "Agregar acción personalizada",
		"delete": "Eliminar",
		"setProperties": "Establecer propiedades de la acción",
		"restoreDefaultTool": "Restaurar una acción del sistema eliminada",
		"selectDefaultTool": "Seleccionar acción del sistema",
		"setReaded": "Marcar como leído",
		"readed": "Leído"
	},
	"isSave": "Guardando, por favor espere...",
	"scriptIncluder": {
		"yes": "Sí",
		"no": "No",
		"selectScript": "Seleccionar script:",
		"repeatAddScriptNotice": "No agregue el mismo script varias veces",
		"selectScriptNotice": "Seleccione un script primero",
		"asyncLoad": "Carga asíncrona:",
		"asyncLoadScript": "Cargar script de forma asíncrona:",
		"syncLoadScript": "Cargar script de forma síncrona:",
		"delete_title": "Confirmación",
		"delete_text": "¿Está seguro de que desea cancelar la carga del script seleccionado?"
	},
	"dictionaryIncluder": {
		"selectDictionary": "Seleccionar:",
		"repeatAddDictionaryNotice": "No agregue el mismo diccionario de datos varias veces",
		"rootDictionaryExistNotice": "Ya se ha agregado la raíz de este diccionario de datos, no es necesario agregarla nuevamente",
		"parentDictionaryExistNotice": "Ya se ha agregado el padre de este diccionario de datos, no es necesario agregarlo nuevamente",
		"subDictionaryExistNotice": "Ya existe una subruta para este diccionario de datos. Elimine primero y luego agregue de nuevo",
		"selectDictionaryNotice": "Seleccione un diccionario de datos primero",
		"path": "Ruta:",
		"delete_title": "Confirmación de cancelación de carga de diccionario de datos",
		"delete_text": "¿Está seguro de que desea cancelar la carga del diccionario de datos seleccionado?"
	},
	"validation": {
		"validation": "Validación",
		"anytime": "siempre",
		"decision": "Decisión",
		"decisionName": "<Nombre de decisión>",
		"value": "Valor",
		"length": "Longitud de valor",
		"valueInput": "<Valor>",
		"isnull": "Es nulo",
		"notnull": "No es nulo",
		"gt": "Mayor que",
		"lt": "Menor que",
		"equal": "Igual a",
		"neq": "No igual a",
		"contain": "Contiene",
		"notcontain": "No contiene",
		"prompt": "Indicación",
		"add": "añadir",
		"modify": "edit",
		"when": "Cuando",
		"as": "como",
		"inputDecisionName": "Ingrese el nombre de la decisión",
		"inputValue": "Ingrese el valor",
		"inputPrompt": "Ingrese el contenido de la indicación",
		"delete_title": "Confirmación",
		"delete_text": "¿Está seguro de que desea eliminar esta validación?"
	},
	"datagrid": {
		"import": "incluir",
		"export": "extraer"
	},
	"selectIcon": "Seleccionar icono",
	"selectImage": "Seleccionar imagen",
	"selectApplication": "Seleccionar aplicación",
	"dutyInputTitle": "Agregar parámetros de puesto",
	"dutyInput": "Por favor, seleccione una organización para el puesto \"{duty}\"",
	"select": "Seleccionar",
	"empty": "Vaciar",
	"creatorUnit": "Organización del autor",
	"currentUnit": "Organización actual",
	"selectUnit": "Seleccionar organización",
	"scriptUnit": "Usar script",
	"creatorCompany": "Empresa del autor",
	"creatorDepartment": "Departamento del autor",
	"currentCompany": "Empresa actual",
	"currentDepartment": "Departamento actual",
	"deleteDutyTitle": "Confirmación",
	"deleteDutyText": "¿Estás seguro de que deseas eliminar el puesto \"{duty}\"?",
	"saveTemplate": "Guardar como plantilla de formulario",
	"templateName": "Nombre de la plantilla",
	"templateCategory": "Categoría de la plantilla",
	"templateDescription": "Descripción de la plantilla",
	"save": "Guardar",
	"cancel": "Cancelar",
	"newCategory": "Nueva categoría",
	"mustSelectFormStyle": "Debe seleccionar un estilo de formulario",
	"notValidJson": "Formato JSON no válido",
	"mustSelectDict": "Primero seleccione el diccionario de datos",
	"mustSelect": "Por favor seleccione",
	"imageClipper": "Editor de imágenes",
	"clearNoDomModuleTitle": "Eliminar configuraciones de componentes fuera de la estructura HTML",
	"clearNoDomModuleContent": "¿Quieres eliminar las configuraciones de los componentes que no están en la estructura HTML? Después de borrar, debe guardar para que los cambios tengan efecto.",
	"refreshDatatemplateImpExpTitle": "Confirmación de importación de campos",
	"refreshDatatemplateImpExpContent": "Esta operación obtiene campos del componente interno de la plantilla de datos. Si realiza esta operación, los campos configurados anteriormente se reemplazarán, ¿desea continuar?",
	"handWriting": "Escritura manual",
	"filter": {
		"and": "Y",
		"or": "O",
		"equals": "Igual a",
		"notEquals": "No igual a",
		"greaterThan": "Mayor que",
		"greaterThanOrEqualTo": "Mayor o igual que",
		"lessThan": "Menor que",
		"lessThanOrEqualTo": "Menor o igual que",
		"like": "Coincide con",
		"notLike": "No coincide con",
		"from": "Desde",
		"value": "Valor"
	},
	"mastInputPath": "Ingrese la ruta de datos",
	"mastInputTitle": "Ingrese el título",
	"delete_filterItem_title": "Confirmación",
	"delete_filterItem": "¿Está seguro de que desea eliminar la condición de filtro actual?",
	"subformNameConflictTitle": "Conflicto en los nombres de campo del subformulario",
	"subformNameConflictInfor": "Los siguientes nombres de campo del subformulario entran en conflicto con los campos existentes del formulario actual: \n{name}",
	"subformConflictTitle": "Error al incrustar el subformulario",
	"subformConflictInfor": "No puede incrustar el mismo subformulario varias veces",
	"subformNestedTitle": "Error al incrustar el subformulario",
	"subformNestedInfor": "No se pueden incrustar subformularios que se anidan mutuamente",
	"checkSubformNestedError": "El subformulario que ha seleccionado tiene anidaciones mutuas, ¡por favor revise!",
	"checkSubformTitle": "Verificación de guardado de formulario",
	"checkFormSaveError": "No se pudo guardar el formulario, las razones son:<br>",
	"checkSubformPcInfor": "En el formulario para PC, hay conflictos en los siguientes campos del subformulario: <br>{subform}<br>",
	"checkSubformMobileInfor": "En el formulario para móvil, hay conflictos en los siguientes campos del subformulario: <br>{subform}",
	"implodeError": "Error en el formato de los datos que se van a importar.",
	"implodeEmpty": "Por favor ingrese los datos que desea importar en el cuadro de edición.",
	"implodeConfirmTitle": "Confirmación de importación",
	"implodeConfirmText": "La importación de datos borrará la página actual y no se puede deshacer, ¿está seguro de que desea importar?",
	"design": "Diseño",
	"script": "Script",
	"html": "HTML",
	"css": "CSS",
	"byModule": "Por diseño",
	"byPath": "Por script",
	"events": "Eventos",
	"pageform": "Página",
	"importO2": "Importar desde datos O2",
	"importHTML": "Importar desde HTML",
	"importOffice": "Importar desde WORD o EXCEL",
	"importO2_infor": "Copie los datos del formulario en formato O2 en el editor siguiente. (Use el botón 'Exportar' de la barra de herramientas del diseñador de formularios o páginas para obtener los datos del formulario) <br/>Presione Ctrl+Alt+I para dar formato a los datos.",
	"importHTML_infor": "Copie los datos HTML en el editor siguiente. Presione Ctrl+Alt+I para dar formato a los datos.",
	"importHTML_infor2": "Copie los datos CSS en el editor siguiente. Presione Ctrl+Alt+I para dar formato a los datos.",
	"importOffice_infor": "Seleccione un archivo de Word o Excel.",
	"import_ok": "Importar",
	"import_cancel": "Cancelar",
	"import_option1": "Agregar cuadros de texto en celdas vacías de la tabla",
	"import_option2": "Eliminar elementos vacíos",
	"implodeOfficeEmpty": "Seleccione primero el archivo de Word o Excel que desea importar.",
	"scriptTitle": {
		"validationOpinion": "Validación de opiniones del formulario",
		"validationRoute": "Validación de rutas del formulario",
		"validationFormCustom": "Validación de formularios",
		"defaultValue": "Valor predeterminado",
		"validation": "Script de validación",
		"sectionByScript": "Sección según script",
		"itemScript": "Script de valores opcionales",
		"iframeScript": "Script de iframe",
		"labelScript": "Valor de texto",
		"rangeKey": "Alcance organizativo",
		"identityRangeKey": "Alcance organizativo de identidad",
		"unitRangeKey": "Alcance seleccionable de la organización",
		"rangeDutyKey": "Alcance de deberes",
		"exclude": "Script de exclusión de selección",
		"cookies": "Cookies de solicitud de fuente de datos",
		"requestBody": "Cuerpo de mensaje de solicitud de fuente de datos",
		"jsonText": "Texto de datos",
		"dataScript": "Script de control de árbol",
		"itemDynamic": "Script de opciones dinámicas",
		"defaultData": "Valor predeterminado de la cuadrícula de datos",
		"editableScript": "¿Es editable la cuadrícula de datos?",
		"config": "Configuración de HTML Editor",
		"filterScript": "Filtro de registro de proceso",
		"readScript": "Script de solo lectura de Office",
		"fileSite": "Script de sitio de archivo de Office",
		"subformScript": "Script de subformulario",
		"selectedScript": "Script de selección de vista",
		"action.tools": "Botones de acción"
	},
	"copyed": "Copiado",
	"selectorButton": {
		"ok": "Aceptar",
		"cancel": "Cancelar"
	},
	"modules": {
		"label": "Texto",
		"textfield": "Campo de texto",
		"number": "Numérico",
		"currency": "moneda",
		"org": "Organización",
		"calendar": "Fecha y hora",
		"textarea": "Texto multilínea",
		"select": "Desplegable",
		"radio": "Botón de opción",
		"checkbox": "CheckBox",
		"combox": "ComboBox",
		"opinion": "OpinionBox",
		"button": "Botón",
		"Address": "Dirección",
		"Actionbar": "Barra de acción",
		"Sidebar": "Sidebar",
		"image": "Imagen",
		"imageclipper": "SelectImg",
		"attachment": "Adjunto",
		"div": "Contenedor",
		"table": "Tabla",
		"datagrid": "Grid(obsoleto)",
		"datatable": "Tablas de datos",
		"datatemplate": "DataTemplate",
		"subform": "Subformulario",
		"ViewSelector": "Seleccionar vista",
		"view": "Vista incrustada",
		"stat": "Estadística",
		"html": "HTML",
		"common": "Comunes",
		"tab": "Pestaña",
		"tree": "Árbol",
		"log": "Registro",
		"monitor": "Monitoreo",
		"iframe": "Iframe",
		"documenteditor": "DocEditor",
		"htmledit": "Editor de HTML",
		"office": "Office",
		"yozoOffice": "Control de Yozo",
		"statementSelector": "StatementSelector",
		"statement": "Statement",
		"SmartBI": "Informe SmartBI",
		"group_all": "Todos",
		"group_form": "Formulario",
		"group_layout": "Diseño",
		"group_process": "Proceso",
		"group_filetext": "FileEdit",
		"group_function": "Función",
		"group_element": "Element",
		"el_container": "Diseño",
		"el_icon": "Icono",
		"el_button": "Botón",
		"el_radio": "Botón de opción",
		"el_checkbox": "CheckBox",
		"el_select": "Selector",
		"el_input": "Campo de texto",
		"el_autocomplete": "Autocomplete",
		"el_cascader": "Cascader",
		"el_number": "Contador",
		"el_switch": "Interruptor",
		"el_slider": "Deslizador",
		"el_time": "Hora",
		"el_date": "Fecha",
		"el_datetime": "Fecha y hora",
		"el_rate": "Calificación",
		"el_colorpicker": "ColorPicker",
		"el_tree": "Árbol",
		"el_dropdown": "Select",
		"el_carousel": "Carrusel",
		"el-menu": "Menu",
		"el_common": "Común",
		"importer": "Importar",
		"readLog": "L.R.",
		"writingBoard": "P.E.",
		"tinymceEditor": "Tinymce",
		"relatedLink": "recomendación",
		"associatedDocument": "Un documento asociado",
		"security": "Etiqueta de seguridad",
		"securityInfo": "Solo se permite un campo de \"identificación de nivel secreto\""
	},
	"propertyTemplate": {
		"base": "Base",
		"event": "Evento",
		"html": "HTML",
		"json": "JSON",
		"action": "Acción",
		"select": "sel.",
		"id": "Identificación",
		"name": "Nombre",
		"description": "Descripción",
		"appearance": "Apariencia",
		"style": "Estilo",
		"attribute": "Atributo",
		"imageStyle": "Estilo de Imagen",
		"hideSystemTools": "Sistema",
		"show": "Mostrar",
		"hide": "Ocultar",
		"readed": "Leído",
		"category": "clasif",
		"formStyle": "Estilo de formulario",
		"icon": "Icono",
		"printForm": "Imprimir formulario",
		"preloadScript": "Pre-cargar script",
		"script": "Script",
		"dict": "Diccionario de datos",
		"dictName": "nombre del diccionario",
		"dictPath": "Ruta de datos",
		"valueKey": "Nombre del atributo de valor",
		"textKey": "Nombre de propiedad de texto",
		"valueColumn": "Columna de valor",
		"textColumn": "Columna de texto",
		"dictKeyNote": "Si devuelve una matriz de objetos, debe configurar el nombre del atributo de valor o el nombre del atributo de texto",
		"firstOptionEnable": "Usar Preferencias",
		"firstOption": "Preferencias",
		"copy": "Copiar",
		"paste": "Pegar",
		"language": "Pack de idioma",
		"languageScript": "Script del Pack de Idioma (S)",
		"languageInfo": "Devuelve un objeto JSON que contiene información sobre el idioma; o2.language obtiene información sobre el idioma actual",
		"SubmitUI": "Interfaz de envío",
		"submit": "Enviar",
		"systemDefault": "Por defecto del sistema",
		"selectForm": "Seleccionar formulario",
		"computeForm": "Calcular formulario",
		"application": "Aplicación",
		"form": "Formulario",
		"crossApplication": "Aplicación cruzada",
		"computeSubmitAnnotation1": "Nombre de la aplicación, alias, id",
		"computeSubmitAnnotation2": "Nombre del formulario, id",
		"computeWidgetAnnotation2": "Nombre del widget, id",
		"thisApplication": "Esta aplicación",
		"submitFormScript": "Script para enviar el formulario",
		"flowActionScript": "Script de acción de flujo",
		"handwritingSetting": "Configuración de escritura a mano",
		"enableHandwriting": "Activar escritura a mano",
		"handwritingWidth": "Ancho del panel de escritura a mano",
		"effectivePC": "Válido en PC",
		"handwritingHeight": "Alto del panel de escritura a mano",
		"promptBoxFlow": "Cuadro de diálogo",
		"yes": "Sí",
		"no": "No",
		"usedNewWindow": "Solo utilizar al abrir una nueva ventana del navegador",
		"promptLocation": "ubicación",
		"lefttop": "Arriba a la izquierda",
		"righttop": "Arriba a la derecha",
		"leftbottom": "Abajo a la izquierda",
		"rightbottom": "Abajo a la derecha",
		"center": "Centro",
		"prompt": "Cuadro de diálogo",
		"notClose": "No cerrar",
		"closeInfo": "Cerrar automáticamente en segundos",
		"afterFlow": "Después del flujo",
		"closeWindow": "Cerrar ventana",
		"redirect": "Redireccionar",
		"redirectScript": "Script de dirección de redirección",
		"returnUrl": "Devolver una URL para redirigir",
		"check": "Verificar",
		"checkOpinion": "Verificar opinión",
		"checkRoute": "Verificar ruta",
		"checkFlow": "Verificar flujo",
		"noEventInfo": "Nota: Cuando se incrusta un formulario secundario, los siguientes eventos no se ejecutarán",
		"none": "Ninguno",
		"default": "Predeterminado",
		"byScript": "Por script",
		"scriptLib": "Script",
		"byFormat": "Por formato",
		"table": "Tabla",
		"languageDefaultInfoScript": "El sistema cargará automáticamente un script llamado (\"lp-\"+o2.language) como paquete de idioma.",
		"languageDefaultInfoDict": "El sistema automáticamente cargará un diccionario de datos (o un script) con el nombre \"lp-\"+o2.language como paquete de idioma.",
		"prefix": "Prefijo",
		"suffix": "Sufijo",
		"value": "Valor",
		"textValue": "Valor fijo",
		"showIcon": "Mostrar icono",
		"readonly": "¿Es de solo lectura?",
		"AIInput": "Entrada inteligente",
		"inputStyle": "Estilo de entrada",
		"itemStyle": "Estilo de elemento",
		"actionStyles": "Estilos de botón",
		"imageStyles": "Estilos de imagen",
		"compute": "Calcular",
		"create": "Crear",
		"save": "Guardar",
		"linkStyles": "Estilos de enlace",
		"defaultValue": "Valor predeterminado",
		"verificationScript": "Script de verificación",
		"verificationLineScript": "Script de validación después de la edición",
		"section": "Sección",
		"enableSection": "Habilitar sección",
		"sectionBy": "Sección por",
		"handler": "Responsable",
		"handlerUnit": "Unidad del responsable",
		"activityId": "ID de actividad",
		"splitValue": "Valor separado",
		"enableSectionMerge": "Combinar Secciones",
		"showSectionKey": "Mostrar clave de sección",
		"editByMerge": "Editar combinando (eliminar la clave de sección)",
		"sectionMergeSortScript": "Script de ordenamiento",
		"sectionNodeStyles": "Estilos de nodo de sección",
		"sectionKeystyles": "Estilos de clave de sección",
		"sectionContentStyles": "Estilos del contenido de sección",
		"mergeDisplay": "Solo lectura",
		"editCurrentSection": "Editar (permitir edición de la sección actual)",
		"mergeEdit": "Editar (combinar datos después de eliminar la clave de sección)",
		"sectionKey": "Clave de sección",
		"sectionKeyScript": "Script de clave de sección",
		"textValue1": "Valor de texto",
		"mergeType": "Tipo de combinación",
		"amountValue": "Valor total",
		"averageValue": "Valor promedio",
		"sectionMergeEditScript": "Script para combinar datos",
		"sectionMergeReadHtmlScript": "Script HTML visible",
		"sectionMergeReadDataScript": "Script de datos",
		"htmlScript": "Script HTML",
		"dataScript": "Script de datos",
		"bySection": "Por sección",
		"byModule": "Por módulo",
		"totalRow": "Fila total",
		"sectionAmountCellStyle": "Estilo de celda de valor total de sección",
		"showAllSection": "Mostrar todas las secciones",
		"rangeByDatetime": "Rango de fecha y hora",
		"rangeByDateAndTime": "Rango de fecha y rango de tiempo",
		"rangeByDate": "Rango de fecha",
		"rangeByTime": "Rango de tiempo",
		"rangeByOhter": "Otros",
		"enableDate": "Fecha válida",
		"enableHours": "Rango de horas válido",
		"enableMinutes": "Rango de minutos válido",
		"enableSeconds": "Rango de segundos válido",
		"decimal": "Punto decimal",
		"showCard": "Mostrar tarjeta",
		"allowInput": "Permitir entrada",
		"dataStructure": "Estructura de datos guardados",
		"complete": "Completo",
		"simple": "Sencillo",
		"separator": "Separador",
		"asyncMode": "Modo asíncrono",
		"identity": "Identidad",
		"unit": "Organización",
		"duty": "Posición",
		"group": "Grupo",
		"person": "Persona",
		"defaultValueScript": "Script de valor predeterminado",
		"showText": "Mostrar texto",
		"showTextScript": "Script para mostrar texto",
		"unitSelectConfig": "Configuración",
		"selectType": "Tipo de selección",
		"selectCount": "Cantidad de selección",
		"returnValue": "Valor de retorno",
		"readonlyScript": "Script de solo lectura",
		"selectTypeInfo": "¡Seleccione la identidad para participar en el procesamiento del flujo de trabajo!",
		"selectTypeInfo2": "Tenga en cuenta que los individuos no pueden participar en el procesamiento del flujo de trabajo.",
		"checkEmpower": "Verificar autorización pendiente",
		"onlyCustom": "Solo usar opciones personalizadas",
		"unitRange": "Rango de organización",
		"allUnit": "Todas las organizaciones",
		"specifyUnit": "Especificar organización",
		"draftUnit": "Organización del redactor",
		"currentUnit": "Organización actual de la persona",
		"inUnit": "Organización de pertenencia directa",
		"levelIs": "El nivel es",
		"levelUnit": "nivel de organización",
		"unitTypeIs": "Tipo de organización",
		"deUnit": "organización",
		"expandNext": "Expandir subordinados",
		"selectUnit": "Seleccionar organización",
		"formData": "Datos del formulario",
		"dutyRange": "Alcance del deber",
		"all": "Todos",
		"all2": "Todo",
		"specifyDuty": "Especificar deber",
		"byUnit": "Por organización",
		"byDuty": "Por deber",
		"showLevel": "Mostrar nivel",
		"byDutyUnit": "Por organización de deber",
		"byIdentityUnit": "Por organización de identidad",
		"selectDuty": "Seleccionar deber",
		"customOption": "Opción personalizada",
		"useScriptAddIdOrPerson": "Usar script para agregar identidad/personal",
		"unitType": "Tipo de organización",
		"selectRange": "Rango de selección",
		"specifyGroup": "Especificar grupo",
		"exclude": "Excluir",
		"excludeInfo": "Rango excluido escrito por script.",
		"firstLevelSelectable": "Permitir seleccionar el primer nivel",
		"dateTime": "Fecha y hora",
		"dateTime2": "Fecha y hora",
		"dateOnly": "Solo fecha",
		"monthOnly": "Solo mes",
		"yearOnly": "Solo año",
		"timeOnly": "Solo hora",
		"weekOnly": "Número de semana",
		"multidate": "Múltiples fechas",
		"datetimerange": "Rango de fecha y hora",
		"daterange": "Rango de fecha",
		"timerange": "Rango de hora",
		"monthrange": "Rango de meses",
		"selectSecond": "Seleccionar segundos",
		"timeSelectType": "Tipo de selección",
		"timeSelectType_slider": "Deslizador",
		"timeSelectType_select": "Menú desplegable",
		"format": "Formato",
		"rateTexts": "Pobre, Desencantado, Normal, Satisfecho, Sorprendido",
		"allowHalf": "Permitir selección media",
		"lowThreshold": "Valor de límite bajo-medio",
		"lowThresholdNote": "Nota: el valor en sí se divide en la clasificación baja.",
		"highThreshold": "Valor de límite medio-alto",
		"highThresholdNote": "Nota: el valor en sí se divide en la clasificación alta",
		"lowColor": "Color del valor bajo",
		"mediumColor": "Color del valor medio",
		"highColor": "Color del valor alto",
		"voidColor": "Color no seleccionado",
		"disabledVoidColor": "Color no seleccionado en modo solo lectura",
		"showAfter": "Mostrar después",
		"showScore": "Mostrar puntuación",
		"textColor": "Color del texto",
		"textContent": "Contenido del texto",
		"showAlpha": "Mostrar transparencia",
		"colorFormat": "Formato de color",
		"nodeKey": "Clave única del nodo",
		"nodeKeyNote": "Atributo utilizado como clave única para cada nodo del árbol. Todo el árbol debe ser único.",
		"renderAfterExpand": "Renderizar los nodos hijos después de expandir el nodo",
		"defaultExpandAll": "Expandir todos los nodos por defecto",
		"highlightCurrent": "Resaltar el nodo actual seleccionado",
		"currentNodeKey": "Clave del nodo actualmente seleccionado",
		"expandOnClickNode": "Expandir al hacer clic en un nodo",
		"clickNode": "Cuando se hace clic en un nodo",
		"clickArrow": "Cuando se hace clic en la flecha",
		"checkOnClickNode": "Seleccionar al hacer clic en un nodo",
		"clickCheckbox": "Cuando se hace clic en la casilla de verificación",
		"defaultExpandedkeys": "Nodos expandidos por defecto",
		"defaultExpandedkeysNote": "Array que contiene las claves de los nodos a expandir por defecto, por ejemplo: ['2', '4'].",
		"showCheckbox": "Permitir selección con casillas de verificación",
		"defaultCheckedKeysNote": "Array que contiene las claves de los nodos marcados por defecto, por ejemplo: ['2', '4'].",
		"defaultCheckedkeys": "Nodos seleccionados por defecto",
		"accordion": "Expandir solo un nodo hermano a la vez",
		"indent": "Sangría por nivel",
		"dragdrop": "Arrastrar y soltar",
		"draggable": "Permitir arrastrar",
		"allowDrag": "Determinar si el nodo se puede arrastrar",
		"allowDrop": "Determinar si se puede soltar un nodo mientras se arrastra",
		"emptyText": "Texto mostrado cuando no hay contenido",
		"allowDragNote": "this.event es el nodo que se pasa como argumento. 'return true' indica que se permite arrastrar el nodo.",
		"allowDropNote": "this.event proporciona los datos { draggingNode, dropNode, type }. El parámetro type tiene tres valores posibles: 'prev', 'inner' o 'next', que indican si el nodo se va a soltar antes, dentro o después del nodo objetivo, respectivamente. 'return true' indica que se permite soltar el nodo.",
		"loadFun": "Script para cargar los datos de los nodos hijos",
		"loadFunNote": "this.event.node es el nodo que se ha hecho clic. this.event.resolve(data) es una devolución de llamada que se activará una vez que se finalice la carga de los datos de los nodos hijos. El argumento data contiene los datos de los nodos hijos.",
		"dataScriptNote": "Formato de retorno para cada nodo:",
		"labelDescription": "Etiqueta del nodo",
		"childrenDescription": "Nodos hijos",
		"disabledDescription": "Disponible solo si se habilita la selección. Indica si la casilla de verificación está deshabilitada.",
		"isLeafDescription": "Disponible solo con la carga dinámica habilitada. Indica si el nodo es una hoja (por defecto no se muestra la flecha).",
		"idDescription": "Opcional. Se utiliza para definir el nodo que se va a expandir por defecto, seleccionar por defecto o marcar por defecto. Se puede utilizar el ID o la clave establecida en las propiedades básicas.",
		"settedKey": "Clave establecida",
		"customDescription": "Otros datos personalizados",
		"selectStyle": "Estilo del selector",
		"options": "Valores opcionales",
		"optionScript": "Script de los valores opcionales",
		"divStyle": "Estilo del contenedor",
		"buttonStyle": "Estilo del botón",
		"extendOptions": "Valores opcionales adicionales",
		"dynamic": "Cálculo dinámico",
		"canSelectCount": "Cantidad seleccionable",
		"showSeparator": "Mostrar separador",
		"optionDynamicScript": "Script de los valores opcionales dinámicos",
		"handwriting": "Escritura a mano",
		"writingBoard": "Tablero de escritura a mano",
		"width": "Ancho",
		"height": "Altura",
		"recording": "Grabación de audio",
		"writingPreview": "Vista previa de la escritura a mano",
		"commonIdea": "Opiniones frecuentes",
		"addressStyle": "Estilo de dirección",
		"location": "Ubicación",
		"right": "Derecha",
		"left": "Izquierda",
		"relocate": "Reubicar",
		"image": "Imagen",
		"selectSrc": "Seleccionar recurso",
		"imageCropping": "Recorte de imagen",
		"unlimited": "Sin límite",
		"fixedSize": "Tamaño fijo",
		"fixedRatio": "Proporción fija",
		"aspectRatio": "Relación de aspecto",
		"site": "site",
		"defaultSiteInfo": "(Por defecto, es el mismo que la identificación)",
		"editInActivex": "Editar en el control ActiveX",
		"activexId": "Identificación del control",
		"showType": "Tipo de visualización",
		"switchStyle": "Cambiar estilo",
		"allow": "Permitir",
		"notAllow": "No permitir",
		"uploadType": "Tipos de archivo permitidos para subir",
		"wordDoc": "Documentos de Word",
		"excelDoc": "Documentos de Excel",
		"pptDoc": "Documentos de PowerPoint",
		"textDoc": "Documentos de texto",
		"imgDoc": "Archivos de imagen",
		"pdfDoc": "Documentos PDF",
		"zipDoc": "Archivos comprimidos",
		"audioDoc": "Archivos de audio",
		"videoDoc": "Archivos de video",
		"otherDoc": "Otros",
		"docSample": "Ejemplo de formato: .doc, .docx, .xls",
		"uploadSize": "Tamaño máximo para subir (MB)",
		"uploadSizeInfo": "Un valor de '0' indica que no hay límite de tamaño de archivo",
		"uploadCount": "Cantidad máxima de archivos a subir",
		"uploadCountInfo": "Un valor de '0' indica que no hay límite en la cantidad de archivos a subir",
		"changeSize": "Cambiar tamaño",
		"useAttachmentStyle": "Estilos de adjuntos permitidos",
		"list": "Lista",
		"sequence": "Secuencia",
		"preview": "Vista previa",
		"attDefaultStyle": "Estilo de adjuntos por defecto",
		"readonlyMode": "Modo de solo lectura",
		"allowUpload": "Permitir cargar",
		"allowPreview": "Permitir previsualización",
		"allowDownload": "Permitir descarga",
		"allowDownloadBatch": "Permitir descargas por lotes",
		"allowEdit": "Permitir edición",
		"officeTool": "Herramienta de vista previa / edición de Office",
		"allowDelete": "Permitir eliminación",
		"allowDelMyAtt": "Permitir eliminación solo de los archivos que el usuario ha cargado",
		"allowDelCurActivityAtt": "Permitir eliminación solo de los archivos cargados en esta actividad",
		"allowDelMyCurActivityAtt": "Permitir eliminación solo de los archivos que el usuario ha cargado en esta actividad",
		"allowReplace": "Permitir reemplazo",
		"allowConfig": "Permitir configurar permisos",
		"allowOrder": "Permitir ordenar",
		"dblClickAttachment": "Doble clic en el adjunto",
		"openAtt": "Abrir",
		"previewFirst": "Previsualizar primero",
		"previewAttachmentNote": "Los siguientes formatos de archivo se pueden previsualizar directamente: zip, pdf, ofd, png, jpg, bmp, jpeg, gif, js, css, java, json, xml, php, html, htm, xhtml, log, md, txt. Los formatos de archivo doc, docx, xls, xlsx, ppt, pptx requieren la instalación de LibreOffice. Al hacer doble clic en los formatos que no se encuentran en la lista anterior, se abre directamente el adjunto.",
		"actionBar": "Barra de acción",
		"hideEditButton": "Ocultar grupo de edición",
		"hideReadButton": "Ocultar grupo de lectura",
		"hideLayoutButton": "Ocultar grupo de diseño",
		"hideSettingButton": "Ocultar grupo de configuración",
		"hideModeButton": "Ocultar modo de operación",
		"showInDatagrid": "Mostrar en la cuadrícula de datos (obsoleto)",
		"attachmentValidation": "Validación durante la carga",
		"attachmentValidationNote": "Puede utilizar 'this.target.uploadingFiles' para obtener los adjuntos cargándose actualmente. Devuelva 'true' para aprobar la validación y un texto para interrumpir la carga con una notificación del sistema.",
		"attachmentValidationScript": "Script de validación durante la carga",
		"hideEraserButton": "Ocultar botón de borrador",
		"hideEraserRadioButton": "Ocultar botón de tamaño de borrador",
		"hideSizeButton": "Ocultar botón de grosor",
		"hideColorButton": "Ocultar botón de color",
		"hideImageButton": "Ocultar botón de insertar imagen",
		"hideImageClipperButton": "Ocultar botón de recortar imagen",
		"tableSize": "Tamaño de la tabla",
		"row": "Fila",
		"col": "Columna",
		"tableWidth": "Ancho de la tabla",
		"pixel": "Píxeles",
		"percent": "Porcentaje",
		"borderWidth": "Ancho del borde",
		"cellpadding": "Margen de celda",
		"cellspacing": "Espacio entre celdas",
		"containStyle": "Estilo del contenedor",
		"containAttribute": "Atributo del contenedor",
		"titleCellStyle": "Estilo de la celda de título",
		"contentCellStyle": "Estilo de la celda de contenido",
		"layoutCellStyle": "Estilo de la celda de diseño",
		"contentTitleCellStyle": "Estilo de la celda de título de contenido",
		"contentLineStyle": "Estilo de fila de contenido",
		"contentLineOverStyle": "Estilo de paso de fila de contenido",
		"columns": "cantidad",
		"onTheLeft": "A la izquierda de la selección",
		"onTheRight": "A la derecha de la selección",
		"rows": "cantidad",
		"onTheTop": "Encima de la selección",
		"onTheBottom": "Debajo de la selección",
		"type": "Tipo",
		"titleCell": "Celda de título",
		"contentCell": "Celda de contenido",
		"layoutCell": "Celda de diseño",
		"other": "Otro",
		"permission": "Permiso",
		"containerStyles": "Estilos del contenedor",
		"tableAttribute": "Atributos de la tabla",
		"border": "Borde",
		"backgroundColor": "Color de fondo",
		"alternateRow": "Fila alternativa",
		"tableStyle": "Estilo de la tabla",
		"defaultData": "Datos predeterminados",
		"allowAdd": "Permitir añadir",
		"allowSort": "Permitir ordenar",
		"exportImport": "Exportar/importar",
		"enabled": "Habilitado",
		"disabled": "Deshabilitado",
		"onlyExport": "Solo exportar",
		"onlyImport": "Solo importar",
		"exportInfo": "Nota: no se pueden exportar/importar números de serie, imágenes, tableros de escritura a mano, archivos adjuntos ni columnas ocultas.",
		"buttonLocation": "Ubicación del botón",
		"centertop": "Centro superior",
		"centerbottom": "Centro inferior",
		"importText": "Texto del botón de importar",
		"importExcel": "Importar Excel",
		"exportExcel": "Exportar Excel",
		"importButtonStyle": "Estilo del botón de importar",
		"exportFileName": "Nombre del archivo exportado",
		"actionCellStyles": "Estilo de la celda de acción",
		"editCellStyles": "Estilo de la celda de edición",
		"amountCellStyle": "Estilo de la celda de total",
		"itemTitleStyle": "Estilo del título de elementos (solo para dispositivos móviles)",
		"canEdit": "¿Se puede editar?",
		"exportText": "Texto del botón de exportar",
		"exporButtonStyle": "Estilo del botón de exportar",
		"content": "Contenido",
		"serialNumber": "Número de serie",
		"total": "Total",
		"notNeeded": "No necesario",
		"totalValue": "Valor total",
		"totalCount": "Cantidad total",
		"showCol": "Mostrar esta columna",
		"hideCol": "Ocultar esta columna",
		"delayedLoading": "Carga con retraso",
		"selectSubform": "Seleccionar subformulario",
		"calculationSubform": "Calcular subformulario",
		"subform": "Subformulario",
		"subformScript": "Script de subformulario",
		"activeType": "Tipo de activación",
		"click": "Activar al hacer clic",
		"delay": "Activar con retraso",
		"immediately": "Activar inmediatamente",
		"buttonText": "Texto del botón",
		"delayNote": "Si se selecciona la activación con retraso, use this.form.get(moduleId).active() para activar el formulario.",
		"viewBox": "Cuadro de selección de vista",
		"viewBoxTitle": "Título del cuadro de selección",
		"columnTitle": "Título de columna",
		"expandDefault": "Expandir por defecto",
		"expand": "Expandir",
		"collapse": "Colapsar",
		"singleChoice": "Selección única",
		"multipleChoice": "Selección múltiple",
		"view": "Vista",
		"statement": "Consulta",
		"boxTitleStyle": "Estilo del título del cuadro de selección",
		"boxItemStyle": "Estilo del elemento del cuadro de selección",
		"selectResultProcessing": "Procesamiento del resultado de la selección",
		"resultProcessing": "Procesamiento del resultado",
		"assignValue": "Asignar valor",
		"assignValueForResult": "Asignar valor al resultado de la selección",
		"selectResult": "Resultado de la selección",
		"defaultSelectedLineScript": "Script para línea seleccionada por defecto",
		"allowSelectiLineScript": "Script para permitir la selección de línea",
		"reservar": "Reservar",
		"changeViewReserve": "Volver a seleccionar después de cambiar la vista, conservar los datos de la vista original",
		"changeViewNotReserve": "Vuelva a seleccionar después de cambiar la vista, elimine los datos de la vista original",
		"filter": "Filtro",
		"title": "Título",
		"path": "Ruta",
		"servicePath": "Ruta del servicio",
		"servicePathNote": "Ejemplo: /jaxrs/user/hotpic/filter/list/page/1/count/6",
		"dataItemPath": "Ruta del ítem de datos",
		"dataItemPathNote": "Ruta de los datos a mostrar, separados por punto '.' si son varios niveles. Ejemplo: data",
		"dataScriptNote2": "El script debe devolver un objeto Promise o datos. Ejemplo: return this.Actions.load('x_hotpic_assemble_control').HotPictureInfoAction.listForPage(1, 6);",
		"dataType": "Tipo de datos",
		"text": "Texto",
		"number": "Número",
		"currencySymbol": "símbolo de moneda",
		"currencySymbolStyles": "Estilos de símbolos de moneda",
		"datetime": "Fecha",
		"boolean": "Booleano",
		"resultType": "Tipo de resultado",
		"asDefaultFilter": "Usar como filtro predeterminado",
		"asCustomFilter": "Usar como datos personalizados de filtro",
		"logic": "Lógica",
		"and": "Y (and)",
		"or": "O (or)",
		"compare": "Comparación",
		"equals": "Igual que",
		"notEquals": "No igual que",
		"greaterThan": "Mayor que",
		"greaterThanOrEqualTo": "Mayor o igual que",
		"lessThan": "Menor que",
		"lessThanOrEqualTo": "Menor o igual que",
		"like": "Coincide con",
		"notLike": "No coincide con",
		"range": "Rango",
		"in": "Contiene",
		"true": "Verdadero",
		"false": "Falso",
		"filterValueInfo": "Múltiples valores separados por coma (,)",
		"defaultFilter": "Filtro predefinido",
		"customFilter": "Datos de filtro personalizados",
		"filterCond": "Filtro",
		"filterNote": "Nota: devuelva la matriz de condición de filtro de la vista, consulte el formato ",
		"titleStyle": "Estilo del título",
		"dataStyle": "Estilo de los datos",
		"loadNow": "Cargar ahora",
		"showTitle": "Mostrar título",
		"allowSelect": "Permitir selección de archivo",
		"stat": "Estadística",
		"showChart": "Mostrar gráfico",
		"showLegend": "Mostrar leyenda",
		"showTable": "Mostrar tabla",
		"selectTag": "Seleccionar etiqueta",
		"elementTag": "Etiqueta de elemento",
		"innerHtml": "HTML interno",
		"delayedTabInfo": "Cuando se activa la carga con retraso, el contenido de la pestaña no se cargará hasta que se muestre por primera vez.",
		"tabContainerStyle": "Estilo del contenedor de pestañas",
		"contentContainerStyle": "Estilo del contenedor de contenido",
		"baseTabStyle": "Estilo básico de la pestaña",
		"baseTabSpanStyle": "Estilo básico de la fuente de la pestaña",
		"currentTabStyle": "Estilo actual de la pestaña",
		"currentTabSpanStyle": "Estilo actual de la fuente de la pestaña",
		"data": "Datos",
		"treeAreaStyle": "Estilo del área del árbol",
		"treeNodeStyle": "Estilo del nodo del árbol",
		"treeNodeFontStyle": "Estilo de la fuente del nodo del árbol",
		"treeSelectNodeFontStyle": "Estilo actual de la fuente del nodo del árbol",
		"record": "Registro",
		"recordTable": "Tabla de registro",
		"recordMedia": "Multimedia (escritura a mano o voz)",
		"expandHandwritten": "Expandir opinión escrita a mano",
		"handwrittenWidth": "Ancho de opinión escrita a mano",
		"validOnPcSide": "(válido en PC)",
		"handwrittenHeight": "Alto de opinión escrita a mano",
		"logFormat": "Formato de registro",
		"logFormatScript": "Script de formato de registro",
		"currentPerson": "Persona actual",
		"readReaded": "Lectura pendiente o leída",
		"readTitle": "Título de lectura pendiente",
		"readedTitle": "Título de lectura leída",
		"exactMatch": "preciso",
		"filterActivity": "Filtro de actividad",
		"filterActivityAlias": "Filtro de alias de actividad",
		"filterPerson": "Filtro de persona de procesamiento",
		"filterRoute": "Filtro de ruta",
		"filterScript": "Filtrar mediante script",
		"activity": "Actividad",
		"opinionGroup": "Grupo de opiniones",
		"unitLevelName": "Nombre del nivel organizacional",
		"unitLevel": "Nivel organizacional",
		"sortInCategory": "Ordenar por categoría",
		"sortByActivity": "Ordenar por actividad",
		"sortByTimeAsc": "Ordenar por tiempo ascendente",
		"sortByTimeDesc": "Ordenar por tiempo descendente",
		"noSort": "Sin orden",
		"categoryTable": "Tabla de categorías",
		"categoryTableAttr": "Atributos de la tabla de categorías",
		"categoryTableStyle": "Estilo de la tabla de categorías",
		"categoryTitleCellStyle": "Estilo de celda de título de categoría",
		"categoryContentCellStyle": "Estilo de celda de contenido de categoría",
		"categoryContentCellInnerStyle": "Estilo interno de celda de contenido de categoría",
		"expandOrCollapse": "Expandir o colapsar",
		"defaultExpandCount": "Número de elementos expandidos por defecto",
		"expandHtml": "HTML para expandir nodo",
		"collapseHtml": "HTML para colapsar nodo",
		"relativedLinkField": "Campo opcional: flag, title, createTime, updateTime, creatorPerson, creatorUnit, score",
		"documentListShow": "Lista de documentos",
		"associatedDocumentField": "Campo opcional：targetTitle,targetStartTime,targetCreatorPersonCn,targetType,targetCategory",
		"associatedDocumentScriptNote": "\nLos datos del elemento actual se pueden obtener a través de esta línea",
		"fileTemplate": "Plantilla de archivo",
		"systemTemplate": "Plantilla del sistema",
		"customTemplate": "Plantilla personalizada",
		"selectTemplate": "Seleccionar plantilla",
		"templatePath": "Ruta de la plantilla",
		"templateId": "Identificador de la plantilla",
		"edit": "Editar",
		"printFile": "Imprimir contenido",
		"viewTraces": "Ver rastros",
		"viewTracesFullScreen": "Pantalla completa de rastros",
		"viewTracesFullScreenInfo": "Mostrar en pantalla completa al ver rastros",
		"editScript": "Editar script",
		"printScript": "Permitir script de impresión",
		"viewTracesScript": "Permitir script de ver rastros",
		"handwrittenApproval": "Aprobación escrita a mano",
		"handwrittenApprovalScript": "Permitir script de aprobación escrita a mano",
		"handwrittenApprovalType": "Tipo de aprobación escrita a mano",
		"savetext": "Guardar texto (como fondo)",
		"notsavetext": "No guardar texto",
		"handwrittenApprovalTypeInfo": "Guardar el texto como fondo es aplicable cuando el contenido del flujo de trabajo se modificará después de la aprobación escrita a mano",
		"zoom": "Establecer zoom",
		"zoomInfo": "Si los usuarios pueden personalizar o no el nivel de zoom",
		"fullWidth": "Conversión de ancho completo",
		"fullWidthInfo": "Seleccione 'Sí' para convertir automáticamente los espacios en blanco de medio ancho en espacios en blanco de ancho completo.",
		"paragraphIndent": "Sangría de párrafo",
		"paragraphIndentInfo": "Seleccione 'Sí' para sangrar automáticamente la primera línea de cada párrafo",
		"doublePage": "Mostrar doble página",
		"doublePageInfo": "Permitir o no mostrar dos páginas simultáneamente",
		"fullScreen": "Pantalla completa",
		"fullScreenInfo": "Permitir o no la visualización en pantalla completa",
		"wordConversion": "Conversión de WORD",
		"wordConversionType": "Tipo de conversión",
		"isConversionSeal": "Convertir sello",
		"wordConversionWithService": "Usar servicio",
		"fileName": "Nombre del archivo",
		"fileSite": "Sitio del archivo adjunto",
		"addPageNumber": "Agregar números de página",
		"addPageNumberInfo": "Agregar números de página después de la conversión a Word",
		"whenConversion": "Cuándo convertir",
		"onSubmit": "Al enviar",
		"onSave": "Al guardar",
		"conversionCondition": "Condición de conversión",
		"alwaysConvert": "Convertir siempre",
		"whenConditionsMet": "Convertir cuando se cumplan las condiciones",
		"static": "Estático",
		"wordConversionEncryption": "Protección de edición",
		"wordConversionEncryptionInfo1": "(Solo disponible en el modo OOXML)",
		"wordConversionEncryptionInfo": "Si se selecciona 'Sí', se aplicará protección de edición al archivo convertido para restringir todas las ediciones en el documento de Word convertido.",
		"wordEncryptionPasswordType": "Contraseña",
		"toWordPasswordScript": "Script de contraseña",
		"wordEncryptionPasswordInput": "Introducir contraseña",
		"toWordPasswordScriptInfo": "Devuelve una cadena como contraseña. Tenga en cuenta que el administrador u otros miembros relevantes deben conocer esta contraseña para poder desbloquear el documento protegido después de la conversión.",
		"config": "Config",
		"copiesSecretPriority": "Copias, Nivel de secreto, Prioridad",
		"isShow": "Mostrar o no",
		"copies": "Copias",
		"auto": "Automático",
		"showScript": "Script de mostrar",
		"bindValue": "Valor de enlace",
		"bindValueScript": "Script de valor de enlace",
		"secret": "Nivel secreto",
		"priority": "Prioridad",
		"redHeader": "Encabezado rojo",
		"redLine": "Línea roja",
		"fileNo": "Número de archivo",
		"signer": "Firmante",
		"subject": "Título del documento",
		"editSubjectInfo": "Si se permite la edición del título, no vincule datos",
		"mainSend": "Destinatario principal",
		"attachment": "Adjunto",
		"attachmentText": "Contenido del adjunto",
		"attachmentInfor": "[Haga clic aquí para editar el contenido del adjunto]",
		"issuanceUnit": "Unidad emisora",
		"issuanceDate": "Fecha de emisión",
		"annotation": "Anotación",
		"copyto": "Destinatarios adicionales",
		"copyto2": "A",
		"editionUnit": "Unidad editora",
		"editionDate": "Fecha de publicación",
		"meetingAttend": "Asistencia a reuniones",
		"meetingLeave": "Ausencia en reuniones",
		"meetingSit": "Participante invitado a reuniones",
		"meetingRecord": "Acta de la reunión",
		"customElement": "Configuración de los elementos personalizados",
		"subjectEditBindFormData": "Ruta sincrónica de los datos",
		"fontFamily": "Fuente",
		"autoCorrect": "Corrección automática",
		"ckeditorInfo": "Para obtener más ayuda sobre las propiedades, consulte",
		"ckeditorInfo2": "Devuelve el objeto Config de CKEditor para la inicialización del editor",
		"ckeditorInfo3": "Para obtener más ayuda sobre los eventos, consulte",
		"tinymceInfo": "Para obtener más ayuda sobre las propiedades, consulte",
		"tinymceInfo2": "Devuelve el objeto Config de TinyMCE para la inicialización del editor",
		"tinymceInfo3": "Los eventos queryLoad, postLoad, load y afterLoad son eventos de la plataforma O2. Los demás eventos son eventos del editor TinyMCE. Puede usar this.target para obtener el entorno de script y this.event para obtener el objeto de evento. Consulte",
		"base64Encode": "Codificar imagen en Base64",
		"imagePreview": "Vista previa de imagen original",
		"ieOnly": "Solo disponible en el navegador IE",
		"keepHistory": "¿Mantener historial de versiones?",
		"openAttachment": "¿Permitir abrir archivos adjuntos?",
		"attachmentId": "Identificador de cuadro de archivo adjunto",
		"attachmentReadonly": "Solo lectura para archivos adjuntos",
		"autoSave": "Guardado automático",
		"historyCount": "Número de versiones a mantener",
		"timeInterval": "Intervalo de tiempo (en minutos)",
		"showSummary": "Mostrar resumen si no se puede habilitar el control",
		"byTemplate": "Crear según plantilla",
		"readonlyCondition": "Hacer solo lectura si se cumplen las condiciones",
		"officeFileSite": "Sitio para leer archivos",
		"userTitle": "Título de usuario",
		"userId": "Identificación de usuario",
		"toolbar": "Barra de herramientas",
		"tools": "Herramientas",
		"newDoc": "Nuevo documento",
		"openLocal": "Abrir archivo local",
		"saveLocal": "Guardar en local",
		"traceSwitch": "Alternar rastros",
		"fullscreenMode": "Modo pantalla completa",
		"toolbarSwitch": "Alternar barra de herramientas",
		"printPreview": "Vista previa de impresión",
		"redFileButton": "Botón de encabezado rojo",
		"stampButton": "Botón de sello",
		"showHistory": "Ver historial de versiones",
		"showTitleBar": "¿Mostrar barra de título?",
		"showMenuBar": "¿Mostrar barra de menú?",
		"showToolBar": "¿Mostrar barra de herramientas?",
		"showStatusBar": "¿Mostrar barra de estado?",
		"showZoom": "¿Mostrar nivel de zoom?",
		"borderStyle": "Estilo de borde",
		"borderColor": "Color de borde",
		"flat": "Plano",
		"noCopy": "¿Prohibir copiar?",
		"keepTraces": "¿Mantener rastros?",
		"read": "Lectura",
		"otherAttr": "Otras propiedades",
		"querySelectBox": "Cuadro de selección de consulta",
		"selectBoxTitle": "Título del cuadro de selección",
		"query": "Consulta",
		"pathInfo": "Nota: la ruta se escribe como \"alias de tabla.nombre de campo\", por ejemplo: o.titulo",
		"parameterNote": "Nota: el parámetro corresponde al parámetro en la consulta y en la sentencia de recuento total;\npara una condición WHERE como \":campo\", ingrese \"campo\";\npara una condición WHERE como \"?1\", ingrese \"?1\".",
		"source": "Fuente de datos",
		"method": "Método",
		"systemSource": "Fuente de datos de la plataforma",
		"applicationService": "Servicio de aplicación",
		"parameter": "Parámetro",
		"requestBody": "Cuerpo de solicitud",
		"test": "Prueba",
		"hostPort": "Host/Puerto",
		"handle": "Manejar",
		"widget": "Widget",
		"widgetScript": "Script de widget",
		"parameterScript": "Script de parámetro (retorna objeto)",
		"insertWidget": "Insertar elemento de widget",
		"selectWidget": "Seleccionar widget",
		"selectPortal": "Seleccionar portal",
		"inDiv": "¿Envolver en div?",
		"outerSideModuleId": "Identificación de componente externo relacionado",
		"addButtonId": "Identificación de botón Agregar",
		"deleteSelectedButtonId": "Identificación de botón Eliminar elemento seleccionado",
		"selectAllModuleId": "Identificación de componente Seleccionar todo",
		"selectedValue": "Valor seleccionado",
		"innerSideModuleId": "Identificación de componente interno relacionado",
		"deleteButtonId": "Identificación de botón Eliminar",
		"sequenctModuleId": "Identificación de componente Secuencia",
		"selectModuleId": "Identificación de componente Seleccionar",
		"defaultShow": "Mostrar por defecto",
		"item": "Elemento",
		"maxItemCount": "Número máximo de elementos a agregar",
		"minItemCount": "Número mínimo de elementos a mantener",
		"dtImportInfor": "Nota: las imágenes, los archivos adjuntos, las tablas de datos y las plantillas de subdatos no se pueden importar ni exportar.",
		"importButtonId": "Identificación de botón Importar",
		"exportButtonId": "Identificación de botón Exportar",
		"importExporConfig": "Configuración de campos para importar/exportar",
		"validationPopFormConfig": "Configuración del cuadro de diálogo emergente de validación",
		"validationPopFormHeight": "Altura del cuadro de diálogo emergente",
		"validationPopFormWidth": "Ancho del cuadro de diálogo emergente",
		"validationTableStyle": "Estilo de tabla de validación",
		"validationTitleTdStyle": "Estilo de celda de título de validación",
		"validationContentTdStyle": "Estilo de celda de contenido de validación",
		"validationTableAttribute": "Atributos de tabla de validación",
		"count": "Cantidad",
		"import": "Importar",
		"datatableEditMode": "Modo de edición de la tabla de datos",
		"datatableEditModeValue": [
			"Editar una fila cada vez",
			"Editar varias filas al mismo tiempo"
		],
		"onlyPc": "Solo disponible en PC",
		"size": "Tamaño",
		"color": "Color",
		"el_bt_default": "Botón predeterminado",
		"el_bt_primary": "Botón principal",
		"el_bt_success": "Botón de éxito",
		"el_bt_warning": "Botón de advertencia",
		"el_bt_danger": "Botón de peligro",
		"el_bt_info": "Botón de información",
		"el_bt_text": "Botón de texto",
		"el_plain": "Botón plano",
		"el_round": "Botón redondeado",
		"el_circle": "Botón circular",
		"el_icon": "Icono",
		"el_disabled": "¿Deshabilitado?",
		"el_loading": "Cargando",
		"el_autofocus": "Foco predeterminado",
		"el_isText": "Mostrar texto",
		"layout": "Diseño",
		"layoutCode": "Código de diseño",
		"layoutTemplate": "Diseños comunes",
		"elGroupStyles": "Estilos de grupo",
		"elGroupProperties": "Propiedades de grupo",
		"el_border": "Mostrar borde",
		"el_radioColor": "Color de fuente",
		"el_radioFillColor": "Color de relleno",
		"el_buttonRadio": "Modo de botón",
		"datatemplateOuterNote": "Nota: Identificación de componentes relacionados fuera del actual modelo de datos. El modelo de datos puede tener varias capas, y las identificaciones de los componentes externos se deben llenar siguiendo las siguientes reglas:<br/>1. Para el modelo de datos con una sola capa o la capa más externa, complete con \"fieldId\" para representar el componente directo en el formulario.<br/>2. Si hay varias capas de modelo de datos, use \"./fieldId\" para representar los componentes en el mismo nivel que el modelo de datos actual, y use \"../fieldId\" para representar los componentes en el nivel superior del modelo de datos, y así sucesivamente.<br/>3. También se puede usar \"datatemplateId.*.datatemplateId2.*.fieldId\" para representar la ruta completa en diferentes niveles de modelo de datos. datatemplateId representa el id del primer nivel de modelo de datos, y datatemplateId2 representa el id del segundo nivel de modelo de datos, y así sucesivamente.",
		"datatemplateInnerNote": "Nota: Identificación de componentes relacionados dentro del modelo de datos actual. Independientemente de si es un modelo de datos de una sola capa o de varias capas, ingrese directamente la identificación del componente correspondiente.",
		"importModel": "Importar modelo",
		"enable": "Habilitar",
		"disable": "Deshabilitar",
		"downloadTempalte": "Descargar plantilla",
		"downloadTempalteId": "Identificación del componente para descargar plantilla",
		"downloadTempalteIdNote": "Puede crear un componente en el formulario y completar su identificación aquí. El sistema vinculará el evento click para descargar la plantilla a la nodo correspondiente del componente.",
		"province": "Provincia",
		"city": "Ciudad",
		"county": "Distrito",
		"useTextFieldNote": "Nota: se recomienda utilizar componentes de texto",
		"useChecboxNote": "Nota: se recomienda utilizar componentes de selección múltiple",
		"checkboxValueNote": "Nota: corresponde al valor seleccionable del componente seleccionado",
		"checkboxValueAllNote": "Nota: corresponde al valor seleccionable del componente Seleccionar todo",
		"notShow": "No mostrar",
		"insertDataTemplate": "Insertar modelo de datos",
		"widthModules": "Insertar con componentes relacionados",
		"ckeditConfig": "Configuración del editor",
		"ckeditConfigInfor": "Devuelve un objeto json que contiene la configuración del editor",
		"ckeditConfigInfor1": "Puede configurar las funciones de la barra de herramientas del editor a través del siguiente enlace:",
		"ckeditConfigInfor2": "../o2_lib/htmleditor/ckeditor4161/samples/toolbarconfigurator/index.html",
		"ckeditConfigInfor3": "Haga clic aquí",
		"ckeditConfigInfor4": "Para obtener más configuraciones, consulte el sitio web oficial de Ckeditor",
		"ckeditConfigInfor5": "https://ckeditor.com/ckeditor-4/",
		"ckeditConfigInfor6": "Nota: después de personalizar las propiedades del editor, es posible que el formato del cuerpo de texto ya no cumpla con los estándares nacionales para documentos oficiales gubernamentales.",
		"showRead": "Mostrar pendientes de lectura",
		"password": "Contraseña",
		"search": "Buscar",
		"email": "Correo electrónico",
		"datetime-local": "Fecha y hora",
		"month": "Mes",
		"date": "Fecha",
		"time": "Hora",
		"week": "Semana",
		"textarea": "Texto multilínea",
		"wordNumber": "Contador de palabras",
		"maxlength": "Longitud máxima",
		"clearable": "Borrable",
		"showPassword": "Mostrar/ocultar contraseña",
		"prefixIcon": "Ícono en el inicio",
		"suffixIcon": "Ícono en el final",
		"textareaRows": "Número de filas para texto multilínea",
		"autosize": "Ajuste de altura",
		"minRows": "Número mínimo de filas",
		"maxRows": "Número máximo de filas",
		"resize": "Cambio de tamaño",
		"resizeNone": "No permitido",
		"resizeBoth": "Permitido",
		"resizeHorizontal": "Horizontal",
		"resizeVertical": "Vertical",
		"el_placement": "Posición emergente",
		"popperClass": "Nombre de clase para la lista",
		"triggerOnFocus": "Sugerencias aparecen al hacer clic en el cuadro de entrada",
		"itemScriptInfo": "Devuelve una función que proporciona sugerencias de entrada. Function(queryString, callback)",
		"multiple": "¿Múltiple selección?",
		"collapseTags": "Combinar etiquetas (tags)",
		"multipleInfo": "Solo válido si es posible múltiple selección",
		"filterable": "Permitir búsqueda",
		"filterMethod": "Método de búsqueda personalizado",
		"filterRemote": "Búsqueda remota",
		"allowCreate": "Crear nuevo elemento",
		"noMatchText": "Mensaje de texto sin coincidencias",
		"noDataText": "Mensaje de texto sin datos",
		"loadingText": "Mensaje de carga",
		"remoteMethod": "Método de búsqueda remota",
		"multipleLimit": "Número máximo de opciones seleccionables",
		"max": "Valor máximo",
		"min": "Valor mínimo",
		"step": "Incremento",
		"step_strictly": "Solo permitir múltiplos del incremento",
		"precision": "Precisión numérica",
		"controls": "Botones de control",
		"controlsPosition": "Posición de los botones",
		"activeText": "Texto de activación",
		"inactiveText": "Texto de desactivación",
		"activeColor": "Color de activación",
		"inactiveColor": "Color de desactivación",
		"activeIconClass": "Ícono de activación",
		"inactiveIconClass": "Ícono de desactivación",
		"activeValue": "Valor de activación",
		"inactiveValue": "Valor de desactivación",
		"valueType": "Tipo de valor",
		"showInput": "Mostrar entrada de texto",
		"showInputControls": "Mostrar botones en la entrada de texto",
		"inputSize": "Tamaño de entrada de texto",
		"sliderRange": "Seleccionar rango",
		"sliderVertical": "Modo vertical",
		"sliderMarks": "Marcas de selección",
		"showTooltip": "Mostrar información de herramienta (tooltip)",
		"tooltipClass": "Clase de información de herramienta (tooltip)",
		"formatTooltip": "Formato de información de herramienta (tooltip)",
		"formatTooltipScript": "Devuelve una función de formato:",
		"showStops": "Mostrar puntos de interrupción",
		"marksScriptInfo": "Devuelve un objeto. La clave debe ser de tipo número y estar dentro del intervalo cerrado [min, max]. Cada marca puede tener su propio estilo.",
		"optionsGroup": "Opciones de grupo",
		"selectItemScriptInfo": "Devuelve una matriz de valores opcionales. También puede devolver una promesa que resuelva en una matriz de valores opcionales.",
		"selectTemplete": "Plantilla personalizada de opciones",
		"showAllLevels": "Mostrar ruta completa",
		"checkStrictly": "No relacionar nodos padre e hijo",
		"checkStrictlyInfo": "Indica si los nodos padres e hijos no tienen relación entre sí",
		"emitPath": "Emitir matriz completa",
		"emitPathInfo": "Indica si debe retornarse una matriz que contenga los valores de todos los menús en los que se encuentra el nodo seleccionado. Si se establece en falso, solo se devuelve el valor del nodo seleccionado.",
		"lazy": "Carga dinámica",
		"lazyLoadScript": "Método de carga dinámica",
		"props_value": "Propiedad de valor de opción",
		"props_label": "Propiedad de etiqueta de opción",
		"props_children": "Propiedad de opciones secundarias",
		"props_disabled": "Propiedad de opción deshabilitada",
		"props_leaf": "Propiedad de indicador de nodo hoja",
		"expandTrigger": "Activador de expansión",
		"beforeFilter": "Antes del filtrado",
		"filterMethodInfo": "Devuelve una función personalizada para la lógica de búsqueda. El primer parámetro es un nodo y el segundo es una palabra clave a buscar. Retorna un valor booleano que indica si se ha encontrado coincidencia.",
		"beforeFilterInfo": "Devuelve una función que se ejecuta antes del filtrado. El parámetro es el valor ingresado. Si devuelve false o una promesa que se rechaza, el filtrado se detiene.",
		"lazyLoadScriptInfo": "Método para cargar datos de forma dinámica. Solo es válido cuando está activada la carga dinámica. Retorna una función(node, resolve) donde node es el nodo actualmente seleccionado y resolve es el callback cuando se completa la carga de datos (debe ser llamado).",
		"firstPageNumber": "Número de página inicial",
		"showOptions": "Mostrar opciones",
		"onInput": "Cuando se ingresa",
		"onFocus": "Al hacer clic",
		"emptyValue": "Valor vacío",
		"showZero": "Mostrar cero",
		"showNullString": "Mostrar cadena vacía",
		"centerServer": "Servidor central",
		"pathConditions": "Condiciones predeterminadas de ruta",
		"parameterConditions": "Condiciones predeterminadas de parámetros",
		"addDefaultConditionByPath": "Agregar condición predeterminada por ruta",
		"addDefaultConditionByParameter": "Agregar condición predeterminada por parámetro",
		"placementValue": [
			"Arriba Centro",
			"Arriba Izquierda",
			"Arriba Derecha",
			"Abajo Centro",
			"Abajo Izquierda",
			"Abajo Derecha"
		],
		"trigger": "Método de activación",
		"triggerValue": [
			"Pasar el ratón",
			"Hacer clic con el ratón"
		],
		"hideOnClick": "Ocultar menú al hacer clic",
		"showTimeout": "Retraso en la expansión",
		"hideTimeout": "Retraso en la contracción",
		"splitButton": "Habilitar clic y despliegue simultáneamente",
		"splitButtonType": "Tipo de botón",
		"menuItem": "Elemento del menú",
		"dropdownDefaultText": "Menú desplegable",
		"showButton": "Mostrar botón",
		"countPerline": "Número de opciones por línea",
		"countPerlineNote": "0 indica sin límite",
		"wps": {
			"config": "Config",
			"options": "Opciones generales",
			"topArea": "Área superior",
			"show": "Mostrar",
			"hide": "Ocultar",
			"headArea": "Área de la cabeza",
			"showMode": "Modo de visualización",
			"showMode_normal": "Modo normal, muestra todas las funciones",
			"showMode_simple": "Modo minimalista, no muestra encabezado ni barra de herramientas",
			"wordConfig": "Opciones de configuración de Word",
			"comment": "Comentario",
			"isShowDocMap": "¿Activar función de mapa de documento?",
			"isBestScale": "Al abrir el documento, mostrar en escala óptima (PC)",
			"isShowBottomStatusBar": "Barra de estado inferior (PC)",
			"isOpenIntoEdit": "¿Abrir en modo de edición en dispositivos móviles?",
			"component": "comp.",
			"isComponent": "¿Activar componente? (versión de PC)",
			"HeaderLeft": "Encabezado izquierdo",
			"HeaderRight": "Encabezado derecho",
			"FloatQuickHelp": "Ayuda rápida en la esquina inferior derecha (Jin Xiaobao)",
			"HistoryVersion": "Barra de estado superior - menú de historial - versión histórica",
			"HistoryRecord": "Barra de estado superior - menú de historial - registro colaborativo",
			"HistoryVersionDivider": "Tabla - menú emergente - línea de división para versión histórica y registro colaborativo",
			"TabPrintPreview": "Botón de impresión en la barra de herramientas superior",
			"MenuPrintPreview": "Botón de impresión en el menú desplegable de 'Más'",
			"ReviewTrackChanges": "Botón de estado de edición y revisión",
			"TrackChanges": "Opciones desplegables para el modo de edición y revisión",
			"ContextMenuConvene": "Invocar ayuda en línea al hacer clic derecho en el texto",
			"isComponentMobile": "¿Activar componente? (versión móvil)",
			"Logo": "Logotipo en la barra de estado",
			"Cooperation": "Avatar de colaboración en la barra de estado",
			"More": "Botón de 'Más' en la barra de estado",
			"SendButton": "Botón de compartir en la barra de herramientas superior",
			"CooperHistoryMenuItem": "Menú de registro colaborativo en la barra de herramientas superior",
			"WriterHoverToolbars": "Barra de herramientas inferior para el texto",
			"ReadSetting": "Configuración de lectura en la barra de estado del texto"
		},
		"onlyoffice": {
			"config": "Config",
			"moduleConfig": "Configuración de características",
			"autosave": "Guardado automático",
			"chat": "Activar chat",
			"comments": "Habilitar comentarios",
			"compatibleFeatures": "Compatibilidad con versiones antiguas",
			"plugins": "Activar complementos",
			"reviewDisplay": "Forma de visualización de revisiones",
			"reviewDisplay_markup": "Marcado",
			"reviewDisplay_final": "Versión final",
			"reviewDisplay_original": "Original",
			"showReviewChanges": "Mostrar cambios de seguimiento",
			"trackChanges": "Activar modo de edición y revisión",
			"spellcheck": "Corrección ortográfica",
			"viewSet": "Configuración de interfaz",
			"compactHeader": "Ocultar encabezado del editor",
			"compactToolbar": "Barra de herramientas compacta",
			"feedback": "¿Mostrar comentario?",
			"help": "¿Mostrar ayuda?",
			"toolbarHideFileName": "¿Mostrar nombre del archivo en la barra de título?",
			"toolbarNoTabs": "¿Resaltar barra de herramientas superior?",
			"unit": "Unidad de medida de la regla",
			"unit_cm": "Centímetros",
			"unit_pt": "Píxeles",
			"unit_inch": "Pulgadas",
			"zoom": "Ajuste de zoom predeterminado",
			"hideRightMenu": "Ocultar menú lateral",
			"individualization": "Información personalizada",
			"address": "Dirección",
			"mail": "Correo electrónico",
			"info": "Información general",
			"company": "Nombre de la empresa",
			"www": "Sitio web",
			"feedbackUrl": "Dirección de comentario",
			"logoImg": "Logotipo superior izquierdo (172x40)",
			"logoUrl": "Enlace del logotipo"
		},
		"smartbi": {
			"select": "Selección de recursos",
			"displayToolbar": "Mostrar barra de herramientas",
			"toolbarShow": "Mostrar",
			"toolbarHide": "Ocultar",
			"displayLeftTree": "Mostrar árbol lateral izquierdo",
			"leftTreeShow": "Mostrar",
			"leftTreeHide": "Ocultar"
		},
		"weeks": {
			"arr": [
				"Lunes",
				"Martes",
				"Miércoles",
				"Jueves",
				"Viernes",
				"Sábado",
				"Domingo"
			]
		},
		"tabletWidth": "Ancho de la tableta de escritura a mano",
		"tabletHeight": "Altura de la tableta de escritura a mano",
		"tabletSizeNote": "Solo válido en versión de PC, pantalla completa de ancho en dispositivos móviles",
		"tabletToolbarNote": "Solo válido en versión de PC, no se muestra en dispositivos móviles",
		"editable": "Editable",
		"firstDayOfWeek": "Primer día de la semana",
		"disabledDate": "Fechas deshabilitadas",
		"disabledDateNote": "'this.event' es la fecha seleccionada, 'return true' significa que esa fecha está deshabilitada",
		"disabledDateScript": "Script para fechas deshabilitadas",
		"selectableRangeNote": "Devuelve el rango de tiempo seleccionable, por ejemplo: return '18:30:00 - 20:30:00' o return ['09:30:00 - 12:00:00', '14:30:00 - 18:30:00']",
		"selectableRangeScript": "Script para rango de tiempo seleccionable",
		"placeholder": "Texto de marcador de posición",
		"rangeSeparator": "Separador de rango",
		"startPlaceholder": "Marcador de posición de inicio",
		"endPlaceholder": "Marcador de posición de fin",
		"arrowControl": "Usar flechas para seleccionar tiempo",
		"timeSelectType2": "Tipo de selección de tiempo",
		"isRange": "Rango",
		"fixedTimePoint": "Tiempo fijo",
		"anyTimePoint": "Cualquier tiempo",
		"to": "a",
		"startTime": "Hora de inicio",
		"endTime": "Hora de fin",
		"startDate": "Fecha de inicio",
		"endDate": "Fecha de fin",
		"selectableRange": "Rango seleccionable",
		"endSelectableRange": "Fin del rango seleccionable",
		"initialIndex": "Índice inicial de la diapositiva",
		"autoplay": "Cambio automático",
		"interval": "Intervalo de cambio",
		"indicatorPosition": "Posición del indicador",
		"indicatorPositionValue": [
			"Interior",
			"Exterior",
			"Ninguno"
		],
		"arrow": "Flechas",
		"arrowValue": [
			"Mostrar al pasar el mouse",
			"Mostrar siempre",
			"No mostrar"
		],
		"carouselTypeValue": [
			"Predeterminado",
			"Tarjeta"
		],
		"loop": "¿Ciclar?",
		"direction": "Dirección de la presentación",
		"directionValue": [
			"Horizontal",
			"Vertical"
		],
		"hotpicture": "Imagen de punto caliente",
		"page": "Página",
		"filterParameter": "Parámetro de filtro",
		"selectComponent": "Seleccionar aplicación",
		"calculationComponent": "Calcular ruta de la aplicación",
		"component": "Aplicación",
		"scriptComponentNote": "Devuelve la ruta de la aplicación, como 'Gestión de organizaciones'",
		"componentScript": "Script de la ruta de la aplicación",
		"applicationOptions": "Opciones de la aplicación",
		"applicationStatus": "Estado de la aplicación",
		"titleAddTo": "Agregar a la línea de título",
		"firstLine": "Primera línea",
		"lastLine": "Última línea",
		"digitsToSeparate": "Número de separadores",
		"digitsToSeparateNote": "Agregue cada par de dígitos, separadores, como el millar para agregar separadores cada tres dígitos, entonces rellene 3.",
		"asyncLoad": "Carga asíncrona",
		"defaultOptionScript": "Guión opcional predeterminado",
		"reserve": "Retención",
		"showRowToColumn": "Conversión de filas y filas",
		"chartNodeStyles": "Estilo de contenedor gráfico",
		"tableNodeStyles": "Estilo de contenedor de tabla",
		"logHtmlScript": "Guiones HTML",
		"flow": "Continuar circulando",
		"el_iconPosition": "Ubicación del icono",
		"checkOtherFlow": "Verificar otros métodos de circulación",
		"checkOtherFlowNote": "Ejecute el guión de verificación cuando se agregue, restablezca o devuelva, obtenga el método de circulación a través de este.formulario.currentrouteme (agregue la etiqueta a: addatask, restablezca a: reset, devuelva a: goback), obtenga una opinión a través de este.formulario.opinion, obtenga otros parámetros de la circulación a través de este.formulario.flowdata",
		"forceClearCustomViewStyle": "Limpiar estilos personalizados al cambiar",
		"forceClearCustomStyle": "Limpiar estilos personalizados al cambiar"
	},
	"smartbi": {
		"nosetup": "Por favor, instala la aplicación SmartBI primero",
		"txt": "Informe de SmartBI"
	},
	"onlyoffice": {
		"nosetup": "Por favor, instala la aplicación OnlyOffice primero"
	},
	"wpsoffice": {
		"nosetup": "Por favor, instala la aplicación WpsOffice primero"
	},
	"officeonline": {
		"nosetup": "Por favor, instala la aplicación OfficeOnline primero"
	},
	"actionBar": {
		"close": "Cerrar",
		"closeTitle": "Cerrar documento",
		"save": "Guardar",
		"saveTitle": "Guardar documento",
		"flow": "Enviar",
		"flowTitle": "Continuar el flujo de trabajo del documento",
		"submit": "Enviar",
		"submitTitle": "Enviar documento",
		"reroute": "Redirigir",
		"rerouteTitle": "Redirigir documento",
		"reset": "Restablecer",
		"resetTitle": "Restablecer asignatarios",
		"split": "Agregar bifurcación",
		"splitTitle": "Agregar bifurcación de división",
		"retract": "Retirar",
		"retractTitle": "Retirar tarea pendiente",
		"rollback": "Volver atrás",
		"rollbackTitle": "Volver a un paso anterior sin conservar registros de flujo de trabajo",
		"delete": "Eliminar",
		"deleteTitle": "Eliminar archivo",
		"terminar": "Terminar",
		"terminateTitle": "Finalizar transferencia de archivo",
		"print": "Imprimir",
		"printTitle": "Imprimir documento",
		"press": "Urgir",
		"pressTitle": "Urgir la resolución",
		"pause": "Suspender",
		"pauseTitle": "Suspender tarea pendiente",
		"resume": "Reanudar suspensión",
		"resumeTitle": "Reanudar una tarea suspendida",
		"downloadAll": "Descargar todo",
		"downloadAllTitle": "Descargar todo",
		"monitor": "Monitor de proceso",
		"monitorTitle": "Monitor de proceso",
		"setReaded": "Marcar como leído",
		"readed": "Leído",
		"addTask": "Añadir destinatario",
		"addTaskTitle": "Añadir destinatario a la actividad actual",
		"terminate": "Documento de terminación",
		"goBack": "Devolución",
		"goBackTitle": "Devolución a actividades ya pasadas"
	},
	"filedConfigurator": {
		"sequence": "Secuencia",
		"fieldTitle": "Título del campo",
		"fieldId": "Identificación del campo",
		"action": "Acción",
		"moveup": "Mover a la fila anterior",
		"deleteRow": "Eliminar fila",
		"insertRow": "Insertar fila",
		"importFromForm": "Importar configuración de campos desde la interfaz",
		"forceClearCustomViewStyle": "Limpiar estilos personalizados al cambiar"
	},
	"formToolbar": {
		"save": "Guardar formulario",
		"saveNew": "Guardar como plantilla",
		"preview": "vista previa",
		"print": "imprimir",
		"formExplode": "Exportar formulario",
		"formImplode": "Importación de formulario",
		"formImplodeO2": "Importar desde datos de O2",
		"formImplodeO2Title": "Importar formulario en formato O2",
		"htmlImplode": "Importar desde HTML",
		"officeImplode": "Importar desde WORD o EXCEL",
		"help": "ayuda",
		"clearNoDomModule": "Borrar configuraciones de componentes que no están en el árbol HTML",
		"autoSave": "AutoGuardar",
		"brush": "cepillar",
		"viewAllVersion": "Ver todas las versiones del formulario"
	}
}
MWF.xApplication.process.FormDesigner["lp."+o2.language] = MWF.xApplication.process.FormDesigner.LP