MWF.xApplication.process.FormDesigner.LP = {
		"title": "フォーム編集",
		"newForm": "新しいフォーム",
		"property": "プロパティ",
		"tools": "ツール",
		"all": "すべて",
		"repetitionsId": "繰り返しコンポーネントの識別子",
		"notNullId": "コンポーネントの識別子は空白にできません",
		"notNumberId": "コンポーネントの識別子は純粋な数字であってはいけません",
		"notDoubleDotId": "コンポーネントの識別子に連続した2つのドットは含めることはできません",
		"notSpecialCharacterId": "コンポーネントの識別子には次の文字を含めることはできません：!{}<>,;'\"",
		"history": "履歴",
		"componentTree": "コンポーネントツリー",
		"invalidElementUIId": "Elementコンポーネントのデータは双方向バインディングが必要ですので、識別子は以下の構成項目と重複しないようにしてください：",
		"button": {
			"ok": "確定",
			"cancel": "キャンセル"
		},
        "version" : {
            "title": "フォームバージョン履歴を表示",
			"close": "閉じる",
			"no": "番号",
			"updateTime": "更新日時",
			"op": "操作",
			"person": "更新者",
			"resume": "復元",
			"resumeConfirm": "復元の確認",
			"resumeInfo": "フォームを復元する必要があるかどうかを確認しますか？復元を確認すると、現在のフォームが更新され、現在のフォームを手動で保存する必要があります。",
			"resumeSuccess": "復元成功"
        },
		"notice": {
			"save_success": "フォーム保存成功！",
			"saveTemplate_success": "フォームテンプレート保存成功！",
			"saveTemplate_inputName": "テンプレートタイトルを入力してください",
			"saveTemplate_inputCategory": "テンプレートのカテゴリを確定してください",
			"deleteElementTitle": "フォーム要素削除確認",
			"deleteElement": "現在の要素およびその子要素を削除してもよろしいですか？",
			"deleteRowTitle": "テーブル行削除確認",
			"deleteRow": "現在の行を削除すると、その行のすべてのセルの内容が削除されます。現在選択されている行を削除してもよろしいですか？",
			"deleteColTitle": "テーブル列削除確認",
			"deleteCol": "現在の列を削除すると、その列のすべてのセルの内容が削除されます。現在選択されている列を削除してもよろしいですか？",
			"deleteEventTitle": "イベント削除確認",
			"deleteEvent": "現在のイベントを削除してもよろしいですか？",
			"deleteActionTitle": "操作削除確認",
			"deleteAction": "現在の操作を削除してもよろしいですか？",
			"deleteButtonTitle": "ボタン削除確認",
			"deleteButton": "現在の操作ボタンを削除してもよろしいですか？",
			"notUseModuleInMobile": "モバイルでこのモジュールは使用できません",
			"changeToSequenceTitle": "確認",
			"changeToSequence": "この操作は既に追加された要素を削除し、それを「シーケンス」列に変更しますか？"
		},

		"formAction": {
			"insertRow": "行の挿入",
			"insertCol": "列の挿入",
			"deleteRow": "行の削除",
			"deleteCol": "列の削除",
			"mergerCell": "セルの結合",
			"splitCell": "セルの分割",
			"move": "移動",
			"copy": "コピー",
			"delete": "削除",
			"add": "追加",
			"cut": "切り取り",
			"paste": "貼り付け",
			"open": "開く",
			"script": "スクリプト",
			"create": "作成",
			"mergeCell": "セルの結合",
			"styleBrush": "スタイルブラシ",
			"insertTop": "最上部に挿入",
			"insertBottom": "最下部に挿入",
			"insertBefore": "前に挿入",
			"insertAfter": "後に挿入",
			"injectNotice": "Ctrlキーを押しながらマウスを離して正確な位置に配置",
			"selectedContainer": "親オブジェクトの選択",
			"property": "プロパティ",
			"batchModify": "一括変更"
		},

        "actionbar": {
            "readhide": "表示時の読み取り設定",
			"edithide": "編集時の表示設定",
			"hideCondition": "非表示条件の設定",
			"title": "タイトル",
			"img": "アイコン",
			"action": "操作",
			"condition": "表示条件",
			"editScript": "操作スクリプトの編集",
			"editCondition": "非表示条件の編集（trueを返すと操作が非表示になります）",
			"up": "上へ移動",
			"property": "プロパティ",
			"addCustomTool": "カスタム操作の追加",
			"delete": "削除",
			"setProperties": "操作のプロパティを設定",
			"restoreDefaultTool": "削除されたデフォルト操作の復元",
			"selectDefaultTool": "デフォルト操作の選択",
			"setReaded": "既読としてマーク",
			"readed": "既読"
        },
        "isSave": "保存中です。お待ちください...",
		"scriptIncluder": {
			"yes": "はい",
			"no": "いいえ",
			"selectScript": "スクリプトの選択：",
			"repeatAddScriptNotice": "スクリプトを重複して追加しないでください",
			"selectScriptNotice": "まずスクリプトを選択してください",
			"asyncLoad": "非同期読み込み：",
			"asyncLoadScript": "非同期読み込みスクリプト：",
			"syncLoadScript": "同期読み込みスクリプト：",
			"delete_title": "スクリプトの読み込みをキャンセルしますか？",
			"delete_text": "選択したスクリプトの読み込みをキャンセルしますか？"
		},
        "dictionaryIncluder" : {
            "selectDictionary": "選択：",
			"repeatAddDictionaryNotice": "データ辞書を重複して追加しないでください",
			"rootDictionaryExistNotice": "すでにそのデータ辞書のルートパスが追加されています。追加する必要はありません。",
			"parentDictionaryExistNotice": "すでにそのデータ辞書の親パスが追加されています。追加する必要はありません。",
			"subDictionaryExistNotice": "すでにそのデータ辞書のサブパスが存在します。まず削除してから追加してください。",
			"selectDictionaryNotice": "まずデータ辞書を選択してください",
			"path": "パス：",
			"delete_title": "データ辞書の読み込みをキャンセルしますか？",
			"delete_text": "選択したデータ辞書の読み込みをキャンセルしますか？"
        },
        "validation": {
            "validation": "検証",
			"anytime": "いつでも",
			"decision": "決定選択",
			"decisionName": "<決定名>",
			"value": "値",
			"length": "値の長さ",
			"valueInput": "<値>",
			"isnull": "空である",
			"notnull": "空でない",
			"gt": "より大きい",
			"lt": "より小さい",
			"equal": "等しい",
			"neq": "等しくない",
			"contain": "含む",
			"notcontain": "含まない",
			"prompt": "プロンプト",
			"add": "追加",
			"modify": "修正",
			"when": "とき",
			"as": "として",
			"inputDecisionName": "決定名を入力してください",
			"inputValue": "値を入力してください",
			"inputPrompt": "プロンプト内容を入力してください",
			"delete_title": "検証内容の削除確認",
			"delete_text": "この検証コードを削除してもよろしいですか？"
        },

    "datagrid" : {
		"import": "インポート",
		"export": "エクスポート"
    },

    "selectIcon": "アイコンを選択",
    "selectImage": "画像を選択",
    "selectApplication": "アプリケーションを選択",
    "dutyInputTitle": "職務パラメータを追加",
    "dutyInput": "職務“{duty}”の組織を確定してください。",
    "select": "選択",
    "empty": "クリア",

    "creatorUnit": "起案者の所属組織",
    "currentUnit": "処理担当者の所属組織",
    "selectUnit": "組織を選択",
    "scriptUnit": "スクリプトを使用",

    "creatorCompany": "起案者の会社",
    "creatorDepartment": "起案者の部門",
    "currentCompany": "現在の会社",
    "currentDepartment": "現在の部門",

    "deleteDutyTitle": "職務の削除確認",
    "deleteDutyText": "職務“{duty}”を削除しますか？",

    "saveTemplate": "テンプレートとして保存",
    "templateName": "テンプレート名",
    "templateCategory": "テンプレートのカテゴリ",
    "templateDescription": "テンプレートの説明",
    "save": "保存",
    "cancel": "キャンセル",
    "newCategory": "新しいカテゴリ",
    "mustSelectFormStyle": "フォームスタイルを選択してください",
    "notValidJson": "無効なJSON形式",
    "mustSelectDict": "先にデータ辞書を選択してください",
    "mustSelect": "選択してください",

    "imageClipper": "画像エディタ",

    "clearNoDomModuleTitle": "HTMLツリーに存在しないモジュール設定をクリア",
    "clearNoDomModuleContent": "HTMLツリーに存在しないモジュール設定をクリアしますか？クリア後は保存して有効にする必要があります。",

    "refreshDatatemplateImpExpTitle": "フィールドインポートの確認",
    "refreshDatatemplateImpExpContent": "この操作はデータテンプレートの内部コンポーネントからフィールドを取得します。この操作を実行すると、以前に構成したフィールドが置き換えられます。続行しますか？",
    "handWriting": "手書き",

    "filter": {
        "and": "かつ",
		"or": "または",
		"equals": "等しい",
		"notEquals": "等しくない",
		"greaterThan": "より大きい",
		"greaterThanOrEqualTo": "以上",
		"lessThan": "より小さい",
		"lessThanOrEqualTo": "以下",
		"like": "一致",
		"notLike": "一致しない",
		"from": "から",
		"value": "値"
    },
    "mastInputPath": "データパスを入力してください",
    "mastInputTitle": "タイトルを入力してください",
    "delete_filterItem_title": "フィルタ条件削除の確認",
    "delete_filterItem": "現在のフィルタ条件を削除してもよろしいですか？",

    "subformNameConflictTitle": "サブフォームフィールド名の衝突",
    "subformNameConflictInfor": "次のサブフォームフィールド名が既存のフォームと衝突しています:\n{name}",
    "subformConflictTitle": "サブフォームの挿入エラー",
    "subformConflictInfor": "同じサブフォームを重複して挿入することはできません",

    "subformNestedTitle": "サブフォームの挿入エラー",
    "subformNestedInfor": "相互にネストされたサブフォームを挿入することはできません",
    "checkSubformNestedError" : "選択したサブフォームに相互のネストがある場合、確認してください！",

    "checkSubformTitle": "フォーム保存の確認",
    "checkFormSaveError": "フォームを保存できません、以下の理由があります：<br>",
    "checkSubformPcInfor": "PCフォームに以下のサブフォームフィールドの衝突があります：<br>{subform}<br>",
    "checkSubformMobileInfor": "モバイルフォームに以下のサブフォームフィールドの衝突があります：<br>{subform}",

    "implodeError": "インポートするデータの形式が正しくありません",
    "implodeEmpty": "インポートするデータを編集欄に入力してください",
    "implodeConfirmTitle": "インポートの確認",
    "implodeConfirmText": "インポートしたデータは現在のページをクリアし、元に戻すことはできません。インポートしますか？",

    "design": "設計",
    "script": "コード",
    "html": "HTML",
    "css": "CSS",
    "byModule": "要素",
    "byPath": "タイプ",
    "events": "イベント",
    "pageform": "ページ",
    "importO2": "O2データからインポート",
    "importHTML": "HTMLからインポート",
    "importOffice": "WORDまたはEXCELからインポート",
    "importO2_infor": "O2形式のフォームデータを次のエディタにコピーしてください。（フォームまたはページデザイナーツールバーの「エクスポート」ボタンを使用してフォームデータを取得します。）<br/>Ctrl+Alt+Iを押してデータをフォーマットできます。",
    "importHTML_infor": "HTMLデータを次のエディタにコピーしてください。Ctrl+Alt+Iを押してデータをフォーマットできます。",
    "importHTML_infor2": "CSSデータを次のエディタにコピーしてください。Ctrl+Alt+Iを押してデータをフォーマットできます。",
    "importOffice_infor": "WordまたはExcelファイルを選択してください。",
    "import_ok": "インポート",
    "import_cancel": "キャンセル",
    "import_option1": "表の空白セルに入力ボックスを追加",
    "import_option2": "空の要素を削除",
    "implodeOfficeEmpty": "インポートするWordまたはExcelファイルを先に選択してください",

    "scriptTitle": {
        "validationOpinion": "フォームの意見検証",
		"validationRoute": "フォームルートの検証",
		"validationFormCustom": "フォームの検証",
		"defaultValue": "デフォルト値",
		"validation": "検証スクリプト",
		"sectionByScript": "スクリプトに基づくセクション",
		"itemScript": "選択可能な値のスクリプト",
		"iframeScript": "iframeスクリプト",
		"labelScript": "テキスト値",
		"rangeKey": "組織の範囲",
		"identityRangeKey": "身分組織の範囲",
		"unitRangeKey": "組織の選択範囲",
		"rangeDutyKey": "職務の範囲",
		"exclude": "選択排除スクリプト",
		"cookies": "データソースリクエストのクッキー",
		"requestBody": "データソースリクエストボディ",
		"jsonText": "データテキスト",
		"dataScript": "ツリーコントロールスクリプト",
		"itemDynamic": "動的オプションスクリプト",
		"defaultData": "データグリッドのデフォルト値",
		"editableScript": "データグリッドの編集可能性スクリプト",
		"config": "HTMLエディタの設定",
		"filterScript": "プロセスレコードのフィルタリングスクリプト",
		"readScript": "Office読み取り専用スクリプト",
		"fileSite": "Officeファイルサイトスクリプト",
		"subformScript": "サブフォームスクリプト",
		"selectedScript": "ビュー選択スクリプト",
		"action.tools": "アクションボタン"
    },
    "copyed": "コピー済み",
    "selectorButton": {
        "ok": "確認",
        "cancel": "キャンセル"
    },
    "modules": {
        "label": "テキスト",
		"textfield": "テキスト",
		"number": "数字フィールド",
		"org": "人員組織",
		"calendar": "日付選択",
		"textarea": "複数行テキスト",
		"select": "ドロップダウン",
		"radio": "ラジオボタン",
		"checkbox": "チェックボックス",
		"combox": "コンボボックス",
		"opinion": "意見ボックス",
		"button": "ボタン",
		"Address": "住所",
		"Actionbar": "アクションバー",
		"Sidebar": "サイドアクション",
		"image": "画像",
		"imageclipper": "画像エディタ",
		"attachment": "添付ファイル",
		"div": "コンテナ",
		"table": "テーブル",
		"datagrid": "データグリッド(非推奨)",
		"datatable": "データテーブル",
		"datatemplate": "テンプレート",
		"subform": "サブフォーム",
		"ViewSelector": "ビュー選択",
		"view": "埋め込みビュー",
		"stat": "埋め込み統計情報",
		"html": "HTML",
		"common": "一般要素",
		"tab": "タブ",
		"tree": "ツリー",
		"log": "プロセスログ",
		"monitor": "プロセスモニター",
		"iframe": "Iframe",
		"documenteditor": "文書エディタ",
		"htmledit": "HTMLエディタ",
		"office": "Officeコンポ",
		"yozoOffice": "永中コントロール",
		"statementSelector": "クエリビュー選択",
		"statement": "埋込クエリ",
		"SmartBI": "SmartBIレポート",

        "group_all": "すべて",
		"group_form": "フォーム",
		"group_layout": "レイアウト",
		"group_process": "プロセス",
		"group_filetext": "ファイル編集",
		"group_function": "機能",
		"group_element": "Element",

        "el_container": "レイアウト",
		"el_icon": "アイコン",
		"el_button": "ボタン",
		"el_radio": "ラジオボタン",
		"el_checkbox": "チェックボックス",
		"el_select": "セレクトボックス",
		"el_input": "入力ボックス",
		"el_autocomplete": "オートコンプ",
		"el_cascader": "カスケード",
		"el_number": "カウンター",
		"el_switch": "スイッチ",
		"el_slider": "スライダー",
		"el_time": "時間",
		"el_date": "日付",
		"el_datetime": "日時",
		"el_rate": "評価",
		"el_colorpicker": "カラーピッカー",
		"el_tree": "ツリー",
		"el_dropdown": "ドロップダウン",
		"el_carousel": "カルーセル",
		"el-menu": "ナビゲーションメニュー",
		"el_common": "一般",

		"importer": "データインポート",
		"readLog": "読み取りログ",
		"writingBoard": "手書きボード",
		"tinymceEditor": "Tinymce",
		"relatedLink": "関連リンク",
		"associatedDocument": "関連ドキュメント"
    },
    "propertyTemplate": {
        "base": "基本",
		"event": "イベント",
		"html": "HTML",
		"json": "JSON",
		"action": "アクション",
		"select": "選択",

		"id": "ID",
		"name": "名前",
		"description": "説明",
		"appearance": "外観タイプ",
		"style": "スタイル",
		"attribute": "属性",
		"imageStyle": "画像スタイル",

		"hideSystemTools": "システムアクション",
		"show": "表示",
		"hide": "非表示",
		"readed": "既読",

        "category": "カテゴリ",
		"formStyle": "フォームスタイル",
		"icon": "アイコン",
		"printForm": "フォーム印刷",
		"preloadScript": "プリロードスクリプト",
		"script": "スクリプト",
		"dict": "データ辞書",
		"dictName": "辞書名",
		"dictPath": "データパス",
		"valueKey": "値プロパティ名",
		"textKey": "テキストプロパティ名",
		"valueColumn": "値カラム",
		"textColumn": "テキストカラム",
		"dictKeyNote": "オブジェクト配列を返す場合、値プロパティ名またはテキストプロパティ名を構成する必要があります",
		"firstOptionEnable": "最初のオプションを使用",
		"firstOption": "最初のオプション",
		"copy": "コピー",
		"paste": "貼り付け",
		"language": "言語パッケージ",
		"languageScript": "言語パッケージスクリプト (S)",
		"languageInfo": "言語情報を含むJSONオブジェクトを返します；o2.languageを使用して現在の言語情報を取得します",
		"SubmitUI": "UIを送信",
		"submit": "送信",
		"systemDefault": "システムデフォルト",
		"selectForm": "フォームを選択",
		"computeForm": "フォームを計算",
		"application": "アプリケーション",
		"form": "フォーム",
        "crossApplication": "クロスアプリケーション",
		"computeSubmitAnnotation1": "アプリケーション名、エイリアス、ID",
		"computeSubmitAnnotation2": "フォーム名、ID",
		"computeWidgetAnnotation2": "ウィジェット名、ID",
		"thisApplication": "このアプリケーション",
		"submitFormScript": "フォーム提出スクリプト",
		"flowActionScript": "提出（フロー継続）アクションスクリプト",
		"handwritingSetting": "手書き意見設定",
		"enableHandwriting": "手書き意見を有効にする",
		"handwritingWidth": "手書き板の幅",
		"effectivePC": "PCでのみ有効",
		"handwritingHeight": "手書き板の高さ",
		"promptBoxFlow": "フロー後のポップアップ表示",
		"yes": "はい",
		"no": "いいえ",
		"usedNewWindow": "新しいブラウザウィンドウでのみ使用",
		"promptLocation": "ポップアップの位置",
		"lefttop": "左上",
		"righttop": "右上",
		"leftbottom": "左下",
		"rightbottom": "右下",
		"center": "中央",
        "prompt": "プロンプトボックス",
		"notClose": "自動的に閉じない",
		"closeInfo": "秒後に自動的に閉じる",
		"afterFlow": "フロー後",
		"closeWindow": "ウィンドウを閉じる",
		"redirect": "リダイレクト",
		"redirectScript": "リダイレクトスクリプト",
		"returnUrl": "リダイレクト用URL",
		"check": "チェック",
		"checkOpinion": "意見をチェック",
		"checkRoute": "ルートをチェック",
		"checkFlow": "フローをチェック",
		"noEventInfo": "注：サブフォームとして埋め込む場合、以下のイベントは実行されません",
		"none": "なし",
		"default": "デフォルト",
		"byScript": "スクリプトに従う",
		"byFormat": "フォーマットに従う",
		"table": "テーブル",
		"languageDefaultInfo": "システムは o2.language という名前のデータ辞書（またはスクリプト）を自動的にロードして言語パッケージとして使用します",
		"prefix": "接頭辞",
		"suffix": "接尾辞",
		"value": "値",
		"textValue": "固定値",

        "showIcon": "アイコン表示",
		"readonly": "読み取り専用",
		"AIInput": "AI入力",
		"inputStyle": "入力スタイル",
		"itemStyle": "アイテムスタイル",
		"actionStyles": "アクションスタイル",
		"imageStyles": "画像スタイル",
		"compute": "計算",
		"create": "作成",
		"save": "保存",
		"linkStyles": "リンクスタイル",

        "defaultValue": "デフォルト値",
		"verificationScript": "検証スクリプト",
		"verificationLineScript": "1行編集後の検証スクリプト",
		"section": "セクション",
		"enableSection": "セクションを有効にする",
		"sectionBy": "セクションの基準",
		"handler": "担当者",
		"handlerUnit": "担当者の所属組織",
		"activityId": "アクティビティID",
		"splitValue": "分割値",

        "enableSectionMerge": "セクション結合を有効にする",
		"showSectionKey": "セクションキーを表示",
		"editByMerge": "マージ編集（セクションキーの削除）",
		"sectionMergeSortScript": "ソートスクリプト",
		"sectionNodeStyles": "セクションノードスタイル",
		"sectionKeystyles": "セクションキースタイル",
		"sectionContentStyles": "セクションコンテンツスタイル",
		"mergeDisplay": "読み取り専用",
		"editCurrentSection": "編集（現在のセクションの編集を許可）",
		"mergeEdit": "編集（セクションキーを削除してデータをマージ）",
		"sectionKey": "セクションキー",
		"sectionKeyScript": "セクションキースクリプト",
		"textValue1": "テキスト値",
		"mergeType": "マージタイプ",
		"amountValue": "合計値",
		"averageValue": "平均値",
		"sectionMergeEditScript": "データマージスクリプト",
		"sectionMergeReadHtmlScript": "表示用HTMLスクリプト",
		"sectionMergeReadDataScript": "データスクリプト",
		"htmlScript": "HTMLスクリプト",
		"dataScript": "データスクリプト",
		"bySection": "セクション別",
		"byModule": "モジュール別",
		"totalRow": "合計行",
		"sectionAmountCellStyle": "セクション合計セルスタイル",
		"showAllSection": "すべてのセクションを表示",

        "rangeByDatetime": "日時範囲",
		"rangeByDateAndTime": "日付と時刻の範囲",
		"rangeByDate": "日付範囲",
		"rangeByTime": "時刻範囲",
		"rangeByOhter": "その他",
		"enableDate": "有効な日付",
		"enableHours": "有効な時間範囲",
		"enableMinutes": "有効な分範囲",
		"enableSeconds": "有効な秒範囲",

        "decimal": "小数点",

		"showCard": "カードを表示",
		"allowInput": "入力を許可",
		"dataStructure": "データ構造",
		"complete": "完全",
		"simple": "シンプル",
		"separator": "区切り記号",
		"asyncMode": "非同期モード",
		"asyncLoad": "非同期読み込み",

		"identity": "身分",
		"unit": "組織",
		"duty": "職位",
		"group": "グループ",
		"person": "個人",

        "defaultValueScript": "デフォルト値スクリプト",
		"showText": "テキスト表示",
		"showTextScript": "テキスト表示スクリプト",
		"unitSelectConfig": "ユーザーおよび組織選択の構成",
		"selectType": "選択タイプ",
		"selectCount": "選択数",
		"returnValue": "結果の返却",
		"readonlyScript": "読み取り専用スクリプト",

        "selectTypeInfo": "プロセス処理に参加するために身分を選択してください！",
		"selectTypeInfo2": "注意：個人はプロセス処理に参加できません！",
		"checkEmpower": "未処理の権限を確認",
		"onlyCustom": "カスタムオプションのみ使用",
		"unitRange": "組織の範囲",
		"allUnit": "すべての組織",
		"specifyUnit": "指定した組織",
		"draftUnit": "起案者の所属組織",
		"currentUnit": "現在のユーザーの所属組織",
		"inUnit": "直属の所属組織",
		"levelIs": "第",
		"levelUnit": "レベルの組織",
		"unitTypeIs": "タイプは",
		"deUnit": "の組織",
		"expandNext": "次のレベルを展開",
		"selectUnit": "組織を選択",
		"formData": "フォームデータ",
		"dutyRange": "役職の範囲",
		"all": "すべて",
		"all2": "すべて",
		"specifyDuty": "指定した役職",
		"byUnit": "組織別",
		"byDuty": "役職別",
		"showLevel": "レベルを表示",
		"byDutyUnit": "役職が所属する組織別",
		"byIdentityUnit": "身分が所属する組織別",
		"selectDuty": "役職を選択",
		"customOption": "カスタムオプション",
		"useScriptAddIdOrPerson": "スクリプトを使用して身分/個人を追加",
		"unitType": "組織のタイプ",
		"selectRange": "範囲を選択",
		"specifyGroup": "指定したグループ",
		"exclude": "除外",
		"excludeInfo": "スクリプトを記述して組織、身分、個人、およびグループの選択範囲を除外",
		"firstLevelSelectable": "第1レベルの選択を許可",

        "dateTime": "日時",
		"dateTime2": "日時",
		"dateOnly": "日付のみ",
		"monthOnly": "月のみ",
		"yearOnly": "年のみ",
		"timeOnly": "時間のみ",
		"weekOnly": "週番号",
		"multidate": "複数の日付",
		"datetimerange": "日時範囲",
		"daterange": "日付範囲",
		"timerange": "時間範囲",
		"monthrange": "月範囲",
		"selectSecond": "秒を選択",
		"timeSelectType": "時間選択タイプ",
		"timeSelectType_slider" : "スライダー",
		"timeSelectType_select" : "ドロップダウン",
		"format": "フォーマット",

        "rateTexts": "悪い, 不満足, 普通, 満足, 驚異的",
		"allowHalf": "半分の許可",
		"lowThreshold": "低-中間の閾値",
		"lowThresholdNote": "注：値自体が低得点に分類されます",
		"highThreshold": "中間-高い閾値",
		"highThresholdNote": "注：値自体が高得点に分類されます",
		"lowColor": "低得点の色",
		"mediumColor": "中得点の色",
		"highColor": "高得点の色",
		"voidColor": "未選択の色",
		"disabledVoidColor": "読み取り専用時の未選択の色",
		"showAfter": "後に表示",
		"showScore": "スコア表示",
		"textColor": "テキストの色",
		"textContent": "テキスト内容",
		"showAlpha": "透明度表示",
		"colorFormat": "カラーフォーマット",

        "nodeKey": "ノードの一意の識別キー",
		"nodeKeyNote": "各ツリーノードの一意の識別子として使用される属性で、ツリー全体で一意である必要があります。",
		"renderAfterExpand": "ノードを展開した後に子ノードをレンダリング",
		"defaultExpandAll": "デフォルトですべてのノードを展開",
		"highlightCurrent": "現在の選択ノードを強調表示",
		"currentNodeKey": "現在の選択ノードのキー値",
		"expandOnClickNode": "ノードをクリックして展開",
		"clickNode": "ノードをクリックしたとき",
		"clickArrow": "矢印をクリックしたとき",
		"checkOnClickNode": "ノードをクリックして選択",
		"clickCheckbox": "チェックボックスをクリックしたとき",
		"defaultExpandedkeys": "デフォルトで展開されたノード",
		"defaultExpandedkeysNote": "デフォルトで展開されたノードのキー配列を返します。例：return ['2', '4']",
		"showCheckbox": "選択を許可",
		"defaultCheckedKeysNote": "デフォルトでチェックされたノードのキー配列を返します。例：return ['2', '4']",
		"defaultCheckedkeys": "デフォルトでチェックされたノード",
		"accordion": "同じレベルのノードを展開するときに常に1つだけ展開",
		"indent": "各レベルのインデント",
		"dragdrop": "ドラッグアンドドロップ",
		"draggable": "ドラッグ可能",
		"allowDrag": "ノードをドラッグできるかどうかを判断",
		"allowDrop": "ドラッグ時に対象ノードをドロップできるかどうかを判断",
		"emptyText": "内容が空の場合に表示されるテキスト",
		"allowDragNote": "this.eventは渡されたノードです。'return true'はドラッグを許可します。",
		"allowDropNote": "this.eventを使用してデータ { draggingNode, dropNode, type } を取得できます。typeパラメータには 'prev'、'inner'、'next' の3つのタイプがあり、それぞれ対象ノードの前、対象ノード内、対象ノードの後にドロップされることを示します。'return true'は挿入を許可します。",
		"loadFun": "サブツリーデータのロードスクリプト",
		"loadFunNote": "this.event.nodeはクリックされたノードで、this.event.resolve(data)はデータロードが完了した後に呼び出されるコールバックです。dataパラメータはサブツリーデータです。",
		"dataScriptNote": "各ノードのフォーマットは次のとおりです。",
		"labelDescription": "ノードテキスト",
		"childrenDescription": "サブノード",
		"disabledDescription": "有効化された選択後に使用可能な現在の選択ボックスかどうか",
		"isLeafDescription": "ダイナミックロードが有効な場合に使用可能で、現在のノードがリーフノードかどうか（デフォルトでは矢印が表示されません）",
		"idDescription": "表示されなくてもかまいません。デフォルトの展開スクリプト、デフォルトの選択、デフォルトのチェック、およびスクリプト操作に必要な一意の識別子です。idまたは基本属性に設定されたキーを使用できます。",
		"settedKey": "設定されたキー",
		"customDescription": "その他のカスタムデータ",

        "selectStyle": "セレクトスタイル",
		"options": "選択肢",
		"optionScript": "選択肢スクリプト",
		"defaultOptionScript": "デフォルトの選択肢スクリプト",
		"divStyle": "コンテナスタイル",
		"buttonStyle": "ボタンスタイル",
		"extendOptions": "その他の選択肢",

		"dynamic": "ダイナミック",
		"canSelectCount": "選択可能な数",
		"showSeparator": "区切り記号を表示",
		"optionDynamicScript": "選択肢ダイナミックスクリプト",

		"handwriting": "手書き",
		"writingBoard": "手書きボード",
		"width": "幅",
		"height": "高さ",
		"recording": "録音",
		"writingPreview": "手書きプレビュー",
		"commonIdea": "一般的な意見",

		"addressStyle": "住所スタイル",

		"location": "位置",
		"right": "右",
		"left": "左",
		"relocate": "再配置",

		"image": "画像",
		"selectSrc": "リソースの選択",

		"imageCropping": "画像のトリミング",
		"unlimited": "制限なし",
		"fixedSize": "固定サイズ",
		"fixedRatio": "固定比率",
		"aspectRatio": "アスペクト比",

        "site": "サイト",
		"defaultSiteInfo": "（デフォルトはロゴと同じです）",
		"editInActivex": "ActiveXで編集",
		"activexId": "ActiveX識別子",
		"showType": "表示方法",
		"switchStyle": "切り替えスタイル",
		"allow": "許可",
		"notAllow": "許可しない",
		"uploadType": "アップロード可能なタイプ",
		"wordDoc": "WORDドキュメント",
		"excelDoc": "EXCELドキュメント",
		"pptDoc": "PPTドキュメント",
		"textDoc": "テキストドキュメント",
		"imgDoc": "画像ファイル",
		"pdfDoc": "PDFドキュメント",
		"zipDoc": "圧縮ファイル",
		"audioDoc": "オーディオファイル",
		"videoDoc": "ビデオファイル",
		"otherDoc": "その他",
		"docSample": "サンプル入力：.doc, .docx, .xls",
		"uploadSize": "アップロード許容サイズ（M）",
		"uploadSizeInfo": "「0」はアップロードサイズに制限がないことを意味します",
		"uploadCount": "アップロード許容回数",
		"uploadCountInfo": "「0」はアップロード回数に制限がないことを意味します",
		"changeSize": "サイズ変更",
		"useAttachmentStyle": "許可される添付スタイル",
		"list": "リスト",
		"sequence": "シーケンス",
		"preview": "プレビュー",
		"attDefaultStyle": "デフォルトの添付スタイル",
		"readonlyMode": "読み取り専用モード",
		"allowUpload": "アップロードを許可",
		"allowPreview": "プレビューを許可",
		"allowDownload": "ダウンロードを許可",
		"allowEdit": "編集を許可",
		"officeTool": "Officeプレビュー/編集ツール",
		"allowDelete": "削除を許可",
		"allowDelMyAtt": "本人がアップロードしたファイルのみ削除を許可",
		"allowDelCurActivityAtt": "現在のアクティビティのみ削除を許可",
		"allowDelMyCurActivityAtt": "本人が現在のアクティビティにアップロードしたファイルのみ削除を許可",
		"allowReplace": "置換を許可",
		"allowConfig": "権限設定を許可",
		"allowOrder": "並べ替えを許可",
		"dblClickAttachment": "添付ファイルをダブルクリック",
		"openAtt": "開く",
		"previewFirst": "プレビューを優先",
		"previewAttachmentNote": "以下のファイル形式は直接プレビューできます：zip、pdf、ofd、png、jpg、bmp、jpeg、gif、js、css、java、json、xml、php、html、htm、xhtml、log、md、txt。liberofficeをインストールする必要がある形式は次のとおりです：doc、docx、xls、xlsx、ppt、pptx。上記の形式に含まれないファイルはダブルクリックして直接開きます。",

        "actionBar": "アクションバー",
		"hideEditButton": "編集ボタン非表示",
		"hideReadButton": "読み取りボタン非表示",
		"hideLayoutButton": "レイアウトボタン非表示",
		"hideSettingButton": "設定ボタン非表示",
		"hideModeButton": "モードボタン非表示",
		"showInDatagrid": "データグリッドに表示（非推奨）",
		"attachmentValidation": "アップロード時の検証",
		"attachmentValidationNote": "this.target.uploadingFilesを使用して、現在アップロード中の添付ファイルを取得できます。trueを返すと合格、テキストを返すとシステムメッセージテキストを表示してアップロードが中断されます。",
		"attachmentValidationScript": "アップロード検証スクリプト",
		"hideEraserButton": "消しゴムボタン非表示",
		"hideEraserRadioButton": "消しゴムサイズボタン非表示",
		"hideSizeButton": "線の太さボタン非表示",
		"hideColorButton": "色ボタン非表示",
		"hideImageButton": "画像挿入ボタン非表示",
		"hideImageClipperButton": "画像クリップボタン非表示",
		"tableSize": "テーブルサイズ",
		"row": "行",
		"col": "列",
		"tableWidth": "テーブル幅",
		"pixel": "ピクセル",
		"percent": "パーセント",
		"borderWidth": "ボーダー幅",
		"cellpadding": "セル内余白",
		"cellspacing": "セル間隔",

        "containStyle": "コンテナスタイル",
		"containAttribute": "コンテナ属性",
		"titleCellStyle": "タイトルセルスタイル",
		"contentCellStyle": "コンテンツセルスタイル",
		"layoutCellStyle": "レイアウトセルスタイル",
		"contentTitleCellStyle": "コンテンツタイトルセルスタイル",
		"contentLineStyle": "コンテンツ行スタイル",
		"contentLineOverStyle": "コンテンツ行オーバースタイル",
		"columns": "列数",
		"onTheLeft": "選択したものの左",
		"onTheRight": "選択したものの右",
		"rows": "行数",
		"onTheTop": "選択したものの上",
		"onTheBottom": "選択したものの下",
		"type": "タイプ",
		"titleCell": "タイトルセル",
		"contentCell": "コンテンツセル",
		"layoutCell": "レイアウトセル",
		"other": "その他",
		"permission": "権限",

        "containerStyles": "コンテナスタイル",
		"tableAttribute": "テーブル属性",
		"border": "境界線",
		"backgroundColor": "背景色",
		"alternateRow": "交互行",
		"tableStyle": "テーブルスタイル",
		"defaultData": "デフォルトデータ",
		"allowAdd": "追加を許可",
		"allowSort": "ソートを許可",
		"exportImport": "エクスポートとインポート",
		"enabled": "有効",
		"disabled": "無効",
		"onlyExport": "エクスポートのみ",
		"onlyImport": "インポートのみ",
		"exportInfo": "注意：番号、画像、サインボード、添付ファイル、非表示の列はエクスポートおよびインポートできません。",
		"buttonLocation": "ボタンの位置",
		"centertop": "中央上",
		"centerbottom": "中央下",
		"importText": "インポートボタンのテキスト",
		"importExcel": "Excelをインポート",
		"exportExcel": "Excelをエクスポート",
		"importButtonStyle": "インポートボタンスタイル",
		"exportFileName": "エクスポートファイル名",
		"actionCellStyles": "アクションセルスタイル",
		"editCellStyles": "編集セルスタイル",
		"amountCellStyle": "合計セルスタイル",
		"itemTitleStyle": "アイテムタイトルスタイル（モバイル専用）",
		"canEdit": "編集可能かどうか",
		"exportText": "エクスポートボタンのテキスト",
		"exporButtonStyle": "エクスポートボタンスタイル",

        "content": "コンテンツ",
		"serialNumber": "シリアル番号",
		"total": "合計",
		"notNeeded": "不要",
		"totalValue": "合計値",
		"totalCount": "合計数",
		"showCol": "この列を表示",
		"hideCol": "この列を非表示",

		"delayedLoading": "遅延読み込み",
		"selectSubform": "サブフォームを選択",
		"calculationSubform": "サブフォーム計算",
		"subform": "サブフォーム",
		"subformScript": "サブフォームスクリプト",

		"activeType": "アクティブタイプ",
		"click": "クリックでアクティブ",
		"delay": "遅延でアクティブ",
		"immediately": "直ちにアクティブ",
		"buttonText": "ボタンテキスト",
		"delayNote": "遅延アクティブを選択した場合、this.form.get(moduleId).active()を使用してアクティブ化する必要があります",

        "viewBox": "ビューボックス",
		"viewBoxTitle": "選択ボックスのタイトル",
		"columnTitle": "列タイトル",
		"expandDefault": "デフォルトで展開",
		"expand": "展開",
		"collapse": "折りたたむ",
		"singleChoice": "単一選択",
		"multipleChoice": "複数選択",
		"view": "ビュー",
		"statement": "クエリ",
		"boxTitleStyle": "ボックスタイトルスタイル",
		"boxItemStyle": "ボックスアイテムスタイル",
		"selectResultProcessing": "選択結果処理",
		"resultProcessing": "処理方法",
		"assignValue": "値を割り当てる",
		"assignValueForResult": "選択結果の割り当て",
		"selectResult": "選択結果",
		"defaultSelectedLineScript": "デフォルトで選択された行のスクリプト",
		"allowSelectiLineScript": "行選択スクリプトを許可",
		"reserve": "予約",
		"changeViewReserve": "ビューを変更した後、元のビューデータを保持して再選択",
		"changeViewNotReserve": "ビューを変更した後、元のビューデータを削除して再選択",
		"filter": "フィルタ",
		"title": "タイトル",
		"path": "パス",
		"servicePath": "サービスパス",
		"servicePathNote" : "例：/jaxrs/user/hotpic/filter/list/page/1/count/6",
		"dataItemPath": "データアイテムのパス",
		"dataItemPathNote": "表示するデータのパス、ドットで区切られた複数のパスをサポート、例：data",
		"dataScriptNote2": "スクリプトはPromiseオブジェクトまたはデータを返す必要があります、例：return this.Actions.load('x_hotpic_assemble_control').HotPictureInfoAction.listForPage(1, 6);",
		"dataType": "データ型",
		"text": "テキスト",
		"number": "数値",
		"datetime": "日時",
		"boolean": "ブール",
		"resultType": "結果保存タイプ",
		"asDefaultFilter": "デフォルトのフィルタとして使用",
		"asCustomFilter": "カスタムフィルタデータとして使用",
		"logic": "ロジック",
		"and": "かつ",
		"or": "または",
		"compare": "比較",
		"equals": "等しい",
		"notEquals": "等しくない",
		"greaterThan": "より大きい",
		"greaterThanOrEqualTo": "以上",
		"lessThan": "未満",
		"lessThanOrEqualTo": "以下",
		"like": "一致",
		"notLike": "一致しない",
		"range": "範囲",
		"in": "含む",
		"true": "はい",
		"false": "いいえ",
		"filterValueInfo": "複数の値は半角カンマ(,)で区切ります",
		"defaultFilter": "デフォルトのフィルタ条件",
		"customFilter": "カスタムフィルタデータ",
		"filterCond": "フィルタ条件",
		"filterNote": "注意：ビューのフィルタ条件配列を返します、フォーマットについては参照してください",

        "titleStyle": "タイトルスタイル",
		"dataStyle": "データスタイル",
		"loadNow": "即時読み込み",
		"showTitle": "タイトル表示",
		"allowSelect": "ファイル選択を許可",

		"stat": "統計",
		"showChart": "グラフ表示",
		"showLegend": "凡例表示",
		"showTable": "表表示",
		"showRowToColumn": "行列変換",
		"chartNodeStyles": "グラフコンテナスタイル",
		"tableNodeStyles": "テーブルコンテナスタイル",

		"selectTag": "タグ選択",
		"elementTag": "要素タグ",
		"innerHtml": "内蔵HTML",

		"delayedTabInfo": "遅延読み込みが「はい」に設定されている場合、表示されていないタブページの内容は読み込まれず、タブページが初めて表示されるときにのみ内容が読み込まれます。",
		"tabContainerStyle": "タブコンテナスタイル",
		"contentContainerStyle": "コンテンツコンテナスタイル",
		"baseTabStyle": "基本タブスタイル",
		"baseTabSpanStyle": "基本タブフォントスタイル",
		"currentTabStyle": "現在のタブスタイル",
		"currentTabSpanStyle": "現在のタブフォントスタイル",

		"data": "データ",
		"treeAreaStyle": "ツリーエリアスタイル",
		"treeNodeStyle": "ツリーノードスタイル",
		"treeNodeFontStyle": "ツリーノードフォントスタイル",
		"treeSelectNodeFontStyle": "現在のツリーノードフォントスタイル",

        "record": "記録",
		"recordTable": "テーブル",
		"recordMedia": "マルチメディア（手書きまたは音声）",
		"expandHandwritten": "手書き意見を展開",
		"handwrittenWidth": "手書き意見の幅",
		"validOnPcSide": "（PC側で有効）",
		"handwrittenHeight": "手書き意見の高さ",
		"logFormat": "形式",
		"logFormatScript": "形式スクリプト",
		"logHtmlScript": "HTMLスクリプト",
		"currentPerson": "現在の担当者",
		"readReaded": "未読と既読",
		"readTitle": "未読タイトル",
		"readedTitle": "既読タイトル",
		"exactMatch": "完全一致",
		"filterActivity": "アクティビティのフィルタリング",
		"filterActivityAlias": "アクティビティのエイリアスのフィルタリング",
		"filterPerson": "担当者のフィルタリング",
		"filterRoute": "ルートのフィルタリング",
		"filterScript": "スクリプトによるフィルタリング",
		"activity": "アクティビティ",
		"opinionGroup": "意見グループ",
		"unitLevelName": "組織レベル名",
		"unitLevel": "組織レベル",
		"sortInCategory": "カテゴリ内で並べ替え",
		"sortByActivity": "アクティビティで並べ替え",
		"sortByTimeAsc": "時間の昇順で並べ替え",
		"sortByTimeDesc": "時間の降順で並べ替え",
		"noSort": "ソートなし",
		"categoryTable": "カテゴリテーブル",
		"categoryTableAttr": "カテゴリテーブル属性",
		"categoryTableStyle": "カテゴリテーブルスタイル",
		"categoryTitleCellStyle": "カテゴリタイトルセルスタイル",
		"categoryContentCellStyle": "カテゴリコンテンツセルスタイル",
		"categoryContentCellInnerStyle": "カテゴリコンテンツセル内部スタイル",
		"expandOrCollapse": "展開または折りたたむ",
		"defaultExpandCount": "デフォルトの展開項目数",
		"expandHtml": "展開ノードのHTML",
		"collapseHtml": "折りたたみノードのHTML",
		"relativedLinkField": "選択可能なフィールド：flag, title, createTime, updateTime, creatorPerson, creatorUnit, score",
		"documentListShow": "文書リストの表示",
		"associatedDocumentField": "選択可能なフィールド：targetTitle, targetStartTime, targetCreatorPersonCn, targetType, targetCategory",
		"associatedDocumentScriptNote": "\n this.lineを使用して現在のエントリデータを取得できます",

        "fileTemplate": "ファイルテンプレート",
		"systemTemplate": "システムテンプレート",
		"customTemplate": "カスタムテンプレート",
		"selectTemplate": "テンプレート選択",
		"templatePath": "テンプレートパス",
		"templateId": "テンプレートID",
		"edit": "編集",
		"printFile": "本文印刷",
		"viewTraces": "トレース表示",
		"viewTracesFullScreen": "トレースフルスクリーン",
		"viewTracesFullScreenInfo": "トレース表示時にフルスクリーン表示",
		"editScript": "スクリプト編集",
		"printScript": "印刷スクリプト許可",
		"viewTracesScript": "トレーススクリプト許可",
		"handwrittenApproval": "手書き承認",
		"handwrittenApprovalScript": "手書き承認スクリプト許可",
		"handwrittenApprovalType": "承認タイプ",
		"savetext": "本文保存（背景として）",
		"notsavetext": "本文保存しない",
		"handwrittenApprovalTypeInfo": "本文保存は、承認後にプロセス本文が変更される場合に適用されます",
		"zoom": "ズーム設定",
		"zoomInfo": "ユーザーがカスタムズーム比率を設定できるかどうか",
		"fullWidth": "全角変換",
		"fullWidthInfo": "「はい」を選択すると、半角スペースが自動的に全角に変換されます",
		"paragraphIndent": "段落インデント",
		"paragraphIndentInfo": "「はい」を選択すると、各段落の先頭行が自動的にインデントされます",
		"doublePage": "両面表示",
		"doublePageInfo": "両面表示を許可するかどうか",
		"fullScreen": "フルスクリーン",
		"fullScreenInfo": "フルスクリーン表示を許可するかどうか",
		"wordConversion": "WORD変換",
		"wordConversionType": "変換タイプ",
		"isConversionSeal": "印鑑変換",
		"wordConversionWithService": "サービスを使用",
		"fileName": "ファイル名",
		"fileSite": "添付ファイルサイト",
		"addPageNumber": "ページ番号追加",
		"addPageNumberInfo": "Word変換後にページ番号を追加するかどうか",
		"whenConversion": "変換タイミング",
		"onSubmit": "提出時",
		"onSave": "保存時",
		"conversionCondition": "変換条件",
		"alwaysConvert": "常に変換",
		"whenConditionsMet": "条件が満たされた場合に変換",
		"static": "固定",
		"wordConversionEncryption": "編集保護",
		"wordConversionEncryptionInfo1": "（OOXML方式のみ使用可能）",
		"wordConversionEncryptionInfo": "「はい」を選択した場合、変換後のファイルは編集保護され、変換されたWord文書のすべての編集が制限されます。",
		"wordEncryptionPasswordType": "パスワード",
		"toWordPasswordScript": "パスワードスクリプト",
		"wordEncryptionPasswordInput": "パスワード入力",
		"toWordPasswordScriptInfo": "パスワードとして使用する文字列を返します。注意：管理者または文書担当者など関係者は、このパスワードを知っている必要があります。それ以外の場合、変換後のファイルを解除できません。",

        "config": "設定",
		"copiesSecretPriority": "部数、等級、緊急度",
		"isShow": "表示",
		"copies": "部数",
		"auto": "自動",
		"showScript": "スクリプト表示",
		"bindValue": "バインディング値",
		"bindValueScript": "バインディング値スクリプト",
		"secret": "等級",
		"priority": "緊急度",
		"redHeader": "赤いヘッダー",
		"redLine": "赤いライン",
		"fileNo": "文書番号",
		"signer": "署名者",
		"subject": "文書タイトル",
		"editSubjectInfo": "タイトルの編集が許可されている場合、データのバインディングをしないでください。",
		"mainSend": "主宛先",
		"attachment": "添付",
		"attachmentText": "添付ファイル内容",
		"attachmentInfor": "[ここをクリックして添付ファイル内容を編集]",
		"issuanceUnit": "作成組織",
		"issuanceDate": "作成日",
		"annotation": "注釈",
		"copyto": "参照",
		"copyto2": "送信",
		"editionUnit": "発行組織",
		"editionDate": "発行日",
		"meetingAttend": "会議出席",
		"meetingLeave": "会議欠席",
		"meetingSit": "会議出席",
		"meetingRecord": "会議記録",
		"customElement": "カスタムエレメントの設定",
		"subjectEditBindFormData": "データパスを同期",
		"fontFamily": "フォント",

        "autoCorrect": "自動訂正",
		"ckeditorInfo": "詳細なプロパティについては、こちらをご覧ください。",
		"ckeditorInfo2": "CKEditorのConfigオブジェクトを返し、エディタを初期化します。",
		"ckeditorInfo3": "詳細なイベントについては、こちらをご覧ください。",
		"tinymceInfo": "詳細なプロパティについては、こちらをご覧ください。",
		"tinymceInfo2": "TinyMCEのConfigオブジェクトを返し、エディタを初期化します。",
		"tinymceInfo3": "queryLoad、postLoad、load、およびafterLoadイベントはo2プラットフォームのイベントです。その他のイベントはTinyMCEエディタのイベントで、this.targetを使用してスクリプト環境を取得し、this.eventを使用してイベントオブジェクトを取得できます。詳細については、こちらをご覧ください。",
		"base64Encode": "画像をBase64エンコード",
		"imagePreview": "元画像をプレビュー",

        "ieOnly": "IEブラウザのみ対応",
		"keepHistory": "バージョン履歴を保持するか",
		"openAttachment": "添付ファイルの開閉を許可するか",
		"attachmentId": "添付ファイル表示識別子",
		"attachmentReadonly": "添付ファイル読み取り専用",
		"autoSave": "自動保存",
		"historyCount": "バージョン数を保持",
		"timeInterval": "時間間隔（分）",
		"showSummary": "コントロールが利用できない場合に要約を表示するか",
		"byTemplate": "テンプレートに基づいて作成",
		"readonlyCondition": "条件を満たす場合に読み取り専用",
		"officeFileSite": "ファイルのsiteを読み取り",
		"userTitle": "ユーザータイトル",
		"userId": "ユーザー識別子",
		"toolbar": "ツールバー",
		"tools": "ツール",
		"newDoc": "新しい文書",
		"openLocal": "ローカルファイルを開く",
		"saveLocal": "ローカルに保存",
		"traceSwitch": "トレース切り替え",
		"fullscreenMode": "フルスクリーンモード",
		"toolbarSwitch": "ツールバー切り替え",
		"printPreview": "印刷プレビュー",
		"redFileButton": "赤い縁取りボタン",
		"stampButton": "スタンプボタン",
		"showHistory": "バージョン履歴を表示",
		"showTitleBar": "タイトルバーを表示するか",
		"showMenuBar": "メニューバーを表示するか",
		"showToolBar": "ツールバーを表示するか",
		"showStatusBar": "ステータスバーを表示するか",
		"showZoom": "拡大/縮小を表示するか",
		"borderStyle": "ボーダースタイル",
		"borderColor": "ボーダーカラー",
		"flat": "フラット",
		"noCopy": "コピー禁止か",
		"keepTraces": "トレースを保持するか",
		"read": "読み取り",
		"otherAttr": "その他の属性",

        "querySelectBox": "クエリ選択ボックス",
		"selectBoxTitle": "選択ボックスのタイトル",
		"query": "クエリ",
		"pathInfo": "注意: パスの形式は「テーブルエイリアス.フィールド名」で、例: o.title です",
		"parameterNote": "注意: クエリステートメントおよび総数ステートメントのパラメータに対応します；\n例: \":field\"のwhere条件の場合、「field」を入力してください；\n例: \"?1\"のwhere条件の場合、「?1」を入力してください。",

		"source": "データソース",
		"method": "メソッド",
		"systemSource": "プラットフォームデータソース",
		"applicationService": "アプリケーションサービス",
		"parameter": "パラメータ",
		"requestBody": "リクエストボディ",
		"test": "テスト",
		"hostPort": "ホスト/ポート",

		"handle": "処理",

		"widget": "ウィジェット",
		"widgetScript": "ウィジェットスクリプト",
		"parameterScript": "パラメータスクリプト（オブジェクトを返す）",
		"insertWidget": "ウィジェット要素を挿入",
		"selectWidget": "ウィジェットを選択",
		"selectPortal": "ポータルを選択",
		"inDiv": "divで包むかどうか",

        "outerSideModuleId": "外部関連モジュールID",
		"addButtonId": "追加ボタンID",
		"deleteSelectedButtonId": "選択した項目の削除ボタンID",
		"selectAllModuleId": "すべて選択モジュールID",
		"selectedValue": "選択された値",
		"innerSideModuleId": "内部関連モジュールID",
		"deleteButtonId": "削除ボタンID",
		"sequenctModuleId": "シーケンスモジュールID",
		"selectModuleId": "選択モジュールID",
		"defaultShow": "デフォルト表示",
		"item": "項目",
		"maxItemCount": "最大追加数",
		"minItemCount": "最小保持数",
		"dtImportInfor": "注意: 画像、添付ファイル、データテーブル、サブデータテンプレートはインポートおよびエクスポートできません。",
		"importButtonId": "インポートボタンID",
		"exportButtonId": "エクスポートボタンID",
		"importExporConfig": "インポートとエクスポートフィールドの設定",
		"validationPopFormConfig": "バリデーションポップアップフォームの設定",
		"validationPopFormHeight": "ポップアップフォームの高さ",
		"validationPopFormWidth": "ポップアップフォームの幅",
		"validationTableStyle": "バリデーションテーブルスタイル",
		"validationTitleTdStyle": "バリデーションタイトルセルスタイル",
		"validationContentTdStyle": "バリデーションコンテンツセルスタイル",
		"validationTableAttribute": "バリデーションテーブル属性",
		"count": "カウント",
		"import": "インポート",
		"datatableEditMode": "編集モード",
		"datatableEditModeValue": ["毎回単一行を編集", "同時に複数行を編集"],
		"onlyPc": "PCでのみ使用可能",

        "size": "サイズ",
		"color": "カラー",
		"el_bt_default": "デフォルトボタン",
		"el_bt_primary": "プライマリボタン",
		"el_bt_success": "成功ボタン",
		"el_bt_warning": "警告ボタン",
		"el_bt_danger": "危険ボタン",
		"el_bt_info": "情報ボタン",
		"el_bt_text": "テキストボタン",

		"el_plain": "プレーンボタン",
		"el_round": "角丸ボタン",
		"el_circle": "サークルボタン",
		"el_icon": "アイコン",
		"el_disabled": "無効",
		"el_loading": "読み込み中",
		"el_autofocus": "自動フォーカス",
		"el_isText": "テキスト表示",

		"layout": "レイアウト",
		"layoutCode": "レイアウトコード",
		"layoutTemplate": "一般的なレイアウト",

		"elGroupStyles": "グループスタイル",
		"elGroupProperties": "グループプロパティ",

		"el_border": "ボーダー表示",
		"el_radioColor": "フォントカラー",
		"el_radioFillColor": "塗りつぶしカラー",
		"el_buttonRadio": "ボタンモード",


        "datatemplateOuterNote": "注：現在のデータテンプレートの外部にある関連するコンポーネント識別子です。データテンプレートは多層になる場合があり、外部コンポーネント識別子は次の規則に従って記入します：<br/>" +
			"1. 単層または最上位のデータテンプレートの場合、「fieldId」を記入して、フォーム上の直接コンポーネントを表します。<br/>" +
			"2. 複数層のデータテンプレートがある場合、「./fieldId」は現在のデータテンプレートと同じレベルのコンポーネントを表し、「../fieldId」は前のレベルのデータテンプレートと同じレベルのコンポーネントを表します。 これを続けてください。<br/>" +
			"3. 複数層のデータテンプレートがある場合、「datatemplateId.*.datatemplateId2.*.fieldId」を使用してフルレベルパスを示すこともできます。 datatemplateIdは最初のレベルのデータテンプレートのIDで、datatemplateId2は2番目のレベルのIDです。",
		"datatemplateInnerNote": "注：現在のデータテンプレート内部にある関連するコンポーネント識別子です。単一または複数の層のデータテンプレートに関係なく、コンポーネントの識別子を直接入力します。",
		"importModel": "インポートモデル",
		"enable": "有効",
		"disable": "無効",
		"downloadTempalte": "テンプレートのダウンロード",
		"downloadTempalteId": "テンプレートのダウンロードコンポーネント識別子",
		"downloadTempalteIdNote": "フォームにコンポーネントを作成し、ここにコンポーネント識別子を入力することができます。システムはこのコンポーネントのノード(node)にテンプレートのダウンロードクリックイベントをバインドします。",
		"province": "県",
		"city": "県市",
		"county": "県市区",
		"useTextFieldNote": "注：テキストコンポーネントの使用をお勧めします。",
		"useChecboxNote": "注：複数選択コンポーネントの使用をお勧めします。",
		"checkboxValueNote": "注：選択したコンポーネントに対応する値です。",
		"checkboxValueAllNote": "注：すべての選択コンポーネントに対応する値です。",
		"notShow": "非表示",
		"insertDataTemplate": "データテンプレートの挿入",
		"widthModules": "関連するコンポーネントを含めて挿入",
		"ckeditConfig": "エディタの設定",
		"ckeditConfigInfor": "エディタの設定を返すJSONオブジェクトです。",
		"ckeditConfigInfor1": "エディタのツールバー機能を構成する方法については、次のリンクをご覧ください：",
		"ckeditConfigInfor2": "../o2_lib/htmleditor/ckeditor4161/samples/toolbarconfigurator/index.html",
		"ckeditConfigInfor3": "ここをクリックしてください",
		"ckeditConfigInfor4": "詳細な設定については、Ckeditorの公式ウェブサイトを参照してください。",
		"ckeditConfigInfor5": "https://ckeditor.com/ckeditor-4/",
		"ckeditConfigInfor6": "注意：エディタのプロパティをカスタマイズした場合、文書のフォーマットが国家の政府および政府文書のフォーマットスタンダードを満たさなくなる可能性があります。",

        "showRead": "未読表示",
		"password": "パスワード",
		"search": "検索",
		"email": "メール",
		"datetime-local": "日時",
		"month": "月",
		"date": "日付",
		"time": "時間",
		"week": "週",
		"textarea": "複数行テキスト",
		"wordNumber": "文字数統計",
		"maxlength": "最大長",
		"clearable": "クリア可能",
		"showPassword": "パスワード切り替えアイコン表示",
		"prefixIcon": "前置アイコン",
		"suffixIcon": "後置アイコン",
		"textareaRows": "複数行テキスト行数",
		"autosize": "高さ自動調整",
		"minRows": "最小行数",
		"maxRows": "最大行数",
		"resize": "リサイズ",
		"resizeNone": "許可しない",
		"resizeBoth": "許可する",
		"resizeHorizontal": "水平方向",
		"resizeVertical": "垂直方向",
		"el_placement": "ポップアップ位置",
		"popperClass": "リストクラス",
		"triggerOnFocus": "アクティブ時に入力提案を表示",
		"itemScriptInfo": "入力提案を提供する関数を返します。Function(queryString, callback)",
		"multiple": "複数選択可能",
		"collapseTags": "タグを結合",
		"multipleInfo": "複数選択が可能な場合に有効",
		"filterable": "検索を許可",
		"filterMethod": "カスタム検索メソッド",
		"filterRemote": "リモート検索",
		"allowCreate": "新しい項目を作成",
		"noMatchText": "一致なしテキスト",
		"noDataText": "データなしテキスト",
		"loadingText": "読み込み中テキスト",
		"remoteMethod": "リモート検索メソッド",
		"multipleLimit": "最大選択可能数",

        "max": "最大値",
		"min": "最小値",
		"step": "刻み幅",
		"step_strictly": "刻み幅の倍数のみ入力可能",
		"precision": "数値精度",
		"controls": "コントロールボタン",
		"controlsPosition": "ボタンの位置",

        "activeText": "テキストを開く",
		"inactiveText": "テキストを閉じる",
		"activeColor": "アクティブな色",
		"inactiveColor": "非アクティブな色",
		"activeIconClass": "アクティブなアイコン",
		"inactiveIconClass": "非アクティブなアイコン",
		"activeValue": "アクティブな値",
		"inactiveValue": "非アクティブな値",
		"valueType": "値のタイプ",
		"showInput": "入力欄を表示",
		"showInputControls": "入力欄のコントロールを表示",
		"inputSize": "入力欄のサイズ",
		"sliderRange": "範囲選択",
		"sliderVertical": "縦向きモード",
		"sliderMarks": "マーク表示",
		"showTooltip": "ツールチップを表示",
		"tooltipClass": "ツールチップクラス",
		"formatTooltip": "ツールチップのフォーマット",
		"formatTooltipScript": "フォーマット関数を返します:",
		"showStops": "中断点を表示するかどうか",
		"marksScriptInfo": "オブジェクトを返します。キーは数値で、[min, max]の範囲内でなければならず、各マークを個別にスタイル指定できます",
		"optionsGroup": "オプショングループ",
		"selectItemScriptInfo": "選択可能な値の配列リストを返すか、選択可能な値の配列を解決(resolve)したPromiseオブジェクトを返します",
		"selectTemplete": "カスタムオプションテンプレート",
		"showAllLevels": "全ての階層を表示",
		"checkStrictly": "親子ノードを連動しない",
		"checkStrictlyInfo": "親子ノード間の連動を厳密に守るかどうか",
		"emitPath": "完全な配列を返す",
		"emitPathInfo": "選択ノードが変更されたとき、そのノードが属するすべての階層メニューの値で構成された配列を返すか、falseに設定すると選択ノードの値のみを返します",
		"lazy": "ダイナミックロード",
		"lazyLoadScript": "ダイナミックロードメソッド",
		"props_value": "オプションの値プロパティ",
		"props_label": "オプションのラベルプロパティ",
		"props_children": "サブオプションプロパティ",
		"props_disabled": "オプションの無効プロパティ",
		"props_leaf": "リーフノードフラグプロパティ",
		"expandTrigger": "展開トリガー",
		"beforeFilter": "フィルター前",
		"filterMethodInfo": "Functionを返し、カスタム検索ロジックを実装します。第1引数はノード(node)で、第2引数は検索キーワード(keyword)です。ブール値を返して一致を示します",
		"beforeFilterInfo": "Functionを返し、フィルタリング前のフックです。引数は入力値で、falseを返すか、Promiseを返して拒否された場合、フィルタリングを停止します",
		"lazyLoadScriptInfo": "ダイナミックデータのロードメソッド、lazyがtrueの場合にのみ有効; function(node, resolve)を返し、nodeは現在クリックしたノードで、resolveはデータのロードが完了したコールバックです（必ず呼び出す必要があります）",
		"firstPageNumber": "最初のページ番号",

        "showOptions": "オプション表示",
		"onInput": "入力時",
		"onFocus": "クリック時",
		"emptyValue": "空の値",
		"showZero": "ゼロを表示",
		"showNullString": "空文字列を表示",
		"centerServer": "センターサーバー",
		"pathConditions": "パスのデフォルト条件",
		"parameterConditions": "パラメータのデフォルト条件",
		"addDefaultConditionByPath": "パスでデフォルト条件を追加",
		"addDefaultConditionByParameter": "パラメータでデフォルト条件を追加",
		"placementValue": ["上中", "上左", "上右", "下中", "下左", "下右"],
		"trigger": "トリガー方式",
		"triggerValue": ["マウスオーバー", "マウスクリック"],
		"hideOnClick": "クリックでメニューを非表示",
		"showTimeout": "展開遅延時間",
		"hideTimeout": "折りたたみ遅延時間",
		"splitButton": "クリックとドロップダウンを同時に有効化",
		"splitButtonType": "ボタンの種類",
		"menuItem": "メニューアイテム",
		"dropdownDefaultText": "ドロップダウンメニュー",
		"showButton": "ボタンを表示",
		"countPerline": "行ごとのオプション数",
		"countPerlineNote": "0は制限なしを意味します",
		"返回json对象": "JSON オブジェクトを返す",

        "wps" : {
            "config": "設定",
			"options": "一般オプション",
			"topArea": "トップエリア",
			"show": "表示",
			"hide": "非表示",
			"headArea": "ヘッダーエリア",
			"showMode": "表示モード",
			"showMode_normal": "通常モード、すべての機能画面を表示",
			"showMode_simple": "シンプルモード、ヘッダーとツールバーを非表示",
			"wordConfig": "Word設定項目",
			"comment": "コメント",
			"isShowDocMap": "目次機能を有効にするかどうか",
			"isBestScale": "ドキュメントを開く際、デフォルトで最適な比率で表示（PC）",
			"isShowBottomStatusBar": "ボトムステータスバー（PC）",
			"isOpenIntoEdit": "モバイルで開く際、編集に入るかどうか",
			"component": "コンポーネント",
			"isComponent": "コンポーネントを有効にするかどうか（PC）",
			"HeaderLeft": "ヘッダーの左側",
			"HeaderRight": "ヘッダーの右側",
			"FloatQuickHelp": "右下のヘルプ（ゴールデンパンダ）",
			"HistoryVersion": "トップステータスバー - 履歴メニュー - 履歴バージョン",
			"HistoryRecord": "トップステータスバー - 履歴メニュー - 協力記録",
			"HistoryVersionDivider": "テーブル - 右クリックメニュー - 履歴バージョン/協力記録の区切り線",
			"TabPrintPreview": "トップツールバー印刷ボタン",
			"MenuPrintPreview": "その他メニュー印刷ボタン",
			"ReviewTrackChanges": "編集、変更ステータスボタン",
			"TrackChanges": "編集、変更ステータスドロップダウンオプション",
			"ContextMenuConvene": "テキスト右クリックでオンラインサポーターを呼び出す",
			"isComponentMobile": "コンポーネントを有効にするかどうか（モバイル）",
			"Logo": "ステータスバーのロゴ",
			"Cooperation": "ステータスバーの共同プロフィール写真",
			"More": "ステータスバーのその他ボタン",
			"SendButton": "トップツールバーの共有ボタン",
			"CooperHistoryMenuItem": "トップツールバーの協力記録メニュー",
			"WriterHoverToolbars": "テキスト-ボトムツールバー",
			"ReadSetting": "テキスト-ステータスバー-読書設定"
        },
        "onlyoffice" : {
            "config": "設定",
			"moduleConfig": "機能設定",
			"autosave": "自動保存",
			"chat": "チャットを有効にする",
			"comments": "コメントを有効にする",
			"compatibleFeatures": "旧バージョンとの互換性",
			"plugins": "プラグインを有効にする",
			"reviewDisplay": "レビュー表示モード",
			"reviewDisplay_markup": "マークアップ",
			"reviewDisplay_final": "最終版",
			"reviewDisplay_original": "元のバージョン",
			"showReviewChanges": "変更履歴を表示",
			"trackChanges": "レビュー編集モードを有効にする",
			"spellcheck": "スペルチェック",
			"viewSet": "インターフェース設定",
			"compactHeader": "エディターヘッダーを非表示",
			"compactToolbar": "コンパクトツールバー",
			"feedback": "フィードバックの表示",
			"help": "ヘルプの表示",
			"toolbarHideFileName": "タイトルバーにファイル名を表示",
			"toolbarNoTabs": "トップツールバーにタブを表示しない",
			"unit": "スケール測定単位",
			"unit_cm": "センチメートル",
			"unit_pt": "ピクセル",
			"unit_inch": "インチ",
			"zoom": "デフォルトズーム",
			"hideRightMenu": "右側メニューを非表示",
			"individualization": "個人情報",
			"address": "住所",
			"mail": "メール",
			"info": "概要",
			"company": "会社名",
			"www": "ウェブサイト",
			"feedbackUrl": "フィードバックURL",
			"logoImg": "左上のロゴ（172x40）",
			"logoUrl": "ロゴURL"
        },
        "smartbi":{
            "select": "リソース選択",
			"displayToolbar": "ツールバー表示",
			"toolbarShow": "表示",
			"toolbarHide": "非表示",
			"displayLeftTree": "左側ツリー表示",
			"leftTreeShow": "表示",
			"leftTreeHide": "非表示"
        },
        "weeks": {
            "arr": ["月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日", "日曜日"]
        },
        "tabletWidth": "タブレット幅",
		"tabletHeight": "タブレット高さ",
		"tabletSizeNote": "PCでのみ有効で、モバイルでは横幅いっぱいに表示されます。",
		"tabletToolbarNote": "PCでのみ有効で、モバイルでは表示されません。",
		"editable": "編集可能",
		"firstDayOfWeek": "週の開始曜日",
		"disabledDate": "日付選択禁止",
		"disabledDateNote": "this.eventは渡された日付で、'return true'はその日付を選択できなくします。",
		"disabledDateScript": "日付選択禁止スクリプト",
		"selectableRangeNote": "選択可能な時間範囲を返します。例：'18:30:00 - 20:30:00'または['09:30:00 - 12:00:00', '14:30:00 - 18:30:00']",
		"selectableRangeScript": "時間選択可能範囲スクリプト",
		"placeholder": "プレースホルダーテキスト",
		"rangeSeparator": "範囲区切りテキスト",
		"startPlaceholder": "開始プレースホルダーテキスト",
		"endPlaceholder": "終了プレースホルダーテキスト",
		"arrowControl": "矢印を使用して時間を選択",
		"timeSelectType2": "時間選択タイプ",
		"isRange": "範囲",
		"fixedTimePoint": "固定された時間",
		"anyTimePoint": "任意の時間",
		"to": "から",
		"startTime": "開始時間",
		"endTime": "終了時間",
		"startDate": "開始日",
		"endDate": "終了日",
		"selectableRange": "選択可能な範囲",
		"endSelectableRange": "終了選択可能範囲",

        "initialIndex": "初期スライドインデックス",
		"autoplay": "自動切り替え",
		"interval": "切り替え間隔",
		"indicatorPosition": "インジケーターの位置",
		"indicatorPositionValue": ["内部", "外部", "なし"],
		"arrow": "矢印",
		"arrowValue": ["マウスオーバーで表示", "常に表示", "非表示"],
		"carouselTypeValue": ["デフォルト", "カード"],
		"loop": "ループするかどうか",
		"direction": "表示方向",
		"directionValue": ["水平", "垂直"],
		"hotpicture": "ホットポイント画像",
		"page": "ページ数",
		"filterParameter": "フィルターパラメータ",
		"selectComponent": "アプリケーションを選択",
		"calculationComponent": "パスを計算するアプリケーション",
		"component": "アプリケーション",
		"scriptComponentNote": "組織管理などのアプリケーションパスを返します。",
		"componentScript": "アプリケーションパススクリプト",
		"applicationOptions": "アプリケーションオプション",
		"applicationStatus": "アプリケーションステータス",
		"titleAddTo": "タイトル行に追加",
		"firstLine": "最初の行",
		"lastLine": "最後の行"
    },
    "smartbi": {
		"nosetup": "まず SmartBI アプリをインストールしてください",
		"txt": "SmartBI レポート"
	  },
	  "onlyoffice": {
		"nosetup": "まず OnlyOffice アプリをインストールしてください"
	  },
	  "wpsoffice": {
		"nosetup": "まず WpsOffice アプリをインストールしてください"
	  },
	  "officeonline": {
		"nosetup": "まず OfficeOnline アプリをインストールしてください"
	  },
    "actionBar": {
        "close": "閉じる",
		"closeTitle": "文書を閉じる",
		"save": "保存",
		"saveTitle": "文書を保存",
		"flow": "継続的な流れ",
		"flowTitle": "文書の継続的な流れ",
		"reroute": "再ルーティング",
		"rerouteTitle": "文書の再ルーティング",
		"reset": "担当者リセット",
		"resetTitle": "担当者リセット",
		"split": "ブランチを追加",
		"splitTitle": "ブランチを追加",
		"retract": "撤回",
		"retractTitle": "タスクの撤回",
		"rollback": "プロセスの巻き戻し",
		"rollbackTitle": "指定されたステップに巻き戻し、プロセス履歴を削除しない",
		"delete": "文書削除",
		"deleteTitle": "ファイルを削除",
		"print": "印刷",
		"printTitle": "文書を印刷",
		"press": "対処促進",
		"pressTitle": "対処促進",
		"pause": "保留",
		"pauseTitle": "タスクを保留",
		"resume": "保留解除",
		"resumeTitle": "保留状態からの復帰",
		"downloadAll": "一括ダウンロード",
		"downloadAllTitle": "一括ダウンロード",
		"monitor": "プロセス監視",
		"monitorTitle": "プロセス監視",
		"setReaded": "既読としてマーク",
		"readed": "既読",
		"addTask": "タスク追加",
		"addTaskTitle": "現在のアクティビティに担当者を追加",
		"goBack": "戻る",
		"goBackTitle": "過去のアクティビティに戻る"
    },
    "filedConfigurator": {
		"sequence": "シーケンス",
		"fieldTitle": "フィールドタイトル",
		"fieldId": "フィールドID",
		"action": "アクション",
		"moveup": "前の行に移動",
		"deleteRow": "行を削除",
		"insertRow": "行を挿入",
		"importFromForm": "画面からフィールド設定をインポート"
    }
};
