MWF.xApplication.process.FormDesigner.LP = {
		"title": "양식 편집",
		"newForm": "새 양식",
		"property": "속성",
		"tools": "도구",
		"all": "모두",
		"repetitionsId": "반복 구성 요소 식별자",
		"notNullId": "구성 요소 식별자는 비워 둘 수 없습니다.",
		"notNumberId": "구성 요소 식별자는 숫자만으로 구성될 수 없습니다.",
		"notDoubleDotId": "구성 요소 식별자에 연속된 두 개의 점이 포함될 수 없습니다.",
		"notSpecialCharacterId": "구성 요소 식별자에 다음 문자를 포함할 수 없습니다 : !{}<>,;'\"",
		"history": "히스토리",
		"componentTree": "구성 요소 트리",
		"invalidElementUIId": "Element 구성 요소 데이터에 양방향 바인딩이 필요하므로 식별자는 다음과 같은 구성 항목과 중복되지 않도록 해야 합니다 :",
		"button": {
			"ok": "확인",
			"cancel": "취소"
		},
        "version" : {
            "title": "양식 버전 기록 보기",
			"close": "닫기",
			"no": "일련번호",
			"updateTime": "업데이트 시간",
			"op": "조작",
			"person": "업데이트한 사람",
			"resume": "복원",
			"resumeConfirm": "복원 확인",
			"resumeInfo": "양식을 복원하시겠습니까? 복원을 확인하면 현재 양식이 업데이트되며 현재 양식을 수동으로 저장해야 적용됩니다.",
			"resumeSuccess": "복원 성공"
        },
		"notice": {
			"save_success": "양식 저장 성공!",
			"saveTemplate_success": "양식 템플릿 저장 성공!",
			"saveTemplate_inputName": "템플릿 제목을 입력하세요",
			"saveTemplate_inputCategory": "템플릿 카테고리를 확인하세요",
			"deleteElementTitle": "양식 요소 삭제 확인",
			"deleteElement": "현재 요소 및 하위 요소를 삭제하시겠습니까?",
			"deleteRowTitle": "표 행 삭제 확인",
			"deleteRow": "현재 행을 삭제하면 해당 행의 모든 셀 내용이 삭제됩니다. 현재 선택한 행을 삭제하시겠습니까?",
			"deleteColTitle": "표 열 삭제 확인",
			"deleteCol": "현재 열을 삭제하면 해당 열의 모든 셀 내용이 삭제됩니다. 현재 선택한 열을 삭제하시겠습니까?",
			"deleteEventTitle": "이벤트 삭제 확인",
			"deleteEvent": "현재 이벤트를 삭제하시겠습니까?",
			"deleteActionTitle": "작업 삭제 확인",
			"deleteAction": "현재 작업을 삭제하시겠습니까?",
			"deleteButtonTitle": "버튼 삭제 확인",
			"deleteButton": "현재 작업 버튼을 삭제하시겠습니까?",
			"notUseModuleInMobile": "모바일에서는 이 모듈을 사용할 수 없습니다.",
			"changeToSequenceTitle": "확인",
			"changeToSequence": "이 작업은 이미 추가된 구성 요소를 삭제할 것이며, '일련 번호' 열로 변경하시겠습니까?"
		},

		"formAction": {
			"insertRow": "행 삽입",
			"insertCol": "열 삽입",
			"deleteRow": "행 삭제",
			"deleteCol": "열 삭제",
			"mergerCell": "셀 병합",
			"splitCell": "셀 분할",
			"move": "이동",
			"copy": "복사",
			"delete": "삭제",
			"add": "추가",
			"cut": "잘라내기",
			"paste": "붙여넣기",
			"open": "열기",
			"script": "스크립트",
			"create": "생성",
			"mergeCell": "셀 병합",
			"styleBrush": "스타일 브러시",
			"insertTop": "맨 위에 삽입",
			"insertBottom": "맨 아래에 삽입",
			"insertBefore": "앞에 삽입",
			"insertAfter": "뒤에 삽입",
			"injectNotice": "Ctrl 키를 누른 채로 마우스를 놓아 정확한 위치로 이동",
			"selectedContainer": "부모 객체 선택",
			"property": "속성",
			"batchModify": "일괄 수정"
		},

        "actionbar": {
            "readhide": "읽을 때 표시 여부 설정",
			"edithide": "편집 중 표시 여부 설정",
			"hideCondition": "숨김 조건 설정",
			"title": "제목",
			"img": "아이콘",
			"action": "작업",
			"condition": "표시 조건",
			"editScript": "작업 스크립트 편집",
			"editCondition": "숨김 조건 편집 (true 반환하면 작업 숨김)",
			"up": "위로 이동",
			"property": "속성",
			"addCustomTool": "사용자 지정 작업 추가",
			"delete": "삭제",
			"setProperties": "작업 속성 설정",
			"restoreDefaultTool": "삭제한 시스템 작업 복원",
			"selectDefaultTool": "시스템 작업 선택",
			"setReaded": "읽음으로 표시",
			"readed": "읽음"
        },
        "isSave": "저장 중입니다. 잠시 기다려주세요...",
		"scriptIncluder": {
			"yes": "예",
			"no": "아니요",
			"selectScript": "스크립트 선택:",
			"repeatAddScriptNotice": "스크립트를 중복으로 추가하지 마십시오.",
			"selectScriptNotice": "먼저 스크립트를 선택하십시오.",
			"asyncLoad": "비동기 로드:",
			"asyncLoadScript": "비동기 로드 스크립트:",
			"syncLoadScript": "동기 로드 스크립트:",
			"delete_title": "로드 스크립트 취소 확인",
			"delete_text": "선택한 스크립트를 취소하시겠습니까?"
		},
        "dictionaryIncluder" : {
            "selectDictionary": "선택:",
			"repeatAddDictionaryNotice": "데이터 사전을 중복으로 추가하지 마십시오",
			"rootDictionaryExistNotice": "이미 해당 데이터 사전의 루트 경로가 추가되었습니다. 추가할 필요가 없습니다.",
			"parentDictionaryExistNotice": "이미 해당 데이터 사전의 상위 경로가 추가되었습니다. 추가할 필요가 없습니다.",
			"subDictionaryExistNotice": "이미 해당 데이터 사전의 하위 경로가 존재합니다. 먼저 삭제한 다음 추가하십시오.",
			"selectDictionaryNotice": "먼저 데이터 사전을 선택하십시오",
			"path": "경로:",
			"delete_title": "데이터 사전 로드 취소 확인",
			"delete_text": "선택한 데이터 사전의 로드를 취소하시겠습니까?"
        },
        "validation": {
            "validation": "유효성 검사",
			"anytime": "언제나",
			"decision": "결정 선택",
			"decisionName": "<결정 이름>",
			"value": "값",
			"length": "값 길이",
			"valueInput": "<값>",
			"isnull": "비어 있음",
			"notnull": "비어 있지 않음",
			"gt": "크다",
			"lt": "작다",
			"equal": "같음",
			"neq": "같지 않음",
			"contain": "포함",
			"notcontain": "포함하지 않음",
			"prompt": "알림",
			"add": "추가",
			"modify": "수정",
			"when": "때",
			"as": "으로",
			"inputDecisionName": "결정 이름을 입력하세요",
			"inputValue": "값을 입력하세요",
			"inputPrompt": "알림 내용을 입력하세요",
			"delete_title": "유효성 검사 내용 삭제 확인",
			"delete_text": "이 유효성 검사 항목을 삭제하시겠습니까?"
        },

    "datagrid" : {
		"import": "가져오기",
		"export": "내보내기"
    },

    "selectIcon": "아이콘 선택",
    "selectImage": "이미지 선택",
    "selectApplication": "애플리케이션 선택",
    "dutyInputTitle": "직책 매개 변수 추가",
    "dutyInput": "직책 \"{duty}\"의 조직을 확인하십시오.",
    "select": "선택",
    "empty": "비우기",

    "creatorUnit": "작성자 소속 조직",
    "currentUnit": "처리자 소속 조직",
    "selectUnit": "조직 선택",
    "scriptUnit": "스크립트 사용",

    "creatorCompany": "작성자 회사",
    "creatorDepartment": "작성자 부서",
    "currentCompany": "현재 회사",
    "currentDepartment": "현재 부서",

    "deleteDutyTitle": "직책 제거 확인",
    "deleteDutyText": "“{duty}” 직책을 제거하시겠습니까?",

    "saveTemplate": "템플릿으로 저장",
    "templateName": "템플릿 이름",
    "templateCategory": "템플릿 분류",
    "templateDescription": "템플릿 설명",
    "save": "저장",
    "cancel": "취소",
    "newCategory": "새 분류",
    "mustSelectFormStyle": "양식 스타일을 선택해야 합니다",
    "notValidJson": "잘못된 JSON 형식",
    "mustSelectDict": "데이터 사전을 먼저 선택하십시오",
    "mustSelect": "선택하세요",

    "imageClipper": "이미지 편집",

    "clearNoDomModuleTitle": "HTML 트리에 없는 구성 요소 설정 지우기",
    "clearNoDomModuleContent": "HTML 트리에 없는 구성 요소 설정을 지울까요? 삭제 후 저장하여 적용해야 합니다.",

    "refreshDatatemplateImpExpTitle": "필드 가져오기 확인",
    "refreshDatatemplateImpExpContent": "이 작업은 데이터 템플릿의 내부 구성 요소에서 필드를 가져옵니다. 이 작업을 수행하면 이전에 구성한 필드가 대체됩니다. 계속하시겠습니까?",
    "handWriting": "손으로 쓴 글",

    "filter": {
        "and": "그리고",
		"or": "또는",
		"equals": "동일",
		"notEquals": "동일하지 않음",
		"greaterThan": "크다",
		"greaterThanOrEqualTo": "크거나 같음",
		"lessThan": "작다",
		"lessThanOrEqualTo": "작거나 같음",
		"like": "일치",
		"notLike": "일치하지 않음",
		"from": "부터",
		"value": "값"
    },
    "mastInputPath": "데이터 경로를 입력하세요",
    "mastInputTitle": "제목을 입력하세요",
    "delete_filterItem_title": "필터 조건 삭제 확인",
    "delete_filterItem": "현재 필터 조건을 삭제하시겠습니까?",

    "subformNameConflictTitle": "하위 양식 필드 이름 충돌",
    "subformNameConflictInfor": "다음과 같은 하위 양식 필드 이름이 기존 양식과 충돌합니다:\n{name}",
    "subformConflictTitle": "하위 양식 삽입 오류",
    "subformConflictInfor": "동일한 하위 양식을 중복으로 삽입할 수 없습니다",

    "subformNestedTitle": "하위 양식 삽입 오류",
    "subformNestedInfor": "상호 중첩으로 하위 양식을 삽입할 수 없습니다",
    "checkSubformNestedError" : "선택한 하위 양식에 상호 중첩이 있는 경우 확인하십시오!",

    "checkSubformTitle": "양식 저장 확인",
    "checkFormSaveError": "양식을 저장할 수 없음, 이유는 다음과 같습니다:<br>",
    "checkSubformPcInfor": "PC 양식에 다음과 같은 하위 양식 필드 충돌이 있습니다:<br>{subform}<br>",
    "checkSubformMobileInfor": "Mobile 양식에 다음과 같은 하위 양식 필드 충돌이 있습니다:<br>{subform}",

    "implodeError": "가져올 데이터 형식이 잘못되었습니다",
    "implodeEmpty": "가져올 데이터를 편집란에 입력하십시오",
    "implodeConfirmTitle": "가져오기 확인",
    "implodeConfirmText": "가져온 데이터는 현재 페이지를 지우고 취소할 수 없으며, 가져오시겠습니까?",

    "design": "디자인",
    "script": "스크립",
    "html": "HTML",
    "css": "CSS",
    "byModule": "요소",
    "byPath": "유형",
    "events": "이벤트",
    "pageform": "페이지",
    "importO2": "O2 데이터에서 가져오기",
    "importHTML": "HTML에서 가져오기",
    "importOffice": "WORD 또는 EXCEL에서 가져오기",
    "importO2_infor": "O2 형식의 양식 데이터를 다음 편집기로 복사하십시오. (양식 또는 페이지 디자이너 도구 모음에서 '내보내기' 버튼을 사용하여 양식 데이터를 가져옵니다.)<br/>Ctrl+Alt+I를 눌러 데이터를 서식 지정할 수 있습니다.",
    "importHTML_infor": "HTML 데이터를 다음 편집기로 복사하십시오. Ctrl+Alt+I를 눌러 데이터를 서식 지정할 수 있습니다.",
    "importHTML_infor2": "CSS 데이터를 다음 편집기로 복사하십시오. Ctrl+Alt+I를 눌러 데이터를 서식 지정할 수 있습니다.",
    "importOffice_infor": "Word 또는 Excel 파일을 선택하십시오.",
    "import_ok": "가져오기",
    "import_cancel": "취소",
    "import_option1": "빈 셀에 입력란 추가",
    "import_option2": "빈 요소 제거",
    "implodeOfficeEmpty": "가져올 Word 또는 Excel 파일을 먼저 선택하십시오.",

    "scriptTitle": {
        "validationOpinion": "양식 의견 유효성 검사",
		"validationRoute": "양식 경로 유효성 검사",
		"validationFormCustom": "양식 검사",
		"defaultValue": "기본값",
		"validation": "검증 스크립트",
		"sectionByScript": "스크립트에 따른 섹션",
		"itemScript": "선택 가능한 값 스크립트",
		"iframeScript": "iframe 스크립트",
		"labelScript": "텍스트 값",
		"rangeKey": "조직 범위",
		"identityRangeKey": "신분 조직 범위",
		"unitRangeKey": "조직 선택 범위",
		"rangeDutyKey": "직무 범위",
		"exclude": "선택 제외 스크립트",
		"cookies": "데이터 소스 요청 쿠키",
		"requestBody": "데이터 소스 요청 본문",
		"jsonText": "데이터 텍스트",
		"dataScript": "트리 컨트롤 스크립트",
		"itemDynamic": "동적 옵션 스크립트",
		"defaultData": "데이터 그리드 기본값",
		"editableScript": "데이터 그리드 편집 가능 여부 스크립트",
		"config": "HTML 편집기 구성",
		"filterScript": "프로세스 기록 필터 스크립트",
		"readScript": "Office 읽기 전용 스크립트",
		"fileSite": "Office 파일 site 스크립트",
		"subformScript": "서브 폼 스크립트",
		"selectedScript": "뷰 선택 스크립트",
		"action.tools": "작업 버튼"
    },
    "copyed": "복사됨",
    "selectorButton": {
        "ok": "확인",
        "cancel": "취소"
    },
    "modules": {
        "label": "텍스트",
		"textfield": "텍스트 필드",
		"number": "숫자 필드",
		"org": "인사조직",
		"calendar": "날짜 선택",
		"textarea": "다중 텍스트",
		"select": "드롭다운",
		"radio": "라디오 버튼",
		"checkbox": "체크 박스",
		"combox": "콤보 박스",
		"opinion": "의견 상자",
		"button": "버튼",
		"Address": "주소",
		"Actionbar": "액션 바",
		"Sidebar": "사이드바",
		"image": "이미지",
		"imageclipper": "이미지 편집",
		"attachment": "첨부 파일",
		"div": "컨테이너",
		"table": "테이블",
		"datagrid": "데이터 그리드(비추천)",
		"datatable": "데이터 테이블",
		"datatemplate": "데이터 템플릿",
		"subform": "서브 폼",
		"ViewSelector": "뷰 선택",
		"view": "임베드 뷰",
		"stat": "임베드 통계",
		"html": "HTML",
		"common": "일반 요소",
		"tab": "탭",
		"tree": "트리",
		"log": "프로세스 기록",
		"monitor": "프로세스 모니터",
		"iframe": "Iframe",
		"documenteditor": "문서 편집기",
		"htmledit": "HTML 편집기",
		"office": "Office 컨트롤",
		"yozoOffice": "永中 컨트롤",
		"statementSelector": "쿼리 뷰 선택",
		"statement": "임베드 쿼리 뷰",
		"SmartBI": "SmartBI 보고서",

        "group_all": "모두",
		"group_form": "양식",
		"group_layout": "레이아웃",
		"group_process": "프로세스",
		"group_filetext": "파일 편집",
		"group_function": "기능",
		"group_element": "Element",

        "el_container": "레이아웃",
		"el_icon": "아이콘",
		"el_button": "버튼",
		"el_radio": "라디오 버튼",
		"el_checkbox": "체크박스",
		"el_select": "선택기",
		"el_input": "입력란",
		"el_autocomplete": "자동 완성란",
		"el_cascader": "계층 선택기",
		"el_number": "카운터",
		"el_switch": "스위치",
		"el_slider": "슬라이더",
		"el_time": "시간",
		"el_date": "날짜",
		"el_datetime": "날짜 및 시간",
		"el_rate": "평가",
		"el_colorpicker": "색상 선택",
		"el_tree": "트리",
		"el_dropdown": "드롭다운 메뉴",
		"el_carousel": "카루셀",
		"el-menu": "메뉴",
		"el_common": "일반",

		"importer": "데이터 가져오기",
		"readLog": "읽기 로그",
		"writingBoard": "글씨 판",
		"tinymceEditor": "Tinymce 편집기",
		"relatedLink": "관련 링크",
		"associatedDocument": "연관 문서"
    },
    "propertyTemplate": {
        "base": "기본",
		"event": "이벤트",
		"html": "HTML",
		"json": "JSON",
		"action": "작업",
		"select": "선택",

		"id": "식별자",
		"name": "이름",
		"description": "설명",
		"appearance": "외관 유형",
		"style": "스타일",
		"attribute": "속성",
		"imageStyle": "이미지 스타일",

		"hideSystemTools": "시스템 작업",
		"show": "표시",
		"hide": "숨김",
		"readed": "읽음",

        "category": "카테고리",
		"formStyle": "양식 스타일",
		"icon": "아이콘",
		"printForm": "양식 인쇄",
		"preloadScript": "사전로드 스크립트",
		"script": "스크립트",
		"dict": "데이터 사전",
		"dictName": "사전 이름",
		"dictPath": "데이터 경로",
		"valueKey": "값 속성 이름",
		"textKey": "텍스트 속성 이름",
		"valueColumn": "값 열",
		"textColumn": "텍스트 열",
		"dictKeyNote": "객체 배열을 반환하는 경우 값 속성 이름 또는 텍스트 속성 이름을 구성해야 함",
		"firstOptionEnable": "첫 번째 옵션 사용",
		"firstOption": "첫 번째 옵션",
		"copy": "복사",
		"paste": "붙여넣기",
		"language": "언어 팩",
		"languageScript": "언어 팩 스크립트 (S)",
		"languageInfo": "언어 정보를 포함하는 JSON 객체 반환; o2.language로 현재 언어 정보 가져오기",
		"SubmitUI": "제출 UI",
		"submit": "제출",
		"systemDefault": "시스템 기본값",
		"selectForm": "양식 선택",
		"computeForm": "계산 양식",
		"application": "응용 프로그램",
		"form": "양식",
        "crossApplication": "다른 애플리케이션 간 연동",
		"computeSubmitAnnotation1": "애플리케이션 이름, 별명, ID",
		"computeSubmitAnnotation2": "양식 이름, ID",
		"computeWidgetAnnotation2": "위젯 이름, ID",
		"thisApplication": "현재 애플리케이션",
		"submitFormScript": "양식 제출 스크립트",
		"flowActionScript": "작업 제출 (프로세스 계속 진행) 스크립트",
		"handwritingSetting": "필기 의견 설정",
		"enableHandwriting": "필기 의견 활성화",
		"handwritingWidth": "필기판 너비",
		"effectivePC": "PC에서만 유효",
		"handwritingHeight": "필기판 높이",
		"promptBoxFlow": "흐름 이후 팝업 표시",
		"yes": "예",
		"no": "아니오",
		"usedNewWindow": "새 브라우저 창에서만 사용",
		"promptLocation": "팝업 위치",
		"lefttop": "왼쪽 상단",
		"righttop": "오른쪽 상단",
		"leftbottom": "왼쪽 하단",
		"rightbottom": "오른쪽 하단",
		"center": "중앙",
        "prompt": "알림창",
		"notClose": "자동 닫기 비활성화",
		"closeInfo": "초 후 자동으로 닫힙니다",
		"afterFlow": "흐름 이후",
		"closeWindow": "창 닫기",
		"redirect": "리디렉션",
		"redirectScript": "리디렉션 주소 스크립트",
		"returnUrl": "리디렉션용 URL 반환",
		"check": "확인",
		"checkOpinion": "의견 확인",
		"checkRoute": "경로 확인",
		"checkFlow": "흐름 확인",
		"noEventInfo": "참고: 서브 폼으로 포함하는 경우 다음 이벤트는 실행되지 않습니다.",
		"none": "없음",
		"default": "기본",
		"byScript": "스크립트 기반",
		"byFormat": "형식 기반",
		"table": "테이블",
		"languageDefaultInfo": "시스템은 \"lp-\"+o2.language 이름의 데이터 사전(또는 스크립트)을 자동으로로드하여 언어 패키지로 사용합니다",
		"prefix": "접두사",
		"suffix": "접미사",
		"value": "값",
		"textValue": "고정 값",

        "showIcon": "아이콘 표시",
		"readonly": "읽기 전용",
		"AIInput": "AI 입력",
		"inputStyle": "입력 스타일",
		"itemStyle": "항목 스타일",
		"actionStyles": "액션 스타일",
		"imageStyles": "이미지 스타일",
		"compute": "계산",
		"create": "생성",
		"save": "저장",
		"linkStyles": "링크 스타일",

        "defaultValue": "기본값",
		"verificationScript": "검증 스크립트",
		"verificationLineScript": "단일 편집 완료 후 검증 스크립트",
		"section": "섹션",
		"enableSection": "섹션 활성화",
		"sectionBy": "섹션 기준",
		"handler": "담당자",
		"handlerUnit": "담당자 소속 조직",
		"activityId": "활동 ID",
		"splitValue": "분할 값",

        "enableSectionMerge": "섹션 병합 활성화",
		"showSectionKey": "섹션 키 표시",
		"editByMerge": "병합 편집 (섹션 키 삭제)",
		"sectionMergeSortScript": "정렬 스크립트",
		"sectionNodeStyles": "섹션 노드 스타일",
		"sectionKeystyles": "섹션 키 스타일",
		"sectionContentStyles": "섹션 내용 스타일",
		"mergeDisplay": "읽기 전용",
		"editCurrentSection": "편집 (현재 섹션 편집 허용)",
		"mergeEdit": "편집 (섹션 키 삭제 후 데이터 병합)",
		"sectionKey": "섹션 키",
		"sectionKeyScript": "섹션 키 스크립트",
		"textValue1": "텍스트 값",
		"mergeType": "병합 유형",
		"amountValue": "합계 값",
		"averageValue": "평균 값",
		"sectionMergeEditScript": "데이터 병합 스크립트",
		"sectionMergeReadHtmlScript": "표시 HTML 스크립트",
		"sectionMergeReadDataScript": "데이터 스크립트",
		"htmlScript": "HTML 스크립트",
		"dataScript": "데이터 스크립트",
		"bySection": "섹션별",
		"byModule": "모듈별",
		"totalRow": "총계 행",
		"sectionAmountCellStyle": "섹션 총계 셀 스타일",
		"showAllSection": "모든 섹션 표시",

        "rangeByDatetime": "날짜 및 시간 범위",
		"rangeByDateAndTime": "날짜 및 시간 범위",
		"rangeByDate": "날짜 범위",
		"rangeByTime": "시간 범위",
		"rangeByOhter": "기타",
		"enableDate": "유효한 날짜",
		"enableHours": "유효한 시간 범위",
		"enableMinutes": "유효한 분 범위",
		"enableSeconds": "유효한 초 범위",

        "decimal": "소수점",

		"showCard": "카드 표시",
		"allowInput": "입력 허용",
		"dataStructure": "데이터 구조",
		"complete": "완료",
		"simple": "간단",
		"separator": "구분 기호",
		"asyncMode": "비동기 모드",
		"asyncLoad": "비동기로 로드",

		"identity": "신분",
		"unit": "조직",
		"duty": "직책",
		"group": "그룹",
		"person": "개인",

        "defaultValueScript": "기본값 스크립트",
		"showText": "텍스트 표시",
		"showTextScript": "텍스트 표시 스크립트",
		"unitSelectConfig": "사용자 및 조직 선택 구성",
		"selectType": "선택 유형",
		"selectCount": "선택 수",
		"returnValue": "결과 반환",
		"readonlyScript": "읽기 전용 스크립트",

        "selectTypeInfo": "프로세스 처리에 참여하려면 신분을 선택하세요!",
		"selectTypeInfo2": "개인은 프로세스 처리에 참여할 수 없습니다!",
		"checkEmpower": "대기 승인 확인",
		"onlyCustom": "사용자 정의 옵션만 사용",
		"unitRange": "조직 범위",
		"allUnit": "모든 조직",
		"specifyUnit": "지정된 조직",
		"draftUnit": "기안자 소속 조직",
		"currentUnit": "현재 사용자 소속 조직",
		"inUnit": "직속 소속 조직",
		"levelIs": "단계",
		"levelUnit": "단위 조직",
		"unitTypeIs": "유형은",
		"deUnit": "의 조직",
		"expandNext": "하위 항목 펼치기",
		"selectUnit": "조직 선택",
		"formData": "양식 데이터",
		"dutyRange": "직무 범위",
		"all": "모든",
		"all2": "모두",
		"specifyDuty": "지정된 직무",
		"byUnit": "조직 별",
		"byDuty": "직무 별",
		"showLevel": "레벨 표시",
		"byDutyUnit": "직무가 소속된 조직 별",
		"byIdentityUnit": "신분이 소속된 조직 별",
		"selectDuty": "직무 선택",
		"customOption": "사용자 정의 옵션",
		"useScriptAddIdOrPerson": "스크립트를 사용하여 신분/개인 추가",
		"unitType": "조직 유형",
		"selectRange": "범위 선택",
		"specifyGroup": "지정된 그룹",
		"exclude": "제외",
		"excludeInfo": "스크립트를 작성하여 조직, 신분, 개인 및 그룹의 선택 범위에서 제외",
		"firstLevelSelectable": "첫 번째 레벨 선택 허용",

        "dateTime": "날짜 및 시간",
		"dateTime2": "날짜 및 시간",
		"dateOnly": "날짜만",
		"monthOnly": "월만",
		"yearOnly": "연도만",
		"timeOnly": "시간만",
		"weekOnly": "주차",
		"multidate": "다중 날짜",
		"datetimerange": "날짜 및 시간 범위",
		"daterange": "날짜 범위",
		"timerange": "시간 범위",
		"monthrange": "월 범위",
		"selectSecond": "초 선택 여부",
		"timeSelectType": "시간 선택 방식",
		"timeSelectType_slider" : "슬라이더",
		"timeSelectType_select" : "드롭다운",
		"format": "포맷",

        "rateTexts": "미흡, 부족, 보통, 우수, 탁월",
		"allowHalf": "반점 허용",
		"lowThreshold": "낮음-중간 한계 값",
		"lowThresholdNote": "참고: 값 자체가 낮은 점수로 분류됩니다",
		"highThreshold": "중간-높음 한계 값",
		"highThresholdNote": "참고: 값 자체가 높은 점수로 분류됩니다",
		"lowColor": "낮은 점수 색상",
		"mediumColor": "중간 점수 색상",
		"highColor": "높은 점수 색상",
		"voidColor": "미선택 색상",
		"disabledVoidColor": "읽기 전용일 때 미선택 색상",
		"showAfter": "뒷면에 표시",
		"showScore": "점수 표시",
		"textColor": "텍스트 색상",
		"textContent": "텍스트 내용",
		"showAlpha": "투명도 표시",
		"colorFormat": "색상 형식",

        "nodeKey": "노드 고유 식별자 키",
		"nodeKeyNote": "각 트리 노드에 대한 고유 식별자로 사용되는 속성으로, 전체 트리에서 고유해야 합니다.",
		"renderAfterExpand": "노드 확장 후 하위 노드 렌더링",
		"defaultExpandAll": "기본적으로 모든 노드 확장",
		"highlightCurrent": "현재 선택된 노드 강조 표시",
		"currentNodeKey": "현재 선택된 노드 키 값",
		"expandOnClickNode": "노드 클릭으로 확장",
		"clickNode": "노드 클릭 시",
		"clickArrow": "화살표 클릭 시",
		"checkOnClickNode": "노드 클릭으로 선택",
		"clickCheckbox": "체크박스 클릭 시",
		"defaultExpandedkeys": "기본적으로 확장된 노드",
		"defaultExpandedkeysNote": "기본으로 확장된 노드 키 배열을 반환합니다. 예: return ['2', '4']",
		"showCheckbox": "선택 허용",
		"defaultCheckedKeysNote": "기본으로 체크된 노드 키 배열을 반환합니다. 예: return ['2', '4']",
		"defaultCheckedkeys": "기본으로 체크된 노드",
		"accordion": "같은 레벨의 노드를 확장할 때 한 번에 하나만 확장",
		"indent": "각 수준의 들여쓰기",
		"dragdrop": "드래그 앤 드롭",
		"draggable": "드래그 가능",
		"allowDrag": "노드를 드래그할 수 있는지 확인",
		"allowDrop": "드래그할 때 대상 노드를 놓을 수 있는지 확인",
		"emptyText": "내용이 비어 있을 때 표시되는 텍스트",
		"allowDragNote": "this.event는 전달된 노드입니다. 'return true'는 드래그를 허용합니다.",
		"allowDropNote": "this.event를 사용하여 데이터 { draggingNode, dropNode, type }를 가져올 수 있습니다. type 매개변수에는 'prev', 'inner', 'next' 세 가지 유형이 있으며 각각 대상 노드 앞, 대상 노드 내 및 대상 노드 뒤에 놓임을 나타냅니다. 'return true'는 삽입을 허용합니다.",
		"loadFun": "하위 트리 데이터 로드 스크립트",
		"loadFunNote": "this.event.node는 클릭된 노드이며 this.event.resolve(data)는 데이터 로드 완료 후 호출되는 콜백입니다. data 매개변수는 하위 트리 데이터입니다.",
		"dataScriptNote": "각 노드에 대한 반환 및 형식은 다음과 같습니다:",
		"labelDescription": "노드 텍스트",
		"childrenDescription": "하위 노드",
		"disabledDescription": "활성화된 선택 후 사용 가능한 현재 선택란 여부",
		"isLeafDescription": "동적으로로드 가능한 활성화 후 현재 노드가 리프 노드인지 여부 (기본적으로 화살표가 표시되지 않음)",
		"idDescription": "기본적으로 확장 스크립트, 기본적으로 선택, 기본적으로 체크된 및 스크립트 작업에 필요한 고유 식별자입니다. id 또는 기본 속성에 설정된 키를 사용할 수 있습니다.",
		"settedKey": "설정된 키",
		"customDescription": "기타 사용자 정의 데이터",

        "selectStyle": "셀렉트 스타일",
		"options": "옵션",
		"optionScript": "옵션 스크립트",
		"defaultOptionScript": "기본 옵션 스크립트",
		"divStyle": "컨테이너 스타일",
		"buttonStyle": "버튼 스타일",
		"extendOptions": "기타 옵션",

		"dynamic": "동적 계산",
		"canSelectCount": "선택 가능한 개수",
		"showSeparator": "구분 기호 표시",
		"optionDynamicScript": "옵션 동적 스크립트",

		"handwriting": "필기",
		"writingBoard": "필기 보드",
		"width": "폭",
		"height": "높이",
		"recording": "녹음",
		"writingPreview": "필기 미리보기",
		"commonIdea": "일반 의견",

		"addressStyle": "주소 스타일",

		"location": "위치",
		"right": "오른쪽",
		"left": "왼쪽",
		"relocate": "다시 위치 지정",

		"image": "이미지",
		"selectSrc": "리소스 선택",

		"imageCropping": "이미지 자르기",
		"unlimited": "제한 없음",
		"fixedSize": "고정 크기",
		"fixedRatio": "고정 비율",
		"aspectRatio": "가로세로 비율",

        "site": "사이트",
		"defaultSiteInfo": "（기본적으로 로고와 동일함）",
		"editInActivex": "액티브엑스에서 편집",
		"activexId": "액티브엑스 식별자",
		"showType": "표시 형식",
		"switchStyle": "스위치 스타일",
		"allow": "허용",
		"notAllow": "허용 안 함",
		"uploadType": "허용 업로드 유형",
		"wordDoc": "워드 문서",
		"excelDoc": "엑셀 문서",
		"pptDoc": "PPT 문서",
		"textDoc": "텍스트 문서",
		"imgDoc": "이미지 파일",
		"pdfDoc": "PDF 문서",
		"zipDoc": "압축 파일",
		"audioDoc": "오디오 파일",
		"videoDoc": "비디오 파일",
		"otherDoc": "기타",
		"docSample": "예시 입력: .doc, .docx, .xls",
		"uploadSize": "업로드 허용 크기 (M)",
		"uploadSizeInfo": "“0”은 업로드 크기에 제한이 없음을 의미합니다.",
		"uploadCount": "업로드 허용 수량",
		"uploadCountInfo": "“0”은 업로드 수량에 제한이 없음을 의미합니다.",
		"changeSize": "크기 변경",
		"useAttachmentStyle": "허용된 첨부 스타일",
		"list": "목록",
		"sequence": "순서",
		"preview": "미리보기",
		"attDefaultStyle": "기본 첨부 스타일",
		"readonlyMode": "읽기 전용 모드",
		"allowUpload": "업로드 허용",
		"allowPreview": "미리보기 허용",
		"allowDownload": "다운로드 허용",
		"allowEdit": "편집 허용",
		"officeTool": "Office 미리보기/편집 도구",
		"allowDelete": "삭제 허용",
		"allowDelMyAtt": "본인 업로드 파일만 삭제 허용",
		"allowDelCurActivityAtt": "현재 활동 업로드 파일만 삭제 허용",
		"allowDelMyCurActivityAtt": "본인 업로드 및 현재 활동 파일만 삭제 허용",
		"allowReplace": "대체 허용",
		"allowConfig": "권한 설정 허용",
		"allowOrder": "정렬 허용",
		"dblClickAttachment": "첨부 파일 더블 클릭",
		"openAtt": "열기",
		"previewFirst": "미리보기 우선",
		"previewAttachmentNote": "다음 파일 형식은 직접 미리 보기할 수 있습니다: zip, pdf, ofd, png, jpg, bmp, jpeg, gif, js, css, java, json, xml, php, html, htm, xhtml, log, md, txt. 다음 형식은 liberoffice를 설치해야 합니다: doc, docx, xls, xlsx, ppt, pptx. 위 목록에 없는 형식은 더블 클릭하여 첨부 파일을 직접 엽니다.",

        "actionBar": "작업 표시줄",
		"hideEditButton": "편집 작업 그룹 숨기기",
		"hideReadButton": "읽기 작업 그룹 숨기기",
		"hideLayoutButton": "레이아웃 작업 그룹 숨기기",
		"hideSettingButton": "설정 작업 그룹 숨기기",
		"hideModeButton": "모드 작업 숨기기",
		"showInDatagrid": "데이터 그리드에서 표시 (사용하지 않음)",
		"attachmentValidation": "업로드 시 유효성 검사",
		"attachmentValidationNote": "this.target.uploadingFiles로 현재 업로드 중인 첨부 파일을 얻을 수 있습니다. true를 반환하면 통과하고, 텍스트를 반환하면 시스템 메시지 텍스트를 표시한 후 업로드가 중단됩니다.",
		"attachmentValidationScript": "업로드 유효성 검사 스크립트",
		"hideEraserButton": "지우개 버튼 숨기기",
		"hideEraserRadioButton": "지우개 크기 버튼 숨기기",
		"hideSizeButton": "선 굵기 버튼 숨기기",
		"hideColorButton": "색상 버튼 숨기기",
		"hideImageButton": "이미지 삽입 버튼 숨기기",
		"hideImageClipperButton": "이미지 클리퍼 버튼 숨기기",
		"tableSize": "테이블 크기",
		"row": "행",
		"col": "열",
		"tableWidth": "테이블 너비",
		"pixel": "픽셀",
		"percent": "퍼센트",
		"borderWidth": "테두리 두께",
		"cellpadding": "셀 여백",
		"cellspacing": "셀 간격",

        "containStyle": "컨테이너 스타일",
		"containAttribute": "컨테이너 속성",
		"titleCellStyle": "제목 셀 스타일",
		"contentCellStyle": "내용 셀 스타일",
		"layoutCellStyle": "레이아웃 셀 스타일",
		"contentTitleCellStyle": "내용 제목 셀 스타일",
		"contentLineStyle": "내용 행 스타일",
		"contentLineOverStyle": "내용 행 마우스 오버 스타일",
		"columns": "열 수",
		"onTheLeft": "선택한 항목 왼쪽",
		"onTheRight": "선택한 항목 오른쪽",
		"rows": "행 수",
		"onTheTop": "선택한 항목 위쪽",
		"onTheBottom": "선택한 항목 아래쪽",
		"type": "유형",
		"titleCell": "제목 셀",
		"contentCell": "내용 셀",
		"layoutCell": "레이아웃 셀",
		"other": "기타",
		"permission": "권한",

        "containerStyles": "컨테이너 스타일",
		"tableAttribute": "표 속성",
		"border": "테두리",
		"backgroundColor": "배경색",
		"alternateRow": "번갈아가는 행",
		"tableStyle": "표 스타일",
		"defaultData": "기본 데이터",
		"allowAdd": "추가 허용",
		"allowSort": "정렬 허용",
		"exportImport": "내보내기 및 가져오기",
		"enabled": "사용 가능",
		"disabled": "비활성화",
		"onlyExport": "내보내기 전용",
		"onlyImport": "가져오기 전용",
		"exportInfo": "참고: 번호, 이미지, 서명란, 첨부 파일 및 숨겨진 열은 가져오기 및 내보내기할 수 없습니다.",
		"buttonLocation": "버튼 위치",
		"centertop": "중앙 상단",
		"centerbottom": "중앙 하단",
		"importText": "가져오기 버튼 텍스트",
		"importExcel": "Excel 가져오기",
		"exportExcel": "Excel 내보내기",
		"importButtonStyle": "가져오기 버튼 스타일",
		"exportFileName": "내보내기 파일 이름",
		"actionCellStyles": "작업 셀 스타일",
		"editCellStyles": "편집 셀 스타일",
		"amountCellStyle": "합계 셀 스타일",
		"itemTitleStyle": "항목 제목 스타일 (모바일 전용)",
		"canEdit": "편집 가능 여부",
		"exportText": "내보내기 버튼 텍스트",
		"exporButtonStyle": "내보내기 버튼 스타일",

        "content": "콘텐츠",
		"serialNumber": "일련 번호",
		"total": "합계",
		"notNeeded": "불필요함",
		"totalValue": "합계 값",
		"totalCount": "합계 횟수",
		"showCol": "이 열 표시",
		"hideCol": "이 열 숨김",

		"delayedLoading": "지연로딩",
		"selectSubform": "하위 양식 선택",
		"calculationSubform": "하위 양식 계산",
		"subform": "하위 양식",
		"subformScript": "하위 양식 스크립트",

		"activeType": "활성화 방식",
		"click": "클릭 활성화",
		"delay": "지연 활성화",
		"immediately": "즉시 활성화",
		"buttonText": "버튼 텍스트",
		"delayNote": "지연 활성화를 선택한 경우 this.form.get(moduleId).active()를 사용하여 활성화해야 함",

        "viewBox": "뷰 박스",
		"viewBoxTitle": "선택 박스 제목",
		"columnTitle": "열 제목",
		"expandDefault": "기본 확장",
		"expand": "확장",
		"collapse": "축소",
		"singleChoice": "단일 선택",
		"multipleChoice": "다중 선택",
		"view": "보기",
		"statement": "질의",
		"boxTitleStyle": "박스 제목 스타일",
		"boxItemStyle": "박스 항목 스타일",
		"selectResultProcessing": "선택 결과 처리",
		"resultProcessing": "처리 방식",
		"assignValue": "할당",
		"assignValueForResult": "선택 결과 할당",
		"selectResult": "선택 결과",
		"defaultSelectedLineScript": "기본 선택된 라인 스크립트",
		"allowSelectiLineScript": "라인 선택 스크립트 허용",
		"reserve": "보존",
		"changeViewReserve": "뷰 변경 후 다시 선택하여 원래 뷰 데이터 보존",
		"changeViewNotReserve": "뷰 변경 후 다시 선택하여 원래 뷰 데이터 삭제",
		"filter": "필터",
		"title": "제목",
		"path": "경로",
		"servicePath": "서비스 경로",
		"servicePathNote" : "예: /jaxrs/user/hotpic/filter/list/page/1/count/6",
		"dataItemPath": "데이터 항목 경로",
		"dataItemPathNote": "표시할 데이터의 경로, 점으로 구분된 다중 경로 지원, 예: data",
		"dataScriptNote2": "스크립트는 Promise 개체 또는 데이터를 반환해야 합니다. 예: return this.Actions.load('x_hotpic_assemble_control').HotPictureInfoAction.listForPage(1, 6);",
		"dataType": "데이터 유형",
		"text": "텍스트",
		"number": "숫자",
		"datetime": "날짜 및 시간",
		"boolean": "부울",
		"resultType": "결과 저장 유형",
		"asDefaultFilter": "기본 필터로 사용",
		"asCustomFilter": "사용자 지정 필터 데이터로 사용",
		"logic": "논리",
		"and": "및",
		"or": "또는",
		"compare": "비교",
		"equals": "같음",
		"notEquals": "같지 않음",
		"greaterThan": "크다",
		"greaterThanOrEqualTo": "크거나 같음",
		"lessThan": "작다",
		"lessThanOrEqualTo": "작거나 같음",
		"like": "매치",
		"notLike": "매치하지 않음",
		"range": "범위",
		"in": "포함",
		"true": "예",
		"false": "아니요",
		"filterValueInfo": "여러 값을 쉼표(,)로 구분",
		"defaultFilter": "기본 필터 조건",
		"customFilter": "사용자 지정 필터 데이터",
		"filterCond": "필터 조건",
		"filterNote": "참고: 뷰의 필터 조건 배열 반환, 형식은 참조",

        "titleStyle": "제목 스타일",
		"dataStyle": "데이터 스타일",
		"loadNow": "즉시 로드",
		"showTitle": "제목 표시",
		"allowSelect": "파일 선택 허용",

		"stat": "통계",
		"showChart": "차트 표시",
		"showLegend": "범례 표시",
		"showTable": "테이블 표시",
		"showRowToColumn": "행열 전환",
		"chartNodeStyles": "차트 컨테이너 스타일",
		"tableNodeStyles": "테이블 컨테이너 스타일",

		"selectTag": "태그 선택",
		"elementTag": "요소 태그",
		"innerHtml": "내장 HTML",

		"delayedTabInfo": "지연 로드가 '예'로 설정된 경우 표시되지 않은 탭 페이지 내용을로드하지 않으며 탭 페이지가 처음으로 표시될 때 내용이로드됩니다.",
		"tabContainerStyle": "탭 컨테이너 스타일",
		"contentContainerStyle": "콘텐츠 컨테이너 스타일",
		"baseTabStyle": "기본 탭 스타일",
		"baseTabSpanStyle": "기본 탭 글꼴 스타일",
		"currentTabStyle": "현재 탭 스타일",
		"currentTabSpanStyle": "현재 탭 글꼴 스타일",

		"data": "데이터",
		"treeAreaStyle": "트리 영역 스타일",
		"treeNodeStyle": "트리 노드 스타일",
		"treeNodeFontStyle": "트리 노드 글꼴 스타일",
		"treeSelectNodeFontStyle": "현재 트리 노드 글꼴 스타일",

        "record": "기록",
		"recordTable": "표",
		"recordMedia": "멀티미디어(손글씨 또는 음성)",
		"expandHandwritten": "손글씨 의견 확장",
		"handwrittenWidth": "손글씨 의견 너비",
		"validOnPcSide": "(PC 측에서 유효함)",
		"handwrittenHeight": "손글씨 의견 높이",
		"logFormat": "형식",
		"logFormatScript": "형식 스크립트",
		"logHtmlScript": "HTML 스크립트",
		"currentPerson": "현재 처리자",
		"readReaded": "대기 읽음",
		"readTitle": "대기 제목",
		"readedTitle": "읽음 제목",
		"exactMatch": "정확한 일치",
		"filterActivity": "활동 필터링",
		"filterActivityAlias": "활동 별명 필터링",
		"filterPerson": "처리자 필터링",
		"filterRoute": "경로 필터링",
		"filterScript": "스크립트로 필터링",
		"activity": "활동",
		"opinionGroup": "의견 그룹",
		"unitLevelName": "조직 레벨 이름",
		"unitLevel": "조직 레벨",
		"sortInCategory": "카테고리 내 정렬",
		"sortByActivity": "활동별 정렬",
		"sortByTimeAsc": "시간순으로 정렬",
		"sortByTimeDesc": "시간 역순으로 정렬",
		"noSort": "정렬 없음",
		"categoryTable": "카테고리 테이블",
		"categoryTableAttr": "카테고리 테이블 속성",
		"categoryTableStyle": "카테고리 테이블 스타일",
		"categoryTitleCellStyle": "카테고리 제목 셀 스타일",
		"categoryContentCellStyle": "카테고리 내용 셀 스타일",
		"categoryContentCellInnerStyle": "카테고리 내용 셀 내부 스타일",
		"expandOrCollapse": "확장 또는 축소",
		"defaultExpandCount": "기본 확장 항목 수",
		"expandHtml": "확장 노드 HTML",
		"collapseHtml": "축소 노드 HTML",
		"relativedLinkField": "선택 가능한 필드: flag, title, createTime, updateTime, creatorPerson, creatorUnit, score",
		"documentListShow": "문서 목록 표시",
		"associatedDocumentField": "선택 가능한 필드: targetTitle, targetStartTime, targetCreatorPersonCn, targetType, targetCategory",
		"associatedDocumentScriptNote": "\n this.line을 사용하여 현재 항목 데이터를 가져올 수 있습니다.",

        "fileTemplate": "파일 템플릿",
		"systemTemplate": "시스템 템플릿",
		"customTemplate": "사용자 지정 템플릿",
		"selectTemplate": "템플릿 선택",
		"templatePath": "템플릿 경로",
		"templateId": "템플릿 식별자",
		"edit": "편집",
		"printFile": "본문 인쇄",
		"viewTraces": "추적 보기",
		"viewTracesFullScreen": "전체 화면 추적",
		"viewTracesFullScreenInfo": "추적 보기 시 전체 화면으로 표시",
		"editScript": "스크립트 편집",
		"printScript": "인쇄 스크립트 허용",
		"viewTracesScript": "추적 보기 스크립트 허용",
		"handwrittenApproval": "손글씨 승인",
		"handwrittenApprovalScript": "손글씨 승인 스크립트 허용",
		"handwrittenApprovalType": "승인 유형",
		"savetext": "본문 저장 (배경으로)",
		"notsavetext": "본문 저장 안 함",
		"handwrittenApprovalTypeInfo": "본문 저장은 승인 후 프로세스 본문이 수정되는 경우에 적용됩니다.",
		"zoom": "확대/축소 설정",
		"zoomInfo": "사용자 지정 확대/축소 비율 허용 여부",
		"fullWidth": "전각 변환",
		"fullWidthInfo": "예 선택 시 반각 공백을 자동으로 전각으로 변환합니다.",
		"paragraphIndent": "단락 들여쓰기",
		"paragraphIndentInfo": "예 선택 시 각 단락의 첫 줄을 자동으로 들여쓰기합니다.",
		"doublePage": "이중 페이지 표시",
		"doublePageInfo": "이중 페이지 표시 허용 여부",
		"fullScreen": "전체 화면",
		"fullScreenInfo": "전체 화면 표시 허용 여부",
		"wordConversion": "WORD 변환",
		"wordConversionType": "변환 방식",
		"isConversionSeal": "인장 변환",
		"wordConversionWithService": "서비스 사용",
		"fileName": "파일 이름",
		"fileSite": "첨부 파일 사이트",
		"addPageNumber": "페이지 번호 추가",
		"addPageNumberInfo": "Word로 변환한 후 페이지 번호를 추가할지 여부",
		"whenConversion": "변환 시점",
		"onSubmit": "제출 시",
		"onSave": "저장 시",
		"conversionCondition": "변환 조건",
		"alwaysConvert": "항상 변환",
		"whenConditionsMet": "조건 충족 시 변환",
		"static": "고정",
		"wordConversionEncryption": "편집 보호",
		"wordConversionEncryptionInfo1": "(OOXML 방식만 사용 가능)",
		"wordConversionEncryptionInfo": "예 선택 시 변환된 파일을 편집 보호로 제한하여 변환된 Word 문서를 모두 편집하지 못하도록 합니다.",
		"wordEncryptionPasswordType": "암호",
		"toWordPasswordScript": "암호 스크립트",
		"wordEncryptionPasswordInput": "암호 입력",
		"toWordPasswordScriptInfo": "암호로 사용할 문자열을 반환합니다. 관리자 또는 문서 작성자 등과 공유해야 암호를 알 수 있으며, 그렇지 않으면 변환된 파일을 해제할 수 없습니다.",

        "config": "설정",
		"copiesSecretPriority": "부수, 등급 및 긴급 정도",
		"isShow": "표시 여부",
		"copies": "부수",
		"auto": "자동",
		"showScript": "스크립트 표시",
		"bindValue": "바인딩 값",
		"bindValueScript": "바인딩 값 스크립트",
		"secret": "등급",
		"priority": "긴급 정도",
		"redHeader": "빨간 머리글",
		"redLine": "빨간 선",
		"fileNo": "문서 번호",
		"signer": "서명자",
		"subject": "문서 제목",
		"editSubjectInfo": "제목 편집이 허용되는 경우 데이터 바인딩을 하지 마십시오.",
		"mainSend": "주 송신",
		"attachment": "첨부",
		"attachmentText": "첨부 파일 내용",
		"attachmentInfor": "[여기를 클릭하여 첨부 파일 내용을 편집]",
		"issuanceUnit": "작성 기관",
		"issuanceDate": "작성일",
		"annotation": "비고",
		"copyto": "참조",
		"copyto2": "발송",
		"editionUnit": "발행 기관",
		"editionDate": "발행일",
		"meetingAttend": "회의 참석",
		"meetingLeave": "회의 결석",
		"meetingSit": "회의 출석",
		"meetingRecord": "회의록",
		"customElement": "사용자 정의 요소 설정",
		"subjectEditBindFormData": "데이터 경로 동기화",
		"fontFamily": "글꼴",

        "autoCorrect": "자동 수정",
		"ckeditorInfo": "더 많은 속성에 대한 도움말은 확인하세요.",
		"ckeditorInfo2": "CKEditor 구성 객체를 반환하여 에디터를 초기화합니다.",
		"ckeditorInfo3": "더 많은 이벤트에 대한 도움말은 확인하세요.",
		"tinymceInfo": "더 많은 속성에 대한 도움말은 확인하세요.",
		"tinymceInfo2": "TinyMCE 구성 객체를 반환하여 에디터를 초기화합니다.",
		"tinymceInfo3": "queryLoad, postLoad, load 및 afterLoad 이벤트는 o2 플랫폼 이벤트입니다. 다른 이벤트는 TinyMCE 에디터 이벤트이며, this.target을 통해 스크립트 환경을 얻을 수 있으며, this.event를 통해 이벤트 객체를 얻을 수 있습니다. 자세한 내용은 확인하세요.",
		"base64Encode": "이미지를 Base64로 인코딩",
		"imagePreview": "원본 이미지 미리 보기",

        "ieOnly": "IE 브라우저 전용",
		"keepHistory": "버전 기록 유지 여부",
		"openAttachment": "첨부 파일 열기 허용 여부",
		"attachmentId": "첨부 파일 표시 식별자",
		"attachmentReadonly": "첨부 파일 읽기 전용",
		"autoSave": "자동 저장",
		"historyCount": "버전 수 보존",
		"timeInterval": "시간 간격 (분)",
		"showSummary": "컨트롤 사용 불가능 시 요약 표시",
		"byTemplate": "템플릿 기반으로 생성",
		"readonlyCondition": "조건 충족 시 읽기 전용",
		"officeFileSite": "파일 사이트 읽기",
		"userTitle": "사용자 제목",
		"userId": "사용자 식별자",
		"toolbar": "도구 모음",
		"tools": "도구",
		"newDoc": "새 문서",
		"openLocal": "로컬 파일 열기",
		"saveLocal": "로컬에 저장",
		"traceSwitch": "추적 전환",
		"fullscreenMode": "전체 화면 모드",
		"toolbarSwitch": "도구 모음 전환",
		"printPreview": "인쇄 미리 보기",
		"redFileButton": "레드 테두리 버튼",
		"stampButton": "도장 버튼",
		"showHistory": "버전 기록 보기",
		"showTitleBar": "타이틀 바 표시 여부",
		"showMenuBar": "메뉴 바 표시 여부",
		"showToolBar": "도구 모음 표시 여부",
		"showStatusBar": "상태 표시줄 표시 여부",
		"showZoom": "확대/축소 표시",
		"borderStyle": "테두리 스타일",
		"borderColor": "테두리 색상",
		"flat": "플랫",
		"noCopy": "복사 금지 여부",
		"keepTraces": "추적 기록 유지 여부",
		"read": "읽기",
		"otherAttr": "기타 속성",

        "querySelectBox": "조회 선택 상자",
		"selectBoxTitle": "선택 상자 제목",
		"query": "쿼리",
		"pathInfo": "참고: 경로 형식은 \"테이블 별명.필드 이름\"으로 작성되며 예시: o.title",
		"parameterNote": "참고: 쿼리 문 및 총수 문의 매개변수와 대응됩니다;\n예: \":field\"의 where 조건의 경우 \"field\"를 입력하십시오;\n예: \"?1\"의 where 조건의 경우 \"?1\"를 입력하십시오.",

		"source": "데이터 소스",
		"method": "메서드",
		"systemSource": "플랫폼 데이터 소스",
		"applicationService": "서비스 응용 프로그램",
		"parameter": "매개변수",
		"requestBody": "요청 본문",
		"test": "테스트",
		"hostPort": "호스트/포트",

		"handle": "처리",

		"widget": "위젯",
		"widgetScript": "위젯 스크립트",
		"parameterScript": "매개변수 스크립트 (객체 반환)",
		"insertWidget": "위젯 요소 삽입",
		"selectWidget": "위젯 선택",
		"selectPortal": "포털 선택",
		"inDiv": "div 포장 여부",

        "outerSideModuleId": "외부 관련 컴포넌트 식별자",
		"addButtonId": "추가 버튼 식별자",
		"deleteSelectedButtonId": "선택한 항목 삭제 버튼 식별자",
		"selectAllModuleId": "모두 선택 컴포넌트 식별자",
		"selectedValue": "선택한 값",
		"innerSideModuleId": "내부 관련 컴포넌트 식별자",
		"deleteButtonId": "삭제 버튼 식별자",
		"sequenctModuleId": "일련번호 컴포넌트 식별자",
		"selectModuleId": "선택 컴포넌트 식별자",
		"defaultShow": "기본 표시",
		"item": "항목",
		"maxItemCount": "최대 추가 항목 수",
		"minItemCount": "최소 유지 항목 수",
		"dtImportInfor": "참고: 이미지, 첨부 파일, 데이터 테이블, 서브 데이터 템플릿은 가져오기 및 내보내기할 수 없습니다.",
		"importButtonId": "가져오기 버튼 식별자",
		"exportButtonId": "내보내기 버튼 식별자",
		"importExporConfig": "가져오기 및 내보내기 필드 설정",
		"validationPopFormConfig": "유효성 검사 팝업 폼 설정",
		"validationPopFormHeight": "팝업 폼 높이",
		"validationPopFormWidth": "팝업 폼 너비",
		"validationTableStyle": "유효성 검사 테이블 스타일",
		"validationTitleTdStyle": "유효성 검사 제목 셀 스타일",
		"validationContentTdStyle": "유효성 검사 내용 셀 스타일",
		"validationTableAttribute": "유효성 검사 테이블 속성",
		"count": "개수",
		"import": "가져오기",
		"datatableEditMode": "편집 모드",
		"datatableEditModeValue": ["매 번 단일 행 편집", "다중 행 동시 편집"],
		"onlyPc": "PC에서만 사용 가능",

        "size": "크기",
		"color": "색상",
		"el_bt_default": "기본 버튼",
		"el_bt_primary": "기본 버튼",
		"el_bt_success": "성공 버튼",
		"el_bt_warning": "경고 버튼",
		"el_bt_danger": "위험 버튼",
		"el_bt_info": "정보 버튼",
		"el_bt_text": "텍스트 버튼",

		"el_plain": "단순 버튼",
		"el_round": "둥근 모서리 버튼",
		"el_circle": "원형 버튼",
		"el_icon": "아이콘",
		"el_disabled": "사용 중지",
		"el_loading": "로딩 중",
		"el_autofocus": "자동 포커스",
		"el_isText": "텍스트 표시",

		"layout": "레이아웃",
		"layoutCode": "레이아웃 코드",
		"layoutTemplate": "일반적인 레이아웃",

		"elGroupStyles": "그룹 스타일",
		"elGroupProperties": "그룹 속성",

		"el_border": "테두리 표시",
		"el_radioColor": "글자 색상",
		"el_radioFillColor": "채우기 색상",
		"el_buttonRadio": "버튼 모드",


        "datatemplateOuterNote": "참고: 현재 데이터 템플릿 외부에 있는 관련 구성 요소 식별자입니다. 데이터 템플릿은 여러 계층일 수 있으며 외부 구성 요소 식별자는 다음 규칙에 따라 작성됩니다:<br/>" +
			"1. 단일 계층 또는 최상위 데이터 템플릿의 경우 'fieldId'를 입력하면 양식에서 직접 구성 요소를 나타냅니다.<br/>" +
			"2. 여러 계층 데이터 템플릿이 있는 경우 './fieldId'는 현재 데이터 템플릿과 동일한 수준의 구성 요소를 나타냅니다. '../fieldId'는 이전 계층의 데이터 템플릿과 동일한 수준의 구성 요소를 나타냅니다. 이와 같은 식으로 계속됩니다.<br/>" +
			"3. 여러 계층 데이터 템플릿이 있는 경우 'datatemplateId.*.datatemplateId2.*.fieldId'를 사용하여 전체 계층 경로를 나타낼 수도 있습니다. datatemplateId는 첫 번째 계층 데이터 템플릿의 ID이고, datatemplateId2는 두 번째 계층의 ID입니다.",
		"datatemplateInnerNote": "참고: 현재 데이터 템플릿 내부에 있는 관련 구성 요소 식별자입니다. 단일 또는 다중 계층 데이터 템플릿에 상관없이 구성 요소의 식별자를 직접 입력합니다.",
		"importModel": "가져오기 모델",
		"enable": "활성화",
		"disable": "비활성화",
		"downloadTempalte": "템플릿 다운로드",
		"downloadTempalteId": "템플릿 다운로드 구성 요소 식별자",
		"downloadTempalteIdNote": "양식에 구성 요소를 만들고 여기에 구성 요소 식별자를 입력할 수 있으며, 시스템은 해당 구성 요소의 노드(node)에 템플릿 다운로드 click 이벤트를 바인딩합니다.",
		"province": "도",
		"city": "시/군",
		"county": "시/군/구",
		"useTextFieldNote": "참고: 텍스트 구성 요소를 사용하는 것을 권장합니다.",
		"useChecboxNote": "참고: 다중 선택 구성 요소를 사용하는 것을 권장합니다.",
		"checkboxValueNote": "참고: 선택한 구성 요소에 해당하는 값입니다.",
		"checkboxValueAllNote": "참고: 전체 선택 구성 요소에 해당하는 값입니다.",
		"notShow": "표시 안 함",
		"insertDataTemplate": "데이터 템플릿 삽입",
		"widthModules": "관련 구성 요소와 함께 삽입",
		"ckeditConfig": "에디터 구성",
		"ckeditConfigInfor": "에디터 구성을 반환하는 JSON 객체입니다.",
		"ckeditConfigInfor1": "에디터 도구 모음 기능을 구성하는 방법에 대한 자세한 내용은 다음 링크를 참조하세요:",
		"ckeditConfigInfor2": "../o2_lib/htmleditor/ckeditor4161/samples/toolbarconfigurator/index.html",
		"ckeditConfigInfor3": "여기를 클릭하세요",
		"ckeditConfigInfor4": "추가 구성 정보는 Ckeditor 공식 웹 사이트에서 확인하세요.",
		"ckeditConfigInfor5": "https://ckeditor.com/ckeditor-4/",
		"ckeditConfigInfor6": "참고: 에디터 속성을 사용자 정의한 후에는 문서 형식이 국가 정부 및 정부 문서 형식 표준을 더 이상 준수하지 않을 수 있습니다.",

        "showRead": "읽지 않은 항목 표시",
		"password": "비밀번호",
		"search": "검색",
		"email": "이메일",
		"datetime-local": "날짜 및 시간",
		"month": "월",
		"date": "날짜",
		"time": "시간",
		"week": "주",
		"textarea": "여러 줄 텍스트",
		"wordNumber": "단어 수 통계",
		"maxlength": "최대 길이",
		"clearable": "지울 수 있는",
		"showPassword": "비밀번호 전환 아이콘 표시",
		"prefixIcon": "접두사 아이콘",
		"suffixIcon": "접미사 아이콘",
		"textareaRows": "여러 줄 텍스트 행 수",
		"autosize": "높이 자동 조정",
		"minRows": "최소 행 수",
		"maxRows": "최대 행 수",
		"resize": "크기 변경",
		"resizeNone": "허용 안 함",
		"resizeBoth": "허용",
		"resizeHorizontal": "가로",
		"resizeVertical": "세로",
		"el_placement": "팝업 위치",
		"popperClass": "목록 클래스",
		"triggerOnFocus": "활성화되면 입력 제안 표시",
		"itemScriptInfo": "입력 제안을 제공하는 함수를 반환합니다. Function(queryString, callback)",
		"multiple": "다중 선택 가능 여부",
		"collapseTags": "태그 합병",
		"multipleInfo": "다중 선택 가능할 때 유효",
		"filterable": "검색 허용",
		"filterMethod": "사용자 정의 검색 방법",
		"filterRemote": "원격 검색",
		"allowCreate": "새 항목 생성 허용",
		"noMatchText": "일치하는 항목 없음 텍스트",
		"noDataText": "데이터 없음 텍스트",
		"loadingText": "로딩 중 텍스트",
		"remoteMethod": "원격 검색 방법",
		"multipleLimit": "최대 선택 가능한 수",

        "max": "최대값",
		"min": "최소값",
		"step": "간격",
		"step_strictly": "간격의 배수만 입력 허용",
		"precision": "소수 자릿수",
		"controls": "제어 버튼",
		"controlsPosition": "버튼 위치",

        "activeText": "텍스트 열기",
		"inactiveText": "텍스트 닫기",
		"activeColor": "활성화 색상",
		"inactiveColor": "비활성화 색상",
		"activeIconClass": "활성화 아이콘",
		"inactiveIconClass": "비활성화 아이콘",
		"activeValue": "활성화 값",
		"inactiveValue": "비활성화 값",
		"valueType": "값 유형",
		"showInput": "입력란 표시",
		"showInputControls": "입력란 버튼 표시",
		"inputSize": "입력란 크기",
		"sliderRange": "범위 선택 여부",
		"sliderVertical": "세로 모드",
		"sliderMarks": "마크 표시",
		"showTooltip": "툴팁 표시",
		"tooltipClass": "툴팁 클래스",
		"formatTooltip": "툴팁 형식 지정",
		"formatTooltipScript": "포맷 함수 반환:",
		"showStops": "중단점 표시 여부",
		"marksScriptInfo": "객체 반환, 키는 number 유형이어야 하며 [min, max] 범위 내여야 하며 각 마크를 개별적으로 스타일 지정 가능",
		"optionsGroup": "옵션 그룹",
		"selectItemScriptInfo": "선택값 배열 또는 선택값 배열을 해결(resolve)한 Promise 반환",
		"selectTemplete": "사용자 정의 옵션 템플릿",
		"showAllLevels": "전체 경로",
		"checkStrictly": "상하관계 없음",
		"checkStrictlyInfo": "부모-자식 노드 간 상호 연결 해제 여부",
		"emitPath": "전체 배열 반환",
		"emitPathInfo": "선택 노드가 변경될 때 해당 노드가 속한 모든 수준의 메뉴 값으로 이루어진 배열 반환, false로 설정하면 해당 노드 값만 반환",
		"lazy": "동적 로드",
		"lazyLoadScript": "동적 로드 메서드",
		"props_value": "옵션 값 속성",
		"props_label": "옵션 라벨 속성",
		"props_children": "하위 옵션 속성",
		"props_disabled": "옵션 비활성화 속성",
		"props_leaf": "말단 노드 플래그 속성",
		"expandTrigger": "확장 트리거",
		"beforeFilter": "필터링 전",
		"filterMethodInfo": "Function 반환, 사용자 정의 검색 논리 구현, 첫 번째 매개변수는 노드(node), 두 번째 매개변수는 검색어(keyword)이며 불리언 값을 반환하여 일치 여부를 나타냄",
		"beforeFilterInfo": "Function 반환, 필터링 전 훅, 입력값을 인수로 사용하며 false를 반환하거나 프로미스를 반환하고 거부될 경우 필터링 중단",
		"lazyLoadScriptInfo": "동적 데이터 로드 메서드, lazy가 true일 때만 유효; function(node, resolve)를 반환하며 node는 현재 클릭한 노드이고 resolve는 데이터로드 완료 콜백(반드시 호출)",
		"firstPageNumber": "첫 페이지 번호",

        "showOptions": "옵션 표시",
		"onInput": "입력 시",
		"onFocus": "클릭 시",
		"emptyValue": "빈 값",
		"showZero": "제로 표시",
		"showNullString": "빈 문자열 표시",
		"centerServer": "중앙 서버",
		"pathConditions": "경로 기본 조건",
		"parameterConditions": "매개변수 기본 조건",
		"addDefaultConditionByPath": "경로로 기본 조건 추가",
		"addDefaultConditionByParameter": "매개변수로 기본 조건 추가",
		"placementValue": ["상 중앙", "상 좌측", "상 우측", "하 중앙", "하 좌측", "하 우측"],
		"trigger": "트리거 방식",
		"triggerValue": ["마우스 오버", "마우스 클릭"],
		"hideOnClick": "클릭 시 메뉴 숨기기",
		"showTimeout": "열기 지연 시간",
		"hideTimeout": "접기 지연 시간",
		"splitButton": "클릭 및 드롭다운 동시 사용",
		"splitButtonType": "버튼 유형",
		"menuItem": "메뉴 항목",
		"dropdownDefaultText": "드롭다운 메뉴",
		"showButton": "버튼 표시",
		"countPerline": "행당 옵션 수",
		"countPerlineNote": "0은 제한 없음을 의미합니다",

        "wps" : {
            "config": "구성",
			"options": "일반 옵션",
			"topArea": "상단 영역",
			"show": "표시",
			"hide": "숨기기",
			"headArea": "머리 부분 영역",
			"showMode": "표시 모드",
			"showMode_normal": "일반 모드, 모든 기능 화면 표시",
			"showMode_simple": "간단 모드, 머리말 및 도구 모음 표시 안 함",
			"wordConfig": "Word 구성 옵션",
			"comment": "의견",
			"isShowDocMap": "목차 기능 활성화 여부",
			"isBestScale": "문서 열기 시 기본 최적 비율로 표시 (PC)",
			"isShowBottomStatusBar": "하단 상태 표시줄 (PC)",
			"isOpenIntoEdit": "모바일에서 열 때 편집으로 진입 여부",
			"component": "구성 요소",
			"isComponent": "구성 요소 사용 여부 (PC)",
			"HeaderLeft": "머리말 왼쪽",
			"HeaderRight": "머리말 오른쪽",
			"FloatQuickHelp": "오른쪽 하단 도움말 (골든 판다)",
			"HistoryVersion": "상단 상태 표시줄 - 버전 기록 메뉴 - 기록된 버전",
			"HistoryRecord": "상단 상태 표시줄 - 버전 기록 메뉴 - 협업 기록",
			"HistoryVersionDivider": "표 - 오른쪽 클릭 메뉴 - 버전 기록/협업 기록 분할선",
			"TabPrintPreview": "상단 도구 모음 인쇄 버튼",
			"MenuPrintPreview": "더보기 메뉴 인쇄 버튼",
			"ReviewTrackChanges": "편집, 수정 상태 버튼",
			"TrackChanges": "편집, 수정 상태 드롭다운 옵션",
			"ContextMenuConvene": "텍스트 오른쪽 클릭하여 온라인 지원 요청",
			"isComponentMobile": "구성 요소 사용 여부 (모바일)",
			"Logo": "상태 표시줄 로고",
			"Cooperation": "상태 표시줄 협업 프로필 사진",
			"More": "상태 표시줄 더보기 버튼",
			"SendButton": "상단 도구 모음 - 공유 버튼",
			"CooperHistoryMenuItem": "상단 도구 모음 - 협업 기록 메뉴",
			"WriterHoverToolbars": "텍스트 - 하단 도구 모음",
			"ReadSetting": "텍스트 - 상태 표시줄 - 읽기 설정"
        },
        "onlyoffice" : {
            "config": "설정",
			"moduleConfig": "기능 설정",
			"autosave": "자동 저장",
			"chat": "채팅 활성화",
			"comments": "댓글 활성화",
			"compatibleFeatures": "이전 버전과 호환",
			"plugins": "플러그인 활성화",
			"reviewDisplay": "검토 표시 방법",
			"reviewDisplay_markup": "마크업",
			"reviewDisplay_final": "최종 버전",
			"reviewDisplay_original": "원본",
			"showReviewChanges": "검토 변경 내용 표시",
			"trackChanges": "편집 모드 활성화",
			"spellcheck": "스펠 체크",
			"viewSet": "인터페이스 설정",
			"compactHeader": "헤더 숨기기",
			"compactToolbar": "간소한 도구 모음",
			"feedback": "피드백 표시 여부",
			"help": "도움말 표시 여부",
			"toolbarHideFileName": "제목 표시줄에 파일 이름 표시 여부",
			"toolbarNoTabs": "상단 도구 모음에 탭 표시 여부",
			"unit": "척도 측정 단위",
			"unit_cm": "센티미터",
			"unit_pt": "픽셀",
			"unit_inch": "인치",
			"zoom": "기본 확대/축소",
			"hideRightMenu": "우측 메뉴 숨기기",
			"individualization": "개인 정보",
			"address": "주소",
			"mail": "이메일",
			"info": "소개",
			"company": "회사 이름",
			"www": "웹 사이트",
			"feedbackUrl": "피드백 주소",
			"logoImg": "왼쪽 상단 로고 (172x40)",
			"logoUrl": "로고 링크"
        },
        "smartbi":{
            "select": "자원 선택",
			"displayToolbar": "도구 모음 표시",
			"toolbarShow": "표시",
			"toolbarHide": "숨기기",
			"displayLeftTree": "왼쪽 트리 표시",
			"leftTreeShow": "표시",
			"leftTreeHide": "숨기기"
        },
        "weeks": {
            "arr": ["월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일"]
        },
        "tabletWidth": "태블릿 폭",
		"tabletHeight": "태블릿 높이",
		"tabletSizeNote": "PC에서만 유효하며, 모바일에서 가로 스크린을 채웁니다.",
		"tabletToolbarNote": "PC에서만 유효하며, 모바일에서는 표시되지 않습니다.",
		"editable": "편집 가능",
		"firstDayOfWeek": "주의 시작 요일",
		"disabledDate": "날짜 선택 비활성화",
		"disabledDateNote": "this.event가 전달된 날짜이며, 'return true'는 해당 날짜를 선택하지 못하게 합니다.",
		"disabledDateScript": "날짜 선택 비활성화 스크립트",
		"selectableRangeNote": "선택 가능한 시간 범위를 반환합니다. 예: '18:30:00 - 20:30:00' 또는 ['09:30:00 - 12:00:00', '14:30:00 - 18:30:00']",
		"selectableRangeScript": "시간 선택 가능 범위 스크립트",
		"placeholder": "자리 표시자 텍스트",
		"rangeSeparator": "범위 구분자 텍스트",
		"startPlaceholder": "시작 자리 표시자 텍스트",
		"endPlaceholder": "끝 자리 표시자 텍스트",
		"arrowControl": "화살표를 사용하여 시간 선택",
		"timeSelectType2": "시간 선택 유형",
		"isRange": "범위",
		"fixedTimePoint": "고정된 시간",
		"anyTimePoint": "임의의 시간",
		"to": "에서",
		"startTime": "시작 시간",
		"endTime": "끝 시간",
		"startDate": "시작 날짜",
		"endDate": "끝 날짜",
		"selectableRange": "선택 가능한 범위",
		"endSelectableRange": "종료 선택 가능 범위",

        "initialIndex": "초기 슬라이드 인덱스",
		"autoplay": "자동 전환",
		"interval": "전환 간격",
		"indicatorPosition": "인디케이터 위치",
		"indicatorPositionValue": ["내부", "외부", "없음"],
		"arrow": "화살표",
		"arrowValue": ["마우스 오버 시 표시", "항상 표시", "표시 안 함"],
		"carouselTypeValue": ["기본", "카드"],
		"loop": "루프 여부",
		"direction": "표시 방향",
		"directionValue": ["수평", "수직"],
		"hotpicture": "핫포인트 이미지",
		"page": "페이지 수",
		"filterParameter": "필터 매개 변수",
		"selectComponent": "애플리케이션 선택",
		"calculationComponent": "경로 계산 애플리케이션",
		"component": "애플리케이션",
		"scriptComponentNote": "조직 관리와 같은 애플리케이션 경로를 반환합니다.",
		"componentScript": "애플리케이션 경로 스크립트",
		"applicationOptions": "애플리케이션 옵션",
		"applicationStatus": "애플리케이션 상태",
		"titleAddTo": "타이틀 행 추가",
		"firstLine": "첫 번째 행",
		"lastLine": "마지막 행"
    },
    "smartbi": {
		"nosetup": "먼저 SmartBI 앱을 설치하십시오",
		"txt": "SmartBI 보고서"
	  },
	  "onlyoffice": {
		"nosetup": "먼저 OnlyOffice 앱을 설치하십시오"
	  },
	  "wpsoffice": {
		"nosetup": "먼저 WpsOffice 앱을 설치하십시오"
	  },
	  "officeonline": {
		"nosetup": "먼저 OfficeOnline 앱을 설치하십시오"
	  },
    "actionBar": {
        "close": "닫기",
		"closeTitle": "문서 닫기",
		"save": "저장",
		"saveTitle": "문서 저장",
		"flow": "계속 순환",
		"flowTitle": "문서 계속 순환",
		"reroute": "재지정",
		"rerouteTitle": "문서 재지정",
		"reset": "담당자 재설정",
		"resetTitle": "담당자 재설정",
		"split": "분기 추가",
		"splitTitle": "분기 추가",
		"retract": "철회",
		"retractTitle": "문서 철회",
		"rollback": "프로세스 롤백",
		"rollbackTitle": "지정된 단계로 롤백, 프로세스 기록 삭제 안 함",
		"delete": "문서 삭제",
		"deleteTitle": "파일 삭제",
		"print": "인쇄",
		"printTitle": "문서 인쇄",
		"press": "처리 유도",
		"pressTitle": "처리 유도",
		"pause": "보류",
		"pauseTitle": "문서 보류",
		"resume": "보류 해제",
		"resumeTitle": "보류 상태에서 복구",
		"downloadAll": "일괄 다운로드",
		"downloadAllTitle": "일괄 다운로드",
		"monitor": "프로세스 모니터링",
		"monitorTitle": "프로세스 모니터링",
		"setReaded": "읽음 표시",
		"readed": "읽음",
		"addTask": "추가 서명",
		"addTaskTitle": "현재 활동에 담당자 추가",
		"goBack": "반환",
		"goBackTitle": "이미 지난 활동으로 반환"
    },
    "filedConfigurator": {
		"sequence": "일련번호",
		"fieldTitle": "필드 제목",
		"fieldId": "필드 식별자",
		"action": "작업",
		"moveup": "이전 행으로 이동",
		"deleteRow": "행 삭제",
		"insertRow": "행 삽입",
		"importFromForm": "화면에서 필드 설정 가져오기"
    }
};
