MWF.xApplication.process.FormDesigner.LP = {
		"title": "表单编辑",
		"newForm": "新建表单",
		"property": "属性",
		"tools": "工具",
		"all": "全部",
		
		"repetitionsId": "重复的元素标识符",
		"notNullId": "元素标识符不能为空",
		
		"button":{
			"ok": "确定",
			"cancel": "取消"
		},
        "version" : {
            "title" : "查看表单版本记录",
            "close" : "关闭",
            "no":"序号",
            "updateTime":"更新时间",
            "op":"操作",
            "resume" : "恢复",
            "resumeConfirm" : "恢复确认",
            "resumeInfo" : "您确认是否需要执行表单恢复操作？确认恢复后当前表单会更新，需要手动保存当前表单才会生效。",
            "resumeSuccess" :"恢复成功"
        },
		"notice": {
			"save_success": "表单保存成功！",
            "saveTemplate_success": "表单模板保存成功！",
            "saveTemplate_inputName": "请输入模板标题",
            "saveTemplate_inputCategory": "请确定模板分类",
			
			"deleteElementTitle": "删除表单元素确认",
			"deleteElement": "是否确定删除当前元素，及其子元素吗？",
			
			"deleteRowTitle": "删除表格行确认",
			"deleteRow": "删除当前行将删除该行所有单元格中的内容，是否确定删除当前选中的行？",
			"deleteColTitle": "删除表格列确认",
			"deleteCol": "删除当前行将删除该列所有单元格中的内容，是否确定删除当前选中的列？",
            "deleteEventTitle": "删除事件确认",
            "deleteEvent": "是否确定删除当前事件吗？",

            "deleteActionTitle": "删除操作确认",
            "deleteAction": "是否确定删除当前操作吗？",

            "deleteButtonTitle": "删除操作确认",
            "deleteButton": "确定要删除当前操作按钮吗？",

            "notUseModuleInMobile": "移动端不支持此组件",

            "changeToSequenceTitle": "确认",
            "changeToSequence": "此操作会删除已经添加的组件，确定要改成“序号”列吗？"
		},
		
		"formAction": {
			"insertRow": "插入行",
			"insertCol": "插入列",
			"deleteRow": "删除行",
			"deleteCol": "删除列",
			"mergerCell": "合并单元格",
			"splitCell": "拆分单元格",
			"move": "移动",
			"copy": "复制",
			"delete": "删除",
			"add": "添加",
			"script": "脚本",
            "styleBrush": "格式刷",
            "insertTop" : "插入到顶部",
            "insertBottom" : "插入到底部",
            "insertBefore" : "插入到前面",
            "insertAfter" : "插入到后面",
            "injectNotice" : "按住Ctrl松开鼠标精确定位"
		},

        "actionbar": {
            "readhide": "设置阅读时是否显示",
            "edithide": "设置编辑时是否显示",
            "hideCondition": "设置隐藏条件",
            "title": "标题",
            "img": "图标",
            "action": "操作",
            "condition": "显示条件",
            "editScript": "操作脚本编辑",
            "editCondition": "隐藏条件编辑（返回true隐藏操作）",
            "up" : "上移",
            "property" : "属性",
            "addCustomTool" : "添加自定义操作",
            "delete" : "删除",
            "setProperties" : "设置操作属性",
            "restoreDefaultTool" : "恢复删除的系统操作",
            "selectDefaultTool" : "选择系统操作",
            "setReaded" : "标记为已阅",
            "readed" : "已阅"
        },
        "isSave": "正在保存，请稍候...",
        "scriptIncluder" : {
		    "yes" : "是",
            "no" : "否",
		    "selectScript" : "选择脚本：",
		    "repeatAddScriptNotice" : "请不要重复添加脚本",
		    "selectScriptNotice" : "请先选择脚本",
            "asyncLoad" : "异步加载：",
		    "asyncLoadScript" : "异步加载脚本：",
            "syncLoadScript" : "同步加载脚本：",
            "delete_title": "取消加载脚本确认",
            "delete_text": "您确定要取消加载选择的脚本？"
        },
        "dictionaryIncluder" : {
            "selectDictionary" : "选择：",
            "repeatAddDictionaryNotice" : "请不要重复添加数据字典",
            "rootDictionaryExistNotice" : "已经添加了该数据字典的根路径，无需再添加",
            "parentDictionaryExistNotice" : "已经添加了该数据字典的父路径，无需再添加",
            "subDictionaryExistNotice" : "已经存在该数据字典的子路径，请先删除再添加",
            "selectDictionaryNotice" : "请先选择数据字典",
            "path" : "路径：",
            "delete_title": "取消加载数据字典确认",
            "delete_text": "您确定要取消加载选择的数据字典？"
        },
        "validation": {
            "validation": "校验",
            "anytime": "任何时候",
            "decision": "选择决策",
            "decisionName": "<决策名>",
            "value": "值",
            "length": "值长度",
            "valueInput": "<值>",
            "isnull": "为空",
            "notnull": "不为空",
            "gt": "大于",
            "lt": "小于",
            "equal": "等于",
            "neq": "不等于",
            "contain": "包含",
            "notcontain": "不包含",
            "prompt": "提示",
            "add": "添加",
            "modify": "修改",
            "when": "当",
            "as": "时",
            "inputDecisionName": "请输入决策名称",
            "inputValue": "请输入值",
            "inputPrompt": "请输入提示内容",
            "delete_title": "删除校验内容确认",
            "delete_text": "您确定要删除此项校验码？"
        },

    "datagrid" : {
		"import" : "导入",
       "export" : "导出"
    },

    "selectIcon": "选择图标",
    "selectImage": "选择图片",
    "selectApplication" : "选择应用",
    "dutyInputTitle": "添加职务参数",
    "dutyInput": "请为职务“{duty}”确定组织",
    "select": "选择",
    "empty": "清空",

    "creatorUnit": "拟稿人所在组织",
    "currentUnit": "处理人所在组织",
    "selectUnit": "选择组织",
    "scriptUnit": "使用脚本",

    "creatorCompany": "拟稿公司",
    "creatorDepartment": "拟稿部门",
    "currentCompany": "当前公司",
    "currentDepartment": "当前部门",

    "deleteDutyTitle": "移除职务确认",
    "deleteDutyText": "您确认要移除职务“{duty}”吗？",

    "saveTemplate": "保存为表单模板",
    "templateName": "模板名称",
    "templateCategory": "模板分类",
    "templateDescription": "模板描述",
    "save": "保存",
    "cancel": "取消",
    "newCategory": "新分类",
    "mustSelectFormStyle" : "必须选择一种表单样式",
    "notValidJson" : "错误的json格式",

    "imageClipper" : "图片编辑",

    "clearNoDomModuleTitle" : "清除未在HTML树中的组件配置",
    "clearNoDomModuleContent" : "是否清除未在HTML树中的组件配置？清除后需要保存生效。",

    "filter": {
        "and": "并且",
        "or": "或者",
        "equals": "等于",
        "notEquals": "不等于",
        "greaterThan": "大于",
        "greaterThanOrEqualTo": "大于等于",
        "lessThan": "小于",
        "lessThanOrEqualTo": "小于等于",
        "like": "匹配",
        "notLike": "不匹配",
        "from" : "从",
        "value" : "值"
    },
    "mastInputPath": "请输入数据路径",
    "mastInputTitle": "请输入标题",
    "delete_filterItem_title": "删除过滤条件确认",
    "delete_filterItem": "您确定要删除当前过滤条件吗？",

    "subformNameConflictTitle": "子表单字段名称冲突",
    "subformNameConflictInfor": "子表单的以下字段名称和现有表单冲突：\n{name}",
    "subformConflictTitle": "子表单嵌入错误",
    "subformConflictInfor": "您不能重复嵌入同一个子表单",

    "subformNestedTitle": "子表单嵌入错误",
    "subformNestedInfor": "不能相互嵌套的嵌入子表单",
    "checkSubformNestedError" : "您选择的子表单存在相互嵌套的情况，请检查！",

    "checkSubformTitle": "表单保存校验",
    "checkFormSaveError": "无法保存表单，原因如下：<br>",
    "checkSubformPcInfor": "PC表单中，有以下子表单字段冲突：<br>{subform}<br>",
    "checkSubformMobileInfor": "Mobile表单中，有以下子表单字段冲突：<br>{subform}",

    "implodeError": "要导入的数据格式有误",
    "implodeEmpty": "请在编辑框中填入要导入的数据",
    "implodeConfirmTitle": "导入确认",
    "implodeConfirmText": "导入数据将清除当前页面，并无法撤销，您确定要导入吗？",

    "design": "设计",
    "script": "脚本",
    "html": "HTML",
    "css": "CSS",
    "byModule": "按设计元素",
    "byPath": "按脚本类型",
    "events": "事件",
    "pageform": "页面",
    "importO2": "从O2数据导入",
    "importHTML": "从HTML导入",
    "importOffice": "从WORD或EXCEL导入",
    "importO2_infor": "请将O2格式的表单数据拷贝到以下编辑器中。（使用表单或页面设计器工具条上的“导出”按钮，获取表单数据）<br/>按下Ctrl+Alt+I可格式化数据",
    "importHTML_infor": "请将HTML数据拷贝到以下编辑器中。按下Ctrl+Alt+I可格式化数据",
    "importHTML_infor2": "请将CSS数据拷贝到以下编辑器中。按下Ctrl+Alt+I可格式化数据",
    "importOffice_infor": "请选择一个Word或Excel文件。",
    "import_ok": "导入",
    "import_cancel": "取消",
    "import_option1": "在表格的空单元格中添加输入框",
    "import_option2": "去除空元素",
    "implodeOfficeEmpty": "请先选择要导入的Word或Excel文件",

    "scriptTitle": {
        "validationOpinion": "表单意见校验",
        "validationRoute": "表单路由校验",
        "validationFormCustom": "表单校验",
        "defaultValue": "默认值",
        "validation": "校验脚本",
        "sectionByScript": "区段依据",
        "itemScript": "可选值脚本",
        "iframeScript": "iframe脚本",
        "labelScript": "文本值",
        "rangeKey": "组织范围",
        "identityRangeKey": "身份组织范围",
        "unitRangeKey": "组织选择范围",
        "rangeDutyKey": "职务范围",
        "exclude": "选择排除脚本",
        "cookies": "数据源请求cookies",
        "requestBody": "数据源请求消息体",
        "jsonText": "数据文本",
        "dataScript": "树控件脚本",
        "itemDynamic": "动态选项脚本",
        "defaultData": "数据网格默认值",
        "editableScript": "数据网格是否可编辑",
        "config": "HTML编辑框配置",
        "filterScript": "流程记录过滤",
        "readScript": "Office只读脚本",
        "fileSite": "Office文件site脚本",
        "subformScript": "子表单脚本",
        "selectedScript": "视图选择脚本",
        "action.tools": "操作按钮"
    },
    "copyed": "已复制",
    "selectorButton" : {
        "ok" : "确　定",
        "cancel" : "取 消"
    },
    "modules": {
        "label": "文本",
        "textfield": "文本字段",
        "number": "数字字段",
        "org": "人员组织",
        "calendar": "日期选择",
        "textarea": "多行文本",
        "select": "下拉框",
        "radio": "单选框",
        "checkbox": "多选框",
        "combox": "组合框",
        "opinion": "意见框",
        "button": "按钮",
        "Address": "地址",
        "Actionbar": "操作条",
        "Sidebar": "侧边操作条",
        "image": "图片",
        "imageclipper": "图片编辑",
        "attachment": "附件",
        "div": "容器",
        "table": "表格",
        "datagrid": "数据网格",
        "subform": "子表单",
        "ViewSelector": "选择视图",
        "view": "嵌入视图",
        "stat": "嵌入统计",
        "html": "HTML",
        "common": "通用元素",
        "tab": "分页",
        "tree": "树",
        "log": "流程记录",
        "monitor": "流程监控",
        "iframe": "Iframe",
        "documenteditor": "公文编辑器",
        "htmledit": "HTML编辑器",
        "office": "Office控件",
        "statementSelector": "选择查询视图",
        "statement": "嵌入查询视图"
    },
    "propertyTemplate": {
        "base": "基本",
        "event": "事件",
        "html": "HTML",
        "json": "JSON",
        "action": "操作",
        "select": "选择",

        "id": "标识",
        "name": "名称",
        "description": "描述",
        "appearance": "外观类型",
        "style": "样式",
        "attribute": "属性",

        "hideSystemTools": "系统操作",
        "show": "显示",
        "hide": "隐藏",
        "readed": "已阅",

        "category": "分类",
        "formStyle": "表单样式",
        "icon": "图标",
        "printForm": "打印表单",
        "preloadScript": "预加载脚本",
        "script": "脚本",
        "copy": "复制",
        "paste": "粘贴",
        "languageScript": "语言包脚本 (S)",
        "languageInfo": "返回包含语言信息的JSON对象；o2.language获取当前语言信息",
        "SubmitUI": "提交界面",
        "submit": "提交",
        "systemDefault": "系统默认",
        "selectForm": "选择表单",
        "computeForm": "计算表单",
        "application": "应用",
        "form": "表单",
        "crossApplication": "跨应用",
        "computeSubmitAnnotation1": "应用名称、别名、id",
        "computeSubmitAnnotation2": "表单名称、id",
        "thisApplication": "本应用",
        "submitFormScript": "提交表单脚本",
        "flowActionScript": "提交（继续流转）操作脚本",
        "handwritingWidth": "提交意见手写板宽度",
        "effectivePC": "pc端有效",
        "handwritingHeight": "提交意见手写板高度",
        "promptBoxFlow": "流转后提示框",
        "yes": "是",
        "no": "否",
        "usedNewWindow": "仅用于新浏览器窗口打开时",
        "promptLocation": "提示框位置",
        "lefttop": "左上",
        "righttop": "右上",
        "leftbottom": "左下",
        "rightbottom": "右下",
        "center": "中央",
        "prompt": "提示框",
        "notClose":"不关闭",
        "closeInfo": "秒后自动关闭",
        "afterFlow": "流转后",
        "closeWindow": "关闭窗口",
        "redirect": "重定向",
        "redirectScript": "重定向地址脚本",
        "returnUrl": "返回一个URL用于重定向",
        "check": "校验",
        "checkOpinion": "校验意见",
        "checkRoute": "校验路由",
        "checkFlow": "流转校验",
        "noEventInfo": "注：当以子表单嵌入时，下列事件不会被执行",
        "none": "无",
        "default": "默认",
        "byScript": "根据脚本",
        "languageDefaultInfo": "系统会自动载入名称为 \"lp-\"+o2.language 的数据字典，作为语言包",

        "prefix": "前缀",
        "suffix": "后缀",

        "value": "值",
        "textValue": "固定值",

        "showIcon": "显示图标",
        "readonly": "是否只读",
        "AIInput": "智能输入",
        "inputStyle": "Input样式",
        "compute": "计算",
        "create": "创建",
        "save": "保存",

        "defaultValue": "默认值",
        "verificationScript": "校验脚本",
        "section": "区段",
        "enableSection": "启用区段",
        "sectionBy": "区段依据",
        "handler": "处理人",
        "handlerUnit": "处理人所在组织",
        "activityId": "活动ID",
        "splitValue": "拆分值",

        "decimal": "小数点",

        "showCard": "显示卡片",
        "allowInput": "允许输入",
        "dataStructure": "数据保存",
        "complete": "完整",
        "simple": "精简",
        "separator": "分隔符",

        "identity": "身份",
        "unit": "组织",
        "duty": "职位",
        "group": "群组",
        "person": "个人",

        "defaultValueScript": "默认值脚本",
        "showText": "显示文本",
        "showTextScript": "显示文本脚本",
        "unitSelectConfig": "人员组织选择配置",
        "selectType": "选择类型",
        "selectCount": "选择数量",
        "returnValue": "结果返回",

        "selectTypeInfo": "参与流程处理请选身份！",
        "selectTypeInfo2": "注意，个人无法参与流程处理！",
        "checkEmpower": "检查待办授权",
        "onlyCustom": "只使用自定义选项",
        "unitRange": "组织范围",
        "allUnit": "所有组织",
        "specifyUnit": "指定组织",
        "draftUnit": "拟稿人所在的组织",
        "currentUnit": "当前人所在的组织",
        "inUnit": "直接所属组织",
        "levelIs": "第",
        "levelUnit": "层组织",
        "unitTypeIs": "类型为",
        "deUnit": "的组织",
        "expandNext": "展开下级",
        "selectUnit": "选择组织",
        "formData": "表单数据",
        "dutyRange": "职务范围",
        "all": "所有",
        "all2": "全部",
        "specifyDuty": "指定职务",
        "byUnit": "按组织",
        "byDuty": "按职务",
        "showLevel": "展现层级",
        "byDutyUnit": "按职务所在组织",
        "byIdentityUnit": "按身份所在组织",
        "selectDuty": "选择职务",
        "customOption": "自定义选项",
        "useScriptAddIdOrPerson": "使用脚本添加身份/个人",
        "unitType": "组织类型",
        "selectRange": "选择范围",
        "specifyGroup": "指定群组",
        "exclude": "排除",
        "excludeInfo": "通过编写脚本排除组织、身份、个人和群组的选择范围",

        "dateTime": "日期时间",
        "dateOnly": "仅日期",
        "monthOnly": "仅月份",
        "yearOnly": "仅年度",
        "timeOnly": "仅时间",
        "selectSecond": "是否选择秒",
        "format": "格式化",

        "selectStyle": "Select样式",
        "options": "可选值",
        "optionScript": "可选值脚本",
        "divStyle": "容器样式",
        "buttonStyle": "按钮样式",

        "dynamic": "动态计算",
        "canSelectCount": "可选数量",
        "showSeparator": "显示分隔符",
        "optionDynamicScript": "可选值动态脚本"

    },
    "actionBar": {
        "close":"关闭",
        "closeTitle": "关闭文档",
        "save": "保存",
        "saveTitle": "保存文档",
        "flow": "继续流转",
        "flowTitle": "继续流转文档",
        "reroute": "调度",
        "rerouteTitle": "调度文档",
        "reset": "重置处理人",
        "resetTitle": "重置处理人",
        "split": "增加分支",
        "splitTitle": "增加拆分分支",
        "retract": "撤回",
        "retractTitle": "待办撤回",
        "rollback": "流程回溯",
        "rollbackTitle": "回溯到指定的环节，不保留流程记录",
        "delete": "删除文档",
        "deleteTitle": "删除文件",
        "print": "打印",
        "printTitle": "打印文档",
        "press": "催促办理",
        "pressTitle": "催促办理",
        "pause": "挂起",
        "pauseTitle": "待办挂起",
        "resume": "挂起恢复",
        "resumeTitle": "从挂起状态恢复",
        "downloadAll": "一键下载",
        "downloadAllTitle": "一键下载"
    }
};
