MWF.xApplication.process.FormDesigner.LP = {
    "title": "表单编辑",
    "newForm": "新建表单",
    "property": "属性",
    "tools": "工具",
    "all": "全部",

    "repetitionsId": "重复的组件标识符",
    "notNullId": "组件标识符不能为空",
    "notNumberId": "组件标识符不能为纯数字",
    "notDoubleDotId": "组件标识符不能包含连续的两个点号",
    "notSpecialCharacterId": "组件标识中不能包含下列字符：!{}<>,;'\"",
    "history": "历史",
    "componentTree": "组件树",
    "invalidElementUIId": "由于Element组件的数据需要做双向绑定，标识请不要和配置项重名，如下：",

    "button":{
        "ok": "确定",
        "cancel": "取消"
    },
    "version" : {
        "title" : "查看表单版本记录",
        "close" : "关闭",
        "no":"序号",
        "updateTime":"更新时间",
        "op":"操作",
        "person":"更新人",
        "resume" : "恢复",
        "resumeConfirm" : "恢复确认",
        "resumeInfo" : "您确认是否需要执行表单恢复操作？确认恢复后当前表单会更新，需要手动保存当前表单才会生效。",
        "resumeSuccess" :"恢复成功"
    },
    "notice": {
        "save_success": "表单保存成功！",
        "saveTemplate_success": "表单模板保存成功！",
        "saveTemplate_inputName": "请输入模板标题",
        "saveTemplate_inputCategory": "请确定模板分类",

        "deleteElementTitle": "删除表单元素确认",
        "deleteElement": "是否确定删除当前元素，及其子元素吗？",

        "deleteRowTitle": "删除表格行确认",
        "deleteRow": "删除当前行将删除该行所有单元格中的内容，是否确定删除当前选中的行？",
        "deleteColTitle": "删除表格列确认",
        "deleteCol": "删除当前行将删除该列所有单元格中的内容，是否确定删除当前选中的列？",
        "deleteEventTitle": "删除事件确认",
        "deleteEvent": "是否确定删除当前事件吗？",

        "deleteActionTitle": "删除操作确认",
        "deleteAction": "是否确定删除当前操作吗？",

        "deleteButtonTitle": "删除操作确认",
        "deleteButton": "确定要删除当前操作按钮吗？",

        "notUseModuleInMobile": "移动端不支持此组件",

        "changeToSequenceTitle": "确认",
        "changeToSequence": "此操作会删除已经添加的组件，确定要改成“序号”列吗？"
    },

    "formAction": {
        "insertRow": "插入行",
        "insertCol": "插入列",
        "deleteRow": "删除行",
        "deleteCol": "删除列",
        "mergerCell": "合并单元格",
        "splitCell": "拆分单元格",
        "move": "移动",
        "copy": "复制",
        "delete": "删除",
        "add": "添加",
        "cut": "剪切",
        "paste": "黏贴",
        "open": "打开",
        "script": "脚本",
        "create": "创建",
        "mergeCell": "合并单元格",
        "styleBrush": "格式刷",
        "insertTop" : "插入到顶部",
        "insertBottom" : "插入到底部",
        "insertBefore" : "插入到前面",
        "insertAfter" : "插入到后面",
        "injectNotice" : "按住Ctrl松开鼠标精确定位",
        "selectedContainer": "选择父对象",
        "property": "属性",
        "batchModify": "批量修改",
        "selectParent": "选择上级组件"
    },

    "actionbar": {
        "readhide": "设置阅读时是否显示",
        "edithide": "设置编辑时是否显示",
        "hideCondition": "设置隐藏条件",
        "title": "标题",
        "img": "图标",
        "action": "操作",
        "condition": "显示条件",
        "editScript": "操作脚本编辑",
        "editCondition": "隐藏条件编辑（返回true隐藏操作）",
        "up" : "上移",
        "property" : "属性",
        "addCustomTool" : "添加自定义操作",
        "delete" : "删除",
        "setProperties" : "设置操作属性",
        "restoreDefaultTool" : "恢复删除的系统操作",
        "selectDefaultTool" : "选择系统操作",
        "setReaded" : "标记为已阅",
        "readed" : "已阅"
    },
    "isSave": "正在保存，请稍候...",
    "scriptIncluder" : {
        "yes" : "是",
        "no" : "否",
        "selectScript" : "选择脚本：",
        "repeatAddScriptNotice" : "请不要重复添加脚本",
        "selectScriptNotice" : "请先选择脚本",
        "asyncLoad" : "异步加载：",
        "asyncLoadScript" : "异步加载脚本：",
        "syncLoadScript" : "同步加载脚本：",
        "delete_title": "取消加载脚本确认",
        "delete_text": "您确定要取消加载选择的脚本？"
    },
    "dictionaryIncluder" : {
        "selectDictionary" : "选择：",
        "repeatAddDictionaryNotice" : "请不要重复添加数据字典",
        "rootDictionaryExistNotice" : "已经添加了该数据字典的根路径，无需再添加",
        "parentDictionaryExistNotice" : "已经添加了该数据字典的父路径，无需再添加",
        "subDictionaryExistNotice" : "已经存在该数据字典的子路径，请先删除再添加",
        "selectDictionaryNotice" : "请先选择数据字典",
        "path" : "路径：",
        "delete_title": "取消加载数据字典确认",
        "delete_text": "您确定要取消加载选择的数据字典？"
    },
    "validation": {
        "validation": "校验",
        "anytime": "任何时候",
        "decision": "选择决策",
        "decisionName": "<决策名>",
        "value": "值",
        "length": "值长度",
        "valueInput": "<值>",
        "isnull": "为空",
        "notnull": "不为空",
        "gt": "大于",
        "lt": "小于",
        "equal": "等于",
        "neq": "不等于",
        "contain": "包含",
        "notcontain": "不包含",
        "prompt": "提示",
        "add": "添加",
        "modify": "修改",
        "when": "当",
        "as": "时",
        "inputDecisionName": "请输入决策名称",
        "inputValue": "请输入值",
        "inputPrompt": "请输入提示内容",
        "delete_title": "删除校验内容确认",
        "delete_text": "您确定要删除此项校验码？"
    },

    "datagrid" : {
        "import" : "导入",
        "export" : "导出"
    },

    "selectIcon": "选择图标",
    "selectImage": "选择图片",
    "selectApplication" : "选择应用",
    "dutyInputTitle": "添加职务参数",
    "dutyInput": "请为职务“{duty}”确定组织",
    "select": "选择",
    "empty": "清空",

    "creatorUnit": "拟稿人所在组织",
    "currentUnit": "处理人所在组织",
    "selectUnit": "选择组织",
    "scriptUnit": "使用脚本",

    "creatorCompany": "拟稿公司",
    "creatorDepartment": "拟稿部门",
    "currentCompany": "当前公司",
    "currentDepartment": "当前部门",

    "deleteDutyTitle": "移除职务确认",
    "deleteDutyText": "您确认要移除职务“{duty}”吗？",

    "saveTemplate": "保存为表单模板",
    "templateName": "模板名称",
    "templateCategory": "模板分类",
    "templateDescription": "模板描述",
    "save": "保存",
    "cancel": "取消",
    "newCategory": "新分类",
    "mustSelectFormStyle" : "必须选择一种表单样式",
    "notValidJson" : "错误的json格式",
    "mustSelectDict" : "请先选择数据字典",
    "mustSelect": "请选择",

    "imageClipper" : "图片编辑",

    "clearNoDomModuleTitle" : "清除未在HTML树中的组件配置",
    "clearNoDomModuleContent" : "是否清除未在HTML树中的组件配置？清除后需要保存生效。",

    "refreshDatatemplateImpExpTitle": "导入字段确认",
    "refreshDatatemplateImpExpContent": "本操作从数据模板的内部组件获取字段。如果执行本操作，之前配置的字段会被替换，是否继续？",
    "handWriting": "手写",

    "filter": {
        "and": "并且",
        "or": "或者",
        "equals": "等于",
        "notEquals": "不等于",
        "greaterThan": "大于",
        "greaterThanOrEqualTo": "大于等于",
        "lessThan": "小于",
        "lessThanOrEqualTo": "小于等于",
        "like": "匹配",
        "notLike": "不匹配",
        "from" : "从",
        "value" : "值"
    },
    "mastInputPath": "请输入数据路径",
    "mastInputTitle": "请输入标题",
    "delete_filterItem_title": "删除过滤条件确认",
    "delete_filterItem": "您确定要删除当前过滤条件吗？",

    "subformNameConflictTitle": "子表单字段名称冲突",
    "subformNameConflictInfor": "子表单的以下字段名称和现有表单冲突：\n{name}",
    "subformConflictTitle": "子表单嵌入错误",
    "subformConflictInfor": "您不能重复嵌入同一个子表单",

    "subformNestedTitle": "子表单嵌入错误",
    "subformNestedInfor": "不能相互嵌套的嵌入子表单",
    "checkSubformNestedError" : "您选择的子表单存在相互嵌套的情况，请检查！",

    "checkSubformTitle": "表单保存校验",
    "checkFormSaveError": "无法保存表单，原因如下：<br>",
    "checkSubformPcInfor": "PC表单中，有以下子表单字段冲突：<br>{subform}<br>",
    "checkSubformMobileInfor": "Mobile表单中，有以下子表单字段冲突：<br>{subform}",

    "implodeError": "要导入的数据格式有误",
    "implodeEmpty": "请在编辑框中填入要导入的数据",
    "implodeConfirmTitle": "导入确认",
    "implodeConfirmText": "导入数据将清除当前页面，并无法撤销，您确定要导入吗？",

    "design": "设计",
    "script": "脚本",
    "html": "HTML",
    "css": "CSS",
    "byModule": "按设计元素",
    "byPath": "按脚本类型",
    "events": "事件",
    "pageform": "页面",
    "importO2": "从O2数据导入",
    "importHTML": "从HTML导入",
    "importOffice": "从WORD导入（仅支持Word 97-2003文件 *.doc）",
    "importO2_infor": "请将O2格式的表单数据拷贝到以下编辑器中。（使用表单或页面设计器工具条上的“导出”按钮，获取表单数据）<br/>按下Ctrl+Alt+I可格式化数据",
    "importHTML_infor": "请将HTML数据拷贝到以下编辑器中。按下Ctrl+Alt+I可格式化数据",
    "importHTML_infor2": "请将CSS数据拷贝到以下编辑器中。按下Ctrl+Alt+I可格式化数据",
    "importOffice_infor": "请选择一个Word或Excel文件。",
    "import_ok": "导入",
    "import_cancel": "取消",
    "import_option1": "在表格的空单元格中添加输入框",
    "import_option2": "去除空元素",
    "implodeOfficeEmpty": "请先选择要导入的Word或Excel文件",

    "scriptTitle": {
        "validationOpinion": "表单意见校验",
        "validationRoute": "表单路由校验",
        "validationFormCustom": "表单校验",
        "defaultValue": "默认值",
        "validation": "校验脚本",
        "sectionByScript": "区段依据",
        "itemScript": "可选值脚本",
        "iframeScript": "iframe脚本",
        "labelScript": "文本值",
        "rangeKey": "组织范围",
        "identityRangeKey": "身份组织范围",
        "unitRangeKey": "组织选择范围",
        "rangeDutyKey": "职务范围",
        "exclude": "选择排除脚本",
        "cookies": "数据源请求cookies",
        "requestBody": "数据源请求消息体",
        "jsonText": "数据文本",
        "dataScript": "树控件脚本",
        "itemDynamic": "动态选项脚本",
        "defaultData": "数据网格默认值",
        "editableScript": "数据网格是否可编辑",
        "config": "HTML编辑框配置",
        "filterScript": "流程记录过滤",
        "readScript": "Office只读脚本",
        "fileSite": "Office文件site脚本",
        "subformScript": "子表单脚本",
        "selectedScript": "视图选择脚本",
        "action.tools": "操作按钮"
    },
    "copyed": "已复制",
    "selectorButton" : {
        "ok" : "确　定",
        "cancel" : "取 消"
    },
    "modules": {
        "label": "文本",
        "textfield": "文本字段",
        "number": "数字字段",
        "currency": "货币字段",
        "org": "人员组织",
        "calendar": "日期选择",
        "textarea": "多行文本",
        "select": "下拉框",
        "radio": "单选框",
        "checkbox": "多选框",
        "combox": "组合框",
        "opinion": "意见框",
        "button": "按钮",
        "Address": "地址",
        "Actionbar": "操作条",
        "Sidebar": "侧边操作条",
        "image": "图片",
        "imageclipper": "图片编辑",
        "attachment": "附件",
        "div": "容器",
        "table": "表格",
        "datagrid": "数据网格(过时)",
        "datatable": "数据表格",
        "datatemplate": "数据模板",
        "subform": "子表单",
        "ViewSelector": "选择视图",
        "view": "嵌入视图",
        "stat": "嵌入统计",
        "html": "HTML",
        "common": "通用元素",
        "tab": "分页",
        "tree": "树",
        "log": "流程记录",
        "monitor": "流程监控",
        "iframe": "Iframe",
        "documenteditor": "公文编辑器",
        "htmledit": "HTML编辑器",
        "office": "Office控件(Ntko)",
        "yozoOffice" : "永中控件",
        "statementSelector": "选择查询视图",
        "statement": "嵌入查询视图",
        "SmartBI":"SmartBI报表",

        "group_all": "所有组件",
        "group_form": "表单组件",
        "group_layout": "布局组件",
        "group_process": "流程组件",
        "group_filetext": "文件编辑组件",
        "group_function": "功能组件",
        "group_element": "Element组件",

        "el_container": "布局容器",
        "el_icon": "图标",
        "el_button": "按钮",
        "el_radio": "单选框",
        "el_checkbox": "多选框",
        "el_select": "选择器",
        "el_input": "输入框",
        "el_autocomplete": "自动完成框",
        "el_cascader": "级联选择器",
        "el_number": "计数器",
        "el_switch": "开关",
        "el_slider": "滑块",
        "el_time": "时间",
        "el_date": "日期",
        "el_datetime": "日期时间",
        "el_rate": "评分",
        "el_colorpicker": "颜色选择",
        "el_tree": "树",
        "el_dropdown": "下拉菜单",
        "el_carousel": "幻灯片",
        "el-menu": "导航菜单",
        "el_common": "通用",

        "importer": "数据导入",
        "readLog": "阅读记录",
        "writingBoard": "手写板",
        "tinymceEditor": "Tinymce编辑器",
        "relatedLink": "相关推荐",
        "associatedDocument": "关联文档",
        "security": "密级标识",

        "securityInfo": "只允许一个“密级标识”字段",
    },
    "propertyTemplate": {
        "base": "基本",
        "event": "事件",
        "html": "HTML",
        "json": "JSON",
        "action": "操作",
        "select": "选择",

        "id": "标识",
        "name": "名称",
        "description": "描述",
        "appearance": "外观类型",
        "style": "样式",
        "attribute": "属性",
        "imageStyle": "图片样式",

        "hideSystemTools": "系统操作",
        "show": "显示",
        "hide": "隐藏",
        "readed": "已阅",

        "category": "分类",
        "formStyle": "表单样式",
        "icon": "图标",
        "printForm": "打印表单",
        "preloadScript": "预加载脚本",
        "script": "脚本",
        "dict": "数据字典",
        "dictName": "字典名称",
        "dictPath": "数据路径",
        "valueKey": "值属性名",
        "textKey": "文本属性名",
        "valueColumn": "值列",
        "textColumn": "文本列",
        "dictKeyNote": "如返回对象数组，需配置值属性名或文本属性名",
        "firstOptionEnable": "使用第一个选项",
        "firstOption": "第一个选项",
        "copy": "复制",
        "paste": "粘贴",
        "language": "语言包",
        "languageScript": "语言包脚本 (S)",
        "languageInfo": "返回包含语言信息的JSON对象；o2.language获取当前语言信息",
        "SubmitUI": "提交界面",
        "submit": "提交",
        "systemDefault": "系统默认",
        "selectForm": "选择表单",
        "computeForm": "计算表单",
        "application": "应用",
        "form": "表单",
        "crossApplication": "跨应用",
        "computeSubmitAnnotation1": "应用名称、别名、id",
        "computeSubmitAnnotation2": "表单名称、id",
        "computeWidgetAnnotation2": "部件名称、id",
        "thisApplication": "本应用",
        "submitFormScript": "提交表单脚本",
        "flowActionScript": "提交（继续流转）操作脚本",
        "handwritingSetting": "手写意见设置",
        "enableHandwriting": "启动手写意见",
        "handwritingWidth": "手写板宽度",
        "effectivePC": "pc端有效",
        "handwritingHeight": "手写板高度",
        "promptBoxFlow": "流转后提示框",
        "yes": "是",
        "no": "否",
        "usedNewWindow": "仅用于新浏览器窗口打开时",
        "promptLocation": "提示框位置",
        "lefttop": "左上",
        "righttop": "右上",
        "leftbottom": "左下",
        "rightbottom": "右下",
        "center": "中央",
        "prompt": "提示框",
        "notClose":"不关闭",
        "closeInfo": "秒后自动关闭",
        "afterFlow": "流转后",
        "closeWindow": "关闭窗口",
        "redirect": "重定向",
        "redirectScript": "重定向地址脚本",
        "returnUrl": "返回一个URL用于重定向",
        "check": "校验",
        "checkOpinion": "校验意见",
        "checkRoute": "校验路由",
        "checkFlow": "流转校验",
        "checkOtherFlow": "校验其他流转方式",
        "checkOtherFlowNote": "当加签、重置、退回时执行该校验脚本,通过this.form.currentRouteName获取流转方式（加签为：addTask,重置为: reset,退回为：goBack），通过this.form.opinion获取意见，通过this.form.flowData获取流转的其他参数",
        "noEventInfo": "注：当以子表单嵌入时，下列事件不会被执行",
        "none": "无",
        "default": "默认",
        "byScript": "根据脚本",
        "scriptLib": "脚本库",
        "byFormat": "根据格式",
        "table": "表格",
        "languageDefaultInfoScript": "系统会自动载入名称为 \"lp-\"+o2.language 的脚本，作为语言包",
        "languageDefaultInfoDict": "系统会自动载入名称为 \"lp-\"+o2.language 的数据字典，作为语言包",

        "prefix": "前缀",
        "suffix": "后缀",

        "value": "值",
        "textValue": "固定值",

        "showIcon": "显示图标",
        "readonly": "是否只读",
        "AIInput": "智能输入",
        "inputStyle": "Input样式",
        "itemStyle": "条目样式",
        "actionStyles": "按钮样式",
        "imageStyles": "图片样式",
        "compute": "计算",
        "create": "创建",
        "save": "保存",
        "linkStyles": "条目样式",

        "defaultValue": "默认值",
        "verificationScript": "校验脚本",
        "verificationLineScript": "单行编辑完成后校验脚本",
        "section": "区段",
        "enableSection": "启用区段",
        "sectionBy": "区段依据",
        "handler": "处理人",
        "handlerUnit": "处理人所在组织",
        "activityId": "活动ID",
        "splitValue": "拆分值",

        "enableSectionMerge": "区段合并",
        "showSectionKey": "显示区段值",
        "editByMerge": "合并编辑(删除区段值)",
        "sectionMergeSortScript": "排序脚本",
        "sectionNodeStyles": "区段条目样式",
        "sectionKeystyles": "区段值样式",
        "sectionContentStyles": "区段内容样式",
        "mergeDisplay": "只读",
        "editCurrentSection": "编辑（允许编辑当前区段）",
        "mergeEdit": "编辑（删除区段值后合并数据）",
        "sectionKey": "区段值",
        "sectionKeyScript": "区段值脚本",
        "textValue1": "文本值",
        "mergeType": "合并方式",
        "amountValue": "合计数值",
        "averageValue": "平均值",
        "sectionMergeEditScript": "合并数据脚本",
        "sectionMergeReadHtmlScript": "展现的html脚本",
        "sectionMergeReadDataScript": "数据脚本",
        "htmlScript": "html脚本",
        "dataScript": "数据脚本",
        "bySection": "按区段",
        "byModule": "按组件",
        "totalRow": "总计行",
        "sectionAmountCellStyle": "区段总计单元格样式",
        "showAllSection": "显示所有区段",

        "rangeByDatetime": "日期时间范围",
        "rangeByDateAndTime": "日期范围和时间范围",
        "rangeByDate": "日期范围",
        "rangeByTime": "时间范围",
        "rangeByOhter": "其他",
        "enableDate": "有效日期",
        "enableHours": "有效小时范围",
        "enableMinutes": "有效分钟范围",
        "enableSeconds": "有效秒范围",

        "decimal": "小数点",

        "showCard": "显示卡片",
        "allowInput": "允许输入",
        "dataStructure": "数据保存",
        "complete": "完整",
        "simple": "精简",
        "separator": "分隔符",
        "digitsToSeparate": "分隔符位数",
        "digitsToSeparateNote": "每几个数位添加,分隔符，如千分位为每3位数添加分隔符，那么填3。",
        "asyncMode": "异步模式",
        "asyncLoad": "异步加载",

        "identity": "身份",
        "unit": "组织",
        "duty": "职位",
        "group": "群组",
        "person": "个人",

        "defaultValueScript": "默认值脚本",
        "showText": "显示文本",
        "showTextScript": "显示文本脚本",
        "unitSelectConfig": "人员组织选择配置",
        "selectType": "选择类型",
        "selectCount": "选择数量",
        "returnValue": "结果返回",

        "readonlyScript": "只读脚本",

        "selectTypeInfo": "参与流程处理请选身份！",
        "selectTypeInfo2": "注意，个人无法参与流程处理！",
        "checkEmpower": "检查待办授权",
        "onlyCustom": "只使用自定义选项",
        "unitRange": "组织范围",
        "allUnit": "所有组织",
        "specifyUnit": "指定组织",
        "draftUnit": "拟稿人所在的组织",
        "currentUnit": "当前人所在的组织",
        "inUnit": "直接所属组织",
        "levelIs": "第",
        "levelUnit": "层组织",
        "unitTypeIs": "类型为",
        "deUnit": "的组织",
        "expandNext": "展开下级",
        "selectUnit": "选择组织",
        "formData": "表单数据",
        "dutyRange": "职务范围",
        "all": "所有",
        "all2": "全部",
        "specifyDuty": "指定职务",
        "byUnit": "按组织",
        "byDuty": "按职务",
        "showLevel": "展现层级",
        "byDutyUnit": "按职务所在组织",
        "byIdentityUnit": "按身份所在组织",
        "selectDuty": "选择职务",
        "customOption": "自定义选项",
        "useScriptAddIdOrPerson": "使用脚本添加身份/个人",
        "unitType": "组织类型",
        "selectRange": "选择范围",
        "specifyGroup": "指定群组",
        "exclude": "排除",
        "excludeInfo": "通过编写脚本排除组织、身份、个人和群组的选择范围",
        "firstLevelSelectable": "允许选择第一层",

        "dateTime": "日期时间",
        "dateTime2": "日期时间",
        "dateOnly": "仅日期",
        "monthOnly": "仅月份",
        "yearOnly": "仅年度",
        "timeOnly": "仅时间",
        "weekOnly": "第几周",
        "multidate": "多个日期",
        "datetimerange": "日期时间范围",
        "daterange": "日期范围",
        "timerange": "时间范围",
        "monthrange": "月份范围",
        "selectSecond": "是否选择秒",
        "timeSelectType": "时间选择方式",
        "timeSelectType_slider" : "滑块",
        "timeSelectType_select" : "下拉",
        "format": "格式化",

        "rateTexts": "极差, 失望, 一般, 满意, 惊喜",
        "allowHalf": "允许半选",
        "lowThreshold": "低-中界限值",
        "lowThresholdNote": "注：值本身被划分在低分中",
        "highThreshold": "中-高界限值",
        "highThresholdNote": "注：值本身被划分在高分中",
        "lowColor": "低分值颜色",
        "mediumColor": "中等分值颜色",
        "highColor": "高分值颜色",
        "voidColor": "未选中颜色",
        "disabledVoidColor": "只读时未选中颜色",
        "showAfter": "后方显示",
        "showScore": "显示分数",
        "textColor": "文本颜色",
        "textContent": "文本内容",

        "showAlpha": "显示透明度",
        "colorFormat": "颜色格式",

        "nodeKey": "节点的唯一标识key",
        "nodeKeyNote": "每个树节点用来作为唯一标识的属性，整棵树应该是唯一的。",
        "renderAfterExpand": "展开节点后才渲染子节点",
        "defaultExpandAll": "默认展开所有节点",
        "highlightCurrent": "高亮当前选中节点",
        "currentNodeKey" : "当前选中节点key值",
        "expandOnClickNode": "点击展开",
        "clickNode": "点击节点时",
        "clickArrow": "点击箭头时",
        "checkOnClickNode": "点击选中",
        "clickCheckbox": "点击复选框时",
        "defaultExpandedkeys": "默认展开的节点",
        "defaultExpandedkeysNote": "返回默认展开的节点key数组, 如:return['2','4']",
        "showCheckbox": "允许选择",
        "defaultCheckedKeysNote": "返回默认勾选的节点key数组, 如:return['2','4']",
        "defaultCheckedkeys": "默认勾选的节点",
        "accordion" : "每次展开一个同级节点",
        "indent": "每级缩进",
        "dragdrop": "拖拽",
        "draggable": "允许拖拽",
        "allowDrag": "判断节点能否被拖拽",
        "allowDrop": "拖拽时判定目标节点能否被放置",
        "emptyText": "内容为空显示的文本",
        "allowDragNote": "this.event为传入节点，'return true'表示允许拖拽",
        "allowDropNote": "this.event 可以获取数据 { draggingNode, dropNode, type }。type 参数有三种情况：'prev'、'inner' 和 'next'，分别表示放置在目标节点前、插入至目标节点和放置在目标节点后。'return true'表示允许插入。",
        "loadFun": "加载子树数据脚本",
        "loadFunNote": "this.event.node为被点击的节点，this.event.resolve(data)为数据加载完成后的回调，data参数为子树数据",
        "dataScriptNote": "返回及每个节点格式：",
        "labelDescription":"节点文本",
        "childrenDescription":"下级节点",
        "disabledDescription":"启用选择后可用，当前选择框是否禁用",
        "isLeafDescription":"启用动态加载后可用，当前节点是否为叶子节点（默认不出现箭头）",
        "idDescription":"只展现可不需要。需要默认展开脚本、默认选中、默认勾选及脚本操作的时候必填。可以使用id或者基本属性里设置的key。",
        "settedKey": "设置的key",
        "customDescription": "其他自定义数据",

        "selectStyle": "Select样式",
        "options": "可选值",
        "optionScript": "可选值脚本",
        "defaultOptionScript": "默认可选值脚本",
        "divStyle": "容器样式",
        "buttonStyle": "按钮样式",
        "extendOptions": "其他可选值",

        "dynamic": "动态计算",
        "canSelectCount": "可选数量",
        "showSeparator": "显示分隔符",
        "optionDynamicScript": "可选值动态脚本",

        "handwriting": "手写",
        "writingBoard": "手写板",
        "width": "宽度",
        "height": "高度",
        "recording": "录音",
        "writingPreview": "手写预览",
        "commonIdea": "常用意见",

        "addressStyle": "Address样式",

        "location": "位置",
        "right": "右",
        "left": "左",
        "relocate": "重新定位",

        "image": "图片",
        "selectSrc": "选择资源",

        "imageCropping": "图片裁剪",
        "unlimited": "无限制",
        "fixedSize": "固定大小",
        "fixedRatio": "固定比例",
        "aspectRatio": "宽高比",

        "site": "site",
        "defaultSiteInfo":"（默认与标识相同）", //(The default is the same as the logo)
        "editInActivex": "在控件中编辑",
        "activexId": "控件标识",
        "showType": "显示方式",
        "switchStyle": "切换样式",
        "allow": "允许",
        "notAllow": "不允许",
        "uploadType": "允许上传类型",
        "wordDoc": "WORD文档",
        "excelDoc": "EXCEL文档",
        "pptDoc": "PPT文档",
        "textDoc": "文本文档",
        "imgDoc": "图片文件",
        "pdfDoc": "PDF文档",
        "zipDoc": "压缩文档",
        "audioDoc": "音频文档",
        "videoDoc": "视频文档",
        "otherDoc": "其他",
        "docSample": "填写样例：.doc, .docx, .xls",
        "uploadSize": "允许上传大小（M）",
        "uploadSizeInfo": "“0”表示上传大小没有限制",
        "uploadCount": "允许上传数量",
        "uploadCountInfo": "“0”表示上传数量没有限制",
        "changeSize": "改变大小",
        "useAttachmentStyle": "允许使用的附件样式",
        "list": "列表",
        "sequence": "序列",
        "preview": "预览",
        "attDefaultStyle": "默认附件样式",
        "readonlyMode": "只读模式",
        "allowUpload": "允许上载",
        "allowPreview": "允许预览",
        "allowDownload": "允许下载",
        "allowDownloadBatch": "允许批量下载",
        "allowEdit": "允许编辑",
        "officeTool": "Office预览/编辑工具",
        "allowDelete": "允许删除",
        "allowDelMyAtt": "仅允许本人上传的文件",
        "allowDelCurActivityAtt": "仅允许本活动上传的文件",
        "allowDelMyCurActivityAtt": "仅允许本活动且本人上传的文件",
        "allowReplace": "允许替换",
        "allowConfig": "允许设置权限",
        "allowOrder": "允许排序",
        "dblClickAttachment": "双击附件",
        "openAtt": "打开",
        "previewFirst": "优先预览",
        "previewAttachmentNote": "下列文件格式可直接预览：zip, pdf, ofd, png, jpg, bmp, jpeg, gif, js, css, java, json, xml, php, html, htm, xhtml, log, md, txt。下列格式需安装liberoffice: doc, docx, xls, xlsx, ppt, pptx。不在上述格式中的双击直接打开附件。",

        "actionBar": "操作条",
        "hideEditButton": "隐藏编辑操作组",
        "hideReadButton": "隐藏阅读操作组",
        "hideLayoutButton": "隐藏布局操作组",
        "hideSettingButton": "隐藏设置操作组",
        "hideModeButton": "隐藏模式操作",
        "showInDatagrid": "数据网格中的展现（过时）",
        "attachmentValidation": "上传时校验",
        "attachmentValidationNote": "可以通过this.target.uploadingFiles获取当前正在上传的附件。返回true表示通过，返回文本系统提示文本后中断上传。",
        "attachmentValidationScript": "上传时校验脚本",

        "hideEraserButton": "隐藏橡皮按钮",
        "hideEraserRadioButton": "隐藏橡皮大小按钮",
        "hideSizeButton": "隐藏粗细按钮",
        "hideColorButton": "隐藏颜色按钮",
        "hideImageButton": "隐藏插入图片按钮",
        "hideImageClipperButton": "隐藏图片剪切按钮",

        "tableSize": "表格大小",
        "row": "行",
        "col": "列",
        "tableWidth": "表格宽度",
        "pixel": "像素",
        "percent": "百分比",
        "borderWidth": "边框粗细",
        "cellpadding": "单元格边距",
        "cellspacing": "单元格间距",

        "containStyle": "容器样式",
        "containAttribute": "容器属性",
        "titleCellStyle": "标题单元格样式",
        "contentCellStyle": "内容单元格样式",
        "layoutCellStyle": "布局单元格样式",

        "contentTitleCellStyle": "内容标题单元格样式",
        "contentLineStyle": "内容行样式",
        "contentLineOverStyle": "内容行经过样式",

        "columns": "列数",
        "onTheLeft": "所选之左",
        "onTheRight": "所选之右",
        "rows": "行数",
        "onTheTop": "所选之上",
        "onTheBottom": "所选之下",
        "type": "类型",
        "titleCell": "标题单元格",
        "contentCell": "内容单元格",
        "layoutCell": "布局单元格",
        "other": "其他",

        "permission": "权限",

        "containerStyles": "容器样式",
        "tableAttribute": "表格属性",
        "border": "边框",
        "backgroundColor": "背景颜色",
        "alternateRow": "交替行",
        "tableStyle": "表格样式",
        "defaultData": "默认数据",
        "allowAdd": "允许添加",
        "allowSort": "允许排序",
        "exportImport": "导出导入",
        "enabled": "启用",
        "disabled": "禁用",
        "onlyExport": "仅导出",
        "onlyImport": "仅导入",
        "exportInfo": "注：序号、图片、手写板、附件和隐藏列不能导入导出。",
        "buttonLocation": "按钮位置",
        "centertop": "中上",
        "centerbottom": "中下",
        "importText": "导入按钮文本",
        "importExcel": "导入Excel",
        "exportExcel": "导出Excel",
        "importButtonStyle": "导入按钮样式",
        "exportFileName": "导出文件名称",
        "actionCellStyles": "操作单元格样式",
        "editCellStyles": "编辑单元格样式",
        "amountCellStyle": "总计单元格样式",
        "itemTitleStyle": "条目标题样式（仅移动端）",
        "canEdit": "是否可编辑",
        "exportText": "导出按钮文本",
        "exporButtonStyle": "导出按钮样式",

        "content": "内容",
        "serialNumber": "序号",
        "total": "合计",
        "notNeeded": "不需要",
        "totalValue": "合计数值",
        "totalCount": "合计数量",
        "showCol": "显示该列",
        "hideCol": "隐藏该列",

        "delayedLoading": "延时加载",
        "selectSubform": "选择子表单",
        "calculationSubform": "计算子表单",
        "subform": "子表单",
        "subformScript": "子表单脚本",

        "activeType": "激活方式",
        "click": "点击激活",
        "delay": "延迟激活",
        "immediately": "直接激活",
        "buttonText": "按钮文本",
        "delayNote": "选择延时激活时，需要使用this.form.get(moduleId).active()激活",

        "viewBox": "视图选择框",
        "viewBoxTitle": "选择框标题",
        "columnTitle": "列标题",
        "expandDefault": "默认展开",
        "expand": "展开",
        "collapse": "折叠",
        "singleChoice": "单选",
        "multipleChoice": "多选",
        "view": "视图",
        "statement": "查询",
        "boxTitleStyle": "选择框标题样式",
        "boxItemStyle": "选择框条目样式",
        "selectResultProcessing": "选择结果处理",
        "resultProcessing": "处理方式",
        "assignValue": "赋值",
        "assignValueForResult": "选择结果赋值",
        "selectResult": "选择结果",
        "defaultSelectedLineScript": "默认选中行脚本",
        "allowSelectiLineScript": "允许选择行脚本",
        "reserve": "保留",
        "changeViewReserve": "更换视图后重选，保留原视图数据",
        "changeViewNotReserve": "更换视图后重选，删除原视图数据",
        "filter": "过滤",
        "title": "标题",
        "path": "路径",
        "servicePath": "服务路径",
        "servicePathNote" : "如：/jaxrs/user/hotpic/filter/list/page/1/count/6",
        "dataItemPath": "数据项路径",
        "dataItemPathNote": "需显示数据的路径，多层用点号'.'分隔，如：data",
        "dataScriptNote2": "脚本返回Promise对象或数据，如：return this.Actions.load('x_hotpic_assemble_control').HotPictureInfoAction.listForPage(1, 6);",
        "dataType": "数据类型",
        "text": "文本",
        "number": "数字",
        "currencySymbol": "货币符号",
        "currencySymbolStyles": "货币符号样式",
        "datetime": "日期",
        "boolean": "布尔",
        "resultType": "结果保存类型",
        "asDefaultFilter": "作为默认过滤条件",
        "asCustomFilter": "作为自定义过滤数据",
        "logic": "逻辑",
        "and": "并且(and)",
        "or": "或者(or)",
        "compare": "比较",
        "equals": "等于",
        "notEquals": "不等于",
        "greaterThan": "大于",
        "greaterThanOrEqualTo": "大于等于",
        "lessThan": "小于",
        "lessThanOrEqualTo": "小于等于",
        "like": "匹配",
        "notLike": "不匹配",
        "range": "范围",
        "in": "包含",
        "true": "是",
        "false": "否",
        "filterValueInfo": "多值用半角逗号(,)隔开",
        "defaultFilter": "默认过滤条件",
        "customFilter": "自定义过滤数据",
        "filterCond": "过滤条件",
        "filterNote": "注：返回视图的过滤条件数组，格式请查看",

        "titleStyle": "标题样式",
        "dataStyle": "数据样式",
        "loadNow": "立即载入",
        "showTitle": "显示标题",
        "allowSelect": "选择文件",

        "stat": "统计",
        "showChart": "显示图表",
        "showLegend": "显示图例",
        "showTable": "显示表格",
        "showRowToColumn": "行列转换",
        "chartNodeStyles": "图表容器样式",
        "tableNodeStyles": "表格容器样式",

        "selectTag": "选择标签",
        "elementTag": "元素标签",
        "innerHtml": "内置HTML",

        "delayedTabInfo": "延时加载为是时，未显示的tab页内容不会加载，只有在tab页第一次显示时才会加载内容",
        "tabContainerStyle": "Tab容器样式",
        "contentContainerStyle": "内容容器样式",
        "baseTabStyle": "基本Tab样式",
        "baseTabSpanStyle": "基本Tab字体样式",
        "currentTabStyle": "当前Tab样式",
        "currentTabSpanStyle": "当前Tab字体样式",

        "data": "数据",
        "treeAreaStyle": "tree区域样式",
        "treeNodeStyle": "tree节点样式",
        "treeNodeFontStyle": "tree节点字体样式",
        "treeSelectNodeFontStyle": "当前tree节点字体样式",

        "record": "记录",
        "recordTable": "表格",
        "recordMedia": "多媒体（手写或语音）",
        "expandHandwritten": "展开手写意见",
        "handwrittenWidth": "手写意见宽度",
        "validOnPcSide": "（pc端有效）",
        "handwrittenHeight": "手写意见高度",
        "logFormat": "格式",
        "logFormatScript": "格式脚本",
        "logHtmlScript": "html脚本",
        "currentPerson": "当前处理人",
        "readReaded": "待阅已阅",
        "readTitle": "待阅标题",
        "readedTitle": "已阅标题",
        "exactMatch": "精确匹配",
        "filterActivity": "活动过滤",
        "filterActivityAlias": "活动别名过滤",
        "filterPerson": "处理人过滤",
        "filterRoute": "路由过滤",
        "filterScript": "通过脚本过滤",
        "activity": "活动",
        "opinionGroup": "意见组",
        "unitLevelName":"组织层次名",
        "unitLevel": "组织层次",
        "sortInCategory": "分类内排序",
        "sortByActivity": "按活动排序",
        "sortByTimeAsc": "按时间顺序",
        "sortByTimeDesc": "按时间倒序",
        "noSort": "不排序",
        "categoryTable": "分类表格",
        "categoryTableAttr": "分类表格属性",
        "categoryTableStyle": "分类表格样式",
        "categoryTitleCellStyle": "分类标题单元格样式",
        "categoryContentCellStyle": "分类内容单元格样式",
        "categoryContentCellInnerStyle": "分类内容单元格内部样式",
        "expandOrCollapse": "展开折叠",
        "defaultExpandCount": "默认展开条数",
        "expandHtml": "展开节点HTML",
        "collapseHtml": "折叠节点HTML",
        "relativedLinkField": "可选字段：flag,title,createTime,updateTime,creatorPerson,creatorUnit,score",
        "documentListShow": "文档列表展现",
        "associatedDocumentField": "可选字段：targetTitle,targetStartTime,targetCreatorPersonCn,targetType,targetCategory",
        "associatedDocumentScriptNote": "\n通过this.line可以获取当前条目数据",

        "fileTemplate": "文件模板",
        "systemTemplate": "系统模板",
        "customTemplate": "自定义模板",
        "selectTemplate": "选择模板",
        "templatePath": "模板路径",
        "templateId": "模板标识",
        "edit": "编辑",
        "printFile": "打印正文",
        "viewTraces": "查看痕迹",
        "viewTracesFullScreen": "痕迹全屏",
        "viewTracesFullScreenInfo": "查看痕迹时全屏显示",
        "editScript": "编辑脚本",
        "printScript": "允许打印脚本",
        "viewTracesScript": "允许查看痕迹脚本",
        "handwrittenApproval": "手写签批",
        "handwrittenApprovalScript": "允许手写签批脚本",
        "handwrittenApprovalType": "签批类型",
        "savetext": "保存正文（作为背景）",
        "notsavetext": "不保存正文",
        "handwrittenApprovalTypeInfo": "保存正文适用于签批后流程正文会修改的情况",
        "zoom": "设置缩放",
        "zoomInfo": "用户是否可自定义缩放比例",
        "fullWidth": "全角转换",
        "fullWidthInfo": "选择“是”自动将输入的半角空格转换为全角",
        "paragraphIndent": "段落缩进",
        "paragraphIndentInfo": "选择“是”每段首行自动缩进",
        "doublePage": "双页显示",
        "doublePageInfo": "是否允许双页显示",
        "fullScreen": "全屏",
        "fullScreenInfo": "是否允许全屏显示",
        "wordConversion": "WORD转换",
        "wordConversionType": "转换方式",
        "isConversionSeal": "转换印章",
        "wordConversionWithService": "使用服务",
        "fileName": "文件名",
        "fileSite": "附件site",
        "addPageNumber": "添加页码",
        "addPageNumberInfo": "转换Word后是否要添加页码",
        "whenConversion": "何时转换",
        "onSubmit": "提交时",
        "onSave": "保存时",
        "conversionCondition": "转换条件",
        "alwaysConvert": "始终转换",
        "whenConditionsMet": "满足条件时转换",
        "static": "固定",
        "wordConversionEncryption": "编辑保护",
        "wordConversionEncryptionInfo1": "（仅OOXML方式可用）",
        "wordConversionEncryptionInfo": "如果选择“是”，将对转换后的文件进行编辑保护，限制对转换的Word文档的所有编辑。",
        "wordEncryptionPasswordType": "密码",
        "toWordPasswordScript": "密码脚本",
        "wordEncryptionPasswordInput":"输入密码",
        "toWordPasswordScriptInfo": "返回一个字符串作为密码。注意：管理员或文书等相关人员需要知晓此密码，否则转换后的文件将无法解除保护",

        "config": "配置",
        "copiesSecretPriority": "份数密级紧急度",
        "isShow": "是否显示",
        "copies": "份数",
        "auto": "自动",
        "showScript": "显示脚本",
        "bindValue": "绑定值",
        "bindValueScript": "绑定值脚本",
        "secret": "密级",
        "priority": "紧急度",
        "redHeader": "红头",
        "redLine": "红线",
        "fileNo": "文号",
        "signer": "签发人",
        "subject": "文件标题",
        "editSubjectInfo": "标题允许编辑时，请不要绑定数据",
        "mainSend": "主送",
        "attachment": "附件",
        "attachmentText": "附件内容",
        "attachmentInfor": "[点击此处编辑附件内容]",
        "issuanceUnit": "成文单位",
        "issuanceDate": "成文日期",
        "annotation": "附注",
        "copyto": "抄送",
        "copyto2": "发",
        "editionUnit": "印发单位",
        "editionDate": "印发日期",
        "meetingAttend": "会议出席",
        "meetingLeave": "会议请假",
        "meetingSit": "会议列席",
        "meetingRecord": "会议记录",
        "customElement": "自定义元素配置",
        "subjectEditBindFormData": "同步数据路径",
        "fontFamily": "字体",

        "autoCorrect": "自动纠错",
        "ckeditorInfo": "更多属性帮助请查看",
        "ckeditorInfo2": "返回CKEditor的Config对象，用于编辑器初始化",
        "ckeditorInfo3": "更多事件帮助请查看",
        "tinymceInfo": "更多属性帮助请查看",
        "tinymceInfo2": "返回TinyMCE的Config对象，用于编辑器初始化",
        "tinymceInfo3": "queryLoad,postLoad,load和afterLoad事件为o2平台事件。其他事件为tinymce编辑器事件，可以通过this.target获取脚本环境，this.event获取事件对象，请查看",
        "base64Encode": "图片Base64编码",
        "imagePreview": "浏览原图",

        "ieOnly": "仅IE浏览器可用",
        "keepHistory": "是否保留历史版本",
        "openAttachment": "是否可打开附件",
        "attachmentId": "附件框标识",
        "attachmentReadonly": "附件只读",
        "autoSave": "自动保存",
        "historyCount": "保留版本数",
        "timeInterval": "时间间隔(分钟)",
        "showSummary": "无法启用控件时显示摘要",
        "byTemplate": "根据模板创建",
        "readonlyCondition": "满足条件时只读",
        "officeFileSite": "读取文件的site",
        "userTitle": "用户标题",
        "userId": "用户标识",
        "toolbar": "工具栏",
        "tools": "工具",
        "newDoc": "新建文档",
        "openLocal": "打开本地文件",
        "saveLocal": "保存到本地",
        "traceSwitch": "痕迹切换",
        "fullscreenMode": "全屏模式",
        "toolbarSwitch": "工具栏切换",
        "printPreview": "打印预览",
        "redFileButton": "套红按钮",
        "stampButton": "盖章按钮",
        "showHistory": "查看历史版本",
        "showTitleBar": "是否显示标题栏",
        "showMenuBar": "是否显示菜单栏",
        "showToolBar": "是否显示工具栏",
        "showStatusBar": "是否显示状态栏",
        "showZoom": "显示比例",
        "borderStyle": "边框样式",
        "borderColor": "边框颜色",
        "flat": "平面",
        "noCopy": "是否禁止拷贝",
        "keepTraces": "是否保留痕迹",
        "read": "阅读",
        "otherAttr": "其他属性",

        "querySelectBox": "查询选择框",
        "selectBoxTitle": "选择框标题",
        "query": "查询",
        "pathInfo": "注：路径的写法是\"表别名.字段名\"，如：o.title",
        "parameterNote": "注：对应查询语句和总数语句中的参数；\n如\":field\"的where条件，填写\"field\"；\n如\"?1\"的where条件，填写\"?1\"。",

        "source": "数据源",
        "method": "方法",
        "systemSource": "平台数据源",
        "applicationService": "服务应用",
        "parameter": "参数",
        "requestBody": "请求正文",
        "test": "测试",
        "hostPort": "主机/端口",

        "flow": "继续流转",

        "widget": "部件",
        "widgetScript": "部件脚本",
        "parameterScript": "参数脚本 (返回对象)",
        "insertWidget": "插入部件元素",
        "selectWidget": "选择部件",
        "selectPortal": "选择门户",
        "inDiv": "是否包裹div",

        "outerSideModuleId": "外部相关组件标识",
        "addButtonId": "添加按钮标识",
        "deleteSelectedButtonId": "删除选中条目按钮标识",
        "selectAllModuleId": "全选组件标识",
        "selectedValue": "选中值",
        "innerSideModuleId": "内部相关组件标识",
        "deleteButtonId": "删除按钮标识",
        "sequenctModuleId": "序号组件标识",
        "selectModuleId": "选中组件标识",
        "defaultShow": "默认显示",
        "item": "项",
        "maxItemCount": "最多添加",
        "minItemCount": "最少保留",
        "dtImportInfor": "注：图片、附件、数据表格、子数据模板不能导入导出。",
        "importButtonId": "导入按钮标识",
        "exportButtonId": "导出按钮标识",
        "importExporConfig": "导入导出字段配置",
        "validationPopFormConfig": "校验弹出框配置",
        "validationPopFormHeight": "弹出框高度",
        "validationPopFormWidth": "弹出框宽度",
        "validationTableStyle": "校验表格样式",
        "validationTitleTdStyle": "校验标题单元格样式",
        "validationContentTdStyle": "校验内容单元格样式",
        "validationTableAttribute": "校验表格属性",
        "count": "数量",
        "import" : "导入",
        "datatableEditMode": "编辑方式",
        "datatableEditModeValue": ["每次编辑单行","同时编辑多行"],
        "onlyPc": "仅PC端可用",

        "size": "尺寸",
        "color": "颜色",
        "el_bt_default": "默认按钮",
        "el_bt_primary": "主要按钮",
        "el_bt_success": "成功按钮",
        "el_bt_warning": "警告按钮",
        "el_bt_danger": "危险按钮",
        "el_bt_info": "信息按钮",
        "el_bt_text": "文字按钮",

        "el_plain": "朴素按钮",
        "el_round": "圆角按钮",
        "el_circle": "圆型按钮",
        "el_icon": "图标",
        "el_disabled": "是否禁用",
        "el_loading": "加载中",
        "el_autofocus": "默认焦点",
        "el_isText": "显示文字",
        "el_iconPosition": "图标位置",

        "layout": "布局",
        "layoutCode": "布局代码",
        "layoutTemplate": "常用布局",

        "elGroupStyles": "组样式",
        "elGroupProperties": "组属性",

        "el_border": "显示边框",
        "el_radioColor": "字体颜色",
        "el_radioFillColor": "填充颜色",
        "el_buttonRadio": "按钮模式",


        "datatemplateOuterNote": "注: 位于当前数据模板外部的相关组件标识。数据模板可以有多层，外部组件标识填写有下列规则：<br/>" +
            "1、单层或者是最外层的数据模板，填\"fieldId\"，表示表单上的直接组件。<br/>" +
            "2、如果有多层数据模板，\"./fieldId\"表示和当前数据模板同层次的组件，\"../fieldId\"表示和上一层数据模板同层次的组件，以此类推。<br/>" +
            "3、如果有多层数据模板，也可通过\"datatemplateId.*.datatemplateId2.*.fieldId\"来表示全层次路径。datatemplateId表示第一层数据模板的id，datatemplateId2表示第二层的id。",
        "datatemplateInnerNote": "注:  位于当前数据模板内部的相关组件标识，不管单层还是多层数据模板，直接填写组件的标识。",
        "importModel": "导入模型",
        "enable": "启用",
        "disable": "禁用",
        "downloadTempalte": "下载模板",
        "downloadTempalteId": "下载模板组件标识",
        "downloadTempalteIdNote": "您可以在表单上创建一个组件，并在这里填写上组件标识，系统会在该组件的节点(node)绑定下载模板的click事件。",
        "province": "省",
        "city": "省市",
        "county": "省市县",
        "useTextFieldNote": "注：建议使用文本组件",
        "useChecboxNote": "注：建议使用多选组件",
        "checkboxValueNote": "注：对应选中组件的可选值",
        "checkboxValueAllNote": "注：对应全选组件的可选值",

        "notShow": "不显示",

        "insertDataTemplate": "插入数据模板",
        "widthModules": "带相关组件插入",

        "ckeditConfig": "编辑器配置",

        "ckeditConfigInfor": "返回编辑器配置的json对象",
        "ckeditConfigInfor1": "可以通过以下链接配置编辑器工具栏功能：",
        "ckeditConfigInfor2": "../o2_lib/htmleditor/ckeditor4161/samples/toolbarconfigurator/index.html",
        "ckeditConfigInfor3": "点击此处",

        "ckeditConfigInfor4": "更多配置请查看Ckeditor官方网站",
        "ckeditConfigInfor5": "https://ckeditor.com/ckeditor-4/",
        "ckeditConfigInfor6": "注意：自定义了编辑器属性后，正文格式有可能不再符合国家党政机关公文格式标准",

        "showRead": "显示待阅",
        "password": "密码",
        "search": "搜索",
        "email": "邮箱",
        "datetime-local":"日期时间",
        "month": "月份",
        "date": "日期",
        "time": "时间",
        "week": "周",
        "textarea": "多行文本",
        "wordNumber": "字数统计",
        "maxlength": "最大长度",
        "clearable": "可清空",
        "showPassword": "显示切换密码图标",
        "prefixIcon": "头部图标",
        "suffixIcon": "尾部图标",
        "textareaRows": "多行文本行数",
        "autosize": "适应高度",
        "minRows": "最小行数",
        "maxRows": "最大行数",
        "resize": "改变大小",
        "resizeNone": "不允许",
        "resizeBoth": "允许",
        "resizeHorizontal": "横向",
        "resizeVertical": "纵向",
        "el_placement": "弹出位置",
        "popperClass": "列表类名",
        "triggerOnFocus": "激活即列出输入建议",
        "itemScriptInfo": "返回一个提供输入建议的方法。Function(queryString, callback)",
        "multiple": "是否多选",
        "collapseTags": "合并Tags",
        "multipleInfo": "可多选时有效",
        "filterable": "允许搜索",
        "filterMethod": "自定义搜索方法",
        "filterRemote": "远程搜索",
        "allowCreate": "创建新条目",
        "noMatchText": "无匹配文本",
        "noDataText": "无数据文本",
        "loadingText": "加载中文本",
        "remoteMethod": "远程搜索方法",
        "multipleLimit": "最多可选数",

        "max": "最大值",
        "min": "最小值",
        "step": "步长",
        "step_strictly": "只允许输入步长的倍数",
        "precision": "数值精度",
        "controls": "控制按钮",
        "controlsPosition": "按钮位置",

        "activeText": "打开文本",
        "inactiveText": "关闭文本",
        "activeColor": "打开颜色",
        "inactiveColor": "关闭颜色",
        "activeIconClass": "打开图标",
        "inactiveIconClass": "关闭图标",
        "activeValue": "打开的值",
        "inactiveValue": "关闭的值",
        "valueType": "值类型",
        "showInput": "显示输入框",
        "showInputControls": "显示输入框按钮",
        "inputSize": "输入框大小",
        "sliderRange": "是否范围选择",
        "sliderVertical": "竖向模式",
        "sliderMarks": "Marks 标记",
        "showTooltip": "显示提示",
        "tooltipClass": "提示类名",
        "formatTooltip": "格式化提示",
        "formatTooltipScript": "返回一个格式化函数：",
        "showStops": "是否显示间断点",
        "marksScriptInfo": "返回一个对象，key 的类型必须为 number 且取值在闭区间 [min, max] 内，每个标记可以单独设置样式",
        "optionsGroup": "可选项分组",
        "selectItemScriptInfo": "返回一个可选值数组列表；或者一个resolve了可选值数组的Promise对象",
        "selectTemplete": "自定义选项模板",
        "showAllLevels": "完整路径",
        "checkStrictly": "父子节点不关联",
        "checkStrictlyInfo": "是否严格的遵守父子节点不互相关联",
        "emitPath": "返回完整数组",
        "emitPathInfo": "在选中节点改变时，是否返回由该节点所在的各级菜单的值所组成的数组，若设置 false，则只返回该节点的值",
        "lazy": "动态加载",
        "lazyLoadScript": "动态加载方法",
        "props_value": "选项值属性",
        "props_label": "选项标签属性",
        "props_children": "子选项属性",
        "props_disabled": "选项禁用属性",
        "props_leaf": "叶子节点标志属性",
        "expandTrigger": "展开方式",
        "beforeFilter": "筛选之前",
        "filterMethodInfo": "返回一个Function。自定义搜索逻辑，第一个参数是节点node，第二个参数是搜索关键词keyword，通过返回布尔值表示是否命中",
        "beforeFilterInfo": "返回一个Function。筛选之前的钩子，参数为输入的值，若返回 false 或者返回 Promise 且被 reject，则停止筛选",
        "lazyLoadScriptInfo": "加载动态数据的方法，仅在 lazy 为 true 时有效; 返回一个function(node, resolve)，node为当前点击的节点，resolve为数据加载完成的回调(必须调用)",
        "firstPageNumber": "首页页码",

        "showOptions": "显示选项",
        "onInput": "输入时",
        "onFocus": "点击时",
        "emptyValue": "空值",
        "showZero": "显示零",
        "showNullString": "显示空字符串",
        "centerServer": "中心服务",
        "pathConditions": "路径默认条件",
        "parameterConditions": "参数默认条件",
        "addDefaultConditionByPath": "通过路径添加默认条件",
        "addDefaultConditionByParameter": "通过参数添加默认条件",

        "placementValue": ["上中","上左","上右","下中","下左","下右"],
        "trigger": "触发方式",
        "triggerValue": ["鼠标经过","鼠标点击"],
        "hideOnClick": "点击隐藏菜单",
        "showTimeout": "展开延时",
        "hideTimeout": "折叠延时",
        "splitButton": "点击和下拉同时启用",
        "splitButtonType": "按钮类型",
        "menuItem": "菜单项",
        "dropdownDefaultText": "下拉菜单",
        "showButton": "显示按钮",
        "countPerline": "每行选项数",
        "countPerlineNote": "0表示不限制",

        "wps" : {
            "config":"配置",
            "options" : "通用选项",
            "topArea":"顶部区域",
            "show":"显示",
            "hide":"隐藏",
            "headArea" : "头部区域",
            "showMode" : "显示模式",
            "showMode_normal" : "普通模式， 展示所有功能界面",
            "showMode_simple" : "极简模式， 不显示头部和工具栏",
            "wordConfig" : "Word配置项",
            "comment" : "评论",
            "isShowDocMap" : "是否开启目录功能",
            "isBestScale" : "打开文档时，默认以最佳比例显示(PC)",
            "isShowBottomStatusBar" : "底部状态栏(PC)",
            "isOpenIntoEdit" : "移动端打开时是否进入编辑",
            "component" : "组件",
            "isComponent" : "是否启用组件（PC端）",
            "HeaderLeft" :"头部左侧",
            "HeaderRight" :"头部右侧",
            "FloatQuickHelp" :"右下角帮助(金小豹)",
            "HistoryVersion" :"顶部状态栏-历史记录菜单-历史版本",
            "HistoryRecord" :"顶部状态栏-历史记录菜单-协作记录",
            "HistoryVersionDivider" :"表格-右键菜单-历史版本/协作记录分割线",
            "TabPrintPreview" : "顶部工具栏打印按钮",
            "MenuPrintPreview" : "更多菜单打印按钮",
            "ReviewTrackChanges" : "编辑、修订状态按钮",
            "TrackChanges" :"编辑、修订状态下拉选项",
            "ContextMenuConvene" : "文字右键召唤在线协助者",
            "isComponentMobile" : "是否启用组件（手机端）",
            "Logo" : "状态栏Logo",
            "Cooperation" :"状态栏协作头像",
            "More" : "状态栏更多按钮",
            "SendButton" : "顶部工具栏-分享按钮",
            "CooperHistoryMenuItem" :"顶部工具栏-协作记录菜单",
            "WriterHoverToolbars" :"文字-底部工具栏",
            "ReadSetting" :"文字-状态栏-阅读设置"
        },
        "onlyoffice" : {
            "config":"配置",
            "moduleConfig":"功能设置",
            "autosave":"自动保存",
            "chat" :"启用聊天",
            "comments" :"开启评论",
            "compatibleFeatures":"兼容旧版本",
            "plugins":"启用插件",
            "reviewDisplay":"修订显示方式",
            "reviewDisplay_markup":"标记",
            "reviewDisplay_final":"最终版",
            "reviewDisplay_original":"原始",
            "showReviewChanges":"显示跟踪变化",
            "trackChanges":"打开审阅编辑模式",
            "spellcheck" :"拼写检查",
            "viewSet":"界面设置",
            "compactHeader" : "隐藏编辑器头",
            "compactToolbar" : "紧凑型工具栏",
            "feedback" : "是否显示反馈",
            "help" :"是否显示帮助",
            "toolbarHideFileName":"标题栏是否显示文件名",
            "toolbarNoTabs":"顶部工具栏是否高亮显示",
            "unit":"标尺测量单位",
            "unit_cm":"厘米",
            "unit_pt":"像素",
            "unit_inch":"英寸",
            "zoom":"默认缩放",
            "hideRightMenu":"隐藏侧栏",
            "individualization" : "个性化信息",
            "address":"地址",
            "mail":"邮箱",
            "info":"简介",
            "company" :"公司名称",
            "www":"网址",
            "feedbackUrl":"反馈地址",
            "logoImg":"左上角logo（172x40）",
            "logoUrl":"logo链接"
        },
        "smartbi":{
            "select":"资源选择",
            "displayToolbar":"显示工具栏",
            "toolbarShow":"显示",
            "toolbarHide":"隐藏",
            "displayLeftTree":"显示左侧树",
            "leftTreeShow":"显示",
            "leftTreeHide":"隐藏"
        },
        "weeks": {
            "arr": ["周一","周二","周三","周四","周五","周六","周日"]
        },
        "tabletWidth": "手写板宽度",
        "tabletHeight": "手写板高度",
        "tabletSizeNote": "仅PC端有效，移动端横向满屏",
        "tabletToolbarNote": "仅PC端有效，移动端不显示",

        "editable": "可编辑",
        "firstDayOfWeek": "周开始日",
        "disabledDate": "禁止选择",
        "disabledDateNote": "this.event为传入日期，'return true'表示该日期禁止选择",
        "disabledDateScript": "禁止选择日期脚本",
        "selectableRangeNote": "返回可选时间段，例如return '18:30:00 - 20:30:00'或者return ['09:30:00 - 12:00:00', '14:30:00 - 18:30:00']",
        "selectableRangeScript": "时间可选范围脚本",
        "placeholder": "占位文本",
        "rangeSeparator": "分隔文本",
        "startPlaceholder": "起始占位文本",
        "endPlaceholder": "结束占位文本",
        "arrowControl": "使用箭头选择时间",
        "timeSelectType2": "时间选择类型",
        "isRange": "范围",
        "fixedTimePoint": "固定时间",
        "anyTimePoint": "任意时间",
        "to": "至",
        "startTime": "开始时间",
        "endTime": "结束时间",
        "startDate": "开始日期",
        "endDate": "结束日期",
        "selectableRange": "可选范围",
        "endSelectableRange": "结束可选范围",

        "initialIndex": "初始幻灯片索引",
        "autoplay": "自动切换",
        "interval": "切换间隔",
        "indicatorPosition": "指示器位置",
        "indicatorPositionValue": ["内部","外部","无"],
        "arrow": "箭头",
        "arrowValue": ["鼠标经过时显示", "一直显示","不显示"],
        "carouselTypeValue": ["默认","卡片"],
        "loop": "是否循环",
        "direction": "展示方向",
        "directionValue": ["水平","垂直"],
        "hotpicture": "热点图片",
        "page": "页数",
        "filterParameter": "过滤参数",

        "selectComponent": "选择应用",
        "calculationComponent": "计算应用路径",
        "component": "应用",
        "scriptComponentNote": "返回应用路径，如组织管理",
        "componentScript": "应用路径脚本",
        "applicationOptions": "应用options",
        "applicationStatus": "应用status",
        "titleAddTo": "标题行添加",
        "firstLine": "首行",
        "lastLine": "末行",
        "forceClearCustomStyle": "切换时清除自定义样式"
    },
    "smartbi":{
        "nosetup":"请先安装SmartBI应用",
        "txt":"SmartBI报表"
    },
    "onlyoffice":{
        "nosetup":"请先安装OnlyOffice应用",
    },
    "wpsoffice":{
        "nosetup":"请先安装WpsOffice应用",
    },
    "officeonline":{
        "nosetup":"请先安装OfficeOnline应用",
    },
    "actionBar": {
        "close":"关闭",
        "closeTitle": "关闭文档",
        "save": "保存",
        "saveTitle": "保存文档",
        "flow": "继续流转",
        "flowTitle": "继续流转文档",
        "submit": "提交",
        "submitTitle": "提交文档",
        "reroute": "调度",
        "rerouteTitle": "调度文档",
        "reset": "重置处理人",
        "resetTitle": "重置处理人",
        "split": "增加分支",
        "splitTitle": "增加拆分分支",
        "retract": "撤回",
        "retractTitle": "待办撤回",
        "rollback": "流程回溯",
        "rollbackTitle": "回溯到指定的环节，不保留流程记录",
        "delete": "删除文档",
        "deleteTitle": "删除文件",
        "terminate": "终止文件",
        "terminateTitle": "结束文件流转",
        "print": "打印",
        "printTitle": "打印文档",
        "press": "催促办理",
        "pressTitle": "催促办理",
        "pause": "挂起",
        "pauseTitle": "待办挂起",
        "resume": "挂起恢复",
        "resumeTitle": "从挂起状态恢复",
        "downloadAll": "一键下载",
        "downloadAllTitle": "一键下载",
        "monitor": "流程监控",
        "monitorTitle": "流程监控",
        "setReaded" : "标记为已阅",
        "readed" : "已阅",
        "addTask": "加签",
        "addTaskTitle": "在当前活动添加处理人",
        "goBack": "退回",
        "goBackTitle": "退回到已经过的活动"
    },
    "filedConfigurator": {
        "sequence": "序号",
        "fieldTitle": "字段标题",
        "fieldId": "字段标识",
        "action": "操作",
        "moveup": "移动到上一行",
        "deleteRow": "删除行",
        "insertRow": "插入行",
        "importFromForm": "从界面上中导入字段配置"
    },
    "formToolbar":{
        "save": "保存表单",
        "saveNew": "保存为模板",
        "preview": "预览",
        "print": "打印",
        "formExplode": "表单导出",
        "formImplode": "表单导入",
        "formImplodeO2": "从O2数据导入",
        "formImplodeO2Title": "导入O2格式表单",
        "htmlImplode": "从HTML导入",
        "officeImplode": "从WORD导入（仅支持Word 97-2003文件 *.doc）",
        "help": "帮助",
        "clearNoDomModule": "清除未在HTML树中的组件配置",
        "autoSave": "自动保存",
        "brush": "格式刷",
        "viewAllVersion": "查看所有表单版本",
        "add": "新建",
        "gotoApp": "打开所在应用"
    }
};
