MWF.xApplication.cms = MWF.xApplication.cms ||{};
MWF.xApplication.cms.Column = MWF.xApplication.cms.Column|| {};
MWF.xApplication.cms.Column.LP = {
    "title": "CMS Settings",
    "description": "AppInfo and category management",
    "inverse": "Inverse election",
    "cate": "category",
    "form": "Form",
    "list": "List",
    "queryView": "View",
    "dictionary": "Data Dictionary",
    "script": "Script",
    "export": "Export",
    "export_cancel": "Cancel",
    "close": "Close",
    "cancel": "Cancel",
    "export_ok": "OK",
    "allApp": "All apps",
    "column": {
        "title" :"AppInfo Management",
        "create": "New App",
        "findDesigner": "FindCode",
        "searchText": "Please enter a keyword",
        "loadding": "Loading...",
        "loaded": "AppInfo loaded",
        "nameLabel": "Name",
        "aliasLabel": "Alias",
        "descriptionLabel": "Description",
        "sortLabel": "Order",
        "iconLabel": "Icon",
        "typeLabel": "Type",
        "cancel": "Cancel",
        "ok": "OK",
        "inputName":"Please enter the AppInfo name",
        "create_cancel_title": "Cancel Confirmation of New App",
        "create_cancel": "Are you sure you want to cancel the new App?",
        "noDescription": "No description",
        "delete": "Delete AppInfo",
        "delete_confirm_title": "Delete AppInfo",
        "delete_confirm_content": "Are you sure you want to delete the AppInfo?",
        "edit": "Edit AppInfo",
        "createColumnSuccess": "AppInfo created successfully",
        "updateColumnSuccess": "AppInfo modification succeeded",
        "noElement": "There is no AppInfo in the system or there is no AppInfo you have permission to manage",
        "category": "Category",
        "form": "Form",
        "export": "Export AppInfo",
        "changeIcon": "Change Icon"
    },

    "category": {
        "title" :"Category Management",
        "create": "Create a new category",
        "nameLabel": "Category Name",
        "aliasLabel": "Category Alias",
        "descriptionLabel": "Category description",
        "sortLabel": "Queue number",
        "columnLabel": "AppInfo",
        "iconLabel": "Category Icon",
        "cancel": "Cancel",
        "ok": "OK",
        "inputName":"Please enter the category name",
        "create_cancel_title": "Cancel New Category Confirmation",
        "create_cancel": "Are you sure you want to cancel the new category?",
        "noDescription": "There is no description for this category",
        "delete": "Delete category",
        "edit": "Edit category"
    }
};