MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Column = MWF.xApplication.cms.Column || {};
MWF.xApplication.cms.Column.LP={
	"title": "Gestión de contenido",
	"description": "Administración de categorías y clasificaciones",
	"inverse": "Invertir selección",
	"cate": "Categoría",
	"form": "Formulario",
	"list": "Lista",
	"queryView": "Vista",
	"dictionary": "Diccionario de datos",
	"script": "Script",
	"export": "Exportar",
	"export_cancel": "Cancelar",
	"close": "Cerrar",
	"cancel": "Cancelar",
	"export_ok": "Aceptar",
	"allApp": "Todas",
	"searchAppPlacholder": "Ingrese el nombre para buscar una categoría",
	"searchAppTitle": "Coincide con el nombre, alias e id de la aplicación",
	"column": {
		"title": "Administración de categorías",
		"create": "Crear",
		"findDesigner": "Buscar",
		"searchText": "Ingrese una palabra clave",
		"loadding": "Cargando...",
		"loaded": "Categorías cargadas correctamente.",
		"nameLabel": "Nombre",
		"aliasLabel": "Alias",
		"descriptionLabel": "Descripción",
		"sortLabel": "Orden",
		"iconLabel": "Ícono",
		"typeLabel": "Tipo",
		"editform": "Formulario de edición",
		"editformNote": "Nota: Formulario de edición predeterminado al crear una categoría",
		"readform": "Formulario de lectura",
		"readformNote": "Nota: Formulario de lectura predeterminado al crear una categoría. Si no se selecciona, es igual al formulario de edición.",
		"cancel": "Cancelar",
		"ok": "Aceptar",
		"inputName": "Ingrese el nombre de la categoría",
		"create_cancel_title": "Confirmación de cancelar nueva categoría",
		"create_cancel": "¿Está seguro de que desea cancelar la creación de una nueva categoría?",
		"noDescription": "Esta categoría no tiene descripción.",
		"delete": "Eliminar categoría",
		"delete_confirm_title": "Eliminar categoría",
		"delete_confirm_content": "¿Está seguro de que desea eliminar esta categoría?",
		"edit": "Editar categoría",
		"createColumnSuccess": "Categoría creada correctamente.",
		"updateColumnSuccess": "Categoría actualizada correctamente.",
		"noElement": "No hay categorías en el sistema o no tiene permisos para administrar ninguna.",
		"category": "Categoría",
		"form": "Formulario",
		"export": "Exportar categorías",
		"changeIcon": "Cambiar ícono"
	},
	"createSelectTemplate": "Seleccionar plantilla de formulario",
	"templateCategory": "Categoría de plantilla:",
	"all": "Todos",
	"formType": {
		"empty": "Formulario en blanco",
		"publishEdit": "Formulario de edición de publicación",
		"publishRead": "Formulario de lectura de publicación",
		"dataInput": "Formulario de entrada de datos"
	},
	"category": {
		"title": "Administración de categorías",
		"create": "Crear nueva categoría",
		"nameLabel": "Nombre de la categoría",
		"aliasLabel": "Alias de la categoría",
		"sendNotify": "¿Enviar notificación al publicar?",
		"descriptionLabel": "Descripción de la categoría",
		"sortLabel": "Orden de la categoría",
		"columnLabel": "Pertenece a la categoría",
		"iconLabel": "Ícono de la categoría",
		"cancel": "Cancelar",
		"ok": "Aceptar",
		"inputName": "Ingrese el nombre de la categoría",
		"create_cancel_title": "Confirmación",
		"create_cancel": "¿Está seguro de que desea cancelar la creación de una nueva categoría?",
		"noDescription": "Esta categoría no tiene descripción.",
		"delete": "Eliminar categoría",
		"edit": "Editar categoría"
	}
}
MWF.xApplication.cms.Column["lp."+o2.language] = MWF.xApplication.cms.Column.LP