MWF.xApplication.cms = MWF.xApplication.cms ||{};
MWF.xApplication.cms.Column = MWF.xApplication.cms.Column|| {};
MWF.xApplication.cms.Column.LP = {
	"title": "コンテンツ管理設定",
    "description": "カテゴリおよび分類の管理",
    "inverse": "反転",
    "cate": "カテゴリ",
    "form": "フォーム",
    "list": "リスト",
    "queryView": "ビュー",
    "dictionary": "データ辞書",
    "script": "スクリプト",
    "export": "エクスポート",
    "export_cancel": "キャンセル",
    "close": "閉じる",
    "cancel": "キャンセル",
    "export_ok": "確認",
    "allApp": "すべて",
    "searchAppPlacholder": "カテゴリを検索",
    "searchAppTitle": "アプリケーションの名前、別名、および識別子と一致するものを検索",
	"column": {
        "title": "コラム管理",
        "create": "新規カラム",
        "findDesigner": "検索",
        "searchText": "キーワードを入力してください",
        "loadding": "ロード中...",
        "loaded": "コラムのロード完了",
        "nameLabel": "コラム名",
        "aliasLabel": "コラムの別名",
        "descriptionLabel": "コラムの説明",
        "sortLabel": "コラムの並び替え",
        "iconLabel": "コラムアイコン",
        "typeLabel": "コラムの種類",
        "editform": "デフォルトの編集フォーム",
        "editformNote": "注：カテゴリを作成する際のデフォルトの編集フォーム",
        "readform": "デフォルトの読み取りフォーム",
        "readformNote": "注：カテゴリを作成する際のデフォルトの読み取りフォーム、選択しない場合は編集フォームと同じ",
        "cancel": "キャンセル",
        "ok": "確認",
        "inputName": "コラム名を入力してください",
        "create_cancel_title": "コラムの作成をキャンセル",
        "create_cancel": "コラムの作成をキャンセルしてもよろしいですか？",
        "noDescription": "このコラムには説明がありません",
        "delete": "コラムの削除",
        "delete_confirm_title": "コラムの削除",
        "delete_confirm_content": "コラムを削除してもよろしいですか？",
        "edit": "コラムの編集",
        "createColumnSuccess": "コラムの作成に成功しました",
        "updateColumnSuccess": "コラムの更新に成功しました",
        "noElement": "システムにはコラムがないか、管理権限のあるコラムがありません",
        "category": "カテゴリ",
        "form": "フォーム",
        "export": "コラムのエクスポート",
        "changeIcon": "アイコンの変更"
    },

	"createSelectTemplate": "フォームテンプレートを選択",
    "templateCategory": "テンプレートカテゴリ：",
    "all": "すべて",

    "formType": {
        "empty": "空白フォーム",
        "publishEdit": "発行用編集フォーム",
        "publishRead": "発行用読み取りフォーム",
        "dataInput": "データ入力フォーム"
    },

	"category": {
        "title": "カテゴリ管理",
        "create": "カテゴリの作成",
        "nameLabel": "カテゴリ名",
        "aliasLabel": "カテゴリ別名",
        "sendNotify": "発行時のメッセージ送信",
        "descriptionLabel": "カテゴリの説明",
        "sortLabel": "カテゴリのソート",
        "columnLabel": "所属コラム",
        "iconLabel": "カテゴリアイコン",
        "cancel": "キャンセル",
        "ok": "確認",
        "inputName": "カテゴリ名を入力してください",
        "create_cancel_title": "カテゴリ作成のキャンセル確認",
        "create_cancel": "カテゴリの作成をキャンセルしますか？",
        "noDescription": "このカテゴリには説明がありません",
        "delete": "カテゴリの削除",
        "edit": "カテゴリの編集"
    }
};
