MWF.xApplication.cms = MWF.xApplication.cms ||{};
MWF.xApplication.cms.Column = MWF.xApplication.cms.Column|| {};
MWF.xApplication.cms.Column.LP = {
	"title": "콘텐츠 관리 설정",
    "description": "카테고리 및 분류 관리",
    "inverse": "선택 반전",
    "cate": "카테고리",
    "form": "폼",
    "list": "목록",
    "queryView": "뷰",
    "dictionary": "데이터 사전",
    "script": "스크립트",
    "export": "내보내기",
    "export_cancel": "취소",
    "close": "닫기",
    "cancel": "취소",
    "export_ok": "확인",
    "allApp": "모든 카테고리",
    "searchAppPlacholder": "카테고리 검색",
    "searchAppTitle": "이름, 별명 및 식별자와 일치하는 앱 검색",
	"column": {
        "title": "컬럼 관리",
        "create": "컬럼 생성",
        "findDesigner": "디자이너 찾기",
        "searchText": "키워드를 입력하세요",
        "loadding": "로딩 중...",
        "loaded": "컬럼 로드 완료",
        "nameLabel": "컬럼 이름",
        "aliasLabel": "컬럼 별칭",
        "descriptionLabel": "컬럼 설명",
        "sortLabel": "컬럼 정렬",
        "iconLabel": "컬럼 아이콘",
        "typeLabel": "컬럼 유형",
        "editform": "기본 편집 폼",
        "editformNote": "참고: 카테고리를 생성할 때의 기본 편집 폼",
        "readform": "기본 읽기 폼",
        "readformNote": "참고: 카테고리를 생성할 때의 기본 읽기 폼, 선택하지 않으면 편집 폼과 동일",
        "cancel": "취소",
        "ok": "확인",
        "inputName": "컬럼 이름을 입력하세요",
        "create_cancel_title": "컬럼 생성 취소 확인",
        "create_cancel": "컬럼 생성을 취소하시겠습니까?",
        "noDescription": "이 컬럼에는 설명이 없습니다",
        "delete": "컬럼 삭제",
        "delete_confirm_title": "컬럼 삭제",
        "delete_confirm_content": "컬럼을 삭제하시겠습니까?",
        "edit": "컬럼 편집",
        "createColumnSuccess": "컬럼이 성공적으로 생성되었습니다",
        "updateColumnSuccess": "컬럼이 성공적으로 업데이트되었습니다",
        "noElement": "시스템에는 컬럼이나 권한을 관리할 수 있는 컬럼이 없습니다",
        "category": "카테고리",
        "form": "폼",
        "export": "컬럼 내보내기",
        "changeIcon": "아이콘 변경"
    },

	"createSelectTemplate": "폼 템플릿 선택",
    "templateCategory": "템플릿 카테고리:",
    "all": "전체",

    "formType": {
        "empty": "빈 폼",
        "publishEdit": "발행 편집 폼",
        "publishRead": "발행 읽기 폼",
        "dataInput": "데이터 입력 폼"
    },

	"category": {
        "title": "카테고리 관리",
        "create": "카테고리 생성",
        "nameLabel": "카테고리 이름",
        "aliasLabel": "카테고리 별칭",
        "sendNotify": "발행 시 메시지 전송 여부",
        "descriptionLabel": "카테고리 설명",
        "sortLabel": "카테고리 정렬",
        "columnLabel": "소속 열",
        "iconLabel": "카테고리 아이콘",
        "cancel": "취소",
        "ok": "확인",
        "inputName": "카테고리 이름을 입력하세요",
        "create_cancel_title": "카테고리 생성 취소 확인",
        "create_cancel": "카테고리 생성을 취소하시겠습니까?",
        "noDescription": "이 카테고리에는 설명이 없습니다",
        "delete": "카테고리 삭제",
        "edit": "카테고리 편집"
    }
};
