MWF.xApplication.cms = MWF.xApplication.cms ||{};
MWF.xApplication.cms.Column = MWF.xApplication.cms.Column|| {};
MWF.xApplication.cms.Column.LP = {
    "title": "ຕັ້ງຄ່າບໍລິຫານເນື້ອໃນ",
    "description" : "ຖັນແລະປະເພດບໍລິຫານ",
    "inverse" : "ກົງກັນຂ້າມ",
    "cate" : "ໝວດໝູ່",
    "form" : "ຟອມ",
    "list" : "ລາຍການ",
    "queryView" : "View",
    "dictionary" : "ຂໍ້ມູນວັດຈະນານຸກົມ",
    "script" : "ລາຍງານ",
    "export" : "ນຳອອກ",
    "export_cancel" : "ຍົກເລີກ",
    "close" : "ປິດ",
    "cancel" : "ຍົກເລີກ",
    "export_ok" : "ຢືນຢັນ",
    "allApp": "ເລືອກທັງໝົດ",
    "searchAppPlacholder": "ຄົ້ນຫາແອັບ",
    "searchAppTitle": "ບໍ່ມີຊື່ແອັບທີ່ຕົງກັນ、ຊື່ອື່ນແລະໂລໂກ້",
    "column" : {
        "title" :"ການຈັດການແອັບພິເຄຊັ່ນ",
        "create" : "ສ້າງແອັບໃໝ່",
        "findDesigner": "ຄົ້ນພົບ",
        "searchText": "ກະລຸນາໃສ່ຄຳຫຼັກ",
        "loadding": "ກຳລັງໂຫລດ……",
        "loaded": "ໂຫລດສຳເລັດ",
        "nameLabel" : "ຊື່",
        "aliasLabel" : "ນາມແຝງ",
        "descriptionLabel" : "ອະທິບາຍ",
        "sortLabel" : "ຈັດລຽນ",
        "iconLabel" : "Icon",
        "typeLabel" : "ປະເພດ",
        "editform": "ຮູບແບບການແກ້ໄຂເລີ່ມຕົ້ນ",
        "editformNote": "ໝາຍເຫດ：ແກ້ໄຂແບບຟອມເມື່ອສ້າງໝວດໝູ່",
        "readform": "ແບບຟອມການອ່ານ",
        "readformNote": "ໝາຍເຫດ：ແບບຟອມການອ່ານເມື່ອສ້າງໝວດໝູ່，ຖ້າຫາກບໍາເລືອກກໍຈະຄືກັບແບບຟອມແກ້ໄຂ",
        "cancel" : "ຍົກເລີກ",
        "ok" : "ຢືນຢັນ",
        "inputName":"ກະລຸນາປ້ອນຊື່ AppInfo",
        "create_cancel_title": "ຍົກເລີກຢືນຢັນ AppInfo ໃໝ່",
        "create_cancel": "ແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກຢືນຢັນ AppInfo ໃໝ່?",
        "noDescription" : "ບໍ່ມີອະທິບາຍ",
        "delete" : "ລົບ",
        "delete_confirm_title" : "ລົບ",
        "delete_confirm_content" : "ຢືນຢັນລົບ  AppInfo？",
        "edit" : "ແກ້ໄຂ",
        "createColumnSuccess" : "ສ້າງຖັນສຳເລັດ",
        "updateColumnSuccess" : "ແກ້ໄຂຖັນສຳເລັດ",
        "noElement" : "ບໍ່ມີ AppInfo ໃນລະບົບ ຫຼື ບໍ່ມີ AppInfoທີ່ມີສິດຈັດການໄດ້",
        "category" : "ປະເພດ",
        "form" : "ຟອມ",
        "export" : "ນຳອອກ",
        "changeIcon" : "ປ່ຽນ Icon",
    },

    "createSelectTemplate": "ເລອກຟອມ template ",
    "templateCategory": "ປະເພດtemplate：",
    "all": "ທັງໝົດ",

    "formType": {
        "empty": "ຟອມເປົ່າວ່າງ",
        "publishEdit": "ແບບຟອມການແກ້ໄຂ",
        "publishRead": "ແບບຟອມການອ່ານ",
        "dataInput": "ແບບຟອມປ້ອນຂໍ້ມູນ"
    },

    "category" : {
        "title" :"ບໍລິຫານປະເພດ",
        "create" : "ສ້າງປະເພດ",
        "nameLabel" : "ຊື່ໝວດໝູ່",
        "aliasLabel" : "ນາມແຝງໝວດໝູ່",
        "sendNotify" : "ສົ່ງຂໍ້ຄວາມຫຼືບໍ",
        "descriptionLabel" : "ອະທິບາຍໝວດໝູ່",
        "sortLabel" : "ລຽນຕາມໝວດໝູ່",
        "columnLabel" : "ຄຸນສົມບັດ",
        "iconLabel" : "ປະເພດ Icon",
        "cancel" : "ຍົກເລີກ",
        "ok" : "ຢືນຢັນ",
        "inputName":"ກະລຸນາປ້ອນຊື່ໝວກໝູ່",
        "create_cancel_title": "ຍົກເລີກການຢືນຢັນໝວດໝູ່ໃໝ່",
        "create_cancel": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກການຢືນຢັນໝວດໝູ່ໃໝ່?",
        "noDescription" : "ໝວດໝູ່ນີ້ບໍ່ມີຄຳອະທິບາຍ",
        "delete" : "ລົບໝວດໝູ່",
        "edit" : "ແກ້ໄຂໝວດໝູ່"
    }
};
