MWF.xApplication.cms = MWF.xApplication.cms ||{};
MWF.xApplication.cms.Column = MWF.xApplication.cms.Column|| {};
MWF.xApplication.cms.Column.LP = {
	"title": "内容管理设置",
	"description" : "栏目和分类管理",
	"inverse" : "反选",
	"cate" : "分类",
	"form" : "表单",
	"list" : "列表",
	"queryView" : "视图",
	"dictionary" : "数据字典",
	"script" : "脚本",
	"export" : "导出",
	"export_cancel" : "取消",
	"close" : "关闭",
	"cancel" : "取消",
	"export_ok" : "确定",
	"allApp": "全部栏目",
	"searchAppPlacholder": "搜索栏目",
	"searchAppTitle": "可匹配应用的名称、别名和标识",
	"column" : {
		"title" :"栏目管理",
		"create" : "新建栏目",
		"findDesigner": "查找设计",
		"searchText": "请输入关键字",
		"loadding": "正在加载……",
		"loaded": "栏目加载完毕",
		"nameLabel" : "栏目名称",
		"aliasLabel" : "栏目别名",
		"descriptionLabel" : "栏目描述",
		"sortLabel" : "栏目排序",
		"iconLabel" : "栏目图标",
		"typeLabel" : "栏目类型",
		"editform": "默认编辑表单",
		"editformNote": "注：创建分类时的默认编辑表单",
		"readform": "默认阅读表单",
		"readformNote": "注：创建分类时的默认阅读表单，如果不选则和编辑表单一致",
		"cancel" : "取消",
		"ok" : "确定",
		"inputName":"请输入栏目名称",
		"create_cancel_title": "取消新建栏目确认",
		"create_cancel": "您确定要取消新建栏目吗?",
		"noDescription" : "此栏目没有描述",
		"delete" : "删除栏目",
		"delete_confirm_title" : "删除栏目",
		"delete_confirm_content" : "确定要删除栏目？",
		"edit" : "编辑栏目",
		"createColumnSuccess" : "栏目创建成功",
		"updateColumnSuccess" : "栏目修改成功",
		"noElement" : "系统没有栏目或者没有您有权限管理的栏目",
		"category" : "分类",
		"form" : "表单",
		"export" : "导出栏目",
		"changeIcon" : "更改图标",
	},

	"createSelectTemplate": "选择表单模板",
	"templateCategory": "模板分类：",
	"all": "全部",

	"formType": {
		"empty": "空白表单",
		"publishEdit": "发布类编辑表单",
		"publishRead": "发布类阅读表单",
		"dataInput": "数据录入类表单"
	},

	"category" : {
		"title" :"分类管理",
		"create" : "新建分类",
		"nameLabel" : "分类名称",
		"aliasLabel" : "分类别名",
		"sendNotify" : "发布时是否发送消息",
		"descriptionLabel" : "分类描述",
		"sortLabel" : "分类排序",
		"columnLabel" : "所属栏目",
		"iconLabel" : "分类图标",
		"cancel" : "取消",
		"ok" : "确定",
		"inputName":"请输入分类名称",
		"create_cancel_title": "取消新建分类确认",
		"create_cancel": "您确定要取消新建分类吗?",
		"noDescription" : "此分类没有描述",
		"delete" : "删除分类",
		"edit" : "编辑分类"
	}
};
