MWF.xApplication.cms = MWF.xApplication.cms ||{};
MWF.xApplication.cms.Column = MWF.xApplication.cms.Column|| {};
MWF.xApplication.cms.Column.LP = {
	"title": "內容管理設定",
    "description": "欄目和分類管理",
    "inverse": "反選",
    "cate": "分類",
    "form": "表單",
    "list": "列表",
    "queryView": "視圖",
    "dictionary": "數據字典",
    "script": "腳本",
    "export": "匯出",
    "export_cancel": "取消",
    "close": "關閉",
    "cancel": "取消",
    "export_ok": "確定",
    "allApp": "全部欄目",
    "searchAppPlacholder": "搜索欄目",
    "searchAppTitle": "可匹配應用的名稱、別名和標識",
	"column": {
        "title": "欄目管理",
        "create": "新建欄目",
        "findDesigner": "查找設計",
        "searchText": "請輸入關鍵字",
        "loadding": "正在載入...",
        "loaded": "欄目載入完成",
        "nameLabel": "欄目名稱",
        "aliasLabel": "欄目別名",
        "descriptionLabel": "欄目描述",
        "sortLabel": "欄目排序",
        "iconLabel": "欄目圖標",
        "typeLabel": "欄目類型",
        "editform": "默認編輯表單",
        "editformNote": "注：創建分類時的默認編輯表單",
        "readform": "默認閱讀表單",
        "readformNote": "注：創建分類時的默認閱讀表單，如不選則與編輯表單一致",
        "cancel": "取消",
        "ok": "確定",
        "inputName": "請輸入欄目名稱",
        "create_cancel_title": "取消新建欄目確認",
        "create_cancel": "您確定要取消新建欄目嗎？",
        "noDescription": "此欄目沒有描述",
        "delete": "刪除欄目",
        "delete_confirm_title": "刪除欄目",
        "delete_confirm_content": "確定要刪除欄目嗎？",
        "edit": "編輯欄目",
        "createColumnSuccess": "欄目創建成功",
        "updateColumnSuccess": "欄目修改成功",
        "noElement": "系統沒有欄目或者沒有您有權限管理的欄目",
        "category": "分類",
        "form": "表單",
        "export": "導出欄目",
        "changeIcon": "更改圖標"
    },

	"createSelectTemplate": "選擇表單模板",
    "templateCategory": "模板分類：",
    "all": "全部",

    "formType": {
        "empty": "空白表單",
        "publishEdit": "發佈類編輯表單",
        "publishRead": "發佈類閱讀表單",
        "dataInput": "數據輸入類表單"
    },

	"category": {
        "title": "分類管理",
        "create": "新建分類",
        "nameLabel": "分類名稱",
        "aliasLabel": "分類別名",
        "sendNotify": "發佈時是否發送消息",
        "descriptionLabel": "分類描述",
        "sortLabel": "分類排序",
        "columnLabel": "所屬欄目",
        "iconLabel": "分類圖標",
        "cancel": "取消",
        "ok": "確定",
        "inputName": "請輸入分類名稱",
        "create_cancel_title": "取消新建分類確認",
        "create_cancel": "您確定要取消新建分類嗎？",
        "noDescription": "此分類沒有描述",
        "delete": "刪除分類",
        "edit": "編輯分類"
    }
};
