CREATE TABLE WEBSITEVISITRECORD (
	ID VARCHAR(40) NOT NULL,
	CREATETIME TIMESTAMP,
	HOSTIP VARCHAR(50),
	OPERATIONYEAR VARCHAR(4),
	OPERATIONMONTH VARCHAR(4),
	OPERATIONDAY VARCHAR(4),
	XOPERATOR VARCHAR(32),
	PAGENAME VARCHAR(255),
	PROVINCE VARCHAR(100),
	CITY VARCHAR(100),
	DESCRIPTION VARCHAR(255), 
	PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE WEBSITEDOWNLOADRECORD (
  	ID VARCHAR(40) NOT NULL,
	CREATETIME TIMESTAMP,
	HOSTIP VARCHAR(50),
	OPERATIONYEAR VARCHAR(4),
	OPERATIONMONTH VARCHAR(4),
	OPERATIONDAY VARCHAR(4),
	XOPERATOR VARCHAR(32),
	FILENAME VARCHAR(255),
	PROVINCE VARCHAR(100),
	CITY VARCHAR(100),
	DESCRIPTION VARCHAR(255), 
	PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

CREATE TABLE WEBSITEFEEDBACKRECORD (
  	ID VARCHAR(40) NOT NULL,
	CREATETIME TIMESTAMP,
	HOSTIP VARCHAR(50),
	OPERATIONYEAR VARCHAR(4),
	OPERATIONMONTH VARCHAR(4),
	OPERATIONDAY VARCHAR(4),
	XOPERATOR VARCHAR(32),
	TITLE VARCHAR(255),
	PROVINCE VARCHAR(100),
	CITY VARCHAR(100),
	TELEPHONE VARCHAR(20),
	EMAIL VARCHAR(50),
	DESCRIPTION VARCHAR(255), 
	PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE WEBSITEFEEDBACKCONTENT (
  	ID VARCHAR(40) NOT NULL,
	CREATETIME TIMESTAMP,
	CONTENT TEXT,
	PRIMARY KEY (ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;