MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Minder = MWF.xApplication.Minder || {};
MWF.xApplication.Minder.LP={
	"title": "Mind Map",
	"dropUpload": "Drag and drop file here to upload",
	"upload": "Upload",
	"createFolder": "Create Folder",
	"operation": "Operation",
	"inputFolderName": "Please enter folder name",
	"inputName": "Please enter folder or file name",
	"searchKey": "Enter keyword to search",
	"ok": "OK",
	"cancel": "Cancel",
	"folderNameNotEmpty": "Folder name cannot be empty",
	"nameNotEmpty": "Folder or file name cannot be empty",
	"download": "Download",
	"delete": "Delete",
	"rename": "Rename",
	"share": "Share...",
	"move": "Move to...",
	"uploadTo": "Upload to",
	"deleteFolderTitle": "Confirm Delete Folder",
	"deleteFileTitle": "Confirm Delete File",
	"deleteFolder": "Are you sure you want to delete the selected folder \"{name}\"?",
	"deleteFile": "Are you sure you want to delete the selected file?",
	"deleteFolderDisable_hasSubFolder": "This folder has subfolders, please delete the subfolders and files first before deleting!",
	"deleteFolderDisable_hasFile": "This folder has files, please delete the subfolders and files first before deleting!",
	"deleteFolderFilesTitle": "Confirm Delete Files",
	"deleteFolderFiles": "Are you sure you want to delete the selected files and folders?",
	"shareTarget": "Share Target",
	"shareFile": "Share File",
	"selectShareUser": "Please select user(s) to share",
	"fileShareSuccess": "File has been shared with: ",
	"sendFile": "Send for Editing",
	"selectSendUser": "Send file to other users for editing",
	"fileSendSuccess": "File has been sent to: ",
	"editorFiles": "Received Files",
	"myFiles": "My Files",
	"shareFiles": "Shared Files",
	"filename": "Name",
	"thumbnail": "Thumbnail",
	"createTime": "Created Time",
	"updateTime": "Modified Time",
	"fileVersion": "Version"
}
MWF.xApplication.Minder["lp."+o2.language] = MWF.xApplication.Minder.LP