MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Minder = MWF.xApplication.Minder || {};
MWF.xApplication.Minder.LP={
	"title": "Mapa mental",
	"dropUpload": "Arrastre y suelte el archivo aquí para cargarlo",
	"upload": "Cargar",
	"createFolder": "Crear carpeta",
	"operation": "Operación",
	"inputFolderName": "Ingrese el nombre de la carpeta",
	"inputName": "Ingrese el nombre de la carpeta o archivo",
	"searchKey": "Ingrese la palabra clave para buscar",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"folderNameNotEmpty": "El nombre de la carpeta no puede estar vacío",
	"nameNotEmpty": "El nombre de la carpeta o archivo no puede estar vacío",
	"download": "Descargar",
	"delete": "Eliminar",
	"rename": "Renombrar",
	"share": "Compartir...",
	"move": "Mover a...",
	"uploadTo": "Cargar en",
	"deleteFolderTitle": "Confirmación de eliminación de carpeta",
	"deleteFileTitle": "Confirmación de eliminación de archivo",
	"deleteFolder": "¿Está seguro de que desea eliminar la carpeta seleccionada '{name}'?",
	"deleteFile": "¿Está seguro de que desea eliminar el archivo seleccionado?",
	"deleteFolderDisable_hasSubFolder": "Esta carpeta tiene subcarpetas, elimínelas antes de eliminar esta carpeta!",
	"deleteFolderDisable_hasFile": "Esta carpeta tiene archivos, elimínelos antes de eliminar esta carpeta!",
	"deleteFolderFilesTitle": "Confirmación de eliminación de archivos",
	"deleteFolderFiles": "¿Está seguro de que desea eliminar los archivos y carpetas seleccionados?",
	"shareTarget": "Objetivo de compartir",
	"shareFile": "Compartir archivo",
	"selectShareUser": "Seleccione el usuario para compartir",
	"fileShareSuccess": "Archivo compartido con éxito con: ",
	"sendFile": "Enviar a otros usuarios para editar",
	"selectSendUser": "Envíe el archivo a otros usuarios para que lo editen",
	"fileSendSuccess": "Archivo enviado exitosamente a: ",
	"editorFiles": "Archivos recibidos",
	"myFiles": "Mis archivos",
	"shareFiles": "Archivos compartidos",
	"filename": "Nombre",
	"thumbnail": "Miniatura",
	"createTime": "Hora de creación",
	"updateTime": "Hora de modificación",
	"fileVersion": "Versión"
}
MWF.xApplication.Minder["lp."+o2.language] = MWF.xApplication.Minder.LP