MWF.xApplication.Minder.LP = {
	"title": "マインドマップ",
    "dropUpload": "ファイルをここにドラッグしてアップロード",
    "upload": "アップロード",
    "createFolder": "フォルダを作成",
    "operation": "操作",
    "inputFolderName": "フォルダ名を入力してください",
    "inputName": "フォルダまたはファイル名を入力してください",
    "searchKey": "キーワードを入力して検索",
    "ok": "確認",
    "cancel": "キャンセル",
    "folderNameNotEmpty": "フォルダ名は空にできません",
    "nameNotEmpty": "フォルダまたはファイル名は空にできません",
    "download": "ダウンロード",
    "delete": "削除",
    "rename": "名前の変更",
    "share": "共有...",
    "move": "移動先...",
    "uploadTo": "アップロード先",
    "deleteFolderTitle": "フォルダの削除確認",
    "deleteFileTitle": "ファイルの削除確認",
	
	"deleteFolder": "選択したフォルダ '{name}' を削除しますか？",
    "deleteFile": "選択したファイルを削除しますか？",
    "deleteFolderDisable_hasSubFolder": "このフォルダにはサブフォルダがまだあります。サブフォルダとファイルを削除してから削除してください！",
    "deleteFolderDisable_hasFile": "このフォルダにはファイルがまだあります。サブフォルダとファイルを削除してから削除してください！",
    "deleteFolderFilesTitle": "ファイルとフォルダを削除しますか？",
    "deleteFolderFiles": "選択したファイルとフォルダを削除しますか？",
    "shareTarget": "共有対象",
    "shareFile": "ファイル共有",
    "selectShareUser": "共有するユーザーを選択してください",
    "fileShareSuccess": "ファイルが次のユーザーに共有されました：",
    "sendFile": "編集ファイル送信",
    "selectSendUser": "ファイルを他のユーザーに編集のために送信してください",
    "fileSendSuccess": "ファイルが次のユーザーに送信されました：",
    "editorFiles": "受信ファイル",
    "myFiles": "私のファイル",
    "shareFiles": "共有ファイル",
    "filename": "名前",
    "thumbnail": "サムネイル",
    "createTime": "作成時間",
    "updateTime": "更新時間",
    "fileVersion": "バージョン"
	
};