MWF.xApplication.Minder.LP = {
	"title": "마인드 맵",
    "dropUpload": "파일을 여기로 드래그하여 업로드",
    "upload": "업로드",
    "createFolder": "폴더 만들기",
    "operation": "작업",
    "inputFolderName": "폴더 이름을 입력하세요",
    "inputName": "폴더 또는 파일 이름을 입력하세요",
    "searchKey": "검색어 입력",
    "ok": "확인",
    "cancel": "취소",
    "folderNameNotEmpty": "폴더 이름을 비워 둘 수 없습니다",
    "nameNotEmpty": "폴더 또는 파일 이름을 비워 둘 수 없습니다",
    "download": "다운로드",
    "delete": "삭제",
    "rename": "이름 바꾸기",
    "share": "공유...",
    "move": "다음 위치로 이동...",
    "uploadTo": "업로드 위치",
    "deleteFolderTitle": "폴더 삭제 확인",
    "deleteFileTitle": "파일 삭제 확인",
	
	"deleteFolder": "선택한 폴더 '{name}'를 삭제하시겠습니까?",
    "deleteFile": "선택한 파일을 삭제하시겠습니까?",
    "deleteFolderDisable_hasSubFolder": "이 폴더에 하위 폴더가 있습니다. 하위 폴더와 파일을 먼저 삭제해 주세요!",
    "deleteFolderDisable_hasFile": "이 폴더에 파일이 있습니다. 하위 폴더와 파일을 먼저 삭제해 주세요!",
    "deleteFolderFilesTitle": "파일 및 폴더 삭제 확인",
    "deleteFolderFiles": "선택한 파일과 폴더를 삭제하시겠습니까?",
    "shareTarget": "공유 대상",
    "shareFile": "파일 공유",
    "selectShareUser": "공유할 사용자를 선택하세요",
    "fileShareSuccess": "파일이 다음 사용자에게 공유되었습니다: ",
    "sendFile": "편집 파일 보내기",
    "selectSendUser": "파일을 다른 사용자에게 편집을 위해 보내세요",
    "fileSendSuccess": "파일이 다음 사용자에게 전송되었습니다: ",
    "editorFiles": "받은 파일",
    "myFiles": "내 파일",
    "shareFiles": "공유 파일",
    "filename": "이름",
    "thumbnail": "미리보기",
    "createTime": "생성 시간",
    "updateTime": "수정 시간",
    "fileVersion": "버전"
	
};