MWF.xApplication.Minder.LP = {
	"title": "腦圖",
    "dropUpload": "將文件拖至此處上載",
    "upload": "上載",
    "createFolder": "創建文件夾",
    "operation": "操作",
    "inputFolderName": "請輸入文件夾名稱",
    "inputName": "請輸入文件夾或文件名稱",
    "searchKey": "輸入關鍵字搜索",
    "ok": "確定",
    "cancel": "取消",
    "folderNameNotEmpty": "文件夾名稱不能為空",
    "nameNotEmpty": "文件夾或文件名稱不能為空",
    "download": "下載",
    "delete": "刪除",
    "rename": "重新命名",
    "share": "分享...",
    "move": "移動到...",
    "uploadTo": "上載至",
    "deleteFolderTitle": "刪除文件夾確認",
    "deleteFileTitle": "刪除文件確認",
	
	"deleteFolder": "您確定要刪除選擇的文件夾“{name}”嗎？",
    "deleteFile": "您確定要刪除選擇的文件嗎？",
    "deleteFolderDisable_hasSubFolder": "該文件夾下還有子文件夾，請先刪除子文件夾和文件後再刪除！",
    "deleteFolderDisable_hasFile": "該文件夾下還有文件，請先刪除子文件夾和文件後再刪除！",
    "deleteFolderFilesTitle": "刪除文件確認",
    "deleteFolderFiles": "您確定要刪除選擇的文件和文件夾嗎？",
    "shareTarget": "分享對象",
    "shareFile": "分享文件",
    "selectShareUser": "請選擇分享用戶",
    "fileShareSuccess": "文件已分享給：",
    "sendFile": "發送編輯文件",
    "selectSendUser": "將文件發送給其他用戶進行編輯",
    "fileSendSuccess": "文件已發送給：",
    "editorFiles": "收到文件",
    "myFiles": "我的文件",
    "shareFiles": "分享文件",
    "filename": "名稱",
    "thumbnail": "縮略圖",
    "createTime": "創建時間",
    "updateTime": "修改時間",
    "fileVersion": "版本"
	
};