/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.Company.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:35:40 CST 2017")
public class Company_ extends SliceJpaObject_  {
    public static volatile ListAttribute<Company,String> controllerList;
    public static volatile SingularAttribute<Company,Date> createTime;
    public static volatile SingularAttribute<Company,String> display;
    public static volatile SingularAttribute<Company,String> id;
    public static volatile SingularAttribute<Company,Integer> level;
    public static volatile SingularAttribute<Company,String> name;
    public static volatile SingularAttribute<Company,Integer> orderNumber;
    public static volatile SingularAttribute<Company,String> pinyin;
    public static volatile SingularAttribute<Company,String> pinyinInitial;
    public static volatile SingularAttribute<Company,String> sequence;
    public static volatile SingularAttribute<Company,String> shortName;
    public static volatile SingularAttribute<Company,String> superior;
    public static volatile SingularAttribute<Company,String> unique;
    public static volatile SingularAttribute<Company,Date> updateTime;
}
