/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.Department.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:35:40 CST 2017")
public class Department_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Department,String> company;
    public static volatile SingularAttribute<Department,Date> createTime;
    public static volatile SingularAttribute<Department,String> display;
    public static volatile SingularAttribute<Department,String> id;
    public static volatile SingularAttribute<Department,Integer> level;
    public static volatile SingularAttribute<Department,String> name;
    public static volatile SingularAttribute<Department,Integer> orderNumber;
    public static volatile SingularAttribute<Department,String> pinyin;
    public static volatile SingularAttribute<Department,String> pinyinInitial;
    public static volatile SingularAttribute<Department,String> sequence;
    public static volatile SingularAttribute<Department,String> shortName;
    public static volatile SingularAttribute<Department,String> superior;
    public static volatile SingularAttribute<Department,String> unique;
    public static volatile SingularAttribute<Department,Date> updateTime;
}
