/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.organization.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.organization.core.entity.Group.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Mar 10 10:09:49 CST 2017")
public class Group_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Group,Date> createTime;
    public static volatile SingularAttribute<Group,String> display;
    public static volatile ListAttribute<Group,String> groupList;
    public static volatile SingularAttribute<Group,String> id;
    public static volatile SingularAttribute<Group,String> name;
    public static volatile SingularAttribute<Group,Integer> orderNumber;
    public static volatile ListAttribute<Group,String> personList;
    public static volatile SingularAttribute<Group,String> pinyin;
    public static volatile SingularAttribute<Group,String> pinyinInitial;
    public static volatile SingularAttribute<Group,String> sequence;
    public static volatile SingularAttribute<Group,String> unique;
    public static volatile SingularAttribute<Group,Date> updateTime;
}
