MWF.xApplication.AuditLog.LP = {
	"title": "Three-Member Management Log",

	"person": "User",
	"node": "Node",
	"clientIp": "Client IP",
	"module": "Module",
	"operation": "operation",
	"httpType": "Type",
	"httpStatus": "Status",
	"httpUrl": "Request address",
	"startTime": "Start Time",
	"endTime": "End Time",
	"createTime": "Start Time",
	"updateTime": "End Time",
	"spendTime": "Execution duration (milliseconds)",
	"spendTime1 ":" Execution duration",
	"millisecond ": "milliseconds",
	"firstPage": "First Page",
	"lastPage": "Last Page",
	"query": "Search",
	"reset": "Reset",
	"noItem": "No data can be queried under current conditions",
	"all": "All Logs",
	"sendData": "Request Data",

	"cancel": "Cancel",
	"close": "Close",
	"ok": "OK",
	"edit": "Edit",
	"remove": "Remove",
	"action": "Action",
	"view": "View",
	"viewDetail": "View Detail",
	"logDetail": "Log Detail",

	"yesterday": "Yesterday",
	"twoDaysAgo": "The day before yesterday",
	"weekAgo": "Week Ago",
	"dayAgo": "Day Ago",
	"hourAgo": "Hours ago",
	"minuteAgo": "minutes ago",
	"justNow": "JustNow",
	"publishJustNow": "Just published"
};