/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.AppCatagoryPermission.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:17:48 CST 2016")
public class AppCatagoryPermission_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AppCatagoryPermission,Date> createTime;
    public static volatile SingularAttribute<AppCatagoryPermission,String> creatorUid;
    public static volatile SingularAttribute<AppCatagoryPermission,String> description;
    public static volatile SingularAttribute<AppCatagoryPermission,String> id;
    public static volatile SingularAttribute<AppCatagoryPermission,String> objectId;
    public static volatile SingularAttribute<AppCatagoryPermission,String> objectType;
    public static volatile SingularAttribute<AppCatagoryPermission,String> sequence;
    public static volatile SingularAttribute<AppCatagoryPermission,Date> updateTime;
    public static volatile SingularAttribute<AppCatagoryPermission,String> usedObjectCode;
    public static volatile SingularAttribute<AppCatagoryPermission,String> usedObjectName;
    public static volatile SingularAttribute<AppCatagoryPermission,String> usedObjectType;
}
