/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.AppCategoryAdmin.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sat May 06 19:34:34 CST 2017")
public class AppCategoryAdmin_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AppCategoryAdmin,String> adminLevel;
    public static volatile SingularAttribute<AppCategoryAdmin,String> adminName;
    public static volatile SingularAttribute<AppCategoryAdmin,String> adminUid;
    public static volatile SingularAttribute<AppCategoryAdmin,Date> createTime;
    public static volatile SingularAttribute<AppCategoryAdmin,String> creatorUid;
    public static volatile SingularAttribute<AppCategoryAdmin,String> description;
    public static volatile SingularAttribute<AppCategoryAdmin,String> id;
    public static volatile SingularAttribute<AppCategoryAdmin,String> objectId;
    public static volatile SingularAttribute<AppCategoryAdmin,String> objectName;
    public static volatile SingularAttribute<AppCategoryAdmin,String> objectType;
    public static volatile SingularAttribute<AppCategoryAdmin,String> sequence;
    public static volatile SingularAttribute<AppCategoryAdmin,Date> updateTime;
}
