/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.cms.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.cms.core.entity.AppCatagoryAdmin.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:17:48 CST 2016")
public class AppCatagoryAdmin_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<AppCatagoryAdmin,String> adminLevel;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> adminName;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> adminUid;
    public static volatile SingularAttribute<AppCatagoryAdmin,Date> createTime;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> creatorUid;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> description;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> id;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> objectId;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> objectType;
    public static volatile SingularAttribute<AppCatagoryAdmin,String> sequence;
    public static volatile SingularAttribute<AppCatagoryAdmin,Date> updateTime;
}
