MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.File = MWF.xApplication.File || {};
MWF.xApplication.File.LP={
	"title": "Unidad de red empresarial",
	"dropUpload": "Arrastre y suelte archivos aquí para cargarlos",
	"upload": "Cargar",
	"createFolder": "Crear carpeta",
	"operation": "Operación",
	"inputFolderName": "Ingrese el nombre de la carpeta",
	"inputName": "Ingrese el nombre de la carpeta o archivo",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"folderNameNotEmpty": "El nombre de la carpeta no puede estar vacío",
	"nameNotEmpty": "El nombre de la carpeta o archivo no puede estar vacío",
	"download": "Descargar",
	"delete": "Eliminar",
	"rename": "Renombrar",
	"share": "Compartir...",
	"move": "Mover a...",
	"uploadTo": "Cargar en",
	"deleteFolderTitle": "Confirmación de eliminación de la carpeta",
	"deleteFileTitle": "Confirmación de eliminación del archivo",
	"deleteFolder": "¿Está seguro de que desea eliminar la carpeta seleccionada?",
	"deleteFile": "¿Está seguro de que desea eliminar el archivo seleccionado?",
	"deleteFolderFilesTitle": "Confirmación de eliminación de archivos",
	"deleteFolderFiles": "¿Está seguro de que desea eliminar los archivos y carpetas seleccionados?",
	"shareFile": "Compartir archivo",
	"selectShareUser": "Seleccione los usuarios para compartir",
	"fileShareSuccess": "El archivo se ha compartido con: ",
	"sendFile": "Enviar para editar",
	"selectSendUser": "Enviar el archivo para que otros usuarios lo editen",
	"fileSendSuccess": "El archivo se ha enviado a: ",
	"editorFiles": "Archivos recibidos",
	"myFiles": "Mis archivos",
	"shareFiles": "Archivos compartidos"
}
MWF.xApplication.File["lp."+o2.language] = MWF.xApplication.File.LP