MWF.xApplication.File.LP = {
	"title": "企業クラウド",
  "dropUpload": "ファイルをここにドラッグアンドドロップしてアップロード",
  "upload": "アップロード",
  "createFolder": "フォルダを作成",
  "operation": "操作",
  "inputFolderName": "フォルダ名を入力してください",
  "inputName": "フォルダまたはファイル名を入力してください",
  "ok": "確認",
  "cancel": "キャンセル",
  "folderNameNotEmpty": "フォルダ名を空にできません",
  "nameNotEmpty": "フォルダまたはファイル名を空にできません",
  "download": "ダウンロード",
  "delete": "削除",
  "rename": "名前を変更",
  "share": "共有...",
  "move": "移動先...",
  "uploadTo": "アップロード先",
  "deleteFolderTitle": "フォルダの削除確認",
  "deleteFileTitle": "ファイルの削除確認",
  "deleteFolder": "選択したフォルダを削除してもよろしいですか？",
  "deleteFile": "選択したファイルを削除してもよろしいですか？",
  "deleteFolderFilesTitle": "ファイルの削除確認",
  "deleteFolderFiles": "選択したファイルとフォルダを削除してもよろしいですか？",
  "shareFile": "ファイルを共有",
  "selectShareUser": "共有ユーザーを選択してください",
  "fileShareSuccess": "ファイルが次のユーザーと共有されました：",
  "sendFile": "編集のためファイルを送信",
  "selectSendUser": "他のユーザーにファイルを送信して編集します",
  "fileSendSuccess": "ファイルが次のユーザーに送信されました：",
  "editorFiles": "受信したファイル",
  "myFiles": "私のファイル",
  "shareFiles": "共有ファイル"
	
};
