MWF.xApplication.File.LP = {
	"title": "기업 클라우드",
  "dropUpload": "파일을 여기에 끌어서 업로드하세요",
  "upload": "업로드",
  "createFolder": "폴더 만들기",
  "operation": "작업",
  "inputFolderName": "폴더 이름을 입력하세요",
  "inputName": "폴더 또는 파일 이름을 입력하세요",
  "ok": "확인",
  "cancel": "취소",
  "folderNameNotEmpty": "폴더 이름을 비울 수 없습니다",
  "nameNotEmpty": "폴더 또는 파일 이름을 비울 수 없습니다",
  "download": "다운로드",
  "delete": "삭제",
  "rename": "이름 변경",
  "share": "공유...",
  "move": "다음 위치로 이동...",
  "uploadTo": "업로드 위치",
  "deleteFolderTitle": "폴더 삭제 확인",
  "deleteFileTitle": "파일 삭제 확인",
  "deleteFolder": "선택한 폴더를 삭제하시겠습니까?",
  "deleteFile": "선택한 파일을 삭제하시겠습니까?",
  "deleteFolderFilesTitle": "파일 및 폴더 삭제 확인",
  "deleteFolderFiles": "선택한 파일과 폴더를 삭제하시겠습니까?",
  "shareFile": "파일 공유",
  "selectShareUser": "공유할 사용자를 선택하세요",
  "fileShareSuccess": "파일이 공유되었습니다: ",
  "sendFile": "편집을 위해 파일 보내기",
  "selectSendUser": "다른 사용자에게 파일을 보내어 편집하세요",
  "fileSendSuccess": "파일이 다음 사용자에게 보내졌습니다: ",
  "editorFiles": "수신 파일",
  "myFiles": "내 파일",
  "shareFiles": "공유 파일"
	
};
