/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.Hint.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:03 CST 2018")
public class Hint_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Hint,String> application;
    public static volatile SingularAttribute<Hint,String> id;
    public static volatile SingularAttribute<Hint,String> job;
    public static volatile SingularAttribute<Hint,String> message;
    public static volatile SingularAttribute<Hint,String> process;
    public static volatile SingularAttribute<Hint,String> work;
}
