/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.processplatform.core.entity.content.SerialNumber.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:44:03 CST 2018")
public class SerialNumber_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<SerialNumber,String> application;
    public static volatile SingularAttribute<SerialNumber,String> id;
    public static volatile SingularAttribute<SerialNumber,String> name;
    public static volatile SingularAttribute<SerialNumber,String> process;
    public static volatile SingularAttribute<SerialNumber,Integer> serial;
}
