MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.process = MWF.xApplication.process || {};
MWF.xApplication.process.ApplicationExplorer = MWF.xApplication.process.ApplicationExplorer || {};
MWF.xApplication.process.ApplicationExplorer.LP={
	"title": "App de flujo",
	"all": "Todos",
	"create": "Crear APP",
	"import": "Importar",
	"find": "Buscar",
	"noApplicationCreate": "No hay aplicaciones en el sistema o no tiene permisos para administrar ninguna aplicación. <br/> Haga clic aquí para crear una nueva aplicación",
	"noApplication": "No hay aplicaciones en el sistema o no tiene permisos para administrar ninguna aplicación.",
	"unDescription": "Esta aplicación no tiene descripción.",
	"form": "Formulario",
	"process": "Proceso",
	"noProcess": "Esta aplicación aún no tiene procesos. Haga clic aquí para crear un nuevo proceso.",
	"noForm": "Esta aplicación aún no tiene formularios. Haga clic aquí para crear un nuevo formulario.",
	"unCategory": "Sin clasificar",
	"name": "Nombre",
	"alias": "Alias",
	"description": "Descripción",
	"type": "Tipo",
	"icon": "Icono",
	"action_ok": "Aceptar",
	"action_cancel": "Cancelar",
	"createApplication_cancel_title": "Confirmación de cancelación de creación de aplicación",
	"createApplication_cancel": "¿Seguro que desea cancelar la creación de la aplicación?",
	"createApplicationSuccess": "¡Se ha creado la aplicación satisfactoriamente!",
	"searchAppPlacholder": "Ingresar nombre",
	"searchAppTitle": "Coincide con el nombre, alias e id de la aplicación",
	"application": {
		"export": "Exportar aplicación",
		"export_ok": "Aceptar",
		"export_cancel": "Cancelar",
		"process": "Proceso",
		"form": "Formulario",
		"dictionary": "Diccionario de datos",
		"script": "Script",
		"import": "Importar APP",
		"import_confirm_title": "Confirmación",
		"import_confirm": "La aplicación que desea importar ya existe, ¿desea sobrescribirla? \nSi hace clic en 'Aceptar', se sobrescribirá la aplicación existente y esta acción no podrá deshacerse.",
		"createApplication_cancel_title": "Confirmación",
		"createApplication_cancel": "¿Está seguro de que desea cancelar la creación de la aplicación?",
		"inputApplicationName": "¡Ingrese el nombre de la aplicación!",
		"createApplicationSuccess": "¡Se ha creado la aplicación satisfactoriamente!",
		"deleteElements": "Eliminar las aplicaciones seleccionadas",
		"deleteElementsTitle": "Confirmación",
		"deleteElementsConfirm": "¿Está seguro de que desea eliminar las aplicaciones seleccionadas?  <br><font style='color: red'>Esta acción eliminará todos los elementos de diseño de las aplicaciones seleccionadas, incluidos los procesos, formularios, datos, scripts, y no se puede deshacer<br></font>",
		"deleteApplicationAllConfirm": "Eliminar también todas las instancias de proceso completadas",
		"deleteApplicationAllInfo": "¡Debe asegurarse de que esta aplicación no tenga instancias de trabajo en proceso, de lo contrario no se puede eliminar!",
		"deleteElementsConfirmAgain": "<font style='color: #00F; font-size:14px'>Confirme una vez más que desea eliminar las siguientes aplicaciones:</font>",
		"deleteElementsAllConfirmAgain": "<font style='color: #00F; font-size:14px'>Confirme una vez más que desea eliminar las siguientes aplicaciones y todas sus instancias de proceso:</font>",
		"select": "Invertir selección"
	}
}
MWF.xApplication.process.ApplicationExplorer["lp."+o2.language] = MWF.xApplication.process.ApplicationExplorer.LP