MWF.xApplication.Selector.LP = MWF.SelectorLP = {
    "title": "Select",
    "selectPerson": "Select Person",
    "selectIdentity": "Select Identity",
    "selectUnit": "Select Unit",
    "selectGroup": "Select Group",
    "selectDuty": "Select Duty",
    "selectField": "Select Field",
    "selectAppliction": "Select Process Appliction",
    "selectProcess": "Select Process",
    "selectView": "Select View",
    "selectCMSApplication": "Select CMS Application",
    "selectCMSCategory": "Select CMS Category",
    "searchDescription" : "search",

    "waitingSelect" : "Waiting Select",
    "selected" : "Selected",
    "empty" : "<Empty",

    "identity" : "Identity",
    "person" : "Person",
    "application" : "Application",
    "CMSApplication" : "Application",
    "CMSCategory" : "Category",
    "CMSFormField" : "Field",
    "formField" : "Field",
    "process" : "Process",
    "role" : "Role",
    "group" : "Group",
    "unit" : "Unit",

    "cancel": "Cancel",
    "back": "Back",
    "ok": "Ok",
    "noPerson": "User “{name}” not exist"
};