MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Selector = MWF.xApplication.Selector || {};
MWF.xApplication.Selector.LP={
	"title": "Seleccionar",
	"multiSelectTitle": "Seleccionar",
	"selectPerson": "Persona",
	"selectIdentity": "Identidad",
	"selectUnit": "Organización",
	"selectGroup": "Grupo",
	"selectRole": "Rol",
	"selectDuty": "Trabajo",
	"selectField": "Campo",
	"selectFile": "Archivo de recursos",
	"selectAppliction": "Aplicación de flujo de trabajo",
	"selectProcess": "Proceso",
	"selectView": "Vista",
	"selectStatement": "Consulta",
	"selectTable": "Tabla de datos",
	"selectList": "Lista",
	"selectFormStyle": "Estilo del formulario",
	"selectCMSApplication": "Aplicación de gestión de contenidos",
	"selectCMSCategory": "Categoría de gestión de contenidos",
	"noSelectableItemText": "Ninguna opción disponible.",
	"selectScript": "Script",
	"selectDictionary": "Diccionario de datos",
	"selectImportModel": "Modelo de importación",
	"searchDescription": "Buscar contenido",
	"waitingSelect": "En espera de selección",
	"selected": "Seleccionado",
	"empty": "Vaciar",
	"remove": "Eliminar",
	"selected2": "Seleccionado",
	"identity": "Identidad",
	"person": "Persona",
	"duty": "Trabajo",
	"application": "Aplicación",
	"CMSApplication": "Aplicación",
	"CMSCategory": "Categoría",
	"CMSFormField": "Campo",
	"formField": "Campo",
	"process": "Proceso",
	"role": "Rol",
	"group": "Grupo",
	"unit": "Organización",
	"systemList": "Lista de sistemas",
	"quantifier": {
		"person": "persona",
		"identity": "identidad",
		"unit": "unidad",
		"group": "grupo",
		"role": "rol"
	},
	"appType": {
		"process": "Proceso",
		"cms": "Contenido",
		"portal": "Portal",
		"service": "Servicio"
	},
	"cancel": "Cancelar",
	"back": "Volver",
	"ok": "Aceptar",
	"noPerson": "La persona \"{name}\" no existe.",
	"processPlatform": "Proceso",
	"cms": "Contenido",
	"portal": "Portal",
	"query": "Datos",
	"service": "Servicio",
	"systemStyle": "Estilo del sistema",
	"customStyle": "Estilo personalizado (Script)",
	"selectAll": "Seleccionar todo",
	"selectChildren": "Seleccionar todo lo siguiente",
	"selectItemMaxText": "Puede seleccionar un máximo de {count} opciones.",
	"service1": "Servicio",
	"agent": "Agente"
}
MWF.xApplication.Selector["lp."+o2.language] = MWF.xApplication.Selector.LP