MWF.xApplication.Selector=MWF.xApplication.Selector||{};
MWF.xApplication.Selector.LP = MWF.SelectorLP = {
    "title": "選択",
	"multiSelectTitle": "複数選択",
	"selectPerson": "人を選択",
	"selectIdentity": "アイデンティティを選択",
	"selectUnit": "組織を選択",
	"selectGroup": "グループを選択",
	"selectRole": "役割を選択",
	"selectDuty": "職務を選択",
	"selectField": "フィールドを選択",
	"selectFile": "リソースファイルを選択",
	"selectAppliction": "プロセスアプリケーションを選択",
	"selectProcess": "プロセスを選択",
	"selectView": "ビューを選択",
	"selectStatement": "クエリを選択",
	"selectTable": "データテーブルを選択",
	"selectList": "リストを選択",
	"selectFormStyle": "フォームスタイルを選択",
	"selectCMSApplication": "コンテンツ管理アプリケーションを選択",
	"selectCMSCategory": "コンテンツ管理カテゴリを選択",
	"noSelectableItemText": "選択可能なアイテムがありません",
	"selectScript": "スクリプトを選択",
	"selectDictionary": "データディクショナリを選択",
	"selectImportModel": "インポートモデルを選択",
	"searchDescription": "コンテンツ検索",
	"waitingSelect": "待機中",
	"selected": "選択済み",
	"empty": "空にする",

    "identity": "アイデンティティ",
	"person": "個人",
	"duty": "職務",
	"application": "アプリケーション",
	"CMSApplication": "アプリケーション",
	"CMSCategory": "カテゴリ",
	"CMSFormField": "フィールド",
	"formField": "フィールド",
	"process": "プロセス",
	"role": "役割",
	"group": "グループ",
	"unit": "組織",
	"systemList": "システムリスト",
	"appType": {
		"process": "プロセス管理",
		"cms": "コンテンツ管理",
		"portal": "ポータル管理",
		"service": "サービス管理"
	},
	"cancel": "キャンセル",
	"back": "戻る",
	"ok": "確認",
	"noPerson": "人物 '{name}' が存在しません",
	"processPlatform": "プロセスプラットフォーム",
	"cms": "コンテンツ管理",
	"portal": "ポータル管理",
	"query": "データセンター",
	"service": "サービス管理",

    "systemStyle": "システムスタイル",
	"customStyle": "カスタムスタイル（スクリプト）",
	"selectAll": "すべて選択",
	"selectChildren": "子供を全選択",
	"selectItemMaxText": "最大 {count} 項目を選択できます",
	"service1": "サービス",
	"agent": "エージェント"
};
MWF.xApplication.Selector["lp."+o2.language] = MWF.xApplication.Selector.LP;
