MWF.xApplication.Selector=MWF.xApplication.Selector||{};
MWF.xApplication.Selector.LP = MWF.SelectorLP = {
    "title": "선택",
	"multiSelectTitle": "다중 선택",
	"selectPerson": "사람 선택",
	"selectIdentity": "신분 선택",
	"selectUnit": "조직 선택",
	"selectGroup": "그룹 선택",
	"selectRole": "역할 선택",
	"selectDuty": "직책 선택",
	"selectField": "필드 선택",
	"selectFile": "리소스 파일 선택",
	"selectAppliction": "프로세스 애플리케이션 선택",
	"selectProcess": "프로세스 선택",
	"selectView": "뷰 선택",
	"selectStatement": "쿼리 선택",
	"selectTable": "데이터 테이블 선택",
	"selectList": "목록 선택",
	"selectFormStyle": "양식 스타일 선택",
	"selectCMSApplication": "콘텐츠 관리 애플리케이션 선택",
	"selectCMSCategory": "콘텐츠 관리 카테고리 선택",
	"noSelectableItemText": "선택 가능한 항목 없음",
	"selectScript": "스크립트 선택",
	"selectDictionary": "데이터 사전 선택",
	"selectImportModel": "가져오기 모델 선택",
	"searchDescription": "컨텐츠 검색",
	"waitingSelect": "대기 중",
	"selected": "선택됨",
	"empty": "비우기",

    "identity": "신분",
	"person": "개인",
	"duty": "직무",
	"application": "애플리케이션",
	"CMSApplication": "애플리케이션",
	"CMSCategory": "카테고리",
	"CMSFormField": "필드",
	"formField": "필드",
	"process": "프로세스",
	"role": "역할",
	"group": "그룹",
	"unit": "조직",
	"systemList": "시스템 목록",
	"appType": {
		"process": "프로세스 관리",
		"cms": "콘텐츠 관리",
		"portal": "포털 관리",
		"service": "서비스 관리"
	},
	"cancel": "취소",
	"back": "뒤로",
	"ok": "확인",
	"noPerson": "사용자 '{name}'을(를) 찾을 수 없습니다",
	"processPlatform": "프로세스 플랫폼",
	"cms": "콘텐츠 관리",
	"portal": "포털 관리",
	"query": "데이터 센터",
	"service": "서비스 관리",

    "systemStyle": "시스템 스타일",
	"customStyle": "사용자 정의 스타일 (스크립트)",
	"selectAll": "모두 선택",
	"selectChildren": "하위 모두 선택",
	"selectItemMaxText": "최대 {count}개 항목을 선택할 수 있습니다",
	"service1": "서비스",
	"agent": "에이전트"
};
MWF.xApplication.Selector["lp."+o2.language] = MWF.xApplication.Selector.LP;
