MWF.xApplication.Selector=MWF.xApplication.Selector||{};
MWF.xApplication.Selector.LP = MWF.SelectorLP = {
    "title": "选择",
    "multiSelectTitle": "选择",
    "selectPerson": "选择人员",
    "selectIdentity": "选择身份",
    "selectUnit": "选择组织",
    "selectGroup": "选择群组",
    "selectRole": "选择角色",
    "selectDuty": "选择职务",
    "selectField": "选择字段",
    "selectFile": "选择资源文件",
    "selectAppliction": "选择流程应用",
    "selectProcess": "选择流程",
    "selectWidget": "选择部件",
    "selectView": "选择视图",
    "selectStatement" : "选择查询",
    "selectTable": "选择数据表",
    "selectList" : "选择列表",
    "selectFormStyle" : "选择表单样式",
    "selectCMSApplication": "选择内容管理应用",
    "selectCMSCategory": "选择内容管理栏目",
    "noSelectableItemText" : "无待选项",
    "selectScript" : "选择脚本",
    "selectDictionary" : "选择数据字典",
    "selectImportModel": "选择导入模型",
    "selectFieldProperty": "选择字段属性",
    "selectPanFile": "选择网盘文件",

    "personFile": "个人文件",
    "unitFile": "企业文件",

    "searchDescription" : "搜索内容",
    "searchDescriptionFieldProperty": "展开过的表单可以搜索组件",

    "waitingSelect" : "待选",
    "selected" : "已选",
    "empty" : "清空",
    "remove": "移除",
    "selected2": "已选",
    "searchResult": "搜索结果",

    "identity" : "身份",
    "person" : "个人",
    "duty" : "职务",
    "application" : "应用",
    "CMSApplication" : "应用",
    "CMSCategory" : "分类",
    "CMSFormField" : "字段",
    "formField" : "字段",
    "process" : "流程",
    "role" : "角色",
    "group" : "群组",
    "unit" : "组织",
    "unitDuty" : "组织职务",
    "systemList" : "系统列表",
    "processActivity" : "流程活动",
    "activity" : "流程活动",

    "quantifier": {
        "person": "个人",
        "identity": "身份",
        "unit": "组织",
        "group": "群组",
        "role": "角色",
        "processActivity" : "流程活动",
        "activity" : "流程活动",
    },

    "appType" : {
        "process": "流程管理",
        "cms": "内容管理",
        "portal": "门户管理",
        "service": "服务管理",
        "currentForm": "当前表单"
    },

    "cancel": "取消",
    "back": "返回",
    "ok": "确定",
    "noPerson": "人员“{name}”不存在",

    "processPlatform": "流程平台",
    "cms": "内容管理",
    "portal": "门户管理",
    "query": "数据中心",
    "service": "服务管理",
    "currentForm": "当前表单",

    "systemStyle" : "系统样式",
    "customStyle" : "自定义样式（脚本）",
    "selectAll" : "全选",
    "selectChildren" : "全选下级",
    "selectItemMaxText" : "最多可选择{count}个选项",
    "service1" : "服务",
    "agent" : "代理"
};
MWF.xApplication.Selector["lp."+o2.language] = MWF.xApplication.Selector.LP;
