MWF.xApplication.Selector.LP = MWF.SelectorLP = {
    "title": "选择",
    "selectPerson": "选择人员",
    "selectIdentity": "选择身份",
    "selectUnit": "选择组织",
    "selectGroup": "选择群组",
    "selectRole": "选择角色",
    "selectDuty": "选择职务",
    "selectField": "选择字段",
    "selectFile": "选择资源文件",
    "selectAppliction": "选择流程应用",
    "selectProcess": "选择流程",
    "selectView": "选择视图",
    "selectTable": "选择数据表",
    "selectCMSApplication": "选择内容管理应用",
    "selectCMSCategory": "选择内容管理栏目",

    "searchDescription" : "搜索内容",

    "waitingSelect" : "待选",
    "selected" : "已选",
    "empty" : "清空",

    "identity" : "身份",
    "person" : "个人",
    "application" : "应用",
    "CMSApplication" : "应用",
    "CMSCategory" : "分类",
    "CMSFormField" : "字段",
    "formField" : "字段",
    "process" : "流程",
    "role" : "角色",
    "group" : "群组",
    "unit" : "组织",

    "cancel": "取消",
    "back": "返回",
    "ok": "确定",
    "noPerson": "人员“{name}”不存在"
};