MWF.xApplication.Selector=MWF.xApplication.Selector||{};
MWF.xApplication.Selector.LP = MWF.SelectorLP = {
    "title": "選擇",
	"multiSelectTitle": "多選",
	"selectPerson": "選擇人員",
	"selectIdentity": "選擇身份",
	"selectUnit": "選擇組織",
	"selectGroup": "選擇群組",
	"selectRole": "選擇角色",
	"selectDuty": "選擇職務",
	"selectField": "選擇字段",
	"selectFile": "選擇資源文件",
	"selectAppliction": "選擇流程應用",
	"selectProcess": "選擇流程",
	"selectView": "選擇視圖",
	"selectStatement": "選擇查詢",
	"selectTable": "選擇數據表",
	"selectList": "選擇列表",
	"selectFormStyle": "選擇表單樣式",
	"selectCMSApplication": "選擇內容管理應用",
	"selectCMSCategory": "選擇內容管理分類",
	"noSelectableItemText": "無可選項目",
	"selectScript": "選擇腳本",
	"selectDictionary": "選擇數據詞典",
	"selectImportModel": "選擇導入模型",
	"searchDescription": "搜索內容",
	"waitingSelect": "等待選擇",
	"selected": "已選擇",
	"empty": "清空",

    "identity": "身份",
	"person": "個人",
	"duty": "職務",
	"application": "應用",
	"CMSApplication": "應用",
	"CMSCategory": "分類",
	"CMSFormField": "字段",
	"formField": "字段",
	"process": "流程",
	"role": "角色",
	"group": "群組",
	"unit": "組織",
	"systemList": "系統列表",
	"appType": {
		"process": "流程管理",
		"cms": "內容管理",
		"portal": "門戶管理",
		"service": "服務管理"
	},
	"cancel": "取消",
	"back": "返回",
	"ok": "確定",
	"noPerson": "人員“{name}”不存在",
	"processPlatform": "流程平台",
	"cms": "內容管理",
	"portal": "門戶管理",
	"query": "數據中心",
	"service": "服務管理",

    "systemStyle": "系統風格",
	"customStyle": "自訂風格（腳本）",
	"selectAll": "全選",
	"selectChildren": "全選子選項",
	"selectItemMaxText": "最多可選擇 {count} 項",
	"service1": "服務",
	"agent": "代理"
};
MWF.xApplication.Selector["lp."+o2.language] = MWF.xApplication.Selector.LP;
