MWF.xApplication.Calendar.LP = {
    "title": "Calendar",

    "calendar": "Calendar",
    "event": "Event",
    "subject": "Title",
    "applyPerson": "Applicant",
    "myCalendar": "My Calendar",
    "year": "year",
    "month": "Month",
    "day": "Day",
    "list": "Schedule",
    "today": "Today",
    "tomorrow": "Tomorrow",
    "afterTomorrow": "The Day After Tomorrow",
    "yesterday": "Yesterday",
    "beforeYesterday": "The day before yesterday",
    "nextMonth": "Next Month",
    "floor": "Floor",
    "enable": "Available",
    "disable": "Disable",
    "modifyConfirm": "Confirm to modify",
    "cancel": "Cancel",
    "close": "Close",
    "save": "Save",
    //"inputAddress": "input address",
    "begin": "Begin",
    "beginTime": "Begin",
    "end": "End",
    "endTime": "End",
    "time": "Time",
    "remind": "Remind",
    "repeat": "Repeat",
    "notRepeat": "Not Repeat",
    "repeatUntilAvailable": "End",
    "repeatUntilAvailableTextArr": ["Never", "End Date"],
    "eventTime": "Schedule Time",
    "endDate": "End Date",
    "remindWhenBegin": "Remind When Begin",
    "no": "No",
    "editMore": "More edits",
    "calendarName": "Calendar Name",
    "createCalendar": "New Calendar",
    "createNewCalendar": "New Calendar",
    "seeMore": "See More",
    "calendarMarket": "Calendar Square",

    "description": "Remarks",
    "type": "Type",
    "canlendarTypeArr": ["Personal Calendar", "Organization Calendar"],
    "unitCalendar": "Organization Calendar",
    "myFollowCalendar": "Followed Calendar",
    "unit": "Owning Organization",
    "unit2": "Organization,",
    "belongTo": "Belonging",
    "unitEmptyNotice": "Owning organization cannot be empty",
    "isOpened": "Is it open",
    "followed": "Followed",
    "clickToCancelFollow": "Click to cancel following",
    "cancelFollowSuccess": "Unfollow success",
    "follow": "Follow",
    "followSuccess": "Follow Success",

    "saveOptionDialogTitle": "Modify repeat schedule",
    "selectModifyCalendarTypeNotice": "Please select the type of schedule you want to modify",
    "calendarModifyTypeArr":["Only modify the current schedule", "Modify the current schedule and this repeating schedule afterwards", "Modify all this repeating schedule"],

    "deleteOptionDialogTitle": "Delete duplicate schedule",
    "selectDeleteCalendarTypeNotice": "Please select the type of calendar you want to delete",
    "calendarDeleteTypeArr":["Only modify the current schedule", "Modify the current schedule and this repeating schedule afterwards", "Modify all this repeating schedule"],

    "countEvents": "Item Schedule",
    "noEventWeek": "No event within a week",
    "am": "a.m.",
    "pm": "p.m.",
    "eventNotice": "reminder",

    "delete": "Delete",

    "cancel_confirm_title": "Confirm Delete Schedule",
    "cancel_confirm": "Cannot be restored after deletion. Are you sure you want to delete '{name}' schedule?",

    "cancelEvent": "Delete",

    "addEvent": "New Schedule",
    "editEvent": "Edit Schedule",
    "readEvent": "View Schedule",
    "color": "Color",
    "repeatFrequencyArr": ["No","Everyday","Weekly","Monthly (on the day)","Yearly (on the day)"],
    "repeatFrequencyArr2": ["Do not repeat","Every day","Weekly","Monthly (on the day)","Yearly (on the day)"],
    "repeatInfor": "Repeat every {frequency}",
    "remindIntervalArr": ["Do not remind", "At the beginning", "5 minutes early", "10 minutes early", "15 minutes early", "30 minutes early", "1 hour early", "2 hours early" ],
    "allDay": "All Day",
    "trueFalseArr": ["Yes","No"],
    "font": "Font",

    "refresh": "Refresh",
    "setting": "Settings",
    "phone": "Mobile",
    "mail": "Mailbox",
    "eventSubject": "Title",
    "eventDescription": "Description",
    "eventAttachment": "Attachment",
    "eventDetail": "Details",
    "content": "Content",
    "none": "none",

    "address": "Location",
    "locationName": "Location",
    "name": "Name",
    "eventTopInfor": "Hello {userName}!<br/>Today you have <span style='color: #FB4747'>{count}</span> event:",
    "noEventTopInfor": "Hello {userName}! You have no event for today.",

    "createSuccess": "Created successfully!",
    "updateSuccess": "Save successfully!",
    "config_saveSuccess": "Configuration saved successfully!",

    "deleteCalendar": "Delete",
    "deleteCalendarTitle": "Delete Confirmation",
    "deleteCalendarContent": "Cannot be restored after deletion. Are you sure you want to delete '{name}'?",
    "deleteSuccess": "Delete successfully",

    "editCalendar": "Edit Calendar",
    "onlyViewCurrent": "Only view current",
    "viewCalendar": "Calendar Details",
    "noPublicCalendar": "There is no public calendar in the system!",
    "create": "New",

    "cancel_createEvent_title": "Delete Schedule Confirmation",
    "cancel_createEvent": "The schedule is about to be deleted. The data you filled in will be lost. Are you sure you want to cancel the current schedule?",

    "event_input_error": "Please fill in the following correctly:<br/>",
    //"event_input_subject_error": "Please fill in the complete agenda title!",
    //"event_input_room_error": "Please select the schedule room!",
    //"event_input_person_error": "Please choose to invite participants!",
    //"event_input_date_error": "Please select the correct start date and time of the schedule!",
    //"event_input_time_error": "Please select the start time and end time of the schedule correctly!",

    "event_input_subject_error": "The agenda title cannot be empty!",
    "event_input_time_error": "The end time of the schedule cannot be earlier than the start time!",


    //"event_input_subject_error": "Please fill in the complete agenda title!",
    "event_saveSuccess": "The schedule was saved successfully!",

    "deleteAttachmentTitle":"Delete attachment confirmation",
    "deleteAttachment": "Are you sure you want to delete the attachment you selected?",

    "dateFormatMonth": "%Y-%m",
    "dateFormatMonthDay": "%m-%d",
    "dateFormatMonthDay2": "%m-%e",
    "dateFormatMonthOnly": "%m",
    "dateFormatDay": "%Y-%m-%d",
    "dateFormatDayOnly": "%d",
    "dateFormatAll": "%Y-%m-%d %H:%M",
    "dateFormat": "db",
    "person": "person",
    "personal": "Personal",
    "persist": "persist",
    "date": "Day",
    "hour": "Hour",
    "minute": "minute",
    "second": "second",
    "to": "to",
    "all": "All",
    "remindInAdvance": "Remind {text} in advance",
    "isAvaliable": "enable",
    "manager": "Manager",
    "viewerRange": "Visible Range",
    "publisherRange": "Create a new range",

    "noTask": "No Schedule Today",
    "noEvent": "No event on the day",
    "noAddress": "Address not filled in",
    "noEventCurMonth": "There is no schedule for the month",
    "weeklyViewTitle": "{month}, week {week}",

    "week": "Week",
    "weeks": {
        "Sun": "Sun",
        "Mon": "Mon",
        "Tues": "Tues",
        "Wed": "Wed",
        "Thur": "Thur",
        "Fri": "Fri",
        "Sat": "Sat",
        "arr": ["Sun","Mon","Tues","Wed","Thur","Fri","Sat"],
        "rruleArr": ["SU","MO","TU","WE","TH","FR","SA"]
    },
    "weeksShort": {
        "Sun": "Sun",
        "Mon": "Mon",
        "Tues": "Tues",
        "Wed": "Wed",
        "Thur": "Thur",
        "Fri": "Fri",
        "Sat": "Sat",
        "arr": ["Sun","Mon","Tues","Wed","Thur","Fri","Sat"],
        "rruleArr": ["SU","MO","TU","WE","TH","FR","SA"]
    },
    "config": {
        "navi": "Navigation",
        "autoHide": "AutoHide",
        "default": "Default View",
        "applyProcess": "Schedule Process",
        "legend": "Icon",
        "eventStatus": "Event Status",
        "wait": "Appointed",
        "progress": "Progress",
        "completed": "Completed",
        "invite": "Invitation",
        "weekBegin": "Starting day of the week",
        "viewSetting": "Enable View",
        "viewCustomName": "View display name",
        "mobileCreateEnable": "Whether the mobile terminal can create a new schedule",
        "mobileCreateEnableOptions": ["Yes","No"]
    },
    "nextActivity": "Next Activity:",
    "nextUser": "Processor:",
    "deal": "Deal",
    "processStarted": "File has been started",
    "processStartedMessage": "You started a new job:",
    "add": "Add",
    "more": "More",
    "schedule": {
        "noEvent": "You have no agenda for the day",
        "current": "Currently you have",
        "someEvent": "Item agenda!"
    }
};