MWF.xApplication.Calendar.LP = {
	"title": "スケジュール",
    "calendar": "カレンダー",
    "event": "予定",
    "subject": "件名",
    "applyPerson": "申請者",
    "myCalendar": "私のカレンダー",
    "year": "年",
    "month": "月",
    "day": "日",
    "list": "予定一覧",
    "today": "今日",
    "tomorrow": "明日",
    "afterTomorrow": "明後日",
    "yesterday": "昨日",
    "beforeYesterday": "一昨日",
    "nextMonth": "翌月",
    "floor": "フロア",
    "enable": "有効",
    "disable": "無効",
    "modifyConfirm": "変更を確認",
    "cancel": "中止",
    "close": "閉じる",
    "save": "保存",
    //"inputAddress": "输入地址",
    "begin": "開始",
    "beginTime": "開始時間",
    "end": "終了",
    "endTime": "終了時間",
    "time": "時間",
    "remind": "リマインダー",
    "repeat": "繰り返し",
    "notRepeat": "繰り返さない",
    "repeatUntilAvailable": "終了",
    "repeatUntilAvailableTextArr": ["永遠に", "終了日"],
    "eventTime": "イベント時間",
    "endDate": "終了日",
    "remindWhenBegin": "開始時にリマインダー",
    "no": "いいえ",
    "editMore": "詳細編集",
    "calendarName": "カレンダー名",
    "createCalendar": "カレンダー作成",
    "createNewCalendar": "カレンダー作成",
    "seeMore": "詳細表示",
    "calendarMarket": "カレンダーマーケット",

    "description": "備考",
    "type": "タイプ",
    "canlendarTypeArr": ["個人カレンダー", "組織カレンダー"],
    "unitCalendar": "組織カレンダー",
    "myFollowCalendar": "フォローしたカレンダー",
    "unit": "所属組織",
    "unit2": "組織,",
    "belongTo": "所属",
    "unitEmptyNotice": "所属組織を入力してください",
    "isOpened": "公開",
    "followed": "フォロー中",
    "clickToCancelFollow": "フォローをキャンセルするにはクリック",
    "cancelFollowSuccess": "フォローをキャンセルしました",
    "follow": "フォロー",
    "followSuccess": "フォローが成功しました",

    "saveOptionDialogTitle": "繰り返しスケジュールの変更",
    "selectModifyCalendarTypeNotice": "変更するスケジュールの種類を選択してください",
    "calendarModifyTypeArr": ["現在のスケジュールのみ変更", "現在のスケジュールおよび今後の繰り返しスケジュールの変更", "この繰り返しスケジュールすべて変更"],
    "deleteOptionDialogTitle": "繰り返しスケジュールの削除",
    "selectDeleteCalendarTypeNotice": "削除するスケジュールの種類を選択してください",
    "calendarDeleteTypeArr": ["現在のスケジュールのみ削除", "現在のスケジュールおよび今後の繰り返しスケジュールの削除", "この繰り返しスケジュールすべて削除"],
    "countEvents": "スケジュール",
    "noEventWeek": "週間にスケジュールがありません",
    "am": "午前",
    "pm": "午後",
    "eventNotice": "スケジュールリマインダー",
    "delete": "削除",
    "cancel_confirm_title": "スケジュール削除の確認",
    "cancel_confirm": "削除後は元に戻せません。'{name}' スケジュールを削除しますか？",
    "cancelEvent": "スケジュール削除",

    "addEvent": "イベントを追加",
    "editEvent": "イベントを編集",
    "readEvent": "イベントを表示",
    "color": "色",
    "repeatFrequencyArr": ["繰り返さない", "毎日", "毎週", "毎月（当日）", "毎年（当日）"],
    "repeatFrequencyArr2": ["繰り返さない", "毎日", "毎週", "毎月（当日）", "毎年（当日）"],
    "repeatInfor": "毎{frequency}繰り返し",
    "remindIntervalArr": ["リマインダーなし", "開始時刻", "5分前", "10分前", "15分前", "30分前", "1時間前", "2時間前"],
    "allDay": "終日",
    "trueFalseArr": ["はい", "いいえ"],
    "font": "フォント",
    "refresh": "リフレッシュ",
    "setting": "設定",
    "phone": "携帯電話",
    "mail": "メール",
    "eventSubject": "タイトル",
    "eventDescription": "スケジュールの説明",
    "eventAttachment": "添付ファイル",
    "eventDetail": "スケジュール詳細",
    "content": "内容",
    "none": "なし",
    "address": "場所",
    "locationName": "場所名",
    "name": "名前",
    "eventTopInfor": "{userName} こんにちは！今日は<span style='color: #FB4747'>{count}</span>件のスケジュールがあります：",
    "noEventTopInfor": "{userName} こんにちは！今日はスケジュールがありません。",

    "createSuccess": "作成成功！",
    "updateSuccess": "保存成功！",
    "config_saveSuccess": "設定保存成功！",
    "deleteCalendar": "削除",
    "deleteCalendarTitle": "削除の確認",
    "deleteCalendarContent": "削除後は元に戻せません。'{name}' を削除しますか？",
    "deleteSuccess": "削除成功",
    "editCalendar": "カレンダーの編集",
    "onlyViewCurrent": "現在だけ表示",
    "viewCalendar": "カレンダーの詳細",
    "noPublicCalendar": "システム内にはまだ公開カレンダーがありません！",
    "create": "新規作成",
    "cancel_createEvent_title": "スケジュールの削除の確認",
    "cancel_createEvent": "スケジュールを削除しようとしています。入力したデータは失われます。現在のスケジュールをキャンセルしますか？",
    "event_input_error": "以下の内容を正しく入力してください：<br/>",
    //"event_input_subject_error": "请填写完整日程标题！",
    //"event_input_room_error": "请选择日程室！",
    //"event_input_person_error": "请选择邀请参会人员！",
    //"event_input_date_error": "请正确选择日程开始日期和时间！",
    //"event_input_time_error": "请正确选择日程开始时间和结束时间！",
    //"event_input_subject_error": "请填写完整日程标题！",

    "event_input_subject_error": "スケジュールのタイトルが空白です！",
    "event_input_time_error": "スケジュールの終了時間は開始時間より早いことはできません！",
    "event_saveSuccess": "スケジュールの保存が成功しました！",
    "deleteAttachmentTitle": "添付ファイル削除の確認",
    "deleteAttachment": "選択した添付ファイルを削除しますか？",
    "dateFormatMonth": "%Y年%m月",
    "dateFormatMonthDay": "%m月%d日",
    "dateFormatMonthDay2": "%m月%e日",
    "dateFormatMonthOnly": "%m月",
    "dateFormatDay": "%Y年%m月%d日",
    "dateFormatDayOnly": "%d日",
    "dateFormatAll": "%Y年%m月%d日 %H:%M",
    "dateFormat": "db",
    "person": "人",
    "personal": "個人",
    "persist": "継続",
    "date": "日",
    "hour": "時間",
    "minute": "分",
    "second": "秒",
    "to": "から",
    "all": "全て",
    "remindInAdvance": "{text}前に通知",
    "isAvaliable": "利用可能",
    "manager": "管理者",
    "viewerRange": "表示範囲",
    "publisherRange": "新規作成範囲",
    "noTask": "今日のスケジュールはありません",
    "noEvent": "当日のスケジュールはありません",
    "noAddress": "住所が記入されていません",
    "noEventCurMonth": "今月のスケジュールはありません",
    "weeklyViewTitle": "{month}、第{week}週",

    "week": "週",
    "weeks": {
        "Sun": "日曜日",
        "Mon": "月曜日",
        "Tues": "火曜日",
        "Wed": "水曜日",
        "Thur": "木曜日",
        "Fri": "金曜日",
        "Sat": "土曜日",
        "arr": ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"],
        "rruleArr": ["SU", "MO", "TU", "WE", "TH", "FR", "SA"]
    },
    "weeksShort": {
        "Sun": "日",
        "Mon": "月",
        "Tues": "火",
        "Wed": "水",
        "Thur": "木",
        "Fri": "金",
        "Sat": "土",
        "arr": ["日", "月", "火", "水", "木", "金", "土"],
        "rruleArr": ["SU", "MO", "TU", "WE", "TH", "FR", "SA"]
    },
    "config": {
        "navi": "ナビゲーション",
        "autoHide": "自動非表示",
        "default": "デフォルトビュー",
        "applyProcess": "スケジュールプロセス",
        "legend": "図示",
        "eventStatus": "スケジュールステータス",
        "wait": "予約済み",
        "progress": "進行中",
        "completed": "終了済み",
        "invite": "スケジュール招待",
        "weekBegin": "週の開始日",
        "viewSetting": "ビューを有効化",
        "viewCustomName": "ビュー表示名",
        "mobileCreateEnable": "モバイルでスケジュールを作成できるか",
        "mobileCreateEnableOptions": ["はい", "いいえ"]
    },
    "nextActivity": "次のアクティビティ：",
    "nextUser": "担当者：",
    "deal": "処理",
    "processStarted": "ファイルが開始されました",
    "processStartedMessage": "新しい業務を開始しました：",
    "add": "追加",
    "more": "さらに表示",
    "schedule": {
        "noEvent": "今日は予定がありません",
        "current": "現在、",
        "someEvent": "件の予定があります！"
    }
};