MWF.xApplication.Calendar.LP = {
	"title": "일정 계획",
    "calendar": "달력",
    "event": "일정",
    "subject": "제목",
    "applyPerson": "신청자",
    "myCalendar": "내 캘린더",
    "year": "년",
    "month": "월",
    "day": "일",
    "list": "일정 목록",
    "today": "오늘",
    "tomorrow": "내일",
    "afterTomorrow": "모레",
    "yesterday": "어제",
    "beforeYesterday": "그제",
    "nextMonth": "다음 달",
    "floor": "층",
    "enable": "사용 가능",
    "disable": "비활성화",
    "modifyConfirm": "수정 확인",
    "cancel": "취소",
    "close": "닫기",
    "save": "저장",
    //"inputAddress": "输入地址",
    "begin": "시작",
    "beginTime": "시작 시간",
    "end": "끝",
    "endTime": "끝 시간",
    "time": "시간",
    "remind": "알림",
    "repeat": "반복",
    "notRepeat": "반복 안 함",
    "repeatUntilAvailable": "종료",
    "repeatUntilAvailableTextArr": ["영원히", "종료 날짜"],
    "eventTime": "일정 시간",
    "endDate": "종료 날짜",
    "remindWhenBegin": "시작 시 알림",
    "no": "아니요",
    "editMore": "더 많은 편집",
    "calendarName": "일정 이름",
    "createCalendar": "새로운 일정 생성",
    "createNewCalendar": "새로운 일정 생성",
    "seeMore": "더 보기",
    "calendarMarket": "일정 시장",

    "description": "비고",
    "type": "유형",
    "canlendarTypeArr": ["개인 캘린더", "조직 캘린더"],
    "unitCalendar": "조직 캘린더",
    "myFollowCalendar": "팔로우한 캘린더",
    "unit": "소속 조직",
    "unit2": "조직,",
    "belongTo": "속해 있음",
    "unitEmptyNotice": "소속 조직을 입력하세요",
    "isOpened": "공개 여부",
    "followed": "팔로우됨",
    "clickToCancelFollow": "팔로우 취소를 클릭하세요",
    "cancelFollowSuccess": "팔로우 취소가 성공했습니다",
    "follow": "팔로우",
    "followSuccess": "팔로우가 성공했습니다",

    "saveOptionDialogTitle": "반복 일정 수정",
    "selectModifyCalendarTypeNotice": "수정할 일정 유형을 선택하세요",
    "calendarModifyTypeArr": ["현재 일정만 수정", "현재 및 이후 반복 일정 수정", "이 반복 일정 모두 수정"],
    "deleteOptionDialogTitle": "반복 일정 삭제",
    "selectDeleteCalendarTypeNotice": "삭제할 일정 유형을 선택하세요",
    "calendarDeleteTypeArr": ["현재 일정만 삭제", "현재 및 이후 반복 일정 삭제", "이 반복 일정 모두 삭제"],
    "countEvents": "일정",
    "noEventWeek": "주간 일정 없음",
    "am": "오전",
    "pm": "오후",
    "eventNotice": "일정 알림",
    "delete": "삭제",
    "cancel_confirm_title": "일정 삭제 확인",
    "cancel_confirm": "삭제 후 복구할 수 없습니다. ' {name} ' 일정을 삭제하시겠습니까?",
    "cancelEvent": "일정 삭제",

    "addEvent": "일정 추가",
    "editEvent": "일정 편집",
    "readEvent": "일정 확인",
    "color": "색상",
    "repeatFrequencyArr": ["반복 안 함", "매일", "매주", "매월 (당일)", "매년 (당일)"],
    "repeatFrequencyArr2": ["반복 안 함", "매일", "매주", "매월 (당일)", "매년 (당일)"],
    "repeatInfor": "매 {frequency} 반복",
    "remindIntervalArr": ["알림 없음", "시작 시간", "5분 전", "10분 전", "15분 전", "30분 전", "1시간 전", "2시간 전"],
    "allDay": "하루 종일",
    "trueFalseArr": ["예", "아니요"],
    "font": "글꼴",
    "refresh": "새로 고침",
    "setting": "설정",
    "phone": "휴대폰",
    "mail": "이메일",
    "eventSubject": "제목",
    "eventDescription": "일정 설명",
    "eventAttachment": "첨부 파일",
    "eventDetail": "일정 상세 정보",
    "content": "내용",
    "none": "없음",
    "address": "장소",
    "locationName": "장소명",
    "name": "이름",
    "eventTopInfor": "{userName} 안녕하세요! 오늘은 <span style='color: #FB4747'>{count}</span>개의 일정이 있습니다.",
    "noEventTopInfor": "{userName} 안녕하세요! 오늘은 일정이 없습니다.",

    "createSuccess": "생성 성공!",
    "updateSuccess": "저장 성공!",
    "config_saveSuccess": "구성 저장 성공!",
    "deleteCalendar": "캘린더 삭제",
    "deleteCalendarTitle": "삭제 확인",
    "deleteCalendarContent": "삭제 후에는 복구할 수 없습니다. ' {name} '을(를) 삭제하시겠습니까?",
    "deleteSuccess": "삭제 성공",
    "editCalendar": "캘린더 편집",
    "onlyViewCurrent": "현재 캘린더만 표시",
    "viewCalendar": "캘린더 세부 정보",
    "noPublicCalendar": "시스템에 공개 캘린더가 아직 없습니다!",
    "create": "새로 만들기",
    "cancel_createEvent_title": "일정 삭제 확인",
    "cancel_createEvent": "일정을 삭제하려고 합니다. 입력한 데이터는 손실됩니다. 현재 일정을 취소하시겠습니까?",
    "event_input_error": "다음 내용을 올바르게 입력하세요：<br/>",
    //"event_input_subject_error": "请填写完整日程标题！",
    //"event_input_room_error": "请选择日程室！",
    //"event_input_person_error": "请选择邀请参会人员！",
    //"event_input_date_error": "请正确选择日程开始日期和时间！",
    //"event_input_time_error": "请正确选择日程开始时间和结束时间！",
    //"event_input_subject_error": "请填写完整日程标题！",

    "event_input_subject_error": "일정 제목을 입력하세요!",
    "event_input_time_error": "일정 종료 시간은 시작 시간보다 빨라서는 안됩니다!",
    "event_saveSuccess": "일정 저장 성공!",
    "deleteAttachmentTitle": "첨부 파일 삭제 확인",
    "deleteAttachment": "선택한 첨부 파일을 삭제하시겠습니까?",
    "dateFormatMonth": "%Y년%m월",
    "dateFormatMonthDay": "%m월%d일",
    "dateFormatMonthDay2": "%m월%e일",
    "dateFormatMonthOnly": "%m월",
    "dateFormatDay": "%Y년%m월%d일",
    "dateFormatDayOnly": "%d일",
    "dateFormatAll": "%Y년%m월%d일 %H:%M",
    "dateFormat": "db",
    "person": "인",
    "personal": "개인",
    "persist": "지속",
    "date": "일",
    "hour": "시간",
    "minute": "분",
    "second": "초",
    "to": "에서",
    "all": "모두",
    "remindInAdvance": "미리{text} 알림",
    "isAvaliable": "사용 여부",
    "manager": "관리자",
    "viewerRange": "표시 범위",
    "publisherRange": "생성 범위",
    "noTask": "오늘 일정이 없습니다",
    "noEvent": "당일 일정이 없습니다",
    "noAddress": "주소를 입력하지 않았습니다",
    "noEventCurMonth": "이번 달 일정이 없습니다",
    "weeklyViewTitle": "{month} {week} 주",

    "week": "주",
    "weeks": {
        "Sun": "일요일",
        "Mon": "월요일",
        "Tues": "화요일",
        "Wed": "수요일",
        "Thur": "목요일",
        "Fri": "금요일",
        "Sat": "토요일",
        "arr": ["일요일", "월요일", "화요일", "수요일", "목요일", "금요일", "토요일"],
        "rruleArr": ["SU", "MO", "TU", "WE", "TH", "FR", "SA"]
    },
    "weeksShort": {
        "Sun": "일",
        "Mon": "월",
        "Tues": "화",
        "Wed": "수",
        "Thur": "목",
        "Fri": "금",
        "Sat": "토",
        "arr": ["일", "월", "화", "수", "목", "금", "토"],
        "rruleArr": ["SU", "MO", "TU", "WE", "TH", "FR", "SA"]
    },
    "config": {
        "navi": "내비게이션",
        "autoHide": "자동 숨김",
        "default": "기본 보기",
        "applyProcess": "일정 프로세스",
        "legend": "범례",
        "eventStatus": "일정 상태",
        "wait": "예약됨",
        "progress": "진행 중",
        "completed": "종료됨",
        "invite": "일정 초대",
        "weekBegin": "주 시작일",
        "viewSetting": "보기 활성화",
        "viewCustomName": "보기 표시 이름",
        "mobileCreateEnable": "모바일에서 일정 생성 가능 여부",
        "mobileCreateEnableOptions": ["예", "아니요"]
    },
    "nextActivity": "다음 활동:",
    "nextUser": "담당자:",
    "deal": "처리",
    "processStarted": "문서가 시작되었습니다",
    "processStartedMessage": "새로운 업무를 시작했습니다:",
    "add": "추가",
    "more": "더보기",
    "schedule": {
        "noEvent": "오늘은 일정이 없습니다",
        "current": "현재",
        "someEvent": "개의 일정이 있습니다!"
    }
};