MWF.xApplication.Calendar.LP = {
    "title": "ປະຕິທິນ",

    "calendar": "ປະຕິທິນ",
    "event": "ເຫດການ",
    "subject": "ຫົວຂໍ້",
    "applyPerson": "ຜູ້ສະໝັກ",
    "myCalendar": "ປະຕິທິນຂອງຂ້ອຍ",
    "year": "ປີ",
    "month": "ເດືອນ",
    "day": "ວັນ",
    "list": "ຕາຕະລາງ",
    "today": "ມື້ນີ້",
    "tomorrow": "ມື້ອື່ນ",
    "afterTomorrow": "ມື້ຫຼັງຈາກມື້ອື່ນ",
    "yesterday": "ມື້ວານນີ້",
    "beforeYesterday": "ມື້ກ່ອນມື້ວານນີ້",
    "nexMonth": "ເດືອນຕໍ່ໄປ",
    "floor": "ຊັ້ນ",
    "enable": "ມີຢູ່",
    "disable": "ປິດການໃຊ້ງານ",
    "modifyConfirm": "ຢືນຢັນການດັດແກ້",
    "cancel": "ຍົກເລີກ",
    "close": "ປິດ",
    "save": "ບັນທຶກ",
    //"inputAddress": "ທີ່ຢູ່ປ້ອນເຂົ້າ",
    "begin": "ເລີ່ມຕົ້ນ",
    "beginTime": "ເລີ່ມຕົ້ນ",
    "end": "ສິ້ນສຸດ",
    "endTime": "ສິ້ນສຸດ",
    "time": "ເວລາ",
    "remind": "ເຕືອນ",
    "repeat": "ເຮັດຊ້ຳ",
    "notRepeat": "ບໍ່ຊໍ້າຄືນ",
    "repeatUntilAvailable": "ສິ້ນສຸດ",
    "repeatUntilAvailableTextArr": ["ບໍ່ເຄີຍ", "ວັນທີສິ້ນສຸດ"],
    "eventTime": "ເວລາກໍານົດ",
    "endDate": "ວັນສິ້ນສຸດ",
    "remindWhenBegin": "ເຕືອນເມື່ອເລີ່ມຕົ້ນ",
    "no": "ບໍ່",
    "editMore": "ດັດແກ້ເພີ່ມເຕີມ",
    "calendarName": "ຊື່ປະຕິທິນ",
    "createCalendar": "ປະຕິທິນໃໝ່",
    "createNewCalendar": "ປະຕິທິນໃໝ່",
    "seeMore": "ເບິ່ງເພີ່ມເຕີມ",
    "calendarMarket": "ປະຕິທິນ Square",

    "description": "ຂໍ້ສັງເກດ",
    "type": "ປະເພດ",
    "canlendarTypeArr": ["ປະຕິທິນສ່ວນຕົວ", "ປະຕິທິນອົງການ"],
    "unitCalendar": "ປະຕິທິນອົງການ",
    "myFollowCalendar": "ປະຕິທິນທີ່ຕິດຕາມ",
    "unit": "ອົງການທີ່ເປັນເຈົ້າຂອງ",
    "unit2": "ອົງການ,",
    "belongTo": "ເປັນຂອງ",
    "unitEmptyNotice": "ການເປັນເຈົ້າຂອງອົງກອນບໍ່ສາມາດຫວ່າງເປົ່າໄດ້",
    "isOpened": "ເປີດບໍ",
    "followed": "ຕິດຕາມ",
    "clickToCancelFollow": "ຄລິກເພື່ອຍົກເລີກການຕິດຕາມ",
    "cancelFollowSuccess": "ເຊົາຕິດຕາມຄວາມສຳເລັດ",
    "follow": "ຕິດຕາມ",
    "followSuccess": "ປະຕິບັດຕາມຄວາມສຳເລັດ",

    "saveOptionDialogTitle": "ແກ້ໄຂຕາຕະລາງການເຮັດຊ້ຳ",
    "selectModifyCalendarTypeNotice": "ກະລຸນາເລືອກປະເພດຂອງຕາຕະລາງທີ່ທ່ານຕ້ອງການແກ້ໄຂ",
    "calendarModifyTypeArr":["ປັບປຸງຕາຕະລາງການປະຈຸບັນເທົ່ານັ້ນ", "ປັບປຸງແກ້ໄຂກໍານົດເວລາປະຈຸບັນແລະຕາຕະລາງການຊ້ໍານີ້ຫຼັງຈາກນັ້ນ", "ປັບປຸງແກ້ໄຂກໍານົດເວລາການຊ້ໍາທັງຫມົດນີ້"],

    "deleteOptionDialogTitle": "ລົບກຳນົດການຊໍ້າກັນ",
    "selectDeleteCalendarTypeNotice": "ກະລຸນາເລືອກປະເພດຂອງປະຕິທິນທີ່ທ່ານຕ້ອງການລົບ",
    "calendarDeleteTypeArr":["ແກ້ໄຂການກຳນົດການປັດຈຸບັນເທົ່ານັ້ນ", "ແກ້ໄຂກຳນົດການປະຈຸບັນ ແລະກຳນົດການຊໍ້າຄືນນີ້ຫຼັງຈາກນັ້ນ", "ແກ້ໄຂກຳນົດການຊໍ້າຄືນທັງໝົດນີ້"],

    "countEvents": "ກຳນົດລາຍການ",
    "noEventWeek": "ບໍ່ມີເຫດການພາຍໃນໜຶ່ງອາທິດ",
    "am": "ໂມງເຊົ້າ.",
    "pm": "ໂມງແລງ",
    "eventNotice": "ເຕືອນ",

    "delete": "ລົບ",

    "cancel_confirm_title": "ຢືນຢັນການລົບຕາຕະລາງ",
    "cancel_confirm": "ບໍ່ສາມາດກູ້ຄືນໄດ້ຫຼັງຈາກການລົບ",

    "cancelEvent": "ລົບ",

    "addEvent": "ກຳນົດການໃໝ່",
    "editEvent": "ແກ້ໄຂກຳນົດການ",
    "readEvent": "ເບິ່ງກຳນົດການ",
    "color": "ສີ",
    "repeatFrequencyArr": ["ບໍ່","ທຸກໆມື້","ລາຍອາທິດ","ລາຍເດືອນ(ໃນມື້)","ລາຍປີ(ໃນມື້)"],
    "repeatFrequencyArr2": ["ຫ້າມເຮັດຊ້ຳ","ທຸກໆມື້","ລາຍອາທິດ","ລາຍເດືອນ(ໃນມື້)","ລາຍປີ(ໃນມື້)"],
    "repeatInfor": "ເຮັດຊ້ຳທຸກໆ {frequency}",
    "remindIntervalArr": ["ຢ່າເຕືອນ", "ໃນຕອນຕົ້ນ", "5 ນາທີຕົ້ນ", "10 ນາທີຕົ້ນ", "15 ນາທີຕົ້ນ", "30 ນາທີກ່ອນ", "1 ຊົ່ວໂມງກ່ອນ", "2 ຊົ່ວໂມງ ຕົ້ນ" ],
    "allDay": "ໝົດມື້",
    "trueFalseArr": ["ແມ່ນ","ບໍ່"],
    "font": "ຕົວອັກສອນ",

    "refresh": "ໂຫຼດຫນ້າຈໍຄືນ",
    "setting": "ການຕັ້ງຄ່າ",
    "phone": "ມືຖື",
    "mail": "ກ່ອງຈົດໝາຍ",
    "eventSubject": "ຫົວຂໍ້",
    "eventDescription": "ລາຍລະອຽດ",
    "eventAttachment": "ເອກະສານຄັດຕິດ",
    "eventDetail": "ລາຍລະອຽດ",
    "content": "ເນື້ອໃນ",
    "none": "ບໍ່ມີ",

    "address": "ສະຖານທີ່",
    "locationName": "ສະຖານທີ່",
    "name": "ຊື່",
    "eventTopInfor": "ສະບາຍດີ {userName}!<br/>ມື້ນີ້ທ່ານມີເຫດການ <span style='color: #FB4747'>{count}</span>:",
    "noEventTopInfor": "ສະບາຍດີ {userName}! ທ່ານບໍ່ມີນັດໝາຍສຳລັບມື້ນີ້.",

    "createSuccess": "ສ້າງສຳເລັດແລ້ວ!",
    "updateSuccess": "ບັນທຶກສຳເລັດ!",
    "config_saveSuccess": "ບັນທຶກການຕັ້ງຄ່າສຳເລັດແລ້ວ!",

    "deleteCalendar": "ລົົບ",
    "deleteCalendarTitle": "ລົບການຢືນຢັນ",
    "deleteCalendarContent": "ບໍ່ສາມາດກູ້ຄືນໄດ້ຫຼັງຈາກການລົບບ",
    "deleteSuccess": "ລົບສຳເລັດ",

    "editCalendar": "ແກ້ໄຂປະຕິທິນ",
    "onlyViewCurrent": "ເບິ່ງປັດຈຸບັນເທົ່ານັ້ນ",
    "viewCalendar": "ລາຍລະອຽດປະຕິທິນ",
    "noPublicCalendar": "ບໍ່ມີປະຕິທິນສາທາລະນະຢູ່ໃນລະບົບ!",
    "create": "ໃຫມ່",
    "cancel_createEvent_title": "ລົບການຢືນຢັນກຳນົດການ",
    "cancel_createEvent": "ກຳນົດເວລາກຳລັງຈະຖືກລົບອອກ. ຂໍ້ມູນທີ່ທ່ານຕື່ມໃສ່ຈະສູນຫາຍໄປ. ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກກຳນົດການປັດຈຸບັນ?",

    "event_input_error": "ກະລຸນາຕື່ມຂໍ້ມູນຕໍ່ໄປນີ້ໃຫ້ຖືກຕ້ອງ:<br/>",
    //"event_input_subject_error": "ກະລຸນາຕື່ມຫົວຂໍ້ວາລະທີ່ຄົບຖ້ວນ!",
    //"event_input_room_error": "ກະລຸນາເລືອກຫ້ອງກຳນົດການ!",
    //"event_input_person_error": "ກະລຸນາເລືອກເຊີນເຂົ້າຮ່ວມ!",
    //"event_input_date_error": "ກະລຸນາເລືອກວັນທີເລີ່ມຕົ້ນທີ່ຖືກຕ້ອງແລະເວລາຂອງກຳນົດການ!",
    //"event_input_time_error": "ກະລຸນາເລືອກເວລາເລີ່ມຕົ້ນແລະເວລາສິ້ນສຸດຂອງກຳນົດການຢ່າງຖືກຕ້ອງ!",

    "event_input_subject_error": "ຫົວຂໍ້ວາລະບໍ່ສາມາດຫວ່າງເປົ່າ!",
    "event_input_time_error": "ເວລາສິ້ນສຸດຂອງຕາຕະລາງບໍ່ສາມາດໄວກວ່າເວລາເລີ່ມຕົ້ນ!",


    //"event_input_subject_error": "ກະລຸນາຕື່ມຫົວຂໍ້ວາລະທີ່ຄົບຖ້ວນ!",
    "event_saveSuccess": "ຕາຕະລາງຖືກບັນທຶກສຳເລັດແລ້ວ!",

    "deleteAttachmentTitle":"ລົບການຢືນຢັນໄຟລ໌ແນບ",
    "deleteAttachment": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບໄຟລ໌ແນບທີ່ທ່ານເລືອກ?",

    "dateFormatMonth": "%Y-%m",
    "dateFormatMonthDay": "%m-%d",
    "dateFormatMonthDay2": "%m-%e",
    "dateFormatMonthOnly": "%m",
    "dateFormatDay": "%Y-%m-%d",
    "dateFormatDayOnly": "%d",
    "dateFormatAll": "%Y-%m-%d %H:%M",
    "dateFormat": "db",
    "person": "ຄົນ",
    "personal": "ສ່ວນຕົວ",
    "persist": "ຕໍ່ເນື່ອງ",
    "date": "ວັນ",
    "hour": "ຊົ່ວໂມງ",
    "minute": "ນາທີ",
    "second": "ທີສອງ",
    "to": "ໄປ",
    "all": "ທັງໝົດ",
    "remindInAdvance": "ເຕືອນ {text} ລ່ວງໜ້າ",
    "isAvaliable": "ເປີດໃຊ້",
    "manager": "ຜູ້ຈັດການ",
    "viewerRange": "ຂອບເຂດທີ່ເບິ່ງເຫັນ",
    "publisherRange": "ສ້າງຊ່ວງໃໝ່",

    "noTask": "ບໍ່ມີກຳນົດການມື້ນີ້",
    "noEvent": "ບໍ່ມີເຫດການໃນມື້",
    "noAddress": "ທີ່ຢູ່ບໍ່ໄດ້ຕື່ມໃສ່",
    "noEventCurMonth": "ບໍ່ມີກຳນົດເວລາສຳລັບເດືອນ",
    "weeklyViewTitle": "{month}, ອາທິດ {week}",

    "week": "ອາທິດ",
    "weeks": {
        "Sun": "ວັນອາທິດ",
        "Mon": "ຈັນ",
        "Tues": "ອັງຄານ",
        "Wed": "ພຸດ",
        "Thur": "ພະຫັດ",
        "Fri": "ສຸກ",
        "Sat": "ເສົາ",
        "arr": ["ວັນອາທິດ","ຈັນ","ອັງຄານ","ພຸດ","ພະຫັດ","ສຸກ","ເສົາ"],
        "rruleArr": ["ວັນອາທິດ","ຈັນ","ອັງຄານ","ພຸດ","ພະຫັດ","ສຸກ","ເສົາ"]
    },
    "weeksShort": {
        "Sun": "ວັນອາທິດ",
        "Mon": "ຈັນ",
        "Tues": "ອັງຄານ",
        "Wed": "ພຸດ",
        "Thur": "ພະຫັດ",
        "Fri": "ສຸກ",
        "Sat": "ເສົາ",
        "arr": ["ວັນອາທິດ","ຈັນ","ອັງຄານ","ພຸດ","ພະຫັດ","ສຸກ","ເສົາ"],
        "rruleArr": ["ວັນອາທິດ","ຈັນ","ອັງຄານ","ພຸດ","ພະຫັດ","ສຸກ","ເສົາ"]
    },
    "config": {
        "navi": "ນໍາທາງ",
        "autoHide": "ເຊື່ອງອັດຕະໂນມັດ",
        "default": "ເບິ່ງຄ່າເລີ່ມຕົ້ນ",
        "applyProcess": "ຂະບວນການກໍານົດເວລາ",
        "legend": "ໄອຄອນ",
        "eventStatus": "ສະຖານະເຫດການ",
        "wait": "ແຕ່ງຕັ້ງ",
        "progress": "ຄວາມຄືບໜ້າ",
        "completed": "ສໍາເລັດ",
        "invite": "ເຊີນ",
        "weekBegin": "ມື້ເລີ່ມຕົ້ນຂອງອາທິດ",
        "viewSetting": "ເປີດການເບິ່ງ",
        "viewCustomName": "ເບິ່ງຊື່ທີ່ສະແດງ",
        "mobileCreateEnable": "ບໍ່ວ່າສະຖານີໂທລະສັບມືຖືສາມາດສ້າງກຳນົດການໃຫມ່ໄດ້",
        "mobileCreateEnableOptions":["ແມ່ນ","ບໍ່"]
    },
    "nextActivity": "ການເຄື່ອນໄຫວຕໍ່ໄປ:",
    "nextUser": "ໂປເຊດເຊີ:",
    "deal": "ການຕົກລົງ",
    "processStarted": "ໄຟລ໌ໄດ້ຖືກເລີ່ມຕົ້ນ",
    "processStartedMessage": "ເຈົ້າໄດ້ເລີ່ມວຽກໃໝ່:",
    "add": "ເພີ່ມ",
    "more": "ຫຼາຍ",
    "ກຳນົດການ": {
        "noEvent": "ທ່ານບໍ່ມີວາລະສຳລັບມື້",
        "current": "ປະຈຸບັນທ່ານມີ",
        "someEvent": "ວາລະລາຍການ!",
    }
};