MWF.xApplication.Calendar.LP = {
	"title": "日程安排",

    "calendar" : "日历",
    "event" : "日程",
    "subject": "标题",
    "applyPerson": "申请人",
    "myCalendar": "我的日历",
    "year" : "年",
    "month": "月",
    "day": "日",
    "list": "日程",
    "today": "今天",
    "tomorrow": "明天",
    "afterTomorrow": "后天",
    "yesterday": "昨天",
    "beforeYesterday": "前天",
    "nextMonth": "下月",
    "floor": "层",
    "enable": "可用",
    "disable": "停用",
    "modifyConfirm": "确定修改",
    "cancel": "取消",
    "close": "关闭",
    "save": "保存",
    //"inputAddress": "输入地址",
    "begin": "开始",
    "beginTime": "开始",
    "end": "结束",
    "endTime": "结束",
    "time": "时间",
    "remind" : "提醒",
    "repeat" : "重复",
    "notRepeat" : "不重复",
    "repeatUntilAvailable" : "结束",
    "repeatUntilAvailableTextArr" : ["永不", "结束日期"],
    "eventTime" : "日程时间",
    "endDate" : "结束日期",
    "remindWhenBegin" : "开始时提醒",
    "no": "不",
    "editMore": "更多编辑",
    "calendarName" : "日历名称",
    "createCalendar": "新建日历",
    "createNewCalendar": "新建新日历",
    "seeMore" : "查看更多",
    "calendarMarket": "日历广场",

    "description" : "备注",
    "type" : "类型",
    "canlendarTypeArr": ["个人日历", "组织日历"],
    "unitCalendar" : "组织日历",
    "myFollowCalendar" : "关注的日历",
    "unit" : "所属组织",
    "unit2": "组织，",
    "belongTo": "所属",
    "unitEmptyNotice" : "所属组织不能为空",
    "isOpened" : "是否公开",
    "followed" : "已关注",
    "clickToCancelFollow": "点击取消关注",
    "cancelFollowSuccess": "取消关注成功",
    "follow" : "关注",
    "followSuccess" : "关注成功",

    "saveOptionDialogTitle": "修改重复日程",
    "selectModifyCalendarTypeNotice": "请选择您要修改日程的类型",
    "calendarModifyTypeArr":["只修改当前日程", "修改当前日程和之后的此重复日程","修改所有此重复日程"],

    "deleteOptionDialogTitle": "删除重复日程",
    "selectDeleteCalendarTypeNotice" : "请选择您要删除日程的类型",
    "calendarDeleteTypeArr":["只修改当前日程", "修改当前日程和之后的此重复日程","修改所有此重复日程"],

    "countEvents": "项日程",
    "noEventWeek": "一周内无日程",
    "am" : "上午",
    "pm" : "下午",
    "eventNotice" : "日程提醒",

    "delete" : "删除",

    "cancel_confirm_title": "删除日程确认",
    "cancel_confirm": "删除后不能恢复，确定要删除“{name}”日程吗?",

    "cancelEvent" : "删除日程",

    "addEvent": "新建日程",
    "editEvent" : "编辑日程",
     "readEvent" : "查看日程",
    "color" : "颜色",
    "repeatFrequencyArr" : ["不","每天","每周","每月（当日）","每年（当日）"],
    "repeatFrequencyArr2" : ["不重复","每天","每周","每月（当日）","每年（当日）"],
    "repeatInfor" : "每{frequency}重复",
    "remindIntervalArr" : ["不提醒","开始时","提前5分钟","提前10分钟","提前15分钟","提前30分钟","提前1小时","提前2小时"],
    "allDay" : "全天",
    "trueFalseArr" : ["是","否"],
    "font" : "字体",

    "refresh": "刷新",
    "setting": "设置",
    "phone": "手机",
    "mail": "邮箱",
    "eventSubject": "标题",
    "eventDescription": "日程描述",
    "eventAttachment": "附件",
    "eventDetail" : "日程详情",
    "content" : "内容",
    "none": "无",

    "address" : "地点",
    "locationName" : "地点",
    "name" : "名称",
    "eventTopInfor" : "{userName}，您好！<br/>今日您有<span style='color: #FB4747'>{count}</span>项日程：",
    "noEventTopInfor" : "{userName}，您好！今日您暂无日程。",

    "createSuccess" : "创建成功！",
    "updateSuccess" : "保存成功！",
    "config_saveSuccess": "配置保存成功！",

    "deleteCalendar" : "删除日历",
    "deleteCalendarTitle" : "删除确认",
    "deleteCalendarContent": "删除后无法恢复，确定要删除“{name}”？",
    "deleteSuccess" : "删除成功",

    "editCalendar" : "编辑日历",
    "onlyViewCurrent" : "只显示当前日历",
    "viewCalendar" : "日历详情",
    "noPublicCalendar" : "系统内还没有公开日历!",
    "create" : "新建",

    "cancel_createEvent_title": "删除日程确认",
    "cancel_createEvent": "即将删除日程，您填写的数据会丢失，您确定要取消当前日程吗？",

    "event_input_error": "请正确填写以下内容：<br/>",
    //"event_input_subject_error": "请填写完整日程标题！",
    //"event_input_room_error": "请选择日程室！",
    //"event_input_person_error": "请选择邀请参会人员！",
    //"event_input_date_error": "请正确选择日程开始日期和时间！",
    //"event_input_time_error": "请正确选择日程开始时间和结束时间！",

    "event_input_subject_error": "日程标题不能为空！",
    "event_input_time_error": "日程结束时间不能早于开始时间！",


    //"event_input_subject_error": "请填写完整日程标题！",
    "event_saveSuccess": "日程保存成功！",

    "deleteAttachmentTitle":"删除附件确认",
    "deleteAttachment": "是否确定要删除您选中的附件？",

    "dateFormatMonth": "%Y年%m月",
    "dateFormatMonthDay": "%m月%d日",
    "dateFormatMonthDay2": "%m月%e日",
    "dateFormatMonthOnly": "%m月",
    "dateFormatDay": "%Y年%m月%d日",
    "dateFormatDayOnly": "%d日",
    "dateFormatAll": "%Y年%m月%d日 %H:%M",
    "dateFormat": "db",
    "person": "人",
    "personal" : "个人",
    "persist": "持续",
    "date" : "天",
    "hour": "小时",
    "minute" : "分钟",
    "second" : "秒",
    "to" : "至",
    "all" : "全部",
    "remindInAdvance" : "提前{text}提醒",
    "isAvaliable": "是否启用",
    "manager" : "管理者",
    "viewerRange" : "可见范围",
    "publisherRange": "可新建范围",

    "noTask": "今日无日程安排",
    "noEvent": "当日无日程",
    "noAddress" : "未填写地址",
    "noEventCurMonth" : "该月无日程安排",
    "weeklyViewTitle" : "{month}，第{week}周",

    "week" : "周",
    "weeks": {
        "Sun": "周日",
        "Mon": "周一",
        "Tues": "周二",
        "Wed": "周三",
        "Thur": "周四",
        "Fri": "周五",
        "Sat": "周六",
        "arr": ["周日","周一","周二","周三","周四","周五","周六"],
        "rruleArr" : ["SU","MO","TU","WE","TH","FR","SA"]
    },
    "weeksShort": {
        "Sun": "日",
        "Mon": "一",
        "Tues": "二",
        "Wed": "三",
        "Thur": "四",
        "Fri": "五",
        "Sat": "六",
        "arr": ["日","一","二","三","四","五","六"],
        "rruleArr" : ["SU","MO","TU","WE","TH","FR","SA"]
    },
    "config": {
        "navi": "导航",
        "autoHide": "自动隐藏",
        "default": "默认视图",
        "applyProcess": "日程流程",
        "legend": "图示",
        "eventStatus" : "日程状态",
        "wait": "已预约",
        "progress": "进行中",
        "completed": "已结束",
        "invite": "日程邀请",
        "weekBegin" : "一周开始日",
        "viewSetting" : "启用视图",
        "viewCustomName" : "视图显示名称",
        "mobileCreateEnable" : "移动端是否能新建日程",
        "mobileCreateEnableOptions" : ["是","否"]
    },
    "nextActivity": "下一个活动：",
    "nextUser": "处理人：",
    "deal": "处理",
    "processStarted": "文件已启动",
    "processStartedMessage": "您启动了一个新的工作：",
    "add": "增加",
    "more": "更多",
    "schedule": {
	    "noEvent": "当天您没有议程",
        "current": "当前您有",
        "someEvent": "项议程！"
    }
};