MWF.xApplication.Calendar.LP = {
	"title": "日程安排",
    "calendar": "日曆",
    "event": "日程",
    "subject": "標題",
    "applyPerson": "申請人",
    "myCalendar": "我的日曆",
    "year": "年",
    "month": "月",
    "day": "日",
    "list": "日程",
    "today": "今天",
    "tomorrow": "明天",
    "afterTomorrow": "後天",
    "yesterday": "昨天",
    "beforeYesterday": "前天",
    "nextMonth": "下個月",
    "floor": "層",
    "enable": "可用",
    "disable": "停用",
    "modifyConfirm": "確定修改",
    "cancel": "取消",
    "close": "關閉",
    "save": "保存",
    //"inputAddress": "输入地址",
    "begin": "開始",
    "beginTime": "開始時間",
    "end": "結束",
    "endTime": "結束時間",
    "time": "時間",
    "remind": "提醒",
    "repeat": "重複",
    "notRepeat": "不重複",
    "repeatUntilAvailable": "結束",
    "repeatUntilAvailableTextArr": ["永遠", "結束日期"],
    "eventTime": "日程時間",
    "endDate": "結束日期",
    "remindWhenBegin": "開始時提醒",
    "no": "否",
    "editMore": "更多編輯",
    "calendarName": "日曆名稱",
    "createCalendar": "新建日曆",
    "createNewCalendar": "新建新日曆",
    "seeMore": "查看更多",
    "calendarMarket": "日曆市場",

    "description": "備註",
    "type": "類型",
    "canlendarTypeArr": ["個人日曆", "組織日曆"],
    "unitCalendar": "組織日曆",
    "myFollowCalendar": "關注的日曆",
    "unit": "所屬組織",
    "unit2": "組織，",
    "belongTo": "所屬",
    "unitEmptyNotice": "所屬組織不能為空",
    "isOpened": "是否公開",
    "followed": "已關注",
    "clickToCancelFollow": "點擊取消關注",
    "cancelFollowSuccess": "取消關注成功",
    "follow": "關注",
    "followSuccess": "關注成功",

    "saveOptionDialogTitle": "修改重複日程",
    "selectModifyCalendarTypeNotice": "請選擇要修改日程的類型",
    "calendarModifyTypeArr": ["僅修改當前日程", "修改當前日程和之後的重複日程", "修改所有此重複日程"],
    "deleteOptionDialogTitle": "刪除重複日程",
    "selectDeleteCalendarTypeNotice": "請選擇要刪除日程的類型",
    "calendarDeleteTypeArr": ["僅修改當前日程", "修改當前日程和之後的重複日程", "修改所有此重複日程"],
    "countEvents": "項日程",
    "noEventWeek": "一周內無日程",
    "am": "上午",
    "pm": "下午",
    "eventNotice": "日程提醒",
    "delete": "刪除",
    "cancel_confirm_title": "刪除日程確認",
    "cancel_confirm": "刪除後無法恢復，確定要刪除“{name}”的日程嗎？",
    "cancelEvent": "刪除日程",

    "addEvent": "新增日程",
    "editEvent": "編輯日程",
    "readEvent": "查看日程",
    "color": "顏色",
    "repeatFrequencyArr": ["不重複", "每天", "每週", "每月（當日）", "每年（當日）"],
    "repeatFrequencyArr2": ["不重複", "每天", "每週", "每月（當日）", "每年（當日）"],
    "repeatInfor": "每{frequency}重複",
    "remindIntervalArr": ["不提醒", "開始時", "提前5分鐘", "提前10分鐘", "提前15分鐘", "提前30分鐘", "提前1小時", "提前2小時"],
    "allDay": "全天",
    "trueFalseArr": ["是", "否"],
    "font": "字體",
    "refresh": "刷新",
    "setting": "設定",
    "phone": "手機",
    "mail": "郵箱",
    "eventSubject": "標題",
    "eventDescription": "日程描述",
    "eventAttachment": "附件",
    "eventDetail": "日程詳情",
    "content": "內容",
    "none": "無",
    "address": "地點",
    "locationName": "地點名稱",
    "name": "名稱",
    "eventTopInfor": "{userName} 你好！今天有<span style='color: #FB4747'>{count}</span>項日程：",
    "noEventTopInfor": "{userName} 你好！今天沒有日程。",

    "createSuccess": "創建成功！",
    "updateSuccess": "保存成功！",
    "config_saveSuccess": "配置保存成功！",
    "deleteCalendar": "刪除日曆",
    "deleteCalendarTitle": "刪除確認",
    "deleteCalendarContent": "刪除後無法恢復，確定要刪除“{name}”？",
    "deleteSuccess": "刪除成功",
    "editCalendar": "編輯日曆",
    "onlyViewCurrent": "只顯示當前日曆",
    "viewCalendar": "日曆詳情",
    "noPublicCalendar": "系統內還沒有公開日曆!",
    "create": "新建",
    "cancel_createEvent_title": "刪除日程確認",
    "cancel_createEvent": "即將刪除日程，您填寫的數據會丟失，您確定要取消當前日程嗎？",
    "event_input_error": "請正確填寫以下內容：<br/>",
    //"event_input_subject_error": "请填写完整日程标题！",
    //"event_input_room_error": "请选择日程室！",
    //"event_input_person_error": "请选择邀请参会人员！",
    //"event_input_date_error": "请正确选择日程开始日期和时间！",
    //"event_input_time_error": "请正确选择日程开始时间和结束时间！",
    //"event_input_subject_error": "请填写完整日程标题！",

    "event_input_subject_error": "日程標題不能為空！",
    "event_input_time_error": "日程結束時間不能早於開始時間！",
    "event_saveSuccess": "日程保存成功！",
    "deleteAttachmentTitle": "刪除附件確認",
    "deleteAttachment": "是否確定要刪除您選中的附件？",
    "dateFormatMonth": "%Y年%m月",
    "dateFormatMonthDay": "%m月%d日",
    "dateFormatMonthDay2": "%m月%e日",
    "dateFormatMonthOnly": "%m月",
    "dateFormatDay": "%Y年%m月%d日",
    "dateFormatDayOnly": "%d日",
    "dateFormatAll": "%Y年%m月%d日 %H:%M",
    "dateFormat": "db",
    "person": "人",
    "personal": "個人",
    "persist": "持續",
    "date": "天",
    "hour": "小時",
    "minute": "分鐘",
    "second": "秒",
    "to": "至",
    "all": "全部",
    "remindInAdvance": "提前{text}提醒",
    "isAvaliable": "是否啟用",
    "manager": "管理者",
    "viewerRange": "可見範圍",
    "publisherRange": "可新建範圍",
    "noTask": "今天無日程安排",
    "noEvent": "當日無日程",
    "noAddress": "未填寫地址",
    "noEventCurMonth": "該月無日程安排",
    "weeklyViewTitle": "{month}，第{week}周",

    "week": "週",
    "weeks": {
        "Sun": "週日",
        "Mon": "週一",
        "Tues": "週二",
        "Wed": "週三",
        "Thur": "週四",
        "Fri": "週五",
        "Sat": "週六",
        "arr": ["週日", "週一", "週二", "週三", "週四", "週五", "週六"],
        "rruleArr": ["SU", "MO", "TU", "WE", "TH", "FR", "SA"]
    },
    "weeksShort": {
        "Sun": "日",
        "Mon": "一",
        "Tues": "二",
        "Wed": "三",
        "Thur": "四",
        "Fri": "五",
        "Sat": "六",
        "arr": ["日", "一", "二", "三", "四", "五", "六"],
        "rruleArr": ["SU", "MO", "TU", "WE", "TH", "FR", "SA"]
    },
    "config": {
        "navi": "導航",
        "autoHide": "自動隱藏",
        "default": "默認視圖",
        "applyProcess": "日程流程",
        "legend": "圖示",
        "eventStatus": "日程狀態",
        "wait": "已預約",
        "progress": "進行中",
        "completed": "已結束",
        "invite": "日程邀請",
        "weekBegin": "週開始日",
        "viewSetting": "啟用視圖",
        "viewCustomName": "視圖顯示名稱",
        "mobileCreateEnable": "移動端是否能新建日程",
        "mobileCreateEnableOptions": ["是", "否"]
    },
    "nextActivity": "下一個活動:",
    "nextUser": "處理人:",
    "deal": "處理",
    "processStarted": "文件已啟動",
    "processStartedMessage": "您啟動了一個新的工作：",
    "add": "新增",
    "more": "更多",
    "schedule": {
        "noEvent": "當天您沒有議程",
        "current": "當前您有",
        "someEvent": "項議程！"
    }
};