/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.bbs.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.bbs.entity.BBSVoteOptionBinary.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 02 16:17:30 CST 2016")
public class BBSVoteOptionBinary_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<BBSVoteOptionBinary,Date> createTime;
    public static volatile SingularAttribute<BBSVoteOptionBinary,String> id;
    public static volatile SingularAttribute<BBSVoteOptionBinary,String> optionBinary;
    public static volatile SingularAttribute<BBSVoteOptionBinary,String> sequence;
    public static volatile SingularAttribute<BBSVoteOptionBinary,Date> updateTime;
}
