MWF.xApplication.AppMarketV2.Application.LP = {
	"title": "App Market",
    "implodeLocal": "Import from local",
    "download": "Free download",
    "setup": "Install",
    "setupDone":"Installed",
    "update":"Update",
    "ok": "OK",
    "cancel": "Cancel",
    "setupSuccess": "Application is installed successfully!",
    "localApp": "Local Application",
    "appInfoTab":"Features",
    "appDemandTab":"Installation",
    "appCommentTab":"Comment",
    "commentTitle":"Comment",
    "commentsuccess":"Comment successful",
    "confirmsetupTitle":"Installation confirmation",
    "confirmsetupContent":"Are you sure to install this Application?",
    "confirmupdateTitle":"Update confirmation",
    "confirmupdateContent":"Are you sure to update this Application? If you change this app after installing the Application, it will be replaced after this update",
    "bbsname":"Community",
    "bbslink":"http://forum.o2oa.net/x_desktop/forum.html?app=ForumSection&id=b1895d5a-7ef2-4d74-b2d1-a7ae10daaa28",
    "bbstip":"If you have any questions or ideas, please come to our Community to communicate!",

    "commentCountText":"{n} Ratings",
    "category" : "Category",
    "screenshot":"Screenshot",
    "commented" : "You have reviewed this application!",
    "notInstall": "You have not installed this app, so you cannot rate and comment on it!",
    "iNeedComment": "Comment",
    "score": "Scoring:",
    "comment": "Comment:",
    "commentNotice" : "Please submit after comment"
};
