MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.AppMarketV2 = MWF.xApplication.AppMarketV2 || {};
MWF.xApplication.AppMarketV2.Application = MWF.xApplication.AppMarketV2.Application || {};
MWF.xApplication.AppMarketV2.Application.LP={
	"title": "Tienda de aplicaciones",
	"implodeLocal": "Importar desde local",
	"download": "Descarga gratuita",
	"setup": "Instalar",
	"setupDone": "Ya instalado",
	"update": "Actualizar",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"setupSuccess": "¡La aplicación se ha instalado con éxito!",
	"localApp": "Aplicación local",
	"appInfoTab": "Introducción de funciones",
	"appDemandTab": "Instalación y uso",
	"appCommentTab": "Calificación y comentarios",
	"commentTitle": "Calificación y comentarios",
	"commentsuccess": "Comentario enviado con éxito",
	"confirmsetupTitle": "Confirmación de instalación",
	"confirmsetupContent": "¿Está seguro de que desea instalar esta aplicación?",
	"confirmupdateTitle": "Confirmación de actualización",
	"confirmupdateContent": "¿Está seguro de que desea actualizar esta aplicación? Si ha modificado esta aplicación después de instalarla, se sobrescribirá con la actualización.",
	"bbsname": "Comunidad O2",
	"bbslink": "http://forum.o2oa.net/x_desktop/forum.html?app=ForumSection&id=b1895d5a-7ef2-4d74-b2d1-a7ae10daaa28",
	"bbstip": "Si tiene alguna pregunta o idea, ¡venga a nuestra comunidad de O2 para discutirlas!",
	"commentpath": "https://forum.o2oa.net:40020",
	"bbsurl": "http://forum.o2oa.net/x_desktop/forum.html?app=ForumSection&id=b1895d5a-7ef2-4d74-b2d1-a7ae10daaa28",
	"bbsNotice": "Haga clic en este enlace para comentar en el foro o2",
	"commentCountText": "{n} calificaciones en total",
	"category": "Categoría",
	"screenshot": "Captura de pantalla",
	"commented": "¡Ya ha enviado un comentario sobre esta aplicación!",
	"notInstall": "¡No puede calificar ni comentar esta aplicación porque aún no la ha instalado!",
	"iNeedComment": "Quiero calificar y comentar",
	"score": "Calificación:",
	"comment": "Comentario:",
	"commentNotice": "Por favor, califique y comente antes de enviar."
}
MWF.xApplication.AppMarketV2.Application["lp."+o2.language] = MWF.xApplication.AppMarketV2.Application.LP