MWF.xApplication.AppMarketV2.Application.LP = {
    "title": "App Market",
    "implodeLocal": "ນໍາເຂົ້າຈາກສະຖານທີ່",
    "download": "ດາວໂຫລດຟຣີ",
    "setup": "ຕິດຕັ້ງ",
    "setupDone":"ຕິດຕັ້ງແລ້ວ",
    "update":"ອັບເດດ",
    "ok": "ຢືນຢັນ",
    "cancel": "ຍົກເລີກ",
    "setupSuccess": "ຕິດຕັ້ງ Application ສຳເລັດ！",
    "localApp": "ພື້ນທີ່ Application",
    "appInfoTab":"ແນະນຳຄຸນລັກສະນະ",
    "appDemandTab":"ການຕິດຕັ້ງ",
    "appCommentTab":"Comment",
    "commentTitle":"Comment",
    "commentsuccess":"Comment ສຳເລັດ",
    "confirmsetupTitle":"ຢືນຢັນການຕັດຕັ້ງ",
    "confirmsetupContent":"ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການຕິດຕັ້ງ Applicationນີ້？",
    "confirmupdateTitle":"ຢືນຢັນອັບເດດ",
    "confirmupdateContent":"ເຈົ້າແນ່ໃຈວ່າຈະອັບເດດApplicationນີ້？ຖ້າເຈົ້າຕ້ອງການປ່ຽນ Applicationນີ້ ຫຼັງຈາກຕິດຕັ້ງApplicationນີ້ ，ຫຼັງຈາກອັບເດດແລ້ວຈະໄປແທນທີ່ບ່ອນນັ້ນ",
    "bbsname":"Community",
    "bbslink":"http://forum.o2oa.net/x_desktop/forum.html?app=ForumSection&id=b1895d5a-7ef2-4d74-b2d1-a7ae10daaa28",
    "bbstip":"ຖ້າເຈົ້າມີຄຳຖາມ ຫຼື ideas，ກະລຸນາມາທີ່Communityຂອງພວກເຮົາເພື່ອສື່ສານ！",
    "commentpath":"https://forum.o2oa.net:40020",
    "bbsurl":"http://forum.o2oa.net/x_desktop/forum.html?app=ForumSection&id=b1895d5a-7ef2-4d74-b2d1-a7ae10daaa28",
    "bbsNotice":"ຖ້າຕ້ອງການສະແດງຄວາມຄິດເຫັນສາມາດຄິກໄດ້ທີ່o2ຄວາມຄິດເຫັນ",

    "commentCountText":"ທັງໝົດ{n}Ratings",
    "category" : "ໝວດໝູ່",
    "screenshot":"ຖ່າຍຮູບໜ້າຈໍ",
    "commented" : "ເຈົ້າໄດ້ກວດສອບapplicationນີ້ແລ້ວ！",
    "notInstall": "ເຈົ້າບໍ່ມີການຕິດຕັ້ງScoring ，ເຈົ້າບໍ່ສາມາດສະແດງຄວາມຄິດເຫັນຢູ່ເທິ່ງນີ້ໄດ້！",
    "iNeedComment": "ຂ້ອຍຕ້ອງການ Comment",
    "score": "Scoring：",
    "comment": "Comment：",
    "commentNotice" : "ກະລຸນາສະແດງຄວາມຄິດເຫັນ, ຫຼັງຈາກສະແດງຄວາມຄິດເຫັນແລ້ວກະລຸນາສົ່ງ"
};