MWF.xApplication.AppMarketV2.Application.LP = {
	"title": "应用市场",
    "implodeLocal": "从本地导入",
    "download": "免费下载",
    "setup": "安装",
    "setupDone":"已安装",
    "update":"更新",
    "ok": "确定",
    "cancel": "取消",
    "setupSuccess": "应用安装成功！",
    "localApp": "本地应用",
    "appInfoTab":"功能介绍",
    "appDemandTab":"安装及使用",
    "appCommentTab":"评分及评论",
    "commentTitle":"评分及评论",
    "commentsuccess":"评论成功",
    "confirmsetupTitle":"安装提示",
    "confirmsetupContent":"您确认安装本应用么？",
    "confirmupdateTitle":"更新提示",
    "confirmupdateContent":"您确认更新本应用么？如果安装应用后改过本应用，本次更新后会被替换",
    "bbsname":"藕粉社区",
    "bbslink":"http://forum.o2oa.net/x_desktop/forum.html?app=ForumSection&id=b1895d5a-7ef2-4d74-b2d1-a7ae10daaa28",
    "bbstip":"如果您有什么疑问或想法，请来我们的藕粉社区交流吧！"
};