MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.ThreeMember = MWF.xApplication.ThreeMember || {};
MWF.xApplication.ThreeMember.LP={
	"title": "Three-Member Management",
	"person": "User",
	"node": "Node",
	"clientIp": "Client IP",
	"module": "Module",
	"operation": "operation",
	"httpType": "Type",
	"httpStatus": "Status",
	"httpUrl": "Request URL",
	"startTime": "Start",
	"endTime": "End",
	"createTime": "Start Time",
	"updateTime": "End Time",
	"requestTime": "Request Time",
	"spendTime": "Execution duration (milliseconds)",
	"spendTime1 ": " Execution duration",
	"millisecond ": "milliseconds",
	"firstPage": "First Page",
	"lastPage": "Last Page",
	"query": "Search",
	"reset": "Reset",
	"noItem": "No data is queried under the current conditions",
	"all": "All Logs",
	"sendData": "Request Data",
	"cancel": "Cancel",
	"close": "Close",
	"ok": "OK",
	"edit": "Edit",
	"remove": "Remove",
	"action": "Action",
	"view": "View",
	"viewDetail": "View Detail",
	"logDetail": "Log Detail",
	"yesterday": "Yesterday",
	"twoDaysAgo": "The day before yesterday",
	"weekAgo": "Week Ago",
	"dayAgo": "Day Ago",
	"hourAgo": "Hours ago",
	"minuteAgo": "minutes ago",
	"justNow": "JustNow",
	"publishJustNow": "Just published",
	"logConfig": "Log configuration",
	"viewLog": "Log",
	"status": "status",
	"enable": "enable",
	"disable": "disable",
	"configDetail": "Configuration details",
	"moduleSelect": "Select module",
	"actionSelect": "Select a category",
	"methodSelect": "Select service",
	"selectNote": "Note: Selecting modules, selecting categories and selecting services are only for the convenience of automatically filling in the type and request address, and do not save the data to the background.",
	"createSuccess": "Create successfully",
	"updateSuccess": "Save successfully",
	"allConfig": "All log configuration",
	"deleteConfig": "Delete log configuration",
	"deleteConfigText": "It cannot be restored after deletion. Are you sure you want to delete this log configuration?",
	"deleteConfigOK": "Configuration deleted successfully",
	"createConfig": "Create log configuration",
	"home": "Enter system",
	"syncLogSuccess": "Sync log success",
	"process": "Process Management",
	"cms": "Content Management",
	"portal": "Portal Management",
	"query1": "Datacenter",
	"set": "Set",
	"syncLog": "Sync log immediately",
	"save": "Save",
	"saveSuccess": "Save successfully",
	"saveFailure": "Save failed",
	"noPermissionText": "Sorry, the three-person management is not enabled or you do not have permission to view this app.",
	"search": "Search application",
	"viewer": "Use range",
	"publisher": "Publisher",
	"manager": "Manager",
	"starter": "Starter",
	"executor": "Executable",
	"dataViewer": "View Data Range",
	"dataEditor": "Edit data range",
	"yes": "Yes",
	"no": "No",
	"anonymousAccessible": "Allow anonymous execution",
	"log": "View log",
	"permission1": "App Permission",
	"org": "Organization Management",
	"password": "Password Management",
	"logout": "Logout",
	"welcome": "Hello,",
	"noServiceNote": "The three-person management background service is not installed in the system, please contact the administrator to install it in the application market.",
	"noDataText": {
		"process": "There is no process in this application",
		"category": "There is no category in this app",
		"view": "There is no view in this application",
		"stat": "There are no statistics for this app",
		"table": "There is no data table in this application",
		"statement": "There is no query configuration under this application",
		"importer": "There is no import configuration under this application"
	},
	"permission": {
		"application": "Application permissions",
		"process": "Process permissions",
		"column": "Column permissions",
		"category": "Category Authority",
		"portal": "Portal Permissions",
		"query": "Data Center Permissions",
		"view": "View permission",
		"stat": "Statistical Authority",
		"table": "Data table permissions",
		"statement": "Query permission",
		"importer": "Import permission"
	},
	"passwordConfig": {
		"title": "Basic information about the personnel account of the configuration system",
		"password": "Default password for new users",
		"passwordNote": "When creating a new user, use the following password, the user can modify it after logging in to the system",
		"passwordPeriod": "Password expiration time (days)",
		"passwordPeriodNote": "Users who have not changed their passwords for more than this set number of days will be forced to change their passwords after logging in, otherwise they will not be able to enter the system",
		"adminPassword": "Super administrator password",
		"adminPasswordNote": "The password of the super administrator xadmin, because there are many places related to this password, please restart the server immediately after modification",
		"passwordRegex": "Password Check Regular Expression",
		"passwordRegexNote": "Check regular expression when changing password",
		"passwordRegexHint": "Password check hint text",
		"passwordRegexHintNote": "Prompt text when the verification fails when changing the password",
		"failureCount": "Number of wrong passwords",
		"failureCountNote": "The maximum number of incorrect passwords allowed to be entered when logging in",
		"failureInterval": "Login limit time (minutes)",
		"failureIntervalNote": "After reaching the maximum number of incorrect passwords, limit the login time",
		"systemManagerPassword": "System Manager Password",
		"systemManagerPasswordNote": "systemManager Password",
		"securityManagerPassword": "Security Manager Password",
		"securityManagerPasswordNote": "securityManager Password",
		"auditManagerPassword": "Security Auditor Password",
		"auditManagerPasswordNote": "auditManager Password"
	},
	"spendTime1": "Execution duration",
	"millisecond": "millisecond",
	"delete": "delete",
	"lptest": "This is a language pack test"
}
MWF.xApplication.ThreeMember["lp."+o2.language] = MWF.xApplication.ThreeMember.LP