MWF.xApplication.ThreeMember.LP = {
	"title": "三元管理",

    "person": "ユーザー",
    "node": "ノード",
    "clientIp": "クライアントIP",
    "module": "モジュール",
    "operation": "操作",
    "httpType": "タイプ",
    "httpStatus": "ステータス",
    "httpUrl": "リクエストアドレス",
    "startTime": "開始",
    "endTime": "終了",
    "createTime": "開始時間",
    "updateTime": "終了時間",
    "requestTime": "リクエスト時間",
    "spendTime": "実行継続時間(ミリ秒)",
    "spendTime1": "実行継続時間",
    "millisecond": "ミリ秒",
    "firstPage": "最初のページ",
    "lastPage": "最後のページ",
    "query": "検索",
    "reset": "リセット",
    "noItem": "現在の条件ではデータが見つかりません",
    "all": "すべてのログ",
    "sendData": "リクエストデータ",

	"cancel": "キャンセル",
    "close": "閉じる",
    "ok": "確認",
    "edit": "編集",
    "remove": "削除",
    "action": "操作",
    "view": "表示",
    "viewDetail": "詳細を表示",
    "logDetail": "ログの詳細",

    "yesterday": "昨日",
    "twoDaysAgo": "一昨日",
    "weekAgo": "1週間前",
    "dayAgo": "日前",
    "hourAgo": "時間前",
    "minuteAgo": "分前",
    "justNow": "たった今",
    "publishJustNow": "たった今発表",

	"home": "システムに入る",
    "syncLogSuccess": "ログ同期成功",
    "process": "プロセス管理",
    "cms": "コンテンツ管理",
    "portal": "ポータル管理",
    "query1": "データセンター",
    "set": "設定",
    "syncLog": "即時ログ同期",
    "save": "保存",
    "saveSuccess": "保存成功",
    "saveFailure": "保存失敗",
    "noPermissionText": "申し訳ありません、三員管理が有効になっていないか、アプリを表示する権限がありません。",
    "search": "アプリを検索",
    "viewer": "使用範囲",
    "publisher": "発行者",
    "manager": "マネージャー",
    "starter": "スターター",
    "executor": "実行者",
    "dataViewer": "データ範囲を表示",
    "dataEditor": "データ範囲を編集",
    "yes": "はい",
    "no": "いいえ",
    "anonymousAccessible": "匿名アクセスを許可",
    "log": "ログを表示",
    "permission1": "アプリの権限",
    "org": "組織管理",
    "password": "パスワード管理",
    "logout": "ログアウト",
    "welcome": "こんにちは、",
	"noServiceNote": "システムには三員管理バックエンドサービスがインストールされていません。管理者にアプリストアからインストールを依頼してください。",
    "noDataText": {
        "process": "このアプリにはプロセスがありません。",
        "category": "このアプリにはカテゴリがありません。",
        "view": "このアプリにはビューがありません。",
        "stat": "このアプリには統計がありません。",
        "table": "このアプリにはデータテーブルがありません。",
        "statement": "このアプリにはクエリ設定がありません。",
        "importer": "このアプリにはインポート設定がありません。"
    },
    "permission": {
        "application": "アプリの権限",
        "process": "プロセスの権限",
        "column": "列の権限",
        "category": "カテゴリの権限",
        "portal": "ポータルの権限",
        "query": "データセンターの権限",
        "view": "ビューの権限",
        "stat": "統計の権限",
        "table": "データテーブルの権限",
        "statement": "クエリの権限",
        "importer": "インポータの権限"
    },

	"passwordConfig": {
        "title": "人員アカウントの基本情報を設定",
        "password": "新しいユーザーのデフォルトのパスワード",
        "passwordNote": "新しいユーザーを作成する際に使用されるパスワードで、ユーザーはログイン後に自分でパスワードを変更できます。",
        "passwordPeriod": "パスワードの有効期間（日）",
        "passwordPeriodNote": "この期間を超えてパスワードを変更しないユーザーは、ログイン後にパスワードを変更するように強制されます。そうしないとシステムにアクセスできません。",
        "adminPassword": "スーパー管理者のパスワード",
        "adminPasswordNote": "スーパー管理者xadminのパスワードです。このパスワードに関連する場所が多いため、変更したらすぐにサーバーを再起動してください。",
        "passwordRegex": "パスワードの正規表現チェック",
        "passwordRegexNote": "パスワードを変更する際の正規表現チェックです。",
        "passwordRegexHint": "パスワードの正規表現ヒント",
        "passwordRegexHintNote": "パスワードを変更する際の正規表現チェックに合格しない場合に表示されるヒントテキストです。",
        "failureCount": "間違ったパスワードの入力回数",
        "failureCountNote": "ログイン時に許容される間違ったパスワードの入力回数の上限です。",
        "failureInterval": "ログイン制限時間（分）",
        "failureIntervalNote": "間違ったパスワードの入力回数の上限に達した後、ログインが制限される時間です。",
        "systemManagerPassword": "システム管理者のパスワード",
        "systemManagerPasswordNote": "システム管理者のパスワードです。",
        "securityManagerPassword": "セキュリティ管理者のパスワード",
        "securityManagerPasswordNote": "セキュリティ管理者のパスワードです。",
        "auditManagerPassword": "セキュリティ監査担当者のパスワード",
        "auditManagerPasswordNote": "セキュリティ監査担当者のパスワードです。"
    }


};