MWF.xApplication.ThreeMember.LP = {
	"title": "삼원 관리",

    "person": "사용자",
    "node": "노드",
    "clientIp": "클라이언트 IP",
    "module": "모듈",
    "operation": "작업",
    "httpType": "유형",
    "httpStatus": "상태",
    "httpUrl": "요청 주소",
    "startTime": "시작",
    "endTime": "종료",
    "createTime": "시작 시간",
    "updateTime": "종료 시간",
    "requestTime": "요청 시간",
    "spendTime": "실행 지속 시간(밀리초)",
    "spendTime1": "실행 지속 시간",
    "millisecond": "밀리초",
    "firstPage": "첫 페이지",
    "lastPage": "마지막 페이지",
    "query": "검색",
    "reset": "재설정",
    "noItem": "현재 조건에서 데이터를 찾을 수 없습니다",
    "all": "모든 로그",
    "sendData": "요청 데이터",

	"cancel": "취소",
    "close": "닫기",
    "ok": "확인",
    "edit": "편집",
    "remove": "삭제",
    "action": "동작",
    "view": "보기",
    "viewDetail": "상세 정보 보기",
    "logDetail": "로그 상세 정보",

    "yesterday": "어제",
    "twoDaysAgo": "그제",
    "weekAgo": "1주일 전",
    "dayAgo": "일 전",
    "hourAgo": "시간 전",
    "minuteAgo": "분 전",
    "justNow": "방금",
    "publishJustNow": "방금 게시됨",

	"home": "시스템으로 이동",
    "syncLogSuccess": "로그 동기화 성공",
    "process": "프로세스 관리",
    "cms": "콘텐츠 관리",
    "portal": "포털 관리",
    "query1": "데이터 센터",
    "set": "설정",
    "syncLog": "즉시 로그 동기화",
    "save": "저장",
    "saveSuccess": "저장 성공",
    "saveFailure": "저장 실패",
    "noPermissionText": "죄송합니다, 삼원 관리가 활성화되지 않았거나 권한이 없습니다.",
    "search": "앱 검색",
    "viewer": "사용 권한 보유자",
    "publisher": "게시자",
    "manager": "매니저",
    "starter": "시작자",
    "executor": "실행자",
    "dataViewer": "데이터 범위 확인",
    "dataEditor": "데이터 범위 편집",
    "yes": "예",
    "no": "아니요",
    "anonymousAccessible": "익명 액세스 허용",
    "log": "로그 보기",
    "permission1": "앱 권한",
    "org": "조직 관리",
    "password": "비밀번호 관리",
    "logout": "로그아웃",
    "welcome": "안녕하세요,",
	"noServiceNote": "시스템에 삼원 관리 백엔드 서비스가 설치되지 않았습니다. 관리자에게 앱 스토어에서 설치하도록 요청하십시오.",
    "noDataText": {
        "process": "이 앱에는 프로세스가 없습니다.",
        "category": "이 앱에는 카테고리가 없습니다.",
        "view": "이 앱에는 뷰가 없습니다.",
        "stat": "이 앱에는 통계가 없습니다.",
        "table": "이 앱에는 데이터 테이블이 없습니다.",
        "statement": "이 앱에는 쿼리 설정이 없습니다.",
        "importer": "이 앱에는 가져오기 설정이 없습니다."
    },
    "permission": {
        "application": "앱 권한",
        "process": "프로세스 권한",
        "column": "열 권한",
        "category": "카테고리 권한",
        "portal": "포털 권한",
        "query": "데이터 센터 권한",
        "view": "뷰 권한",
        "stat": "통계 권한",
        "table": "데이터 테이블 권한",
        "statement": "쿼리 권한",
        "importer": "가져오기 권한"
    },

	"passwordConfig": {
        "title": "시스템 계정 기본 정보 설정",
        "password": "새로운 사용자의 기본 암호",
        "passwordNote": "새로운 사용자를 생성할 때 사용하는 암호입니다. 사용자는 로그인 후 암호를 변경할 수 있습니다.",
        "passwordPeriod": "암호 만료 기간 (일)",
        "passwordPeriodNote": "암호를 변경하지 않은 사용자는 이 기간 이후에 로그인시 암호를 변경해야 합니다. 그렇지 않으면 시스템에 접근할 수 없습니다.",
        "adminPassword": "슈퍼 관리자 암호",
        "adminPasswordNote": "슈퍼 관리자 xadmin의 암호입니다. 이 암호와 관련된 모든 곳에서 즉시 변경한 후 서버를 다시 시작하십시오.",
        "passwordRegex": "암호 유효성 검사 정규식",
        "passwordRegexNote": "암호 변경 시 유효성을 검사하는 정규식입니다.",
        "passwordRegexHint": "암호 유효성 검사 힌트",
        "passwordRegexHintNote": "암호 변경 시 유효성 검사를 통과하지 못한 경우 표시되는 힌트 텍스트입니다.",
        "failureCount": "잘못된 암호 입력 횟수",
        "failureCountNote": "로그인 시 허용되는 잘못된 암호 입력 횟수 상한선입니다.",
        "failureInterval": "로그인 제한 시간 (분)",
        "failureIntervalNote": "잘못된 암호 입력 횟수 상한선에 도달한 후 로그인이 제한되는 시간입니다.",
        "systemManagerPassword": "시스템 관리자 암호",
        "systemManagerPasswordNote": "시스템 관리자의 암호입니다.",
        "securityManagerPassword": "보안 관리자 암호",
        "securityManagerPasswordNote": "보안 관리자의 암호입니다.",
        "auditManagerPassword": "보안 감사자 암호",
        "auditManagerPasswordNote": "보안 감사자의 암호입니다."
    }


};