MWF.xApplication.ThreeMember.LP = {
	"title": "三员管理",

	"person" : "用户",
	"node": "节点",
	"clientIp": "客户端IP",
	"module": "模块",
	"operation": "操作",
	"httpType": "类型",
	"httpStatus": "状态",
	"httpUrl": "请求地址",
	"startTime": "开始",
	"endTime": "结束",
	"createTime": "开始时间",
	"updateTime": "结束时间",
	"requestTime": "请求时间",
	"spendTime": "执行持续时间(毫秒)",
	"spendTime1": "执行持续时间",
	"millisecond": "毫秒",
	"firstPage": "第一页",
	"lastPage": "最后一页",
	"query": "搜索",
	"reset": "重置",
	"noItem": "当前条件下没有查询到数据",
	"all": "所有日志",
	"sendData": "请求数据",

	"cancel" : "取消",
	"close" : "关闭",
	"ok" : "确定",
	"edit" : "编辑",
	"remove" : "删除",
	"action" : "操作",
	"view": "查看",
	"viewDetail": "查看详情",
	"logDetail": "日志详情",

	"yesterday": "昨天",
	"twoDaysAgo" : "前天",
	"weekAgo" : "周前",
	"dayAgo" : "天前",
	"hourAgo" : "小时前",
	"minuteAgo" : "分钟前",
	"justNow" : "刚才",
	"publishJustNow": "刚刚发表",

	"logConfig": "配置日志",
	"viewLog": "返回",
	"status": "状态",
	"enable": "启用",
	"disable": "禁用",
	"configDetail": "配置详情",
	"moduleSelect": "选择模块",
	"actionSelect": "选择分类",
	"methodSelect": "选择服务",
	"selectNote": "注：选择模块、选择分类和选择服务只为了方便自动填写类型和请求地址，不保存数据到后台。",
	"createSuccess": "创建成功",
	"updateSuccess": "保存成功",
	"allConfig": "所有日志配置",
	"deleteConfig": "删除日志配置",
	"deleteConfigText": "删除后不能恢复，确定要删除该日志配置？",
	"deleteConfigOK": "成功删除配置",
	"createConfig": "创建日志配置",

	"delete": "删除",

	"home": "进入系统",
	"syncLogSuccess": "同步日志成功",
	"process": "流程管理",
	"cms": "内容管理",
	"portal": "门户管理",
	"query1": "数据中心",
	"set": "设置",
	"syncLog": "立即同步日志",
	"save": "保存",
	"saveSuccess": "保存成功",
	"saveFailure": "保存失败",
	"noPermissionText": "抱歉，三员管理未开启或您没有权限查看本应用。",
	"search": "搜索应用",
	"viewer": "使用范围",
	"publisher": "发布者",
	"manager": "管理者",
	"starter": "启动者",
	"executor": "可执行者",
	"dataViewer": "查看数据范围",
	"dataEditor": "编辑数据范围",
	"yes": "是",
	"no": "否",
	"anonymousAccessible": "允许匿名执行",
	"log": "查看日志",
	"permission1": "应用权限",
	"org": "组织管理",
	"password": "密码管理",
	"logout": "注销",
	"welcome": "您好，",
	"noServiceNote": "系统未安装三员管理后台服务，请联系管理员到应用市场安装。",
	"noDataText" : {
		"process": "该应用下无流程",
		"category": "该应用下无分类",
		"view": "该应用下无视图",
		"stat": "该应用下无统计",
		"table": "该应用下无数据表",
		"statement": "该应用下无查询配置",
		"importer": "该应用下无导入配置",
	},

	"permission" : {
		"application": "应用权限",
		"process": "流程权限",
		"column": "栏目权限",
		"category": "分类权限",
		"portal": "门户权限",
		"query": "数据中心权限",
		"view": "视图权限",
		"stat": "统计权限",
		"table": "数据表权限",
		"statement": "查询权限",
		"importer": "导入权限"
	},

	"passwordConfig":{
		"title": "配置系统的人员账户基本信息",
		"password": "新建用户的默认密码",
		"passwordNote": "创建新建用户时，使用以下密码，用户可登录系统后自行修改",
		"passwordPeriod": "密码过期时间（天）",
		"passwordPeriodNote": "超过此设定天数未修改密码的用户，登录后会强制要求修改密码，否则无法进入系统",
		"adminPassword": "超级管理员密码",
		"adminPasswordNote": "超级管理员xadmin的密码，由于该密码相关的地方比较多，修改以后请马上重启服务器",
		"passwordRegex": "密码校验正则表达式",
		"passwordRegexNote": "修改密码时的校验正则表达式",
		"passwordRegexHint": "密码校验提示文本",
		"passwordRegexHintNote": "修改密码时的校验不通过的提示文本",
		"failureCount": "错误密码次数",
		"failureCountNote": "登录时允许输入的错误密码次数上限",
		"failureInterval": "登录限制时间(分钟)",
		"failureIntervalNote": "达到错误密码次数上限后，限制登录的时间",
		"systemManagerPassword": "系统管理员密码",
		"systemManagerPasswordNote": "systemManager密码",
		"securityManagerPassword": "安全管理员密码",
		"securityManagerPasswordNote": "securityManager密码",
		"auditManagerPassword": "安全审计员密码",
		"auditManagerPasswordNote": "auditManager密码"
	},
	"lptest": "这是语言包测试"
};
