MWF.xApplication.ThreeMember.LP = {
	"title": "三员管理",

	"person" : "用户",
	"node": "节点",
	"clientIp": "客户端IP",
	"module": "模块",
	"operation": "操作",
	"httpType": "类型",
	"httpStatus": "状态",
	"httpUrl": "请求地址",
	"startTime": "开始",
	"endTime": "结束",
	"createTime": "开始时间",
	"updateTime": "结束时间",
	"requestTime": "请求时间",
	"spendTime": "执行持续时间(毫秒)",
	"spendTime1": "执行持续时间",
	"millisecond": "毫秒",
	"firstPage": "第一页",
	"lastPage": "最后一页",
	"query": "搜索",
	"reset": "重置",
	"noItem": "当前条件下没有查询到数据",
	"all": "所有日志",
	"sendData": "请求数据",

	"cancel" : "取消",
	"close" : "关闭",
	"ok" : "确定",
	"edit" : "编辑",
	"remove" : "删除",
	"action" : "操作",
	"view": "查看",
	"viewDetail": "查看详情",
	"logDetail": "日志详情",

	"yesterday": "昨天",
	"twoDaysAgo" : "前天",
	"weekAgo" : "周前",
	"dayAgo" : "天前",
	"hourAgo" : "小时前",
	"minuteAgo" : "分钟前",
	"justNow" : "刚才",
	"publishJustNow": "刚刚发表",

	"process": "流程管理",
	"cms": "内容管理",
	"portal": "门户管理",
	"query1": "数据中心",
	"set": "设置",
	"syncLog": "立即同步日志",

	"viewer": "使用范围",
	"publisher": "发布者",
	"manager": "管理者",
	"noDataText" : {
		"process": "该应用下无流程",
		"category": "该应用下无分类",
		"view": "该应用下无视图",
		"stat": "该应用下无统计",
		"table": "该应用下无数据表",
		"statement": "该应用下无查询配置",
		"importer": "该应用下无导入配置",
	},

	"permission" : {
		"application": "应用权限",
		"process": "流程权限",
		"column": "栏目权限",
		"category": "分类权限",
		"portal": "门户权限",
		"query": "数据中心权限",
		"view": "视图权限",
		"stat": "统计权限",
		"table": "数据表权限",
		"statement": "查询权限",
		"importer": "导入权限"
	}


};