MWF.xApplication.ThreeMember.LP = {
	"title": "三員管理",

    "person": "用戶",
    "node": "節點",
    "clientIp": "客戶端IP",
    "module": "模塊",
    "operation": "操作",
    "httpType": "類型",
    "httpStatus": "狀態",
    "httpUrl": "請求地址",
    "startTime": "開始",
    "endTime": "結束",
    "createTime": "開始時間",
    "updateTime": "結束時間",
    "requestTime": "請求時間",
    "spendTime": "執行持續時間(毫秒)",
    "spendTime1": "執行持續時間",
    "millisecond": "毫秒",
    "firstPage": "第一頁",
    "lastPage": "最後一頁",
    "query": "搜索",
    "reset": "重置",
    "noItem": "當前條件下沒有查詢到數據",
    "all": "所有日誌",
    "sendData": "請求數據",

	"cancel": "取消",
    "close": "關閉",
    "ok": "確定",
    "edit": "編輯",
    "remove": "刪除",
    "action": "操作",
    "view": "查看",
    "viewDetail": "查看詳情",
    "logDetail": "日誌詳情",

    "yesterday": "昨天",
    "twoDaysAgo": "前天",
    "weekAgo": "一週前",
    "dayAgo": "天前",
    "hourAgo": "小時前",
    "minuteAgo": "分鐘前",
    "justNow": "剛才",
    "publishJustNow": "剛剛發表",

	"home": "進入系統",
    "syncLogSuccess": "同步日誌成功",
    "process": "流程管理",
    "cms": "內容管理",
    "portal": "門戶管理",
    "query1": "數據中心",
    "set": "設置",
    "syncLog": "立即同步日誌",
    "save": "保存",
    "saveSuccess": "保存成功",
    "saveFailure": "保存失敗",
    "noPermissionText": "抱歉，三員管理未開啟或您沒有權限查看本應用。",
    "search": "搜索應用",
    "viewer": "使用範圍",
    "publisher": "發布者",
    "manager": "管理者",
    "starter": "啟動者",
    "executor": "可執行者",
    "dataViewer": "查看數據範圍",
    "dataEditor": "編輯數據範圍",
    "yes": "是",
    "no": "否",
    "anonymousAccessible": "允許匿名執行",
    "log": "查看日誌",
    "permission1": "應用權限",
    "org": "組織管理",
    "password": "密碼管理",
    "logout": "登出",
    "welcome": "您好，",
	"noServiceNote": "系統未安裝三員管理後台服務，請聯絡管理員到應用市場安裝。",
    "noDataText": {
        "process": "該應用下無流程",
        "category": "該應用下無分類",
        "view": "該應用下無視圖",
        "stat": "該應用下無統計",
        "table": "該應用下無數據表",
        "statement": "該應用下無查詢配置",
        "importer": "該應用下無導入配置"
    },
    "permission": {
        "application": "應用權限",
        "process": "流程權限",
        "column": "欄目權限",
        "category": "分類權限",
        "portal": "門戶權限",
        "query": "數據中心權限",
        "view": "視圖權限",
        "stat": "統計權限",
        "table": "數據表權限",
        "statement": "查詢權限",
        "importer": "導入權限"
    },

	"passwordConfig": {
        "title": "配置系统的人员账户基本信息",
        "password": "新建用户的默认密码",
        "passwordNote": "创建新建用户时，使用以下密码，用户可登录系统后自行修改",
        "passwordPeriod": "密码过期时间（天）",
        "passwordPeriodNote": "超过此设定天数未修改密码的用户，登录后会强制要求修改密码，否则无法进入系统",
        "adminPassword": "超级管理员密码",
        "adminPasswordNote": "超级管理员xadmin的密码，由于该密码相关的地方比较多，修改以后请马上重启服务器",
        "passwordRegex": "密码校验正则表达式",
        "passwordRegexNote": "修改密码时的校验正则表达式",
        "passwordRegexHint": "密码校验提示文本",
        "passwordRegexHintNote": "修改密码时的校验不通过的提示文本",
        "failureCount": "错误密码次数",
        "failureCountNote": "登录时允许输入的错误密码次数上限",
        "failureInterval": "登录限制时间(分钟)",
        "failureIntervalNote": "达到错误密码次数上限后，限制登录的时间",
        "systemManagerPassword": "系统管理员密码",
        "systemManagerPasswordNote": "systemManager密码",
        "securityManagerPassword": "安全管理员密码",
        "securityManagerPasswordNote": "securityManager密码",
        "auditManagerPassword": "安全审计员密码",
        "auditManagerPasswordNote": "auditManager密码"
    }


};