MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.query = MWF.xApplication.query || {};
MWF.xApplication.query.QueryExplorer = MWF.xApplication.query.QueryExplorer || {};
MWF.xApplication.query.QueryExplorer.LP={
	"title": "Centro de datos",
	"all": "Todo",
	"create": "Crear",
	"import": "Importar",
	"find": "Buscar",
	"noApplicationCreate": "El sistema no tiene ninguna aplicación de datos o no tiene permiso para administrar aplicaciones de datos. <br/> Haga clic aquí para crear una nueva aplicación de datos.",
	"noApplication": "El sistema no tiene ninguna aplicación de datos o no tiene permiso para administrar aplicaciones de datos.",
	"unDescription": "No hay descripción disponible",
	"view": "Vista",
	"stat": "Estadística",
	"noView": "Esta aplicación aún no tiene ninguna vista. Haga clic aquí para crear una nueva vista.",
	"noStat": "Esta aplicación aún no tiene ninguna estadística. Haga clic aquí para crear una nueva estadística.",
	"unCategory": "Aplicación sin categoría",
	"name": "Nombre",
	"alias": "Alias",
	"description": "Descripción",
	"type": "Tipo",
	"icon": "Icono",
	"action_ok": "Aceptar",
	"action_cancel": "Cancelar",
	"createApplication_cancel_title": "Confirmación",
	"createApplication_cancel": "¿Está seguro de que desea cancelar la creación de la aplicación de datos?",
	"createApplicationSuccess": "¡La aplicación de datos se ha creado correctamente!",
	"searchAppPlacholder": "Ingrese el nombre",
	"searchAppTitle": "Coincide con el nombre, alias e id de la aplicación",
	"application": {
		"export": "Exportar",
		"export_ok": "Aceptar",
		"export_cancel": "Cancelar",
		"view": "Vista",
		"stat": "Estadística",
		"page": "Página",
		"process": "Proceso",
		"form": "Formulario",
		"dictionary": "Datos",
		"script": "Script",
		"import": "Importar",
		"import_confirm_title": "Confirmación",
		"import_confirm": "La aplicación de datos que se va a importar ya existe ¿Desea sobrescribir? \nHaga clic en 'Aceptar' para sobrescribir la aplicación de datos existente, esta operación no se puede deshacer.",
		"createApplication_cancel_title": "Confirmación",
		"createApplication_cancel": "¿Está seguro de que desea cancelar la creación de la aplicación de datos?",
		"inputApplicationName": "¡Ingrese un nombre!",
		"createApplicationSuccess": "¡La aplicación de datos se ha creado correctamente!",
		"deleteElements": "Eliminar las aplicaciones de datos seleccionadas",
		"deleteElementsTitle": "Confirmación",
		"deleteElementsConfirm": "¿Está seguro de que desea eliminar las aplicaciones de datos seleccionadas? <br><font style='color: red'>Esta acción eliminará todos los elementos de diseño de las aplicaciones de datos seleccionadas, incluyendo vistas, estadísticas, tablas de datos, etc., y no se puede deshacer.<br></font>",
		"deleteApplicationAllConfirm": "También elimine todas las instancias de proceso completadas",
		"deleteElementsConfirmAgain": "<font style='color: #00F; font-size:14px'>Confirme nuevamente que desea eliminar las siguientes aplicaciones de datos:</font>",
		"deleteElementsAllConfirmAgain": "<font style='color: #00F; font-size:14px'>Confirme nuevamente que desea eliminar todas las aplicaciones de datos seleccionadas:</font>",
		"select": "Invertir selección"
	}
}
MWF.xApplication.query.QueryExplorer["lp."+o2.language] = MWF.xApplication.query.QueryExplorer.LP