/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.neural.mlp;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.neural.mlp.InText.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Dec 23 11:58:45 CST 2018")
public class InText_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<InText,Integer> count;
    public static volatile SingularAttribute<InText,String> id;
    public static volatile SingularAttribute<InText,String> project;
    public static volatile SingularAttribute<InText,Integer> serial;
    public static volatile SingularAttribute<InText,String> text;
}
