/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.neural.mlp;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.neural.mlp.InValue.class)
@javax.annotation.Generated
<<<<<<< HEAD:o2server/x_query_core_entity/src/main/java/com/x/query/core/entity/neural/InValue_.java
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Thu Dec 27 11:39:59 CST 2018")
=======
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Dec 23 11:58:45 CST 2018")
>>>>>>> parent of 56d40c07... 更新hanlp1.7.1:o2server/x_query_core_entity/src/main/java/com/x/query/core/entity/neural/mlp/InValue_.java
public class InValue_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<InValue,Integer> count;
    public static volatile SingularAttribute<InValue,String> id;
    public static volatile SingularAttribute<InValue,Integer> inTextSerial;
    public static volatile SingularAttribute<InValue,String> project;
    public static volatile SingularAttribute<InValue,Integer> serial;
    public static volatile SingularAttribute<InValue,String> text;
}
