/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.neural.mlp;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.neural.mlp.OutValue.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon Dec 24 19:04:03 CST 2018")
public class OutValue_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<OutValue,Integer> count;
    public static volatile SingularAttribute<OutValue,String> id;
    public static volatile SingularAttribute<OutValue,String> project;
    public static volatile SingularAttribute<OutValue,Integer> serial;
    public static volatile SingularAttribute<OutValue,String> text;
}
