/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.hotpic.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.hotpic.entity.HotPictureInfo.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:40 CST 2018")
public class HotPictureInfo_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<HotPictureInfo,String> application;
    public static volatile SingularAttribute<HotPictureInfo,String> creator;
    public static volatile SingularAttribute<HotPictureInfo,String> id;
    public static volatile SingularAttribute<HotPictureInfo,String> infoId;
    public static volatile SingularAttribute<HotPictureInfo,String> picId;
    public static volatile SingularAttribute<HotPictureInfo,String> title;
    public static volatile SingularAttribute<HotPictureInfo,String> url;
}
