MWF.xApplication.Attendance.LP = {
	"title": "ການຄຸ້ມຄອງການເຂົ້າຮຽນ",
	"delete": "ລົບ",
	"deleteDocumentTitle": "ລຶບການຢືນຢັນ",
	"deleteDocument": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການລຶບຂໍ້ມູນນີ້ອອກ?",
	"deleteDocumentOK": "ລຶບສຳເລັດ",
	"createSuccess": "ສ້າງສຳເລັດແລ້ວ",
	"updateSuccess": "ອັບເດດສຳເລັດ",
	"inputName": "ກະລຸນາໃສ່ຊື່",

	"dateFormatMonth": "%Y-%m",
	"dateFormatOnlyMonth": "%m",
	"dateFormatDay": "%%Y-%m-%d",
	"dateFormatMonthDayLocal": "%m-%d",
	"dateFormat": "db",

	"month": "ເດືອນ",
	"today": "ມື້ນີ້",
	"day": "ມື້",

	"cancel": "ຍົກເລີກ",
	"ok": "ຕົກລົງ",

	"create_cancel_title": "ຍົກເລີກການຢືນຢັນໃໝ່",
	"create_cancel": "ທ່ານແນ່ໃຈບໍ່ວ່າຕ້ອງການຍົກເລີກການສ້າງໃໝ່?",

	"normal": "ການເຂົ້າຮ່ວມ", // ສີຂຽວ, ປົກກະຕິ
	"levelAsked": "ຂໍອອກ", // ສີຟ້າ, ຂໍໃຫ້ອອກ
	"late": "late", // ສີສົ້ມ, ຊ້າ
	"lateSelectText": ["","late","ບໍ່ຊ້າ"],
	"leaveEarly": "ອອກກ່ອນ", // ສີສົ້ມ, ອອກໄວ
	"noSign":"ບໍ່ມີ", // ສີບົວ, ບໍ່ໄດ້ເຂົ້າສູ່ລະບົບ
	"appealSuccess": "ການອຸທອນຜ່ານ",
	"lackOfTime": "ຂາດເວລາ",
	"abNormalDuty": "ເຊັກອິນຜິດປົກກະຕິ",
	"truefalseSelectText": ["","ແມ່ນ","ບໍ່"],
	"query": "ສອບຖາມ",
	"wholeDay": "ວັນທີ່ຖືໄວ້",
	"am": "ໂມງເຊົ້າ.",
	"pm": "ໂມງແລງ",

	"statusText": {
		"normal": "ການເຂົ້າຮ່ວມ", // ສີຂຽວ, ປົກກະຕິ
		"levelAsked": "ຂໍອອກ", // ສີຟ້າ, ຂໍໃຫ້ອອກ
		"late": "late", // ສີສົ້ມ, ຊ້າ
		"leaveEarly": "ອອກກ່ອນ", // ສີສົ້ມ, ອອກໄວ
		"noSign":"ບໍ່ມີ", // ສີບົວ, ບໍ່ໄດ້ເຂົ້າສູ່ລະບົບ
		"appealSuccess": "ອຸທອນ",
		"lackOfTime": "ຂາດເວລາ",
		"abNormalDuty": "ຂໍ້ຍົກເວັ້ນ",


		"lateTimes": "ຊ້າ",
		"leaveEarlyTimes": "ອອກກ່ອນໄວ",
		"lackOfTimeCount": "ບໍ່ພຽງພໍ",
		"abNormalDutyCount": "ຂໍ້ຍົກເວັ້ນ",
		"resultNormal": "ປົກກະຕິ",
		"seriousLateTimes": "ຊ້າຢ່າງເຂັ້ມງວດ",
		"outsideDutyTimes": "ນອກປ້າຍ",
		"absenteeismTimes": "ຂາດຕົວ",
		"notSignedCount": "ຂາດບັດ",
	},

	"absent": "ບໍ່ຢູ່",
	"notAbsent": "ບໍ່ຢູ່",
	"absendSelectText": ["","ແມ່ນ","ບໍ່"],

	"attendanceStatisic": "ສະຖິຕິການເຂົ້າຮ່ວມ",
	"name": "ຊື່",
	"onDutyTimes": "ເວລາເຂົ້າ",
	"offDutyTimes": "ຈໍານວນການຈ່າຍເງິນ",
	"onDutyDayCount": "ຈໍານວນມື້ເຂົ້າຮ່ວມ",
	"onSelfHolidayCount": "ຈໍານວນມື້ຂໍອອກເດີນທາງ",
	"absenceDayCount": "ຈໍານວນມື້ທີ່ບໍ່ມີຢູ່",
	"lateTimes": "ຈໍານວນຂອງການຊັກຊ້າ",
	"leaveEarlyTimes": "ອອກກ່ອນໄວອັນຄວນ",
	"lackOfTimeCount": "ຂາດຊົ່ວໂມງເຮັດວຽກ",
	"abNormalDutyCount": "ເວລາເຊັກອິນຜິດປົກກະຕິ",
	"resultNormal": "ຈໍານວນຂອງການຕີປົກກະຕິ",
	"seriousLateTimes": "ເວລາຊ້າຢ່າງຈິງຈັງ",
	"outsideDutyTimes": "ນອກເວລາເຊັກອິນ",
	"absenteeismTimes": "ຈຳນວນການຂາດຕົວ",
	"notSignedCount": "ບໍ່ໄດ້ເຊັນຊື່",

	"topUnitAttendanceDetail": "ລາຍລະອຽດການເຂົ້າຮ່ວມຂອງບໍລິສັດ",
	"topUnitAttendanceStatic": "ສະຖິຕິການເຂົ້າຮ່ວມຂອງບໍລິສັດ",
	"unitAttendanceDetail": "ລາຍລະອຽດການເຂົ້າຮຽນຂອງພະແນກ",
	"unitAttendanceStatic":"ສະຖິຕິການເຂົ້າຮຽນຂອງພະແນກ",
	"personAttendanceDetail": "ລາຍລະອຽດການເຂົ້າຮ່ວມສ່ວນຕົວ",
	"personAttendanceStatic": "ສະຖິຕິການເຂົ້າຮ່ວມສ່ວນຕົວ",
	"unitSigninDetail": "ລາຍລະອຽດການເຂົ້າສູ່ລະບົບຂອງພະແນກ",
	"unitSigninStatic": "ສະຖິຕິການເຂົ້າສູ່ລະບົບຂອງພະແນກ",
	"personSigninDetail": "ລາຍລະອຽດການເຂົ້າສູ່ລະບົບສ່ວນຕົວ",
	"personSigninStatic": "ສະຖິຕິການເຂົ້າສູ່ລະບົບສ່ວນຕົວ",
	"staticByDay": "ສະຖິຕິຕາມມື້",
	"staticByMonth": "ສະຖິຕິຕາມເດືອນ",
	"type": "ປະເພດ",
	"topUnit": "ບໍລິສັດ",
	"unit": "ພະແນກ",
	"annuaal": "ປະຈໍາປີ",
	"months": "ເດືອນ",
	"date": "ວັນທີ",
	"seeSchedule": "ເບິ່ງຕາຕະລາງ",
	"unfindSchedule": "ຕາຕະລາງຂອງພະແນກ ແລະບໍລິສັດຂອງເຈົ້າບໍ່ພົບ",
	"scheduleTable": "ຕາຕະລາງຕາຕະລາງ",
	"signTime": "ເວລາເຂົ້າສູ່ລະບົບ",
	"appeal": "ອຸທອນ",
	"createAppeal": "ອຸທອນ",
	"viewAppealDetail": "ເບິ່ງລາຍລະອຽດການອຸທອນ",
	"export": "ສົ່ງອອກ",
	"name1": "ຊື່",
	"alias": "ນາມແຝງ",
	"range": "range",
	"meter": "ແມັດ",
	"description": "ລາຍລະອຽດ",
	"save": "ບັນທຶກ",
	"enableMove": "ອະນຸຍາດໃຫ້ຍ້າຍ",
	"workPlaceEmptyNotice": "ບ່ອນເຮັດວຽກບໍ່ສາມາດຫວ່າງເປົ່າໄດ້",
	"BaiduDeveloperCertification": "ການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu",
	"registerBiaduNotice": "ການຕັ້ງຄ່າບ່ອນເຮັດວຽກໃຊ້ບໍລິການຂອງ Baidu Maps ເປີດແພລຟອມ. ທ່ານສາມາດລົງທະບຽນການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu ເພື່ອເພີ່ມຄວາມສອດຄ່ອງຂອງແຜນທີ່ໄດ້. ຫຼັງຈາກທີ່ການຢັ້ງຢືນສໍາເລັດແລ້ວ, ກະລຸນາຕື່ມຂໍ້ມູນໃສ່ໃນປ່ອງປ້ອນຂໍ້ມູນຂ້າງລຸ່ມນີ້. ",
	"openRegisterUrl": "ຄລິກທີ່ນີ້ເພື່ອເປີດຊ່ອງທາງການພິສູດຢືນຢັນ",
	"secretKey": "ກະແຈລັບ",
	"mustSelectMonth": "ເມື່ອເລືອກວັນທີ, ເຈົ້າຕ້ອງເລືອກເດືອນ",

	"index": {
		"attendanceCalendar":"ປະຕິທິນການເຂົ້າຮ່ວມ",
		"pieChart": "ບົດສະຫຼຸບການເຂົ້າຮ່ວມ",
		"lineChart": "ມຸ່ງຫມັ້ນທີ່ຈະອອກຈາກແນວໂນ້ມການເຮັດວຽກ",
		"absent":"ບໍ່ຢູ່",
		"offDutyTime":"ການເຂົ້າຮ່ວມ, ເວລາເຊັກອິນ:",
		"levelAsked": "ຂໍອອກ"
	},
	"schedule": {
		"inputVaild": "ຫົວໜ່ວຍ, ຊົ່ວໂມງເຮັດວຽກ, ເວລານອກໜ້າທີ່, ເວລາເລີ່ມຕົ້ນສຳລັບການມາຊ້າ, ແລະເວລາເລີ່ມຕົ້ນສຳລັບການຂາດວຽກບໍ່ສາມາດຫວ່າງເປົ່າໄດ້",
		"setSchedule": "ຕັ້ງຕາຕະລາງ",
		"unit": "ຫນ່ວຍ",
		"workTime": "ເວລາເຮັດວຽກ",
		"offTime": "ນອກເວລາ",
		"lateTime":"ເວລາເລີ່ມຕົ້ນຊ້າ",

		"leaveEarlyTime":"ອອກເວລາ",
		"absenteeismTime":"ເວລາເລີ່ມການບໍ່ມີຕົວຕົນ",
		"illegal":{
			"1":["ເວລານອກໜ້າທີ່ບໍ່ສາມາດໄວກວ່າເວລາຢູ່ໃນໜ້າທີ່"],
			"2":["ເວລາເລີ່ມຕົ້ນຂອງການພັກຜ່ອນອາຫານທ່ຽງບໍ່ຄວນໄວກວ່າເວລາເຮັດວຽກ","ເວລາສິ້ນສຸດຂອງການພັກຜ່ອນອາຫານທ່ຽງບໍ່ຄວນໄວກວ່າເວລາເລີ່ມຕົ້ນຂອງການພັກຜ່ອນທ່ຽງ","ເວລາສິ້ນສຸດຂອງ ການພັກຜ່ອນອາຫານທ່ຽງບໍ່ຄວນໄວກວ່າເວລາສິ້ນສຸດຂອງອາຫານທ່ຽງ"],
			"3":["ເວລາອອກຕອນເຊົ້າຈະບໍ່ໄວກວ່າເວລາເຮັດວຽກ","ເວລາເຮັດວຽກໃນຕອນບ່າຍຈະບໍ່ໄວກວ່າໂມງເຮັດວຽກຕອນເຊົ້າ","ເວລາອອກນອກເວລາເຮັດວຽກຈະບໍ່ໄວກວ່າເວລາເຮັດວຽກຕອນບ່າຍ"]
		},
		"lateStartTime":"ເວລາເລີ່ມເດິກຕອນເຊົ້າ",
		"leaveEarlyStartTime":"ອອກຈາກເວລາເລີ່ມຕົ້ນໄວ",
		"leaveEarlyStartTimeMorning":"ອອກຈາກເວລາເລີ່ມຕົ້ນຕອນເຊົ້າ",
		"lateStartTimeAfternoon": "ເວລາເລິ່ມຕົ້ນຕອນບ່າຍ",
		"signProxy":{
			"name":"ກົນລະຍຸດການເຂົ້າ",
			"select":{
				"1": "ໂມງເຂົ້າສອງຄັ້ງ (ເຮັດວຽກຕອນເຊົ້າ, ອອກງານຕອນບ່າຍ)",
				"2": "ເອົາໂມງສາມເທື່ອ (ໄປວຽກຕອນເຊົ້າ, ອອກງານຕອນບ່າຍ ແລະ ທ່ຽງ, ລວມສາມເທື່ອ)",
				"3": "ເຊັກອິນສີ່ຄັ້ງ (ເຊັກອິນທັງຕອນເຊົ້າ ແລະ ຕອນບ່າຍ)"
			},
			"2":{
				"middayRestStartTime":"ເວລາພັກຜ່ອນອາຫານທ່ຽງ",
				"middayRestEndTime":"ເວລາພັກຜ່ອນອາຫານທ່ຽງ",
			},
			"3":{
				"middayRestStartTime":"ຕອນເຊົ້ານອກເວລາ",
				"middayRestEndTime":"ເວລາເຮັດວຽກຕອນບ່າຍ",
			}
		}
	},
	"holiday": {
		"inputValid": "ປີ, ຊື່ວັນພັກ, ເວລາເລີ່ມຕົ້ນ, ເວລາສິ້ນສຸດແມ່ນຕ້ອງການ, ກະລຸນາຕື່ມຂໍ້ມູນໃສ່!",
		"setHoliday": "ການກຳນົດວັນພັກຜ່ອນຕາມກົດໝາຍ",
		"year": "ປີ",
		"name": "ຊື່ວັນພັກ",
		"startDate": "ວັນທີເລີ່ມຕົ້ນ",
		"endDate": "ວັນສິ້ນສຸດ",
		"makeUpClassDay": "ແຕ່ງໜ້າໄປວຽກ",
		"holidaySchedule": "ຕາຕະລາງວັນພັກ",
		"addMakeUpClassDay": "ເພີ່ມການແຕ່ງໜ້າມື້ເຮັດວຽກ",
		"beginGreateThanEndNotice": "ວັນທີເລີ່ມຕົ້ນບໍ່ສາມາດໃຫຍ່ກວ່າວັນທີສິ້ນສຸດໄດ້"
	},
	"permission": {
		"setAttendancer": "ການຕັ້ງພະນັກງານເຂົ້າຮ່ວມ",
		"role": "ບົດບາດ",
		"personName": "ບຸກຄົນ",
		"unit": "ຫນ່ວຍ",
		"roleSelectText": ["ຜູ້ບໍລິຫານບໍລິສັດ","ຜູ້ບໍລິຫານພະແນກ"]
	},
	"selfHoliday": {
		"inputValid": "ພະແນກ, ຊື່ພະນັກງານ, ປະເພດວັນພັກ, ເວລາເລີ່ມຕົ້ນ, ເວລາສິ້ນສຸດ, ແລະຈໍານວນວັນພັກຜ່ອນແມ່ນຕ້ອງການ, ກະລຸນາຕື່ມຂໍ້ມູນໃສ່!"
	},
	"nextActivity": "ການເຄື່ອນໄຫວຕໍ່ໄປ:",
	"nextUser": "ໂປເຊດເຊີ:",
	"deal": "ການຕົກລົງ",
	"processStarted": "ໄຟລ໌ໄດ້ຖືກເລີ່ມຕົ້ນ",
	"processStartedMessage": "ເຈົ້າໄດ້ເລີ່ມວຽກໃໝ່:",

	"auditStatus": "ສະຖານະອະນຸມັດ",
	"auditStatusSelectText": ["ສະຖານະທັງໝົດ","ລໍຖ້າ","ອະນຸມັດຜ່ານ","ອະນຸມັດບໍ່ສໍາເລັດ"],
	"appealReason": "ເຫດຜົນສໍາລັບການອຸທອນ",
	"appealReasonSelectText": ["","ການອອກຊົ່ວຄາວ","ການເດີນທາງທຸລະກິດ","ອອກໄປເຮັດທຸລະກິດ","ອື່ນໆ"],
	"ພະແນກ": "ພະແນກ",
	"person": "ຄົນ",
	"auditor": "ຜູ້ກວດສອບ",
	"search": "ຄົ້ນຫາ",
	"selectPerson": "ບຸກຄົນ",
	"selectCompany": "ບໍລິສັດ",
	"selectDepartment": "ພະແນກ",
	"selectAppealNotice": "ກະລຸນາເລືອກການອຸທອນກ່ອນ",
	"agreeAppealConfirmTitle": "ຕົກລົງທີ່ຈະອຸທອນ",
	"agreeAppealConfirmContent": "ທ່ານແນ່ໃຈບໍ່ທີ່ຈະດໍາເນີນ {count} ການອຸທອນທີ່ທ່ານເລືອກ?",
	"actionSuccess": "ການປະມວນຜົນສຳເລັດ",
	"disagreeAppealConfirmTitle": "ບໍ່ເຫັນດີກັບການອຸທອນ",
	"disagreeAppealConfirmContent": "ທ່ານແນ່ໃຈບໍ່ທີ່ຈະດໍາເນີນ {count} ການອຸທອນທີ່ທ່ານເລືອກ?",
	"draft": "ລິເລີ່ມ",
	"todo": "ການປຸງແຕ່ງ",
	"approve": "ອະນຸມັດ",
	"ປະຕິເສດ": "ການອະນຸມັດລົ້ມເຫລວ",
	"apealApplyForm": "ແບບຟອມຄໍາຮ້ອງສະຫມັກການອຸທອນ",
	"apealForm": "ແບບຟອມການອຸທອນ",
	"employeeName": "ຊື່ພະນັກງານ",
	"recordDate": "ວັນທີເຂົ້າຮ່ວມ",
	"onDutyTime": "OnDutyTime",
	"offDutyTime": "offDutyTime",
	"attendanceStatus": "ສະຖານະພາບການເຂົ້າຮ່ວມ",
	"appealStatus": "ສະຖານະອະນຸມັດ",
	"appealStatusSelectText": ["ກໍາລັງດໍາເນີນ","ລົ້ມເຫລວ","ອະນຸມັດ"],
	"address": "ສະຖານທີ່",
	"leaveType": "ປະເພດອອກ",
	"leaveTypeSelectText": ["","ການພັກປະຈໍາປີທີ່ໄດ້ຈ່າຍ","ການພັກເຊົາທີ່ໄດ້ຮັບຄ່າຈ້າງ","ການອອກສະຫວັດດີການທີ່ໄດ້ຈ່າຍ","ການພັກຜ່ອນທີ່ຈ່າຍ","ອື່ນໆ"],
	"startTime": "ເລີ່ມຕົ້ນ",
	"endTime": "ສິ້ນສຸດ",
	"appealDescriptoin": "ເຫດຜົນ",
	"close": "ປິດ",
	"disagree": "ບໍ່ເຫັນດີ",
	"agree": "ຕົກລົງ",
	"batchDisagree": "Batch Disagree",
	"batchAgree": "Batch Agree",
	"temporaryLeave": "ການອອກຊົ່ວຄາວ",
	"ອອກ": "ການເດີນທາງທຸລະກິດ",
	"businessTrip": "ອອກໄປເຮັດທຸລະກິດ",
	"other": "ອື່ນໆ",
	"inputIdeaNotice": "ກະລຸນາຕື່ມຄວາມຄິດເຫັນຂອງເຈົ້າ",
	"processSuccess": "ການປະມວນຜົນສຳເລັດ",
	"noDepartment": "ບໍ່ພົບພະແນກຂອງເຈົ້າ, ກະລຸນາຕິດຕໍ່ຜູ້ບໍລິຫານ!",
	"signinType": "ປະເພດການເຂົ້າສູ່ລະບົບ",
	"signinTypeSelectText": ["", "ເຊັກອິນຢູ່ບ່ອນເຮັດວຽກ", "ເຊັກອິນຫຼັງຈາກເລີກວຽກ"],
	"signinQywxTypeSelectText": ["", "ເຂົ້າວຽກ", "ເລີກວຽກ", "ອອກໄປນອກ"],
	"signinResult": "ຜົນການເຂົ້າສູ່ລະບົບ",
	"signinResultSelectText": ["", "ປົກກະຕິ", "ອອກກ່ອນໄວ", "ຊ້າ", "ຊ້າຫຼາຍ", "ເຂົ້າຊ້າ", "ບໍ່ໄດ້ໂມງເຂົ້າ", "ເຊັກອິນນອກ"],
	"signinQywxResultSelectText": ["", "ປົກກະຕິ", "ເວລາບໍ່ຖຶກ", "ສະຖານທີ່ບໍ່ຖຶກ", "ບໍ່ໄດ້ສະແກນບັດ" , "wifiບໍ່ໄດ້", "ສະແກນບັດໃນລະບົບ"],
	"recordAddress": "recordAddress",
	"optMachineType": "optMachineType",
	"workTime": "ເວລາເຮັດວຽກ",
	"systemSetting": "ການຕັ້ງຄ່າລະບົບ",
	"reportTo": "ລາຍງານວັດຖຸ",
	"appealEnable": "ສະຖານະເປີດການອຸທອນແລະການອະນຸມັດ",
	"appealSelectText": ["ເປີດ","ປິດ"],
	"appealAuditFlowType": "ປະເພດຂະບວນການອຸທອນຜົນການເຂົ້າຮ່ວມ",
	"appealAuditFlowTypeSelectText": ["Custom Flow","Built-in Flow"],
	"appealAuditorType": "ວິທີການກໍານົດຜູ້ກວດສອບການອຸທອນ",
	"appealAuditorValue": "ຜູ້ກວດສອບການອຸທອນກໍານົດເນື້ອໃນ",
	"directSupervisor": "ຜູ້ຄຸມໂດຍກົງ",
	"appealAuditFlow": "ປັບແຕ່ງຂັ້ນຕອນການສະໝັກ",
	"none": "ບໍ່ມີ",
	"saveSuccess": "ບັນທຶກສຳເລັດ",
	"noReportToNotice": "ວັດຖຸລາຍງານຂອງທ່ານບໍ່ໄດ້ຖືກຕັ້ງຄ່າໃນການຈັດການອົງກອນ, ກະລຸນາຕິດຕໍ່ຜູ້ເບິ່ງແຍງລະບົບ",
	"unitDuty": "ຕໍາແໜ່ງພະແນກ",
	"noUnitDutyNotice": "ບໍ່ມີຕໍາແຫນ່ງ {duty} ກັບ {unit} ທີ່ຖືກຕັ້ງຄ່າໃນລະບົບ, ກະລຸນາຕິດຕໍ່ຜູ້ເບິ່ງແຍງລະບົບ",
	"personAttribute": "ຄຸນລັກສະນະບຸກຄົນ",
	"noPersonAttribute": "ຄຸນສົມບັດສ່ວນຕົວຂອງທ່ານ '{att}' ບໍ່ໄດ້ຖືກຕັ້ງຄ່າໃນລະບົບ, ກະລຸນາຕິດຕໍ່ຜູ້ເບິ່ງແຍງລະບົບ",
	"assignedPerson": "ຜູ້ຖືກມອບໝາຍ",
	"directLeader": "ຜູ້ນໍາໂດຍກົງ",
	"noDirectLeader": "ຄຸນລັກສະນະສ່ວນຕົວຂອງເຈົ້າ 'ຜູ້ນຳໂດຍກົງ' ບໍ່ໄດ້ຖືກຕັ້ງຄ່າໃນລະບົບ, ກະລຸນາຕິດຕໍ່ຜູ້ເບິ່ງແຍງລະບົບ",
	"createAppealNotice": "ການຍື່ນອຸທອນໄດ້ຖືກສົ່ງ",

	"offDutyAbbrev": "ປິດ",
	"onDutyAbbrev": "ເປີດ",
	"attendanceSummary": "ບົດສະຫຼຸບການເຂົ້າຮ່ວມ",
	"attendanceTrendChart": "ແຜນຜັງທ່າອ່ຽງການເດີນທາງໄປມາ",
	"trendChartLegend": ['ເວລາເຮັດວຽກ','ເວລາເຮັດວຽກ'],
	"attendanceTrend": "ທ່າອ່ຽງການເຂົ້າຮ່ວມ",
	"year": "ປີ",

	"importExcelNotice": "ກະລຸນານໍາເຂົ້າໄຟລ໌ excel!",
	"analyseDataSuccess": "ວິເຄາະຂໍ້ມູນການເຂົ້າຮ່ວມຢ່າງສຳເລັດຜົນ",
	"statDataSuccess": "ສະຖິຕິການເຂົ້າຮຽນສຳເລັດຜົນ",
	"importDataStep": "ຂັ້ນຕອນການນໍາເຂົ້າຂໍ້ມູນ",
	"ການນໍາເຂົ້າຂັ້ນຕອນ": [
		"1. ດາວໂຫຼດແມ່ແບບ Excel ແລະຕື່ມຂໍ້ມູນການເຂົ້າຮ່ວມຕາມຮູບແບບແມ່ແບບ;",
		"2. ກົດທີ່ປຸ່ມ ນຳເຂົ້າຂໍ້ມູນການເຂົ້າວຽກ, ເລືອກຂໍ້ມູນການເຂົ້າຮ່ວມ ແລະຢືນຢັນ, ລະບົບຈະກວດສອບວ່າຂໍ້ມູນການເຂົ້າຮ່ວມນັ້ນຖືກຕ້ອງຫຼືບໍ່ ແລະນຳເຂົ້າຂໍ້ມູນ;",
		"3. ກົດປຸ່ມກວດສອບຂໍ້ມູນການເຂົ້າຮຽນ, ເລືອກປີແລະເດືອນທີ່ຈະກວດສອບ, ແລະລະບົບຈະກວດສອບຂໍ້ມູນຂອງພະນັກງານທີ່ຕ້ອງການກວດສອບການເຂົ້າຮຽນ;",
		"4. ກົດປຸ່ມ ວິເຄາະຂໍ້ມູນການເຂົ້າວຽກ, ແລະລະບົບຈະສ້າງຂໍ້ມູນການເຂົ້າຮ່ວມຢ່າງລະອຽດ;",
		"5. ກົດປຸ່ມສະຖິຕິການເຂົ້າຮຽນ, ແລະລະບົບຈະສ້າງສະຖິຕິການເຂົ້າຮ່ວມສໍາລັບບຸກຄົນ, ພະແນກ, ແລະບໍລິສັດ."
	],
	"selectCheckMonth":"ເລືອກເດືອນກວດ",
	"checkDetailSuccess": "ກວດສອບຂໍ້ມູນການເຂົ້າຮ່ວມຢ່າງສຳເລັດຜົນ",
	"importDataResult":"ຜົນການນຳເຂົ້າຂໍ້ມູນການເຂົ້າຮ່ວມ",
	"importDataResultSuccess": "ໄຟລ໌ທີ່ທ່ານອັບໂຫລດ: '{fileName}' ຖືກນຳເຂົ້າສຳເລັດແລ້ວ. ຕໍ່ໄປນີ້ຈະສະແດງ {count} ຂອງພວກມັນ:",
	"importDataResultFail": "ໄຟລ໌ທີ່ທ່ານອັບໂຫລດ: '{fileName}'' ລົ້ມເຫລວໃນການກວດສອບ, ມີຂໍ້ມູນຄວາມຜິດພາດ {errorCount} ຊິ້ນ. ກະລຸນາແກ້ໄຂ ແລະນໍາເຂົ້າຄືນໃໝ່. ຕໍ່ໄປນີ້ຈະສະແດງ {count} ຂອງພວກມັນ:",
	"importDataResultThList": [
		"ເລກແຖວ", "ເລກພະນັກງານ", "ຊື່ພະນັກງານ", "ວັນທີ", "ໂມງເຊົ້າ", "ໂມງເຊົ້າ", "ໂມງຕອນບ່າຍ", "ໂມງຕອນບ່າຍ", "ກວດເບິ່ງຜົນ", "ລາຍລະອຽດ "
	],
	"selectExportMonth":"ເລືອກເດືອນສົ່ງອອກ",
	"exportSourceData": "ຂໍ້ມູນແຫຼ່ງສົ່ງອອກ",
	"true": "ຖືກຕ້ອງ",
	"false": "ຜິດພາດ",
	"checkDataTitle": "ກຳລັງກວດສອບຂໍ້ມູນ",
	"checkDataContent": "ເລີ່ມກວດສອບຂໍ້ມູນ, {count} ລາຍການທັງໝົດ",
	"importDataTitle": "ການນໍາເຂົ້າຂໍ້ມູນ",
	"importDataContent": "ເລີ່ມນໍາເຂົ້າຂໍ້ມູນ, {count} ລາຍການທັງໝົດ",
	"readyToImportData": "ກຳລັງກະກຽມການນຳເຂົ້າຂໍ້ມູນ",
	"readyToImportData1": "ກຳລັງກະກຽມການນຳເຂົ້າຂໍ້ມູນ...",
	"importSpeed": "ລາຍການ/ວິນາທີ",
	"checkingDataContent": "ກຳລັງກວດສອບຂໍ້ມູນ: {speed}/sec, {total} ທັງໝົດ, ຍັງເຫຼືອ {remaning}",
	"checkingDataErrorContent": ",{errorCount} ຂໍ້ຜິດພາດ",
	"importingDataContent": "ການນໍາເຂົ້າຂໍ້ມູນ: {speed}/sec, {total} total, ຍັງເຫຼືອ {remaining}",
	"importingDataErrorContent": ",{errorCount} ຂໍ້ຜິດພາດ",
	"hour":"ຊົ່ວໂມງ",
	"mintue": "ນາທີ",
	"second": "ທີສອງ",
	"importSuccessTitle": "ການນໍາເຂົ້າສຳເລັດ",
	"importSuccessContent": "ຈຳນວນທັງໝົດ {total} ຊິ້ນສ່ວນຂອງຂໍ້ມູນຖືກນຳເຂົ້າ ຄວາມໄວ: {speed} ຕ່ອນ/ວິນາທີ ໃຊ້ເວລາຫຼາຍ: {timeStr}",
	"importFailTitle": "ການນໍາເຂົ້າລົ້ມເຫລວ",
	"importFailContent": "ຂໍ້ມູນທັງໝົດ {total} ລາຍການຜິດພາດ: {errorCount} ລາຍການທີ່ເສຍເວລາ: {timeStr} ກະລຸນາແກ້ໄຂ ແລະນຳເຂົ້າອີກຄັ້ງ",

	"myDetail": "ລາຍລະອຽດການເຂົ້າຮ່ວມຂອງຂ້ອຍ",
	"myDetailStatic": "ສະຖິຕິອັດຕາການເຂົ້າຮຽນຂອງຂ້ອຍ",

	"cyclText": "ຮອບການເຂົ້າຮຽນ: {start} ຫາ {end}",

	"personSetting": "ການຕັ້ງພະນັກງານເຂົ້າຮຽນ",
	"configType": "ປະເພດການຕັ້ງຄ່າ",
	"configTypeSelectText": ["ຕ້ອງການເຂົ້າຮ່ວມ","ບໍ່ຈໍາເປັນຕ້ອງເຂົ້າຮ່ວມ"],
	"topUnitName": "ຊື່ບໍລິສັດ",
	"unitName": "ຊື່ພະແນກ",
	"employeeNumber":"ໝາຍເລກພະນັກງານ",
	"joininDate": "ວັນທີເຂົ້າຮ່ວມ",

	"exportEmployeeHolidayRecord": "ການສົ່ງອອກບັນທຶກການພັກຜ່ອນຂອງພະນັກງານ",
	"employeeHolidayRecord": "ບັນທຶກການພັກຜ່ອນຂອງພະນັກງານ",

	"leaveType1": "ປະເພດອອກ",
	"leaveTypeSelectText1": ["ການພັກປະຈໍາປີທີ່ໄດ້ຈ່າຍ","ການລາພັກທີ່ໄດ້ຮັບຄ່າຈ້າງ","ການອອກເງິນຊ່ວຍເຫຼືອທີ່ໄດ້ຮັບ","ການຢຸດເຊົາຈ່າຍໃນທີ່ຈ່າຍ","ອື່ນໆ"],
	"leaveDayCount": "ນັບມື້ອອກ",

	"statisticsPeriodSetting": "ການກຳນົດໄລຍະເວລາສະຖິຕິ",
	"selectCompanyNotice": "ກົດສອງຄັ້ງເພື່ອເລືອກ, ຕື່ມຂໍ້ມູນໃສ່ '*' ເພື່ອໃຫ້ກົງກັບບໍລິສັດທັງໝົດ",
	"selectDepartmentNotice": "ກົດສອງຄັ້ງເພື່ອເລືອກ, ຕື່ມຂໍ້ມູນໃສ່ '*' ເພື່ອໃຫ້ກົງກັບທຸກພະແນກ",
	"statisticsCompany": "ບໍລິສັດສະຖິຕິ",
	"statisticsUnit": "ຫນ່ວຍງານສະຖິຕິ",
	"cycleYear": "ປີວົງຈອນສະຖິຕິ",
	"cycleMonth":"ເດືອນຮອບວຽນສະຖິຕິ",
	"startDate": "ວັນທີເລີ່ມຕົ້ນ",
	"endData": "ວັນທີສິ້ນສຸດ",

	"selectStartEndEndDataNotice":"ກະລຸນາເລືອກວັນທີເລີ່ມຕົ້ນ ແລະວັນທີສິ້ນສຸດ",
	"weekendSetting": "ການຕັ້ງຄ່າທ້າຍອາທິດ",
	"selectWeekend": "ເລືອກທ້າຍອາທິດ",

	"detail": "ລາຍລະອຽດ",
	"appealDate": "ວັນທີ່ອຸທອນ",
	"auditOpinion": "ຄວາມຄິດເຫັນການອະນຸມັດ",

	"holiday1": "ວັນພັກຜ່ອນ",
	"weekend": "ທ້າຍອາທິດ",
	"work Daysoff": "ມື້ພັກ",
	"workDay": "ມື້ເຮັດວຽກ",

	"middayRestStartTime":"ເວລາພັກຜ່ອນອາຫານທ່ຽງ",
	"middayRestEndTime":"ເວລາພັກຜ່ອນອາຫານທ່ຽງ",
	"isCheckInOutOfRange": "ນອກຂອບເຂດ",
	"yes": "ແມ່ນ",
	"no": "ບໍ່ແມ່ນ",

	"createWorkLocation":"ບ່ອນເຮັດວຽກໃໝ່",
	"createWorkLocationText": "ກົດແລະຍ້າຍໄປທີ່ທີ່ສອດຄ້ອງກັນໃນແຜນທີ່ ແລະກົດອີກຄັ້ງເພື່ອສ້າງ",
	"setBaiduDeveloperCertification": "ຕັ້ງການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu",
	"setBaiduDeveloperCertificationText": "ການຢັ້ງຢືນຜູ້ພັດທະນາ Baidu ແມ່ນຈໍາເປັນເພື່ອຕັ້ງຄ່າບ່ອນເຮັດວຽກ",

	"action": "ການກະທຳ",
	"start": "ເວລາເລີ່ມຕົ້ນ",
	"end": "ເວລາສິ້ນສຸດ",

	"appealIsDisable": "ການອະນຸມັດການອຸທອນການເຂົ້າຮ່ວມໄດ້ຖືກປິດໃຊ້ງານ",
	"batchDeal": "ການປະມວນຜົນຊຸດ:",
	"holi": "ວັນພັກ",
	"work": "ແຕ່ງຫນ້າ",
	"newHoliday": "ການກຳນົດຄ່າວັນພັກໃໝ່",
	"onDutyDayCount1": "ຈໍານວນມື້ທີ່ເຂົ້າຮ່ວມ",
	"onSelfHolidayCount1":"ຈຳນວນມື້ທີ່ຈະຂໍອອກເດີນທາງ",
	"absentCount": "ຈໍານວນມື້ທີ່ບໍ່ມີ",
	"fileName": "ຊື່ໄຟລ໌",
	"fileSize": "ຂະຫນາດໄຟລ໌",
	"uploadTime": "ເວລາອັບໂຫຼດ",
	"uploadPerson": "ຜູ້ອັບໂຫລດ",
	"action": "ການກະທຳ",
	"deleteFile": "ລົບໄຟລ໌",
	"download": "ດາວໂຫຼດໄຟລ໌",
	"viewImportResult": "ເບິ່ງຜົນການນໍາເຂົ້າ",
	"downloadExcelTemplate": "ດາວໂຫຼດແມ່ແບບ",
	"imporData": "ຂໍ້ມູນນໍາເຂົ້າ",
	"checkData": "ກວດສອບຂໍ້ມູນ",
	"statData": "ຂໍ້ມູນສະຖິຕິ",
	"analyzeData": "ວິເຄາະຂໍ້ມູນ",
	"viewDescription": "ເບິ່ງລາຍລະອຽດ",
// "myAppealTitleText": "ກະລຸນາຍື່ນອຸທອນໃນ 'ສະຖິຕິຂອງຂ້ອຍ -> ລາຍລະອຽດການເຂົ້າຮ່ວມຂອງຂ້ອຍ'",
	"myAppealTitleText": "ກະລຸນາອຸທອນໃນ 'ສະຖິຕິຂອງຂ້ອຍ'",

	"createManager": "ການຕັ້ງຄ່າຜູ້ເບິ່ງແຍງລະບົບໃໝ່",
	"createPersonConfig": "ເພີ່ມການຕັ້ງຄ່າພະນັກງານເຂົ້າຮ່ວມ",
	"addStaticCycle": "ເພີ່ມໄລຍະເວລາສະຖິຕິ",
	"errorDescription": "ລາຍລະອຽດຂໍ້ຜິດພາດ",
	"createSchedule ":"ການຕັ້ງຄ່າກຳນົດເວລາໃໝ່",
	"deleteSelected": "ລົບໄຟລ໌ທີ່ເລືອກ",

	"navi": {
		"myIndex": "ບົດລາຍງານປະຈໍາເດືອນຂອງຂ້ອຍ",
		"myDetail": "ສະຖິຕິຂອງຂ້ອຍ",
		"myAppealDeal": "ຄໍາຮ້ອງສະຫມັກການອຸທອນຂອງຂ້ອຍ",
		"appealDeal": "ການອະນຸມັດການອຸທອນ",

		"unitIndex": "ບົດລາຍງານຂອງກົມ",
		"peopleDetail": "ສະຖິຕິສ່ວນຕົວ",
		"unitDetail": "ສະຖິຕິພະແນກ",
		"topUnitDetail": "ສະຖິຕິບໍລິສັດ",
		"unitDingdingIndex": "ບົດລາຍງານພະແນກ Dingding",
		"unitQywxIndex": "ບົດລາຍງານຂອງກົມ Qywx",
		"dingdingPeopleDetail": "Dingding ສະຖິຕິສ່ວນຕົວ",
		"dingdingUnitDetail": " ສະຖິຕິຫນ່ວຍ Dingding ",
		"qywxPeopleDetail": "ສະຖິຕິສ່ວນບຸກຄົນ Qywx",
		"qywxUnitDetail": "ສະຖິຕິຫົວໜ່ວຍ Qywx",

		"maintain": "ບໍາລຸງຮັກສາ",
		"importing": "ການນໍາເຂົ້າຂໍ້ມູນ",
		"importedInvalidInfor": "ຂໍ້ຄວາມສະແດງຂໍ້ຜິດພາດໃນມືຖື",
		"abnormalExport": "ສົ່ງອອກຂໍ້ມູນຜິດປົກກະຕິ",
		"selfHoliday": "ບັນທຶກວັນພັກຜ່ອນ",
		"authorization": "ການອະນຸຍາດ",
		"permissionSetting": "ການຕັ້ງຄ່າຜູ້ເບິ່ງແຍງລະບົບ",
		"personSetting": "ການກຳນົດຄ່າບຸກຄົນ",
		"config": "ການຕັ້ງຄ່າ",
		"scheduleSetting": "ການຕັ້ງຄ່າຕາຕະລາງ",
		"staticsCycleExplorer": "ການຕັ້ງຄ່າໄລຍະເວລາສະຖິຕິ",
		"holidaySetting": "ວັນພັກຜ່ອນຕາມກົດໝາຍ",
		"addressSetting": "ການຕັ້ງຄ່າບ່ອນເຮັດວຽກ",
		"appSetting": "ການຕັ້ງຄ່າການອຸທອນ",
		"weekendSetting": "ການຕັ້ງຄ່າທ້າຍອາທິດ",
	},

	"week": "ອາທິດ",
	"weeks": {
		"Sun": "ວັນອາທິດ",
		"Mon": "ຈັນ",
		"Tues": "ຄານ",
		"Wed": "ພຸດ",
		"Thur": "ພະຫັດ",
		"Fri": "ສຸກ",
		"Sat": "ເສົາ",
		"arr": ["ວັນອາທິດ", "ຈັນ", "ຄານ", "ພຸດ", "ພະຫັດ", "ສຸກ", "ເສົາ"]
	}
};