MWF.xApplication.cms.Module.LP = {
	"title": "Content Management",

	"draftStatus": "Draft",
	"publishedStatus": "Published",
	"archivedStatus": "Archived",

	"noDescription": "Undefined description",

	"searchKey": "Please enter a keyword",
	"all": "All",
	"allDocument": "All Documents",
	"filter": "Filter",
	"ok": "OK",
	"cancel": "Cancel",
	"clear": "Clear",
	"defaultView": "Default View",
	"setDefaultView": "Set the next time you open the category to default to this view",
	"setDefaultSuccess": "Set the default view successfully!",

	"import": "Import",
	"export": "Export",
	"documentTitle": "Title",
	"activity": "activity",
	"status": "Status",
	"action": "Action",
	"person": "Drafter",
	"completedTime": "Completed Time",
	"process": "Process",

	"batchRemove": "Remove",
	"batchRemoveConfirm": "Confirm to clear",

	"processList": "Process",
	"activityNameList": "Activity",
	"creatorCompanyList": "Creator Company",
	"creatorDepartmentList": "Creator Department",
	"startTimeMonthList": "Create Time",
	"completedTimeMonthList": "Completed Time",
	"documentStatusList": "Process Status",
	"start": "New",
	"key": "Keyword",
	"noFormSelected": "No form is set for this category, please notify the administrator",
	"documentStartedMessage": "You created a document:",

	"copy": "Copy",
	"copyto": "Copy to...",
	"copyInfor": "Select documents, press Ctrl+C to copy the document, press Ctrl+V to paste the copied document into the column (this operation is cross-server)",
	"copyed": "The selected document has been copied",
	"copyConfirmTitle": "Copy Document Confirmation",
	"copyConfirmInfor": "The target area already contains the same elements:",
	"copySource": "Original file:",
	"copyTarget": "Copy file:",
	"copyConfirm_overwrite": "Replace",
	"copyConfirm_new": "New",
	"copyConfirm_skip": "Skip",
	"copyConfirm_cancel": "Cancel",
	"copynew": "New",
	"copyConfirmCategoryTitle": "Copy document category confirmation",
	"copyConfirmCategoryInfor_noCategory": "Cannot find the category in the new column according to the original category {name} of the document, please select which category you want to copy to",
	"copyConfirmCategoryInfor_hasSameAlias": "Cannot find the category in the new column according to the original category ID of the document, but there is a category {alias} with the same alias (alias)",
	"copyConfirmCategoryInfor_hasSameName": "Cannot find the category in the new column according to the original category ID of the document, but there is a category {name} with the same name (name)",
	"copyConfirmCateogyrInfor_withChoice": "Or select the category to copy (if you choose to copy according to the selected category):",
	"copyConfirm_SameCategory": "Subsequent documents of the same category are copied according to this operation",
	"notSelectCategory": "Please select a category",

	"open": "Open",
	"delete": "Delete",
	"edit": "Edit",
	"setTop": "SetTop",
	"share": "Share",

	"phone": "Phone",
	"mail": "Mail",

	"deleteDocumentTitle": "Delete Confirmation",
	"deleteDocument": "Are you sure you want to delete {title}?",
	"deleteDocumentOK": "Document deleted successfully",
	"currentDocument": "The document",

	"untitled": "Untitled",
	"select": "Select",
	"cancelSelect": "Cancel Selection",
	"move": "Move",
	"selectDocNotice": "Please select the document",
	"moveDocConfirmTitle": "Move Confirmation",
	"moveDocConfirmContent": "After moving, it will be deleted in this category. Are you sure you want to move the selected {count} documents to {category}?",
	"moveDocSuccessNotice": "Move Succeeded",
	"clearDocConfirmTitle": "Clear Confirmation",
	"clearDocConfirmContent": "Cannot be restored after deletion. Are you sure you want to delete the selected {count} documents?",
	"clearDocSuccessNotice": "Clear successfully",
	"selectCategoryText": "Select the category of {title}",
	"systemList": "System List",

	"enableCopy": "Enable Copy",
	"attachmentBlankNotice": "The uploaded file cannot contain spaces",
	"selectCategory": "Select Category",

	"subject": "Title",
	"appName": "App Name",
	"category": "Category",
	"creatorCompany": "Create Company",
	"creatorDepartment": "Create Department",
	"creatorPerson": "Creator",
	"publishTime": "Publish Time"
};