MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.cms = MWF.xApplication.cms || {};
MWF.xApplication.cms.Module = MWF.xApplication.cms.Module || {};
MWF.xApplication.cms.Module.LP={
	"title": "Gestión de contenido",
	"draftStatus": "Borrador",
	"delayStatus": "Publicación programada",
	"publishedStatus": "Publicado",
	"archivedStatus": "Archivado",
	"noDescription": "Sin descripción definida",
	"searchKey": "Ingrese palabra clave",
	"all": "Todo",
	"allDocument": "Todos los documentos",
	"filter": "Filtro",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"clear": "Limpiar",
	"defaultView": "Vista predeterminada",
	"setDefaultView": "Establecer vista predeterminada por categoría la próxima vez que se abra",
	"setDefaultSuccess": "¡La vista predeterminada se ha establecido con éxito!",
	"import": "Importar",
	"export": "Exportar",
	"documentTitle": "Título del documento",
	"activity": "Actividad",
	"status": "Estado",
	"action": "Acción",
	"person": "Persona que redactó",
	"completedTime": "Tiempo completado",
	"process": "Proceso",
	"batchRemove": "Eliminar",
	"batchRemoveConfirm": "¿Está seguro de que desea eliminar?",
	"processList": "Proceso",
	"activityNameList": "Actividad",
	"creatorCompanyList": "Compañía creadora",
	"creatorDepartmentList": "Departamento creador",
	"startTimeMonthList": "Tiempo de creación",
	"completedTimeMonthList": "Tiempo completado",
	"documentStatusList": "Estado del proceso",
	"start": "Empezar",
	"key": "Palabra clave",
	"noFormSelected": "Este categoría no tiene un formulario configurado, por favor informe al administrador",
	"documentStartedMessage": "Usted ha creado un documento:",
	"copy": "Copiar",
	"copyto": "Copiar a...",
	"copyInfor": "Seleccione el documento, presione Ctrl + C para copiar el documento y presione Ctrl + V para pegar el documento copiado en la columna (esta operación es transversal al servidor)",
	"copyed": "Documentos seleccionados copiados",
	"copyConfirmTitle": "Confirmación",
	"copyConfirmInfor": "El área de destino ya contiene elementos idénticos:",
	"copySource": "Archivo de origen:",
	"copyTarget": "Archivo copiado:",
	"copyConfirm_overwrite": "Reemplazar",
	"copyConfirm_new": "Nuevo",
	"copyConfirm_skip": "Saltar",
	"copyConfirm_cancel": "Cancelar",
	"copynew": "Nuevo",
	"copyConfirmCategoryTitle": "Confirmación",
	"copyConfirmCategoryInfor_noCategory": "No se puede encontrar la categoría según la categoría original del documento {name} en la nueva columna, seleccione la categoría a la que desea copiar",
	"copyConfirmCategoryInfor_hasSameAlias": "No se puede encontrar la categoría según el ID de categoría original del documento en la nueva columna, pero hay una categoría con el mismo alias ({alias})",
	"copyConfirmCategoryInfor_hasSameName": "No se puede encontrar la categoría según el ID de la categoría original del documento en la nueva columna, pero hay una categoría con el mismo nombre ({name})",
	"copyConfirmCateogyrInfor_withChoice": "O elija una categoría para copiar (si elige, significa copiar según la categoría seleccionada):",
	"copyConfirm_SameCategory": "Los documentos siguientes con la misma categoría se copiarán según esta operación",
	"notSelectCategory": "Seleccione una categoría primero",
	"open": "Abrir",
	"delete": "Eliminar",
	"edit": "Editar",
	"setTop": "Fijar en la parte superior",
	"share": "Compartir",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"deleteDocumentTitle": "Confirmación de eliminación",
	"deleteDocument": "¿Está seguro de que desea eliminar {title}?",
	"deleteDocumentOK": "Documento eliminado con éxito",
	"currentDocument": "Este documento",
	"untitled": "Sin título",
	"select": "Seleccionar",
	"cancelSelect": "Cancelar selección",
	"move": "Mover",
	"selectDocNotice": "Seleccione un documento primero",
	"moveDocConfirmTitle": "Confirmación de movimiento",
	"moveDocConfirmContent": "¿Está seguro de que desea mover los {count} documentos seleccionados a {category}? Después de la mudanza, se eliminarán de esta categoría.",
	"moveDocSuccessNotice": "Movido con éxito",
	"clearDocConfirmTitle": "Confirmación de eliminación",
	"clearDocConfirmContent": "Después de la eliminación, no se puede recuperar ¿Está seguro de que desea eliminar los {count} documentos seleccionados?",
	"clearDocSuccessNotice": "Eliminado con éxito",
	"selectCategoryText": "Seleccione la categoría de {title}",
	"systemList": "Lista del sistema",
	"enableCopy": "Habilitar copia",
	"attachmentBlankNotice": "Los archivos cargados no pueden contener espacios en blanco",
	"selectCategory": "Seleccionar categoría",
	"subject": "Título",
	"appName": "Columna",
	"category": "Categoría",
	"creatorCompany": "Compañía creadora",
	"creatorDepartment": "Departamento creador",
	"creatorPerson": "Creador",
	"publishTime": "Tiempo de publicación",
	"publishTimeDelay": "Tiempo de publicación programado"
}
MWF.xApplication.cms.Module["lp."+o2.language] = MWF.xApplication.cms.Module.LP