MWF.xApplication.cms.Module.LP = {
	"title": "컨텐츠 관리",
	"draftStatus": "드래프트",
	"delayStatus": "예약 게시",
	"publishedStatus": "게시됨",
	"archivedStatus": "보관됨",
	"noDescription": "설명이 정의되지 않음",
	"searchKey": "검색어를 입력하세요",
	"all": "모두",
	"allDocument": "모든 문서",
	"filter": "필터",
	"ok": "확인",
	"cancel": "취소",
	"clear": "지우기",
	"defaultView": "기본 보기",
	"setDefaultView": "다음에 분류를 열 때 기본 보기로 설정",
	"setDefaultSuccess": "기본 보기 설정 성공!",
	"import": "가져오기",
	"export": "내보내기",
	"documentTitle": "제목",
	"activity": "활동",
	"status": "상태",
	"action": "작업",
	"person": "작성자",
	"completedTime": "완료 시간",
	"process": "프로세스",
	"batchRemove": "지우기",
	"batchRemoveConfirm": "정말로 삭제하시겠습니까?",
	"processList": "프로세스",
	"activityNameList": "활동",
	"creatorCompanyList": "작성 회사",
	"creatorDepartmentList": "작성 부서",
	"startTimeMonthList": "작성 시간",
	"completedTimeMonthList": "완료 시간",
	"documentStatusList": "프로세스 상태",
	"start": "신규 작성",
	"key": "키워드",
	"noFormSelected": "이 분류에 양식이 설정되지 않았으므로 작성할 수 없습니다. 관리자에게 알려주십시오.",
	"documentStartedMessage": "새로운 문서를 작성하셨습니다:",

	"copy": "복사",
	"copyto": "복사 대상...",
	"copyInfor": "문서를 선택한 후 Ctrl+C를 눌러 복사하고, Ctrl+V를 눌러 복사한 문서를 새 카테고리에 붙여넣을 수 있습니다 (이 작업은 서버 간 복사입니다).",
	"copyed": "선택한 문서가 복사되었습니다.",
	"copyConfirmTitle": "문서 복사 확인",
	"copyConfirmInfor": "대상 영역에 이미 동일한 요소가 포함되어 있습니다:",
	"copySource": "원본 파일:",
	"copyTarget": "복사 파일:",
	"copyConfirm_overwrite": "덮어쓰기",
	"copyConfirm_new": "새로 만들기",
	"copyConfirm_skip": "건너뛰기",
	"copyConfirm_cancel": "취소",
	"copynew": "새로운",
	"copyConfirmCategoryTitle": "문서 카테고리 복사 확인",
	"copyConfirmCategoryInfor_noCategory": "원본 카테고리 {name}을(를) 새로운 카테고리에서 찾을 수 없으므로 원하는 카테고리를 선택하세요.",
	"copyConfirmCategoryInfor_hasSameAlias": "새로운 카테고리에서는 원본 카테고리 ID를 찾을 수 없지만 동일한 별칭(alias) {alias}을 가진 카테고리가 있습니다.",
	"copyConfirmCategoryInfor_hasSameName": "새로운 카테고리에서는 원본 카테고리 ID를 찾을 수 없지만 동일한 이름(name) {name}을 가진 카테고리가 있습니다.",
	"copyConfirmCateogyrInfor_withChoice": "또는 복사할 카테고리를 선택하세요 (선택한 카테고리를 기준으로 복사됩니다):",
	"copyConfirm_SameCategory": "동일한 카테고리를 가진 다음 문서는 이 작업을 기준으로 복사됩니다.",
	"notSelectCategory": "먼저 카테고리를 선택하세요.",

	"open": "열기",
	"delete": "삭제",
	"edit": "편집",
	"setTop": "상단 고정",
	"share": "공유",

	"phone": "전화",
	"mail": "이메일",

	"deleteDocumentTitle": "삭제 확인",
	"deleteDocument": "{title}을(를) 삭제하시겠습니까?",
	"deleteDocumentOK": "문서가 성공적으로 삭제되었습니다.",
	"currentDocument": "현재 문서",

	"untitled": "제목 없음",
	"select": "선택",
	"cancelSelect": "선택 취소",
	"move": "이동",
	"selectDocNotice": "먼저 문서를 선택하세요.",
	"moveDocConfirmTitle": "이동 확인",
	"moveDocConfirmContent": "이동 후 해당 분류에서 삭제되며, 선택한 {count}개의 문서를 {category}로 이동하시겠습니까?",
	"moveDocSuccessNotice": "이동이 성공적으로 완료되었습니다.",
	"clearDocConfirmTitle": "삭제 확인",
	"clearDocConfirmContent": "삭제 후에는 복구할 수 없습니다. 선택한 {count}개의 문서를 삭제하시겠습니까?",
	"clearDocSuccessNotice": "삭제가 성공적으로 완료되었습니다.",
	"selectCategoryText": "{title}의 분류 선택",
	"systemList": "시스템 목록",

	"enableCopy": "복사 활성화",
	"attachmentBlankNotice": "업로드한 파일은 공백을 포함할 수 없습니다.",
	"selectCategory": "분류 선택",

	"subject": "제목",
	"appName": "카테고리",
	"category": "분류",
	"creatorCompany": "회사",
	"creatorDepartment": "부서",
	"creatorPerson": "작성자",
	"publishTime": "게시 시간",
	"publishTimeDelay": "예약 게시 시간"


};