MWF.xApplication.cms.Module.LP = {
	"title": "ບໍລິຫານເນື້ອໃນ",

	"draftStatus" : "ຮ່າງສະບັບ",
	"delayStatus" : "ກຳນົດເວລາເຜີຍແຜ່",
	"publishedStatus" : "ເຜີຍແຜ່ແລ້ວ",
	"archivedStatus" : "ຈັດເກັບແລ້ວ",

	"noDescription" : "ບໍ່ມີອະທິບາຍ",

	"searchKey": "ກະລຸນາໃສ່ຄຳຫຼັກ",
	"all": "ທັງໝົດ",
	"allDocument": "ເອກະສານທັງໝົດ",
	"filter": "ກັ່ນຕອງ",
	"ok": "ຢືນຢັນ",
	"cancel" : "ຍົກເລີກ",
	"clear": "ລ້າງ",
	"defaultView" : "ຄ່າເລີ່ມຕົ້ນ View",
	"setDefaultView" : "ຕັ້ງຄ່າ View ໃຫ້ເປັນຄ່າເລີ່ມຕົ້ນ ໃນຄັ້ງຕໍ່ໄປທີ່ເປີດໝວດໝູ່ ",
	"setDefaultSuccess" : "ຕັ້ງຄ່າ View ສຳເລັດ!",

	"import" : "ນຳເຂົ້າ",
	"export" : "ນຳອອກ",
	"documentTitle": "ຫົວຂໍ້",
	"activity": "activity",
	"status": "ສະຖານະ",
	"action": "ດຳເນີນ",
	"person": "ຄົນຮ່າງ",
	"completedTime": "ເວລາສຳເລັດ",
	"process": "ຂະບວນການ",


	"batchRemove" : "ຍ້າຍອອກ",
	"batchRemoveConfirm" : "ຢືນຢັນຍ້າຍອອກ",

	"processList": "ຂະບວນການ",
	"activityNameList": "activity",
	"creatorCompanyList": "ສ້າງບໍລິສັດ",
	"creatorDepartmentList": "ສ້າງພະແນກ",
	"startTimeMonthList": "ສ້າງເວລາ",
	"completedTimeMonthList": "ເວລາສຳເລັດ",
	"documentStatusList": "ຂະບວນການສະຖານະ",
	"start" : "ໃໝ່",
	"key": "ຄຳຫຼັກ",
	"noFormSelected" : "ບໍ່ມີຟອມໃນການຕັ້ງຄ່າໝວດໝູ່ນີ້，ກະລຸນາແຈ້ງຜູ້ບໍລິຫານ",
	"documentStartedMessage": "ເຈົ້າສ້າງເອກະສານ：",

	"copy": "ສຳເນົາ",
	"copyto": "ສຳເນົາໄປທີ່...",
	"copyInfor": "ເລືອກເອກະສານ，ໃຫ້ Ctrl+Cສາມາດສຳເນົາໄດ້，ກົດCtrl+V ເພື່ອວ່າງເອກະສານທີ່ສຳເນົາໄວ້（ການດຳເນີນການນີ້ແມ່ນ cross-server）",
	"copyed": "ເລືອກສຳເນົາເອກະສານແລ້ວ",
	"copyConfirmTitle": "ຢືນຢັນສຳເນົາເອກະສານ",
	"copyConfirmInfor": "ພື້ນທີ່ເປົ້າໝາຍມີອົງປະກອບດຽວກັນ：",
	"copySource": "ເອກສານເກົ່າ:",
	"copyTarget": "ສຳເນົາເອກະສານ:",
	"copyConfirm_overwrite": "ແທນທີ່",
	"copyConfirm_new": "ໃໝ່",
	"copyConfirm_skip": "ຂ້າມ",
	"copyConfirm_cancel": "ຍົກເລີກ",
	"copynew": "ໃໝ່",
	"copyConfirmCategoryTitle": "ຢືນຢັນສຳເນົາໝວດໝູ່ເອກະສານ",
	"copyConfirmCategoryInfor_noCategory": "ບໍ່ສາມາດພົບໝວດໝູ່ນີ້{name}ໃນຖັນໃໝ່ຊອກຫາໝວດໝູ່ນີ້ໃນຖັນເກົ່າ，ກະລຸນາເລືອກໝວດໝູ່ທີ່ເຈົ້າຕ້ອງການສຳເນົາ",
	"copyConfirmCategoryInfor_hasSameAlias": "ບໍ່ສາມາດພົບໝວດໝູ່ນີ້ ID ໃນຖັນໃໝ່ຊອກຫາໝວດໝູ່ນີ້ໃນຖັນເກົ່າ，ແຕ່ມີຊື່（alias）ໝວດໝູ່ທີ່ຄືກັນ {alias}",
	"copyConfirmCategoryInfor_hasSameName": "ບໍ່ສາມາດພົບໝວດໝູ່ນີ້ ID ໃນຖັນໃໝ່ຊອກຫາໝວດໝູ່ນີ້ໃນຖັນເກົ່າ，ແຕ່ມີຊື່（name）ໝວດໝູ່ທີ່ຄືກັນ {name}",
	"copyConfirmCateogyrInfor_withChoice" : "ຫຼືເລືອກປະເພດເພື່ອສຳເນົາ（ຖ້າວ່າເລືອກໝາຍເຖິງສຳເນົາຕາມໝວດໝູ່ທີ່ເລືອກ）：",
	"copyConfirm_SameCategory" : "ເອກະສານປະເພດດຽວກັນແມ່ນຖືກສຳເນົາຕາມການດຳເນີນການນີ້",
	"notSelectCategory" : "ກະລຸນາເລືອກໝວດໝູ່",

	"open" : "ເປີດ",
	"delete" : "ລົບ",
	"edit" : "ແກ້ໄຂ",
	"setTop" : "ປັກມຸດ",
	"share" : "ແບ່ງປັນ",

	"phone" : "phone",
	"mail" : "ເມວ",

	"deleteDocumentTitle": "ຢືນຢັນລົບ",
	"deleteDocument": "ເຈົ້າແນ່ໃຈບໍ່ວ່າຕ້ອງການລົບ{title}ນີ້?",
	"deleteDocumentOK": "ລົບເອກະສານສຳເລັດ",
	"currentDocument" : "ເອກະສານ",

	"untitled" : "ບໍ່ມີຫົວຂໍ້",
	"select" : "ເລືອກ",
	"cancelSelect" : "ຍົກເລີກເລືອກ",
	"move" : "ຍ້າຍ",
	"selectDocNotice" : "ກະລຸນາເລືອກເອກະສານ",
	"moveDocConfirmTitle" : "ຢືນຢັນຍ້າຍເອກະສານ",
	"moveDocConfirmContent" : "ຫຼັງຈາກການຍ້າຍປະເພດທີ່ຢູ່ນີ້ຈະຖືກລົບ，ແນ່ໃຈວ່າຕ້ອງການຍ້າຍເອກະສານທີ່ເລືອກ{count}ໄປທີ່{category}？",
	"moveDocSuccessNotice" : "ຍ້າຍສຳເລັດ",
	"clearDocConfirmTitle" : "ຢືນຢັນລ້າງຂໍ້ມູນ",
	"clearDocConfirmContent" : "ບໍ່ສາມາດກູ້ຄືນຫຼັງຈາກການລົບໄດ້，ແນ່ໃຈວ່າຈະລົບເອກະສານທີ່ເລືອກ{count}ລາຍການ？",
	"clearDocSuccessNotice" : "ລ້າງສຳເລັດ",
	"selectCategoryText" : "ເລືອກ{title}ປະເພດ",
	"systemList" : "ລາຍການລະບົບ",

	"enableCopy": "ສຳເນົາ ເປີດໃຊ້ງານ",
	"attachmentBlankNotice" : "ເອກະສານອັບໂຫລດບໍ່ສາມາດມີເວັ້ນວ່າງໄດ້",
	"selectCategory": "ເລືອກປະເພດ",

	"subject": "ຫົວຂໍ້",
	"appName": "App Name",
	"category": "ໝວດໝູ່",
	"creatorCompany": "ສ້າງບໍລິສັດ",
	"creatorDepartment": "ສ້າງພະແນກ",
	"creatorPerson": "ຜູ້ສ້າງ",
	"publishTime": "ເວລາເຜີຍແຜ່",
	"publishTimeDelay": "ກຳນົດເວລາເຜີຍແຜ່"


};