MWF.xApplication.cms.Module.LP = {
	"title": "内容管理",

	"draftStatus" : "草稿",
	"publishedStatus" : "已发布",
	"archivedStatus" : "已归档",

	"noDescription" : "未定义描述",

	"searchKey": "请输入关键字",
	"all": "全部",
	"allDocument": "所有文档",
	"filter": "筛选",
	"ok": "确定",
	"cancel" : "取消",
	"clear": "清除",
	"defaultView" : "默认视图",
	"setDefaultView" : "设置下次打开分类默认为该视图",
	"setDefaultSuccess" : "设置默认视图成功!",

	"import" : "导入",
	"export" : "导出",
	"documentTitle": "标题",
	"activity": "活动",
	"status": "状态",
	"action": "操作",
	"person": "拟稿人",
	"completedTime": "完成时间",
	"process": "流程",

	"batchRemove" : "清除",
	"batchRemoveConfirm" : "确定清除",

	"processList": "流程",
	"activityNameList": "活动",
	"creatorCompanyList": "创建公司",
	"creatorDepartmentList": "创建部门",
	"startTimeMonthList": "创建时间",
	"completedTimeMonthList": "完成时间",
	"documentStatusList": "流程状态",
	"start" : "新建",
	"key": "关键字",
	"noFormSelected" : "该分类未设置表单，请通知管理员",
	"documentStartedMessage": "您创建了一份文档：",

	"copy": "复制",
	"copyto": "复制到...",
	"copyInfor": "选择文档，按Ctrl+C可复制文档，按下Ctrl+V可将复制的文档粘贴到栏目（本操作跨服务器）",
	"copyed": "所选文档已复制",
	"copyConfirmTitle": "复制文档确认",
	"copyConfirmInfor": "目标区域已包含相同的元素：",
	"copySource": "原文件:",
	"copyTarget": "复制文件:",
	"copyConfirm_overwrite": "替换",
	"copyConfirm_new": "新建",
	"copyConfirm_skip": "跳过",
	"copyConfirm_cancel": "取消",
	"copynew": "新",
	"copyConfirmCategoryTitle": "复制文档分类确认",
	"copyConfirmCategoryInfor_noCategory": "不能根据文档的原分类{name}在新栏目找到分类，请选择需要拷贝到哪个分类",
	"copyConfirmCategoryInfor_hasSameAlias": "不能根据文档的原分类ID在新栏目找到分类，但有相同别名（alias）的分类{alias}",
	"copyConfirmCategoryInfor_hasSameName": "不能根据文档的原分类ID在新栏目找到分类，但有相同名称（name）的分类{name}",
	"copyConfirmCateogyrInfor_withChoice" : "或者选择分类进行复制（如果选择表示根据选择的分类复制）：",
	"copyConfirm_SameCategory" : "后续相同分类的文档都根据该操作进行复制",
	"notSelectCategory" : "请先选择分类",

	"open" : "打开",
	"delete" : "删除",
	"edit" : "编辑",
	"setTop" : "置顶",
	"share" : "分享",

	"phone" : "电话",
	"mail" : "邮件",

	"deleteDocumentTitle": "删除确认",
	"deleteDocument": "您确定要删除{title}吗?", 
	"deleteDocumentOK": "文档删除成功",
	"currentDocument" : "该文档",

	"untitled" : "无标题",
	"select" : "选择",
	"cancelSelect" : "取消选择",
	"move" : "移动",
	"selectDocNotice" : "请先选择文档",
	"moveDocConfirmTitle" : "移动确认",
	"moveDocConfirmContent" : "移动后将在本分类删除，确定要移动选中的{count}个文档到{category}？",
	"moveDocSuccessNotice" : "移动成功",
	"clearDocConfirmTitle" : "清除确认",
	"clearDocConfirmContent" : "删除后无法恢复，确定要删除选中的{count}个文档？",
	"clearDocSuccessNotice" : "清除成功",
	"selectCategoryText" : "选择{title}的分类",
	"systemList" : "系统列表",

	"enableCopy": "启用复制",
	"attachmentBlankNotice" : "上传的文件不能带空格",
	"selectCategory": "选择分类",

	"subject": "标题",
	"appName": "栏目",
	"category": "分类",
	"creatorCompany": "创建公司",
	"creatorDepartment": "创建部门",
	"creatorPerson": "创建人",
	"publishTime": "发布时间"



};