MWF.xApplication.cms.Module.LP = {
	"title": "內容管理",
	"draftStatus": "草稿",
	"delayStatus": "定時發布",
	"publishedStatus": "已發布",
	"archivedStatus": "已歸檔",
	"noDescription": "未定義描述",
	"searchKey": "請輸入關鍵字",
	"all": "全部",
	"allDocument": "所有文檔",
	"filter": "篩選",
	"ok": "確定",
	"cancel": "取消",
	"clear": "清除",
	"defaultView": "默認視圖",
	"setDefaultView": "設置下次打開分類默認為該視圖",
	"setDefaultSuccess": "設置默認視圖成功！",
	"import": "導入",
	"export": "導出",
	"documentTitle": "標題",
	"activity": "活動",
	"status": "狀態",
	"action": "操作",
	"person": "拟稿人",
	"completedTime": "完成時間",
	"process": "流程",
	"batchRemove": "清除",
	"batchRemoveConfirm": "確定要刪除嗎？",
	"processList": "流程",
	"activityNameList": "活動",
	"creatorCompanyList": "創建公司",
	"creatorDepartmentList": "創建部門",
	"startTimeMonthList": "創建時間",
	"completedTimeMonthList": "完成時間",
	"documentStatusList": "流程狀態",
	"start": "新建",
	"key": "關鍵字",
	"noFormSelected": "該分類未設置表單，無法創建，請聯繫管理員",
	"documentStartedMessage": "您創建了一份文件：",

	"copy": "複製",
	"copyto": "複製到...",
	"copyInfor": "選擇文檔後，按下Ctrl+C可複製文檔，按下Ctrl+V可將複製的文檔粘貼到欄目（此操作跨服務器）。",
	"copyed": "所選文檔已複製。",
	"copyConfirmTitle": "複製文檔確認",
	"copyConfirmInfor": "目標區域已包含相同的元素：",
	"copySource": "原始文件：",
	"copyTarget": "複製文件：",
	"copyConfirm_overwrite": "覆蓋",
	"copyConfirm_new": "新建",
	"copyConfirm_skip": "跳過",
	"copyConfirm_cancel": "取消",
	"copynew": "新",
	"copyConfirmCategoryTitle": "複製文檔分類確認",
	"copyConfirmCategoryInfor_noCategory": "無法根據文檔的原始分類{name}在新欄目中找到分類，請選擇要複製到哪個分類。",
	"copyConfirmCategoryInfor_hasSameAlias": "無法根據文檔的原始分類ID在新欄目中找到分類，但有相同別名（alias）{alias}的分類。",
	"copyConfirmCategoryInfor_hasSameName": "無法根據文檔的原始分類ID在新欄目中找到分類，但有相同名稱（name）{name}的分類。",
	"copyConfirmCateogyrInfor_withChoice": "或者請選擇要複製的分類（如果選擇，表示根據所選的分類進行複製）：",
	"copyConfirm_SameCategory": "後續相同分類的文檔將根據此操作進行複製。",
	"notSelectCategory": "請先選擇分類。",

	"open": "打開",
	"delete": "刪除",
	"edit": "編輯",
	"setTop": "置頂",
	"share": "分享",

	"phone": "電話",
	"mail": "郵件",

	"deleteDocumentTitle": "刪除確認",
	"deleteDocument": "您確定要刪除{title}嗎？",
	"deleteDocumentOK": "文檔刪除成功",
	"currentDocument": "該文檔",

	"untitled": "無標題",
	"select": "選擇",
	"cancelSelect": "取消選擇",
	"move": "移動",
	"selectDocNotice": "請先選擇文檔",
	"moveDocConfirmTitle": "移動確認",
	"moveDocConfirmContent": "移動後將在本分類中刪除，確定要移動選中的{count}個文檔到{category}嗎？",
	"moveDocSuccessNotice": "移動成功",
	"clearDocConfirmTitle": "清除確認",
	"clearDocConfirmContent": "刪除後無法恢復，確定要刪除選中的{count}個文檔嗎？",
	"clearDocSuccessNotice": "清除成功",
	"selectCategoryText": "選擇{title}的分類",
	"systemList": "系統列表",

	"enableCopy": "啟用複製",
	"attachmentBlankNotice": "上傳的文件不能包含空格",
	"selectCategory": "選擇分類",

	"subject": "標題",
	"appName": "分類",
	"category": "分類",
	"creatorCompany": "創建公司",
	"creatorDepartment": "創建部門",
	"creatorPerson": "創建人",
	"publishTime": "發佈時間",
	"publishTimeDelay": "定時發佈時間"


};