MWF.xApplication.FindDesigner.LP = {
	"title": "デザイン内検索",
  "filter": "検索範囲",
  "range": "検索範囲",
  "script": "スクリプト",
  "form": "フォーム",
  "process": "プロセス",
  "page": "ページ",
  "widget": "ウィジェット",
  "view": "ビュー",
  "statement": "クエリ ステートメント",
  "stat": "統計",
  "property": "プロパティ",
  "value": "値",
  "processPlatform": "プロセス プラットフォーム",
  "cms": "コンテンツ管理",
  "portal": "ポータル管理",
  "query": "データセンター",
  "service": "サービス管理",
  "search_placeholder": "検索内容を入力してください",
  "dockToBottom": "下部に固定",
  "dockToRight": "右側に固定",
  "nothingFind": "結果が見つかりません。検索条件を変更してください",
  "nothingFind_keyword": "結果が見つかりません\n検索キーワードを入力してください",
  "nothingFind_noFilter": "結果が見つかりません\n検索タイプを選択してください",
  "nothingFind_noRange": "結果が見つかりません\n検索範囲を確認してください",
  "nothingPreview": "検索結果リストを選択すると、ここでプレビューできます",
  "selectRange": "範囲選択",
  "patternCount": "{n} 項目一致",
  "receiveToFind": "データ検索の準備中...",
  "readyToFind": "デザイン要素が準備完了（合計{n}個）...",
  "findPatternCount": "{n} 項目見つかりました",
  "findPatternCountCompleted": "検索完了、{n} 項目見つかりました",
  "elementPattern": "<b>要素:</b> {element}, <b>プロパティ:</b> {property}: ",
  "element": "要素",
  "saveDesigner": "デザイン要素を保存",
  "openDesigner": "アプリを開く",
  "findInfor": "このデザイン要素で一致する項目が見つかりました:",
  "findInforOpen": "デザイン要素を開くにはここをクリックしてください",
  "notice": {
    "save_success": "保存しました！"
  }
};
