MWF.xApplication.FindDesigner.LP = {
	"title": "디자인 중 찾기",
  "filter": "디자인 검색",
  "range": "검색 범위",
  "script": "스크립트",
  "form": "양식",
  "process": "프로세스",
  "page": "페이지",
  "widget": "위젯",
  "view": "뷰",
  "statement": "쿼리 문장",
  "stat": "통계",
  "property": "속성",
  "value": "값",
  "processPlatform": "프로세스 플랫폼",
  "cms": "콘텐츠 관리",
  "portal": "포털 관리",
  "query": "데이터 센터",
  "service": "서비스 관리",
  "search_placeholder": "검색 내용을 입력하세요",
  "dockToBottom": "하단에 고정",
  "dockToRight": "우측에 고정",
  "nothingFind": "결과를 찾을 수 없습니다. 검색 조건을 수정하세요.",
  "nothingFind_keyword": "결과를 찾을 수 없습니다.\n검색 키워드를 입력하세요",
  "nothingFind_noFilter": "결과를 찾을 수 없습니다.\n검색 유형을 선택하세요",
  "nothingFind_noRange": "결과를 찾을 수 없습니다.\n검색 범위를 확인하세요",
  "nothingPreview": "결과 목록을 선택하면 여기에서 미리보기할 수 있습니다",
  "selectRange": "범위 선택",
  "patternCount": "{n} 항목 일치",
  "receiveToFind": "데이터 검색 준비 중...",
  "readyToFind": "디자인 요소가 준비되었습니다 (총 {n}개)...",
  "findPatternCount": "{n} 항목 찾음",
  "findPatternCountCompleted": "검색 완료, {n} 항목 찾음",
  "elementPattern": "<b>요소:</b> {element}, <b>속성:</b> {property}: ",
  "element": "요소",
  "saveDesigner": "디자인 요소 저장",
  "openDesigner": "응용 프로그램 열기",
  "findInfor": "이 디자인 요소에서 일치하는 항목을 찾았습니다:",
  "findInforOpen": "디자인 요소를 열려면 여기를 클릭하세요",
  "notice": {
    "save_success": "저장되었습니다!"
  }
};
