MWF.xApplication.FindDesigner.LP = {
	"title": "在設計中搜尋",
  "filter": "在設計中搜尋",
  "range": "搜尋範圍",
  "script": "腳本",
  "form": "表單",
  "process": "流程",
  "page": "頁面",
  "widget": "元件",
  "view": "視圖",
  "statement": "查詢語句",
  "stat": "統計",
  "property": "屬性",
  "value": "值",
  "processPlatform": "流程平台",
  "cms": "內容管理",
  "portal": "門戶管理",
  "query": "資料中心",
  "service": "服務管理",
  "search_placeholder": "輸入查詢內容",
  "dockToBottom": "固定到底部",
  "dockToRight": "固定到右側",
  "nothingFind": "未找到任何結果，請修改查詢條件。",
  "nothingFind_keyword": "未找到任何結果\n請輸入查詢關鍵詞",
  "nothingFind_noFilter": "未找到任何結果\n請選擇查詢類型",
  "nothingFind_noRange": "未找到任何結果\n請確定查詢範圍",
  "nothingPreview": "選擇查找結果列表，可在此處預覽",
  "selectRange": "選擇查找範圍",
  "patternCount": "{n} 項匹配",
  "receiveToFind": "準備查詢數據中...",
  "readyToFind": "設計元素準備完畢（共{n}個）...",
  "findPatternCount": "已找到{n}項匹配",
  "findPatternCountCompleted": "查詢完畢，已找到{n}項匹配",
  "elementPattern": "<b>元素:</b> {element}, <b>屬性:</b> {property}: ",
  "element": "元素",
  "saveDesigner": "保存設計元素",
  "openDesigner": "打開應用",
  "findInfor": "您在此設計元素中找到匹配項目：",
  "findInforOpen": "請點擊此處開打設計元素",
  "notice": {
    "save_success": "保存成功。"
  }
};
