/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.calendar.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.calendar.core.entity.Calendar_SettingLobValue.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:22 CST 2018")
public class Calendar_SettingLobValue_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Calendar_SettingLobValue,String> id;
    public static volatile SingularAttribute<Calendar_SettingLobValue,String> lobValue;
}
