/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.calendar.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.calendar.core.entity.Calendar.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:22 CST 2018")
public class Calendar_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Calendar,String> color;
    public static volatile SingularAttribute<Calendar,String> createor;
    public static volatile SingularAttribute<Calendar,String> description;
    public static volatile ListAttribute<Calendar,String> followers;
    public static volatile SingularAttribute<Calendar,String> id;
    public static volatile SingularAttribute<Calendar,Boolean> isPublic;
    public static volatile ListAttribute<Calendar,String> manageablePersonList;
    public static volatile SingularAttribute<Calendar,String> name;
    public static volatile ListAttribute<Calendar,String> publishableGroupList;
    public static volatile ListAttribute<Calendar,String> publishablePersonList;
    public static volatile ListAttribute<Calendar,String> publishableUnitList;
    public static volatile SingularAttribute<Calendar,String> source;
    public static volatile SingularAttribute<Calendar,String> status;
    public static volatile SingularAttribute<Calendar,String> target;
    public static volatile SingularAttribute<Calendar,String> type;
    public static volatile ListAttribute<Calendar,String> viewableGroupList;
    public static volatile ListAttribute<Calendar,String> viewablePersonList;
    public static volatile ListAttribute<Calendar,String> viewableUnitList;
}
