/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.calendar.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.calendar.core.entity.Calendar_Event.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:22 CST 2018")
public class Calendar_Event_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Calendar_Event,Boolean> alarm;
    public static volatile SingularAttribute<Calendar_Event,Boolean> alarmAlready;
    public static volatile SingularAttribute<Calendar_Event,Date> alarmTime;
    public static volatile SingularAttribute<Calendar_Event,String> bundle;
    public static volatile SingularAttribute<Calendar_Event,String> calendarId;
    public static volatile SingularAttribute<Calendar_Event,String> color;
    public static volatile SingularAttribute<Calendar_Event,String> comment;
    public static volatile SingularAttribute<Calendar_Event,String> createPerson;
    public static volatile SingularAttribute<Calendar_Event,Integer> daysOfDuration;
    public static volatile SingularAttribute<Calendar_Event,Date> endTime;
    public static volatile SingularAttribute<Calendar_Event,String> endTimeStr;
    public static volatile SingularAttribute<Calendar_Event,String> eventType;
    public static volatile SingularAttribute<Calendar_Event,String> id;
    public static volatile SingularAttribute<Calendar_Event,Boolean> isAllDayEvent;
    public static volatile SingularAttribute<Calendar_Event,Boolean> isPublic;
    public static volatile SingularAttribute<Calendar_Event,String> latitude;
    public static volatile SingularAttribute<Calendar_Event,String> locationName;
    public static volatile SingularAttribute<Calendar_Event,String> longitude;
    public static volatile ListAttribute<Calendar_Event,String> manageablePersonList;
    public static volatile ListAttribute<Calendar_Event,String> participants;
    public static volatile SingularAttribute<Calendar_Event,String> recurrenceExc;
    public static volatile SingularAttribute<Calendar_Event,String> recurrenceRule;
    public static volatile SingularAttribute<Calendar_Event,String> repeatMasterId;
    public static volatile SingularAttribute<Calendar_Event,String> source;
    public static volatile SingularAttribute<Calendar_Event,Date> startTime;
    public static volatile SingularAttribute<Calendar_Event,String> startTimeStr;
    public static volatile SingularAttribute<Calendar_Event,String> targetType;
    public static volatile SingularAttribute<Calendar_Event,String> title;
    public static volatile SingularAttribute<Calendar_Event,String> updatePerson;
    public static volatile SingularAttribute<Calendar_Event,String> valarmTime_config;
    public static volatile SingularAttribute<Calendar_Event,String> valarm_Summary;
    public static volatile SingularAttribute<Calendar_Event,String> valarm_description;
    public static volatile SingularAttribute<Calendar_Event,String> valarm_mailto;
    public static volatile ListAttribute<Calendar_Event,String> viewableGroupList;
    public static volatile ListAttribute<Calendar_Event,String> viewablePersonList;
    public static volatile ListAttribute<Calendar_Event,String> viewableUnitList;
}
