MWF.xApplication.TeamWork.LP = {
	"title": "TeamWork",
	"ProjectList":{
		"navi":{
			"title":"TeamWork",
			"newItem":"新建项目",
			"allItem":"全部项目",
			"starItem":"我的星标",
			"myItem":"我的项目",
			"unGroupItem":"未分组项目",
			"completeItem":"已完成项目",
			"historyItem":"已归档项目",
			"removeItem":"回收站",
			"groupMenu":"项目分组",
			"groupItemName":"项目分组名称",
			"unname":"未命名",
			"addGroup":"新建项目分组"
		},
		"newProject":{
			"title":"创建项目",
			"name":"项目名称",
			"description":"项目简介",
			"group":"项目分组",
			"add":"创建"
		},
		"content":{
			"addProjectBlockText":"创建新项目",
			"addProjectListText":"创建新项目",
			"listTip":"列表视图",
			"blockTip":"卡片视图"
		}
	},
	"newProject":{
		"title":"创建项目",
		"name":"项目名称",
		"description":"项目简介",
		"group":"项目分组",
		"add":"创建"
	},
	"projectSetting":{
		"title":"项目设置",
		"projectSettingBgText":"项目封面",
		"upload":"上传新封面",
		"projectTitle":"项目名称",
		"projectGroup":"项目分组",
		"projectDes":"项目简介",
		"confirm":"确定",
		"close":"取消"
	},
	"project":{
		"backProject":"返回项目",
		"starItem":"我的星标",
		"allItem":"所有项目",
		"task":"任务",
		"stat":"统计",
		"menu":"菜单",
		"searchTask":"任务搜索",
		"myTask":"我的任务",
		"taskAdd":"新建任务",
		"taskCompleteText":"已完成",
		"taskovertimeText":"已超时",
		"viewTitle":"视图",
		"viewAdd":"新建视图",
		"viewItemAll":"所有工作",
		"viewItemMy":"我负责的任务",
		"viewItemFlow":"未完成的任务",
		"viewItemComplete":"已完成的任务",
		"viewItemOver":"逾期的任务",

		"viewRemove":"删除视图",
		"viewEdit":"编辑视图",

		"newTaskTitle":"新建任务",
		"newTaskPlaceholder":"输入任务名称",
		"newTaskOk":"确定",
		"newTaskClose":"取消"
	},
	"uploadImage":{
		"okBtn":"确定",
		"closeBtn":"取消"
	},
	"task":{
		"newTask":"新建任务",
		"close":"关闭",
		"save":"保存",
		"taskName":"名称",
		"taskNamePlaceholder":"输入任务名称",
		"taskStatus":"状态",
		"taskDuty":"负责人",
		"addDuty":"待确认",
		"taskTime":"时间",
		"taskTimeStart":"设置开始时间",
		"taskTimeEnd":"设置结束时间",
		"taskPriority":"优先级",
		"taskReader":"参与者",
		"taskRemark":"备注",
		"status":{
			"draft":"草稿",
			"flow":"未完成",
			"complete":"已完成",
			"archive":"已归档"
		}
	},
	common:{
		tooltip:{
			group:{
				topText:"新建分组",
				topTextEdit:"编辑分组",
				groupText:"分组名称",
				groupTextTip:"输入分组名称",
				groupIn:"分组名称",
				groupAdd:"确定"
			},
			groupSelect:{
				"name":"项目分组",
				"groupIn":"搜索分组",
				"select":"常用分组",
				"add":"创建项目分组",
				"newGroup":"新建分组",
				"groupTextTip":"输入分组名称",
				"confirm":"确定"
			}
		},
		confirm:{
			"removeTitle":"删除",
			"removeContent":"确认删除？"
		}
	}
};