MWF.xApplication.TeamWork.LP = {
	"title": "TeamWork",
	"ProjectList":{
		"navi":{
			"title":"TeamWork",
			"newItem":"新建项目",
			"allItem":"全部项目",
			"starItem":"我的星标",
			"myItem":"我的项目",
			"unGroupItem":"未分组项目",
			"completeItem":"已完成项目",
			"historyItem":"已归档项目",
			"removeItem":"回收站",
			"groupMenu":"项目分组",
			"groupItemName":"项目分组名称",
			"unname":"未命名",
			"addGroup":"新建项目分组"
		},
		"newProject":{
			"title":"创建项目",
			"name":"项目名称",
			"description":"项目简介",
			"group":"项目分组",
			"add":"创建"
		},
		"content":{
			"addProjectBlockText":"创建新项目",
			"addProjectListText":"创建新项目",
			"listTip":"列表视图",
			"blockTip":"卡片视图"
		}
	},
	"newProject":{
		"title":"创建项目",
		"name":"项目名称",
		"description":"项目简介",
		"group":"项目分组",
		"add":"创建"
	},
	"projectSetting":{
		"general":"概述",
		"customField":"自定义字段",
		"title":"项目设置",
		"projectSettingBgText":"项目封面",
		"upload":"上传新封面",
		"projectTitle":"项目名称",
		"projectGroup":"项目分组",
		"projectDes":"项目简介",
		"confirm":"确定",
		"close":"取消",
		"customTip":"任务的自定义字段",
		"customNew":"新建字段",
		"edit":"编辑",
		"remove":"删除",
		"description":"描述",
		"updateTime":"最后更新时间",
		"option":"选项"
	},
	"extField":{
		"field":"字段",
		"newTip":"新建字段",
		"name":"名称",
		"description":"描述",
		"type":"类型",
		"option":"选项",
		"radio":"单选",
		"checkbox":"多选",
		"date":"日期",
		"datetime":"时间",
		"text":"文本",
		"richtext":"长文本",
		"identity":"人员",
		"unit":"组织",
		"notEmpty":"该字段不能为空",
		"confirm":"确定"
	},
	"project":{
		"backProject":"返回项目",
		"starItem":"我的星标",
		"allItem":"所有项目",
		"task":"任务",
		"stat":"统计",
		"menu":"菜单",
		"setting":"设置",
		"searchTask":"任务搜索",
		"myTask":"我的任务",
		"taskAdd":"新建任务",
		"taskCompleteText":"已完成",
		"taskovertimeText":"已超时",
		"viewTitle":"视图",
		"viewAdd":"新建视图",
		"viewItemAll":"所有工作",
		"viewItemMy":"我负责的任务",
		"viewItemFlow":"未完成的任务",
		"viewItemComplete":"已完成的任务",
		"viewItemOver":"逾期的任务",

		"view":"视图",
		"viewRemove":"删除视图",
		"viewEdit":"编辑视图",

		"taskGroup":"任务列表",
		"taskGroupAdd":"新建任务列表",
		"taskGroupEdit":"编辑任务列表",
		"taskGroupRemove":"删除任务列表",

		"normal":"普通",
		"urgency":"紧急",
		"emergency":"特急",

		"newTaskTitle":"新建任务",
		"newTaskPlaceholder":"输入任务名称",
		"newTaskOk":"确定",
		"newTaskClose":"取消"
	},
	"uploadImage":{
		"okBtn":"确定",
		"closeBtn":"取消"
	},
	"task":{
		"newTask":"新建任务",
		"taskBelongText":"属于任务",
		"close":"关闭",
		"cancel":"取消",
		"save":"保存",
		"taskName":"名称",
		"taskNamePlaceholder":"输入任务名称",
		"taskSubNamePlaceholder":"输入子任务名称",
		"taskSubDes":"点击打开详情",
		"taskStatus":"状态",
		"taskDuty":"负责人",
		"addDuty":"待确认",
		"taskTime":"时间",
		"taskTimeStart":"设置开始时间",
		"taskTimeEnd":"设置结束时间",
		"taskPriority":"优先级",
		"taskTag":"标签",
		"taskTagAddText":"添加标签",
		"taskAttachment":"附件",
		"taskSubName":"子任务",
		"taskSubText":"添加子任务",
		"taskReader":"参与者",
		"taskReaderAdd":"添加参与者",
		"taskRemark":"备注",
		"editTip":"点击编辑",
		"taskMenu":"任务菜单",
		"taskCopy":"复制任务",
		"taskMove":"转移任务",
		"taskRemove":"删除任务",
		"taskFav":"收藏任务",
		"taskSub":"转化为子任务",
		"status":{
			"draft":"草稿",
			"flow":"未完成",
			"processing":"执行中",
			"completed":"已完成",
			"archived":"已归档"
		},
		"priority":{
			"normal":"普通",
			"urgency":"紧急",
			"emergency":"特急"
		},
		"dynamicAll":"所有动态",
		"dynamicAttachment":"仅附件",
		"dynamicChat":"仅评论",
		"chatInsertEmoji":"插入表情",
		"chatSend":"发送",
		"chatPlaceholder":"按Ctrl+Enter快速发布"
	},
	"taskTag":{
		"search":"搜索",
		"taskTagSearch":"搜索标签",
		"taskTagNone":"暂无标签",
		"taskAdd":"新建标签",
		"taskEdit":"编辑标签",
		"tagAdd":"创建",
		"tagRemove":"删除",
		"tagSave":"保存"
	},
	"taskAttachmentList":{
		"attachment":"附件",
		"attachmentMenu":"附件菜单",
		"attachmentAdd":"添加附件",
		"attachmentDetails":"详情",
		"attachmentDownload":"下载",
		"attachmentRemove":"删除"

	},
	"emoji":{
		"aixin":"爱心",
		"baiyan":"白眼",
		"ziya":"呲牙",
		"dajing":"大惊",
		"danao":"大闹",
		"daxiao":"大笑",
		"dianzan":"点赞",
		"fadai":"发呆",
		"fankun":"犯困",
		"feiwen":"飞吻",
		"fendou":"奋斗",
		"fennu":"愤怒",
		"ganga":"尴尬",
		"hanyan":"汗颜",
		"kaixin":"开心",
		"liuhan":"流汗",
		"liulei":"流泪",
		"shenme":"什么",
		"xihuan":"喜欢",
		"kuxiao":"哭笑",
		"xiaolian":"笑脸",
		"xinsui":"心碎",
		"zhadan":"炸弹"
	},
	"taskSub":{
		"title":"转换为子任务",
		"searchPlace":"按回车搜索",
		"ok":"确定"
	},
	"taskMove":{
		"title":"转移任务",
		"searchPlace":"按回车搜索",
		"ok":"确定"
	},
	"stat":{

	},
	"common":{
		"tooltip":{
			"group":{
				"topText":"新建分组",
				"topTextEdit":"编辑分组",
				"groupText":"分组名称",
				"groupTextTip":"输入分组名称",
				"groupIn":"分组名称",
				"groupAdd":"确定"
			},
			"groupSelect":{
				"name":"项目分组",
				"groupIn":"搜索分组",
				"select":"常用分组",
				"add":"创建项目分组",
				"newGroup":"新建分组",
				"groupTextTip":"输入分组名称",
				"confirm":"确定"
			}
		},
		"confirm":{
			"removeTitle":"删除",
			"removeContent":"确认删除？",
			"replaceTitle":"替换",
			"replaceContent":"确认替换？"
		}
	}
};