MWF.xApplication.Homepage.LP = o2.HPLP = {
	"title": "Homepage",
	"myTask": "Task",
	"myTaskCompleted": "Task Completed",
	"myRead": "Read",
	"myReadCompleted": "Read Completed",
	"myDraft": "My Draft",
	"myProcessDraft": "Draft",
	"startProcess": "Start process",
	"noSubject": "Untitled",
	"noWork": "No Documentation",
	"noHotpic": "No hot news at the moment",
	"noInforItem": "No information temporarily",
	"noCalendar": "No schedule on the day",
	"noFile": "Click here to visit the Enterprise Network Disk",
	"moreInfor": "More...",
	"allInfor": "Latest news",
	"moreMeeting": "More...",
	"moreFile": "More...",
	"myMeeting": "My Meetings",
	"myFile": "Netdisk File",
	"myMeetingInvited": "Invitation",
	"myCalender": "Schedule",
	"moreCalender": "More...",
	"calender": "Schedule",
	"noMeeting": "No meetings in the near future",
	"meetingTime": "Meeting Time",
	"meetingLocation": "Meeting Place",
	"accepted": "Accepted",
	"rejected": "Rejected",
	"accept": "Accept",
	"reject": "Reject",
	"acceptConfirmTitle": "Attend the meeting confirmation",
	"acceptConfirm": "Are you sure you want to attend the \"{name}\" meeting?",
	"rejectConfirmTitle": "Decline meeting confirmation",
	"rejectConfirm": "Are you sure you refuse to attend the \"{name}\" meeting?",


	"prevPage": "Previous",
	"nextPage": "Next",
	"nextActivity": "Flow to the next step",
	"completedActivityName": "Process Completed",

	"taskStartTime": "Received Task Time",
	"taskCompletedTime": "Task Processing Time",
	"readStartTime": "Received Read Time",
	"readCompletedTime": "Read Processing Time",
	"readActivity": "Read Activity",
	"draftTime": "Drafting time",
	"draftUser": "Creator",
	"currentActivity": "Current Activity",
	"taskRoute": "Route",
	"currentUser": "Current Processor",
	"publishTime": "Publish time",
	"publishPerson": "Publisher",

	"download": "download",
	"today": "today",
	"allDay": "All Day",
	"calenderInfor": "Hello {name}! {date} You have<div class='o2_homepage_calender_count_flag'>{count}</div>schedules.",
	"noCalenderInfor": "Hello {name}! {date} no schedule。",
	"dateFormat": "%m %d, %Y"
};
