MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.Homepage = MWF.xApplication.Homepage || {};
MWF.xApplication.Homepage.LP={
	"title": "Inicio",
	"myTask": "Pendiente",
	"myTaskCompleted": "Completado",
	"myRead": "Lecturas",
	"myReadCompleted": "Leído",
	"myDraft": "Borradores",
	"myProcessDraft": "Redacción",
	"startProcess": "Crear tarea",
	"noSubject": "Sin título",
	"noWork": "No hay trabajo por el momento",
	"noHotpic": "No hay noticias destacadas por el momento",
	"noInforItem": "No hay información por el momento",
	"noCalendar": "No hay eventos en el calendario de hoy",
	"noFile": "Haga clic aquí para acceder a la nube",
	"moreInfor": "Más",
	"allInfor": "Novedades",
	"moreMeeting": "Más",
	"moreFile": "Más",
	"myMeeting": "Mis reuniones",
	"myFile": "Netdisk archivo",
	"myMeetingInvited": "Invitaciones a reuniones",
	"myCalender": "Mi calendario",
	"moreCalender": "Más",
	"calender": "Calendario",
	"noMeeting": "No hay reuniones próximas",
	"meetingTime": "Hora de la reunión",
	"meetingLocation": "Ubicación de la reunión",
	"meetingLink": "Enlace de la reunión",
	"meetingNumber": "Número de reunión",
	"clickOpen": "Haga clic para abrir",
	"accepted": "Aceptado",
	"rejected": "Rechazado",
	"accept": "Aceptar",
	"reject": "Rechazar",
	"acceptConfirmTitle": "Confirmación de asistencia a la reunión",
	"acceptConfirm": "¿Está seguro de que desea asistir a la reunión \"{name}\"?",
	"rejectConfirmTitle": "Confirmación de rechazo de la reunión",
	"rejectConfirm": "¿Está seguro de que desea rechazar la reunión \"{name}\"?",
	"prevPage": "Página anterior",
	"nextPage": "Siguiente página",
	"nextActivity": "Avanzar al siguiente paso",
	"completedActivityName": "Flujo de trabajo completado",
	"taskStartTime": "Hora de recepción de la tarea pendiente",
	"taskCompletedTime": "Hora en que se procesó la tarea completada",
	"readStartTime": "Hora de recepción de la lectura pendiente",
	"readCompletedTime": "Hora en que se procesó la lectura pendiente",
	"readActivity": "Actividad de lectura pendiente",
	"draftTime": "Hora de creación del borrador",
	"draftUser": "Creador del borrador",
	"currentActivity": "Actividad actual",
	"taskRoute": "Ruta de ejecución",
	"currentUser": "Persona que está procesando actualmente",
	"publishTime": "Hora de publicación",
	"publishPerson": "Persona que publicó",
	"download": "Descargar",
	"today": "Hoy",
	"allDay": "Todo el día",
	"calenderInfor": "{name}, ¡Hola! Tiene <div class='o2_homepage_calender_count_flag'>{count}</div> eventos programados para el {date}.",
	"noCalenderInfor": "{name}, ¡Hola! No hay eventos programados para el {date}.",
	"dateFormat": "%d de %m de %Y"
}
MWF.xApplication.Homepage["lp."+o2.language] = MWF.xApplication.Homepage.LP