MWF.xApplication.Homepage.LP = o2.HPLP = {
	"title": "ホーム",
	"myTask": "未処理",
	"myTaskCompleted": "処理済み",
	"myRead": "未読",
	"myReadCompleted": "既読",
	"myDraft": "下書き",
	"myProcessDraft": "進行中",
	"startProcess": "プロセス開始",
	"noSubject": "タイトルなし",
	"noWork": "現在の仕事なし",
	"noHotpic": "ホットニュースはありません",
	"noInforItem": "情報はありません",
	"noCalendar": "今日のスケジュールはありません",
	"noFile": "ここをクリックしてファイルにアクセス",
	"moreInfor": "詳細情報",
	"allInfor": "最新情報",
	"moreMeeting": "もっと会議",
	"moreFile": "もっとファイル",
	"myMeeting": "私の会議",
	"myFile": "ファイルストレージ",
	"myMeetingInvited": "招待された会議",
	"myCalender": "私のスケジュール",
	"moreCalender": "もっとスケジュール",
	"calender": "スケジュール管理",
	"noMeeting": "近日の会議はありません",
	"meetingTime": "会議時間",
	"meetingLocation": "会議場所",
	"meetingLink": "会議リンク",
	"meetingNumber": "会議番号",
	"clickOpen": "クリックして開く",
	"accepted": "受け入れ済み",
	"rejected": "拒否済み",
	"accept": "受け入れる",
	"reject": "拒否する",
	"acceptConfirmTitle": "会議参加確認",
	"acceptConfirm": "“{name}” 会議に参加しますか？",
	"rejectConfirmTitle": "会議拒否確認",
	"rejectConfirm": "“{name}” 会議への参加を拒否しますか？",


	"prevPage": "前のページ",
	"nextPage": "次のページ",
	"nextActivity": "次のステップに進む",
	"completedActivityName": "完了したアクティビティ",

	"taskStartTime": "未処理タスク受信時間",
	"taskCompletedTime": "処理済みタスク時間",
	"readStartTime": "未読タスク受信時間",
	"readCompletedTime": "既読タスク時間",
	"readActivity": "未読アクティビティ",
	"draftTime": "下書き時間",
	"draftUser": "下書き作成者",
	"currentActivity": "現在のアクティビティ",
	"taskRoute": "実行ルート",
	"currentUser": "現在の処理担当者",
	"publishTime": "発行時間",
	"publishPerson": "発行者",

	"download": "ダウンロード",
	"today": "今日",
	"allDay": "終日",
	"calenderInfor": "{name}こんにちは！{date}に予定が<div class='o2_homepage_calender_count_flag'>{count}</div>つあります。",
	"noCalenderInfor": "{name}さん、こんにちは！{date}にスケジュールはありません。",
	"dateFormat": "%Y年%m月%d日"

};
