MWF.xApplication.Homepage.LP = o2.HPLP = {
	"title": "홈",
	"myTask": "미처리",
	"myTaskCompleted": "처리됨",
	"myRead": "미확인",
	"myReadCompleted": "확인됨",
	"myDraft": "작성중",
	"myProcessDraft": "작업중",
	"startProcess": "프로세스 시작",
	"noSubject": "제목 없음",
	"noWork": "현재 작업 없음",
	"noHotpic": "현재 핫뉴스 없음",
	"noInforItem": "현재 정보 없음",
	"noCalendar": "오늘 일정 없음",
	"noFile": "여기를 클릭하여 파일에 액세스",
	"moreInfor": "더 많은 정보",
	"allInfor": "최신 정보",
	"moreMeeting": "더 많은 회의",
	"moreFile": "더 많은 파일",
	"myMeeting": "내 회의",
	"myFile": "파일 보관함",
	"myMeetingInvited": "초대된 회의",
	"myCalender": "내 일정",
	"moreCalender": "더 많은 일정",
	"calender": "일정 관리",
	"noMeeting": "최근 회의 없음",
	"meetingTime": "회의 시간",
	"meetingLocation": "회의 장소",
	"meetingLink": "회의 링크",
	"meetingNumber": "회의 번호",
	"clickOpen": "열기",
	"accepted": "수락됨",
	"rejected": "거절됨",
	"accept": "수락",
	"reject": "거절",
	"acceptConfirmTitle": "회의 참석 확인",
	"acceptConfirm": "“{name}” 회의에 참석하시겠습니까?",
	"rejectConfirmTitle": "회의 거절 확인",
	"rejectConfirm": "“{name}” 회의 참석을 거절하시겠습니까?",


	"prevPage": "이전 페이지",
	"nextPage": "다음 페이지",
	"nextActivity": "다음 단계로 진행",
	"completedActivityName": "완료된 활동",

	"taskStartTime": "미처리 작업 수신 시간",
	"taskCompletedTime": "처리된 작업 시간",
	"readStartTime": "미확인 작업 수신 시간",
	"readCompletedTime": "확인된 작업 시간",
	"readActivity": "미확인 활동",
	"draftTime": "작성 시간",
	"draftUser": "작성자",
	"currentActivity": "현재 활동",
	"taskRoute": "수행 경로",
	"currentUser": "현재 처리자",
	"publishTime": "발행 시간",
	"publishPerson": "발행자",

	"download": "다운로드",
	"today": "오늘",
	"allDay": "하루 종일",
	"calenderInfor": "{name}님, 안녕! {date}에 <div class='o2_homepage_calender_count_flag'>{count}</div>개의 일정이 있습니다.",
	"noCalenderInfor": "{name}님, 안녕하세요! {date}에 일정이 없습니다.",
	"dateFormat": "%Y년 %m월 %d일"

};
