MWF.xApplication.Homepage.LP = o2.HPLP = {
	"title": "首页",
	"myTask": "待办",
	"myTaskCompleted": "已办",
	"myRead": "待阅",
	"myReadCompleted": "已阅",
	"myDraft": "拟稿",
	"myProcessDraft": "草稿",
	"startProcess": "发起流程",
	"noSubject": "无标题",
	"noWork": "暂时没有工作",
	"noHotpic": "暂时没有热点新闻",
	"noInforItem": "暂时没有信息",
	"noCalendar": "当天没有日程",
	"noFile": "点击此处访问企业网盘",
	"moreInfor": "更多信息",
	"allInfor": "最新信息",
	"moreMeeting": "更多会议",
	"moreFile": "更多文件",
	"myMeeting": "我的会议",
	"myFile": "网盘文件",
	"myMeetingInvited": "会议邀请",
	"myCalender": "我的日程",
	"moreCalender": "更多日程",
	"calender": "日程管理",
	"noMeeting": "近期没有会议",
	"meetingTime": "会议时间",
	"meetingLocation": "会议地点",
	"accepted": "已接受",
	"rejected": "已拒绝",
	"accept": "接受",
	"reject": "拒绝",
	"acceptConfirmTitle": "参加会议确认",
	"acceptConfirm": "您确定要参加”{name}“会议吗？",
	"rejectConfirmTitle": "拒绝会议确认",
	"rejectConfirm": "您确定拒绝参加”{name}“会议吗？",


	"prevPage": "上一页",
	"nextPage": "下一页",
	"nextActivity": "流转到下一步",
	"completedActivityName": "流转完成",

	"taskStartTime": "收到待办时间",
	"taskCompletedTime": "已办处理时间",
	"readStartTime": "收到待阅时间",
	"readCompletedTime": "待阅处理时间",
	"readActivity": "待阅活动",
	"draftTime": "拟稿时间",
	"draftUser": "拟稿人",
	"currentActivity": "当前活动",
	"taskRoute": "执行的路由",
	"currentUser": "当前处理人",
	"publishTime": "发布时间",
	"publishPerson": "发布人",

	"download": "下载",
	"today": "今日",
	"allDay": "全天",
	"calenderInfor": "{name}，您好！{date}您有<div class='o2_homepage_calender_count_flag'>{count}</div>个日程。",
	"noCalenderInfor": "{name}，您好！{date}无日程。",
	"dateFormat": "%Y年%m月%d日"

};
