MWF.xApplication.Homepage.LP = o2.HPLP = {
	"title": "首頁",
	"myTask": "待辦",
	"myTaskCompleted": "已辦",
	"myRead": "待閱",
	"myReadCompleted": "已閱",
	"myDraft": "草稿",
	"myProcessDraft": "工作中",
	"startProcess": "發起流程",
	"noSubject": "無標題",
	"noWork": "暫無工作",
	"noHotpic": "暫無熱門新聞",
	"noInforItem": "暫無信息",
	"noCalendar": "當天無日程",
	"noFile": "點擊此處訪問網盤",
	"moreInfor": "更多信息",
	"allInfor": "最新信息",
	"moreMeeting": "更多會議",
	"moreFile": "更多文件",
	"myMeeting": "我的會議",
	"myFile": "網盤文件",
	"myMeetingInvited": "會議邀請",
	"myCalender": "我的日程",
	"moreCalender": "更多日程",
	"calender": "日程管理",
	"noMeeting": "近期無會議",
	"meetingTime": "會議時間",
	"meetingLocation": "會議地點",
	"meetingLink": "會議鏈接",
	"meetingNumber": "會議號碼",
	"clickOpen": "點擊打開",
	"accepted": "已接受",
	"rejected": "已拒絕",
	"accept": "接受",
	"reject": "拒絕",
	"acceptConfirmTitle": "參加會議確認",
	"acceptConfirm": "您確定要參加“{name}”會議嗎？",
	"rejectConfirmTitle": "拒絕會議確認",
	"rejectConfirm": "您確定拒絕參加“{name}”會議嗎？",


	"prevPage": "上一頁",
	"nextPage": "下一頁",
	"nextActivity": "流轉到下一步",
	"completedActivityName": "流轉完成",

	"taskStartTime": "收到待辦時間",
	"taskCompletedTime": "已辦處理時間",
	"readStartTime": "收到待閱時間",
	"readCompletedTime": "待閱處理時間",
	"readActivity": "待閱活動",
	"draftTime": "草稿時間",
	"draftUser": "草稿人",
	"currentActivity": "當前活動",
	"taskRoute": "執行的路由",
	"currentUser": "當前處理人",
	"publishTime": "發佈時間",
	"publishPerson": "發佈人",

	"download": "下載",
	"today": "今日",
	"allDay": "全天",
	"calenderInfor": "{name}，您好！{date}您有<div class='o2_homepage_calender_count_flag'>{count}</div>個日程。",
	"noCalenderInfor": "{name}，您好！{date}無日程。",
	"dateFormat": "%Y年%m月%d日"

};
