/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.collaboration.core.entity;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.collaboration.core.entity.Dialog.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Sun Sep 02 18:43:31 CST 2018")
public class Dialog_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Dialog,Boolean> arrived;
    public static volatile SingularAttribute<Dialog,String> body;
    public static volatile SingularAttribute<Dialog,String> from;
    public static volatile SingularAttribute<Dialog,String> id;
    public static volatile SingularAttribute<Dialog,String> person;
}
