MWF.xApplication = MWF.xApplication || {};
MWF.xApplication.query = MWF.xApplication.query || {};
MWF.xApplication.query.Query = MWF.xApplication.query.Query || {};
MWF.xApplication.query.Query.LP={
	"title": "Aplicación de datos",
	"searchKey": "Ingrese la palabra clave",
	"all": "Todos",
	"filter": "Filtrar",
	"ok": "Aceptar",
	"cancel": "Cancelar",
	"clear": "Borrar",
	"exportExcel": "Exportar a Excel",
	"noDescription": "Descripción no definida",
	"view": "Vista",
	"stat": "Estadísticas",
	"statement": "Consulta",
	"importer": "Importador",
	"customSearch": "Búsqueda avanzada",
	"searchKeywork": "Ingrese la palabra clave para buscar en la vista",
	"yes": "Sí",
	"no": "No",
	"and": "Y",
	"or": "O",
	"form": {
		"exportExcel": "Exportar a Excel"
	},
	"chart": {
		"bar": "Gráfico de barras",
		"pie": "Gráfico circular",
		"line": "Gráfico de línea",
		"rowToColumn": "Convertir filas en columnas"
	},
	"textFilter": {
		"equals": "Igual a",
		"notEquals": "No igual a",
		"like": "Coincide con",
		"notLike": "No coincide con"
	},
	"numberFilter": {
		"equals": "Igual a",
		"notEquals": "No igual a",
		"greaterThan": "Mayor que",
		"greaterThanOrEqualTo": "Mayor o igual que",
		"lessThan": "Menor que",
		"lessThanOrEqualTo": "Menor o igual que"
	},
	"dateFilter": {
		"equals": "Igual a",
		"notEquals": "No igual a",
		"greaterThan": "Mayor que",
		"lessThan": "Menor que"
	},
	"dateTimeFilter": {
		"greaterThan": "Mayor que",
		"lessThan": "Menor que"
	},
	"booleanFilter": {
		"equals": "Igual a",
		"notEquals": "No igual a"
	},
	"filterErrorTitle": "Seleccione el campo de búsqueda",
	"filterErrorComparison": "Seleccione el operador de comparación",
	"filterErrorValue": "Ingrese el valor de comparación",
	"workTitle": "Título",
	"activity": "Actividad",
	"status": "Estado",
	"action": "Acción",
	"person": "Redactor",
	"expire": "Tiempo de expiración",
	"noExpire": "Ninguno",
	"expired": "Expirado",
	"notExpired": "No expirado",
	"completedTime": "Hora de finalización",
	"process": "Proceso",
	"taskPeople": "Persona responsable de la tarea",
	"processCompleted": "Circulación del documento completada",
	"start": "Iniciar",
	"processing": "Procesando",
	"hanging": "Suspendido",
	"phone": "Teléfono",
	"mail": "Correo electrónico",
	"open": "Abrir",
	"delete": "Eliminar",
	"edit": "Editar",
	"task": "Tareas pendientes",
	"done": "Tareas completadas",
	"read": "Documentos por leer",
	"readed": "Documentos leídos",
	"reset": "Reasignar",
	"resetTo": "Reasignar al administrador",
	"flow": "Flujo",
	"flag": "Marcar como leído",
	"reroute": "Redireccionar",
	"flowManager": "Intentar fluir (usado cuando no hay tareas pendientes y el proceso aún no ha sido fluyendo)",
	"noTask": "Esta tarea no tiene tareas pendientes",
	"noDone": "Esta tarea no tiene tareas completadas",
	"noRead": "Esta tarea no tiene documentos por leer",
	"noReaded": "Esta tarea no tiene documentos leídos",
	"noView": "No hay vistas para mostrar",
	"noStat": "No hay estadísticas para mostrar",
	"deleteWorkTitle": "Confirmar",
	"deleteWork": "¿Estás seguro de que deseas eliminar el trabajo “{title}”? ",
	"flowWorkTitle": "Confirmar",
	"flowWork": "¿Estás seguro de que deseas fluir el trabajo “{title}”? ",
	"deleteAllWork": "¿Desea eliminar los trabajos relacionados con este trabajo? <br/><br/><input type='radio' value='all' name='deleteWork_check'/>Eliminar el trabajo actual y todos los trabajos relacionados; <br/><input type='radio' value='single' name='deleteWork_check'/>Solo elimine el trabajo actual. <br><div id='deleteWork_checkInfor'></div>",
	"deleteAllWorkCheck": "¡Seleccione si desea o no eliminar todos los trabajos relacionados!",
	"deleteTaskTitle": "Confirmar",
	"deleteTask": "¿Estás seguro de que deseas eliminar la tarea pendiente de “ {people} ”?",
	"deleteDoneTitle": "Confirmar",
	"deleteDone": "¿Estás seguro de que deseas eliminar la tarea completada de “ {people} ”?",
	"deleteReadTitle": "Confirmar",
	"deleteRead": "¿Estás seguro de que deseas eliminar el documento por leer de “ {people} ”?",
	"deleteReadedTitle": "Confirmar",
	"deleteReaded": "¿Estás seguro de que deseas eliminar el documento leído de “ {people} ”?",
	"flagReadTitle": "Confirmar",
	"flagRead": "¿Estás seguro de que deseas marcar como leído el documento por leer de “ {people} ”?",
	"deleteSerialTitle": "Confirmar",
	"deleteSerial": "¿Estás seguro de que deseas eliminar el número de serie “ {key} ”?",
	"processList": "Proceso",
	"activityNameList": "Actividad",
	"creatorCompanyList": "Compañía creadora",
	"creatorDepartmentList": "Departamento creador",
	"creatorUnitList": "Organización creadora",
	"startTimeMonthList": "Fecha de creación",
	"completedTimeMonthList": "Fecha de finalización",
	"workStatusList": "Estado del proceso",
	"key": "Palabra clave",
	"toCompleted": "Ver instancias de trabajo completadas",
	"toWork": "Ver instancias de trabajo en progreso",
	"serialNumber": "Número de serie",
	"category": "Categoría",
	"amount": "Total",
	"selecteAll": "Seleccionar todo",
	"selecteAllCol": "Seleccionar todas las columnas",
	"selecteAllRow": "Seleccionar todas las filas",
	"firstPage": "Primera",
	"lastPage": "Última",
	"viewExport": {
		"exportRange": "Rango de exportación",
		"fileName": "Nombre del archivo",
		"to": "a",
		"item": "elementos",
		"description": "Nota: Hay {count} elementos que cumplen con los criterios.",
		"inputIntegerNotice": "Ingrese números enteros positivos para comenzar y terminar los elementos",
		"startLargetThanEndNotice": "El elemento de inicio no puede ser mayor que el elemento final"
	},
	"deleteConfirmContent": "Esta acción no se puede deshacer. ¿Estás seguro de que deseas eliminar este documento?",
	"deleteConfirmTitle": "Confirmar",
	"deleteSuccessNotice": "Eliminado correctamente",
	"importSuccess": "Importación exitosa",
	"validationInfor": "Información de validación",
	"importFail": "Fallo en la importación",
	"importValidationColumnText": "Columna {n}: ",
	"importValidationColumnTextExcel": "Columna {n}: ",
	"notValidNumber": "No es un número válido",
	"notValidDate": "No es un formato de fecha válido",
	"notValidBoolean": "No es un valor booleano válido",
	"notValidJson": "No es un formato JSON válido",
	"fullstop": ".",
	"notExistInSystem": "no existe en el sistema",
	"uploadedFilesCannotHaveSpaces": "los archivos cargados no pueden tener espacios",
	"canNotBeEmpty": "no puede estar vacío",
	"cmsTitleLengthInfor": "El título no puede tener más de 70 caracteres",
	"cmsSummaryLengthInfor": "El resumen no puede tener más de 70 caracteres",
	"caculateFieldValidationText": "Error en el campo calculado:",
	"noDrafter": "No se ha establecido la identidad del autor o el autor no existe en el sistema",
	"drafterIsNotIdentity": "El autor no es una identidad",
	"noPublishTime": "No se ha establecido el tiempo de publicación",
	"publishTimeFormatError": "El formato de la hora de publicación no es válido",
	"noStartTime": "No se ha establecido el tiempo de inicio",
	"startTimeFormatError": "El formato de la hora de inicio no es válido",
	"noEndTime": "No se ha establecido el tiempo de finalización",
	"endTimeFormatError": "El formato de la hora de finalización no es válido",
	"noForm": "No se ha establecido un formulario",
	"importDataResult": "Resultado de importación de datos de asistencia",
	"importDataResultSuccess": "Los datos han sido importados correctamente. A continuación se muestran {count} de ellos:",
	"importDataResultFail": "Los datos no pasaron la validación, hay {errorCount} datos incorrectos. Corrígelos y vuelve a importarlos. A continuación se muestran {count} de ellos:",
	"true": "Verdadero",
	"false": "Falso",
	"checkDataTitle": "Importación de datos",
	"checkDataContent": "Comprobando datos...",
	"importDataTitle": "Importando datos",
	"importDataContent": "Comenzando a importar datos, un total de {count} elementos",
	"readyToImportData": "Preparando la importación de datos",
	"readyToImportData1": "Preparando la importación de datos...",
	"importSpeed": "elementos/segundo",
	"importingDataContent": "Importando datos: {speed} elementos/segundo, un total de {total}, {remaining} restantes",
	"importingDataErrorContent": ", con {errorCount} errores",
	"hour": "hora",
	"mintue": "minuto",
	"second": "segundo",
	"importSuccessTitle": "Importación exitosa",
	"importSuccessContent": "Datos importados correctamente: un total de {total} elementos, velocidad: {speed} elementos/segundo, tiempo: {timeStr}",
	"importPartSuccessTitle": "Importación parcial exitosa",
	"importPartSuccessContent": "Importación parcialmente exitosa: un total de {total} elementos importados, {errorCount} errores, velocidad: {speed} elementos/segundo, tiempo: {timeStr}",
	"importWaitingTitle": "Esperando importación",
	"importWaitingContent": "Otro usuario está importando o la última importación no se ha completado aún. Por favor espere...",
	"importFailTitle": "Fallo en la importación",
	"importFailContent": "Fallo en la importación: {errorInfo}, un total de {total} elementos, pero no se ejecutó la importación. Tiempo: {timeStr}. Por favor, modifícalos y vuelve a importarlos.",
	"importerName": "Nombre del modelo de importación",
	"importTime": "Tiempo de importación",
	"updateTime": "Tiempo de actualización",
	"importCount": "Número total",
	"close": "Cerrar",
	"failCount": "Cantidad de errores",
	"importRecord": "Registro de importación",
	"sequence": "Secuencia",
	"importData": "Importar datos",
	"importRecordDetail": "Detalles del registro de importación",
	"downloadTemplate": "Descargar plantilla",
	"exportErrorDataToExcel": "Exportar datos con errores a Excel",
	"openImportRecordDetail": "Ver detalles de la importación",
	"importStatusList": [
		"Todos",
		"Importados exitosamente",
		"Falló la importación"
	],
	"errorInfor": "Información del error",
	"reExecuteImport": "Reintentar la importación",
	"importPerson": "Persona que importó",
	"showFiveColumn": "(Haga clic para mostrar las primeras 5 columnas)",
	"showAll": "(Haga clic para mostrar todo)",
	"deleteDocument": "Esta acción no se puede deshacer. ¿Estás seguro de que deseas eliminar este registro de importación?",
	"deleteDocumentTitle": "Confirmar",
	"deleteDocumentOK": "El registro de importación se eliminó correctamente",
	"noPermission": "No tienes permiso para acceder a este documento.",
	"associationSuccess": "Asociación exitosa.",
	"associationResult": "Resultado de la asociación",
	"total": "Total",
	"notInOptions": "No en valores opcionales"
}
MWF.xApplication.query.Query["lp."+o2.language] = MWF.xApplication.query.Query.LP