MWF.xApplication.query.Query.LP = {
	"title": "데이터 애플리케이션",
	"searchKey": "키워드를 입력하세요",
	"all": "모두",
	"filter": "필터",
	"ok": "확인",
	"cancel": "취소",
	"clear": "지우기",
	"exportExcel": "Excel 내보내기",
	"noDescription": "설명 없음",
	"view": "뷰",
	"stat": "통계",
	"statement": "쿼리",
	"importer": "가져오기",
	"customSearch": "고급 검색",
	"searchKeywork": "뷰 검색 키워드 입력",
	"yes": "예",
	"no": "아니오",
	"and": "그리고",
	"or": "또는",

    "form": {
		"exportExcel": "Excel 내보내기"
	  },
	  "chart": {
		"bar": "막대 그래프",
		"pie": "원 그래프",
		"line": "선 그래프",
		"rowToColumn": "행-열 전환"
	  },
	  "textFilter": {
		"equals": "같음",
		"notEquals": "다름",
		"like": "일치",
		"notLike": "불일치"
	  },
	  "numberFilter": {
		"equals": "같음",
		"notEquals": "다름",
		"greaterThan": "초과",
		"greaterThanOrEqualTo": "이상",
		"lessThan": "미만",
		"lessThanOrEqualTo": "이하"
	  },

    "dateFilter": {
		"equals": "같음",
		"notEquals": "다름",
		"greaterThan": "초과",
		"lessThan": "미만"
	  },
	  "dateTimeFilter": {
		"greaterThan": "초과",
		"lessThan": "미만"
	  },
	  "booleanFilter": {
		"equals": "같음",
		"notEquals": "다름"
	  },
	  "filterErrorTitle": "검색 필드를 선택하십시오",
	  "filterErrorComparison": "비교 연산자를 선택하십시오",
	  "filterErrorValue": "비교 값을 입력하십시오",


    "workTitle": "제목",
	  "activity": "활동",
	  "status": "상태",
	  "action": "동작",
	  "person": "작성자",
	  "expire": "만료",
	  "noExpire": "없음",
	  "expired": "만료됨",
	  "notExpired": "만료 안됨",
	  "completedTime": "완료 시간",
	  "process": "프로세스",
	  "taskPeople": "처리자",
	  "processCompleted": "문서 전달 완료",

	  "start": "시작",
	  "processing": "진행 중",
	  "hanging": "보류 중",

	  "phone": "휴대전화",
	  "mail": "이메일",

	  "open": "열기",
	  "delete": "삭제",
	  "edit": "편집",

	  "task": "대기",
	  "done": "완료",
	  "read": "대기열",
	  "readed": "완료된",


    "reset": "재할당",
	  "resetTo": "관리자에게 재할당",
	  "flow": "전달",
	  "flag": "확인 표시",
	  "reroute": "재배정",
	  "flowManager": "전달 시도(미할 일 및 프로세스 미전달 시 사용)",

	  "noTask": "이 작업에 대기 중인 항목이 없습니다",
	  "noDone": "이 작업에 완료된 항목이 없습니다",
	  "noRead": "이 작업에 대기 중인 독서 항목이 없습니다",
	  "noReaded": "이 작업에 완료된 독서 항목이 없습니다",

	  "noView": "표시 가능한 뷰가 없습니다",
	  "noStat": "표시 가능한 통계가 없습니다",

	  "deleteWorkTitle": "작업 삭제 확인",
	  "deleteWork": "작업 '{title}'을(를) 삭제하시겠습니까?",

	  "flowWorkTitle": "작업 전달 확인",
	  "flowWork": "작업 '{title}'을(를) 전달하시겠습니까?",

    "deleteAllWork": "이 작업과 관련된 모든 작업을 삭제하시겠습니까? <br/><br/><input type='radio' value='all' name='deleteWork_check'/>현재 작업 및 관련 작업 모두 삭제; " +
		"<br/><input type='radio' value='single' name='deleteWork_check'/>현재 작업만 삭제<br><div id='deleteWork_checkInfor'></div>",
	  "deleteAllWorkCheck": "관련 작업 모두 삭제 여부를 선택하십시오!",

	  "deleteTaskTitle": "대기 중인 항목 삭제 확인",
	  "deleteTask": "{people}의 대기 중인 항목을 삭제하시겠습니까?",

	  "deleteDoneTitle": "완료된 항목 삭제 확인",
	  "deleteDone": "{people}의 완료된 항목을 삭제하시겠습니까?",

	  "deleteReadTitle": "대기 중인 독서 항목 삭제 확인",
	  "deleteRead": "{people}의 대기 중인 독서 항목을 삭제하시겠습니까?",

	  "deleteReadedTitle": "완료된 독서 항목 삭제 확인",
	  "deleteReaded": "{people}의 완료된 독서 항목을 삭제하시겠습니까?",

	  "flagReadTitle": "대기 중인 항목을 완료로 표시 확인",
	  "flagRead": "{people}의 대기 중인 항목을 완료로 표시하시겠습니까?",

	  "deleteSerialTitle": "일련 번호 삭제 확인",
	  "deleteSerial": "{key}의 일련 번호를 삭제하시겠습니까?",

    "processList": "프로세스",
	  "activityNameList": "활동",
	  "creatorCompanyList": "회사",
	  "creatorDepartmentList": "부서",
	  "creatorUnitList": "조직",
	  "startTimeMonthList": "작성 일자",
	  "completedTimeMonthList": "완료 일자",
	  "workStatusList": "프로세스 상태",
	  "key": "키워드",
	  "toCompleted": "완료된 작업 인스턴스 보기",
	  "toWork": "진행 중인 작업 인스턴스 보기",
	  "serialNumber": "일련 번호",
	  "category": "카테고리",
	  "amount": "합계",
	  "selecteAll": "모두 선택",
	  "selecteAllCol": "모든 열 선택",
	  "selecteAllRow": "모든 행 선택",

      "firstPage": "첫 페이지",
	  "lastPage": "마지막 페이지",
	  "viewExport": {
		"exportRange": "내보내기 범위",
		"fileName": "파일 이름",
		"to": "에서",
		"item": "항목",
		"description": "참고: 조건에 맞는 {count}개의 데이터가 있습니다.",
		"inputIntegerNotice": "시작 및 끝 항목 모두 양의 정수를 입력하십시오.",
		"startLargetThanEndNotice": "시작 항목은 끝 항목보다 커서는 안 됩니다."
	  },
	  "deleteConfirmContent": "삭제 후에는 복원할 수 없습니다. 문서를 삭제하시겠습니까?",
	  "deleteConfirmTitle": "삭제 확인",
	  "deleteSuccessNotice": "삭제 성공",

      "importSuccess": "가져오기 성공!",
	  "validationInfor": "유효성 검사 정보",
	  "importFail": "가져오기 실패",
	  "importValidationColumnText": "열 {n}:",
	  "importValidationColumnTextExcel": "열 {n}:",
	  "notValidNumber": "숫자가 아님",
	  "notValidDate": "날짜 형식이 아님",
	  "notValidBoolean": "부울 값이 아님",
	  "notValidJson": "올바른 JSON 형식이 아님",
	  "fullstop": "。",
	  "notExistInSystem": "시스템에 존재하지 않음",
	  "uploadedFilesCannotHaveSpaces": "업로드한 파일에 공백이 포함될 수 없음",
	  "canNotBeEmpty": "비어 있을 수 없음",
	  "cmsTitleLengthInfor": "제목 길이는 70자를 초과할 수 없음",
	  "cmsSummaryLengthInfor": "요약 길이는 70자를 초과할 수 없음",
	  "caculateFieldValidationText": "계산 필드 오류:",

      "noDrafter": "기안자 신분이나 기안자가 시스템에 없습니다",
	  "drafterIsNotIdentity": "기안자는 신분이 아닙니다",
	  "noPublishTime": "발행 시간이 설정되지 않았습니다",
	  "publishTimeFormatError": "발행 시간 형식이 올바르지 않습니다",
	  "noStartTime": "시작 시간이 설정되지 않았습니다",
	  "startTimeFormatError": "시작 시간 형식이 올바르지 않습니다",
	  "noEndTime": "종료 시간이 설정되지 않았습니다",
	  "endTimeFormatError": "종료 시간 형식이 올바르지 않습니다",
	  "noForm": "양식이 설정되지 않았습니다",
	  "importDataResult": "근무 데이터 가져오기 결과",
	  "importDataResultSuccess": "데이터가 성공적으로 가져왔습니다. 아래는 {count}개 항목 중 일부를 표시합니다:",
	  "importDataResultFail": "데이터가 유효성 검사를 통과하지 못했습니다. {errorCount}개의 오류 항목이 있습니다. 수정한 후 다시 가져오세요. 아래는 {count}개 항목 중 일부를 표시합니다:",
    // "importDataResultThList" : [
    //     "行号", "员工号", "员工名字", "日期","上午上班打卡时间","上午下班打卡时间","下午上班打卡时间","下午下班打卡时间","检查结果","描述"
    // ],
      "true": "옳다",
	  "false": "틀려",
	  "checkDataTitle": "데이터 가져오기",
	  "checkDataContent": "데이터 검사 중...",
	  "importDataTitle": "데이터 가져오기 진행 중",
	  "importDataContent": "데이터 가져오기 시작, 총 {count}개 항목",
	  "readyToImportData": "데이터 가져오기 준비 중",
	  "readyToImportData1": "데이터 가져오기 준비 중...",
	  "importSpeed": "개/초",
	  "importingDataContent": "데이터 가져오기 중: {speed}개/초, 총 {total}개, 남은 항목 {remaining}개",
	  "importingDataErrorContent": ", 오류 {errorCount}개",
	  "hour": "시간",
	  "minute": "분",
	  "second": "초",
	  "importSuccessTitle": "가져오기 성공",
	  "importSuccessContent": "가져오기 성공: 총 {total}개 데이터 가져오기  속도: {speed}개/초  소요 시간: {timeStr}",
	  "importPartSuccessTitle": "일부 가져오기 성공",
	  "importPartSuccessContent": "일부 가져오기 성공: 총 {total}개 데이터 가져오기  오류: {errorCount}개  속도: {speed}개/초  소요 시간: {timeStr}",
	  "importWaitingTitle": "가져오기 대기 중",
	  "importWaitingContent": "다른 사람이 가져오기 중이거나 이전 가져오기가 아직 완료되지 않았습니다. 기다려 주십시오...",
	  "importFailTitle": "가져오기 실패",
	  "importFailContent": "가져오기 실패: {errorInfo} 총 데이터 수 {total}개, 가져오기 미실행 소요 시간: {timeStr} 수정 후 다시 가져오십시오",
	  "importerName": "가져오기 모델 이름",
	  "importTime": "가져오기 시간",
	  "updateTime": "업데이트 시간",
	  "importCount": "총 항목",
	  "close": "닫기",
	  "failCount": "오류 항목 수",
	  "importRecord": "가져오기 기록",
	  "sequence": "일련번호",
	  "importData": "데이터 가져오기",
	  "importRecordDetail": "가져오기 상세 정보",
	  "downloadTemplate": "템플릿 다운로드",
	  "exportErrorDataToExcel": "오류 데이터를 Excel로 내보내기",
	  "openImportRecordDetail": "가져오기 상세 정보 보기",
	  "importStatusList": ["전체", "가져오기 성공", "가져오기 실패"],
	  "errorInfo": "오류 정보",
	  "reExecuteImport": "가져오기 다시 실행",
	  "importPerson": "가져오기 사용자",
	  "showFiveColumn": "(상위 5개 열 보이기)",
	  "showAll": "(모두 표시)",
	  "deleteDocument": "삭제한 후 되돌릴 수 없습니다. 이 가져오기 기록을 삭제하시겠습니까?",
	  "deleteDocumentTitle": "가져오기 기록 삭제 확인",
	  "deleteDocumentOK": "가져오기 기록 삭제 성공",
	  "noPermission": "이 문서에 액세스할 수 있는 권한이 없습니다.",
	  "associationSuccess": "연결 성공.",
	  "associationResult": "연결 결과"

};