MWF.xApplication.query.Query.LP = {
	"title": "數據應用",
	"searchKey": "請輸入關鍵字",
	"all": "全部",
	"filter": "篩選",
	"ok": "確定",
	"cancel": "取消",
	"clear": "清除",
	"exportExcel": "導出Excel",
	"noDescription": "未定義描述",
	"view": "視圖",
	"stat": "統計",
	"statement": "查詢",
	"importer": "導入",
	"customSearch": "高級搜索",
	"searchKeywork": "輸入關鍵字搜索視圖",
	"yes": "是",
	"no": "否",
	"and": "並且",
	"or": "或者",

    "form": {
		"exportExcel": "導出Excel"
	  },
	  "chart": {
		"bar": "柱狀圖",
		"pie": "餅圖",
		"line": "折線圖",
		"rowToColumn": "行列轉換"
	  },
	  "textFilter": {
		"equals": "等於",
		"notEquals": "不等於",
		"like": "匹配",
		"notLike": "不匹配"
	  },
	  "numberFilter": {
		"equals": "等於",
		"notEquals": "不等於",
		"greaterThan": "大於",
		"greaterThanOrEqualTo": "大於等於",
		"lessThan": "小於",
		"lessThanOrEqualTo": "小於等於"
	  },

    "dateFilter": {
		"equals": "等於",
		"notEquals": "不等於",
		"greaterThan": "大於",
		"lessThan": "小於"
	  },
	  "dateTimeFilter": {
		"greaterThan": "大於",
		"lessThan": "小於"
	  },
	  "booleanFilter": {
		"equals": "等於",
		"notEquals": "不等於"
	  },
	  "filterErrorTitle": "請選擇搜索字段",
	  "filterErrorComparison": "請選擇比較符",
	  "filterErrorValue": "請輸入比較值",


    "workTitle": "標題",
	  "activity": "活動",
	  "status": "狀態",
	  "action": "操作",
	  "person": "起草人",
	  "expire": "超時",
	  "noExpire": "無",
	  "expired": "超時",
	  "notExpired": "未超時",
	  "completedTime": "完成時間",
	  "process": "流程",
	  "taskPeople": "處理人",
	  "processCompleted": "文件流轉完成",

	  "start": "啟動",
	  "processing": "流轉中",
	  "hanging": "已掛起",

	  "phone": "手機",
	  "mail": "電子郵件",

	  "open": "打開",
	  "delete": "刪除",
	  "edit": "編輯",

	  "task": "待辦",
	  "done": "已辦",
	  "read": "待閱",
	  "readed": "已閱",


    "reset": "重設",
	  "resetTo": "管理員重設",
	  "flow": "傳閱",
	  "flag": "標記已閱",
	  "reroute": "重新分派",
	  "flowManager": "嘗試傳閱（如果沒有待辦任務且沒有流轉時使用）",
	  "noTask": "此工作沒有待辦",
	  "noDone": "此工作沒有已辦",
	  "noRead": "此工作沒有待閱",
	  "noReaded": "此工作沒有已閱",
	  "noView": "沒有可顯示的視圖",
	  "noStat": "沒有可顯示的統計",
	  "deleteWorkTitle": "刪除工作確認",
	  "deleteWork": "您確定要刪除工作“{title}”嗎?",
	  "flowWorkTitle": "傳閱工作確認",
	  "flowWork": "您確定要傳閱工作“{title}”嗎?",

    "deleteAllWork": "您是否要删除此工作的关联工作？ <br/><br/><input type='radio' value='all' name='deleteWork_check'/>删除当前工作及其所有关联工作； <br/><input type='radio' value='single' name='deleteWork_check'/>只删除当前工作<br><div id='deleteWork_checkInfor'></div>",
	  "deleteAllWorkCheck": "请选择是否删除所有关联工作！",
	  "deleteTaskTitle": "删除待办确认",
	  "deleteTask": "您确定要删除“{people}”的待办吗",
	  "deleteDoneTitle": "删除已办确认",
	  "deleteDone": "您确定要删除“{people}”的已办吗?",
	  "deleteReadTitle": "删除待阅确认",
	  "deleteRead": "您确定要删除“{people}”的待阅吗?",
	  "deleteReadedTitle": "删除已阅确认",
	  "deleteReaded": "您确定要删除“{people}”的已阅吗?",
	  "flagReadTitle": "标记已阅确认",
	  "flagRead": "您确定要将“{people}”的待阅，标记为已阅吗?",
	  "deleteSerialTitle": "删除编号确认",
	  "deleteSerial": "您确定要删除“{key}”的编号吗",

    "processList": "流程",
	  "activityNameList": "活動",
	  "creatorCompanyList": "建立公司",
	  "creatorDepartmentList": "建立部門",
	  "creatorUnitList": "建立組織",
	  "startTimeMonthList": "建立時間",
	  "completedTimeMonthList": "完成時間",
	  "workStatusList": "流程狀態",
	  "key": "關鍵字",
	  "toCompleted": "查看已完成的工作實例",
	  "toWork": "查看流轉中的工作實例",
	  "serialNumber": "流水號",
	  "category": "分類",
	  "amount": "總計",
	  "selecteAll": "全選",
	  "selecteAllCol": "選擇所有列",
	  "selecteAllRow": "選擇所有行",

      "firstPage": "第一页",
	  "lastPage": "最后一页",
	  "viewExport": {
		"exportRange": "导出范围",
		"fileName": "文件名",
		"to": "到",
		"item": "条",
		"description": "注：有{count}条符合条件的数据。",
		"inputIntegerNotice": "开始和结束条目都请输入正整数",
		"startLargetThanEndNotice": "开始条目不能大于结束条目"
	  },
	  "deleteConfirmContent": "删除后不能恢复，你确定要删除该文档？",
	  "deleteConfirmTitle": "删除确认",
	  "deleteSuccessNotice": "删除成功",

      "importSuccess": "匯入成功！",
	  "validationInfor": "校驗信息",
	  "importFail": "匯入失敗",
	  "importValidationColumnText": "第{n}列：",
	  "importValidationColumnTextExcel": "列{n}：",
	  "notValidNumber": "不是數字",
	  "notValidDate": "不是日期格式",
	  "notValidBoolean": "不是布爾值",
	  "notValidJson": "不是正確的JSON格式",
	  "fullstop": "。",
	  "notExistInSystem": "在系統中不存在",
	  "uploadedFilesCannotHaveSpaces": "上傳的文件不能帶空格",
	  "canNotBeEmpty": "不能為空",
	  "cmsTitleLengthInfor": "標題長度不能超過70個字",
	  "cmsSummaryLengthInfor": "摘要長度不能超過70個字",
	  "caculateFieldValidationText": "計算字段錯誤:",

    "noDrafter": "未設置擬稿人身份或者擬稿人在系統中不存在",
	"drafterIsNotIdentity": "擬稿人不是身份",
	"noPublishTime": "未設置發佈時間",
	"publishTimeFormatError": "發佈時間格式不正確",
	"noStartTime": "未設置開始時間",
	"startTimeFormatError": "開始時間格式不正確",
	"noEndTime": "未設置結束時間",
	"endTimeFormatError": "結束時間格式不正確",
	"noForm": "未設置表單",
	"importDataResult": "考勤數據導入結果",
	"importDataResultSuccess": "數據已經成功導入。下面顯示其中的{count}條：",
	"importDataResultFail": "數據未通過校驗，有{errorCount}條錯誤數據。請修改後重新導入。下面顯示其中的{count}條：",
    // "importDataResultThList" : [
    //     "行号", "员工号", "员工名字", "日期","上午上班打卡时间","上午下班打卡时间","下午上班打卡时间","下午下班打卡时间","检查结果","描述"
    // ],
    "true": "正確",
	"false": "錯誤",
	"checkDataTitle": "數據導入",
	"checkDataContent": "正在檢查數據...",
	"importDataTitle": "正在導入數據",
	"importDataContent": "開始導入數據，共{count}條",
	"readyToImportData": "正在準備導入數據",
	"readyToImportData1": "正在準備導入數據...",
	"importSpeed": "條/秒",
	"importingDataContent": "正在導入數據: {speed}條/秒，共{total}條，剩餘{remaining}條",
	"importingDataErrorContent": "，出錯{errorCount}條",
	"hour": "小時",
	"mintue": "分鐘",
	"second": "秒",
	"importSuccessTitle": "導入成功",
	"importSuccessContent": "導入成功: 共導入數據{total}條  速度: {speed}條/秒  耗時: {timeStr}",
	"importPartSuccessTitle": "部分導入成功",
	"importPartSuccessContent": "部分導入成功: 共導入數據{total}條 出錯: {errorCount}條 速度: {speed}條/秒  耗時: {timeStr}",
	"importWaitingTitle": "待導入",
	"importWaitingContent": "有其他人正在導入或上次導入還未完成，請耐心等候...",
	"importFailTitle": "導入失敗",
	"importFailContent": "導入失敗: {errorInfo} 共有數據{total}條，但未執行導入 耗時: {timeStr} 請修改後重新導入",
	"importerName": "導入模型名稱",
	"importTime": "導入時間",
	"updateTime": "更新時間",
	"importCount": "總條數",
	"close": "關閉",
	"failCount": "出錯條數",
	"importRecord": "導入記錄",
	"sequence": "序號",
	"importData": "導入數據",
	"importRecordDetail": "導入詳情",
	"downloadTemplate": "下載模板",
	"exportErrorDataToExcel": "導出錯誤數據",
	"openImportRecordDetail": "查看導入詳情",
	"importStatusList": ["全部", "導入成功", "導入失敗"],
	"errorInfor": "錯誤信息",
	"reExecuteImport": "重新執行導入",
	"importPerson": "導入人",
	"showFiveColumn": "(點擊顯示前5列)",
	"showAll": "(點擊顯示全部)",
	"deleteDocument": "刪除後無法恢復，確定要刪除該導入記錄？",
	"deleteDocumentTitle": "刪除確認",
	"deleteDocumentOK": "成功刪除導入記錄",
	"noPermission": "您無權限訪問此文檔。",
	"associationSuccess": "關聯成功。",
	"associationResult": "關聯結果"

};