/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.segment;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Boolean;
import java.lang.String;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.segment.Entry.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Fri Dec 21 15:30:26 CST 2018")
public class Entry_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Entry,String> appId;
    public static volatile SingularAttribute<Entry,String> appName;
    public static volatile SingularAttribute<Entry,String> application;
    public static volatile SingularAttribute<Entry,String> applicationName;
    public static volatile SingularAttribute<Entry,String> bundle;
    public static volatile SingularAttribute<Entry,String> categoryId;
    public static volatile SingularAttribute<Entry,String> categoryName;
    public static volatile SingularAttribute<Entry,String> creatorPerson;
    public static volatile SingularAttribute<Entry,String> creatorUnit;
    public static volatile SingularAttribute<Entry,String> id;
    public static volatile SingularAttribute<Entry,Date> lastUpdateTime;
    public static volatile SingularAttribute<Entry,String> process;
    public static volatile SingularAttribute<Entry,String> processName;
    public static volatile SingularAttribute<Entry,String> reference;
    public static volatile SingularAttribute<Entry,String> summary;
    public static volatile SingularAttribute<Entry,String> title;
    public static volatile SingularAttribute<Entry,String> type;
    public static volatile SingularAttribute<Entry,Boolean> wait;
}
