/** 
 *  Generated by OpenJPA MetaModel Generator Tool.
**/

package com.x.query.core.entity.segment;

import com.x.base.core.entity.SliceJpaObject_;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.metamodel.SingularAttribute;

@javax.persistence.metamodel.StaticMetamodel
(value=com.x.query.core.entity.segment.Word.class)
@javax.annotation.Generated
(value="org.apache.openjpa.persistence.meta.AnnotationProcessor6",date="Mon Dec 24 19:04:03 CST 2018")
public class Word_ extends SliceJpaObject_  {
    public static volatile SingularAttribute<Word,String> bundle;
    public static volatile SingularAttribute<Word,Integer> count;
    public static volatile SingularAttribute<Word,String> entry;
    public static volatile SingularAttribute<Word,String> id;
    public static volatile SingularAttribute<Word,Integer> identifier01;
    public static volatile SingularAttribute<Word,String> label;
    public static volatile SingularAttribute<Word,String> tag;
    public static volatile SingularAttribute<Word,String> type;
    public static volatile SingularAttribute<Word,String> value;
}
